

CREATE FUNCTION `FN_CHK_FCOI_REQUIRED`(
AV_PERSON_ID VARCHAR(40)
) RETURNS int
    DETERMINISTIC
BEGIN

DECLARE LI_COUNT				  int; 

SELECT  count(*) INTO LI_COUNT
        FROM (
			WITH AwardRanks AS (
			SELECT DISTINCT MODULE_ITEM_KEY, MODULE_CODE, DISCLOSURE_VALIDATION_FLAG, DISCLOSURE_REQUIRED_FLAG,
					ROW_NUMBER() OVER (PARTITION BY SUBSTRING_INDEX(MODULE_ITEM_KEY, '-', 1)  
					ORDER BY CASE 
                                    WHEN DISCLOSURE_VALIDATION_FLAG = 'SELF' THEN 1
                                    WHEN (DISCLOSURE_VALIDATION_FLAG = 'HIERARCHY' OR DISCLOSURE_VALIDATION_FLAG IS NULL) AND DISCLOSURE_REQUIRED_FLAG= 'REQUIRED' THEN 2
                                    ELSE 3
                            END,
					CAST(SUBSTRING_INDEX(MODULE_ITEM_KEY, '-', -1) AS UNSIGNED) ASC) AS rn FROM 
				(SELECT DISTINCT MODULE_ITEM_KEY, 1 AS MODULE_CODE,DISCLOSURE_VALIDATION_FLAG,DISCLOSURE_REQUIRED_FLAG FROM COI_DISCL_PROJECTS C1
                INNER JOIN COI_DISCLOSURE C2 ON C2.DISCLOSURE_ID=C1.DISCLOSURE_ID
				INNER JOIN COI_PROJECT_AWARD_V C3 ON C3.AWARD_NUMBER = C1.MODULE_ITEM_KEY
				INNER JOIN COI_PROJECT_TYPE C4 ON C4.COI_PROJECT_TYPE_CODE = C3.COI_PROJECT_TYPE_CODE
                WHERE KEY_PERSON_ID = AV_PERSON_ID AND PERSON_STATUS <> 'I' AND C3.AWARD_STATUS_CODE IN (1, 6, 3)
                AND C4.FCOI_NEEDED = 'Y'
				UNION
				SELECT T1.AWARD_NUMBER AS MODULE_ITEM_KEY, 1 AS MODULE_CODE,DISCLOSURE_VALIDATION_FLAG,DISCLOSURE_REQUIRED_FLAG
				FROM COI_PROJECT_AWARD_V T1
				INNER JOIN COI_PROJECT_TYPE T4 ON T4.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
				LEFT JOIN (SELECT DISTINCT AW2.PROJECT_NUMBER FROM COI_INT_STAGE_AWARD AW1
							INNER JOIN COI_INT_STAGE_AWARD AW2 ON AW2.ROOT_PROJECT_NUMBER = AW1.ROOT_PROJECT_NUMBER
							INNER JOIN COI_INT_STAGE_AWARD_PERSON AW3 ON AW3.PROJECT_NUMBER = AW2.PROJECT_NUMBER
							WHERE AW2.PROJECT_STATUS_CODE IN (1, 6, 3) AND AW3.KEY_PERSON_ID = AV_PERSON_ID
							AND NOT EXISTS (SELECT 1 FROM COI_INT_STAGE_AWARD ROOT
													 WHERE ROOT.PROJECT_NUMBER = AW1.ROOT_PROJECT_NUMBER
													 AND ROOT.PROJECT_STATUS_CODE = 5
													)
				) T5 ON T5.PROJECT_NUMBER = T1.AWARD_NUMBER
				WHERE T1.KEY_PERSON_ID = AV_PERSON_ID AND T1.PERSON_STATUS != 'I'
					AND ((T1.DISCLOSURE_VALIDATION_FLAG = 'SELF')
						OR (T1.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' AND 
						(T1.DISCLOSURE_VALIDATION_FLAG IS NULL OR T1.DISCLOSURE_VALIDATION_FLAG = 'HIERARCHY') AND T5.PROJECT_NUMBER IS NOT NULL))
					AND T1.AWARD_STATUS_CODE IN (1, 6, 3) -- Active/Hold/Pending
					AND T4.FCOI_NEEDED = 'Y')T
			)
			SELECT MODULE_ITEM_KEY, MODULE_CODE
			FROM AwardRanks
			WHERE 
            (DISCLOSURE_VALIDATION_FLAG = 'SELF'  -- Return all SELF entries
			OR (DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' AND (DISCLOSURE_VALIDATION_FLAG IS NULL OR DISCLOSURE_VALIDATION_FLAG = 'HIERARCHY') AND rn = 1 
			AND NOT EXISTS (
						   SELECT 1 
						   FROM AwardRanks AR 
						   WHERE AR.DISCLOSURE_VALIDATION_FLAG = 'SELF'
						   AND SUBSTRING_INDEX(AR.MODULE_ITEM_KEY, '-', 1) = SUBSTRING_INDEX(AwardRanks.MODULE_ITEM_KEY, '-', 1)
						   )
			))
			UNION
				SELECT DISTINCT MODULE_ITEM_KEY, 1 AS MODULE_CODE FROM COI_DISCL_PROJECTS C1
                INNER JOIN COI_DISCLOSURE C2 ON C2.DISCLOSURE_ID=C1.DISCLOSURE_ID
				INNER JOIN COI_PROJECT_AWARD_V C3 ON C3.AWARD_NUMBER = C1.MODULE_ITEM_KEY
				INNER JOIN COI_PROJECT_TYPE C4 ON C4.COI_PROJECT_TYPE_CODE = C3.COI_PROJECT_TYPE_CODE
                WHERE KEY_PERSON_ID = AV_PERSON_ID AND PERSON_STATUS <> 'I' AND C3.AWARD_STATUS_CODE IN (1, 6, 3)
                AND C4.FCOI_NEEDED = 'Y' 
			UNION
            SELECT EXTERNAL_SYSTEM_REF_ID AS MODULE_ITEM_KEY, 3 AS MODULE_CODE
            FROM COI_PROJECT_PROPOSAL_V T1
    		INNER JOIN COI_PROJECT_TYPE T4 ON T4.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
            WHERE KEY_PERSON_ID = AV_PERSON_ID AND T4.FCOI_NEEDED = 'Y' 
            UNION
            SELECT T1.PROPOSAL_NUMBER AS MODULE_ITEM_KEY, 2 AS MODULE_CODE
            FROM COI_PROJECT_INSTITUTE_PROPOSAL_V T1
    		LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS T2 ON T2.SPONSOR_CODE = T1.SPONSOR_CODE
    		LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS T3 ON T3.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE
    		INNER JOIN COI_PROJECT_TYPE T4 ON T4.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
            WHERE T1.KEY_PERSON_ID = AV_PERSON_ID AND T1.PERSON_STATUS != 'I'
            AND T1.LINKED_AWARD_PROJECT_NUMBER IS NULL
            AND (((T2.KEY_PERSON_DISCL_REQUIREMENT = 'ALL' OR ( T2.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI' AND T1.KEY_PERSON_ROLE_CODE IN(1,3)))
    				OR (T3.KEY_PERSON_DISCL_REQUIREMENT = 'ALL' OR (T3.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI' AND T1.KEY_PERSON_ROLE_CODE IN(1,3)))
    			)
    			OR ((T1.PCK = 'PC' AND T1.KEY_PERSON_ROLE_CODE IN(1,3))
    			       OR (T1.PCK = 'PCK' AND T1.KEY_PERSON_ROLE_CODE IN(1,2,3))
    			)
    		)
    		AND T1.PROPOSAL_STATUS_CODE IN (1)
    		AND T4.FCOI_NEEDED = 'Y'
        ) T;

RETURN LI_COUNT;

END
