

CREATE FUNCTION `FN_OPA_DISCLOSURE_REQUIRED`(
AV_LOGGED_IN_PERSON_ID   VARCHAR(40)
) RETURNS int
    DETERMINISTIC
BEGIN

DECLARE LI_REQUIRED INT DEFAULT 1;
DECLARE LI_NOT_REQUIRED INT DEFAULT 0;
DECLARE  LI_COUNT INT;

SELECT count(PERSON_ID) INTO LI_COUNT FROM OPA_PERSON WHERE PERSON_ID = AV_LOGGED_IN_PERSON_ID;
IF LI_COUNT > 0 THEN
	RETURN LI_REQUIRED;
ELSE 
	RETURN LI_NOT_REQUIRED;
END IF;

END
