INSERT INTO claim_attachment_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES ('1','Budget Template','2020-03-18','admin','Y','N');
INSERT INTO claim_attachment_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES ('2','Other document','2020-03-18','admin','Y','N');
INSERT INTO claim_attachment_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,IS_PRIVATE) VALUES ('3','Signed Document','2020-03-18','admin','Y','N');
