-- `GET_NEXT_CLAIM_NUMBER`; 

CREATE PROCEDURE `GET_NEXT_CLAIM_NUMBER`(
AV_TYPE VARCHAR(1),
OUT CLAIM_NUMBER VARCHAR(200))
    DETERMINISTIC
BEGIN
DECLARE LI_MONTH INT(2);
DECLARE LS_CLAIM VARCHAR(12);
DECLARE LI_FISCAL_YEAR INT(4);
DECLARE LS_CLAIM_NUMBER VARCHAR(12);
DECLARE LOCK_ACQUIRED INT;
IF AV_TYPE ='S' THEN 
START TRANSACTION;
    SET LOCK_ACQUIRED =  GET_LOCK('reimbursement_claim_number_generator_lock', 30);
	IF LOCK_ACQUIRED = 1 THEN
            SELECT MAX(FISCAL_YEAR) INTO LI_FISCAL_YEAR FROM CLAIM_NUMBER_SYSTEM_GENERATOR;
            SELECT month(CURDATE()) INTO LI_MONTH FROM dual;	  
                IF LI_MONTH > 3 AND LI_FISCAL_YEAR <> (SELECT YEAR(CURDATE()) FROM dual) THEN
		            INSERT INTO CLAIM_NUMBER_SYSTEM_GENERATOR(next_val,FISCAL_YEAR) VALUES(1, (SELECT YEAR(CURDATE()) FROM dual));
                END IF;
				SET LS_CLAIM = 'R';
					IF LI_MONTH < 4 THEN
						SELECT YEAR(CURDATE()) into LI_FISCAL_YEAR FROM dual;
                         SET LI_FISCAL_YEAR = LI_FISCAL_YEAR-1;
						SET LS_CLAIM = CONCAT(LS_CLAIM,LI_FISCAL_YEAR);
						SET LS_CLAIM = CONCAT(LS_CLAIM,'-');
					ELSE
						SELECT YEAR(CURDATE()) into LI_FISCAL_YEAR FROM dual;
						SET LS_CLAIM = CONCAT(LS_CLAIM,LI_FISCAL_YEAR);
						SET LS_CLAIM = CONCAT(LS_CLAIM,'-');
					END IF;
			SELECT next_val INTO LS_CLAIM_NUMBER FROM CLAIM_NUMBER_SYSTEM_GENERATOR WHERE FISCAL_YEAR = LI_FISCAL_YEAR;
			SET LS_CLAIM = CONCAT(LS_CLAIM,lpad(LS_CLAIM_NUMBER,6,'0'));
            set sql_safe_updates=0;
			update CLAIM_NUMBER_SYSTEM_GENERATOR SET  next_val = LS_CLAIM_NUMBER+1 WHERE FISCAL_YEAR = LI_FISCAL_YEAR;
            set sql_safe_updates=1;
	SET LOCK_ACQUIRED = RELEASE_LOCK('reimbursement_claim_number_generator_lock'); 
	SELECT LS_CLAIM INTO CLAIM_NUMBER;
  
	END IF;
 
COMMIT;
 
ELSE IF AV_TYPE ='D' THEN 
START TRANSACTION;
	SET LOCK_ACQUIRED = GET_LOCK('direct_claim_number_generator_lock', 30);
	
	IF LOCK_ACQUIRED = 1 THEN
		SELECT MAX(FISCAL_YEAR) INTO LI_FISCAL_YEAR FROM CLAIM_NUMBER_MANUAL_GENERATOR;
		SELECT month(CURDATE()) into LI_MONTH FROM dual;
			IF LI_MONTH > 3 AND LI_FISCAL_YEAR <> (SELECT YEAR(CURDATE()) FROM dual) THEN
				INSERT INTO CLAIM_NUMBER_MANUAL_GENERATOR(next_val,FISCAL_YEAR) VALUES(1, (SELECT YEAR(CURDATE()) FROM dual));
			END IF;
			SET LS_CLAIM = 'D';
				IF LI_MONTH < 4 THEN
					SELECT YEAR(CURDATE()) INTO LI_FISCAL_YEAR FROM dual;
                    SET LI_FISCAL_YEAR = LI_FISCAL_YEAR-1;
					SET LS_CLAIM = CONCAT(LS_CLAIM,LI_FISCAL_YEAR);
					SET LS_CLAIM = CONCAT(LS_CLAIM,'-');
				ELSE
					SELECT YEAR(CURDATE()) INTO LI_FISCAL_YEAR FROM dual;
					SET LS_CLAIM = CONCAT(LS_CLAIM,LI_FISCAL_YEAR);
					SET LS_CLAIM = CONCAT(LS_CLAIM,'-');
				END IF;
		SELECT next_val INTO LS_CLAIM_NUMBER FROM CLAIM_NUMBER_MANUAL_GENERATOR WHERE FISCAL_YEAR = LI_FISCAL_YEAR;
		SET LS_CLAIM = CONCAT(LS_CLAIM,lpad(LS_CLAIM_NUMBER,6,'0'));
        set sql_safe_updates=0;
		UPDATE CLAIM_NUMBER_MANUAL_GENERATOR SET  next_val = LS_CLAIM_NUMBER+1 WHERE FISCAL_YEAR = LI_FISCAL_YEAR;
        set sql_safe_updates=1;
	SET LOCK_ACQUIRED = RELEASE_LOCK('direct_claim_number_generator_lock');
	SELECT LS_CLAIM INTO CLAIM_NUMBER;
	
	END IF;
COMMIT;
END IF;
END IF;
END
