-- `GET_CLAIM_MANPOWER_DETAILS`; 

CREATE PROCEDURE `GET_CLAIM_MANPOWER_DETAILS`(
AV_AWARD_NUMBER VARCHAR(12),
AV_CLAIM_ID VARCHAR(10)
)
BEGIN
DECLARE LS_MODE INT;
SELECT COUNT(CLAIM_ID) INTO LS_MODE FROM CLAIM WHERE CLAIM_STATUS_CODE NOT IN (1, 2, 7) and CLAIM_ID = AV_CLAIM_ID;
	IF LS_MODE = 0 THEN
    
		SELECT 
		T3.CLAIM_MANPOWER_ID,
		T3.CLAIM_ID,
		T3.CLAIM_NUMBER,
		T2.PERSON_ID,
		T3.IS_GRANT_USED,
		T3.SOURCE_OF_FUNDING,
		T3.IS_APPROVED_FOR_FOREIGN_STAFF,
		T3.DATE_OF_APPROVAL,
		T3.IS_JOB_REQ_PHD_QUALIFICATION,
		T3.PERCNTGE_TIME_SPENT_ON_PROG,
		T3.INSTITUTION,
		T3.NATIONALITY_WAIVER_DESC,
		T1.BUDGET_REFERENCE_NUMBER AS WBS_NUMBER,
		T1.MANPOWER_TYPE_CODE,
		T2.COST_ALLOCATION,
		T2.CHARGE_START_DATE,
		T2.CHARGE_END_DATE,
		T2.COMMITTED_COST,
		T2.POSITION_ID,
		T2.WORKDAY_REFERENCE_ID,
		T2.RESOURCE_UNIQUE_ID,
        T2.JOB_PROFILE_TYPE_CODE,
        T2.POSITION_STATUS_CODE,
        T7.DESCRIPTION AS POSITION_STATUS,
		T3.UPDATE_TIMESTAMP,
		T3.UPDATE_USER,
		T4.FULL_NAME,
        (CASE T4.STATUS
            WHEN 'A' THEN 'Employed'
            WHEN 'I' THEN 'Resigned'
        END) AS PERSON_STATUS,
        T4.DATE_OF_BIRTH,
        T5.UNIT_NAME,
        T6.DESCRIPTION AS JOB_PROFILE_TYPE,
        T6.DEFAULT_JOB_TITLE,
        T9.QUANTITY AS APPROVED_HEADCOUNT,
		T10.FULL_NAME AS UPDATE_USER_FULL_NAME
		FROM AWARD_MANPOWER T1
		INNER JOIN (
		SELECT AWARD_MANPOWER_ID, COST_ALLOCATION, NULL AS WBS_NUMBER, CHARGE_START_DATE, CHARGE_END_DATE, COMMITTED_COST, POSITION_ID,
		PERSON_ID, NULL AS WORKDAY_REFERENCE_ID, RESOURCE_UNIQUE_ID, JOB_PROFILE_TYPE_CODE, POSITION_STATUS_CODE FROM AWARD_MANPOWER_RESOURCE
		UNION
		SELECT NULL AS AWARD_MANPOWER_ID, COST_ALLOCATION, WBS_NUMBER, CHARGE_START_DATE, CHARGE_END_DATE, COMMITTED_COST,
		POSITION_ID, PERSON_ID, WORKDAY_REFERENCE_ID, NULL AS RESOURCE_UNIQUE_ID, JOB_PROFILE_TYPE_CODE, POSITION_STATUS_CODE FROM MANPOWER_WORKDAY_RESOURCE
		) T2 ON T1.BUDGET_REFERENCE_NUMBER = T2.WBS_NUMBER OR T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID
		LEFT OUTER JOIN CLAIM_MANPOWER T3 ON T1.BUDGET_REFERENCE_NUMBER = T3.WBS_NUMBER AND T3.CLAIM_ID = AV_CLAIM_ID AND ((T3.PERSON_ID = T2.PERSON_ID 
		AND T2.CHARGE_START_DATE = T3.CHARGE_START_DATE AND T2.CHARGE_END_DATE = T3.CHARGE_END_DATE AND 
		T2.WORKDAY_REFERENCE_ID = T3.WORKDAY_REFERENCE_ID) OR T2.RESOURCE_UNIQUE_ID = T3.RESOURCE_UNIQUE_ID)
		LEFT OUTER JOIN PERSON T4 ON T2.PERSON_ID = T4.PERSON_ID
        LEFT OUTER JOIN UNIT T5 ON T4.HOME_UNIT = T5.UNIT_NUMBER
        LEFT OUTER JOIN MANPOWER_JOB_PROFILE_TYPE T6 ON T6.JOB_PROFILE_TYPE_CODE = T2.JOB_PROFILE_TYPE_CODE
        LEFT OUTER JOIN MANPOWER_POSITION_STATUS T7 ON T7.POSITION_STATUS_CODE = T2.POSITION_STATUS_CODE
        INNER JOIN AWARD_BUDGET_HEADER T8 ON T8.AWARD_ID = T1.AWARD_ID AND T8.VERSION_NUMBER = (select max(VERSION_NUMBER) from AWARD_BUDGET_HEADER where AWARD_ID = T1.AWARD_ID)
		INNER JOIN AWARD_BUDGET_DETAIL T9 ON T9.INTERNAL_ORDER_CODE = T1.BUDGET_REFERENCE_NUMBER AND T9.BUDGET_HEADER_ID = T8.BUDGET_HEADER_ID
		LEFT OUTER JOIN PERSON T10 ON T10.USER_NAME = T3.UPDATE_USER
		WHERE T1.AWARD_NUMBER = AV_AWARD_NUMBER AND T1.SEQUENCE_NUMBER = 0 AND T2.PERSON_ID NOT IN ('999999999100') AND T1.MANPOWER_TYPE_CODE NOT IN (3);
	ELSE 
		
		SELECT T1.*, T2.FULL_NAME, (CASE T2.STATUS WHEN 'A' THEN 'Employed' WHEN 'I' THEN 'Resigned' END) AS PERSON_STATUS,
        T2.DATE_OF_BIRTH, T3.UNIT_NAME, T5.DESCRIPTION AS POSITION_STATUS, T4.DESCRIPTION AS JOB_PROFILE_TYPE, T4.DEFAULT_JOB_TITLE,T6.FULL_NAME AS UPDATE_USER_FULL_NAME FROM CLAIM_MANPOWER T1
        LEFT OUTER JOIN PERSON T2 ON T2.PERSON_ID = T1.PERSON_ID 
        LEFT OUTER JOIN UNIT T3 ON T2.HOME_UNIT = T3.UNIT_NUMBER
        LEFT OUTER JOIN MANPOWER_JOB_PROFILE_TYPE T4 ON T4.JOB_PROFILE_TYPE_CODE = T1.JOB_PROFILE_TYPE_CODE
        LEFT OUTER JOIN MANPOWER_POSITION_STATUS T5 ON T5.POSITION_STATUS_CODE = T1.POSITION_STATUS_CODE
		LEFT OUTER JOIN PERSON T6 ON T6.USER_NAME=T1.UPDATE_USER
        WHERE CLAIM_ID = AV_CLAIM_ID;
		
	END IF;
END
