-- `UPDATE_CLAIM_INDIRECT_COST`; 

CREATE PROCEDURE `UPDATE_CLAIM_INDIRECT_COST`(
IN AV_TYPE INT)
BEGIN
DECLARE LI_FLAG int;
DECLARE LI_CLAIM_ID int(11);
DECLARE LI_AWARD_ID int(11);
DECLARE LI_IDC_ORGINAL_AMOUNT DECIMAL(15,2);
DECLARE LI_IDC_LATEST_AMOUNT DECIMAL(15,2);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
	
		BEGIN
		
		DECLARE DONE3 INT DEFAULT FALSE;
		DECLARE CUR_SUMMARY_DATA CURSOR FOR					
		
		SELECT CLAIM_ID, AWARD_ID, AWARD_NUMBER FROM CLAIM WHERE CREATE_USER = 'admin' and date_format(CREATE_TIMESTAMP,'%Y-%m-%d') = '2022-02-26' and (IDC_ORGINAL_AMOUNT is null or IDC_LATEST_AMOUNT is null);
		
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
	
		OPEN CUR_SUMMARY_DATA;
		
		INSERT_LOOP3: LOOP 
		FETCH CUR_SUMMARY_DATA INTO
		LI_CLAIM_ID,LI_AWARD_ID,LS_AWARD_NUMBER;
		
		IF DONE3 THEN
			LEAVE INSERT_LOOP3;
		END IF;
						
            SELECT  COUNT(1) INTO LI_FLAG 			
            FROM AWARD_BUDGET_HEADER T1
			LEFT OUTER JOIN(SELECT a2.TOTAL_INDIRECT_COST, a2.AWARD_ID
							FROM AWARD_BUDGET_HEADER A2
							WHERE A2.AWARD_ID = LI_AWARD_ID
							AND A2.VERSION_NUMBER IN (SELECT MIN(AB1.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER AB1
							WHERE AB1.AWARD_ID = A2.AWARD_ID)															   
							)S1 on s1.AWARD_ID = t1.AWARD_ID
			WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER AND T1.AWARD_ID = LI_AWARD_ID AND T1.VERSION_NUMBER IN (SELECT MAX(AB1.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER AB1 WHERE AB1.AWARD_ID = T1.AWARD_ID);
            
            IF LI_FLAG > 0 THEN
			
				SELECT  S1.TOTAL_INDIRECT_COST , t1.TOTAL_INDIRECT_COST INTO LI_IDC_ORGINAL_AMOUNT, LI_IDC_LATEST_AMOUNT FROM AWARD_BUDGET_HEADER T1
				LEFT OUTER JOIN(SELECT a2.TOTAL_INDIRECT_COST, a2.AWARD_ID
								FROM AWARD_BUDGET_HEADER A2
								WHERE A2.AWARD_ID = LI_AWARD_ID
								AND A2.VERSION_NUMBER IN (SELECT MIN(AB1.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER AB1
								WHERE AB1.AWARD_ID = A2.AWARD_ID)															   
								)S1 on s1.AWARD_ID = t1.AWARD_ID
				WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER AND T1.AWARD_ID = LI_AWARD_ID AND T1.VERSION_NUMBER IN (SELECT MAX(AB1.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER AB1 WHERE AB1.AWARD_ID = T1.AWARD_ID);
				
				UPDATE CLAIM SET IDC_ORGINAL_AMOUNT = LI_IDC_ORGINAL_AMOUNT, IDC_LATEST_AMOUNT = LI_IDC_LATEST_AMOUNT WHERE CLAIM_ID = LI_CLAIM_ID;
			END IF;
		COMMIT;    
		END LOOP;
		CLOSE CUR_SUMMARY_DATA;
		END;
		
               
 END
