
DROP TABLE IF EXISTS `sr_header_field`;
CREATE TABLE `sr_header_field` (
  `SR_HEADER_FIELD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIELD_NAME` varchar(30) DEFAULT NULL,
  `FIELD_TYPE` varchar(30) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `VALUE` varchar(1000) DEFAULT NULL,
  `SR_HEADER_ID` int(11) NOT NULL,
  `IS_EDITABLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SR_HEADER_FIELD_ID`),
  KEY `SR_HEADER_FIELD_FK1` (`SR_HEADER_ID`),
  CONSTRAINT `SR_HEADER_FIELD_FK1` FOREIGN KEY (`SR_HEADER_ID`) REFERENCES `sr_header` (`SR_HEADER_ID`)
) ;