DROP TABLE IF EXISTS `sr_process_flow`;

CREATE TABLE `sr_process_flow` (
  `PROCESS_FLOW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTION_LOG_ID` int(11) DEFAULT NULL,
  `HAS_REVIEW_RIGHT` varchar(255) DEFAULT NULL,
  `PROCESS_END_TIMESTAMP` datetime(6) DEFAULT NULL,
  `PROCESS_START_TIMESTAMP` datetime(6) DEFAULT NULL,
  `ROLE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `STATUS_CODE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SR_HEADER_ID` int(11) NOT NULL,
  PRIMARY KEY (`PROCESS_FLOW_ID`),
  KEY `SR_PROCESS_FLOW_FK1` (`SR_HEADER_ID`),
  KEY `SR_PROCESS_FLOW_FK3` (`ROLE_TYPE_CODE`),
  KEY `SR_PROCESS_FLOW_FK2` (`STATUS_CODE`),
  CONSTRAINT `SR_PROCESS_FLOW_FK1` FOREIGN KEY (`SR_HEADER_ID`) REFERENCES `sr_header` (`SR_HEADER_ID`),
  CONSTRAINT `SR_PROCESS_FLOW_FK2` FOREIGN KEY (`STATUS_CODE`) REFERENCES `sr_status` (`STATUS_CODE`),
  CONSTRAINT `SR_PROCESS_FLOW_FK3` FOREIGN KEY (`ROLE_TYPE_CODE`) REFERENCES `sr_role_type` (`ROLE_TYPE_CODE`)
) ;
