DROP TABLE IF EXISTS `sr_reporter_change_history`;

CREATE TABLE `sr_reporter_change_history` (
  `REPORTER_CHANGE_HISTORY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTION_LOG_ID` int(11) DEFAULT NULL,
  `NEW_REPORTER_PERSON_ID` varchar(40) DEFAULT NULL,
  `OLD_REPORTER_PERSON_ID` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SR_HEADER_ID` int(11) NOT NULL,
  PRIMARY KEY (`REPORTER_CHANGE_HISTORY_ID`),
  KEY `SR_REPORTER_CHANGE_HISTORY_FK1` (`SR_HEADER_ID`),
  KEY `SR_REPORTER_CHANGE_HISTORY_FK2` (`ACTION_LOG_ID`),
  CONSTRAINT `SR_REPORTER_CHANGE_HISTORY_FK1` FOREIGN KEY (`SR_HEADER_ID`) REFERENCES `sr_header` (`SR_HEADER_ID`),
  CONSTRAINT `SR_REPORTER_CHANGE_HISTORY_FK2` FOREIGN KEY (`ACTION_LOG_ID`) REFERENCES `sr_action_log` (`ACTION_LOG_ID`)
) ;
