
DROP TABLE IF EXISTS `sr_status`;

CREATE TABLE `sr_status` (
  `STATUS_CODE` int(11) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `ACTION_TYPE_CODE` int(11) DEFAULT NULL,
  PRIMARY KEY (`STATUS_CODE`),
  KEY `SR_STATUS_FK1` (`ACTION_TYPE_CODE`),
  CONSTRAINT `SR_STATUS_FK1` FOREIGN KEY (`ACTION_TYPE_CODE`) REFERENCES `sr_action_type` (`ACTION_TYPE_CODE`)
) ;
