DROP TABLE IF EXISTS `ext_review_action_type`;

CREATE TABLE `ext_review_action_type` (
  `EXT_REVIEW_ACTION_TYPE_CODE` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `MESSAGE` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`EXT_REVIEW_ACTION_TYPE_CODE`)
);

