

DROP TABLE IF EXISTS `ext_specialism_keyword`;

CREATE TABLE `ext_specialism_keyword` (
  `SPECIALISM_KEYWORD_CODE` varchar(15) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`SPECIALISM_KEYWORD_CODE`)
);

