SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `ext_review_comments`;

CREATE TABLE `ext_review_comments` (
  `EXT_REVIEW_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REVIEW_REVIEWER_ID` int(11) DEFAULT NULL,
  `EXT_REVIEW_ID` int(11) DEFAULT NULL,
  `REVIEW_COMMENT` varchar(4000) DEFAULT NULL,
  `COMMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `IS_PRIVATE_COMMENT` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `ADMIN_USER_ID` int(11) DEFAULT NULL,
  `EXT_REV_COMMENT_ATTACHMENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EXT_REVIEW_COMMENT_ID`),
  KEY `EXT_REVIEW_COMMENTS_FK_01` (`REVIEW_REVIEWER_ID`),
  KEY `EXT_REVIEW_COMMENTS_FK_02` (`EXT_REVIEW_ID`),
  KEY `EXT_REVIEW_COMMENTS_FK_04` (`COMMENT_TYPE_CODE`),
  KEY `EXT_REVIEW_COMMENTS_FK_03` (`EXT_REV_COMMENT_ATTACHMENT_ID`),
  CONSTRAINT `EXT_REVIEW_COMMENTS_FK_01` FOREIGN KEY (`REVIEW_REVIEWER_ID`) REFERENCES `ext_review_reviewers` (`REVIEW_REVIEWER_ID`),
  CONSTRAINT `EXT_REVIEW_COMMENTS_FK_02` FOREIGN KEY (`EXT_REVIEW_ID`) REFERENCES `ext_review` (`EXT_REVIEW_ID`),
  CONSTRAINT `EXT_REVIEW_COMMENTS_FK_03` FOREIGN KEY (`EXT_REV_COMMENT_ATTACHMENT_ID`) REFERENCES `ext_rev_comment_attachment` (`EXT_REV_COMMENT_ATTACHMENT_ID`),
  CONSTRAINT `EXT_REVIEW_COMMENTS_FK_04` FOREIGN KEY (`COMMENT_TYPE_CODE`) REFERENCES `ext_review_comment_type` (`EXT_REVIEW_COMMENT_TYPE_CODE`)
);
SET FOREIGN_KEY_CHECKS = 1;