

--
--  `external_user`
--

DROP TABLE IF EXISTS `external_user`;

CREATE TABLE `external_user` (
  `PERSON_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FULL_NAME` varchar(100) DEFAULT NULL,
  `USER_NAME` varchar(60) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(60) DEFAULT NULL,
  `FUNDING_OFFICE` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(400) DEFAULT NULL,
  `ORGANIZATION_ID` varchar(20) DEFAULT NULL,
  `VERIFIED_FLAG` varchar(1) DEFAULT NULL,
  `CREATED_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATED_TIMESTAMP` datetime DEFAULT NULL,
  `VERIFIED_AT` datetime DEFAULT NULL,
  `VERIFIED_BY` varchar(60) DEFAULT NULL,
  `IS_SGAF_USER` varchar(1) DEFAULT NULL,
  `ADMIN_COMMENT` varchar(600) DEFAULT NULL,
  `IS_MAIL_SENT` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`PERSON_ID`)
);

