

DROP TABLE IF EXISTS `external_reviewer_attachments`;

CREATE TABLE `external_reviewer_attachments` (
  `EXTERNAL_REVIEWER_ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATTACHMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `EXTERNAL_REVIEWER_ID` int(11) NOT NULL,
  PRIMARY KEY (`EXTERNAL_REVIEWER_ATTACHMENT_ID`),
  KEY `EXTERNAL_REVIEWER_ATTACHMENTS_FK1` (`ATTACHMENT_TYPE_CODE`),
  KEY `EXTERNAL_REVIEWER_ATTACHMENTS_FK2` (`EXTERNAL_REVIEWER_ID`),
  CONSTRAINT `EXTERNAL_REVIEWER_ATTACHMENTS_FK1` FOREIGN KEY (`ATTACHMENT_TYPE_CODE`) REFERENCES `ext_reviewer_attachment_type` (`ATTACHMENT_TYPE_CODE`),
  CONSTRAINT `EXTERNAL_REVIEWER_ATTACHMENTS_FK2` FOREIGN KEY (`EXTERNAL_REVIEWER_ID`) REFERENCES `external_reviewer` (`EXTERNAL_REVIEWER_ID`)
);

