

--
--  `external_reviewer_ext`
--

DROP TABLE IF EXISTS `external_reviewer_ext`;

CREATE TABLE `external_reviewer_ext` (
  `EXTERNAL_REVIEWER_EXT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXTERNAL_REVIEWER_ID` int(11) DEFAULT NULL,
  `HI_INDEX` int(11) DEFAULT NULL,
  `SCOPUS_URL` varchar(1000) DEFAULT NULL,
  `COI_WITH_PERSON` VARCHAR(1000) DEFAULT NULL,
  `SUPPLIER_DOF` varchar(50) DEFAULT NULL,
  `CIRA_CODE` varchar(3) DEFAULT NULL,
  `ORGINALITY_CODE` varchar(15) DEFAULT NULL,
  `THOROUGHNESS_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `URL_PROFILE` VARCHAR(1000) DEFAULT NULL,
  `DISCIPLINARY_FIELD` VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (`EXTERNAL_REVIEWER_EXT_ID`),
  KEY `EXTERNAL_REVIEWER_EXT_FK2` (`CIRA_CODE`),
  KEY `EXTERNAL_REVIEWER_EXT_FK3` (`ORGINALITY_CODE`),
  KEY `EXTERNAL_REVIEWER_EXT_FK4` (`THOROUGHNESS_CODE`),
  KEY `EXTERNAL_REVIEWER_EXT_FK1` (`EXTERNAL_REVIEWER_ID`),
  CONSTRAINT `EXTERNAL_REVIEWER_EXT_FK1` FOREIGN KEY (`EXTERNAL_REVIEWER_ID`) REFERENCES `external_reviewer` (`EXTERNAL_REVIEWER_ID`),
  CONSTRAINT `EXTERNAL_REVIEWER_EXT_FK2` FOREIGN KEY (`CIRA_CODE`) REFERENCES `ext_reviewer_cira` (`CIRA_CODE`),
  CONSTRAINT `EXTERNAL_REVIEWER_EXT_FK3` FOREIGN KEY (`ORGINALITY_CODE`) REFERENCES `ext_reviewer_originality` (`ORGINALITY_CODE`),
  CONSTRAINT `EXTERNAL_REVIEWER_EXT_FK4` FOREIGN KEY (`THOROUGHNESS_CODE`) REFERENCES `ext_reviewer_thoroughness` (`THOROUGHNESS_CODE`)
);

