INSERT INTO manpower_compensation_type (COMPENSATION_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('1','M1','Y','admin','2020-10-23 10:36:21');
INSERT INTO manpower_compensation_type (COMPENSATION_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('2','M2','Y','admin','2020-10-23 10:36:21');
INSERT INTO manpower_compensation_type (COMPENSATION_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('3','M3','Y','admin','2020-10-23 10:36:21');
