INSERT INTO manpower_budget_reference_type (BUDGET_REFERENCE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,IS_ACTIVE) VALUES ('1','WBS','admin','2020-10-23 10:36:21','Y');
INSERT INTO manpower_budget_reference_type (BUDGET_REFERENCE_TYPE_CODE,DESCRIPTION,UPDATE_USER,UPDATE_TIMESTAMP,IS_ACTIVE) VALUES ('2','B','admin','2020-10-23 10:36:21','Y');
