INSERT INTO manpower_type (MANPOWER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('1','Staff','Y','admin','2020-10-23 10:36:21');
INSERT INTO manpower_type (MANPOWER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('2','Student','Y','admin','2020-10-23 10:36:21');
INSERT INTO manpower_type (MANPOWER_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('3','Others','Y','admin','2020-10-23 10:36:21');
