CREATE FUNCTION FN_FETCH_DYN_SR_PLACEHOLDER(AV_MODULE_CODE INT, AV_PROJECT_ID INT, AV_SR_HEADER_ID INT) RETURNS json
DETERMINISTIC
BEGIN
DECLARE LS_TITLE VARCHAR(1000) DEFAULT '';
DECLARE LS_PROJECT_NUMBER VARCHAR(12) DEFAULT '';
DECLARE LS_SPONSOR_NAME VARCHAR(255) DEFAULT '';
DECLARE LS_SPONSOR_CODE VARCHAR(6) DEFAULT '';
DECLARE LS_PI_NAME VARCHAR(90) DEFAULT '';
    
    IF AV_MODULE_CODE = 1 THEN
        SELECT TITLE,  AWARD_NUMBER,  SPONSOR_CODE INTO LS_TITLE, LS_PROJECT_NUMBER , LS_SPONSOR_CODE 
        FROM AWARD WHERE AWARD_ID = AV_PROJECT_ID;

    ELSEIF AV_MODULE_CODE = 2 THEN
   
        SELECT TITLE,  PROPOSAL_ID,  SPONSOR_CODE INTO LS_TITLE, LS_PROJECT_NUMBER , LS_SPONSOR_CODE 
        FROM PROPOSAL
        WHERE PROPOSAL_ID = AV_PROJECT_ID;

    ELSEIF AV_MODULE_CODE = 3 THEN
   
        SELECT TITLE,  PROPOSAL_ID,  SPONSOR_CODE INTO LS_TITLE, LS_PROJECT_NUMBER , LS_SPONSOR_CODE 
        FROM EPS_PROPOSAL
        WHERE PROPOSAL_ID = AV_PROJECT_ID;

    ELSEIF  AV_MODULE_CODE = 13 THEN
        SELECT TITLE,  AGREEMENT_REQUEST_ID,  SPONSOR_CODE INTO LS_TITLE, LS_PROJECT_NUMBER, LS_SPONSOR_CODE 
        FROM AGREEMENT_HEADER
        WHERE AGREEMENT_REQUEST_ID = AV_PROJECT_ID;
    
    ELSEIF  AV_MODULE_CODE = 20 THEN
        SELECT SUBJECT AS TITLE,  SR_HEADER_ID,  NULL AS SPONSOR_CODE INTO LS_TITLE, LS_PROJECT_NUMBER, LS_SPONSOR_CODE 
        FROM SR_HEADER
        WHERE SR_HEADER_ID = AV_PROJECT_ID;
    
    END IF;
    
    IF LS_SPONSOR_CODE IS NOT NULL THEN
        SELECT COALESCE(DISPLAY_NAME, '') INTO LS_SPONSOR_NAME FROM SPONSOR WHERE SPONSOR_CODE = LS_SPONSOR_CODE;
    END IF;
    
    SELECT COALESCE(FULL_NAME, '') INTO LS_PI_NAME FROM SR_PERSONS WHERE SR_HEADER_ID = AV_SR_HEADER_ID AND PERSON_ROLE_ID = 3;
    
    RETURN  JSON_OBJECT(
            '{LINKED_MODULE_TITLE}', LS_TITLE,
            '{LINKED_MODULE_NUMBER}', LS_PROJECT_NUMBER,
            '{SPONSOR_DETAILS}', LS_SPONSOR_NAME,
            '{PRINCIPAL_INVESTIGATOR}', LS_PI_NAME
        );
END
