CREATE PROCEDURE GET_NEGATIVE_UNCOMMITTED_BALANCE()
BEGIN
    SELECT DISTINCT
        T1.BUDGET_REFERENCE_NUMBER AS WBS_NUMBER,
        T3.LINE_ITEM_COST AS BUDGET_AMOUNT,
        T7.DESCRIPTION AS COST_ELEMENT,
        T7.COST_ELEMENT AS COST_ELEMENT_CODE,
        COUNT(T4.MANPOWER_WORKDAY_RESOURCE_ID) AS ACTUAL_HEAD_COUNT,
        CAST(T3.QUANTITY AS UNSIGNED) AS APPROVED_HEAD_COUNT,
        IFNULL(T5.TOTAL_EXPENSE_AMOUNT, 0) AS EXPENSE_AMOUNT,
        IFNULL(T6.COMMITTED_AMOUNT, 0) AS COMMITTED_AMOUNT,
        (IFNULL(T3.LINE_ITEM_COST, 0) - IFNULL(T6.COMMITTED_AMOUNT, 0)) AS UNCOMMITTED_AMOUNT,
        T8.DESCRIPTION AS BUDGET_CATEGORY,
        T4.POSITION_ID AS POSITION_ID,
        T4.CHARGE_START_DATE AS CHARGE_START_DATE,
        T4.CHARGE_END_DATE AS CHARGE_END_DATE,
        T4.COST_ALLOCATION AS COST_ALLOCATION,
        T4.PERSON_ID AS PERSON_ID,
        T4.JOB_PROFILE_TYPE_CODE AS JOB_PROFILE
		
    FROM AWARD_MANPOWER T1
	INNER JOIN award awd on t1.AWARD_ID = awd.AWARD_ID 
		and awd.AWARD_SEQUENCE_STATUS in ('ACTIVE', 'PENDING') and awd.STATUS_CODE= '1'
    INNER JOIN award_budget_header T2 
        ON T2.AWARD_ID = T1.AWARD_ID 
        AND T2.VERSION_NUMBER = (
            SELECT MAX(VERSION_NUMBER) 
            FROM award_budget_header 
            WHERE AWARD_ID = T1.AWARD_ID
        )
    INNER JOIN award_budget_detail T3 
        ON T3.BUDGET_HEADER_ID = T2.BUDGET_HEADER_ID 
        AND (T3.INTERNAL_ORDER_CODE = T1.BUDGET_REFERENCE_NUMBER 
             OR T3.BUDGET_DETAILS_ID = T1.BUDGET_REFERENCE_NUMBER)
    INNER JOIN cost_element T7 
        ON T7.COST_ELEMENT = T3.COST_ELEMENT
    INNER JOIN BUDGET_CATEGORY T8 
        ON T8.BUDGET_CATEGORY_CODE = T3.BUDGET_CATEGORY_CODE
    LEFT OUTER JOIN MANPOWER_WORKDAY_RESOURCE T4 
        ON T4.WBS_NUMBER = T1.BUDGET_REFERENCE_NUMBER
        AND T4.PERSON_ID IS NOT NULL 
        AND T4.POSITION_STATUS_CODE NOT IN ('8', '5') 
        AND T4.PERSON_ID <> '999999999100'
        AND UTC_DATE() BETWEEN DATE(T4.CHARGE_START_DATE) AND DATE(T4.CHARGE_END_DATE)
    LEFT OUTER JOIN AWARD_EXPENSE_DETAILS T5 
        ON T5.INTERNAL_ORDER_CODE = T1.BUDGET_REFERENCE_NUMBER
    LEFT OUTER JOIN (
        SELECT IFNULL(SUM(sub_query.amount), 0) AS COMMITTED_AMOUNT,
               sub_query.WBS_NUMBER AS WBS_NUMBER, sub_query.AWARD_ID as AWARD_ID
        FROM (
            SELECT IFNULL(SUM(COALESCE(ta1.COMMITTED_COST, ta1.PLANNED_SALARY, 0)), 0) AS amount,
                   ta2.BUDGET_REFERENCE_NUMBER AS WBS_NUMBER ,ta2.AWARD_ID as AWARD_ID
            FROM award_manpower_resource ta1
            JOIN AWARD_MANPOWER ta2 
                ON ta1.AWARD_MANPOWER_ID = ta2.AWARD_MANPOWER_ID
            LEFT JOIN workday_position_requisition ta3 
                ON ta1.POSITION_ID = ta3.POSITION_ID
            JOIN award ta4 
                ON ta2.AWARD_ID = ta4.AWARD_ID
            WHERE (ta2.MANPOWER_TYPE_CODE = 1 
                   AND (ta1.POSITION_ID IS NULL
                        OR ta3.JOB_REQUISITION_STATUS IS NULL
                        OR ta3.JOB_REQUISITION_STATUS = 'Open'))
                   OR ta2.MANPOWER_TYPE_CODE <> 1
            GROUP BY ta2.AWARD_ID, ta2.BUDGET_REFERENCE_NUMBER 
            UNION 
            SELECT SUM(COALESCE(sq1.ADJUSTED_COMMITTED_COST, sq1.COMMITTED_COST, 0)) AS amount, 
                   sq1.WBS_NUMBER AS WBS_NUMBER, sqawd.AWARD_ID as AWARD_ID
            FROM manpower_workday_resource sq1 
			INNER JOIN award sqawd on 
				sqawd.ACCOUNT_NUMBER =  substring_index(sq1.WBS_NUMBER, "EOM", 1) 
				and sqawd.AWARD_SEQUENCE_STATUS in ('ACTIVE', 'PENDING') and sqawd.STATUS_CODE='1'
            GROUP BY sqawd.AWARD_ID, sq1.WBS_NUMBER
        ) sub_query 
        GROUP BY sub_query.AWARD_ID, sub_query.WBS_NUMBER
    ) T6 
        ON T6.WBS_NUMBER = T1.BUDGET_REFERENCE_NUMBER 
		 and T6.AWARD_ID = T1.AWARD_ID
    WHERE IFNULL(T3.LINE_ITEM_COST, 0) < IFNULL(T6.COMMITTED_AMOUNT, 0)
    GROUP BY T1.BUDGET_REFERENCE_NUMBER, T7.DESCRIPTION;
END
