-- `UPDATE_MANPOWER_AWARD_NUMBER`; 

CREATE PROCEDURE `UPDATE_MANPOWER_AWARD_NUMBER`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE C1 CURSOR FOR 
	SELECT AWARD_NUMBER,AWARD_MANPOWER_ID FROM AWARD_MANPOWER;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE LS_AWARD_MANPOWER_ID INT;
    DECLARE LS_AWARD_NUMBER VARCHAR(200);
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
FETCH C1 INTO LS_AWARD_NUMBER, LS_AWARD_MANPOWER_ID;
	UPDATE AWARD_MANPOWER_RESOURCE SET AWARD_NUMBER = LS_AWARD_NUMBER, MODULE_CODE = 1 AND SUB_MODULE_CODE = 4 WHERE AWARD_MANPOWER_ID = LS_AWARD_MANPOWER_ID;
	COMMIT;
IF DONE THEN
LEAVE LOOP1;
END IF;
END; 
END LOOP;
CLOSE C1;
END
