DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `COI_EVALUATE_VALIDATION_MESSAGE`(
	AV_DISCLOSURE_ID INT,
    AV_PERSON_ID VARCHAR(45),
	AV_VALIDATION_TYPE VARCHAR(10),
    AV_VALIDATION_MSG_TYPE VARCHAR(10)
  )
BEGIN
DECLARE LS_PARAMETER VARCHAR(20);
DECLARE LI_SFI_FLAG INT DEFAULT 0;
DECLARE LI_SFI_FLAG_2 INT DEFAULT 0;
IF AV_VALIDATION_TYPE = 'VE' AND AV_VALIDATION_MSG_TYPE = 'PS' THEN
		SELECT VALUE INTO LS_PARAMETER FROM PARAMETER WHERE PARAMETER_NAME = 'ENGAGEMENT_TYPE_FOR_COI_DISCLOSURE';
			SELECT DISTINCT
				NULL AS SFIs,
				CONCAT(
					'DisclDetailId:: ', T1.COI_DISCL_PROJECT_ENTITY_REL_ID, '||',
					'Title:: ', COALESCE(T2.TITLE, T3.TITLE, T6.TITLE), '||',
					'Entity:: ', T4.PRIMARY_NAME, '||',
					'ModuleCode:: ', COALESCE(T2.COI_PROJECT_TYPE_CODE, T3.COI_PROJECT_TYPE_CODE, T6.COI_PROJECT_TYPE_CODE), '||',
					'ModuleItemKey:: ', COALESCE(T2.AWARD_NUMBER, T3.PROPOSAL_NUMBER, T6.PROPOSAL_NUMBER)
				) AS PROJ_SFI_DETAILS
				FROM COI_DISCL_PROJECT_ENTITY_REL T1
				INNER JOIN COI_DISCL_PROJECTS T7
					ON T7.COI_DISCL_PROJECTS_ID = T1.COI_DISCL_PROJECTS_ID
				INNER JOIN PERSON_ENTITY_RELATIONSHIP T5
					ON T5.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
				INNER JOIN PERSON_ENTITY PE
					ON PE.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
				LEFT JOIN COI_PROJECT_AWARD_V T2
					ON T2.AWARD_NUMBER = T7.MODULE_ITEM_KEY AND T7.MODULE_CODE = 1
				LEFT JOIN COI_PROJECT_PROPOSAL_V T3
					ON T3.PROPOSAL_NUMBER = T7.MODULE_ITEM_KEY AND T7.MODULE_CODE = 3
				LEFT JOIN COI_PROJECT_INSTITUTE_PROPOSAL_V T6
					ON T6.PROPOSAL_NUMBER = T7.MODULE_ITEM_KEY AND T7.MODULE_CODE = 2
				INNER JOIN ENTITY T4
					ON T4.ENTITY_ID = T1.ENTITY_ID
				WHERE T7.DISCLOSURE_ID = AV_DISCLOSURE_ID
				  AND T1.PROJECT_CONFLICT_STATUS_CODE IS NULL
				  AND T1.PERSON_ENTITY_ID IS NOT NULL
				  AND (
						LS_PARAMETER = 'ALL_ENG'
						OR (LS_PARAMETER = 'ALL_FIN' AND T5.VALID_PERS_ENTITY_REL_TYP_CODE IN (1, 2, 3))
						OR (LS_PARAMETER = 'ALL_SFI' AND PE.IS_SIGNIFICANT_FIN_INTEREST = 'Y')
					  );
       SET LS_PARAMETER = '';
ELSEIF AV_VALIDATION_TYPE = 'VW' AND AV_VALIDATION_MSG_TYPE = 'PS' THEN
			SELECT DISTINCT NULL AS SFIs ,
             CONCAT('DisclDetailId:: ', T1.COI_DISCL_PROJECT_ENTITY_REL_ID, '||', 'Title:: ', COALESCE(T5.TITLE, T6.TITLE, T8.TITLE), '||', 'Entity:: ', T7.PRIMARY_NAME, '||',
             'ModuleCode:: ', COALESCE(T5.COI_PROJECT_TYPE_CODE, T6.COI_PROJECT_TYPE_CODE, T8.COI_PROJECT_TYPE_CODE), '||', 'ModuleItemKey:: ', COALESCE(T5.AWARD_NUMBER, T6.PROPOSAL_NUMBER, T8.PROPOSAL_NUMBER)) AS PROJ_SFI_DETAILS
             FROM COI_DISCL_PROJECT_ENTITY_REL T1
  		   INNER JOIN COI_DISCL_PROJECTS T9 ON T9.COI_DISCL_PROJECTS_ID = T1.COI_DISCL_PROJECTS_ID
             INNER JOIN PERSON_ENTITY T2 ON T2.PERSON_ENTITY_NUMBER = T1.PERSON_ENTITY_NUMBER
             LEFT JOIN COI_PROJECT_AWARD_V T5 ON T5.AWARD_NUMBER = T9.MODULE_ITEM_KEY AND T9.MODULE_CODE = 1
             LEFT JOIN COI_PROJECT_PROPOSAL_V T6 ON T6.PROPOSAL_NUMBER = T9.MODULE_ITEM_KEY AND T9.MODULE_CODE = 3
             LEFT JOIN coi_project_institute_proposal_v T8 ON T8.PROPOSAL_NUMBER = T9.MODULE_ITEM_KEY AND T9.MODULE_CODE = 2
             INNER JOIN ENTITY T7 ON T7.ENTITY_ID = T1.ENTITY_ID
             WHERE  (T1.PREVIOUS_PERSON_ENTITY_ID IS NOT NULL AND T1.PERSON_ENTITY_ID != T1.PREVIOUS_PERSON_ENTITY_ID ) AND T9.DISCLOSURE_ID = AV_DISCLOSURE_ID;
ELSEIF AV_VALIDATION_TYPE = 'VE' AND AV_VALIDATION_MSG_TYPE = 'RS' THEN
	SET LI_SFI_FLAG = 0;
	SET LI_SFI_FLAG_2 = 0;
	  SELECT COUNT(*) INTO LI_SFI_FLAG
  		FROM COI_DISCL_PERSON_ENTITY_REL t1
  		INNER JOIN PERSON_ENTITY t2 ON t2.PERSON_ENTITY_ID = t1.PERSON_ENTITY_ID
      INNER JOIN ENTITY t3 ON t3.ENTITY_NUMBER = t2.ENTITY_NUMBER
  		WHERE t1.DISCLOSURE_ID = AV_DISCLOSURE_ID AND t2.ENTITY_ID != t3.ENTITY_ID AND t3.IS_ACTIVE IN ('N', 'Y')
      AND t3.VERSION_STATUS = 'ACTIVE';
	  SELECT COUNT(*) INTO LI_SFI_FLAG_2
  		    FROM COI_DISCL_PERSON_ENTITY_REL t1
            INNER JOIN PERSON_ENTITY t2 ON t2.PERSON_ENTITY_ID = t1.PERSON_ENTITY_ID
            INNER JOIN ENTITY t3 ON t3.ENTITY_NUMBER = t2.ENTITY_NUMBER
            WHERE t1.DISCLOSURE_ID = AV_DISCLOSURE_ID AND t3.DOCUMENT_STATUS_TYPE_CODE = '2' AND t3.VERSION_STATUS = 'ACTIVE';
	IF LI_SFI_FLAG > 0 AND  LI_SFI_FLAG_2 > 0 THEN
		    SELECT DISTINCT CONCAT(t2.PERSON_ENTITY_ID, '||', t5.PRIMARY_NAME) AS SFIs, NULL AS PROJ_SFI_DETAILS
  			FROM COI_DISCL_PERSON_ENTITY_REL t1
            INNER JOIN PERSON_ENTITY t2 ON t2.PERSON_ENTITY_ID = t1.PERSON_ENTITY_ID
            INNER JOIN ENTITY t3 ON t3.ENTITY_NUMBER = t2.ENTITY_NUMBER
             INNER JOIN ENTITY t5 ON t5.ENTITY_ID = t2.ENTITY_ID
            WHERE t1.DISCLOSURE_ID = AV_DISCLOSURE_ID
			AND ((t3.DOCUMENT_STATUS_TYPE_CODE = '2' AND t3.VERSION_STATUS = 'ACTIVE')OR (t2.ENTITY_ID != t3.ENTITY_ID AND t3.IS_ACTIVE IN ('N', 'Y') AND t3.VERSION_STATUS = 'ACTIVE'));
	END IF;
	  IF LI_SFI_FLAG_2 > 0 THEN
	    	SELECT DISTINCT CONCAT(t2.PERSON_ENTITY_ID, '||', t5.PRIMARY_NAME) AS SFIs, NULL AS PROJ_SFI_DETAILS
  			FROM COI_DISCL_PERSON_ENTITY_REL t1
            INNER JOIN PERSON_ENTITY t2 ON t2.PERSON_ENTITY_ID = t1.PERSON_ENTITY_ID
            INNER JOIN ENTITY t3 ON t3.ENTITY_NUMBER = t2.ENTITY_NUMBER
            INNER JOIN ENTITY t5 ON t5.ENTITY_ID = t2.ENTITY_ID
            WHERE t1.DISCLOSURE_ID = AV_DISCLOSURE_ID AND t3.DOCUMENT_STATUS_TYPE_CODE = '2' AND t3.VERSION_STATUS = 'ACTIVE';
	  END IF;
	  IF LI_SFI_FLAG > 0 THEN
	    	SELECT DISTINCT CONCAT(t2.PERSON_ENTITY_ID, '||', t4.PRIMARY_NAME) AS SFIs, NULL AS PROJ_SFI_DETAILS
  			FROM COI_DISCL_PERSON_ENTITY_REL t1
  			INNER JOIN PERSON_ENTITY t2 ON t2.PERSON_ENTITY_ID = t1.PERSON_ENTITY_ID
  			INNER JOIN ENTITY t3 ON t3.ENTITY_NUMBER = t2.ENTITY_NUMBER
            INNER JOIN ENTITY t4 ON t4.ENTITY_ID = t1.ENTITY_ID
            WHERE t1.DISCLOSURE_ID = AV_DISCLOSURE_ID AND t2.ENTITY_ID != t3.ENTITY_ID AND t3.IS_ACTIVE IN ('N', 'Y') AND t3.VERSION_STATUS = 'ACTIVE';
	END IF;
ELSEIF AV_VALIDATION_TYPE = 'VE' AND AV_VALIDATION_MSG_TYPE = 'US' THEN
			SELECT DISTINCT CONCAT(T2.PERSON_ENTITY_ID, '||', T3.PRIMARY_NAME) AS SFIs, NULL AS PROJ_SFI_DETAILS
              FROM COI_DISCL_PERSON_ENTITY_REL T1
              INNER JOIN COI_DISCLOSURE T0 ON T0.DISCLOSURE_ID = T1.DISCLOSURE_ID
              RIGHT JOIN (SELECT t1.PERSON_ENTITY_ID, t1.PERSON_ENTITY_NUMBER, t1.ENTITY_ID, t1.ENTITY_NUMBER FROM PERSON_ENTITY t1
              INNER JOIN PERSON_ENTITY_RELATIONSHIP t2 ON t2.PERSON_ENTITY_ID = t1.PERSON_ENTITY_ID
              INNER JOIN VALID_PERSON_ENTITY_REL_TYPE t3 ON t3.VALID_PERS_ENTITY_REL_TYP_CODE = t2.VALID_PERS_ENTITY_REL_TYP_CODE
              WHERE t1.PERSON_ENTITY_NUMBER NOT IN (SELECT DISTINCT t5.PERSON_ENTITY_NUMBER FROM COI_DISCL_PERSON_ENTITY_REL t5
  				WHERE t5.DISCLOSURE_ID = AV_DISCLOSURE_ID AND t5.PERSON_ENTITY_NUMBER IS NOT NULL)
              AND t1.VERSION_STATUS='ACTIVE' AND t3.DISCLOSURE_TYPE_CODE = '1' AND t1.PERSON_ID = AV_PERSON_ID) T2
              ON (T1.PERSON_ENTITY_NUMBER IS NULL OR T1.PERSON_ENTITY_NUMBER != T2.PERSON_ENTITY_NUMBER)
              INNER JOIN ENTITY T3 ON T3.ENTITY_ID = T2.ENTITY_ID
              WHERE T1.DISCLOSURE_ID = AV_DISCLOSURE_ID AND T0.REVIEW_STATUS_CODE IN (1,5,6);
ELSEIF AV_VALIDATION_TYPE = 'VE' AND AV_VALIDATION_MSG_TYPE = 'INS' THEN
     SELECT VALUE INTO LS_PARAMETER FROM PARAMETER WHERE PARAMETER_NAME = 'ENGAGEMENT_FLOW_TYPE';
	      IF LS_PARAMETER = 'REL_SUMMARY' OR LS_PARAMETER = 'REL_COMP' THEN
    SELECT DISTINCT CONCAT(T2.PERSON_ENTITY_ID, '||', T3.PRIMARY_NAME) AS SFIs, NULL AS PROJ_SFI_DETAILS
                     FROM PERSON_ENTITY T2
                     INNER JOIN ENTITY T3 ON T3.ENTITY_ID = T2.ENTITY_ID
                     WHERE  T2.IS_FORM_COMPLETED = 'N'  AND T2.PERSON_ID = AV_PERSON_ID AND T2.VERSION_STATUS = 'ACTIVE';
		ELSE
          SELECT DISTINCT CONCAT(T2.PERSON_ENTITY_ID, '||', T3.PRIMARY_NAME) AS SFIs, NULL AS PROJ_SFI_DETAILS
                     FROM COI_DISCL_PERSON_ENTITY_REL T1
                     INNER JOIN PERSON_ENTITY T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
                     INNER JOIN ENTITY T3 ON T3.ENTITY_ID = T2.ENTITY_ID
                     WHERE  T2.IS_FORM_COMPLETED = 'N'  AND T1.DISCLOSURE_ID = AV_DISCLOSURE_ID;
	END IF;
ELSEIF AV_VALIDATION_TYPE = 'VE' AND AV_VALIDATION_MSG_TYPE = 'QM' THEN
    SELECT NULL AS SFIs , NULL AS PROJ_SFI_DETAILS;
END IF;
END
$$
DELIMITER ;
