DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `ENRICH_ENTITY_INDUSTRY_CATE_JSON`(
    IN AV_ENTITY_ID INT,
    IN AV_PERSON_ID VARCHAR(255),
    IN AV_JSON_DATA JSON
)
BEGIN
    DECLARE i INT DEFAULT 0;
    DECLARE total INT;
    DECLARE v_INDUSTRY_CATEGORY_ID INT;
    DECLARE v_INDUSTRY_CATEGORY_CODE VARCHAR(10);
    DECLARE v_CODE_DESCRIPTION VARCHAR(255);
    DECLARE v_TYPE_DESCRIPTION VARCHAR(255);
    DECLARE v_INDUSTRY_CATEGORY_TYPE_CODE VARCHAR(10);
    CREATE TEMPORARY TABLE TempIndustryCategory (
        INDUSTRY_CATEGORY_ID INT PRIMARY KEY
    );
    SET total = JSON_LENGTH(AV_JSON_DATA);
    WHILE i < total DO
        SET v_INDUSTRY_CATEGORY_CODE = JSON_UNQUOTE(JSON_EXTRACT(AV_JSON_DATA, CONCAT('$[', i, '].code')));
        SET v_CODE_DESCRIPTION = JSON_UNQUOTE(JSON_EXTRACT(AV_JSON_DATA, CONCAT('$[', i, '].description')));
        SET v_TYPE_DESCRIPTION = JSON_UNQUOTE(JSON_EXTRACT(AV_JSON_DATA, CONCAT('$[', i, '].typeDescription')));
        SET v_INDUSTRY_CATEGORY_TYPE_CODE = JSON_UNQUOTE(JSON_EXTRACT(AV_JSON_DATA, CONCAT('$[', i, '].typeDnBCode')));
        SELECT INDUSTRY_CATEGORY_ID
        INTO v_INDUSTRY_CATEGORY_ID
        FROM industry_category_code
        WHERE INDUSTRY_CATEGORY_TYPE_CODE = v_INDUSTRY_CATEGORY_TYPE_CODE
        AND INDUSTRY_CATEGORY_CODE = v_INDUSTRY_CATEGORY_CODE;
        IF v_INDUSTRY_CATEGORY_ID IS NOT NULL THEN
            INSERT IGNORE INTO TempIndustryCategory VALUES (v_INDUSTRY_CATEGORY_ID);
            IF NOT EXISTS (
                SELECT 1
                FROM entity_industry_classification
                WHERE ENTITY_ID = AV_ENTITY_ID
                  AND INDUSTRY_CATEGORY_ID = v_INDUSTRY_CATEGORY_ID
            ) THEN
                INSERT INTO entity_industry_classification (ENTITY_ID, INDUSTRY_CATEGORY_ID, IS_PRIMARY, UPDATED_BY, UPDATE_TIMESTAMP)
                VALUES (AV_ENTITY_ID, v_INDUSTRY_CATEGORY_ID, 'N', AV_PERSON_ID, NOW());
            END IF;
        ELSE
            IF NOT EXISTS (
                SELECT 1
                FROM industry_category_type
                WHERE INDUSTRY_CATEGORY_TYPE_CODE = v_INDUSTRY_CATEGORY_TYPE_CODE
            ) THEN
                INSERT INTO industry_category_type (INDUSTRY_CATEGORY_TYPE_CODE, IS_PRIMARY, DESCRIPTION, IS_ACTIVE, UPDATED_BY, UPDATE_TIMESTAMP)
                VALUES (v_INDUSTRY_CATEGORY_TYPE_CODE, 'N', v_TYPE_DESCRIPTION, 'Y', AV_PERSON_ID, NOW());
            END IF;
            INSERT INTO industry_category_code (INDUSTRY_CATEGORY_CODE, INDUSTRY_CATEGORY_TYPE_CODE, DESCRIPTION, IS_ACTIVE, UPDATED_BY, UPDATE_TIMESTAMP)
            VALUES (v_INDUSTRY_CATEGORY_CODE, v_INDUSTRY_CATEGORY_TYPE_CODE, v_CODE_DESCRIPTION, 'Y', AV_PERSON_ID, NOW());
            SET v_INDUSTRY_CATEGORY_ID = LAST_INSERT_ID();
            INSERT IGNORE INTO TempIndustryCategory VALUES (v_INDUSTRY_CATEGORY_ID);
            INSERT INTO entity_industry_classification (ENTITY_ID, INDUSTRY_CATEGORY_ID, IS_PRIMARY, UPDATED_BY, UPDATE_TIMESTAMP)
            VALUES (AV_ENTITY_ID, v_INDUSTRY_CATEGORY_ID, 'N', AV_PERSON_ID, NOW());
        END IF;
        SET i = i + 1;
    END WHILE;
    DELETE FROM entity_industry_classification
    WHERE ENTITY_ID = AV_ENTITY_ID
    AND INDUSTRY_CATEGORY_ID NOT IN (
        SELECT INDUSTRY_CATEGORY_ID FROM TempIndustryCategory
    )
    AND INDUSTRY_CATEGORY_ID NOT IN (
        SELECT INDUSTRY_CATEGORY_ID FROM industry_category_code WHERE INDUSTRY_CATEGORY_CODE IS NULL
    );
    DROP TEMPORARY TABLE TempIndustryCategory;
END
$$
DELIMITER ;
