DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `ENRICH_ENTITY_MAILING_ADDRESS`(
    IN AV_ENTITY_ID INT,
    IN AV_COUNTRY_CODE VARCHAR(3),
    IN AV_CITY VARCHAR(200),
    IN AV_STATE VARCHAR(200),
    IN AV_POSTAL_CODE VARCHAR(20),
    IN AV_ADDRESS_LINE_1 VARCHAR(500),
    IN AV_ADDRESS_LINE_2 VARCHAR(500),
    IN AV_PERSON_ID VARCHAR(40)
)
    DETERMINISTIC
BEGIN
    DECLARE LS_COUNTRY_CODE VARCHAR(3);
    SELECT COUNTRY_CODE INTO LS_COUNTRY_CODE
		FROM country
		WHERE COUNTRY_CODE_ISO2 = AV_COUNTRY_CODE;
    IF NOT EXISTS (
        SELECT 1
        FROM ENTITY_MAILING_ADDRESS
        WHERE ENTITY_ID = AV_ENTITY_ID
        AND ADDRESS_TYPE_CODE=2
    ) THEN
        INSERT INTO ENTITY_MAILING_ADDRESS
        (ENTITY_ID, ADDRESS_TYPE_CODE, ADDRESS_LINE_1, ADDRESS_LINE_2, CITY, STATE, POST_CODE, COUNTRY_CODE, UPDATE_TIMESTAMP, UPDATED_BY)
        VALUES(AV_ENTITY_ID, 2, AV_ADDRESS_LINE_1, AV_ADDRESS_LINE_2, AV_CITY, AV_STATE, AV_POSTAL_CODE, LS_COUNTRY_CODE, now(), AV_PERSON_ID);
	ELSE
		UPDATE ENTITY_MAILING_ADDRESS
        SET ADDRESS_LINE_1=AV_ADDRESS_LINE_1, ADDRESS_LINE_2=AV_ADDRESS_LINE_2, CITY=AV_CITY, STATE=AV_STATE, POST_CODE=AV_POSTAL_CODE,
        COUNTRY_CODE=LS_COUNTRY_CODE, UPDATE_TIMESTAMP=now(), UPDATED_BY=AV_PERSON_ID
        WHERE ENTITY_ID=AV_ENTITY_ID AND ADDRESS_TYPE_CODE=2;
    END IF;
END
$$
DELIMITER ;
