DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FIBI_COI_AWD_PER_IS_DISCL_REQ`(
  AV_PROJECT_NUMBER VARCHAR(50),
  AV_PERSON_ID VARCHAR(50)
) RETURNS varchar(20) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
  DECLARE LI_COUNT INT DEFAULT 0;
  DECLARE LS_PERSON_ROLE_CODE VARCHAR(12) DEFAULT NULL;
  IF AV_PERSON_ID IS NULL THEN
    RETURN 'NOT_REQUIRED';
  END IF;
  SELECT T2.PERSON_ROLE_ID
  INTO LS_PERSON_ROLE_CODE
  FROM AWARD T1
  INNER JOIN AWARD_PERSONS T2
    ON T2.AWARD_ID = T1.AWARD_ID
  WHERE T1.AWARD_NUMBER = AV_PROJECT_NUMBER
    AND T1.AWARD_SEQUENCE_STATUS = 'ACTIVE'
    AND T2.PERSON_ID = AV_PERSON_ID
    AND T2.SEQUENCE_NUMBER = (
      SELECT MAX(AP.SEQUENCE_NUMBER)
      FROM AWARD_PERSONS AP
      WHERE AP.AWARD_ID = T2.AWARD_ID
        AND AP.PERSON_ID = AV_PERSON_ID
    )
  LIMIT 1;
  SELECT COUNT(A.AWARD_ID)
  INTO LI_COUNT
  FROM AWARD A
  LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS S
    ON A.SPONSOR_CODE = S.SPONSOR_CODE
    OR A.PRIME_SPONSOR_CODE = S.SPONSOR_CODE
  WHERE A.AWARD_NUMBER = AV_PROJECT_NUMBER
    AND A.AWARD_SEQUENCE_STATUS = 'ACTIVE'
    AND S.KEY_PERSON_DISCL_REQUIREMENT = 'ALL';
  IF LI_COUNT > 0 THEN
    RETURN 'REQUIRED';
  END IF;
  SELECT COUNT(A.AWARD_ID)
  INTO LI_COUNT
  FROM AWARD A
  LEFT JOIN SPONSOR_DISCLOSURE_REQUIREMENTS S
    ON A.SPONSOR_CODE = S.SPONSOR_CODE
    OR A.PRIME_SPONSOR_CODE = S.SPONSOR_CODE
  WHERE A.AWARD_NUMBER = AV_PROJECT_NUMBER
    AND A.AWARD_SEQUENCE_STATUS = 'ACTIVE'
    AND S.KEY_PERSON_DISCL_REQUIREMENT = 'PI-COI';
  IF LI_COUNT > 0 AND LS_PERSON_ROLE_CODE IN ('1','6','3','4') THEN
    RETURN 'REQUIRED';
  END IF;
  RETURN 'NOT_REQUIRED';
END
$$
DELIMITER ;
