DELIMITER $$
CREATE  FUNCTION `FN_CHK_IP_LINKED`(
AV_PROPOSAL_ID   int(10)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_AWARD_NUMBER int;
SELECT COUNT(1) INTO  LI_AWARD_NUMBER FROM EPS_PROPOSAL WHERE PROPOSAL_ID = AV_PROPOSAL_ID AND BASE_PROPOSAL_NUMBER IS NOT NULL;
IF LI_AWARD_NUMBER = 1 THEN
   RETURN 'TRUE';
END IF;
RETURN 'FALSE';
END
$$
DELIMITER ;
