DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_CHK_PROPOSAL_BUDGET_DATE`(
AV_PROPOSAL_ID INT(10)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LS_PROPOSAL_START_DATE datetime;
DECLARE LS_PROPOSAL_END_DATE datetime;
DECLARE LS_BUDGET_START_DATE datetime;
DECLARE LS_BUDGET_END_DATE datetime;
SELECT START_DATE, END_DATE
INTO LS_PROPOSAL_START_DATE, LS_PROPOSAL_END_DATE
FROM EPS_PROPOSAL
WHERE PROPOSAL_ID = AV_PROPOSAL_ID;
SELECT START_DATE, END_DATE
INTO LS_BUDGET_START_DATE, LS_BUDGET_END_DATE
FROM BUDGET_HEADER T1
WHERE T1.PROPOSAL_ID = AV_PROPOSAL_ID
AND T1.VERSION_NUMBER = (SELECT MAX(T2.VERSION_NUMBER) FROM BUDGET_HEADER T2
WHERE T1.PROPOSAL_ID = T2.PROPOSAL_ID
);
IF LS_BUDGET_START_DATE >= LS_PROPOSAL_START_DATE and LS_BUDGET_END_DATE <= LS_PROPOSAL_END_DATE THEN
RETURN 'TRUE';
ELSE
RETURN 'FALSE';
END IF;
END
$$
DELIMITER ;
