DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_CHK_FOREIGN_ACT_SP_REVW`(AV_PROPOSAL_ID VARCHAR(20)) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
	SELECT COUNT(1) INTO LI_FLAG FROM EPS_PROPOSAL_SPECIAL_REVIEW
	WHERE SPECIAL_REVIEW_CODE = 16
	AND PROPOSAL_ID = AV_PROPOSAL_ID;
	IF LI_FLAG > 0 THEN
		RETURN 'TRUE';
	END IF;
	RETURN 'FALSE';
END
$$
DELIMITER ;
