DELIMITER $$
CREATE  FUNCTION `FN_CHK_INCMPLTE_ENAGMNT`(
    AV_DISCLOSURE_ID INT,
	AV_PERSON_ID VARCHAR(45)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
	DECLARE LI_SFI_FLAG INT DEFAULT 0;
	DECLARE LS_PARAMETER VARCHAR(20);
	SELECT VALUE INTO LS_PARAMETER FROM PARAMETER WHERE PARAMETER_NAME = 'ENGAGEMENT_FLOW_TYPE';
    IF LS_PARAMETER = 'REL_SUMMARY' OR LS_PARAMETER = 'REL_COMP' THEN
		SELECT COUNT(T2.PERSON_ENTITY_ID)  INTO LI_SFI_FLAG
  		  FROM PERSON_ENTITY T2
            WHERE  T2.IS_FORM_COMPLETED = 'N'  AND T2.PERSON_ID = AV_PERSON_ID AND T2.VERSION_STATUS = 'ACTIVE';
		IF LI_SFI_FLAG > 0 THEN
		RETURN 'TRUE';
		END IF;
    ELSE
    SELECT COUNT(T2.PERSON_ENTITY_ID) INTO LI_SFI_FLAG
  		  FROM COI_DISCL_PROJECT_ENTITY_REL T1
  		  INNER JOIN COI_DISCL_PROJECTS T8 ON T8.COI_DISCL_PROJECTS_ID = T1.COI_DISCL_PROJECTS_ID
            INNER JOIN PERSON_ENTITY T2 ON T2.PERSON_ENTITY_ID = T1.PERSON_ENTITY_ID
            WHERE  T2.IS_FORM_COMPLETED = 'N'  AND T8.DISCLOSURE_ID = AV_DISCLOSURE_ID;
		IF LI_SFI_FLAG > 0 THEN
		RETURN 'TRUE';
		END IF;
	END IF;
RETURN 'FALSE';
END
$$
DELIMITER ;
