DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_CHCK_IS_TERMINAL_STATUS`(
AV_STATUS_CODE          VARCHAR(3)) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
    IF AV_STATUS_CODE NOT IN ('10', '4', '8', '9', '5') THEN
        RETURN 'TRUE';
    ELSE
        RETURN 'FALSE';
    END IF;
END
$$
DELIMITER ;
