DELIMITER $$
CREATE  FUNCTION `FN_CHK_PC_CC_FC`(
AV_AWARD_ID    varchar(6)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE PROFIT_CENTER_CODE VARCHAR(200);
DECLARE FUND_CENTER_CODE VARCHAR(200);
DECLARE COST_CENTER_CODE VARCHAR(200);
DECLARE LI_FLAG INT;
select COUNT(1) INTO LI_FLAG from CUSTOM_DATA where MODULE_ITEM_KEY = AV_AWARD_ID AND ( CUSTOM_DATA_ELEMENTS_ID = 22  OR CUSTOM_DATA_ELEMENTS_ID = 21  OR CUSTOM_DATA_ELEMENTS_ID = 23);
IF LI_FLAG > 0 THEN
	SELECT VALUE INTO PROFIT_CENTER_CODE FROM CUSTOM_DATA WHERE MODULE_ITEM_KEY = AV_AWARD_ID AND MODULE_ITEM_CODE = 1 AND CUSTOM_DATA_ELEMENTS_ID = (
		SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_DATA_ELEMENTS_ID =21 AND IS_LATEST_VERSION ='Y');
	SELECT VALUE INTO FUND_CENTER_CODE FROM CUSTOM_DATA WHERE MODULE_ITEM_KEY = AV_AWARD_ID AND MODULE_ITEM_CODE = 1 AND CUSTOM_DATA_ELEMENTS_ID = (
		SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_DATA_ELEMENTS_ID =22 AND IS_LATEST_VERSION ='Y');
	SELECT VALUE INTO COST_CENTER_CODE FROM CUSTOM_DATA WHERE MODULE_ITEM_KEY = AV_AWARD_ID AND MODULE_ITEM_CODE = 1 AND CUSTOM_DATA_ELEMENTS_ID = (
		SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_DATA_ELEMENTS_ID =23 AND IS_LATEST_VERSION ='Y');
	IF FUND_CENTER_CODE ='' THEN
	   SET FUND_CENTER_CODE = NULL ;
	END IF;
	IF COST_CENTER_CODE ='' THEN
	   SET COST_CENTER_CODE = NULL ;
	END IF;
	SELECT COUNT(1) INTO LI_FLAG FROM AWARD WHERE AWARD_ID = AV_AWARD_ID AND AWARD_DOCUMENT_TYPE_CODE = 1;
	IF LI_FLAG > 0 THEN
		IF ((PROFIT_CENTER_CODE = IFNULL(FUND_CENTER_CODE,PROFIT_CENTER_CODE)) AND (PROFIT_CENTER_CODE = IFNULL(COST_CENTER_CODE,PROFIT_CENTER_CODE))) THEN
			RETURN 'TRUE';
		ELSE
			RETURN 'FALSE';
		END IF;
	ELSE
		RETURN 'TRUE';
	END IF;
	ELSE
			RETURN 'TRUE';
	END IF;
END
$$
DELIMITER ;
