DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_CHK_AWARD_CUSTOM_ELEMENTS`(
AV_AWARD_ID    DECIMAL(22)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT(10);
DECLARE ls_value VARCHAR(4000);
DECLARE LI_FLAG INT;
DECLARE  LI_COUNT INT;
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'STEM/Non-STEM')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'STEM/Non-STEM')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
		SET ls_value = NULL;
END IF;
IF ls_value IS NULL or ls_value = '' THEN
		RETURN 'FALSE';
END IF;
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Display at Acad Profile?')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Display at Acad Profile?')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
	SET ls_value = NULL;
END IF;
IF ls_value IS NULL or ls_value = '' THEN
	RETURN 'FALSE';
END IF;
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'RIE Domain')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'RIE Domain')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
	SET ls_value = NULL;
END IF;
		IF ls_value IS NULL or ls_value = '' THEN
			RETURN 'FALSE';
		END IF;
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Input GST Category')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Input GST Category')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
	SET ls_value = NULL;
END IF;
	IF ls_value IS NULL or ls_value = '' THEN
		RETURN 'FALSE';
	END IF;
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Output GST Category')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Output GST Category')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
	SET ls_value = NULL;
END IF;
IF ls_value IS NULL or ls_value = '' THEN
	RETURN 'FALSE';
END IF;
	SELECT COUNT(1) INTO LI_FLAG FROM CUSTOM_DATA_ELEMENTS
	WHERE COLUMN_LABEL = 'GRANT CODE';
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'GRANT CODE')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'GRANT CODE')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
	SET ls_value = NULL;
END IF;
IF ls_value IS NULL or ls_value = '' OR LENGTH(ls_value)<20 THEN
RETURN 'FALSE';
END IF;
SELECT COUNT(*) INTO LI_COUNT
 FROM CUSTOM_DATA T1
WHERE  T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY =0
AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'FUND CODE')
AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
								WHERE T2.COLUMN_ID = T1.COLUMN_ID
								AND T2.MODULE_ITEM_CODE = 1
								AND T2.MODULE_SUB_ITEM_CODE = 0
								AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
								AND T2.MODULE_SUB_ITEM_KEY =0);
IF LI_COUNT > 0 THEN
		SELECT T1.VALUE INTO ls_value
		 FROM CUSTOM_DATA T1
		WHERE  T1.MODULE_ITEM_CODE = 1
		AND T1.MODULE_SUB_ITEM_CODE = 0
		AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
		AND T1.MODULE_SUB_ITEM_KEY =0
		AND T1.COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'FUND CODE')
		AND T1.COLUMN_VERSION_NUMBER = (SELECT MAX(T2.COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA T2
										WHERE T2.COLUMN_ID = T1.COLUMN_ID
										AND T2.MODULE_ITEM_CODE = 1
										AND T2.MODULE_SUB_ITEM_CODE = 0
										AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
										AND T2.MODULE_SUB_ITEM_KEY =0);
ELSE
	SET ls_value = NULL;
END IF;
IF ls_value IS NULL or ls_value = '' THEN
	RETURN 'FALSE';
END IF;
	RETURN 'TRUE';
END
$$
DELIMITER ;
