DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_FOR_ALL_NEGOTIATION`(
AV_NEGOTIATION_ID decimal(22,0)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
   RETURN 'TRUE';
END
$$
DELIMITER ;
