DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_PRIME_SPONSOR_NULL`(
AV_PROPOSAL_ID   int(10)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_PRIME_SPONSOR_CODE int;
SELECT COUNT(1) INTO  LI_PRIME_SPONSOR_CODE FROM EPS_PROPOSAL WHERE PROPOSAL_ID = AV_PROPOSAL_ID AND PRIME_SPONSOR_CODE IS NOT NULL;
IF LI_PRIME_SPONSOR_CODE = 1 THEN
   RETURN 'TRUE';
END IF;
RETURN 'FALSE';
END
$$
DELIMITER ;
