DELIMITER $$
CREATE DEFINER=`fibi`@`%` FUNCTION `FN_VARIATION_TYPE_INTRAVOTE`(
AV_AWARD_ID INT
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG 					INT;
DECLARE LS_BUDGET_CATEGORY_CODE  	VARCHAR(3);
DECLARE LI_PREV_BUDGET_HEADER_ID 	INT(12);
DECLARE LI_PREV_COST				DECIMAL(13,2);
DECLARE LI_CUR_COST					DECIMAL(13,2);
DECLARE LI_CUR_BUDGET_HEADER_ID 	INT(12);
	SELECT COUNT(1) INTO LI_FLAG FROM AWARD T1
	WHERE T1.AWARD_ID = AV_AWARD_ID
	AND T1.AWARD_VARIATION_TYPE_CODE = 9
    AND T1.AWARD_DOCUMENT_TYPE_CODE = 3;
	IF LI_FLAG > 0 THEN
        SELECT BUDGET_HEADER_ID INTO LI_PREV_BUDGET_HEADER_ID
		FROM AWARD_BUDGET_HEADER T3
        WHERE T3.AWARD_ID = AV_AWARD_ID
		AND T3.VERSION_NUMBER IN (SELECT MIN(t2.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER T2
								  where t3.award_id = t2.award_id);
		SELECT BUDGET_HEADER_ID INTO LI_CUR_BUDGET_HEADER_ID
		FROM AWARD_BUDGET_HEADER T3
        WHERE T3.AWARD_ID = AV_AWARD_ID
		AND T3.VERSION_NUMBER IN (SELECT MAX(t2.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER T2
									where t3.award_id = t2.award_id);
		BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL CURSOR FOR
		SELECT BUDGET_CATEGORY_CODE,IFNULL(SUM(LINE_ITEM_COST),0) AS PREVIOUS_COST
		FROM AWARD_BUDGET_DETAIL
		WHERE BUDGET_HEADER_ID = LI_PREV_BUDGET_HEADER_ID
		GROUP BY BUDGET_CATEGORY_CODE;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL;
		INSERT_LOOP1: LOOP
		FETCH CUR_SEL INTO
		LS_BUDGET_CATEGORY_CODE,
		LI_PREV_COST;
		IF DONE1 THEN
			LEAVE INSERT_LOOP1;
		END IF;
			SELECT IFNULL(SUM(LINE_ITEM_COST),0)
			INTO LI_CUR_COST
			FROM AWARD_BUDGET_DETAIL
			WHERE BUDGET_HEADER_ID = LI_CUR_BUDGET_HEADER_ID
			AND BUDGET_CATEGORY_CODE = LS_BUDGET_CATEGORY_CODE
			GROUP BY BUDGET_CATEGORY_CODE;
			IF LI_CUR_COST <> LI_PREV_COST THEN
				RETURN 'FALSE';
			END IF;
		END LOOP;
		CLOSE CUR_SEL;
		END;
    END IF;
RETURN 'TRUE';
END
$$
DELIMITER ;
