DELIMITER $$
CREATE  PROCEDURE `GET_COI_OPA_DASHBOARD`(
	AV_PERSON_ID                    VARCHAR(60),
	AV_FILTER_TYPE					VARCHAR(10),
    AV_IS_COUNT                    	BOOLEAN,
    AV_SORT_TYPE                    VARCHAR(500),
    AV_PAGED                        INT,
    AV_LIMIT                        INT,
    AV_TAB_TYPE                     VARCHAR(30),
    AV_DISCLOSURE_STATUS_CODES      VARCHAR(30),
    AV_DISPOSITION_STATUS_CODES     VARCHAR(30),
    AV_SUBMISSION_TIMESTAMP         VARCHAR(30),
    AV_UNIT_NUMBER                  VARCHAR(8),
    AV_FETCH_ALL_RECORDS            BOOLEAN,
    AV_SEARCH_PERSON_ID             VARCHAR(60),
    AV_ENTITY_ID                    VARCHAR(60),
    AV_IS_FACULTY                   VARCHAR(10),
    AV_PERIOD_START_DATE            VARCHAR(30),
    AV_PERIOD_END_DATE              VARCHAR(30),
    AV_EXPIRATION_DATE				VARCHAR(30),
    AV_ADMIN_PERSON_ID				VARCHAR(1200),
    AV_ENTITY_NAME					VARCHAR(500),
    AV_OPA_DISCLOSURE_TYPES			VARCHAR(40)
)
BEGIN
	DECLARE LS_DYN_SQL 					LONGTEXT;
	DECLARE LS_FILTER_CONDITION 		LONGTEXT;
    DECLARE OPA_SELECTED_FIELDS 	    LONGTEXT;
    DECLARE OPA_JOINS               	LONGTEXT;
    DECLARE LI_OFFSET 			        INT;
    DECLARE LS_OFFSET_CONDITION         VARCHAR(600);
	SET LS_DYN_SQL ='';
    SET OPA_SELECTED_FIELDS = '';
    SET OPA_JOINS = '';
    SET LI_OFFSET = (AV_LIMIT * AV_PAGED);
    SET LS_OFFSET_CONDITION = '';
    SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP AS ( SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MANAGE_OPA_DISCLOSURE'', ''VIEW_OPA_DISCLOSURE'')
							UNION SELECT T1.UNIT_NUMBER FROM PERSON_ROLES T1
                            INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
							WHERE T2.MODULE_CODE=23 AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							UNION SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
							WHERE UNIT_NUMBER IN ( SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MANAGE_OPA_DISCLOSURE'', ''VIEW_OPA_DISCLOSURE'')
                            )),
							ACCESS_PRIVATE_COMMENT AS (SELECT UNIT_NUMBER
												FROM PERSON_ROLES T1
												INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
												INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
												WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
												AND T3.RIGHT_NAME IN (''VIEW_OPA_PRIVATE_COMMENTS'',''MAINTAIN_OPA_PRIVATE_COMMENTS'')
												UNION
												SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
												WHERE UNIT_NUMBER IN (SELECT UNIT_NUMBER
																		FROM PERSON_ROLES T1
																		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
																		INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
																		WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
																		AND T3.RIGHT_NAME IN (''VIEW_OPA_PRIVATE_COMMENTS'',''MAINTAIN_OPA_PRIVATE_COMMENTS''))),
							COMMENTS AS (SELECT COUNT(COMMENT_ID) AS COMMENT_COUNT, MODULE_ITEM_KEY
										FROM DISCL_COMMENT DC
										WHERE DC.MODULE_CODE = 23
										AND DC.COMPONENT_TYPE_CODE IN (''3'',''4'',''5'',''6'',''8'',''9'',''2'',''10'',''11'',''12'',''13'',''14'')
										AND DC.PARENT_COMMENT_ID IS NULL
										AND (EXISTS (SELECT 1 FROM ACCESS_PRIVATE_COMMENT)
											OR (DC.IS_PRIVATE = ''N''
												  OR (DC.IS_PRIVATE = ''Y'' AND DC.COMMENT_BY_PERSON_ID = ''',AV_PERSON_ID,''') OR DC.MODULE_ITEM_KEY IN (
															SELECT OPA_DISCLOSURE_ID
															FROM OPA_REVIEW CR
															WHERE CR.ASSIGNEE_PERSON_ID = ''',AV_PERSON_ID,'''
														)
											  )) GROUP BY MODULE_ITEM_KEY)');
IF AV_TAB_TYPE = 'ALL_REVIEWS' THEN
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ', RW_ACCESS_TMP AS (SELECT T1.UNIT_NUMBER FROM PERSON_ROLES T1
                            INNER JOIN ADMIN_GROUP T2 ON T2.ROLE_ID = T1.ROLE_ID
							WHERE T2.MODULE_CODE=23 AND T1.PERSON_ID = ''',AV_PERSON_ID,''') ' );
END IF;
    IF AV_TAB_TYPE = 'MY_DASHBOARD' THEN
        SET LS_FILTER_CONDITION = CONCAT(' T1.PERSON_ID = ''', AV_PERSON_ID,'''');
    ELSEIF AV_TAB_TYPE = 'NEW_SUBMISSIONS' THEN
        SET LS_FILTER_CONDITION = CONCAT(' T1.REVIEW_STATUS_CODE = 2
				AND T1.ADMIN_GROUP_ID IS NULL AND T1.ADMIN_PERSON_ID IS NULL ');
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND (T1.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) )');
    ELSEIF AV_TAB_TYPE = 'MY_REVIEWS' THEN
        SET LS_FILTER_CONDITION = CONCAT(' T1.REVIEW_STATUS_CODE IN (3,7,8,9) AND ((T8.ASSIGNEE_PERSON_ID = ''', AV_PERSON_ID ,'''
                    AND T8.REVIEW_STATUS_TYPE_CODE IN (1,2))
                    OR (T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,''')
                    OR exists  (SELECT 1 FROM WORKFLOW WF
                        INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                        WHERE WF.MODULE_ITEM_ID = T1.OPA_DISCLOSURE_ID
                        AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND WF.MODULE_CODE = 23 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                        AND WFD.APPROVAL_STATUS = ''W'' )) ');
    ELSEIF AV_TAB_TYPE = 'ALL_REVIEWS' THEN
      SET LS_FILTER_CONDITION = CONCAT(' (T1.REVIEW_STATUS_CODE IN (4,7,8)AND (''', AV_PERSON_ID ,''' IN (SELECT T8.ASSIGNEE_PERSON_ID WHERE T8.REVIEW_STATUS_TYPE_CODE = 3)))
                                OR ( T1.REVIEW_STATUS_CODE = 9 AND exists  (SELECT 1 FROM WORKFLOW WF
                                INNER JOIN WORKFLOW_DETAIL WFD ON WF.WORKFLOW_ID = WFD.WORKFLOW_ID
                                WHERE WF.MODULE_ITEM_ID = T1.OPA_DISCLOSURE_ID
                                AND WFD.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                                AND WF.MODULE_CODE = 23 AND WF.IS_WORKFLOW_ACTIVE = ''Y''
                                AND WFD.APPROVAL_STATUS = ''W'' ))
                                OR (T1.REVIEW_STATUS_CODE = 9 AND T1.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP))
                                OR(T1.REVIEW_STATUS_CODE IN (3,7,8,9) AND (T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,'''
                                OR (T1.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM RW_ACCESS_TMP))))');
    ELSEIF AV_TAB_TYPE = 'ALL_DISCLOSURES' THEN
		SET LS_FILTER_CONDITION = CONCAT('(T1.HOME_UNIT IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID ,''')  ');
    END IF;
    IF AV_DISPOSITION_STATUS_CODES IS NOT NULL  AND AV_DISPOSITION_STATUS_CODES <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.DISPOSITION_STATUS_CODE IN (',AV_DISPOSITION_STATUS_CODES,') ');
	END IF;
    IF AV_DISCLOSURE_STATUS_CODES IS NOT NULL  AND AV_DISCLOSURE_STATUS_CODES <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.REVIEW_STATUS_CODE IN (',AV_DISCLOSURE_STATUS_CODES,') ');
	END IF;
    IF AV_UNIT_NUMBER IS NOT NULL AND AV_UNIT_NUMBER <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.HOME_UNIT = ''',AV_UNIT_NUMBER,''' ');
    END IF;
    IF AV_SUBMISSION_TIMESTAMP IS NOT NULL AND AV_SUBMISSION_TIMESTAMP <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.SUBMISSION_TIMESTAMP) = ''', STR_TO_DATE(AV_SUBMISSION_TIMESTAMP,'%Y-%m-%d'),''' ');
	END IF;
    IF AV_SEARCH_PERSON_ID IS NOT NULL AND AV_SEARCH_PERSON_ID <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.PERSON_ID = ''',AV_SEARCH_PERSON_ID,''' ');
    END IF;
    IF AV_ENTITY_ID IS NOT NULL AND AV_ENTITY_ID <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T11.ENTITY_ID = ''',AV_ENTITY_ID,''' ');
    END IF;
    IF AV_IS_FACULTY IS NOT NULL AND AV_IS_FACULTY <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.IS_FACULTY IN (', AV_IS_FACULTY, ') ');
    END IF;
    IF AV_PERIOD_START_DATE IS NOT NULL AND AV_PERIOD_START_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T2.PERIOD_START_DATE >= ''',AV_PERIOD_START_DATE,''' ');
    END IF;
    IF AV_PERIOD_END_DATE IS NOT NULL AND AV_PERIOD_END_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T2.PERIOD_END_DATE <= ''',AV_PERIOD_END_DATE,''' ');
    END IF;
    IF AV_EXPIRATION_DATE IS NOT NULL AND AV_EXPIRATION_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.EXPIRATION_DATE) = ''',AV_EXPIRATION_DATE,''' ');
    END IF;
    IF AV_ADMIN_PERSON_ID IS NOT NULL AND AV_ADMIN_PERSON_ID <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND FIND_IN_SET(T1.ADMIN_PERSON_ID, ''',AV_ADMIN_PERSON_ID,''') ');
    END IF;
    IF AV_ENTITY_NAME IS NOT NULL AND AV_ENTITY_NAME <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T18.PRIMARY_NAME = ''',AV_ENTITY_NAME,''' ');
    END IF;
    IF AV_OPA_DISCLOSURE_TYPES IS NOT NULL AND AV_OPA_DISCLOSURE_TYPES <> '' THEN
		IF AV_OPA_DISCLOSURE_TYPES = 'INITIAL' THEN
			SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.VERSION_NUMBER = 1 ');
		END IF;
		IF AV_OPA_DISCLOSURE_TYPES = 'REVISION' THEN
			SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.VERSION_NUMBER > 1 ');
		END IF;
    END IF;
    IF AV_IS_COUNT THEN
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' SELECT COUNT(*) FROM ( SELECT DISTINCT ');
        SET OPA_SELECTED_FIELDS = CONCAT(' T1.OPA_DISCLOSURE_ID ');
    ELSE
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' SELECT * FROM ( SELECT DISTINCT ');
        SET OPA_SELECTED_FIELDS= CONCAT('T1.OPA_DISCLOSURE_ID, T1.OPA_DISCLOSURE_NUMBER, T1.OPA_CYCLE_NUMBER,
            T2.PERIOD_START_DATE, T2.PERIOD_END_DATE, T2.OPA_CYCLE_STATUS, T2.OPEN_DATE, T2.CLOSE_DATE,
            T16.FULL_NAME AS PERSON_NAME, T1.PERSON_ID, T1.HOME_UNIT AS UNIT_NUMBER, T3.UNIT_NAME, T1.IS_FACULTY, T1.IS_FALL_SABATICAL,
            T1.IS_SPRING_SABATICAL, T1.RECEIVED_SUMMER_COMP, T1.SUMMER_COMP_MONTHS, T1.HAS_POTENTIAL_CONFLICT,
            T1.CONFLICT_DESCRIPTION, T1.CREATE_TIMESTAMP, T1.CREATE_USER, T1.SUBMISSION_TIMESTAMP, T1.UPDATE_TIMESTAMP,
            T1.UPDATED_BY, T5.FULL_NAME AS UPDATE_USER_FULL_NAME , T1.DISPOSITION_STATUS_CODE, T1.REVIEW_STATUS_CODE,
            T6.DESCRIPTION AS OPA_DISCLOSURE_STATUS, T7.DESCRIPTION AS DISPOSITION_STATUS, T9.FULL_NAME AS ADMIN_FULL_NAME,
            T10.ADMIN_GROUP_NAME, GROUP_CONCAT(DISTINCT
            CASE    WHEN T8.ASSIGNEE_PERSON_ID IS NULL THEN CONCAT(T15.DESCRIPTION, " : ", "null", " : ",T14.DESCRIPTION, " : ",T14.REVIEW_STATUS_CODE)
					ELSE CONCAT(T15.DESCRIPTION, " : ", T13.FULL_NAME, " : ", T14.DESCRIPTION, " : ",T14.REVIEW_STATUS_CODE)
					END
			SEPARATOR ";") AS REVIEWERS, T1.VERSION_NUMBER, T1.VERSION_STATUS, T1.EXPIRATION_DATE, IFNULL(T19.COMMENT_COUNT, 0) AS DISCLOSURE_COMMENT_COUNT ');
        IF NOT AV_FETCH_ALL_RECORDS THEN
			SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LI_OFFSET);
        END IF;
    END IF;
    SET OPA_JOINS = CONCAT(' INNER JOIN OPA_CYCLES T2 ON T2.OPA_CYCLE_NUMBER = T1.OPA_CYCLE_NUMBER
        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT
        INNER JOIN PERSON T5 ON T5.PERSON_ID = T1.UPDATED_BY
        INNER JOIN OPA_REVIEW_STATUS_TYPE T6 ON T6.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE
        LEFT JOIN OPA_DISPOSITION_STATUS_TYPE T7 ON T7.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
        LEFT JOIN OPA_REVIEW T8 ON T8.OPA_DISCLOSURE_ID = T1.OPA_DISCLOSURE_ID
        LEFT JOIN PERSON T9 ON T9.PERSON_ID = T1.ADMIN_PERSON_ID
        LEFT JOIN ADMIN_GROUP T10 ON T10.ADMIN_GROUP_ID = T1.ADMIN_GROUP_ID
        LEFT JOIN OPA_DISCL_PERSON_ENTITY T11 ON T11.OPA_DISCLOSURE_ID = T1.OPA_DISCLOSURE_ID
		LEFT JOIN PERSON T13 ON T13.PERSON_ID = T8.ASSIGNEE_PERSON_ID
        LEFT JOIN opa_review_reviewer_status_type T14 ON T14.REVIEW_STATUS_CODE = T8.REVIEW_STATUS_TYPE_CODE
        LEFT JOIN opa_review_location_type T15 ON T15.LOCATION_TYPE_CODE = T8.LOCATION_TYPE_CODE
        LEFT JOIN PERSON T16 ON T16.PERSON_ID = T1.PERSON_ID
        LEFT JOIN OPA_DISCL_PERSON_ENTITY T17 ON T17.OPA_DISCLOSURE_ID = T1.OPA_DISCLOSURE_ID
        LEFT JOIN ENTITY T18 ON T18.ENTITY_ID = T17.ENTITY_ID
        LEFT JOIN COMMENTS T19 ON T19.MODULE_ITEM_KEY = T1.OPA_DISCLOSURE_ID');
    IF AV_IS_COUNT THEN
		SET AV_SORT_TYPE =   '';
    ELSEIF AV_SORT_TYPE IS NULL THEN
        SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
    ELSE
        SET AV_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
    END IF;
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, OPA_SELECTED_FIELDS, ' FROM OPA_DISCLOSURE T1 ',
            OPA_JOINS,  ' WHERE ', LS_FILTER_CONDITION, ' AND T1.VERSION_STATUS IN (''PENDING'',''ACTIVE'')
            GROUP BY T1.OPA_DISCLOSURE_ID ) T ', AV_SORT_TYPE, LS_OFFSET_CONDITION);
    SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
END
$$
DELIMITER ;
