DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `GET_MIG_ENG_ENTITY`(AV_ENG_ID INT)
BEGIN
    DECLARE LS_ENTITY_NAME VARCHAR(60) DEFAULT '';
    SELECT LOWER(TRIM(ENTITY_NAME)) INTO LS_ENTITY_NAME
    FROM LEGACY_COI_ENGAGEMENTS
    WHERE ENGAGEMENT_ID = AV_ENG_ID;
    SELECT
        e.ENTITY_ID,
        e.ENTITY_NUMBER,
        e.PRIMARY_NAME,
        e.PRIMARY_ADDRESS_LINE_1,
        e.PRIMARY_ADDRESS_LINE_2,
        e.CITY,
        e.STATE,
        c.COUNTRY_NAME,
        e.DUNS_NUMBER,
        e.UEI_NUMBER,
        o.ORGANIZATION_ID,
        s.SPONSOR_CODE,
        e.POST_CODE,
        e.CAGE_NUMBER,
        e.WEBSITE_ADDRESS,
        ow.DESCRIPTION AS OWNERSHIP_TYPE,
        b.DESCRIPTION AS BUSINESS_TYPE
    FROM ENTITY e
    INNER JOIN COUNTRY c ON c.COUNTRY_CODE = e.COUNTRY_CODE
    LEFT JOIN ENTITY_SUB_ORG_INFO o ON o.ENTITY_ID = e.ENTITY_ID
    LEFT JOIN ENTITY_SPONSOR_INFO s ON s.ENTITY_ID = e.ENTITY_ID
    LEFT JOIN ENTITY_OWNERSHIP_TYPE ow ON ow.OWNERSHIP_TYPE_CODE = e.ENTITY_OWNERSHIP_TYPE_CODE
    LEFT JOIN ENTITY_BUSINESS_TYPE b ON b.BUSINESS_TYPE_CODE = e.BUSINESS_TYPE_CODE
    WHERE
		LOWER(TRIM(e.PRIMARY_NAME)) = LS_ENTITY_NAME
		AND e.ENTITY_STATUS_TYPE_CODE != '3'
		AND e.VERSION_STATUS NOT IN ('ARCHIVE', 'CANCELLED')
		AND e.DOCUMENT_STATUS_TYPE_CODE NOT IN ('2','3')
	LIMIT 20;
END
$$
DELIMITER ;
