DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `GET_PROP_OVERALL_DISCL_STS`(AV_DISCLOSURE_ID INT)
BEGIN
	DECLARE LS_OVERALL_DISCL_STS VARCHAR(50);
	DECLARE LS_OVERALL_DISCL_RVW_STS VARCHAR(50);
	DECLARE LS_PROPOSAL_NUMBER VARCHAR(45);
	DECLARE LS_PERSON_ID VARCHAR(45);
    SET SQL_SAFE_UPDATES = 0;
	 SELECT MODULE_ITEM_KEY
	    INTO LS_PROPOSAL_NUMBER
	   FROM COI_DISCL_PROJECTS
	   WHERE MODULE_CODE = '3'
	   AND DISCLOSURE_ID = AV_DISCLOSURE_ID;
    UPDATE COI_INT_STAGE_DEV_PROPOSAL_PERSON CPP,
		COI_DISCLOSURE CD
	SET CPP.DISCLOSURE_STATUS =(CASE
								WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
									THEN CASE
											WHEN CD.REVIEW_STATUS_CODE IN (
													2
													,3
													,4
													,7
													,8
													)
												THEN 'DISCLOSURE_COMPLETED'
											ELSE 'DISCLOSURE_PENDING'
											END
								WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'
									THEN 'DISCLOSURE_NOT_REQUIRED'
								ELSE 'DISCLOSURE_TO_BE_DETERMINED'
								END),
			DISCLOSURE_REVIEW_STATUS = (CASE
										WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
											THEN ( SELECT UPPER(DESCRIPTION) FROM COI_REVIEW_STATUS_TYPE WHERE REVIEW_STATUS_CODE = CD.REVIEW_STATUS_CODE)
										WHEN CPP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'
											THEN 'DISCLOSURE_REVIEW_NA'
										ELSE NULL
										END )
	 WHERE CD.DISCLOSURE_ID  IN (SELECT DISCLOSURE_ID
								  FROM COI_DISCL_PROJECTS CDP
								WHERE  CDP.MODULE_CODE = '3'
								  AND CDP.MODULE_ITEM_KEY = LS_PROPOSAL_NUMBER)
	   AND CD.DISPOSITION_STATUS_CODE != '2'
	   AND CPP.KEY_PERSON_ID = CD.PERSON_ID
	   AND CPP.PROPOSAL_NUMBER =  LS_PROPOSAL_NUMBER;
	   SELECT MODULE_ITEM_KEY
	    INTO LS_PROPOSAL_NUMBER
	   FROM COI_DISCL_PROJECTS
	   WHERE MODULE_CODE = '3'
	   AND DISCLOSURE_ID = AV_DISCLOSURE_ID;
	   SELECT PERSON_ID
		 INTO LS_PERSON_ID
	    FROM COI_DISCLOSURE
		WHERE DISCLOSURE_ID = AV_DISCLOSURE_ID;
		SET LS_OVERALL_DISCL_STS := NULL;
	    IF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND (DISCLOSURE_STATUS IS NOT NULL)
		) THEN
			SET LS_OVERALL_DISCL_STS := NULL;
		ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND (DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED')
		) THEN
			 SET LS_OVERALL_DISCL_STS := NULL;
        ELSEIF  EXISTS (
        SELECT 1
        FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
        WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
          AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
		  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_PENDING';
		ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS != 'DISCLOSURE_COMPLETED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			 SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_COMPLETED';
		ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS IN ('DISCLOSURE_NOT_REQUIRED' )
			  AND DISCLOSURE_STATUS IS NOT NULL
		) AND EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS = 'DISCLOSURE_TO_BE_DETERMINED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) AND NOT EXISTS (
				SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
			  AND DISCLOSURE_STATUS IS NOT NULL)
		THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_NOT_REQUIRED';
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_NOT_REQUIRED';
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS != 'DISCLOSURE_TO_BE_DETERMINED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := NULL;
        ELSEIF EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS IN ('DISCLOSURE_NOT_REQUIRED', 'DISCLOSURE_TO_BE_DETERMINED')
			  AND DISCLOSURE_STATUS IS NOT NULL
		) AND EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
			  AND DISCLOSURE_STATUS IS NOT NULL
		) THEN
			SET LS_OVERALL_DISCL_STS := 'DISCLOSURE_COMPLETED';
		END IF;
		SET LS_OVERALL_DISCL_RVW_STS := NULL;
		IF NOT EXISTS (
			SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			)  THEN
				SET LS_OVERALL_DISCL_RVW_STS := NULL;
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			  AND DISCLOSURE_STATUS != 'DISCLOSURE_PENDING'
		) THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_PENDING';
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_REVIEW_NA')
			  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
		) THEN
			IF EXISTS (
				SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS IS NULL
				  AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
				) THEN
			 SET LS_OVERALL_DISCL_RVW_STS := NULL;
			 ELSE
				SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_NA_REVIEW';
			 END IF;
		ELSEIF NOT EXISTS (
				SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
				  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
		   )  THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_NOT_REQUIRED';
		ELSEIF EXISTS (
				SELECT 1
				FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
				WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
				  AND DISCLOSURE_REVIEW_STATUS IN ('WITHDRAWN', 'SUBMITTED', 'PENDING',
											'REVIEW IN PROGRESS', 'REVIEW ASSIGNED', 'RETURNED',
											'ASSIGNED REVIEW COMPLETED')
				   AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			)  THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_PENDING';
		ELSEIF NOT EXISTS (
			SELECT 1
			FROM COI_INT_STAGE_DEV_PROPOSAL_PERSON
			WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER
			  AND DISCLOSURE_REVIEW_STATUS NOT IN ('COMPLETED',
											'DISCLOSURE_REVIEW_NA',
											'DISCLOSURE_NOT_REQUIRED')
			  AND DISCLOSURE_REVIEW_STATUS IS NOT NULL
			 )  THEN
			SET LS_OVERALL_DISCL_RVW_STS := 'DISCLOSURE_COMPLETED';
		END IF;
		UPDATE COI_INT_STAGE_DEV_PROPOSAL
		   SET OVERALL_DISCLOSURE_STATUS = LS_OVERALL_DISCL_STS,
		       OVERALL_DISCL_REVIEW_STATUS = LS_OVERALL_DISCL_RVW_STS
		WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER;
	SET SQL_SAFE_UPDATES = 1;
END
$$
DELIMITER ;
