DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `GET_PROJECTS_BY_DISC_REVIEW_STATUS`(
    AV_DISCLOSURE_ID INT,
    AV_REVIEW_STATUS_CODE INT
)
BEGIN
    WITH ProjectDisclosureDetails AS (
        SELECT
            COALESCE(t5.KEY_PERSON_ID, t6.KEY_PERSON_ID, t10.KEY_PERSON_ID) AS KEY_PERSON_ID,
            t9.MODULE_ITEM_KEY,
            t9.MODULE_CODE,
            t20.DISCLOSURE_ID,
            COALESCE(t5.PROPOSAL_ID, t10.IP_NUMBER, t6.AWARD_NUMBER) AS PROJECT_NUMBER,
            COALESCE(t5.PROPOSAL_TITLE, t10.IP_TITLE, t6.AWARD_TITLE) AS PROJECT_TITLE,
            COALESCE(t5.PROPOSAL_PI, t10.IP_PI, t6.AWARD_PI) AS PRINCIPAL_INVESTIGATOR,
            t14.DESCRIPTION as PROJECT_TYPE,
            COALESCE(t5.LEAD_UNIT_NUMBER, t10.LEAD_UNIT_NUMBER, t6.LEAD_UNIT_NUMBER) AS DEPARTMENT_NUMBER,
            COALESCE(t5.LEAD_UNIT_NAME, t10.LEAD_UNIT_NAME, t6.LEAD_UNIT_NAME) AS DEPARTMENT_NAME,
            COALESCE(t5.OVERALL_DISCLOSURE_STATUS, t6.OVERALL_DISCLOSURE_STATUS) AS PROJECT_SUBMISSION_STATUS,
   COALESCE(t5.OVERALL_DISCL_REVIEW_STATUS, t6.OVERALL_DISCL_REVIEW_STATUS) AS PROJECT_OVERALL_REVIEW_STATUS
        FROM COI_DISCLOSURE t1
        LEFT JOIN COI_DISCL_PROJECTS t9 ON t9.DISCLOSURE_ID = t1.DISCLOSURE_ID
        LEFT JOIN (
            SELECT EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID, KEY_PERSON_ID,TITLE as PROPOSAL_TITLE,PI_NAME as PROPOSAL_PI, LEAD_UNIT_NUMBER, LEAD_UNIT_NAME, OVERALL_DISCLOSURE_STATUS, OVERALL_DISCL_REVIEW_STATUS
            FROM COI_PROJECT_PROPOSAL_V WHERE OVERALL_DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
        ) t5 ON t5.PROPOSAL_ID = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 3
        LEFT JOIN (
            SELECT AWARD_NUMBER, KEY_PERSON_ID, TITLE as AWARD_TITLE, PI_NAME as AWARD_PI, LEAD_UNIT_NUMBER, LEAD_UNIT_NAME, OVERALL_DISCLOSURE_STATUS, OVERALL_DISCL_REVIEW_STATUS
            FROM COI_PROJECT_AWARD_V WHERE OVERALL_DISCLOSURE_STATUS = 'DISCLOSURE_COMPLETED'
        ) t6 ON t6.AWARD_NUMBER = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 1
        LEFT JOIN (
            SELECT PROPOSAL_NUMBER AS IP_NUMBER, KEY_PERSON_ID,TITLE as IP_TITLE, PI_NAME as IP_PI, LEAD_UNIT_NUMBER, LEAD_UNIT_NAME
            FROM COI_PROJECT_INSTITUTE_PROPOSAL_V  WHERE PERSON_STATUS = 'A'
        ) t10 ON t10.IP_NUMBER = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 2
        LEFT JOIN COI_DISCLOSURE t20 ON
            (t20.PERSON_ID = t5.KEY_PERSON_ID OR
             t20.PERSON_ID = t6.KEY_PERSON_ID OR
             t20.PERSON_ID = t10.KEY_PERSON_ID)
            AND (
                (t20.REVIEW_STATUS_CODE = AV_REVIEW_STATUS_CODE) OR
                (AV_REVIEW_STATUS_CODE = 2 AND t20.REVIEW_STATUS_CODE NOT IN (1, 5, 6))
            )
            AND t20.VERSION_STATUS != 'ARCHIVE'
        LEFT JOIN COI_DISCL_PROJECTS t21 ON
            (t21.DISCLOSURE_ID = t20.DISCLOSURE_ID) AND
            ((t5.PROPOSAL_ID = t21.MODULE_ITEM_KEY AND t21.MODULE_CODE = 3) OR
             (t6.AWARD_NUMBER = t21.MODULE_ITEM_KEY AND t21.MODULE_CODE = 1) OR
             (t10.IP_NUMBER = t21.MODULE_ITEM_KEY AND t21.MODULE_CODE = 2))
  LEFT JOIN COI_PROJECT_TYPE t14 ON t14.COI_PROJECT_TYPE_CODE = t9.MODULE_CODE
        WHERE t1.DISCLOSURE_ID = AV_DISCLOSURE_ID
    )
    SELECT distinct
        T1.MODULE_ITEM_KEY,
        T1.MODULE_CODE,
        T1.PROJECT_NUMBER,
        T1.PROJECT_TITLE,
        T1.PROJECT_TYPE,
        T1.PRINCIPAL_INVESTIGATOR,
        T1.DEPARTMENT_NUMBER,
        T1.DEPARTMENT_NAME,
        T1.PROJECT_SUBMISSION_STATUS,
        T1.PROJECT_OVERALL_REVIEW_STATUS
    FROM ProjectDisclosureDetails T1
    WHERE NOT EXISTS (
        SELECT 1
        FROM ProjectDisclosureDetails
        WHERE MODULE_ITEM_KEY = T1.MODULE_ITEM_KEY AND MODULE_CODE = T1.MODULE_CODE AND DISCLOSURE_ID IS NULL
    )
    AND T1.MODULE_CODE = 1
    ORDER BY T1.MODULE_CODE, T1.MODULE_ITEM_KEY, T1.KEY_PERSON_ID;
END
$$
DELIMITER ;
