DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `GET_COI_DISCLOSURE_DASHBOARD`(
	AV_PERSON_ID                    VARCHAR(200),
			AV_SORT_TYPE                    VARCHAR(500),
			AV_PAGED                        INT(10),
			AV_LIMIT                        INT(10),
			AV_TAB_TYPE                     VARCHAR(40),
			AV_UNLIMITED                    BOOLEAN,
			AV_TYPE                         VARCHAR(1),
			AV_FILTER_TYPE					VARCHAR(10),
			AV_SEARCHWORD                   VARCHAR(100)
	)
BEGIN
	DECLARE LS_DYN_SQL 			LONGTEXT;
	DECLARE LS_FILTER_CONDITION LONGTEXT;
	DECLARE LS_OFFSET_CONDITION VARCHAR(600);
	DECLARE LS_OFFSET 			INT(11);
	DECLARE TAB_QUERY 			LONGTEXT;
	DECLARE JOIN_CONDITION 		LONGTEXT;
	DECLARE SELECTED_FIELD_LIST LONGTEXT;
	DECLARE SEARCH_CONDITION    LONGTEXT;
	DECLARE LI_LATE_SUBMISSION_DUE_DAYS   	INT(3);
	SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
	SET LS_FILTER_CONDITION ='';
	SET LS_DYN_SQL ='';
	SET JOIN_CONDITION = '';
	SET SELECTED_FIELD_LIST= '';
	SET TAB_QUERY = '';
	SET SEARCH_CONDITION = '';
	IF AV_TAB_TYPE = 'IN_PROGRESS_DISCLOSURES' THEN
			IF AV_FILTER_TYPE = 'ALL' THEN
					SET TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE IN (1,2,3) AND T1.REVIEW_STATUS_CODE != 4
									AND T1.VERSION_STATUS = ''PENDING'' ');
			ELSEIF AV_FILTER_TYPE = 'FCOI' THEN
					SET TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE IN (1,3) AND T1.REVIEW_STATUS_CODE != 4
									AND T1.VERSION_STATUS = ''PENDING'' ');
			ELSEIF AV_FILTER_TYPE = 'PROJECT' THEN
					SET TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE = 2 AND T1.REVIEW_STATUS_CODE != 4
									AND T1.VERSION_STATUS = ''PENDING'' ');
			END IF;
	ELSEIF AV_TAB_TYPE = 'APPROVED_DISCLOSURES' THEN
			IF AV_FILTER_TYPE = 'ALL' THEN
					SET TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE IN (1,2,3) AND T1.REVIEW_STATUS_CODE = 4
									AND T1.VERSION_STATUS = ''ACTIVE'' ');
			ELSEIF AV_FILTER_TYPE = 'FCOI' THEN
					SET TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE IN (1,3) AND T1.REVIEW_STATUS_CODE = 4
									AND T1.VERSION_STATUS = ''ACTIVE'' ');
			ELSEIF AV_FILTER_TYPE = 'PROJECT' THEN
					SET TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE = 2 AND T1.REVIEW_STATUS_CODE = 4
									AND T1.VERSION_STATUS = ''ACTIVE'' ');
			END IF;
	ELSEIF AV_TAB_TYPE = 'TRAVEL_DISCLOSURES' THEN
			 IF AV_FILTER_TYPE = 'ALL' THEN
				SET TAB_QUERY = CONCAT(' AND T21.VERSION_STATUS IN (''PENDING'',''ACTIVE'') ');
			 END IF;
	ELSEIF AV_TAB_TYPE = 'DISCLOSURE_HISTORY' THEN
					SET TAB_QUERY = CONCAT(' AND T1.VERSION_STATUS = ''ARCHIVE'' ');
	END IF;
					SET JOIN_CONDITION =  CONCAT(JOIN_CONDITION,' LEFT JOIN (SELECT IFNULL(COUNT(DISTINCT T1.PERSON_ENTITY_ID),0) AS NO_OF_SFI,T1.DISCLOSURE_ID
												FROM COI_DISCL_PERSON_ENTITY_REL T1
												GROUP BY T1.DISCLOSURE_ID) T7 ON T7.DISCLOSURE_ID = T1.DISCLOSURE_ID
											LEFT JOIN (SELECT IFNULL(COUNT(DISTINCT T1.MODULE_ITEM_KEY),0) AS NO_OF_PROPOSAL,T1.DISCLOSURE_ID, T2.DESCRIPTION AS COI_PROJECT_TYPE
												FROM COI_DISCL_PROJECTS T1
												INNER JOIN COI_PROJECT_TYPE T2 ON T2.COI_PROJECT_TYPE_CODE = 3
												WHERE MODULE_CODE = 3 GROUP BY T1.DISCLOSURE_ID) T8 ON T8.DISCLOSURE_ID = T1.DISCLOSURE_ID AND T1.FCOI_TYPE_CODE != 2
											LEFT JOIN (SELECT IFNULL(COUNT(DISTINCT T1.MODULE_ITEM_KEY),0) AS NO_OF_AWARD,T1.DISCLOSURE_ID, T2.DESCRIPTION AS COI_PROJECT_TYPE
												FROM COI_DISCL_PROJECTS T1
												INNER JOIN COI_PROJECT_TYPE T2 ON T2.COI_PROJECT_TYPE_CODE = 1
												WHERE MODULE_CODE = 1 GROUP BY T1.DISCLOSURE_ID) T9 ON T9.DISCLOSURE_ID = T1.DISCLOSURE_ID AND T1.FCOI_TYPE_CODE != 2
											LEFT JOIN (SELECT IFNULL(COUNT(DISTINCT T1.MODULE_ITEM_KEY),0) AS NO_OF_IPS,T1.DISCLOSURE_ID, T2.DESCRIPTION AS COI_PROJECT_TYPE
												FROM COI_DISCL_PROJECTS T1
												INNER JOIN COI_PROJECT_TYPE T2 ON T2.COI_PROJECT_TYPE_CODE = 2
												WHERE MODULE_CODE = 2 GROUP BY T1.DISCLOSURE_ID) T60 ON T60.DISCLOSURE_ID = T1.DISCLOSURE_ID AND T1.FCOI_TYPE_CODE != 2
											LEFT JOIN (SELECT EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID, COI_PROJECT_TYPE_CODE,
													  TITLE  AS PROPOSAL_TITLE, EXTERNAL_SYSTEM_REF_ID FROM COI_PROJECT_PROPOSAL_V )T14
													  ON T14.EXTERNAL_SYSTEM_REF_ID = T61.MODULE_ITEM_KEY AND T14.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
											LEFT  JOIN (SELECT AWARD_NUMBER , EXTERNAL_SYSTEM_REF_ID, COI_PROJECT_TYPE_CODE,
													   TITLE AS AWARD_TITLE FROM COI_PROJECT_AWARD_V ) T15
													   ON T15.AWARD_NUMBER = T61.MODULE_ITEM_KEY AND T15.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
											LEFT  JOIN (SELECT PROPOSAL_NUMBER AS IP_NUMBER , EXTERNAL_SYSTEM_REF_ID, COI_PROJECT_TYPE_CODE,
													   TITLE AS IP_TITLE FROM coi_project_institute_proposal_v ) T62
													   ON T62.IP_NUMBER = T61.MODULE_ITEM_KEY  AND T62.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE');
	IF AV_SORT_TYPE IS NULL THEN
			SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
	ELSE
		SET AV_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
	END IF;
	IF AV_UNLIMITED = TRUE THEN
			SET LS_OFFSET_CONDITION = '';
	ELSE
			SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
	END IF;
	IF LS_FILTER_CONDITION <>'' THEN
			SET LS_FILTER_CONDITION = CONCAT(' WHERE ',LS_FILTER_CONDITION);
			SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;
	END IF;
	IF AV_TAB_TYPE = 'CONSULTING_DISCLOSURES' THEN
			IF AV_SEARCHWORD IS NOT NULL THEN
				SET AV_SEARCHWORD = CONCAT('''%',AV_SEARCHWORD, '%''');
				SET SEARCH_CONDITION = CONCAT(' AND (T50.DISCLOSURE_ID LIKE ',AV_SEARCHWORD, ' OR T54.PRIMARY_NAME LIKE ',AV_SEARCHWORD, ' OR
				T51.UNIT_NAME LIKE ', AV_SEARCHWORD, ' OR T51.UNIT_NUMBER LIKE ', AV_SEARCHWORD, ' OR T52.DESCRIPTION LIKE ', AV_SEARCHWORD, '  OR T56.DESCRIPTION LIKE ', AV_SEARCHWORD,
				' OR T58.ADMIN_GROUP_NAME LIKE ', AV_SEARCHWORD,' OR T59.FULL_NAME LIKE ', AV_SEARCHWORD,' )');
			END IF;
			SET LS_DYN_SQL = CONCAT(' SELECT DISTINCT *  FROM(SELECT DISTINCT
								T50.DISCLOSURE_ID,
								T51.UNIT_NUMBER AS UNIT,
								T51.UNIT_NAME,
								T52.REVIEW_STATUS_CODE,
								T52.DESCRIPTION AS REVIEW_STATUS_DESCRIPTION,
								T56.DISPOSITION_STATUS_CODE,
								T56.DESCRIPTION AS DISPOSITION_STATUS_DESCRIPTION,
								T54.PRIMARY_NAME as ENTITY_NAME,
								T54.ENTITY_ID,
								T55.FULL_NAME,
								T55.PERSON_ID,
								T50.CERTIFIED_AT,
								T50.CERTIFIED_BY,
								T50.EXPIRATION_DATE,
								NULL AS IS_EXTENDED,
								T50.UPDATE_TIMESTAMP,
								T50.UPDATED_BY,
								T57.FULL_NAME AS UPDATE_USER_FULL_NAME,
								T58.ADMIN_GROUP_NAME,
								T59.FULL_NAME AS ADMINISTRATOR ' ,SELECTED_FIELD_LIST,'
								FROM CONSULTING_DISCLOSURE T50
								LEFT JOIN PERSON_ENTITY T53 ON T53.PERSON_ENTITY_ID = T50.PERSON_ENTITY_ID
								LEFT JOIN ENTITY T54 on T54.ENTITY_ID = T53.ENTITY_ID
								LEFT JOIN ADMIN_GROUP T58 ON T58.ADMIN_GROUP_ID = T50.ADMIN_GROUP_ID
								LEFT JOIN PERSON T59 ON T59.PERSON_ID = T50.ADMIN_PERSON_ID
								INNER JOIN CONSULTING_DISCL_REVIEW_STATUS_TYPE T52 ON T52.REVIEW_STATUS_CODE = T50.REVIEW_STATUS_CODE
								INNER JOIN UNIT T51 ON T51.UNIT_NUMBER = T50.HOME_UNIT
								INNER JOIN CONSULTING_DISCL_DISPOSITION_STATUS_TYPE T56 ON T56.DISPOSITION_STATUS_CODE = T50.DISPOSITION_STATUS_CODE
								INNER JOIN PERSON T57 ON T57.PERSON_ID = T50.UPDATED_BY
								INNER JOIN PERSON T55 ON T55.PERSON_ID=T50.PERSON_ID WHERE T50.PERSON_ID = ''',AV_PERSON_ID,'''',TAB_QUERY, SEARCH_CONDITION,
											' GROUP BY T50.DISCLOSURE_ID)T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION);
	ELSEIF AV_TAB_TYPE = 'TRAVEL_DISCLOSURES' THEN
			IF AV_SEARCHWORD IS NOT NULL THEN
				SET AV_SEARCHWORD = CONCAT('''%',AV_SEARCHWORD, '%''');
				SET SEARCH_CONDITION = CONCAT(' AND (T21.TRAVEL_DISCLOSURE_ID LIKE ',AV_SEARCHWORD, ' OR T22.PRIMARY_NAME LIKE ',AV_SEARCHWORD, ' OR
				T5.UNIT_NAME LIKE ', AV_SEARCHWORD, ' OR T5.UNIT_NUMBER LIKE ', AV_SEARCHWORD, ' OR T24.DESCRIPTION LIKE ', AV_SEARCHWORD, '  OR T29.RELATIONSHIP_TYPES LIKE ',
				AV_SEARCHWORD, AV_SEARCHWORD,' OR T32.DESCRIPTION LIKE ', AV_SEARCHWORD,' )');
			END IF;
			SELECT VALUE INTO LI_LATE_SUBMISSION_DUE_DAYS  FROM PARAMETER WHERE PARAMETER_NAME = 'TRAVEL_DISCL_SUBMISSION_DUE_DAYS';
			SET LS_DYN_SQL = CONCAT('WITH ACCESS_PRIVATE_COMMENT AS (SELECT 1
												FROM PERSON_ROLES T1
												INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
												INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
												WHERE T1.PERSON_ID = ''',AV_PERSON_ID,'''
												AND T3.RIGHT_NAME IN (''VIEW_OPA_PRIVATE_COMMENTS'',''MAINTAIN_OPA_PRIVATE_COMMENTS'')),
									COMMENTS AS (SELECT COUNT(COMMENT_ID) AS COMMENT_COUNT, MODULE_ITEM_KEY
												FROM DISCL_COMMENT DC
												WHERE DC.MODULE_CODE = 24
												AND DC.COMPONENT_TYPE_CODE IN (''3'',''4'',''5'',''6'',''8'',''9'',''2'',''10'',''11'',''12'',''13'',''14'')
												AND DC.PARENT_COMMENT_ID IS NULL
												AND ( EXISTS (SELECT 1 FROM ACCESS_PRIVATE_COMMENT)
													OR (DC.IS_PRIVATE = ''N''
														  OR (DC.IS_PRIVATE = ''Y'' AND DC.COMMENT_BY_PERSON_ID = ''',AV_PERSON_ID,''')
													  )) GROUP BY MODULE_ITEM_KEY)');
			SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' SELECT DISTINCT *  FROM(SELECT DISTINCT
								T21.TRAVEL_DISCLOSURE_ID,
								T21.TRAVEL_NUMBER,
								T5.UNIT_NUMBER AS UNIT,
								T5.UNIT_NAME,
								T24.REVIEW_STATUS_CODE,
								T24.DESCRIPTION AS REVIEW_STATUS_DESCRIPTION,
								T29.RELATIONSHIP_TYPES AS TRAVELER_TYPE_DESCRIPTION,
								T22.PRIMARY_NAME AS TRAVEL_ENTITY_NAME,
								T22.ENTITY_ID,
								T23.FULL_NAME AS TRAVELLER_NAME,
								T23.PERSON_ID,
								T21.SUBMISSION_DATE,
								T21.EXPIRATION_DATE,
								NULL AS IS_EXTENDED,
								T41.VALUE AS PURPOSE_OF_THE_TRIP,
								T43.VALUE AS TRIP_TITLE,
								T45.VALUE AS TRAVEL_AMOUNT,
								T21.UPDATE_TIMESTAMP,
								T21.VERSION_STATUS,
								T21.CREATE_TIMESTAMP,
								T32.DOCUMENT_STATUS_CODE,
								T32.DESCRIPTION AS DOCUMENT_STATUS_DESCRIPTION,
								T46.DESCRIPTION AS FUNDING_TYPE,
								CASE
									WHEN TIMESTAMPDIFF(DAY, T21.CREATE_TIMESTAMP, T21.CERTIFIED_AT) > ',LI_LATE_SUBMISSION_DUE_DAYS,' THEN true
									ELSE false
								END AS IS_LATE_SUBMISSION,
								T21.CERTIFIED_AT,
								 T47.FULL_NAME AS UPDATE_USER_FULL_NAME,
								T48.MIN_START_DATE AS TRAVEL_START_DATE,
								 T48.MAX_END_DATE AS TRAVEL_END_DATE,
							   T49.TRAVEL_DESTINATIONS,
								T50.FULL_NAME AS ADMIN_PERSON_NAME,
								T51.ADMIN_GROUP_NAME,
								IFNULL(T19.COMMENT_COUNT, 0) AS DISCLOSURE_COMMENT_COUNT ',SELECTED_FIELD_LIST,'
								FROM COI_TRAVEL_DISCLOSURE T21
								LEFT JOIN ENTITY T22 ON T22.ENTITY_ID=T21.ENTITY_ID
								LEFT JOIN COI_TRAVEL_REVIEW_STATUS T24 ON T24.REVIEW_STATUS_CODE=T21.REVIEW_STATUS_CODE
								LEFT JOIN UNIT T5 ON T5.UNIT_NUMBER = T21.HOME_UNIT
								LEFT JOIN(SELECT T21.TRAVEL_DISCLOSURE_ID, GROUP_CONCAT(DISTINCT T25.DESCRIPTION ORDER BY T25.VALID_PERS_ENTITY_REL_TYP_CODE ASC) AS RELATIONSHIP_TYPES FROM COI_TRAVEL_DISCLOSURE T21
									LEFT JOIN COI_TRAVEL_DISCLOSURE_TRAVELER T27 ON T27.TRAVEL_DISCLOSURE_ID = T21.TRAVEL_DISCLOSURE_ID
									LEFT JOIN VALID_PERSON_ENTITY_REL_TYPE T25 ON T25.VALID_PERS_ENTITY_REL_TYP_CODE = T27.VALID_PERS_ENTITY_REL_TYP_CODE
									GROUP BY T21.TRAVEL_DISCLOSURE_ID)T29 ON T29.TRAVEL_DISCLOSURE_ID = T21.TRAVEL_DISCLOSURE_ID
								LEFT JOIN COI_TRAVEL_DOCUMENT_STATUS_TYPE T32 ON T32.DOCUMENT_STATUS_CODE = T21.DOCUMENT_STATUS_CODE
								LEFT JOIN PERSON T23 ON T23.PERSON_ID=T21.PERSON_ID
								LEFT JOIN FB_COMP_CUSTOM_ELEMENT T40 ON T40.CUSTOM_ELEMENT_NAME = "Purpose"
								LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER T41 ON T41.CUSTOM_DATA_ELEMENTS_ID = T40.CUSTOM_DATA_ELEMENTS_ID AND T41.MODULE_ITEM_CODE = 24 AND T41.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID
								LEFT JOIN FB_COMP_CUSTOM_ELEMENT T42 ON T42.CUSTOM_ELEMENT_NAME = "Trip Title"
								LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER T43 ON T43.CUSTOM_DATA_ELEMENTS_ID = T42.CUSTOM_DATA_ELEMENTS_ID AND T43.MODULE_ITEM_CODE = 24 AND T43.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID
								LEFT JOIN FB_COMP_CUSTOM_ELEMENT T44 ON T44.CUSTOM_ELEMENT_NAME = "Reimbursed Cost"
								LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER T45 ON T45.CUSTOM_DATA_ELEMENTS_ID = T44.CUSTOM_DATA_ELEMENTS_ID AND T45.MODULE_ITEM_CODE = 24 AND T45.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID
								LEFT JOIN COI_TRAVEL_FUNDING_TYPE T46 ON T46.FUNDING_TYPE_CODE = T21.FUNDING_TYPE_CODE
								LEFT JOIN PERSON T47 ON T47.PERSON_ID = T21.UPDATED_BY
								LEFT JOIN (SELECT TRAVEL_DISCLOSURE_ID, MIN(STAY_START_DATE) AS MIN_START_DATE, MAX(STAY_END_DATE) AS MAX_END_DATE FROM COI_TRAVEL_DESTINATIONS GROUP BY TRAVEL_DISCLOSURE_ID) T48 ON T48.TRAVEL_DISCLOSURE_ID = T21.TRAVEL_DISCLOSURE_ID
								LEFT JOIN ( SELECT TD.TRAVEL_DISCLOSURE_ID, GROUP_CONCAT(C.COUNTRY_NAME SEPARATOR ''||'') AS TRAVEL_DESTINATIONS FROM COI_TRAVEL_DESTINATIONS TD
								LEFT JOIN COUNTRY C ON C.COUNTRY_CODE = TD.COUNTRY_CODE GROUP BY TD.TRAVEL_DISCLOSURE_ID) T49 ON T49.TRAVEL_DISCLOSURE_ID = T21.TRAVEL_DISCLOSURE_ID
								LEFT JOIN PERSON T50 ON T50.PERSON_ID = T21.ADMIN_PERSON_ID
								LEFT JOIN ADMIN_GROUP T51 ON T51.ADMIN_GROUP_ID = T21.ADMIN_GROUP_ID
								LEFT JOIN COMMENTS T19 ON T19.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID
								WHERE T21.PERSON_ID = ''',AV_PERSON_ID,'''',TAB_QUERY, SEARCH_CONDITION,
								' GROUP BY T21.TRAVEL_DISCLOSURE_ID)T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION);
	ELSE
			IF AV_SEARCHWORD IS NOT NULL THEN
				SET AV_SEARCHWORD = CONCAT('''%',AV_SEARCHWORD, '%''');
				SET SEARCH_CONDITION = CONCAT(' AND (T1.DISCLOSURE_NUMBER LIKE ',AV_SEARCHWORD, ' OR T1.DISCLOSURE_ID LIKE ',AV_SEARCHWORD, ' OR
				T20.UNIT_NAME LIKE ', AV_SEARCHWORD, ' OR T20.UNIT_NUMBER LIKE ', AV_SEARCHWORD, ' OR T61.PROJECT_SNAPSHOT->>''$.PROJECT_TITLE'' LIKE ',AV_SEARCHWORD,
				' OR T14.PROPOSAL_TITLE LIKE ', AV_SEARCHWORD, '  OR T15.AWARD_TITLE LIKE ', AV_SEARCHWORD, 'OR T62.IP_TITLE LIKE ', AV_SEARCHWORD,
				' OR T4.DESCRIPTION LIKE', AV_SEARCHWORD, ' OR T1.VERSION_STATUS LIKE ', AV_SEARCHWORD, ' OR T3.DESCRIPTION LIKE ', AV_SEARCHWORD,
				' OR T2.DESCRIPTION LIKE ', AV_SEARCHWORD, ' )');
			END IF;
			SET LS_DYN_SQL = CONCAT('WITH ACCESS_COMMENT AS (SELECT
										MAX(T3.RIGHT_NAME IN (''VIEW_COI_COMMENTS'',''MAINTAIN_COI_COMMENTS'',''VIEW_COI_PRIVATE_COMMENTS'',''MAINTAIN_COI_PRIVATE_COMMENTS'')) AS HAS_PROJ_COMMENT_ACCESS,
										MAX(T3.RIGHT_NAME IN (''VIEW_COI_PRIVATE_COMMENTS'',''MAINTAIN_COI_PRIVATE_COMMENTS'')) AS HAS_PRIVATE_COMMENT_ACCESS
										FROM PERSON_ROLES T1
										INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
										INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
										WHERE T1.PERSON_ID = ''',AV_PERSON_ID,'''),
									PROJECT_COMMENTS AS (
										SELECT COUNT(CPC.COMMENT_ID) AS COMMENT_COUNT, DP.DISCLOSURE_ID
										FROM COI_PROJECT_COMMENT CPC
										JOIN COI_DISCL_PROJECTS DP ON DP.MODULE_CODE = CPC.MODULE_CODE AND DP.MODULE_ITEM_KEY = CPC.MODULE_ITEM_KEY
										WHERE CPC.COMMENT_TYPE_CODE = 1
										  AND CPC.PARENT_COMMENT_ID IS NULL
										  AND (
											 (SELECT HAS_PROJ_COMMENT_ACCESS FROM ACCESS_COMMENT) = 1
											  OR EXISTS (
												  SELECT 1 FROM COI_DISCLOSURE T1
												  WHERE DP.DISCLOSURE_ID = T1.DISCLOSURE_ID
													AND T1.PERSON_ID = ''',AV_PERSON_ID,''' )
										  )
										GROUP BY DP.DISCLOSURE_ID),
									DISCL_COMMENTS AS (
										SELECT COUNT(COMMENT_ID) AS COMMENT_COUNT, MODULE_ITEM_KEY
										FROM DISCL_COMMENT DC
										WHERE DC.MODULE_CODE = 8
										  AND DC.COMPONENT_TYPE_CODE IN (''2'',''3'',''4'',''5'',''6'',''8'',''9'',''10'',''11'',''12'',''13'',''14'')
										  AND DC.PARENT_COMMENT_ID IS NULL
										  AND (
											  (SELECT HAS_PRIVATE_COMMENT_ACCESS FROM ACCESS_COMMENT) = 1
											  OR (DC.IS_PRIVATE = ''N'' OR (DC.IS_PRIVATE = ''Y'' AND DC.COMMENT_BY_PERSON_ID = ''',AV_PERSON_ID,''')OR DC.MODULE_ITEM_KEY IN (
																	SELECT DISCLOSURE_ID
																	FROM COI_REVIEW CR
																	WHERE CR.ASSIGNEE_PERSON_ID = ''',AV_PERSON_ID,''')
										  ))
										GROUP BY MODULE_ITEM_KEY)
								 ');
			SET LS_DYN_SQL =CONCAT(LS_DYN_SQL, 'SELECT DISTINCT *  FROM(SELECT DISTINCT
											T1.DISCLOSURE_ID,
											T1.DISCLOSURE_NUMBER,
											T1.VERSION_NUMBER,
											T1.PERSON_ID,
											T1.HOME_UNIT AS UNIT,
											T20.UNIT_NAME,
											T20.ORGANIZATION_ID,
											T20.PARENT_UNIT_NUMBER,
											T20.IS_ACTIVE,
											T20.ACRONYM,
											T20.IS_FUNDING_UNIT,
											T1.CONFLICT_STATUS_CODE,
											T2.DESCRIPTION AS DISCLOSURE_STATUS,
											T1.DISPOSITION_STATUS_CODE,
											T3.DESCRIPTION AS DISPOSITION_STATUS,
											T1.FCOI_TYPE_CODE,
											T10.DESCRIPTION AS DISCLOSURE_CATEGORY_TYPE,
											T1.REVIEW_STATUS_CODE,
											T4.DESCRIPTION AS REVIEW_STATUS,
											T1.VERSION_STATUS,
											T1.CERTIFICATION_TEXT,
											T1.CERTIFIED_AT,
											T6.FULL_NAME AS DISCLOSURE_PERSON_FULL_NAME,
											T1.UPDATED_BY,
											T30.FULL_NAME AS UPDATE_USER_FULL_NAME,
											T1.CREATED_BY,
											T1.UPDATE_TIMESTAMP,
											T1.CREATE_TIMESTAMP,
											T1.EXPIRATION_DATE,
											T1.IS_EXTENDED,
											T1.COI_PROJECT_TYPE_CODE,
											JSON_ARRAY(
												IF(T8.DISCLOSURE_ID IS NOT NULL,
													JSON_OBJECT(
														''projectType'', T8.COI_PROJECT_TYPE,
														''projectCount'', T8.NO_OF_PROPOSAL,
														''moduleCode'', 3
													), NULL),
												IF(T9.DISCLOSURE_ID IS NOT NULL,
													JSON_OBJECT(
														''projectType'', T9.COI_PROJECT_TYPE,
														''projectCount'', T9.NO_OF_AWARD,
														''moduleCode'', 1
													), NULL),
												IF(T60.DISCLOSURE_ID IS NOT NULL,
													JSON_OBJECT(
														''projectType'', T60.COI_PROJECT_TYPE,
														''projectCount'', T60.NO_OF_IPS,
														''moduleCode'', 2
													), NULL)
											) AS PROJECT_COUNT,
											CASE WHEN T1.FCOI_TYPE_CODE = 2 AND T61.PROJECT_SNAPSHOT IS NULL THEN
												COALESCE(T14.PROPOSAL_TITLE, T62.IP_TITLE, T15.AWARD_TITLE)
											ELSE
												CASE WHEN T1.FCOI_TYPE_CODE = 2 AND T61.PROJECT_SNAPSHOT IS NOT NULL THEN
													T61.PROJECT_SNAPSHOT->>''$.PROJECT_TITLE''
												ELSE NULL END
											END AS PROJECT_TITLE,
											CASE WHEN T1.FCOI_TYPE_CODE = 2 AND T61.PROJECT_SNAPSHOT IS NULL THEN
												COALESCE(T14.PROPOSAL_ID, T62.IP_NUMBER, T15.AWARD_NUMBER)
											ELSE
												CASE WHEN T1.FCOI_TYPE_CODE = 2 AND T61.PROJECT_SNAPSHOT IS NOT NULL THEN
													T61.PROJECT_SNAPSHOT->>''$.PROJECT_NUMBER''
												ELSE NULL END
											END AS PROJECT_NUMBER,
											T63.BADGE_COLOR,
											T63.PROJECT_ICON,
											T63.DESCRIPTION AS COI_PROJECT_TYPE,
											T7.NO_OF_SFI,
											T1.REVISION_COMMENT,
											T31.ADMIN_GROUP_NAME,
											T40.FULL_NAME AS ADMINISTRATOR,
											(IFNULL(PC.COMMENT_COUNT, 0) + IFNULL(DC.COMMENT_COUNT, 0)) AS DISCLOSURE_COMMENT_COUNT,
                                            IFNULL(T64.DISCLOSURE_ATTACHMENT_COUNT, 0) AS DISCLOSURE_ATTACHMENT_COUNT', SELECTED_FIELD_LIST, '
											FROM COI_DISCLOSURE T1
											LEFT JOIN COI_DISCL_PROJECTS T61 ON T61.DISCLOSURE_ID = T1.DISCLOSURE_ID
											LEFT JOIN COI_PROJECT_TYPE T63 ON T63.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
											LEFT JOIN COI_CONFLICT_STATUS_TYPE T2 ON T2.CONFLICT_STATUS_CODE=T1.CONFLICT_STATUS_CODE
											INNER JOIN COI_DISPOSITION_STATUS_TYPE T3 ON T3.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
											INNER JOIN COI_REVIEW_STATUS_TYPE T4 ON T4.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE
											LEFT JOIN PERSON T6 ON T6.PERSON_ID = T1.PERSON_ID
											LEFT JOIN PERSON T30 ON T30.PERSON_ID = T1.UPDATED_BY
											LEFT JOIN UNIT T20 ON T20.UNIT_NUMBER = T1.HOME_UNIT
											LEFT JOIN ADMIN_GROUP T31 ON T31.ADMIN_GROUP_ID = T1.ADMIN_GROUP_ID
											LEFT JOIN PERSON T40 ON T40.PERSON_ID = T1.ADMIN_PERSON_ID
                                            LEFT JOIN (
												SELECT DISCLOSURE_ID, COUNT(DISTINCT ATTACHMENT_NUMBER) AS DISCLOSURE_ATTACHMENT_COUNT
												FROM DISCL_ATTACHMENT
												GROUP BY DISCLOSURE_ID
											) T64 ON T64.DISCLOSURE_ID = T1.DISCLOSURE_ID
											INNER JOIN COI_DISCLOSURE_FCOI_TYPE T10 ON T10.FCOI_TYPE_CODE = T1.FCOI_TYPE_CODE
											LEFT JOIN PROJECT_COMMENTS PC ON PC.DISCLOSURE_ID = T1.DISCLOSURE_ID
											LEFT JOIN DISCL_COMMENTS DC ON DC.MODULE_ITEM_KEY = T1.DISCLOSURE_ID
											',JOIN_CONDITION,' WHERE T1.PERSON_ID = ''',
											AV_PERSON_ID,'''',' AND T1.DISPOSITION_STATUS_CODE != ''2''', TAB_QUERY,SEARCH_CONDITION,
											' GROUP BY T1.DISCLOSURE_ID)T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE);
	END IF;
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
	END
$$
DELIMITER ;
