DELIMITER $$
CREATE  PROCEDURE `GET_MIG_ENG_DASHBOARD`(
AV_PERSON_ID VARCHAR(40),
AV_TAB 		 VARCHAR(30),
AV_FILTER  	 VARCHAR(1),
AV_COUNT	 BOOLEAN,
AV_PAGED 	 INT,
AV_LIMIT	 INT)
BEGIN
DECLARE LS_FILTER_CONDITION TEXT DEFAULT '';
DECLARE LS_DYN_SQL 			LONGTEXT;
DECLARE LS_OFFSET 			INT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600) DEFAULT '';
IF AV_PAGED IS NOT NULL AND AV_PAGED <> '' THEN
	SET LS_OFFSET = (AV_LIMIT * (AV_PAGED - 1));
	SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ', AV_LIMIT, ' OFFSET ',LS_OFFSET);
END IF;
IF AV_FILTER IS NOT NULL OR AV_FILTER <> '' THEN
	IF AV_FILTER = 'F' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.IS_FINANCIAL = ''Y''');
	END IF;
	IF AV_FILTER = 'T' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.IS_TRAVEL = ''Y'' AND T1.IS_FINANCIAL = ''N''');
	END IF;
END IF;
IF AV_TAB = 'COMPLETED' THEN
	SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND MIGRATION_STATUS = 1');
END IF;
IF AV_TAB = 'EXCLUDED' THEN
	SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND MIGRATION_STATUS = 2');
END IF;
IF AV_TAB = 'TO REVIEW' OR AV_TAB IS NULL OR AV_TAB = '' THEN
	SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND MIGRATION_STATUS = 3');
END IF;
SET LS_DYN_SQL = CONCAT('SELECT
						T1.ENGAGEMENT_ID,
						T1.ENTITY_NAME AS ENTITY_NAME,
                        CASE WHEN T1.IS_TRAVEL = ''N'' AND T1.IS_FINANCIAL = ''Y'' THEN ''Financial''
							WHEN T1.IS_TRAVEL = ''Y'' AND T1.IS_FINANCIAL = ''N'' THEN ''Travel''
							ELSE ''Financial and Travel''
                        END AS RELATIONSHIP_TYPE,
						NULLIF(T2.DESCRIPTION,'''') AS ENTITY_TYPE,
                        CASE WHEN T1.ENTITY_OWNERSHIP_TYPE = ''V'' THEN ''Private''
							WHEN T1.ENTITY_OWNERSHIP_TYPE = ''P'' THEN ''Public''
							ELSE NULL END AS OWNERSHIP_TYPE,
                        NULLIF(T1.RELATIONSHIP_DESCRIPTION,'''') AS ENTITY_BUSINESS_FOCUS,
                        NULLIF(T1.STUDENT_INVOLVEMENT,'''') AS INVOLVEMENT_OF_STUDENTS,
                        NULLIF(T1.STAFF_INVOLVEMENT,'''') AS INVOLVEMENT_OF_STAFF,
                        NULLIF(T1.INST_RESOURCE_INVOLVEMENT,'''') AS USE_OF_MIT_RESOURCES,
                        CASE WHEN T1.IS_FOUNDER = ''Y'' THEN ''Yes''
							 WHEN T1.IS_FOUNDER = ''N'' THEN ''No''
							 ELSE NULL END AS FOUNDER,
						T3.DESCRIPTION AS MIGRATION_STATUS,
                        CASE WHEN T1.ENTITY_OWNERSHIP_TYPE = ''V'' THEN ''2''
							 WHEN T1.ENTITY_OWNERSHIP_TYPE = ''P'' THEN ''1''
							 ELSE ''3'' END AS OWNERSHIP_TYPE_CODE
						FROM LEGACY_COI_ENGAGEMENTS T1
                        LEFT JOIN FIBI_COI_ENTITY_TYPE T2 ON T2.ENTITY_TYPE_CODE = T1.ENTITY_TYPE_CODE
						LEFT JOIN FIBI_COI_ENG_REVIEW_STATUS T3 ON T3.ENG_REVIEW_STATUS_CODE = T1.MIGRATION_STATUS
						WHERE PERSON_ID =''', AV_PERSON_ID,'''',' AND T1.STATUS_CODE = 1' , LS_FILTER_CONDITION, ' ORDER BY T1.ENTITY_NAME ASC');
IF AV_COUNT = TRUE THEN
	SET LS_DYN_SQL = CONCAT('SELECT COUNT(*) AS TOTAL_COUNT FROM (', LS_DYN_SQL, ') T');
ELSE
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' ', LS_OFFSET_CONDITION);
END IF;
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STATEMENT;
END
$$
DELIMITER ;
