DELIMITER $$
CREATE  PROCEDURE `INSERT_MIG_ENG_FB_ANS`(
    IN AV_ENG_ID INT,
    IN AV_LEG_ENG_ID INT,
    IN AV_PERSON_ID VARCHAR(40)
)
BEGIN
    DECLARE LI_FB_ID INT;
    DECLARE LI_QUESTNR_ID INT;
    DECLARE LI_QUESTN_ID INT;
    DECLARE LI_CMPNT_ID INT;
    DECLARE LI_ANS_ID INT;
    DECLARE LS_ANSWER VARCHAR(4000);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
    END;
    DECLARE EXIT HANDLER FOR NOT FOUND
    BEGIN
        ROLLBACK;
    END;
    START TRANSACTION;
    IF NOT EXISTS (
		SELECT 1
		FROM FORM_BUILDER_ANS_HEADER
		WHERE MODULE_ITEM_CODE = 8
		  AND MODULE_ITEM_KEY = AV_ENG_ID
		  AND MODULE_SUB_ITEM_KEY = 0
	) THEN
        SELECT FBH.FORM_BUILDER_ID
        INTO LI_FB_ID
        FROM FORM_BUILDER_HEADER FBH
        WHERE FBH.DESCRIPTION = 'Engagement Form'
			AND FBH.VERSION_STATUS = 'ACTIVE'
            AND FBH.IS_ACTIVE = 'Y'
            AND FBH.VERSION_NUMBER = (
                SELECT MAX(FBH1.VERSION_NUMBER)
                FROM FORM_BUILDER_HEADER FBH1
                WHERE FBH1.FORM_BUILDER_NUMBER = FBH.FORM_BUILDER_NUMBER
            );
        SELECT T1.FORM_BUILDER_SECT_COMP_ID, T1.COMPONENT_REF_ID
        INTO LI_CMPNT_ID, LI_QUESTNR_ID
        FROM FORM_BUILDER_SECTION_COMPONENT T1
        INNER JOIN FORM_BUILDER_SECTION T2 ON T1.FORM_BUILDER_SECTION_ID = T2.FORM_BUILDER_SECTION_ID
        INNER JOIN FORM_BUILDER_HEADER T3 ON T2.FORM_BUILDER_ID = T3.FORM_BUILDER_ID
        WHERE T1.IS_ACTIVE = 'Y'
            AND T2.IS_ACTIVE = 'Y'
            AND T3.FORM_BUILDER_ID = LI_FB_ID
            AND T1.COMPONENT_TYPE_CODE = 'QN';
        SELECT RELATIONSHIP_DESCRIPTION
        INTO LS_ANSWER
        FROM LEGACY_COI_ENGAGEMENTS
        WHERE ENGAGEMENT_ID = AV_LEG_ENG_ID
            AND PERSON_ID = AV_PERSON_ID;
        INSERT INTO form_builder_ans_header (
            FORM_BUILDER_ID, MODULE_ITEM_CODE, MODULE_SUB_ITEM_CODE,
            MODULE_ITEM_KEY, MODULE_SUB_ITEM_KEY,
            CREATE_TIMESTAMP, CREATE_USER,
            UPDATE_TIMESTAMP, UPDATE_USER
        ) VALUES (
            LI_FB_ID, '8', '801', AV_ENG_ID, '0',
            UTC_TIMESTAMP(), AV_PERSON_ID,
            UTC_TIMESTAMP(), AV_PERSON_ID
        );
        INSERT INTO FB_QUEST_ANSWER_HEADER (
            QUESTIONNAIRE_ID, MODULE_ITEM_CODE, MODULE_SUB_ITEM_CODE,
            MODULE_ITEM_KEY, MODULE_SUB_ITEM_KEY,
            QUESTIONNAIRE_COMPLETED_FLAG,
            UPDATE_TIMESTAMP, UPDATE_USER
        ) VALUES (
            LI_QUESTNR_ID, '8', '801', AV_ENG_ID, LI_CMPNT_ID,
            'N', UTC_TIMESTAMP(), AV_PERSON_ID
        );
        SELECT LAST_INSERT_ID() INTO LI_ANS_ID;
        SELECT QUESTION_ID
        INTO LI_QUESTN_ID
        FROM QUEST_QUESTION
        WHERE QUESTIONNAIRE_ID = LI_QUESTNR_ID
            AND SORT_ORDER = 1
            AND QUESTION = 'What is the business focus of this entity?';
        INSERT INTO FB_QUEST_ANSWER (
            QUESTIONNAIRE_ANS_HEADER_ID, QUESTION_ID,
            ANSWER_NUMBER, ANSWER,
            UPDATE_TIMESTAMP, UPDATE_USER
        ) VALUES (
            LI_ANS_ID, LI_QUESTN_ID, '1',
            LS_ANSWER, UTC_TIMESTAMP(), AV_PERSON_ID
        );
    END IF;
    COMMIT;
END
$$
DELIMITER ;
