DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `INSERT_LINENUMBER_INTO_BUDGET_DETAILS`(av_type int)
BEGIN
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE DONE2 INT DEFAULT FALSE;
DECLARE LS_BUDGET_HEADER_ID INT(11);
DECLARE  LS_BUDGET_DETAIL_ID INT(12);
DECLARE LS_BUDGET_PERIOD_ID INT(12);
DECLARE LS_BUDGET_PERIOD INT(11);
DECLARE LS_TOTAL_DIRECT_COST DECIMAL(10,2);
DECLARE LS_TOTAL_INDIRECT_COST DECIMAL(10,2);
DECLARE LS_SUBCONTRACT_COST DECIMAL(10,2);
DECLARE LS_UPDATE_USER VARCHAR(60);
DECLARE LD_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_COUNT INT;
DECLARE SEQ_BUDGET_DETAILS_ID  INT(12);
DECLARE LI_LINE_ITEM_COUNT INT;
BEGIN
DECLARE BUDGET_HEADER_CURSOR CURSOR FOR
SELECT BUDGET_HEADER_ID FROM BUDGET_HEADER;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN BUDGET_HEADER_CURSOR;
BUDGET_HEADER_CURSOR_LOOP : LOOP
        FETCH BUDGET_HEADER_CURSOR INTO  LS_BUDGET_HEADER_ID ;
		IF DONE1 THEN
			LEAVE BUDGET_HEADER_CURSOR_LOOP;
		END IF;
        BEGIN
		DECLARE BUDGET_PERIOD_CURSOR CURSOR FOR
		SELECT BUDGET_PERIOD_ID,BUDGET_PERIOD,TOTAL_DIRECT_COST,TOTAL_INDIRECT_COST,SUBCONTRACT_COST,UPDATE_USER,UPDATE_TIMESTAMP
		FROM BUDGET_PERIOD
		WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
        OPEN BUDGET_PERIOD_CURSOR;
		BUDGET_PERIOD_CURSOR_LOOP : LOOP
				FETCH BUDGET_PERIOD_CURSOR INTO  LS_BUDGET_PERIOD_ID,LS_BUDGET_PERIOD,LS_TOTAL_DIRECT_COST,LS_TOTAL_INDIRECT_COST,LS_SUBCONTRACT_COST,LS_UPDATE_USER,LD_UPDATE_TIMESTAMP;
				IF DONE2 THEN
					LEAVE BUDGET_PERIOD_CURSOR_LOOP;
				END IF;
				select COUNT(BUDGET_DETAILS_ID) INTO LS_COUNT from BUDGET_DETAIL
				WHERE BUDGET_PERIOD_ID = LS_BUDGET_PERIOD_ID;
				IF LS_COUNT > 0 THEN
			    SET LI_LINE_ITEM_COUNT = 0;
								BEGIN
								DECLARE BUDGET_DETAIL_Y_CURSOR CURSOR FOR
								SELECT BUDGET_DETAILS_ID FROM BUDGET_DETAIL
				                WHERE BUDGET_PERIOD_ID = LS_BUDGET_PERIOD_ID AND IS_SYSTEM_GENRTED_COST_ELEMENT ='Y';
								DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
								OPEN BUDGET_DETAIL_Y_CURSOR;
								BUDGET_DETAIL_Y_CURSOR_LOOP : LOOP
										FETCH BUDGET_DETAIL_Y_CURSOR INTO LS_BUDGET_DETAIL_ID;
										IF DONE2 THEN
											LEAVE BUDGET_DETAIL_Y_CURSOR_LOOP;
										END IF;
										SET LI_LINE_ITEM_COUNT = LI_LINE_ITEM_COUNT + 1;
										UPDATE BUDGET_DETAIL SET LINE_ITEM_NUMBER = LI_LINE_ITEM_COUNT WHERE BUDGET_DETAILS_ID = LS_BUDGET_DETAIL_ID;
							    END LOOP;
								CLOSE BUDGET_DETAIL_Y_CURSOR;
								SET DONE2 = FALSE ;
								END;
								BEGIN
								DECLARE BUDGET_DETAIL_N_CURSOR CURSOR FOR
								SELECT BUDGET_DETAILS_ID FROM BUDGET_DETAIL
				                WHERE BUDGET_PERIOD_ID = LS_BUDGET_PERIOD_ID AND IS_SYSTEM_GENRTED_COST_ELEMENT ='N';
								DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
								OPEN BUDGET_DETAIL_N_CURSOR;
								BUDGET_DETAIL_N_CURSOR_LOOP : LOOP
										FETCH BUDGET_DETAIL_N_CURSOR INTO LS_BUDGET_DETAIL_ID;
										IF DONE2 THEN
											LEAVE BUDGET_DETAIL_N_CURSOR_LOOP;
										END IF;
										SET LI_LINE_ITEM_COUNT = LI_LINE_ITEM_COUNT + 1;
										UPDATE BUDGET_DETAIL SET LINE_ITEM_NUMBER = LI_LINE_ITEM_COUNT WHERE BUDGET_DETAILS_ID = LS_BUDGET_DETAIL_ID;
							    END LOOP;
								CLOSE BUDGET_DETAIL_N_CURSOR;
								SET DONE2 = FALSE ;
								END;
		      END IF;
	   END LOOP;
	 CLOSE BUDGET_PERIOD_CURSOR;
	END;
	SET DONE2 = FALSE ;
END LOOP;
CLOSE BUDGET_HEADER_CURSOR;
END;
END
$$
DELIMITER ;
