DELIMITER $$
CREATE  PROCEDURE `KKI_MIGRATION_AWARD_HIERARCHY`(av_type int)
BEGIN
DECLARE LS_LEGACY_PROJECT_ID			VARCHAR(100);
DECLARE LS_LEGACY_WBS_NUMBER			VARCHAR(100);
DECLARE LS_MA_GRANT_CODE				VARCHAR(50);
DECLARE LS_MA_ACCOUNT_NUMBER			VARCHAR(100);
DECLARE LI_MIGRATION_AWARD_HIERARCHY_ID	INT(11);
DECLARE LS_PARENT_LEGACY_WBS_NUMBER		VARCHAR(100);
DECLARE LI_COUNT 						INT;
DECLARE LI_AWARD_ID  					DECIMAL(22,0);
DECLARE LS_AWARD_NUMBER 				VARCHAR(12);
DECLARE LI_RESRCH_AREA_ID 				INT(11);
DECLARE LI_AWARD_HIERARCHY_ID 			DECIMAL(22,0);
DECLARE LS_PARENT_AWARD_NUMBER  		VARCHAR(12);
DECLARE LS_FILE_TYPE 					VARCHAR(50);
DECLARE LI_PARENT_AWARD_ID              DECIMAL(22,0);
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_AWARD_HIERARCHY_CURSOR1 CURSOR FOR
		SELECT AWARD_ID,AWARD_NUMBER FROM MIGRATION_AWARD where CONCAT(SUBSTRING(AWARD_NUMBER,7,6)) = '-00001';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO MIGRATION_ERROR_LOG(LEGACY_PROJECT_ID,LEGACY_WBS_NUMBER,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
			VALUES(LS_LEGACY_PROJECT_ID,LS_AWARD_NUMBER,'Exception','AWARD_HIERARCHY',SUBSTR(LS_ERROR,1,999),'During Migration',LS_FILE_TYPE);
			COMMIT;
		END;
		OPEN MIGRATION_AWARD_HIERARCHY_CURSOR1;
		MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP1 : LOOP
				FETCH MIGRATION_AWARD_HIERARCHY_CURSOR1 INTO LI_AWARD_ID,LS_AWARD_NUMBER;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP1;
				END IF;
				SELECT  COUNT(*) INTO LI_COUNT
				FROM AWARD WHERE AWARD_ID = LI_AWARD_ID;
				IF LI_COUNT = 0 THEN
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP1;
				END IF;
				IF ( IFNULL(TRIM(LS_AWARD_NUMBER),'') ='') THEN
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP1;
				END IF;
				SELECT IFNULL(MAX(AWARD_HIERARCHY_ID),0)+1 INTO LI_AWARD_HIERARCHY_ID
				FROM AWARD_HIERARCHY;
				INSERT INTO AWARD_HIERARCHY(AWARD_HIERARCHY_ID,
											AWARD_NUMBER,
											PARENT_AWARD_NUMBER,
											ROOT_AWARD_NUMBER,
											ORIGINATING_AWARD_NUMBER,
											UPDATE_TIMESTAMP,
											UPDATE_USER,
											ACTIVE)
				VALUES(LI_AWARD_HIERARCHY_ID,
				LS_AWARD_NUMBER,
				'000000-00000',
				LS_AWARD_NUMBER,
				LS_AWARD_NUMBER,
				UTC_TIMESTAMP(),
				'quickstart',
				'Y'
				);
		END LOOP;
		CLOSE MIGRATION_AWARD_HIERARCHY_CURSOR1;
		COMMIT;
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_AWARD_HIERARCHY_CURSOR CURSOR FOR
		SELECT AWARD_ID,AWARD_NUMBER FROM MIGRATION_AWARD where CONCAT(SUBSTRING(AWARD_NUMBER,7,6)) <> '-00001';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO MIGRATION_ERROR_LOG(LEGACY_PROJECT_ID,LEGACY_WBS_NUMBER,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
			VALUES(LS_LEGACY_PROJECT_ID,LS_AWARD_NUMBER,'Exception','AWARD_HIERARCHY',SUBSTR(LS_ERROR,1,999),'During Migration',LS_FILE_TYPE);
			COMMIT;
		END;
		OPEN MIGRATION_AWARD_HIERARCHY_CURSOR;
		MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_HIERARCHY_CURSOR INTO LI_AWARD_ID,LS_AWARD_NUMBER;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
				END IF;
				SET LI_PARENT_AWARD_ID =NULL;
				SET LS_PARENT_AWARD_NUMBER =NULL;
				IF ( IFNULL(TRIM(LS_AWARD_NUMBER),'') ='') THEN
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
				END IF;
				SELECT  COUNT(*) INTO LI_COUNT
				FROM AWARD WHERE AWARD_ID = LI_AWARD_ID;
				IF LI_COUNT = 0 THEN
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
				END IF;
				SELECT AWARD_ID,AWARD_NUMBER INTO  LI_PARENT_AWARD_ID,LS_PARENT_AWARD_NUMBER
				FROM AWARD
				WHERE AWARD_NUMBER = CONCAT(SUBSTRING(LS_AWARD_NUMBER,1,6),'-00001');
				SELECT  COUNT(*) INTO LI_COUNT
				FROM AWARD WHERE AWARD_ID = LI_PARENT_AWARD_ID;
				IF LI_COUNT = 0 THEN
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
				END IF;
				SELECT IFNULL(MAX(AWARD_HIERARCHY_ID),0)+1 INTO LI_AWARD_HIERARCHY_ID
				FROM AWARD_HIERARCHY;
				INSERT INTO AWARD_HIERARCHY(AWARD_HIERARCHY_ID,
											AWARD_NUMBER,
											PARENT_AWARD_NUMBER,
											ROOT_AWARD_NUMBER,
											ORIGINATING_AWARD_NUMBER,
											UPDATE_TIMESTAMP,
											UPDATE_USER,
											ACTIVE)
				VALUES(LI_AWARD_HIERARCHY_ID,
				LS_AWARD_NUMBER,
				LS_PARENT_AWARD_NUMBER,
				CONCAT(SUBSTRING(LS_AWARD_NUMBER,1,6),'-00001'),
				CONCAT(SUBSTRING(LS_AWARD_NUMBER,1,6),'-00001'),
				UTC_TIMESTAMP(),
				'quickstart',
				'Y'
				);
COMMIT;
		END LOOP;
		CLOSE MIGRATION_AWARD_HIERARCHY_CURSOR;
END;
set sql_safe_updates =0;
UPDATE AWARD_HIERARCHY_ID_GENERATOR SET NEXT_VAL = LI_AWARD_HIERARCHY_ID + 1;
SELECT 1  AS RESULT;
END
$$
DELIMITER ;
