DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `KKI_MIGRATION_AWARD_SUBORG`(AV_TYPE INT)
BEGIN
DECLARE LS_LEGACY_PROJECT_ID	    VARCHAR(100);
DECLARE LS_LEGACY_WBS_NUMBER	    VARCHAR(100);
DECLARE LS_PERSON_ID				VARCHAR(40);
DECLARE LS_ROLODEX_ID				VARCHAR(10);
DECLARE LS_PERSON_ROLE				VARCHAR(50);
DECLARE LI_PERSON_ROLE_CODE 		INT(12);
DECLARE LS_PERCENTAGE_OF_EFFORT 	VARCHAR(5);
DECLARE LI_COUNT 					INT;
DECLARE LS_FILE_TYPE 				VARCHAR(50);
DECLARE LS_FULL_NAME 				VARCHAR(90);
DECLARE LS_EMAIL_ADDRESS			VARCHAR(255);
DECLARE LI_AWARD_ID  				INT(22);
DECLARE LS_AWARD_NUMBER 			VARCHAR(12);
DECLARE LI_AWARD_PERSON_ID 		INT(11);
DECLARE LS_HOME_UNIT               VARCHAR(8);
DECLARE LI_AWARD_APPROVED_SUBAWARD_ID DECIMAL(22,0);
DECLARE LS_IS_MULTI_PI             VARCHAR(1);
DECLARE LS_ACCOUNT_NUMBER  VARCHAR(100);
DECLARE LS_YEAR   VARCHAR(100);
DECLARE LS_SUB_AWARD_ORGANIZATION  VARCHAR(200);
DECLARE LS_SUB_AWARD_ORGANIZATION_AMOUNT DECIMAL(12,2);
DECLARE  LI_SEQUENCE_NUMBER int(3);
DECLARE LS_ORGANIZATION_ID VARCHAR(200);
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_AWARD_SUBORG_CURSOR CURSOR FOR
		SELECT  ACCOUNT_NUMBER,
				YEAR,
				SUB_AWARD_ORGANIZATION,
				SUB_AWARD_ORGANIZATION_AMOUNT
		FROM KKI_MIGRATION_AWARD_SUBORG;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO MIGRATION_ERROR_LOG(LEGACY_PROJECT_ID,LEGACY_WBS_NUMBER,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
			VALUES(LS_LEGACY_PROJECT_ID,LS_ACCOUNT_NUMBER,'Exception','AWARD_SUBORG',SUBSTR(LS_ERROR,1,999),'During Migration',LS_FILE_TYPE);
			COMMIT;
		END;
		OPEN MIGRATION_AWARD_SUBORG_CURSOR;
		MIGRATION_AWARD_SUBORG_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_SUBORG_CURSOR INTO LS_ACCOUNT_NUMBER,
															LS_YEAR,
															LS_SUB_AWARD_ORGANIZATION,
															LS_SUB_AWARD_ORGANIZATION_AMOUNT;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_SUBORG_CURSOR_LOOP;
				END IF;
				AWARD_LABEL :BEGIN
				set LS_AWARD_NUMBER = NULL;
				set LI_AWARD_ID = NULL;
				set  LI_SEQUENCE_NUMBER = NULL;
				set LS_ORGANIZATION_ID  = null;
				IF (  IFNULL(TRIM(LS_ACCOUNT_NUMBER),'') = '' ) THEN
						LEAVE AWARD_LABEL;
				END IF;
				IF ( IFNULL(TRIM(LS_SUB_AWARD_ORGANIZATION),'') = '' ) THEN
						LEAVE AWARD_LABEL;
				END IF;
				IF ( IFNULL(TRIM(LS_SUB_AWARD_ORGANIZATION),'') <> '' AND IFNULL(TRIM(LS_SUB_AWARD_ORGANIZATION_AMOUNT),'') = ''  ) THEN
						LEAVE AWARD_LABEL;
				END IF;
				IF ( IFNULL(TRIM(LS_SUB_AWARD_ORGANIZATION),'') <> '' AND UPPER(TRIM(LS_SUB_AWARD_ORGANIZATION)) NOT IN (SELECT UPPER(TRIM(ORGANIZATION_NAME))
																														 FROM ORGANIZATION)  ) THEN
						LEAVE AWARD_LABEL;
				END IF;
				SELECT COUNT(*) INTO LI_COUNT
				FROM MIGRATION_AWARD
				WHERE UPPER(TRIM(ACCOUNT_NUMBER)) = UPPER(TRIM(LS_ACCOUNT_NUMBER));
				IF LI_COUNT = 0 THEN
					LEAVE AWARD_LABEL;
				ELSE
					SELECT AWARD_NUMBER,AWARD_ID,SEQUENCE_NUMBER INTO LS_AWARD_NUMBER,LI_AWARD_ID,LI_SEQUENCE_NUMBER
					FROM MIGRATION_AWARD
					WHERE UPPER(TRIM(ACCOUNT_NUMBER)) = UPPER(TRIM(LS_ACCOUNT_NUMBER));
				END IF;
				SELECT ORGANIZATION_ID INTO LS_ORGANIZATION_ID
				FROM ORGANIZATION
				WHERE UPPER(TRIM(ORGANIZATION_NAME)) = UPPER(TRIM(LS_SUB_AWARD_ORGANIZATION));
				SELECT IFNULL(MAX(AWARD_APPROVED_SUBAWARD_ID),0)+1 INTO LI_AWARD_APPROVED_SUBAWARD_ID
				FROM AWARD_APPROVED_SUBAWARDS;
				INSERT INTO AWARD_APPROVED_SUBAWARDS(AWARD_APPROVED_SUBAWARD_ID,
														AWARD_ID,
														AWARD_NUMBER,
														SEQUENCE_NUMBER,
														ORGANIZATION_ID,
														AMOUNT,
														UPDATE_TIMESTAMP,
														UPDATE_USER)
				VALUES(LI_AWARD_APPROVED_SUBAWARD_ID,
				LI_AWARD_ID,
				LS_AWARD_NUMBER,
				LI_SEQUENCE_NUMBER,
				LS_ORGANIZATION_ID,
				LS_SUB_AWARD_ORGANIZATION_AMOUNT,
				UTC_TIMESTAMP(),
				'quickstart');
				END;
		END LOOP;
		CLOSE MIGRATION_AWARD_SUBORG_CURSOR;
END;
UPDATE AWARD_APPROVED_SUBAWARD_ID_GENERATOR SET NEXT_VAL = (SELECT IFNULL(MAX(AWARD_APPROVED_SUBAWARD_ID),0)+1  FROM AWARD_APPROVED_SUBAWARDS);
COMMIT;
SELECT 1  AS RESULT;
END
$$
DELIMITER ;
