DELIMITER $$
CREATE  PROCEDURE `kki_epsprop_budget_feed`(av_type int)
BEGIN
declare ls_PROPOSAL_ID int(11);
declare ls_BUDGET_HEADER_ID int(11);
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE EXP_CURSOR CURSOR FOR
SELECT p.PROPOSAL_ID,p.BUDGET_HEADER_ID
FROM kki_prod.fibi_proposal p left join kki_prod.fibi_budget_header b on p.BUDGET_HEADER_ID = b.BUDGET_HEADER_ID;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN EXP_CURSOR;
EXP_CURSOR_LOOP : LOOP
        FETCH EXP_CURSOR INTO  ls_PROPOSAL_ID,ls_BUDGET_HEADER_ID ;
		IF DONE1 THEN
			LEAVE EXP_CURSOR_LOOP;
		END IF;
		update fibikki_prod.budget_header  set PROPOSAL_ID = ls_PROPOSAL_ID
		where BUDGET_HEADER_ID = ls_BUDGET_HEADER_ID;
END LOOP;
CLOSE EXP_CURSOR;
END
$$
DELIMITER ;
