DELIMITER $$
CREATE  PROCEDURE `proposal_aggregator_role_insertion`(av_type int)
BEGIN
DECLARE LI_PROPOSAL_ID INT(11);
DECLARE LS_CREATE_USER VARCHAR(60);
DECLARE LS_PERSON_ID VARCHAR(40);
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE LI_COUNT INT(11);
DECLARE LD_CREATE_TIMESTAMP VARCHAR(15);
declare LI_PROPOSAL_PERSON_ROLE_ID int(11);
DECLARE EXP_CURSOR CURSOR FOR
SELECT PROPOSAL_ID,CREATE_USER,CREATE_TIMESTAMP
FROM fibikki_prod.EPS_PROPOSAL
WHERE PROPOSAL_ID < 523 and ifnull(trim(CREATE_USER),'') <>'';
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN EXP_CURSOR;
EXP_CURSOR_LOOP : LOOP
        FETCH EXP_CURSOR INTO  LI_PROPOSAL_ID,LS_CREATE_USER,LD_CREATE_TIMESTAMP ;
IF DONE1 THEN
LEAVE EXP_CURSOR_LOOP;
END IF;
SELECT PERSON_ID into LS_PERSON_ID
FROM PERSON
WHERE UPPER(TRIM(USER_NAME)) = UPPER(TRIM(LS_CREATE_USER));
SELECT COUNT(*) INTO LI_COUNT
FROM EPS_PROPOSAL_PERSON_ROLES
WHERE PERSON_ID = LS_PERSON_ID
AND ROLE_ID = 5
AND PROPOSAL_ID = LI_PROPOSAL_ID;
IF LI_COUNT = 0 THEN
SELECT IFNULL(MAX(PROPOSAL_PERSON_ROLE_ID),0)+1 INTO LI_PROPOSAL_PERSON_ROLE_ID
FROM EPS_PROPOSAL_PERSON_ROLES;
INSERT INTO EPS_PROPOSAL_PERSON_ROLES(PROPOSAL_PERSON_ROLE_ID,PROPOSAL_ID,PERSON_ID,ROLE_ID,UPDATE_TIMESTAMP,UPDATE_USER)
VALUES(LI_PROPOSAL_PERSON_ROLE_ID,LI_PROPOSAL_ID,LS_PERSON_ID,5,LD_CREATE_TIMESTAMP,LS_CREATE_USER);
END IF;
END LOOP;
CLOSE EXP_CURSOR;
END
$$
DELIMITER ;
