DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `TRAVEL_VALIDATE_REIMBURSEMENT_COST`(AV_PERSON_ENTITY_NUMBER INT)
BEGIN
DECLARE LI_REIMBURSEMENT_COST_LIMIT   	DECIMAL(12, 2);
DECLARE LI_REIMBURSED_LIMIT_PERIOD   	INT(3);
DECLARE LS_PERSON_ENTITY_ID INT(3);
    SELECT VALUE INTO LI_REIMBURSEMENT_COST_LIMIT  FROM PARAMETER WHERE PARAMETER_NAME = 'TRAVEL_REIMBURSED_COST_THRESHOLD';
    SELECT VALUE INTO LI_REIMBURSED_LIMIT_PERIOD  FROM PARAMETER WHERE PARAMETER_NAME = 'TRAVEL_REIMBURSED_THRESHOLD_PERIOD';
    DROP TEMPORARY TABLE IF EXISTS TEMP_REIMBURSE_SUMMARY;
    CREATE TEMPORARY TABLE TEMP_REIMBURSE_SUMMARY (
        PERSON_ENTITY_NUMBER INT,
        PERSON_ID VARCHAR(60),
        TOTAL_REIMBURSED_COST DECIMAL(14,2),
        TOTAL_NO_OF_TRAVELS INT
    );
    INSERT INTO TEMP_REIMBURSE_SUMMARY (PERSON_ENTITY_NUMBER, PERSON_ID, TOTAL_REIMBURSED_COST, TOTAL_NO_OF_TRAVELS)
    SELECT
        t1.PERSON_ENTITY_NUMBER,
        t1.PERSON_ID,
        SUM(CAST(t3.VALUE AS DECIMAL(14, 2))) AS TOTAL_REIMBURSED_COST,
        COUNT(t1.TRAVEL_DISCLOSURE_ID) AS TOTAL_NO_OF_TRAVELS
    FROM COI_TRAVEL_DISCLOSURE t1
    LEFT JOIN FB_COMP_CUSTOM_ELEMENT t2
        ON t2.CUSTOM_ELEMENT_NAME = 'Reimbursed Cost'
    LEFT JOIN FB_COMP_CUSTOM_ELEMENT_ANSWER t3
        ON t3.CUSTOM_DATA_ELEMENTS_ID = t2.CUSTOM_DATA_ELEMENTS_ID
        AND t3.MODULE_ITEM_CODE = 24
        AND t3.MODULE_ITEM_KEY = t1.TRAVEL_DISCLOSURE_ID
    INNER JOIN COI_TRAVEL_DESTINATIONS t4
        ON t4.TRAVEL_DISCLOSURE_ID = t1.TRAVEL_DISCLOSURE_ID
    WHERE
        t4.STAY_START_DATE >= DATE_SUB(UTC_DATE(), INTERVAL LI_REIMBURSED_LIMIT_PERIOD MONTH)
        AND t1.REVIEW_STATUS_CODE != 1
        AND t1.PERSON_ENTITY_NUMBER = AV_PERSON_ENTITY_NUMBER
    GROUP BY t1.PERSON_ENTITY_NUMBER, t1.PERSON_ID;
	SELECT MAX(PERSON_ENTITY_ID)
    INTO LS_PERSON_ENTITY_ID
    FROM PERSON_ENTITY
    WHERE PERSON_ENTITY_NUMBER = AV_PERSON_ENTITY_NUMBER
    AND VERSION_STATUS = 'ACTIVE';
    UPDATE PERSON_ENTITY pe
    JOIN TEMP_REIMBURSE_SUMMARY t
        ON pe.PERSON_ENTITY_NUMBER = t.PERSON_ENTITY_NUMBER
    SET pe.TRAVEL_REIMBURSEMENT_AMOUNT = t.TOTAL_REIMBURSED_COST
    WHERE pe.PERSON_ENTITY_ID = LS_PERSON_ENTITY_ID;
    SELECT *
    FROM TEMP_REIMBURSE_SUMMARY
    WHERE TOTAL_REIMBURSED_COST > LI_REIMBURSEMENT_COST_LIMIT;
    DROP TEMPORARY TABLE IF EXISTS TEMP_REIMBURSE_SUMMARY;
END
$$
DELIMITER ;
