DELIMITER $$
CREATE  PROCEDURE `UPD_AWARD_ATTACHMENT`(
AV_ID	INT
)
BEGIN
DECLARE LS_ERROR_MSG		VARCHAR(1000);
DECLARE LS_TABLE_NAME		VARCHAR(30);
DECLARE LI_FLAG				INT;
DECLARE LI_AWARD_ID							DECIMAL(22,0);
DECLARE LS_AWARD_NUMBER						VARCHAR(12);
DECLARE LI_MIN_SEQ							INT(4);
DECLARE LI_CUR_SEQUENCE_NUMBER				INT(4);
DECLARE LI_CUR_DOCUMENT_ID					INT(11);
DECLARE LI_NEW_DOC_ID						INT(11);
DECLARE LI_PREV_DOCUMENT_ID					INT(11);
DECLARE LI_PREV_SEQ_NUMBER					INT(4);
DECLARE LI_PREV_NEW_DOC_ID					INT(11);
DECLARE LI_AWARD_ATTACHMENT_ID				DECIMAL(12,0);
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO AWARD_ERROR_LOG(AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, ERROR_MESSAGE, PROCEDURE_NAME, TABLE_NAME,SECTION_CODE,VARIATION_TYPE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_AWARD_ID,LS_AWARD_NUMBER,LI_CUR_SEQUENCE_NUMBER,LS_ERROR_MSG,'UPD_AWARD_ATTACHMENT',NULL,NULL,null,UTC_TIMESTAMP(),'quickstart');
			COMMIT;
		END;
		BEGIN
			DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE CUR_AWARD_DATA CURSOR FOR
			SELECT
				DISTINCT AWARD_NUMBER
			FROM AWARD_ATTACHMENT;
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN CUR_AWARD_DATA;
			INSERT_AWARD_LOOP: LOOP
			FETCH CUR_AWARD_DATA INTO
			LS_AWARD_NUMBER;
			IF DONE1 THEN
				LEAVE INSERT_AWARD_LOOP;
			END IF;
				BEGIN
					DECLARE DONE2 INT DEFAULT FALSE;
					DECLARE CUR_AWARD_ATT_DATA CURSOR FOR
					SELECT
						AWARD_ATTACHMENT_ID,
						AWARD_ID,
						SEQUENCE_NUMBER,
						DOCUMENT_ID
					FROM AWARD_ATTACHMENT
					WHERE AWARD_NUMBER = LS_AWARD_NUMBER
					ORDER BY SEQUENCE_NUMBER;
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
					OPEN CUR_AWARD_ATT_DATA;
					INSERT_AWARD_ATT_LOOP: LOOP
					FETCH CUR_AWARD_ATT_DATA INTO
					LI_AWARD_ATTACHMENT_ID,
					LI_AWARD_ID,
					LI_CUR_SEQUENCE_NUMBER,
					LI_CUR_DOCUMENT_ID;
					IF DONE2 THEN
						LEAVE INSERT_AWARD_ATT_LOOP;
					END IF;
						SELECT
							MIN(SEQUENCE_NUMBER)
						INTO
							LI_MIN_SEQ
						FROM AWARD_ATTACHMENT
						WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
						IF LI_MIN_SEQ = LI_CUR_SEQUENCE_NUMBER THEN
							SET LI_NEW_DOC_ID = LI_CUR_DOCUMENT_ID;
							SET LI_PREV_SEQ_NUMBER = LI_CUR_SEQUENCE_NUMBER;
						ELSE
							IF LI_CUR_SEQUENCE_NUMBER <> LI_PREV_SEQ_NUMBER THEN
								SELECT
									MAX(NEW_DOCUMENT_ID) + 1
								INTO
									LI_NEW_DOC_ID
								FROM AWARD_ATTACHMENT
								WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
							ELSE
								IF LI_CUR_DOCUMENT_ID <> LI_PREV_DOCUMENT_ID THEN
									SELECT
										MAX(NEW_DOCUMENT_ID) + 1
									INTO
										LI_NEW_DOC_ID
									FROM AWARD_ATTACHMENT
									WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
								ELSE
									SELECT
										MAX(NEW_DOCUMENT_ID)
									INTO
										LI_NEW_DOC_ID
									FROM AWARD_ATTACHMENT
									WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
								END IF;
							END IF;
							SET LI_PREV_DOCUMENT_ID = LI_CUR_DOCUMENT_ID;
							SET LI_PREV_SEQ_NUMBER = LI_CUR_SEQUENCE_NUMBER;
						END IF;
						UPDATE AWARD_ATTACHMENT
						SET NEW_DOCUMENT_ID = LI_NEW_DOC_ID
						WHERE AWARD_ATTACHMENT_ID = LI_AWARD_ATTACHMENT_ID;
					END LOOP;
					CLOSE CUR_AWARD_ATT_DATA;
				END;
				SET LI_MIN_SEQ 				= NULL;
				SET LI_CUR_SEQUENCE_NUMBER 	= NULL;
				SET LI_CUR_DOCUMENT_ID 		= NULL;
				SET LI_NEW_DOC_ID 			= NULL;
				SET LI_PREV_DOCUMENT_ID 	= NULL;
				SET LI_PREV_SEQ_NUMBER 		= NULL;
				SET LI_PREV_NEW_DOC_ID 		= NULL;
				SET LI_AWARD_ATTACHMENT_ID 	= NULL;
			END LOOP;
			CLOSE CUR_AWARD_DATA;
		END;
END
$$
DELIMITER ;
