DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `UPD_COI_AWD_DISCLOSURE_STS`(AV_AWARD_NUMBER VARCHAR(12),
											UPD_PERSON_STS VARCHAR(1))
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	IF UPD_PERSON_STS  = 'Y' THEN
		UPDATE COI_INT_STAGE_AWARD_PERSON CAP,
				COI_INT_STAGE_AWARD CIA
		SET MAX_DISCLOSURE_ID = (SELECT MAX(T1.DISCLOSURE_ID)
					  FROM COI_DISCL_PROJECTS T1,
						   COI_DISCLOSURE T2
					  WHERE  T1.MODULE_CODE = 1
						AND SUBSTRING_INDEX(T1.MODULE_ITEM_KEY,'-',1) = SUBSTRING_INDEX(CAP.PROJECT_NUMBER,'-',1)
						AND  T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
						AND  T2.DISPOSITION_STATUS_CODE <> 2
						AND  T2.VERSION_STATUS <> 'ARCHIVE'
						AND  T2.PERSON_ID = CAP.KEY_PERSON_ID),
			CAP.DISCLOSURE_STATUS =(CASE
									WHEN CAP.NEW_DISCLOSURE_REQUIRED = 'Y'
										THEN 'NOT_YET_DISCLOSED'
									WHEN (CIA.DISCLOSURE_VALIDATION_FLAG = 'SELF' OR ( CAP.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
									 AND (CIA.DISCLOSURE_VALIDATION_FLAG IS NULL OR CIA.DISCLOSURE_VALIDATION_FLAG = 'HIERARCHY')))
										THEN  IFNULL((SELECT CASE WHEN C1.REVIEW_STATUS_CODE IN  (2,3,4,7,8) THEN 'DISCLOSURE_COMPLETED'
														   WHEN C1.REVIEW_STATUS_CODE IN  (1,5,6) THEN 'DISCLOSURE_PENDING'
														   ELSE  'NOT_YET_DISCLOSED'
														END
												FROM COI_DISCLOSURE C1
												WHERE C1.DISCLOSURE_ID = (SELECT MAX(T1.DISCLOSURE_ID)
																		  FROM COI_DISCL_PROJECTS T1,
																			   COI_DISCLOSURE T2
																		  WHERE  T1.MODULE_CODE = 1
																			AND SUBSTRING_INDEX(T1.MODULE_ITEM_KEY,'-',1) = SUBSTRING_INDEX(CAP.PROJECT_NUMBER,'-',1)
																			AND  T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
																			AND  T2.DISPOSITION_STATUS_CODE <> 2
																			AND  T2.VERSION_STATUS <> 'ARCHIVE'
																			AND  T2.PERSON_ID = CAP.KEY_PERSON_ID)
												),'NOT_YET_DISCLOSED')
									WHEN CAP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'  AND IFNULL(CIA.DISCLOSURE_VALIDATION_FLAG,'x') <> 'SELF'
										THEN 'DISCLOSURE_NOT_REQUIRED'
									END
									),
					DISCLOSURE_REVIEW_STATUS = (CASE
											WHEN CAP.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' OR (CIA.DISCLOSURE_VALIDATION_FLAG = 'SELF' AND CAP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED')
												THEN (SELECT CR.DESCRIPTION
												FROM COI_DISCLOSURE C1,
													 COI_REVIEW_STATUS_TYPE CR
												WHERE C1.DISCLOSURE_ID = (SELECT MAX(T1.DISCLOSURE_ID)
																		  FROM COI_DISCL_PROJECTS T1,
																			   COI_DISCLOSURE T2
																		  WHERE  T1.MODULE_CODE = 1
																		   AND SUBSTRING_INDEX(T1.MODULE_ITEM_KEY,'-',1) = SUBSTRING_INDEX(CAP.PROJECT_NUMBER,'-',1)
																			AND  T1.DISCLOSURE_ID = T2.DISCLOSURE_ID
																			AND  T2.DISPOSITION_STATUS_CODE <> 2
																			AND  T2.VERSION_STATUS <> 'ARCHIVE'
																			AND  T2.PERSON_ID = CAP.KEY_PERSON_ID)
												 AND CR.REVIEW_STATUS_CODE = C1.REVIEW_STATUS_CODE
												)
											WHEN CAP.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED' AND IFNULL(CIA.DISCLOSURE_VALIDATION_FLAG,'x') <> 'SELF'
												THEN 'DISCLOSURE_REVIEW_NA'
											ELSE NULL
											END )
		   WHERE CIA.PROJECT_NUMBER = AV_AWARD_NUMBER
			 AND CAP.PROJECT_NUMBER =  CIA.PROJECT_NUMBER
			 AND CAP.STATUS = 'A';
		END IF;
		UPDATE COI_INT_STAGE_AWARD  CIA
		   SET OVERALL_DISCLOSURE_STATUS = CASE WHEN NOT EXISTS (
																	SELECT 1
																	FROM COI_INT_STAGE_AWARD_PERSON
																	WHERE PROJECT_NUMBER = CIA.PROJECT_NUMBER
																	  AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_COMPLETED','DISCLOSURE_NOT_REQUIRED')
													            ) THEN 'DISCLOSURE_COMPLETED'
												WHEN NOT EXISTS (
																	SELECT 1
																	FROM COI_INT_STAGE_AWARD_PERSON
																	WHERE PROJECT_NUMBER = CIA.PROJECT_NUMBER
																	  AND DISCLOSURE_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
																) THEN 'DISCLOSURE_NOT_REQUIRED'
												WHEN  EXISTS (
																SELECT 1
																FROM COI_INT_STAGE_AWARD_PERSON
																WHERE PROJECT_NUMBER = CIA.PROJECT_NUMBER
																  AND DISCLOSURE_STATUS = 'NOT_YET_DISCLOSED'
															) THEN 'NOT_YET_DISCLOSED'
												WHEN EXISTS (
																SELECT 1
																FROM COI_INT_STAGE_AWARD_PERSON
																WHERE PROJECT_NUMBER = CIA.PROJECT_NUMBER
																  AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
															) THEN 'DISCLOSURE_PENDING'
												END
		 WHERE  PROJECT_NUMBER = AV_AWARD_NUMBER;
		UPDATE COI_INT_STAGE_AWARD  CIA
		   SET OVERALL_DISCL_REVIEW_STATUS = CASE
												WHEN OVERALL_DISCLOSURE_STATUS = 'DISCLOSURE_NOT_REQUIRED' THEN 'N/A'
												WHEN OVERALL_DISCLOSURE_STATUS = 'NOT_YET_DISCLOSED' THEN '--'
												WHEN NOT EXISTS (
																	SELECT 1
																	FROM COI_INT_STAGE_AWARD_PERSON
																	WHERE PROJECT_NUMBER = CIA.PROJECT_NUMBER
																	  AND DISCLOSURE_REVIEW_STATUS NOT IN ('Completed')
													            ) THEN 'Completed'
												ELSE 'Pending'
												END
		 WHERE  PROJECT_NUMBER = AV_AWARD_NUMBER;
		SET SQL_SAFE_UPDATES = 1;
END
$$
DELIMITER ;
