DELIMITER $$
CREATE  PROCEDURE `UPDATE_BUDGET_HEADER`(av_type int)
BEGIN
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE DONE2 INT DEFAULT FALSE;
DECLARE LS_BUDGET_HEADER_ID INT(11);
DECLARE LS_BUDGET_DETAIL_ID INT(12);
DECLARE LS_BUDGET_PERIOD_ID INT(12);
DECLARE LI_LINE_ITEM_COST	decimal(10,2);
DECLARE LS_COUNT INT;
DECLARE LI_TOTAL_COST decimal(10,2);
DECLARE LI_DIRECT_LINE_ITEM_COST decimal(10,2);
DECLARE LI_INDIRECT_LINE_ITEM_COST decimal(10,2);
BEGIN
DECLARE BUDGET_HEADER_CURSOR CURSOR FOR
SELECT BUDGET_HEADER_ID FROM BUDGET_HEADER;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN BUDGET_HEADER_CURSOR;
BUDGET_HEADER_CURSOR_LOOP : LOOP
        FETCH BUDGET_HEADER_CURSOR INTO  LS_BUDGET_HEADER_ID ;
		IF DONE1 THEN
			LEAVE BUDGET_HEADER_CURSOR_LOOP;
		END IF;
				select SUM(TOTAL_DIRECT_COST) INTO LI_DIRECT_LINE_ITEM_COST from BUDGET_PERIOD
				WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
				select SUM(TOTAL_INDIRECT_COST) INTO LI_INDIRECT_LINE_ITEM_COST from BUDGET_PERIOD
				WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
				select SUM(TOTAL_COST) INTO LI_TOTAL_COST from BUDGET_PERIOD
				WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
				UPDATE BUDGET_HEADER SET TOTAL_DIRECT_COST = LI_DIRECT_LINE_ITEM_COST WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
				UPDATE BUDGET_HEADER SET TOTAL_INDIRECT_COST = LI_INDIRECT_LINE_ITEM_COST WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
				UPDATE BUDGET_HEADER SET TOTAL_COST = LI_TOTAL_COST WHERE BUDGET_HEADER_ID = LS_BUDGET_HEADER_ID;
				COMMIT;
END LOOP;
CLOSE BUDGET_HEADER_CURSOR;
END;
END
$$
DELIMITER ;
