DELIMITER $$
CREATE DEFINER=`fibi`@`%` PROCEDURE `UPDATE_CLAIM_WITH_REVENUE_DATA`()
BEGIN
DECLARE LI_CLAIM_ID int(12);
DECLARE	LI_INVOICE_LOG_ID int(12);
DECLARE LS_CLAIM_NUMBER VARCHAR(12);
DECLARE LI_COUNT INT(3);
DECLARE LI_COUNT_2 INT(3);
DECLARE LD_DOCUMENT_DATE	datetime;
DECLARE LD_PAYMENT_DATE	datetime;
DECLARE LI_FLAG INT;
    SET SQL_SAFE_UPDATES = 0;
	SELECT COUNT(1) into LI_FLAG FROM CLAIM T1
	LEFT JOIN CLAIM_INVOICE_LOG T3 ON T1.CLAIM_ID = T3.CLAIM_ID AND T3.CLAIM_INVOICE_LOG_ID IN (SELECT MAX(CLAIM_INVOICE_LOG_ID) FROM CLAIM_INVOICE_LOG WHERE CLAIM_ID = T1.CLAIM_ID AND STATUS = 'S')
	LEFT JOIN CLAIM_INVOICE_DETAILS_LOG T4 ON T3.CLAIM_INVOICE_LOG_ID = T4.CLAIM_INVOICE_LOG_ID
	LEFT JOIN AWARD_REVENUE_TRANSACTIONS T2 ON T1.CLAIM_NUMBER = T2.TRANSACTION_REFERENCE_NUMBER AND  T2.INTERNAL_ORDER_CODE = T4.GRT_WBS AND
	T2.REFERENCE_DOCUMENT_NUMBER = T3.OUTPUT_DOCUMENT_NUMBER  AND T2.PAYMENT_DATE IS NOT NULL
	WHERE T1.CLAIM_STATUS_CODE = '10';
	IF LI_FLAG > 0 THEN
		BEGIN
		DECLARE DONE3 INT DEFAULT FALSE;
		DECLARE CUR_SUMMARY_DATA CURSOR FOR
		SELECT distinct T1.CLAIM_ID,T3.CLAIM_INVOICE_LOG_ID,T3.CLAIM_NUMBER FROM CLAIM T1
		LEFT JOIN CLAIM_INVOICE_LOG T3 ON T1.CLAIM_ID = T3.CLAIM_ID AND T3.CLAIM_INVOICE_LOG_ID IN (SELECT MAX(CLAIM_INVOICE_LOG_ID) FROM CLAIM_INVOICE_LOG WHERE CLAIM_ID = T1.CLAIM_ID AND STATUS = 'S')
		LEFT JOIN CLAIM_INVOICE_DETAILS_LOG T4 ON T3.CLAIM_INVOICE_LOG_ID = T4.CLAIM_INVOICE_LOG_ID
		LEFT JOIN AWARD_REVENUE_TRANSACTIONS T2 ON T1.CLAIM_NUMBER = T2.TRANSACTION_REFERENCE_NUMBER AND  T2.INTERNAL_ORDER_CODE = T4.GRT_WBS AND
		T2.REFERENCE_DOCUMENT_NUMBER = T3.OUTPUT_DOCUMENT_NUMBER  AND T2.PAYMENT_DATE IS NOT NULL
		WHERE T1.CLAIM_STATUS_CODE = '10';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
		OPEN CUR_SUMMARY_DATA;
		INSERT_LOOP3: LOOP
		FETCH CUR_SUMMARY_DATA INTO
		LI_CLAIM_ID, LI_INVOICE_LOG_ID, LS_CLAIM_NUMBER;
		IF DONE3 THEN
			LEAVE INSERT_LOOP3;
		END IF;
		SELECT COUNT(1) INTO LI_COUNT FROM CLAIM_INVOICE_DETAILS_LOG WHERE CLAIM_INVOICE_LOG_ID = LI_INVOICE_LOG_ID;
		SELECT COUNT(distinct t3.REVENUE_TRACKER_ID) INTO LI_COUNT_2 FROM CLAIM_INVOICE_DETAILS_LOG T1
		INNER JOIN CLAIM_INVOICE_LOG T2 ON T1.CLAIM_INVOICE_LOG_ID = T2.CLAIM_INVOICE_LOG_ID
		INNER JOIN AWARD_REVENUE_TRANSACTIONS T3 ON T2.CLAIM_NUMBER = T3.TRANSACTION_REFERENCE_NUMBER AND  T3.INTERNAL_ORDER_CODE = T1.GRT_WBS AND
		T3.REFERENCE_DOCUMENT_NUMBER = T2.OUTPUT_DOCUMENT_NUMBER  AND T3.PAYMENT_DATE IS NOT NULL
		WHERE T2.CLAIM_ID = LI_CLAIM_ID AND t2.CLAIM_INVOICE_LOG_ID in (select max(CLAIM_INVOICE_LOG_ID) from CLAIM_INVOICE_LOG where status = 'S' and claim_id = T2.CLAIM_ID );
		IF LI_COUNT = LI_COUNT_2 THEN
			SELECT distinct max(T3.DOCUMENT_DATE),max(T3.PAYMENT_DATE) INTO LD_DOCUMENT_DATE,LD_PAYMENT_DATE FROM CLAIM_INVOICE_DETAILS_LOG T1
			INNER JOIN CLAIM_INVOICE_LOG T2 ON T1.CLAIM_INVOICE_LOG_ID = T2.CLAIM_INVOICE_LOG_ID
			INNER JOIN AWARD_REVENUE_TRANSACTIONS T3 ON T2.CLAIM_NUMBER = T3.TRANSACTION_REFERENCE_NUMBER AND  T3.INTERNAL_ORDER_CODE = T1.GRT_WBS AND
			T3.REFERENCE_DOCUMENT_NUMBER = T2.OUTPUT_DOCUMENT_NUMBER   AND T3.PAYMENT_DATE IS NOT NULL
			WHERE T2.CLAIM_ID = LI_CLAIM_ID
            AND T3.REVENUE_TRACKER_ID IN (SELECT MAX(REVENUE_TRACKER_ID) FROM AWARD_REVENUE_TRANSACTIONS WHERE TRANSACTION_REFERENCE_NUMBER = T2.CLAIM_NUMBER)
			AND t2.CLAIM_INVOICE_LOG_ID in (select max(CLAIM_INVOICE_LOG_ID) from CLAIM_INVOICE_LOG where status = 'S' and claim_id = T2.CLAIM_ID );
			UPDATE CLAIM SET CLAIM_STATUS_CODE = 4, DOCUMENT_DATE = LD_DOCUMENT_DATE, PAYMENT_DATE = LD_PAYMENT_DATE WHERE CLAIM_ID = LI_CLAIM_ID;
		END IF;
		END LOOP;
		CLOSE CUR_SUMMARY_DATA;
		END;
	END IF;
 END
$$
DELIMITER ;
