DELIMITER $$
CREATE  PROCEDURE `VALIDATE_CREATE_TASK`(
AV_AWARD_ID		VARCHAR(10),
AV_TASK_TYPE	VARCHAR(10),
AV_TASK_ID		VARCHAR(10)
)
BEGIN
	DECLARE MANPOWER_TASK_DESCRIPTION VARCHAR(255);
	DECLARE CONFIRM_PROJECT_TASK_DESCRIPTION VARCHAR(255);
	IF AV_TASK_TYPE IN (2, 5) AND AV_TASK_ID = '' THEN
		SELECT DESCRIPTION INTO MANPOWER_TASK_DESCRIPTION FROM TASK_TYPE WHERE TASK_TYPE_CODE = 2;
        SELECT DESCRIPTION INTO CONFIRM_PROJECT_TASK_DESCRIPTION FROM TASK_TYPE WHERE TASK_TYPE_CODE = 5;
    END IF;
END
$$
DELIMITER ;
