-- `APPROVE_TASK_STOPS`; 

CREATE PROCEDURE `APPROVE_TASK_STOPS`(
MESSAGE TEXT,
STOP_NUMBER INT)
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE DONE1 TINYINT DEFAULT 0;
DECLARE LS_FILTER_CONDITION VARCHAR(200);
DECLARE C1 CURSOR FOR 
	SELECT T1.MODULE_ITEM_ID,T2.APPROVER_PERSON_ID,T3.USER_NAME FROM WORKFLOW T1
	INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
	INNER JOIN PERSON T3 ON T2.APPROVER_PERSON_ID = T3.PERSON_ID
	WHERE T1.MODULE_ITEM_ID IN(
    SELECT AWARD_ID FROM AWARD WHERE AWARD_ID IN (6778)
    )
    AND T1.MODULE_CODE = 1
	AND T1.SUB_MODULE_ITEM_ID = 0
	AND T1.SUB_MODULE_CODE = 0
    AND T1.IS_WORKFLOW_ACTIVE = 'Y'
    AND T2. APPROVAL_STOP_NUMBER = STOP_NUMBER AND T2.PRIMARY_APPROVER_FLAG = 'Y';
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE AWARD_ID VARCHAR(40);
	DECLARE LS_PERSON_ID VARCHAR(40);
	DECLARE LS_USER_NAME VARCHAR(20);
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
FETCH C1 INTO AWARD_ID, LS_PERSON_ID, LS_USER_NAME;
BLOCK2: BEGIN
	DECLARE C2 CURSOR FOR 
    SELECT T2.TASK_ID FROM TASK T2 WHERE T2.MODULE_ITEM_ID = AWARD_ID;
    OPEN C2;
	LOOP2: LOOP BEGIN
        DECLARE TASK_ID VARCHAR(40);
    DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE1 = 1;
	FETCH C2 INTO TASK_ID;
    IF DONE1 THEN
	LEAVE LOOP2;
	END IF;
	SET LS_FILTER_CONDITION = FN_WORKFLOW_APPROVE(AWARD_ID, 1, LS_PERSON_ID, LS_USER_NAME, MESSAGE, 'A', 2, TASK_ID);
        END; 
		END LOOP;
	CLOSE C2;
	END BLOCK2;
IF DONE THEN
LEAVE LOOP1;
END IF;
END;
END LOOP;
CLOSE C1;
END
