-- `AWARD_DMP_REMAINDER_MARCH`; 

CREATE PROCEDURE `AWARD_DMP_REMAINDER_MARCH`( AV_DAYS INT )
BEGIN
	DECLARE AV_REMAINDER_DATE DATE;
	DECLARE AV_SCHEDULED_DAY INT;
	DECLARE AV_SCHEDULED_MONTH INT;
	SET AV_SCHEDULED_DAY = 1;
    SET AV_SCHEDULED_MONTH = 3;
	SET AV_REMAINDER_DATE = date(DATE_ADD(utc_timestamp(),INTERVAL AV_DAYS DAY));
	SELECT 0 AS SUB_MODULE_ITEM_KEY, AWARD_ID AS MODULE_ITEM_KEY, 1 AS MODULE_CODE, 0 AS SUB_MODULE_CODE, FINAL_EXPIRATION_DATE as EXP FROM AWARD
	WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
	AND (YEAR(FINAL_EXPIRATION_DATE) >= YEAR(utc_timestamp)) AND (MONTH(FINAL_EXPIRATION_DATE) > AV_SCHEDULED_MONTH) 
	AND (MONTH(AV_REMAINDER_DATE) = AV_SCHEDULED_MONTH) AND (DAY(AV_REMAINDER_DATE) = AV_SCHEDULED_DAY);			
END
