-- `DELETE_AWARD_MASTER_DATA`; 

CREATE PROCEDURE `DELETE_AWARD_MASTER_DATA`(AV_ID INT)
BEGIN
DECLARE LI_OLD_AWARD_ID 		INT;
DECLARE LS_AWARD_NUMBER			VARCHAR(12);
DECLARE LI_OLD_SEQUENCE_NUMBER 	INT(4);
DECLARE LI_AWARD_ID				INT;
DECLARE LS_ERROR_MSG	VARCHAR(1000);
DECLARE LS_TABLE_NAME	VARCHAR(30);
DECLARE LI_FLAG			INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
					 
					SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
					
					SELECT @full_error INTO LS_ERROR_MSG;
																	
					INSERT INTO AWARD_ERROR_LOG(AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, ERROR_MESSAGE, PROCEDURE_NAME, TABLE_NAME,SECTION_CODE,VARIATION_TYPE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_AWARD_ID,LS_AWARD_NUMBER,0,LS_ERROR_MSG,'DELETE_AWARD_MASTER_DATA',NULL,NULL,null,UTC_TIMESTAMP(),'admin');
					COMMIT;
					
					
				END;
				SET SQL_SAFE_UPDATES = 0;
				
				BEGIN
					
					DECLARE DONE1 INT DEFAULT FALSE;
					DECLARE CUR_AWARD_DATA CURSOR FOR
					SELECT OLD_AWARD_ID,OLD_AWARD_NUMBER,OLD_SEQUENCE_NUMBER,NEW_AWARD_ID
					FROM TEMP_AWARD_MASTER_DATA;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
					OPEN CUR_AWARD_DATA;
					INSERT_AWARD_LOOP: LOOP 
					FETCH CUR_AWARD_DATA INTO
					LI_OLD_AWARD_ID,
					LS_AWARD_NUMBER,
					LI_OLD_SEQUENCE_NUMBER,
					LI_AWARD_ID;
					
					IF DONE1 THEN
						LEAVE INSERT_AWARD_LOOP;
					END IF;
					
					DELETE FROM AWARD_SCIENCE_KEYWORD
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_RESEARCH_AREAS
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_KPI_CRITERIA
					WHERE AWARD_KPI_ID IN(SELECT AWARD_KPI_ID FROM AWARD_KPI
									  WHERE AWARD_ID = LI_AWARD_ID
									  );
									  
					DELETE
					FROM AWARD_KPI
					WHERE AWARD_ID = LI_AWARD_ID;
									  
					DELETE FROM AWARD_BUDGET_DET_CAL_AMT
					WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
											WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																	   WHERE AWARD_ID = LI_AWARD_ID
																	  )
										   );
					DELETE FROM AWARD_BUDGET_NON_PERSON_DETAIL
					WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
											WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																	   WHERE AWARD_ID = LI_AWARD_ID
																	  )
										   );
					DELETE FROM AWARD_BUDGET_PERSON_DETAIL 
					WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
											WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																	   WHERE AWARD_ID = LI_AWARD_ID
																	  )
										   );
										   
					DELETE FROM AWARD_BUDGET_RATE_AND_BASE
					WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
											WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																	   WHERE AWARD_ID = LI_AWARD_ID
																	  )
										   );
										   
					DELETE FROM AWARD_BUDGET_DETAIL
					WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
										   WHERE AWARD_ID = LI_AWARD_ID
										  );
										  
					DELETE FROM AWARD_BUDGET_PERIOD
					WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
										   WHERE AWARD_ID = LI_AWARD_ID
										  );
										  
					DELETE
					FROM AWARD_BUDGET_PERSONS		
					WHERE BUDGET_HEADER_ID IN(SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = LI_AWARD_ID);
					
					DELETE
					FROM AWARD_RATES		
					WHERE BUDGET_HEADER_ID IN(SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = LI_AWARD_ID);
										  
					DELETE FROM AWARD_BUDGET_HEADER
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_CONTACT
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_COST_SHARE 
					WHERE AWARD_ID = LI_AWARD_ID;
					
					DELETE FROM QUEST_ANSWER_ATTACHMENT
					WHERE QUESTIONNAIRE_ANSWER_ID IN(SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER
												 WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
																					 FROM QUEST_ANSWER_HEADER
																					 WHERE MODULE_ITEM_CODE = 1
																					 AND MODULE_SUB_ITEM_CODE = 3
																					 AND MODULE_ITEM_KEY = LI_AWARD_ID
																					)
												);
					DELETE FROM QUEST_ANSWER
					WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
													 FROM QUEST_ANSWER_HEADER
													 WHERE MODULE_ITEM_CODE = 1
													 AND MODULE_SUB_ITEM_CODE = 3
													 AND MODULE_ITEM_KEY = LI_AWARD_ID
													 );
					
												
					DELETE
					FROM QUEST_ANSWER_HEADER
					WHERE MODULE_ITEM_CODE = 1
					AND MODULE_SUB_ITEM_CODE = 3
					AND MODULE_ITEM_KEY = LI_AWARD_ID;
												
					DELETE
					FROM AWARD_FUNDING_PROPOSALS 
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE 
					FROM AWARD_PERSON_UNIT
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE 
					FROM AWARD_PERSON_ATTACHMNT
					WHERE AWARD_PERSON_ID IN (SELECT AWARD_PERSON_ID FROM AWARD_PERSONS
										  WHERE AWARD_ID = LI_AWARD_ID
										  );
					DELETE
					FROM AWARD_PERSONS WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_MANPOWER
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE 
					FROM AWARD_MANPOWER_RESOURCE
					WHERE AWARD_MANPOWER_ID IN(SELECT AWARD_MANPOWER_ID FROM AWARD_MANPOWER
										   WHERE AWARD_ID = LI_AWARD_ID);
										   
					DELETE
					FROM AWARD_MILESTONE
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM CUSTOM_DATA 
					WHERE MODULE_ITEM_KEY = LI_AWARD_ID
					AND MODULE_ITEM_CODE = 1
					AND MODULE_SUB_ITEM_CODE = 0
					AND MODULE_SUB_ITEM_KEY = 0;
					DELETE
					FROM AWARD_PUBLICATIONS 
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_ACHIEVEMENTS_ATTACHMENTS 
					WHERE AWARD_ID = LI_AWARD_ID;
					
					DELETE
					FROM AWARD_ASSOC_DETAIL
					WHERE AWARD_ASSOCIATION_ID IN(SELECT AWARD_ASSOCIATION_ID FROM AWARD_ASSOCIATION
											      WHERE AWARD_ID = LI_AWARD_ID);
						
					DELETE
					FROM AWARD_ASSOCIATION
					WHERE AWARD_ID = LI_AWARD_ID;
					
					DELETE
					FROM AWARD_PROJECT_TEAM
					WHERE AWARD_ID = LI_AWARD_ID;
					
					
													 
					DELETE FROM QUEST_ANSWER_ATTACHMENT
					WHERE QUESTIONNAIRE_ANSWER_ID IN(SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER
												 WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
																					 FROM QUEST_ANSWER_HEADER
																					 WHERE MODULE_ITEM_CODE = 1
																					 AND MODULE_SUB_ITEM_CODE = 0
																					 AND MODULE_ITEM_KEY = LI_AWARD_ID
																					)
												);
						
					DELETE FROM QUEST_ANSWER
					WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
													 FROM QUEST_ANSWER_HEADER
													 WHERE MODULE_ITEM_CODE = 1
													 AND MODULE_SUB_ITEM_CODE = 0
													 AND MODULE_ITEM_KEY = LI_AWARD_ID
													 );
												
					DELETE
					FROM QUEST_ANSWER_HEADER
					WHERE MODULE_ITEM_CODE = 1
					AND MODULE_SUB_ITEM_CODE = 0
					AND MODULE_ITEM_KEY = LI_AWARD_ID;
					
					DELETE
					FROM AWARD_REPORT_TRACKING_FILE
					WHERE AWARD_ID = LI_AWARD_ID;	
					DELETE
					FROM AWARD_REPORT_TRACKING
					WHERE AWARD_ID = LI_AWARD_ID;
					
					DELETE
					FROM AWARD_REPORT_TERM_RECIPIENT
					WHERE AWARD_ID = LI_AWARD_ID;
					
					DELETE
					FROM AWARD_REPORT_TERMS
					WHERE AWARD_ID = LI_AWARD_ID;
				
					DELETE
					FROM AWARD_PERSON_ROLES
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_APPROVED_EQUIPMENT 
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_APPROVED_FOREIGN_TRAVEL 
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_SPECIAL_REVIEW 
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_APPROVED_SUBAWARDS 
					WHERE AWARD_ID = LI_AWARD_ID;
					DELETE
					FROM AWARD_SPONSOR_TERM
					WHERE AWARD_ID = LI_AWARD_ID;
					
					DELETE FROM 
					AWARD WHERE AWARD_ID = LI_AWARD_ID;
					
					UPDATE AWARD SET AWARD_SEQUENCE_STATUS = 'ACTIVE'
					WHERE AWARD_ID = LI_OLD_AWARD_ID;
					
					END LOOP;
					CLOSE CUR_AWARD_DATA;
				
				END;
END
