-- `GET_AWARD_REPORT_REQ_BASE_DATES`; 

CREATE PROCEDURE `GET_AWARD_REPORT_REQ_BASE_DATES`( AV_AWARD_ID INT )
    DETERMINISTIC
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LI_AWARD_NUMBER VARCHAR(20);
DECLARE LI_AWARD_BEGIN_DATE DATETIME;
DECLARE LI_AWARD_FINAL_EXPIRATION_DATE DATETIME;
DECLARE LI_BASE_DATE VARCHAR(200);
DECLARE LI_FINANCIAL_YEAR VARCHAR(200);
DECLARE LI_CALENDAR_YEAR VARCHAR(200);
DECLARE LI_PROJECT_START_YEAR VARCHAR(200);
DECLARE LI_PROJECT_END_YEAR VARCHAR(200);
DECLARE LS_BASE_DATE_REP_15_APR DATETIME;
DECLARE LS_BASE_DATE_REP_30_APR DATETIME;
DECLARE LS_BASE_DATE_REP_31_MAY DATETIME;
DECLARE LS_BASE_DATE_REP_30_SEP DATETIME;
DECLARE LS_BASE_DATE_REP_31_DEC DATETIME;
DECLARE LS_BASE_DATE_REP_15_MONTH DATETIME;
 
SET LS_DYN_SQL ='';
SET LI_BASE_DATE = '';
SET LI_FINANCIAL_YEAR = '';
SET LI_CALENDAR_YEAR = '';
SET LI_PROJECT_START_YEAR = '';
SELECT T1.AWARD_NUMBER,T1.BEGIN_DATE,T1.FINAL_EXPIRATION_DATE 
INTO LI_AWARD_NUMBER,LI_AWARD_BEGIN_DATE,LI_AWARD_FINAL_EXPIRATION_DATE FROM AWARD T1
WHERE T1.AWARD_ID = AV_AWARD_ID;
SELECT YEAR(LI_AWARD_BEGIN_DATE) INTO LI_PROJECT_START_YEAR FROM DUAL;
	IF (MONTH(LI_AWARD_BEGIN_DATE) > 3) THEN
		SET LI_BASE_DATE = CONVERT(CONCAT(DATE_FORMAT(DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 1 YEAR), '%Y-'), '04','-','01'), DATETIME);
	ELSE 
		SET LI_BASE_DATE = CONVERT(CONCAT(DATE_FORMAT(LI_AWARD_BEGIN_DATE, '%Y-'), '04','-','01'), DATETIME);
	END IF;
	IF (LI_BASE_DATE < LI_AWARD_FINAL_EXPIRATION_DATE) THEN
		SET LI_FINANCIAL_YEAR =  LI_BASE_DATE;
	 END IF;
	SET LI_BASE_DATE = CONVERT(CONCAT(DATE_FORMAT(DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 1 YEAR), '%Y-'), '01','-','01'), DATETIME);
	IF (LI_BASE_DATE < LI_AWARD_FINAL_EXPIRATION_DATE) THEN
		SET LI_CALENDAR_YEAR =  LI_BASE_DATE;
	END IF;
	IF (DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 3 MONTH) < CONCAT(YEAR(LI_AWARD_BEGIN_DATE),'-04-15')) THEN
		SET LS_BASE_DATE_REP_15_APR = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE)),'-04-15'), DATETIME);
	  ELSE 
		SET LS_BASE_DATE_REP_15_APR = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE) + 1),'-04-15'), DATETIME);
	END IF;
	IF (DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 3 MONTH) < CONCAT(YEAR(LI_AWARD_BEGIN_DATE),'-04-30')) THEN
		SET LS_BASE_DATE_REP_30_APR = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE)),'-04-30'), DATETIME);
	  ELSE 
		SET LS_BASE_DATE_REP_30_APR = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE) + 1),'-04-30'), DATETIME);
	END IF;
    IF (DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 3 MONTH) < CONCAT(YEAR(LI_AWARD_BEGIN_DATE),'-05-31')) THEN
		SET LS_BASE_DATE_REP_31_MAY = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE)),'-05-31'), DATETIME);
	  ELSE 
		SET LS_BASE_DATE_REP_31_MAY = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE) + 1),'-05-31'), DATETIME);
	END IF;
    IF (DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 3 MONTH) < CONCAT(YEAR(LI_AWARD_BEGIN_DATE),'-09-30')) THEN
		SET LS_BASE_DATE_REP_30_SEP = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE)),'-09-30'), DATETIME);
	  ELSE 
		SET LS_BASE_DATE_REP_30_SEP = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE) + 1),'-09-30'), DATETIME);
	END IF;
    IF (DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 3 MONTH) < CONCAT(YEAR(LI_AWARD_BEGIN_DATE),'-12-31')) THEN
		SET LS_BASE_DATE_REP_31_DEC = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE)),'-12-31'), DATETIME);
	  ELSE 
		SET LS_BASE_DATE_REP_31_DEC = CONVERT(CONCAT((YEAR(LI_AWARD_BEGIN_DATE) + 1),'-12-31'), DATETIME);
	END IF;
	SET LS_BASE_DATE_REP_15_MONTH = DATE_ADD(LI_AWARD_BEGIN_DATE, INTERVAL 15 MONTH);
	SET LS_DYN_SQL = CONCAT('SELECT 1 AS FREQUENCY_BASE_CODE, AWARD_EFFECTIVE_DATE AS BASE_DATE 
								FROM AWARD WHERE AWARD_ID = ',AV_AWARD_ID,'
							UNION
								SELECT 2 AS FREQUENCY_BASE_CODE, ''',LI_AWARD_BEGIN_DATE,''' AS BASE_DATE 
							UNION
							   (SELECT 3 AS FREQUENCY_BASE_CODE, OBLIGATION_EXPIRATION_DATE AS BASE_DATE
								FROM AWARD_AMOUNT_INFO T1 
								INNER JOIN AWARD_AMOUNT_TRANSACTION T2 ON T1.TRANSACTION_ID = T2.TRANSACTION_ID
								WHERE T1.AWARD_AMOUNT_INFO_ID IN (SELECT MAX(T2.AWARD_AMOUNT_INFO_ID) FROM AWARD_AMOUNT_INFO T2 
								INNER JOIN AWARD_AMOUNT_TRANSACTION T3 ON T2.TRANSACTION_ID = T3.TRANSACTION_ID
								WHERE  T2.AWARD_NUMBER = ''',LI_AWARD_NUMBER,'''))
							UNION 
								SELECT 4 AS FREQUENCY_BASE_CODE, ''',LI_AWARD_FINAL_EXPIRATION_DATE,''' AS BASE_DATE 
							UNION
							   (SELECT 5 AS FREQUENCY_BASE_CODE, CURRENT_FUND_EFFECTIVE_DATE AS BASE_DATE
								FROM AWARD_AMOUNT_INFO T1 
								INNER JOIN AWARD_AMOUNT_TRANSACTION T2 ON T1.TRANSACTION_ID = T2.TRANSACTION_ID
								WHERE T1.AWARD_AMOUNT_INFO_ID IN (SELECT MAX(T2.AWARD_AMOUNT_INFO_ID) FROM AWARD_AMOUNT_INFO T2 
								INNER JOIN AWARD_AMOUNT_TRANSACTION T3 ON T2.TRANSACTION_ID = T3.TRANSACTION_ID
								WHERE T2.AWARD_NUMBER = ''',LI_AWARD_NUMBER,'''))
							UNION  
								SELECT 7 AS FREQUENCY_BASE_CODE, ''',LI_FINANCIAL_YEAR,''' AS BASE_DATE
							UNION
								SELECT 8 AS FREQUENCY_BASE_CODE, ''',LI_CALENDAR_YEAR,''' AS BASE_DATE
							UNION
								SELECT 9 AS FREQUENCY_BASE_CODE, ''',LS_BASE_DATE_REP_15_APR,''' AS BASE_DATE
                                UNION
								SELECT 10 AS FREQUENCY_BASE_CODE, ''',LS_BASE_DATE_REP_30_APR,''' AS BASE_DATE
                                UNION
								SELECT 11 AS FREQUENCY_BASE_CODE, ''',LS_BASE_DATE_REP_31_MAY,''' AS BASE_DATE
                                UNION
								SELECT 12 AS FREQUENCY_BASE_CODE, ''',LS_BASE_DATE_REP_30_SEP,''' AS BASE_DATE
                                UNION
								SELECT 13 AS FREQUENCY_BASE_CODE, ''',LS_BASE_DATE_REP_31_DEC,''' AS BASE_DATE
                                UNION
								SELECT 14 AS FREQUENCY_BASE_CODE, ''',LS_BASE_DATE_REP_15_MONTH,''' AS BASE_DATE
							');
             
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
END
