-- `GET_MANPOWER_CLOSE_POSITION_LIST`; 

CREATE PROCEDURE `GET_MANPOWER_CLOSE_POSITION_LIST`()
BEGIN
select distinct t1.AWARD_ID, t1.AWARD_NUMBER,  t3.POSITION_ID,
	CASE
		WHEN (
				SELECT COUNT(distinct s1.POSITION_ID, s1.AWARD_NUMBER) 
				FROM AWARD_MANPOWER_RESOURCE  s1
				WHERE s1.POSITION_ID = t3.POSITION_ID
				and s1.POSITION_OWNED_BY_AWARD ='Y'
			) > 1 THEN "MULIPLE"		
		ELSE "SINGLE"
	END as EXCLUSION_TYPE,
	FN_CAMPUS_FOR_UNIT(t1.LEAD_UNIT_NUMBER) as SCHOOL 
	from award t1
	inner join award_manpower t2 on t2.AWARD_ID = t1.AWARD_ID
	inner join award_manpower_resource t3 on t3.AWARD_MANPOWER_ID = t2.AWARD_MANPOWER_ID
	where t1.AWARD_SEQUENCE_STATUS = 'ACTIVE' and t3.POSITION_ID is not null
	and t3.POSITION_OWNED_BY_AWARD = 'Y'
	and cast(t1.FINAL_EXPIRATION_DATE as DATE) = (CURDATE() - INTERVAL 15 DAY )
	and ( t3.PERSON_ID <> '999999999100' OR t3.PERSON_ID is null)
    UNION
    select distinct t1.AWARD_ID, t1.AWARD_NUMBER,  t3.POSITION_ID,
    "NIL" as EXCLUSION_TYPE,    
	FN_CAMPUS_FOR_UNIT(t1.LEAD_UNIT_NUMBER) as SCHOOL 
	from award t1
	inner join award_manpower t2 on t2.AWARD_ID = t1.AWARD_ID
	inner join award_manpower_resource t3 on t3.AWARD_MANPOWER_ID = t2.AWARD_MANPOWER_ID
	where t1.AWARD_SEQUENCE_STATUS = 'ACTIVE' and t3.POSITION_ID is not null
    and 0  = (
				SELECT COUNT(distinct s1.POSITION_ID, s1.AWARD_NUMBER) 
				FROM AWARD_MANPOWER_RESOURCE  s1
				WHERE s1.POSITION_ID = t3.POSITION_ID
				and s1.POSITION_OWNED_BY_AWARD ='Y'			
			 )
	and cast(t1.FINAL_EXPIRATION_DATE as DATE) = (CURDATE() - INTERVAL 15 DAY )
	and ( t3.PERSON_ID <> '999999999100' OR t3.PERSON_ID is null)  
	ORDER BY SCHOOL;
END
