-- `GET_AWARD_TIMESHEET_DASHBOARD`; 

CREATE PROCEDURE `GET_AWARD_TIMESHEET_DASHBOARD`(
        AV_AWARD_NUMBER         VARCHAR(20),
        AV_SPONSOR_AWARD_NUMBER VARCHAR(200),
        AV_TITLE                VARCHAR(1000),
		AV_PERSON_ID            VARCHAR(200),
        AV_LOGIN_PERSON_ID       VARCHAR(200),
		AV_LEAD_UNIT_NUMBER     VARCHAR(200),
        AV_SPONSOR_CODE         VARCHAR(200),
		AV_SORT_TYPE            VARCHAR(500),
        AV_PAGED                INT(10),
        AV_LIMIT                INT(10),
		AV_AWARD_TYPE_CODE      VARCHAR(200)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
SET LS_FILTER_CONDITION ='';
SET LS_DYN_SQL ='';
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
 IF AV_TITLE IS NOT NULL  AND AV_TITLE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' WHERE T.TITLE LIKE ''%',AV_TITLE,'%'' AND ');
        END IF;
 IF AV_AWARD_NUMBER IS NOT NULL  AND AV_AWARD_NUMBER <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' WHERE T.AWARD_NUMBER LIKE ''%',AV_AWARD_NUMBER,'%'' AND ');
        END IF;
 IF AV_SPONSOR_AWARD_NUMBER IS NOT NULL  AND AV_SPONSOR_AWARD_NUMBER <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' WHERE T.SPONSOR_AWARD_NUMBER LIKE ''%',AV_SPONSOR_AWARD_NUMBER,'%'' AND ');
	END IF;
 IF AV_LEAD_UNIT_NUMBER IS NOT NULL  AND AV_LEAD_UNIT_NUMBER <> '' THEN
				 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' WHERE T.LEAD_UNIT_NUMBER = ',AV_LEAD_UNIT_NUMBER,' AND ');
        END IF;
 IF AV_SPONSOR_CODE IS NOT NULL  AND AV_SPONSOR_CODE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' WHERE T.SPONSOR_CODE = ',AV_SPONSOR_CODE,' AND ');
        END IF;
 IF AV_AWARD_TYPE_CODE IS NOT NULL  AND AV_AWARD_TYPE_CODE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' WHERE T.AWARD_TYPE_CODE IN (',AV_AWARD_TYPE_CODE,') AND ');
        END IF;
SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
IF LS_FILTER_CONDITION <>'' THEN
        SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;
END IF;
IF AV_SORT_TYPE IS NULL THEN
        SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.CREATE_TIMESTAMP DESC ');
    ELSE
        SET AV_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
END IF;
SET LS_DYN_SQL = CONCAT('SELECT * FROM (  WITH ACCESS_TMP AS (
  SELECT UNIT_NUMBER
  FROM PERSON_ROLES T1
  INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
  INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
  WHERE T1.DESCEND_FLAG = ''N''
    AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
    AND RIGHT_NAME IN (''VIEW_AWARD'')
  UNION
  SELECT CHILD_UNIT_NUMBER
  FROM UNIT_WITH_CHILDREN
  WHERE UNIT_NUMBER IN (
    SELECT UNIT_NUMBER
    FROM PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
    WHERE T1.DESCEND_FLAG = ''Y''
      AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
      AND RIGHT_NAME IN (''VIEW_AWARD'')
  )),
    RIGHT_TIMESHEET AS (
  SELECT UNIT_NUMBER
  FROM PERSON_ROLES T1
  INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
  INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
  WHERE T1.DESCEND_FLAG = ''N''
      AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
    AND RIGHT_NAME IN ( ''VIEW_KEY_PERSON_TIMESHEET'', ''MAINTAIN_KEY_PERSON_TIMESHEET'')
    AND UNIT_NUMBER IN (SELECT * FROM ACCESS_TMP)
  UNION
  SELECT CHILD_UNIT_NUMBER
  FROM UNIT_WITH_CHILDREN
  WHERE UNIT_NUMBER IN (
    SELECT UNIT_NUMBER
    FROM PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
    INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
    WHERE T1.DESCEND_FLAG = ''Y''
        AND T1.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
       AND RIGHT_NAME IN (''VIEW_KEY_PERSON_TIMESHEET'', ''MAINTAIN_KEY_PERSON_TIMESHEET'')
        AND UNIT_NUMBER IN (SELECT * FROM ACCESS_TMP)))
SELECT  T1.AWARD_ID,
T1.AWARD_NUMBER,
T1.ACCOUNT_NUMBER,
T1.TITLE,
T2.FULL_NAME,
T3.SPONSOR_CODE,
T3.DISPLAY_NAME AS SPONSOR_NAME,
T3.ACRONYM,
T5.DESCRIPTION AS AWARD_TYPE,
T6.DISPLAY_NAME AS UNIT_NAME ,
T1.LEAD_UNIT_NUMBER,
T1.SPONSOR_AWARD_NUMBER,
T1.AWARD_SEQUENCE_STATUS,
T1.FINAL_EXPIRATION_DATE,
T1.BEGIN_DATE,
T1.AWARD_EXECUTION_DATE,
T1.AWARD_EFFECTIVE_DATE,
T2.PERSON_ID,
T2.PERSON_ROLE_ID,
T2.AWARD_PERSON_ID,
T4.DESCRIPTION,
T1.AWARD_TYPE_CODE,
T1.CREATE_TIMESTAMP,
T13.NAME AS NAME,
(SELECT IFNULL(P2.FULL_NAME,R1.FULL_NAME) FROM
        AWARD_PERSONS P1
        LEFT JOIN PERSON P2 ON P1.PERSON_ID = P2.PERSON_ID
        LEFT JOIN ROLODEX R1 ON P1.ROLODEX_ID = R1.ROLODEX_ID
        WHERE P1.AWARD_ID = T1.AWARD_ID AND P1.PI_FLAG = ''Y''
        ) AS PI_NAME,
CASE WHEN T1.LEAD_UNIT_NUMBER   IN (SELECT * FROM RIGHT_TIMESHEET)AND T1.AWARD_SEQUENCE_STATUS = ''ACTIVE''
 THEN ''Y'' ELSE ''N'' END AS IS_TIMESHEET_RIGHT_EXIST
FROM AWARD T1
LEFT JOIN GRANT_CALL_HEADER T13 ON T13.GRANT_HEADER_ID = T1.GRANT_HEADER_ID
INNER JOIN  AWARD_PERSONS T2 ON T2.AWARD_ID = T1.AWARD_ID
INNER JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T1.SPONSOR_CODE
INNER JOIN EPS_PROP_PERSON_ROLE T4 ON T4.PROP_PERSON_ROLE_ID = T2.PERSON_ROLE_ID
LEFT JOIN AWARD_TYPE T5 ON T5.AWARD_TYPE_CODE = T1.AWARD_TYPE_CODE
LEFT JOIN UNIT T6 ON T6.UNIT_NUMBER = T1.LEAD_UNIT_NUMBER
WHERE
 (
EXISTS ( SELECT 1 FROM AWARD_PERSON_ROLES APR
INNER JOIN ROLE_RIGHTS RR ON  APR.ROLE_ID = RR.ROLE_ID
INNER JOIN RIGHTS R ON RR.RIGHT_ID = R.RIGHT_ID
WHERE R.RIGHT_NAME = ''VIEW_AWARD'' AND APR.PERSON_ID = ''',AV_LOGIN_PERSON_ID,'''
AND APR.AWARD_ID = T1.AWARD_ID )
OR
T1.LEAD_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM ACCESS_TMP)
)
AND  T2.PERSON_ROLE_ID IN (1,3)
AND T1.AWARD_SEQUENCE_STATUS = ''ACTIVE''
AND T2.PERSON_ID =   ''',AV_PERSON_ID,''')T',LS_FILTER_CONDITION,' ',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION);
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
 END
