-- `GET_AWARD_EXPENSE_TRACKER_REPORT`; 

CREATE PROCEDURE `GET_AWARD_EXPENSE_TRACKER_REPORT`()
BEGIN
SELECT T3.UNIT_NUMBER,T3.UNIT_NAME, T3.CAMPUS,
				T1.ACCOUNT_NUMBER,T1.INTERNAL_ORDER_CODE,T1.REMARKS,T1.AMOUNT_IN_FMA_CURRENCY,  
				T1.ACTUAL_OR_COMMITTED_FLAG,T1.PO_PR_FLAG,T1.BANK_CLEARING_DATE,T1.FM_POSTING_DATE  
				,T1.FI_POSTING_DATE,T1.VENDOR_CODE,T1.VENDOR_NAME,T1.DOCUMENT_DATE,T1.FI_GL_ACCOUNT,  
				T1.FI_GL_DESCRIPTION,T1.GR_DATE,T1.INVOICE_DATE,T1.PR_DATE,T1.REQUESTER_NAME,T1.TRANSACTION_REFERENCE_NUMBER,  
				T1.DOCUMENT_NUMBER,T1.PO_DATE,T1.ITEM_NUMBER,T1.REFERENCE_DOCUMENT_CATEGORY,T1.REFERENCE_ORG_UNIT,T1.ACCT_ASSIGNMENT_NUMBER, 
				T1.SCHEDULE_LINE_NUMBER,T1.CONDITION_COUNTER,T1.REFERENCE_PROCEDURE,
				T1.DOCUMENT_NUMBER_FM_LINE_ITEM,T1.NUMBER_OF_POST_FM_LINE_ITEM,T1.COMPANY_CODE,
				T1.VALUE_TYPE,T1.AMOUNT_TYPE,T1.FISCAL_YEAR,T1.BATCH_ID,T1.FM_AREA,
				T1.FUND,T1.FUND_CENTER,T1.FUNCTIONAL_AREA FROM AWARD_EXPENSE_TRANSACTIONS T1 
				LEFT OUTER JOIN AWARD T2 ON T2.ACCOUNT_NUMBER = T1.ACCOUNT_NUMBER AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
				LEFT OUTER JOIN UNIT T3 ON T3.UNIT_NUMBER = T2.LEAD_UNIT_NUMBER 
				WHERE T1.FILE_ID is not null;
END
