-- `GET_DMP_AWARD_DATA`; 

CREATE PROCEDURE `GET_DMP_AWARD_DATA`(
AV_PARENT_QUESTION_ID INT
)
BEGIN
DECLARE LI_QUESTIONNAIRE_ANS_HEADER_ID 	INT(12);
DECLARE LS_MODULE_ITEM_KEY 				VARCHAR(20);
DECLARE LI_QUESTIONNAIRE_ANSWER_ID 		INT(12);
DECLARE LS_ANSWER 				 	 	VARCHAR(4000);
DECLARE LS_SEL_STMT 					LONGTEXT;
DECLARE LI_OTHER_QUESTION_ID			INT(12);
DECLARE LI_FLAG 						INT(3);
	BEGIN 
			DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE CUR_QUEST_ANSWER CURSOR FOR
			SELECT 
				T1.QUESTIONNAIRE_ANS_HEADER_ID,
				T1.MODULE_ITEM_KEY
			FROM QUEST_ANSWER_HEADER T1
			WHERE T1.QUESTIONNAIRE_ID = 1227
			AND T1.MODULE_ITEM_CODE = 1
			AND T1.MODULE_SUB_ITEM_CODE = 3;
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN CUR_QUEST_ANSWER;
			INSERT_LOOP: LOOP 
			FETCH CUR_QUEST_ANSWER INTO
			LI_QUESTIONNAIRE_ANS_HEADER_ID,
			LS_MODULE_ITEM_KEY;
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
			BEGIN
				DECLARE DONE2 INT DEFAULT FALSE;
				DECLARE CUR_SEL_ANS CURSOR FOR
				SELECT 
					T3.ANSWER
				FROM QUEST_ANSWER T3 
				WHERE  T3.QUESTIONNAIRE_ANS_HEADER_ID = LI_QUESTIONNAIRE_ANS_HEADER_ID
				AND T3.QUESTION_ID = AV_PARENT_QUESTION_ID;
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
				OPEN CUR_SEL_ANS;
				INSERT_LOOP2: LOOP 
				FETCH CUR_SEL_ANS INTO 
				LS_ANSWER;
				IF DONE2 THEN
					LEAVE INSERT_LOOP2;
				END IF; 
					SET LS_SEL_STMT:= CONCAT(IFNULL(LS_SEL_STMT,''),',',LS_ANSWER);
				END LOOP;
				CLOSE CUR_SEL_ANS;
				SELECT TRIM(both ',' FROM LS_SEL_STMT) INTO LS_SEL_STMT FROM DUAL;
			END;
			  BEGIN
				DECLARE DONE3 INT DEFAULT FALSE;
				DECLARE CUR_SEL_CONDITIONS CURSOR FOR
				SELECT T2.QUESTION_ID FROM quest_question_condition T1
				INNER JOIN QUEST_QUESTION T2 ON UPPER(TRIM(T1.GROUP_NAME)) = UPPER(TRIM(T2.GROUP_NAME))
				WHERE T1.QUESTION_ID = AV_PARENT_QUESTION_ID
				AND TRIM(T1.CONDITION_VALUE) not in (LS_SEL_STMT)
				AND T2.QUESTIONNAIRE_ID = 1227;
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
				OPEN CUR_SEL_CONDITIONS;
				INSERT_LOOP3: LOOP 
				FETCH CUR_SEL_CONDITIONS INTO 
				LI_OTHER_QUESTION_ID;
				IF DONE3 THEN
					LEAVE INSERT_LOOP3;
				END IF; 
				SELECT COUNT(1) INTO LI_FLAG
				FROM QUEST_ANSWER 
				WHERE QUESTIONNAIRE_ANS_HEADER_ID = LI_QUESTIONNAIRE_ANS_HEADER_ID
				AND QUESTION_ID = LI_OTHER_QUESTION_ID;
				IF LI_FLAG > 0 THEN
					UPDATE QUEST_ANSWER SET EXPLANATION = CONCAT('WRONG_DATA-',LS_MODULE_ITEM_KEY)
					WHERE QUESTIONNAIRE_ANS_HEADER_ID = LI_QUESTIONNAIRE_ANS_HEADER_ID
					AND QUESTION_ID = LI_OTHER_QUESTION_ID;
				END IF;
				END LOOP;
				CLOSE CUR_SEL_CONDITIONS;				
				END;
			END LOOP;
			CLOSE CUR_QUEST_ANSWER;
	END;
END
