-- `GET_AWARD_COST_SHARE`; 

CREATE PROCEDURE `GET_AWARD_COST_SHARE`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
SELECT 
        T1.AWARD_ID,
        T1.AWARD_NUMBER,
        T1.COST_SHARE_PERCENTAGE,
        T1.COST_SHARE_TYPE_CODE,
        T2.DESCRIPTION AS COST_SHARE_TYPE,
        T1.PROJECT_PERIOD,
        T1.COMMITMENT_AMOUNT
    FROM AWARD_COST_SHARE T1
    INNER JOIN COST_SHARE_TYPE T2 ON T1.COST_SHARE_TYPE_CODE = T2.COST_SHARE_TYPE_CODE
    WHERE T1.AWARD_ID = AV_AWARD_ID;
END
