-- `GET_AWARD_APPROVD_TRAVEL`; 

CREATE PROCEDURE `GET_AWARD_APPROVD_TRAVEL`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
SELECT  
    T1.AWARD_ID,
    T1.AWARD_NUMBER,
    T1.TRAVELER_NAME,
    T1.DESTINATION,
    T1.START_DATE,
    T1.END_DATE,
    T1.AMOUNT
    FROM AWARD_APPROVED_FOREIGN_TRAVEL T1
    WHERE AWARD_ID = AV_AWARD_ID;
END
