-- `GET_AWARD_FUNDED_PROPOSAL`; 

CREATE PROCEDURE `GET_AWARD_FUNDED_PROPOSAL`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
      SELECT 
       T1.AWARD_ID,
       T1.AWARD_NUMBER,
       T3.PROPOSAL_NUMBER,
       T4.FULL_NAME AS PI,
       T3.HOME_UNIT_NUMBER,
       T5.UNIT_NAME,
       T3.SPONSOR_CODE,
       T6.SPONSOR_NAME,
       DATE_FORMAT(T3.START_DATE,'%m/%d/%Y') AS START_DATE,
       DATE_FORMAT(T3.END_DATE,'%m/%d/%Y') AS END_DATE,
       T7.TOTAL_DIRECT_COST
    FROM AWARD T1
    INNER JOIN AWARD_FUNDING_PROPOSALS T2 ON T1.AWARD_ID = T2.AWARD_ID
    INNER JOIN PROPOSAL T3 ON T2.PROPOSAL_ID = T3.PROPOSAL_ID
	LEFT JOIN IP_BUDGET_HEADER T7 ON T7.PROPOSAL_ID = T3.PROPOSAL_ID
    LEFT OUTER JOIN PROPOSAL_PERSONS T4 ON T3.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3
    INNER JOIN UNIT T5 ON T3.HOME_UNIT_NUMBER = T5.UNIT_NUMBER
    INNER JOIN SPONSOR T6 ON T3.SPONSOR_CODE = T6.SPONSOR_CODE
    WHERE T1.AWARD_ID = AV_AWARD_ID;    
END
