-- `GET_AWARD_PERSON_DETAILS`; 

CREATE PROCEDURE `GET_AWARD_PERSON_DETAILS`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
 SELECT 
      T1.AWARD_ID,
      T1.AWARD_NUMBER,
      T2.PERSON_ID,
      T2.FULL_NAME,
      T2.PERSON_ROLE_ID as CONTACT_ROLE_CODE,
      T3.UNIT_NUMBER,
      T4.UNIT_NAME,
      T5.FULL_NAME AS PRNCPL_NM
      FROM AWARD T1
      LEFT OUTER JOIN AWARD_PERSONS T2 ON T1.AWARD_ID = T2.AWARD_ID
      LEFT OUTER JOIN AWARD_PERSON_UNIT T3 ON T2.AWARD_PERSON_ID = T3.AWARD_PERSON_ID 
      LEFT OUTER JOIN UNIT T4 ON T3.UNIT_NUMBER = T4.UNIT_NUMBER
      LEFT OUTER JOIN PERSON T5 ON T2.PERSON_ID = T5.PERSON_ID
      WHERE T1.AWARD_ID = AV_AWARD_ID;
END
