CREATE PROCEDURE `GET_AWARD_TABLE_COUNT`(
AV_TYPE					VARCHAR(20)
)
BEGIN

DECLARE LS_ERROR_MSG		VARCHAR(1000);
DECLARE LS_TABLE_NAME		VARCHAR(30);
DECLARE LI_FLAG				INT;

DECLARE AV_AWARD_ID			INT;
DECLARE LI_AWARD_ID			INT;
DECLARE LS_AWARD_NUMBER		VARCHAR(12);
DECLARE LI_SEQUENCE_NUMBER	INT;
DECLARE LI_SCIENCE_KEYWORD_CNT	INT(10);
DECLARE LI_AWARD_RSRCH_CNT		INT(10);
DECLARE LI_AWARD_KPI_CNT		INT(10);
DECLARE LI_AWARD_KPI_CRIT_CNT	INT(10);
DECLARE	LI_AWD_BUDGT_CAL_AMT_CNT 			INT(10);	
DECLARE LI_AWD_BUDGT_NON_PERSN_DTL_CNT		INT(10);
DECLARE LI_AWD_BUDGT_PERSN_DTL_CNT			INT(10);
DECLARE LI_AWD_BUDGT_RATE_BASE_CNT			INT(10);
DECLARE LI_AWD_BUDGT_DETL_ID_CNT			INT(10);
DECLARE LI_AWD_BUDGT_PERIOD_CNT				INT(10);
DECLARE LI_AWAD_RATE_ID_CNT					INT(10);
DECLARE	LI_AWD_BUDGT_HEADER_CNT				INT(10);
DECLARE LI_AWARD_CONTACT_CNT				INT(10);
DECLARE LI_TOTAL_COST_SHARE_CNT				INT(10);
DECLARE LI_QST_ANS_HDR_CNT					INT(10);
DECLARE	LI_QST_ANSWER_CNT					INT(10);
DECLARE	LI_QST_ANS_ATT_CNT					INT(10);
DECLARE LI_TOTAL_AWARD_FUNDING_PROP_CNT		INT(10);
DECLARE LI_AWARD_PERSON_UNIT_CNT			INT(10);
DECLARE LI_AWARD_PERSON_ATTACHMNT_CNT		INT(10);
DECLARE	LI_AWARD_PERSONS_CNT				INT(10);
DECLARE LI_AWARD_MANPWR_CNT					INT(10);
DECLARE	LI_AWD_MANPW_RES_CNT				INT(10);
DECLARE	LI_AWARD_MILE_ST_CNT				INT(10);
DECLARE	LI_TOTAL_AWARD_CUSTOM_CNT			INT(10);
DECLARE LI_TOTAL_AWARD_PUBLICATION_CNT		INT(10);
DECLARE LI_TOTAL_AWARD_ACHIEVMNT_ATTACH_CNT	INT(10);
DECLARE LI_AWAD_ASSOC_CNT					INT(10);
DECLARE LI_AWAD_ASSOC_DTL_CNT				INT(10);
DECLARE	LI_PROJECT_TEAM_CNT					INT(10);
DECLARE LI_QST_AWD_ANS_HDR_CNT 				INT(10);
DECLARE LI_QST_AWD_ANSWER_CNT 				INT(10);
DECLARE LI_QST_AWD_ANS_ATT_CNT 				INT(10);
DECLARE LI_AWARD_REPORT_TERMS_CNT			INT(10);
DECLARE LI_AWARD_REPT_TERM_RECPT_CNT		INT(10);
DECLARE LI_AWD_REPT_TRACK_CNT				INT(10);
DECLARE LI_AWARD_RPT_TRCK_FILE_CNT			INT(10);
DECLARE LI_AWARD_PERSON_ROLE_ID_CNT			INT(10);
DECLARE LI_AWARD_APPR_EQP_CNT			INT(10);
DECLARE LI_AWARD_APRVD_FOREIGN_TRA_CNT	INT(10);
DECLARE LI_AWARD_SPECIAL_REVIEW_CNT		INT(10);
DECLARE LI_AWARD_APPROVED_SUBAWARDS_CNT		INT(10);
DECLARE LI_SPONSOR_TERM_CNT					INT(10);


		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
															
			INSERT INTO AWARD_ERROR_LOG(AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, ERROR_MESSAGE, PROCEDURE_NAME, TABLE_NAME,SECTION_CODE,VARIATION_TYPE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,LS_ERROR_MSG,'GET_AWARD_TABLE_COUNT',NULL,NULL,null,UTC_TIMESTAMP(),'admin');
			COMMIT;
			
			
		END;
		
		BEGIN
					
			DECLARE DONE1 INT DEFAULT FALSE;

			DECLARE CUR_AWARD_DATA CURSOR FOR
			SELECT 
			AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER
			FROM AWARD 
			WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE';
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

			OPEN CUR_AWARD_DATA;
			INSERT_AWARD_LOOP: LOOP 
			FETCH CUR_AWARD_DATA INTO
			LI_AWARD_ID,
			LS_AWARD_NUMBER,
			LI_SEQUENCE_NUMBER;
			
			IF DONE1 THEN
				LEAVE INSERT_AWARD_LOOP;
			END IF;
			
			SELECT COUNT(1) INTO LI_SCIENCE_KEYWORD_CNT
			FROM AWARD_SCIENCE_KEYWORD
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_RSRCH_CNT
			FROM AWARD_RESEARCH_AREAS
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_KPI_CNT
			FROM AWARD_KPI
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO  LI_AWARD_KPI_CRIT_CNT
			FROM AWARD_KPI_CRITERIA
			WHERE AWARD_KPI_ID IN(SELECT AWARD_KPI_ID FROM AWARD_KPI
								  WHERE AWARD_ID = AV_AWARD_ID
								  );
								  
			SELECT COUNT(1) INTO LI_AWD_BUDGT_CAL_AMT_CNT FROM AWARD_BUDGET_DET_CAL_AMT
			WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
										WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																   WHERE AWARD_ID = AV_AWARD_ID
																  )
									   );
			
			SELECT COUNT(1) INTO LI_AWD_BUDGT_NON_PERSN_DTL_CNT FROM AWARD_BUDGET_NON_PERSON_DETAIL
			WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
										WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																   WHERE AWARD_ID = AV_AWARD_ID
																  )
									   );
			
			SELECT COUNT(1) INTO LI_AWD_BUDGT_PERSN_DTL_CNT FROM AWARD_BUDGET_PERSON_DETAIL 
			WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
										WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																   WHERE AWARD_ID = AV_AWARD_ID
																  )
									   );
									   
			SELECT COUNT(1) INTO LI_AWD_BUDGT_RATE_BASE_CNT FROM AWARD_BUDGET_RATE_AND_BASE
			WHERE BUDGET_DETAILS_ID IN (SELECT BUDGET_DETAILS_ID FROM AWARD_BUDGET_DETAIL
										WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
																   WHERE AWARD_ID = AV_AWARD_ID
																  )
									   );
									   
			SELECT COUNT(1) INTO LI_AWD_BUDGT_DETL_ID_CNT FROM AWARD_BUDGET_DETAIL
			WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
									   WHERE AWARD_ID = AV_AWARD_ID
									  );
									  
			SELECT COUNT(1) INTO LI_AWD_BUDGT_PERIOD_CNT FROM AWARD_BUDGET_PERIOD
			WHERE BUDGET_HEADER_ID IN (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER
									   WHERE AWARD_ID = AV_AWARD_ID
									  );
									  
			SELECT COUNT(1) INTO LI_AWAD_RATE_ID_CNT
			FROM AWARD_RATES		
			WHERE BUDGET_HEADER_ID IN(SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = AV_AWARD_ID);
									  
			SELECT COUNT(1) INTO LI_AWD_BUDGT_HEADER_CNT FROM AWARD_BUDGET_HEADER
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_CONTACT_CNT
			FROM AWARD_CONTACT
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_TOTAL_COST_SHARE_CNT
			FROM AWARD_COST_SHARE 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_QST_ANS_HDR_CNT
			FROM QUEST_ANSWER_HEADER
			WHERE MODULE_ITEM_CODE = 1
			AND MODULE_SUB_ITEM_CODE = 3
			AND MODULE_ITEM_KEY = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_QST_ANSWER_CNT FROM QUEST_ANSWER
			WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
												 FROM QUEST_ANSWER_HEADER
												 WHERE MODULE_ITEM_CODE = 1
												 AND MODULE_SUB_ITEM_CODE = 3
												 AND MODULE_ITEM_KEY = AV_AWARD_ID
												 );
			
			SELECT COUNT(1) INTO LI_QST_ANS_ATT_CNT FROM QUEST_ANSWER_ATTACHMENT
			WHERE QUESTIONNAIRE_ANSWER_ID IN(SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER
											 WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
																				 FROM QUEST_ANSWER_HEADER
																				 WHERE MODULE_ITEM_CODE = 1
																				 AND MODULE_SUB_ITEM_CODE = 3
																				 AND MODULE_ITEM_KEY = AV_AWARD_ID
																				)
											);
											
			SELECT COUNT(1) INTO LI_TOTAL_AWARD_FUNDING_PROP_CNT
			FROM AWARD_FUNDING_PROPOSALS 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_PERSON_UNIT_CNT 
			FROM AWARD_PERSON_UNIT
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_PERSON_ATTACHMNT_CNT 
			FROM AWARD_PERSON_ATTACHMNT
			WHERE AWARD_PERSON_ID IN (SELECT AWARD_PERSON_ID FROM AWARD_PERSONS
									  WHERE AWARD_ID = AV_AWARD_ID
									  );
			SELECT COUNT(1) INTO LI_AWARD_PERSONS_CNT
			FROM AWARD_PERSONS WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_MANPWR_CNT
			FROM AWARD_MANPOWER
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWD_MANPW_RES_CNT 
			FROM AWARD_MANPOWER_RESOURCE
			WHERE AWARD_MANPOWER_ID IN(SELECT AWARD_MANPOWER_ID FROM AWARD_MANPOWER
									   WHERE AWARD_ID = AV_AWARD_ID);
									   
			SELECT COUNT(1) INTO LI_AWARD_MILE_ST_CNT
			FROM AWARD_MILESTONE
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_TOTAL_AWARD_CUSTOM_CNT
			FROM CUSTOM_DATA 
			WHERE MODULE_ITEM_KEY = AV_AWARD_ID
			AND MODULE_ITEM_CODE = 1
			AND MODULE_SUB_ITEM_CODE = 0
			AND MODULE_SUB_ITEM_KEY = 0;
			
			SELECT COUNT(1) INTO LI_TOTAL_AWARD_PUBLICATION_CNT
			FROM AWARD_PUBLICATIONS 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_TOTAL_AWARD_ACHIEVMNT_ATTACH_CNT
			FROM AWARD_ACHIEVEMENTS_ATTACHMENTS 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWAD_ASSOC_CNT
			FROM AWARD_ASSOCIATION
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWAD_ASSOC_DTL_CNT 
			FROM AWARD_ASSOC_DETAIL
			WHERE AWARD_ASSOCIATION_ID IN(SELECT AWARD_ASSOCIATION_ID FROM AWARD_ASSOCIATION
										  WHERE AWARD_ID = AV_AWARD_ID);
										  
			SELECT COUNT(1) INTO LI_PROJECT_TEAM_CNT
			FROM AWARD_PROJECT_TEAM
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_QST_AWD_ANS_HDR_CNT
			FROM QUEST_ANSWER_HEADER
			WHERE MODULE_ITEM_CODE = 1
			AND MODULE_SUB_ITEM_CODE = 0
			AND MODULE_ITEM_KEY = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_QST_AWD_ANSWER_CNT FROM QUEST_ANSWER
			WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
												 FROM QUEST_ANSWER_HEADER
												 WHERE MODULE_ITEM_CODE = 1
												 AND MODULE_SUB_ITEM_CODE = 0
												 AND MODULE_ITEM_KEY = AV_AWARD_ID
												 );
												 
			SELECT COUNT(1) INTO LI_QST_AWD_ANS_ATT_CNT FROM QUEST_ANSWER_ATTACHMENT
			WHERE QUESTIONNAIRE_ANSWER_ID IN(SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER
											 WHERE QUESTIONNAIRE_ANS_HEADER_ID IN(SELECT QUESTIONNAIRE_ANS_HEADER_ID
																				 FROM QUEST_ANSWER_HEADER
																				 WHERE MODULE_ITEM_CODE = 1
																				 AND MODULE_SUB_ITEM_CODE = 0
																				 AND MODULE_ITEM_KEY = AV_AWARD_ID
																				)
											);
											
			SELECT COUNT(1) INTO LI_AWARD_REPORT_TERMS_CNT
			FROM AWARD_REPORT_TERMS
			WHERE AWARD_ID = AV_AWARD_ID;

			SELECT COUNT(1) INTO LI_AWARD_REPT_TERM_RECPT_CNT
			FROM AWARD_REPORT_TERM_RECIPIENT
			WHERE AWARD_ID = AV_AWARD_ID;

			SELECT COUNT(1) INTO LI_AWD_REPT_TRACK_CNT
			FROM AWARD_REPORT_TRACKING
			WHERE AWARD_ID = AV_AWARD_ID;

			SELECT COUNT(1) INTO LI_AWARD_RPT_TRCK_FILE_CNT
			FROM AWARD_REPORT_TRACKING_FILE
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_PERSON_ROLE_ID_CNT
			FROM AWARD_PERSON_ROLES
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_APPR_EQP_CNT
			FROM AWARD_APPROVED_EQUIPMENT 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_APRVD_FOREIGN_TRA_CNT
			FROM AWARD_APPROVED_FOREIGN_TRAVEL 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_SPECIAL_REVIEW_CNT
			FROM AWARD_SPECIAL_REVIEW 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_AWARD_APPROVED_SUBAWARDS_CNT
			FROM AWARD_APPROVED_SUBAWARDS 
			WHERE AWARD_ID = AV_AWARD_ID;
			
			SELECT COUNT(1) INTO LI_SPONSOR_TERM_CNT
			FROM AWARD_SPONSOR_TERM
			WHERE AWARD_ID = AV_AWARD_ID;
				
			IF AV_TYPE = 'BEFORE' THEN
				-- -------------------STARTS INSERTION----------------------------------------
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_SCIENCE_KEYWORD',LI_SCIENCE_KEYWORD_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_RESEARCH_AREAS',LI_AWARD_RSRCH_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_KPI',LI_AWARD_KPI_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_KPI_CRITERIA',LI_AWARD_KPI_CRIT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_DET_CAL_AMT',LI_AWD_BUDGT_CAL_AMT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_NON_PERSON_DETAIL',LI_AWD_BUDGT_NON_PERSN_DTL_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_PERSON_DETAIL',LI_AWD_BUDGT_PERSN_DTL_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_RATE_AND_BASE',LI_AWD_BUDGT_RATE_BASE_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_DETAIL',LI_AWD_BUDGT_DETL_ID_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_PERIOD',LI_AWD_BUDGT_PERIOD_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_RATES',LI_AWAD_RATE_ID_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_BUDGET_HEADER',LI_AWD_BUDGT_HEADER_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_CONTACT',LI_AWARD_CONTACT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_COST_SHARE',LI_TOTAL_COST_SHARE_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'QUEST_DMP_ANSWER_HEADER',LI_QST_ANS_HDR_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'QUEST_DMP_ANSWER',LI_QST_ANSWER_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'QUEST_DMP_ANSWER_ATTACHMENT',LI_QST_ANS_ATT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_FUNDING_PROPOSALS',LI_TOTAL_AWARD_FUNDING_PROP_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_PERSON_UNIT',LI_AWARD_PERSON_UNIT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_PERSON_ATTACHMNT',LI_AWARD_PERSON_ATTACHMNT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_PERSONS',LI_AWARD_PERSONS_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_MANPOWER',LI_AWARD_MANPWR_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_MANPOWER_RESOURCE',LI_AWD_MANPW_RES_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_MILESTONE',LI_AWARD_MILE_ST_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'CUSTOM_DATA',LI_TOTAL_AWARD_CUSTOM_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_PUBLICATIONS',LI_TOTAL_AWARD_PUBLICATION_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_ACHIEVEMENTS_ATTACHMENTS',LI_TOTAL_AWARD_ACHIEVMNT_ATTACH_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_ASSOCIATION',LI_AWAD_ASSOC_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_ASSOC_DETAIL',LI_AWAD_ASSOC_DTL_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_PROJECT_TEAM',LI_PROJECT_TEAM_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'QUEST_AWD_ANSWER_HEADER',LI_QST_AWD_ANS_HDR_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'QUEST_AWD_ANSWER',LI_QST_AWD_ANSWER_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'QUEST_AWD_ANSWER_ATTACHMENT',LI_QST_AWD_ANS_ATT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_REPORT_TERMS',LI_AWARD_REPORT_TERMS_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_REPORT_TERM_RECIPIENT',LI_AWARD_REPT_TERM_RECPT_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_REPORT_TRACKING',LI_AWD_REPT_TRACK_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_REPORT_TRACKING_FILE',LI_AWARD_RPT_TRCK_FILE_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_PERSON_ROLES',LI_AWARD_PERSON_ROLE_ID_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_APPROVED_EQUIPMENT',LI_AWARD_APPR_EQP_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_APPROVED_FOREIGN_TRAVEL',LI_AWARD_APRVD_FOREIGN_TRA_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_SPECIAL_REVIEW',LI_AWARD_SPECIAL_REVIEW_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_APPROVED_SUBAWARDS',LI_AWARD_APPROVED_SUBAWARDS_CNT,NOW(),'admin');
				
				INSERT INTO AWARD_TABLE_TOTAL_COUNT(AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,TABLE_NAME, BEFORE_TOTAL_COUNT, UPDATETIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER,'AWARD_SPONSOR_TERM',LI_SPONSOR_TERM_CNT,NOW(),'admin');
				-- -------------------ENDS INSERTION------------------------------------------
			END IF;
			
			END LOOP;
			CLOSE CUR_AWARD_DATA;
		END;
END 
