CREATE PROCEDURE GET_AWARD_BUDGET_MIGRATED_TO_AGREEMENT_FINANCIAL(
    IN AV_SOURCE_MODULE_ID INT
)
BEGIN

			SELECT 'ID'
				,'Title'
				,'Status'
				,'Award Effective Date'
				,'Final Expiration Date'
				,'Campus Flag'
				,'F&A Rate Type'
				,'F&A Rate (%)'
				,'Direct Cost'
				,'Indirect Cost'
				,'Cost Share'
				-- ,'Total Cost'
				,'Obligated Amount'
				,'Anticipated Amount'
UNION
				SELECT 
					T1.AWARD_NUMBER,
					T1.TITLE,
					AWS.DESCRIPTION AS AWARD_STATUS,
					DATE(T1.BEGIN_DATE) AS PROJECT_START_DATE,
					DATE(T1.FINAL_EXPIRATION_DATE) AS PROJECT_END_DATE,
					CASE WHEN T3.ON_OFF_CAMPUS_FLAG = 'N' THEN 'ON'
					WHEN T3.ON_OFF_CAMPUS_FLAG = 'F' THEN 'OFF' end as flag,
					T4.DESCRIPTION AS FA_RATE,
					CASE WHEN T3.ON_OFF_CAMPUS_FLAG = 'N' THEN CONCAT(T3.ON_CAMPUS_RATES,'%')
					WHEN T3.ON_OFF_CAMPUS_FLAG = 'F' THEN CONCAT(T3.OFF_CAMPUS_RATES,'%')
					WHEN T3.ON_OFF_CAMPUS_FLAG = 'D' THEN CONCAT(T3.OFF_CAMPUS_RATES + T3.ON_CAMPUS_RATES,'%')
					end as CAMPUS_RATES,
					IFNULL(T3.TOTAL_DIRECT_COST, 0.00) AS TOTAL_DIRECT_COST,
					IFNULL(T3.TOTAL_INDIRECT_COST, 0.00) AS TOTAL_INDIRECT_COST,
					 IFNULL(T6.COST_SHARE_AMT, 0.00) AS COST_SHARE,
					-- IFNULL(T3.TOTAL_COST, 0.00) AS TOTAL_COST,
					 IFNULL(T2.AMOUNT_OBLIGATED_TO_DATE, 0.00) AS OBLIGATED_AMOUNT,
					IFNULL(T2.ANTICIPATED_TOTAL_AMOUNT, 0.00) AS ANTICIPATED_AMOUNT
				FROM AWARD T1
				LEFT JOIN (
					SELECT 
						S1.AWARD_ID,
						S1.AWARD_NUMBER,
						S1.ANTICIPATED_TOTAL_AMOUNT,
						S1.AMOUNT_OBLIGATED_TO_DATE,
						S1.FINAL_EXPIRATION_DATE,
						S1.CURRENT_FUND_EFFECTIVE_DATE,
						S1.OBLIGATION_EXPIRATION_DATE,
						S1.TOTAL_COST_IN_CURRENCY
					FROM AWARD_AMOUNT_INFO S1
					INNER JOIN (
						SELECT 
							MAX(S3.AWARD_AMOUNT_INFO_ID) AS AWARD_AMOUNT_INFO_ID,
							S3.AWARD_NUMBER
						FROM AWARD_AMOUNT_INFO S3
						LEFT JOIN AWARD_AMOUNT_TRANSACTION S2 ON S3.TRANSACTION_ID = S2.TRANSACTION_ID
						INNER JOIN AWARD S5 ON S5.AWARD_NUMBER = S3.AWARD_NUMBER
						WHERE (S2.TRANSACTION_STATUS_CODE IN ('P', 'A') AND S5.AWARD_DOCUMENT_TYPE_CODE = 1 
							AND S5.AWARD_SEQUENCE_STATUS = 'PENDING') 
							OR (S2.TRANSACTION_STATUS_CODE = 'A' AND S5.AWARD_SEQUENCE_STATUS = 'ACTIVE')
						GROUP BY S3.AWARD_NUMBER
					) S2 ON S1.AWARD_AMOUNT_INFO_ID = S2.AWARD_AMOUNT_INFO_ID
					AND S1.AWARD_NUMBER = S2.AWARD_NUMBER
				) T2 ON T1.AWARD_NUMBER = T2.AWARD_NUMBER
				LEFT JOIN (
					SELECT 
						S3.AWARD_ID,
						S3.TOTAL_COST,
						S3.TOTAL_DIRECT_COST,
						S3.TOTAL_INDIRECT_COST,
						S3.RATE_CLASS_CODE,
						S3.CUMULATIVE_VIREMENT,
						S3.RATE_TYPE_CODE,
						S3.ON_OFF_CAMPUS_FLAG,
						S3.ON_CAMPUS_RATES,
						S3.OFF_CAMPUS_RATES
					FROM AWARD_BUDGET_HEADER S3
					WHERE S3.VERSION_NUMBER = (
						SELECT MAX(S4.VERSION_NUMBER) 
						FROM AWARD_BUDGET_HEADER S4
						WHERE S3.AWARD_ID = S4.AWARD_ID
					)
				) T3 ON T1.AWARD_ID = T3.AWARD_ID
				LEFT JOIN (
					SELECT 
						S5.AWARD_ID,
						SUM(COMMITMENT_AMOUNT) AS COST_SHARE_AMT
					FROM AWARD_COST_SHARE S5
					GROUP BY S5.AWARD_ID
				) T6 ON T1.AWARD_ID = T6.AWARD_ID
				LEFT JOIN RATE_TYPE T4 ON T3.RATE_TYPE_CODE = T4.RATE_TYPE_CODE
					AND T3.RATE_CLASS_CODE = T4.RATE_CLASS_CODE
				INNER JOIN AWARD_STATUS AWS ON T1.STATUS_CODE = AWS.STATUS_CODE	
				WHERE T1.AWARD_ID = AV_SOURCE_MODULE_ID;
END
