-- `INSERT_ROLE_IN_AWARD_PERMISSION_ROLE`; 

CREATE PROCEDURE `INSERT_ROLE_IN_AWARD_PERMISSION_ROLE`()
BEGIN
    DECLARE LS_AWARD_NUMBER VARCHAR(20);
    DECLARE LI_SEQUENCE_NUMBER INT;
    DECLARE LS_PERSON_ID VARCHAR(40);
    DECLARE LI_AWARD_ID INT;
    DECLARE LI_AWARD_PERSON_ROLE_ID INT;
	DECLARE AV_ROLE_ID INT;
    DECLARE NOT_FOUND INT DEFAULT 0;
    DECLARE SEL_AWARD_PERSON_DATA CURSOR FOR 
        SELECT DISTINCT AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, PERSON_ID 
        FROM AWARD_PERSONS 
        WHERE PERSON_ROLE_ID = 3
        AND PI_FLAG = 'Y'
        AND AWARD_ID NOT IN (
            SELECT DISTINCT AWARD_ID 
            FROM AWARD_PERSON_ROLES 
            WHERE ROLE_ID = AV_ROLE_ID
        )
        ORDER BY 1 ASC;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
	
SELECT DISTINCT MDR.ROLE_ID INTO AV_ROLE_ID FROM MODULE_DERIVED_ROLES MDR 
INNER JOIN ROLE_RIGHTS RR ON RR.ROLE_ID = MDR.ROLE_ID
LEFT JOIN RIGHTS R ON R.RIGHT_ID = RR.RIGHT_ID
WHERE R.RIGHT_NAME IN ('VIEW_PROGRESS_REPORT','MODIFY_PROGRESS_REPORT','CREATE_PROGRESS_REPORT');
    OPEN SEL_AWARD_PERSON_DATA;
    INSERT_LOOP: LOOP
        FETCH SEL_AWARD_PERSON_DATA INTO 
            LI_AWARD_ID,
            LS_AWARD_NUMBER,
            LI_SEQUENCE_NUMBER,
            LS_PERSON_ID;
        IF NOT_FOUND = 1 THEN
            LEAVE INSERT_LOOP;
        END IF;
 
        INSERT INTO AWARD_PERSON_ROLES
        (            
            AWARD_ID,
            AWARD_NUMBER,
            SEQUENCE_NUMBER,
            PERSON_ID,
            ROLE_ID,
            UPDATE_TIMESTAMP,
            UPDATE_USER,
            IS_SYSTEM_GENERATED
        ) 
        VALUES
        (
            LI_AWARD_ID,
            LS_AWARD_NUMBER,
            LI_SEQUENCE_NUMBER,
            LS_PERSON_ID,
            AV_ROLE_ID,
            UTC_TIMESTAMP(),
            'ADMIN',
            'Y'
        );
        COMMIT;
    END LOOP;
    CLOSE SEL_AWARD_PERSON_DATA;
END
