-- `MERGE_AWD_SECTION_AREA_OF_RSRCH`; 

CREATE PROCEDURE `MERGE_AWD_SECTION_AREA_OF_RSRCH`(
AV_AWARD_ID 			INT,
AV_AWARD_NUMBER			VARCHAR(12),
AV_SEQUENCE_NUMBER		INT(4),
AV_VARIATION_TYPE_CODE	VARCHAR(3),
AV_UPDATE_USER			VARCHAR(60)
)
BEGIN
DECLARE LS_ERROR_MSG						VARCHAR(1000);
DECLARE LS_TABLE_NAME						VARCHAR(30);
DECLARE LI_FLAG								INT;
DECLARE LI_MASTER_AWARD_ID					DECIMAL(22,0);
DECLARE LI_MASTER_SEQ_NUMBER				INT(4);
DECLARE LS_RESRCH_TYPE_CODE				VARCHAR(3);
DECLARE LS_RESEARCH_AREA_CODE			VARCHAR(8);
DECLARE LS_RESEARCH_SUB_AREA_CODE		VARCHAR(3);
DECLARE LS_UPDATE_TIMESTAMP				DATETIME;
DECLARE LS_UPDATE_USER					VARCHAR(60);
DECLARE LS_CHALLENGE_AREA_CODE			VARCHAR(3);
DECLARE LS_CHALLENGE_SUBAREA_CODE		VARCHAR(3);
DECLARE LS_RESRCH_TYPE_SUB_AREA_CODE	VARCHAR(8);
DECLARE LS_RESRCH_TYPE_AREA_CODE		VARCHAR(8);
DECLARE LS_DOCUMENT_UPDATE_USER			VARCHAR(60);
DECLARE LS_DOCUMENT_UPDATE_TIMESTAMP	DATETIME;
DECLARE LI_RESEARCH_RANK INT;
	BEGIN
	
			DECLARE EXIT HANDLER FOR SQLEXCEPTION
			BEGIN
			
				GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
				 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
				 
				SET @full_error = CONCAT(@msg,'|SEC125|',LS_TABLE_NAME );
					
				SELECT @full_error INTO LS_ERROR_MSG;
																	
				RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
				
			END;
			
			SELECT COUNT(1) INTO LI_FLAG
			FROM AWARD 
			WHERE AWARD_NUMBER = AV_AWARD_NUMBER
			AND SEQUENCE_NUMBER = 0;
			
			IF LI_FLAG > 0 THEN
			
				SELECT AWARD_ID,SEQUENCE_NUMBER 
				INTO LI_MASTER_AWARD_ID,LI_MASTER_SEQ_NUMBER
				FROM AWARD 
				WHERE AWARD_NUMBER = AV_AWARD_NUMBER
				AND SEQUENCE_NUMBER = 0;
			
			END IF;
			
			DELETE FROM AWARD_RESEARCH_AREAS
			WHERE AWARD_ID = LI_MASTER_AWARD_ID;
			
			SET LS_TABLE_NAME = 'AWARD_RESEARCH_AREAS';
            BEGIN
			
				DECLARE DONE1 INT DEFAULT FALSE;
				DECLARE CUR_AWARD_RSRCH CURSOR FOR
				SELECT 
					RESRCH_TYPE_CODE, 
					RESEARCH_AREA_CODE, 
					RESEARCH_SUB_AREA_CODE,
					UPDATE_TIMESTAMP, 
					UPDATE_USER, 
					CHALLENGE_AREA_CODE, 
					CHALLENGE_SUBAREA_CODE,
					RESRCH_TYPE_SUB_AREA_CODE,
				RESRCH_TYPE_AREA_CODE,
                RESEARCH_RANK
				FROM AWARD_RESEARCH_AREAS
				WHERE AWARD_ID = AV_AWARD_ID;
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
				OPEN CUR_AWARD_RSRCH;
				INSERT_AWARD_RSRCH_LOOP: LOOP 
				FETCH CUR_AWARD_RSRCH INTO
				LS_RESRCH_TYPE_CODE,
				LS_RESEARCH_AREA_CODE,
				LS_RESEARCH_SUB_AREA_CODE,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER,
				LS_CHALLENGE_AREA_CODE,
				LS_CHALLENGE_SUBAREA_CODE,
				LS_RESRCH_TYPE_SUB_AREA_CODE,
				LS_RESRCH_TYPE_AREA_CODE,
                LI_RESEARCH_RANK;
								
				IF DONE1 THEN
					LEAVE INSERT_AWARD_RSRCH_LOOP;
				END IF;
				
				INSERT INTO AWARD_RESEARCH_AREAS(
				RESRCH_TYPE_CODE, 
				RESEARCH_AREA_CODE, 
				RESEARCH_SUB_AREA_CODE, 
				AWARD_ID, 
				AWARD_NUMBER, 
				SEQUENCE_NUMBER, 
				UPDATE_TIMESTAMP, 
				UPDATE_USER, 
				CHALLENGE_AREA_CODE, 
				CHALLENGE_SUBAREA_CODE,
				RESRCH_TYPE_SUB_AREA_CODE,
				RESRCH_TYPE_AREA_CODE,
                RESEARCH_RANK
				)
				VALUES
				(
				LS_RESRCH_TYPE_CODE,
				LS_RESEARCH_AREA_CODE,
				LS_RESEARCH_SUB_AREA_CODE,
				LI_MASTER_AWARD_ID,
				AV_AWARD_NUMBER,
				LI_MASTER_SEQ_NUMBER,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER,
				LS_CHALLENGE_AREA_CODE,
				LS_CHALLENGE_SUBAREA_CODE,
				LS_RESRCH_TYPE_SUB_AREA_CODE,
				LS_RESRCH_TYPE_AREA_CODE,
				LI_RESEARCH_RANK
				);
			
				END LOOP;
				CLOSE CUR_AWARD_RSRCH;
			
			END;
			
	END;
END
