CREATE PROCEDURE `SAP_COMPARISON_DESCREPANCY`(AV_ID INT)
BEGIN

DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_ERROR_MSG VARCHAR(1000);
DECLARE LI_FEED_ID	INT;
DECLARE LS_BATCH_ID INT;
DECLARE LI_AWARD_ID INT;
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LS_ACCOUNT_NUMBER VARCHAR(100);
DECLARE LI_LINE_ITEM_COST DECIMAL(15,2);
DECLARE LI_PREV_LINE_ITEM_COST DECIMAL(15,2);
DECLARE LS_BUDGET_CATEGORY_CODE VARCHAR(50);
DECLARE LS_IO_CODE VARCHAR(200);
DECLARE LI_BUDGET_HEADER_ID	INT;
DECLARE LI_BUDGET_AMOUNT DECIMAL(15,2);
DECLARE LI_WRITE_FLAG INT;
DECLARE LI_FLAG INT;
DECLARE LI_PREV_VERSION_NUMBER INT;
DECLARE LI_CUR_VERSION_NUMBER INT;
DECLARE LI_PREV_AWARD_ID INT;
DECLARE LS_AWD_ACCOUNT_TYPE_CODE VARCHAR(3);
DECLARE LS_FUND_CODE			VARCHAR(4000);
DECLARE LS_ROOT_AWARD_NUMBER	VARCHAR(12);

		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
			
			INSERT INTO SAP_FEED_REPORT_ERROR_LOG(ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LS_ERROR_MSG,utc_timestamp(),'admin');
			COMMIT;
			
			
		END;
		
		BEGIN
		
			DECLARE DONE1 INT DEFAULT FALSE;

			DECLARE CUR_FEED_DATA CURSOR FOR
			SELECT FEED_ID,BATCH_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER 
			FROM SAP_AWARD_FEED WHERE BATCH_ID >= 28 AND BATCH_ID <= 249 order by FEED_ID;
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

			OPEN CUR_FEED_DATA;
			INSERT_LOOP: LOOP 
			FETCH CUR_FEED_DATA INTO
			LI_FEED_ID,
			LS_BATCH_ID,
			LI_AWARD_ID,
			LS_AWARD_NUMBER,
			LI_SEQUENCE_NUMBER;
			
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
			
				SELECT COUNT(1) INTO LI_FLAG
				FROM AWARD
				WHERE AWARD_ID = LI_AWARD_ID
				AND ACCOUNT_NUMBER IS NOT NULL;
				
				IF LI_FLAG > 0 THEN
				
					SELECT 
						ACCOUNT_NUMBER,
						IF(TRIM(ACCOUNT_TYPE_CODE) = '',NULL,TRIM(ACCOUNT_TYPE_CODE)) 
					INTO 
						LS_ACCOUNT_NUMBER,
						LS_AWD_ACCOUNT_TYPE_CODE
					FROM AWARD
					WHERE AWARD_ID = LI_AWARD_ID;
					
				
				END IF;
				
				
				
				-- ------------------STARTS FINDING 'FUND CODE'----------------------------------
				
				IF LS_AWD_ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN 

					/*
						1 - External Funding (RSO)
						2 - External funding (non-RSO)
						4 - External talent award (TRACS)
						6 - RCA			
					*/
				
					SET LS_FUND_CODE = 'R_RESFUND';
					
				ELSEIF LS_AWD_ACCOUNT_TYPE_CODE = '7' THEN -- Internal Funding (Co-Funding)
				
					SET LS_FUND_CODE = 'R_NTUCORES';
					
				ELSEIF LS_AWD_ACCOUNT_TYPE_CODE IN ('3','5') THEN 
				
					/*
						3 - 'Internal funding'
						5 - 'Internal talent award (TRACS)'
					*/
					
					IF SUBSTR(LS_AWARD_NUMBER,INSTR(LS_AWARD_NUMBER,'-')+1) = '00001' THEN
					
						SET LS_FUND_CODE = 'G_DESIGNAT';
						
					ELSE
						
						SELECT CONCAT(SUBSTR(LS_AWARD_NUMBER,1,INSTR(LS_AWARD_NUMBER,'-')-1),'-00001') 
						INTO LS_ROOT_AWARD_NUMBER
						FROM DUAL;
						
						SELECT COUNT(1) INTO LI_FLAG
						FROM AWARD
						WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
						AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
						
						IF LI_FLAG > 0 THEN
						
							SELECT 
								CASE WHEN ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN 
								'R_NTUCORES'  
								ELSE
								'G_DESIGNAT'
								END
							INTO LS_FUND_CODE
							FROM AWARD
							WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
							AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
							
						ELSE
						
							SELECT 
								CASE WHEN ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN 
								'R_NTUCORES'  
								ELSE
								'G_DESIGNAT'
								END
							INTO LS_FUND_CODE
							FROM AWARD
							WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
							AND AWARD_SEQUENCE_STATUS = 'PENDING'
							AND SEQUENCE_NUMBER IN(SELECT MAX(SEQUENCE_NUMBER) FROM AWARD
													WHERE  AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
													AND AWARD_SEQUENCE_STATUS = 'PENDING' 
												  );
						
						END IF;
						
					END IF;
					
				END IF;
								
				-- ------------------ENDS FINDING 'FUND CODE'------------------------------------
				
				
				-- ------------------STARTS FINDING PREVIOUS FEED_ID-------------------
				
				SELECT COUNT(1) INTO LI_FLAG FROM SAP_AWARD_FEED T1
				WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
				AND T1.FEED_ID IN (SELECT MAX(T2.FEED_ID) FROM SAP_AWARD_FEED T2 
									WHERE  T1.AWARD_NUMBER = T2.AWARD_NUMBER 
									AND T2.FEED_ID < LI_FEED_ID
									-- AND T2.FEED_STATUS <> 'N'
									);
														  

				
				IF LI_FLAG > 0 THEN
				
					SELECT AWARD_ID INTO LI_PREV_AWARD_ID FROM SAP_AWARD_FEED T1
					WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
					AND T1.FEED_ID IN (SELECT MAX(T2.FEED_ID) FROM SAP_AWARD_FEED T2 
									WHERE  T1.AWARD_NUMBER = T2.AWARD_NUMBER 
									AND T2.FEED_ID < LI_FEED_ID
									-- AND T2.FEED_STATUS <> 'N'
									);
															  
	
				
				END IF;
				
				-- ------------------ENDS FINDING PREVIOUS FEED_ID---------------------
				
				-- ----------------------------------------STARTS FETCHING BUDGET DETAILS-----------------------------------------------
				
				
				BEGIN
				
					DECLARE DONE4 INT DEFAULT FALSE;
					
					DECLARE CUR_MASTER_BUD_DETAIL CURSOR FOR 
					
					SELECT SUM(T2.LINE_ITEM_COST),SUM(T2.PREVIOUS_LINE_ITEM_COST),
					IF(TRIM(T2.BUDGET_CATEGORY_CODE) = '',NULL,TRIM(T2.BUDGET_CATEGORY_CODE)),
					IF(TRIM(T2.INTERNAL_ORDER_CODE) = '',NULL,TRIM(T2.INTERNAL_ORDER_CODE)),
					T2.BUDGET_HEADER_ID
					FROM AWARD_BUDGET_HEADER T1
					INNER JOIN AWARD_BUDGET_DETAIL T2 ON T2.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID
					WHERE T1.AWARD_ID = LI_AWARD_ID 
					-- AND T1.IS_LATEST_VERSION = 'Y'
					AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
											  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
											 )
					AND T1.AWARD_BUDGET_STATUS_CODE = 10
					GROUP BY T2.INTERNAL_ORDER_CODE;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
					
					OPEN CUR_MASTER_BUD_DETAIL;
					
					INSERT_LOOP4: LOOP 
					FETCH CUR_MASTER_BUD_DETAIL INTO 
					LI_LINE_ITEM_COST,
					LI_PREV_LINE_ITEM_COST,
					LS_BUDGET_CATEGORY_CODE,
					LS_IO_CODE,
					LI_BUDGET_HEADER_ID;
					
					IF DONE4 THEN
						LEAVE INSERT_LOOP4;
					END IF;
					
					SET LI_BUDGET_AMOUNT = IFNULL(LI_LINE_ITEM_COST,0) - IFNULL(LI_PREV_LINE_ITEM_COST,0);
					
					IF LI_BUDGET_AMOUNT = 0 THEN -- CHECKING IF BUDGET AMOUNT IS ZERO THEN NO NEED TO WRITE
						
						SET LI_WRITE_FLAG = 0;

					END IF;
					
					IF LI_PREV_AWARD_ID IS NOT NULL THEN 
					
						SELECT MAX(VERSION_NUMBER) INTO LI_PREV_VERSION_NUMBER FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = LI_PREV_AWARD_ID 
						AND AWARD_BUDGET_STATUS_CODE = 10;
						
						SELECT MAX(VERSION_NUMBER) INTO LI_CUR_VERSION_NUMBER FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = LI_AWARD_ID
						AND AWARD_BUDGET_STATUS_CODE = 10;
						
						IF LI_PREV_VERSION_NUMBER = LI_CUR_VERSION_NUMBER THEN
						
							SET LI_WRITE_FLAG = 0;
							
						END IF;
						
					END IF;
					
					IF LS_BUDGET_CATEGORY_CODE = 'GRT' THEN

						SET LI_WRITE_FLAG = 0;

					END IF;
					
					IF LI_WRITE_FLAG = 1 THEN
					
					
						SELECT COUNT(1) INTO LI_FLAG
						FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
						WHERE T1.SPONSOR_CLASS = LS_IO_CODE
						AND T1.FEED_ID = LI_FEED_ID
						AND T1.BATCH_ID = LS_BATCH_ID;
						
						IF LI_FLAG = 0  THEN
						
							SELECT COUNT(1) INTO LI_FLAG
							FROM SAP_FEED_TMPL_FM_BUDGET T1
							WHERE T1.FUNDED_PROGRAM = LS_IO_CODE
							AND T1.FEED_ID = LI_FEED_ID
							AND T1.BATCH_ID = LS_BATCH_ID;
							
							IF LI_FLAG = 0 THEN
						
								INSERT INTO SAP_COMPARISON_DESCREPANCY(FEED_ID, BATCH_ID, AWARD_ID, AWARD_NUMBER, ACCOUNT_NUMBER, SEQUENCE_NUMBER, BUDGET_HEADER_ID, INTERNAL_ORDER_CODE,CURRENT_LINE_ITEM_COST, PREVIOUS_LINE_ITEM_COST, AMOUNT,FUND_CODE)
								VALUES(LI_FEED_ID,LS_BATCH_ID,LI_AWARD_ID,LS_AWARD_NUMBER,LS_ACCOUNT_NUMBER,LI_SEQUENCE_NUMBER,LI_BUDGET_HEADER_ID,LS_IO_CODE,LI_LINE_ITEM_COST,LI_PREV_LINE_ITEM_COST,LI_BUDGET_AMOUNT,LS_FUND_CODE);
							
							END IF;
						END IF;
					
					END IF;
					
					END LOOP;
					CLOSE CUR_MASTER_BUD_DETAIL;
				
				
				END;
				
				-- ----------------------------------------ENDS FETCHING BUDGET DETAILS-------------------------------------------------
			    
			
			
			END LOOP;
			CLOSE CUR_FEED_DATA;
			commit;
		
		END;


END 
