-- `SAP_FEED_REINTERFACE_FEED_DATA`; 

CREATE PROCEDURE `SAP_FEED_REINTERFACE_FEED_DATA`(
AV_PREV_FEED_ID		INT,
AV_PREV_BATCH_ID	INT,
AV_NEW_FEED_ID		INT,
AV_NEW_BATCH_ID		INT
)
BEGIN

DECLARE LI_SEQ_ERROR_LOG_ID 	INT;
DECLARE LS_ERROR_MSG        	VARCHAR(4000);
DECLARE LS_UPDATE_USER			VARCHAR(60);

DECLARE LS_SPONSOR_PROGRAM			VARCHAR(20);
DECLARE LS_PROGRAM_DESCRIPTION		VARCHAR(30);
DECLARE LS_CREATE_STATUS			VARCHAR(1);
DECLARE LI_SP_PRGM_ID				INT;

DECLARE LS_SPONSOR_CLASS		VARCHAR(20);
DECLARE LS_CLASS_DESCRIPTION	VARCHAR(30);
DECLARE LS_CLASS_TYPE			VARCHAR(1);
DECLARE LI_SP_CLASS_ID			INT;

DECLARE LS_GRANT_CODE			VARCHAR(20);
DECLARE LS_COMPANY_CODE			VARCHAR(4);
DECLARE LS_GRANT_CURRENCY		VARCHAR(3);
DECLARE LS_FUND_CODE			VARCHAR(10);
DECLARE LI_GM_ID				INT;

DECLARE LS_FUNDED_PROGRAM		VARCHAR(20);
DECLARE LS_FUNDED_PROGRAM_TYPE	VARCHAR(4);
DECLARE LI_FUND_PGM_ID			INT;

DECLARE LS_PROJECT_DEFINITION				VARCHAR(80);
DECLARE LS_PROJECT_PROFILE					VARCHAR(80);
DECLARE LS_SHORT_DESCRIPTION				VARCHAR(40);
DECLARE LS_NUM_OF_THE_RESPONSIBLE_PERSON	VARCHAR(80);
DECLARE LS_CONTROLLING_AREA					VARCHAR(80);
DECLARE LS_DEF_COMPANY_CODE					VARCHAR(80);
DECLARE LS_DEF_BUSINESS_AREA				VARCHAR(80);
DECLARE LS_PLANT							VARCHAR(80);
DECLARE LS_FUNCTIONAL_AREA					VARCHAR(80);
DECLARE LS_PROFIT_CENTER					VARCHAR(80);
DECLARE LS_PROJECT_CURRENCY					VARCHAR(80);
DECLARE LS_START_DATE						DATETIME;
DECLARE LS_FINISH_DATE						DATETIME;
DECLARE LS_FACTORY_CALENDER_KEY				VARCHAR(80);
DECLARE LS_BUDGET_PROFILE					VARCHAR(80);
DECLARE LS_PLANNING_PROFILE					VARCHAR(80);
DECLARE LS_AWARD_STATUS						VARCHAR(1);
DECLARE LI_PRJ_DEF_ID						INT;

DECLARE LS_PROCESS					VARCHAR(4);
DECLARE LS_GM_DOC_TYPE				VARCHAR(2);
DECLARE LS_HEADER_DESCRIPTION		VARCHAR(40);
DECLARE LS_BUDGET_AMOUNT			DECIMAL(15,2);
DECLARE LS_POSTING_DATE				DATETIME;
DECLARE LS_DOCUMENT_DATE			DATETIME;
DECLARE LS_BUDGET_VERSION			VARCHAR(4);
DECLARE LS_LINE_ITEM_TEXT			VARCHAR(50);
DECLARE LS_GRANT_CUR				VARCHAR(3);
DECLARE LS_COMMITMENT_ITEM			VARCHAR(10);
DECLARE LS_GM_BUD_FUNCTIONAL_AREA	VARCHAR(8);
DECLARE LS_FUND_CENTER				VARCHAR(10);
DECLARE LS_DISTR_KEY				VARCHAR(1);
DECLARE LS_YEAR						INT(4);
DECLARE LS_FM_AREA					VARCHAR(3);
DECLARE LI_GM_BUD_ID				INT;

DECLARE LS_LINE_ITEM			VARCHAR(10);
DECLARE LS_BCS_VALUE_TYPE		VARCHAR(2);
DECLARE LS_DOC_TYPE				VARCHAR(4);
DECLARE LI_YEAR					INT(4);
DECLARE LS_BUDGET_TYPE			VARCHAR(4);
DECLARE LS_FM_GRANT				VARCHAR(10);
DECLARE LS_LOCAL_CURRENCY		VARCHAR(3);
DECLARE LS_DISTRIBUTION_KEY		VARCHAR(1);
DECLARE LI_FM_BUD_ID			INT;

DECLARE LS_WBS_ELEMENT					VARCHAR(24);
DECLARE LS_PROJECT						VARCHAR(24);
DECLARE LI_WBS_LEVEL					INT(3);
DECLARE LS_WBS_ELEMENT_HIERARCHY		VARCHAR(24);
DECLARE LS_PERSON_RESPONSIBLE_NUMBER	VARCHAR(8);
DECLARE LS_BUSINESS_AREA				VARCHAR(80);
DECLARE LS_PROJECT_TYPE					VARCHAR(2);
DECLARE LS_BASIC_START_DATE				DATETIME;
DECLARE LS_BASIC_FINISH_DATE			DATETIME;
DECLARE LS_KEYWORD_ID					VARCHAR(7);
DECLARE LS_RESPONSIBLE_COST_CENTER		VARCHAR(10);
DECLARE LS_ACCOUNT_ASSIGNMENT_ELEMENT	VARCHAR(1);
DECLARE LS_BILLING_ELEMENT				VARCHAR(1);
DECLARE LS_CURRENCY						VARCHAR(5);
DECLARE LS_OBJECT_CLASS					VARCHAR(5);
DECLARE LS_FACTORY_CALENDER				VARCHAR(2);
DECLARE LS_FUND							VARCHAR(10);
DECLARE LS_PRNCP_INVESTGTR				VARCHAR(20);
DECLARE LS_GST_CLAIMABLE				VARCHAR(1);
DECLARE LI_WBSID						INT;
DECLARE LS_TO_WBS_ELEMENT				VARCHAR(255);
DECLARE LS_FROM_WBS_ELEMENT				VARCHAR(255);
DECLARE LS_TARGET_FUND_CENTER			VARCHAR(255);
DECLARE LS_TARGET_FUND_CODE				VARCHAR(255);
DECLARE LS_TARGET_FUNDED_PROGRAM		VARCHAR(255);
DECLARE LS_TARGET_COMMITMENT_ITEM		VARCHAR(255);
DECLARE LS_TARGET_GRANT					VARCHAR(255);
DECLARE LS_FROM_GL_ACCOUNT				VARCHAR(255);
DECLARE	LS_TO_GL_ACCOUNT				VARCHAR(255);
DECLARE	LS_SPONSORED_PROGRAM			VARCHAR(255);
DECLARE	LS_SPONSORED_CLASS				VARCHAR(255);


		DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
		
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			
			INSERT INTO SAP_AWARD_FEED_BATCH_ERROR_LOG(BATCH_ID,FEED_ID,ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(AV_NEW_BATCH_ID,AV_NEW_FEED_ID,LS_ERROR_MSG,UTC_TIMESTAMP(),LS_UPDATE_USER);
			COMMIT;
		END;
		
		SET LS_UPDATE_USER = 'admin';
		-- -----------------STARTS SAP_FEED_TMPL_SPONSOR_PRGM -----------------------------
			BEGIN
			
				DECLARE DONE1 INT DEFAULT FALSE;

				DECLARE CUR_SP_PGM CURSOR FOR
				SELECT 
					SPONSOR_PROGRAM, 
					PROGRAM_DESCRIPTION, 
					BUSINESS_AREA, 
					CREATE_STATUS
				FROM SAP_FEED_TMPL_SPONSOR_PRGM
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

				OPEN CUR_SP_PGM;
				INSERT_CUR_SP_PGM_LOOP: LOOP 
				FETCH CUR_SP_PGM INTO
				LS_SPONSOR_PROGRAM,
				LS_PROGRAM_DESCRIPTION,
				LS_BUSINESS_AREA,
				LS_CREATE_STATUS;
								
				IF DONE1 THEN
					LEAVE INSERT_CUR_SP_PGM_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_SPONSOR_PRGM(
				BATCH_ID, 
				FEED_ID, 
				SPONSOR_PROGRAM, 
				PROGRAM_DESCRIPTION, 
				BUSINESS_AREA, 
				CREATE_STATUS, 
				UPDATE_USER, 
				UPDATE_TIMESTAMP,
				FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_SPONSOR_PROGRAM,
				LS_PROGRAM_DESCRIPTION,
				LS_BUSINESS_AREA,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_SP_PGM;
			
			END;
			COMMIT;
			-- -------------------ENDS SAP_FEED_TMPL_SPONSOR_PRGM--------------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_SPONSOR_CLASS-----------------------------------
			BEGIN
			
				DECLARE DONE2 INT DEFAULT FALSE;

				DECLARE CUR_SP_CLASS CURSOR FOR
				SELECT 
					SPONSOR_CLASS, 
					CLASS_DESCRIPTION, 
					CLASS_TYPE, 
					CREATE_STATUS
				FROM SAP_FEED_TMPL_SPONSOR_CLASS
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;

				OPEN CUR_SP_CLASS;
				INSERT_CUR_SP_CLASS_LOOP: LOOP 
				FETCH CUR_SP_CLASS INTO
				LS_SPONSOR_CLASS,
				LS_CLASS_DESCRIPTION,
				LS_CLASS_TYPE,
				LS_CREATE_STATUS;
								
				IF DONE2 THEN
					LEAVE INSERT_CUR_SP_CLASS_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_SPONSOR_CLASS(
				BATCH_ID, 
				FEED_ID, 
				SPONSOR_CLASS, 
				CLASS_DESCRIPTION, 
				CLASS_TYPE, 
				CREATE_STATUS,
				UPDATE_USER, 
				UPDATE_TIMESTAMP,
				FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_SPONSOR_CLASS,
				LS_CLASS_DESCRIPTION,
				LS_CLASS_TYPE,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_SP_CLASS;
			
			END;
			COMMIT;
			
			-- -------------------ENDS SAP_FEED_TMPL_SPONSOR_CLASS-------------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_GRANT_MASTER------------------------------------
			BEGIN
			
				DECLARE DONE3 INT DEFAULT FALSE;

				DECLARE CUR_GM CURSOR FOR
				SELECT 
					GRANT_CODE, 
					COMPANY_CODE, 
					GRANT_CURRENCY, 
					FUND_CODE, 
					SPONSOR_PROGRAM, 
					SPONSOR_CLASS, 
					CREATE_STATUS
				FROM SAP_FEED_TMPL_GRANT_MASTER
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;

				OPEN CUR_GM;
				INSERT_CUR_GM_LOOP: LOOP 
				FETCH CUR_GM INTO
				LS_GRANT_CODE,
				LS_COMPANY_CODE,
				LS_GRANT_CURRENCY,
				LS_FUND_CODE,
				LS_SPONSOR_PROGRAM,
				LS_SPONSOR_CLASS,
				LS_CREATE_STATUS;
								
				IF DONE3 THEN
					LEAVE INSERT_CUR_GM_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_GRANT_MASTER(
				BATCH_ID, 
				FEED_ID, 
				GRANT_CODE, 
				COMPANY_CODE, 
				GRANT_CURRENCY, 
				FUND_CODE, 
				SPONSOR_PROGRAM, 
				SPONSOR_CLASS, 
				CREATE_STATUS,
				UPDATE_USER, 
				UPDATE_TIMESTAMP,
				FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_GRANT_CODE,
				LS_COMPANY_CODE,
				LS_GRANT_CURRENCY,
				LS_FUND_CODE,
				LS_SPONSOR_PROGRAM,
				LS_SPONSOR_CLASS,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_GM;
			
			END;
			COMMIT;
			
			
			-- -------------------ENDS SAP_FEED_TMPL_GRANT_MASTER--------------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_FUNDED_PRGM-------------------------------------
			
			BEGIN
			
				DECLARE DONE4 INT DEFAULT FALSE;

				DECLARE CUR_FUND_PGM CURSOR FOR
				SELECT 
					FUNDED_PROGRAM, 
					PROGRAM_DESCRIPTION, 
					FUNDED_PROGRAM_TYPE, 
					CREATE_STATUS
				FROM SAP_FEED_TMPL_FUNDED_PRGM
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;

				OPEN CUR_FUND_PGM;
				INSERT_CUR_FUND_PGM_LOOP: LOOP 
				FETCH CUR_FUND_PGM INTO
				LS_FUNDED_PROGRAM,
				LS_PROGRAM_DESCRIPTION,
				LS_FUNDED_PROGRAM_TYPE,
				LS_CREATE_STATUS;
								
				IF DONE4 THEN
					LEAVE INSERT_CUR_FUND_PGM_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_FUNDED_PRGM(
				BATCH_ID, 
				FEED_ID, 
				FUNDED_PROGRAM, 
				PROGRAM_DESCRIPTION, 
				FUNDED_PROGRAM_TYPE, 
				CREATE_STATUS, 
				UPDATE_USER, 
				UPDATE_TIMESTAMP,
				FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_FUNDED_PROGRAM,
				LS_PROGRAM_DESCRIPTION,
				LS_FUNDED_PROGRAM_TYPE,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_FUND_PGM;
			
			END;
			COMMIT;
			
			-- -------------------ENDS SAP_FEED_TMPL_FUNDED_PRGM---------------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_PROJECT_DEF-------------------------------------
			
			BEGIN
			
				DECLARE DONE5 INT DEFAULT FALSE;

				DECLARE CUR_PRJ_DEF CURSOR FOR
				SELECT 
					PROJECT_DEFINITION, 
					PROJECT_PROFILE, 
					SHORT_DESCRIPTION, 
					NUM_OF_THE_RESPONSIBLE_PERSON, 
					CONTROLLING_AREA, 
					COMPANY_CODE, 
					BUSINESS_AREA, 
					PLANT, 
					FUNCTIONAL_AREA, 
					PROFIT_CENTER, 
					PROJECT_CURRENCY, 
					START_DATE, 
					FINISH_DATE, 
					FACTORY_CALENDER_KEY, 
					BUDGET_PROFILE, 
					PLANNING_PROFILE, 
					AWARD_STATUS, 
					CREATE_STATUS
				FROM SAP_FEED_TMPL_PROJECT_DEF
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE5 = TRUE;

				OPEN CUR_PRJ_DEF;
				INSERT_CUR_PRJ_DEF_LOOP: LOOP 
				FETCH CUR_PRJ_DEF INTO
				LS_PROJECT_DEFINITION,
				LS_PROJECT_PROFILE,
				LS_SHORT_DESCRIPTION,
				LS_NUM_OF_THE_RESPONSIBLE_PERSON,
				LS_CONTROLLING_AREA,
				LS_DEF_COMPANY_CODE,
				LS_DEF_BUSINESS_AREA,
				LS_PLANT,
				LS_FUNCTIONAL_AREA,
				LS_PROFIT_CENTER,
				LS_PROJECT_CURRENCY,
				LS_START_DATE,
				LS_FINISH_DATE,
				LS_FACTORY_CALENDER_KEY,
				LS_BUDGET_PROFILE,
				LS_PLANNING_PROFILE,
				LS_AWARD_STATUS,
				LS_CREATE_STATUS;
				
				IF DONE5 THEN
					LEAVE INSERT_CUR_PRJ_DEF_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_PROJECT_DEF(
				BATCH_ID, 
				FEED_ID, 
				PROJECT_DEFINITION, 
				PROJECT_PROFILE, 
				SHORT_DESCRIPTION, 
				NUM_OF_THE_RESPONSIBLE_PERSON, 
				CONTROLLING_AREA, 
				COMPANY_CODE, 
				BUSINESS_AREA, 
				PLANT, 
				FUNCTIONAL_AREA, 
				PROFIT_CENTER, 
				PROJECT_CURRENCY, 
				START_DATE, 
				FINISH_DATE, 
				FACTORY_CALENDER_KEY, 
				BUDGET_PROFILE, 
				PLANNING_PROFILE, 
				AWARD_STATUS, 
				CREATE_STATUS, 
				UPDATE_USER, 
				UPDATE_TIMESTAMP,
				FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_PROJECT_DEFINITION,
				LS_PROJECT_PROFILE,
				LS_SHORT_DESCRIPTION,
				LS_NUM_OF_THE_RESPONSIBLE_PERSON,
				LS_CONTROLLING_AREA,
				LS_DEF_COMPANY_CODE,
				LS_DEF_BUSINESS_AREA,
				LS_PLANT,
				LS_FUNCTIONAL_AREA,
				LS_PROFIT_CENTER,
				LS_PROJECT_CURRENCY,
				LS_START_DATE,
				LS_FINISH_DATE,
				LS_FACTORY_CALENDER_KEY,
				LS_BUDGET_PROFILE,
				LS_PLANNING_PROFILE,
				LS_AWARD_STATUS,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_PRJ_DEF;
			
			END;
			COMMIT;
			
			-- -------------------ENDS SAP_FEED_TMPL_PROJECT_DEF---------------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_GRANT_BUD_MASTER--------------------------------
			BEGIN
			
				DECLARE DONE6 INT DEFAULT FALSE;

				DECLARE CUR_GM_BUD CURSOR FOR
				SELECT 
					PROCESS, GRANT_CODE, GM_DOC_TYPE, HEADER_DESCRIPTION, FUND_CODE, SPONSOR_PROGRAM, SPONSOR_CLASS, BUDGET_AMOUNT, POSTING_DATE, DOCUMENT_DATE, BUDGET_VERSION, LINE_ITEM_TEXT, GRANT_CUR, COMMITMENT_ITEM, FUNDED_PROGRAM, FUNCTIONAL_AREA, FUND_CENTER, DISTR_KEY, YEAR, FM_AREA, CREATE_STATUS
				FROM SAP_FEED_TMPL_GRANT_BUD_MASTER
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE6 = TRUE;

				OPEN CUR_GM_BUD;
				INSERT_CUR_GM_BUD_LOOP: LOOP 
				FETCH CUR_GM_BUD INTO
				LS_PROCESS,
				LS_GRANT_CODE,
				LS_GM_DOC_TYPE,
				LS_HEADER_DESCRIPTION,
				LS_FUND_CODE,
				LS_SPONSOR_PROGRAM,
				LS_SPONSOR_CLASS,
				LS_BUDGET_AMOUNT,
				LS_POSTING_DATE,
				LS_DOCUMENT_DATE,
				LS_BUDGET_VERSION,
				LS_LINE_ITEM_TEXT,
				LS_GRANT_CUR,
				LS_COMMITMENT_ITEM,
				LS_FUNDED_PROGRAM,
				LS_GM_BUD_FUNCTIONAL_AREA,
				LS_FUND_CENTER,
				LS_DISTR_KEY,
				LS_YEAR,
				LS_FM_AREA,
				LS_CREATE_STATUS;
				
				IF DONE6 THEN
					LEAVE INSERT_CUR_GM_BUD_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_GRANT_BUD_MASTER(
				 BATCH_ID, FEED_ID, PROCESS, GRANT_CODE, GM_DOC_TYPE, HEADER_DESCRIPTION, FUND_CODE, SPONSOR_PROGRAM, SPONSOR_CLASS, BUDGET_AMOUNT, POSTING_DATE, DOCUMENT_DATE, BUDGET_VERSION, LINE_ITEM_TEXT, GRANT_CUR, COMMITMENT_ITEM, FUNDED_PROGRAM, FUNCTIONAL_AREA, FUND_CENTER, DISTR_KEY, YEAR, FM_AREA, CREATE_STATUS,UPDATE_USER, UPDATE_TIMESTAMP,FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_PROCESS,
				LS_GRANT_CODE,
				LS_GM_DOC_TYPE,
				LS_HEADER_DESCRIPTION,
				LS_FUND_CODE,
				LS_SPONSOR_PROGRAM,
				LS_SPONSOR_CLASS,
				LS_BUDGET_AMOUNT,
				LS_POSTING_DATE,
				LS_DOCUMENT_DATE,
				LS_BUDGET_VERSION,
				LS_LINE_ITEM_TEXT,
				LS_GRANT_CUR,
				LS_COMMITMENT_ITEM,
				LS_FUNDED_PROGRAM,
				LS_GM_BUD_FUNCTIONAL_AREA,
				LS_FUND_CENTER,
				LS_DISTR_KEY,
				LS_YEAR,
				LS_FM_AREA,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_GM_BUD;
			
			END;
			COMMIT;
			
			-- -------------------ENDS SAP_FEED_TMPL_GRANT_BUD_MASTER----------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_FM_BUDGET---------------------------------------
			
			BEGIN
			
				DECLARE DONE7 INT DEFAULT FALSE;

				DECLARE CUR_FM_BUD CURSOR FOR
				SELECT 
					LINE_ITEM, BCS_VALUE_TYPE, PROCESS, DOC_TYPE, BUDGET_VERSION, DOCUMENT_DATE, YEAR, BUDGET_TYPE, FM_GRANT, FUND_CODE, FUND_CENTER, COMMITMENT_ITEM, FUNCTIONAL_AREA, FUNDED_PROGRAM, BUDGET_AMOUNT, LOCAL_CURRENCY, DISTRIBUTION_KEY, LINE_ITEM_TEXT, CREATE_STATUS
				FROM SAP_FEED_TMPL_FM_BUDGET
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE7 = TRUE;

				OPEN CUR_FM_BUD;
				INSERT_CUR_FM_BUD_LOOP: LOOP 
				FETCH CUR_FM_BUD INTO
				LS_LINE_ITEM,
				LS_BCS_VALUE_TYPE,
				LS_PROCESS,
				LS_DOC_TYPE,
				LS_BUDGET_VERSION,
				LS_DOCUMENT_DATE,
				LI_YEAR,
				LS_BUDGET_TYPE,
				LS_FM_GRANT,
				LS_FUND_CODE,
				LS_FUND_CENTER,
				LS_COMMITMENT_ITEM,
				LS_FUNCTIONAL_AREA,
				LS_FUNDED_PROGRAM,
				LS_BUDGET_AMOUNT,
				LS_LOCAL_CURRENCY,
				LS_DISTRIBUTION_KEY,
				LS_LINE_ITEM_TEXT,
				LS_CREATE_STATUS;
				
				IF DONE7 THEN
					LEAVE INSERT_CUR_FM_BUD_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_FM_BUDGET(
			    BATCH_ID, FEED_ID, LINE_ITEM, BCS_VALUE_TYPE, PROCESS, DOC_TYPE, BUDGET_VERSION, DOCUMENT_DATE, YEAR, BUDGET_TYPE, FM_GRANT, FUND_CODE, FUND_CENTER, COMMITMENT_ITEM, FUNCTIONAL_AREA, FUNDED_PROGRAM, BUDGET_AMOUNT, LOCAL_CURRENCY, DISTRIBUTION_KEY, LINE_ITEM_TEXT, CREATE_STATUS,UPDATE_USER, UPDATE_TIMESTAMP,
				FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_LINE_ITEM,
				LS_BCS_VALUE_TYPE,
				LS_PROCESS,
				LS_DOC_TYPE,
				LS_BUDGET_VERSION,
				LS_DOCUMENT_DATE,
				LI_YEAR,
				LS_BUDGET_TYPE,
				LS_FM_GRANT,
				LS_FUND_CODE,
				LS_FUND_CENTER,
				LS_COMMITMENT_ITEM,
				LS_FUNCTIONAL_AREA,
				LS_FUNDED_PROGRAM,
				LS_BUDGET_AMOUNT,
				LS_LOCAL_CURRENCY,
				LS_DISTRIBUTION_KEY,
				LS_LINE_ITEM_TEXT,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_FM_BUD;
			
			END;
			COMMIT;
			
			-- -------------------ENDS SAP_FEED_TMPL_FM_BUDGET-----------------------------------------
			
			-- -------------------STARTS SAP_FEED_TMPL_WBS---------------------------------------------
			
			BEGIN
			
				DECLARE DONE8 INT DEFAULT FALSE;

				DECLARE CUR_WBS CURSOR FOR
				SELECT 
					WBS_ELEMENT, PROJECT, WBS_LEVEL, WBS_ELEMENT_HIERARCHY, SHORT_DESCRIPTION, PERSON_RESPONSIBLE_NUMBER, COMPANY_CODE, BUSINESS_AREA, CONTROLLING_AREA, PROFIT_CENTER, PROJECT_TYPE, PLANT, BASIC_START_DATE, BASIC_FINISH_DATE, KEYWORD_ID, RESPONSIBLE_COST_CENTER, ACCOUNT_ASSIGNMENT_ELEMENT, BILLING_ELEMENT, CURRENCY, OBJECT_CLASS, FACTORY_CALENDER, FUND, PRNCP_INVESTGTR, GST_CLAIMABLE, CREATE_STATUS
				FROM SAP_FEED_TMPL_WBS
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE8 = TRUE;

				OPEN CUR_WBS;
				INSERT_CUR_WBS_LOOP: LOOP 
				FETCH CUR_WBS INTO
				LS_WBS_ELEMENT,
				LS_PROJECT,
				LI_WBS_LEVEL,
				LS_WBS_ELEMENT_HIERARCHY,
				LS_SHORT_DESCRIPTION,
				LS_PERSON_RESPONSIBLE_NUMBER,
				LS_COMPANY_CODE,
				LS_BUSINESS_AREA,
				LS_CONTROLLING_AREA,
				LS_PROFIT_CENTER,
				LS_PROJECT_TYPE,
				LS_PLANT,
				LS_BASIC_START_DATE,
				LS_BASIC_FINISH_DATE,
				LS_KEYWORD_ID,
				LS_RESPONSIBLE_COST_CENTER,
				LS_ACCOUNT_ASSIGNMENT_ELEMENT,
				LS_BILLING_ELEMENT,
				LS_CURRENCY,
				LS_OBJECT_CLASS,
				LS_FACTORY_CALENDER,
				LS_FUND,
				LS_PRNCP_INVESTGTR,
				LS_GST_CLAIMABLE,
				LS_CREATE_STATUS;
				
				IF DONE8 THEN
					LEAVE INSERT_CUR_WBS_LOOP;
				END IF;
				
				INSERT INTO SAP_FEED_TMPL_WBS(
				BATCH_ID, FEED_ID, WBS_ELEMENT, PROJECT, WBS_LEVEL, WBS_ELEMENT_HIERARCHY, SHORT_DESCRIPTION, PERSON_RESPONSIBLE_NUMBER, COMPANY_CODE, BUSINESS_AREA, CONTROLLING_AREA, PROFIT_CENTER, PROJECT_TYPE, PLANT, BASIC_START_DATE, BASIC_FINISH_DATE, KEYWORD_ID, RESPONSIBLE_COST_CENTER, ACCOUNT_ASSIGNMENT_ELEMENT, BILLING_ELEMENT, CURRENCY, OBJECT_CLASS, FACTORY_CALENDER, FUND, PRNCP_INVESTGTR, GST_CLAIMABLE, CREATE_STATUS, UPDATE_USER, UPDATE_TIMESTAMP,FEED_STATUS
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_WBS_ELEMENT,
				LS_PROJECT,
				LI_WBS_LEVEL,
				LS_WBS_ELEMENT_HIERARCHY,
				LS_SHORT_DESCRIPTION,
				LS_PERSON_RESPONSIBLE_NUMBER,
				LS_COMPANY_CODE,
				LS_BUSINESS_AREA,
				LS_CONTROLLING_AREA,
				LS_PROFIT_CENTER,
				LS_PROJECT_TYPE,
				LS_PLANT,
				LS_BASIC_START_DATE,
				LS_BASIC_FINISH_DATE,
				LS_KEYWORD_ID,
				LS_RESPONSIBLE_COST_CENTER,
				LS_ACCOUNT_ASSIGNMENT_ELEMENT,
				LS_BILLING_ELEMENT,
				LS_CURRENCY,
				LS_OBJECT_CLASS,
				LS_FACTORY_CALENDER,
				LS_FUND,
				LS_PRNCP_INVESTGTR,
				LS_GST_CLAIMABLE,
				LS_CREATE_STATUS,
				LS_UPDATE_USER,
				UTC_TIMESTAMP(),
				'F'
				);
			
				END LOOP;
				CLOSE CUR_WBS;
			
			END;
			COMMIT;
			
			-- -------------------ENDS SAP_FEED_TMPL_WBS-----------------------------------------------

BEGIN
			
				DECLARE DONE9 INT DEFAULT FALSE;

				DECLARE CUR_FM_DERIVATION CURSOR FOR
				SELECT 
					CREATE_STATUS, FROM_WBS_ELEMENT, TO_WBS_ELEMENT, TARGET_FUNDS_CENTER, TARGET_FUND, TARGET_FUNDED_PROGRAM, TARGET_COMMITMENT_ITEM, TARGET_GRANT
				FROM SAP_FEED_TMPL_FM_DERIVATION
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE9 = TRUE;

				OPEN CUR_FM_DERIVATION;
				INSERT_CUR_FM_DERIVATION_LOOP: LOOP 
				FETCH CUR_FM_DERIVATION INTO
				LS_CREATE_STATUS,
				LS_FROM_WBS_ELEMENT,
				LS_TO_WBS_ELEMENT,
				LS_TARGET_FUND_CENTER,
				LS_TARGET_FUND_CODE,
				LS_TARGET_FUNDED_PROGRAM,
				LS_TARGET_COMMITMENT_ITEM,
				LS_TARGET_GRANT;
				
				IF DONE9 THEN
					LEAVE INSERT_CUR_FM_DERIVATION_LOOP;
				END IF;

				INSERT INTO SAP_FEED_TMPL_FM_DERIVATION(
				BATCH_ID, CREATE_STATUS, FEED_ID, FEED_STATUS, FROM_WBS_ELEMENT, TO_WBS_ELEMENT, TARGET_FUNDS_CENTER, TARGET_FUND, TARGET_FUNDED_PROGRAM, TARGET_COMMITMENT_ITEM, TARGET_GRANT, UPDATE_TIMESTAMP, UPDATE_USER
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				LS_CREATE_STATUS,
				AV_NEW_FEED_ID,
				'F',
				LS_FROM_WBS_ELEMENT,
				LS_TO_WBS_ELEMENT,
				LS_TARGET_FUND_CENTER,
				LS_TARGET_FUND_CODE,
				LS_TARGET_FUNDED_PROGRAM,
				LS_TARGET_COMMITMENT_ITEM,
				LS_TARGET_GRANT,
				UTC_TIMESTAMP(),
				LS_UPDATE_USER
				);
			
				END LOOP;
				CLOSE CUR_FM_DERIVATION;
			
			END;
			COMMIT;

-- -------------------ENDS SAP_FEED_TMPL_FM_DERIVATION-----------------------------------------------

				BEGIN
			
				DECLARE DONE10 INT DEFAULT FALSE;

				DECLARE CUR_GM_DERIVATION CURSOR FOR
				SELECT 
					CREATE_STATUS, WBS_ELEMENT, FROM_GL_ACCOUNT, TO_GL_ACCOUNT, SPONSORED_PROGRAM, SPONSORED_CLASS, GRANT_CODE, FUND
				FROM SAP_FEED_TMPL_GM_DERIVATION
				WHERE FEED_ID = AV_PREV_FEED_ID
				AND BATCH_ID = AV_PREV_BATCH_ID
				AND FEED_STATUS = 'E';
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE10 = TRUE;

				OPEN CUR_GM_DERIVATION;
				INSERT_CUR_GM_DERIVATION_LOOP: LOOP 
				FETCH CUR_GM_DERIVATION INTO
				LS_CREATE_STATUS,
				LS_WBS_ELEMENT,
				LS_FROM_GL_ACCOUNT,
				LS_TO_GL_ACCOUNT,
				LS_SPONSORED_PROGRAM,
				LS_SPONSORED_CLASS,
				LS_GRANT_CODE,
				LS_FUND;
				
				IF DONE10 THEN
					LEAVE INSERT_CUR_GM_DERIVATION_LOOP;
				END IF;

				INSERT INTO SAP_FEED_TMPL_GM_DERIVATION(
				BATCH_ID, CREATE_STATUS, FEED_ID, FEED_STATUS, WBS_ELEMENT,FROM_GL_ACCOUNT,TO_GL_ACCOUNT,SPONSORED_PROGRAM,SPONSORED_CLASS,GRANT_CODE,FUND, UPDATE_TIMESTAMP, UPDATE_USER
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				LS_CREATE_STATUS,
				AV_NEW_FEED_ID,
				'F',
				LS_WBS_ELEMENT,
				LS_FROM_GL_ACCOUNT,
				LS_TO_GL_ACCOUNT,
				LS_SPONSORED_PROGRAM,
				LS_SPONSORED_CLASS,
				LS_GRANT_CODE,
				LS_FUND,
				UTC_TIMESTAMP(),
				LS_UPDATE_USER
				);
			
				END LOOP;
				CLOSE CUR_GM_DERIVATION;
			
			END;
			COMMIT;

-- -------------------ENDS SAP_FEED_TMPL_GM_DERIVATION-----------------------------------------------

			UPDATE SAP_AWARD_FEED SET FEED_STATUS = 'F',UPDATE_USER = 'admin' ,UPDATE_TIMESTAMP = UTC_TIMESTAMP()
				WHERE FEED_ID = AV_NEW_FEED_ID;
				COMMIT;
END
