-- `SAP_AWARD_UPDATE_HOLD_STATUS_MANUALLY`; 

CREATE PROCEDURE `SAP_AWARD_UPDATE_HOLD_STATUS_MANUALLY`(
AV_AWARD_ID INT
)
    DETERMINISTIC
BEGIN
DECLARE LI_AWARD_ID 		INT;
DECLARE LS_AWARD_NUMBER 	VARCHAR(12);
DECLARE LI_SEQUENCE_NUMBER 	INT;
DECLARE LI_FLAG 			INT;
DECLARE LS_RETURN_VALUE		VARCHAR(10);
DECLARE LS_ERROR_MSG 		VARCHAR(1000);
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_AWARD_ID_LIST VARCHAR(4000);
DECLARE LS_AWARD_VARIATION_TYPE_CODE	VARCHAR(3);
DECLARE LS_AWARD_DOCUMENT_TYPE_CODE 	VARCHAR(3);
DECLARE LI_FEED_ID INT;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		    GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
		INSERT INTO SAP_AWARD_FEED_BATCH_ERROR_LOG(ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(CONCAT(' SAP_AWARD_UPDATE_HOLD_STATUS_MANUALLY ',SUBSTR(LS_ERROR_MSG,1,999)),NOW(),'admin');
	END;
	SET LI_AWARD_ID = AV_AWARD_ID;
	SELECT AWARD_NUMBER,SEQUENCE_NUMBER INTO LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER
	FROM AWARD WHERE AWARD_ID = AV_AWARD_ID;
			UPDATE AWARD SET STATUS_CODE = 12 , AWARD_SEQUENCE_STATUS = 'ARCHIVE' 
			WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
			SELECT AWARD_DOCUMENT_TYPE_CODE, AWARD_VARIATION_TYPE_CODE INTO LS_AWARD_DOCUMENT_TYPE_CODE, LS_AWARD_VARIATION_TYPE_CODE FROM AWARD WHERE AWARD_ID = LI_AWARD_ID;
			IF LS_AWARD_DOCUMENT_TYPE_CODE = 2 OR LS_AWARD_VARIATION_TYPE_CODE = 16 THEN
				UPDATE AWARD SET WORKFLOW_AWARD_STATUS_CODE = 3 , AWARD_SEQUENCE_STATUS = 'ACTIVE' 
				WHERE AWARD_ID = LI_AWARD_ID;
			ELSE 
				UPDATE AWARD SET WORKFLOW_AWARD_STATUS_CODE = 3,STATUS_CODE = '1' , AWARD_SEQUENCE_STATUS = 'ACTIVE' 
				WHERE AWARD_ID = LI_AWARD_ID;
			END IF;
			COMMIT;
			SET LS_AWARD_ID_LIST = CONCAT(ifnull(LS_AWARD_ID_LIST,''), ',',LI_AWARD_ID);
	SET LI_AWARD_ID = NULL;
	SELECT TRIM(BOTH ',' from LS_AWARD_ID_LIST) AS AWARD_ID_LIST;
END
