-- `SAP_FEED_WRITING_ERROR_ROWS`; 

CREATE PROCEDURE `SAP_FEED_WRITING_ERROR_ROWS`(
AV_PREV_FEED_ID 	INT,
AV_PREV_BATCH_ID	INT,
AV_NEW_FEED_ID		INT,
AV_NEW_BATCH_ID 	INT,
AV_TYPE 		VARCHAR(10)
)
BEGIN
DECLARE LI_GRANT_BUD_MASTER_ID	INT;
DECLARE LS_ERROR_MSG	VARCHAR(1000);
DECLARE LI_SEQ_ERROR_LOG_ID	INT;
DECLARE LS_GRANT_CODE			VARCHAR(20);
DECLARE LS_GM_DOC_TYPE			VARCHAR(2);
DECLARE LS_HEADER_DESCRIPTION	VARCHAR(40);
DECLARE LS_FUND_CODE			VARCHAR(10);
DECLARE LS_SPONSOR_PROGRAM		VARCHAR(20);
DECLARE LS_SPONSOR_CLASS		VARCHAR(20);
DECLARE LS_BUDGET_AMOUNT		DECIMAL(15,2);
DECLARE LS_POSTING_DATE		DATETIME;
DECLARE LS_DOCUMENT_DATE		DATETIME;
DECLARE LS_BUDGET_VERSION		VARCHAR(4);
DECLARE LS_LINE_ITEM_TEXT		VARCHAR(50);
DECLARE LS_GRANT_CUR			VARCHAR(3);
DECLARE LS_COMMITMENT_ITEM		VARCHAR(10);
DECLARE LS_FUNDED_PROGRAM		VARCHAR(20);
DECLARE LS_FUNCTIONAL_AREA		VARCHAR(8);
DECLARE LS_FUND_CENTER			VARCHAR(10);
DECLARE LS_DISTR_KEY			VARCHAR(1);
DECLARE LS_YEAR				INT(4);
DECLARE LS_FM_AREA				VARCHAR(3);
DECLARE LS_CREATE_STATUS		VARCHAR(1);
DECLARE LI_FLAG					INT;
DECLARE LS_FEED_STATUS          VARCHAR(1);
DECLARE LS_AWARD_NUMBR 			VARCHAR(12);
DECLARE LS_BCS_VALUE_TYPE			VARCHAR(2);
DECLARE LS_PROCESS					VARCHAR(4);
DECLARE LS_DOC_TYPE					VARCHAR(4); 
DECLARE LS_BUDGET_TYPE				VARCHAR(4);
DECLARE LS_FM_GRANT					VARCHAR(10);
DECLARE LS_LOCAL_CURRENCY			VARCHAR(3);
DECLARE LS_DISTRIBUTION_KEY			VARCHAR(1);
DECLARE LI_FM_ID 					INT;
DECLARE LS_LINE_ITEM				VARCHAR(20);
DECLARE LI_LINE_ITEM_COUNT			INT;
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
	
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		 
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		
		SELECT @full_error INTO LS_ERROR_MSG;
		
		SELECT IFNULL(MAX(BATCH_ERROR_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM SAP_AWARD_FEED_BATCH_ERROR_LOG;
			
		INSERT INTO SAP_AWARD_FEED_BATCH_ERROR_LOG(BATCH_ERROR_ID,ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,CONCAT('IN SAP_FEED_WRITING_ERROR_ROWS PROCEDURE ',SUBSTR(LS_ERROR_MSG,1,960)),NOW(),'admin');
			
		
	END;
	
	SELECT AWARD_NUMBER INTO LS_AWARD_NUMBR 
	FROM SAP_AWARD_FEED
	WHERE FEED_ID = AV_PREV_FEED_ID;
	
	IF AV_PREV_BATCH_ID IS NULL THEN
		
		SELECT MAX(BATCH_ID) INTO AV_PREV_BATCH_ID 
		FROM SAP_AWARD_FEED
		WHERE AWARD_NUMBER = LS_AWARD_NUMBR
		AND BATCH_ID IS NOT NULL
		AND FEED_ID < AV_NEW_FEED_ID;
		
		
	END IF;
	
	IF AV_TYPE = 'GM' THEN
	
		BEGIN
			DECLARE DONE4 INT DEFAULT FALSE;
						
			DECLARE CUR_MASTER_BUD_DETAIL CURSOR FOR 
			SELECT 
				DISTINCT
				PROCESS,
				GRANT_CODE,
				GM_DOC_TYPE,
				HEADER_DESCRIPTION,
				FUND_CODE,
				SPONSOR_PROGRAM,
				SPONSOR_CLASS,
				BUDGET_AMOUNT,
				POSTING_DATE,
				DOCUMENT_DATE,
				BUDGET_VERSION,
				LINE_ITEM_TEXT,
				GRANT_CUR,
				COMMITMENT_ITEM,
				FUNDED_PROGRAM,
				FUNCTIONAL_AREA,
				FUND_CENTER,
				DISTR_KEY,
				YEAR,
				FM_AREA,
				CREATE_STATUS,
				FEED_STATUS
			FROM 
			SAP_FEED_TMPL_GRANT_BUD_MASTER 
			WHERE FEED_ID in (SELECT FEED_ID FROM SAP_AWARD_FEED WHERE AWARD_NUMBER = LS_AWARD_NUMBR and FEED_ID <> AV_NEW_FEED_ID)
			AND BATCH_ID = AV_PREV_BATCH_ID
			AND (FEED_STATUS = 'E' OR FEED_STATUS IS NULL OR FEED_STATUS = '');
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;			
			OPEN CUR_MASTER_BUD_DETAIL;
			
			INSERT_LOOP4: LOOP 
			FETCH CUR_MASTER_BUD_DETAIL INTO
			LS_PROCESS,
			LS_GRANT_CODE,
			LS_GM_DOC_TYPE,
			LS_HEADER_DESCRIPTION,
			LS_FUND_CODE,
			LS_SPONSOR_PROGRAM,
			LS_SPONSOR_CLASS,
			LS_BUDGET_AMOUNT,
			LS_POSTING_DATE,
			LS_DOCUMENT_DATE,
			LS_BUDGET_VERSION,
			LS_LINE_ITEM_TEXT,
			LS_GRANT_CUR,
			LS_COMMITMENT_ITEM,
			LS_FUNDED_PROGRAM,
			LS_FUNCTIONAL_AREA,
			LS_FUND_CENTER,
			LS_DISTR_KEY,
			LS_YEAR,
			LS_FM_AREA,
			LS_CREATE_STATUS,
			LS_FEED_STATUS;
			
			IF DONE4 THEN
				LEAVE INSERT_LOOP4;
			END IF;
			
			SELECT COUNT(1) INTO LI_FLAG
			FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
			WHERE PROCESS = LS_PROCESS AND
				GRANT_CODE = LS_GRANT_CODE AND
				GM_DOC_TYPE = LS_GM_DOC_TYPE AND 
				HEADER_DESCRIPTION = LS_HEADER_DESCRIPTION AND
				FUND_CODE = LS_FUND_CODE AND 
				SPONSOR_PROGRAM = LS_SPONSOR_PROGRAM AND 
				SPONSOR_CLASS = LS_SPONSOR_CLASS AND 
				BUDGET_AMOUNT = LS_BUDGET_AMOUNT AND 
				DATE(POSTING_DATE) = DATE(LS_POSTING_DATE) AND
				DATE(DOCUMENT_DATE) = DATE(LS_DOCUMENT_DATE) AND 
				BUDGET_VERSION = LS_BUDGET_VERSION AND 
				IFNULL(LINE_ITEM_TEXT,'0') = IFNULL(LS_LINE_ITEM_TEXT,'0') AND
				GRANT_CUR = LS_GRANT_CUR AND
				COMMITMENT_ITEM = LS_COMMITMENT_ITEM AND 
				FUNDED_PROGRAM = LS_FUNDED_PROGRAM AND
				FUNCTIONAL_AREA = LS_FUNCTIONAL_AREA AND
				FUND_CENTER = LS_FUND_CENTER AND
				DISTR_KEY = LS_DISTR_KEY AND
				YEAR = LS_YEAR AND 
				FM_AREA = LS_FM_AREA AND
				CREATE_STATUS = LS_CREATE_STATUS AND
				IFNULL(FEED_STATUS,'0') = IFNULL(LS_FEED_STATUS,'0')
				AND FEED_ID = AV_NEW_FEED_ID
				AND BATCH_ID = AV_NEW_BATCH_ID;
			
			IF LI_FLAG = 0 THEN
			
				INSERT INTO SAP_FEED_TMPL_GRANT_BUD_MASTER
				(
				BATCH_ID, 
				FEED_ID, 
				PROCESS, 
				GRANT_CODE,
				GM_DOC_TYPE,					
				HEADER_DESCRIPTION, 
				FUND_CODE, 
				SPONSOR_PROGRAM, 
				SPONSOR_CLASS, 
				BUDGET_AMOUNT, 
				POSTING_DATE, 
				DOCUMENT_DATE, 
				BUDGET_VERSION, 
				LINE_ITEM_TEXT, 
				GRANT_CUR,
				COMMITMENT_ITEM,
				FUNDED_PROGRAM,
				FUNCTIONAL_AREA,
				FUND_CENTER,
				DISTR_KEY,
				YEAR,
				FM_AREA,
				CREATE_STATUS,
				UPDATE_USER, 
				UPDATE_TIMESTAMP
				)
				VALUES
				(
				AV_NEW_BATCH_ID,
				AV_NEW_FEED_ID,
				LS_PROCESS,
				LS_GRANT_CODE,
				LS_GM_DOC_TYPE,
				LS_HEADER_DESCRIPTION,
				LS_FUND_CODE,
				LS_SPONSOR_PROGRAM,
				LS_SPONSOR_CLASS,
				LS_BUDGET_AMOUNT,
				LS_POSTING_DATE,
				LS_DOCUMENT_DATE,
				LS_BUDGET_VERSION,
				LS_LINE_ITEM_TEXT,
				LS_GRANT_CUR,
				LS_COMMITMENT_ITEM,
				LS_FUNDED_PROGRAM,
				LS_FUNCTIONAL_AREA,
				LS_FUND_CENTER,
				LS_DISTR_KEY,
				LS_YEAR,
				LS_FM_AREA,
				LS_CREATE_STATUS,
				'admin',
				NOW()
				);
			
			
			END IF;
			SET LS_PROCESS = NULL;
			SET LS_GRANT_CODE = NULL;
			SET LS_GM_DOC_TYPE = NULL;
			SET LS_HEADER_DESCRIPTION = NULL;
			SET LS_FUND_CODE = NULL;
			SET LS_SPONSOR_PROGRAM = NULL;
			SET LS_SPONSOR_CLASS = NULL;
			SET LS_BUDGET_AMOUNT = NULL;
			SET LS_POSTING_DATE = NULL;
			SET LS_DOCUMENT_DATE = NULL;
			SET LS_BUDGET_VERSION = NULL;
			SET LS_LINE_ITEM_TEXT = NULL;
			SET LS_GRANT_CUR = NULL;
			SET LS_COMMITMENT_ITEM = NULL;
			SET LS_FUNDED_PROGRAM = NULL;
			SET LS_FUNCTIONAL_AREA = NULL;
			SET LS_FUND_CENTER = NULL;
			SET LS_DISTR_KEY = NULL;
			SET LS_YEAR = NULL;
			SET LS_FM_AREA = NULL;
			SET LS_CREATE_STATUS = NULL;
			SET LS_FEED_STATUS = NULL;
			
			
			END LOOP;
			CLOSE CUR_MASTER_BUD_DETAIL;
		
		END;
	
	
			
		
	ELSEIF AV_TYPE = 'FM' THEN
	
	SET LI_LINE_ITEM_COUNT = 0;	
	BEGIN
			DECLARE DONE5 INT DEFAULT FALSE;
						
			DECLARE CUR_FM_BUD_DETAIL CURSOR FOR 
			SELECT 
				DISTINCT
				LINE_ITEM,
				BCS_VALUE_TYPE,
				PROCESS,
				DOC_TYPE, 
				BUDGET_VERSION,
				DOCUMENT_DATE,
				YEAR,
				BUDGET_TYPE,
				FM_GRANT,
				FUND_CODE,
				FUND_CENTER,
				COMMITMENT_ITEM,
				FUNCTIONAL_AREA,
				FUNDED_PROGRAM,
				BUDGET_AMOUNT,
				LOCAL_CURRENCY,
				DISTRIBUTION_KEY,
				LINE_ITEM_TEXT,
				CREATE_STATUS,
				FEED_STATUS	
			FROM 
			SAP_FEED_TMPL_FM_BUDGET 
			WHERE FEED_ID in (SELECT FEED_ID FROM SAP_AWARD_FEED WHERE AWARD_NUMBER = LS_AWARD_NUMBR and FEED_ID <> AV_NEW_FEED_ID)
			AND BATCH_ID = AV_PREV_BATCH_ID
			AND (FEED_STATUS = 'E' OR FEED_STATUS IS NULL OR FEED_STATUS = '');
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE5 = TRUE;			
			OPEN CUR_FM_BUD_DETAIL;
			
			INSERT_LOOP5: LOOP 
			FETCH CUR_FM_BUD_DETAIL INTO
			LS_LINE_ITEM,
			LS_BCS_VALUE_TYPE,
			LS_PROCESS,
			LS_DOC_TYPE, 
			LS_BUDGET_VERSION,
			LS_DOCUMENT_DATE,
			LS_YEAR,
			LS_BUDGET_TYPE,
			LS_FM_GRANT,
			LS_FUND_CODE,
			LS_FUND_CENTER,
			LS_COMMITMENT_ITEM,
			LS_FUNCTIONAL_AREA,
			LS_FUNDED_PROGRAM,
			LS_BUDGET_AMOUNT,
			LS_LOCAL_CURRENCY,
			LS_DISTRIBUTION_KEY,
			LS_LINE_ITEM_TEXT,
			LS_CREATE_STATUS,
			LS_FEED_STATUS;
			
			IF DONE5 THEN
				LEAVE INSERT_LOOP5;
			END IF;
			
			SELECT COUNT(1) INTO LI_FLAG
			FROM SAP_FEED_TMPL_FM_BUDGET T1
			WHERE 
				BCS_VALUE_TYPE = LS_BCS_VALUE_TYPE AND
				PROCESS = LS_PROCESS AND 
				DOC_TYPE = LS_DOC_TYPE AND 
				BUDGET_VERSION = LS_BUDGET_VERSION AND 
				DATE(DOCUMENT_DATE) = DATE(LS_DOCUMENT_DATE) AND
				YEAR = LS_YEAR AND
				BUDGET_TYPE = LS_BUDGET_TYPE AND
				FM_GRANT = LS_FM_GRANT AND
				FUND_CODE = LS_FUND_CODE AND
				FUND_CENTER = LS_FUND_CENTER AND
				COMMITMENT_ITEM = LS_COMMITMENT_ITEM AND
				FUNCTIONAL_AREA = LS_FUNCTIONAL_AREA AND
				FUNDED_PROGRAM = LS_FUNDED_PROGRAM AND
				BUDGET_AMOUNT = LS_BUDGET_AMOUNT AND
				LOCAL_CURRENCY = LS_LOCAL_CURRENCY AND
				DISTRIBUTION_KEY = LS_DISTRIBUTION_KEY AND
				IFNULL(LINE_ITEM_TEXT,'0') = IFNULL(LINE_ITEM_TEXT,'0') AND 
				CREATE_STATUS = LS_CREATE_STATUS AND
				IFNULL(FEED_STATUS,'0') = IFNULL(LS_FEED_STATUS,'0')
				AND FEED_ID = AV_NEW_FEED_ID
				AND BATCH_ID = AV_NEW_BATCH_ID;
			
			IF LI_FLAG = 0 THEN
					INSERT INTO SAP_FEED_TMPL_FM_BUDGET
					(
					BATCH_ID,
					FEED_ID,
					LINE_ITEM,
					BCS_VALUE_TYPE,
					PROCESS,
					DOC_TYPE,
					BUDGET_VERSION,
					DOCUMENT_DATE,
					YEAR,
					BUDGET_TYPE,
					FM_GRANT,
					FUND_CODE,
					FUND_CENTER,
					COMMITMENT_ITEM,
					FUNCTIONAL_AREA,
					FUNDED_PROGRAM,
					BUDGET_AMOUNT,
					LOCAL_CURRENCY,
					DISTRIBUTION_KEY,
					LINE_ITEM_TEXT,
					CREATE_STATUS,
					UPDATE_USER,
					UPDATE_TIMESTAMP
					)
					VALUES
					(
					AV_NEW_BATCH_ID,
					AV_NEW_FEED_ID,
					LS_LINE_ITEM,
					LS_BCS_VALUE_TYPE,
					LS_PROCESS,
					LS_DOC_TYPE, 
					LS_BUDGET_VERSION,
					LS_DOCUMENT_DATE,
					LS_YEAR,
					LS_BUDGET_TYPE,
					LS_FM_GRANT,
					LS_FUND_CODE,
					LS_FUND_CENTER,
					LS_COMMITMENT_ITEM,
					LS_FUNCTIONAL_AREA,
					LS_FUNDED_PROGRAM,
					LS_BUDGET_AMOUNT,
					LS_LOCAL_CURRENCY,
					LS_DISTRIBUTION_KEY,
					LS_LINE_ITEM_TEXT,
					LS_CREATE_STATUS,
					'admin',
					now()
					);
				
			END IF;
			
			SET LS_BCS_VALUE_TYPE = NULL;
			SET LS_PROCESS = NULL;
			SET LS_DOC_TYPE = NULL; 
			SET LS_BUDGET_VERSION = NULL;
			SET LS_DOCUMENT_DATE = NULL;
			SET LS_YEAR = NULL;
			SET LS_BUDGET_TYPE = NULL;
			SET LS_FM_GRANT = NULL;
			SET LS_FUND_CODE = NULL;
			SET LS_FUND_CENTER = NULL;
			SET LS_COMMITMENT_ITEM = NULL;
			SET LS_FUNCTIONAL_AREA = NULL;
			SET LS_FUNDED_PROGRAM = NULL;
			SET LS_BUDGET_AMOUNT = NULL;
			SET LS_LOCAL_CURRENCY = NULL;
			SET LS_DISTRIBUTION_KEY = NULL;
			SET LS_LINE_ITEM_TEXT = NULL;
			SET LS_CREATE_STATUS = NULL;
			SET LS_FEED_STATUS = NULL;
			
			END LOOP;
			CLOSE CUR_FM_BUD_DETAIL;
		
		END;
	
			
	
	END IF;
	
			
	
END;
END
