-- `SAP_AWARD_UPDATE_HOLD_STATUS`; 

CREATE PROCEDURE `SAP_AWARD_UPDATE_HOLD_STATUS`(
)
    DETERMINISTIC
BEGIN
DECLARE LI_AWARD_ID 		INT;
DECLARE LS_AWARD_NUMBER 	VARCHAR(12);
DECLARE LI_SEQUENCE_NUMBER 	INT;
DECLARE LI_FLAG 			INT;
DECLARE LS_RETURN_VALUE		VARCHAR(10);
DECLARE LS_ERROR_MSG 		VARCHAR(1000);
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_AWARD_ID_LIST VARCHAR(4000);
DECLARE LS_AWARD_VARIATION_TYPE_CODE	VARCHAR(3);
DECLARE LS_AWARD_DOCUMENT_TYPE_CODE 	VARCHAR(3);
DECLARE LS_VARIATION_TYPE_CODE varchar(3);
DECLARE LI_FEED_ID INT;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		    GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
            SET @full_error = CONCAT(@msg,'|SEC117|',LS_TABLE_NAME );
			SELECT @full_error INTO LS_ERROR_MSG;
            RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
		INSERT INTO SAP_AWARD_FEED_BATCH_ERROR_LOG(ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(CONCAT(' SAP_AWARD_UPDATE_HOLD_STATUS ',SUBSTR(LS_ERROR_MSG,1,999)),NOW(),'admin');
		COMMIT;
	END;
BEGIN
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE CUR_SEL_DATA CURSOR FOR
	SELECT AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,AWARD_VARIATION_TYPE_CODE FROM AWARD
	WHERE WORKFLOW_AWARD_STATUS_CODE = 6;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	OPEN CUR_SEL_DATA;
	INSERT_LOOP: LOOP 
	FETCH CUR_SEL_DATA INTO
	LI_AWARD_ID,
	LS_AWARD_NUMBER,
	LI_SEQUENCE_NUMBER,
	LS_VARIATION_TYPE_CODE;
	IF DONE1 THEN
		LEAVE INSERT_LOOP;
	END IF;
		SELECT COUNT(1) INTO LI_FLAG
		FROM SAP_AWARD_FEED_BATCH_ERROR_LOG
		WHERE FEED_ID IN(SELECT FEED_ID FROM SAP_AWARD_FEED 
						 WHERE AWARD_ID = LI_AWARD_ID
		) AND ERROR_TYPE = 'GRANT_CODE_ERROR';
		IF LI_FLAG > 0 THEN
			IF LS_VARIATION_TYPE_CODE IN('4','12') THEN
				SET LI_FLAG = 1;
			ELSE
				SET LI_FLAG = 0;
			END IF;
		END IF;
	IF LI_FLAG = 0 THEN
		SET LS_RETURN_VALUE := FN_CHK_SAP_AWARD_FEED_RESPONSE(LS_AWARD_NUMBER , LI_AWARD_ID);
		IF LS_RETURN_VALUE = 'TRUE' THEN
			UPDATE AWARD SET STATUS_CODE = 12 , AWARD_SEQUENCE_STATUS = 'ARCHIVE',DOCUMENT_UPDATE_TIMESTAMP=utc_timestamp() 
			WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
			SELECT AWARD_DOCUMENT_TYPE_CODE, AWARD_VARIATION_TYPE_CODE INTO LS_AWARD_DOCUMENT_TYPE_CODE, LS_AWARD_VARIATION_TYPE_CODE FROM AWARD WHERE AWARD_ID = LI_AWARD_ID;
			IF LS_AWARD_DOCUMENT_TYPE_CODE = 2 OR LS_AWARD_VARIATION_TYPE_CODE = 16 THEN
				UPDATE AWARD SET WORKFLOW_AWARD_STATUS_CODE = 3 , AWARD_SEQUENCE_STATUS = 'ACTIVE',DOCUMENT_UPDATE_TIMESTAMP=utc_timestamp()  
				WHERE AWARD_ID = LI_AWARD_ID;
			ELSE 
				UPDATE AWARD SET WORKFLOW_AWARD_STATUS_CODE = 3,STATUS_CODE = '1' , AWARD_SEQUENCE_STATUS = 'ACTIVE',DOCUMENT_UPDATE_TIMESTAMP=utc_timestamp() 
				WHERE AWARD_ID = LI_AWARD_ID;
			END IF;
			COMMIT;
			SET LS_AWARD_ID_LIST = CONCAT(ifnull(LS_AWARD_ID_LIST,''), ',',LI_AWARD_ID);
		END IF;
	END IF;
	SET LI_AWARD_ID = NULL;
	SET LI_FEED_ID = NULL;
	END LOOP;
	CLOSE CUR_SEL_DATA;
	SELECT TRIM(BOTH ',' from LS_AWARD_ID_LIST) AS AWARD_ID_LIST;
END;
END
