-- `UPD_AWARD_TRANSACTION_STATUS`; 

CREATE PROCEDURE `UPD_AWARD_TRANSACTION_STATUS`(AV_TYPE INT)
BEGIN
BEGIN 
DECLARE LI_AWARD_ID DECIMAL(22,0);
DECLARE LS_AWARD_NUMBER VARCHAR(50);
DECLARE LI_SEQUENCE_NUMBER  INT(3);
DECLARE LI_ARCHIVE_AWARD_ID DECIMAL(22,0);
DECLARE LI_ARCHIVE_SEQUENCE_NUMBER  INT(3);
DECLARE LI_ARCHIVE_LI_COUNT  INT(3);
DECLARE LI_CANCELLED_COUNT  INT(3);
DECLARE LI_ADDITIONAL_TRANS_COUNT INT(3);
DECLARE LS_ERROR VARCHAR(1000);
DECLARE LI_COUNT  INT(3);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_ROOTAWRD_CURSOR CURSOR FOR 
		SELECT DISTINCT AWARD_NUMBER
		FROM AWARD WHERE AWARD_SEQUENCE_STATUS ='CANCELLED'
        AND  AWARD_NUMBER ='003032-00001'
		ORDER BY AWARD_NUMBER ASC;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO MIGRATION_ERROR_LOG(LEGACY_PROJECT_ID,LEGACY_WBS_NUMBER,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
			VALUES(LS_AWARD_NUMBER,LI_AWARD_ID,'Exception','UPD_AWARD_TRANSACTION_STATUS',SUBSTR(LS_ERROR,1,999),'During Migration',NULL);
			COMMIT;
		END;
		OPEN MIGRATION_ROOTAWRD_CURSOR;
		MIGRATION_ROOTAWRD_CURSOR_LOOP : LOOP
				FETCH MIGRATION_ROOTAWRD_CURSOR INTO LS_AWARD_NUMBER;
				IF DONE1 THEN
					LEAVE MIGRATION_ROOTAWRD_CURSOR_LOOP;
				END IF;
					BEGIN
						DECLARE DONE1 INT DEFAULT FALSE;
						DECLARE MIGRATION_ROOTAWRD_CURSOR1 CURSOR FOR 
						SELECT AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER 
						FROM AWARD 
						WHERE AWARD_NUMBER = LS_AWARD_NUMBER
						AND AWARD_SEQUENCE_STATUS ='CANCELLED'
						ORDER BY SEQUENCE_NUMBER ASC;
						DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
						DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
						BEGIN
							GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
							 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
							SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
							SELECT @full_error INTO LS_ERROR;
							INSERT INTO MIGRATION_ERROR_LOG(LEGACY_PROJECT_ID,LEGACY_WBS_NUMBER,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
							VALUES(LS_AWARD_NUMBER,LI_AWARD_ID,'Exception','UPD_AWARD_TRANSACTION_STATUS',SUBSTR(LS_ERROR,1,999),'During Migration',NULL);
							COMMIT;
						END;
						OPEN MIGRATION_ROOTAWRD_CURSOR1;
						MIGRATION_ROOTAWRD_CURSOR_LOOP1 : LOOP
								FETCH MIGRATION_ROOTAWRD_CURSOR1 INTO LI_AWARD_ID,LS_AWARD_NUMBER,LI_SEQUENCE_NUMBER;
								IF DONE1 THEN
									LEAVE MIGRATION_ROOTAWRD_CURSOR_LOOP1;
								END IF;
								SELECT COUNT(*) INTO LI_CANCELLED_COUNT 
								FROM AWARD_AMOUNT_INFO 
								WHERE AWARD_ID = LI_AWARD_ID;
								IF LI_CANCELLED_COUNT > 0 THEN
									SELECT COUNT(*) INTO LI_COUNT  
									FROM AWARD 
									WHERE AWARD_NUMBER = LS_AWARD_NUMBER
									AND AWARD_SEQUENCE_STATUS in ('ARCHIVE','ACTIVE')
									AND SEQUENCE_NUMBER < LI_SEQUENCE_NUMBER
									AND SEQUENCE_NUMBER  = (SELECT MAX(SEQUENCE_NUMBER) FROM AWARD WHERE AWARD_NUMBER = LS_AWARD_NUMBER 
															AND AWARD_SEQUENCE_STATUS in ('ARCHIVE','ACTIVE')
															AND SEQUENCE_NUMBER < LI_SEQUENCE_NUMBER);	
									IF LI_COUNT  > 0 THEN
										SELECT  AWARD_ID,SEQUENCE_NUMBER 
										INTO LI_ARCHIVE_AWARD_ID,LI_ARCHIVE_SEQUENCE_NUMBER
										FROM AWARD 
										WHERE AWARD_NUMBER = LS_AWARD_NUMBER
										AND AWARD_SEQUENCE_STATUS in ('ARCHIVE','ACTIVE')
										AND SEQUENCE_NUMBER < LI_SEQUENCE_NUMBER
										AND SEQUENCE_NUMBER  = (SELECT MAX(SEQUENCE_NUMBER) FROM AWARD WHERE AWARD_NUMBER = LS_AWARD_NUMBER 
																AND AWARD_SEQUENCE_STATUS in ('ARCHIVE','ACTIVE')
																AND SEQUENCE_NUMBER < LI_SEQUENCE_NUMBER);	
										SELECT COUNT(*) INTO LI_ARCHIVE_LI_COUNT 
										FROM AWARD_AMOUNT_INFO 
										WHERE AWARD_ID = LI_ARCHIVE_AWARD_ID;	
												SELECT COUNT(*) INTO LI_ADDITIONAL_TRANS_COUNT 
												FROM AWARD_AMOUNT_INFO 
												WHERE AWARD_ID =  LI_AWARD_ID
												AND TRANSACTION_ID NOT IN(SELECT TRANSACTION_ID 
												FROM AWARD_AMOUNT_INFO 
												WHERE AWARD_ID =  LI_ARCHIVE_AWARD_ID);
												IF LI_ADDITIONAL_TRANS_COUNT > 0 THEN
													UPDATE  AWARD_AMOUNT_TRANSACTION
													SET TRANSACTION_STATUS_CODE = 'V'
													WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID 
																				FROM AWARD_AMOUNT_INFO 
																				WHERE AWARD_ID =  LI_AWARD_ID
																				AND TRANSACTION_ID NOT IN(SELECT TRANSACTION_ID 
																				FROM AWARD_AMOUNT_INFO 
																				WHERE AWARD_ID = LI_ARCHIVE_AWARD_ID))
													AND TRANSACTION_STATUS_CODE IS NULL;
													UPDATE  AWARD_AMOUNT_TRANSACTION
													SET TRANSACTION_STATUS_CODE = 'A'
													WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID 
																				FROM AWARD_AMOUNT_INFO 
																				WHERE AWARD_ID =  LI_ARCHIVE_AWARD_ID)
													AND TRANSACTION_STATUS_CODE IS NULL;
												END IF;
									END IF;
								END IF;
						END LOOP;
						CLOSE MIGRATION_ROOTAWRD_CURSOR1;
						END;
		END LOOP;
		CLOSE MIGRATION_ROOTAWRD_CURSOR;
END;
END
