CREATE TABLE `award_status` (
  `STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`STATUS_CODE`)
);
