


CREATE PROCEDURE COI_INT_VALDTE_PERSN_DETILS(AV_PERSON_FEED_ID INT)
BEGIN
    DECLARE LS_PERSON_ID VARCHAR(40);
    DECLARE LS_COUNTRY_OF_CITIZENSHIP VARCHAR(30);
    DECLARE LS_COUNTRY_CODE VARCHAR(3);
    DECLARE LS_HOME_UNIT VARCHAR(8);
    DECLARE LI_COUNT INT DEFAULT 0;
    DECLARE NOT_FOUND INT DEFAULT 0;
    DECLARE LS_VALIDATION_STATUS LONGTEXT DEFAULT '';
    DECLARE LS_INVALID_PERSONS LONGTEXT DEFAULT '';
    DECLARE LS_ERROR_MSG VARCHAR(4000) DEFAULT NULL;
    DECLARE LS_PROC_LOC VARCHAR(1000) DEFAULT 'START';
    DECLARE LI_BEFORE_COUNT INT DEFAULT 0;
    DECLARE LI_UPD_COUNT INT DEFAULT 0;
    DECLARE LI_TOTAL_COUNT INT DEFAULT 0;


    DECLARE INVALID_UNIT_PERSONS TEXT DEFAULT '';
    DECLARE INVALID_COUNTRY_CITIZENSHIP_PERSONS TEXT DEFAULT '';
    DECLARE INVALID_COUNTRY_CODE_PERSONS TEXT DEFAULT '';

    DECLARE SEL_DATA CURSOR FOR 
	SELECT PERSON_ID, TRIM(COUNTRY_OF_CITIZENSHIP), TRIM(COUNTRY_CODE), TRIM(HOME_UNIT) 
	FROM FIBI_COI_PERSON 
	WHERE (VALIDATION_STATUS = 'PENDING' OR VALIDATION_STATUS = 'ERROR')
    AND (COUNTRY_OF_CITIZENSHIP IS NOT NULL 
		OR COUNTRY_CODE IS NOT NULL 
		OR HOME_UNIT IS NOT NULL);


    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
    
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN	
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
            
			INSERT INTO FIBI_COI_INT_ERROR_LOG (SECTION,ERROR_TYPE,ERROR_MESSAGE,ERROR_DETAILS,MODULE_CODE,MODULE_ITEM_KEY, 
			MODULE_SUB_ITEM_KEY,UPDATE_TIMESTAMP) VALUES ('PERSON','DATABASE',LS_ERROR_MSG, CONCAT('ERROR IN COI_INT_VALDTE_PERSN_DETILS : ',LS_ERROR_MSG,' AT ',LS_PROC_LOC),
			'6',LS_PERSON_ID,NULL,CURRENT_TIMESTAMP);		
		END;
    SET LS_PROC_LOC = 'SEL_DATA'; 

SELECT COUNT(1) INTO LI_BEFORE_COUNT FROM PERSON;

SET SQL_SAFE_UPDATES = 0;
    OPEN SEL_DATA;

    SEL_DATA: LOOP
    SET NOT_FOUND = 0;
        FETCH SEL_DATA INTO LS_PERSON_ID, LS_COUNTRY_OF_CITIZENSHIP, LS_COUNTRY_CODE, LS_HOME_UNIT;

        IF NOT_FOUND = 1 THEN
            LEAVE SEL_DATA;
        END IF;
        
      IF LS_HOME_UNIT IS NOT NULL AND LS_HOME_UNIT<> '' THEN 
        SET LI_COUNT = 0;
        SELECT COUNT(1) INTO LI_COUNT FROM UNIT WHERE UPPER(UNIT_NUMBER) = UPPER(LS_HOME_UNIT);

        IF LI_COUNT = 0 THEN 
            UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'ERROR', VALIDATION_MESSEGE = CONCAT(LS_PERSON_ID,' - Person Home unit ''',LS_HOME_UNIT,''' is not Available in Unit Table') WHERE PERSON_ID = LS_PERSON_ID;
            ITERATE SEL_DATA;
        END IF;
	  END IF;
      
      IF LS_COUNTRY_OF_CITIZENSHIP IS NOT NULL AND LS_COUNTRY_OF_CITIZENSHIP <> '' THEN 
        SET LI_COUNT = 0;
        SELECT COUNT(1) INTO LI_COUNT FROM COUNTRY WHERE UPPER(COUNTRY_NAME) = UPPER(LS_COUNTRY_OF_CITIZENSHIP);

        IF LI_COUNT = 0 THEN 
            UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'ERROR', VALIDATION_MESSEGE = CONCAT(LS_PERSON_ID,' - Person Country of Citizen Code ''',LS_COUNTRY_OF_CITIZENSHIP,''' is not Available in Country Table') WHERE PERSON_ID = LS_PERSON_ID;
            ITERATE SEL_DATA;
        END IF;
        
	END IF;

		IF LS_COUNTRY_CODE IS NOT NULL AND LS_COUNTRY_CODE <> '' THEN 
        SET LI_COUNT = 0;
        SELECT COUNT(1) INTO LI_COUNT FROM COUNTRY WHERE ((UPPER(COUNTRY_CODE_ISO2) = UPPER(LS_COUNTRY_CODE)) OR (UPPER(COUNTRY_CODE) = UPPER(LS_COUNTRY_CODE)));
        IF LI_COUNT = 0 THEN 
            UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'ERROR', VALIDATION_MESSEGE = CONCAT(LS_PERSON_ID,' - Person Country Code ''',LS_COUNTRY_CODE,''' is not Available in Country Table') WHERE PERSON_ID = LS_PERSON_ID;
            ITERATE SEL_DATA;
        END IF;
		END IF;
    
	COMMIT;

    END LOOP;    

    CLOSE SEL_DATA;
    UPDATE FIBI_COI_PERSON SET VALIDATION_STATUS = 'SUCCESS' WHERE VALIDATION_STATUS = 'PENDING';
    
    SET LS_PROC_LOC = 'PERSON_INTEGRATION';   

    SELECT COUNT(1) INTO LI_UPD_COUNT FROM PERSON WHERE PERSON_ID IN (SELECT PERSON_ID FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'SUCCESS');
 
    SET FOREIGN_KEY_CHECKS = 0;
    DELETE FROM PERSON WHERE PERSON_ID IN (SELECT PERSON_ID FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'SUCCESS');
    SET FOREIGN_KEY_CHECKS = 1;

    INSERT INTO PERSON (
    PERSON_ID, LAST_NAME, FIRST_NAME, MIDDLE_NAME, FULL_NAME, PRIOR_NAME,
    USER_NAME, EMAIL_ADDRESS, DATE_OF_BIRTH, AGE, AGE_BY_FISCAL_YEAR, GENDER,
    EDUCATION_LEVEL, OFFICE_LOCATION, OFFICE_PHONE, SECONDRY_OFFICE_LOCATION, 
    SECONDRY_OFFICE_PHONE, SCHOOL, DIRECTORY_DEPARTMENT, SALUTATION,
    COUNTRY_OF_CITIZENSHIP, PRIMARY_TITLE, DIRECTORY_TITLE, HOME_UNIT, IS_FACULTY,
    IS_GRADUATE_STUDENT_STAFF, IS_RESEARCH_STAFF, IS_SERVICE_STAFF, IS_SUPPORT_STAFF,
    IS_OTHER_ACCADEMIC_GROUP, IS_MEDICAL_STAFF, ADDRESS_LINE_1, ADDRESS_LINE_2,
    ADDRESS_LINE_3, CITY, COUNTY, STATE, POSTAL_CODE, COUNTRY_CODE,
    FAX_NUMBER, PAGER_NUMBER, MOBILE_PHONE_NUMBER, VISA_CODE, VISA_TYPE,
    VISA_RENEWAL_DATE, STATUS, SALARY_ANNIVERSARY_DATE, UPDATE_TIMESTAMP,
    UPDATE_USER
	)
	SELECT 
		T1.PERSON_ID, T1.LAST_NAME, T1.FIRST_NAME, T1.MIDDLE_NAME, T1.FULL_NAME, T1.PRIOR_NAME,
		T1.USER_NAME, T1.EMAIL_ADDRESS, T1.DATE_OF_BIRTH, T1.AGE, T1.AGE_BY_FISCAL_YEAR, T1.GENDER,
		T1.EDUCATION_LEVEL, T1.OFFICE_LOCATION, T1.OFFICE_PHONE, T1.SECONDRY_OFFICE_LOCATION, 
		T1.SECONDRY_OFFICE_PHONE, T1.SCHOOL, T1.DIRECTORY_DEPARTMENT, T1.SALUTATION,
		(SELECT COUNTRY_CODE FROM COUNTRY WHERE UPPER(TRIM(COUNTRY_NAME)) = UPPER(TRIM(T1.COUNTRY_OF_CITIZENSHIP))), T1.PRIMARY_TITLE, T1.DIRECTORY_TITLE, T1.HOME_UNIT, T1.IS_FACULTY,
		T1.IS_GRADUATE_STUDENT_STAFF, T1.IS_RESEARCH_STAFF, T1.IS_SERVICE_STAFF, T1.IS_SUPPORT_STAFF,
		T1.IS_OTHER_ACCADEMIC_GROUP, T1.IS_MEDICAL_STAFF, T1.ADDRESS_LINE_1, T1.ADDRESS_LINE_2,
		T1.ADDRESS_LINE_3, T1.CITY, T1.COUNTY, T1.STATE, T1.POSTAL_CODE, (SELECT COUNTRY_CODE FROM COUNTRY WHERE UPPER(TRIM(COUNTRY_CODE_ISO2)) = UPPER(TRIM(T1.COUNTRY_CODE))),
		T1.FAX_NUMBER, T1.PAGER_NUMBER, T1.MOBILE_PHONE_NUMBER, T1.VISA_CODE, VISA_TYPE,
		T1.VISA_RENEWAL_DATE, T1.STATUS, T1.SALARY_ANNIVERSARY_DATE, T1.UPDATE_TIMESTAMP,
		T1.UPDATE_USER
	FROM FIBI_COI_PERSON T1 WHERE T1.VALIDATION_STATUS = 'SUCCESS'; 
    
     SET LS_PROC_LOC = 'PERSON_INTEGRATION_STATUS_SETUP'; 

     SELECT COUNT(1) INTO LI_TOTAL_COUNT FROM PERSON;

	SET SESSION group_concat_max_len = 4294967295;
    SELECT GROUP_CONCAT(CONCAT(PERSON_ID,' : ',VALIDATION_MESSEGE)) INTO LS_VALIDATION_STATUS FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'ERROR';
    SELECT GROUP_CONCAT(PERSON_ID) INTO LS_INVALID_PERSONS FROM FIBI_COI_PERSON WHERE VALIDATION_STATUS = 'ERROR';  
   
    SET SQL_SAFE_UPDATES = 1;
    SELECT IFNULL(LS_VALIDATION_STATUS,'SUCCESS') AS VALIDATION_MESSAGE,LS_INVALID_PERSONS AS INVALID_PERSON_IDS,IFNULL(CASE WHEN (LI_TOTAL_COUNT - LI_BEFORE_COUNT) < 0 THEN 0 END,0) AS NO_OF_NEW_RECORDS,
     IFNULL(LI_UPD_COUNT,0) AS NO_OF_UPDATE_RECORDS;
END