CREATE PROCEDURE COPY_FORM_DATA_TO_NEW_VERSION(
    IN AV_NEW_FORM_ID INT,
    IN AV_OLD_FORM_ID INT,
    IN AV_OLD_MODULE_ITEM_KEY VARCHAR(50),
    IN AV_NEW_MODULE_ITEM_KEY VARCHAR(50),
    IN AV_MODULE_ITEM_CODE INT,
    IN AV_MODULE_SUB_ITEM_CODE INT,
    IN AV_MODULE_SUB_ITEM_KEY VARCHAR(20),
    IN AV_UPDATE_USER VARCHAR(60)
)
BEGIN

    DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT;
    DECLARE LI_MODULE_ITEM_CODE INT;
    DECLARE LI_MODULE_SUB_ITEM_CODE INT;
    DECLARE LI_MODULE_SUB_ITEM_KEY INT DEFAULT NULL;
    DECLARE LS_VALUE VARCHAR(4000);
    DECLARE LS_DESCRIPTION VARCHAR(255);
    DECLARE LS_OLD_QNR_ID VARCHAR(10);
    DECLARE LI_QUESTIONNAIRE_NUMBER INT;
    DECLARE LI_QUESTIONNAIRE_ANS_HEADER_ID INT;
    DECLARE LS_NEW_FB_SECTION_COMPONENT_ID VARCHAR(20);
    DECLARE LS_NEW_QNR_ID VARCHAR(10);
    DECLARE LI_ANS_HEADER_ID INT;
    DECLARE DONE INT DEFAULT FALSE;

    DECLARE CUR CURSOR FOR 
        SELECT 
            ANSWER.CUSTOM_DATA_ELEMENTS_ID, 
            ANSWER.MODULE_ITEM_CODE,
            ANSWER.MODULE_SUB_ITEM_CODE,
            cmp.FORM_BUILDER_SECT_COMP_ID AS MODULE_SUB_ITEM_KEY,
            ANSWER.VALUE,
            ANSWER.DESCRIPTION 
        FROM FB_COMP_CUSTOM_ELEMENT_ANSWER ANSWER
        INNER JOIN FORM_BUILDER_SECTION_COMPONENT COMPONENT 
            ON ANSWER.MODULE_SUB_ITEM_KEY = COMPONENT.FORM_BUILDER_SECT_COMP_ID
        INNER JOIN FORM_BUILDER_SECTION SECTION 
            ON COMPONENT.FORM_BUILDER_SECTION_ID = SECTION.FORM_BUILDER_SECTION_ID
        INNER JOIN FORM_BUILDER_SECTION_COMPONENT cmp 
            ON cmp.COMPONENT_REF_ID = COMPONENT.COMPONENT_REF_ID
        INNER JOIN FORM_BUILDER_SECTION NEW_SECTION 
            ON cmp.FORM_BUILDER_SECTION_ID = NEW_SECTION.FORM_BUILDER_SECTION_ID  
        WHERE SECTION.FORM_BUILDER_ID = AV_OLD_FORM_ID
        AND NEW_SECTION.FORM_BUILDER_ID = AV_NEW_FORM_ID
        AND ANSWER.MODULE_ITEM_KEY = AV_OLD_MODULE_ITEM_KEY;

    DECLARE QNR_CURSOR CURSOR FOR 
        SELECT 
            fb_old.COMPONENT_REF_ID, 
            qnr_old.QUESTIONNAIRE_NUMBER, 
            ans_header.QUESTIONNAIRE_ANS_HEADER_ID, 
            fb_new.COMPONENT_REF_ID,
            fb_new.FORM_BUILDER_SECT_COMP_ID
        FROM FORM_BUILDER_SECTION_COMPONENT fb_old
        INNER JOIN FORM_BUILDER_SECTION section_old 
            ON fb_old.FORM_BUILDER_SECTION_ID = section_old.FORM_BUILDER_SECTION_ID
        INNER JOIN QUEST_HEADER qnr_old 
            ON fb_old.COMPONENT_REF_ID = qnr_old.QUESTIONNAIRE_ID
        INNER JOIN FB_QUEST_ANSWER_HEADER ans_header 
            ON qnr_old.QUESTIONNAIRE_ID = ans_header.QUESTIONNAIRE_ID 
            AND ans_header.MODULE_SUB_ITEM_KEY = fb_old.FORM_BUILDER_SECT_COMP_ID
        INNER JOIN QUEST_HEADER qnr_match 
            ON qnr_match.QUESTIONNAIRE_NUMBER = qnr_old.QUESTIONNAIRE_NUMBER
        INNER JOIN FORM_BUILDER_SECTION_COMPONENT fb_new 
            ON fb_new.COMPONENT_REF_ID = qnr_match.QUESTIONNAIRE_ID
        INNER JOIN FORM_BUILDER_SECTION section_new 
            ON fb_new.FORM_BUILDER_SECTION_ID = section_new.FORM_BUILDER_SECTION_ID
            AND fb_new.COMPONENT_REF_ID = qnr_match.QUESTIONNAIRE_ID
        WHERE section_old.FORM_BUILDER_ID = AV_OLD_FORM_ID
            AND ans_header.MODULE_ITEM_KEY = AV_OLD_MODULE_ITEM_KEY
            AND ans_header.MODULE_ITEM_CODE = AV_MODULE_ITEM_CODE
            AND fb_old.COMPONENT_TYPE_CODE = 'QN' 
            AND section_new.FORM_BUILDER_ID = AV_NEW_FORM_ID
            AND fb_new.COMPONENT_TYPE_CODE = 'QN'
        ORDER BY fb_old.COMPONENT_ORDER_NUMBER;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;

    SET DONE = FALSE;

    SELECT ANS_HEADER_ID
    INTO LI_ANS_HEADER_ID
    FROM FORM_BUILDER_ANS_HEADER
    WHERE MODULE_ITEM_KEY = AV_OLD_MODULE_ITEM_KEY AND FORM_BUILDER_ID = AV_OLD_FORM_ID 
    AND MODULE_ITEM_CODE = AV_MODULE_ITEM_CODE AND MODULE_SUB_ITEM_CODE = AV_MODULE_SUB_ITEM_CODE
    AND MODULE_SUB_ITEM_KEY = AV_MODULE_SUB_ITEM_KEY;

    IF LI_ANS_HEADER_ID IS NOT NULL THEN
        INSERT INTO FORM_BUILDER_ANS_HEADER(
            FORM_BUILDER_ID, 
            MODULE_ITEM_CODE, 
            MODULE_SUB_ITEM_CODE, 
            MODULE_ITEM_KEY, 
            MODULE_SUB_ITEM_KEY, 
            CREATE_TIMESTAMP, 
            CREATE_USER, 
            UPDATE_TIMESTAMP, 
            UPDATE_USER
        ) VALUES (
            AV_NEW_FORM_ID, 
            AV_MODULE_ITEM_CODE, 
            AV_MODULE_SUB_ITEM_CODE,
            AV_NEW_MODULE_ITEM_KEY,
            AV_MODULE_SUB_ITEM_KEY, 
            UTC_TIMESTAMP(), 
            AV_UPDATE_USER,
            UTC_TIMESTAMP(), 
            AV_UPDATE_USER
        );
    END IF;

    OPEN CUR;
    FETCH_LOOP: LOOP
        FETCH CUR INTO LI_CUSTOM_DATA_ELEMENTS_ID, LI_MODULE_ITEM_CODE, LI_MODULE_SUB_ITEM_CODE, LI_MODULE_SUB_ITEM_KEY, LS_VALUE, LS_DESCRIPTION;
        
        IF DONE THEN
            LEAVE FETCH_LOOP;
        END IF;

        IF LI_MODULE_SUB_ITEM_KEY IS NULL THEN
            SET LI_MODULE_SUB_ITEM_KEY = 0;
        END IF;

        INSERT INTO FB_COMP_CUSTOM_ELEMENT_ANSWER(
            CUSTOM_DATA_ELEMENTS_ID, 
            MODULE_ITEM_CODE, 
            MODULE_ITEM_KEY, 
            MODULE_SUB_ITEM_CODE, 
            MODULE_SUB_ITEM_KEY, 
            UPDATE_TIMESTAMP, 
            UPDATE_USER, 
            VALUE, 
            DESCRIPTION
        ) VALUES (
            LI_CUSTOM_DATA_ELEMENTS_ID, 
            LI_MODULE_ITEM_CODE, 
            AV_NEW_MODULE_ITEM_KEY,
            LI_MODULE_SUB_ITEM_CODE, 
            LI_MODULE_SUB_ITEM_KEY, 
            UTC_TIMESTAMP(), 
            AV_UPDATE_USER,
            LS_VALUE, 
            LS_DESCRIPTION
        );
    END LOOP;
    CLOSE CUR;

    SET DONE = FALSE;
    OPEN QNR_CURSOR;
    READ_LOOP: LOOP
        FETCH QNR_CURSOR INTO LS_OLD_QNR_ID, LI_QUESTIONNAIRE_NUMBER, LI_QUESTIONNAIRE_ANS_HEADER_ID, LS_NEW_QNR_ID ,LS_NEW_FB_SECTION_COMPONENT_ID;
        
        IF DONE THEN
            LEAVE READ_LOOP;
        END IF;

        IF LS_NEW_QNR_ID IS NOT NULL AND LI_QUESTIONNAIRE_ANS_HEADER_ID IS NOT NULL THEN
        CALL UPD_FB_ANS_TO_NEW_QUEST_VERSN(LS_NEW_QNR_ID, LI_QUESTIONNAIRE_ANS_HEADER_ID, AV_UPDATE_USER,LS_NEW_FB_SECTION_COMPONENT_ID);
        END IF;

    END LOOP;
    CLOSE QNR_CURSOR;

END
