


CREATE PROCEDURE `ENRICH_ENTITY_CORPORATE_LINKAGE`(
    IN AV_ENTITY_ID INT,
    IN AV_FAMILY_ROLE_TYPE_CODE VARCHAR(5),
    IN AV_PERSON_ID VARCHAR(40)
)
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM ENTITY_FAMILY_TREE_ROLE
        WHERE ENTITY_ID = AV_ENTITY_ID 
          AND FAMILY_ROLE_TYPE_CODE = AV_FAMILY_ROLE_TYPE_CODE
    ) THEN
        INSERT INTO ENTITY_FAMILY_TREE_ROLE(ENTITY_ID, FAMILY_ROLE_TYPE_CODE, UPDATE_TIMESTAMP, UPDATED_BY)
        VALUES (AV_ENTITY_ID, AV_FAMILY_ROLE_TYPE_CODE, NOW(), AV_PERSON_ID);
    END IF;
END