


CREATE PROCEDURE `GET_AWARD_DASHBOARD_OVERVIEW`(
    AV_PERSON_ID                    VARCHAR(40),
    AV_PAGED                        INT,
    AV_LIMIT                        INT,
    AV_IS_COUNT                     BOOLEAN,
    AV_SEARCHWORD                   VARCHAR(100)
)
BEGIN
    DECLARE LS_FILTER_CONDITION LONGTEXT;
    DECLARE LS_JOIN_CONDITION   LONGTEXT;
    DECLARE LS_DYN_SQL          LONGTEXT;
    DECLARE LS_OFFSET_CONDITION VARCHAR(600);
    DECLARE LS_OFFSET           INT;
	DECLARE SEARCH_CONDITION    LONGTEXT;

    -- Initialize variables
    SET LS_DYN_SQL = '';
    SET LS_FILTER_CONDITION = '';
    SET LS_JOIN_CONDITION = '';
	SET SEARCH_CONDITION = '';
    SET LS_OFFSET = COALESCE(AV_LIMIT * AV_PAGED, 0);

    -- Construct join condition
    SET LS_JOIN_CONDITION = CONCAT(' INNER JOIN COI_PROJECT_TYPE T2 ON T2.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
									  LEFT JOIN (SELECT DISTINCT AW2.PROJECT_NUMBER 
									  FROM COI_INT_STAGE_AWARD AW1 
									  INNER JOIN COI_INT_STAGE_AWARD AW2 ON AW2.ROOT_PROJECT_NUMBER = AW1.ROOT_PROJECT_NUMBER 
									  INNER JOIN COI_INT_STAGE_AWARD_PERSON AW3 ON AW3.PROJECT_NUMBER = AW2.PROJECT_NUMBER 
									  WHERE AW2.PROJECT_STATUS_CODE IN (1, 6, 3) 
									  AND AW3.KEY_PERSON_ID = ''', AV_PERSON_ID, ''' 
									  AND NOT EXISTS (SELECT 1 FROM COI_INT_STAGE_AWARD ROOT
													 WHERE ROOT.PROJECT_NUMBER = AW1.ROOT_PROJECT_NUMBER
													 AND ROOT.PROJECT_STATUS_CODE = 5
													)) T5 ON T5.PROJECT_NUMBER = T1.AWARD_NUMBER '
								  );

    -- Construct filter condition
    SET LS_FILTER_CONDITION = CONCAT(' WHERE T1.KEY_PERSON_ID = ''', AV_PERSON_ID, ''' 
										 AND T1.PERSON_STATUS != ''I'' 
										 AND ((T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'') 
										 OR (T1.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED'' 
										 AND (T1.DISCLOSURE_VALIDATION_FLAG IS NULL OR T1.DISCLOSURE_VALIDATION_FLAG = ''HIERARCHY'') 
										 AND T5.PROJECT_NUMBER IS NOT NULL)) 
										 AND T1.AWARD_STATUS_CODE IN (1, 6, 3)										 '
									);

    IF AV_SEARCHWORD IS NOT NULL THEN
            SET AV_SEARCHWORD = CONCAT('''%',AV_SEARCHWORD, '%''');
            SET SEARCH_CONDITION = CONCAT(' AND (PROJECT_NUMBER LIKE ',AV_SEARCHWORD, ' OR TITLE LIKE ', AV_SEARCHWORD, ' OR LEAD_UNIT_NAME LIKE ',
                AV_SEARCHWORD, ' )');
        END IF;

    IF AV_IS_COUNT = TRUE THEN
        SET LS_OFFSET_CONDITION = '';
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' SELECT COUNT(*) ');
    ELSE
		IF AV_LIMIT = 0 THEN
			SET LS_OFFSET_CONDITION = '';
		ELSE
			SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ', AV_LIMIT, ' OFFSET ', LS_OFFSET);					
		END IF;
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, ' SELECT * ');
    END IF;


    SET LS_DYN_SQL = CONCAT(
							LS_DYN_SQL,
							' FROM (WITH Awards AS (
							 SELECT DISTINCT T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_ID,
														T1.AWARD_NUMBER AS PROJECT_NUMBER,T1.TITLE,T1.PI_NAME,
														T1.KEY_PERSON_ROLE_NAME AS KEY_PERSON_ROLE,T1.SPONSOR_NAME, 
														T1.SPONSOR_CODE,T1.PRIME_SPONSOR_NAME,T1.PRIME_SPONSOR_CODE,
														T1.LEAD_UNIT_NUMBER,T1.LEAD_UNIT_NAME,T1.AWARD_START_DATE,
														T1.AWARD_END_DATE,T1.AWARD_STATUS AS PROJECT_STATUS,T2.COI_PROJECT_TYPE_CODE AS PROJECT_TYPE_CODE,
														T2.DESCRIPTION AS PROJECT_TYPE,T2.BADGE_COLOR,
														T1.UPDATE_TIMESTAMP,T1.DISCLOSURE_VALIDATION_FLAG,T1.DISCLOSURE_REQUIRED_FLAG,T2.PROJECT_ICON,T1.DOCUMENT_NUMBER,T1.ACCOUNT_NUMBER,
														ROW_NUMBER() OVER (PARTITION BY SUBSTRING_INDEX(T1.AWARD_NUMBER, ''-'', 1)  
														ORDER BY CASE 
																		WHEN T1.DISCLOSURE_VALIDATION_FLAG = ''SELF'' THEN 1
																		WHEN (T1.DISCLOSURE_VALIDATION_FLAG = ''HIERARCHY'' OR DISCLOSURE_VALIDATION_FLAG IS NULL) 
																		AND T1.DISCLOSURE_REQUIRED_FLAG= ''REQUIRED'' THEN 2
																		ELSE 3
																END,
														CAST(SUBSTRING_INDEX(T1.AWARD_NUMBER, ''-'', -1) AS UNSIGNED) ASC) AS rn,
														T1.NEW_DISCLOSURE_REQUIRED
							 FROM COI_PROJECT_AWARD_V T1 ', LS_JOIN_CONDITION,'', LS_FILTER_CONDITION, ') 
							 SELECT * FROM Awards WHERE PROJECT_NUMBER NOT IN (
																SELECT MODULE_ITEM_KEY
																FROM COI_DISCLOSURE C1
																	INNER JOIN COI_DISCL_PROJECTS C2 ON C2.DISCLOSURE_ID=C1.DISCLOSURE_ID
																	INNER JOIN COI_PROJECT_AWARD_V C3 ON C3.AWARD_NUMBER = C2.MODULE_ITEM_KEY
																WHERE MODULE_CODE = 1 AND PERSON_ID = ''', AV_PERSON_ID, ''' 
																AND (C3.NEW_DISCLOSURE_REQUIRED IS NULL OR C3.NEW_DISCLOSURE_REQUIRED = ''N'') AND C3.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED''
																AND (C3.DISCLOSURE_VALIDATION_FLAG IS NULL OR C3.DISCLOSURE_VALIDATION_FLAG = ''HIERARCHY'') 
															) AND NOT EXISTS (SELECT 1 
																	FROM COI_DISCLOSURE CD1
																	INNER JOIN COI_DISCL_PROJECTS CD2 ON CD2.DISCLOSURE_ID = CD1.DISCLOSURE_ID
																	WHERE DISPOSITION_STATUS_CODE = 1 AND REVIEW_STATUS_CODE =1 AND PERSON_ID = ''', AV_PERSON_ID, ''' AND PROJECT_NUMBER = CD2.MODULE_ITEM_KEY
																)
                                                            AND ((DISCLOSURE_VALIDATION_FLAG = ''SELF'' AND NEW_DISCLOSURE_REQUIRED = ''Y'')
												OR (DISCLOSURE_REQUIRED_FLAG = ''REQUIRED'' AND (DISCLOSURE_VALIDATION_FLAG IS NULL OR DISCLOSURE_VALIDATION_FLAG = ''HIERARCHY'') 
												AND rn = 1 
												AND NOT EXISTS (
															   SELECT 1 
															   FROM Awards AR 
															   WHERE AR.DISCLOSURE_VALIDATION_FLAG = ''SELF''
															   AND SUBSTRING_INDEX(AR.PROJECT_NUMBER, ''-'', 1) = SUBSTRING_INDEX(Awards.PROJECT_NUMBER, ''-'', 1)
												))) ',SEARCH_CONDITION,') T ORDER BY T.UPDATE_TIMESTAMP DESC ',LS_OFFSET_CONDITION
						);

    -- Execute dynamic SQL
    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
END