


CREATE PROCEDURE `GET_COI_DISCL_GENERAL_DETAILS`(
	AV_COLUMN_NAMES           	VARCHAR(4000),
    AV_MODULE_ITEM_KEY         	INT,
	AV_SUB_MODULE_ITEM_KEY      INT
)
BEGIN

DECLARE LS_DYN_SQL 					LONGTEXT;
DECLARE LS_DYN_JOINS				LONGTEXT;
DECLARE LS_DYN_CONDITIONS			LONGTEXT;
DECLARE LS_DYN_SELECT_COLUMNS		LONGTEXT;

SET LS_DYN_SQL = CONCAT('SELECT ', AV_COLUMN_NAMES, ' FROM
	(SELECT t1.DISCLOSURE_NUMBER, DATE_FORMAT(t1.EXPIRATION_DATE, ''%m-%d-%Y'') AS EXPIRATION_DATE,
	DATE_FORMAT(t1.CERTIFIED_AT, ''%m-%d-%Y %H:%i:%s'') AS CERTIFICATION_DATE,
	t4.DESCRIPTION AS REVIEW_STATUS,
	t3.UNIT_NAME AS DEPARTMENT_NAME,
	t1.HOME_UNIT AS DEPARTMENT_NUMBER,
	t2.FULL_NAME AS REPORTER_NAME,
	t5.DESCRIPTION AS DISCLOSURE_STATUS,
	t14.DESCRIPTION AS PROJECT_TYPE,
	t7.DESCRIPTION AS FCOI_TYPE,
	t8.FULL_NAME AS ADMINISTRATOR_NAME,
	t1.DISCLOSURE_ID AS DISCLOSURE_ID,
	COALESCE(t5.PROPOSAL_TITLE, t10.IP_TITLE, t6.AWARD_TITLE) AS PROJECT_TITLE,
	COALESCE(t5.PROPOSAL_ID, t10.IP_NUMBER, t6.AWARD_NUMBER) AS PROJECT_NUMBER,
	t15.FULL_NAME AS UPDATED_USER_FULL_NAME,
	t1.UPDATE_TIMESTAMP,
	DATE_FORMAT(T1.CREATE_TIMESTAMP, ''%m-%d-%Y'') AS CREATE_DATE,
	T16.DESCRIPTION AS DISPOSITION_STATUS
	FROM COI_DISCLOSURE t1
	INNER JOIN PERSON t2 ON t2.PERSON_ID=t1.PERSON_ID
	INNER JOIN UNIT t3 ON t3.UNIT_NUMBER = t1.HOME_UNIT
	INNER JOIN COI_REVIEW_STATUS_TYPE t4 ON t4.REVIEW_STATUS_CODE = t1.REVIEW_STATUS_CODE
	LEFT JOIN COI_CONFLICT_STATUS_TYPE t5 ON t5.CONFLICT_STATUS_CODE=t1.CONFLICT_STATUS_CODE
	INNER JOIN COI_DISCLOSURE_FCOI_TYPE t7 ON t7.FCOI_TYPE_CODE = t1.FCOI_TYPE_CODE
	LEFT JOIN PERSON t8 ON t8.PERSON_ID = t1.ADMIN_PERSON_ID
	LEFT JOIN COI_DISCL_PROJECTS t9 ON t9.DISCLOSURE_ID = t1.DISCLOSURE_ID AND t1.FCOI_TYPE_CODE = 2
	LEFT JOIN (SELECT EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID,
		TITLE  AS PROPOSAL_TITLE, EXTERNAL_SYSTEM_REF_ID FROM COI_PROJECT_PROPOSAL_V ) t5 ON t5.PROPOSAL_ID = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 3
	LEFT  JOIN (SELECT AWARD_NUMBER, EXTERNAL_SYSTEM_REF_ID,
		TITLE AS AWARD_TITLE FROM COI_PROJECT_AWARD_V ) t6  ON t6.AWARD_NUMBER = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 1
	LEFT  JOIN (SELECT PROPOSAL_NUMBER AS IP_NUMBER , EXTERNAL_SYSTEM_REF_ID,
		TITLE AS IP_TITLE FROM COI_PROJECT_INSTITUTE_PROPOSAL_V ) t10 ON t10.IP_NUMBER = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 2
	LEFT JOIN COI_PROJECT_TYPE t14 ON t14.COI_PROJECT_TYPE_CODE = t1.COI_PROJECT_TYPE_CODE
	LEFT JOIN PERSON t15 ON t15.PERSON_ID = t1.UPDATED_BY
	INNER JOIN COI_DISPOSITION_STATUS_TYPE T16 ON T16.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
	WHERE t1.DISCLOSURE_ID = ', AV_MODULE_ITEM_KEY, ' ) T');

    SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
END