


CREATE PROCEDURE `GET_ENTITY_TAB_STATUS`(
AV_ENTITY_ID                        INT(10)
)
BEGIN

DECLARE LI_SAO_COUNT 					INT(11);
DECLARE LI_ESI_COUNT 					INT(11);
DECLARE LI_E_COUNT 						INT(11);
DECLARE LS_ESOI_FEED_STATUS				VARCHAR(500);
DECLARE LS_ESI_FEED_STATUS				VARCHAR(500);
DECLARE LS_ESOI_FEED_STATUS_CODE		INT(11);
DECLARE LS_ESI_FEED_STATUS_CODE			INT(11);
DECLARE LS_ESOI_ORG_ID					VARCHAR(10);
DECLARE LS_ESI_SPONSOR_CODE				VARCHAR(10);
DECLARE LI_SPONSOR_ADDRESS_COUNT        INT(11);
DECLARE LI_ORG_ADDRESS_COUNT            INT(11);


SELECT COUNT(*) INTO LI_SAO_COUNT
FROM entity_risk ER
INNER JOIN entity_risk_type ERT ON ER.RISK_TYPE_CODE = ERT.RISK_TYPE_CODE
WHERE ER.ENTITY_ID = AV_ENTITY_ID AND ERT.RISK_CATEGORY_CODE = 'OR';

IF LI_SAO_COUNT > 0 THEN
	SET LI_SAO_COUNT = 0;
	SELECT COUNT(*) INTO LI_SAO_COUNT
	FROM entity_sub_org_info ESOI
	WHERE ESOI.ENTITY_ID = AV_ENTITY_ID AND ESOI.ORGANIZATION_TYPE_CODE IS NOT NULL;
ELSE 
	SET LI_SAO_COUNT = 0;
END IF;

SELECT COUNT(*) INTO LI_ESI_COUNT 
FROM entity_sponsor_info ESI 
where ESI.ENTITY_ID = AV_ENTITY_ID AND ESI.SPONSOR_TYPE_CODE IS NOT NULL;

SELECT COUNT(*) INTO LI_E_COUNT
FROM entity e 
where e.ENTITY_ID = AV_ENTITY_ID AND e.PRIMARY_NAME IS NOT NULL
AND e.ENTITY_OWNERSHIP_TYPE_CODE IS NOT NULL AND e.PRIMARY_ADDRESS_LINE_1 IS NOT NULL 
AND e.CITY IS NOT NULL AND e.STATE IS NOT NULL AND e.POST_CODE IS NOT NULL AND e.COUNTRY_CODE IS NOT NULL;

SELECT EFST.DESCRIPTION, EFST.FEED_STATUS_CODE, ESI.SPONSOR_CODE  INTO LS_ESI_FEED_STATUS, LS_ESI_FEED_STATUS_CODE, LS_ESI_SPONSOR_CODE 
FROM entity_sponsor_info ESI 
INNER JOIN entity_feed_status_type EFST ON ESI.FEED_STATUS_CODE = EFST.FEED_STATUS_CODE
WHERE ESI.ENTITY_ID = AV_ENTITY_ID;

SELECT EFST.DESCRIPTION, EFST.FEED_STATUS_CODE, ESOI.ORGANIZATION_ID INTO LS_ESOI_FEED_STATUS, LS_ESOI_FEED_STATUS_CODE, LS_ESOI_ORG_ID 
FROM entity_sub_org_info ESOI
INNER JOIN entity_feed_status_type EFST ON ESOI.FEED_STATUS_CODE = EFST.FEED_STATUS_CODE
WHERE ESOI.ENTITY_ID = AV_ENTITY_ID;

SELECT COUNT(*) INTO LI_SPONSOR_ADDRESS_COUNT
	FROM ENTITY_MAILING_ADDRESS EMA
	WHERE EMA.ENTITY_ID = AV_ENTITY_ID
	AND EMA.ADDRESS_TYPE_CODE = '3';

SELECT COUNT(*) INTO LI_ORG_ADDRESS_COUNT
	FROM ENTITY_MAILING_ADDRESS EMA
	WHERE EMA.ENTITY_ID = AV_ENTITY_ID
	AND EMA.ADDRESS_TYPE_CODE = '4';

SELECT 
    CASE 
        WHEN LI_SAO_COUNT > 0 AND LI_ORG_ADDRESS_COUNT > 0 THEN TRUE
        ELSE FALSE
    END AS entity_sub_org_info,
    CASE 
        WHEN LI_ESI_COUNT > 0 AND LI_SPONSOR_ADDRESS_COUNT > 0 THEN TRUE
        ELSE FALSE
    END AS entity_sponsor_info,
    CASE 
        WHEN LI_E_COUNT > 0 THEN TRUE
        ELSE FALSE 
    END AS entity_overview,
    LS_ESOI_FEED_STATUS as organization_feed_status,
    LS_ESOI_FEED_STATUS_CODE as organization_feed_status_code,
    LS_ESI_FEED_STATUS as sponsor_feed_status,
    LS_ESI_FEED_STATUS_CODE as sponsor_feed_status_code,
    LS_ESOI_ORG_ID as organization_id,
    LS_ESI_SPONSOR_CODE as sponsor_code
FROM DUAL;

END