

CREATE PROCEDURE `UPD_DOCS_WITH_ORG_ENTITY`(
AV_DUPLICATE_ENTITY_ID                        INT(10),
AV_ORIGINAL_ENTITY_ID                         INT(10)
)
BEGIN

DECLARE LI_ORG_ENTITY_NUMBER 		INT;

SELECT ENTITY_NUMBER INTO LI_ORG_ENTITY_NUMBER FROM ENTITY WHERE ENTITY_ID = AV_DUPLICATE_ENTITY_ID;

SET SQL_SAFE_UPDATES = 0;

UPDATE PERSON_ENTITY set ENTITY_ID = AV_ORIGINAL_ENTITY_ID, ENTITY_NUMBER = LI_ORG_ENTITY_NUMBER where ENTITY_ID = AV_DUPLICATE_ENTITY_ID;
UPDATE COI_DISCL_PROJECT_ENTITY_REL set ENTITY_ID = AV_ORIGINAL_ENTITY_ID where ENTITY_ID = AV_DUPLICATE_ENTITY_ID;
UPDATE coi_travel_disclosure set ENTITY_ID = AV_ORIGINAL_ENTITY_ID, ENTITY_NUMBER = LI_ORG_ENTITY_NUMBER  where ENTITY_ID = AV_DUPLICATE_ENTITY_ID;
UPDATE OPA_DISCL_PERSON_ENTITY set ENTITY_ID = AV_ORIGINAL_ENTITY_ID, ENTITY_NUMBER = LI_ORG_ENTITY_NUMBER  where ENTITY_ID = AV_DUPLICATE_ENTITY_ID;

SET SQL_SAFE_UPDATES = 1;
END
