
DROP TABLE IF EXISTS `grant_call_eligible_department`;

CREATE TABLE `grant_call_eligible_department` (
  `ELIGIBILE_DEPT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UNIT_NAME` varchar(255) DEFAULT NULL,
  `UNIT_NUMBER` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `GRANT_HEADER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ELIGIBILE_DEPT_ID`),
  KEY `GRANT_CALL_ELIGIBLE_DEPT_FK1` (`GRANT_HEADER_ID`),
  CONSTRAINT `GRANT_CALL_ELIGIBLE_DEPT_FK1` FOREIGN KEY (`GRANT_HEADER_ID`) REFERENCES `grant_call_header` (`GRANT_HEADER_ID`)
) ;