
DROP TABLE IF EXISTS `grant_call_research_areas`;

CREATE TABLE `grant_call_research_areas` (
  `GRANT_RESEARCH_AREAS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRANT_HEADER_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `RESRCH_TYPE_AREA_CODE` varchar(255) DEFAULT NULL,
  `RESRCH_TYPE_CODE` varchar(255) DEFAULT NULL,
  `RESRCH_TYPE_SUB_AREA_CODE` varchar(255) DEFAULT NULL,
  `CHALLENGE_AREA_CODE` varchar(255) DEFAULT NULL,
  `RESEARCH_AREA_CODE` varchar(255) DEFAULT NULL,
  `RESEARCH_SUB_AREA_CODE` varchar(255) DEFAULT NULL,
  `RESEARCH_TYPE_CODE` int(11) DEFAULT NULL,
  `CHALLENGE_SUBAREA_CODE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GRANT_RESEARCH_AREAS_ID`),
  KEY `GRANT_CALL_RSRCH_AREA_FK1` (`GRANT_HEADER_ID`),
  KEY `GRANT_CALL_RSRCH_AREA_FK2` (`RESRCH_TYPE_CODE`),
  KEY `GRANT_CALL_RSRCH_AREA_FK3` (`RESRCH_TYPE_AREA_CODE`),
  KEY `GRANT_CALL_RSRCH_AREA_FK4` (`RESRCH_TYPE_SUB_AREA_CODE`),
  KEY `GRANT_CALL_RSRCH_AREA_FK5` (`CHALLENGE_AREA_CODE`),
  KEY `GRANT_CALL_RSRCH_AREA_FK6` (`CHALLENGE_SUBAREA_CODE`),
  CONSTRAINT `GRANT_CALL_RSRCH_AREA_FK1` FOREIGN KEY (`GRANT_HEADER_ID`) REFERENCES `grant_call_header` (`GRANT_HEADER_ID`),
  CONSTRAINT `GRANT_CALL_RSRCH_AREA_FK2` FOREIGN KEY (`RESRCH_TYPE_CODE`) REFERENCES `research_type` (`RESRCH_TYPE_CODE`),
  CONSTRAINT `GRANT_CALL_RSRCH_AREA_FK3` FOREIGN KEY (`RESRCH_TYPE_AREA_CODE`) REFERENCES `research_type_area` (`RESRCH_TYPE_AREA_CODE`),
  CONSTRAINT `GRANT_CALL_RSRCH_AREA_FK4` FOREIGN KEY (`RESRCH_TYPE_SUB_AREA_CODE`) REFERENCES `research_type_sub_area` (`RESRCH_TYPE_SUB_AREA_CODE`),
  CONSTRAINT `GRANT_CALL_RSRCH_AREA_FK5` FOREIGN KEY (`CHALLENGE_AREA_CODE`) REFERENCES `societal_challenge_area` (`CHALLENGE_AREA_CODE`),
  CONSTRAINT `GRANT_CALL_RSRCH_AREA_FK6` FOREIGN KEY (`CHALLENGE_SUBAREA_CODE`) REFERENCES `societal_challenge_subarea` (`CHALLENGE_SUBAREA_CODE`)
) ;