
DROP TABLE IF EXISTS `grant_call_kpi`;

CREATE TABLE `grant_call_kpi` (
  `GRANT_CALL_KPI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRANT_HEADER_ID` int(11) DEFAULT NULL,
  `KPI_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`GRANT_CALL_KPI_ID`),
  KEY `GRANT_CALL_KPI_FK` (`GRANT_HEADER_ID`),
  KEY `GRANT_CALL_KPI_FK2` (`KPI_TYPE_CODE`),
  CONSTRAINT `GRANT_CALL_KPI_FK` FOREIGN KEY (`GRANT_HEADER_ID`) REFERENCES `grant_call_header` (`GRANT_HEADER_ID`),
  CONSTRAINT `GRANT_CALL_KPI_FK2` FOREIGN KEY (`KPI_TYPE_CODE`) REFERENCES `kpi_type` (`KPI_TYPE_CODE`)
) ;