DROP TABLE IF EXISTS `grant_call_elgiblity_type`;

CREATE TABLE `grant_call_elgiblity_type` (
  `GRANT_ELGBLTY_TYPE_CODE` int(11) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `HAS_TARGET` varchar(255) DEFAULT NULL,
  `MORE_INFORMATION` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`GRANT_ELGBLTY_TYPE_CODE`)
) ;
