
DROP TABLE IF EXISTS `grant_call_kpi_criteria`;

CREATE TABLE `grant_call_kpi_criteria` (
  `GRANT_CALL_KPI_CRITERIA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRANT_CALL_KPI_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `KPI_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`GRANT_CALL_KPI_CRITERIA_ID`),
  KEY `GRANT_CALL_KPI_CRITERIA_FK1` (`GRANT_CALL_KPI_ID`),
  KEY `GRANT_CALL_KPI_CRITERIA_FK2` (`KPI_CRITERIA_TYPE_CODE`),
  CONSTRAINT `GRANT_CALL_KPI_CRITERIA_FK1` FOREIGN KEY (`GRANT_CALL_KPI_ID`) REFERENCES `grant_call_kpi` (`GRANT_CALL_KPI_ID`),
  CONSTRAINT `GRANT_CALL_KPI_CRITERIA_FK2` FOREIGN KEY (`KPI_CRITERIA_TYPE_CODE`) REFERENCES `kpi_criteria_type` (`KPI_CRITERIA_TYPE_CODE`)
) ;
