
DROP TABLE IF EXISTS `grant_call_type`;

CREATE TABLE `grant_call_type` (
  `GRANT_TYPE_CODE` int(11) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `GRANT_CALL_CATEGORY_CODE` int(11) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`GRANT_TYPE_CODE`),
  KEY `GRANT_CALL_TYPE_FK1` (`GRANT_CALL_CATEGORY_CODE`),
  CONSTRAINT `GRANT_CALL_TYPE_FK1` FOREIGN KEY (`GRANT_CALL_CATEGORY_CODE`) REFERENCES `grant_call_category` (`GRANT_CALL_CATEGORY_CODE`)
) ;