
DROP TABLE IF EXISTS `grant_eligibility_target`;

CREATE TABLE `grant_eligibility_target` (
  `GRANT_ELIGIBILITY_TARGET_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRANT_ELIGIBILITY_ID` int(11) DEFAULT NULL,
  `ELIGIBILITY_TARGET_TYPE_CODE` varchar(3) DEFAULT NULL,
  `TARGET_CATEGORY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `TARGET_VALUE` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`GRANT_ELIGIBILITY_TARGET_ID`),
  KEY `GRANT_ELIGIBILITY_TARGET_FK` (`GRANT_ELIGIBILITY_ID`),
  KEY `GRANT_ELIGIBILITY_TARGET_FK2` (`ELIGIBILITY_TARGET_TYPE_CODE`),
  CONSTRAINT `GRANT_ELIGIBILITY_TARGET_FK` FOREIGN KEY (`GRANT_ELIGIBILITY_ID`) REFERENCES `grant_call_eligibility` (`GRANT_ELIGIBILITY_ID`),
  CONSTRAINT `GRANT_ELIGIBILITY_TARGET_FK2` FOREIGN KEY (`ELIGIBILITY_TARGET_TYPE_CODE`) REFERENCES `grant_eligibility_target_type` (`ELIGIBILITY_TARGET_TYPE_CODE`)
) ;