
DROP TABLE IF EXISTS `grant_call_ioi_header`;

CREATE TABLE `grant_call_ioi_header` (
  `IOI_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GRANT_HEADER_ID` int(11) DEFAULT NULL,
  `PROJECT_TITLE` varchar(1000) DEFAULT NULL,
  `REQUESTED_DIRECT_COST` decimal(14,2) DEFAULT NULL,
  `UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `PI_PERSON_ID` varchar(40) DEFAULT NULL,
  `SUBMITING_UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `STATUS_CODE` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_ANSWER_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`IOI_ID`),
  KEY `GRANT_CALL_IOI_HEADER_FK` (`GRANT_HEADER_ID`),
  KEY `GRANT_CALL_IOI_HEADER_FK3` (`UNIT_NUMBER`),
  KEY `GRANT_CALL_IOI_HEADER_FK4` (`PI_PERSON_ID`),
  KEY `GRANT_CALL_IOI_HEADER_FK2` (`STATUS_CODE`),
  KEY `GRANT_CALL_IOI_HEADER_FK5` (`SUBMITING_UNIT_NUMBER`),
  CONSTRAINT `GRANT_CALL_IOI_HEADER_FK` FOREIGN KEY (`GRANT_HEADER_ID`) REFERENCES `grant_call_header` (`GRANT_HEADER_ID`),
  CONSTRAINT `GRANT_CALL_IOI_HEADER_FK2` FOREIGN KEY (`STATUS_CODE`) REFERENCES `ioi_status` (`STATUS_CODE`),
  CONSTRAINT `GRANT_CALL_IOI_HEADER_FK3` FOREIGN KEY (`UNIT_NUMBER`) REFERENCES `unit` (`UNIT_NUMBER`),
  CONSTRAINT `GRANT_CALL_IOI_HEADER_FK4` FOREIGN KEY (`PI_PERSON_ID`) REFERENCES `person` (`PERSON_ID`),
  CONSTRAINT `GRANT_CALL_IOI_HEADER_FK5` FOREIGN KEY (`SUBMITING_UNIT_NUMBER`) REFERENCES `unit` (`UNIT_NUMBER`)
) ;