DELIMITER $$
CREATE FUNCTION `FN_AWD_MANPOWER_COST_ALLOCATN`(
AV_PERSON_ID VARCHAR(40),
AV_COST_ALLOCATION DECIMAL(5,2),
AV_START_DATE DATETIME,
AV_END_DATE DATETIME,
AV_AWARD_NUMBER VARCHAR(20),
AV_UPGRADE_TYPE_CODE VARCHAR(1)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LS_COST_ALLOCATION DECIMAL(5,2);
DECLARE LS_COST_ALLOCATION_TOTAL DECIMAL(5,2);
DECLARE LI_PERSON_COUNT INT;
DECLARE LI_POSITION_ACTIVE_IN_DURATION_COUNT INT;
DECLARE LI_PERSON_EXISTS_IN_AWARD_COUNT INT;
SET LI_PERSON_COUNT = 0;
SET LS_COST_ALLOCATION = 0;
SET LS_COST_ALLOCATION_TOTAL = 0;
SET LI_POSITION_ACTIVE_IN_DURATION_COUNT = 0;
SET LI_PERSON_EXISTS_IN_AWARD_COUNT = 0;
IF AV_UPGRADE_TYPE_CODE <> 3 THEN
	SELECT COUNT(PERSON_ID) INTO LI_PERSON_EXISTS_IN_AWARD_COUNT FROM AWARD_MANPOWER_RESOURCE
	WHERE PERSON_ID = AV_PERSON_ID AND POSITION_OWNED_BY_AWARD = 'Y' AND AWARD_NUMBER = AV_AWARD_NUMBER;
	IF LI_PERSON_EXISTS_IN_AWARD_COUNT = 0 THEN
		SELECT COUNT(AWARD_ID) INTO LI_POSITION_ACTIVE_IN_DURATION_COUNT FROM AWARD WHERE AWARD_ID in (
		SELECT AWARD_ID FROM AWARD_MANPOWER WHERE AWARD_MANPOWER_ID IN(
		SELECT AWARD_MANPOWER_ID FROM AWARD_MANPOWER_RESOURCE WHERE PERSON_ID = AV_PERSON_ID AND POSITION_OWNED_BY_AWARD = 'Y'
		AND POSITION_STATUS_CODE NOT IN (5, 8)))
		AND AWARD_SEQUENCE_STATUS = 'ACTIVE' AND FINAL_EXPIRATION_DATE < AV_END_DATE;
	END IF;
END IF;
	IF LI_POSITION_ACTIVE_IN_DURATION_COUNT = 0 THEN
		SELECT COUNT(PERSON_ID) INTO LI_PERSON_COUNT FROM AWARD_MANPOWER_RESOURCE T1
		INNER JOIN AWARD_MANPOWER T2 ON T2.AWARD_MANPOWER_ID = T1.AWARD_MANPOWER_ID
		INNER JOIN AWARD T3 ON T3.AWARD_ID = T2.AWARD_ID
		WHERE T3.AWARD_ID IN (SELECT AWARD_ID FROM AWARD WHERE (AWARD_NUMBER,SEQUENCE_NUMBER) IN
		(SELECT AWARD_NUMBER,MAX(SEQUENCE_NUMBER) FROM AWARD WHERE AWARD_NUMBER in (
		SELECT AWARD_NUMBER FROM AWARD_MANPOWER WHERE AWARD_NUMBER <> AV_AWARD_NUMBER
		) AND ((AWARD_SEQUENCE_STATUS = 'PENDING' AND (AWARD_DOCUMENT_TYPE_CODE = '1' OR AWARD_VARIATION_TYPE_CODE IN ('19','20','9','18'))) OR
        AWARD_SEQUENCE_STATUS = 'ACTIVE') group by award_number))
		AND T1.PERSON_ID = AV_PERSON_ID AND T1.POSITION_STATUS_CODE NOT IN (5, 8)
		AND (
		CASE
		WHEN T1.CHARGE_START_DATE IS NOT NULL AND T1.CHARGE_END_DATE IS NOT NULL
			THEN (AV_START_DATE BETWEEN T1.CHARGE_START_DATE AND T1.CHARGE_END_DATE)
				OR (AV_END_DATE BETWEEN T1.CHARGE_START_DATE AND T1.CHARGE_END_DATE)
				OR (T1.CHARGE_START_DATE BETWEEN AV_START_DATE AND AV_END_DATE )
				OR (T1.CHARGE_END_DATE BETWEEN AV_START_DATE AND AV_END_DATE)
		ELSE
			(AV_START_DATE BETWEEN T1.PLAN_START_DATE AND T1.PLAN_END_DATE)
			OR (AV_END_DATE BETWEEN T1.PLAN_START_DATE AND T1.PLAN_END_DATE)
			OR (T1.PLAN_START_DATE BETWEEN AV_START_DATE AND AV_END_DATE )
			OR (T1.PLAN_END_DATE BETWEEN AV_START_DATE AND AV_END_DATE)
		END
		);
			IF LI_PERSON_COUNT > 0 THEN
				SELECT SUM(COST_ALLOCATION) INTO LS_COST_ALLOCATION FROM AWARD_MANPOWER_RESOURCE T1
		INNER JOIN AWARD_MANPOWER T2 ON T2.AWARD_MANPOWER_ID = T1.AWARD_MANPOWER_ID
		INNER JOIN AWARD T3 ON T3.AWARD_ID = T2.AWARD_ID
		WHERE T3.AWARD_ID IN (SELECT AWARD_ID FROM AWARD WHERE (AWARD_NUMBER,SEQUENCE_NUMBER) IN
		(SELECT AWARD_NUMBER,MAX(SEQUENCE_NUMBER) FROM AWARD WHERE AWARD_NUMBER in (
		SELECT AWARD_NUMBER FROM AWARD_MANPOWER WHERE AWARD_NUMBER <> AV_AWARD_NUMBER
		) AND ((AWARD_SEQUENCE_STATUS = 'PENDING' AND (AWARD_DOCUMENT_TYPE_CODE = '1' OR AWARD_VARIATION_TYPE_CODE IN ('19','20','9','18'))) OR
        AWARD_SEQUENCE_STATUS = 'ACTIVE') group by award_number))
		AND T1.PERSON_ID = AV_PERSON_ID AND T1.POSITION_STATUS_CODE NOT IN (5, 8)
		AND (
		CASE
		WHEN T1.CHARGE_START_DATE IS NOT NULL AND T1.CHARGE_END_DATE IS NOT NULL
			THEN (AV_START_DATE BETWEEN T1.CHARGE_START_DATE AND T1.CHARGE_END_DATE)
				OR (AV_END_DATE BETWEEN T1.CHARGE_START_DATE AND T1.CHARGE_END_DATE)
				OR (T1.CHARGE_START_DATE BETWEEN AV_START_DATE AND AV_END_DATE )
				OR (T1.CHARGE_END_DATE BETWEEN AV_START_DATE AND AV_END_DATE)
		ELSE
			(AV_START_DATE BETWEEN T1.PLAN_START_DATE AND T1.PLAN_END_DATE)
			OR (AV_END_DATE BETWEEN T1.PLAN_START_DATE AND T1.PLAN_END_DATE)
			OR (T1.PLAN_START_DATE BETWEEN AV_START_DATE AND AV_END_DATE )
			OR (T1.PLAN_END_DATE BETWEEN AV_START_DATE AND AV_END_DATE)
		END
		);
			ELSE
				IF AV_COST_ALLOCATION <= 100 THEN
				RETURN 'Y';
				END IF;
			END IF;
		SET LS_COST_ALLOCATION_TOTAL = IFNULL(LS_COST_ALLOCATION,0) + IFNULL(AV_COST_ALLOCATION,0);
			IF LS_COST_ALLOCATION_TOTAL <= 100 THEN
				RETURN 'Y';
			ELSE
				RETURN 'N';
			END IF;
	ELSE
		RETURN 'P';
	END IF;
END
$$
DELIMITER ;
