DELIMITER $$
CREATE  FUNCTION `FN_CHK_TIMESHEET_MANDATORY`(
AV_AWARD_ID    varchar(6)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_COLUMN_ID INT;
DECLARE LI_VALUE VARCHAR(200);
	SELECT DISTINCT COLUMN_ID INTO LI_COLUMN_ID FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Key Person Timesheet';
	SELECT VALUE INTO LI_VALUE FROM CUSTOM_DATA WHERE
	COLUMN_VERSION_NUMBER = (
		SELECT MAX(COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA
		WHERE COLUMN_ID = LI_COLUMN_ID AND MODULE_ITEM_CODE=1 AND  MODULE_SUB_ITEM_CODE = 0 AND
		MODULE_ITEM_KEY =AV_AWARD_ID AND MODULE_SUB_ITEM_KEY = '0')
	AND COLUMN_ID = LI_COLUMN_ID AND MODULE_ITEM_CODE=1 AND  MODULE_SUB_ITEM_CODE = 0 AND
	MODULE_ITEM_KEY =AV_AWARD_ID AND MODULE_SUB_ITEM_KEY = '0';
    IF LI_VALUE = 'Yes' THEN
		RETURN 'TRUE';
	ELSE
		RETURN 'FALSE';
    END IF;
END
$$
DELIMITER ;
