DELIMITER $$
CREATE DEFINER=`ku_rms_user`@`%` FUNCTION `FN_CHK_GRANTCALL_ELIG_TARGET`(
AV_PROPOSAL_ID    VARCHAR(20)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
	DECLARE LI_FLAG INT;
	DECLARE LI_GRANT_HEADER_ID int(10);
	DECLARE LS_PERSON_ID VARCHAR(40);
	DECLARE LS_DIRECTORY_TITLE varchar(50);
	DECLARE LI_PROP_PERSON_ROLE_ID INT;
	DECLARE LI_GRANT_ELGBLTY_TYPE_CODE INT;
	DECLARE LS_GRANT_CRITERIA VARCHAR(40);
	DECLARE LS_CRITERIA_MET_FLAG  INT;
	DECLARE LS_GRANT_ELIGIBILITY_TARGET_ID INT(10);
	DECLARE LS_GRANT_ELIGIB_TARGET_ID INT(10);
	DECLARE LS_TARGET_VALUE	VARCHAR(50);
	DECLARE LS_HOME_UNIT  VARCHAR(50);
	DECLARE LS_UNIT_NAME VARCHAR(200);
	DECLARE LS_GRANT_ELIGIBILITY_ID INT(10);
    DECLARE LS_DESCRIPTION VARCHAR(40);
    set SQL_SAFE_UPDATES = 0;
	SELECT GRANT_HEADER_ID INTO LI_GRANT_HEADER_ID FROM EPS_PROPOSAL
	WHERE PROPOSAL_ID = AV_PROPOSAL_ID;
	IF LI_GRANT_HEADER_ID IS NULL THEN
		RETURN 'TRUE';
	END IF;
	SELECT COUNT(1) INTO LI_FLAG FROM GRANT_CALL_ELIGIBILITY
	WHERE GRANT_HEADER_ID = LI_GRANT_HEADER_ID;
	IF LI_FLAG = 0 THEN
		RETURN 'TRUE';
	END IF;
	IF LI_FLAG > 0 THEN
		BEGIN
			DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE ELGBLTY_CUR CURSOR FOR
			SELECT PROP_PERSON_ROLE_ID,GRANT_ELGBLTY_TYPE_CODE,GRANT_ELIGIBILITY_ID
            FROM GRANT_CALL_ELIGIBILITY
			WHERE GRANT_HEADER_ID = LI_GRANT_HEADER_ID
            AND PROP_PERSON_ROLE_ID IN(1,6);
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN ELGBLTY_CUR;
			ELGBLTY_CUR_LOOP : LOOP
			FETCH ELGBLTY_CUR
			INTO LI_PROP_PERSON_ROLE_ID,LI_GRANT_ELGBLTY_TYPE_CODE,LS_GRANT_ELIGIBILITY_ID;
			    SET LS_CRITERIA_MET_FLAG = 0;
				IF DONE1 THEN
						LEAVE ELGBLTY_CUR_LOOP;
				END IF;
				BEGIN
						DECLARE DONE2 INT DEFAULT FALSE;
						DECLARE EPS_PER_CUR CURSOR FOR
						SELECT PERSON_ID from EPS_PROPOSAL_PERSONS
						WHERE PROPOSAL_ID = AV_PROPOSAL_ID
						AND PROP_PERSON_ROLE_ID = LI_PROP_PERSON_ROLE_ID;
						DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
						OPEN EPS_PER_CUR;
						EPS_PER_CUR_LOOP : LOOP
						FETCH EPS_PER_CUR
						INTO LS_PERSON_ID;
						IF DONE2 THEN
								LEAVE EPS_PER_CUR_LOOP;
						END IF;
							SET LS_CRITERIA_MET_FLAG = 0;
							SELECT DIRECTORY_TITLE,HOME_UNIT INTO LS_DIRECTORY_TITLE,LS_HOME_UNIT
							FROM PERSON WHERE PERSON_ID = LS_PERSON_ID;
							IF LI_GRANT_ELGBLTY_TYPE_CODE = 5 THEN
								SET LS_GRANT_CRITERIA = 'Faculty';
							ELSE
								SELECT DESCRIPTION INTO LS_GRANT_CRITERIA
                                FROM GRANT_CALL_ELGIBLITY_TYPE
								WHERE GRANT_ELGBLTY_TYPE_CODE = LI_GRANT_ELGBLTY_TYPE_CODE;
							END IF;
							IF LS_DIRECTORY_TITLE = LS_GRANT_CRITERIA THEN
								SELECT GRANT_ELIGIBILITY_TARGET_ID INTO LS_GRANT_ELIGIBILITY_TARGET_ID
								FROM GRANT_CALL_ELIGIBILITY T1 INNER JOIN GRANT_ELIGIBILITY_TARGET T2
								ON T1.GRANT_ELIGIBILITY_ID = T2.GRANT_ELIGIBILITY_ID
								WHERE T1.GRANT_ELIGIBILITY_ID = LS_GRANT_ELIGIBILITY_ID;
								IF LS_GRANT_ELIGIBILITY_TARGET_ID IS  NULL THEN
									SET LS_CRITERIA_MET_FLAG = 1;
                                ELSE
									SELECT ELIGIBILITY_TARGET_TYPE_CODE,TARGET_VALUE INTO LS_GRANT_ELIGIB_TARGET_ID,LS_TARGET_VALUE
									FROM GRANT_ELIGIBILITY_TARGET
									where GRANT_ELIGIBILITY_TARGET_ID = LS_GRANT_ELIGIBILITY_TARGET_ID;
									IF LS_GRANT_ELIGIB_TARGET_ID = 3 THEN
										IF LS_PERSON_ID = LS_TARGET_VALUE THEN
											SET LS_CRITERIA_MET_FLAG = 1;
										END IF;
									ELSEIF LS_GRANT_ELIGIB_TARGET_ID = 2 THEN
										IF LS_HOME_UNIT = LS_TARGET_VALUE THEN
											SET LS_CRITERIA_MET_FLAG = 1;
										END IF;
									ELSE
										SET LS_CRITERIA_MET_FLAG = 1;
									END IF;
								END IF;
							END IF;
						END LOOP;
						CLOSE EPS_PER_CUR;
			END ;
			IF LS_CRITERIA_MET_FLAG = 0 THEN
				UPDATE EPS_PROPOSAL SET IS_ELIGIBLE_CRITERIA_MET = 'N'
                WHERE PROPOSAL_ID = AV_PROPOSAL_ID;
				RETURN 'FALSE';
			END IF;
			END LOOP;
			CLOSE ELGBLTY_CUR;
		END;
	END IF;
UPDATE EPS_PROPOSAL SET IS_ELIGIBLE_CRITERIA_MET = 'Y'
WHERE PROPOSAL_ID = AV_PROPOSAL_ID;
RETURN 'TRUE';
END
$$
DELIMITER ;
