DELIMITER $$
CREATE FUNCTION `FN_CHK_AWARD_BUDGET_DATE`(
AV_AWARD_ID DECIMAL(22,0)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LS_AWARD_START_DATE datetime;
DECLARE LS_AWARD_END_DATE datetime;
DECLARE LS_BUDGET_START_DATE datetime;
DECLARE LS_BUDGET_END_DATE datetime;
SELECT BEGIN_DATE, FINAL_EXPIRATION_DATE
INTO LS_AWARD_START_DATE, LS_AWARD_END_DATE
FROM AWARD
WHERE AWARD_ID = AV_AWARD_ID;
SELECT START_DATE, END_DATE
INTO LS_BUDGET_START_DATE, LS_BUDGET_END_DATE
FROM AWARD_BUDGET_HEADER T1
WHERE T1.AWARD_ID = AV_AWARD_ID
AND T1.SEQUENCE_NUMBER = (SELECT MAX(T2.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T2
WHERE T1.AWARD_ID = T2.AWARD_ID
);
IF LS_BUDGET_START_DATE >= LS_AWARD_START_DATE and LS_BUDGET_END_DATE <= LS_AWARD_END_DATE THEN
RETURN 'TRUE';
ELSE
RETURN 'FALSE';
END IF;
END
$$
DELIMITER ;
