DELIMITER $$
CREATE FUNCTION `FN_CHK_IS_PROP_BUDGET_CREATED`(
AV_PROPOSAL_ID    varchar(6)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_GRANT_CALL_COUNT INT;
DECLARE LI_BUDGET_COUNT INT;
SELECT COUNT(T1.GRANT_HEADER_ID) INTO LI_GRANT_CALL_COUNT
FROM EPS_PROPOSAL T1
WHERE T1.PROPOSAL_ID = AV_PROPOSAL_ID;
SELECT COUNT(T2.BUDGET_HEADER_ID) INTO LI_BUDGET_COUNT
	FROM BUDGET_HEADER T2
	WHERE T2.PROPOSAL_ID = AV_PROPOSAL_ID;
	IF LI_GRANT_CALL_COUNT > 0 AND LI_BUDGET_COUNT = 0  THEN
			RETURN 'FALSE';
	ELSEIF LI_GRANT_CALL_COUNT = 0 AND LI_BUDGET_COUNT = 0 THEN
			RETURN 'TRUE';
	END IF;
END
$$
DELIMITER ;
