DELIMITER $$
CREATE FUNCTION `FN_CHK_AWD_HAS_SUP_ORG`(
    AV_AWARD_ID DECIMAL(22)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE ls_value VARCHAR(4000);
DECLARE LI_COUNT INT;
SELECT  COUNT(AWARD_ID) INTO LI_COUNT
FROM award_manpower t1
INNER JOIN award_manpower_resource t2
ON t1.AWARD_MANPOWER_ID = t2.AWARD_MANPOWER_ID
WHERE t1.AWARD_ID = AV_AWARD_ID
AND t1.MANPOWER_TYPE_CODE = 1
AND ( t2.PERSON_ID <> '999999999100' OR t2.PERSON_ID IS NULL )
AND t2.position_status_code = 2;
IF LI_COUNT = 0 THEN
    RETURN 'TRUE';
END IF;
SELECT  COUNT(1) INTO LI_COUNT
FROM CUSTOM_DATA T1
WHERE T1.MODULE_ITEM_CODE = 1
AND T1.MODULE_SUB_ITEM_CODE = 0
AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
AND T1.MODULE_SUB_ITEM_KEY = 0
AND length(T1.VALUE ) > 0
AND T1.COLUMN_ID = (
SELECT  MAX(COLUMN_ID)
FROM CUSTOM_DATA_ELEMENTS
WHERE CUSTOM_ELEMENT_NAME = 'Level_2_Sup_Org') AND T1.COLUMN_VERSION_NUMBER = (
SELECT  MAX(T2.COLUMN_VERSION_NUMBER)
FROM CUSTOM_DATA T2
WHERE T2.COLUMN_ID = T1.COLUMN_ID
AND T2.MODULE_ITEM_CODE = 1
AND T2.MODULE_SUB_ITEM_CODE = 0
AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
AND T2.MODULE_SUB_ITEM_KEY = 0);
IF LI_COUNT > 0 THEN
    SELECT  T1.VALUE INTO ls_value
    FROM CUSTOM_DATA T1
    WHERE T1.MODULE_ITEM_CODE = 1
    AND T1.MODULE_SUB_ITEM_CODE = 0
    AND T1.MODULE_ITEM_KEY = AV_AWARD_ID
    AND T1.MODULE_SUB_ITEM_KEY = 0
    AND T1.COLUMN_ID = (
    SELECT  MAX(COLUMN_ID)
    FROM CUSTOM_DATA_ELEMENTS
    WHERE CUSTOM_ELEMENT_NAME = 'Level_2_Sup_Org') AND T1.COLUMN_VERSION_NUMBER = (
    SELECT  MAX(T2.COLUMN_VERSION_NUMBER)
    FROM CUSTOM_DATA T2
    WHERE T2.COLUMN_ID = T1.COLUMN_ID
    AND T2.MODULE_ITEM_CODE = 1
    AND T2.MODULE_SUB_ITEM_CODE = 0
    AND T2.MODULE_ITEM_KEY = AV_AWARD_ID
    AND T2.MODULE_SUB_ITEM_KEY = 0);
ELSE
    SELECT  LEAD_UNIT_NUMBER into ls_value
    FROM award
    WHERE AWARD_ID = AV_AWARD_ID;
END IF;
SELECT  COUNT(UNIT_NUMBER) INTO LI_COUNT
FROM sap_feed_unit_mapping
WHERE UNIT_NUMBER = ls_value
AND SUPERIOR_SUP_ORG is not null
AND length(SUPERIOR_SUP_ORG) > 0;
IF LI_COUNT = 0 THEN
    RETURN 'FALSE';
END IF;
RETURN 'TRUE';
END
$$
DELIMITER ;
