DELIMITER $$
CREATE FUNCTION `FN_COUNT_OF_DMP_UPDATE`(AV_AWARD_NUMBER  VARCHAR(22)
) RETURNS int
    DETERMINISTIC
BEGIN
	DECLARE LI_COUNT INT;
	SELECT
	count(T1.AWARD_NUMBER)+1 INTO LI_COUNT
	FROM AWARD T1
	LEFT OUTER JOIN  SR_HEADER T8 ON T8.MODULE_CODE = 1 and T8.MODULE_ITEM_KEY in (SELECT  max(award_id) from award where award_id < T1.AWARD_ID and award_number = T1.award_number)
	LEFT OUTER JOIN SR_TYPE T9 ON T9.TYPE_CODE = T8.TYPE_CODE
	WHERE T8.TYPE_CODE = 5
	AND T1.AWARD_NUMBER = AV_AWARD_NUMBER;
RETURN LI_COUNT;
END
$$
DELIMITER ;
