DELIMITER $$
CREATE FUNCTION `FN_CHK_AWARD_QNR_COMPLETE_NEW`(
AV_AWARD_ID    int(10)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
DECLARE LS_AWARD_TYPE_CODE VARCHAR(3);
DECLARE LI_QUESTIONNAIRE_ID INT;
SELECT COUNT(1) INTO LI_FLAG
FROM AWARD
WHERE AWARD_ID = AV_AWARD_ID
AND AWARD_TYPE_CODE IS NOT NULL;
IF LI_FLAG > 0 THEN
	SELECT AWARD_TYPE_CODE
	INTO LS_AWARD_TYPE_CODE
	FROM AWARD
	WHERE AWARD_ID = AV_AWARD_ID;
	IF LS_AWARD_TYPE_CODE IN (1,2,4) THEN
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_DATA CURSOR FOR
		SELECT QUESTIONNAIRE_ID FROM QUEST_USAGE
		WHERE MODULE_ITEM_CODE = 1
		AND MODULE_SUB_ITEM_CODE = 0
		AND IS_MANDATORY = 'Y';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_DATA INTO
		LI_QUESTIONNAIRE_ID;
		IF DONE1 THEN
		LEAVE INSERT_LOOP;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG FROM QUEST_ANSWER_HEADER
		WHERE MODULE_ITEM_CODE = 1
		AND MODULE_SUB_ITEM_CODE = 0
		AND MODULE_ITEM_KEY = AV_AWARD_ID
		AND QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID;
		IF LI_FLAG = 0 THEN
			RETURN 'FALSE';
		END IF;
		SELECT COUNT(1) INTO LI_FLAG FROM QUEST_ANSWER_HEADER
		WHERE MODULE_ITEM_CODE = 1
		AND MODULE_SUB_ITEM_CODE = 0
		AND MODULE_ITEM_KEY = AV_AWARD_ID
		AND QUESTIONNAIRE_COMPLETED_FLAG = 'N'
		AND QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID;
		IF LI_FLAG > 0 THEN
			RETURN 'FALSE';
		END IF;
		END LOOP;
		CLOSE CUR_DATA;
	END;
	ELSE
		RETURN 'TRUE';
	END IF;
ELSE
	RETURN 'TRUE';
END IF;
RETURN 'TRUE';
END
$$
DELIMITER ;
