DELIMITER $$
CREATE  FUNCTION `FN_FOR_ALL_NDA`(
AV_AGREEMENT_REQUEST_ID VARCHAR(12)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT(2);
	SELECT COUNT(1) INTO LI_FLAG FROM AGREEMENT_HEADER
	WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_REQUEST_ID
	AND AGREEMENT_TYPE_CODE = 1;
    IF LI_FLAG > 0 THEN
		RETURN 'TRUE';
    END IF;
    RETURN 'FALSE';
END
$$
DELIMITER ;
