DELIMITER $$
CREATE FUNCTION `FN_IS_FEDERAL_SPONSOR`(
AV_PROPOSAL_ID    INT(10)
) RETURNS varchar(20) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_CODE       VARCHAR(3);
DECLARE LI_ARG_CODE   VARCHAR(3);
SELECT T3.SPONSOR_TYPE_CODE
INTO    LI_CODE
FROM EPS_PROPOSAL T1 LEFT JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE
LEFT JOIN SPONSOR_TYPE T3 ON T3.SPONSOR_TYPE_CODE = T2.SPONSOR_TYPE_CODE
WHERE T1.PROPOSAL_ID = AV_PROPOSAL_ID;
IF (LI_CODE IN (3,5,10,13,15)) THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
END IF;
END
$$
DELIMITER ;
