DELIMITER $$
CREATE FUNCTION `FN_VALIADATE_GR_AMOUNT`(
AV_AWARD_ID    int(10)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
	DECLARE LI_COUNT INT(3);
	SELECT count(T2.BUDGET_HEADER_ID) INTO LI_COUNT
	FROM  AWARD_BUDGET_HEADER T1
	INNER JOIN AWARD_BUDGET_DETAIL T2 ON T2.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID
	WHERE T1.AWARD_ID = AV_AWARD_ID
	AND T1.VERSION_NUMBER = (SELECT MAX(S1.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER S1 WHERE S1.AWARD_ID = T1.AWARD_ID)
	AND T2.BUDGET_CATEGORY_CODE = 'GRT'
	AND T2.LINE_ITEM_COST > 0;
	IF LI_COUNT > 0 THEN
		RETURN 'TRUE';
	END IF;
	RETURN 'FALSE';
END
$$
DELIMITER ;
