DELIMITER $$
CREATE PROCEDURE `GET_TABLE_COUNT_FOR_VALIDATION`(AV_SCHEMA_NAME VARCHAR(100))
BEGIN
DECLARE LS_TABLE_NAME       VARCHAR(100);
DECLARE LI_COUNT			INT(11);
DECLARE LS_FILE_TYPE  		VARCHAR(50);
DECLARE LS_IS_LOOKUP        VARCHAR(1);
DECLARE LI_COLUMN_COUNT     INT(11);
DECLARE LS_TABLE_TYPE       VARCHAR(100);
DECLARE L1_ROW_COUNT        INT(11);
VAL_LABEL : BEGIN
		SELECT COUNT(*) INTO LI_COUNT
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = AV_SCHEMA_NAME;
		IF LI_COUNT = 0 THEN
			SELECT 'Invalid schema';
			LEAVE VAL_LABEL;
		END IF;
		TRUNCATE TABLE TABLE_COUNT_VALIDATION;
		BEGIN
				DECLARE LS_ERROR VARCHAR(2000);
				DECLARE DONE1 INT DEFAULT FALSE;
				DECLARE TABLE_COUNT_CURSOR CURSOR FOR
				SELECT DISTINCT TABLE_NAME
				FROM INFORMATION_SCHEMA.TABLES
				WHERE TABLE_SCHEMA = AV_SCHEMA_NAME;
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
				DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
				BEGIN
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
					SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
					SELECT @full_error INTO LS_ERROR;
					INSERT INTO MIGRATION_ERROR_LOG(ERROR_TYPE,FILE_NAME,ERROR_MESSAGE)
					VALUES('Exception','TABLE_COUNT_FOR_VALIDATION',SUBSTR(LS_ERROR,1,999));
					COMMIT;
				END;
				OPEN TABLE_COUNT_CURSOR;
				TABLE_COUNT_CURSOR_LOOP : LOOP
						FETCH TABLE_COUNT_CURSOR INTO 	LS_TABLE_NAME;
						IF DONE1 THEN
							LEAVE TABLE_COUNT_CURSOR_LOOP;
						END IF;
						SELECT COUNT(COLUMN_NAME) INTO LI_COLUMN_COUNT
						FROM INFORMATION_SCHEMA.COLUMNS
						WHERE TABLE_SCHEMA = AV_SCHEMA_NAME
						AND TABLE_NAME = LS_TABLE_NAME;
						IF LI_COLUMN_COUNT <= 5 THEN
						  set	LS_IS_LOOKUP = 'Y';
						ELSE
						   set  LS_IS_LOOKUP = 'N';
						END IF;
						SELECT TABLE_TYPE INTO LS_TABLE_TYPE
						FROM INFORMATION_SCHEMA.TABLES
						WHERE TABLE_SCHEMA = AV_SCHEMA_NAME
						AND TABLE_NAME = LS_TABLE_NAME;
						SET @QUERY_STATEMENT =CONCAT('SELECT COUNT(*) INTO @RESULT FROM ',AV_SCHEMA_NAME,'.',LS_TABLE_NAME);
						PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
						EXECUTE EXECUTABLE_STAEMENT;
						SET L1_ROW_COUNT = @RESULT;
						DEALLOCATE PREPARE EXECUTABLE_STAEMENT;
						INSERT INTO TABLE_COUNT_VALIDATION (TABLE_NAME,IS_LOOKUP,TABLE_TYPE,COLUMN_COUNT,ROWS_COUNT,UPDATE_TIMESTAMP)
						VALUES (LS_TABLE_NAME,LS_IS_LOOKUP,LS_TABLE_TYPE,LI_COLUMN_COUNT,L1_ROW_COUNT,UTC_TIMESTAMP());
						COMMIT;
				END LOOP;
				CLOSE TABLE_COUNT_CURSOR;
		END;
		SELECT 1  AS RESULT;
END;
END
$$
DELIMITER ;
