DELIMITER $$
CREATE PROCEDURE `GET_FIBI_AWARD_HIERARCHY_bckup`(
AV_AWARD_NUMBER 	varchar(12)
)
    DETERMINISTIC
BEGIN
DECLARE LS_VAR        LONGTEXT;
DECLARE LS_INTO_VAR   LONGTEXT;
DECLARE LS_CHILD_LIST LONGTEXT;
SET LS_VAR = AV_AWARD_NUMBER;
SET LS_CHILD_LIST = '';
    REPEAT
		SELECT GROUP_CONCAT(AWARD_NUMBER SEPARATOR ',') INTO LS_INTO_VAR FROM AWARD_HIERARCHY WHERE FIND_IN_SET(PARENT_AWARD_NUMBER, LS_VAR) > 0  ;
            IF LS_INTO_VAR IS NOT NULL  THEN
				SET LS_CHILD_LIST = CONCAT(LS_CHILD_LIST,',',LS_INTO_VAR) ;
				SET LS_VAR = LS_INTO_VAR ;
			END IF;
       UNTIL LS_INTO_VAR IS NULL  END REPEAT;
SELECT T2.AWARD_ID,T1.ROOT_AWARD_NUMBER,T1.AWARD_NUMBER, T1.LVL AS LEVEL, T1.PARENT_AWARD_NUMBER, T1.PI_NAME, T2.ACCOUNT_NUMBER, T2.STATUS_CODE
FROM
(
  SELECT ROOT_AWARD_NUMBER,AWARD_NUMBER,1 AS LVL ,PARENT_AWARD_NUMBER,FN_AB_GET_PI_FULL_NAME(AWARD_NUMBER) AS PI_NAME
  FROM AWARD_HIERARCHY WHERE AWARD_NUMBER = AV_AWARD_NUMBER
  UNION ALL
  SELECT ROOT_AWARD_NUMBER,AWARD_NUMBER,FN_GET_AWARD_HIERARCHY_LEVEL(AWARD_NUMBER,AV_AWARD_NUMBER) AS LVL,PARENT_AWARD_NUMBER,FN_AB_GET_PI_FULL_NAME(AWARD_NUMBER) AS PI_NAME
  FROM AWARD_HIERARCHY WHERE FIND_IN_SET(AWARD_NUMBER,LS_CHILD_LIST)
) T1
INNER JOIN AWARD T2 ON T1.AWARD_NUMBER = T2.AWARD_NUMBER
WHERE T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
ORDER BY  T1.LVL,T1.PARENT_AWARD_NUMBER,T1.AWARD_NUMBER;
END
$$
DELIMITER ;
