DELIMITER $$
CREATE  PROCEDURE `GET_SERVICE_REQUEST_DASHBOARD_COUNT`(
AV_SR_HEADER_ID	            VARCHAR(6),
AV_REQUEST_SUBJECT	        VARCHAR(1000),
AV_MODULE_CODE	            VARCHAR(100),
AV_REQUEST_TYPE   	        VARCHAR(200),
AV_REQUEST_STATUS           VARCHAR(200),
AV_LEAD_UNIT_NUMBER   	    VARCHAR(50),
AV_PRIORITY                 VARCHAR(200),
AV_PERSON_ID 			    VARCHAR(200),
AV_SORT_TYPE 			    VARCHAR(500),
AV_PAGED  				    INT(10),
AV_LIMIT				    INT(10),
AV_TAB_TYPE 				VARCHAR(30),
AV_UNLIMITED                BOOLEAN,
AV_TYPE                     VARCHAR(1)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
DECLARE TAB_QUERY LONGTEXT;
DECLARE JOIN_CONDITION LONGTEXT;
DECLARE SELECTED_FIELD_LIST LONGTEXT;
DECLARE IS_UNIT_ADMIN INT(11);
DECLARE IS_DEPT_ADMIN INT(11);
DECLARE IS_GROUP_ADMIN INT(11);
DECLARE LS_FILTER_CONDITION2 	LONGTEXT;
DECLARE LS_ADMIN_GROUP_CONDITION LONGTEXT;
DECLARE LS_GROUP_ADMIN_AND_ADMINISTRATOR LONGTEXT;
DECLARE LS_PI_PERSON LONGTEXT;
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
SET LS_FILTER_CONDITION ='';
SET TAB_QUERY ='';
SET LS_DYN_SQL ='';
SET JOIN_CONDITION = '';
SET SELECTED_FIELD_LIST= '';
SET LS_FILTER_CONDITION2 ='';
SET LS_FILTER_CONDITION2 = CONCAT(LS_FILTER_CONDITION2,' WHERE (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)');
SET LS_ADMIN_GROUP_CONDITION = CONCAT('WHERE (T1.ADMIN_GROUP_ID IN(
																	SELECT AG.ADMIN_GROUP_ID
																	FROM ADMIN_GROUP AG
																	INNER JOIN ROLE_RIGHTS RR ON AG.ROLE_ID = RR.ROLE_ID
																	INNER JOIN RIGHTS R ON RR.RIGHT_ID = R.RIGHT_ID
																	INNER JOIN PERSON_ROLES PR ON RR.ROLE_ID = PR.ROLE_ID
																	WHERE PR.PERSON_ID = ''', AV_PERSON_ID ,'''
																	AND R.RIGHT_NAME = ''VIEW_ASSIGMENT_GROUP_SERVICE_REQUEST'')');
IF AV_TYPE = 'A'   THEN
			IF AV_SR_HEADER_ID IS NOT NULL AND AV_SR_HEADER_ID <> '' THEN
			  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.SR_HEADER_ID LIKE ''%',AV_SR_HEADER_ID,'%'' AND ');
			END IF;
			IF AV_REQUEST_SUBJECT IS NOT NULL  AND AV_REQUEST_SUBJECT <> '' THEN
				SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.SUBJECT LIKE ''%',AV_REQUEST_SUBJECT,'%'' AND ');
			END IF;
			IF AV_REQUEST_TYPE IS NOT NULL  AND AV_REQUEST_TYPE <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.TYPE_CODE IN (',AV_REQUEST_TYPE,') AND ');
            END IF;
			IF AV_LEAD_UNIT_NUMBER IS NOT NULL  AND AV_LEAD_UNIT_NUMBER <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.UNIT_NUMBER LIKE ''%',AV_LEAD_UNIT_NUMBER,'%'' AND ');
			END IF;
			IF AV_PRIORITY IS NOT NULL  AND AV_PRIORITY <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PRIORITY_ID IN (',AV_PRIORITY,')  AND ');
			END IF;
			IF AV_REQUEST_STATUS IS NOT NULL  AND AV_REQUEST_STATUS <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.STATUS_CODE IN (',AV_REQUEST_STATUS,')  AND ');
			END IF;
			IF AV_MODULE_CODE IS NOT NULL  AND AV_MODULE_CODE <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.MODULE_CODE IN (',AV_MODULE_CODE,')  AND ');
			END IF;
END IF;
		SELECT
    COUNT(1)
INTO IS_UNIT_ADMIN FROM
    ROLE_RIGHTS T1
        LEFT JOIN
    RIGHTS T2 ON T1.RIGHT_ID = T2.RIGHT_ID
        LEFT JOIN
    PERSON_ROLES T3 ON T1.ROLE_ID = T3.ROLE_ID
WHERE
    T3.PERSON_ID = AV_PERSON_ID
        AND T2.RIGHT_NAME = 'SERVICE_REQUEST_ADMINISTRATOR';
		SELECT
    COUNT(1)
INTO IS_GROUP_ADMIN FROM
    ROLE_RIGHTS T1
        LEFT JOIN
    RIGHTS T2 ON T1.RIGHT_ID = T2.RIGHT_ID
        LEFT JOIN
    PERSON_ROLES T3 ON T1.ROLE_ID = T3.ROLE_ID
WHERE
    T3.PERSON_ID = AV_PERSON_ID
        AND T2.RIGHT_NAME = 'VIEW_ASSIGMENT_GROUP_SERVICE_REQUEST';
IF AV_TAB_TYPE = 'MY_REQUEST' THEN
			SET TAB_QUERY = CONCAT(' WHERE ( T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''',AV_PERSON_ID,''')
                                            OR (T5.WATCHER_PERSON_ID IN (''',AV_PERSON_ID,''')))' );
ELSEIF AV_TAB_TYPE = 'ALL_REQUEST' THEN
            SET LS_GROUP_ADMIN_AND_ADMINISTRATOR = CONCAT('WHERE (T1.ADMIN_GROUP_ID IN(
																	SELECT AG.ADMIN_GROUP_ID
																	FROM ADMIN_GROUP AG
																	INNER JOIN ROLE_RIGHTS RR ON AG.ROLE_ID = RR.ROLE_ID
																	INNER JOIN RIGHTS R ON RR.RIGHT_ID = R.RIGHT_ID
																	INNER JOIN PERSON_ROLES PR ON RR.ROLE_ID = PR.ROLE_ID
																	WHERE PR.PERSON_ID = ''', AV_PERSON_ID ,'''
																	AND R.RIGHT_NAME = ''VIEW_ASSIGMENT_GROUP_SERVICE_REQUEST''))
                                                                    OR (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP))');
		   SET LS_PI_PERSON = CONCAT('( T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''',AV_PERSON_ID,''')
                                            OR (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_SR)) OR (T5.WATCHER_PERSON_ID IN (''',AV_PERSON_ID,'''))
                                                                                       OR (T1.ASSIGNEE_PERSON_ID = ''',AV_PERSON_ID,''') )');
			IF IS_UNIT_ADMIN > 0 && IS_GROUP_ADMIN > 0 THEN
               SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_GROUP_ADMIN_AND_ADMINISTRATOR,' OR ', LS_PI_PERSON);
			ELSEIF IS_UNIT_ADMIN > 0 THEN
				SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_FILTER_CONDITION2,' ) OR ' , LS_PI_PERSON);
			ELSEIF IS_GROUP_ADMIN > 0 THEN
				SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_ADMIN_GROUP_CONDITION, ') OR ' , LS_PI_PERSON );
			ELSE
				SET TAB_QUERY = CONCAT(' WHERE ', LS_PI_PERSON);
			END IF;
ELSEIF AV_TAB_TYPE = 'NEW_SUBMISSIONS' THEN
			IF IS_UNIT_ADMIN > 0 THEN
				SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_FILTER_CONDITION2 ,' AND T1.STATUS_CODE = 4 )');
			ELSE
				SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_ADMIN_GROUP_CONDITION ,' AND T1.STATUS_CODE = 4 )');
			END IF;
ELSEIF AV_TAB_TYPE = 'MY_PENDING_SERVICE_REQUEST' THEN
					SET TAB_QUERY = CONCAT(' WHERE ( T1.ASSIGNEE_PERSON_ID =''',AV_PERSON_ID,'''
                                            ) AND T1.STATUS_CODE IN(2,4)
											OR T1.SR_HEADER_ID in (SELECT T9.MODULE_ITEM_ID FROM WORKFLOW T9
                                        INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
                                        WHERE T9.MODULE_ITEM_ID = T1.SR_HEADER_ID
                                        AND T10.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                                        AND T9.MODULE_CODE = 20 AND T9.IS_WORKFLOW_ACTIVE = ''Y''
                                        AND T10.APPROVAL_STATUS = ''W''
                                 )' );
 ELSEIF AV_TAB_TYPE = 'ALL_PENDING_SERVICE_REQUEST' THEN
			IF IS_UNIT_ADMIN > 0 THEN
				SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_FILTER_CONDITION2 ,' AND T1.STATUS_CODE in (3,4,2,7))');
			ELSE
				SET TAB_QUERY = CONCAT(TAB_QUERY,' ',LS_ADMIN_GROUP_CONDITION ,' AND T1.STATUS_CODE in (3,4,2,7) )');
			END IF;
END IF;
IF AV_SORT_TYPE IS NULL or AV_SORT_TYPE ='' THEN
	SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
ELSE
    SET AV_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
END IF;
IF AV_UNLIMITED = TRUE THEN
	SET LS_OFFSET_CONDITION = '';
ELSE
	SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
END IF;
 IF LS_FILTER_CONDITION <>'' THEN
SET LS_FILTER_CONDITION = CONCAT(' WHERE T.IS_SYSTEM_GENERATED = ''N'' AND',LS_FILTER_CONDITION);
SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) INTO LS_FILTER_CONDITION FROM DUAL;
ELSE
SET LS_FILTER_CONDITION = CONCAT(' WHERE T.IS_SYSTEM_GENERATED = ''N''',LS_FILTER_CONDITION);
 END IF;
SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ',AV_PERSON_ID,'
							AND RIGHT_NAME IN (''SERVICE_REQUEST_ADMINISTRATOR'')
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ',AV_PERSON_ID,'
							AND RIGHT_NAME IN (''SERVICE_REQUEST_ADMINISTRATOR'')
                            )),
							ACCESS_TMP_SR
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_SERVICE_REQUEST'',''VIEW_SERVICE_REQUEST'')
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_SERVICE_REQUEST'',''VIEW_SERVICE_REQUEST'')
                            )),
							SR_TEMP AS (SELECT T9.MODULE_ITEM_ID FROM WORKFLOW T9
                                        INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
                                        WHERE T9.MODULE_ITEM_ID = T1.SR_HEADER_ID
                                        AND T10.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                                        AND T9.MODULE_CODE = 20 AND T9.IS_WORKFLOW_ACTIVE = ''Y''
                                        AND T10.APPROVAL_STATUS = ''W'')
							');
        SET LS_DYN_SQL =CONCAT(LS_DYN_SQL,'SELECT COUNT(1) FROM (SELECT DISTINCT *  FROM(SELECT T1.SR_HEADER_ID,
																	T1.MODULE_ITEM_KEY,
                                                                    T8.DESCRIPTION AS CATEGORY,
																	T6.FULL_NAME AS ASIGNEE_FULL_NAME,
																	T7.FULL_NAME AS REPORTER_FUL_NAME,
																	T2.DESCRIPTION AS REQUEST_TYPE,
																	T1.TYPE_CODE,
																	T1.STATUS_CODE,
                                                                    T1.PRIORITY_ID,
																	T1.SUBJECT,
                                                                    T4.UNIT_NAME,
																	T1.UNIT_NUMBER,
																	T3.DESCRIPTION AS REQUEST_STATUS,
																	T1.UPDATE_TIMESTAMP,
                                                                    T1.ADMIN_GROUP_ID,
                                                                    T1.IS_SYSTEM_GENERATED,
																	T1.MODULE_CODE,
                                                                    T9.DESCRIPTION AS PRIORITY
															FROM SR_HEADER T1
															INNER JOIN SR_TYPE T2 ON T1.TYPE_CODE = T2.TYPE_CODE
															INNER JOIN SR_STATUS T3 ON T3.STATUS_CODE = T1.STATUS_CODE
															LEFT JOIN UNIT T4 ON T4.UNIT_NUMBER = T1.UNIT_NUMBER
															LEFT JOIN SR_WATCHER T5 ON T5.SR_HEADER_ID = T1.SR_HEADER_ID
															LEFT JOIN PERSON T6 ON T6.PERSON_ID = T1.ASSIGNEE_PERSON_ID
															LEFT JOIN PERSON T7 ON T7.PERSON_ID = T1.REPORTER_PERSON_ID
															LEFT JOIN COEUS_MODULE T8 ON T8.MODULE_CODE = T1.MODULE_CODE
                                                            LEFT JOIN SR_PRIORITY T9 ON T9.PRIORITY_ID = T1.PRIORITY_ID
															',JOIN_CONDITION,TAB_QUERY,
									')T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE, ') R' );
 SET @QUERY_STATEMENT = LS_DYN_SQL;
 PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
 EXECUTE EXECUTABLE_STAEMENT;
END
$$
DELIMITER ;
