DELIMITER $$
CREATE  PROCEDURE `INSERT_MILESTONE_NUMBER`()
BEGIN
DECLARE LS_AWARD_NUMBER VARCHAR(22);
DECLARE LS_MILESTONE varchar(1000);
DECLARE LS_START_DATE datetime;
DECLARE LS_END_DATE datetime;
BEGIN
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE CUR_CRITERIA CURSOR FOR
select AWARD_NUMBER,MILESTONE,START_DATE,END_DATE from award_milestone
where MILESTONE_NUMBER is NULL
group by AWARD_NUMBER,MILESTONE,START_DATE,END_DATE;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN CUR_CRITERIA;
INSERT_CUR_MAPPING_LOOP: LOOP
FETCH CUR_CRITERIA INTO
LS_AWARD_NUMBER,
LS_MILESTONE,
LS_START_DATE,
LS_END_DATE;
IF DONE1 THEN
LEAVE INSERT_CUR_MAPPING_LOOP;
END IF;
UPDATE AWARD_MILESTONE SET MILESTONE_NUMBER = (SELECT current_timestamp(3)) WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND MILESTONE = LS_MILESTONE AND START_DATE = LS_START_DATE AND END_DATE = LS_END_DATE;
END LOOP;
CLOSE CUR_CRITERIA;
END;
END
$$
DELIMITER ;
