DELIMITER $$
CREATE DEFINER=`irshad`@`%` PROCEDURE `KU_STDT_PJT_TEAM_PREPROCESS`(AV_TYPE INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LS_STUDENT_ID VARCHAR(40);
DECLARE LS_STUDENT_NAME VARCHAR(255);
DECLARE LS_FULL_NAME VARCHAR(255);
DECLARE LS_ROLE VARCHAR(100);
DECLARE LS_ACCOUNT_NUMBER VARCHAR(100);
DECLARE LS_START_DATE VARCHAR(50);
DECLARE LS_END_DATE VARCHAR(50);
DECLARE LI_PERCENTAGE DECIMAL(5,2);
DECLARE LI_CNT INT;
DECLARE DONE BOOLEAN;
DECLARE LS_ERROR VARCHAR(2000);
DECLARE LS_ERR_FLG VARCHAR(1);
DECLARE CUR_INPT CURSOR FOR
 SELECT INPUT_RECORD_ID, TRIM(STUDENT_ID),TRIM(ROLE), TRIM(ACCOUNT_NUMBER), TRIM(START_DATE), TRIM(END_DATE), TRIM(PERCENTAGE_CHARGED)
  FROM KU_STUDENT_PROJECT_TEAM_HDR
  WHERE STATUS IS NULL;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
	 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
	SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
	SELECT @full_error INTO LS_ERROR;
	UPDATE KU_STUDENT_PROJECT_TEAM_HDR
	SET STATUS = 'ERROR',
		ERROR_MESSAGE = (LS_ERROR)
	WHERE INPUT_RECORD_ID = LI_RECORD_ID;
	INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
			(INPUT_RECORD_ID,ERROR_MESSAGE)
	VALUES  (LI_RECORD_ID,LS_ERROR);
	SET LS_ERR_FLG ='Y';
END;
 BEGIN
	SELECT 'Truncating details table';
	TRUNCATE TABLE KU_STUDENT_PROJECT_TEAM_DTLS;
	SELECT 'Truncate complete';
	OPEN CUR_INPT;
	inpt_loop: LOOP
		SET DONE = FALSE;
		FETCH CUR_INPT INTO LI_RECORD_ID,LS_STUDENT_ID,LS_ROLE,LS_ACCOUNT_NUMBER,LS_START_DATE,LS_END_DATE,LI_PERCENTAGE;
		IF DONE = TRUE THEN
		   LEAVE inpt_loop;
		END IF;
		SET LS_ERR_FLG ='N';
		SET LI_CNT = -1;
		SELECT COUNT(*)
		  INTO LI_CNT
		  FROM PERSON
		WHERE PERSON_ID = LS_STUDENT_ID
		 AND STATUS = 'A';
		IF LI_CNT <> 1 THEN
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'ERROR',
				  ERROR_MESSAGE = 'Invalid value of student id'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
			INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
					(INPUT_RECORD_ID,ERROR_MESSAGE)
			VALUES  (LI_RECORD_ID,'Invalid value of student id');
			SET LS_ERR_FLG ='Y';
		ELSE
			SELECT FULL_NAME
			  INTO LS_STUDENT_NAME
			  FROM PERSON
			WHERE PERSON_ID = LS_STUDENT_ID
			 AND STATUS = 'A';
		END IF;
		IF LENGTH(LS_ROLE) > 100 THEN
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'ERROR',
				  ERROR_MESSAGE = 'Role provided is too long'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
			INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
					(INPUT_RECORD_ID,ERROR_MESSAGE)
			VALUES  (LI_RECORD_ID,'Role provided is too long');
			SET LS_ERR_FLG ='Y';
		END IF;
		SET LI_CNT = -1;
		SELECT COUNT(*)
		  INTO LI_CNT
		FROM AWARD
		WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
		AND ACCOUNT_NUMBER = LS_ACCOUNT_NUMBER;
		IF LI_CNT = 0 THEN
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'ERROR',
				  ERROR_MESSAGE = 'No active awards fetched for the account number provided'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
			INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
					(INPUT_RECORD_ID,ERROR_MESSAGE)
			VALUES  (LI_RECORD_ID,'No active awards fetched for the account number provided');
			SET LS_ERR_FLG ='Y';
        ELSE
			SET LI_CNT = -1;
			SELECT COUNT(*)
			  INTO LI_CNT
			  FROM AWARD_PROJECT_TEAM
			WHERE PERSON_ID = LS_STUDENT_ID
			  AND AWARD_ID IN (SELECT AWARD_ID
								  FROM AWARD
								 WHERE ACCOUNT_NUMBER = LS_ACCOUNT_NUMBER
								   AND AWARD_SEQUENCE_STATUS = 'ACTIVE') ;
			IF LI_CNT <> 0 THEN
				UPDATE KU_STUDENT_PROJECT_TEAM_HDR
				  SET STATUS = 'ERROR',
					  ERROR_MESSAGE = 'Student id already exists in Award Proj Team'
				WHERE INPUT_RECORD_ID = LI_RECORD_ID;
				INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
						(INPUT_RECORD_ID,ERROR_MESSAGE)
				VALUES  (LI_RECORD_ID,'Student id already exists in Award Proj Team');
				SET LS_ERR_FLG ='Y';
			END IF;
		END IF;
		IF STR_TO_DATE(LS_START_DATE,'%d-%M-%y') IS NULL THEN
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'ERROR',
				  ERROR_MESSAGE = 'Invalid format for start date'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
			INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
					(INPUT_RECORD_ID,ERROR_MESSAGE)
			VALUES  (LI_RECORD_ID,'Invalid format for start date');
			SET LS_ERR_FLG ='Y';
		END IF;
		IF STR_TO_DATE(LS_END_DATE,'%d-%M-%y') IS NULL THEN
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'ERROR',
				  ERROR_MESSAGE = 'Invalid format for end date'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
			INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
					(INPUT_RECORD_ID,ERROR_MESSAGE)
			VALUES  (LI_RECORD_ID,'Invalid format for end date');
			SET LS_ERR_FLG ='Y';
		END IF;
		IF LI_PERCENTAGE IS NOT NULL  AND ( LI_PERCENTAGE < 0 OR LI_PERCENTAGE > 100) THEN
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'ERROR',
				  ERROR_MESSAGE = 'Invalid Percentage value, please provide a value between 0 and 100'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
			INSERT INTO KU_STUDENT_PROJECT_TEAM_ERRLOG
					(INPUT_RECORD_ID,ERROR_MESSAGE)
			VALUES  (LI_RECORD_ID, 'Invalid Percentage value, please provide a value between 0 and 100');
			SET LS_ERR_FLG ='Y';
		END IF;
		IF LS_ERR_FLG = 'N' THEN
			INSERT INTO KU_STUDENT_PROJECT_TEAM_DTLS (
							 INPUT_RECORD_ID,
							 AWARD_NUMBER,
							 AWARD_ID,
							 SEQUENCE_NUMBER,
							 AWARD_SEQUENCE_STATUS,
							 STUDENT_ID,
							 STUDENT_NAME ,
							 ROLE,
							 ACCOUNT_NUMBER,
							 START_DATE,
							 END_DATE,
							 PERCENTAGE_CHARGED)
					   (SELECT LI_RECORD_ID ,AWARD_NUMBER,AWARD_ID,SEQUENCE_NUMBER,AWARD_SEQUENCE_STATUS, LS_STUDENT_ID,LS_STUDENT_NAME,
							  LS_ROLE,LS_ACCOUNT_NUMBER,LS_START_DATE,LS_END_DATE,LI_PERCENTAGE
						  FROM AWARD
						 WHERE ACCOUNT_NUMBER = LS_ACCOUNT_NUMBER
						   AND AWARD_SEQUENCE_STATUS = 'ACTIVE'
						);
			UPDATE KU_STUDENT_PROJECT_TEAM_HDR
			  SET STATUS = 'VALID'
			WHERE INPUT_RECORD_ID = LI_RECORD_ID;
		END IF;
	END LOOP;
	CLOSE CUR_INPT;
 END;
 SELECT 'Pre process complete';
END
$$
DELIMITER ;
