DELIMITER $$
CREATE DEFINER=`ku_rms_user`@`%` PROCEDURE `LOAD_PROP_PRE_RPT_DTLS_NW`(AV_TYPE INT)
BEGIN
	TRUNCATE TABLE PROP_DETAILS_TAB;
	INSERT INTO  PROP_DETAILS_TAB
	(     PROPOSAL_ID,
		  TITLE,
		  END_DATE ,
		  START_DATE,
		  DURATION,
		  PROPOSAL_STATUS,
		  ANTICIPATED_AWARD_TYPE,
		  SPONSOR_DEADLINE_DATE,
		  SUBMISSION_DATE,
		  PROPOSAL_TYPE,
		  GRANT_CALL_TYPE,
		  GRANT_CALL_TITLE,
		  BUDGET_STATUS ,
		  TOTAL_DIRECT_COST ,
		  TOTAL_INDIRECT_COST ,
		  TOTAL_SUBCONTRACT_COST ,
		  UNDERRECOVERY_AMOUNT,
		  SPONSOR_NAME,
		  LEAD_UNIT_NAME,
		  ACTIVITY_TYPE ,
		  SPECIAL_REVIEW ,
		  FUNDING_SCHEME ,
		  TYPE_OF_FUNDING_AGENCY ,
		  DISCIPLINE_CLUSTER,
		  ORGANIZATION,
		  PI_PERSON_ID ,
		  PI_NAME,
		  PERSON_ID ,
		  PERSON_NAME ,
		  EMPLOYEE_FLAG,
		  PERCENTAGE_OF_EFFORT,
		  PERSON_ROLE ,
		  PERSON_ROLE_ID ,
		  LEAD_UNIT_NUMBER,
		  SPECIAL_REVIEW_APPROVAL_STATUS,
		  SPR_PROTOCOL_NUMBER,
		  SPR_APPLICATION_DATE,
		  SPR_APPROVAL_DATE,
		  SPR_EXPIRATION_DATE,
		  PRIME_SPONSOR_NAME,
		  INTERNAL_DEADLINE_DATE,
		  SPONSOR_PROPOSAL_NUMBER,
		  EXTERNAL_FUNDING_AGENCY_ID,
		  CFDA_NUMBER,
		  PROGRAM_ANNOUNCEMENT_NUMBER,
		  BUDGET_VERSION_NUMBER,
		  FINAL_VERSION_FLAG,
		  GRANT_CALL_ABBREVIATION,
		  GRANT_CALL_HOME_UNIT_NAME,
		  GRANT_CALL_OPENING_DATE,
		  GRANT_CALL_closing_date,
		  BUDGET_CATEGORY,
		  COST_ELEMENT,
		  LINE_ITEM_COST,
		  PERSON_EMAIL,
		  KEY_PERSON_TITLE,
		  PERSON_DEPARTMENT,
		  PROPOSAL_PERCENTAGE_OF_EFFORT,
		  PROPOSAL_NUMBER,
		  PROPOSAL_CREATE_DATE ,
		  TOTAL_COST,
		  IN_KIND_CONTRIBUTION,
		  TOTAL_REQUESTED_COST ,
		  TOTAL_REQUESTED_COST_USD,
		  FACULTY_TITLE,
		  FACULTY_EMAIL_ADDRESS,
		  SPONSOR,
		  SPONSOR_CODE ,
		  INS_PROPOSAL_STATUS,
		  FUNDING_SPONSOR_NAME,
		  SUBMIT_USER,
		  RESEARCH_CENTER,
		  VERTICAL_AREA,
		  HORIZONTAL_AREA,
		  IP_PROPOSAL_ID
		)
	(SELECT  DISTINCT
			t1.PROPOSAL_ID AS PROPOSAL_ID,
			t1.TITLE AS TITLE,
			CAST(t1.END_DATE AS DATE) AS END_DATE,
			CAST(t1.START_DATE AS DATE) AS START_DATE,
			t1.DURATION AS DURATION,
			(SELECT DESCRIPTION FROM EPS_PROPOSAL_STATUS WHERE STATUS_CODE = t1.STATUS_CODE) AS PROPOSAL_STATUS,
			(SELECT AWARD_TYPE_CODE FROM award_type WHERE AWARD_TYPE_CODE = t1.AWARD_TYPE_CODE) AS  ANTICIPATED_AWARD_TYPE,
			CAST(t1.SPONSOR_DEADLINE_DATE AS DATE) AS SPONSOR_DEADLINE_DATE,
			CAST(t1.SUBMISSION_DATE AS DATE) AS SUBMISSION_DATE,
			(SELECT t3.DESCRIPTION FROM eps_proposal_type t3 WHERE t3.TYPE_CODE = t1.TYPE_CODE ) AS PROPOSAL_TYPE,
			(SELECT t4.DESCRIPTION FROM grant_call_type t4 WHERE t4.GRANT_TYPE_CODE = t1.GRANT_TYPE_CODE ) AS GRANT_CALL_TYPE,
			t5.NAME AS GRANT_CALL_TITLE,
			bd.BUDGET_STATUS,
			bd.TOTAL_DIRECT_COST AS TOTAL_DIRECT_COST,
			bd.TOTAL_INDIRECT_COST AS TOTAL_INDIRECT_COST,
			bd.TOTAL_SUBCONTRACT_COST AS TOTAL_SUBCONTRACT_COST,
			bd.UNDERRECOVERY_AMOUNT AS UNDERRECOVERY_AMOUNT,
			t14.SPONSOR_NAME AS SPONSOR_NAME,
			t1.HOME_UNIT_NAME AS LEAD_UNIT_NAME,
			(SELECT DESCRIPTION FROM activity_type WHERE  ACTIVITY_TYPE_CODE = t1.ACTIVITY_TYPE_CODE ) AS ACTIVITY_TYPE,
			(SELECT DESCRIPTION FROM special_review WHERE SPECIAL_REVIEW_CODE = t11.SPECIAL_REVIEW_CODE) AS SPECIAL_REVIEW,
			(SELECT t32.DESCRIPTION
				FROM sponsor_funding_scheme t13, funding_scheme t32
			  WHERE t13.FUNDING_SCHEME_ID =  t5.FUNDING_SCHEME_ID
				AND t32.FUNDING_SCHEME_CODE = t13.FUNDING_SCHEME_CODE
			) AS FUNDING_SCHEME,
			(SELECT DESCRIPTION FROM sponsor_type WHERE SPONSOR_TYPE_CODE = t14.SPONSOR_TYPE_CODE) AS TYPE_OF_FUNDING_AGENCY,
			(SELECT DESCRIPTION FROM  EPS_PROP_DISCIPLINE_CLUSTER WHERE CLUSTER_CODE = t1.CLUSTER_CODE) AS DISCIPLINE_CLUSTER,
			( SELECT t18.ORGANIZATION_NAME
			   FROM  ROLODEX t17,
					 ORGANIZATION t18
			  WHERE  t17.rolodex_id = t8.rolodex_id
				AND  t18.organization_id = t17.organization
			)  AS ORGANIZATION,
			IFNULL(t19.PERSON_ID, t19.ROLODEX_ID) AS PI_PERSON_ID,
			t19.FULL_NAME AS PI_NAME,
			IFNULL(t8.PERSON_ID, t8.ROLODEX_ID) AS PERSON_ID,
			t8.FULL_NAME AS PERSON_NAME,
			(CASE
				WHEN (t8.PERSON_ID IS NOT NULL) THEN 'Y'
				ELSE 'N'
			END) AS EMPLOYEE_FLAG,
			t8.PERCENTAGE_OF_EFFORT AS PERCENTAGE_OF_EFFORT,
			t20.DESCRIPTION AS PERSON_ROLE,
			t20.PROP_PERSON_ROLE_ID AS PERSON_ROLE_ID,
			t1.HOME_UNIT_NUMBER AS LEAD_UNIT_NUMBER,
		  /*  t23.TITLE AS AWARD_TITLE,
			t23.KEY_PERSON_NAME AS AWARD_KEY_PERSON_NAME,
			t23.KEY_PERSON_ID AS AWARD_KEY_PERSON_ID,
			t23.AWARD_TYPE AS AWARD_TYPE,
			t23.ACCOUNT_TYPE AS AWARD_ACCOUNT_TYPE,
			t23.AWARD_STATUS AS AWARD_STATUS,
			t23.SPONSOR_NAME AS AWARD_SPONSOR_NAME,
			t23.SPONSOR_TYPE AS AWARD_SPONSOR_TYPE,
			t23.SPONSOR_AWARD_NUMBER AS AWARD_SPONSOR_AWARD_NUMBER,
			t23.LEAD_UNIT_NUMBER AS AWARD_LEAD_UNIT_NUMBER,
			t23.unit_name AS AWARD_LEAD_UNIT_NAME,
			t23.AWARD_EFFECTIVE_DATE AS AWARD_EFFECTIVE_DATE,
			t23.FINAL_EXPIRATION_DATE AS AWARD_FINAL_EXPIRATION_DATE,
			t23.DURATION AS AWARD_DURATION,
			t23.AWARD_NUMBER AS AWARD_NUMBER,
			t23.ACCOUNT_NUMBER AS AWARD_ACCOUNT_NUMBER,
			t23.ANTICIPATED_TOTAL_AMOUNT AS ANTICIPATED_TOTAL_AMOUNT,
			t23.AMOUNT_OBLIGATED_TO_DATE AS AMOUNT_OBLIGATED_TO_DATE,
			t23.AWARD_ID AS AWARD_ID,*/
			(SELECT DESCRIPTION FROM sp_rev_approval_type WHERE APPROVAL_TYPE_CODE  = t11.SPR_APPROVAL_TYPE_CODE) AS SPECIAL_REVIEW_APPROVAL_STATUS,
			t11.SPR_PROTOCOL_NUMBER AS SPR_PROTOCOL_NUMBER,
			CAST(t11.SPR_APPLICATION_DATE AS DATE) AS SPR_APPLICATION_DATE,
			CAST(t11.SPR_APPROVAL_DATE AS DATE) AS SPR_APPROVAL_DATE,
			CAST(t11.SPR_EXPIRATION_DATE AS DATE) AS SPR_EXPIRATION_DATE,
			(SELECT SPONSOR_NAME FROM SPONSOR WHERE SPONSOR_CODE = t1.PRIME_SPONSOR_CODE) AS PRIME_SPONSOR_NAME,
			CAST(t1.INTERNAL_DEADLINE_DATE AS DATE) AS INTERNAL_DEADLINE_DATE,
			t1.SPONSOR_PROPOSAL_NUMBER AS SPONSOR_PROPOSAL_NUMBER,
			t1.EXTERNAL_FUNDING_AGENCY_ID AS EXTERNAL_FUNDING_AGENCY_ID,
			t1.CFDA_NUMBER AS CFDA_NUMBER,
			t1.PROGRAM_ANNOUNCEMENT_NUMBER AS PROGRAM_ANNOUNCEMENT_NUMBER,
			bd.BUDGET_VERSION_NUMBER,
		bd.FINAL_VERSION_FLAG,
			t5.ABBREVIATION AS GRANT_CALL_ABBREVIATION,
			t5.HOME_UNIT_NAME AS GRANT_CALL_HOME_UNIT_NAME,
			CAST(t5.OPENING_DATE AS DATE) AS GRANT_CALL_OPENING_DATE,
			CAST(t5.CLOSING_DATE AS DATE) AS GRANT_CALL_closing_date,
		--   (SELECT DESCRIPTION FROM budget_category WHERE BUDGET_CATEGORY_CODE = t26.BUDGET_CATEGORY_CODE) AS BUDGET_CATEGORY,
		--   (SELECT DESCRIPTION FROM cost_element WHERE COST_ELEMENT = t26.COST_ELEMENT) AS COST_ELEMENT,
          bd.BUDGET_CATEGORY,
		   bd.COST_ELEMENT,
			bd.LINE_ITEM_COST AS LINE_ITEM_COST,
			IFNULL((SELECT EMAIL_ADDRESS FROM PERSON WHERE PERSON_ID = t8.PERSON_ID),(SELECT EMAIL_ADDRESS FROM ROLODEX WHERE ROLODEX_ID = t8.ROLODEX_ID)
				  ) AS PERSON_EMAIL,
			 t8.DESIGNATION AS KEY_PERSON_TITLE,
			IFNULL( (SELECT UNIT_NAME FROM UNIT WHERE UNIT_NUMBER = ( SELECT HOME_UNIT FROM PERSON WHERE PERSON_ID = t8.PERSON_ID)),
					 ( SELECT t18.ORGANIZATION_NAME
						 FROM  ROLODEX t17,
							   ORGANIZATION t18
						WHERE  t17.rolodex_id = t8.rolodex_id
						  AND  t18.organization_id = t17.organization)
				 ) AS PERSON_DEPARTMENT,
			t8.PERCENTAGE_OF_EFFORT AS PROPOSAL_PERCENTAGE_OF_EFFORT,
		  /*  t23.PERCENTAGE_OF_EFFORT AS AWARD_PERCENTAGE_OF_EFFORT,
			t23.PRIME_SPONSOR_NAME AS AWARD_PRIME_SPONSOR_NAME,
			t23.PI_NAME AS AWARD_PI_NAME,
			t23.PERSON_ROLE AS AWARD_KEY_PERSON_ROLE,
			IFNULL(t23.KEY_PERSON_DEPARTMENT,
					t23.KEY_PERSON_ORGANIZATION) AS AWARD_KEY_PERSON_DEPT,
			t23.KEY_PERSON_EMAIL AS AWARD_KEY_PERSON_EMAIL,
			t23.ACCOUNT_TYPE AS ACCOUNT_TYPE,*/
			t1.IP_NUMBER AS PROPOSAL_NUMBER,
			t1.CREATE_TIMESTAMP AS PROPOSAL_CREATE_DATE,
		   -- t23.AWARD_CREATE_TIMESTAMP AS AWARD_CREATE_DATE,
		   -- t23.AWARD_EFFECTIVE_DATE AS AWARD_NOTICE_DATE,
			bd.TOTAL_COST,
			bd.IN_KIND_CONTRIBUTION,
			bd.TOTAL_REQUESTED_COST,
			bd.TOTAL_REQUESTED_COST_USD,
			   t19.DESIGNATION AS FACULTY_TITLE,
				t19.FACULTY_EMAIL_ADDRESS AS FACULTY_EMAIL_ADDRESS,
			CONCAT(t14.SPONSOR_CODE,
					'-',
					t14.SPONSOR_NAME) AS SPONSOR,
			t14.SPONSOR_CODE AS SPONSOR_CODE,
			(SELECT ps.DESCRIPTION
			  FROM  proposal_status ps
			  WHERE ps.STATUS_CODE = tp.STATUS_CODE ) AS INS_PROPOSAL_STATUS,
		   -- t23.BEGIN_DATE AS BEGIN_DATE,
			t14.SPONSOR_NAME AS FUNDING_SPONSOR_NAME,
			(SELECT FULL_NAME FROM PERSON WHERE USER_NAME = t1.SUBMIT_USER) AS SUBMIT_USER,
			cd.RESEARCH_CENTER AS RESEARCH_CENTER,
			t50.VERTICAL_AREA,
			t51.HORIZONTAL_AREA,
			tp.proposal_id AS IP_PROPOSAL_ID
	FROM eps_proposal t1
	LEFT JOIN grant_call_header t5 ON ( t5.GRANT_HEADER_ID = t1.GRANT_HEADER_ID )
	/*LEFT JOIN budget_header t6 ON  (t6.PROPOSAL_ID = t1.PROPOSAL_ID
									 AND (IS_FINAL_BUDGET = 'Y'
										  OR
										  (IS_LATEST_VERSION = 'Y' AND NOT EXISTS (SELECT 1 FROM BUDGET_HEADER WHERE PROPOSAL_ID = t6.PROPOSAL_ID AND IS_FINAL_BUDGET = 'Y'))
										  )
									)*/
	 LEFT JOIN (SELECT  DISTINCT	t6.PROPOSAL_ID,
                 (SELECT DESCRIPTION FROM budget_status WHERE BUDGET_STATUS_CODE = t6.BUDGET_STATUS_CODE) AS BUDGET_STATUS,
                 t6.TOTAL_DIRECT_COST AS TOTAL_DIRECT_COST,
			t6.TOTAL_INDIRECT_COST AS TOTAL_INDIRECT_COST,
			t6.TOTAL_SUBCONTRACT_COST AS TOTAL_SUBCONTRACT_COST,
			t6.UNDERRECOVERY_AMOUNT AS UNDERRECOVERY_AMOUNT,
            t6.VERSION_NUMBER AS BUDGET_VERSION_NUMBER,
			t6.IS_FINAL_BUDGET AS FINAL_VERSION_FLAG,
            FORMAT((t6.COST_SHARING_AMOUNT + t6.TOTAL_COST),
				2) AS TOTAL_COST,
			FORMAT(t6.COST_SHARING_AMOUNT,2) AS IN_KIND_CONTRIBUTION,
			ROUND(t6.TOTAL_COST, 2) AS TOTAL_REQUESTED_COST,
			ROUND((t6.TOTAL_COST / (SELECT
						currency_rate.CURRENCY_RATE
					FROM
						currency_rate
					WHERE
						(currency_rate.COUNTRY_CODE = 'USA'))),
				2) AS TOTAL_REQUESTED_COST_USD,
				(SELECT DESCRIPTION FROM budget_category WHERE BUDGET_CATEGORY_CODE = t26.BUDGET_CATEGORY_CODE) AS BUDGET_CATEGORY,
		        (SELECT DESCRIPTION FROM cost_element WHERE COST_ELEMENT = t26.COST_ELEMENT) AS COST_ELEMENT,
			     t26.LINE_ITEM_COST AS LINE_ITEM_COST
                  FROM budget_header t6
			 LEFT JOIN budget_period t25 ON (t6.BUDGET_HEADER_ID = t25.BUDGET_HEADER_ID)
	         LEFT JOIN budget_detail t26 ON (t25.BUDGET_PERIOD_ID = t26.BUDGET_PERIOD_ID)
              WHERE (t6.IS_FINAL_BUDGET = 'Y'
										  OR
										  (t6.IS_LATEST_VERSION = 'Y' AND NOT EXISTS (SELECT 1 FROM BUDGET_HEADER WHERE PROPOSAL_ID = t6.PROPOSAL_ID AND IS_FINAL_BUDGET = 'Y'))
					)
     ) bd	 ON 	(bd.PROPOSAL_ID = t1.PROPOSAL_ID )
	JOIN eps_proposal_persons t8 ON (t1.PROPOSAL_ID = t8.PROPOSAL_ID )
	LEFT JOIN (SELECT
				s1.PROPOSAL_ID AS PROPOSAL_ID,
					s1.SPECIAL_REVIEW_CODE AS SPECIAL_REVIEW_CODE,
					s1.APPROVAL_TYPE_CODE AS SPR_APPROVAL_TYPE_CODE,
					s1.PROTOCOL_NUMBER AS SPR_PROTOCOL_NUMBER,
					s1.APPLICATION_DATE AS SPR_APPLICATION_DATE,
					s1.APPROVAL_DATE AS SPR_APPROVAL_DATE,
					s1.EXPIRATION_DATE AS SPR_EXPIRATION_DATE
			FROM
				eps_proposal_special_review s1
			WHERE
				s1.PROPOSAL_SPECIAL_REVIEW_ID IN (SELECT
						MAX(s2.PROPOSAL_SPECIAL_REVIEW_ID)
					FROM
						eps_proposal_special_review s2
					WHERE
						(s1.PROPOSAL_ID = s2.PROPOSAL_ID)
					GROUP BY s2.PROPOSAL_ID , s2.SPECIAL_REVIEW_CODE)) t11 ON (t11.PROPOSAL_ID = t1.PROPOSAL_ID)
	 LEFT JOIN sponsor t14 ON (t14.SPONSOR_CODE = t1.SPONSOR_CODE)
	 LEFT JOIN    (SELECT
					p1.PROPOSAL_ID AS PROPOSAL_ID,
					p1.PERSON_ID AS PERSON_ID,
					p1.ROLODEX_ID AS ROLODEX_ID,
					p1.FULL_NAME AS FULL_NAME,
					p1.PERCENTAGE_OF_EFFORT AS PERCENTAGE_OF_EFFORT,
					p1.DESIGNATION AS DESIGNATION,
					IFNULL((SELECT EMAIL_ADDRESS FROM PERSON WHERE PERSON_ID = P1.PERSON_ID),
						   (SELECT EMAIL_ADDRESS FROM ROLODEX WHERE ROLODEX_ID = P1.ROLODEX_ID)
						  ) AS FACULTY_EMAIL_ADDRESS
			FROM
				eps_proposal_persons p1
			WHERE PI_FLAG = 'Y'
			GROUP BY p1.PROPOSAL_ID) t19 ON (t19.PROPOSAL_ID = t1.PROPOSAL_ID)
	 LEFT JOIN eps_prop_person_role t20 ON (t20.PROP_PERSON_ROLE_ID = t8.PROP_PERSON_ROLE_ID)
	 LEFT JOIN proposal tp ON (tp.PROPOSAL_NUMBER = t1.IP_NUMBER AND tp.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE')
	 -- LEFT JOIN award_funding_proposals t22 ON (t22.PROPOSAL_ID =tp.PROPOSAL_ID)
	 -- LEFT JOIN award_master_dataset_rt t23 ON (t23.AWARD_ID = t22.AWARD_ID)
	 -- LEFT JOIN budget_period t25 ON (t6.BUDGET_HEADER_ID = t25.BUDGET_HEADER_ID)
	-- LEFT JOIN budget_detail t26 ON (t25.BUDGET_PERIOD_ID = t26.BUDGET_PERIOD_ID)
	 LEFT JOIN custom_data_report_rt cd ON (cd.MODULE_ITEM_KEY = t1.PROPOSAL_ID AND cd.MODULE_ITEM_CODE = 3)
	 LEFT JOIN (SELECT
            r1.PROPOSAL_ID AS PROPOSAL_ID,
                CONCAT(GROUP_CONCAT(CONCAT('{', r1.RESEARCH_RANK, '| ', r2.DESCRIPTION, IFNULL(CONCAT('| ', r3.DESCRIPTION), ''), '}')
                    SEPARATOR ',')) AS VERTICAL_AREA
        FROM
            ((eps_proposal_resrch_areas r1
        LEFT JOIN research_type_area r2 ON (((r2.RESRCH_TYPE_AREA_CODE = r1.RESRCH_TYPE_AREA_CODE)
            AND (r2.RESRCH_TYPE_CODE = 4))))
        LEFT JOIN research_type_sub_area r3 ON ((r1.RESRCH_TYPE_SUB_AREA_CODE = r3.RESRCH_TYPE_SUB_AREA_CODE)))
        GROUP BY r1.PROPOSAL_ID) t50 ON ((t1.PROPOSAL_ID = t50.PROPOSAL_ID))
	  LEFT JOIN (SELECT
            r1.PROPOSAL_ID AS PROPOSAL_ID,
                CONCAT(GROUP_CONCAT(CONCAT('{', r1.RESEARCH_RANK, '| ', r2.DESCRIPTION, IFNULL(CONCAT('| ', r3.DESCRIPTION), ''), '}')
                    SEPARATOR ',')) AS HORIZONTAL_AREA
        FROM
            ((eps_proposal_resrch_areas r1
        LEFT JOIN research_type_area r2 ON (((r2.RESRCH_TYPE_AREA_CODE = r1.RESRCH_TYPE_AREA_CODE)
            AND (r2.RESRCH_TYPE_CODE = 3))))
        LEFT JOIN research_type_sub_area r3 ON ((r1.RESRCH_TYPE_SUB_AREA_CODE = r3.RESRCH_TYPE_SUB_AREA_CODE)))
        GROUP BY r1.PROPOSAL_ID) t51 ON ((t1.PROPOSAL_ID = t51.PROPOSAL_ID))
	 WHERE ((t1.DOCUMENT_STATUS_CODE <> '3')
				OR (t1.DOCUMENT_STATUS_CODE IS NULL))
	);
	TRUNCATE TABLE PROP_AWD_DETAILS_TAB;
    INSERT INTO PROP_AWD_DETAILS_TAB
        (
		  IP_PROPOSAL_ID ,
		  AWARD_TITLE,
		  AWARD_KEY_PERSON_NAME,
		  AWARD_KEY_PERSON_ID ,
		  AWARD_TYPE,
		  AWARD_ACCOUNT_TYPE,
		  AWARD_STATUS ,
		  AWARD_SPONSOR_NAME,
		  AWARD_SPONSOR_TYPE ,
		  AWARD_SPONSOR_AWARD_NUMBER ,
		  AWARD_LEAD_UNIT_NUMBER,
		  AWARD_LEAD_UNIT_NAME,
		  AWARD_EFFECTIVE_DATE,
		  AWARD_FINAL_EXPIRATION_DATE,
		  AWARD_DURATION,
		  AWARD_NUMBER,
		  AWARD_ACCOUNT_NUMBER,
		  ANTICIPATED_TOTAL_AMOUNT ,
		  AMOUNT_OBLIGATED_TO_DATE ,
		  AWARD_ID ,
		  AWARD_PERCENTAGE_OF_EFFORT ,
		  AWARD_PRIME_SPONSOR_NAME,
		  AWARD_PI_NAME,
		  AWARD_KEY_PERSON_ROLE,
		  AWARD_KEY_PERSON_DEPT,
		  AWARD_KEY_PERSON_EMAIL,
		  ACCOUNT_TYPE,
		  AWARD_CREATE_DATE ,
		  AWARD_NOTICE_DATE ,
		  BEGIN_DATE
		)
		(SELECT  DISTINCT AFP.PROPOSAL_ID AS IP_PROPOSAL_ID,
				t23.TITLE AS AWARD_TITLE,
				t23.KEY_PERSON_NAME AS AWARD_KEY_PERSON_NAME,
				t23.KEY_PERSON_ID AS AWARD_KEY_PERSON_ID,
				t23.AWARD_TYPE AS AWARD_TYPE,
				t23.ACCOUNT_TYPE AS AWARD_ACCOUNT_TYPE,
				t23.AWARD_STATUS AS AWARD_STATUS,
				t23.SPONSOR_NAME AS AWARD_SPONSOR_NAME,
				t23.SPONSOR_TYPE AS AWARD_SPONSOR_TYPE,
				t23.SPONSOR_AWARD_NUMBER AS AWARD_SPONSOR_AWARD_NUMBER,
				t23.LEAD_UNIT_NUMBER AS AWARD_LEAD_UNIT_NUMBER,
				t23.unit_name AS AWARD_LEAD_UNIT_NAME,
				t23.AWARD_EFFECTIVE_DATE AS AWARD_EFFECTIVE_DATE,
				t23.FINAL_EXPIRATION_DATE AS AWARD_FINAL_EXPIRATION_DATE,
				t23.DURATION AS AWARD_DURATION,
				t23.AWARD_NUMBER AS AWARD_NUMBER,
				t23.ACCOUNT_NUMBER AS AWARD_ACCOUNT_NUMBER,
				t23.ANTICIPATED_TOTAL_AMOUNT AS ANTICIPATED_TOTAL_AMOUNT,
				t23.AMOUNT_OBLIGATED_TO_DATE AS AMOUNT_OBLIGATED_TO_DATE,
				t23.AWARD_ID AS AWARD_ID,
				t23.PERCENTAGE_OF_EFFORT AS AWARD_PERCENTAGE_OF_EFFORT,
				t23.PRIME_SPONSOR_NAME AS AWARD_PRIME_SPONSOR_NAME,
				t23.PI_NAME AS AWARD_PI_NAME,
				t23.PERSON_ROLE AS AWARD_KEY_PERSON_ROLE,
				IFNULL(t23.KEY_PERSON_DEPARTMENT,
						t23.KEY_PERSON_ORGANIZATION) AS AWARD_KEY_PERSON_DEPT,
				t23.KEY_PERSON_EMAIL AS AWARD_KEY_PERSON_EMAIL,
				t23.ACCOUNT_TYPE AS ACCOUNT_TYPE,
				t23.AWARD_CREATE_TIMESTAMP AS AWARD_CREATE_DATE,
				t23.AWARD_EFFECTIVE_DATE AS AWARD_NOTICE_DATE,
				t23.BEGIN_DATE
			FROM AWARD_FUNDING_PROPOSALS  AFP,
			  AWARD_MASTER_DATASET_RT T23 	-- ON (T23.AWARD_ID = AFP.AWARD_ID)
			WHERE AFP.PROPOSAL_ID IN (SELECT  DISTINCT IP_PROPOSAL_ID FROM PROP_DETAILS_TAB	WHERE IP_PROPOSAL_ID IS NOT NULL
									  )
			 -- AND (SELECT AWARD_SEQUENCE_STATUS FROM AWARD WHERE AWARD_ID = AFP.AWARD_ID) = 'ACTIVE'
			  AND T23.AWARD_ID = AFP.AWARD_ID
		);
END
$$
DELIMITER ;
