DELIMITER $$
CREATE  PROCEDURE `MIG_PERSON_DATA`(IN AV_TYPE VARCHAR(10))
BEGIN
    DECLARE NOT_FOUND INT DEFAULT 0;
    DECLARE LS_QUERY LONGTEXT;
    DECLARE LS_ERROR_MSG VARCHAR(4000) DEFAULT NULL;
    DECLARE LS_TABLE_NAMES VARCHAR(255);
	DECLARE LS_COLUMN_NAMES VARCHAR(255);
	DECLARE LS_COLUMN_NAMES_DATA VARCHAR(255);
	DECLARE LS_OLD_PERSON_ID VARCHAR(255);
	DECLARE LS_NEW_PERSON_ID VARCHAR(255);
    DECLARE SEL_UPDATE CURSOR FOR
    SELECT CONCAT(
    'UPDATE ', TABLE_NAMES, ' AG SET AG.', COLUMN_NAMES, ' = (SELECT NEW_PERSON_ID FROM MIG_PERSON_DETAILS WHERE OLD_PERSON_ID = AG.', COLUMN_NAMES, ')
    WHERE AG.', COLUMN_NAMES, ' IN (SELECT OLD_PERSON_ID FROM MIG_PERSON_DETAILS);'
		) AS UPDATE_QUERY,TABLE_NAMES,COLUMN_NAMES
	FROM MIG_PERSON_MATRIX WHERE (MIGRATION_STATUS IS NULL OR MIGRATION_STATUS = 'FAILED' OR MIGRATION_STATUS = 'ERROR')
	AND (NEW_PERSON_ID IS NOT NULL AND PERSON_ID IS NOT NULL)
	GROUP BY TABLE_NAMES, COLUMN_NAMES;
    DECLARE SEL_REVERT CURSOR FOR
    SELECT CONCAT(
    'UPDATE ', TABLE_NAMES, ' AG SET AG.', COLUMN_NAMES, ' = (SELECT OLD_PERSON_ID FROM MIG_PERSON_DETAILS WHERE NEW_PERSON_ID = AG.', COLUMN_NAMES, ')
    WHERE AG.', COLUMN_NAMES, ' IN (SELECT NEW_PERSON_ID FROM MIG_PERSON_DETAILS);'
		) AS UPDATE_QUERY,TABLE_NAMES,COLUMN_NAMES
	FROM MIG_PERSON_MATRIX WHERE  NEW_PERSON_ID IS NOT NULL
	GROUP BY TABLE_NAMES, COLUMN_NAMES;
	DECLARE SEL_TAB_DATA CURSOR FOR
	SELECT COLUMN_NAMES,PERSON_ID,NEW_PERSON_ID FROM MIG_PERSON_MATRIX WHERE TABLE_NAMES = 'PROP_DETAILS_TAB';
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1
            @sqlstate = RETURNED_SQLSTATE,
            @errno = MYSQL_ERRNO,
            @msg = MESSAGE_TEXT;
        SET LS_ERROR_MSG = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
        SET SQL_SAFE_UPDATES = 0;
        UPDATE MIG_PERSON_MATRIX SET MIGRATION_STATUS = 'ERROR' WHERE TABLE_NAMES = LS_TABLE_NAMES AND COLUMN_NAMES = LS_COLUMN_NAMES AND NEW_PERSON_ID IS NOT NULL;
        SET SQL_SAFE_UPDATES = 1;
        SELECT 'ERROR' AS MIGRATION_STATUS, LS_ERROR_MSG AS ERROR_MSG;
    END;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
    IF AV_TYPE = 'UPDATE' THEN
    SET SESSION group_concat_max_len = 4294967295;
        OPEN SEL_UPDATE;
        UPDATE_LOOP: LOOP
            FETCH SEL_UPDATE INTO LS_QUERY,LS_TABLE_NAMES,LS_COLUMN_NAMES;
            IF NOT_FOUND = 1 THEN
                LEAVE UPDATE_LOOP;
            END IF;
			IF LOWER(LS_TABLE_NAMES) = 'prop_details_tab' THEN
			SET LS_QUERY = NULL;
			        OPEN SEL_TAB_DATA;
					SEL_TAB_DATA: LOOP
					SET NOT_FOUND = 0;
					FETCH SEL_TAB_DATA INTO LS_COLUMN_NAMES_DATA,LS_OLD_PERSON_ID,LS_NEW_PERSON_ID;
					IF NOT_FOUND = 1 THEN
						LEAVE SEL_TAB_DATA;
					END IF;
					SET LS_QUERY = CONCAT(' UPDATE PROP_DETAILS_TAB SET ',LS_COLUMN_NAMES_DATA,' = ''',LS_NEW_PERSON_ID,''' WHERE ',LS_COLUMN_NAMES_DATA,' = ''',LS_OLD_PERSON_ID,''';');
					SET SQL_SAFE_UPDATES = 0;
					SET FOREIGN_KEY_CHECKS = 0;
					SET @QUERY_STATEMENT = LS_QUERY;
					PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
					EXECUTE EXECUTABLE_STATEMENT;
					DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
					COMMIT;
					UPDATE MIG_PERSON_MATRIX SET MIGRATION_STATUS = 'SUCCESS' WHERE TABLE_NAMES = LS_TABLE_NAMES AND COLUMN_NAMES = LS_COLUMN_NAMES AND NEW_PERSON_ID IS NOT NULL;
					SET FOREIGN_KEY_CHECKS = 1;
					SET SQL_SAFE_UPDATES = 1;
					END LOOP;
					CLOSE SEL_TAB_DATA;
			ELSE
					SET SQL_SAFE_UPDATES = 0;
					SET FOREIGN_KEY_CHECKS = 0;
					SET @QUERY_STATEMENT = LS_QUERY;
					PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
					EXECUTE EXECUTABLE_STATEMENT;
					DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
					COMMIT;
					UPDATE MIG_PERSON_MATRIX SET MIGRATION_STATUS = 'SUCCESS' WHERE TABLE_NAMES = LS_TABLE_NAMES AND COLUMN_NAMES = LS_COLUMN_NAMES AND NEW_PERSON_ID IS NOT NULL;
					SET FOREIGN_KEY_CHECKS = 1;
					SET SQL_SAFE_UPDATES = 1;
			END IF;
        END LOOP;
        CLOSE SEL_UPDATE;
		CALL MIG_PERSON_VALIDATION('AFTER');
    ELSEIF AV_TYPE = 'REVERT' THEN
    SET SESSION group_concat_max_len = 4294967295;
        OPEN SEL_REVERT;
        REVERT_LOOP: LOOP
            FETCH SEL_REVERT INTO LS_QUERY,LS_TABLE_NAMES,LS_COLUMN_NAMES;
            IF NOT_FOUND = 1 THEN
                LEAVE REVERT_LOOP;
            END IF;
            SET SQL_SAFE_UPDATES = 0;
            SET FOREIGN_KEY_CHECKS = 0;
            SET @QUERY_STATEMENT = LS_QUERY;
            PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
            EXECUTE EXECUTABLE_STATEMENT;
            DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
			SET SQL_SAFE_UPDATES = 0;
            UPDATE MIG_PERSON_MATRIX SET MIGRATION_STATUS = NULL WHERE TABLE_NAMES = LS_TABLE_NAMES AND COLUMN_NAMES = LS_COLUMN_NAMES AND NEW_PERSON_ID IS NOT NULL;
        END LOOP;
        CLOSE SEL_REVERT;
		SET SQL_SAFE_UPDATES = 0;
        UPDATE MIG_PERSON_MATRIX SET AFTER_OLD_PERSON_CNT = 0,AFTER_NEW_PERSON_CNT = 0;
		SET SQL_SAFE_UPDATES = 1;
    END IF;
    SELECT 'SUCCESS' AS MIGRATION_STATUS, LS_ERROR_MSG AS ERROR_MSG;
END
$$
DELIMITER ;
