DELIMITER $$
CREATE  PROCEDURE `MIGRATION_MANPOWER_WORKDAY_RESOURCE`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE LS_LATEST_EXPENSE_DATE	 VARCHAR(35);
DECLARE LS_RESOURCE_EXISTS_FOR_WBS_NUMBER   INT (3);
DECLARE CURSOR_EXPENSE_AMOUNT CURSOR FOR
	SELECT INTERNAL_ORDER_CODE, TOTAL_EXPENSE_AMOUNT FROM AWARD_EXPENSE_DETAILS WHERE INTERNAL_ORDER_CODE LIKE '%EOM%';
SET LS_RESOURCE_EXISTS_FOR_WBS_NUMBER = 0;
SET LS_LATEST_EXPENSE_DATE = NULL;
SELECT DATE_FORMAT(MAX(UPDATE_TIMESTAMP), "%d %M %Y") INTO LS_LATEST_EXPENSE_DATE FROM AWARD_EXPENSE_DETAILS;
SELECT COUNT(1) INTO LS_RESOURCE_EXISTS_FOR_WBS_NUMBER FROM MANPOWER_WORKDAY_RESOURCE
WHERE POSITION_ID like 'Actual EOM Exp as at%';
IF LS_RESOURCE_EXISTS_FOR_WBS_NUMBER > 0 THEN
    DELETE FROM MANPOWER_WORKDAY_RESOURCE WHERE POSITION_ID like 'Actual EOM Exp as at%';
END IF;
OPEN CURSOR_EXPENSE_AMOUNT;
	CURSOR_LOOP: LOOP BEGIN
	DECLARE LS_WBS_NUMBER				        VARCHAR(22);
    DECLARE LS_EXPENSE_AMOUNT					DECIMAL(22,2);
	DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
	FETCH CURSOR_EXPENSE_AMOUNT INTO LS_WBS_NUMBER, LS_EXPENSE_AMOUNT;
	IF DONE THEN
		LEAVE CURSOR_LOOP;
	END IF;
    INSERT INTO MANPOWER_WORKDAY_RESOURCE(
        WBS_NUMBER,
        COMMITTED_COST,
        POSITION_ID,
        CREATE_TIMESTAMP,
        CREATE_USER,
        UPDATE_USER,
        UPDATE_TIMESTAMP
    ) VALUES (
        LS_WBS_NUMBER,
        LS_EXPENSE_AMOUNT,
        CONCAT('Actual EOM Exp as at ',LS_LATEST_EXPENSE_DATE),
        NOW(),
        'quickstart',
        'quickstart',
        NOW()
    );
END;
END LOOP;
CLOSE CURSOR_EXPENSE_AMOUNT;
END
$$
DELIMITER ;
