DELIMITER $$
CREATE PROCEDURE `UPDATE_AWARD_EXP_UNIQUE_VALUES`(
IN AV_TYPE INT)
BEGIN
DECLARE LI_FLAG INT;
DECLARE LI_VENDOR_NAME 	varchar(300);
DECLARE LI_VENDOR_CODE 	varchar(50);
DECLARE LI_PREDECESSOR_DOC_NUMBER varchar(50);
DECLARE LI_PO_DATE DATETIME;
DECLARE LI_BANK_CLEARING_DATE DATETIME;
DECLARE LI_DOCUMENT_NUMBER varchar(100);
DECLARE LI_ITEM_NUMBER varchar(5);
DECLARE LI_REFERENCE_DOCUMENT_CATEGORY varchar(3);
DECLARE LI_REFERENCE_ORG_UNIT varchar(10);
DECLARE LI_ACCT_ASSIGNMENT_NUMBER varchar(5);
DECLARE LI_SCHEDULE_LINE_NUMBER varchar(4);
DECLARE LI_CONDITION_COUNTER varchar(5);
DECLARE LI_REFERENCE_PROCEDURE varchar(5);
DECLARE LI_DOCUMENT_NUMBER_FM_LINE_ITEM varchar(10);
DECLARE LI_NUMBER_OF_POST_FM_LINE_ITEM varchar(3);
DECLARE LI_COMPANY_CODE varchar(4);
DECLARE LI_VALUE_TYPE varchar(2);
DECLARE LI_AMOUNT_TYPE varchar(4);
DECLARE LI_FISCAL_YEAR varchar(4);
DECLARE LI_TRANSACTION_NUMBER varchar(40);
DECLARE LI_AWARD_EXPENSE_TRANS_ID int;
		BEGIN
		DECLARE DONE3 INT DEFAULT FALSE;
		DECLARE CUR_SUMMARY_DATA CURSOR FOR
		select t2.AWARD_EXPENSE_TRANS_ID, t1.BANK_CLEARING_DATE,t1.PO_DATE,t1.PREDECESSOR_DOC_NUMBER,t1.VENDOR_CODE,t1.VENDOR_NAME
	from award_expense_transactions_update_june t1
inner join award_expense_transactions t2
on t1.DOCUMENT_NUMBER = t2.DOCUMENT_NUMBER
and t1.ITEM_NUMBER = t2.ITEM_NUMBER
and t1.REFERENCE_DOCUMENT_CATEGORY = t2.REFERENCE_DOCUMENT_CATEGORY
and t1.REFERENCE_ORG_UNIT = t2.REFERENCE_ORG_UNIT
and t1.ACCT_ASSIGNMENT_NUMBER = t2.ACCT_ASSIGNMENT_NUMBER
and t1.SCHEDULE_LINE_NUMBER = t2.SCHEDULE_LINE_NUMBER
and t1.CONDITION_COUNTER = t2.CONDITION_COUNTER
and t1.REFERENCE_PROCEDURE = t2.REFERENCE_PROCEDURE
and t1.DOCUMENT_NUMBER_FM_LINE_ITEM = t2.DOCUMENT_NUMBER_FM_LINE_ITEM
and t1.NUMBER_OF_POST_FM_LINE_ITEM = t2.NUMBER_OF_POST_FM_LINE_ITEM
and t1.COMPANY_CODE = t2.COMPANY_CODE
and t1.VALUE_TYPE = t2.VALUE_TYPE
and t1.AMOUNT_TYPE = t2.AMOUNT_TYPE
and t1.FISCAL_YEAR = t2.FISCAL_YEAR
and t1.TRANSACTION_NUMBER = t2.TRANSACTION_NUMBER;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
		OPEN CUR_SUMMARY_DATA;
		INSERT_LOOP3: LOOP
		FETCH CUR_SUMMARY_DATA INTO
		LI_AWARD_EXPENSE_TRANS_ID,LI_BANK_CLEARING_DATE, LI_PO_DATE,LI_PREDECESSOR_DOC_NUMBER,LI_VENDOR_CODE,LI_VENDOR_NAME		;
		IF DONE3 THEN
			LEAVE INSERT_LOOP3;
		END IF;
		UPDATE AWARD_EXPENSE_TRANSACTIONS SET FILE_ID = 0, BANK_CLEARING_DATE = LI_BANK_CLEARING_DATE,PO_DATE = LI_PO_DATE ,PREDECESSOR_DOC_NUMBER = LI_PREDECESSOR_DOC_NUMBER,VENDOR_CODE = LI_VENDOR_CODE,VENDOR_NAME = LI_VENDOR_NAME WHERE
	    AWARD_EXPENSE_TRANS_ID  = LI_AWARD_EXPENSE_TRANS_ID ;
		END LOOP;
		CLOSE CUR_SUMMARY_DATA;
		END;
       COMMIT;
 END
$$
DELIMITER ;
