DELIMITER $$
CREATE PROCEDURE `UPDATE_CUSTDATA`(AV_TYPE INT)
BEGIN
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT;
DECLARE LS_LOOKUP_ARGUMENT VARCHAR(1000);
DECLARE LS_DEFAULT_VALUE VARCHAR(1000);
DECLARE LS_VALUE VARCHAR(1000);
DECLARE LS_DESCRIPTION VARCHAR(1000);
DECLARE LS_TABLE_NAME VARCHAR(1000);
DECLARE LS_ID_COLUMN VARCHAR(1000);
DECLARE LI_CUSTOM_DATA_ID INT;
DECLARE LL_QUERY_STRING VARCHAR(2000);
DECLARE LL_VALUE VARCHAR(2000) default null;
DECLARE LL_DESCRIPTION VARCHAR (2000) default null;
DECLARE LI_COUNT INT;
DECLARE LS_FILE_TYPE VARCHAR(50);
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE UPDATE_CUSTDATA_CURSOR CURSOR FOR
		select T2.CUSTOM_DATA_ELEMENTS_ID,T2.LOOKUP_ARGUMENT,T2.DEFAULT_VALUE,T1.VALUE, T1.DESCRIPTION, T1.CUSTOM_DATA_ID
		from custom_data T1
			INNER JOIN CUSTOM_DATA_ELEMENTS T2 ON T1.CUSTOM_DATA_ELEMENTS_ID = T2.CUSTOM_DATA_ELEMENTS_ID
			WHERE T2.DATA_TYPE IN(6,7,8,9) and t1.value is not null and t1.value <> '' ;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO CUSTOM_UPDATE_ERROR_LOG(ERROR_MESSAGE,CUSTOM_DATA_ID)
			VALUES(CONCAT(LS_ERROR), CUSTOM_DATA_ID);
			COMMIT;
		END;
		OPEN UPDATE_CUSTDATA_CURSOR;
		UPDATE_CUSTDATA_CURSOR_LOOP : LOOP
				FETCH UPDATE_CUSTDATA_CURSOR INTO  LI_CUSTOM_DATA_ELEMENTS_ID, LS_LOOKUP_ARGUMENT, LS_DEFAULT_VALUE, LS_VALUE, LS_DESCRIPTION, LI_CUSTOM_DATA_ID;
				IF DONE1 THEN
					LEAVE UPDATE_CUSTDATA_CURSOR_LOOP;
				END IF;
				SET LL_VALUE = NULL;
				SET LL_DESCRIPTION = NULL;
		IF (LS_LOOKUP_ARGUMENT ='grantCodeName' AND LS_DEFAULT_VALUE = 'grantCode' AND  LS_VALUE IS NOT NULL AND LS_VALUE <> '') THEN
						SELECT COUNT(*) INTO LI_COUNT
						FROM SAP_GRANT_CODE
						WHERE (GRANT_CODE = LS_VALUE OR GRANT_CODE_NAME = LS_VALUE);
						IF LI_COUNT > 0 THEN
							SELECT GRANT_CODE,GRANT_CODE_NAME INTO LL_VALUE,LL_DESCRIPTION
							FROM SAP_GRANT_CODE
							WHERE (GRANT_CODE = LS_VALUE OR GRANT_CODE_NAME = LS_VALUE);
						END IF;
				IF IFNULL(TRIM(LL_VALUE),'')  <> '' AND IFNULL(TRIM(LL_DESCRIPTION),'')  <> '' THEN
					UPDATE CUSTOM_DATA SET TEMP_VALUE = LL_VALUE , TEMP_DESCRIPTION =LL_VALUE WHERE CUSTOM_DATA_ID = LI_CUSTOM_DATA_ID;
				END IF;
		END IF;
		IF (LS_LOOKUP_ARGUMENT ='unitName' AND LS_DEFAULT_VALUE = 'unitName' AND  LS_VALUE IS NOT NULL AND LS_VALUE <> '') THEN
						SELECT COUNT(*) INTO LI_COUNT
						FROM UNIT
						WHERE (UNIT_NUMBER = LS_VALUE OR UNIT_NAME = LS_VALUE);
						IF LI_COUNT > 0 THEN
							SELECT UNIT_NUMBER,UNIT_NAME INTO LL_VALUE,LL_DESCRIPTION
							FROM UNIT
							WHERE (UNIT_NUMBER = LS_VALUE OR UNIT_NAME = LS_VALUE);
						END IF;
				IF IFNULL(TRIM(LL_VALUE),'')  <> '' AND IFNULL(TRIM(LL_DESCRIPTION),'')  <> '' THEN
					UPDATE CUSTOM_DATA SET TEMP_VALUE = LL_VALUE , TEMP_DESCRIPTION =LL_DESCRIPTION WHERE CUSTOM_DATA_ID = LI_CUSTOM_DATA_ID;
				END IF;
		END IF;
		IF (LS_LOOKUP_ARGUMENT ='profitCenterName' AND LS_DEFAULT_VALUE = 'profitCenterCode' AND  LS_VALUE IS NOT NULL AND LS_VALUE <> '') THEN
						SELECT COUNT(*) INTO LI_COUNT
						FROM SAP_PROFIT_CENTER
						WHERE (PROFIT_CENTER_CODE = LS_VALUE OR PROFIT_CENTER_NAME = LS_VALUE);
						IF LI_COUNT > 0 THEN
							SELECT PROFIT_CENTER_CODE,PROFIT_CENTER_NAME INTO LL_VALUE,LL_DESCRIPTION
							FROM SAP_PROFIT_CENTER
							WHERE (PROFIT_CENTER_CODE = LS_VALUE OR PROFIT_CENTER_NAME = LS_VALUE);
						END IF;
				IF IFNULL(TRIM(LL_VALUE),'')  <> '' AND IFNULL(TRIM(LL_DESCRIPTION),'')  <> '' THEN
					UPDATE CUSTOM_DATA SET TEMP_VALUE = LL_VALUE , TEMP_DESCRIPTION =LL_VALUE WHERE CUSTOM_DATA_ID = LI_CUSTOM_DATA_ID;
				END IF;
		END IF;
		IF (LS_LOOKUP_ARGUMENT ='fundCenterName' AND LS_DEFAULT_VALUE = 'fundCenterCode' AND  LS_VALUE IS NOT NULL AND LS_VALUE <> '') THEN
						SELECT COUNT(*) INTO LI_COUNT
						FROM SAP_FUND_CENTER
						WHERE (FUND_CENTER_CODE = LS_VALUE OR FUND_CENTER_NAME = LS_VALUE);
						IF LI_COUNT > 0 THEN
							SELECT FUND_CENTER_CODE,FUND_CENTER_NAME INTO LL_VALUE,LL_DESCRIPTION
							FROM SAP_FUND_CENTER
							WHERE (FUND_CENTER_CODE = LS_VALUE OR FUND_CENTER_NAME = LS_VALUE);
						END IF;
				IF IFNULL(TRIM(LL_VALUE),'')  <> '' AND IFNULL(TRIM(LL_DESCRIPTION),'')  <> '' THEN
					UPDATE CUSTOM_DATA SET TEMP_VALUE = LL_VALUE , TEMP_DESCRIPTION =LL_VALUE WHERE CUSTOM_DATA_ID = LI_CUSTOM_DATA_ID;
				END IF;
		END IF;
		IF (LS_LOOKUP_ARGUMENT ='costCenterName' AND LS_DEFAULT_VALUE = 'costCenterCode' AND  LS_VALUE IS NOT NULL AND LS_VALUE <> '') THEN
						SELECT COUNT(*) INTO LI_COUNT
						FROM SAP_COST_CENTER
						WHERE (COST_CENTER_CODE = LS_VALUE OR COST_CENTER_NAME = LS_VALUE);
						IF LI_COUNT > 0 THEN
							SELECT COST_CENTER_CODE,COST_CENTER_NAME INTO LL_VALUE,LL_DESCRIPTION
							FROM SAP_COST_CENTER
							WHERE (COST_CENTER_CODE = LS_VALUE OR COST_CENTER_NAME = LS_VALUE);
						END IF;
				IF IFNULL(TRIM(LL_VALUE),'')  <> '' AND IFNULL(TRIM(LL_DESCRIPTION),'')  <> '' THEN
					UPDATE CUSTOM_DATA SET TEMP_VALUE = LL_VALUE , TEMP_DESCRIPTION =LL_VALUE WHERE CUSTOM_DATA_ID = LI_CUSTOM_DATA_ID;
				END IF;
		END IF;
		END LOOP;
		CLOSE UPDATE_CUSTDATA_CURSOR;
END;
SELECT 1  AS RESULT;
END
$$
DELIMITER ;
