DELIMITER $$
CREATE  PROCEDURE `UPDATE_CLAIM_WITH_REVENUE_DOC_DATA`()
BEGIN
DECLARE LS_CLAIM_NUMBER VARCHAR(12);
DECLARE LD_DOCUMENT_DATE	datetime;
DECLARE LI_FLAG INT;
    SET SQL_SAFE_UPDATES = 0;
		SELECT count(1) into LI_FLAG FROM CLAIM_INVOICE_LOG T1
		INNER JOIN CLAIM T3 ON T1.CLAIM_ID = T3.CLAIM_ID
		INNER JOIN AWARD_REVENUE_TRANSACTIONS T2 ON T1.CLAIM_NUMBER = T2.TRANSACTION_REFERENCE_NUMBER AND
		T2.REFERENCE_DOCUMENT_NUMBER = T1.OUTPUT_DOCUMENT_NUMBER
		WHERE T3.CLAIM_STATUS_CODE = '10' and t3.DOCUMENT_DATE <> t2.DOCUMENT_DATE AND T1.CLAIM_INVOICE_LOG_ID IN (SELECT MAX(CLAIM_INVOICE_LOG_ID) FROM CLAIM_INVOICE_LOG WHERE STATUS = 'S' AND TYPE_CODE = 2 and claim_number = t1.claim_number);
	IF LI_FLAG > 0 THEN
		BEGIN
		DECLARE DONE3 INT DEFAULT FALSE;
		DECLARE CUR_SUMMARY_DATA CURSOR FOR
		SELECT DISTINCT T3.CLAIM_NUMBER,t2.DOCUMENT_DATE FROM CLAIM_INVOICE_LOG T1
		INNER JOIN CLAIM T3 ON T1.CLAIM_ID = T3.CLAIM_ID
		INNER JOIN AWARD_REVENUE_TRANSACTIONS T2 ON T1.CLAIM_NUMBER = T2.TRANSACTION_REFERENCE_NUMBER AND
		T2.REFERENCE_DOCUMENT_NUMBER = T1.OUTPUT_DOCUMENT_NUMBER
		WHERE T3.CLAIM_STATUS_CODE = '10' and t3.DOCUMENT_DATE <> t2.DOCUMENT_DATE AND T1.CLAIM_INVOICE_LOG_ID IN (SELECT MAX(CLAIM_INVOICE_LOG_ID) FROM CLAIM_INVOICE_LOG WHERE STATUS = 'S' AND TYPE_CODE = 2 and claim_number = t1.claim_number);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
		OPEN CUR_SUMMARY_DATA;
		INSERT_LOOP3: LOOP
		FETCH CUR_SUMMARY_DATA INTO
		 LS_CLAIM_NUMBER,LD_DOCUMENT_DATE;
		IF DONE3 THEN
			LEAVE INSERT_LOOP3;
		END IF;
		UPDATE CLAIM SET  DOCUMENT_DATE = LD_DOCUMENT_DATE WHERE CLAIM_NUMBER = LS_CLAIM_NUMBER;
		END LOOP;
		CLOSE CUR_SUMMARY_DATA;
		END;
	END IF;
 END
$$
DELIMITER ;
