

CREATE FUNCTION `FN_CHK_OPA_PERSON_IS_FACULTY`( 
AV_PERSON_ID  varchar(22)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN

DECLARE LS_IS_FACULTY VARCHAR(1);


	SELECT IS_FACULTY INTO LS_IS_FACULTY 
    FROM OPA_PERSON
	WHERE PERSON_ID = AV_PERSON_ID;
    
    IF LS_IS_FACULTY = 'Y' THEN
    
		RETURN 'TRUE';
	
    ELSE 
    
		RETURN 'FALSE';
    
    END IF;

END
