

CREATE FUNCTION `FN_CHK_DISCL_SYNC_FLAG_REQ_IN_IP`(
    AV_PROJECT_NUMBER  VARCHAR(12),
    AV_PROJECT_STATUS_CODE VARCHAR(12),
    AV_SPONSOR_CODE VARCHAR(10),
    AV_PRIME_SPONSOR_CODE VARCHAR(10),
    AV_ATTRIBUTE_1_VALUE VARCHAR(10),
    AV_LINKED_AWARD_NUMBER VARCHAR(12),
    AV_LINKED_PROPOSAL_IDS VARCHAR(200)
) RETURNS tinyint
    DETERMINISTIC
BEGIN
/*
 *Currently, for MIT, the Master disclosure only displays IP and Award information, 
 *so the synchronization check for development proposals has not been implemented.
 *This functionality can be implemented for other universities if needed.
*/
     
DECLARE LS_COUNT INT DEFAULT '0';

  SELECT COUNT(*) INTO LS_COUNT FROM COI_INT_STAGE_PROPOSAL WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER;
  
   IF LS_COUNT = 0 THEN
    RETURN 1;
   END IF; 
  
 
 SELECT COUNT(*) INTO LS_COUNT FROM COI_INT_STAGE_PROPOSAL
 WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER
 AND (PROJECT_STATUS_CODE != AV_PROJECT_STATUS_CODE OR SPONSOR_CODE != AV_SPONSOR_CODE)
 OR (SPONSOR_CODE IS NOT NULL AND AV_SPONSOR_CODE IS NULL)
 OR (PROJECT_STATUS_CODE IS NOT NULL AND AV_PROJECT_STATUS_CODE IS NULL);

        IF LS_COUNT > 0 THEN
            RETURN 1;
		END IF;
  
    
        -- Check if prime sponsor code matches
 SELECT COUNT(*) INTO LS_COUNT FROM COI_INT_STAGE_PROPOSAL
    WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER
 AND (PRIME_SPONSOR_CODE IS NOT NULL AND PRIME_SPONSOR_CODE != AV_PRIME_SPONSOR_CODE
 OR (PRIME_SPONSOR_CODE IS NOT NULL  AND AV_PRIME_SPONSOR_CODE IS NULL)
 OR (PRIME_SPONSOR_CODE IS NULL  AND AV_PRIME_SPONSOR_CODE IS NOT NULL));

        IF LS_COUNT > 0 THEN
            RETURN 1;
        END IF;

-- Check if PCK flag data matches

SELECT COUNT(*) INTO LS_COUNT FROM COI_INT_STAGE_PROPOSAL
    WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER
 AND (ATTRIBUTE_1_VALUE IS NOT NULL AND ATTRIBUTE_1_VALUE != AV_ATTRIBUTE_1_VALUE
 OR (ATTRIBUTE_1_VALUE IS NOT NULL  AND AV_ATTRIBUTE_1_VALUE IS NULL)
 OR (ATTRIBUTE_1_VALUE IS NULL  AND AV_ATTRIBUTE_1_VALUE IS NOT NULL));

        IF LS_COUNT > 0 THEN
            RETURN 1;
        END IF;
        
  -- Check if linked award number matches
 SELECT COUNT(*) INTO LS_COUNT
    FROM COI_INT_STAGE_PROPOSAL
    WHERE PROJECT_NUMBER = AV_PROJECT_NUMBER
 AND (LINKED_AWARD_PROJECT_NUMBER IS NOT NULL AND LINKED_AWARD_PROJECT_NUMBER != AV_LINKED_AWARD_NUMBER
 OR (LINKED_AWARD_PROJECT_NUMBER IS NOT NULL AND AV_LINKED_AWARD_NUMBER IS NULL)
 OR (LINKED_AWARD_PROJECT_NUMBER IS NULL AND AV_LINKED_AWARD_NUMBER IS NOT NULL));

  IF LS_COUNT > 0 THEN
            RETURN 1;
        END IF;
  
 
RETURN 0;

END
