

CREATE FUNCTION `FN_GET_OVERALL_PRJT_DISCL_RVW_STATUS`(PROJECT_NUMBER INT) RETURNS varchar(50) CHARSET latin1
    DETERMINISTIC
BEGIN
    DECLARE RESULT_STATUS VARCHAR(50);
        IF NOT EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
           
    )  THEN
        RETURN NULL;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
          AND DISCLOSURE_STATUS != 'DISCLOSURE_PENDING'
           
    ) THEN
        RETURN 'DISCLOSURE_PENDING';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_REVIEW_NA')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL         
		 
    ) THEN
        
        IF EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NULL
          AND DISCLOSURE_STATUS = 'DISCLOSURE_PENDING'
           
		) THEN
         RETURN NULL;
         
         ELSE 
         RETURN 'DISCLOSURE_NA_REVIEW';
         END IF;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
    )  THEN
        RETURN 'DISCLOSURE_NOT_REQUIRED';
    END IF;



    IF EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IN ('WITHDRAWN', 'SUBMITTED', 'PENDING', 
                                    'REVIEW IN PROGRESS', 'REVIEW ASSIGNED', 'RETURNED',
                                    'ASSIGNED REVIEW COMPLETED')
           AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
           
    )  THEN
        RETURN 'DISCLOSURE_PENDING';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureProjects
        WHERE PROJECT_ID = PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('COMPLETED', 
                                        'DISCLOSURE_REVIEW_NA', 
                                        'DISCLOSURE_NOT_REQUIRED')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
         )  THEN
        RETURN 'DISCLOSURE_COMPLETED';
    END IF;

    RETURN NULL;
END
