

CREATE FUNCTION `FN_GET_OVRAL_AWD_PRJT_DISCL_RVW_STATUS`(AV_PROJECT_NUMBER INT) RETURNS varchar(50) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    DETERMINISTIC
BEGIN
    DECLARE RESULT_STATUS VARCHAR(50);
        DECLARE LI_COUNT INT DEFAULT 0;
    DECLARE LI_DISC_COUNT INT DEFAULT 0;
    
SELECT COUNT(1) INTO LI_COUNT  FROM COI_INT_STAGE_AWARD_PERSON T1 WHERE T1.PROJECT_NUMBER = (SELECT PROJECT_NUMBER FROM coi_int_stage_award WHERE PROJECT_ID = AV_PROJECT_NUMBER )
AND (T1.KEY_PERSON_ID IN ( SELECT KEY_PERSON_ID FROM COI_INT_STAGE_AWARD_PERSON WHERE 
DISCLOSURE_REQUIRED_FLAG = 'REQUIRED' AND PROJECT_NUMBER = T1.PROJECT_NUMBER)
OR 
T1.KEY_PERSON_ID IN
( SELECT KEY_PERSON_ID FROM COI_INT_STAGE_AWARD_PERSON WHERE 
DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED' AND PROJECT_NUMBER = T1.PROJECT_NUMBER AND ATTRIBUTE_1_VALUE = 'N'  AND ATTRIBUTE_1_VALUE = 'N'));

SELECT COUNT(1) INTO LI_DISC_COUNT FROM DisclosureAwardProjects WHERE PROJECT_ID = AV_PROJECT_NUMBER AND DISCLOSURE_ID IS NOT NULL;

        IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
           
    ) AND  LI_COUNT = LI_DISC_COUNT THEN
        RETURN NULL;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
          AND DISCLOSURE_STATUS != 'DISCLOSURE_PENDING'
           
    ) AND  LI_COUNT = LI_DISC_COUNT THEN
        RETURN 'DISCLOSURE_PENDING';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_REVIEW_NA')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
         
    )  THEN
        RETURN 'DISCLOSURE_REVIEW_NA';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('DISCLOSURE_NOT_REQUIRED')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
    ) THEN
        RETURN 'DISCLOSURE_NOT_REQUIRED';
    END IF;



    IF EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IN ('WITHDRAWN', 'SUBMITTED', 'PENDING', 
                                    'REVIEW IN PROGRESS', 'REVIEW ASSIGNED', 
                                    'ASSIGNED REVIEW COMPLETED')
           AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
           
    )AND  LI_COUNT = LI_DISC_COUNT THEN
        RETURN 'DISCLOSURE_PENDING';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('COMPLETED', 
                                        'DISCLOSURE_REVIEW_NA', 
                                        'DISCLOSURE_NOT_REQUIRED')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
         ) AND  LI_COUNT = LI_DISC_COUNT THEN
        RETURN 'DISCLOSURE_COMPLETED';
    END IF;
    
        IF NOT EXISTS (
        SELECT 1
        FROM DisclosureAwardProjects
        WHERE PROJECT_ID = AV_PROJECT_NUMBER
          AND PROJECT_DISCLOSURE_REVIEW_STATUS NOT IN ('COMPLETED')
          AND PROJECT_DISCLOSURE_REVIEW_STATUS IS NOT NULL
         ) AND  LI_COUNT = LI_DISC_COUNT THEN
        RETURN 'DISCLOSURE_COMPLETED';
    END IF;
    
IF LI_COUNT != LI_DISC_COUNT THEN
        RETURN 'NOT_YET_DISCLOSED';
    END IF;  

    RETURN NULL;
END
