-- `GET_RESEARCH_SUMMARY_AGREEMENT_COUNT`; 

CREATE PROCEDURE `GET_RESEARCH_SUMMARY_AGREEMENT_COUNT`(
AV_WIDGET 			VARCHAR(200),
AV_PERSON_ID 		VARCHAR(40),
AV_UNIT_NUMBER 		VARCHAR(8),
AV_CATEGORY_CODE 	VARCHAR(100),
AV_STATUS_CODE 		VARCHAR(100),
AV_START_DATE 		VARCHAR(30),
AV_END_DATE 		VARCHAR(30),
AV_DESCENT_FLAG 	VARCHAR(1)
)
BEGIN
DECLARE LS_DYN_SQL 				LONGTEXT;
DECLARE LS_UNIT_CONDITION 		LONGTEXT;
DECLARE LS_STATUS_CONDITION 	VARCHAR(600);
DECLARE LS_CATEGORY_CONDITION 	VARCHAR(600);
IF AV_START_DATE = '' THEN
    SET AV_START_DATE = CASE 
        WHEN MONTH(NOW()) >= 4 THEN CONCAT(DATE(CONCAT(YEAR(NOW()), '-04-01')), ' 00:00:00')
        ELSE CONCAT(DATE(CONCAT(YEAR(NOW()) - 1, '-04-01')), ' 00:00:00')
    END;
END IF;
IF AV_END_DATE = '' THEN
    SET AV_END_DATE = CASE 
        WHEN MONTH(NOW()) >= 4 THEN CONCAT(DATE(CONCAT(YEAR(NOW()) + 1, '-03-31')), ' 00:00:00')
        ELSE CONCAT(DATE(CONCAT(YEAR(NOW()), '-03-31')), ' 00:00:00')
    END;
END IF;
IF AV_UNIT_NUMBER <> '' THEN
	IF AV_DESCENT_FLAG = 'Y' THEN
		SET LS_UNIT_CONDITION = CONCAT(' AND T1.UNIT_NUMBER IN (SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER = ''',AV_UNIT_NUMBER,''')');
	ELSE
		SET LS_UNIT_CONDITION = CONCAT(' AND T1.UNIT_NUMBER = ''',AV_UNIT_NUMBER,'''');
	END IF;
ELSE 
	SET LS_UNIT_CONDITION = '';
END IF;
IF AV_CATEGORY_CODE IS NULL OR AV_CATEGORY_CODE = '' THEN
	SET LS_CATEGORY_CONDITION = (' T2.CATEGORY_CODE IN (SELECT CATEGORY_CODE FROM AGREEMENT_CATEGORY )');
ELSE
	SET LS_CATEGORY_CONDITION = CONCAT(' T2.CATEGORY_CODE IN (',AV_CATEGORY_CODE,')');
END IF;
IF AV_STATUS_CODE IS NULL OR AV_STATUS_CODE = '' THEN
	SET LS_STATUS_CONDITION = CONCAT(' AND T1.AGREEMENT_STATUS_CODE IN (''1'',''2'',''3'',''4'',''5'',''6'',''7'',''8'',''9'',''10'')');
ELSE
	SET LS_STATUS_CONDITION = CONCAT(' AND T1.AGREEMENT_STATUS_CODE IN (',AV_STATUS_CODE,')');
END IF;
IF AV_WIDGET = 'AGREEMENT_SUMMARY' THEN
	SET LS_DYN_SQL = CONCAT('WITH ACCESS_ADMIN_TMP AS (
		SELECT  UNIT_NUMBER
		FROM PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
		WHERE T1.DESCEND_FLAG = ''N'' 
		AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
		AND RIGHT_NAME IN (''VIEW_ALL_AGREEMENT'', ''MODIFY_ALL_AGREEMENT'', ''AGREEMENT_ADMINISTRATOR'')
		UNION
		SELECT CHILD_UNIT_NUMBER 
		FROM UNIT_WITH_CHILDREN 
		WHERE UNIT_NUMBER IN (
			SELECT  UNIT_NUMBER
			FROM PERSON_ROLES T1
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
			INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
			WHERE T1.DESCEND_FLAG = ''Y'' 
			AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
			AND RIGHT_NAME IN (''VIEW_ALL_AGREEMENT'', ''MODIFY_ALL_AGREEMENT'', ''AGREEMENT_ADMINISTRATOR'')
		)
	),
	PRINCIPAL_INVESTIGATOR AS (
		SELECT AGREEMENT_REQUEST_ID
		FROM AGREEMENT_PEOPLE 
		WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PEOPLE_TYPE_ID = 3
	),
	NEGOTIATOR AS (
		SELECT ASSOCIATED_PROJECT_ID
		FROM NEGOTIATION_ASSOCIATION T1
		INNER JOIN NEGOTIATION_LOCATION T2 ON T1.NEGOTIATION_ID = T2.NEGOTIATION_ID
		WHERE T2.ASSIGNEE_PERSON_ID = ''',AV_PERSON_ID,'''
	),
	ACCESS_ADMIN_GROUP_TMP AS (SELECT T1.AGREEMENT_REQUEST_ID 
							FROM AGREEMENT_HEADER T1
							LEFT JOIN ADMIN_GROUP T2 ON T1.ADMIN_GROUP_ID = T2.ADMIN_GROUP_ID
							WHERE T2.ROLE_ID IN (SELECT T3.ROLE_ID FROM ROLE_RIGHTS T3 
							LEFT JOIN RIGHTS T4 ON T3.RIGHT_ID = T4.RIGHT_ID
							LEFT JOIN PERSON_ROLES T5 ON T3.ROLE_ID = T5.ROLE_ID
							WHERE T5.PERSON_ID = ''',AV_PERSON_ID,''' AND T4.RIGHT_NAME = ''VIEW_ADMIN_GROUP_AGREEMENT'')),
	ACCESS_TMP AS (SELECT R1.AGREEMENT_REQUEST_ID
						FROM AGREEMENT_PEOPLE_ROLES R1
						INNER JOIN ROLE_RIGHTS R2 ON R1.ROLE_ID = R2.ROLE_ID
						INNER JOIN RIGHTS R3 ON R2.RIGHT_ID = R3.RIGHT_ID 
						WHERE R1.PERSON_ID = ''',AV_PERSON_ID,'''
						AND R3.RIGHT_NAME IN (''VIEW_ALL_AGREEMENT'',''MODIFY_ALL_AGREEMENT''))
	SELECT
		''TOTAL_RECORDS'' AS RECORD_TYPE,
		COALESCE(COUNT(T1.AGREEMENT_REQUEST_ID), 0) AS RECORD_COUNT,
		T2.DESCRIPTION AS CATEGORY_DESCRIPTION,
		T2.CATEGORY_CODE
	FROM AGREEMENT_CATEGORY T2
	LEFT JOIN AGREEMENT_HEADER T1 ON T1.CATEGORY_CODE = T2.CATEGORY_CODE'
	, LS_STATUS_CONDITION,
	' AND T1.UPDATE_TIMESTAMP BETWEEN ''',AV_START_DATE,''' AND ''',AV_END_DATE,'''
	AND (( EXISTS (SELECT 1 FROM ACCESS_ADMIN_TMP WHERE  UNIT_NUMBER = T1.UNIT_NUMBER)
		 OR EXISTS (SELECT 1 FROM PRINCIPAL_INVESTIGATOR WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		 OR EXISTS (SELECT 1 FROM NEGOTIATOR WHERE ASSOCIATED_PROJECT_ID = T1.AGREEMENT_REQUEST_ID)
         OR T1.REQUESTOR_PERSON_ID = ''',AV_PERSON_ID,'''
         OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID, '''
		 OR (EXISTS (SELECT 1
					FROM WORKFLOW T9
					INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
					WHERE T9.MODULE_CODE = 13 
                        AND T10.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND T9.MODULE_ITEM_ID = T1.AGREEMENT_REQUEST_ID
                        AND T9.IS_WORKFLOW_ACTIVE = ''Y''
                        AND T10.APPROVAL_STATUS = ''W''))
		OR EXISTS (SELECT 1 FROM ACCESS_ADMIN_GROUP_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		OR EXISTS (SELECT 1 FROM ACCESS_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
	)',LS_UNIT_CONDITION, ' )
	AND T1.AGREEMENT_SEQUENCE_STATUS <> ''TEMPLATE''
	WHERE ',LS_CATEGORY_CONDITION,' 
	GROUP BY 
		T2.DESCRIPTION,
		T2.CATEGORY_CODE
	UNION ALL 
	SELECT 
		DISTINCT
		''AGING_RECORDS'' AS RECORD_TYPE,
		COALESCE(COUNT(T1.AGREEMENT_REQUEST_ID), 0) AS RECORD_COUNT,
		T2.DESCRIPTION AS CATEGORY_DESCRIPTION,
		T2.CATEGORY_CODE
	FROM AGREEMENT_CATEGORY T2
	LEFT JOIN AGREEMENT_HEADER T1 ON T1.CATEGORY_CODE = T2.CATEGORY_CODE
	', LS_STATUS_CONDITION,
	' AND T1.AGREEMENT_STATUS_CODE IN (1,2,3,5,7)
	AND T1.UPDATE_TIMESTAMP BETWEEN''', AV_START_DATE,''' AND''', AV_END_DATE,'''
	AND (( EXISTS (SELECT 1 FROM ACCESS_ADMIN_TMP WHERE UNIT_NUMBER = T1.UNIT_NUMBER)
		 OR EXISTS (SELECT 1 FROM PRINCIPAL_INVESTIGATOR WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		 OR EXISTS (SELECT 1 FROM NEGOTIATOR WHERE ASSOCIATED_PROJECT_ID = T1.AGREEMENT_REQUEST_ID)
         OR T1.REQUESTOR_PERSON_ID = ''',AV_PERSON_ID,'''
         OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID, '''
		 OR (EXISTS (SELECT 1
					FROM WORKFLOW T9
					INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
					WHERE T9.MODULE_CODE = 13 
                        AND T10.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND T9.MODULE_ITEM_ID = T1.AGREEMENT_REQUEST_ID
                        AND T9.IS_WORKFLOW_ACTIVE = ''Y''
                        AND T10.APPROVAL_STATUS = ''W''))
		OR EXISTS (SELECT 1 FROM ACCESS_ADMIN_GROUP_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		OR EXISTS (SELECT 1 FROM ACCESS_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
	)',LS_UNIT_CONDITION, ' ) 
	AND T1.AGREEMENT_SEQUENCE_STATUS <> ''TEMPLATE'' 
	WHERE ',LS_CATEGORY_CONDITION,' 
	GROUP BY 
		T2.DESCRIPTION,
		T2.CATEGORY_CODE
	UNION ALL 
	SELECT 
		DISTINCT
		''PROCESSED_RECORDS'' AS RECORD_TYPE,
		COALESCE(COUNT(T1.AGREEMENT_REQUEST_ID), 0) AS RECORD_COUNT,
		T2.DESCRIPTION AS CATEGORY_DESCRIPTION,
		T2.CATEGORY_CODE
	FROM AGREEMENT_CATEGORY T2
	LEFT JOIN AGREEMENT_HEADER T1 ON T1.CATEGORY_CODE = T2.CATEGORY_CODE
	', LS_STATUS_CONDITION,
	' AND T1.AGREEMENT_STATUS_CODE IN (4)
	AND T1.UPDATE_TIMESTAMP BETWEEN''', AV_START_DATE,''' AND''', AV_END_DATE,'''
	AND (( EXISTS (SELECT 1 FROM ACCESS_ADMIN_TMP WHERE UNIT_NUMBER = T1.UNIT_NUMBER)
		 OR EXISTS (SELECT 1 FROM PRINCIPAL_INVESTIGATOR WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		 OR EXISTS (SELECT 1 FROM NEGOTIATOR WHERE ASSOCIATED_PROJECT_ID = T1.AGREEMENT_REQUEST_ID)
         OR T1.REQUESTOR_PERSON_ID = ''',AV_PERSON_ID,'''
         OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID, '''
		 OR (EXISTS (SELECT 1
					FROM WORKFLOW T9
					INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
					WHERE T9.MODULE_CODE = 13 
                        AND T10.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND T9.MODULE_ITEM_ID = T1.AGREEMENT_REQUEST_ID
                        AND T9.IS_WORKFLOW_ACTIVE = ''Y''
                        AND T10.APPROVAL_STATUS = ''W''))
		OR EXISTS (SELECT 1 FROM ACCESS_ADMIN_GROUP_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		OR EXISTS (SELECT 1 FROM ACCESS_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
	)',LS_UNIT_CONDITION, ' )
	AND T1.AGREEMENT_SEQUENCE_STATUS <> ''TEMPLATE'' 
    WHERE ',LS_CATEGORY_CONDITION,'
	GROUP BY 
		T2.DESCRIPTION,
		T2.CATEGORY_CODE
	UNION ALL
    SELECT 
		DISTINCT
		''UNPROCESSED_RECORDS'' AS RECORD_TYPE,
		COALESCE(COUNT(T1.AGREEMENT_REQUEST_ID), 0) AS RECORD_COUNT,
		T2.DESCRIPTION AS CATEGORY_DESCRIPTION,
		T2.CATEGORY_CODE
	FROM AGREEMENT_CATEGORY T2
	LEFT JOIN AGREEMENT_HEADER T1 ON T1.CATEGORY_CODE = T2.CATEGORY_CODE
	', LS_STATUS_CONDITION,
	' AND T1.AGREEMENT_STATUS_CODE IN (6,8,9,10)
	AND T1.UPDATE_TIMESTAMP BETWEEN''', AV_START_DATE,''' AND''', AV_END_DATE,'''
	AND (( EXISTS (SELECT 1 FROM ACCESS_ADMIN_TMP WHERE UNIT_NUMBER = T1.UNIT_NUMBER)
		 OR (SELECT T1.AGREEMENT_REQUEST_ID IN (SELECT AGREEMENT_REQUEST_ID FROM PRINCIPAL_INVESTIGATOR))
         OR EXISTS (SELECT 1 FROM PRINCIPAL_INVESTIGATOR WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		 OR EXISTS (SELECT 1 FROM NEGOTIATOR WHERE ASSOCIATED_PROJECT_ID = T1.AGREEMENT_REQUEST_ID)
         OR T1.REQUESTOR_PERSON_ID = ''',AV_PERSON_ID,'''
         OR T1.ADMIN_PERSON_ID = ''', AV_PERSON_ID, '''
		 OR (EXISTS (SELECT 1
					FROM WORKFLOW T9
					INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
					WHERE T9.MODULE_CODE = 13 
                        AND T10.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''
                        AND T9.MODULE_ITEM_ID = T1.AGREEMENT_REQUEST_ID
                        AND T9.IS_WORKFLOW_ACTIVE = ''Y''
                        AND T10.APPROVAL_STATUS = ''W''))
		OR EXISTS (SELECT 1 FROM ACCESS_ADMIN_GROUP_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
		OR EXISTS (SELECT 1 FROM ACCESS_TMP WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID)
	)',LS_UNIT_CONDITION, ' ) 
	AND T1.AGREEMENT_SEQUENCE_STATUS <> ''TEMPLATE'' 
	WHERE ',LS_CATEGORY_CONDITION,' 
	GROUP BY 
		T2.DESCRIPTION,
		T2.CATEGORY_CODE');
END IF;
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
END
