-- `INSERT_AGREEMENT_ACTION_LOG`; 

CREATE PROCEDURE `INSERT_AGREEMENT_ACTION_LOG`(
AV_AGREEMENT_REQUEST_ID INT,
AV_ACTION_TYPE_CODE VARCHAR(3),
AV_DESCRIPTION VARCHAR(200),
AV_UPDATE_USER VARCHAR(60)
)
BEGIN
INSERT INTO agreement_action_log (ACTION_TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, AGREEMENT_REQUEST_ID) 
VALUES (AV_ACTION_TYPE_CODE, AV_DESCRIPTION, UTC_TIMESTAMP(), AV_UPDATE_USER, AV_AGREEMENT_REQUEST_ID);
COMMIT;
END
