DROP TABLE IF EXISTS `budget_template_type`;

CREATE TABLE `budget_template_type` (
  `BUDGET_TEMPLATE_TYPE_ID` int(11) NOT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_TEMPLATE_TYPE_ID`)
) ;
