DROP TABLE IF EXISTS `budget_modular`;

CREATE TABLE `budget_modular` (
  `BUDGET_PERIOD_ID` int(11) NOT NULL,
  `BUDGET_HEADER_ID` int(11) DEFAULT NULL,
  `CONSORTIUM_FNA` decimal(15,2) DEFAULT NULL,
  `DIRECT_COST_LESS_CONSOR_FNA` decimal(15,2) DEFAULT NULL,
  `TOTAL_DIRECT_COST` decimal(15,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_PERIOD_ID`)
) ;
