DROP TABLE IF EXISTS `budget_status`;

CREATE TABLE `budget_status` (
  `BUDGET_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`BUDGET_STATUS_CODE`)
) ;
