SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `budget_template`;

CREATE TABLE `budget_template` (
  `BUDGET_TEMPLATE_ID` int(11) NOT NULL,
  `COST_ELEMENT` varchar(200) DEFAULT NULL,
  `IS_SYSTEM_GENRTED_COST_ELEMENT` varchar(200) DEFAULT NULL,
  `BUDGET_TEMPLATE_TYPE_ID` int(11) DEFAULT NULL,
  `RULE_ID` varchar(50) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `SYSTEM_GEN_COST_ELEMENT_TYPE` varchar(50) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_TEMPLATE_ID`),
  KEY `BUDGET_TEMPLATE_FK1` (`COST_ELEMENT`),
  KEY `BUDGET_TEMPLATE_FK2` (`BUDGET_TEMPLATE_TYPE_ID`),
  CONSTRAINT `BUDGET_TEMPLATE_FK1` FOREIGN KEY (`COST_ELEMENT`) REFERENCES `cost_element` (`COST_ELEMENT`),
  CONSTRAINT `BUDGET_TEMPLATE_FK2` FOREIGN KEY (`BUDGET_TEMPLATE_TYPE_ID`) REFERENCES `budget_template_type` (`BUDGET_TEMPLATE_TYPE_ID`)
) ;
SET FOREIGN_KEY_CHECKS = 1;