DROP TABLE IF EXISTS `budget_period`;

CREATE TABLE `budget_period` (
  `BUDGET_PERIOD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BUDGET_PERIOD` int(11) DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `IS_OBLIGATED_PERIOD` varchar(1) DEFAULT NULL,
  `MODULE_ITEM_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(30) DEFAULT NULL,
  `PERIOD_LABEL` varchar(255) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `TOTAL_COST` decimal(15,2) DEFAULT NULL,
  `TOTAL_DIRECT_COST` decimal(15,2) DEFAULT NULL,
  `TOTAL_INDIRECT_COST` decimal(15,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `VERSION_NUMBER` int(11) DEFAULT NULL,
  `BUDGET_HEADER_ID` int(11) DEFAULT NULL,
  `SUBCONTRACT_COST` decimal(15,2) DEFAULT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `COST_SHARING_AMOUNT` decimal(15,2) DEFAULT NULL,
  `TOTAL_COST_LIMIT` decimal(15,2) DEFAULT NULL,
  `TOTAL_DIRECT_COST_LIMIT` decimal(15,2) DEFAULT NULL,
  `UNDERRECOVERY_AMOUNT` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_PERIOD_ID`),
  KEY `BUDGET_PERIOD_FK1` (`BUDGET_HEADER_ID`),
  CONSTRAINT `BUDGET_PERIOD_FK1` FOREIGN KEY (`BUDGET_HEADER_ID`) REFERENCES `budget_header` (`BUDGET_HEADER_ID`)
) ;
