DROP TABLE IF EXISTS `budget_rate_and_base`;

CREATE TABLE `budget_rate_and_base` (
  `BUDGET_RATE_AND_BASE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BASE_COST` decimal(15,2) DEFAULT NULL,
  `BUDGET_ID` int(11) DEFAULT NULL,
  `BUDGET_PERIOD` int(11) DEFAULT NULL,
  `BUDGET_PERIOD_NUMBER` int(11) DEFAULT NULL,
  `LINE_ITEM_NUMBER` int(11) DEFAULT NULL,
  `RATE_CLASS_CODE` varchar(3) DEFAULT NULL,
  `RATE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `BUDGET_DETAILS_ID` int(11) DEFAULT NULL,
  `APPLIED_RATE` decimal(5,2) DEFAULT NULL,
  `BASE_COST_SHARING` decimal(15,2) DEFAULT NULL,
  `CALCULATED_COST` decimal(15,2) DEFAULT NULL,
  `CALCULATED_COST_SHARING` decimal(15,2) DEFAULT NULL,
  `END_DATE` datetime(6) DEFAULT NULL,
  `ON_OFF_CAMPUS_FLAG` varchar(255) DEFAULT NULL,
  `RATE_NUMBER` int(11) DEFAULT NULL,
  `START_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_RATE_AND_BASE_ID`),
  KEY `BUDGET_RATE_AND_BASE_FK1` (`BUDGET_DETAILS_ID`),
  CONSTRAINT `BUDGET_RATE_AND_BASE_FK1` FOREIGN KEY (`BUDGET_DETAILS_ID`) REFERENCES `budget_detail` (`BUDGET_DETAILS_ID`)
) ;
