DROP TABLE IF EXISTS `budget_type`;

CREATE TABLE `budget_type` (
  `BUDGET_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_TYPE_CODE`)
);
