DROP TABLE IF EXISTS `budget_det_cal_amt`;

CREATE TABLE `budget_det_cal_amt` (
  `BUDGET_DETAILS_CAL_AMTS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `APPLY_RATE_FLAG` varchar(1) DEFAULT NULL,
  `BUDGET_ID` int(11) DEFAULT NULL,
  `BUDGET_PERIOD` int(11) DEFAULT NULL,
  `BUDGET_PERIOD_NUMBER` int(11) DEFAULT NULL,
  `CALCULATED_COST` decimal(15,2) DEFAULT NULL,
  `CALCULATED_COST_SHARING` decimal(15,2) DEFAULT NULL,
  `LINE_ITEM_NUMBER` int(11) DEFAULT NULL,
  `RATE_CLASS_CODE` varchar(3) DEFAULT NULL,
  `RATE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `RATE_TYPE_DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `BUDGET_DETAILS_ID` int(11) DEFAULT NULL,
  `APPLICABLE_RATE` decimal(12,2) DEFAULT NULL,
  `CALCULATED_FUND_REQUESTED` decimal(15,2) DEFAULT NULL,
  `APPLICABLE_COST_SHARING_RATE` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_DETAILS_CAL_AMTS_ID`),
  KEY `BUDGET_DET_CAL_AMT_FK1` (`BUDGET_DETAILS_ID`),
  KEY `FK1yqc7yi3gvdici899nfot13fb` (`RATE_CLASS_CODE`,`RATE_TYPE_CODE`),
  CONSTRAINT `BUDGET_DET_CAL_AMT_FK1` FOREIGN KEY (`BUDGET_DETAILS_ID`) REFERENCES `budget_detail` (`BUDGET_DETAILS_ID`),
  CONSTRAINT `BUDGET_DET_CAL_AMT_FK2` FOREIGN KEY (`RATE_CLASS_CODE`) REFERENCES `rate_class` (`RATE_CLASS_CODE`),
  CONSTRAINT `BUDGET_DET_CAL_AMT_FK3` FOREIGN KEY (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`) REFERENCES `rate_type` (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`)
) ;