DROP TABLE IF EXISTS `cp_report_project_details`;

CREATE TABLE `cp_report_project_details` (
  `CP_REPORT_PROJECT_DETAIL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CP_REPORT_HEADER_ID` int(11) DEFAULT NULL,
  `LINKED_MODULE_CODE` int(11) DEFAULT NULL,
  `LINKED_MODULE_ITEM_ID` varchar(20) DEFAULT NULL,
  `IS_EXCLUDED` varchar(1) DEFAULT NULL,
  `IS_MANUALLY_ADDED` varchar(1) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `PROJECT_TITLE` varchar(1000) DEFAULT NULL,
  `GRANT_CALL_NAME` varchar(500) DEFAULT NULL,
  `PROP_PERSON_ROLE_ID` int(11) DEFAULT NULL,
  `AMOUNT` decimal(15,2) DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `SPONSOR_TYPE_CODE` varchar(20) DEFAULT NULL,
  `SPONSOR` varchar(500) DEFAULT NULL,
  `FUNDING_STATUS_CODE` int(11) DEFAULT NULL,
  `SPONSOR_CODE` varchar(20) DEFAULT NULL,
  `CURRENCY_CODE` varchar(20) DEFAULT NULL,
  `PERCENTAGE_OF_EFFORT` decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (`CP_REPORT_PROJECT_DETAIL_ID`),
  KEY `CP_REPORT_PROJECT_DETAILS_FK` (`CP_REPORT_HEADER_ID`),
  CONSTRAINT `CP_REPORT_PROJECT_DETAILS_FK` FOREIGN KEY (`CP_REPORT_HEADER_ID`) REFERENCES `cp_report_header` (`CP_REPORT_HEADER_ID`)
) ;
