DROP TABLE IF EXISTS `eps_proposal_comments`;

CREATE TABLE `eps_proposal_comments` (
  `EPS_PROPOSAL_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROPOSAL_ID` int(11) DEFAULT NULL,
  `COMMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COMMENTS` longtext,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_PRIVATE` varchar(1) DEFAULT NULL,
  `IS_PUBLIC` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EPS_PROPOSAL_COMMENT_ID`),
  KEY `EPS_PROPOSAL_COMMENTS_FK1` (`PROPOSAL_ID`),
  KEY `EPS_PROPOSAL_COMMENTS_FK2` (`COMMENT_TYPE_CODE`),
  CONSTRAINT `EPS_PROPOSAL_COMMENTS_FK1` FOREIGN KEY (`PROPOSAL_ID`) REFERENCES `eps_proposal` (`PROPOSAL_ID`),
  CONSTRAINT `EPS_PROPOSAL_COMMENTS_FK2` FOREIGN KEY (`COMMENT_TYPE_CODE`) REFERENCES `comment_type` (`COMMENT_TYPE_CODE`)
) ;
