DROP TABLE IF EXISTS `eps_proposal_ext`;

CREATE TABLE `eps_proposal_ext` (
  `PROPOSAL_ID` int(11) NOT NULL,
  `IS_FOREIGN_ACTIVITIES` varchar(1) DEFAULT NULL,
  `IS_SUBCONTRACT` varchar(1) DEFAULT NULL,
  `IS_MULTISITE_STUDY` varchar(1) DEFAULT NULL,
  `IS_DOMESTIC_SITE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`PROPOSAL_ID`)
);
