DROP TABLE IF EXISTS `eps_proposal_person_degree`;

CREATE TABLE `eps_proposal_person_degree` (
  `PROPOSAL_PERSON_DEGREE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROPOSAL_PERSON_ID` int(11) DEFAULT NULL,
  `DEGREE_CODE` varchar(10) DEFAULT NULL,
  `DEGREE` varchar(200) DEFAULT NULL,
  `FIELD_OF_STUDY` varchar(200) DEFAULT NULL,
  `SPECIALIZATION` varchar(200) DEFAULT NULL,
  `SCHOOL` varchar(200) DEFAULT NULL,
  `GRADUATION_DATE` varchar(20) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`PROPOSAL_PERSON_DEGREE_ID`),
  KEY `EPS_PROP_PERSON_DEGREE_FK1` (`PROPOSAL_PERSON_ID`),
  KEY `DEGREE_CODE_FK3` (`DEGREE_CODE`),
  CONSTRAINT `DEGREE_CODE_FK3` FOREIGN KEY (`DEGREE_CODE`) REFERENCES `degree_type` (`DEGREE_CODE`),
  CONSTRAINT `EPS_PROP_PERSON_DEGREE_FK1` FOREIGN KEY (`PROPOSAL_PERSON_ID`) REFERENCES `eps_proposal_persons` (`PROPOSAL_PERSON_ID`)
) ;
