DROP TABLE IF EXISTS `eps_proposal_kpi_criteria`;

CREATE TABLE `eps_proposal_kpi_criteria` (
  `EPS_PROPOSAL_KPI_CRITERIA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_CRITERIA_TYPE_CODE` varchar(255) DEFAULT NULL,
  `KPI_TYPE_CODE` varchar(255) DEFAULT NULL,
  `PROPOSAL_KPI_ID` int(11) DEFAULT NULL,
  `TARGET` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EPS_PROPOSAL_KPI_CRITERIA_ID`),
  KEY `EPS_PROPOSAL_KPI_CRITERIA_FK3` (`KPI_CRITERIA_TYPE_CODE`),
  KEY `EPS_PROPOSAL_KPI_CRITERIA_FK2` (`KPI_TYPE_CODE`),
  KEY `EPS_PROPOSAL_KPI_CRITERIA_FK1` (`PROPOSAL_KPI_ID`),
  CONSTRAINT `EPS_PROPOSAL_KPI_CRITERIA_FK1` FOREIGN KEY (`PROPOSAL_KPI_ID`) REFERENCES `eps_proposal_kpi` (`PROPOSAL_KPI_ID`),
  CONSTRAINT `EPS_PROPOSAL_KPI_CRITERIA_FK2` FOREIGN KEY (`KPI_TYPE_CODE`) REFERENCES `kpi_type` (`KPI_TYPE_CODE`),
  CONSTRAINT `EPS_PROPOSAL_KPI_CRITERIA_FK3` FOREIGN KEY (`KPI_CRITERIA_TYPE_CODE`) REFERENCES `kpi_criteria_type` (`KPI_CRITERIA_TYPE_CODE`)
);
