DROP TABLE IF EXISTS `eps_prop_pre_review_attachment`;

CREATE TABLE `eps_prop_pre_review_attachment` (
  `PRE_REVIEW_ATTACHMENT_ID` int(11) NOT NULL,
  `PRE_REVIEW_COMMENT_ID` int(11) DEFAULT NULL,
  `PRE_REVIEW_ID` int(11) DEFAULT NULL,
  `PROPOSAL_ID` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `ATTACHMENT` blob,
  `FILE_NAME` varchar(1000) DEFAULT NULL,
  `MIME_TYPE` varchar(100) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PRE_REVIEW_ATTACHMENT_ID`),
  KEY `PRE_REVIEWER_ATTACHMENT_FK1` (`PRE_REVIEW_COMMENT_ID`),
  CONSTRAINT `PRE_REVIEWER_ATTACHMENT_FK1` FOREIGN KEY (`PRE_REVIEW_COMMENT_ID`) REFERENCES `eps_prop_pre_review_comment` (`PRE_REVIEW_COMMENT_ID`)
) ;
