DROP TABLE IF EXISTS `eps_proposal_comment_attachments`;

CREATE TABLE `eps_proposal_comment_attachments` (
  `COMMENT_ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EPS_PROPOSAL_COMMENT_ID` int(11) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `FILE_DATA_ID` varchar(36) DEFAULT NULL,
  `MIME_TYPE` varchar(250) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COMMENT_ATTACHMENT_ID`),
  KEY `EPS_PROP_COMMENT_ATTACHMENT_FK1` (`EPS_PROPOSAL_COMMENT_ID`),
  CONSTRAINT `EPS_PROP_COMMENT_ATTACHMENT_FK1` FOREIGN KEY (`EPS_PROPOSAL_COMMENT_ID`) REFERENCES `eps_proposal_comments` (`EPS_PROPOSAL_COMMENT_ID`)
) ;
