DELIMITER $$
CREATE  FUNCTION `FN_CHK_ATTA_NOA_BUDSETUP`(
AV_TASK_ID varchar(10)) RETURNS varchar(6) CHARSET latin1
    DETERMINISTIC
BEGIN
DECLARE LI_AWARD_ID INT(22);
DECLARE LS_COUNT INT;
SELECT MODULE_ITEM_ID INTO LI_AWARD_ID
FROM TASK
where TASK_ID = AV_TASK_ID;
SELECT COUNT(1) INTO LS_COUNT FROM AWARD_ATTACHMENT T1
INNER JOIN AWARD_ATTACHMENT T2 ON T1.AWARD_ID = T2.AWARD_ID
WHERE T1.AWARD_ID = LI_AWARD_ID
AND T1.TYPE_CODE = 150
AND T2.TYPE_CODE = 151;
IF LS_COUNT > 0 THEN
	RETURN 'TRUE';
ELSE
    RETURN 'FALSE';
END IF;
END
$$
DELIMITER ;
