DELIMITER $$
CREATE  PROCEDURE `GET_OPA_DETAILS`(
IN AV_COLUMN_NAMES VARCHAR(4000),
    IN AV_MODULE_ITEM_KEY INT,
    IN AV_SUB_MODULE_ITEM_KEY  INT
)
BEGIN
    DECLARE LS_DYN_SQL LONGTEXT;
    SET LS_DYN_SQL = CONCAT(
        'SELECT ', AV_COLUMN_NAMES, ' FROM(
        SELECT
        T1.OPA_DISCLOSURE_ID AS OPA_DISCLOSURE_ID,
        T4.FULL_NAME AS REPORTER_NAME,
        DATE(T1.SUBMISSION_TIMESTAMP) AS CERTIFICATION_DATE,
        T1.HOME_UNIT AS DEPARTMENT_NUMBER,
        T2.UNIT_NAME AS DEPARTMENT_NAME,
        T3.DESCRIPTION AS DISPOSITION_STATUS
        FROM OPA_DISCLOSURE T1
        LEFT JOIN UNIT T2 ON T2.UNIT_NUMBER = T1.HOME_UNIT
        LEFT JOIN OPA_DISPOSITION_STATUS_TYPE T3 ON T3.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
        LEFT JOIN PERSON T4 ON T4.PERSON_ID = T1.PERSON_ID
        WHERE T1.OPA_DISCLOSURE_ID = ', AV_MODULE_ITEM_KEY, ') T');
    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STATEMENT;
    DEALLOCATE PREPARE EXECUTABLE_STATEMENT;
END
$$
DELIMITER ;
