DELIMITER $$
CREATE  PROCEDURE `GET_MIG_ENG_DETAILS`(AV_ENG_ID INT, AV_PERSON_ID VARCHAR(9))
BEGIN
	SELECT
		T1.ENGAGEMENT_ID,
		T1.ENTITY_NAME AS ENTITY_NAME,
		CASE WHEN T1.IS_TRAVEL = 'N' AND T1.IS_FINANCIAL = 'Y' THEN 'Financial'
			WHEN T1.IS_TRAVEL = 'Y' AND T1.IS_FINANCIAL = 'N' THEN 'Travel'
			ELSE 'Financial and Travel'
		END AS RELATIONSHIP_TYPE,
		NULLIF(T2.DESCRIPTION,'') AS ENTITY_TYPE,
		CASE WHEN T1.ENTITY_OWNERSHIP_TYPE = 'V' THEN 'Private'
			WHEN T1.ENTITY_OWNERSHIP_TYPE = 'P' THEN 'Public'
			ELSE NULL END AS OWNERSHIP_TYPE,
		NULLIF(T1.RELATIONSHIP_DESCRIPTION,'') AS ENTITY_BUSINESS_FOCUS,
		NULLIF(T1.STUDENT_INVOLVEMENT,'') AS INVOLVEMENT_OF_STUDENTS,
		NULLIF(T1.STAFF_INVOLVEMENT,'') AS INVOLVEMENT_OF_STAFF,
		NULLIF(T1.INST_RESOURCE_INVOLVEMENT,'') AS USE_OF_MIT_RESOURCES,
		CASE WHEN T1.IS_FOUNDER = 'Y' THEN 'Yes'
			 WHEN T1.IS_FOUNDER = 'N' THEN 'No'
			 ELSE NULL END AS FOUNDER,
		T3.DESCRIPTION AS MIGRATION_STATUS,
        CASE WHEN T1.ENTITY_OWNERSHIP_TYPE = 'V' THEN '2'
			WHEN T1.ENTITY_OWNERSHIP_TYPE = 'P' THEN '1'
			ELSE '3' END AS OWNERSHIP_TYPE_CODE
		FROM LEGACY_COI_ENGAGEMENTS T1
		LEFT JOIN FIBI_COI_ENTITY_TYPE T2 ON T2.ENTITY_TYPE_CODE = T1.ENTITY_TYPE_CODE
		LEFT JOIN FIBI_COI_ENG_REVIEW_STATUS T3 ON T3.ENG_REVIEW_STATUS_CODE = T1.MIGRATION_STATUS
		WHERE T1.ENGAGEMENT_ID = AV_ENG_ID AND T1.PERSON_ID = AV_PERSON_ID AND T1.STATUS_CODE = 1;
END
$$
DELIMITER ;
