DELIMITER $$
CREATE  PROCEDURE `KKI_PERSON_REFRESH`(AV_TYPE INT)
BEGIN
DECLARE LI_PERSON_RT_ID INT(12);
DECLARE LS_PERSON_ID VARCHAR(100);
DECLARE LS_LAST_NAME VARCHAR(100);
DECLARE LS_FIRST_NAME VARCHAR(100);
DECLARE LS_FULL_NAME VARCHAR(200);
DECLARE LS_USER_NAME VARCHAR(100);
DECLARE LS_EMAIL_ADDRESS VARCHAR(100);
DECLARE LS_DEGREE VARCHAR(200);
DECLARE LS_OFFICE_LOCATION VARCHAR(100);
DECLARE LS_OFFICE_PHONE VARCHAR(100);
DECLARE LS_DIRECTORY_DEPARTMENT VARCHAR(200);
DECLARE LS_PRIMARY_TITLE VARCHAR(200);
DECLARE LS_HOME_UNIT VARCHAR(100);
DECLARE LS_RELATIONSHIP VARCHAR(200);
DECLARE LS_ADDRESS_LINE_1 VARCHAR(200);
DECLARE LS_CITY VARCHAR(100);
DECLARE LS_STATE_PROVINCE VARCHAR(100);
DECLARE LS_ZIP_CODE VARCHAR(100);
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE LI_COUNT INT;
DECLARE LI_ERROR_FLAG INT;
DECLARE LI_ROLODEX_ID INT(12);
DECLARE LS_ERROR VARCHAR(4000);
DECLARE LS_IS_RESEARCH_STAFF VARCHAR(1);
DECLARE LS_IS_FACULTY VARCHAR(1);
DECLARE LS_IS_SUPPORT_STAFF VARCHAR(1);
DECLARE LS_IS_OTHER_ACADEMIC_GROUP VARCHAR(1);
DECLARE LI_TOTAL_FILE_COUNT INT(8);
DECLARE LI_TOTAL_PERSON_COUNT INT(8);
DECLARE LI_TOTAL_ROLODEX_COUNT INT(8);
DECLARE LI_TOTAL_PERSON_INSERT INT(8);
DECLARE LI_TOTAL_ROLODEX_INSERT INT(8);
DECLARE LI_PERSON_TO_BE_INSERTED INT(8);
DECLARE LI_PERSON_INSERTED INT(8);
DECLARE LI_ROLODEX_TO_BE_INSERTED INT(8);
DECLARE LI_ROLODEX_INSERTED INT(8);
DECLARE LI_PERSON_TO_BE_UPDATED INT(8);
DECLARE LI_ROLODEX_TO_BE_UPDATED INT(8);
DECLARE LI_PERSON_UPDATED INT(8);
DECLARE LI_ROLODEX_UPDATED INT(8);
DECLARE LI_FAILED INT;
SET SQL_SAFE_UPDATES =0;
PARENT_LABEL : BEGIN
	DECLARE PERSON_CURSOR CURSOR FOR
		SELECT PERSON_RT_ID,
		PERSON_ID,
		LAST_NAME,
		FIRST_NAME,
		FULL_NAME,
		USER_NAME,
		EMAIL_ADDRESS,
		DEGREE,
		OFFICE_LOCATION,
		OFFICE_PHONE,
		DIRECTORY_DEPARTMENT,
		PRIMARY_TITLE,
		HOME_UNIT,
		RELATIONSHIP,
		ADDRESS_LINE_1,
		CITY,
		STATE_PROVINCE,
		ZIP_CODE
		FROM PERSON_RT ;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
SELECT @full_error INTO LS_ERROR;
		INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,ERROR_TYPE,ERROR_MESSAGE) VALUES(LS_PERSON_ID,'Exception',SUBSTR(LS_ERROR,1,999));
		COMMIT;
		SELECT 'FALSE' AS RESULT;
		END;
		TRUNCATE TABLE PERSON_FEED_ERROR_LOG;
		UPDATE PERSON_RT SET STATUS = NULL;
		COMMIT;
		SET LI_ERROR_FLAG = 0;
OPEN PERSON_CURSOR;
PERSON_CURSOR_LOOP : LOOP
FETCH PERSON_CURSOR INTO
					LI_PERSON_RT_ID,
					LS_PERSON_ID,
					LS_LAST_NAME,
					LS_FIRST_NAME,
					LS_FULL_NAME,
					LS_USER_NAME,
					LS_EMAIL_ADDRESS,
					LS_DEGREE,
					LS_OFFICE_LOCATION,
					LS_OFFICE_PHONE,
					LS_DIRECTORY_DEPARTMENT,
					LS_PRIMARY_TITLE,
					LS_HOME_UNIT,
					LS_RELATIONSHIP,
					LS_ADDRESS_LINE_1,
					LS_CITY,
					LS_STATE_PROVINCE,
					LS_ZIP_CODE;
		IF DONE1 THEN
		LEAVE PERSON_CURSOR_LOOP;
		END IF;
		IF ( IFNULL(TRIM(LS_PERSON_ID),'') = '' AND UPPER(TRIM(LS_RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF')) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Person id cannot be NULL',LS_PERSON_ID);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_PERSON_ID)) > 40 AND UPPER(TRIM(LS_RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF')) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Person id cannot be more than 40 characters',LS_PERSON_ID);
			COMMIT;
		END IF;
		IF ( UPPER(TRIM(LS_RELATIONSHIP)) NOT IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF','CONTRACTOR','EXTERNAL RESOURCE') ) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Relationship does not exist',LS_RELATIONSHIP);
			COMMIT;
		END IF;
		IF ( (IFNULL(TRIM(LS_USER_NAME),'') = '') AND UPPER(TRIM(LS_RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF')) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','User name cannot be NULL',LS_PERSON_ID);
			COMMIT;
		ELSEIF(LENGTH(TRIM(LS_USER_NAME)) > 60) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','User name cannot be more than 60 characters',LS_USER_NAME);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_LAST_NAME)) > 50) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Last Name cannot be more than 50 characters',LS_LAST_NAME);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_FIRST_NAME)) > 50) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','First Name cannot be more than 50 characters',LS_FIRST_NAME);
			COMMIT;
		END IF;
		IF (LENGTH(COALESCE(TRIM(LS_FULL_NAME),TRIM(TRAILING ', ' FROM CONCAT(IF(IFNULL(TRIM(LS_LAST_NAME),'')='','',concat(LS_LAST_NAME,', ')), IFNULL(TRIM(LS_FIRST_NAME),''))))) > 200) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Full Name cannot be more than 200 characters',COALESCE(TRIM(LS_FULL_NAME),TRIM(TRAILING ', ' FROM CONCAT(IF(IFNULL(TRIM(LS_LAST_NAME),'')='','',concat(LS_LAST_NAME,', ')), IFNULL(TRIM(LS_FIRST_NAME),'')))));
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_EMAIL_ADDRESS)) > 60) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Email Address cannot be more than 60 characters',LS_EMAIL_ADDRESS);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_DEGREE)) > 128) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Degree cannot be more than 128 characters',LS_DEGREE);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_OFFICE_LOCATION)) > 100) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Office Location cannot be more than 100 characters',LS_OFFICE_LOCATION);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_OFFICE_PHONE)) > 26) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Office Phone cannot be more than 26 characters',LS_OFFICE_PHONE);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_PRIMARY_TITLE)) > 100) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Primary Title cannot be more than 100 characters',LS_PRIMARY_TITLE);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_ADDRESS_LINE_1)) > 80) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Address Line cannot be more than 80 characters',LS_ADDRESS_LINE_1);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_CITY)) > 30) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','City cannot be more than 30 characters',LS_CITY);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_STATE_PROVINCE)) > 30) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','State cannot be more than 30 characters',LS_STATE_PROVINCE);
			COMMIT;
		END IF;
		IF (LENGTH(TRIM(LS_ZIP_CODE)) > 15) THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Zip code cannot be more than 40 characters',LS_ZIP_CODE);
			COMMIT;
		END IF;
		SELECT COUNT(*) INTO LI_COUNT
		FROM UNIT WHERE UPPER(TRIM(UNIT_NUMBER)) = UPPER(TRIM(LS_HOME_UNIT));
		IF LI_COUNT = 0 THEN
			INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE,ERROR_VALUE) VALUES(LS_PERSON_ID,LS_USER_NAME,LS_FIRST_NAME,LS_LAST_NAME,'Exception','Unit Number missing in the unit master data table',LS_HOME_UNIT);
			COMMIT;
		ELSE
			SET LS_DIRECTORY_DEPARTMENT = (SELECT UNIT_NAME FROM UNIT WHERE UPPER(TRIM(UNIT_NUMBER)) = UPPER(TRIM(LS_HOME_UNIT)));
		END IF;
END LOOP;
CLOSE PERSON_CURSOR;
DROP TABLE IF EXISTS PERSON_FEEDBACKUP ;
CREATE TABLE PERSON_FEEDBACKUP AS
SELECT * FROM PERSON;
COMMIT;
DROP TABLE IF EXISTS ROLODEX_FEEDBACKUP ;
CREATE TABLE ROLODEX_FEEDBACKUP AS
SELECT * FROM ROLODEX;
COMMIT;
SELECT COUNT(*) INTO LI_TOTAL_FILE_COUNT
FROM PERSON_RT;
SELECT COUNT(*) INTO LI_TOTAL_PERSON_COUNT
FROM PERSON_RT
WHERE UPPER(TRIM(RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF')
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
SELECT COUNT(*) INTO LI_PERSON_TO_BE_INSERTED
FROM PERSON_RT
WHERE UPPER(TRIM(RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF')
AND UPPER(TRIM(PERSON_ID)) NOT IN(SELECT UPPER(TRIM(PERSON_ID)) FROM PERSON)
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
SELECT COUNT(*) INTO LI_PERSON_TO_BE_UPDATED
FROM PERSON_RT
WHERE UPPER(TRIM(RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF')
AND UPPER(TRIM(PERSON_ID)) IN(SELECT UPPER(TRIM(PERSON_ID)) FROM PERSON)
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
SELECT COUNT(*) INTO LI_TOTAL_ROLODEX_COUNT
FROM PERSON_RT
WHERE UPPER(TRIM(RELATIONSHIP)) IN('CONTRACTOR','EXTERNAL RESOURCE')
AND PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
SELECT COUNT(*) INTO LI_ROLODEX_TO_BE_INSERTED
FROM PERSON_RT
WHERE UPPER(TRIM(RELATIONSHIP)) IN('CONTRACTOR','EXTERNAL RESOURCE')
AND ( CONCAT(IFNULL(TRIM(LAST_NAME),''),IFNULL(TRIM(FIRST_NAME),'')) NOT IN(SELECT CONCAT(IFNULL(TRIM(LAST_NAME),''),IFNULL(TRIM(FIRST_NAME),'')) FROM ROLODEX)
OR UPPER(TRIM(FULL_NAME)) NOT IN(SELECT IFNULL(UPPER(TRIM(LS_FULL_NAME)),'*') FROM ROLODEX)
)AND PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
SELECT COUNT(*) INTO LI_ROLODEX_TO_BE_UPDATED
FROM PERSON_RT
WHERE UPPER(TRIM(RELATIONSHIP)) IN('CONTRACTOR','EXTERNAL RESOURCE')
AND ( CONCAT(IFNULL(TRIM(LAST_NAME),''),IFNULL(TRIM(FIRST_NAME),'')) IN(SELECT CONCAT(IFNULL(TRIM(LAST_NAME),''),IFNULL(TRIM(FIRST_NAME),'')) FROM ROLODEX)
OR UPPER(TRIM(FULL_NAME)) IN(SELECT IFNULL(UPPER(TRIM(LS_FULL_NAME)),'*') FROM ROLODEX)
)AND PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
BEGIN
DECLARE DONE2 INT DEFAULT FALSE;
DECLARE PERSON_UPDATION_CURSOR CURSOR FOR
		SELECT PERSON_RT_ID,
				PERSON_ID,
				LAST_NAME,
				FIRST_NAME,
				FULL_NAME,
				USER_NAME,
				EMAIL_ADDRESS,
				DEGREE,
				OFFICE_LOCATION,
				OFFICE_PHONE,
				DIRECTORY_DEPARTMENT,
				PRIMARY_TITLE,
				HOME_UNIT,
				RELATIONSHIP,
				ADDRESS_LINE_1,
				CITY,
				STATE_PROVINCE,
				ZIP_CODE
		FROM PERSON_RT WHERE PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
SELECT @full_error INTO LS_ERROR;
	INSERT INTO PERSON_FEED_ERROR_LOG (PERSON_ID,USER_NAME,FIRST_NAME,LAST_NAME ,ERROR_TYPE,ERROR_MESSAGE) VALUES(LS_PERSON_ID,LS_FIRST_NAME,LS_LAST_NAME ,'Exception',SUBSTR(LS_ERROR,1,999));
	COMMIT;
	SELECT 'FALSE' AS RESULT;
END;
OPEN PERSON_UPDATION_CURSOR;
PERSON_UPDATION_CURSOR_LOOP : LOOP
FETCH PERSON_UPDATION_CURSOR INTO 	LI_PERSON_RT_ID,
									LS_PERSON_ID,
									LS_LAST_NAME,
									LS_FIRST_NAME,
									LS_FULL_NAME,
									LS_USER_NAME,
									LS_EMAIL_ADDRESS,
									LS_DEGREE,
									LS_OFFICE_LOCATION,
									LS_OFFICE_PHONE,
									LS_DIRECTORY_DEPARTMENT,
									LS_PRIMARY_TITLE,
									LS_HOME_UNIT,
									LS_RELATIONSHIP,
									LS_ADDRESS_LINE_1,
									LS_CITY,
									LS_STATE_PROVINCE,
									LS_ZIP_CODE;
IF DONE2 THEN
LEAVE PERSON_UPDATION_CURSOR_LOOP;
END IF;
SET LS_IS_RESEARCH_STAFF = NULL;
SET LS_IS_FACULTY = NULL;
SET LS_IS_SUPPORT_STAFF = NULL;
SET LS_IS_OTHER_ACADEMIC_GROUP = NULL;
IF ( UPPER(TRIM(LS_RELATIONSHIP)) IN('CONTRACTOR','EXTERNAL RESOURCE') ) THEN
		SELECT COUNT(*) INTO LI_COUNT
		FROM ROLODEX
		WHERE ( CONCAT(IFNULL(TRIM(LAST_NAME),''),IFNULL(TRIM(FIRST_NAME),'')) = CONCAT(IFNULL(TRIM(LS_LAST_NAME),''),IFNULL(TRIM(LS_FIRST_NAME),''))
		OR UPPER(TRIM(FULL_NAME)) = IFNULL(UPPER(TRIM(LS_FULL_NAME)),'*')
		);
		IF LI_COUNT = 0 THEN
		SELECT IFNULL(MAX(ROLODEX_ID),0)+1 INTO LI_ROLODEX_ID FROM ROLODEX;
		INSERT INTO ROLODEX (ROLODEX_ID,
							LAST_NAME,
							FIRST_NAME,
							FULL_NAME,
							EMAIL_ADDRESS,
							PHONE_NUMBER,
							OWNED_BY_UNIT,
							ADDRESS_LINE_1,
							CITY,
							STATE,
							POSTAL_CODE,
							COUNTRY_CODE,
							ORGANIZATION,
							UPDATE_TIMESTAMP,
							UPDATE_USER,
							CREATE_USER)
							VALUES (LI_ROLODEX_ID,
							TRIM(LS_LAST_NAME),
							TRIM(LS_FIRST_NAME),
							COALESCE(TRIM(LS_FULL_NAME),TRIM(TRAILING ', ' FROM CONCAT(IF(IFNULL(TRIM(LS_LAST_NAME),'')='','',concat(LS_LAST_NAME,', ')), IFNULL(TRIM(LS_FIRST_NAME),'')))),
							TRIM(LS_EMAIL_ADDRESS),
							TRIM(LS_OFFICE_PHONE),
							TRIM(LS_HOME_UNIT),
							TRIM(LS_ADDRESS_LINE_1),
							TRIM(LS_CITY),
							TRIM(LS_STATE_PROVINCE),
							TRIM(LS_ZIP_CODE),
							'USA',
							'000001',
							NOW(),
							'quickstart',
							'quickstart'
							);
		UPDATE PERSON_RT SET STATUS = 'I' WHERE UPPER(TRIM(PERSON_ID)) = UPPER(TRIM(LS_PERSON_ID)) AND UPPER(TRIM(USER_NAME)) = UPPER(TRIM(LS_USER_NAME));
		COMMIT;
		ELSE
		UPDATE ROLODEX SET LAST_NAME = TRIM(LS_LAST_NAME),
							FIRST_NAME = TRIM(LS_FIRST_NAME),
							FULL_NAME = COALESCE(TRIM(LS_FULL_NAME),TRIM(TRAILING ', ' FROM CONCAT(IF(IFNULL(TRIM(LS_LAST_NAME),'')='','',concat(LS_LAST_NAME,', ')), IFNULL(TRIM(LS_FIRST_NAME),'')))),
							EMAIL_ADDRESS = TRIM(LS_EMAIL_ADDRESS),
							PHONE_NUMBER = TRIM(LS_OFFICE_PHONE),
							OWNED_BY_UNIT = TRIM(LS_HOME_UNIT),
							ADDRESS_LINE_1 = TRIM(LS_ADDRESS_LINE_1),
							CITY = TRIM(LS_CITY),
							STATE = TRIM(LS_STATE_PROVINCE),
							POSTAL_CODE = TRIM(LS_ZIP_CODE),
							COUNTRY_CODE = 'USA',
							ORGANIZATION = '000001',
							UPDATE_TIMESTAMP = NOW(),
							UPDATE_USER = 'quickstart',
							CREATE_USER = 'quickstart'
							WHERE ( CONCAT(IFNULL(TRIM(LAST_NAME),''),IFNULL(TRIM(FIRST_NAME),'')) = CONCAT(IFNULL(TRIM(LS_LAST_NAME),''),IFNULL(TRIM(LS_FIRST_NAME),''))
							OR UPPER(TRIM(FULL_NAME)) = IFNULL(UPPER(TRIM(LS_FULL_NAME)),'*')
		);
		UPDATE PERSON_RT SET STATUS = 'U' WHERE UPPER(TRIM(PERSON_ID)) = UPPER(TRIM(LS_PERSON_ID)) AND UPPER(TRIM(USER_NAME)) = UPPER(TRIM(LS_USER_NAME));
		COMMIT;
		END IF;
		ELSE
		IF UPPER(TRIM(LS_RELATIONSHIP)) = 'EMPLOYEE' THEN
		SET LS_IS_RESEARCH_STAFF = 'Y';
		SET LS_IS_FACULTY = 'N';
		SET LS_IS_SUPPORT_STAFF = 'N';
		SET LS_IS_OTHER_ACADEMIC_GROUP = 'N';
		ELSEIF UPPER(TRIM(LS_RELATIONSHIP)) = 'TRAINEE' THEN
		SET LS_IS_RESEARCH_STAFF = 'N';
		SET LS_IS_FACULTY = 'N';
		SET LS_IS_SUPPORT_STAFF = 'N';
		SET LS_IS_OTHER_ACADEMIC_GROUP = 'Y';
		ELSEIF UPPER(TRIM(LS_RELATIONSHIP)) = 'FACULTYEMPLOYEE' THEN
		SET LS_IS_RESEARCH_STAFF = 'N';
		SET LS_IS_FACULTY = 'Y';
		SET LS_IS_SUPPORT_STAFF = 'N';
		SET LS_IS_OTHER_ACADEMIC_GROUP = 'N';
		ELSEIF UPPER(TRIM(LS_RELATIONSHIP)) = 'SRSTAFF' THEN
		SET LS_IS_RESEARCH_STAFF = 'N';
		SET LS_IS_FACULTY = 'N';
		SET LS_IS_SUPPORT_STAFF = 'Y';
		SET LS_IS_OTHER_ACADEMIC_GROUP = 'N';
		END IF;
		SELECT COUNT(*) INTO LI_COUNT
		FROM PERSON
		WHERE UPPER(TRIM(PERSON_ID)) = UPPER(TRIM(LS_PERSON_ID));
		IF LI_COUNT = 0 THEN
			INSERT INTO PERSON(
					PERSON_ID,
					LAST_NAME,
					FIRST_NAME,
					FULL_NAME,
					USER_NAME,
					EMAIL_ADDRESS,
					DEGREE,
					OFFICE_LOCATION,
					OFFICE_PHONE,
					DIRECTORY_DEPARTMENT,
					PRIMARY_TITLE,
					HOME_UNIT,
					ADDRESS_LINE_1,
					CITY,
					STATE,
					POSTAL_CODE,
					PASSWORD,
					UPDATE_TIMESTAMP,
					UPDATE_USER,
					IS_RESEARCH_STAFF,
					IS_FACULTY,
					IS_SUPPORT_STAFF,
					IS_OTHER_ACCADEMIC_GROUP,
					STATUS
					)
					VALUES(TRIM(LS_PERSON_ID),
					TRIM(LS_LAST_NAME),
					TRIM(LS_FIRST_NAME),
					COALESCE(TRIM(LS_FULL_NAME),TRIM(TRAILING ', ' FROM CONCAT(IF(IFNULL(TRIM(LS_LAST_NAME),'')='','',concat(LS_LAST_NAME,', ')), IFNULL(TRIM(LS_FIRST_NAME),'')))),
					LOWER(TRIM(LS_USER_NAME)),
					TRIM(LS_EMAIL_ADDRESS),
					TRIM(LS_DEGREE),
					TRIM(LS_OFFICE_LOCATION),
					TRIM(LS_OFFICE_PHONE),
					TRIM(LS_DIRECTORY_DEPARTMENT),
					TRIM(LS_PRIMARY_TITLE),
					TRIM(LS_HOME_UNIT),
					TRIM(LS_ADDRESS_LINE_1),
					TRIM(LS_CITY),
					TRIM(LS_STATE_PROVINCE),
					TRIM(LS_ZIP_CODE),
					NULL,
					NOW(),
					'quickstart',
					LS_IS_RESEARCH_STAFF,
					LS_IS_FACULTY,
					LS_IS_SUPPORT_STAFF,
					LS_IS_OTHER_ACADEMIC_GROUP,
					'A'
			);
			UPDATE PERSON_RT SET STATUS = 'I' WHERE UPPER(TRIM(PERSON_ID)) = UPPER(TRIM(LS_PERSON_ID)) AND UPPER(TRIM(USER_NAME)) = UPPER(TRIM(LS_USER_NAME));
			COMMIT;
			ELSE
			UPDATE PERSON SET LAST_NAME = TRIM(LS_LAST_NAME),
								FIRST_NAME = TRIM(LS_FIRST_NAME),
								FULL_NAME = COALESCE(TRIM(LS_FULL_NAME),TRIM(TRAILING ', ' FROM CONCAT(IF(IFNULL(TRIM(LS_LAST_NAME),'')='','',concat(LS_LAST_NAME,', ')), IFNULL(TRIM(LS_FIRST_NAME),'')))),
								USER_NAME = LOWER(TRIM(LS_USER_NAME)),
								EMAIL_ADDRESS = TRIM(LS_EMAIL_ADDRESS),
								DEGREE = TRIM(LS_DEGREE),
								OFFICE_LOCATION = TRIM(LS_OFFICE_LOCATION),
								OFFICE_PHONE = TRIM(LS_OFFICE_PHONE),
								DIRECTORY_DEPARTMENT = TRIM(LS_DIRECTORY_DEPARTMENT),
								PRIMARY_TITLE = TRIM(LS_PRIMARY_TITLE),
								HOME_UNIT = TRIM(LS_HOME_UNIT),
								ADDRESS_LINE_1 = TRIM(LS_ADDRESS_LINE_1),
								CITY = TRIM(LS_CITY),
								STATE = TRIM(LS_STATE_PROVINCE),
								POSTAL_CODE = TRIM(LS_ZIP_CODE),
								UPDATE_TIMESTAMP = NOW(),
								UPDATE_USER = 'quickstart',
								IS_RESEARCH_STAFF = LS_IS_RESEARCH_STAFF ,
								IS_FACULTY = LS_IS_FACULTY,
								IS_SUPPORT_STAFF = LS_IS_SUPPORT_STAFF,
								IS_OTHER_ACCADEMIC_GROUP = LS_IS_OTHER_ACADEMIC_GROUP,
								STATUS = 'A'
								WHERE UPPER(TRIM(PERSON_ID)) = UPPER(TRIM(LS_PERSON_ID));
			UPDATE PERSON_RT SET STATUS = 'U' WHERE UPPER(TRIM(PERSON_ID)) = UPPER(TRIM(LS_PERSON_ID)) AND UPPER(TRIM(USER_NAME)) = UPPER(TRIM(LS_USER_NAME));
			COMMIT;
		END IF;
	END IF;
END LOOP;
CLOSE PERSON_UPDATION_CURSOR;
END;
SELECT COUNT(*) INTO LI_ROLODEX_INSERTED
FROM PERSON_RT WHERE STATUS = 'I'
AND UPPER(TRIM(RELATIONSHIP)) IN('CONTRACTOR','EXTERNAL RESOURCE');
SELECT COUNT(*) INTO LI_PERSON_INSERTED
FROM PERSON_RT WHERE STATUS = 'I'
AND UPPER(TRIM(RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF');
SELECT COUNT(*) INTO LI_ROLODEX_UPDATED
FROM PERSON_RT WHERE STATUS = 'U'
AND UPPER(TRIM(RELATIONSHIP)) IN('CONTRACTOR','EXTERNAL RESOURCE');
SELECT COUNT(*) INTO LI_PERSON_UPDATED
FROM PERSON_RT WHERE STATUS = 'U'
AND UPPER(TRIM(RELATIONSHIP)) IN('EMPLOYEE','TRAINEE','FACULTYEMPLOYEE','SRSTAFF');
INSERT INTO PERSON_FEED_TEST_MATRIX(TOTAL_FILE_COUNT,TOTAL_PERSON_COUNT,TOTAL_ROLODEX_COUNT,
PERSON_TO_BE_INSERTED,PERSON_INSERTED,
PERSON_TO_BE_UPDATED,PERSON_UPDATED,
ROLODEX_TO_BE_INSERTED,ROLODEX_INSERTED,
ROLODEX_TO_BE_UPDATED,ROLODEX_UPDATED,
STATUS)
VALUES(LI_TOTAL_FILE_COUNT,LI_TOTAL_PERSON_COUNT,LI_TOTAL_ROLODEX_COUNT,
LI_PERSON_TO_BE_INSERTED,LI_PERSON_INSERTED,
LI_PERSON_TO_BE_UPDATED,LI_PERSON_UPDATED,
LI_ROLODEX_TO_BE_INSERTED,LI_ROLODEX_INSERTED,
LI_ROLODEX_TO_BE_UPDATED,LI_ROLODEX_UPDATED,
IF((
(LI_PERSON_TO_BE_INSERTED = LI_PERSON_INSERTED)
AND (LI_ROLODEX_TO_BE_INSERTED = LI_ROLODEX_INSERTED)
AND (LI_ROLODEX_TO_BE_UPDATED = LI_ROLODEX_UPDATED)
AND (LI_PERSON_TO_BE_UPDATED = LI_PERSON_UPDATED)
AND (LI_TOTAL_FILE_COUNT = (LI_PERSON_INSERTED+LI_PERSON_UPDATED+LI_ROLODEX_INSERTED+LI_ROLODEX_UPDATED))
),"SUCCESS","FAILED"));
commit;
DELETE FROM PERSON_RT WHERE PERSON_ID NOT IN (SELECT PERSON_ID FROM PERSON_FEED_ERROR_LOG);
SELECT COUNT(1) INTO LI_FAILED FROM PERSON_RT;
IF LI_FAILED > 0 THEN
	SELECT 'FALSE' AS RESULT;
ELSE
	SELECT 'TRUE' AS RESULT;
END IF;
END;
UPDATE ROLODEX_ID_GENERATOR set next_val = (SELECT IFNULL(MAX(ROLODEX_ID),0)+1 FROM ROLODEX);
SET SQL_SAFE_UPDATES =1;
END
$$
DELIMITER ;
