-- `FN_CHECK_USER_HAS_RIGHT_IN_DOC`; 

CREATE FUNCTION FN_CHECK_USER_HAS_RIGHT_IN_DOC(
AV_MODULE_CODE	int(3),
AV_MODULE_ITEM_ID	VARCHAR(22),
AV_RIGHT_NAME VARCHAR(100),
AV_PERSON_ID VARCHAR(40)

) RETURNS varchar(6)
    DETERMINISTIC
BEGIN

DECLARE LI_FLAG INT(2);
DECLARE LS_FLAG INT(2);
DECLARE LS_LEAD_UNIT varchar(50);
DECLARE GC_LEAD_UNIT varchar(50);

IF AV_MODULE_CODE = 1 THEN
	SELECT COUNT(1) INTO LI_FLAG FROM AWARD_PERSON_ROLES T1
	INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
	INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
	WHERE T1.AWARD_ID = AV_MODULE_ITEM_ID AND T3.RIGHT_NAME = AV_RIGHT_NAME AND T1.PERSON_ID = AV_PERSON_ID;
	IF LI_FLAG > 0 THEN
		RETURN 'TRUE';	
	ELSE
		RETURN 'FALSE';
	END IF;

ELSEIF AV_MODULE_CODE = 3 AND AV_RIGHT_NAME = 'VIEW_PRIVATE_COMMENTS' THEN
	SELECT HOME_UNIT_NUMBER INTO LS_LEAD_UNIT FROM EPS_PROPOSAL WHERE 
	PROPOSAL_ID = AV_MODULE_ITEM_ID;
	
SELECT  COUNT(1)
INTO LS_FLAG FROM  EPS_PROPOSAL
WHERE  PROPOSAL_ID = AV_MODULE_ITEM_ID  AND GRANT_HEADER_ID IS NOT NULL;
    
    IF LS_FLAG > 0 THEN 
		SELECT COUNT(1) INTO LS_FLAG FROM GRANT_CALL_HEADER T1
		INNER JOIN EPS_PROPOSAL T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
		WHERE T2.PROPOSAL_ID = AV_MODULE_ITEM_ID
		AND T1.HOME_UNIT_NUMBER <> (SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = 'ROOT_UNIT') ;
		
	END IF;
	
	IF LS_FLAG = 0 THEN 
		SELECT  COUNT(1) INTO LI_FLAG
        FROM
        PERSON_ROLES PR JOIN 
        (SELECT ROLE_ID,RT.RIGHT_NAME 
           FROM ROLE_RIGHTS RR,
                RIGHTS RT
            WHERE RR.RIGHT_ID = RT.RIGHT_ID
              AND RT.RIGHT_NAME = AV_RIGHT_NAME
        ) RLE ON RLE.ROLE_ID = PR.ROLE_ID
        WHERE PR.PERSON_ID = AV_PERSON_ID
          AND (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1
                                                                 FROM UNIT_WITH_CHILDREN 
                                                                                  WHERE UNIT_NUMBER = PR.UNIT_NUMBER
																				  AND CHILD_UNIT_NUMBER = LS_LEAD_UNIT
             ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT )
            );
		IF LI_FLAG > 0 THEN
		RETURN 'TRUE';
	END IF;

			SELECT 
    COUNT(1)
INTO LI_FLAG FROM EPS_PROPOSAL_PERSON_ROLES T1
        INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
        INNER JOIN
    RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
WHERE
    T1.PROPOSAL_ID = AV_MODULE_ITEM_ID
        AND T1.PERSON_ID = AV_PERSON_ID
        AND T3.RIGHT_NAME = AV_RIGHT_NAME;
			
			IF LI_FLAG > 0 THEN
		RETURN 'TRUE';	
	END IF;
		
	ELSE -- IF LINKED WITH GRANT CALL
	
		
		SELECT  COUNT(1) INTO LI_FLAG
        FROM
        PERSON_ROLES PR JOIN
        (SELECT ROLE_ID,RT.RIGHT_NAME 
           FROM ROLE_RIGHTS RR,
                RIGHTS RT
            WHERE RR.RIGHT_ID = RT.RIGHT_ID
              AND RT.RIGHT_NAME = AV_RIGHT_NAME
        ) RLE ON RLE.ROLE_ID = PR.ROLE_ID 
        WHERE PR.PERSON_ID = AV_PERSON_ID
          AND (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1
                                                                 FROM UNIT_WITH_CHILDREN 
                                                                                  WHERE UNIT_NUMBER = PR.UNIT_NUMBER
																				  AND CHILD_UNIT_NUMBER = LS_LEAD_UNIT
             ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT )
            );	
			
			IF LI_FLAG > 0 THEN
		RETURN 'TRUE';	
	END IF;

			SELECT 
    COUNT(1)
INTO LI_FLAG FROM
    EPS_PROPOSAL_PERSON_ROLES T1
        INNER JOIN
    ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
        INNER JOIN
    RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
WHERE
    T1.PROPOSAL_ID = AV_MODULE_ITEM_ID
        AND T1.PERSON_ID = AV_PERSON_ID
        AND T3.RIGHT_NAME = AV_RIGHT_NAME;
			
			IF LI_FLAG > 0 THEN
		RETURN 'TRUE';	
	END IF;
	
	SELECT  G1.HOME_UNIT_NUMBER INTO GC_LEAD_UNIT
        FROM EPS_PROPOSAL EPS1 INNER JOIN
            GRANT_CALL_HEADER G1 ON EPS1.GRANT_HEADER_ID = G1.GRANT_HEADER_ID
        WHERE EPS1.PROPOSAL_ID = AV_MODULE_ITEM_ID;
	
	IF GC_LEAD_UNIT IS NOT NULL THEN
			SELECT  COUNT(1) INTO LI_FLAG
        FROM
        PERSON_ROLES PR JOIN
        (SELECT ROLE_ID,RT.RIGHT_NAME 
           FROM ROLE_RIGHTS RR,
                RIGHTS RT
            WHERE RR.RIGHT_ID = RT.RIGHT_ID
              AND RT.RIGHT_NAME = AV_RIGHT_NAME
        ) RLE ON RLE.ROLE_ID = PR.ROLE_ID AND PR.ROLE_ID = 100
        WHERE PR.PERSON_ID = AV_PERSON_ID
          AND (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1
                                                                 FROM UNIT_WITH_CHILDREN 
                                                                                  WHERE UNIT_NUMBER = PR.UNIT_NUMBER
																				  AND CHILD_UNIT_NUMBER = GC_LEAD_UNIT
             ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = GC_LEAD_UNIT )
            );
											
						IF LI_FLAG > 0 THEN
				RETURN 'TRUE';	
			END IF;		
	END IF;
	END IF;
	RETURN 'FALSE';
	END IF;
END
