CREATE FUNCTION `FN_EVALUATE_RULE`(
    AV_MODULE_CODE INT,
    AV_SUBMODULE_CODE INT,
    AV_MODULE_ITEM_KEY VARCHAR(20),
    AV_RULE_ID INT,
    AV_LOGGING_PERSON_ID VARCHAR(40),
    AV_UPDATE_USER VARCHAR(60),
    AV_SUB_MODULE_ITEM_KEY VARCHAR(20)
) RETURNS int
    NO SQL
    DETERMINISTIC
BEGIN

   DECLARE result INT;
   
    
     CALL RULE_EVALUATION_FOR_FN(
        AV_MODULE_CODE,
        AV_MODULE_CODE,
        AV_SUBMODULE_CODE,
        AV_MODULE_ITEM_KEY,
        AV_RULE_ID,
        AV_LOGGING_PERSON_ID,
        AV_UPDATE_USER,
        AV_SUB_MODULE_ITEM_KEY,
        result
    );

    RETURN result;
END
