-- `FN_GET_UNIT_HIERARCHY_LEVEL`; 

CREATE FUNCTION `FN_GET_UNIT_HIERARCHY_LEVEL`(AV_UNIT_NUMBER  VARCHAR(50)) RETURNS int(11)
    DETERMINISTIC
BEGIN
 DECLARE LVL INT;
 DECLARE LS_UNIT_NUMBER VARCHAR(50); 
  SELECT AV_UNIT_NUMBER INTO LS_UNIT_NUMBER FROM DUAL;
 SET LVL = 1;
   REPEAT
       SET LVL = LVL + 1;
		SELECT PARENT_UNIT_NUMBER INTO LS_UNIT_NUMBER 
        FROM UNIT 
        WHERE UNIT_NUMBER = LS_UNIT_NUMBER;
     
      UNTIL  LS_UNIT_NUMBER=(SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = 'ROOT_UNIT') OR LS_UNIT_NUMBER IS NULL END REPEAT;
   RETURN LVL;
END
