INSERT INTO eps_proposal_document_status (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Active','2021-06-10 14:26:00','admin');
INSERT INTO eps_proposal_document_status (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Admin Correction','2021-06-10 14:26:00','admin');
INSERT INTO eps_proposal_document_status (DOCUMENT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Archive','2021-06-10 14:26:00','admin');
