INSERT INTO eps_proposal_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,CAN_MERGE_TO_IP) VALUES (1,'New',UTC_TIMESTAMP(),'fibiuser','Y','N');
INSERT INTO eps_proposal_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,CAN_MERGE_TO_IP) VALUES (2,'Resubmission','2025-03-26 14:11:35','admin','Y','Y');
INSERT INTO eps_proposal_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,CAN_MERGE_TO_IP) VALUES (3,'Renewal',UTC_TIMESTAMP(),'fibiuser','Y','N');
INSERT INTO eps_proposal_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,CAN_MERGE_TO_IP) VALUES (4,'Cost Extension',UTC_TIMESTAMP(),'fibiuser','Y','N');
INSERT INTO eps_proposal_type (TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,CAN_MERGE_TO_IP) VALUES (5,'Revision',UTC_TIMESTAMP(),'fibiuser','N','N');

INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('6', 'Task Order', '2024-08-01 12:20:38', 'fibi_admin', 'N', 'N');
INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('500', 'New - Change/Corrected', '2024-08-01 12:20:38', 'fibi_admin', 'N', 'N');
INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('501', 'Pre Proposal', '2024-08-01 12:20:38', 'fibi_admin', 'Y', 'N');
INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('502', 'Supplement-Changed/Corrected', '2024-08-01 12:20:38', 'fibi_admin', 'Y', 'N');
INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('503', 'Resubmission-Changed/Corrected', '2024-08-01 12:20:38', 'fibi_admin', 'N', 'N');
INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('504', 'Budget-SOW Update', '2024-08-01 12:20:38', 'fibi_admin', 'Y', 'N');
INSERT INTO eps_proposal_type (TYPE_CODE, DESCRIPTION, UPDATE_TIMESTAMP, UPDATE_USER, IS_ACTIVE, CAN_MERGE_TO_IP) VALUES ('505', 'Renewal-Changed/Corrected', '2024-08-01 12:20:38', 'fibi_admin', 'N', 'N');
