-- `UPDATE_OLD_SR_HEADER_VALUES`; 

CREATE PROCEDURE `UPDATE_OLD_SR_HEADER_VALUES`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE LS_MODULE_ITEM_KEY VARCHAR(12);
DECLARE C1 CURSOR FOR 
	SELECT MODULE_ITEM_KEY FROM SR_HEADER WHERE CREATE_TIMESTAMP <'<Specify the timestamp to update the datas>' AND MODULE_CODE = 1 AND MODULE_ITEM_KEY IS NOT NULL AND ORIGINATING_MODULE_ITEM_KEY IS NULL;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE LS_AWARD_NUMBER VARCHAR(20);
	DECLARE LI_SEQUENCE_NUMBER INT;
	DECLARE LI_AWARD_ID INT;
	DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
	FETCH C1 INTO LS_MODULE_ITEM_KEY;
	SELECT DISTINCT AWARD_NUMBER INTO LS_AWARD_NUMBER FROM AWARD WHERE AWARD_ID = LS_MODULE_ITEM_KEY;
    SELECT AWARD_ID INTO LI_AWARD_ID FROM AWARD WHERE SEQUENCE_NUMBER = 
    (SELECT (SEQUENCE_NUMBER)+1 FROM AWARD WHERE AWARD_ID = LS_MODULE_ITEM_KEY) AND AWARD_NUMBER = LS_AWARD_NUMBER; 
	UPDATE SR_HEADER SET ORIGINATING_MODULE_ITEM_KEY = LI_AWARD_ID WHERE MODULE_ITEM_KEY = LS_MODULE_ITEM_KEY;
IF DONE THEN
	LEAVE LOOP1;
	END IF;
END; 
END LOOP;
CLOSE C1;
END
