DELIMITER $$
CREATE DEFINER=`ncbsfibi`@`%` PROCEDURE `AWARD_CLOSURE_REMAINDER`(AV_DAYS INT)
BEGIN
SELECT DISTINCT
       0 AS SUB_MODULE_ITEM_KEY,
       T1.AWARD_ID AS MODULE_ITEM_KEY,
       1 AS MODULE_CODE,
       0 AS SUB_MODULE_CODE,
       T1.TITLE AS AWARD_TITLE,
       T1.AWARD_NUMBER,
       S.SPONSOR_NAME AS SPONSOR,
       P.FULL_NAME AS PRINCIPAL_INVESTIGATOR,
       T1.FINAL_EXPIRATION_DATE AS AWARD_END_DATE,
       T1.SPONSOR_AWARD_NUMBER
FROM AWARD T1
LEFT JOIN SPONSOR S ON S.SPONSOR_CODE = T1.SPONSOR_CODE
INNER JOIN AWARD_PERSONS AP ON T1.AWARD_ID = AP.AWARD_ID AND AP.PERSON_ROLE_ID = 3
INNER JOIN PERSON P ON AP.PERSON_ID = P.PERSON_ID
  WHERE DATE(T1.FINAL_EXPIRATION_DATE) = DATE(DATE_ADD(UTC_TIMESTAMP(), INTERVAL AV_DAYS DAY))
  AND T1.AWARD_SEQUENCE_STATUS = 'ACTIVE';
END
$$
DELIMITER ;
