DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE_INSTITUTE_PROPOSAL_DATA`(AV_PROPOSAL_ID_1 INT,AV_PROPOSAL_ID_2 INT)
BEGIN
DECLARE LI_PROPOSAL_ID  INT;
DECLARE LS_ERROR_MSG	VARCHAR(1000);
DECLARE LS_ERROR_FLAG  VARCHAR(10);
DECLARE LS_PROPOSAL_NUMBER VARCHAR(100);
DECLARE LS_TITLE VARCHAR(1000);
DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
					SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
					SELECT @full_error INTO LS_ERROR_MSG;
					 SELECT LS_ERROR_MSG;
				END;
				BEGIN
					DECLARE DONE1 INT DEFAULT FALSE;
					DECLARE CUR_PROPOSAL_DATA CURSOR FOR
					SELECT PROPOSAL_ID,PROPOSAL_NUMBER FROM proposal  WHERE PROPOSAL_ID  BETWEEN AV_PROPOSAL_ID_1 and AV_PROPOSAL_ID_2
                    ;
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
					OPEN CUR_PROPOSAL_DATA;
					INSERT_PROPOSAL_LOOP: LOOP
					FETCH CUR_PROPOSAL_DATA INTO
					 LI_PROPOSAL_ID,LS_PROPOSAL_NUMBER;
					IF DONE1 THEN
						LEAVE INSERT_PROPOSAL_LOOP;
					END IF;
					   DELETE from inbox where MODULE_ITEM_KEY in (LI_PROPOSAL_ID);
						DELETE FROM proposal_review_comment WHERE REVIEW_ID IN (
						SELECT REVIEW_ID FROM proposal_review WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM PROPOSAL WHERE PROPOSAL_ID = LI_PROPOSAL_ID)) ;
						DELETE FROM proposal_review_attachment WHERE REVIEW_COMMENT_ID IN (
						SELECT REVIEW_COMMENT_ID FROM proposal_review_comment WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM PROPOSAL WHERE PROPOSAL_ID = LI_PROPOSAL_ID)) ;
						DELETE FROM proposal_persons_attachmnt WHERE PROPOSAL_PERSON_ID IN (
						SELECT PROPOSAL_PERSON_ID FROM proposal_persons WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID  = LI_PROPOSAL_ID));
						DELETE FROM proposal_review WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM eps_proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE from proposal_version_history WHERE ACTIVE_PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_action_log WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID) ;
						DELETE FROM prop_person_units WHERE PROPOSAL_PERSON_ID IN (
						SELECT PROPOSAL_PERSON_ID FROM proposal_persons WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID =LI_PROPOSAL_ID));
                        DELETE FROM budget_persons WHERE BUDGET_HEADER_ID IN(
						SELECT BUDGET_HEADER_ID FROM budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID)) );
						DELETE FROM budget_person_detail WHERE BUDGET_DETAILS_ID IN (
						SELECT BUDGET_DETAILS_ID FROM budget_detail WHERE BUDGET_HEADER_ID IN(
						SELECT BUDGET_HEADER_ID FROM budget_header WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID)
						));
						DELETE FROM budget_det_cal_amt WHERE BUDGET_DETAILS_ID IN (
						SELECT BUDGET_DETAILS_ID FROM budget_detail WHERE BUDGET_PERIOD_ID IN(
						SELECT BUDGET_PERIOD_ID FROM BUDGET_PERIOD WHERE BUDGET_HEADER_ID IN(
						SELECT BUDGET_HEADER_ID FROM budget_header WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID)
						)));
						DELETE FROM budget_detail WHERE BUDGET_PERIOD_ID IN(
						SELECT BUDGET_PERIOD_ID FROM BUDGET_PERIOD WHERE BUDGET_HEADER_ID IN(
						SELECT BUDGET_HEADER_ID FROM budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID))
						));
						DELETE FROM BUDGET_PERIOD WHERE BUDGET_HEADER_ID IN(
						SELECT BUDGET_HEADER_ID FROM budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID))
						);
						DELETE FROM budget_modular WHERE BUDGET_HEADER_ID IN (
						SELECT BUDGET_HEADER_ID FROM budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID)));
                         DELETE FROM budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID IN (LI_PROPOSAL_ID));
						 DELETE FROM quest_answer_attachment WHERE QUESTIONNAIRE_ANSWER_ID IN(
						SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (
						SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer_header WHERE MODULE_ITEM_KEY IN (LI_PROPOSAL_ID)));
						DELETE FROM quest_answer WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (
						SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer_header WHERE MODULE_ITEM_KEY IN (LI_PROPOSAL_ID));
						DELETE FROM quest_table_answer WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (
						SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer_header WHERE MODULE_ITEM_KEY IN (LI_PROPOSAL_ID));
						DELETE FROM quest_answer_header WHERE MODULE_ITEM_KEY IN (LI_PROPOSAL_ID);
						DELETE FROM proposal_sponsors WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM  award_funding_proposals WHERE PROPOSAL_ID IN (
                         SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_special_review WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_resrch_areas WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID) ;
						DELETE FROM proposal_project_team WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_persons WHERE   PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID =LI_PROPOSAL_ID);
						DELETE FROM proposal_keywords WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_attachments WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_admin_details WHERE INST_PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM ip_budget_period WHERE  BUDGET_HEADER_ID IN(SELECT BUDGET_HEADER_ID FROM ip_budget_header WHERE PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID));
						DELETE FROM ip_budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM ip_budget_header WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal_comments WHERE PROPOSAL_ID IN (
						SELECT PROPOSAL_ID FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID);
						DELETE FROM proposal WHERE PROPOSAL_ID = LI_PROPOSAL_ID;
					END LOOP;
					CLOSE CUR_PROPOSAL_DATA;
				END;
END
$$
DELIMITER ;
