DELIMITER $$
CREATE  FUNCTION `FN_AWD_MANPOWER_CUTOFFDATE`(
AV_AWARD_ID DECIMAL(22,0)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_CUT_OFF_DATE INT;
DECLARE LI_CHARGE_START_DATE INT;
DECLARE LI_RESOURSEWITHCUTOFFDATE INT;
DECLARE LS_CUT_OFF_DATE INT;
SET LI_RESOURSEWITHCUTOFFDATE = 0;
SELECT CONFIGURATION_VALUE INTO LS_CUT_OFF_DATE
FROM MANPOWER_CONFIGURATION_DATA WHERE CONFIGURATION_KEY = 'MANPOWER_CUT_OFF_DATE';
SELECT COUNT(*) INTO LI_RESOURSEWITHCUTOFFDATE FROM AWARD_MANPOWER_RESOURCE WHERE AWARD_MANPOWER_ID IN(
SELECT AWARD_MANPOWER_ID FROM AWARD_MANPOWER WHERE AWARD_ID = AV_AWARD_ID)
AND ( DAY(CHARGE_START_DATE) = LS_CUT_OFF_DATE )
AND ( DAY(SYSDATE()) = LS_CUT_OFF_DATE );
	IF LI_RESOURSEWITHCUTOFFDATE <> 0 THEN
		RETURN 'TRUE';
	ELSE
		RETURN 'FALSE';
	END IF;
END
$$
DELIMITER ;
