DELIMITER $$
CREATE  PROCEDURE `GET_AGREEMENT_DASHBOARD`(
AV_AGREEMENT_REQUEST_ID varchar(20),
AV_TITLE                varchar(1000),
AV_REQUESTOR_PERSON_ID    varchar(40),
AV_CATEGORY_CODE        VARCHAR(255),
AV_TYPE_CODE            VARCHAR(255),
AV_STATUS_CODE          VARCHAR(255),
AV_PERSON_ID            VARCHAR(255),
AV_SORT_TYPE            VARCHAR(255),
AV_PAGED                INT,
AV_LIMIT                INT,
AV_TAB_TYPE             VARCHAR(255),
AV_UNLIMITED            VARCHAR(255),
AV_TYPE                 VARCHAR(255),
AV_UNIT_NUMBER			VARCHAR(255),
AV_ORGANIZATION 		VARCHAR(255),
AV_NEGO_PERSON_ID		VARCHAR(255),
AV_PI_PERSON_ID			VARCHAR(255),
AV_CAT_PERSON_ID		VARCHAR(255),
AV_STO_PERSON_ID 		VARCHAR(255),
AV_CA_PERSON_ID			VARCHAR(255),
AV_REVIEW_STATUS		VARCHAR(255),
AV_ORGANIZATION_TYPE 	VARCHAR(255),
AV_ADMIN_PERSON_ID 		VARCHAR(255),
AV_START_DATE 		 VARCHAR(255),
AV_END_DATE		 VARCHAR(255),
AV_PROJECT_ID		 VARCHAR(255),
AV_ADMIN_GROUP_ID     VARCHAR(255)
)
BEGIN
DECLARE LS_DYN_SQL 				LONGTEXT;
DECLARE LS_FILTER_CONDITION 	LONGTEXT;
DECLARE LS_OFFSET_CONDITION 	VARCHAR(600);
DECLARE LS_OFFSET 				INT(11);
DECLARE LS_TAB_QUERY 			LONGTEXT;
DECLARE LS_JOIN_CONDITION 		LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST 	LONGTEXT;
DECLARE LS_FILTER_CONDITION1 	LONGTEXT;
DECLARE LS_FILTER_CONDITION2 	LONGTEXT;
DECLARE LS_FILTER_CONDITION3 	LONGTEXT;
DECLARE LS_FILTER_CONDITION4 	LONGTEXT;
DECLARE LS_FILTER_CONDITION5 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST1 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST2		LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST3 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST4 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST5 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST6 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST7 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST8 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST9 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST10 	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST11	LONGTEXT;
DECLARE LS_SELECTED_FIELD_LIST12	LONGTEXT;
DECLARE LS_FILTER_CONDITION_NEW		LONGTEXT;
DECLARE LI_FROM_ROW				INT(10);
DECLARE LI_TO_ROW				INT(10);
DECLARE LS_SORT_TYPE            VARCHAR(1000);
DECLARE IS_UNIT_ADMIN INT(11);
DECLARE IS_DEPT_ADMIN INT(11);
DECLARE IS_GROUP_ADMIN INT(11);
DECLARE LS_ADMIN_GROUP_CONDITION LONGTEXT;
DECLARE LS_FILTER_TEMPLATE_CONDITION 	LONGTEXT;
SET LS_FILTER_CONDITION ='';
SET LS_FILTER_CONDITION_NEW ='';
SET LS_FILTER_CONDITION1 ='';
SET LS_FILTER_CONDITION2 ='';
SET LS_FILTER_CONDITION3 ='';
SET LS_FILTER_CONDITION4 ='';
SET LS_FILTER_CONDITION5 	='';
SET LS_TAB_QUERY 	='';
SET LS_ADMIN_GROUP_CONDITION ='';
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
SET LS_FILTER_TEMPLATE_CONDITION ='T.AGREEMENT_SEQUENCE_STATUS <> ''TEMPLATE''';
SET LS_FILTER_CONDITION2 = CONCAT(LS_FILTER_CONDITION2,' (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_ADMIN))');
SET LS_FILTER_CONDITION3 = CONCAT(LS_FILTER_CONDITION3 ,' (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)OR (T1.REQUESTOR_PERSON_ID =''', AV_PERSON_ID ,''')
																			  OR (T6.PEOPLE_TYPE_ID IN (3) AND T6.PERSON_ID=''', AV_PERSON_ID ,'''))');
SET LS_FILTER_CONDITION4 = CONCAT(LS_FILTER_CONDITION4 ,' (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP))');
SET LS_FILTER_CONDITION5 = CONCAT(LS_FILTER_CONDITION5 ,' (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)OR (T1.REQUESTOR_PERSON_ID =''', AV_PERSON_ID ,''')
																			  OR (T6.PERSON_ID=''', AV_PERSON_ID ,'''))');
SET LS_SELECTED_FIELD_LIST1 = '(SELECT FULL_NAME FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 2))AS NEGO_FULL_NAME';
SET LS_SELECTED_FIELD_LIST2 = ',(SELECT FULL_NAME FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 3)) AS PI_FULL_NAME';
SET LS_SELECTED_FIELD_LIST3 = ',(SELECT FULL_NAME FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 5))AS CAT_FULL_NAME';
SET LS_SELECTED_FIELD_LIST4 = ',(SELECT FULL_NAME  FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 6)) AS STO_FULL_NAME';
SET LS_SELECTED_FIELD_LIST5 = ',(SELECT FULL_NAME FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 7)) AS CA_FULL_NAME';
SET LS_SELECTED_FIELD_LIST6 = ',(SELECT IFNULL (PERSON_ID, ROLODEX_ID) AS PERSON_ID FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 2))AS NEGO_PERSON_ID';
SET LS_SELECTED_FIELD_LIST7 = ',(SELECT IFNULL (PERSON_ID, ROLODEX_ID) AS PERSON_ID FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 3)) AS PI_PERSON_ID';
SET LS_SELECTED_FIELD_LIST8 = ',(SELECT IFNULL (PERSON_ID, ROLODEX_ID) AS PERSON_ID FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 5))AS CAT_PERSON_ID';
SET LS_SELECTED_FIELD_LIST9 = ',(SELECT IFNULL (PERSON_ID, ROLODEX_ID) AS PERSON_ID FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 6)) AS STO_PERSON_ID';
SET LS_SELECTED_FIELD_LIST10 = ',(SELECT IFNULL (PERSON_ID, ROLODEX_ID) AS PERSON_ID FROM AGREEMENT_PEOPLE WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_PEOPLE_ID =
(select max(AGREEMENT_PEOPLE_ID) FROM AGREEMENT_PEOPLE WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND PEOPLE_TYPE_ID = 7)) AS CA_PERSON_ID';
SET LS_SELECTED_FIELD_LIST11 = ',(SELECT SPONSOR_NAME FROM AGREEMENT_SPONSOR WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_SPONSOR_ID =
(select max(AGREEMENT_SPONSOR_ID) FROM AGREEMENT_SPONSOR WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND AGREEMENT_SPONSOR_TYPE_CODE = 1)) AS ORGANIZATION';
SET LS_SELECTED_FIELD_LIST12 = ',(SELECT UPDATE_TIMESTAMP FROM AGREEMENT_ACTION_LOG WHERE
AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND ACTION_LOG_ID =
(select min(ACTION_LOG_ID) FROM AGREEMENT_ACTION_LOG WHERE AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID AND ACTION_TYPE_CODE = 2)) AS SUBMITTED_TIMESTAMP ';
  IF AV_TYPE = 'A'   THEN
		IF AV_AGREEMENT_REQUEST_ID IS NOT NULL AND AV_AGREEMENT_REQUEST_ID <> '' THEN
		  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' LOWER(T.AGREEMENT_REQUEST_ID) LIKE  ''%',LOWER(AV_AGREEMENT_REQUEST_ID),'%'' AND ');
		END IF;
		IF AV_TITLE IS NOT NULL AND AV_TITLE <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' LOWER(T.TITLE ) LIKE  ''%',LOWER(AV_TITLE),'%'' AND ');
        END IF;
		IF AV_REQUESTOR_PERSON_ID IS NOT NULL AND AV_REQUESTOR_PERSON_ID <> ''  THEN
		 SET LS_FILTER_CONDITION =CONCAT( LS_FILTER_CONDITION,' LOWER(T.REQUESTOR_PERSON_ID ) LIKE ''%',LOWER(AV_REQUESTOR_PERSON_ID),'%'' AND ');
		END IF;
		IF AV_CATEGORY_CODE IS NOT NULL AND AV_CATEGORY_CODE <> ''  THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' T.CATEGORY_CODE IN (',AV_CATEGORY_CODE,') AND ');
		END IF;
	    IF AV_TYPE_CODE IS NOT NULL AND AV_TYPE_CODE <> ''  THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' T.AGREEMENT_TYPE_CODE IN (',AV_TYPE_CODE,') AND ');
		END IF;
	    IF AV_STATUS_CODE IS NOT NULL AND AV_STATUS_CODE <> '' THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' T.AGREEMENT_STATUS_CODE IN (',AV_STATUS_CODE,') AND ');
		END IF;
	   IF AV_UNIT_NUMBER IS NOT NULL AND AV_UNIT_NUMBER <> '' THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' T.UNIT_NUMBER IN (',AV_UNIT_NUMBER,') AND ');
		END IF;
	   IF AV_ORGANIZATION IS NOT NULL AND AV_ORGANIZATION <> '' THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.ORGANIZATION) LIKE  ''%',LOWER(AV_ORGANIZATION),'%'' AND ');
		END IF;
		IF AV_NEGO_PERSON_ID IS NOT NULL AND AV_NEGO_PERSON_ID <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.NEGO_PERSON_ID) LIKE ''%',LOWER(AV_NEGO_PERSON_ID),'%'' AND ');
		END IF;
		IF AV_PI_PERSON_ID IS NOT NULL AND AV_PI_PERSON_ID <> ''THEN
		 SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.PI_PERSON_ID)  LIKE ''%',LOWER(AV_PI_PERSON_ID),'%'' AND ');
		END IF;
		IF AV_CAT_PERSON_ID IS NOT NULL AND AV_CAT_PERSON_ID <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.CAT_PERSON_ID ) LIKE  ''%',LOWER(AV_CAT_PERSON_ID),'%'' AND ');
		END IF;
		IF AV_STO_PERSON_ID IS NOT NULL AND AV_STO_PERSON_ID <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.STO_PERSON_ID ) LIKE  ''%',LOWER(AV_STO_PERSON_ID),'%'' AND ');
		END IF;
		IF AV_CA_PERSON_ID IS NOT NULL AND AV_CA_PERSON_ID <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.CA_PERSON_ID ) LIKE ''%',LOWER(AV_CA_PERSON_ID),'%'' AND ');
		END IF;
    IF AV_REVIEW_STATUS IS NOT NULL  AND AV_REVIEW_STATUS <> '' THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' T.WORKFLOW_STATUS_CODE IN (',AV_REVIEW_STATUS,') AND ');
		END IF;
	IF AV_ORGANIZATION_TYPE IS NOT NULL  AND AV_ORGANIZATION_TYPE <> '' THEN
			SET LS_FILTER_CONDITION_NEW = CONCAT( LS_FILTER_CONDITION_NEW,' AND T20.AGREEMENT_SPONSOR_ID IN (SELECT MAX(AGREEMENT_SPONSOR_ID) FROM AGREEMENT_SPONSOR T21
																						 WHERE T21.AGREEMENT_REQUEST_ID = T20.AGREEMENT_REQUEST_ID AND  T21.AGREEMENT_SPONSOR_TYPE_CODE = 1
															                             AND T21.SPONSOR_CODE IN (SELECT SP1.SPONSOR_CODE FROM SPONSOR SP1
																												  INNER JOIN SPONSOR_TYPE SP2 ON SP1.SPONSOR_TYPE_CODE = SP2.SPONSOR_TYPE_CODE
																						WHERE SP2.SPONSOR_TYPE_CODE IN  (',AV_ORGANIZATION_TYPE,')))' );
		END IF;
	IF AV_ADMIN_PERSON_ID IS NOT NULL AND AV_ADMIN_PERSON_ID <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' LOWER(T.ADMIN_PERSON_ID ) LIKE  ''%',LOWER(AV_ADMIN_PERSON_ID),'%'' AND ');
	END IF;
  	IF (AV_START_DATE IS NOT NULL AND AV_START_DATE <> '') OR (AV_END_DATE IS NOT NULL AND AV_END_DATE <> '') THEN
			IF AV_START_DATE IS NOT NULL AND AV_END_DATE IS NOT NULL THEN
				SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' DATE(T.SUBMITTED_TIMESTAMP ) >=  DATE_FORMAT(''',AV_START_DATE,''',''%Y-%m-%d'') AND TRIM(T.SUBMITTED_TIMESTAMP ) <=  DATE_FORMAT(''',AV_END_DATE,''',''%Y-%m-%d'') AND ');
			END IF;
			IF AV_START_DATE IS NOT NULL AND AV_END_DATE IS NULL  THEN
				SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' DATE(T.SUBMITTED_TIMESTAMP ) >=   DATE_FORMAT(''',AV_START_DATE,''',''%Y-%m-%d'') AND ');
			END IF;
			IF AV_END_DATE IS NOT NULL AND AV_START_DATE IS NULL THEN
				SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' DATE(T.SUBMITTED_TIMESTAMP ) <= DATE_FORMAT(''',AV_END_DATE,''',''%Y-%m-%d'') AND ');
			END IF;
	END IF;
   IF AV_PROJECT_ID IS NOT NULL AND AV_PROJECT_ID <> '' THEN
			SET LS_FILTER_CONDITION_NEW = CONCAT( LS_FILTER_CONDITION_NEW,' AND T1.AGREEMENT_REQUEST_ID IN (SELECT T54.AGREEMENT_REQUEST_ID FROM AGREEMENT_ASSOCIATION_LINK T54
																					 WHERE T54.MODULE_ITEM_KEY LIKE ''%',AV_PROJECT_ID,'%'') ');
	END IF;
    IF AV_ADMIN_GROUP_ID IS NOT NULL AND AV_ADMIN_GROUP_ID <> '' THEN
			SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,'T.ADMIN_GROUP_ID IN (',AV_ADMIN_GROUP_ID,') AND ');
	END IF;
END IF;
		SELECT COUNT(1) INTO IS_UNIT_ADMIN
        FROM
        PERSON_ROLES PR,
        (SELECT ROLE_ID,RT.RIGHT_NAME
           FROM ROLE_RIGHTS RR,
                RIGHTS RT
            WHERE RR.RIGHT_ID = RT.RIGHT_ID
              AND RT.RIGHT_NAME IN (
        'AGREEMENT_ADMINISTRATOR'
    )
        ) RLE
        WHERE PR.PERSON_ID = AV_PERSON_ID AND RLE.ROLE_ID = PR.ROLE_ID;
		SELECT
    COUNT(1)
INTO IS_GROUP_ADMIN FROM
    ROLE_RIGHTS T1
        LEFT JOIN
    RIGHTS T2 ON T1.RIGHT_ID = T2.RIGHT_ID
        LEFT JOIN
    PERSON_ROLES T3 ON T1.ROLE_ID = T3.ROLE_ID
WHERE
    T3.PERSON_ID = AV_PERSON_ID
        AND T2.RIGHT_NAME = 'VIEW_ADMIN_GROUP_AGREEMENT';
				SELECT  COUNT(1) INTO IS_DEPT_ADMIN
        FROM PERSON_ROLES PR,
        (SELECT ROLE_ID,RT.RIGHT_NAME
           FROM ROLE_RIGHTS RR,
                RIGHTS RT
            WHERE RR.RIGHT_ID = RT.RIGHT_ID
              AND RT.RIGHT_NAME IN ('VIEW_ALL_AGREEMENT' , 'MODIFY_ALL_AGREEMENT')
        ) RLE
        WHERE PR.PERSON_ID = AV_PERSON_ID AND RLE.ROLE_ID = PR.ROLE_ID;
		IF AV_TAB_TYPE = 'IN_PROGRESS_AGREEMENTS' THEN
			IF IS_UNIT_ADMIN > 0 THEN
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,' ',LS_FILTER_CONDITION2 ,') AND T1.AGREEMENT_STATUS_CODE = 1 ');
			ELSEIF IS_GROUP_ADMIN > 0 THEN
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,') AND T1.AGREEMENT_STATUS_CODE = 1 ');
			ELSE
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,' ',LS_FILTER_CONDITION3,') AND T1.AGREEMENT_STATUS_CODE = 1 ');
            END IF;
		ELSEIF AV_TAB_TYPE = 'ALL_AGREEMENTS' THEN
			IF IS_UNIT_ADMIN > 0 THEN
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,' ',LS_FILTER_CONDITION2 ,')');
			ELSEIF IS_GROUP_ADMIN > 0 THEN
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,' ',LS_FILTER_CONDITION4 ,')');
			ELSE
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,' ',LS_FILTER_CONDITION3 ,')' );
			END IF;
		ELSEIF AV_TAB_TYPE = 'NEW_SUBMISSIONS' THEN
			IF IS_UNIT_ADMIN > 0 THEN
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,' ',LS_FILTER_CONDITION2 ,') AND T1.AGREEMENT_STATUS_CODE = 7 ');
			ELSE
				SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY,') AND T1.AGREEMENT_STATUS_CODE = 7 ');
			END IF;
		ELSEIF AV_TAB_TYPE = 'MY_PENDING_AGREEMENTS' THEN
					SET  LS_TAB_QUERY = CONCAT(LS_TAB_QUERY ,'WHERE   ((EXISTS (SELECT S1.NEGOTIATION_LOCATION_ID FROM NEGOTIATION_LOCATION S1
																		WHERE S1.NEGOTIATION_ID IN(SELECT S0.NEGOTIATION_ID
																							FROM NEGOTIATION_ASSOCIATION S0
																							WHERE S0.ASSOCIATED_PROJECT_ID  = T1.AGREEMENT_REQUEST_ID
																							AND S0.ASSOCIATION_TYPE_CODE = 4) AND S1.LOCATION_STATUS_CODE in (1,2)
																							AND S1.ASSIGNEE_PERSON_ID=''',AV_PERSON_ID,''')
																							)
																		or (
																		T1.ADMIN_PERSON_ID =''',AV_PERSON_ID,'''
																		)
																		  )	AND  T1.AGREEMENT_STATUS_CODE IN(2,3,6,5) ');
	ELSEIF AV_TAB_TYPE = 'ALL_PENDING_AGREEMENTS' THEN
		IF IS_UNIT_ADMIN > 0 THEN
			SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY ,' (((EXISTS (SELECT S1.NEGOTIATION_LOCATION_ID FROM NEGOTIATION_LOCATION S1
															WHERE S1.NEGOTIATION_ID IN(SELECT S0.NEGOTIATION_ID
																				FROM NEGOTIATION_ASSOCIATION S0
																				WHERE S0.ASSOCIATED_PROJECT_ID  = T1.AGREEMENT_REQUEST_ID
																				AND S0.ASSOCIATION_TYPE_CODE = 4) AND S1.LOCATION_STATUS_CODE in (1,2)
																				))
													  or (
													    T1.AGREEMENT_REQUEST_ID in (SELECT AGREEMENT_REQUEST_ID
																					FROM AGREEMENT_PEOPLE
																					WHERE PEOPLE_TYPE_ID IN (2,5,6,7))
													   )
															or (
																T1.AGREEMENT_REQUEST_ID in (SELECT T9.MODULE_ITEM_ID FROM WORKFLOW T9
																INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
																WHERE T9.MODULE_ITEM_ID = T1.AGREEMENT_REQUEST_ID
																AND T9.MODULE_CODE = 13 AND T9.IS_WORKFLOW_ACTIVE = ''Y''
																AND T10.APPROVAL_STATUS = ''W''
																) and T1.AGREEMENT_STATUS_CODE not in (6,3,4,8,9,10)
																)
															or (
															T1.ADMIN_PERSON_ID IS NOT NULL
															   )
															  )
															  AND T1.AGREEMENT_STATUS_CODE IN(2,3,6,5))
															  OR (T1.UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_ADMIN))) AND T1.AGREEMENT_STATUS_CODE IN(2,3,6,5)');
		ELSE
			SET LS_TAB_QUERY = CONCAT(LS_TAB_QUERY ,' AND (((EXISTS (SELECT S1.NEGOTIATION_LOCATION_ID FROM NEGOTIATION_LOCATION S1
															WHERE S1.NEGOTIATION_ID IN(SELECT S0.NEGOTIATION_ID
																				FROM NEGOTIATION_ASSOCIATION S0
																				WHERE S0.ASSOCIATED_PROJECT_ID  = T1.AGREEMENT_REQUEST_ID
																				AND S0.ASSOCIATION_TYPE_CODE = 4) AND S1.LOCATION_STATUS_CODE in (1,2)
																				)
																				)
													  or (
													    T1.AGREEMENT_REQUEST_ID in (SELECT AGREEMENT_REQUEST_ID FROM AGREEMENT_PEOPLE WHERE PEOPLE_TYPE_ID IN (2,5,6,7)) AND
														T1.AGREEMENT_STATUS_CODE  NOT IN(4,8,9,10)
													   )
															or (
																T1.AGREEMENT_REQUEST_ID in (SELECT T9.MODULE_ITEM_ID FROM WORKFLOW T9
																INNER JOIN WORKFLOW_DETAIL T10 ON T9.WORKFLOW_ID = T10.WORKFLOW_ID
																WHERE T9.MODULE_ITEM_ID = T1.AGREEMENT_REQUEST_ID
																AND T9.MODULE_CODE = 13 AND T9.IS_WORKFLOW_ACTIVE = ''Y''
																AND T10.APPROVAL_STATUS = ''W''
																)
																)
															or (
															T1.ADMIN_PERSON_ID IS NOT NULL
															)))) AND T1.AGREEMENT_STATUS_CODE IN(2,3,6,5) ');
		END IF;
	END IF;
	IF AV_SORT_TYPE IS NULL THEN
		SET LS_SORT_TYPE = CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
	ELSE
		SET LS_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
	END IF;
    IF AV_UNLIMITED = TRUE THEN
        SET LS_OFFSET_CONDITION = '';
ELSE
        SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
END IF;
	IF (LS_FILTER_CONDITION IS NOT NULL AND TRIM(LS_FILTER_CONDITION) <> '' ) THEN
		SET LS_FILTER_CONDITION = CONCAT(' WHERE ',LS_FILTER_CONDITION);
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION ,LS_FILTER_TEMPLATE_CONDITION);
SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) INTO LS_FILTER_CONDITION FROM DUAL;
  ELSE
		SET LS_FILTER_CONDITION = CONCAT(' WHERE ', LS_FILTER_TEMPLATE_CONDITION);
	END IF;
	IF IS_GROUP_ADMIN > 0 AND (AV_TAB_TYPE <> 'MY_PENDING_AGREEMENTS') THEN
	 SET LS_ADMIN_GROUP_CONDITION =  CONCAT(' LEFT JOIN ADMIN_GROUP T50 ON T1.ADMIN_GROUP_ID = T50.ADMIN_GROUP_ID
                                    WHERE (T50.ROLE_ID IN (SELECT T51.ROLE_ID FROM ROLE_RIGHTS T51
																	LEFT JOIN RIGHTS T52 ON T51.RIGHT_ID = T52.RIGHT_ID
																	LEFT JOIN PERSON_ROLES T53 ON T51.ROLE_ID = T53.ROLE_ID
																	WHERE T53.PERSON_ID = ''', AV_PERSON_ID ,''' AND T52.RIGHT_NAME = ''VIEW_ADMIN_GROUP_AGREEMENT'')');
							IF IS_UNIT_ADMIN > 0 OR (IS_GROUP_ADMIN > 0 AND  AV_TAB_TYPE =  'ALL_AGREEMENTS')THEN
                                SET LS_ADMIN_GROUP_CONDITION =  CONCAT(LS_ADMIN_GROUP_CONDITION,'OR ');
	                        END IF;
    ELSEIF  LS_ADMIN_GROUP_CONDITION = '' AND (AV_TAB_TYPE <> 'MY_PENDING_AGREEMENTS') THEN
     SET LS_TAB_QUERY = CONCAT(' WHERE (', LS_TAB_QUERY);
    END IF;
	SET ls_dyn_sql = CONCAT('WITH ACCESS_TMP
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_ALL_AGREEMENT'',''MODIFY_ALL_AGREEMENT'')
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_ALL_AGREEMENT'',''MODIFY_ALL_AGREEMENT'')
                            )),
							ACCESS_TMP_ADMIN
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''AGREEMENT_ADMINISTRATOR'')
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''AGREEMENT_ADMINISTRATOR'')
                            )),
							VIEW_ACCESS_TMP_ADMIN
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_AGREEMENT'')
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_ADMIN_GROUP_AGREEMENT'')
                            ))
							');
    SET ls_dyn_sql =CONCAT(ls_dyn_sql,'SELECT * FROM
                                    (
									SELECT
                                        distinct
										T1.AGREEMENT_REQUEST_ID,
                                        T1.TITLE,
                                        T3.DESCRIPTION AS CATEGORY_NAME,
										T2.DESCRIPTION AS STATUS,
										T1.AGREEMENT_STATUS_CODE,
										T4.DESCRIPTION AS TYPE,
										T1.START_DATE,
										T1.REQUESTOR_PERSON_ID,
										T1.REQUESTOR_NAME,
										T1.END_DATE,
										T1.AGREEMENT_TYPE_CODE,
										T1.CATEGORY_CODE,
										T1.CONTRACT_VALUE,
										T1.UNIT_NUMBER,
										T5.UNIT_NAME AS UNIT,
										IFNULL(T1.CURRENCY_CODE, ''USD'') AS CURRENCY_CODE,
										T1.WORKFLOW_STATUS_CODE,
										T1.ADMIN_PERSON_NAME,
										T1.ADMIN_PERSON_ID,
										T30.DESCRIPTION AS REVIEW_STATUS,
										S0.NEGOTIATION_ID,
										T1.ADMIN_GROUP_ID,
										T1.UPDATE_TIMESTAMP,
										T1.AGREEMENT_SEQUENCE_STATUS,',LS_SELECTED_FIELD_LIST1,LS_SELECTED_FIELD_LIST2, LS_SELECTED_FIELD_LIST3,LS_SELECTED_FIELD_LIST4,
										LS_SELECTED_FIELD_LIST5,
										LS_SELECTED_FIELD_LIST6,LS_SELECTED_FIELD_LIST7,LS_SELECTED_FIELD_LIST8,LS_SELECTED_FIELD_LIST9,LS_SELECTED_FIELD_LIST10,LS_SELECTED_FIELD_LIST11,
										LS_SELECTED_FIELD_LIST12 ,'
                                     FROM AGREEMENT_HEADER T1
                                    LEFT JOIN AGREEMENT_STATUS T2 ON T2.AGREEMENT_STATUS_CODE = T1.AGREEMENT_STATUS_CODE
                                    LEFT JOIN UNIT T5 ON T1.UNIT_NUMBER = T5.UNIT_NUMBER
									LEFT JOIN AGREEMENT_PEOPLE T6 ON T6.AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID
                                    LEFT JOIN AGREEMENT_TYPE T4 ON T4.AGREEMENT_TYPE_CODE = T1.AGREEMENT_TYPE_CODE
                                    LEFT JOIN AGREEMENT_SPONSOR T20 ON T20.AGREEMENT_REQUEST_ID = T1.AGREEMENT_REQUEST_ID
                                    LEFT JOIN AGREEMENT_WORKFLOW_STATUS T30 ON T1.WORKFLOW_STATUS_CODE = T30.WORKFLOW_STATUS_CODE
                                    LEFT JOIN NEGOTIATION_ASSOCIATION S0 ON T1.AGREEMENT_REQUEST_ID = S0.ASSOCIATED_PROJECT_ID
                                    LEFT JOIN AGREEMENT_CATEGORY T3 ON T1.CATEGORY_CODE = T3.CATEGORY_CODE ',LS_ADMIN_GROUP_CONDITION,LS_TAB_QUERY,LS_FILTER_CONDITION_NEW,' ) T ', LS_FILTER_CONDITION,'',LS_SORT_TYPE,LS_OFFSET_CONDITION);
  SET @QUERY_STATEMENT = LS_DYN_SQL;
 PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
 EXECUTE EXECUTABLE_STAEMENT;
END
$$
DELIMITER ;
