CREATE PROCEDURE `GET_AGREEMENT_DETAILS_FOR_ASSOC`(
    IN AV_STAGE_AGREEMENT_ID INT
)
BEGIN
    SELECT 
        'ID' AS AGREEMENT_REQUEST_ID,
        'Title' AS TITLE,
        'Status' AS STATUS,
        'Principal Investigator' AS PI_FULL_NAME,
        'Lead Unit' AS LEAD_UNIT,
        'Type' AS TYPE,
        'Sponsor' AS SPONSOR
    UNION ALL
    SELECT 
        AGREEMENT_ID AS AGREEMENT_REQUEST_ID,
        TITLE,
        AGREEMENT_STATUS AS STATUS,
        PRINCIPAL_PERSON_FULL_NAME AS PI_FULL_NAME,
		CONCAT(UNIT_NUMBER, ' - ', UNIT_NAME) AS LEAD_UNIT,
        AGREEMENT_TYPE AS TYPE,
        CONCAT(SPONSOR_CODE, ' - ', SPONSOR_NAME) AS SPONSOR
    FROM SR_INT_STAGE_AGREEMENT
    WHERE AGREEMENT_ID = AV_STAGE_AGREEMENT_ID;
END
