INSERT INTO frequency_base (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,REGENERATION_TYPE_NAME,SORT_ORDER) VALUES ('2','Project Start Date','2019-05-31','admin','Y',NULL,1);
INSERT INTO frequency_base (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,REGENERATION_TYPE_NAME,SORT_ORDER) VALUES ('3','Obligation End Date','2019-05-31','admin','Y',NULL,4);
INSERT INTO frequency_base (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,REGENERATION_TYPE_NAME,SORT_ORDER) VALUES ('4','Project End Date','2019-05-31','admin','Y',NULL,2);
INSERT INTO frequency_base (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,REGENERATION_TYPE_NAME,SORT_ORDER) VALUES ('5','Obligation Start Date','2019-05-31','admin','Y',NULL,3);
INSERT INTO frequency_base (FREQUENCY_BASE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE,REGENERATION_TYPE_NAME,SORT_ORDER) VALUES ('6','As Required','2019-05-31','admin','Y',NULL,5);
