DELIMITER $$
CREATE  PROCEDURE `DELETE_INACTIVE_PERSONS`(AV_TYPE VARCHAR(8),
AV_DATE DATETIME)
BEGIN
DECLARE LI_COUNT INT(11);
DECLARE LS_PERSON_ID VARCHAR(40);
DECLARE LI_DELETED_COUNT INT;
DECLARE LI_FLAG INT;
IF      AV_TYPE = 'STAFF' THEN
        UPDATE PERSON SET STATUS = 'I',UPDATE_TIMESTAMP = UTC_TIMESTAMP(), DATE_WHEN_PERSON_INACTIVE = DATE_SUB(AV_DATE, INTERVAL 1 DAY) WHERE ( IS_GRADUATE_STUDENT_STAFF = 'N' OR IS_GRADUATE_STUDENT_STAFF IS NULL )
        AND UPDATE_TIMESTAMP <> AV_DATE AND DATE_WHEN_PERSON_INACTIVE IS NULL AND IS_EXTERNAL_USER IS NULL;
ELSEIF  AV_TYPE = 'STUDENT' THEN
        UPDATE PERSON SET STATUS = 'I',UPDATE_TIMESTAMP = UTC_TIMESTAMP(), DATE_WHEN_PERSON_INACTIVE = DATE_SUB(AV_DATE, INTERVAL 1 DAY) WHERE IS_GRADUATE_STUDENT_STAFF = 'Y'
        AND UPDATE_TIMESTAMP <> AV_DATE AND DATE_WHEN_PERSON_INACTIVE IS NULL;
END IF;
SELECT LI_DELETED_COUNT AS DELETED_PERSON_COUNT FROM DUAL;
END
$$
DELIMITER ;
