DELIMITER $$
CREATE  FUNCTION `FN_CHK_PROP_EXST_BUDGET_FINAL`(
AV_PROPOSAL_ID    varchar(6)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
	SELECT COUNT(1) INTO LI_FLAG FROM BUDGET_HEADER
	WHERE PROPOSAL_ID = AV_PROPOSAL_ID;
    IF LI_FLAG = 0 THEN
		RETURN 'FALSE';
    END IF;
	SELECT COUNT(1) INTO LI_FLAG FROM BUDGET_HEADER
	WHERE PROPOSAL_ID = AV_PROPOSAL_ID
	AND (IS_FINAL_BUDGET = 'Y' OR IS_APPROVED_BUDGET = 'Y');
	IF LI_FLAG > 0 THEN
		RETURN 'TRUE';
	END IF;
	RETURN 'FALSE';
END
$$
DELIMITER ;
