DELIMITER $$
CREATE  FUNCTION `FN_CHK_IS_AWARD_EXTENSION`(
AV_AWARD_ID    varchar(12)
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
	DECLARE LS_TOTAL_MONTHS VARCHAR(10);
	DECLARE LS_FINAL_EXPIRATION_DATE DATETIME;
    DECLARE LI_FLAG INT;
	DECLARE LS_AWARD_NUMBER VARCHAR(12);
	DECLARE LI_AWARD_ID DECIMAL(22,0);
	SELECT COUNT(1) INTO LI_FLAG FROM AWARD
	WHERE AWARD_ID = AV_AWARD_ID AND AWARD_VARIATION_TYPE_CODE = 1
	AND WORKFLOW_AWARD_STATUS_CODE in (1,4);
	IF LI_FLAG > 0 THEN
		SELECT AWARD_NUMBER
		INTO LS_AWARD_NUMBER
		FROM AWARD
		WHERE AWARD_ID = AV_AWARD_ID;
		SELECT AWARD_ID INTO LI_AWARD_ID FROM AWARD
		WHERE AWARD_NUMBER = LS_AWARD_NUMBER
		AND AWARD_SEQUENCE_STATUS='ACTIVE';
		SELECT 	FINAL_EXPIRATION_DATE
		INTO LS_FINAL_EXPIRATION_DATE
		FROM AWARD
		WHERE AWARD_ID = LI_AWARD_ID;
		IF LS_FINAL_EXPIRATION_DATE < NOW() THEN
			RETURN 'FALSE';
		END IF;
		SELECT 	SUBSTR(((DATEDIFF(FINAL_EXPIRATION_DATE,NOW())+1)/30),1,INSTR(((DATEDIFF(FINAL_EXPIRATION_DATE,NOW())+1)/30),'.')-1)
		INTO LS_TOTAL_MONTHS
		FROM AWARD
		WHERE AWARD_ID = LI_AWARD_ID;
		IF LS_TOTAL_MONTHS >= 6 THEN
			RETURN 'TRUE';
		ELSE
			RETURN 'FALSE';
		END IF;
	ELSE
		RETURN 'FALSE';
	END IF;
END
$$
DELIMITER ;
