DELIMITER $$
CREATE  FUNCTION `FN_CHK_KP_APPROVE_AUTHORITY_VR`(
AV_AWARD_ID VARCHAR(12)
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LS_LEAD_UNIT VARCHAR(8);
DECLARE LS_COUNT int(11);
		SELECT LEAD_UNIT_NUMBER
		INTO LS_LEAD_UNIT
		FROM AWARD
		where AWARD_ID = AV_AWARD_ID;
		SELECT COUNT(1) INTO LS_COUNT
		FROM AWARD_PERSONS
		WHERE AWARD_ID = AV_AWARD_ID
		AND PERSON_ID IN (
							SELECT T1.PERSON_ID
							FROM PERSON_ROLES T1
							LEFT JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID
							WHERE ROLE_ID = 400
							AND T1.UNIT_NUMBER =  LS_LEAD_UNIT
							);
		IF LS_COUNT THEN
			RETURN 'TRUE';
		ELSE
			RETURN 'FALSE';
		END IF;
END
$$
DELIMITER ;
