DELIMITER $$
CREATE  FUNCTION `FN_RULE_BUILD_WORKFLOW`(
AV_MODULE_ITEM_ID    VARCHAR(20),
AV_MODULE_CODE       INT(3),
AV_SUBMODULE_CODE    DECIMAL(38,0),
AV_PERSON_ID         VARCHAR(40),
AV_UPDATE_USER       VARCHAR(100),
AV_MAPID             DECIMAL(38,0),
AV_MAP_NUMBER        INT(3),
AV_WORKFLOW_ID       INT(6),
AV_SUB_MODULE_ITEM_KEY   VARCHAR(20),
AV_RULE_ID			 INT(6)
) RETURNS int
    DETERMINISTIC
BEGIN
DECLARE		LL_APPROVAL_STOP_NUMBER     INT(3);
DECLARE		LL_APPROVER_NUMBER 		    INT(3);
DECLARE		LL_APPROVER_PERSON_ID       VARCHAR(40);
DECLARE		LL_PRIMARY_APPROVER_FLAG    VARCHAR(1);
DECLARE		LL_IS_ROLE				    VARCHAR(1);
DECLARE		LL_ROLE_TYPE_CODE 		    INT(3);
DECLARE		LI_WORKFLOW_SEQUENCE        INT;
DECLARE	    LI_MAX_WRKFLW_SEQUENCE      INT;
DECLARE		LI_WRKFLW_COUNT			    INT;
DECLARE		LL_MAP_NUMBER			    INT;
DECLARE		LI_WORKFLOW_ID              DECIMAL(38,0);
DECLARE		LI_LOOP_NUMBER              DECIMAL(38,0);
DECLARE		LS_APPROVAL_STATUS          VARCHAR(1);
DECLARE		LL_USER_ID				    VARCHAR(100);
DECLARE		LL_PERSON_ID			    VARCHAR(40);
DECLARE	    LS_UNIT_NUMBER              VARCHAR(8);
DECLARE     LL_FULL_NAME                VARCHAR(90);
DECLARE     LL_EMAIL_ADDRESS            VARCHAR(60);
DECLARE     DONE1                       INT DEFAULT FALSE;
DECLARE     DONE2                       INT DEFAULT FALSE;
DECLARE		LL_MIN_STOP_NUMBER     INT(3);
SET LI_WORKFLOW_SEQUENCE= 1;
SET LI_MAX_WRKFLW_SEQUENCE = 1;
SET LL_MAP_NUMBER = 0;
SET LI_LOOP_NUMBER = 0;
BEGIN
DECLARE MAP_CURSOR CURSOR FOR
(SELECT APPROVAL_STOP_NUMBER,APPROVER_NUMBER,APPROVER_PERSON_ID,PRIMARY_APPROVER_FLAG,IS_ROLE,ROLE_TYPE_CODE
 FROM WORKFLOW_MAP_DETAIL
 WHERE MAP_ID = AV_MAPID AND ROLE_TYPE_CODE IS NOT NULL
 ORDER BY APPROVAL_STOP_NUMBER)
UNION ALL
 SELECT APPROVAL_STOP_NUMBER,APPROVER_NUMBER,APPROVER_PERSON_ID,PRIMARY_APPROVER_FLAG,IS_ROLE,ROLE_TYPE_CODE
 FROM WORKFLOW_MAP_DETAIL T1
 INNER JOIN PERSON T2 ON T2.PERSON_ID = T1.APPROVER_PERSON_ID
 WHERE MAP_ID = AV_MAPID AND STATUS = 'A'
 ORDER BY APPROVAL_STOP_NUMBER;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN MAP_CURSOR;
SET LL_MAP_NUMBER = LL_MAP_NUMBER + 1;
MAP_CURSOR_LOOP : LOOP
        FETCH MAP_CURSOR INTO LL_APPROVAL_STOP_NUMBER ,LL_APPROVER_NUMBER,LL_APPROVER_PERSON_ID,LL_PRIMARY_APPROVER_FLAG,LL_IS_ROLE,LL_ROLE_TYPE_CODE;
		IF DONE1 THEN
			LEAVE MAP_CURSOR_LOOP;
		END IF;
        IF LI_LOOP_NUMBER = 0 THEN
            SET LL_MAP_NUMBER = 1;
        END IF;
		 SET  LS_APPROVAL_STATUS = 'T';
		IF LL_IS_ROLE = 'Y' AND  LL_ROLE_TYPE_CODE IS NOT NULL THEN
                CALL INSERT_WORKFLOW_FOR_ROLE_TYPE(AV_MODULE_CODE,AV_MODULE_ITEM_ID,LL_ROLE_TYPE_CODE,
												   AV_WORKFLOW_ID,AV_MAPID,AV_MAP_NUMBER,LL_APPROVAL_STOP_NUMBER,
                                                   LL_APPROVER_NUMBER,LL_PRIMARY_APPROVER_FLAG,LS_APPROVAL_STATUS,
                                                   AV_UPDATE_USER,AV_SUBMODULE_CODE,AV_SUB_MODULE_ITEM_KEY,AV_RULE_ID
												   );
		ELSE
            SELECT FULL_NAME,EMAIL_ADDRESS INTO LL_FULL_NAME,LL_EMAIL_ADDRESS
            FROM PERSON
            WHERE PERSON_ID = LL_APPROVER_PERSON_ID;
			INSERT INTO WORKFLOW_DETAIL(
				  WORKFLOW_ID,
				  MAP_ID,
				  MAP_NUMBER,
				  APPROVAL_STOP_NUMBER,
				  APPROVER_NUMBER,
				  PRIMARY_APPROVER_FLAG,
				  APPROVER_PERSON_ID,
				  APPROVAL_STATUS,
				  UPDATE_USER,
				  UPDATE_TIMESTAMP,
                  ROLE_TYPE_CODE,
                  EMAIL_ADDRESS,
                  APPROVER_PERSON_NAME
			)
			VALUES(
				AV_WORKFLOW_ID,
				AV_MAPID,
				AV_MAP_NUMBER,
				LL_APPROVAL_STOP_NUMBER,
				LL_APPROVER_NUMBER,
				LL_PRIMARY_APPROVER_FLAG,
				LL_APPROVER_PERSON_ID,
				LS_APPROVAL_STATUS,
				AV_UPDATE_USER,
				utc_timestamp(),
                LL_ROLE_TYPE_CODE,
				LL_EMAIL_ADDRESS,
                LL_FULL_NAME
			);
			SET LI_LOOP_NUMBER = LI_LOOP_NUMBER + 1;
			END IF;
END LOOP;
CLOSE MAP_CURSOR;
END;
RETURN 1;
END
$$
DELIMITER ;
