DELIMITER $$
CREATE  FUNCTION `FN_VARIATION_TYPE_NEW_FUNDABLE`(
AV_AWARD_ID INT
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LS_CREATE_USER VARCHAR(60);
DECLARE LS_PERSON_ID	VARCHAR(40);
DECLARE LI_FLAG 		INT;
	SELECT COUNT(1) INTO LI_FLAG FROM AWARD T1
	WHERE T1.AWARD_ID = AV_AWARD_ID
	AND T1.AWARD_VARIATION_TYPE_CODE = 10
    AND T1.AWARD_DOCUMENT_TYPE_CODE = 3;
	IF LI_FLAG > 0 THEN
		SELECT CREATE_USER INTO LS_CREATE_USER FROM AWARD T1
		WHERE T1.AWARD_ID = AV_AWARD_ID
		AND T1.AWARD_VARIATION_TYPE_CODE = 10
        AND T1.AWARD_DOCUMENT_TYPE_CODE = 3;
		SELECT T1.PERSON_ID INTO LS_PERSON_ID
		FROM PERSON T1 WHERE UPPER(TRIM(T1.USER_NAME)) = UPPER(TRIM(LS_CREATE_USER));
		SELECT COUNT(1) INTO LI_FLAG FROM PERSON_ROLES
		WHERE PERSON_ID = LS_PERSON_ID
		AND ROLE_ID = 100;
		IF LI_FLAG > 0 THEN
			RETURN 'TRUE';
		ELSE
			RETURN 'FALSE';
		END IF;
	END IF;
	RETURN 'FALSE';
END
$$
DELIMITER ;
