DELIMITER $$
CREATE  FUNCTION `FN_VARIATION_INTRAVOTE_NEWITEM`(
AV_AWARD_ID INT
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG 					INT;
DECLARE LI_PREV_BUDGET_HEADER_ID 	INT(12);
DECLARE LI_PREV_ITEM_COUNT			INT(12);
DECLARE LI_CUR_ITEM_COUNT			INT(12);
DECLARE LI_CUR_BUDGET_HEADER_ID 	INT(12);
DECLARE LI_PREV_ACTIVE_AWARD_ID     DECIMAL(22,0);
	SELECT COUNT(1) INTO LI_FLAG FROM AWARD T1
	WHERE T1.AWARD_ID = AV_AWARD_ID
	AND T1.AWARD_VARIATION_TYPE_CODE = 9
    AND T1.AWARD_DOCUMENT_TYPE_CODE = 3;
	IF LI_FLAG > 0 THEN
		SELECT AWARD_ID INTO LI_PREV_ACTIVE_AWARD_ID FROM AWARD T2
		WHERE T2.AWARD_NUMBER = (SELECT AWARD_NUMBER FROM AWARD T3 WHERE T3.AWARD_ID = AV_AWARD_ID) AND
		T2.AWARD_SEQUENCE_STATUS = 'ACTIVE';
		SELECT BUDGET_HEADER_ID INTO LI_PREV_BUDGET_HEADER_ID
		FROM AWARD_BUDGET_HEADER T4
		WHERE T4.AWARD_ID = LI_PREV_ACTIVE_AWARD_ID
		AND T4.VERSION_NUMBER = (SELECT MAX(T5.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER T5
								WHERE T5.AWARD_ID = LI_PREV_ACTIVE_AWARD_ID);
		SELECT BUDGET_HEADER_ID INTO LI_CUR_BUDGET_HEADER_ID
		FROM AWARD_BUDGET_HEADER T4
		WHERE T4.AWARD_ID = AV_AWARD_ID
		AND T4.VERSION_NUMBER = (SELECT MAX(T5.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER T5
								WHERE T4.AWARD_ID = T5.AWARD_ID);
		SELECT COUNT(BUDGET_DETAILS_ID) INTO LI_CUR_ITEM_COUNT
        FROM AWARD_BUDGET_DETAIL T5
        WHERE T5.BUDGET_HEADER_ID = LI_CUR_BUDGET_HEADER_ID;
        SELECT COUNT(BUDGET_DETAILS_ID) INTO LI_PREV_ITEM_COUNT
        FROM AWARD_BUDGET_DETAIL T6
        WHERE T6.BUDGET_HEADER_ID = LI_PREV_BUDGET_HEADER_ID;
			IF LI_CUR_ITEM_COUNT <> LI_PREV_ITEM_COUNT THEN
				RETURN 'FALSE';
			END IF;
    END IF;
RETURN 'TRUE';
END
$$
DELIMITER ;
