DELIMITER $$
CREATE  PROCEDURE `GET_MODULE_DETAILS_FOR_AGREEMENT`(
AV_MODULE_CODE varchar(3),
AV_MODULE_ITEM_KEY varchar(12)
)
BEGIN
   IF AV_MODULE_CODE = '1' THEN
			SELECT
		t1.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
        t5.unit_name AS LEAD_UNIT_NAME,
		t5.UNIT_NUMBER AS LEAD_UNIT_NUMBER,
		t1.title AS TITLE,
		t3.DESCRIPTION AS STATUS,
		IFNULL(t6.FULL_NAME, t7.FULL_NAME) AS PI_NAME,
		t4.SPONSOR_NAME AS SPONSOR,
        t1.AWARD_NUMBER AS AWARD_NUMBER,
		1 AS MODULE_CODE,
        t1.AWARD_ID AS AWARD_ID,
       t2.PERSON_ID AS PERSON_ID,
        t1.SPONSOR_CODE AS SPONSOR_CODE,
		t1.AWARD_EFFECTIVE_DATE AS START_DATE,
		t1.FINAL_EXPIRATION_DATE AS END_DATE,
		t1.PRIME_SPONSOR_CODE AS PRIME_SPONSOR_CODE,
		t2.ROLODEX_ID AS ROLODEX_ID
    FROM
        ((((((award t1
        LEFT JOIN award_persons t2 ON (((t1.AWARD_ID = t2.AWARD_ID)
            AND (t2.PERSON_ROLE_ID = 3) AND (t2.PI_FLAG ='Y'))))
        LEFT JOIN award_status t3 ON ((t1.STATUS_CODE = t3.STATUS_CODE)))
        LEFT JOIN sponsor t4 ON ((t4.SPONSOR_CODE = t1.SPONSOR_CODE)))
        LEFT JOIN unit t5 ON ((t1.LEAD_UNIT_NUMBER = t5.UNIT_NUMBER)))
        LEFT JOIN PERSON t6 ON ((t2.PERSON_ID = t6.PERSON_ID)))
		 LEFT JOIN ROLODEX t7 ON ((t2.ROLODEX_ID = t7.ROLODEX_ID)))
    WHERE
        (t1.AWARD_ID = AV_MODULE_ITEM_KEY);
   ELSEIF AV_MODULE_CODE = '2' THEN
   		SELECT
		"" AS ACCOUNT_NUMBER,
        t5.unit_name AS LEAD_UNIT_NAME,
		t1.HOME_UNIT_NUMBER AS LEAD_UNIT_NUMBER,
		t1.title AS TITLE,
		t3.DESCRIPTION AS STATUS,
		IFNULL(t6.FULL_NAME, t7.FULL_NAME) AS PI_NAME,
		t4.SPONSOR_NAME AS SPONSOR,
        t1.PROPOSAL_NUMBER AS MODULE_ITEM_KEY,
		 2 AS MODULE_CODE,
        t1.PROPOSAL_ID AS MODULE_ITEM_ID,
       t2.PERSON_ID AS PERSON_ID,
        t1.SPONSOR_CODE AS SPONSOR_CODE,
		t1.START_DATE AS START_DATE,
		t1.END_DATE AS END_DATE,
		t1.PRIME_SPONSOR_CODE AS PRIME_SPONSOR_CODE,
		t2.ROLODEX_ID AS ROLODEX_ID
    FROM
        ((((((proposal t1
        LEFT JOIN proposal_persons t2 ON (((t1.PROPOSAL_ID = t2.PROPOSAL_ID)
            AND (t2.PROP_PERSON_ROLE_ID = 3) AND (t2.PI_FLAG ='Y'))))
        LEFT JOIN proposal_status t3 ON ((t1.STATUS_CODE = t3.STATUS_CODE)))
        LEFT JOIN sponsor t4 ON ((t4.SPONSOR_CODE = t1.SPONSOR_CODE)))
        LEFT JOIN unit t5 ON ((t1.HOME_UNIT_NUMBER = t5.UNIT_NUMBER)))
        LEFT JOIN PERSON t6 ON ((t2.PERSON_ID = t6.PERSON_ID)))
		 LEFT JOIN ROLODEX t7 ON ((t2.ROLODEX_ID = t7.ROLODEX_ID)))
    WHERE
        (t1.PROPOSAL_ID = AV_MODULE_ITEM_KEY);
    ELSEIF AV_MODULE_CODE = '3' THEN
    		SELECT
		"" AS ACCOUNT_NUMBER,
        t5.unit_name AS LEAD_UNIT_NAME,
		t1.HOME_UNIT_NUMBER AS LEAD_UNIT_NUMBER,
		t1.title AS TITLE,
		t3.DESCRIPTION AS STATUS,
		IFNULL(t6.FULL_NAME, t7.FULL_NAME) AS PI_NAME,
		t4.SPONSOR_NAME AS SPONSOR,
        t1.PROPOSAL_ID AS MODULE_ITEM_KEY,
		3 AS MODULE_CODE,
        t1.PROPOSAL_ID AS MODULE_ITEM_ID,
       t2.PERSON_ID AS PERSON_ID,
        t1.SPONSOR_CODE AS SPONSOR_CODE,
		t1.START_DATE AS START_DATE,
		t1.END_DATE AS END_DATE,
		t1.PRIME_SPONSOR_CODE AS PRIME_SPONSOR_CODE,
		t2.ROLODEX_ID AS ROLODEX_ID
    FROM
        ((((((eps_proposal t1
        LEFT JOIN eps_proposal_persons t2 ON (((t1.PROPOSAL_ID = t2.PROPOSAL_ID)
            AND (t2.PROP_PERSON_ROLE_ID = 3) AND (t2.PI_FLAG ='Y'))))
        LEFT JOIN eps_proposal_status t3 ON ((t1.STATUS_CODE = t3.STATUS_CODE)))
        LEFT JOIN sponsor t4 ON ((t4.SPONSOR_CODE = t1.SPONSOR_CODE)))
        LEFT JOIN unit t5 ON ((t1.HOME_UNIT_NUMBER = t5.UNIT_NUMBER)))
        LEFT JOIN PERSON t6 ON ((t2.PERSON_ID = t6.PERSON_ID)))
		 LEFT JOIN ROLODEX t7 ON ((t2.ROLODEX_ID = t7.ROLODEX_ID)))
    WHERE
        (t1.PROPOSAL_ID = AV_MODULE_ITEM_KEY);
	 ELSEIF AV_MODULE_CODE = '13' THEN
	 	SELECT
		"" AS ACCOUNT_NUMBER,
        t1.UNIT_NAME AS LEAD_UNIT_NAME,
		t1.UNIT_NUMBER AS LEAD_UNIT_NUMBER,
		t1.title AS TITLE,
		t3.DESCRIPTION AS STATUS,
        t2.FULL_NAME AS PI_NAME,
		t4.SPONSOR_NAME AS SPONSOR,
        t1.AGREEMENT_REQUEST_ID AS MODULE_ITEM_KEY,
		13 AS MODULE_CODE,
        t1.AGREEMENT_REQUEST_ID AS MODULE_ITEM_ID,
       t2.PERSON_ID AS PERSON_ID,
        t4.SPONSOR_CODE AS SPONSOR_CODE,
		t1.START_DATE AS START_DATE,
		t1.END_DATE AS END_DATE,
		"" AS PRIME_SPONSOR_CODE,
		t2.ROLODEX_ID AS ROLODEX_ID
    FROM
        (((agreement_header t1
               LEFT JOIN (SELECT
            	ap4.PERSON_ID AS PERSON_ID,
            	ap4.ROLODEX_ID AS ROLODEX_ID,
                ap4.FULL_NAME AS FULL_NAME,
                ap4.AGREEMENT_REQUEST_ID AS AGREEMENT_REQUEST_ID
        FROM
            agreement_people ap4
        WHERE
            ap4.AGREEMENT_PEOPLE_ID IN (SELECT
                    MAX(ap1.AGREEMENT_PEOPLE_ID)
                FROM
                    agreement_people ap1
                WHERE
                    ((ap1.AGREEMENT_REQUEST_ID = ap4.AGREEMENT_REQUEST_ID)
                        AND (ap1.PEOPLE_TYPE_ID = 3)))) t2 ON ((t2.AGREEMENT_REQUEST_ID = t1.AGREEMENT_REQUEST_ID)))
        LEFT JOIN agreement_status t3 ON ((t1.AGREEMENT_STATUS_CODE= t3.AGREEMENT_STATUS_CODE)))
               LEFT JOIN (SELECT
            as1.SPONSOR_CODE AS SPONSOR_CODE,
                as1.SPONSOR_NAME AS SPONSOR_NAME,
                as1.AGREEMENT_REQUEST_ID AS AGREEMENT_REQUEST_ID
        FROM
            agreement_sponsor as1
        WHERE
            as1.AGREEMENT_SPONSOR_ID IN (SELECT
                    MAX(as0.AGREEMENT_SPONSOR_ID)
                FROM
                    agreement_sponsor as0
                WHERE
                    ((as0.AGREEMENT_REQUEST_ID = as1.AGREEMENT_REQUEST_ID)
                        AND (as0.AGREEMENT_SPONSOR_TYPE_CODE = 1)))) t4 ON ((t4.AGREEMENT_REQUEST_ID = t1.AGREEMENT_REQUEST_ID)))
    WHERE
        (t1.AGREEMENT_REQUEST_ID = AV_MODULE_ITEM_KEY);
    END IF;
END
$$
DELIMITER ;
