DELIMITER $$
CREATE  PROCEDURE `GET_GRANTCALL_ELIGIBLITY_STATUS`(
AV_GRANT_HEADER_ID    INT(11),
AV_ROLE_ID int(11),
AV_PERSON_ID varchar(40)
)
    DETERMINISTIC
BEGIN
DECLARE LI_PROP_PERSON_ROLE_ID int(11);
DECLARE LS_TARGET_VALUE varchar(40);
DECLARE LI_FLAG INT(1);
DECLARE LS_DYN_SQL LONGTEXT;
   BEGIN
		SELECT 'TRUE' AS STATUS, 'Success ' AS MESSAGE FROM DUAL;
	END;
END
$$
DELIMITER ;
