DELIMITER $$
CREATE  PROCEDURE `GET_SERVICE_REQUEST_DASHBOARD_BCK`(
AV_MODULE_ITEM_KEY     		VARCHAR(22),
AV_MODULE_CODE	            VARCHAR(3),
AV_SR_HEADER_ID	            VARCHAR(6),
AV_REQUEST_SUBJECT	        VARCHAR(1000),
AV_REQUEST_TYPE   	        VARCHAR(200),
AV_REQUEST_STATUS           VARCHAR(200),
AV_PI_PERSON_ID             VARCHAR(40),
AV_LEAD_UNIT_NAME   	    VARCHAR(60),
AV_TITLE                    VARCHAR(200),
AV_PERSON_ID 			    VARCHAR(200),
AV_SORT_TYPE 			    VARCHAR(500),
AV_PAGED  				    INT(10),
AV_LIMIT				    INT(10),
AV_TAB_TYPE 				VARCHAR(30),
AV_UNLIMITED                BOOLEAN,
AV_TYPE                     VARCHAR(1)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
DECLARE TAB_QUERY LONGTEXT;
DECLARE JOIN_CONDITION LONGTEXT;
DECLARE SELECTED_FIELD_LIST LONGTEXT;
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
SET LS_FILTER_CONDITION ='';
SET LS_DYN_SQL ='';
SET JOIN_CONDITION = '';
SET SELECTED_FIELD_LIST= '';
IF AV_TYPE = 'A'   THEN
			IF AV_MODULE_ITEM_KEY IS NOT NULL AND AV_MODULE_ITEM_KEY <> '' THEN
			  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.MODULE_ITEM_KEY LIKE ''%',AV_MODULE_ITEM_KEY,'%'' AND  T.MODULE_CODE = ''',AV_MODULE_CODE,''' AND ');
			END IF;
			IF AV_SR_HEADER_ID IS NOT NULL AND AV_SR_HEADER_ID <> '' THEN
			  SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.SR_HEADER_ID LIKE ''%',AV_SR_HEADER_ID,'%'' AND ');
			END IF;
			IF AV_REQUEST_SUBJECT IS NOT NULL  AND AV_REQUEST_SUBJECT <> '' THEN
				SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.SUBJECT LIKE ''%',AV_REQUEST_SUBJECT,'%'' AND ');
			END IF;
			IF AV_REQUEST_TYPE IS NOT NULL  AND AV_REQUEST_TYPE <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.TYPE_CODE IN (',AV_REQUEST_TYPE,') AND ');
            END IF;
			IF AV_PI_PERSON_ID IS NOT NULL  AND AV_PI_PERSON_ID <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PI_PERSON_ID = ''',AV_PI_PERSON_ID,''' AND ');
			END IF;
			IF AV_LEAD_UNIT_NAME IS NOT NULL  AND AV_LEAD_UNIT_NAME <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.UNIT_NAME LIKE ''%',AV_LEAD_UNIT_NAME,'%'' AND ');
			END IF;
			IF AV_TITLE IS NOT NULL  AND AV_TITLE <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.TITLE LIKE ''%',AV_TITLE,'%'' AND ');
			END IF;
			IF AV_REQUEST_STATUS IS NOT NULL  AND AV_REQUEST_STATUS <> '' THEN
			 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.STATUS_CODE IN (',AV_REQUEST_STATUS,')  AND ');
			END IF;
			IF 	AV_TAB_TYPE = 'ALL_REQUEST'	THEN
						 IF (SELECT COUNT(*)  FROM PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID AND ROLE_ID = 100) THEN
							SET TAB_QUERY = '';
						 ELSEIF (SELECT COUNT(*)  FROM PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID AND ROLE_ID IN(120,400)) THEN
							 SET TAB_QUERY = CONCAT(' WHERE ( COALESCE(T2.LEAD_UNIT_NUMBER,T3.HOME_UNIT_NUMBER,T4.HOME_UNIT_NUMBER) IN(SELECT DISTINCT UNIT_NUMBER FROM PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND ROLE_ID IN(120,400) )  )');
						ELSE
							  SET TAB_QUERY = CONCAT(' WHERE (( T1.MODULE_ITEM_KEY IN(SELECT AWARD_ID FROM AWARD_PERSONS WHERE PERSON_ID=''',AV_PERSON_ID,''' AND PERSON_ROLE_ID IN (1,3,6) ) AND T1.MODULE_CODE = 1 )
																OR ( T1.MODULE_ITEM_KEY IN(SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID=''',AV_PERSON_ID,''' AND PROP_PERSON_ROLE_ID IN (1,3,6) ) AND T1.MODULE_CODE = 3 )
																OR ( T1.MODULE_ITEM_KEY IN(SELECT PROPOSAL_ID FROM PROPOSAL_PERSONS WHERE PERSON_ID=''',AV_PERSON_ID,''' AND PROP_PERSON_ROLE_ID IN (1,3,6) ) AND T1.MODULE_CODE = 2 )) ');
						 END IF;
			END IF;
END IF;
IF AV_TAB_TYPE = 'MY_REQUEST' THEN
			SET TAB_QUERY = CONCAT(' WHERE ( T1.CREATE_USER = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID = ''',AV_PERSON_ID,''')
											AND T1.STATUS_CODE NOT IN (4,8)
                                            OR ( T1.ASSIGNEE_PERSON_ID = ''',AV_PERSON_ID,''' )
											OR ( T1.MODULE_ITEM_KEY IN(SELECT AWARD_ID FROM AWARD_PERSONS WHERE PERSON_ID=''',AV_PERSON_ID,''' AND PERSON_ROLE_ID IN (1,3,6) ) AND T1.MODULE_CODE = 1 )
										    OR ( T1.MODULE_ITEM_KEY IN(SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID=''',AV_PERSON_ID,''' AND PROP_PERSON_ROLE_ID IN (1,3,6) ) AND T1.MODULE_CODE = 3 )
										    OR ( T1.MODULE_ITEM_KEY IN(SELECT PROPOSAL_ID FROM PROPOSAL_PERSONS WHERE PERSON_ID=''',AV_PERSON_ID,''' AND PROP_PERSON_ROLE_ID IN (1,3,6) ) AND T1.MODULE_CODE = 2 )  )' );
END IF;
IF AV_SORT_TYPE IS NULL THEN
	SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
ELSE
    SET AV_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
END IF;
IF AV_UNLIMITED = TRUE THEN
	SET LS_OFFSET_CONDITION = '';
ELSE
	SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
END IF;
IF LS_FILTER_CONDITION <>'' THEN
SET LS_FILTER_CONDITION = CONCAT(' WHERE  ',LS_FILTER_CONDITION);
SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;
END IF;
			SET LS_DYN_SQL =CONCAT('SELECT DISTINCT *  FROM(SELECT T1.SR_HEADER_ID,
																	T1.MODULE_ITEM_KEY,
                                                                    T1.MODULE_CODE,
																	COALESCE(T2.AWARD_NUMBER,T3.PROPOSAL_ID,T4.PROPOSAL_ID) AS PROJECT_ID,
																	COALESCE(T2.TITLE,T3.TITLE,T4.TITLE) AS TITLE,
																	COALESCE(T5.FULL_NAME,T6.FULL_NAME,T7.FULL_NAME) AS PI_FULL_NAME,
                                                                    COALESCE(T5.PERSON_ID,T6.PERSON_ID,T7.PERSON_ID) AS PI_PERSON_ID,
																	T8.DESCRIPTION AS REQUEST_TYPE,
																	T1.TYPE_CODE,
																	T1.STATUS_CODE,
																	T1.SUBJECT,
																	COALESCE(T2.LEAD_UNIT_NUMBER,T3.HOME_UNIT_NUMBER,T4.HOME_UNIT_NUMBER) AS LEAD_UNIT_NUMBER,
                                                                    T10.UNIT_NAME,
																	T9.DESCRIPTION AS REQUEST_STATUS,
																	T1.UPDATE_TIMESTAMP
															FROM SR_HEADER T1
															LEFT JOIN AWARD T2 ON T1.MODULE_ITEM_KEY = T2.AWARD_ID AND T1.MODULE_CODE = 1
															LEFT JOIN EPS_PROPOSAL T3 ON T1.MODULE_ITEM_KEY = T3.PROPOSAL_ID AND T1.MODULE_CODE = 3
															LEFT JOIN PROPOSAL T4 ON T1.MODULE_ITEM_KEY = T4.PROPOSAL_ID AND T1.MODULE_CODE = 2
															LEFT JOIN AWARD_PERSONS T5 ON T5.AWARD_ID = T2.AWARD_ID AND T5.PERSON_ROLE_ID = 3
															LEFT JOIN EPS_PROPOSAL_PERSONS T6 ON T6.PROPOSAL_ID = T3.PROPOSAL_ID AND T6.PROP_PERSON_ROLE_ID = 3
															LEFT JOIN PROPOSAL_PERSONS T7 ON T7.PROPOSAL_ID = T4.PROPOSAL_ID AND T7.PROP_PERSON_ROLE_ID = 3
															LEFT JOIN SR_TYPE T8 ON T8.TYPE_CODE = T1.TYPE_CODE
															LEFT JOIN SR_STATUS T9 ON T9.STATUS_CODE = T1.STATUS_CODE
															LEFT JOIN UNIT T10 ON T10.UNIT_NUMBER = COALESCE(T2.LEAD_UNIT_NUMBER,T3.HOME_UNIT_NUMBER,T4.HOME_UNIT_NUMBER)  ',JOIN_CONDITION,TAB_QUERY,
									' GROUP BY T1.SR_HEADER_ID)T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION );
SELECT LS_DYN_SQL;
END
$$
DELIMITER ;
