DELIMITER $$
CREATE  PROCEDURE `GET_RESEARCH_SUMMARY_DETAILS`(
AV_WIDGET VARCHAR(200),
AV_PERSON_ID VARCHAR(50),
AV_LEVEL INT,
AV_UNIT_NUMBER VARCHAR(10)
)
BEGIN
DECLARE COL1 VARCHAR(200);
DECLARE COL2 VARCHAR(200);
DECLARE COL3 VARCHAR(200);
DECLARE LS_COUNT INT;
IF AV_UNIT_NUMBER = '' THEN
	SET AV_UNIT_NUMBER = null ;
END IF;
IF AV_WIDGET = 'AWARD_BUDGET_AND_EXPENSES' THEN
	SELECT DISTINCT
	SPONSOR_AWARD_NUMBER,
	TITLE,
	FINAL_EXPIRATION_DATE,
	TOTAL_DIRECT_COST,
	(ACTUAL_EXPENSE_WO_IRC+COMMITTED_EXPENSE_WO_IRC) AS EXPENSE,
	(TOTAL_DIRECT_COST-((ACTUAL_EXPENSE_WO_IRC+COMMITTED_EXPENSE_WO_IRC))) AS BALANCE,
	UTILIZATION_RATE_WO_IRC AS UTILIZATION_RATE ,
	CASE WHEN (FINAL_EXPIRATION_DATE >= utc_timestamp() AND ((UTILIZATION_RATE_WO_IRC + 10) < ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100))  THEN 'Low Utilisation'
	WHEN (FINAL_EXPIRATION_DATE >= utc_timestamp() AND ((UTILIZATION_RATE_WO_IRC - 10) > ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100))  THEN 'High Utilisation'
	WHEN (FINAL_EXPIRATION_DATE >= utc_timestamp() AND (((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100
	BETWEEN (UTILIZATION_RATE_WO_IRC - 10)
	AND (UTILIZATION_RATE_WO_IRC + 10))) THEN 'Acceptable Utilisation'
	WHEN FINAL_EXPIRATION_DATE < utc_timestamp() THEN 'Passed Project End Date' END AS FLAGGED,
	CASE WHEN datediff(FINAL_EXPIRATION_DATE,UTC_TIMESTAMP()) BETWEEN 0 AND 365 THEN 'Project Ending < 12 Month' END AS REMINDER,
	AWARD_ID,
	CASE WHEN FINAL_EXPIRATION_DATE < utc_timestamp() THEN NULL ELSE FINAL_EXPIRATION_DATE END AS SORT
	FROM award_master_dataset_rt
	WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
	AND (KEY_PERSON_ID  = AV_PERSON_ID AND PERSON_ROLE_ID IN ('3','9')
			AND AWARD_STATUS_CODE NOT IN ('3', '5')
	) ORDER BY ISNULL(SORT), SORT ASC;
ELSEIF AV_WIDGET = 'AWARD_BY_SPONSOR' THEN
	if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SELECT COUNT(1) INTO LS_COUNT FROM SPONSOR;
	(SELECT IFNULL(SPONSOR_GROUP,SPONSOR_CODE) AS SPONSOR_CODE,IFNULL(SPONSOR_GROUP,SPONSOR_NAME) AS SPONSOR_NAME , COUNT(1), SUM(ANTICIPATED_TOTAL_AMOUNT)/1000000 FROM (
SELECT DISTINCT A1.SPONSOR_CODE,A1.SPONSOR_NAME,A1.AWARD_NUMBER, A1.ANTICIPATED_TOTAL_AMOUNT, A2.SPONSOR_GROUP  FROM
award_master_dataset_rt A1
INNER JOIN SPONSOR A2 ON A1.SPONSOR_CODE = A2.SPONSOR_CODE
WHERE A1.AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND (ifnull (A1.FUND_CODE , 'R_RESFUND')) <> 'G_DESIGNAT'
AND A1.BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
AND A1.AWARD_STATUS_CODE <> '3'
AND (AV_UNIT_NUMBER is null OR A1.LEAD_UNIT_NUMBER = AV_UNIT_NUMBER)
AND (
    A1.AWARD_ID  IN
    (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
OR A1.LEAD_UNIT_NUMBER IN (
SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
AND PERSON_ID = AV_PERSON_ID
)))AS TAB GROUP BY IFNULL(SPONSOR_GROUP,SPONSOR_CODE) order by count(1) desc limit 9)
UNION
    select 'Other', "Others", sum(count), sum(amnt) from
    (SELECT SPONSOR_CODE,IFNULL(SPONSOR_GROUP,SPONSOR_NAME) AS SPONSOR, COUNT(1) as count, SUM(ANTICIPATED_TOTAL_AMOUNT)/1000000 as amnt FROM (
SELECT DISTINCT A1.SPONSOR_CODE,A1.SPONSOR_NAME,A1.AWARD_NUMBER, A1.ANTICIPATED_TOTAL_AMOUNT, A2.SPONSOR_GROUP FROM
award_master_dataset_rt A1
INNER JOIN SPONSOR A2 ON A1.SPONSOR_CODE = A2.SPONSOR_CODE
WHERE A1.AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND (ifnull (A1.FUND_CODE , 'R_RESFUND')) <> 'G_DESIGNAT'
AND A1.BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
 AND A1.AWARD_STATUS_CODE <> '3'
 AND (AV_UNIT_NUMBER is null OR A1.LEAD_UNIT_NUMBER = AV_UNIT_NUMBER)
AND (
    A1.AWARD_ID  IN
    (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
OR A1.LEAD_UNIT_NUMBER IN (
SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
AND PERSON_ID = AV_PERSON_ID
))
    )AS TAB GROUP BY IFNULL(SPONSOR_GROUP,SPONSOR_CODE) order by count(1) desc limit LS_COUNT offset 9) tab1
    having count(1)>0;
ELSEIF AV_WIDGET IN ('AWARD_BY_SPONSOR_TYPE','ACTIVE_AWARDS_BY_SPONSOR_TYPE') THEN
	if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SELECT SPONSOR_TYPE_CODE,SPONSOR_TYPE, COUNT(1), SUM(ANTICIPATED_TOTAL_AMOUNT)/1000000  FROM (
	SELECT DISTINCT SPONSOR_TYPE_CODE,SPONSOR_TYPE,AWARD_NUMBER, ANTICIPATED_TOTAL_AMOUNT FROM
	award_master_dataset_rt
	WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
	AND (ifnull (FUND_CODE , 'R_RESFUND')) <> 'G_DESIGNAT'
    AND AWARD_STATUS_CODE <> '3'
	AND BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
	AND (
    AWARD_ID  IN
    (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
	INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
	WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
	OR LEAD_UNIT_NUMBER IN (
	SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
	AND PERSON_ID = AV_PERSON_ID
	))
	)AS TAB
	GROUP BY SPONSOR_TYPE_CODE;
ELSEIF AV_WIDGET = 'UNDER_UTALIZED_AWARD' THEN
	select FLAGGED,count(1) from(
	SELECT distinct AWARD_NUMBER,UTILIZATION_RATE_WO_IRC ,
	CASE WHEN ((UTILIZATION_RATE_WO_IRC + 10) < ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100)  THEN 'Low Utilisation'
	WHEN ((UTILIZATION_RATE_WO_IRC - 10) > ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100)  THEN 'High Utilisation'
	WHEN (((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100 BETWEEN (UTILIZATION_RATE_WO_IRC - 10) AND (UTILIZATION_RATE_WO_IRC + 10)) THEN 'Acceptable Utilisation' END AS FLAGGED
	FROM award_master_dataset_rt
	WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
    AND AWARD_STATUS_CODE = '1'
	AND FINAL_EXPIRATION_DATE >= utc_timestamp()
	AND (
    AWARD_ID  IN
    (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
	INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
	WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
	OR LEAD_UNIT_NUMBER IN (
	SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')AND PERSON_ID = AV_PERSON_ID)
	)
    ORDER BY FINAL_EXPIRATION_DATE ASC
	) as TAB group by FLAGGED;
ELSEIF AV_WIDGET = 'RECENT_AWARDS' THEN
	SELECT DISTINCT T1.UNIT_NAME, T1.TITLE, T1.PI_NAME, T1.GRANT_CALL_TITLE, T1.AWARD_ID FROM AWARD_MASTER_DATASET_RT T1
	INNER JOIN TASK T2 ON T1.AWARD_ID = T2.MODULE_ITEM_ID AND T2.TASK_TYPE_CODE = 5
	INNER JOIN TASK_ACTION_LOG T3 ON T2.TASK_ID = T3.TASK_ID AND T3.ACTION_TYPE_CODE = '4'
	AND DATEDIFF(UTC_TIMESTAMP(),T3.UPDATE_TIMESTAMP) BETWEEN 0 AND 90
	where (ifnull (T1.DISPLAY_AT_ACAD_PROFILE , 'NO')) = 'YES'
	AND T1.AWARD_TYPE <> 'Sub-project'
	AND AWARD_STATUS_CODE <> '3'
	ORDER BY T3.UPDATE_TIMESTAMP DESC;
ELSEIF AV_WIDGET = 'PROPOSAL_BY_SPONSOR_TYPE' THEN
	SELECT T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION AS SPONSOR_TYPE,COUNT(1) FROM EPS_PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE
	INNER JOIN SPONSOR_TYPE T3 ON T2.SPONSOR_TYPE_CODE=T3.SPONSOR_TYPE_CODE WHERE T1.DOCUMENT_STATUS_CODE <> '3' AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL
	WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID)
	UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID UNION
	SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1
	INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = AV_PERSON_ID
	AND S1.MODULE_CODE = 3) GROUP BY T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION;
ELSEIF AV_WIDGET = 'INPROGRESS_PROPOSAL_BY_SPONSOR' THEN
	SELECT T1.SPONSOR_CODE,T2.SPONSOR_NAME AS SPONSOR,COUNT(1) AS COUNT FROM EPS_PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE WHERE T1.STATUS_CODE = 1
	AND T1.DOCUMENT_STATUS_CODE <> '3' AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL')
	AND PERSON_ID = AV_PERSON_ID) UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID UNION
	SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID
	WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = AV_PERSON_ID	AND S1.MODULE_CODE = 3) GROUP BY T1.SPONSOR_CODE,T2.SPONSOR_NAME;
ELSEIF AV_WIDGET = 'AWARDED_PROPOSAL_BY_SPONSOR' THEN
    SELECT T1.SPONSOR_CODE,T2.SPONSOR_NAME AS SPONSOR,COUNT(1) AS COUNT FROM PROPOSAL T1 INNER JOIN SPONSOR T2 ON T2.SPONSOR_CODE = T1.SPONSOR_CODE WHERE T1.STATUS_CODE = 2
	AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_NUMBER IN (SELECT PROPOSAL_NUMBER FROM PROPOSAL WHERE T1.HOME_UNIT_NUMBER IN
	(SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID) UNION
	SELECT PROPOSAL_ID FROM PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID) GROUP BY T1.SPONSOR_CODE,T2.SPONSOR_NAME;
ELSEIF AV_WIDGET = 'PROPOSAL_EXPENDITURE_VOLUME' THEN
	SELECT DATE_FORMAT(T3.START_DATE, '%Y') AS BUDGET_PERIOD, SUM(T3.TOTAL_DIRECT_COST) AS DIRECT_COST, SUM(T3.TOTAL_INDIRECT_COST) AS FA
	FROM EPS_PROPOSAL T1 INNER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID   AND T2.IS_LATEST_VERSION  = 'Y'
	INNER JOIN BUDGET_PERIOD T3 ON T2.BUDGET_HEADER_ID = T3.BUDGET_HEADER_ID WHERE T1.DOCUMENT_STATUS_CODE <> '3' AND T1.PROPOSAL_ID IN(
	SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL
	WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID)
	UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID)GROUP BY YEAR(T3.START_DATE) ORDER BY YEAR(T3.START_DATE);
ELSEIF AV_WIDGET = 'RESEARCH_SUMMARY_TABLE' THEN
			(SELECT 'Approval In Progress Proposals' AS APPROVAL_INPROGRESS_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT FROM EPS_PROPOSAL T1
			LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' WHERE T1.STATUS_CODE = 2
			AND T1.DOCUMENT_STATUS_CODE <> '3' AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL
			WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN  ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID)
			UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID  UNION
			SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y'
			AND S2.APPROVER_PERSON_ID = AV_PERSON_ID AND S1.MODULE_CODE = 3))
            UNION
            (
            SELECT 'In Progress Proposals' AS INPROGRESS_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT FROM EPS_PROPOSAL T1
			LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_LATEST_VERSION  = 'Y'  WHERE T1.STATUS_CODE = 1 AND T1.DOCUMENT_STATUS_CODE <> '3' AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_ID IN (
			SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (
			SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID) UNION
			SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID))
            UNION
            (
            SELECT 'Submitted Proposals' AS AWARDED_PROPOSALS, COUNT(T1.PROPOSAL_ID) AS COUNT,SUM(T2.TOTAL_COST) AS TOTAL_AMOUNT
				FROM EPS_PROPOSAL T1
				LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_FINAL_BUDGET = 'Y' WHERE T1.STATUS_CODE = 11
				AND T1.DOCUMENT_STATUS_CODE <> '3' AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_ID IN (                SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID
													   UNION
												   SELECT PROPOSAL_ID FROM EPS_PROPOSAL
							                           WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID)
													   UNION
													   SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID
													   UNION
													   SELECT PROPOSAL_ID FROM EPS_PROPOSAL
							                           WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = AV_PERSON_ID AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)
										));
ELSEIF AV_WIDGET = 'SUBMITTED_CLAIMS_IN_LAST_THREE_YEAR' THEN
if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
END IF;
		SET COL2 = COL3-1;
        SET COL1 = COL2-1;
        select 'Sponsor Group', COL3, COL2, COL1, 1 AS SORT_ORDER
        union
		SELECT SPONSOR, SUM(COL3_SUM),SUM(COL2_SUM),SUM(COL1_SUM), 2 AS SORT_ORDER FROM
(select T3.SPONSOR_CODE,T3.SPONSOR_NAME,
sum(case when (T1.CLAIM_SUBMISSION_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end)/1000000 AS COL3_SUM,
        sum(case when (T1.CLAIM_SUBMISSION_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end)/1000000 AS COL2_SUM,
        SUM(case when (T1.CLAIM_SUBMISSION_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end)/1000000 AS COL1_SUM,
        CASE WHEN T3.SPONSOR_GROUP IN('NRF','A*STAR','MOH','MOE') THEN T3.SPONSOR_GROUP ELSE 'OTHER' END AS SPONSOR,
        2 from CLAIM T1
INNER JOIN AWARD T2 ON T1.AWARD_NUMBER = T2.AWARD_NUMBER
INNER JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T2.SPONSOR_CODE
where T1.CLAIM_STATUS_CODE in (4,8,6)
        AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
        AND T2.STATUS_CODE <> '3'
		AND (
		T2.AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_CLAIMS')
		OR T2.LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_CLAIMS') AND PERSON_ID = AV_PERSON_ID))
		GROUP BY T3.SPONSOR_GROUP) TAB GROUP BY SPONSOR
		order by SORT_ORDER;
   ELSEIF AV_WIDGET = 'SUBMITTED_CLAIMS_BY_STATUS' THEN
        SELECT DESCRIPTION INTO COL3 FROM CLAIM_STATUS WHERE CLAIM_STATUS_CODE = '4';
		SELECT DESCRIPTION INTO COL2 FROM CLAIM_STATUS WHERE CLAIM_STATUS_CODE = '8';
        SELECT DESCRIPTION INTO COL1 FROM CLAIM_STATUS WHERE CLAIM_STATUS_CODE = '6';
        select 'Sponsor Group', COL1, COL2, COL3, 'Total',1 as SORT_ORDER
        union
		SELECT SPONSOR, SUM(COL1_SUM)/1000000,SUM(COL2_SUM)/1000000, SUM(COL3_SUM)/1000000 ,
		(ifnull(SUM(COL1_SUM),0)+ifnull(SUM(COL2_SUM),0)+ifnull(SUM(COL3_SUM),0))/1000000 AS TOTAL, 2 FROM
		(select T3.SPONSOR_CODE,T3.SPONSOR_NAME,
				SUM(case when T1.CLAIM_STATUS_CODE = '6' then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS COL1_SUM,
				sum(case when T1.CLAIM_STATUS_CODE = '8' then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS COL2_SUM,
				sum(case when T1.CLAIM_STATUS_CODE = '4' then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS COL3_SUM,
                CASE WHEN T3.SPONSOR_GROUP IN('NRF','A*STAR','MOH','MOE') THEN T3.SPONSOR_GROUP ELSE 'OTHER' END AS SPONSOR
				from CLAIM T1
		INNER JOIN AWARD T2 ON T1.AWARD_NUMBER = T2.AWARD_NUMBER
		INNER JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T2.SPONSOR_CODE
		where T1.CLAIM_STATUS_CODE in (4,8,6)
				AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
                AND T2.STATUS_CODE <> '3'
		AND (
		T2.AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_CLAIMS')
		OR T2.LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_CLAIMS')
		AND PERSON_ID = AV_PERSON_ID))
				GROUP BY T3.SPONSOR_GROUP,T1.CLAIM_STATUS_CODE ) TAB
                GROUP BY SPONSOR
				order by SORT_ORDER;
ELSEIF AV_WIDGET = 'ANNUALIZED_RESEARCH_FUNDING' THEN
        if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
END IF;
		SET COL2 = COL3-1;
        SET COL1 = COL2-1;
	select 'Unit Name', 'Lead Unit NUmber',COL1,COL2,COL3,  1 AS SORT_ORDER
    union
	SELECT unit_name,LEAD_UNIT_NUMBER, SUM(FY_COL1)/1000000, SUM(FY_COL2)/1000000, SUM(FY_COL3)/1000000,  2 FROM
(select award_number,unit_name, LEAD_UNIT_NUMBER,(ifnull(A,0)+ifnull(B,0)+ifnull(C,0)+ifnull(D,0)) as 'FY_COL1', (ifnull(F,0)+ifnull(F,0)+ifnull(G,0)+ifnull(H,0)) AS 'FY_COL2', (ifnull(I,0)+ifnull(J,0)+ifnull(K,0)+ifnull(L,0)) AS 'FY_COL3' FROM (
select award_number,BEGIN_DATE, GRANT_PER_MONTH,FINAL_EXPIRATION_DATE,unit_name, LEAD_UNIT_NUMBER
,( case when (concat(COL1,",04,01") <= BEGIN_DATE AND concat(COL2,",03,31")>= BEGIN_DATE AND concat(COL2,",03,31")>= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,BEGIN_DATE, FINAL_EXPIRATION_DATE))*GRANT_PER_MONTH end) AS A
,(case when (concat(COL1,",04,01") >= BEGIN_DATE AND concat(COL2,",03,31")>= FINAL_EXPIRATION_DATE AND concat(COL1,",04,01")<= FINAL_EXPIRATION_DATE) then (TIMESTAMPDIFF(MONTH,concat(COL1,",04,01"), FINAL_EXPIRATION_DATE))*GRANT_PER_MONTH end) AS B,
(case when (concat(COL1,",04,01") >= BEGIN_DATE AND concat(COL2,",03,31")<= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,concat(COL1,",04,01"), concat(COL2,",03,31"))+1)*GRANT_PER_MONTH end) AS C,
(case when (concat(COL1,",04,01") <= BEGIN_DATE AND concat(COL2,",03,31")>= BEGIN_DATE AND concat(COL2,",03,31")<= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,BEGIN_DATE, concat(COL2,",03,31")))*GRANT_PER_MONTH end) AS D
,( case when (concat(COL2,",04,01") <= BEGIN_DATE AND concat(COL2,",03,31")>= BEGIN_DATE AND concat(COL3,",03,31")>= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,BEGIN_DATE, FINAL_EXPIRATION_DATE))*GRANT_PER_MONTH end) AS E
,(case when (concat(COL2,",04,01") >= BEGIN_DATE AND concat(COL3,",03,31")>= FINAL_EXPIRATION_DATE AND concat(COL2,",04,01")<= FINAL_EXPIRATION_DATE) then (TIMESTAMPDIFF(MONTH,concat(COL2,",04,01"), FINAL_EXPIRATION_DATE))*GRANT_PER_MONTH end) AS F,
(case when (concat(COL2,",04,01") >= BEGIN_DATE AND concat(COL3,",03,31")<= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,concat(COL2,",04,01"), concat(COL3,",03,31"))+1)*GRANT_PER_MONTH end) AS G,
(case when (concat(COL2,",04,01") <= BEGIN_DATE AND concat(COL2,",03,31")>= BEGIN_DATE AND concat(COL3,",03,31")<= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,BEGIN_DATE, concat(COL3,",03,31")))*GRANT_PER_MONTH end) AS H
,( case when (concat(COL3,",04,01") <= BEGIN_DATE AND concat(COL2,",03,31")>= BEGIN_DATE AND concat(COL3+1,",03,31")>= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,BEGIN_DATE, FINAL_EXPIRATION_DATE))*GRANT_PER_MONTH end) AS I
,(case when (concat(COL3,",04,01") >= BEGIN_DATE AND concat(COL3+1,",03,31")>= FINAL_EXPIRATION_DATE AND concat(COL3,",04,01")<= FINAL_EXPIRATION_DATE) then (TIMESTAMPDIFF(MONTH,concat(COL3,",04,01"), FINAL_EXPIRATION_DATE))*GRANT_PER_MONTH end) AS J,
(case when (concat(COL3,",04,01") >= BEGIN_DATE AND concat(COL3+1,",03,31")<= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,concat(COL3,",04,01"), concat(COL3+1,",03,31"))+1)*GRANT_PER_MONTH end) AS K,
(case when (concat(COL3,",04,01") <= BEGIN_DATE AND concat(COL2,",03,31")>= BEGIN_DATE AND concat(COL3+1,",03,31")<= FINAL_EXPIRATION_DATE ) then (TIMESTAMPDIFF(MONTH,BEGIN_DATE, concat(COL3+1,",03,31")))*GRANT_PER_MONTH end) AS L
FROM AWARD_MASTER_DATASET_RT
WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND AWARD_STATUS_CODE <> '3'
AND (
		AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
		OR LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
		AND PERSON_ID = AV_PERSON_ID))
group by award_number) AS TAB
) AS TAB2 group by LEAD_UNIT_NUMBER
ORDER BY SORT_ORDER;
ELSEIF AV_WIDGET = 'AWARDS_BY_DEPARTMENT' THEN
if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
END IF;
		SET COL2 = COL3-1;
        SET COL1 = COL2-1;
	select 'Unit Name', 'Lead Unit Number',concat("Awards in ",COL3), COL3,concat("Awards in ",COL2), COL2,concat("Awards in ",COL1),COL1, 'Level', 1 AS SORT_ORDER
    union
	SELECT unit_name,LEAD_UNIT_NUMBER,SUM(COL3_COUNT), SUM(COL3_SUM)/1000000,SUM(COL2_COUNT), SUM(COL2_SUM)/1000000,SUM(COL1_COUNT), SUM(COL1_SUM)/1000000, SS.LVL , 2 FROM
	(
	select DISTINCT unit_name,AWARD_NUMBER, LEAD_UNIT_NUMBER
,case when (BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL3_SUM,
case when (BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then 1 end AS COL3_COUNT,
 case when (BEGIN_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL2_SUM,
 case when (BEGIN_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then 1 end AS COL2_COUNT,
 case when (BEGIN_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL1_SUM,
 case when (BEGIN_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then 1 end AS COL1_COUNT
FROM AWARD_MASTER_DATASET_RT
WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND AWARD_STATUS_CODE <> '3'
AND (
		AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
		OR LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
		AND PERSON_ID = AV_PERSON_ID))
) AS TAB2 inner join (select distinct t2.lvl,t1.UNIT_NUMBER from person_role_rt t1
						inner join UNIT_LEVEL t2 on t1.UNIT_NUMBER = t2.UNIT_NUMBER
						where
                        t1.PERSON_ID = AV_PERSON_ID
						and t1.RIGHT_NAME = 'VIEW_AWARD'
						and t2.lvl in ( select min(s2.LVL) from person_role_rt s1
						inner join UNIT_LEVEL s2 on s1.UNIT_NUMBER = s2.UNIT_NUMBER
						where
                        s1.PERSON_ID = AV_PERSON_ID
						and s1.RIGHT_NAME = 'VIEW_AWARD'
						and s2.LVL > AV_LEVEL)
						and ((AV_UNIT_NUMBER is null and t2.PARENT_UNIT_NUMBER is null) or
                        (AV_UNIT_NUMBER is not null and t2.PARENT_UNIT_NUMBER = AV_UNIT_NUMBER)or
                        AV_UNIT_NUMBER is null and t2.PARENT_UNIT_NUMBER is not null)
						) SS on SS.UNIT_NUMBER = TAB2.LEAD_UNIT_NUMBER
 group by LEAD_UNIT_NUMBER
 order by SORT_ORDER;
 ELSEIF AV_WIDGET = 'SUBMISSION_BASED_CLAIM_AGE' THEN
SELECT COUNT(1) INTO LS_COUNT FROM SPONSOR;
 SET COL3 = '';
 (select 'Sponsor Name','Sponsor Code', concat('Ã”Ã«Ã±30',COL3, ' Days'), concat('31 - 60 Days',COL3) , concat('61 - 90 Days',COL3) , concat('91 - 120 Days',COL3) , concat('121 - 180 Days',COL3) ,concat('>181 Days',COL3) ,CONCAT('Total',COL3))
union
(SELECT SPONSOR_NAME,SPONSOR_CODE,GRT_EQ_30/1000000,GRT_61/1000000,GRT_91/1000000,GRT_121/1000000,GRT_181/1000000,GRTTT_181/1000000,
(ifnull(GRT_EQ_30,0)+ifnull(GRT_61,0)+ifnull(GRT_91,0)+ifnull(GRT_121,0)+ifnull(GRT_181,0)+ifnull(GRTTT_181,0))/1000000 AS Total
 FROM
(SELECT T3.SPONSOR_NAME AS SPONSOR_NAME, T3.SPONSOR_CODE AS SPONSOR_CODE,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<=30 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>0) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_EQ_30,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=31 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<61) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_61,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=61 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<91) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_91,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=91 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<121) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_121,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=121 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<181) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_181,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=181 ) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRTTT_181
FROM CLAIM T1
INNER JOIN AWARD T2 ON T1.AWARD_NUMBER = T2.AWARD_NUMBER AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
INNER JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T2.SPONSOR_CODE
WHERE T1.CLAIM_SUBMISSION_DATE IS NOT NULL
AND T2.STATUS_CODE <> '3'
AND T1.CLAIM_STATUS_CODE <> '4'
AND (
		T2.AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_CLAIMS')
		OR T2.LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_CLAIMS')
		AND PERSON_ID = AV_PERSON_ID))
GROUP BY T3.SPONSOR_CODE
) AS TAB
order by Total desc limit 9)
UNION
(SELECT 'Others','OTHER',SUM(GRT_EQ_30)/1000000,SUM(GRT_61)/1000000,SUM(GRT_91)/1000000,SUM(GRT_121)/1000000,SUM(GRT_181)/1000000,SUM(GRTTT_181)/1000000,
SUM(Total)/1000000 AS Totals from
(SELECT SPONSOR_NAME,SPONSOR_CODE,GRT_EQ_30,GRT_61,GRT_91,GRT_121,GRT_181,GRTTT_181,
ifnull(GRT_EQ_30,0)+ifnull(GRT_61,0)+ifnull(GRT_91,0)+ifnull(GRT_121,0)+ifnull(GRT_181,0)+ifnull(GRTTT_181,0) AS Total
 FROM
(SELECT T3.SPONSOR_NAME,T3.SPONSOR_CODE,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<=30 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>0) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_EQ_30,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=31 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<61) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_61,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=61 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<91) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_91,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=91 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<121) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_121,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=121 AND datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)<181) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRT_181,
SUM(CASE WHEN (datediff(UTC_TIMESTAMP(), T1.CLAIM_SUBMISSION_DATE)>=181 ) then FN_GET_CLAIM_AMOUNT(T2.AWARD_NUMBER, T1.CLAIM_ID) end) AS GRTTT_181
FROM CLAIM T1
INNER JOIN AWARD T2 ON T1.AWARD_NUMBER = T2.AWARD_NUMBER AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
INNER JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T2.SPONSOR_CODE
WHERE T1.CLAIM_SUBMISSION_DATE IS NOT NULL
AND T2.STATUS_CODE <> '3'
AND T1.CLAIM_STATUS_CODE <> '4'
AND (
		T2.AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_CLAIMS')
		OR T2.LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_CLAIMS')
		AND PERSON_ID = AV_PERSON_ID))
GROUP BY T3.SPONSOR_CODE
) AS TAB
order by Total desc limit LS_COUNT offset 1) as TAB2
having count(1)>0);
 ELSEIF AV_WIDGET = 'AWARD_EXPENDITURE_BY_FINANCIAL_YEAR' THEN
		if month(NOW()) >= '4' then
				SET COL3 = YEAR(NOW());
				else
				SET COL3 = YEAR(NOW()) - 1;
		END IF;
				SET COL2 = COL3-1;
				SET COL1 = COL2-1;
		SELECT 'Vote',COL3,COL2,COL1
        UNION
		(SELECT S1.DESCRIPTION AS BUDGET_DESCRIPTION,
	SUM(CASE WHEN (TAB.FM_MONTH >3 AND TAB.FM_YEAR = COL3)OR(TAB.FM_YEAR = COL3+1 AND TAB.FM_MONTH <4) THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS 'A',
	SUM(CASE WHEN (TAB.FM_MONTH >3 AND TAB.FM_YEAR = COL2)OR(TAB.FM_YEAR = COL2+1 AND TAB.FM_MONTH <4) THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS 'B',
	SUM(CASE WHEN (TAB.FM_MONTH >3 AND TAB.FM_YEAR = COL1)OR(TAB.FM_YEAR = COL1+1 AND TAB.FM_MONTH <4) THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS 'C'
FROM BUDGET_CATEGORY S1
LEFT OUTER JOIN
(
	SELECT
	substr(T1.INTERNAL_ORDER_CODE,16,3) as BUDGET_CATEGORY_CODE,
	T3.DESCRIPTION AS BUDGET_CATEGORY,
	SUM(T1.AMOUNT_IN_FMA_CURRENCY) AS TOTAL_EXPENSE_AMOUNT,
	MONTH(FM_POSTING_DATE) AS FM_MONTH,
	YEAR(FM_POSTING_DATE) AS FM_YEAR
	FROM AWARD_EXPENSE_TRANSACTIONS T1
	INNER JOIN AWARD T2 ON T2.AWARD_NUMBER = T1.AWARD_NUMBER
	INNER JOIN BUDGET_CATEGORY T3 ON T3.BUDGET_CATEGORY_CODE = substr(T1.INTERNAL_ORDER_CODE,16,3)
	WHERE T1.ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER FROM AWARD WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE' )
	AND T1.ACTUAL_OR_COMMITTED_FLAG = 'A'
	AND T2.STATUS_CODE <> '3'
	AND substr(T1.INTERNAL_ORDER_CODE,16,3) NOT IN('IRC','COM','GRT','IPP','TSF')
	AND T1.FM_POSTING_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL3+1,"-03-31")
	AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
	AND (T2.AWARD_ID IN (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
			INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
			WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME IN('VIEW_EOM_EXPENDITURE_TO_DATE')
	)
	OR T2.LEAD_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_EOM_EXPENDITURE_TO_DATE') AND PERSON_ID = AV_PERSON_ID)
	)
	GROUP BY YEAR(FM_POSTING_DATE),MONTH(FM_POSTING_DATE),substr(T1.INTERNAL_ORDER_CODE,16,3)) TAB
ON TAB.BUDGET_CATEGORY_CODE = S1.BUDGET_CATEGORY_CODE
WHERE S1.BUDGET_CATEGORY_CODE NOT IN('IRC','COM','GRT','IPP','TSF')
GROUP BY S1.BUDGET_CATEGORY_CODE ORDER BY BUDGET_DESCRIPTION);
 ELSEIF AV_WIDGET = 'AWARD_EXPENDITURE_BY_CURRENT_YEAR' THEN
 if month(NOW()) >= '4' then
				SET COL3 = YEAR(NOW());
				else
				SET COL3 = YEAR(NOW()) - 1;
END IF;
				SET COL2 = COL3+1;
		SELECT 'Vote', CONCAT('APR ',COL3),CONCAT('MAY ',COL3),CONCAT('JUN ',COL3),CONCAT('JUL ',COL3),CONCAT('AUG ',COL3),CONCAT('SEP ',COL3),CONCAT('OCT ',COL3),CONCAT('NOV ',COL3),CONCAT('DEC ',COL3),CONCAT('JAN ',COL2),CONCAT('FEB ',COL2),CONCAT('MAR ',COL2)
UNION
	(SELECT S1.DESCRIPTION AS BUDGET_DESCRIPTION,
	SUM(CASE WHEN TAB.FM_MONTH = 4 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS APR,
	SUM(CASE WHEN TAB.FM_MONTH = 5 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS MAY,
	SUM(CASE WHEN TAB.FM_MONTH = 6 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS JUN,
	SUM(CASE WHEN TAB.FM_MONTH = 7 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS JUL,
	SUM(CASE WHEN TAB.FM_MONTH = 8 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS AUG,
	SUM(CASE WHEN TAB.FM_MONTH = 9 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS SEP,
	SUM(CASE WHEN TAB.FM_MONTH = 10 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS OCT,
	SUM(CASE WHEN TAB.FM_MONTH = 11 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS NOV,
	SUM(CASE WHEN TAB.FM_MONTH = 12 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS DECE,
	SUM(CASE WHEN TAB.FM_MONTH = 1 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS JAN,
	SUM(CASE WHEN TAB.FM_MONTH = 2 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS FEB,
	SUM(CASE WHEN TAB.FM_MONTH = 3 THEN TAB.TOTAL_EXPENSE_AMOUNT END)/1000000 AS MAR
	FROM
	BUDGET_CATEGORY S1 LEFT OUTER JOIN
	(SELECT
	substr(T1.INTERNAL_ORDER_CODE,16,3) as BUDGET_CATEGORY_CODE,
	T3.DESCRIPTION AS BUDGET_CATEGORY,
	SUM(T1.AMOUNT_IN_FMA_CURRENCY) AS TOTAL_EXPENSE_AMOUNT,
	MONTH(FM_POSTING_DATE) AS FM_MONTH
	FROM AWARD_EXPENSE_TRANSACTIONS T1
	INNER JOIN AWARD T2 ON T2.AWARD_NUMBER = T1.AWARD_NUMBER
	INNER JOIN BUDGET_CATEGORY T3 ON T3.BUDGET_CATEGORY_CODE = substr(T1.INTERNAL_ORDER_CODE,16,3)
	WHERE T1.ACCOUNT_NUMBER IN (SELECT ACCOUNT_NUMBER FROM AWARD WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE' )
	AND T1.ACTUAL_OR_COMMITTED_FLAG = 'A'
	AND T2.STATUS_CODE <> '3'
	AND substr(T1.INTERNAL_ORDER_CODE,16,3) NOT IN('IRC','COM','GRT','IPP','TSF')
	AND T1.FM_POSTING_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL2,"-03-31")
	AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
	AND (T2.AWARD_ID IN (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
			INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
			WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME IN('VIEW_EOM_EXPENDITURE_TO_DATE')
	)
	OR T2.LEAD_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_EOM_EXPENDITURE_TO_DATE') AND PERSON_ID = AV_PERSON_ID)
	)
	GROUP BY MONTH(FM_POSTING_DATE),substr(T1.INTERNAL_ORDER_CODE,16,3)) TAB
	ON TAB.BUDGET_CATEGORY_CODE = S1.BUDGET_CATEGORY_CODE
    WHERE S1.BUDGET_CATEGORY_CODE NOT IN('IRC','COM','GRT','IPP','TSF')
	GROUP BY S1.BUDGET_CATEGORY_CODE ORDER BY BUDGET_DESCRIPTION);
ELSEIF AV_WIDGET = 'AWARDS_BY_DEPARTMENT_INTERNAL' THEN
 if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
END IF;
		SET COL2 = COL3-1;
        SET COL1 = COL2-1;
	select 'Unit Name', 'Lead Unit Number',concat("Awards in ",COL3), COL3,concat("Awards in ",COL2), COL2,concat("Awards in ",COL1),COL1, 'Level', 1 AS SORT_ORDER
    union
	SELECT unit_name,LEAD_UNIT_NUMBER,SUM(COL3_COUNT), SUM(COL3_SUM)/1000000,SUM(COL2_COUNT), SUM(COL2_SUM)/1000000,SUM(COL1_COUNT), SUM(COL1_SUM)/1000000, SS.LVL , 2 FROM
(
select DISTINCT unit_name,AWARD_NUMBER, LEAD_UNIT_NUMBER
,case when (BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL3_SUM,
case when (BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then 1 end AS COL3_COUNT,
 case when (BEGIN_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL2_SUM,
 case when (BEGIN_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then 1 end AS COL2_COUNT,
 case when (BEGIN_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL1_SUM,
 case when (BEGIN_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then 1 end AS COL1_COUNT
FROM AWARD_MASTER_DATASET_RT
WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND AWARD_STATUS_CODE <> '3'
AND FUND_CODE = 'G_DESIGNAT'
AND (
		AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
		OR LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
		AND PERSON_ID = AV_PERSON_ID))
) AS TAB2 inner join (select distinct t2.lvl,t1.UNIT_NUMBER from person_role_rt t1
						inner join UNIT_LEVEL t2 on t1.UNIT_NUMBER = t2.UNIT_NUMBER
						where
                        t1.PERSON_ID = AV_PERSON_ID
						and t1.RIGHT_NAME = 'VIEW_AWARD'
						and t2.lvl in ( select min(s2.LVL) from person_role_rt s1
						inner join UNIT_LEVEL s2 on s1.UNIT_NUMBER = s2.UNIT_NUMBER
						where
                        s1.PERSON_ID = AV_PERSON_ID
						and s1.RIGHT_NAME = 'VIEW_AWARD'
						and s2.LVL > AV_LEVEL)
						and ((AV_UNIT_NUMBER is null and t2.PARENT_UNIT_NUMBER is null) or
                        (AV_UNIT_NUMBER is not null and t2.PARENT_UNIT_NUMBER = AV_UNIT_NUMBER)or
                        AV_UNIT_NUMBER is null and t2.PARENT_UNIT_NUMBER is not null)
						) SS on SS.UNIT_NUMBER = TAB2.LEAD_UNIT_NUMBER
 group by LEAD_UNIT_NUMBER
 order by SORT_ORDER;
ELSEIF AV_WIDGET = 'AWARDS_BY_DEPARTMENT_EXTERNAL' THEN
  if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
END IF;
		SET COL2 = COL3-1;
        SET COL1 = COL2-1;
	select 'Unit Name', 'Lead Unit Number',concat("Awards in ",COL3), COL3,concat("Awards in ",COL2), COL2,concat("Awards in ",COL1),COL1, 'Level', 1 AS SORT_ORDER
    union
	SELECT unit_name,LEAD_UNIT_NUMBER,SUM(COL3_COUNT), SUM(COL3_SUM)/1000000,SUM(COL2_COUNT), SUM(COL2_SUM)/1000000,SUM(COL1_COUNT), SUM(COL1_SUM)/1000000, SS.LVL , 2 FROM
(
select DISTINCT unit_name,AWARD_NUMBER, LEAD_UNIT_NUMBER
,case when (BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL3_SUM,
case when (BEGIN_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")) then 1 end AS COL3_COUNT,
 case when (BEGIN_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL2_SUM,
 case when (BEGIN_DATE BETWEEN concat(COL2,"-04-01") AND concat(COL2+1,"-03-31")) then 1 end AS COL2_COUNT,
 case when (BEGIN_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then ANTICIPATED_TOTAL_AMOUNT end AS COL1_SUM,
 case when (BEGIN_DATE BETWEEN concat(COL1,"-04-01") AND concat(COL1+1,"-03-31")) then 1 end AS COL1_COUNT
FROM AWARD_MASTER_DATASET_RT
WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND AWARD_STATUS_CODE <> '3'
AND FUND_CODE = 'R_RESFUND'
AND (
		AWARD_ID  IN
		(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
		OR LEAD_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
		AND PERSON_ID = AV_PERSON_ID))
) AS TAB2 inner join (select distinct t2.lvl,t1.UNIT_NUMBER from person_role_rt t1
						inner join UNIT_LEVEL t2 on t1.UNIT_NUMBER = t2.UNIT_NUMBER
						where
                        t1.PERSON_ID = AV_PERSON_ID
						and t1.RIGHT_NAME = 'VIEW_AWARD'
						and t2.lvl in ( select min(s2.LVL) from person_role_rt s1
						inner join UNIT_LEVEL s2 on s1.UNIT_NUMBER = s2.UNIT_NUMBER
						where
                        s1.PERSON_ID = AV_PERSON_ID
						and s1.RIGHT_NAME = 'VIEW_AWARD'
						and s2.LVL > AV_LEVEL)
						and ((AV_UNIT_NUMBER is null and t2.PARENT_UNIT_NUMBER is null) or
                        (AV_UNIT_NUMBER is not null and t2.PARENT_UNIT_NUMBER = AV_UNIT_NUMBER)or
                        AV_UNIT_NUMBER is null and t2.PARENT_UNIT_NUMBER is not null)
						) SS on SS.UNIT_NUMBER = TAB2.LEAD_UNIT_NUMBER
 group by LEAD_UNIT_NUMBER
 order by SORT_ORDER;
 ELSEIF AV_WIDGET = 'AWARD_ENDED_BUT_NOT_CLOSED' THEN
	 SELECT GROUPED, COUNT(1)FROM (SELECT DISTINCT
		CASE WHEN DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) <=90 THEN 'Open 90 days'
		WHEN DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) >90 AND DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) <=180 THEN '91 - 180 days'
		WHEN DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) >180 AND DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) <=365 THEN '181 - 365 days'
		ELSE '> 365 days'END AS GROUPED,
        CASE WHEN DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) <=90 THEN 1
		WHEN DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) >90 AND DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) <=180 THEN 2
		WHEN DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) >180 AND DATEDIFF(UTC_TIMESTAMP(),FINAL_EXPIRATION_DATE) <=365 THEN 3
		ELSE 4 END AS SORT,
        AWARD_NUMBER
		FROM AWARD_MASTER_DATASET_RT
		WHERE UTC_TIMESTAMP() > FINAL_EXPIRATION_DATE
		AND AWARD_STATUS_CODE = '15'
		AND (
			AWARD_ID  IN
			(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
			INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
			WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
			OR LEAD_UNIT_NUMBER IN (
			SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
			AND PERSON_ID = AV_PERSON_ID
			))) AS TAB
		GROUP BY GROUPED ORDER BY SORT;
 ELSEIF AV_WIDGET = 'ATTENTION_LIST' THEN
 SELECT 'Sponsor Ref number / Proposal Number', 'Project Title','Item/ Task/ Reminder', 'Due Date', 'Module', 'id', 1 AS SORT_ORDER
	UNION
(SELECT T2.SPONSOR_AWARD_NUMBER AS REF_NUMBER,T2.TITLE AS TITLE, 'Outstanding Progress/Final Report' AS ITEM, T2.FINAL_EXPIRATION_DATE AS DUE_DATE,16,T1.PROGRESS_REPORT_ID, 2 AS SORT_ORDER FROM AWARD_PROGRESS_REPORT T1
INNER JOIN AWARD T2 ON T1.AWARD_ID = T2.AWARD_ID
WHERE T1.PROGRESS_REPORT_STATUS_CODE = 1
AND DATEDIFF(T2.FINAL_EXPIRATION_DATE,UTC_TIMESTAMP()) BETWEEN 0 AND 30
AND T2.AWARD_SEQUENCE_STATUS = 'ACTIVE'
AND T2.STATUS_CODE <> '3'
AND (T1.AWARD_ID  IN
    (SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
	INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
	WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
	OR T2.LEAD_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_AWARD')
								AND PERSON_ID = AV_PERSON_ID)
	) ORDER BY T2.FINAL_EXPIRATION_DATE)
	UNION
(SELECT T1.PROPOSAL_ID AS REF_NUMBER, T1.TITLE AS TITLE, 'Proposal Task',T2.CLOSING_DATE AS DUE_DATE,3, T1.PROPOSAL_ID, 3 AS SORT_ORDER FROM EPS_PROPOSAL T1
	INNER JOIN GRANT_CALL_HEADER T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
	WHERE T1.STATUS_CODE IN(1,3,9,12)
	AND T1.DOCUMENT_STATUS_CODE <> '3' AND DATEDIFF(T2.CLOSING_DATE,UTC_TIMESTAMP()) BETWEEN 0 AND 7
  AND (T1.PROPOSAL_ID  IN
    (SELECT T1.PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES T1
    INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
	INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
	WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_PROPOSAL')
	OR T2.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_PROPOSAL')
								AND PERSON_ID = AV_PERSON_ID)
	)
    ORDER BY T2.CLOSING_DATE)
ORDER BY SORT_ORDER ASC;
ELSEIF AV_WIDGET = 'PROPOSAL_SUBMITTED_BY_LEAD_UNIT' THEN
	if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SELECT T1.HOME_UNIT_NAME,
		SUM(CASE WHEN T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) THEN 1 END) AS SUBMITTED,
		SUM(CASE WHEN T1.STATUS_CODE = 40 THEN 1 END) AS SHORTLISTED,
		SUM(CASE WHEN T1.STATUS_CODE = 11 THEN 1 END) AS AWARDED
FROM EPS_PROPOSAL T1
WHERE
T1.SUBMISSION_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
AND
(
    T1.PROPOSAL_ID  IN
    (SELECT S1.PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES S1
    INNER JOIN ROLE_RIGHTS S2 ON S1.ROLE_ID = S2.ROLE_ID
	INNER JOIN RIGHTS S3 ON S3.RIGHT_ID = S2.RIGHT_ID
	WHERE S1.PERSON_ID = AV_PERSON_ID AND S3.RIGHT_NAME = 'VIEW_PROPOSAL')
	OR T1.HOME_UNIT_NUMBER IN (
	SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_PROPOSAL')AND PERSON_ID = AV_PERSON_ID)
	)
AND T1.DOCUMENT_STATUS_CODE <> '3' AND T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) GROUP BY T1.HOME_UNIT_NUMBER;
ELSEIF AV_WIDGET = 'PROPOSAL_BY_SPONSOR' THEN
	if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SELECT COUNT(1) INTO LS_COUNT FROM SPONSOR;
	(SELECT IFNULL(T2.SPONSOR_GROUP,T2.SPONSOR_NAME) AS SPONSOR_NAME,
		SUM(CASE WHEN T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) THEN 1 END) AS SUBMITTED,
		SUM(CASE WHEN T1.STATUS_CODE = 40 THEN 1 END) AS SHORTLISTED,
		SUM(CASE WHEN T1.STATUS_CODE = 11 THEN 1 END) AS AWARDED
FROM EPS_PROPOSAL T1
INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE
WHERE
T1.SUBMISSION_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
AND T1.DOCUMENT_STATUS_CODE <> '3' AND
(
    T1.PROPOSAL_ID  IN
    (SELECT S1.PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES S1
    INNER JOIN ROLE_RIGHTS S2 ON S1.ROLE_ID = S2.ROLE_ID
	INNER JOIN RIGHTS S3 ON S3.RIGHT_ID = S2.RIGHT_ID
	WHERE S1.PERSON_ID = AV_PERSON_ID AND S3.RIGHT_NAME = 'VIEW_PROPOSAL')
	OR T1.HOME_UNIT_NUMBER IN (
	SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_PROPOSAL')AND PERSON_ID = AV_PERSON_ID)
	)
AND T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) GROUP BY IFNULL(T2.SPONSOR_GROUP,T2.SPONSOR_CODE) order by count(1) desc limit 9)
UNION
SELECT 'Others', SUM(TAB.SUBMITTED),SUM(TAB.SHORTLISTED), SUM(TAB.AWARDED)
from
(SELECT 'OTHER' AS SPONSOR_CODE, T2.SPONSOR_NAME,
		SUM(CASE WHEN T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) THEN 1 END) AS SUBMITTED,
		SUM(CASE WHEN T1.STATUS_CODE = 40 THEN 1 END) AS SHORTLISTED,
		SUM(CASE WHEN T1.STATUS_CODE = 11 THEN 1 END) AS AWARDED
FROM EPS_PROPOSAL T1
INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE
WHERE
T1.SUBMISSION_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
AND T1.DOCUMENT_STATUS_CODE <> '3' AND
(
    T1.PROPOSAL_ID  IN
    (SELECT S1.PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES S1
    INNER JOIN ROLE_RIGHTS S2 ON S1.ROLE_ID = S2.ROLE_ID
	INNER JOIN RIGHTS S3 ON S3.RIGHT_ID = S2.RIGHT_ID
	WHERE S1.PERSON_ID = AV_PERSON_ID AND S3.RIGHT_NAME = 'VIEW_PROPOSAL')
	OR T1.HOME_UNIT_NUMBER IN (
	SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_PROPOSAL')AND PERSON_ID = AV_PERSON_ID)
	)
AND T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) GROUP BY IFNULL(T2.SPONSOR_GROUP,T2.SPONSOR_CODE) HAVING COUNT(1) > 0 ORDER BY COUNT(1) DESC LIMIT LS_COUNT OFFSET 9) AS TAB GROUP BY TAB.SPONSOR_CODE;
ELSEIF AV_WIDGET = 'PROPOSAL_BY_FUNDING_SCHEME' THEN
if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SELECT T4.SCHEME_NAME,
			SUM(CASE WHEN T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) THEN 1 END) AS SUBMITTED,
			SUM(CASE WHEN T1.STATUS_CODE = 40 THEN 1 END) AS SHORTLISTED,
			SUM(CASE WHEN T1.STATUS_CODE = 11 THEN 1 END) AS AWARDED
	FROM EPS_PROPOSAL T1
	INNER JOIN GRANT_CALL_HEADER T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
	INNER JOIN SPONSOR_FUNDING_SCHEME T3 ON T2.FUNDING_SCHEME_ID = T3.FUNDING_SCHEME_ID
	INNER JOIN FUNDING_SCHEME T4 ON T3.FUNDING_SCHEME_CODE = T4.FUNDING_SCHEME_CODE
	WHERE T1.SUBMISSION_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
	AND
    (
		T1.PROPOSAL_ID  IN
		(SELECT S1.PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES S1
		INNER JOIN ROLE_RIGHTS S2 ON S1.ROLE_ID = S2.ROLE_ID
		INNER JOIN RIGHTS S3 ON S3.RIGHT_ID = S2.RIGHT_ID
		WHERE S1.PERSON_ID = AV_PERSON_ID AND S3.RIGHT_NAME = 'VIEW_PROPOSAL')
		OR T1.HOME_UNIT_NUMBER IN (
		SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_PROPOSAL')AND PERSON_ID = AV_PERSON_ID)
		)
	AND T1.DOCUMENT_STATUS_CODE <> '3' AND T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) GROUP BY T4.FUNDING_SCHEME_CODE;
ELSEIF AV_WIDGET = 'PROPOSAL_BY_GRANT_CALL' THEN
if month(NOW()) >= '4' then
		SET COL3 = YEAR(NOW());
        else
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SELECT T2.NAME,
		SUM(CASE WHEN T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) THEN 1 END) AS SUBMITTED,
		SUM(CASE WHEN T1.STATUS_CODE = 40 THEN 1 END) AS SHORTLISTED,
		SUM(CASE WHEN T1.STATUS_CODE = 11 THEN 1 END) AS AWARDED
FROM EPS_PROPOSAL T1
INNER JOIN GRANT_CALL_HEADER T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
WHERE T1.SUBMISSION_DATE BETWEEN concat(COL3,"-04-01") AND concat(COL3+1,"-03-31")
AND
(
    T1.PROPOSAL_ID  IN
    (SELECT S1.PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES S1
    INNER JOIN ROLE_RIGHTS S2 ON S1.ROLE_ID = S2.ROLE_ID
	INNER JOIN RIGHTS S3 ON S3.RIGHT_ID = S2.RIGHT_ID
	WHERE S1.PERSON_ID = AV_PERSON_ID AND S3.RIGHT_NAME = 'VIEW_PROPOSAL')
	OR T1.HOME_UNIT_NUMBER IN (
	SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('VIEW_PROPOSAL')AND PERSON_ID = AV_PERSON_ID)
	)
AND T1.DOCUMENT_STATUS_CODE <> '3' AND T1.STATUS_CODE IN (38,11,40,29,8,2,37,41) GROUP BY T2.GRANT_HEADER_ID;
ELSEIF AV_WIDGET = 'PENDING_PROPOSAL_BY_SPONSOR_TYPE' THEN
	SELECT T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION AS SPONSOR_TYPE,COUNT(1), SUM(T4.TOTAL_COST) AS TOTAL_COST FROM EPS_PROPOSAL T1
    LEFT JOIN (SELECT SPONSOR_TYPE_CODE,SPONSOR_CODE from SPONSOR) T2 ON T1.SPONSOR_CODE=T2.SPONSOR_CODE
	INNER JOIN SPONSOR_TYPE T3 ON T2.SPONSOR_TYPE_CODE=T3.SPONSOR_TYPE_CODE
    LEFT JOIN (SELECT TOTAL_COST,IS_LATEST_VERSION,BUDGET_HEADER_ID,PROPOSAL_ID FROM  BUDGET_HEADER
            WHERE IS_LATEST_VERSION = 'Y' GROUP BY BUDGET_HEADER_ID) T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID
    WHERE T1.STATUS_CODE = 41 AND T1.DOCUMENT_STATUS_CODE <> '3' AND (AV_UNIT_NUMBER is null OR T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL
	WHERE HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM PERSON_ROLE_RT WHERE RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') AND PERSON_ID = AV_PERSON_ID)
	UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID UNION
	SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = AV_PERSON_ID UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1
	INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID WHERE S1.IS_WORKFLOW_ACTIVE = 'Y' AND S2.APPROVER_PERSON_ID = AV_PERSON_ID
	AND S1.MODULE_CODE = 3) GROUP BY T2.SPONSOR_TYPE_CODE, T3.DESCRIPTION;
END IF;
END
$$
DELIMITER ;
