DELIMITER $$
CREATE  PROCEDURE `MERGE_AWD_SECTION_OTHER_INFORMATION`(
AV_AWARD_ID 			DECIMAL(22,0),
AV_AWARD_NUMBER			VARCHAR(12),
AV_SEQUENCE_NUMBER		INT(4),
AV_VARIATION_TYPE_CODE	VARCHAR(3),
AV_UPDATE_USER			VARCHAR(60)
)
BEGIN
DECLARE LS_ERROR_MSG	VARCHAR(1000);
DECLARE LS_TABLE_NAME	VARCHAR(30);
DECLARE LI_FLAG			INT;
DECLARE LI_NEXT_VAL	INT(10);
DECLARE LI_MASTER_AWARD_ID	DECIMAL(22,0);
DECLARE LI_TOTAL_AWARD_CUSTOM_DATA INT(10);
DECLARE LI_CUSTOM_DATA_ID	int(22);
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID	int(10);
DECLARE LI_MODULE_ITEM_CODE	int(3);
DECLARE LI_MODULE_SUB_ITEM_CODE	int(30);
DECLARE LS_MODULE_ITEM_KEY	varchar(20);
DECLARE LS_MODULE_SUB_ITEM_KEY	varchar(20);
DECLARE LS_VALUE	varchar(4000);
DECLARE LD_UPDATE_TIMESTAMP	datetime;
DECLARE LS_UPDATE_USER	varchar(60);
DECLARE LI_COLUMN_ID	int(6);
DECLARE LI_COLUMN_VERSION_NUMBER	int(4);
DECLARE LS_DESCRIPTION	varchar(255);
DECLARE LS_DOCUMENT_UPDATE_USER			VARCHAR(60);
DECLARE LS_DOCUMENT_UPDATE_TIMESTAMP	DATETIME;
		BEGIN
				DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
				BEGIN
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
					SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
					SELECT @full_error INTO LS_ERROR_MSG;
					INSERT INTO AWARD_ERROR_LOG(AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, ERROR_MESSAGE, PROCEDURE_NAME, TABLE_NAME,SECTION_CODE,VARIATION_TYPE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(AV_AWARD_ID,AV_AWARD_NUMBER,AV_SEQUENCE_NUMBER,LS_ERROR_MSG,'MERGE_AWD_OTHER_INFORMATION',LS_TABLE_NAME,120,AV_VARIATION_TYPE_CODE,UTC_TIMESTAMP(),AV_UPDATE_USER);
					COMMIT;
				END;
				SET SQL_SAFE_UPDATES = 0;
				SET LS_TABLE_NAME = 'CUSTOM_DATA';
				SELECT COUNT(1) INTO LI_FLAG
				FROM AWARD
				WHERE AWARD_NUMBER = AV_AWARD_NUMBER
				AND SEQUENCE_NUMBER = 0;
				IF LI_FLAG > 0 THEN
					SELECT AWARD_ID INTO LI_MASTER_AWARD_ID
					FROM AWARD
					WHERE AWARD_NUMBER = AV_AWARD_NUMBER
					AND SEQUENCE_NUMBER = 0;
				END IF;
				DELETE FROM CUSTOM_DATA
				WHERE MODULE_ITEM_KEY = LI_MASTER_AWARD_ID
				AND MODULE_ITEM_CODE = 1
				AND MODULE_SUB_ITEM_CODE = 0
				AND MODULE_SUB_ITEM_KEY = 0;
				SELECT COUNT(*) INTO LI_TOTAL_AWARD_CUSTOM_DATA
				FROM CUSTOM_DATA
				WHERE MODULE_ITEM_KEY = AV_AWARD_ID
				AND MODULE_ITEM_CODE = 1
				AND MODULE_SUB_ITEM_CODE = 0
				AND MODULE_SUB_ITEM_KEY = 0;
				SELECT IFNULL(max(NEXT_VAL),0) INTO LI_NEXT_VAL FROM CUSTOM_DATA_ID_GENERATOR;
				UPDATE CUSTOM_DATA_ID_GENERATOR SET NEXT_VAL = LI_NEXT_VAL + LI_TOTAL_AWARD_CUSTOM_DATA  + 1;
				COMMIT;
				BEGIN
					DECLARE DONE1 INT DEFAULT FALSE;
					DECLARE CUR_AWARD_CUSTOM_DATA CURSOR FOR
					SELECT CUSTOM_DATA_ID,
							CUSTOM_DATA_ELEMENTS_ID,
							MODULE_ITEM_CODE,
							MODULE_SUB_ITEM_CODE,
							MODULE_ITEM_KEY,
							MODULE_SUB_ITEM_KEY,
							VALUE,
							UPDATE_TIMESTAMP,
							UPDATE_USER,
							COLUMN_ID,
							COLUMN_VERSION_NUMBER,
							DESCRIPTION
					FROM CUSTOM_DATA
					WHERE MODULE_ITEM_KEY = AV_AWARD_ID
                    AND MODULE_ITEM_CODE = 1
					AND MODULE_SUB_ITEM_CODE = 0
					AND MODULE_SUB_ITEM_KEY = 0;
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
					OPEN CUR_AWARD_CUSTOM_DATA;
					INSERT_AWARD_CUSTOM_DATA_LOOP: LOOP
					FETCH CUR_AWARD_CUSTOM_DATA INTO
					LI_CUSTOM_DATA_ID,
					LI_CUSTOM_DATA_ELEMENTS_ID,
					LI_MODULE_ITEM_CODE,
					LI_MODULE_SUB_ITEM_CODE,
					LS_MODULE_ITEM_KEY,
					LS_MODULE_SUB_ITEM_KEY,
					LS_VALUE,
					LD_UPDATE_TIMESTAMP,
					LS_UPDATE_USER,
					LI_COLUMN_ID,
					LI_COLUMN_VERSION_NUMBER,
					LS_DESCRIPTION;
					IF DONE1 THEN
						LEAVE INSERT_AWARD_CUSTOM_DATA_LOOP;
					END IF;
						SET LI_NEXT_VAL = LI_NEXT_VAL+1;
						INSERT INTO CUSTOM_DATA
						(CUSTOM_DATA_ID,
							CUSTOM_DATA_ELEMENTS_ID,
							MODULE_ITEM_CODE,
							MODULE_SUB_ITEM_CODE,
							MODULE_ITEM_KEY,
							MODULE_SUB_ITEM_KEY,
							VALUE,
							UPDATE_TIMESTAMP,
							UPDATE_USER,
							COLUMN_ID,
							COLUMN_VERSION_NUMBER,
							DESCRIPTION)
						VALUES
						(LI_NEXT_VAL,
						LI_CUSTOM_DATA_ELEMENTS_ID,
						LI_MODULE_ITEM_CODE,
						LI_MODULE_SUB_ITEM_CODE,
						LI_MASTER_AWARD_ID,
						LS_MODULE_SUB_ITEM_KEY,
						LS_VALUE,
						LD_UPDATE_TIMESTAMP,
						LS_UPDATE_USER,
						LI_COLUMN_ID,
						LI_COLUMN_VERSION_NUMBER,
						LS_DESCRIPTION);
					END LOOP;
					CLOSE CUR_AWARD_CUSTOM_DATA;
				END;
		END;
END
$$
DELIMITER ;
