DELIMITER $$
CREATE  PROCEDURE `MERGE_AWD_SECTION_ROLES`(
AV_AWARD_ID 			DECIMAL(22,0),
AV_AWARD_NUMBER			VARCHAR(12),
AV_SEQUENCE_NUMBER		INT(4),
AV_VARIATION_TYPE_CODE	VARCHAR(3),
AV_UPDATE_USER			VARCHAR(60)
)
BEGIN
DECLARE LS_ERROR_MSG						VARCHAR(1000);
DECLARE LS_TABLE_NAME						VARCHAR(30);
DECLARE LI_FLAG								INT;
DECLARE LI_MASTER_AWARD_ID					DECIMAL(22,0);
DECLARE LI_MASTER_SEQ_NUMBER				INT(4);
DECLARE LI_AWARD_PERSON_ROLE_ID_NEXT_VAL	BIGINT(20);
DECLARE LI_AWARD_PERSON_ROLE_ID_CNT			INT(10);
DECLARE LS_PERSON_ID				VARCHAR(40);
DECLARE LI_ROLE_ID					INT(5);
DECLARE LS_UPDATE_TIMESTAMP			DATETIME;
DECLARE LS_UPDATE_USER				VARCHAR(60);
DECLARE LI_IS_SYSTEM_GENERATED			VARCHAR(1);
DECLARE LS_DOCUMENT_UPDATE_USER			VARCHAR(60);
DECLARE LS_DOCUMENT_UPDATE_TIMESTAMP	DATETIME;
	BEGIN
			DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
			BEGIN
				GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
				 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
				SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
				SELECT @full_error INTO LS_ERROR_MSG;
				INSERT INTO AWARD_ERROR_LOG(AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, ERROR_MESSAGE, PROCEDURE_NAME, TABLE_NAME,SECTION_CODE,VARIATION_TYPE_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(AV_AWARD_ID,AV_AWARD_NUMBER,AV_SEQUENCE_NUMBER,LS_ERROR_MSG,'MERGE_AWD_SECTION_ROLES',LS_TABLE_NAME,107,AV_VARIATION_TYPE_CODE,UTC_TIMESTAMP(),AV_UPDATE_USER);
				COMMIT;
			END;
			SELECT COUNT(1) INTO LI_FLAG
			FROM AWARD
			WHERE AWARD_NUMBER = AV_AWARD_NUMBER
			AND SEQUENCE_NUMBER = 0;
			IF LI_FLAG > 0 THEN
				SELECT AWARD_ID,SEQUENCE_NUMBER
				INTO LI_MASTER_AWARD_ID,LI_MASTER_SEQ_NUMBER
				FROM AWARD
				WHERE AWARD_NUMBER = AV_AWARD_NUMBER
				AND SEQUENCE_NUMBER = 0;
			END IF;
			DELETE FROM AWARD_PERSON_ROLES
			WHERE AWARD_ID = LI_MASTER_AWARD_ID;
			SELECT IFNULL(MAX(NEXT_VAL),0) INTO LI_AWARD_PERSON_ROLE_ID_NEXT_VAL
			FROM AWARD_PERSON_ROLE_ID_GENERATOR;
			SELECT COUNT(1) INTO LI_AWARD_PERSON_ROLE_ID_CNT
			FROM AWARD_PERSON_ROLES
			WHERE AWARD_ID = AV_AWARD_ID;
			UPDATE AWARD_PERSON_ROLE_ID_GENERATOR
			SET NEXT_VAL = LI_AWARD_PERSON_ROLE_ID_NEXT_VAL + LI_AWARD_PERSON_ROLE_ID_CNT + 1;
			COMMIT;
			SET LS_TABLE_NAME = 'AWARD_PERSON_ROLES';
            BEGIN
				DECLARE DONE1 INT DEFAULT FALSE;
				DECLARE CUR_AWARD_PERSON_ROLES CURSOR FOR
				SELECT
					PERSON_ID,
					ROLE_ID,
					UPDATE_TIMESTAMP,
					UPDATE_USER,
					IS_SYSTEM_GENERATED
				FROM AWARD_PERSON_ROLES
				WHERE AWARD_ID = AV_AWARD_ID;
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
				OPEN CUR_AWARD_PERSON_ROLES;
				INSERT_CUR_AWARD_PERSON_LOOP: LOOP
				FETCH CUR_AWARD_PERSON_ROLES INTO
				LS_PERSON_ID,
				LI_ROLE_ID,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER,
				LI_IS_SYSTEM_GENERATED;
				IF DONE1 THEN
					LEAVE INSERT_CUR_AWARD_PERSON_LOOP;
				END IF;
				SET LI_AWARD_PERSON_ROLE_ID_NEXT_VAL = LI_AWARD_PERSON_ROLE_ID_NEXT_VAL + 1;
				INSERT INTO AWARD_PERSON_ROLES(
				AWARD_PERSON_ROLE_ID,
				AWARD_ID,
				AWARD_NUMBER,
				SEQUENCE_NUMBER,
				PERSON_ID,
				ROLE_ID,
				UPDATE_TIMESTAMP,
				UPDATE_USER,
				IS_SYSTEM_GENERATED
				)
				VALUES
				(
				LI_AWARD_PERSON_ROLE_ID_NEXT_VAL,
				LI_MASTER_AWARD_ID,
				AV_AWARD_NUMBER,
				LI_MASTER_SEQ_NUMBER,
				LS_PERSON_ID,
				LI_ROLE_ID,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER,
				LI_IS_SYSTEM_GENERATED
				);
				END LOOP;
				CLOSE CUR_AWARD_PERSON_ROLES;
			END;
	END;
END
$$
DELIMITER ;
