DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_PROPOSAL_PERSONS`(
)
BEGIN
DECLARE LS_APPLICATION_ID 				VARCHAR(50);
DECLARE LS_PROJECT_TEAM_MEMBER_TYPE 	VARCHAR(50);
DECLARE LS_NT_LOGIN_ID 					VARCHAR(60);
DECLARE LS_PROJECT_TEAM_NAME 			VARCHAR(100);
DECLARE LS_PROJECT_TEAM_DESIGNATION 	VARCHAR(100);
DECLARE LS_SEQUENCE_PROJECT_TEAM 		VARCHAR(100);
DECLARE LS_PROJECT_TEAM_ROLE 			VARCHAR(100);
DECLARE LS_PROJECT_TEAM_PERCENT_EFFORT 	VARCHAR(10);
DECLARE LS_PROJECT_TEAM_DEPARTMENT 		VARCHAR(1000);
DECLARE LS_PROJECT_TEAM_ORGANISATION 	VARCHAR(1000);
DECLARE LS_PROJECT_TEAM_COUNTRY 		VARCHAR(100);
DECLARE LS_PROJECT_TEAM_CV 				VARCHAR(100);
DECLARE LS_PROJECT_TEAM_TRACK 			VARCHAR(100);
DECLARE LI_FLAG							INT;
DECLARE LI_COUNT 						INT;
DECLARE LI_SEQ_ERROR_LOG_ID 			INT;
DECLARE LS_ERROR_MSG 					VARCHAR(1000);
DECLARE LI_MISSING_ID					INT;
DECLARE LS_ORAGANIZATION_ID				VARCHAR(10);
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON',LS_ERROR_MSG,'PRE_VALIDATION',NOW(),'quickstart');
		COMMIT;
	END;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT
			APPLICATION_ID,
			PROJECT_TEAM_MEMBER_TYPE,
			NT_LOGIN_ID,
			PROJECT_TEAM_NAME,
			PROJECT_TEAM_DESIGNATION,
			SEQUENCE_PROJECT_TEAM,
			PROJECT_TEAM_ROLE,
			PROJECT_TEAM_PERCENT_EFFORT,
			PROJECT_TEAM_DEPARTMENT,
			PROJECT_TEAM_ORGANISATION,
			PROJECT_TEAM_COUNTRY,
			PROJECT_TEAM_CV,
			PROJECT_TEAM_TRACK,
			ORAGANIZATION_ID
		FROM MIGRATION_PROPOSAL_PERSONS
        where APPLICATION_ID in ('000435', '000409', '000372', '000337', '000336', '000334', '000327', '000290', '000220', '000212', '000186', '000178',
								 '000174', '000169', '000166', '000164', '000146', '000133', '000125', '000114', '000108', '000104', '000093', '000089',
								 '000072', '000067', '000064', '000031', '000023', '000022', '000008', '000002');
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_APPLICATION_ID,
		LS_PROJECT_TEAM_MEMBER_TYPE,
		LS_NT_LOGIN_ID,
		LS_PROJECT_TEAM_NAME,
		LS_PROJECT_TEAM_DESIGNATION,
		LS_SEQUENCE_PROJECT_TEAM,
		LS_PROJECT_TEAM_ROLE,
		LS_PROJECT_TEAM_PERCENT_EFFORT,
		LS_PROJECT_TEAM_DEPARTMENT,
		LS_PROJECT_TEAM_ORGANISATION,
		LS_PROJECT_TEAM_COUNTRY,
		LS_PROJECT_TEAM_CV,
		LS_PROJECT_TEAM_TRACK,
		LS_ORAGANIZATION_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG
		FROM MIGRATION_PROPOSAL
		WHERE UPPER(TRIM(APPLICATION_ID)) = UPPER(TRIM(LS_APPLICATION_ID));
		IF LI_FLAG = 0 THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER,CAN_CREATE_PROPOSAL
										   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON','APPLICATION_ID DOES NOT EXIST',LS_APPLICATION_ID,'PREVALIDATION',NOW(),'quickstart','N');
			COMMIT;
		END IF;
		IF LS_PROJECT_TEAM_MEMBER_TYPE = 'Non-SMU Employee' THEN
			SELECT COUNT(1) INTO LI_FLAG FROM ROLODEX
			WHERE UPPER(TRIM(FULL_NAME))  COLLATE utf8mb4_general_ci =  UPPER(TRIM(LS_PROJECT_TEAM_NAME));
			IF LI_FLAG = 0 THEN
					SELECT COUNT(1) INTO LI_COUNT
					FROM MIGRATION_MISSING_PERSONS
					WHERE
					EMPLOYEE_TYPE = 'ROLODEX'
					AND UPPER(TRIM(FULL_NAME)) = UPPER(TRIM(LS_PROJECT_TEAM_NAME));
					IF LI_COUNT = 0 THEN
						SELECT IFNULL(MAX(ID),0)+1 INTO LI_MISSING_ID FROM MIGRATION_MISSING_PERSONS;
						INSERT INTO MIGRATION_MISSING_PERSONS
						(
						ID,FILE_TYPE, APPLICATION_ID, EMPLOYEE_TYPE, USER_NAME, FULL_NAME,
						PROJECT_TEAM_DESIGNATION, PROJECT_TEAM_DEPARTMENT,
						PROJECT_TEAM_ORGANISATION, PROJECT_TEAM_COUNTRY,ORAGANIZATION_ID)
						VALUES(LI_MISSING_ID,'PROPOSAL',LS_APPLICATION_ID,'ROLODEX',NULL,TRIM(LS_PROJECT_TEAM_NAME),
						LS_PROJECT_TEAM_DESIGNATION,LS_PROJECT_TEAM_DEPARTMENT,LS_PROJECT_TEAM_ORGANISATION,LS_PROJECT_TEAM_COUNTRY,LS_ORAGANIZATION_ID);
						COMMIT;
					END IF;
			END IF;
		ELSEIF LS_PROJECT_TEAM_MEMBER_TYPE = 'SMU Employee' THEN
			SELECT COUNT(1) INTO LI_FLAG FROM PERSON
			WHERE TRIM(UPPER(USER_NAME)) = TRIM(UPPER(LS_NT_LOGIN_ID));
			IF LI_FLAG = 0 THEN
					SELECT COUNT(1) INTO LI_COUNT
					FROM MIGRATION_MISSING_PERSONS
					WHERE
					EMPLOYEE_TYPE = 'PERSON'
					AND UPPER(TRIM(USER_NAME)) = UPPER(TRIM(LS_NT_LOGIN_ID));
					IF LI_COUNT = 0 THEN
						SELECT IFNULL(MAX(ID),0)+1 INTO LI_MISSING_ID FROM MIGRATION_MISSING_PERSONS;
						INSERT INTO MIGRATION_MISSING_PERSONS
						(
						ID,FILE_TYPE, APPLICATION_ID, EMPLOYEE_TYPE, USER_NAME, FULL_NAME,
						PROJECT_TEAM_DESIGNATION, PROJECT_TEAM_DEPARTMENT,
						PROJECT_TEAM_ORGANISATION, PROJECT_TEAM_COUNTRY,ORAGANIZATION_ID)
						VALUES(LI_MISSING_ID,'PROPOSAL',LS_APPLICATION_ID,'PERSON',TRIM(LS_NT_LOGIN_ID),TRIM(LS_PROJECT_TEAM_NAME),
						LS_PROJECT_TEAM_DESIGNATION,LS_PROJECT_TEAM_DEPARTMENT,LS_PROJECT_TEAM_ORGANISATION,LS_PROJECT_TEAM_COUNTRY,LS_ORAGANIZATION_ID);
						COMMIT;
					END IF;
			END IF;
		END IF;
		IF LS_PROJECT_TEAM_ROLE IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM EPS_PROP_PERSON_ROLE
			WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_TEAM_ROLE));
			IF LI_FLAG = 0 THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER
										   )
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON','PROPOSAL PERSON ROLE NOT EXIST',LS_PROJECT_TEAM_ROLE,'PREVALIDATION',NOW(),'quickstart');
					COMMIT;
			END IF;
		ELSE
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
									VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER
								   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON','PROPOSAL PERSON ROLE IS NULL',LS_PROJECT_TEAM_ROLE,'PREVALIDATION',NOW(),'quickstart');
			COMMIT;
	   END IF;
	IF LS_PROJECT_TEAM_MEMBER_TYPE = 'SMU Employee' THEN
		IF LS_PROJECT_TEAM_DEPARTMENT IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG
			FROM UNIT
			WHERE UPPER(TRIM(UNIT_NAME)) = UPPER(TRIM(LS_PROJECT_TEAM_DEPARTMENT));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
										VALIDATION_TYPE,UPDATE_TIMESTAMP, UPDATE_USER
									   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON','UNIT DOES NOT EXIST',CONCAT('PERSON NAME:',IFNULL(LS_PROJECT_TEAM_NAME,''),'UNIT NAME:',LS_PROJECT_TEAM_DEPARTMENT),'PREVALIDATION',NOW(),'quickstart');
				COMMIT;
			END IF;
		ELSE
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
										VALIDATION_TYPE,UPDATE_TIMESTAMP, UPDATE_USER
									   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON','UNIT IS NULL',CONCAT('PERSON NAME:',IFNULL(LS_PROJECT_TEAM_NAME,''),'UNIT NAME:',IFNULL(LS_PROJECT_TEAM_DEPARTMENT,'')),'PREVALIDATION',NOW(),'quickstart');
				COMMIT;
	  END IF;
	END IF;
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
END;
END
$$
DELIMITER ;
