DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PROPOSAL_BUDGET_INTERNAL`(
av_id int
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID 			INT;
DECLARE LS_ERROR_MSG 					VARCHAR(1000);
DECLARE LS_APPLICATION_ID 				VARCHAR(50);
DECLARE LS_PROPOSED_BUDGET_TOTAL		VARCHAR(50);
DECLARE LS_PROPOSED_BUDGET_EOM 			VARCHAR(50);
DECLARE LS_PROPOSED_BUDGET_EQPT			VARCHAR(50);
DECLARE LS_PROPOSED_BUDGET_OOE			VARCHAR(50);
DECLARE LS_TOTAL_LINE_ITEM_COST			DECIMAL(13,2);
DECLARE LI_FLAG 						INT;
DECLARE LI_PROPOSAL_ID					INT(11);
DECLARE LI_BUDGET_HEADER_ID				INT(12);
DECLARE LS_START_DATE					DATETIME;
DECLARE LS_END_DATE						DATETIME;
DECLARE LI_BUDGET_PERIOD_ID				INT(12);
DECLARE	LI_BUDGET_DETAILS_ID			INT(12);
DECLARE LI_LINE_ITEM_NUMBER				INT;
	BEGIN
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'EXCEPTION','PROPOSAL_BUDGET',LS_ERROR_MSG,'CREATION',NOW(),'quickstart');
			COMMIT;
		END;
			BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT
			APPLICATION_ID,
			PROPOSED_BUDGET_TOTAL,
			PROPOSED_BUDGET_EOM,
			PROPOSED_BUDGET_EQPT,
			PROPOSED_BUDGET_OOE
		FROM MIGRATION_PROPOSAL_BUDGET_INTERNAL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_APPLICATION_ID,
		LS_PROPOSED_BUDGET_TOTAL,
		LS_PROPOSED_BUDGET_EOM,
		LS_PROPOSED_BUDGET_EQPT,
		LS_PROPOSED_BUDGET_OOE;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG
		FROM MIGRATION_PROPOSAL_INTERNAL
		WHERE UPPER(TRIM(APPLICATION_ID)) = UPPER(TRIM(LS_APPLICATION_ID));
		IF LI_FLAG = 0 THEN
			ITERATE INSERT_LOOP;
		END IF;
		SET LI_LINE_ITEM_NUMBER = 0;
		SELECT COUNT(1) INTO LI_FLAG FROM MIGRATION_PROPOSAL_INTERNAL
		WHERE APPLICATION_ID = LS_APPLICATION_ID;
		IF LI_FLAG > 0 THEN
			SELECT PROPOSAL_ID INTO LI_PROPOSAL_ID FROM MIGRATION_PROPOSAL_INTERNAL
			WHERE UPPER(TRIM(APPLICATION_ID)) = UPPER(TRIM(LS_APPLICATION_ID));
			SELECT COUNT(1) INTO LI_FLAG
			FROM EPS_PROPOSAL
			WHERE PROPOSAL_ID = LI_PROPOSAL_ID;
			IF LI_FLAG > 0 THEN
				SELECT START_DATE,END_DATE INTO LS_START_DATE,LS_END_DATE FROM EPS_PROPOSAL
				WHERE PROPOSAL_ID = LI_PROPOSAL_ID;
			END IF;
		END IF;
		SELECT IFNULL(MAX(BUDGET_HEADER_ID),0)+1 INTO LI_BUDGET_HEADER_ID FROM BUDGET_HEADER;
		INSERT INTO BUDGET_HEADER(
		BUDGET_HEADER_ID,
		BUDGET_STATUS_CODE,
		BUDGET_TYPE_CODE,
		CREATE_TIMESTAMP,
		CREATE_USER,
		CREATE_USER_NAME,
		END_DATE,
		IS_AUTO_CALC,
		ON_OFF_CAMPUS_FLAG,
		RATE_CLASS_CODE,
		RATE_TYPE_CODE,
		START_DATE,
		TOTAL_COST,
		TOTAL_DIRECT_COST,
		TOTAL_INDIRECT_COST,
		UPDATE_TIMESTAMP,
		UPDATE_USER,
		UPDATE_USER_NAME,
		VERSION_NUMBER,
		TOTAL_SUBCONTRACT_COST,
		PROPOSAL_ID,
		IS_FINAL_BUDGET,
		COST_SHARING_AMOUNT,
		IS_LATEST_VERSION,
		MODULAR_BUDGET_FLAG,
		SUBMIT_COST_SHARING_FLAG,
		TOTAL_COST_LIMIT,
		UNDERRECOVERY_AMOUNT,
		IS_APPROVED_BUDGET
		)
		VALUES
		(
		LI_BUDGET_HEADER_ID,
		3,
		1,
		NOW(),
		'quickstart',
		'quickstart',
		LS_END_DATE,
		'N',
		'N',
		'1',
		'1',
		LS_START_DATE,
		IFNULL(CAST(LS_PROPOSED_BUDGET_TOTAL AS DECIMAL(13,2)),0),
		IFNULL(CAST(LS_PROPOSED_BUDGET_TOTAL AS DECIMAL(13,2)),0),
		0,
		NOW(),
		'quickstart',
		'quickstart',
		1,
		0,
		LI_PROPOSAL_ID,
		'Y',
		0,
		'Y',
		'N',
		'N',
		0,
		0,
		'N'
		);
		COMMIT;
		SELECT IFNULL(MAX(BUDGET_PERIOD_ID),0)+1 INTO LI_BUDGET_PERIOD_ID FROM BUDGET_PERIOD;
		INSERT INTO BUDGET_PERIOD(
		BUDGET_PERIOD_ID,
		BUDGET_PERIOD,
		END_DATE,
		START_DATE,
		TOTAL_COST,
		TOTAL_DIRECT_COST,
		TOTAL_INDIRECT_COST,
		UPDATE_TIMESTAMP,
		UPDATE_USER,
		VERSION_NUMBER,
		BUDGET_HEADER_ID,
		SUBCONTRACT_COST,
		COST_SHARING_AMOUNT,
		TOTAL_COST_LIMIT,
		TOTAL_DIRECT_COST_LIMIT,
		UNDERRECOVERY_AMOUNT
		)
		VALUES(
		LI_BUDGET_PERIOD_ID,
		1,
		LS_END_DATE,
		LS_START_DATE,
		IFNULL(CAST(LS_PROPOSED_BUDGET_TOTAL AS DECIMAL(13,2)),0),
		IFNULL(CAST(LS_PROPOSED_BUDGET_TOTAL AS DECIMAL(13,2)),0),
		0,
		NOW(),
		'quickstart',
		1,
		LI_BUDGET_HEADER_ID,
		0,
		0,
		0,
		0,
		0
		);
		COMMIT;
		SET LS_APPLICATION_ID = NULL;
		SET LS_PROPOSED_BUDGET_TOTAL = NULL;
		SET LS_PROPOSED_BUDGET_EOM = NULL;
		SET LS_PROPOSED_BUDGET_EQPT = NULL;
		SET LS_PROPOSED_BUDGET_OOE = NULL;
		END LOOP;
		CLOSE CUR_SEL_DATA;
		UPDATE BUDGET_HEADER_ID_GENERATOR SET NEXT_VAL = (SELECT MAX(BUDGET_HEADER_ID)+1 FROM BUDGET_HEADER);
		UPDATE BUDGET_PERIOD_ID_GENERATOR SET NEXT_VAL = (SELECT MAX(BUDGET_PERIOD_ID)+1 FROM BUDGET_PERIOD);
		END;
		COMMIT;
	END;
END
$$
DELIMITER ;
