DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_AWARD_BUDGET_INTERNAL`(
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID 			INT;
DECLARE LS_ERROR_MSG 					VARCHAR(1000);
DECLARE LI_FLAG 						INT;
DECLARE LS_PROJECT_ID 					VARCHAR(50);
DECLARE LS_FUND_CENTRE					VARCHAR(50);
DECLARE LS_FUND_CODE					VARCHAR(50);
DECLARE LS_BUDGET_CATEGORY				VARCHAR(50);
DECLARE LS_BUDGET_LINE_ITEM				VARCHAR(50);
DECLARE LS_QUANTITY						VARCHAR(50);
DECLARE LS_IO_CODE						VARCHAR(50);
DECLARE LS_ORIGINAL_APPROVED_BUDGET		VARCHAR(50);
DECLARE LS_CURRENT_APPROVED_BUDGET		VARCHAR(50);
DECLARE LS_EXPENDITURE_TO_DATE			VARCHAR(50);
DECLARE LS_AMOUNT_REMAIN_BAL			VARCHAR(50);
DECLARE LS_UTILIZATION_RATE				VARCHAR(50);
DECLARE LS_BUDGET_TOTAL VARCHAR(50);
DECLARE LS_BUDGET_LINE_ITEM_TOTAL VARCHAR(50);
DECLARE LS_TOTAL_DIFF VARCHAR(50);
DECLARE LS_DETAIL varchar(2000);
DECLARE LS_BUDGET_DETAIL varchar(2000);
DECLARE LI_ID INT;
DECLARE LS_BUDGET_JUSTIFICATION VARCHAR(2000);
DECLARE LS_ERROR_FLAG VARCHAR(1);
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'EXCEPTION','PROJECT_BUDGET',LS_ERROR_MSG,'PRE_VALIDATION',NOW(),'quickstart');
			COMMIT;
		END;
		BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT ID,
			PROJECT_ID,
			FUND_CENTRE,
			FUND_CODE,
			BUDGET_CATEGORY,
			BUDGET_LINE_ITEM,
			QUANTITY,
			IO_CODE,
			ORIGINAL_APPROVED_BUDGET,
			CURRENT_APPROVED_BUDGET,
			EXPENDITURE_TO_DATE,
			AMOUNT_REMAIN_BAL,
			UTILIZATION_RATE,
			DETAIL,
			BUDGET_DETAIL
		FROM MIGRATION_AWARD_BUDGET_INTERNAL_00_17
		WHERE PROJECT_ID IN (SELECT PROJECT_ID FROM MIGRATION_AWARD_INTERNAL_00_17)
        and VALIDATION_STATUS is null;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
							LI_ID,
							LS_PROJECT_ID,
							LS_FUND_CENTRE,
							LS_FUND_CODE,
							LS_BUDGET_CATEGORY,
							LS_BUDGET_LINE_ITEM,
							LS_QUANTITY,
							LS_IO_CODE,
							LS_ORIGINAL_APPROVED_BUDGET,
							LS_CURRENT_APPROVED_BUDGET,
							LS_EXPENDITURE_TO_DATE,
							LS_AMOUNT_REMAIN_BAL,
							LS_UTILIZATION_RATE
							,LS_DETAIL
							, LS_BUDGET_DETAIL;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
			SET LS_ERROR_FLAG = 'N';
			SELECT COUNT(1) INTO LI_FLAG
			FROM MIGRATION_AWARD_INTERNAL_00_17
			WHERE UPPER(TRIM(PROJECT_ID)) = UPPER(TRIM(LS_PROJECT_ID));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','PROJECT_ID  DOES NOT EXISTS IN PROJECT FILE',LS_PROJECT_ID,'PRE_VALIDATION','N',NOW(),'quickstart');
				COMMIT;
				SET LS_ERROR_FLAG = 'Y';
			END IF;
			IF LS_BUDGET_LINE_ITEM IS NOT NULL THEN
				SELECT COUNT(1) INTO LI_FLAG FROM MIGRATION_COST_ELEMENT_MAPPING
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_BUDGET_LINE_ITEM));
				IF LI_FLAG = 0 THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
													VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','COST ELEMENT DOES NOT EXISTS',LS_BUDGET_LINE_ITEM,'PRE_VALIDATION','N',NOW(),'quickstart');
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
				END IF;
			ELSE
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
													VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','COST ELEMENT IS NULL',LS_BUDGET_LINE_ITEM,'PRE_VALIDATION','N',NOW(),'quickstart');
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
			END IF;
			IF LS_BUDGET_CATEGORY IS NOT NULL THEN
				SELECT COUNT(1) INTO LI_FLAG FROM BUDGET_CATEGORY
				WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_BUDGET_CATEGORY));
				IF LI_FLAG = 0 THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
													VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','BUDGET_CATEGORY DOES NOT EXISTS',LS_BUDGET_CATEGORY,'PRE_VALIDATION','N',NOW(),'quickstart');
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
				END IF;
			ELSE
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
													VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','BUDGET_CATEGORY IS NULL',LS_BUDGET_CATEGORY,'PRE_VALIDATION','N',NOW(),'quickstart');
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
			END IF;
			IF LS_BUDGET_CATEGORY IS NOT NULL AND LS_BUDGET_LINE_ITEM IS NOT NULL THEN
				SELECT COUNT(1) INTO LI_FLAG FROM MIGRATION_COST_ELEMENT_MAPPING
				WHERE BUDGET_CATEGORY_CODE = (SELECT BUDGET_CATEGORY_CODE FROM BUDGET_CATEGORY
				                              WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_BUDGET_CATEGORY))
											  )
				AND UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_BUDGET_LINE_ITEM));
				IF LI_FLAG = 0 THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
													VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','BUDGET_CATEGORY COST ELEMENT MAPPING DOES NOT EXISTS',CONCAT('Budget_Category:- ',ifnull(LS_BUDGET_CATEGORY,''),',Costelement:-',ifnull(LS_BUDGET_LINE_ITEM,'')),'PRE_VALIDATION','N',NOW(),'quickstart');
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
				END IF;
			END IF;
			SELECT CAST(ROUND(SUM(ORIGINAL_APPROVED_BUDGET),2) AS CHAR) INTO LS_BUDGET_LINE_ITEM_TOTAL FROM MIGRATION_AWARD_BUDGET_INTERNAL_00_17 WHERE PROJECT_ID = LS_PROJECT_ID;
			SELECT TOTAL_CASH INTO LS_BUDGET_TOTAL FROM MIGRATION_AWARD_INTERNAL_00_17 WHERE PROJECT_ID = LS_PROJECT_ID;
			IF  CAST(LS_BUDGET_LINE_ITEM_TOTAL AS UNSIGNED) > CAST(LS_BUDGET_TOTAL AS UNSIGNED) THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
													VALIDATION_TYPE,CAN_CREATE_BUDGET, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_BUDGET','BUDGET LINE ITEM COST EXCEEDS BUDGET TOTAL COST',CONCAT('BUDGET LINE ITEM COST : ',LS_BUDGET_LINE_ITEM_TOTAL,'\n BUDGET TOTAL COST : ',LS_BUDGET_TOTAL),'PRE_VALIDATION','N',NOW(),'quickstart');
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
			END IF;
			set LS_BUDGET_JUSTIFICATION = '';
			IF(LS_DETAIL is NULL or LS_DETAIL = '0' OR trim(LS_DETAIL) = '' ) then
				set LS_DETAIL = '';
			END IF;
			IF(LS_BUDGET_DETAIL is NULL or LS_BUDGET_DETAIL = '0' OR trim(LS_BUDGET_DETAIL) = '') then
				set LS_BUDGET_DETAIL = '';
			END IF;
			set LS_BUDGET_JUSTIFICATION = concat(LS_DETAIL,' : ' ,LS_BUDGET_DETAIL);
			IF  substring(LS_BUDGET_JUSTIFICATION, 1,1) = ':' then
            set LS_BUDGET_JUSTIFICATION = substring(LS_BUDGET_JUSTIFICATION, 2);
            END IF;
			Update migration_award_budget_internal_00_17 set BUDGET_JUSTIFICATION = trim(LS_BUDGET_JUSTIFICATION)
			where ID = LI_ID;
		set sql_safe_updates = 0;
		IF LS_ERROR_FLAG = 'Y' then
		UPDATE MIGRATION_AWARD_BUDGET_INTERNAL_00_17 set validation_status = 'ERROR' where ID = LI_ID;
		 UPDATE MIGRATION_AWARD_INTERNAL_00_17 set validation_status = 'ERROR' where PROJECT_ID = LS_PROJECT_ID;
		ELSE
		UPDATE MIGRATION_AWARD_BUDGET_INTERNAL_00_17 set validation_status = 'VALID' where ID = LI_ID;
		 UPDATE MIGRATION_AWARD_INTERNAL_00_17 set validation_status = 'VALID' where PROJECT_ID = LS_PROJECT_ID;
		END IF;
		END LOOP;
		CLOSE CUR_SEL_DATA;
END;
END
$$
DELIMITER ;
