DELIMITER $$
CREATE  PROCEDURE `MIGRATION_CUSTOM_DATA`(AV_TYPE int)
BEGIN
DECLARE LS_LEGACY_PROJECT_ID VARCHAR(100);
DECLARE LS_LEGACY_WBS_NUMBER VARCHAR(100);
DECLARE LI_COUNT INT;
DECLARE LS_FILE_TYPE VARCHAR(50);
DECLARE LI_AWARD_ID INT(22);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_HOME_UNIT VARCHAR(8);
DECLARE LS_PROJECT_ID VARCHAR(20);
DECLARE LS_TITLE VARCHAR(4000);
DECLARE LS_PROJECT_STATUS VARCHAR(200);
DECLARE LS_LEAD_UNIT VARCHAR(200);
DECLARE LS_CUST_SCHOOL_UNIVERSITY VARCHAR(200);
DECLARE LS_GRANTCALL_TYPE VARCHAR(200);
DECLARE LS_MODULE_TYPE VARCHAR(10);
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT(11);
DECLARE LI_COLUMN_ID INT(11);
DECLARE LI_COLUMN_VERSION_NUMBER INT(11);
DECLARE LI_CUSTOM_DATA_ID INT(11);
DECLARE LI_PROPOSAL_ID INT(12);
BEGIN
DECLARE LS_ERROR VARCHAR(2000);
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE MIGRATION_CUSTOM_DATA_CURSOR CURSOR FOR
SELECT PROJECT_ID,
TITLE,
PROJECT_STATUS,
LEAD_UNIT,
CUST_SCHOOL_UNIVERSITY,
GRANTCALL_TYPE,
MODULE_TYPE
FROM MIGRATION_CUSTOM_DATA;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
SELECT @full_error INTO LS_ERROR;
INSERT INTO MIGRATION_ERROR_LOG(LEGACY_PROJECT_ID,LEGACY_WBS_NUMBER,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
VALUES(LS_PROJECT_ID,LS_MODULE_TYPE,'Exception','CUSTOM_DATA',SUBSTR(LS_ERROR,1,999),'During Migration',LS_FILE_TYPE);
COMMIT;
END;
select CUSTOM_DATA_ELEMENTS_ID,COLUMN_ID,COLUMN_VERSION_NUMBER into LI_CUSTOM_DATA_ELEMENTS_ID,LI_COLUMN_ID,LI_COLUMN_VERSION_NUMBER
FROM CUSTOM_DATA_ELEMENTS
WHERE CUSTOM_ELEMENT_NAME ='School/University'
AND COLUMN_ID = (SELECT MAX(COLUMN_ID) FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'School/University');
OPEN MIGRATION_CUSTOM_DATA_CURSOR;
MIGRATION_CUSTOM_DATA_CURSOR_LOOP : LOOP
FETCH MIGRATION_CUSTOM_DATA_CURSOR INTO LS_PROJECT_ID,
LS_TITLE,
LS_PROJECT_STATUS,
LS_LEAD_UNIT,
LS_CUST_SCHOOL_UNIVERSITY,
LS_GRANTCALL_TYPE,
LS_MODULE_TYPE;
IF DONE1 THEN
LEAVE MIGRATION_CUSTOM_DATA_CURSOR_LOOP;
END IF;
SELECT COUNT(*) INTO LI_COUNT
FROM MIGRATION_ERROR_LOG
WHERE ERROR_TYPE = 'Validation'
AND LEGACY_PROJECT_ID = LS_PROJECT_ID;
IF LI_COUNT > 0 THEN
ITERATE MIGRATION_CUSTOM_DATA_CURSOR_LOOP;
END IF;
IF LS_MODULE_TYPE = 'AWARD' THEN
SELECT AWARD_ID INTO LI_AWARD_ID
FROM AWARD
WHERE AWARD_NUMBER = LS_PROJECT_ID
AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1 INTO LI_CUSTOM_DATA_ID
FROM CUSTOM_DATA;
INSERT INTO CUSTOM_DATA(CUSTOM_DATA_ID,
CUSTOM_DATA_ELEMENTS_ID,
MODULE_ITEM_CODE,
MODULE_SUB_ITEM_CODE,
MODULE_ITEM_KEY,
MODULE_SUB_ITEM_KEY,
VALUE,
UPDATE_TIMESTAMP,
UPDATE_USER,
COLUMN_ID,
COLUMN_VERSION_NUMBER)
VALUES(LI_CUSTOM_DATA_ID,
LI_CUSTOM_DATA_ELEMENTS_ID,
1,
0,
LI_AWARD_ID,
0,
LS_CUST_SCHOOL_UNIVERSITY,
UTC_TIMESTAMP(),
'quickstart',
LI_COLUMN_ID,
LI_COLUMN_VERSION_NUMBER
);
COMMIT;
ELSE
SELECT PROPOSAL_ID INTO LI_PROPOSAL_ID
FROM EPS_PROPOSAL
WHERE APPLICATION_ID = LS_PROJECT_ID;
SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1 INTO LI_CUSTOM_DATA_ID
FROM CUSTOM_DATA;
INSERT INTO CUSTOM_DATA(CUSTOM_DATA_ID,
CUSTOM_DATA_ELEMENTS_ID,
MODULE_ITEM_CODE,
MODULE_SUB_ITEM_CODE,
MODULE_ITEM_KEY,
MODULE_SUB_ITEM_KEY,
VALUE,
UPDATE_TIMESTAMP,
UPDATE_USER,
COLUMN_ID,
COLUMN_VERSION_NUMBER)
VALUES(LI_CUSTOM_DATA_ID,
LI_CUSTOM_DATA_ELEMENTS_ID,
3,
0,
LI_PROPOSAL_ID,
0,
LS_CUST_SCHOOL_UNIVERSITY,
UTC_TIMESTAMP(),
'quickstart',
LI_COLUMN_ID,
LI_COLUMN_VERSION_NUMBER
);
COMMIT;
END IF;
END LOOP;
CLOSE MIGRATION_CUSTOM_DATA_CURSOR;
END;
UPDATE CUSTOM_DATA_ID_GENERATOR SET NEXT_VAL = (SELECT IFNULL(MAX(CUSTOM_DATA_ID),0)+1 FROM CUSTOM_DATA);
SELECT 'Migration completed' AS RESULT;
END
$$
DELIMITER ;
