DELIMITER $$
CREATE  PROCEDURE `MIGRATION_GENERATE_IP_INTERNAL`(av_id int
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_ERROR_MSG 		VARCHAR(1000);
DECLARE LI_AWARD_ID			INT;
DECLARE LS_AWARD_NUMBER		VARCHAR(12);
DECLARE LS_PROJECT_ID		VARCHAR(50);
DECLARE LI_DEV_PROPOSAL_ID	INT;
DECLARE LS_RETURN			VARCHAR(40);
declare LI_SEQUENCE_NUMBER int;
	BEGIN
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'EXCEPTION','INSTITUTE_PROPOSAL',LS_ERROR_MSG,'CREATION',NOW(),'quickstart');
		COMMIT;
	END;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT MASTER_AWARD_ID,AWARD_NUMBER,PROJECT_ID FROM MIGRATION_AWARD_INTERNAL_00_17
		WHERE PROJECT_ID IN(SELECT TRIM(APPLICATION_ID) FROM MIGRATION_PROPOSAL_INTERNAL_00_17);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LI_AWARD_ID,
		LS_AWARD_NUMBER,
		LS_PROJECT_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SELECT PROPOSAL_ID INTO LI_DEV_PROPOSAL_ID FROM EPS_PROPOSAL
		WHERE APPLICATION_ID = LS_PROJECT_ID;
		SET LS_RETURN = MIGRATION_FN_FEED_INST_PROPOSAL_INTERNAL(LI_DEV_PROPOSAL_ID,LS_PROJECT_ID,'quickstart',LI_AWARD_ID);
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
END;
END
$$
DELIMITER ;
