DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_AWARD_PERSONS_PI_INTERNAL`(
)
BEGIN
DECLARE LS_PROJECT_ID 				VARCHAR(50);
DECLARE LI_FLAG							INT;
DECLARE LI_SEQ_ERROR_LOG_ID 			INT;
DECLARE LS_ERROR_MSG 					VARCHAR(1000);
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'EXCEPTION','PROJECT_PERSON',LS_ERROR_MSG,'PRE_VALIDATION',NOW(),'quickstart');
		COMMIT;
	END;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT T1.PROJECT_ID FROM MIGRATION_AWARD_INTERNAL_00_17 T1
		LEFT OUTER JOIN MIGRATION_AWARD_PERSONS_INTERNAL_00_17 T2 ON TRIM(T1.PROJECT_ID) = TRIM(T2.PROJECT_ID)
												   AND UPPER(TRIM(T2.PROJECT_ROLE)) = UPPER('Principal Investigator')
		WHERE T2.PROJECT_ID IS NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_PROJECT_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,
										VALUE,VALIDATION_TYPE, CAN_CREATE_AWARD, UPDATE_TIMESTAMP, UPDATE_USER
									   )
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_PERSON','PROJECT DOES NOT HAVE PI PERSON',LS_PROJECT_ID,'PREVALIDATION','N',NOW(),'quickstart');
		COMMIT;
		 set sql_safe_updates = 0;
		update MIGRATION_AWARD_INTERNAL_00_17 set VALIDATION_STATUS = 'ERROR' where PROJECT_ID = LS_PROJECT_ID;
		update MIGRATION_AWARD_PERSONS_INTERNAL_00_17 set VALIDATION_STATUS = 'ERROR' where PROJECT_ID = LS_PROJECT_ID;
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
END;
END
$$
DELIMITER ;
