DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_PROPOSAL_PERSONS_PI`(
)
BEGIN
DECLARE LS_APPLICATION_ID 				VARCHAR(50);
DECLARE LI_FLAG							INT;
DECLARE LS_ERROR_MSG					VARCHAR(1000);
DECLARE LI_SEQ_ERROR_LOG_ID				INT;
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'EXCEPTION','PROPOSAL_PERSON',LS_ERROR_MSG,'PRE_VALIDATION',NOW(),'quickstart');
		COMMIT;
	END;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT T1.APPLICATION_ID FROM MIGRATION_PROPOSAL T1
		LEFT OUTER JOIN MIGRATION_PROPOSAL_PERSONS T2 ON T1.APPLICATION_ID = T2.APPLICATION_ID
													  AND UPPER(TRIM(T2.PROJECT_TEAM_ROLE)) = UPPER('Principal Investigator')
		WHERE  T2.APPLICATION_ID IS NULL and APPLICATION_ID in ('000334','000372');
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_APPLICATION_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
										VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
									   )
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL_PERSON','PROPOSAL DOES NOT HAVE PI PERSON',LS_APPLICATION_ID,'PREVALIDATION','N',NOW(),'quickstart');
		COMMIT;
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
END;
END
$$
DELIMITER ;
