DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_ATTACHMENTS_INTERNAL`()
BEGIN
DECLARE LS_ERROR VARCHAR(2000);
DECLARE LS_LEGACY_PROJECT_ID VARCHAR(100);
DECLARE LS_PROJECT_ID   VARCHAR(200);
DECLARE LS_PROJECT_TYPE VARCHAR(10);
DECLARE LS_PROJECT_ATTACHMENT_TYPE      VARCHAR(50);
DECLARE LS_PROJECT_FILE_NAME    VARCHAR(500);
DECLARE LS_PROJECT_MIME_TYPE    VARCHAR(100);
DECLARE LS_PROJECT_FILE_DATA    LONGBLOB;
DECLARE LI_PROJECT_ATTACHMENT_ID DECIMAL(12,0);
DECLARE LS_PROJECT_NUMBER VARCHAR(20);
DECLARE LI_PROJECT_COUNT INT(10);
DECLARE LI_ATT_TYPE_COUNT INT(11);
DECLARE LS_TYPE_CODE VARCHAR(3);
DECLARE UNIQUE_ID VARCHAR(36);
DECLARE LI_DOCUMENT_ID  INT(11);
DECLARE LI_VERSION_AWARD_ID int;
DECLARE LI_MASTER_AWARD_ID int;
DECLARE LI_ATTACHMENT_ID int(11);
DECLARE LS_ERROR_FLAG VARCHAR(1);
begin
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE AWARD_CURSOR CURSOR FOR
SELECT ATTACHMENT_ID, PROJECT_ID,PROJECT_TYPE,ATTACHMENT_TYPE,FILE_NAME,MIME_TYPE,DATA
FROM migration_attachments_internal_00_17
where validation_status is NULL
and( PROJECT_ID not like '18%' or PROJECT_ID not like '19%' or PROJECT_ID not like '20%');
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
        GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
         @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
        SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
        SELECT @full_error INTO LS_ERROR;
        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
        VALUES(LS_PROJECT_ID,'Exception','ATTACHMENT MIGRATION',LS_ERROR,'MIGRATION',LS_PROJECT_TYPE);
END;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN AWARD_CURSOR;
AWARD_CURSOR_LOOP : LOOP
        FETCH AWARD_CURSOR INTO
        LI_ATTACHMENT_ID,
		LS_PROJECT_ID,
		LS_PROJECT_TYPE,
		LS_PROJECT_ATTACHMENT_TYPE,
		LS_PROJECT_FILE_NAME,
		LS_PROJECT_MIME_TYPE,
		LS_PROJECT_FILE_DATA;
                IF DONE1 THEN
                        LEAVE AWARD_CURSOR_LOOP;
                END IF;
		set LS_ERROR_FLAG = 'N';
		IF upper(trim(LS_PROJECT_TYPE)) = 'AWARD'  THEN -- or upper(trim(LS_PROJECT_TYPE)) = '' THEN
                IF (IFNULL(TRIM(LS_PROJECT_FILE_DATA),'') = '') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','ATTACHMENT IS EMPTY','BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						set LS_ERROR_FLAG = 'Y';
                END IF;
                if (IFNULL(TRIM(LS_PROJECT_ID),'') ='') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','PROJECT ID IN NULL','BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        set LS_ERROR_FLAG = 'Y';
			    else
				 set  LS_PROJECT_ID = trim(substring(LS_PROJECT_ID,1,16));
                SELECT  COUNT(*) INTO LI_PROJECT_COUNT
                FROM MIGRATION_AWARD_INTERNAL_00_17 WHERE PROJECT_ID = trim(LS_PROJECT_ID);
                IF LI_PROJECT_COUNT = 0 THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','PROJECT ID DOESN''T EXIST','BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        set LS_ERROR_FLAG = 'Y';
                END IF;
				end if;
                SELECT COUNT(*) INTO LI_ATT_TYPE_COUNT
                FROM AWARD_ATTACHMENT_TYPE
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ATTACHMENT_TYPE));
                IF LI_ATT_TYPE_COUNT = 0 THEN
						INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,ERROR_VALUE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','AWARD ATTACHMENT TYPE DOESN''T EXIST',TRIM(LS_PROJECT_ATTACHMENT_TYPE),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						set LS_ERROR_FLAG = 'Y';
                END IF;
				IF LS_ERROR_FLAG = 'Y' THEN
					UPDATE migration_attachments_internal_00_17 set validation_status = 'ERROR'
					where ATTACHMENT_ID = LI_ATTACHMENT_ID;
				ELSE
					UPDATE migration_attachments_internal_00_17 set validation_status = 'VALID'
					where ATTACHMENT_ID = LI_ATTACHMENT_ID;
				END IF;
		elseif upper(trim(LS_PROJECT_TYPE)) = 'PROPOSAL' THEN -- or upper(trim(LS_PROJECT_TYPE)) = '' THEN
			set LS_ERROR_FLAG = 'N';
                IF (IFNULL(TRIM(LS_PROJECT_FILE_DATA),'') = '') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('ATTACHMENT IS EMPTY'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						set LS_ERROR_FLAG = 'Y';
                END IF;
                if (IFNULL(TRIM(LS_PROJECT_ID),'') ='') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','PROPOSAL ID IN NULL','BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        set LS_ERROR_FLAG = 'Y';
                else
				SET  LS_PROJECT_ID = TRIM(SUBSTRING(LS_PROJECT_ID,1,16));
                SELECT  COUNT(*) INTO LI_PROJECT_COUNT
                FROM MIGRATION_PROPOSAL_INTERNAL_00_17 WHERE APPLICATION_ID = trim(LS_PROJECT_ID);
                IF LI_PROJECT_COUNT = 0 THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','PROPOSAL ID DOESN''T EXIST','BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        set LS_ERROR_FLAG = 'Y';
				end if;
                END IF;
                SELECT COUNT(*) INTO LI_ATT_TYPE_COUNT
                FROM EPS_PROPOSAL_ATTACH_TYPE
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ATTACHMENT_TYPE));
                IF LI_ATT_TYPE_COUNT = 0 THEN
						INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,ERROR_VALUE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION','PROPOSAL ATTACHMENT TYPE DOESN''T EXIST',TRIM(LS_PROJECT_ATTACHMENT_TYPE),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						set LS_ERROR_FLAG = 'Y';
                END IF;
				IF LS_ERROR_FLAG = 'Y' THEN
					UPDATE migration_attachments_internal_00_17 set validation_status = 'ERROR'
					where ATTACHMENT_ID = LI_ATTACHMENT_ID;
				ELSE
					UPDATE migration_attachments_internal_00_17 set validation_status = 'VALID'
					where ATTACHMENT_ID = LI_ATTACHMENT_ID;
					END IF;
	end if;
COMMIT;
END LOOP;
END;
END
$$
DELIMITER ;
