DELIMITER $$
CREATE  PROCEDURE `MIGRATION_ATTACHMENTS`(AV_TYPE INT)
BEGIN
DECLARE LS_ERROR VARCHAR(2000);
DECLARE LS_LEGACY_PROJECT_ID VARCHAR(100);
DECLARE LS_PROJECT_ID   VARCHAR(200);
DECLARE LS_PROJECT_TYPE VARCHAR(10);
DECLARE LS_PROJECT_ATTACHMENT_TYPE      VARCHAR(50);
DECLARE LS_PROJECT_FILE_NAME    VARCHAR(500);
DECLARE LS_PROJECT_MIME_TYPE    VARCHAR(100);
DECLARE LS_PROJECT_FILE_DATA    LONGBLOB;
DECLARE LI_PROJECT_ATTACHMENT_ID DECIMAL(12,0);
DECLARE LS_PROJECT_NUMBER VARCHAR(20);
DECLARE LI_PROJECT_COUNT INT(10);
DECLARE LI_ATT_TYPE_COUNT INT(11);
DECLARE LS_TYPE_CODE VARCHAR(3);
DECLARE UNIQUE_ID VARCHAR(36);
DECLARE LI_DOCUMENT_ID  INT(11);
begin
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE AWARD_CURSOR CURSOR FOR
SELECT PROJECT_ID,PROJECT_TYPE,ATTACHMENT_TYPE,FILE_NAME,MIME_TYPE,DATA
FROM MIGRATION_ATTACHMENTS;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
        GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
         @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
        SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
        SELECT @full_error INTO LS_ERROR;
        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
        VALUES(LS_PROJECT_ID,'Exception','ATTACHMENT MIGRATION',LS_ERROR,'BEFORE MIGRATION',LS_PROJECT_TYPE);
END;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
OPEN AWARD_CURSOR;
AWARD_CURSOR_LOOP : LOOP
        FETCH AWARD_CURSOR INTO
		LS_PROJECT_ID,
		LS_PROJECT_TYPE,
		LS_PROJECT_ATTACHMENT_TYPE,
		LS_PROJECT_FILE_NAME,
		LS_PROJECT_MIME_TYPE,
		LS_PROJECT_FILE_DATA;
                IF DONE1 THEN
                        LEAVE AWARD_CURSOR_LOOP;
                END IF;
		IF upper(trim(LS_PROJECT_TYPE)) = 'AWARD' THEN
                IF (IFNULL(TRIM(LS_PROJECT_FILE_DATA),'') = '') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('ATTACHMENT IS EMPTY'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						ITERATE AWARD_CURSOR_LOOP;
                END IF;
                if (IFNULL(TRIM(LS_PROJECT_ID),'') ='') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('PROJECT ID IN NULL'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        ITERATE AWARD_CURSOR_LOOP;
			    else
				set  LS_PROJECT_ID = trim(substring(LS_PROJECT_ID,1,15));
                SELECT  COUNT(*) INTO LI_PROJECT_COUNT
                FROM MIGRATION_AWARD_INTERNAL WHERE PROJECT_ID = LS_PROJECT_ID;
                IF LI_PROJECT_COUNT = 0 THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('PROJECT ID DOESN''T EXIST'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        ITERATE AWARD_CURSOR_LOOP;
				else
						select  AWARD_ID, AWARD_NUMBER into LS_PROJECT_ID,LS_PROJECT_NUMBER
						from MIGRATION_AWARD_INTERNAL WHERE PROJECT_ID = LS_PROJECT_ID;
                END IF;
				end if;
                SELECT COUNT(*) INTO LI_ATT_TYPE_COUNT
                FROM AWARD_ATTACHMENT_TYPE
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ATTACHMENT_TYPE));
                IF LI_ATT_TYPE_COUNT > 0 THEN
                        SELECT TYPE_CODE INTO LS_TYPE_CODE
                        FROM AWARD_ATTACHMENT_TYPE
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ATTACHMENT_TYPE));
                ELSE
						INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('AWARD ATTACHMENT TYPE "',TRIM(LS_PROJECT_ATTACHMENT_TYPE),'" DOESN''T EXIST'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						ITERATE AWARD_CURSOR_LOOP;
                END IF;
                SELECT NEXT_VAL INTO LI_PROJECT_ATTACHMENT_ID FROM AWARD_ATTACHMENT_ID_GENERATOR;
                SELECT UUID() INTO UNIQUE_ID FROM DUAL;
                INSERT INTO AWARD_ATTACHMENT (
                AWARD_ATTACHMENT_ID,
                AWARD_ID,
                AWARD_NUMBER,
                SEQUENCE_NUMBER,
                TYPE_CODE,
                DESCRIPTION,
                DOCUMENT_STATUS_CODE,
                UPDATE_TIMESTAMP,
                UPDATE_USER,
                FILE_DATA_ID,
                FILE_NAME,
                MIME_TYPE,
                NARRATIVE_STATUS_CODE,
                VERSION_NUMBER)
                values (
                LI_PROJECT_ATTACHMENT_ID,
                LS_PROJECT_ID,
                LS_PROJECT_NUMBER,
                1,
                LS_TYPE_CODE,
                NULL,
                1,
                NOW(),
                'quickstart',
                UNIQUE_ID,
                LS_PROJECT_FILE_NAME,
                LS_PROJECT_MIME_TYPE,
                'C',
                1
                );
                INSERT INTO FILE_DATA VALUES(UNIQUE_ID,LS_PROJECT_FILE_DATA);
                COMMIT;
				UPDATE AWARD_ATTACHMENT_ID_GENERATOR SET NEXT_VAL = LI_PROJECT_ATTACHMENT_ID+1;
				COMMIT;
BEGIN
DECLARE DONE2 INT DEFAULT FALSE;
DECLARE PROJECT_DOC_ID_CURSOR CURSOR FOR
SELECT DISTINCT AWARD_ID
FROM AWARD_ATTACHMENT
where DOCUMENT_ID = null;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
SET LI_DOCUMENT_ID = 0;
OPEN PROJECT_DOC_ID_CURSOR;
PROJECT_DOC_ID_CURSOR_LOOP : LOOP
        FETCH PROJECT_DOC_ID_CURSOR INTO  LS_PROJECT_ID;
                IF DONE2 THEN
                        LEAVE PROJECT_DOC_ID_CURSOR_LOOP;
                END IF;
                SET LI_DOCUMENT_ID = 0;
                BEGIN
                DECLARE DONE3 INT DEFAULT FALSE;
                        DECLARE PROJECT_DOC_ID_CURSOR1 CURSOR FOR
                        SELECT AWARD_ATTACHMENT_ID,AWARD_ID
                        FROM AWARD_ATTACHMENT
                        WHERE AWARD_ID = LS_PROJECT_ID;
                        DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
                        OPEN PROJECT_DOC_ID_CURSOR1;
                        PROJECT_DOC_ID_CURSOR_LOOP1 : LOOP
                                        FETCH PROJECT_DOC_ID_CURSOR1 INTO
										LI_PROJECT_ATTACHMENT_ID,
										LS_PROJECT_ID ;
                                        IF DONE3 THEN
                                                LEAVE PROJECT_DOC_ID_CURSOR_LOOP1;
                                        END IF;
                                        UPDATE AWARD_ATTACHMENT SET DOCUMENT_ID = LI_DOCUMENT_ID+1 WHERE AWARD_ATTACHMENT_ID = LI_PROJECT_ATTACHMENT_ID;
                        END LOOP;
                        CLOSE PROJECT_DOC_ID_CURSOR1;
                END;
END LOOP;
CLOSE PROJECT_DOC_ID_CURSOR;
COMMIT;
END;
	elseif upper(trim(LS_PROJECT_TYPE)) = 'PROPOSAL' THEN
                IF (IFNULL(TRIM(LS_PROJECT_FILE_DATA),'') = '') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('ATTACHMENT IS EMPTY'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						ITERATE AWARD_CURSOR_LOOP;
                END IF;
                if (IFNULL(TRIM(LS_PROJECT_ID),'') ='') THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('PROPOSAL ID IN NULL'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        ITERATE AWARD_CURSOR_LOOP;
                else
				set  LS_PROJECT_ID = substring(LS_PROJECT_ID,1,15);
                SELECT  COUNT(*) INTO LI_PROJECT_COUNT
                FROM MIGRATION_PROPOSAL_INTERNAL WHERE APPLICATION_ID = LS_PROJECT_ID;
                IF LI_PROJECT_COUNT = 0 THEN
                        INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('PROPOSAL ID DOESN''T EXIST'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
                        ITERATE AWARD_CURSOR_LOOP;
				end if;
				select PROPOSAL_ID into LS_PROJECT_ID from MIGRATION_PROPOSAL_INTERNAL
				where APPLICATION_ID = LS_PROJECT_ID;
                END IF;
                SELECT COUNT(*) INTO LI_ATT_TYPE_COUNT
                FROM eps_proposal_attach_type
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ATTACHMENT_TYPE));
                IF LI_ATT_TYPE_COUNT > 0 THEN
                        SELECT ATTACHMNT_TYPE_CODE INTO LS_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ATTACHMENT_TYPE));
                ELSE
						INSERT INTO MIGRATION_ATTACHMENT_ERROR_LOG(LEGACY_PROJECT_ID,ERROR_TYPE,FILE_NAME,ERROR_MESSAGE,VALIDATION_TYPE,FILE_TYPE)
                        VALUES(LS_PROJECT_ID,'VALIDATION','ATTACHMENT MIGRATION',CONCAT('PROPOSAL ATTACHMENT TYPE "',TRIM(LS_PROJECT_ATTACHMENT_TYPE),'" DOESN''T EXIST'),'BEFORE MIGRATION',LS_PROJECT_TYPE);
                        COMMIT;
						ITERATE AWARD_CURSOR_LOOP;
                END IF;
                SELECT NEXT_VAL INTO LI_PROJECT_ATTACHMENT_ID FROM eps_prop_attach_id_generator;
                SELECT UUID() INTO UNIQUE_ID FROM DUAL;
                INSERT INTO eps_proposal_attachments (
                ATTACHMENT_ID,
                PROPOSAL_ID,
                ATTACHMNT_TYPE_CODE,
                DESCRIPTION,
                DOCUMENT_STATUS_CODE,
                UPDATE_TIMESTAMP,
                UPDATE_USER,
                FILE_DATA_ID,
                FILE_NAME,
                MIME_TYPE,
                NARRATIVE_STATUS_CODE,
                VERSION_NUMBER)
                values (
                LI_PROJECT_ATTACHMENT_ID,
                LS_PROJECT_ID,
                LS_TYPE_CODE,
                NULL,
                1,
                NOW(),
                'quickstart',
                UNIQUE_ID,
                LS_PROJECT_FILE_NAME,
                LS_PROJECT_MIME_TYPE,
                'C',
                1
                );
                INSERT INTO FILE_DATA VALUES(UNIQUE_ID,LS_PROJECT_FILE_DATA);
                COMMIT;
				UPDATE eps_prop_attach_id_generator SET NEXT_VAL = LI_PROJECT_ATTACHMENT_ID+1;
				COMMIT;
	end if;
BEGIN
DECLARE DONE4 INT DEFAULT FALSE;
DECLARE PROPOSAL_DOC_ID_CURSOR CURSOR FOR
SELECT DISTINCT PROPOSAL_ID
FROM eps_proposal_attachments
where DOCUMENT_ID = null;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
SET LI_DOCUMENT_ID = 0;
OPEN PROPOSAL_DOC_ID_CURSOR;
PROPOSAL_DOC_ID_CURSOR_LOOP : LOOP
        FETCH PROPOSAL_DOC_ID_CURSOR INTO  LS_PROJECT_ID;
                IF DONE4 THEN
                        LEAVE PROPOSAL_DOC_ID_CURSOR_LOOP;
                END IF;
                SET LI_DOCUMENT_ID = 0;
                BEGIN
                DECLARE DONE3 INT DEFAULT FALSE;
                        DECLARE PROPOSAL_DOC_ID_CURSOR1 CURSOR FOR
                        SELECT PROPOSAL_ATTACHMENT_ID,PROPOSAL_ID
                        FROM eps_proposal_attachments
                        WHERE PROPOSAL_ID = LS_PROJECT_ID;
                        DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
                        OPEN PROPOSAL_DOC_ID_CURSOR1;
                        PROPOSAL_DOC_ID_CURSOR_LOOP1 : LOOP
                                        FETCH PROPOSAL_DOC_ID_CURSOR1 INTO
										LI_PROJECT_ATTACHMENT_ID,
										LS_PROJECT_ID ;
                                        IF DONE3 THEN
                                                LEAVE PROPOSAL_DOC_ID_CURSOR_LOOP1;
                                        END IF;
                                        UPDATE eps_proposal_attachments SET DOCUMENT_ID = LI_DOCUMENT_ID+1 WHERE PROPOSAL_ATTACHMENT_ID = LI_PROJECT_ATTACHMENT_ID;
                        END LOOP;
                        CLOSE PROPOSAL_DOC_ID_CURSOR1;
                END;
END LOOP;
CLOSE PROPOSAL_DOC_ID_CURSOR;
COMMIT;
END;
		END LOOP;
		CLOSE AWARD_CURSOR;
END;
END
$$
DELIMITER ;
