DELIMITER $$
CREATE  PROCEDURE `MIGRATION_AWARD_ATTACHMENT_BASE64`(
AV_START int,
AV_END int
)
BEGIN
	DECLARE LI_SEQ_ERROR_LOG_ID INT;
	DECLARE LS_ERROR_MSG		VARCHAR(1000);
	DECLARE	LI_ATTACHMENT_ID int;
	DECLARE LS_FILE_DATA_ID varchar(500);
	BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LI_ATTACHMENT_ID,'EXCEPTION','AWARD',LS_ERROR_MSG,'ATTACHMENT_CONVERSION',NOW(),'quickstart');
		COMMIT;
	END;
		BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT AWARD_ATTACHMENT_ID,FILE_DATA_ID FROM AWARD_ATTACHMENT WHERE AWARD_ATTACHMENT_ID BETWEEN AV_START AND AV_END;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LI_ATTACHMENT_ID,
		LS_FILE_DATA_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		UPDATE FILE_DATA SET DATA = FROM_BASE64(DATA)
		WHERE ID = LS_FILE_DATA_ID;
		END LOOP;
		CLOSE CUR_SEL_DATA;
		END;
	END;
END
$$
DELIMITER ;
