DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PROPOSAL_INTERNAL_POSTVAL_MATRIX`(AV_TYPE INT)
BEGIN
DECLARE LI_SOURCE_COUNT          int;
DECLARE LI_DESTINATION_COUNT     int;
select count(distinct(NAME_OF_GRANT_CALL)) into LI_SOURCE_COUNT from MIGRATION_PROPOSAL_INTERNAL;
select count(distinct(NAME_OF_GRANT_CALL)) into LI_DESTINATION_COUNT from  migration_proposal_internal;
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('GRANT_CALL','TOTAL NUMBER OF DISTINCT GRANT CALLS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_PROPOSAL_INTERNAL ;
select count(*) into LI_DESTINATION_COUNT from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal);
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL','TOTAL NUMBER OF DISTINCT PROPOSALS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select COUNT(*) INTO LI_SOURCE_COUNT from MIGRATION_PROPOSAL_INTERNAL where PROPOSAL_STATUS = 'Awarded';
select count(*) into LI_DESTINATION_COUNT from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal)
and status_code in (SELECT STATUS_CODE FROM EPS_PROPOSAL_STATUS
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER('Awarded')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL','TOTAL NUMBER OF DISTINCT PROPOSALS WITH PROPOSAL_STATUS ''Awarded''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select COUNT(*) INTO LI_SOURCE_COUNT from MIGRATION_PROPOSAL_INTERNAL where PROPOSAL_STATUS = 'Unsuccessful';
select count(*) into LI_DESTINATION_COUNT from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal)
and status_code in (SELECT STATUS_CODE FROM EPS_PROPOSAL_STATUS
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER('Unsuccessful')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL','TOTAL NUMBER OF DISTINCT PROPOSALS WITH PROPOSAL_STATUS ''Unsuccessful''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_PROPOSAL_PERSONS_INTERNAL ;
select count(*) into LI_DESTINATION_COUNT from EPS_PROPOSAL_PERSONS
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_PERSON','TOTAL NUMBER OF DISTINCT PROPOSAL PERSONS ',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select COUNT(*) INTO LI_SOURCE_COUNT from MIGRATION_PROPOSAL_PERSONS_INTERNAL where UPPER(TRIM(PROJECT_TEAM_ROLE)) = UPPER('Principal Investigator');
select count(*) into LI_DESTINATION_COUNT  from EPS_PROPOSAL_PERSONS
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and PI_FLAG = 'Y';
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_PERSON','TOTAL NUMBER OF DISTINCT PROPOSAL PI''s ',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL'));
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'Application Form';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Application Form')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''Application Form''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'Quotations';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Quotations')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''Quotations''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'Others';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Others')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''Others''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'CV';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('CV')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''CV''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'Research Proposal';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Research Proposal')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''Research Proposal''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'References';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('References')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''References''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('PROPOSAL')) and ATTACHMENT_TYPE = 'Admin Documents(Confidential)';
select count(*) into LI_DESTINATION_COUNT from eps_proposal_attachments
where proposal_id in (select proposal_id from EPS_PROPOSAL where APPLICATION_ID in (select APPLICATION_ID from migration_proposal_internal))
and ATTACHMNT_TYPE_CODE in (SELECT ATTACHMNT_TYPE_CODE
                        FROM eps_proposal_attach_type
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Admin Documents(Confidential)')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROPOSAL ATTACHMENTS WITH TYPE ''Admin Documents(Confidential)''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select round(sum(PROPOSED_BUDGET_TOTAL)) into LI_SOURCE_COUNT  from MIGRATION_proposal_budget_INTERNAL;
select round(sum(TOTAL_COST)) into LI_DESTINATION_COUNT from budget_header where PROPOSAL_ID in (select PROPOSAL_ID from migration_proposal_internal);
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROPOSAL_BUDGET','TOTAL PROPOSAL BUDGET COST',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_AWARD_INTERNAL ;
select count(*) into LI_DESTINATION_COUNT from AWARD where award_id in (select award_id from migration_award_internal);
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT','TOTAL NUMBER OF DISTINCT PROJECTS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_AWARD_INTERNAL where PROJECT_STATUS = 'Live';
select count(*) into LI_DESTINATION_COUNT from AWARD where award_id in (select award_id from migration_award_internal)
and STATUS_CODE in (SELECT STATUS_CODE
				FROM AWARD_STATUS
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Live')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT','TOTAL NUMBER OF DISTINCT PROJECTS WITH AWARD_STATUS ''Live''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_AWARD_INTERNAL where PROJECT_STATUS = 'Terminated by SMU';
select count(*) into LI_DESTINATION_COUNT from AWARD where award_id in (select award_id from migration_award_internal)
and STATUS_CODE in (SELECT STATUS_CODE
				FROM AWARD_STATUS
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Terminated by SMU')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT','TOTAL NUMBER OF DISTINCT PROJECTS WITH AWARD_STATUS ''Terminated by SMU''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_AWARD_INTERNAL where PROJECT_STATUS = 'Closed';
select count(*) into LI_DESTINATION_COUNT from AWARD where award_id in (select award_id from migration_award_internal)
and STATUS_CODE in (SELECT STATUS_CODE
				FROM AWARD_STATUS
				WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Closed')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT','TOTAL NUMBER OF DISTINCT PROJECTS WITH AWARD_STATUS ''Closed''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_DESTINATION_COUNT = LI_SOURCE_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT COUNT(*) INTO LI_SOURCE_COUNT
FROM  MIGRATION_AWARD_PERSONS_INTERNAL ;
select count(*) into LI_DESTINATION_COUNT from AWARD_PERSONS
where award_id in (select award_id  from migration_award_internal);
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_PERSON','TOTAL NUMBER OF DISTINCT PROJECT PERSONS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED') ,NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_AWARD_persons_INTERNAL where MEMBER_TYPE = 'SMU Employee';
select count(*) into LI_DESTINATION_COUNT from AWARD_PERSONS
where award_id in (select award_id  from migration_award_internal)
and PERSON_ID is not null;
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_PERSON','TOTAL NUMBER OF DISTINCT EMPLOYEES IN PROJECTS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED') ,NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_AWARD_persons_INTERNAL where MEMBER_TYPE = 'Non-SMU Employee';
select count(*) into LI_DESTINATION_COUNT from AWARD_PERSONS
where award_id in (select award_id  from migration_award_internal)
and ROLODEX_ID is not null;
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_PERSON','TOTAL NUMBER OF DISTINCT NON_EMPLOYEES IN PROJECTS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED') ,NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT
from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('AWARD'));
select count(*) into LI_DESTINATION_COUNT from AWARD_ATTACHMENT
where award_id in (select award_id  from migration_award_internal);
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROJECT ATTACHMENTS',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT  from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('Award')) and ATTACHMENT_TYPE = 'Letter of Award / Agreement';
select count(*) into LI_DESTINATION_COUNT from AWARD_ATTACHMENT
where award_id in (select award_id  from migration_award_internal)
and type_code in (SELECT TYPE_CODE
                        FROM AWARD_ATTACHMENT_TYPE
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Letter of Award / Agreement')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROJECT ATTACHMENTS WITH TYPE ''Letter of Award / Agreement''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT  from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('Award')) and ATTACHMENT_TYPE = 'Variation Requests';
select count(*) into LI_DESTINATION_COUNT from AWARD_ATTACHMENT
where award_id in (select award_id  from migration_award_internal)
and type_code in (SELECT TYPE_CODE
                        FROM AWARD_ATTACHMENT_TYPE
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Variation Requests')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROJECT ATTACHMENTS WITH TYPE ''Variation Requests''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT  from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('Award')) and ATTACHMENT_TYPE = 'Finance';
select count(*) into LI_DESTINATION_COUNT from AWARD_ATTACHMENT
where award_id in (select award_id  from migration_award_internal)
and type_code in (SELECT TYPE_CODE
                        FROM AWARD_ATTACHMENT_TYPE
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Finance')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROJECT ATTACHMENTS WITH TYPE ''Finance''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT  from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('Award')) and ATTACHMENT_TYPE = 'Admin Documents' ;
select count(*) into LI_DESTINATION_COUNT from AWARD_ATTACHMENT
where award_id in (select award_id  from migration_award_internal)
and type_code in (SELECT TYPE_CODE
                        FROM AWARD_ATTACHMENT_TYPE
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Admin Documents')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROJECT ATTACHMENTS WITH TYPE ''Admin Documents''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT from MIGRATION_ATTACHMENTS
where upper(trim(PROJECT_TYPE)) = upper(trim('Award')) and ATTACHMENT_TYPE = 'RGS Attachments';
select count(*) into LI_DESTINATION_COUNT from AWARD_ATTACHMENT
where award_id in (select award_id  from migration_award_internal)
and type_code in (SELECT TYPE_CODE
                        FROM AWARD_ATTACHMENT_TYPE
                        WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('RGS Attachments')));
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_ATTACHMENT','TOTAL NUMBER OF DISTINCT PROJECT ATTACHMENTS WITH TYPE ''RGS Attachments''',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select round(sum(ORIGINAL_APPROVED_BUDGET))  into LI_SOURCE_COUNT from MIGRATION_AWARD_budget_INTERNAL;
select round(sum(TOTAL_COST))  into LI_DESTINATION_COUNT from award_budget_header where award_id in (select award_id from migration_award_internal);
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_BUDGET','TOTAL AWARD BUDGET COST',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
select count(*) into LI_SOURCE_COUNT  from PROPOSAL where grant_header_id in (select grant_header_id from migration_proposal_internal);
select count(*) into LI_DESTINATION_COUNT  from  migration_award_internal;
INSERT INTO MIGRATION_TEST_MATRIX(MODULE,TEST_CASE,CRITERIA,SOURCE_COUNT,DESTINATION_COUNT,STATUS,FILE_TYPE)
VALUES('PROJECT_BUDGET','TOTAL NUMBER OF INSTITUTE PROPOSALS GENERATED',NULL,LI_SOURCE_COUNT,LI_DESTINATION_COUNT,IF(LI_SOURCE_COUNT = LI_DESTINATION_COUNT,'SUCCESS','FAILED'),NULL);
COMMIT;
SELECT 1;
END
$$
DELIMITER ;
