DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_AWARD_PERSONS_INTERNAL`(
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID 			INT;
DECLARE LS_ERROR_MSG 					VARCHAR(1000);
DECLARE LS_PROJECT_ID					VARCHAR(50);
DECLARE LS_MEMBER_TYPE					VARCHAR(50);
DECLARE LS_NTLOGIN_ID					VARCHAR(50);
DECLARE LS_NAME							VARCHAR(100);
DECLARE LS_DESIGNATION					VARCHAR(500);
DECLARE LS_SEQUENCE_IN_PROJECT_TEAM		VARCHAR(10);
DECLARE LS_DEPARTMENT					VARCHAR(500);
DECLARE LS_ORGANISATION					VARCHAR(500);
DECLARE LS_COUNTRY_OF_ORGANISATION		VARCHAR(500);
DECLARE LS_PROJECT_ROLE 				VARCHAR(50);
DECLARE LS_PERCENTAGE_OF_EFFORT			VARCHAR(50);
DECLARE LI_FLAG							INT;
DECLARE LI_COUNT							INT;
DECLARE LI_ROLODEX							INT;
DECLARE LI_PERSON							INT;
DECLARE LI_ROLE						INT;
DECLARE LI_DEPT							INT;
DECLARE LI_MISSING INT;
DECLARE LI_MISSING_ID 					INT;
DECLARE LS_ORAGANIZATION_ID				VARCHAR(10);
DECLARE LS_ERROR_FLAG VARCHAR(1);
DECLARE LI_ID INT;
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'EXCEPTION','PROJECT_PERSON',LS_ERROR_MSG,'PRE_VALIDATION',NOW(),'quickstart');
		COMMIT;
	END;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT ID,
			PROJECT_ID,
			MEMBER_TYPE,
			NTLOGIN_ID,
			NAME,
			DESIGNATION,
			SEQUENCE_IN_PROJECT_TEAM,
			DEPARTMENT,
			ORGANISATION,
			COUNTRY_OF_ORGANISATION,
			PROJECT_ROLE,
			PERCENTAGE_OF_EFFORT,
			ORAGANIZATION_ID
		FROM MIGRATION_AWARD_PERSONS_INTERNAL_00_17  where VALIDATION_STATUS is null
		and PROJECT_ID in (select PROJECT_ID from migration_award_internal_00_17 where VALIDATION_STATUS = 'VALID');
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO LI_ID,
							LS_PROJECT_ID,
							LS_MEMBER_TYPE,
							LS_NTLOGIN_ID,
							LS_NAME,
							LS_DESIGNATION,
							LS_SEQUENCE_IN_PROJECT_TEAM,
							LS_DEPARTMENT,
							LS_ORGANISATION,
							LS_COUNTRY_OF_ORGANISATION,
							LS_PROJECT_ROLE,
							LS_PERCENTAGE_OF_EFFORT,
							LS_ORAGANIZATION_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SET LS_ERROR_FLAG = 'N';
		SELECT COUNT(1) INTO LI_COUNT FROM MIGRATION_AWARD_INTERNAL_00_17
					where PROJECT_ID = 	LS_PROJECT_ID;
		IF LI_COUNT = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_PERSON','PROJECT ID DOES NOT EXIST',LS_PROJECT_ROLE,'PREVALIDATION',NOW(),'quickstart');
				COMMIT;
				UPDATE MIGRATION_PROPOSAL_INTERNAL_00_17 set validation_status = 'ERROR' where ID = LI_ID;
				ITERATE INSERT_LOOP;
		END IF;
		IF LS_MEMBER_TYPE = 'Non-SMU Employee' THEN
			SELECT COUNT(1) INTO LI_ROLODEX FROM ROLODEX
			WHERE UPPER(TRIM(FULL_NAME)) COLLATE utf8mb4_general_ci = UPPER(TRIM(LS_NAME));
			IF LI_ROLODEX = 0 THEN
					SELECT COUNT(1) INTO LI_MISSING
					FROM MIGRATION_MISSING_PERSONS
					WHERE EMPLOYEE_TYPE = 'ROLODEX'
					AND UPPER(TRIM(FULL_NAME)) COLLATE utf8mb4_general_ci = UPPER(TRIM(LS_NAME));
					IF LI_MISSING = 0 THEN
						SELECT IFNULL(MAX(ID),0)+1 INTO LI_MISSING_ID FROM MIGRATION_MISSING_PERSONS;
						INSERT INTO MIGRATION_MISSING_PERSONS
						(
						ID,ROLODEX_ID,FILE_TYPE, APPLICATION_ID, EMPLOYEE_TYPE, USER_NAME, FULL_NAME, PROJECT_TEAM_DESIGNATION, PROJECT_ROLE, PROJECT_TEAM_DEPARTMENT,PROJECT_TEAM_ORGANISATION, PROJECT_TEAM_COUNTRY,ORAGANIZATION_ID)
						VALUES(LI_MISSING_ID,IFNULL((select max(mmp.ROLODEX_ID)+1 from MIGRATION_MISSING_PERSONS mmp), (SELECT IFNULL(MAX(ROLODEX_ID),0)+1 FROM ROLODEX)),'PROPOSAL',LS_APPLICATION_ID,'ROLODEX',NULL,TRIM(LS_PROJECT_TEAM_NAME), LS_PROJECT_TEAM_DESIGNATION, LS_PROJECT_TEAM_ROLE, LS_PROJECT_TEAM_DEPARTMENT,LS_PROJECT_TEAM_ORGANISATION,LS_PROJECT_TEAM_COUNTRY,LS_ORAGANIZATION_ID);
						COMMIT;
						SET LS_ERROR_FLAG = 'Y';
					END IF;
			END IF;
		ELSEIF LS_MEMBER_TYPE = 'SMU Employee' THEN
			SELECT COUNT(1) INTO LI_PERSON FROM PERSON
			WHERE TRIM(UPPER(USER_NAME)) = TRIM(UPPER(LS_NTLOGIN_ID));
			IF LI_PERSON = 0 THEN
				SELECT COUNT(1) INTO LI_MISSING
				FROM MIGRATION_MISSING_PERSONS
				WHERE EMPLOYEE_TYPE = 'PERSON'
				AND USER_NAME = TRIM(LS_NTLOGIN_ID);
				IF LI_MISSING = 0 THEN
					SELECT IFNULL(MAX(ID),0)+1 INTO LI_MISSING_ID FROM MIGRATION_MISSING_PERSONS;
					INSERT INTO MIGRATION_MISSING_PERSONS
					(
					ID,FILE_TYPE, APPLICATION_ID, EMPLOYEE_TYPE, USER_NAME, FULL_NAME, PROJECT_TEAM_DESIGNATION, PROJECT_ROLE, PROJECT_TEAM_DEPARTMENT, PROJECT_TEAM_ORGANISATION, PROJECT_TEAM_COUNTRY,ORAGANIZATION_ID)
					VALUES(LI_MISSING_ID,'PROJECT',LS_PROJECT_ID,'PERSON',TRIM(LS_NTLOGIN_ID),TRIM(LS_NAME), LS_DESIGNATION,LS_PROJECT_ROLE, LS_DEPARTMENT,LS_ORGANISATION,LS_COUNTRY_OF_ORGANISATION,LS_ORAGANIZATION_ID);
					COMMIT;
					SET LS_ERROR_FLAG = 'Y';
				END IF;
			END IF;
		END IF;
	IF LS_PROJECT_ROLE IS NOT NULL THEN
		SELECT COUNT(1) INTO LI_ROLE FROM EPS_PROP_PERSON_ROLE
		WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROJECT_ROLE));
		IF LI_ROLE = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_PERSON','PROJECT PERSON ROLE DOES NOT EXIST',LS_PROJECT_ROLE,'PREVALIDATION',NOW(),'quickstart');
				SET LS_ERROR_FLAG = 'Y';
				COMMIT;
		END IF;
	ELSE
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER
								   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_PERSON','PROJECT PERSON ROLE IS NULL',LS_PROJECT_ROLE,'PREVALIDATION',NOW(),'quickstart');
			SET LS_ERROR_FLAG = 'Y';
			COMMIT;
	END IF;
	IF LS_MEMBER_TYPE = 'SMU Employee' THEN
		IF LS_DEPARTMENT IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_DEPT
			FROM UNIT
			WHERE UPPER(TRIM(UNIT_NAME)) = UPPER(TRIM(LS_DEPARTMENT));
			IF LI_DEPT = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_PERSON','UNIT DOES NOT EXIST',CONCAT('PERSON NAME:',IFNULL(LS_NAME,''),' UNIT NAME:',LS_DEPARTMENT),'PREVALIDATION',NOW(),'quickstart');
				SET LS_ERROR_FLAG = 'Y';
				COMMIT;
			END IF;
		ELSE
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_PROJECT_ID,'PROJECT_PERSON','UNIT IS NULL',CONCAT('PERSON NAME:',IFNULL(LS_NAME,''),' UNIT NAME:',IFNULL(LS_DEPARTMENT,'')),'PREVALIDATION',NOW(),'quickstart');
				SET LS_ERROR_FLAG = 'Y';
				COMMIT;
		END IF;
	END IF;
		set sql_safe_updates = 0;
		IF LS_ERROR_FLAG = 'Y' then
			UPDATE MIGRATION_AWARD_PERSONS_INTERNAL_00_17 set validation_status = 'ERROR' where ID = LI_ID;
			UPDATE MIGRATION_award_INTERNAL_00_17 set validation_status = 'ERROR' where PROJECT_ID = LS_PROJECT_ID;
		ELSE
			UPDATE MIGRATION_AWARD_PERSONS_INTERNAL_00_17 set validation_status = 'VALID' where  ID = LI_ID;
			UPDATE MIGRATION_award_INTERNAL_00_17 set validation_status = 'VALID' where PROJECT_ID = LS_PROJECT_ID;
		END IF;
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
		UPDATE MIGRATION_MISSING_PERSONS T1
		INNER JOIN ORGANIZATION T2 ON TRIM(UPPER(T1.PROJECT_TEAM_ORGANISATION))= TRIM(UPPER(T2.ORGANIZATION_NAME))
		SET T1.ORAGANIZATION_ID = T2.ORGANIZATION_ID
		WHERE T1.APPLICATION_ID IN (SELECT APPLICATION_ID FROM MIGRATION_PROPOSAL_INTERNAL_00_17 );
END;
END
$$
DELIMITER ;
