DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PREVAL_EXT_PROPOSAL`(
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_ERROR_MSG 		VARCHAR(1000);
DECLARE LS_SUBMISSION_DATE VARCHAR(20);
DECLARE LS_INTERNAL_DEADLINE_DATE VARCHAR(20);
DECLARE LS_PROPOSAL_STATUS VARCHAR(200);
DECLARE LS_APPLICATION_ID VARCHAR(255);
DECLARE LS_EXTERNAL_FUNDING_AGENCY_ID VARCHAR(50);
DECLARE LS_TITLE VARCHAR(500);
DECLARE LS_ACTIVITY_TYPE VARCHAR(50);
DECLARE LS_DISCIPLINE_CLUSTER VARCHAR(200);
DECLARE LS_PROPOSAL_LEAD_UNIT VARCHAR(500);
DECLARE LS_PROPOSED_START_DATE VARCHAR(20);
DECLARE LS_PROPOSED_END_DATE VARCHAR(20);
DECLARE LS_PROJECT_DURATION VARCHAR(255);
DECLARE LS_KEYWORDS_OF_RESEARCH longtext;
DECLARE LS_GRANT_CALL_ID int(10);
DECLARE LS_TYPE_OF_GRANT VARCHAR(200);
DECLARE LS_NAME_OF_GRANT_CALL VARCHAR(1000);
DECLARE LS_NAME_OF_FUNDING_AGENCY VARCHAR(500);
DECLARE LS_NAME_OF_FUNDING_SCHEME VARCHAR(500);
DECLARE LS_TYPE_OF_FUNDING_AGENCY VARCHAR(500);
DECLARE LS_GRANT_CALL_THEME LONGTEXT;
DECLARE LS_GRANT_CALL_CLOSING_DATE VARCHAR(20);
DECLARE LS_INTERNAL_SUBMISSION_DATE VARCHAR(20);
DECLARE LS_RESEARCH_AREA VARCHAR(500);
DECLARE LS_RESEARCH_SUB_AREA VARCHAR(500);
DECLARE LS_SOCIETAL_CHALLENGE_AREA VARCHAR(500);
DECLARE LS_SOCIETAL_CHALLENGE_SUB_AREA VARCHAR(500);
DECLARE LS_RESEARCH_AREA_DESC LONGTEXT;
DECLARE LS_MULTI_DISCIPLINARY_DESC LONGTEXT;
DECLARE LS_ABSTRACT_DESC LONGTEXT;
DECLARE LS_STRATEGY_FOR_EXTERNAL_FUNDING VARCHAR(3000);
DECLARE LS_DETAILS_RESEARCH_PROPOSAL VARCHAR(500);
DECLARE LS_CONFIDENTIALITY VARCHAR(500);
DECLARE LS_CONFIDENTIALITY_REMARKS VARCHAR(500);
DECLARE LS_FULL_NAME VARCHAR(100);
DECLARE LS_SPONSOR_TYPE VARCHAR(200);
DECLARE LS_SPONSOR VARCHAR(200);
DECLARE LS_START_DATE VARCHAR(20);
DECLARE LS_END_DATE VARCHAR(20);
DECLARE LS_AMOUNT VARCHAR(20);
DECLARE LS_FUNDING_STATUS VARCHAR(200);
DECLARE LS_ETHICS_CONSIDERATION VARCHAR(1000);
DECLARE LS_PROPOSAL_ID INT(11);
DECLARE LI_FLAG INT;
BEGIN
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
		INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID,ERROR_TYPE, FILE_NAME, ERROR_MESSAGE, VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'EXCEPTION','PROPOSAL',LS_ERROR_MSG,'PRE_VALIDATION',NOW(),'quickstart');
		COMMIT;
	END;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT
		SUBMISSION_DATE,
		INTERNAL_DEADLINE_DATE,
		PROPOSAL_STATUS,
		APPLICATION_ID,
		EXTERNAL_FUNDING_AGENCY_ID,
		TITLE,
		ACTIVITY_TYPE,
		DISCIPLINE_CLUSTER,
		PROPOSAL_LEAD_UNIT,
		PROPOSED_START_DATE,
		PROPOSED_END_DATE,
		PROJECT_DURATION,
		KEYWORDS_OF_RESEARCH,
		GRANT_CALL_ID,
		TYPE_OF_GRANT,
		NAME_OF_GRANT_CALL,
		NAME_OF_FUNDING_AGENCY,
		NAME_OF_FUNDING_SCHEME,
		TYPE_OF_FUNDING_AGENCY,
		GRANT_CALL_THEME,
		GRANT_CALL_CLOSING_DATE,
		INTERNAL_SUBMISSION_DATE,
		RESEARCH_AREA,
		RESEARCH_SUB_AREA,
		SOCIETAL_CHALLENGE_AREA,
		SOCIETAL_CHALLENGE_SUB_AREA,
		RESEARCH_AREA_DESC,
		MULTI_DISCIPLINARY_DESC,
		ABSTRACT_DESC,
		STRATEGY_FOR_EXTERNAL_FUNDING,
		DETAILS_RESEARCH_PROPOSAL,
		CONFIDENTIALITY,
		CONFIDENTIALITY_REMARKS,
		FULL_NAME,
		SPONSOR_TYPE,
		SPONSOR_CODE,
		START_DATE,
		END_DATE,
		AMOUNT,
		FUNDING_STATUS,
		ETHICS_CONSIDERATION,
		PROPOSAL_ID
		FROM MIGRATION_EXT_PROPOSAL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_SUBMISSION_DATE,
		LS_INTERNAL_DEADLINE_DATE,
		LS_PROPOSAL_STATUS,
		LS_APPLICATION_ID,
		LS_EXTERNAL_FUNDING_AGENCY_ID,
		LS_TITLE,
		LS_ACTIVITY_TYPE,
		LS_DISCIPLINE_CLUSTER,
		LS_PROPOSAL_LEAD_UNIT,
		LS_PROPOSED_START_DATE,
		LS_PROPOSED_END_DATE,
		LS_PROJECT_DURATION,
		LS_KEYWORDS_OF_RESEARCH,
		LS_GRANT_CALL_ID,
		LS_TYPE_OF_GRANT,
		LS_NAME_OF_GRANT_CALL,
		LS_NAME_OF_FUNDING_AGENCY,
		LS_NAME_OF_FUNDING_SCHEME,
		LS_TYPE_OF_FUNDING_AGENCY,
		LS_GRANT_CALL_THEME,
		LS_GRANT_CALL_CLOSING_DATE,
		LS_INTERNAL_SUBMISSION_DATE,
		LS_RESEARCH_AREA,
		LS_RESEARCH_SUB_AREA,
		LS_SOCIETAL_CHALLENGE_AREA,
		LS_SOCIETAL_CHALLENGE_SUB_AREA,
		LS_RESEARCH_AREA_DESC,
		LS_MULTI_DISCIPLINARY_DESC,
		LS_ABSTRACT_DESC,
		LS_STRATEGY_FOR_EXTERNAL_FUNDING,
		LS_DETAILS_RESEARCH_PROPOSAL,
		LS_CONFIDENTIALITY,
		LS_CONFIDENTIALITY_REMARKS,
		LS_FULL_NAME,
		LS_SPONSOR_TYPE,
		LS_SPONSOR,
		LS_START_DATE,
		LS_END_DATE,
		LS_AMOUNT,
		LS_FUNDING_STATUS,
		LS_ETHICS_CONSIDERATION,
		LS_PROPOSAL_ID;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		IF LS_NAME_OF_FUNDING_SCHEME IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG
			FROM FUNDING_SOURCE_TYPE WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_NAME_OF_FUNDING_SCHEME));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME,ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'GRANT_CALL','GRANT CALL FUNDING SCHEME DOES NOT EXIST',LS_NAME_OF_FUNDING_SCHEME,'PREVALIDATION',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_NAME_OF_GRANT_CALL IS NULL OR LS_NAME_OF_GRANT_CALL = '' THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME,ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL,CAN_CREATE_GRANTCALL, UPDATE_TIMESTAMP, UPDATE_USER
										   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'GRANT_CALL','GRANT CALL TITLE IS NULL',NULL,'PREVALIDATION','N','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG FROM GRANT_CALL_TYPE
		WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_TYPE_OF_GRANT));
		IF LI_FLAG = 0 THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME,ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL,CAN_CREATE_GRANTCALL, UPDATE_TIMESTAMP, UPDATE_USER
										   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'GRANT_CALL','GRANT CALL TYPE DOES NOT EXIST',LS_TYPE_OF_GRANT,'PREVALIDATION','N','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG FROM SPONSOR
		WHERE TRIM(UPPER(SPONSOR_NAME)) = TRIM(UPPER(LS_NAME_OF_FUNDING_AGENCY));
		IF LI_FLAG = 0 THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME,ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL,CAN_CREATE_GRANTCALL, UPDATE_TIMESTAMP, UPDATE_USER
										   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'GRANT_CALL','GRANT CALL SPONSOR DOES NOT EXIST',LS_NAME_OF_FUNDING_AGENCY,'PREVALIDATION','N','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG
		FROM SPONSOR_TYPE
		WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_TYPE_OF_FUNDING_AGENCY));
		IF LI_FLAG = 0 THEN
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME,ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, UPDATE_TIMESTAMP, UPDATE_USER
										   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'GRANT_CALL','GRANT CALL SPONSOR TYPE NOT EXIST',LS_TYPE_OF_FUNDING_AGENCY,'PREVALIDATION',NOW(),'quickstart');
			COMMIT;
		END IF;
	IF LS_ACTIVITY_TYPE IS NOT NULL THEN
		SELECT COUNT(1) INTO LI_FLAG
		FROM ACTIVITY_TYPE
		WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_ACTIVITY_TYPE));
		IF LI_FLAG = 0 THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','PROPOSAL CATEGORY DOES NOT EXIST',LS_ACTIVITY_TYPE,'PREVALIDATION','N',NOW(),'quickstart');
			COMMIT;
		END IF;
	END IF;
		IF LS_PROPOSAL_STATUS IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG
			FROM EPS_PROPOSAL_STATUS
			WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_PROPOSAL_STATUS));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','PROPOSAL STATUS DOES NOT EXIST',LS_PROPOSAL_STATUS,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		ELSE
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','PROPOSAL STATUS ID IS NULL',LS_PROPOSAL_STATUS,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
		END IF;
		IF LS_TITLE IS NULL OR LS_TITLE = '' THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
										   )
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','PROPOSAL TITLE IS NULL',NULL,'PREVALIDATION','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		IF LS_PROPOSAL_LEAD_UNIT IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG
			FROM UNIT
			WHERE UPPER(TRIM(UNIT_NAME)) = UPPER(TRIM(LS_PROPOSAL_LEAD_UNIT));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','LEAD UNIT DOES NOT EXIST',LS_PROPOSAL_LEAD_UNIT,'PREVALIDATION','N',NOW(),'quickstart');
				COMMIT;
			END IF;
		ELSE
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','UNIT IS NULL',LS_PROPOSAL_LEAD_UNIT,'PREVALIDATION','N',NOW(),'quickstart');
				COMMIT;
		END IF;
		IF ( IFNULL(TRIM(LS_PROPOSED_START_DATE),'')  = '' OR STR_TO_DATE(LS_PROPOSED_START_DATE,'%d/%m/%Y') IS NULL ) THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL',CONCAT('Proposed Start date can''t be NULL or Improper format'),LS_PROPOSED_START_DATE,'PREVALIDATION','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		IF ( IFNULL(TRIM(LS_PROPOSED_END_DATE),'') = '' OR STR_TO_DATE(LS_PROPOSED_END_DATE,'%d/%m/%Y') IS NULL ) THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL',CONCAT('Proposed End date can''t be NULL or Improper format'),LS_PROPOSED_END_DATE,'PREVALIDATION','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		IF (  STR_TO_DATE(LS_PROPOSED_START_DATE,'%d/%m/%Y') IS NOT NULL AND TRIM(LS_PROPOSED_START_DATE) <> ''
				      AND STR_TO_DATE(LS_PROPOSED_END_DATE,'%d/%m/%Y') IS NOT NULL AND TRIM(LS_PROPOSED_END_DATE) <> ''
					  AND STR_TO_DATE(LS_PROPOSED_START_DATE,'%d/%m/%Y') > STR_TO_DATE(LS_PROPOSED_END_DATE,'%d/%m/%Y') )THEN
			SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
			INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
											VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL',CONCAT('Proposed Start date "',TRIM(LS_PROPOSED_START_DATE),'" should come before Proposed end date "',TRIM(LS_PROPOSED_END_DATE),'"'),CONCAT(LS_PROPOSED_START_DATE,',',LS_PROPOSED_END_DATE),'PREVALIDATION','N',NOW(),'quickstart');
			COMMIT;
		END IF;
		IF LS_DISCIPLINE_CLUSTER IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM EPS_PROP_DISCIPLINE_CLUSTER
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_DISCIPLINE_CLUSTER));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','DISCIPLINE CLUSTER DOES NOT EXIST',LS_DISCIPLINE_CLUSTER,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_RESEARCH_AREA IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM RESEARCH_AREAS
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_RESEARCH_AREA));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','RESEARCH AREA DOES NOT EXIST',LS_RESEARCH_AREA,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_RESEARCH_SUB_AREA IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM RESEARCH_AREAS
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_RESEARCH_SUB_AREA));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','RESEARCH SUBAREA DOES NOT EXIST',LS_RESEARCH_SUB_AREA,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_SOCIETAL_CHALLENGE_AREA IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM SOCIETAL_CHALLENGE_AREA
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_SOCIETAL_CHALLENGE_AREA));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','SOCIETAL CHALLENGE AREA DOES NOT EXIST',LS_SOCIETAL_CHALLENGE_AREA,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_SOCIETAL_CHALLENGE_SUB_AREA IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM SOCIETAL_CHALLENGE_SUBAREA
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_SOCIETAL_CHALLENGE_SUB_AREA));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','SOCIETAL CHALLENGE SUBAREA DOES NOT EXIST',LS_SOCIETAL_CHALLENGE_SUB_AREA,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_SPONSOR IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM SPONSOR
			WHERE TRIM(UPPER(SPONSOR_NAME)) = TRIM(UPPER(LS_SPONSOR));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','SPONSOR DOES NOT EXIST(DECLARATION OF OTHER FUNDING SUPPORT)',LS_SPONSOR,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_FUNDING_STATUS IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM PROPOSAL_FUNDING_STATUS
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_FUNDING_STATUS));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','FUNDING STATUS DOES NOT EXIST(Declaration of other funding support - Status)',LS_FUNDING_STATUS,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_SPONSOR_TYPE IS NOT NULL THEN
			SELECT COUNT(1) INTO LI_FLAG FROM SPONSOR_TYPE
			WHERE TRIM(UPPER(DESCRIPTION)) = TRIM(UPPER(LS_SPONSOR_TYPE));
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER
											   )
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','SPONSOR TYPE DOES NOT EXIST(Declaration of other funding support - Type of Funding Agency)',LS_SPONSOR_TYPE,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_SUBMISSION_DATE IS NOT NULL THEN
			IF ( IFNULL(TRIM(LS_SUBMISSION_DATE),'') = '' OR STR_TO_DATE(LS_SUBMISSION_DATE,'%d/%m/%Y') IS NULL ) THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL',CONCAT(' SUBMISSION_DATE IS NULL OR IMPROPER FORMAT'),LS_SUBMISSION_DATE,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_INTERNAL_DEADLINE_DATE IS NOT NULL THEN
			IF ( IFNULL(TRIM(LS_INTERNAL_DEADLINE_DATE),'') = '' OR STR_TO_DATE(LS_INTERNAL_DEADLINE_DATE,'%d/%m/%Y') IS NULL ) THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL',CONCAT('INTERNAL_DEADLINE_DATE IS NULL OR IMPROPER FORMAT'),LS_INTERNAL_DEADLINE_DATE,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_INTERNAL_SUBMISSION_DATE IS NOT NULL THEN
			IF ( IFNULL(TRIM(LS_INTERNAL_SUBMISSION_DATE),'') = '' OR STR_TO_DATE(LS_INTERNAL_SUBMISSION_DATE,'%d/%m/%Y') IS NULL ) THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'GRANT_CALL',CONCAT('INTERNAL_SUBMISSION_DATE IS NULL OR IMPROPER FORMAT'),LS_INTERNAL_SUBMISSION_DATE,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_START_DATE IS NOT NULL THEN
			IF ( IFNULL(TRIM(LS_START_DATE),'') = '' OR STR_TO_DATE(LS_START_DATE,'%d/%m/%Y') IS NULL ) THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','START DATE IS IMPROPER FORMAT(Declaration of other funding support - Start Date)',LS_START_DATE,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		IF LS_END_DATE IS NOT NULL THEN
			IF ( IFNULL(TRIM(LS_END_DATE),'') = '' OR STR_TO_DATE(LS_END_DATE,'%d/%m/%Y') IS NULL ) THEN
				SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
				INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID, LEGACY_PROJECT_ID, FILE_NAME, ERROR_MESSAGE,VALUE,
												VALIDATION_TYPE, CAN_CREATE_PROPOSAL, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES(LI_SEQ_ERROR_LOG_ID,LS_APPLICATION_ID,'PROPOSAL','END DATE IS IMPROPER FORMAT(Declaration of other funding support - End Date)',LS_END_DATE,'PREVALIDATION','Y',NOW(),'quickstart');
				COMMIT;
			END IF;
		END IF;
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
END;
END
$$
DELIMITER ;
