DELIMITER $$
CREATE  PROCEDURE `smu_publication_refresh`()
BEGIN
DECLARE LS_PUBLICATION_ID 		INT(12);
DECLARE LS_EDITION 				VARCHAR(1000);
DECLARE LS_ISSN 				VARCHAR(1000);
DECLARE LS_PAGE 				VARCHAR(90);
DECLARE LS_STATUS 				VARCHAR(200);
DECLARE LS_TYPE 				VARCHAR(200);
DECLARE LS_REVIEW_STATUS 		VARCHAR(4000);
DECLARE LS_TITLE 				VARCHAR(4000);
DECLARE LS_URL 					VARCHAR(1000);
DECLARE LS_VOLUME 				VARCHAR(3000);
DECLARE LS_YEAR 				VARCHAR(4);
DECLARE LS_PERSON_ID 			VARCHAR(40);
DECLARE LS_SEQUENCE_NUMBER 		INT(11);
DECLARE LI_FLAG					INT(5);
DECLARE LS_HOME_UNIT 			VARCHAR(8);
DECLARE LS_FULL_NAME            VARCHAR(90);
DECLARE LS_AUTHOR_NAMES 		VARCHAR(4000);
DECLARE LS_PUBLICATION_MEDIA 	VARCHAR(2000);
DECLARE LS_UNIT_NAME 			VARCHAR(500);
DECLARE LS_AUTHOR_ORGANIZATION 	VARCHAR(4000);
DECLARE LS_ALTERNATIVE_URL 		VARCHAR(1000);
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT
			PUBLICATION_ID,
			EDITION,
			ISSN,
			PAGE,
			STATUS,
			TYPE,
			REVIEW_STATUS,
			TITLE,
			URL,
			VOLUME,
			YEAR,
            PUBLICATION_MEDIA,
			ALTERNATIVE_URL
	FROM PUBLICATION_RT;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	OPEN CUR_SEL_DATA;
	INSERT_LOOP: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_PUBLICATION_ID,
		LS_EDITION,
		LS_ISSN,
		LS_PAGE,
		LS_STATUS,
		LS_TYPE,
		LS_REVIEW_STATUS,
		LS_TITLE,
		LS_URL,
		LS_VOLUME,
		LS_YEAR,
        LS_PUBLICATION_MEDIA,
		LS_ALTERNATIVE_URL;
	IF DONE1 THEN
		LEAVE INSERT_LOOP;
	END IF;
	SELECT COUNT(1) INTO LI_FLAG
	FROM PUBLICATION
	WHERE PUBLICATION_ID = LS_PUBLICATION_ID;
	IF LI_FLAG = 0 THEN
	INSERT INTO PUBLICATION
		(
		PUBLICATION_ID,
		EDITION,
		ISSN,
		PAGE,
		STATUS,
		TYPE,
		REVIEW_STATUS,
		SCHOOL_OF_AUTHOR,
		TITLE,
		UPDATE_TIMESTAMP,
		UPDATE_USER,
		URL,
		VOLUME,
		YEAR,
		AUTHORGANIZATION,
        PUBLICATION_MEDIA,
		ALTERNATIVE_URL
		)
		VALUES
		(
		LS_PUBLICATION_ID,
		LS_EDITION,
		LS_ISSN,
		LS_PAGE,
		LS_STATUS,
		LS_TYPE,
		LS_REVIEW_STATUS,
		null,
		LS_TITLE,
		NOW(),
		'quickstart',
		LS_URL,
		LS_VOLUME,
		LS_YEAR,
		null,
        LS_PUBLICATION_MEDIA,
		LS_ALTERNATIVE_URL
		);
	ELSE
		UPDATE PUBLICATION SET
		EDITION = LS_EDITION,
		ISSN = LS_ISSN,
		PAGE = LS_PAGE,
		STATUS = LS_STATUS,
		TYPE = LS_TYPE,
		REVIEW_STATUS = LS_REVIEW_STATUS,
		TITLE = LS_TITLE,
		UPDATE_TIMESTAMP = NOW(),
		UPDATE_USER = 'quickstart',
		URL = LS_URL,
		VOLUME = LS_VOLUME,
		YEAR = LS_YEAR,
        PUBLICATION_MEDIA = LS_PUBLICATION_MEDIA,
		ALTERNATIVE_URL = LS_ALTERNATIVE_URL
		WHERE PUBLICATION_ID = LS_PUBLICATION_ID;
	END IF;
	END LOOP;
	CLOSE CUR_SEL_DATA;
	END;
	BEGIN
		DECLARE DONE2 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR
		SELECT
			PUBLICATION_ID,
			PERSON_ID,
			SEQUENCE_NUMBER
		FROM PUBLICATION_PERSONS_RT ORDER BY PUBLICATION_ID, SEQUENCE_NUMBER;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
	OPEN CUR_SEL_DATA;
	INSERT_LOOP1: LOOP
		FETCH CUR_SEL_DATA INTO
		LS_PUBLICATION_ID,
		LS_PERSON_ID,
		LS_SEQUENCE_NUMBER;
	IF DONE2 THEN
		LEAVE INSERT_LOOP1;
	END IF;
	SELECT COUNT(1)  INTO LI_FLAG FROM PERSON WHERE PERSON_ID = LS_PERSON_ID;
	IF LI_FLAG > 0 THEN
		SELECT COUNT(1) INTO LI_FLAG
		FROM PUBLICATION_PERSONS
		WHERE PUBLICATION_ID = LS_PUBLICATION_ID
		AND PERSON_ID = LS_PERSON_ID;
	IF LI_FLAG = 0 THEN
			INSERT INTO PUBLICATION_PERSONS
			(
				PUBLICATION_ID,
				PERSON_ID,
				SEQUENCE_NUMBER,
				UPDATE_TIMESTAMP,
				UPDATE_USER
			)
			VALUES
			(
				LS_PUBLICATION_ID,
				LS_PERSON_ID,
				LS_SEQUENCE_NUMBER,
				NOW(),
				'quickstart'
			);
			IF LS_SEQUENCE_NUMBER = 1 THEN
				SELECT COUNT(1) INTO LI_FLAG FROM PERSON
				WHERE PERSON_ID = LS_PERSON_ID
				AND HOME_UNIT IS NOT NULL;
				IF LI_FLAG > 0 THEN
					SELECT HOME_UNIT INTO LS_HOME_UNIT FROM PERSON
					WHERE PERSON_ID = LS_PERSON_ID;
                    SELECT UNIT_NAME INTO LS_UNIT_NAME FROM UNIT
                    WHERE UNIT_NUMBER = LS_HOME_UNIT;
					UPDATE PUBLICATION
					SET SCHOOL_OF_AUTHOR = LS_UNIT_NAME
					-- AUTHORGANIZATION = LS_UNIT_NAME
					WHERE PUBLICATION_ID = LS_PUBLICATION_ID;
				END IF;
			END IF;
	   SELECT COUNT(1) INTO LI_FLAG FROM PERSON
	   WHERE PERSON_ID = LS_PERSON_ID;
	   IF LI_FLAG > 0 THEN
				SET LS_HOME_UNIT = NULL;
				SET LS_UNIT_NAME = NULL;
				SELECT FULL_NAME,HOME_UNIT
				INTO LS_FULL_NAME,LS_HOME_UNIT
				FROM PERSON
				WHERE PERSON_ID = LS_PERSON_ID;
				SELECT UNIT_NAME INTO LS_UNIT_NAME FROM UNIT
				WHERE UNIT_NUMBER = LS_HOME_UNIT;
				SELECT AUTHORS,AUTHORGANIZATION INTO LS_AUTHOR_NAMES,LS_AUTHOR_ORGANIZATION
				FROM PUBLICATION
				WHERE PUBLICATION_ID = LS_PUBLICATION_ID;
				SET LS_AUTHOR_NAMES = CONCAT(IFNULL(LS_AUTHOR_NAMES,''),', ',IFNULL(LS_FULL_NAME,''));
				SET LS_AUTHOR_ORGANIZATION = CONCAT(IFNULL(LS_AUTHOR_ORGANIZATION,''),', ',IFNULL(LS_UNIT_NAME,''));
				UPDATE PUBLICATION
				SET AUTHORS = TRIM(BOTH ',' FROM LS_AUTHOR_NAMES),
				AUTHORGANIZATION = TRIM(BOTH ',' FROM LS_AUTHOR_ORGANIZATION)
				WHERE PUBLICATION_ID = LS_PUBLICATION_ID;
		END IF;
	  END IF;
    END IF;
		SET LS_FULL_NAME = NULL;
		SET LS_AUTHOR_NAMES = NULL;
		SET LS_HOME_UNIT = NULL;
		SET LS_AUTHOR_ORGANIZATION = NULL;
		SET LS_UNIT_NAME = NULL;
	END LOOP;
	CLOSE CUR_SEL_DATA;
	END;
END
$$
DELIMITER ;
