DELIMITER $$
CREATE  PROCEDURE `smu_expense_tracker_refresh`()
BEGIN
DECLARE LS_FUND						VARCHAR(50);
DECLARE ls_award_number				VARCHAR(20);
DECLARE LI_FLAG						INT;
DECLARE LS_MSG 			TEXT;
DECLARE LS_ERROR       	VARCHAR(1000);
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LI_LOG_ID		INT;
DECLARE LS_ERROR_MSG 		VARCHAR(1000);
DECLARE LI_ERROR_FLAG 		INT;
DECLARE LI_ERR_FLAG 		INT;
DECLARE LI_AWARD_COUNT		INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM SAP_ERROR_LOG;
		INSERT INTO SAP_ERROR_LOG(ERROR_LOG_ID,ERROR_TYPE,ERROR,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,'SAP_FINANCE_REFRESH',LS_ERROR_MSG,NOW(),'quickstart');
		COMMIT;
		SET LI_ERROR_FLAG = 1;
	END;
	SET LI_ERR_FLAG = 0;
	TRUNCATE TABLE AWARD_EXPENSE_LOG;
	INSERT INTO AWARD_EXPENSE_LOG(ACCOUNT_NUMBER, INTERNAL_ORDER_CODE,EXCEPTION_TYPE,UPDATE_TIMESTAMP, UPDATE_USER)
			SELECT DISTINCT ERT.FUND,NULL, '3',NOW(),'quickstart'
			FROM EXPENSE_TRACKER_RT ERT
			WHERE NOT EXISTS ( SELECT 1
								FROM AWARD_EXPENSE_LOG
								WHERE ACCOUNT_NUMBER = ERT.FUND
								AND EXCEPTION_TYPE = '3')
			AND  (SELECT COUNT(DISTINCT AWARD_NUMBER)
			 FROM AWARD
			WHERE ACCOUNT_NUMBER = ERT.FUND) > 1
			UNION ALL
			SELECT  DISTINCT ERT.FUND,NULL, '1',NOW(),'quickstart'
			FROM EXPENSE_TRACKER_RT ERT
			WHERE NOT EXISTS ( SELECT 1
								FROM AWARD_EXPENSE_LOG
								WHERE ACCOUNT_NUMBER = ERT.FUND
								AND EXCEPTION_TYPE = '1')
			AND  (SELECT COUNT(1)
			 FROM AWARD
			WHERE ACCOUNT_NUMBER = ERT.FUND) = 0
			UNION ALL
			SELECT DISTINCT ERT.FUND,(case when ERT.COMBINED_IO_CODE = '' THEN NULL ELSE ERT.COMBINED_IO_CODE END),'2',NOW(),'quickstart'
			FROM EXPENSE_TRACKER_RT ERT
			WHERE NOT EXISTS ( SELECT 1
								FROM AWARD_EXPENSE_LOG
								WHERE IFNULL(INTERNAL_ORDER_CODE,'0') = IFNULL((case when ERT.COMBINED_IO_CODE = '' THEN NULL ELSE ERT.COMBINED_IO_CODE END),'0')
								AND EXCEPTION_TYPE = '2')
			AND  NOT EXISTS (SELECT 1
			 FROM AWARD_BUDGET_DETAIL
			WHERE IFNULL(INTERNAL_ORDER_CODE,'0') = IFNULL((case when ERT.COMBINED_IO_CODE = '' THEN NULL ELSE ERT.COMBINED_IO_CODE END),'0')
			);
	INSERT INTO AWARD_EXPENSE_TRANSACTIONS
		(
		AWARD_NUMBER,
		ACCOUNT_NUMBER,
		INTERNAL_ORDER_CODE,
		REMARKS,
		AMOUNT_IN_FMA_CURRENCY,
		BANK_CLEARING_DATE,
		FM_POSTING_DATE,
		FI_POSTING_DATE,
		GL_DESCRIPTION,
		ASSET,
		ASSET_INTERNAL_ORDER,
		COMMITMENT_ITEM,
		VENDOR_NAME,
		TC_AMOUNT,
		TRANSACTION_CURRENCY,
		ASSET_LOCATION,
		UPDATE_TIMESTAMP,
		UPDATE_USER,
		FM_DOC_NUMBER,
		INVOICE_NUMBER,
		ACTUAL_OR_COMMITTED_FLAG,
		ASSET_COST_CENTER,
		ASSET_LOCATION_CODE,
		DOCUMENT_DATE,
		FI_GL_ACCOUNT,
		FI_GL_DESCRIPTION,
		FI_PO_COST_CENTRE,
		PO_DATE,
		PO_GL_ACCOUNT,
		PO_GL_DESCRIPTION,
		PO_NUMBER,
		PREDECESSOR_DOC_CAT,
		PREDECESSOR_DOC_CAT_TEXT,
		PREDECESSOR_DOC_ITEM,
		PREDECESSOR_DOC_ITEM_ACCOUNT,
		PREDECESSOR_DOC_ITEM_ORG_UNIT,
		PREDECESSOR_DOC_NUMBER,
		REFERENCE_DOC_NUMBER,
		VENDOR_CLEARING_DATE,
		VENDOR_CODE,
		FUND_CENTRE
		)
		(SELECT
		(
				SELECT AWARD_NUMBER FROM AWARD T1
		WHERE T1.ACCOUNT_NUMBER = ERT.FUND
		AND T1.SEQUENCE_NUMBER IN (SELECT MAX(T2.SEQUENCE_NUMBER) FROM AWARD T2
								  WHERE T1.AWARD_NUMBER=T2.AWARD_NUMBER) LIMIT 1),
			ERT.FUND,
			CASE when TRIM(ERT.COMBINED_IO_CODE) = '' then NULL else ERT.COMBINED_IO_CODE end,
			ERT.REMARKS,
			ERT.AMOUNT_IN_FMA_CURRENCY,
			date_format(str_to_date( (CASE WHEN ERT.BANK_CLEARING_DATE = '' then NULL ELSE ERT.BANK_CLEARING_DATE END) ,'%d.%m.%Y'),'%Y-%m-%d'),
			date_format(str_to_date( (CASE WHEN ERT.FM_POSTING_DATE = '' then NULL ELSE ERT.FM_POSTING_DATE end) ,'%d.%m.%Y'),'%Y-%m-%d'),
			date_format(str_to_date( (CASE WHEN ERT.FI_POSTING_DATE = '' then NULL ELSE ERT.FI_POSTING_DATE end) ,'%d.%m.%Y'),'%Y-%m-%d'),
			NULL,
			ERT.ASSET,
			ERT.ASSET_INTERNAL_ORDER,
			ERT.COMMITMENT_ITEM,
			ERT.VENDOR_NAME_1,
			ERT.TC_AMOUNT,
			ERT.TRANSACTION_CURRENCY,
			ERT.ASSET_LOCATION_DESC,
			utc_timestamp(),
			'quickstart',
			ERT.FM_DOC_NUMBER,
			NULL,
			ERT.AC,
			ERT.ASSET_COST_CENTER,
			ERT.ASSET_LOCATION_CODE,
			date_format(str_to_date( (CASE WHEN ERT.DOCUMENT_DATE = '' then NULL ELSE ERT.DOCUMENT_DATE end) ,'%d.%m.%Y'),'%Y-%m-%d'),
			ERT.FI_GL_ACCOUNT,
			ERT.FI_GL_DESCRIPTION,
			ERT.FI_PO_COST_CENTRE,
			date_format(str_to_date( (CASE WHEN ERT.PO_DATE = '' then NULL ELSE ERT.PO_DATE end) ,'%d.%m.%Y'),'%Y-%m-%d'),
			ERT.PO_GL_ACCOUNT,
			ERT.PO_GL_DESCRIPTION,
			ERT.PO_NUMBER,
			ERT.PREDECESSOR_DOC_CAT,
			ERT.PREDECESSOR_DOC_CAT_TEXT,
			ERT.PREDECESSOR_DOC_ITEM,
			ERT.PREDECESSOR_DOC_ITEM_ACCOUNT,
			ERT.PREDECESSOR_DOC_ITEM_ORG_UNIT,
			ERT.PREDECESSOR_DOC_NUMBER,
			NULL,
			date_format(str_to_date( (CASE WHEN ERT.VENDOR_CLEARING_DATE = '' then NULL ELSE ERT.VENDOR_CLEARING_DATE end) ,'%d.%m.%Y'),'%Y-%m-%d'),
			ERT.VENDOR_CODE,
			ERT.FUND_CENTRE
			FROM EXPENSE_TRACKER_RT ERT);
	INSERT INTO SMU_DEBUG_INFO(DEBUG_MSG) VALUES ('After Insert');
	UPDATE	AWARD_EXPENSE_TRANSACTIONS SET INTERNAL_ORDER_CODE = NULL WHERE INTERNAL_ORDER_CODE = '';
	INSERT INTO SMU_DEBUG_INFO(DEBUG_MSG) VALUES ('After Update');
			COMMIT;
END
$$
DELIMITER ;
