DELIMITER $$
CREATE  PROCEDURE `SMU_DATA_MASK_LOAD_TAB_DTLS`(AV_ACTION INT)
BEGIN
/*DECLARE LI_CNT_FULL INT;
DECLARE LI_CNT_FIRST INT;
DECLARE LI_CNT_LAST INT;
DECLARE LI_CNT_USERNAME INT;
DECLARE LI_CNT_EMAIL INT;
DECLARE LI_CNT_FULL_RLDX INT;
DECLARE LI_CNT_FIRST_RLDX INT;
DECLARE LI_CNT_LAST_RLDX INT;
DECLARE LI_CNT_EMAIL_RLDX INT; */
DECLARE LS_SCHEMA VARCHAR(20);
DECLARE LS_EXEC_STMT LONGTEXT;
DECLARE LS_TAB_NAME VARCHAR(100);
DECLARE LS_COL_NAME VARCHAR(100);
DECLARE LS_STAGE VARCHAR(50);
DECLARE LS_ERR_FLG VARCHAR(1);
DECLARE LS_ERROR VARCHAR(2000);
DECLARE LS_ERR_TABLE_NAME VARCHAR(100);
DECLARE DONE BOOLEAN;
DECLARE CUR_NAME CURSOR FOR
	SELECT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA  AND COLUMN_NAME LIKE '%NAME%'
	AND TABLE_NAME NOT IN ('PERSON','ROLODEX')
	AND TABLE_NAME NOT LIKE 'MIGRATION%'
	AND COLUMN_NAME NOT IN ('COUNTRY_NAME','GRANT_CALL_NAME','LINKED_NAME_OF_FUNDING_SCHEME')
	AND NOT EXISTS (SELECT 1
					FROM INFORMATION_SCHEMA.TABLES T
					WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
					AND T.TABLE_NAME = C.TABLE_NAME
					AND T.TABLE_TYPE ='VIEW');
DECLARE CUR_EMAIL CURSOR FOR
	SELECT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA AND COLUMN_NAME LIKE '%EMAIL%'
	AND TABLE_NAME NOT IN ('PERSON','ROLODEX')
	AND NOT EXISTS (SELECT 1
					FROM INFORMATION_SCHEMA.TABLES T
					WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
					AND T.TABLE_NAME = C.TABLE_NAME
					AND T.TABLE_TYPE ='VIEW');
	DECLARE CUR_USR CURSOR FOR
	SELECT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA AND COLUMN_NAME  IN
					('UPDATE_USER','CREATE_USER','SUBMIT_USER','DOCUMENT_UPDATE_USER','AWARD_CREATE_USER','VARIATION_REQUEST_APPROVAL_USER',
					'VARIATION_CREATE_USER','CLAIM_SUBMIT_USER','PROMPT_USER','INST_PROP_CREATE_USER')
	AND TABLE_NAME NOT IN ('PERSON','ROLODEX')
	AND NOT EXISTS (SELECT 1
					FROM INFORMATION_SCHEMA.TABLES T
					WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
					AND T.TABLE_NAME = C.TABLE_NAME
					AND T.TABLE_TYPE ='VIEW');
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		ROLLBACK;
		INSERT INTO SMU_DATA_MASK_AUDIT_LOG
				(STAGE,STATUS,ERR_TABLE_NAME,ERROR_MESSAGE)
		VALUES( LS_STAGE,'ERROR',LS_ERR_TABLE_NAME,LS_ERROR);
		COMMIT;
		SET LS_ERR_FLG ='Y';
	END;
BEGIN
	TRUNCATE TABLE SMU_DATA_MASK_TAB_DTLS;
	TRUNCATE TABLE SMU_DATA_MASK_AUDIT_LOG;
	SELECT 'here';
	SET LS_ERR_FLG = 'N';
	SET LS_SCHEMA = 'smu_qa062022';
	SET LS_STAGE = 'Fetching name related Tables';
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
		(STAGE,STATUS)
	VALUES( LS_STAGE,'Started');
	OPEN CUR_NAME;
		name_loop: LOOP
			/*SET LI_CNT_FULL = 0;
			SET LI_CNT_FIRST = 0;
			SET LI_CNT_LAST  = 0;
			SET LI_CNT_USERNAME  = 0;
			SET LI_CNT_FULL_RLDX = 0;
			SET LI_CNT_FIRST_RLDX = 0;
			SET LI_CNT_LAST_RLDX = 0;*/
			SET DONE = FALSE;
			FETCH CUR_NAME INTO LS_TAB_NAME, LS_COL_NAME;
			IF DONE = TRUE THEN
				LEAVE name_loop;
			END IF;
			SET LS_ERR_TABLE_NAME = LS_TAB_NAME;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_FULL FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT FULL_NAME FROM PERSON WHERE UPPER(FULL_NAME) NOT LIKE ''TEST%'' AND FULL_NAME <> ''SMU Admin'')');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE  LS_EXEC_STMT ;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_FULL > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('PER','FULL_NAME',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_FIRST FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT FIRST_NAME FROM PERSON WHERE UPPER(FIRST_NAME) NOT LIKE ''TEST%'' AND FIRST_NAME <> '''' AND FULL_NAME <> ''SMU Admin'')');
			PREPARE LS_EXEC_STMT FROM  @stmt;
			EXECUTE  LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_FIRST > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('PER','FIRST_NAME',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_LAST FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT LAST_NAME FROM PERSON WHERE UPPER(LAST_NAME) NOT LIKE ''TEST%'' AND FULL_NAME <> ''SMU Admin'')');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE  LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_LAST > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('PER','LAST_NAME',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_USERNAME FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT USER_NAME FROM PERSON WHERE UPPER(USER_NAME) NOT LIKE ''TEST%'' AND FULL_NAME <> ''SMU Admin'')');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_USERNAME > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('PER','USER_NAME',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			-- RLDX
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_FULL_RLDX FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT FULL_NAME FROM ROLODEX WHERE UPPER(FULL_NAME) NOT LIKE ''TEST%'')');
			PREPARE LS_EXEC_STMT FROM  @stmt;
			EXECUTE LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_FULL_RLDX > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('RLDX','FULL_NAME',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_FIRST_RLDX FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT FIRST_NAME FROM ROLODEX WHERE UPPER(FIRST_NAME) NOT LIKE ''TEST%''  AND FIRST_NAME <> '''')');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_FIRST_RLDX > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('RLDX','FIRST_NAME',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_LAST_RLDX FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT LAST_NAME FROM ROLODEX WHERE UPPER(LAST_NAME) NOT LIKE ''TEST%'')');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_LAST_RLDX > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('RLDX','LAST_NAME',LS_TAB_NAME, LS_COL_NAME);
					/*ELSE
						PREPARE LS_EXEC_STMT FROM CONCAT ('SELECT COUNT(*) INTO LI_CNT_USERNAME_RLDX FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT USER_NAME FROM ROLODEX)');
						EXECUTE  LS_EXEC_STMT INTO;
						DEALLOCATE PREPARE LS_EXEC_STMT;
						IF LI_CNT_USERNAME_RLDX > 0 THEN
							INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('RLDX','USER_NAME',LS_TAB_NAME, LS_COL_NAME);
						END IF;*/
			END IF;
		END LOOP;
	CLOSE CUR_NAME;
	SET LS_ERR_TABLE_NAME = NULL;
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
		(STAGE,STATUS)
	VALUES( LS_STAGE,'Completed');
	SET LS_STAGE = 'Fetching email related tables';
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Started');
	OPEN CUR_EMAIL;
		email_loop: LOOP
			/*SET LI_CNT_EMAIL = 0;
			SET LI_CNT_EMAIL_RLDX = 0;*/
			SET DONE = FALSE;
			FETCH CUR_EMAIL INTO LS_TAB_NAME, LS_COL_NAME;
			SET LS_ERR_TABLE_NAME = LS_TAB_NAME;
			IF DONE = TRUE THEN
				LEAVE email_loop;
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_EMAIL FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT EMAIL_ADDRESS FROM PERSON)');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_EMAIL > 0 THEN
				INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('PER','EMAIL',LS_TAB_NAME, LS_COL_NAME);
			END IF;
			SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_EMAIL_RLDX FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT EMAIL_ADDRESS FROM ROLODEX)');
			PREPARE LS_EXEC_STMT FROM @stmt;
			EXECUTE LS_EXEC_STMT;
			DEALLOCATE PREPARE LS_EXEC_STMT;
			IF @LI_CNT_EMAIL_RLDX > 0 THEN
			   INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('RLDX','EMAIL',LS_TAB_NAME, LS_COL_NAME);
			END IF;
		END LOOP;
	CLOSE CUR_EMAIL;
	OPEN CUR_USR;
	usr_loop: LOOP
		SET DONE = FALSE;
		FETCH CUR_USR INTO LS_TAB_NAME, LS_COL_NAME;
		SET LS_ERR_TABLE_NAME = LS_TAB_NAME;
		IF DONE = TRUE THEN
			LEAVE usr_loop;
		END IF;
		SET @stmt = CONCAT ('SELECT COUNT(*) INTO @LI_CNT_USR FROM ', LS_TAB_NAME, ' WHERE ', LS_COL_NAME, ' IN (SELECT USER_NAME FROM PERSON WHERE UPPER(USER_NAME) NOT LIKE ''TEST%'' AND FULL_NAME <> ''SMU Admin'')');
		PREPARE LS_EXEC_STMT FROM @stmt;
		EXECUTE LS_EXEC_STMT;
		DEALLOCATE PREPARE LS_EXEC_STMT;
		IF @LI_CNT_USR > 0 THEN
			INSERT INTO SMU_DATA_MASK_TAB_DTLS (PERSON_TYPE,DATA_CATEGORY, TABLE_NAME,COLUMN_NAME) VALUES ('PER','USR',LS_TAB_NAME, LS_COL_NAME);
		END IF;
	END LOOP;
	CLOSE CUR_USR;
	SET LS_ERR_TABLE_NAME = NULL;
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Completed');
	SET LS_STAGE = 'Fetching address related tables';
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Started');
	INSERT INTO SMU_DATA_MASK_TAB_DTLS (DATA_CATEGORY, TABLE_NAME,COLUMN_NAME)
		(SELECT 'ADDRESS', TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA AND COLUMN_NAME LIKE '%ADDRESS%'
			AND COLUMN_NAME NOT LIKE '%EMAIL%ADDRESS%'
			AND TABLE_NAME NOT IN ('SPONSOR')
			AND NOT EXISTS (SELECT 1
							FROM INFORMATION_SCHEMA.TABLES T
							WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
							AND T.TABLE_NAME = C.TABLE_NAME
							AND T.TABLE_TYPE ='VIEW')
		);
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Completed');
	SET LS_STAGE = 'Fetching postal code related tables';
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Started');
	INSERT INTO SMU_DATA_MASK_TAB_DTLS (DATA_CATEGORY, TABLE_NAME,COLUMN_NAME)
		( SELECT 'POSTAL_CODE',TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA AND COLUMN_NAME LIKE '%POSTAL_CODE%'
			AND TABLE_NAME NOT IN ('SPONSOR')
			AND NOT EXISTS (SELECT 1
							FROM INFORMATION_SCHEMA.TABLES T
							WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
							AND T.TABLE_NAME = C.TABLE_NAME
							AND T.TABLE_TYPE ='VIEW')
		);
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Completed');
	SET LS_STAGE = 'Fetching phone related tables';
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Started');
	INSERT INTO SMU_DATA_MASK_TAB_DTLS (DATA_CATEGORY, TABLE_NAME,COLUMN_NAME)
		(SELECT 'PHONE_NUMBER', TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA AND COLUMN_NAME LIKE '%PHONE_NUMBER%'
			AND TABLE_NAME NOT IN ('SPONSOR')
			AND NOT EXISTS (SELECT 1
							FROM INFORMATION_SCHEMA.TABLES T
							WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
							AND T.TABLE_NAME = C.TABLE_NAME
							AND T.TABLE_TYPE ='VIEW')
		);
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Completed');
	SET LS_STAGE = 'Fetching fax related tables';
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Started');
	INSERT INTO SMU_DATA_MASK_TAB_DTLS (DATA_CATEGORY, TABLE_NAME,COLUMN_NAME)
		(SELECT 'FAX_NUMBER',TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_SCHEMA = LS_SCHEMA AND COLUMN_NAME LIKE '%FAX_NUMBER%'
			AND TABLE_NAME NOT IN ('SPONSOR')
			AND NOT EXISTS (SELECT 1
							FROM INFORMATION_SCHEMA.TABLES T
							WHERE T.TABLE_SCHEMA=C.TABLE_SCHEMA
							AND T.TABLE_NAME = C.TABLE_NAME
							AND T.TABLE_TYPE ='VIEW')
		);
	INSERT INTO SMU_DATA_MASK_AUDIT_LOG
	(STAGE,STATUS)
	VALUES( LS_STAGE,'Completed');
	IF LS_ERR_FLG = 'N' THEN
		COMMIT;
	END IF;
END;
END
$$
DELIMITER ;
