DELIMITER $$
CREATE  PROCEDURE `smu_expense_tracker_refresh_bkp`()
BEGIN
DECLARE LS_AC 						VARCHAR(10);
DECLARE LS_FI_PO_COST_CENTRE		VARCHAR(50);
DECLARE LS_FUND_CENTRE 				VARCHAR(50);
DECLARE LS_FUND						VARCHAR(50);
DECLARE LS_IO_CODE					VARCHAR(100);
DECLARE LS_FMAC_AMNT				VARCHAR(100);
DECLARE LS_REMARKS					VARCHAR(4000);
DECLARE LS_VNDOR_CLARNG_DATE		VARCHAR(40);
DECLARE LS_BANK_CLARNG_DATE			VARCHAR(100);
DECLARE LS_FM_POSTING_DATE			VARCHAR(20);
DECLARE LS_FI_POSTING_DATE			VARCHAR(20);
DECLARE LS_FI_GL_ACCOUNT			VARCHAR(20);
DECLARE LS_FI_GL_DESC				VARCHAR(1000);
DECLARE LS_PO_GL_ACCOUNT			VARCHAR(50);
DECLARE LS_PO_GL_DESC				VARCHAR(1000);
DECLARE LS_ASSET					VARCHAR(50);
DECLARE LS_ASSET_SUBNUMBER			VARCHAR(50);
DECLARE LS_ASSET_INTERNAL_ORDER		VARCHAR(50);
DECLARE LS_ASSET_COST_CENTER		VARCHAR(50);
DECLARE LS_ASSET_LOCATION_CODE		VARCHAR(50);
DECLARE LS_ASSET_LOCATION_DESC		VARCHAR(50);
DECLARE LS_CMMT_ITEM				VARCHAR(50);
DECLARE LS_VENDOR_CODE				VARCHAR(50);
DECLARE LS_VENDOR_NAME_1			VARCHAR(100);
DECLARE LS_VENDOR_NAME_2			VARCHAR(100);
DECLARE LS_TC_AMOUNT				VARCHAR(20);
DECLARE LS_TRAN_CURR				VARCHAR(20);
DECLARE LS_PRD_DOC_NO				VARCHAR(20);
DECLARE LS_PRED_DI					VARCHAR(20);
DECLARE LS_PRED_DIAC				VARCHAR(20);
DECLARE LS_PRED_DIORG				VARCHAR(20);
DECLARE LS_PRED_DOC_CAT				VARCHAR(20);
DECLARE LS_PRED_DOC_CAT_TEXT		VARCHAR(50);
DECLARE LS_FM_DOC_NO				VARCHAR(50);
DECLARE LS_FI_REFERENCE				VARCHAR(50);
DECLARE LS_DOC_DATE					VARCHAR(50);
DECLARE LS_PO_NUMBER				VARCHAR(50);
DECLARE LS_PO_DATE					VARCHAR(20);
DECLARE ls_award_number				VARCHAR(20);
DECLARE LI_FLAG						INT;
DECLARE LI_AWARD_ID 				INT;
DECLARE LS_CODE 		CHAR(5) DEFAULT '00000';
DECLARE LS_MSG 			TEXT;
DECLARE LS_ERROR       	VARCHAR(1000);
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LI_LOG_ID		INT;
DECLARE LI_BUDGET_HEADER_ID	INT;
DECLARE LS_ERROR_MSG 		VARCHAR(1000);
DECLARE LI_ERROR_FLAG 		INT;
DECLARE LI_ERR_FLAG 		INT;
DECLARE LI_AWARD_COUNT		INT;
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR_MSG;
		SELECT IFNULL(MAX(ERROR_LOG_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM SAP_ERROR_LOG;
		INSERT INTO SAP_ERROR_LOG(ERROR_LOG_ID,ERROR_TYPE,ERROR,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES(LI_SEQ_ERROR_LOG_ID,'SAP_FINANCE_REFRESH',LS_ERROR_MSG,NOW(),'quickstart');
		COMMIT;
		SET LI_ERROR_FLAG = 1;
	END;
	SET LI_ERR_FLAG = 0;
	truncate table AWARD_EXPENSE_LOG;
	BEGIN
		DECLARE done1 INT DEFAULT FALSE;
		DECLARE cur_sel_data CURSOR FOR
		select
			AC,
			FI_PO_COST_CENTRE,
			FUND_CENTRE,
			FUND,
			INTERNAL_ORDER_CODE,
			AMOUNT_IN_FMA_CURRENCY,
			REMARKS,
			VENDOR_CLEARING_DATE,
			BANK_CLEARING_DATE,
			FM_POSTING_DATE,
			FI_POSTING_DATE,
			FI_GL_ACCOUNT,
			FI_GL_DESCRIPTION,
			PO_GL_ACCOUNT,
			PO_GL_DESCRIPTION,
			ASSET,
			SUBNUMBER,
			ASSET_INTERNAL_ORDER,
			ASSET_COST_CENTER,
			ASSET_LOCATION_CODE,
			ASSET_LOCATION_DESC,
			COMMITMENT_ITEM,
			VENDOR_CODE,
			VENDOR_NAME_1,
			VENDOR_NAME_2,
			TC_AMOUNT,
			TRANSACTION_CURRENCY,
			PREDECESSOR_DOC_NUMBER,
			PREDECESSOR_DOC_ITEM,
			PREDECESSOR_DOC_ITEM_ACCOUNT,
			PREDECESSOR_DOC_ITEM_ORG_UNIT,
			PREDECESSOR_DOC_CAT,
			PREDECESSOR_DOC_CAT_TEXT,
			FM_DOC_NUMBER,
			FI_REFERENCE,
			DOCUMENT_DATE,
			PO_NUMBER,
			PO_DATE
	from EXPENSE_TRACKER_RT;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET done1 = TRUE;
	OPEN cur_sel_data;
	insert_loop: LOOP
		FETCH cur_sel_data INTO
		LS_AC,
		LS_FI_PO_COST_CENTRE,
		LS_FUND_CENTRE,
		LS_FUND,
		LS_IO_CODE,
		LS_FMAC_AMNT,
		LS_REMARKS,
		LS_VNDOR_CLARNG_DATE,
		LS_BANK_CLARNG_DATE,
		LS_FM_POSTING_DATE,
		LS_FI_POSTING_DATE,
		LS_FI_GL_ACCOUNT,
		LS_FI_GL_DESC,
		LS_PO_GL_ACCOUNT,
		LS_PO_GL_DESC,
		LS_ASSET,
		LS_ASSET_SUBNUMBER,
		LS_ASSET_INTERNAL_ORDER,
		LS_ASSET_COST_CENTER,
		LS_ASSET_LOCATION_CODE,
		LS_ASSET_LOCATION_DESC,
		LS_CMMT_ITEM,
		LS_VENDOR_CODE,
		LS_VENDOR_NAME_1,
		LS_VENDOR_NAME_2,
		LS_TC_AMOUNT,
		LS_TRAN_CURR,
		LS_PRD_DOC_NO,
		LS_PRED_DI,
		LS_PRED_DIAC,
		LS_PRED_DIORG,
		LS_PRED_DOC_CAT,
		LS_PRED_DOC_CAT_TEXT,
		LS_FM_DOC_NO,
		LS_FI_REFERENCE,
		LS_DOC_DATE,
		LS_PO_NUMBER,
		LS_PO_DATE;
	IF done1 THEN
		LEAVE insert_loop;
	END IF;
	IF LS_IO_CODE = '' THEN
		SET LS_IO_CODE = NULL;
	END IF;
	SELECT COUNT(DISTINCT AWARD_NUMBER) INTO LI_AWARD_COUNT FROM AWARD
	WHERE ACCOUNT_NUMBER = LS_FUND;
	IF LI_AWARD_COUNT > 1 THEN
		SELECT COUNT(1) INTO LI_FLAG
		FROM AWARD_EXPENSE_LOG
		WHERE ACCOUNT_NUMBER = LS_FUND
		AND EXCEPTION_TYPE = '3';
		IF LI_FLAG = 0 THEN
			SELECT IFNULL(MAX(LOG_ID),0)+1 INTO LI_LOG_ID FROM AWARD_EXPENSE_LOG;
			INSERT INTO AWARD_EXPENSE_LOG(LOG_ID, EXCEPTION_TYPE, ACCOUNT_NUMBER, INTERNAL_ORDER_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES (LI_LOG_ID,'3',LS_FUND,NULL,NOW(),'quickstart');
		END IF;
	END IF;
    SELECT COUNT(1) INTO LI_FLAG
    FROM AWARD T1
	WHERE T1.ACCOUNT_NUMBER = LS_FUND
    AND T1.SEQUENCE_NUMBER IN (SELECT MAX(T2.SEQUENCE_NUMBER) FROM AWARD T2
							  WHERE T1.AWARD_NUMBER=T2.AWARD_NUMBER);
    IF LI_FLAG > 0 THEN
		SELECT AWARD_NUMBER INTO ls_award_number FROM AWARD T1
		WHERE T1.ACCOUNT_NUMBER = LS_FUND
		AND T1.SEQUENCE_NUMBER IN (SELECT MAX(T2.SEQUENCE_NUMBER) FROM AWARD T2
								  WHERE T1.AWARD_NUMBER=T2.AWARD_NUMBER) LIMIT 1;
		SELECT AWARD_ID INTO LI_AWARD_ID
		FROM AWARD T1
		WHERE T1.AWARD_NUMBER = ls_award_number
		AND T1.SEQUENCE_NUMBER IN (SELECT MAX(T2.SEQUENCE_NUMBER) FROM AWARD T2
								  WHERE T1.AWARD_NUMBER = T2.AWARD_NUMBER
								  );
		SELECT COUNT(1) INTO LI_FLAG
		FROM AWARD_BUDGET_HEADER T1
		WHERE T1.AWARD_ID = LI_AWARD_ID;
		IF LI_FLAG > 0 THEN
			SELECT BUDGET_HEADER_ID
			INTO LI_BUDGET_HEADER_ID
			FROM AWARD_BUDGET_HEADER T1
			WHERE T1.AWARD_ID = LI_AWARD_ID
			AND T1.VERSION_NUMBER IN (SELECT MAX(T2.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER T2 WHERE T1.AWARD_ID = T2.AWARD_ID);
			SELECT COUNT(1) INTO LI_FLAG
			FROM AWARD_BUDGET_DETAIL
			WHERE BUDGET_HEADER_ID = LI_BUDGET_HEADER_ID
			AND IFNULL(INTERNAL_ORDER_CODE,'0') = IFNULL(LS_IO_CODE,'0');
			IF LI_FLAG = 0 THEN
				SELECT COUNT(1) INTO LI_FLAG
				FROM AWARD_EXPENSE_LOG
				WHERE ACCOUNT_NUMBER = LS_FUND
				AND IFNULL(INTERNAL_ORDER_CODE,'0') = IFNULL(LS_IO_CODE,'0')
				AND EXCEPTION_TYPE = '2';
				IF LI_FLAG = 0 THEN
					SELECT IFNULL(MAX(LOG_ID),0)+1 INTO LI_LOG_ID FROM AWARD_EXPENSE_LOG;
					INSERT INTO AWARD_EXPENSE_LOG(LOG_ID, EXCEPTION_TYPE, ACCOUNT_NUMBER, INTERNAL_ORDER_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
					VALUES (LI_LOG_ID,'2',LS_FUND,LS_IO_CODE,NOW(),'quickstart');
				END IF;
			END IF;
		ELSE
			SELECT COUNT(1) INTO LI_FLAG
			FROM AWARD_EXPENSE_LOG
			WHERE ACCOUNT_NUMBER = LS_FUND
			AND IFNULL(INTERNAL_ORDER_CODE,'0') = IFNULL(LS_IO_CODE,'0')
			AND EXCEPTION_TYPE = '2';
			IF LI_FLAG = 0 THEN
				SELECT IFNULL(MAX(LOG_ID),0)+1 INTO LI_LOG_ID FROM AWARD_EXPENSE_LOG;
				INSERT INTO AWARD_EXPENSE_LOG(LOG_ID, EXCEPTION_TYPE, ACCOUNT_NUMBER, INTERNAL_ORDER_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
				VALUES (LI_LOG_ID,'2',LS_FUND,LS_IO_CODE,NOW(),'quickstart');
			END IF;
		END IF;
	ELSE
		SELECT COUNT(1) INTO LI_FLAG
		FROM AWARD_EXPENSE_LOG
		WHERE ACCOUNT_NUMBER = LS_FUND
		AND EXCEPTION_TYPE = '1';
		IF LI_FLAG = 0 THEN
		SELECT IFNULL(MAX(LOG_ID),0)+1 INTO LI_LOG_ID FROM AWARD_EXPENSE_LOG;
		INSERT INTO AWARD_EXPENSE_LOG(LOG_ID, EXCEPTION_TYPE, ACCOUNT_NUMBER, INTERNAL_ORDER_CODE, UPDATE_TIMESTAMP, UPDATE_USER)
		VALUES (LI_LOG_ID,'1',LS_FUND,NULL,NOW(),'quickstart');
		END IF;
	END IF;
	IF LS_BANK_CLARNG_DATE ='' THEN
		SET LS_BANK_CLARNG_DATE = NULL;
	END IF;
	IF LS_FM_POSTING_DATE ='' THEN
		SET LS_FM_POSTING_DATE = NULL;
	END IF;
	IF LS_FI_POSTING_DATE ='' THEN
		SET LS_FI_POSTING_DATE = NULL;
	END IF;
	IF LS_DOC_DATE ='' THEN
		SET LS_DOC_DATE = NULL;
	END IF;
	IF LS_PO_DATE ='' THEN
		SET LS_PO_DATE = NULL;
	END IF;
	IF LS_VNDOR_CLARNG_DATE ='' THEN
		SET LS_VNDOR_CLARNG_DATE = NULL;
	END IF;
        set ls_award_number := null;
        SET LS_FUND = NULL;
		SET LS_IO_CODE = NULL;
	END LOOP;
	CLOSE cur_sel_data;
	END;
END
$$
DELIMITER ;
