DELIMITER $$
CREATE  PROCEDURE `SYNC_UNIT_WITH_CHILDREN_PERSON_ROLE`(
	AV_UNIT_NUMBER            VARCHAR(60),
	AV_CHILD_UNIT_NUMBER            VARCHAR(60),
	AV_UNIT_NAME            VARCHAR(60),
	AV_CHILD_UNIT_NAME            VARCHAR(60)
)
BEGIN
	INSERT INTO unit_with_children (UNIT_NUMBER, CHILD_UNIT_NUMBER, UNIT_NAME, CHILD_UNIT_NAME)
		SELECT T1.UNIT_NUMBER, AV_CHILD_UNIT_NUMBER AS CHILD_UNIT_NUMBER, UNIT_NAME, CHILD_UNIT_NAME
		FROM unit_with_children T1 WHERE T1.CHILD_UNIT_NUMBER = AV_UNIT_NUMBER;
    INSERT INTO unit_with_children (UNIT_NUMBER, CHILD_UNIT_NUMBER, UNIT_NAME, CHILD_UNIT_NAME) VALUES(
		AV_CHILD_UNIT_NUMBER, AV_CHILD_UNIT_NUMBER, AV_UNIT_NAME, AV_CHILD_UNIT_NAME);
    INSERT INTO PERSON_ROLE_RT(RIGHT_NAME,PERSON_ID, UNIT_NUMBER, ROLE_ID)
		(SELECT DISTINCT T3.RIGHT_NAME,T1.PERSON_ID, AV_CHILD_UNIT_NUMBER AS unit_number ,T1.ROLE_ID
		FROM PERSON_ROLES T1
		INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
		WHERE T1.DESCEND_FLAG = 'Y'
		AND T1.UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM unit_with_children WHERE CHILD_UNIT_NUMBER = AV_CHILD_UNIT_NUMBER));
END
$$
DELIMITER ;
