DELIMITER $$
CREATE  PROCEDURE `UPDATE_ATTACHMENT_DOC_ID`()
BEGIN
DECLARE LS_AWARD_NUMBER VARCHAR(200);
DECLARE DONE TINYINT DEFAULT 0;
DECLARE LI_AWARD_ATTACHMENT_ID INT;
DECLARE LI_DOCUMENT_ID INT;
DECLARE C1 CURSOR FOR
SELECT AWARD_ATTACHMENT_ID, AWARD_NUMBER FROM AWARD_ATTACHMENT WHERE DOCUMENT_ID IS NULL and VERSION_NUMBER = 1;
OPEN C1;
LOOP1: LOOP BEGIN
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
FETCH C1 INTO LI_AWARD_ATTACHMENT_ID, LS_AWARD_NUMBER;
select ifnull(max(DOCUMENT_ID),0)+1 INTO LI_DOCUMENT_ID from award_attachment where AWARD_NUMBER = LS_AWARD_NUMBER;
UPDATE AWARD_ATTACHMENT SET DOCUMENT_ID = LI_DOCUMENT_ID WHERE AWARD_ATTACHMENT_ID = LI_AWARD_ATTACHMENT_ID;
IF DONE THEN
LEAVE LOOP1;
END IF;
END;
END LOOP;
CLOSE C1;
END
$$
DELIMITER ;
