DELIMITER $$
CREATE  PROCEDURE `UPDATE_AWARD_REPORT_TRACKING`()
BEGIN
DECLARE LI_AWARD_ID 			INT;
DECLARE LI_AWARD_REPORT_TERM_ID 			INT;
DECLARE LS_AWARD_NUMBER 		VARCHAR(12);
DEclARE LI_SEQ_NUMBER 			INT;
DECLARE LS_PERSON_ID 			VARCHAR(40);
DECLARE LI_SEQ_AWARD_PERSON_ROLE_ID INT;
DECLARE LS_UPDATE_USER 				VARCHAR(60);
DEclARE LS_UPDATE_TIMESTAMP 			DATETIME;
DEclARE LS_DUE_DATE 			DATETIME;
	BEGIN
		DECLARE DONE4 INT DEFAULT FALSE;
		DECLARE CUR_DETAIL CURSOR FOR
		select AWARD_REPORT_TERMS_ID, AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,UPDATE_TIMESTAMP,UPDATE_USER,DUE_DATE from award_report_terms where BASE_DATE is null and
		FREQUENCY_BASE_CODE = '6'
         AND AWARD_REPORT_TERMS_ID NOT IN
        (SELECT AWARD_REPORT_TERMS_ID FROM award_report_tracking);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
		OPEN CUR_DETAIL;
		INSERT_LOOP4: LOOP
		FETCH CUR_DETAIL INTO
		LI_AWARD_REPORT_TERM_ID,
		LI_AWARD_ID,
		LS_AWARD_NUMBER,
		LI_SEQ_NUMBER,
		LS_UPDATE_TIMESTAMP,
		LS_UPDATE_USER,
		LS_DUE_DATE;
		IF DONE4 THEN
			LEAVE INSERT_LOOP4;
		END IF;
 		INSERT INTO AWARD_REPORT_TRACKING(
		AWARD_REPORT_TERMS_ID,
		AWARD_ID,
		AWARD_NUMBER,
		SEQUENCE_NUMBER,
		STATUS_CODE,
		UPDATE_TIMESTAMP,
		UPDATE_USER,
		DUE_DATE)
		VALUES
		(
		LI_AWARD_REPORT_TERM_ID,
		LI_AWARD_ID,
		LS_AWARD_NUMBER,
		LI_SEQ_NUMBER,
		1,
		LS_UPDATE_TIMESTAMP,
		LS_UPDATE_USER,
		LS_DUE_DATE
		);
		END LOOP;
		CLOSE CUR_DETAIL;
	END;
END
$$
DELIMITER ;
