CREATE PROCEDURE `GET_PROPOSAL_BUDGET_SUMMARY_JSON`(
    IN AV_PROPOSAL_ID INT,
    OUT OUT_BUDGET_SUMMARY_JSON JSON
)
BEGIN
    DECLARE LI_BUDGET_ID INT;
	DECLARE LI_TOTAL_COST DECIMAL(15,2);

    SELECT BUDGET_HEADER_ID INTO LI_BUDGET_ID FROM BUDGET_HEADER WHERE PROPOSAL_ID = AV_PROPOSAL_ID ORDER BY VERSION_NUMBER LIMIT 1; -- MENTION VERSION OF BUDGET

	SELECT
		COALESCE(SUM(
			CASE
				-- If budget details exist for this period, sum line item costs
				WHEN EXISTS (SELECT 1
							 FROM BUDGET_DETAIL BD
							 WHERE BD.BUDGET_PERIOD_ID = BP.BUDGET_PERIOD_ID)
				THEN (SELECT COALESCE(SUM(LINE_ITEM_COST), 0)
					  FROM BUDGET_DETAIL BD
					  WHERE BD.BUDGET_PERIOD_ID = BP.BUDGET_PERIOD_ID)
				-- Else, sum costSharingAmount + totalCost as totalInKind + totalCost
				ELSE COALESCE(BP.COST_SHARING_AMOUNT,0) + COALESCE(BP.TOTAL_COST,0)
			END
		), 0)
	INTO LI_TOTAL_COST
	FROM BUDGET_PERIOD BP
	WHERE BP.BUDGET_HEADER_ID = LI_BUDGET_ID;

    SELECT JSON_OBJECT(
        'HEADER', (
            SELECT JSON_OBJECT(
                'BUDGET_HEADER_ID', T1.BUDGET_HEADER_ID,
                'OVERHEAD_RATE', T2.DESCRIPTION,
                'UNDERRECOVERY_RATE', T3.DESCRIPTION,
                'BUDGET_STATUS', T4.DESCRIPTION,
                'IS_FINAL', T1.IS_FINAL_BUDGET,
                'TOTAL_DIRECT_COST', T1.TOTAL_DIRECT_COST,
                'TOTAL_INDIRECT_COST', T1.TOTAL_INDIRECT_COST,
                'COST_SHARING_AMOUNT', T1.COST_SHARING_AMOUNT,
                'UNDERRECOVERY_AMOUNT', T1.UNDERRECOVERY_AMOUNT,
                'TOTAL_COST', LI_TOTAL_COST,
                'ON_OFF_CAMPUS_FLAG', T1.ON_OFF_CAMPUS_FLAG,
                'ON_CAMPUS_RATES', T1.ON_CAMPUS_RATES,
                'OFF_CAMPUS_RATES', T1.OFF_CAMPUS_RATES,
                'BUDGET_DESCRIPTION', T1.COMMENTS
            )
            FROM BUDGET_HEADER T1
                INNER JOIN RATE_TYPE T2 ON T1.RATE_CLASS_CODE = T2.RATE_CLASS_CODE AND T1.RATE_TYPE_CODE = T2.RATE_TYPE_CODE
                INNER JOIN RATE_TYPE T3 ON T1.UNDERRECOVERY_CLASS_CODE = T3.RATE_CLASS_CODE AND T1.UNDERRECOVERY_TYPE_CODE = T3.RATE_TYPE_CODE
                INNER JOIN BUDGET_STATUS T4 ON T1.BUDGET_STATUS_CODE = T4.BUDGET_STATUS_CODE
            WHERE T1.BUDGET_HEADER_ID = LI_BUDGET_ID
        ),
        'PERIODS', (
            SELECT JSON_ARRAYAGG(
                JSON_OBJECT(
                    'BUDGET_PERIOD', BUDGET_PERIOD,
                    'START_DATE', START_DATE,
                    'END_DATE', END_DATE,
                    'TOTAL_DIRECT_COST', TOTAL_DIRECT_COST,
                    'TOTAL_INDIRECT_COST', TOTAL_INDIRECT_COST,
                    'COST_SHARING_AMOUNT', COST_SHARING_AMOUNT,
                    'UNDERRECOVERY_AMOUNT', UNDERRECOVERY_AMOUNT,
                    'TOTAL_COST', TOTAL_COST
                )
            )
            FROM BUDGET_PERIOD
            WHERE BUDGET_HEADER_ID = LI_BUDGET_ID
        ),
        'PERSONS', (
            SELECT JSON_ARRAYAGG(
                JSON_OBJECT(
                    'TYPE', T2.NAME,
                    'PERSON_NAME', T1.PERSON_NAME,
                    'JOB_TITLE', T3.JOB_TITLE,
                    'APPOINTMENT_TYPE', T4.DESCRIPTION,
                    'EFFECTIVE_DATE', T1.EFFECTIVE_DATE,
                    'CALC_BASE', T1.CALCULATION_BASE
                )
            )
            FROM BUDGET_PERSONS T1
                INNER JOIN PROPOSAL_PERSONNEL_TYPE T2 ON T1.PERSON_TYPE = T2.VALUE
                INNER JOIN JOB_CODE T3 ON T1.JOB_CODE = T3.JOB_CODE
                INNER JOIN APPOINTMENT_TYPE T4 ON T1.APPOINTMENT_TYPE_CODE = T4.APPOINTMENT_TYPE_CODE
            WHERE T1.BUDGET_HEADER_ID = LI_BUDGET_ID
        ),
        'LINE_ITEMS', (
            SELECT JSON_ARRAYAGG(
                JSON_OBJECT(
                    'COST_ELEMENT_DESCRIPTION', T2.DESCRIPTION,
                    'LINE_ITEM', T1.LINE_ITEM_DESCRIPTION,
                    'CATEGORY_DESCRIPTION', T3.DESCRIPTION,
                    'CATEGORY_TYPE_DESCRIPTION', T4.DESCRIPTION,
                    'BUDGET_PERIOD', T1.BUDGET_PERIOD,
                    'QUANTITY', T1.QUANTITY,
                    'LINE_ITEM_COST', T1.LINE_ITEM_COST,
                    'COST_SHARING_PERCENT', T1.COST_SHARING_PERCENT,
                    'COST_SHARING_AMOUNT', T1.COST_SHARING_AMOUNT,
                    'SPONSOR_REQUESTED_AMOUNT', T1.SPONSOR_REQUESTED_AMOUNT
                )
            )
            FROM BUDGET_DETAIL T1
                INNER JOIN COST_ELEMENT T2 ON T1.COST_ELEMENT = T2.COST_ELEMENT
                INNER JOIN BUDGET_CATEGORY T3 ON T2.BUDGET_CATEGORY_CODE = T3.BUDGET_CATEGORY_CODE
                INNER JOIN BUDGET_CATEGORY_TYPE T4 ON T3.BUDGET_CATEGORY_TYPE_CODE = T4.BUDGET_CATEGORY_TYPE_CODE
            WHERE T1.BUDGET_PERIOD_ID IN (
                SELECT BUDGET_PERIOD_ID
                FROM BUDGET_PERIOD
                WHERE BUDGET_HEADER_ID = LI_BUDGET_ID
            )
        ),
        'PERSON_DETAILS', (
            SELECT JSON_ARRAYAGG(
                JSON_OBJECT(
                    'PERSON_NAME', T1.PERSON_NAME,
                    'COST_ELEMENT_DESCRIPTION', CE.DESCRIPTION,
                    'CATEGORY_DESCRIPTION', BC.DESCRIPTION,
                    'CATEGORY_TYPE_DESCRIPTION', BCT.DESCRIPTION,
                    'BUDGET_PERIOD', T2.BUDGET_PERIOD,
                    'START_DATE', T1.START_DATE,
                    'END_DATE', T1.END_DATE,
                    'SALARY', T1.SALARY,
                    'PERCENT_EFFORT', T1.PERCENT_EFFORT,
                    'SALARY_REQUESTED', T1.SALARY_REQUESTED,
                    'COST_SHARING_PERCENT', T1.COST_SHARING_PERCENT,
                    'COST_SHARING_AMOUNT', T1.COST_SHARING_AMOUNT,
                    'SPONSOR_REQUESTED_AMOUNT', T1.SPONSOR_REQUESTED_AMOUNT
                )
            )
            FROM BUDGET_PERSON_DETAIL T1
                INNER JOIN BUDGET_DETAIL T2 ON T1.BUDGET_DETAILS_ID = T2.BUDGET_DETAILS_ID
                INNER JOIN COST_ELEMENT CE ON T2.COST_ELEMENT = CE.COST_ELEMENT
                INNER JOIN BUDGET_CATEGORY BC ON CE.BUDGET_CATEGORY_CODE = BC.BUDGET_CATEGORY_CODE
                INNER JOIN BUDGET_CATEGORY_TYPE BCT ON BC.BUDGET_CATEGORY_TYPE_CODE = BCT.BUDGET_CATEGORY_TYPE_CODE
            WHERE T2.BUDGET_PERIOD_ID IN (
                SELECT BUDGET_PERIOD_ID
                FROM BUDGET_PERIOD
                WHERE BUDGET_HEADER_ID = LI_BUDGET_ID
            )
        )
) AS FULL_BUDGET_DATA INTO OUT_BUDGET_SUMMARY_JSON;
END
