-- `FN_CHK_PROP_BUDGET_TOT_COST`; 

CREATE FUNCTION `FN_CHK_PROP_BUDGET_TOT_COST`(
AV_PROPOSAL_ID int(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
DECLARE LI_MAX_BUDGET DECIMAL(14,2);
DECLARE LI_TOTAL_COST DECIMAL(10,2);
DECLARE LI_BUDGET_HEADER_ID INT(12);
SELECT COUNT(1) INTO LI_FLAG
FROM EPS_PROPOSAL
WHERE PROPOSAL_ID = AV_PROPOSAL_ID
AND GRANT_HEADER_ID IS NOT NULL;
IF LI_FLAG = 0 THEN
	RETURN 'TRUE';
END IF;
SELECT COUNT(1) INTO LI_FLAG
FROM GRANT_CALL_HEADER
WHERE GRANT_HEADER_ID = (SELECT GRANT_HEADER_ID
FROM EPS_PROPOSAL
WHERE PROPOSAL_ID = AV_PROPOSAL_ID
)
AND MAX_BUDGET IS NOT NULL;
IF LI_FLAG = 0 THEN
	RETURN 'TRUE';
END IF;
SELECT COUNT(1) INTO LI_FLAG
FROM BUDGET_HEADER T1
WHERE T1.PROPOSAL_ID = AV_PROPOSAL_ID;
IF LI_FLAG = 0 THEN
	RETURN 'TRUE';
END IF;
SELECT MAX_BUDGET INTO LI_MAX_BUDGET
FROM EPS_PROPOSAL T1
INNER JOIN GRANT_CALL_HEADER T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
WHERE PROPOSAL_ID = AV_PROPOSAL_ID;
SELECT BUDGET_HEADER_ID INTO LI_BUDGET_HEADER_ID
FROM BUDGET_HEADER WHERE PROPOSAL_ID = AV_PROPOSAL_ID AND (IS_FINAL_BUDGET = 'Y'  OR IS_APPROVED_BUDGET = 'Y');
IF LI_BUDGET_HEADER_ID IS NULL THEN
SELECT MAX(BUDGET_HEADER_ID) INTO LI_BUDGET_HEADER_ID
FROM BUDGET_HEADER 
WHERE PROPOSAL_ID = AV_PROPOSAL_ID ;
IF LI_BUDGET_HEADER_ID IS NULL THEN
	RETURN 'TRUE';
END IF;
END IF;
SELECT TOTAL_COST INTO LI_TOTAL_COST
FROM BUDGET_HEADER WHERE BUDGET_HEADER_ID = LI_BUDGET_HEADER_ID;
IF LI_TOTAL_COST <= LI_MAX_BUDGET THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
END IF;
END
