-- `FN_CHK_IS_PROP_BUDGET_AS_FINAL`; 

CREATE FUNCTION `FN_CHK_IS_PROP_BUDGET_AS_FINAL`(
AV_PROPOSAL_ID    varchar(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
	SELECT COUNT(1) INTO LI_FLAG FROM BUDGET_HEADER
	WHERE PROPOSAL_ID = AV_PROPOSAL_ID; 
    IF LI_FLAG = 0 THEN
		RETURN 'TRUE';
    END IF;
	SELECT COUNT(1) INTO LI_FLAG FROM BUDGET_HEADER
	WHERE PROPOSAL_ID = AV_PROPOSAL_ID
	AND (IS_FINAL_BUDGET = 'Y'  OR IS_APPROVED_BUDGET = 'Y');
	IF LI_FLAG > 0 THEN
		RETURN 'TRUE';
	END IF;
	RETURN 'FALSE';
END
