-- `FN_CHK_RSO_HOD_IS_NOT_PI`; 

CREATE FUNCTION `FN_CHK_RSO_HOD_IS_NOT_PI`(
AV_PROPOSAL_ID    varchar(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LS_HOME_UNIT_NUMBER VARCHAR(50);
DECLARE LS_COUNT INT;
SELECT T1.HOME_UNIT_NUMBER INTO LS_HOME_UNIT_NUMBER 
FROM EPS_PROPOSAL T1
WHERE T1.PROPOSAL_ID = AV_PROPOSAL_ID;
IF LS_HOME_UNIT_NUMBER IS NULL THEN
	RETURN 'FALSE';
ELSE
    IF LS_HOME_UNIT_NUMBER = '252' THEN
		SELECT COUNT(*) INTO LS_COUNT 
		FROM EPS_PROPOSAL_PERSONS 
		WHERE PROPOSAL_ID = AV_PROPOSAL_ID
		AND PERSON_ID IN (	
							SELECT T1.PERSON_ID 
							FROM PERSON_ROLES T1 
							WHERE T1.ROLE_ID = 400
							AND T1.UNIT_NUMBER =  LS_HOME_UNIT_NUMBER
							)
		AND PROP_PERSON_ROLE_ID = 3;
		IF  LS_COUNT = 0 THEN
			RETURN 'TRUE';
		END IF;
    END IF;
RETURN 'FALSE';
END IF;
END
