INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('1', '1', 'DISCLOSURE_STATUS', 'Disclosure Status', '2024-11-30 01:31:16', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('2', '1', 'EXPIRATION_DATE', 'Disclosure Expiration Date', '2024-11-30 01:31:16', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('3', '1', 'CERTIFICATION_DATE', 'Disclosure Certification Date', '2024-11-30 01:31:17', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('4', '1', 'REVIEW_STATUS', 'Disclosure Review Status', '2024-11-30 01:31:17', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('5', '1', 'DEPARTMENT_NAME', 'Disclosure Department Name', '2024-11-30 01:31:17', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('6', '1', 'DEPARTMENT_NUMBER', 'Disclosure Department Number', '2024-11-30 01:31:17', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('7', '1', 'REPORTER_NAME', 'Reporter Name', '2024-11-30 01:31:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('8', '2', 'WITHDRAWAL_REASON', 'Disclosure Withdrawal Reason', '2024-11-30 01:31:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('9', '2', 'WITHDRAWAL_DATE', 'Disclosure Withdrawal Date', '2024-11-30 01:31:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('10', '2', 'RETURN_REASON', 'Disclosure Return Reason', '2024-11-30 01:31:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('11', '1', 'ADMINISTRATOR_NAME', 'Administrator Name', '2024-11-30 01:31:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('12', '2', 'ADMIN_ASSIGNED_BY', 'Administrator Assigned By', '2024-11-30 01:31:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('13', '2', 'ADMIN_ASSIGNED_TO', 'Administrator Assigned To', '2024-11-30 01:31:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('14', '3', 'REVIEW_LOCATION', 'Review Location', '2024-11-30 01:31:20', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('15', '3', 'REVIEWER_REVIEW_STATUS', 'Reviewer Review Status', '2024-11-30 01:31:20', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('16', '1', 'PROJECT_NUMBER', 'Disclosure Project ID/Number', '2024-11-30 01:31:20', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('17', '1', 'PROJECT_TITLE', 'Disclosure Project Title', '2024-11-30 01:31:21', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('22', '4', 'PROJECT_MODULE_ITEM_KEY', 'Project Number', '2024-11-30 01:31:21', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('23', '4', 'PROJECT_PERSON_NAME', 'Project Person Name', '2024-11-30 01:31:21', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('24', '4', 'PROJECT_TITLE', 'Project Title', '2024-11-30 01:31:22', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('25', '5', 'DISCLOSURE_URL', 'Disclosure Url', '2024-11-30 01:31:22', 'admin', '1', '/create-disclosure/screening?disclosureId={COI_DISCLOSURE#DISCLOSURE_ID}');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('26', '1', 'DISCLOSURE_ID', 'Disclosure Id', '2024-11-30 01:31:22', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('27', '3', 'REVIEWER_NAME', 'Reviewer Name', '2024-11-30 01:31:22', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('28', '2', 'PREVIOUS_RISK', 'Previous Risk', '2024-11-30 01:31:23', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('29', '2', 'NEW_RISK', 'New Risk', '2024-11-30 01:31:23', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('30', '2', 'RISK_MODIFIED_REASON', 'Reason for Risk Modification', '2024-11-30 01:31:23', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('32', '2', 'PREVIOUS_DISCLOSURE_STATUS', 'Disclosure Previous Status', '2024-11-30 01:31:24', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('33', '2', 'NEW_DISCLOSURE_STATUS', 'Disclosure New Status', '2024-11-30 01:31:24', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('34', '2', 'DISCLOSURE_STATUS_MODIFY_REASON', 'Disclosure Status Modify Reason', '2024-11-30 01:31:24', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('35', '2', 'DISCLOSURE_STATUS_MODIFY_REASON', 'Disclosure Status Modify Reason', '2024-11-30 01:31:24', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('36', '1', 'PROJECT_TYPE', 'Disclosure Project Type', '2024-11-30 01:31:25', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('37', '2', 'DAYS_LEFT_TO_EXPIRE', 'No of Days for Disclosure Expiration', '2024-11-30 01:31:25', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('38', '1', 'FCOI_TYPE', 'FCOI Type', '2024-11-30 01:31:25', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('39', '6', 'FOREIGN_NAME', 'Entity Foreign Name', '2024-11-30 01:31:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('40', '6', 'PRIOR_NAME', 'Entity Prior Name', '2024-11-30 01:31:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('41', '6', 'SHORT_NAME', 'Entity Short Name', '2024-11-30 01:31:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('42', '6', 'DUNS_NUMBER', 'Entity Duns Name', '2024-11-30 01:31:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('43', '6', 'UEI_NUMBER', 'Entity UEI Name', '2024-11-30 01:31:27', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('44', '6', 'CAGE_NUMBER', 'Entity CAGE Name', '2024-11-30 01:31:27', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('45', '6', 'PRIMARY_ADDRESS_LINE_1', 'Primary Address Line 1', '2024-11-30 01:31:27', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('46', '6', 'PRIMARY_ADDRESS_LINE_2', 'Primary Address Line 2', '2024-11-30 01:31:28', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('47', '6', 'CITY', 'City', '2024-11-30 01:31:28', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('48', '6', 'STATE', 'State', '2024-11-30 01:31:28', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('49', '6', 'POST_CODE', 'Postal Code', '2024-11-30 01:31:28', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('50', '6', 'ENTITY_STATUS', 'Entity Status', '2024-11-30 01:31:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('51', '6', 'ENTITY_OWNERSHIP', 'Entity Ownership', '2024-11-30 01:31:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('52', '6', 'COUNTRY_NAME', 'Country Name', '2024-11-30 01:31:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('53', '9', 'ENTITY_URL', 'Entity Url', '2024-11-30 01:31:30', 'admin', '1', '/manage-entity/entity-overview?entityManageId={GLOBAL_ENTITY#ENTITY_ID}');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('54', '6', 'ENTITY_ID', 'Entity Id', '2024-11-30 01:31:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('55', '6', 'ENTITY_CREATED_BY', 'Entity Created By', '2024-11-30 01:31:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('56', '8', 'ENTITY_INACTIVATE_REASON', 'Entity Inactivation Reason', '2024-11-30 01:31:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('57', '6', 'CREATE_TIMESTAMP', 'Entity Created At', '2024-11-30 01:31:31', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('58', '2', 'REVIEWER_REVIEW_OLD_LOCATION', 'Review Previous Location', '2024-11-30 01:31:31', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('59', '2', 'OLD_REVIEWER_NAME', 'Previous Reviewer Name', '2024-11-30 01:31:31', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('60', '6', 'PRIMARY_NAME', 'Entity Primary Name', '2024-11-30 01:31:32', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('61', '2', 'DECLINE_REASON', 'Disclosure Decline Reason', '2024-11-30 01:31:32', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('62', '4', 'DEPARTMENT_NAME', 'Project Department Name', '2025-01-02 11:56:20', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('63', '4', 'DEPARTMENT_NUMBER', 'Project Department Number', '2025-01-02 11:56:20', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('64', '4', 'PROJECT_STATUS', 'Disclosure Project Status', '2025-01-02 11:56:20', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('65', '4', 'PROJECT_TYPE', 'Project Type', '2025-01-02 11:56:21', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('66', '10', 'MY_AWARDS_DASHBOARD_URL', 'My Awards Url', '2025-01-02 11:56:21', 'admin', '1', '/user-dashboard/awards');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('67', '2', 'ENGAGEMENT_NAME', 'Engagement Name', '2025-01-02 12:19:50', 'Will Smith');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('68', '12', 'ENGAGEMENT_NAME', 'Travel Engagement Name', '2025-01-08 12:26:51', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('69', '12', 'NO_OF_TRAVELS', 'No of Travels', '2025-01-08 12:26:51', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('70', '12', 'TOTAL_REIMBURSED_COST', 'Total Reimbursed Cost', '2025-01-08 12:26:51', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('81', '13', 'HOME_PAGE_URL', 'Coi Home page url', '2025-01-08 12:30:47', 'admin', '1', '/user-dashboard/disclosures');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('82', '11', 'SYNC_START_DATE_AND_TIME', 'Person Feed Starts at', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('83', '11', 'PERSON_ID', 'Person ID', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('84', '11', 'SYNC_START_DATE_AND_TIME', 'Person Feed Starts at', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('85', '11', 'SYNC_END_DATE_AND_TIME', 'Person Feed Ends at', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('86', '11', 'TOTAL_DURATION', 'Duration', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('87', '11', 'TOTAL_NO_OF_PERSONS', 'Total Users Processed', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('88', '11', 'TOTAL_NO_OF_NEW_PERSONS', 'New Persons', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('89', '11', 'TOTAL_NO_OF_UPDATED_PERSONS', 'Updated Persons', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('90', '11', 'EXCEPTION_DETAILS', 'Exception Details', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('91', '11', 'PERSON_FEED_SYNC_STATUS', 'Status', '2025-01-31 17:43:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('101', '14', 'REPORTER_NAME', 'Travel Reporter Name', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('102', '14', 'CERTIFICATION_DATE', 'Travel Certification Date', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('103', '14', 'DEPARTMENT_NUMBER', 'Department Number', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('104', '14', 'DEPARTMENT_NAME', 'Department Name', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('105', '14', 'ENTITY_NAME', 'Entity Name', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('106', '14', 'TRAVEL_START_DATE', 'Travel Start date', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('107', '14', 'TRAVEL_END_DATE', 'Travel End Date', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('108', '16', 'TRAVEL_URL', 'Travel url', '2025-02-28 17:53:26', 'admin', '1', '/travel-disclosure/summary?disclosureId={TRAVEL_DETAILS#TRAVEL_DISCLOSURE_ID}');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('109', '12', 'ADMIN_ASSIGNED_BY', 'Administrator Assigned By', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('110', '12', 'ADMIN_ASSIGNED_TO', 'Administrator Assigned To', '2025-02-28 17:53:26', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('111', '12', 'ADMINISTRATOR_NAME', 'Administrator Name', '2025-02-28 17:53:27', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('112', '12', 'WITHDRAWAL_REASON', 'Withdrawal Reason', '2025-02-28 17:53:27', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('113', '12', 'RETURN_REASON', 'Return Reason', '2025-02-28 17:53:27', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('121', '1', 'UPDATED_USER_FULL_NAME', 'Updated User full name', '2025-02-28 18:02:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('122', '1', 'UPDATE_TIMESTAMP', 'Updated Timestamp', '2025-02-28 18:02:29', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('123', '8', 'PERSON_ENTITY_ID', 'Engagement Id', '2025-02-28 18:02:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('124', '8', 'ENGAGEMENT_PERSON', 'Engagement Person Name', '2025-02-28 18:02:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('125', '8', 'PERSON_ENTITY_NUMBER', 'Engagement Number', '2025-02-28 18:02:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('126', '9', 'ENGAGEMENT_URL', 'Engagement url', '2025-02-28 18:02:30', 'admin', '1', '/entity-details/entity?personEntityId={GLOBAL_ENTITY_OTHER#PERSON_ENTITY_ID}&personEntityNumber={GLOBAL_ENTITY_OTHER#PERSON_ENTITY_NUMBER}');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('127', '6', 'PROJECT_TYPE', 'FCOI Project Type', '2025-02-28 18:02:30', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('128', '15', 'SYNC_START_DATE_AND_TIME', 'Start Date and Time', '2025-02-21 04:59:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('129', '15', 'SYNC_END_DATE_AND_TIME', 'End Date and Time', '2025-02-21 04:59:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('130', '15', 'TOTAL_DURATION', 'Duration', '2025-02-21 04:59:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('131', '15', 'TOTAL_NO_OF_TRAININGS', 'Total Count of  Person\'s Training', '2025-02-21 04:59:18', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('132', '15', 'FAILED_COUNT', 'Failed Person\'s Training Count', '2025-02-21 04:59:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('133', '15', 'EXCEPTION_DETAILS', 'Exception Details', '2025-02-21 04:59:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('134', '15', 'PERSON_FEED_SYNC_STATUS', 'Status', '2025-02-21 04:59:19', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('135', '16', 'TRAVEL_URL', 'Travel url', '2025-02-27 09:13:13', 'admin', '1', '/travel-disclosure/summary?disclosureId={TRAVEL_DETAILS#TRAVEL_DISCLOSURE_ID}');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('136', '17', 'ENG_NAME', 'Engagement Name', '2025-03-10 09:54:05', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('137', '17', 'REPORTER_NAME', 'Reporter Name', '2025-03-10 09:54:05', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('138', '17', 'ENG_REL_TYPE', 'Engagement Relationship Type', '2025-03-10 09:54:06', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('139', '17', 'DISCLOSURE_TYPE', 'Disclosure Type', '2025-03-10 09:54:06', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('140', '17', 'PERSON_ENTITY_NUMBER', 'Engagement Number', '2025-03-10 09:54:06', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('141', '17', 'PERSON_ENTITY_ID', 'Engagement Id', '2025-03-10 09:54:06', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`, `BASE_URL_ID`, `URL_PATH`) VALUES ('142', '18', 'ENGAGEMENT_URL', 'Engagement URL', '2025-03-10 09:54:07', 'admin', '1', '/entity-details/entity?personEntityId={ENG_DIS_REQ#PERSON_ENTITY_ID}&personEntityNumber={ENG_DIS_REQ#PERSON_ENTITY_NUMBER}');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('143', '1', 'CREATE_DATE', 'Disclosure Created date', '2025-03-21 12:52:42', 'admin');

INSERT INTO `notify_placeholder_columns` (`NOTIFY_PLACEHOLDER_COLUMN_ID`, `NOTIFY_PLACEHOLDER_HEADER_ID`, `QUERY_COLUMN_NAME`, `LABEL_NAME`, `UPDATE_TIMESTAMP`, `UPDATE_USER`) VALUES ('144', '1', 'DISPOSITION_STATUS', 'Disclosure Disposition Status', '2025-03-21 12:52:42', 'admin');