INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('001', '1', '1', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('002', '1', '2', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('003', '1', '3', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('004', '1', '4', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('005', '1', '5', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('006', '1', '6', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('007', '1', '7', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('008', '1', '8', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('009', '1', '9', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('014', '2', '1', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('015', '2', '2', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('016', '2', '3', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('017', '2', '4', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('018', '2', '5', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('019', '2', '6', '2025-01-01 11:39:39', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('020', '2', '7', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('021', '2', '8', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('022', '2', '9', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('027', '3', '1', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('028', '3', '2', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('029', '3', '3', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('030', '3', '4', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('031', '3', '5', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('032', '3', '6', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('033', '3', '7', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('034', '3', '8', '2025-01-01 11:39:40', 'System');

INSERT INTO `per_ent_matrix_rel_mapping` (`MAPPING_CODE`, `RELATIONSHIP_TYPE_CODE`, `MATRIX_QUESTION_ID`, `UPDATE_TIMESTAMP`, `UPDATED_BY`) VALUES ('035', '3', '9', '2025-01-01 11:39:40', 'System');