INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'In-Progress','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Sent For Review','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (3,'Completed','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (4,'Review Draft','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (5,'Review Pending','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (6,'Review In Progress','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (7,'Review Recalled','2022-07-22 07:22:37','admin','Y');
INSERT INTO ext_review_status (EXT_REVIEW_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (8,'Inactive','2025-03-21 13:36:43','admin','Y');
