INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Mathematics','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('10','Mechanical engineering','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('11','Chemical engineering','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('12','Materials engineering','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('13','Medical engineering','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('14','Environmental engineering','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('15','Environmental biotechnology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('16','Industrial Biotechnology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('17','Nano-technology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('18','Other engineering and technologies','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('19','Basic medicine','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Computer and information sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('20','Clinical medicine','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('21','Health sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('22','Health biotechnology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('23','Other medical sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('24','Agriculture, forestry, and fisheries','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('25','Animal and dairy science','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('26','Veterinary science','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('27','Agricultural biotechnology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('28','Other agricultural sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('29','Psychology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Physical sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('30','Economics and business','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('31','Educational sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('32','Sociology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('33','Law','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('34','Political Science','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('35','Social and economic geography','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('36','Media and communications','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('37','Other social sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('38','History and archaeology','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('39','Languages and literature','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Chemical sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('40','Philosophy, ethics and religion','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('41','Art (arts, history of arts, performing arts,music)','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('42','Other humanities','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Earth and related environmental sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Biological sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('7','Other natural sciences','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('8','Civil engineering','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_area (ACADEMIC_AREA_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('9','Electrical engineering, electronic 

engineering, information engineering','2022-07-22 07:22:31','admin');
