INSERT INTO ext_review_attachment_type (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (1,'Review Document','2022-07-22 07:22:37','admin');
INSERT INTO ext_review_attachment_type (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (2,'Supporting Documents','2022-07-22 07:22:37','admin');
INSERT INTO ext_review_attachment_type (ATTACHMENT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES (3,'Other Documents','2022-07-22 07:22:37','admin');
