INSERT INTO ext_reviewer_academic_rank (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Full Prof.','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_rank (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Assoc. Prof.','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_rank (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','Asst. Prof.','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_rank (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Postdoc','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_rank (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('5','Res. Sci.','2022-07-22 07:22:31','admin');
INSERT INTO ext_reviewer_academic_rank (ACADEMIC_RANK_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('6','Cent/Inst Dir.','2022-07-22 07:22:32','admin');
