INSERT INTO `assoc_relation_type_module_mapping` (`ASSOC_MAPPING_CODE`, `ASSOC_RELATION_TYPE_CODE`, `MODULE_CODE`, `UPDATE_USER`, `UPDATE_TIMESTAMP`) VALUES ('1', '1', '1', 'admin', UTC_TIMESTAMP());
INSERT INTO `assoc_relation_type_module_mapping` (`ASSOC_MAPPING_CODE`, `ASSOC_RELATION_TYPE_CODE`, `MODULE_CODE`, `UPDATE_USER`, `UPDATE_TIMESTAMP`) VALUES ('2', '2', '1', 'admin', UTC_TIMESTAMP());
INSERT INTO `assoc_relation_type_module_mapping` (`ASSOC_MAPPING_CODE`, `ASSOC_RELATION_TYPE_CODE`, `MODULE_CODE`, `UPDATE_USER`, `UPDATE_TIMESTAMP`) VALUES ('3', '3', '1', 'admin', UTC_TIMESTAMP());
INSERT INTO `assoc_relation_type_module_mapping` (`ASSOC_MAPPING_CODE`, `ASSOC_RELATION_TYPE_CODE`, `MODULE_CODE`, `UPDATE_USER`, `UPDATE_TIMESTAMP`) VALUES ('4', '4', '1', 'admin', UTC_TIMESTAMP());
