INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Award','Award','CHILD_AWARD','2025-03-21 13:37:02','admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Award','ServiceRequest','CREATED','2025-03-21 13:37:02','admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Award','Award','CHILD_AWARD','2025-03-21 13:37:02','admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Award','ACProtocol','AC_PROTOCOL_AWD','2025-03-21 13:37:02','admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Award','IRBProtocol','IRB_PROTOCOL_AWD','2025-03-21 13:37:02','admin');
