-- `FN_CHCK_BUDGET_PERIOD_DATES`; 


CREATE FUNCTION `FN_CHCK_BUDGET_PERIOD_DATES`(AV_PROPOSAL_ID VARCHAR(10)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
DECLARE LI_BUDGET_HEADER_ID int(11);
DECLARE LD_START_DATE DATETIME;
DECLARE LD_END_DATE DATETIME;
	SELECT COUNT(*) INTO LI_FLAG
	FROM budget_header t1
	where t1.PROPOSAL_ID = AV_PROPOSAL_ID
	and IS_FINAL_BUDGET = 'Y';
IF LI_FLAG = 0 THEN 
	SELECT COUNT(*) INTO LI_FLAG
	FROM budget_header t1
	where t1.PROPOSAL_ID = AV_PROPOSAL_ID
	and VERSION_NUMBER = (select max(s1.VERSION_NUMBER) 
					 from budget_header s1 
                     where s1.PROPOSAL_ID = t1.PROPOSAL_ID);
		IF LI_FLAG > 0 THEN 	 
			SELECT t1.BUDGET_HEADER_ID,T2.START_DATE,T2.END_DATE 
			INTO LI_BUDGET_HEADER_ID,LD_START_DATE,LD_END_DATE
			FROM budget_header t1
			INNER JOIN EPS_PROPOSAL T2 ON T2.PROPOSAL_ID = t1.PROPOSAL_ID
			where t1.PROPOSAL_ID = AV_PROPOSAL_ID
			and VERSION_NUMBER = (select max(s1.VERSION_NUMBER) 
							 from budget_header s1 
							 where s1.PROPOSAL_ID = t1.PROPOSAL_ID);
		ELSE
			RETURN 'FALSE';
		END IF;
 ELSE IF LI_FLAG > 0 THEN 
		SELECT t1.BUDGET_HEADER_ID,T2.START_DATE,T2.END_DATE 
		INTO LI_BUDGET_HEADER_ID,LD_START_DATE,LD_END_DATE
		FROM budget_header t1
		INNER JOIN EPS_PROPOSAL T2 ON T2.PROPOSAL_ID = t1.PROPOSAL_ID
		where t1.PROPOSAL_ID = AV_PROPOSAL_ID
		and IS_FINAL_BUDGET = 'Y';
else
	RETURN 'FALSE';
END IF;
END IF;
SELECT COUNT(*) INTO LI_FLAG
FROM budget_period t1
where t1.BUDGET_HEADER_ID = LI_BUDGET_HEADER_ID
and (date(t1.START_DATE) < date(LD_START_DATE)
or date(t1.END_DATE) > date(LD_END_DATE));
IF LI_FLAG > 0 THEN 
 RETURN 'TRUE';
 ELSE 
	RETURN 'FALSE';
END IF;
END
