-- `FN_CHK_PROP_ORGANIZATION`; 

CREATE FUNCTION `FN_CHK_PROP_ORGANIZATION`(AV_PROPOSAL_ID VARCHAR(6)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT(3);
SELECT COUNT(*) INTO LI_COUNT 
FROM EPS_PROPOSAL_ORGANIZATION 
WHERE PROPOSAL_ID = AV_PROPOSAL_ID
AND ORGANIZATION_TYPE_CODE IN(1,2);
IF LI_COUNT > 1 THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
END IF;
END
