-- `FN_KEY_PERSON_EFFORT_NULL_CHK`; 

CREATE FUNCTION `FN_KEY_PERSON_EFFORT_NULL_CHK`(
AV_PROPOSAL_ID   int(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT int;
SELECT COUNT(1) INTO  LI_COUNT FROM eps_proposal_persons WHERE PROPOSAL_ID = AV_PROPOSAL_ID AND PERCENTAGE_OF_EFFORT IS NULL;
IF LI_COUNT > 0 THEN
   RETURN 'FALSE';
END IF;
RETURN 'TRUE';
END
