CREATE PROCEDURE `CREATE_AGREEMENT`(
	JSON_FORMAT JSON,
    AV_FILE_NAME VARCHAR(255),
    AV_EMAIL VARCHAR(60)
)
BEGIN
DECLARE LS_ERROR_MSG		VARCHAR(1000);
DECLARE LD_CURRENT_DATE 	DATE;
DECLARE LI_AGREEMENT_ID		INT;
DECLARE LI_IPN_COUNT   		INT;
DECLARE LS_IPN_NUMBER 		VARCHAR(20);
DECLARE LI_PROPOSAL_ID 		INT;
DECLARE LS_AWARD_TYPE 		VARCHAR(3);
DECLARE LS_SPONSOR_CODE		VARCHAR(6);
DECLARE LI_NEGOTIATION_ID  	INT;
DECLARE LI_CUST_DATA_ELEMENTS_ID INT;
DECLARE LI_CUST_DATA_OPT_ID INT;

DECLARE LS_TITLE_JSON       VARCHAR(200);
DECLARE LD_START_DATE		DATETIME;
DECLARE LD_END_DATE			DATETIME;
DECLARE LS_PERIOD			VARCHAR(30);
DECLARE LS_UNIT_NUMBER		VARCHAR(50);
DECLARE LS_UNIT_NAME 		VARCHAR(255);
DECLARE LS_PERSON_NAME		VARCHAR(90);
DECLARE LS_DONE 			INT DEFAULT FALSE;
DECLARE LS_PERSON_ID 		VARCHAR(40);
DECLARE LI_ROLE_ID 			INT;
DECLARE LS_ERROR_FLAG 		VARCHAR(1) DEFAULT 'N';
DECLARE LS_MESSAGE 			VARCHAR(100);
DECLARE LS_RECIPIENT_ID 	VARCHAR(40);
DECLARE LI_MODULE_CODE		INT DEFAULT 13;		-- agreement
    
 DECLARE AGMT_ROLE_CUR CURSOR FOR
    WITH DERIVED_ROLE AS
    (
    SELECT ROLE_ID, 3 AS ROLE_TYPE FROM MODULE_DERIVED_ROLES WHERE MODULE_CODE = LI_MODULE_CODE AND IS_ACTIVE = 'Y' AND AUTO_GRANT_TO_PI = 'Y'
    UNION
    SELECT ROLE_ID, 1 AS ROLE_TYPE FROM MODULE_DERIVED_ROLES WHERE MODULE_CODE = LI_MODULE_CODE AND IS_ACTIVE = 'Y' AND AUTO_GRANT_TO_COI = 'Y'
    )
    SELECT  PP.PERSON_ID, MDR.ROLE_ID AS ROLE_ID FROM PROPOSAL_PERSONS PP
    INNER JOIN DERIVED_ROLE MDR ON MDR.ROLE_TYPE = PP.PROP_PERSON_ROLE_ID
    WHERE PERSON_ID IS NOT NULL AND PP.PROP_PERSON_ROLE_ID in (3, 1) AND PP.PROPOSAL_ID = LI_PROPOSAL_ID;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET LS_DONE = TRUE;

BEGIN

			DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
			BEGIN
			
				GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
				 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
				 
				SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
				
				SELECT @full_error INTO LS_ERROR_MSG;
																
				INSERT INTO EXCEPTION_LOG (`ERROR_CODE`,`MESSAGE`,`API_REQUEST`,`METHOD`,`REQUEST_BODY`,`DEBUG_MESSSAGE`,`STACKTRACE`,`REQUESTER_PERSON`,`CREATE_TIMESTAMP`,`CREATE_USER`) 
				VALUES ('ERR','Exception while creating automated agreement','CREATE_AGREEMENT PROC','POST','','','','',UTC_TIMESTAMP(),'admin');
				COMMIT;
				
			END;



IF AV_FILE_NAME IS NOT NULL THEN
	SET LS_IPN_NUMBER = AV_FILE_NAME;
	SELECT COUNT(1) INTO LI_IPN_COUNT FROM PROPOSAL WHERE PROPOSAL_NUMBER = LS_IPN_NUMBER AND PROPOSAL_SEQUENCE_STATUS = 'ACTIVE';

	IF LI_IPN_COUNT > 0 THEN

		SELECT PROPOSAL_ID, AWARD_TYPE_CODE, SPONSOR_CODE,HOME_UNIT_NAME, HOME_UNIT_NUMBER INTO LI_PROPOSAL_ID, LS_AWARD_TYPE, LS_SPONSOR_CODE, LS_UNIT_NAME, LS_UNIT_NUMBER
        FROM PROPOSAL WHERE PROPOSAL_NUMBER = LS_IPN_NUMBER AND PROPOSAL_SEQUENCE_STATUS = 'ACTIVE';
		
		SET LS_TITLE_JSON = JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT, '$."RESEARCH TITLE ANDOR DESCRIPTION OF PROJECT ANDOR PROPOSAL TITLE"'));
		SET LS_PERIOD := JSON_UNQUOTE(JSON_EXTRACT(JSON_FORMAT, '$."PERIOD OF PERFORMANCE"'));
	
		SET LD_START_DATE = STR_TO_DATE(SUBSTRING_INDEX(LS_PERIOD, ' ', 1), '%m/%d/%Y');
		SET LD_END_DATE   = STR_TO_DATE(SUBSTRING_INDEX(LS_PERIOD, ' ', -1), '%m/%d/%Y');

		IF LS_TITLE_JSON IS NOT NULL AND LS_TITLE_JSON != '' THEN
			SET LS_TITLE_JSON = CONCAT('(Automated) ', LS_TITLE_JSON);
		END IF;


		SELECT CURDATE() INTO LD_CURRENT_DATE;

		-- START,END DATES
		IF LD_START_DATE IS NULL AND LD_END_DATE IS NULL THEN
			SET LD_START_DATE = LD_CURRENT_DATE, LD_END_DATE = LD_CURRENT_DATE;
		ELSEIF LD_START_DATE IS NULL THEN
			SET LD_START_DATE = LD_CURRENT_DATE;
		ELSEIF LD_END_DATE IS NULL THEN
			SET LD_END_DATE = LD_START_DATE;
		END IF;

  	-- Default user = 10000000001

		INSERT INTO AGREEMENT_HEADER (`TITLE`,`DOCUMENT_TYPE_CODE`,`AGREEMENT_TYPE_CODE`,`AGREEMENT_STATUS_CODE`, `REQUESTOR_PERSON_ID`, `REQUESTOR_NAME`,
			`UPDATE_TIMESTAMP`,`UPDATE_USER`,`START_DATE`,`END_DATE`,`AMOUNT_IN_WORDS`,`CATEGORY_CODE`, `CONTRACT_VALUE`,`CREATE_TIMESTAMP`,
            `CREATE_USER`,`CURRENCY_CODE`, `REMARKS`,`SUBMIT_USER`,`UNIT_NAME`,`UNIT_NUMBER`, `REVIEW_STATUS_CODE`,`ADMIN_PERSON_ID`, `ADMIN_ASSIGN_DATE`,
            `ADMIN_GROUP_ID`,`ADMIN_PERSON_NAME`,`AGREEMENT_SEQUENCE_STATUS`, `SUBMIT_USER_ID`,`IS_HOLD`) 
		VALUES (LS_TITLE_JSON, NULL, LS_AWARD_TYPE, '1', '10000000001', (SELECT FULL_NAME FROM PERSON WHERE PERSON_ID ='10000000001'), 
			UTC_TIMESTAMP(), 'admin', LD_START_DATE, LD_END_DATE, NULL, '1', '0.00', UTC_TIMESTAMP(),
            'admin', NULL, NULL, NULL, LS_UNIT_NAME, LS_UNIT_NUMBER, NULL, NULL, NULL,
             NULL, NULL, 'ACTIVE', NULL, 'N');
	
		SELECT LAST_INSERT_ID() INTO LI_AGREEMENT_ID FROM AGREEMENT_HEADER;

		INSERT INTO AGREEMENT_ACTION_LOG (`ACTION_TYPE_CODE`,`DESCRIPTION`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`AGREEMENT_REQUEST_ID`) 
        VALUES ('1','Agreement has been created',UTC_TIMESTAMP(),'admin', LI_AGREEMENT_ID);

        INSERT INTO ACTIVITY_DURATION_TRACKER (`MODULE_CODE`,`SECTION_CODE`,`MODULE_ITEM_KEY`,`MODULE_ITEM_ID`,`SECTION_ITEM_ID`,`FIELD`,`VALUE_STRING`,`VALUE_ID`,
			`MESSAGE`,`START_TIME`,`END_TIME`,`DURATION`,`START_PERSON_ID`,`END_PERSON_ID`,`IS_HOLD`,`ASSIGNEE_PERSON_ID`,`ASSIGNEE_GROUP`,`PARENT_ADT_ID`) 
		VALUES (LI_MODULE_CODE, NULL, NULL, LI_AGREEMENT_ID, NULL, 'status', 'In Progress', '1',
			NULL, UTC_TIMESTAMP(), NULL, NULL, '10000000001', NULL, 'N', NULL, NULL, NULL);

		INSERT INTO NEGOTIATION (`NEGOTIATION_STATUS_CODE`,`WORKFLOW_STATUS_CODE`,`AGREEMENT_TYPE_CODE`,`NEGOTIATOR_PERSON_ID`,`NEGOTIATOR_FULL_NAME`,
			`START_DATE`,`END_DATE`,`FINAL_CONTRACT_DOCUMENT`,`SUMMARY_COMMENT`,`NEGOTIATOR_COMMENT`,`LEGAL_COMMENT`,`CREATE_TIMESTAMP`,`CREATE_USER`,`UPDATE_TIMESTAMP`,
			`UPDATE_USER`,`ASSOCIATED_PROJECT_ID`,`TITLE`,`SUBMIT_USER`,`SUBMISSION_DATE`,`TOTAL_BUDGET_AMOUNT`,`TOTAL_FUND_REQUESTED`) 
        VALUES (NULL, '1', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.00, NULL);

		SELECT LAST_INSERT_ID() INTO LI_NEGOTIATION_ID FROM NEGOTIATION;
        
		INSERT INTO NEGOTIATION_ASSOCIATION(`NEGOTIATION_ID`,`ASSOCIATION_TYPE_CODE`,`ASSOCIATED_PROJECT_ID`,`UPDATE_TIMESTAMP`,`UPDATE_USER`) 
		VALUES (LI_NEGOTIATION_ID, '4', LI_AGREEMENT_ID, UTC_TIMESTAMP(), 'admin');

		/* project association starts */
			INSERT INTO ASSOC_AGREEMENT (`AGREEMENT_ID`,`ASSOC_RELATION_TYPE_CODE`,`ASSOC_CONFIG_CODE`,`MODULE_CODE`,`MODULE_ITEM_KEY`,`MODULE_ITEM_ID`,`ASSOC_TYPE`,`UPDATE_USER`,`UPDATE_TIMESTAMP`,`IS_IMPORTED`) 
			VALUES (LI_AGREEMENT_ID, '4' ,'5' ,2, LS_IPN_NUMBER, LI_PROPOSAL_ID, 'DIRECT', 'admin', UTC_TIMESTAMP(), 'Y');
		  /* project association ends */
	  
		/* Financial details insertion starts */
			INSERT INTO AGREEMENT_FINANCIAL_DETAIL (
				AGREEMENT_REQUEST_ID, 
				PROJECT_START_DATE, 
				PROJECT_END_DATE,
				FA_RATE_TYPE_CODE, 
				FA_RATE_CLASS_CODE,
				FA_RATE,
				LOCATION, 
				COST_SHARE,
				OBLIGATED_AMOUNT, 
				ANTICIPATED_AMOUNT, 
				DESCRIPTION, 
				UPDATE_TIMESTAMP, 
				UPDATE_USER
			)
			SELECT 
				LI_AGREEMENT_ID,
				DATE(T1.START_DATE) AS START_DATE,
				DATE(T1.END_DATE) AS END_DATE,
				T3.RATE_TYPE_CODE,
				T3.RATE_CLASS_CODE,
				 CASE 
					WHEN T3.ON_OFF_CAMPUS_FLAG = 'N' THEN T3.ON_CAMPUS_RATES
					WHEN T3.ON_OFF_CAMPUS_FLAG = 'F' THEN T3.OFF_CAMPUS_RATES
					WHEN T3.ON_OFF_CAMPUS_FLAG = 'D' THEN T3.OFF_CAMPUS_RATES + T3.ON_CAMPUS_RATES
				END AS CAMPUS_RATES,
				T3.ON_OFF_CAMPUS_FLAG AS DESCRIPTION,
				IFNULL(T3.COST_SHARING_AMOUNT, 0.00) AS COST_SHARE,
				IFNULL(T3.TOTAL_COST, 0.00) AS OBLIGATED_AMOUNT,
				IFNULL(T3.TOTAL_COST, 0.00) AS ANTICIPATED_AMOUNT,
				null,
				UTC_TIMESTAMP(),
				'admin'
			FROM PROPOSAL T1
			LEFT JOIN (
				SELECT 
					S3.PROPOSAL_ID,
					S3.TOTAL_COST,
					S3.TOTAL_DIRECT_COST,
					S3.TOTAL_INDIRECT_COST,
					S3.RATE_CLASS_CODE,
					S3.RATE_TYPE_CODE,
					S3.ON_OFF_CAMPUS_FLAG,
					S3.COST_SHARING_AMOUNT,
					S3.ON_CAMPUS_RATES,
					S3.OFF_CAMPUS_RATES
				FROM IP_BUDGET_HEADER S3
				WHERE S3.VERSION_NUMBER = (
					SELECT MAX(S4.VERSION_NUMBER) 
					FROM IP_BUDGET_HEADER S4
					WHERE S3.PROPOSAL_ID = S4.PROPOSAL_ID
				)
			) T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID
			LEFT JOIN RATE_TYPE T4 ON T3.RATE_TYPE_CODE = T4.RATE_TYPE_CODE
				AND T3.RATE_CLASS_CODE = T4.RATE_CLASS_CODE
			WHERE T1.PROPOSAL_ID = LI_PROPOSAL_ID;

		/* Financial details insertion ends */

			INSERT INTO AGREEMENT_SPONSOR (
					AGREEMENT_REQUEST_ID, SPONSOR_NAME, SPONSOR_CODE, UPDATE_TIMESTAMP, SPONSOR_ROLE_TYPE_CODE, AGREEMENT_SPONSOR_TYPE_CODE, UPDATE_USER
				) SELECT
					LI_AGREEMENT_ID, DISPLAY_NAME, SPONSOR_CODE, UTC_TIMESTAMP(), 1, 1, 'admin'
					FROM SPONSOR WHERE SPONSOR_CODE = LS_SPONSOR_CODE;

			SELECT CUSTOM_DATA_ELEMENTS_ID INTO LI_CUST_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS WHERE COLUMN_LABEL = 'Action Type' AND IS_ACTIVE = 'Y';
			SELECT CUSTOM_DATA_OPTION_ID INTO LI_CUST_DATA_OPT_ID FROM CUSTOM_DATA_ELEMENTS_OPTIONS WHERE OPTION_NAME = 'New';

			IF LI_CUST_DATA_ELEMENTS_ID IS NOT NULL AND LI_CUST_DATA_OPT_ID IS NOT NULL THEN         
				INSERT INTO CUSTOM_DATA (`CUSTOM_DATA_ELEMENTS_ID`,`MODULE_ITEM_CODE`,`MODULE_ITEM_KEY`,`MODULE_SUB_ITEM_CODE`,`MODULE_SUB_ITEM_KEY`,`UPDATE_TIMESTAMP`,`UPDATE_USER`,`VALUE`,`DESCRIPTION`)
				VALUES (LI_CUST_DATA_ELEMENTS_ID, LI_MODULE_CODE, LI_AGREEMENT_ID, 0, '0', UTC_TIMESTAMP(), 'admin', LI_CUST_DATA_OPT_ID ,'New');
			END IF;
           
           /*Agreement people section starts*/
           
	IF NOT EXISTS (SELECT 1 FROM AGREEMENT_PEOPLE WHERE PEOPLE_TYPE_ID IN (3, 17) AND AGREEMENT_REQUEST_ID = LI_AGREEMENT_ID) THEN
        INSERT INTO AGREEMENT_PEOPLE(
            AGREEMENT_REQUEST_ID,
            PERSON_ID,
            ROLODEX_ID,
            FULL_NAME,
            PEOPLE_TYPE_ID,
            UPDATE_TIMESTAMP,
            UPDATE_USER
        ) 
			SELECT
            LI_AGREEMENT_ID,
            PERSON_ID,
            ROLODEX_ID,
            FULL_NAME,
			IF(PROP_PERSON_ROLE_ID = 1, 17, PROP_PERSON_ROLE_ID),
            UTC_TIMESTAMP(),
            'admin'
            FROM PROPOSAL_PERSONS WHERE
            PROPOSAL_ID = LI_PROPOSAL_ID AND PROP_PERSON_ROLE_ID IN (1, 3);
    END IF;

	OPEN AGMT_ROLE_CUR;

		ROLE_LOOP: LOOP
			FETCH AGMT_ROLE_CUR INTO LS_PERSON_ID, LI_ROLE_ID;
		IF LS_DONE THEN
			LEAVE ROLE_LOOP;
		END IF;
        
        IF NOT EXISTS (SELECT 1 FROM AGREEMENT_PEOPLE_ROLES WHERE ROLE_ID = LI_ROLE_ID AND PERSON_ID = LS_PERSON_ID AND AGREEMENT_REQUEST_ID = LI_AGREEMENT_ID) THEN

            INSERT INTO AGREEMENT_PEOPLE_ROLES(
            AGREEMENT_REQUEST_ID,
			IS_SYSTEM_DERIVED_ROLE,
			PERSON_ID,
			ROLE_ID,
			UPDATE_TIMESTAMP,
			UPDATE_USER)
            VALUES 
			(LI_AGREEMENT_ID,
			'Y',
			LS_PERSON_ID,
			LI_ROLE_ID,
			UTC_TIMESTAMP(),
			'admin');

        END IF;

		END LOOP;
	CLOSE AGMT_ROLE_CUR;
           /*Agreement people section ends*/
	END IF;
END IF;

	IF AV_EMAIL IS NOT NULL THEN
		SELECT PERSON_ID INTO LS_RECIPIENT_ID FROM PERSON WHERE EMAIL_ADDRESS = AV_EMAIL;
	END IF;

	IF AV_FILE_NAME IS NOT NULL AND LI_IPN_COUNT = 0 THEN
		SET LS_ERROR_FLAG = 'Y';
		SET LS_MESSAGE = 'IPN Number is not found.';
	END IF;
    
    SELECT LI_AGREEMENT_ID AS MODULE_ITEM_ID, NULL AS MODULE_ITEM_KEY, LI_MODULE_CODE AS MODULE_CODE, LS_RECIPIENT_ID, LS_ERROR_FLAG, LS_MESSAGE;
END;
END
