-- `FN_CHCK_AWARD_TASK_TYPE_1`; 


CREATE FUNCTION `FN_CHCK_AWARD_TASK_TYPE_1`( 
AV_TASK_ID    varchar(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_TASK_TYPE_CODE INT;
select TASK_TYPE_CODE INTO LI_TASK_TYPE_CODE
FROM TASK 
where TASK_ID = AV_TASK_ID;
IF LI_TASK_TYPE_CODE = 1 THEN
    RETURN 'TRUE';
else
    RETURN 'FALSE';
END IF;
END
