-- `FN_CHK_AWARD_REVIEWERS`; 


CREATE FUNCTION `FN_CHK_AWARD_REVIEWERS`( 
AV_AWARD_ID    varchar(22)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_REVIEWER_STATUS_C INT;
DECLARE LI_REVIEWER_COUNT INT;
	SELECT COUNT(1) INTO LI_REVIEWER_COUNT FROM PRE_REVIEW 
	WHERE MODULE_ITEM_CODE = 1
	AND MODULE_SUB_ITEM_CODE = 0
	AND MODULE_ITEM_KEY = AV_AWARD_ID;
    IF LI_REVIEWER_COUNT = 0 THEN
		RETURN 'TRUE';
    END IF;
	SELECT COUNT(1) INTO LI_REVIEWER_STATUS_C 
	FROM PRE_REVIEW 
	WHERE MODULE_ITEM_CODE = 1
	AND MODULE_SUB_ITEM_CODE = 0
	AND MODULE_ITEM_KEY = AV_AWARD_ID
	AND PRE_REVIEW_STATUS_CODE = 2;
	IF LI_REVIEWER_COUNT =  LI_REVIEWER_STATUS_C THEN
		RETURN 'TRUE';
	END IF;
	RETURN 'FALSE';
END
