-- `FN_CHK_AWARD_QNR_COMPLETE`; 


CREATE FUNCTION `FN_CHK_AWARD_QNR_COMPLETE`(
AV_AWARD_ID    int(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
	DECLARE LI_FLAG INT;
	DECLARE LI_COUNT INT(3);
	SELECT COUNT(*) INTO LI_COUNT 
	FROM AWARD 
	WHERE AWARD_ID = AV_AWARD_ID
	AND AWARD_DOCUMENT_TYPE_CODE = 1; 
	IF LI_COUNT = 0 THEN  
		RETURN 'TRUE';
	END IF;
	select COUNT(1) INTO LI_FLAG from QUEST_ANSWER_HEADER
	where MODULE_ITEM_CODE = 1 
	AND MODULE_SUB_ITEM_CODE = 0
	and MODULE_ITEM_KEY = AV_AWARD_ID;
	IF LI_FLAG = 0 THEN 
		RETURN 'FALSE';
	END IF;
	select COUNT(1) INTO LI_FLAG from QUEST_ANSWER_HEADER
	where MODULE_ITEM_CODE = 1 
	AND MODULE_SUB_ITEM_CODE = 0
	and MODULE_ITEM_KEY = AV_AWARD_ID
	and QUESTIONNAIRE_COMPLETED_FLAG = 'N'
	AND QUESTIONNAIRE_ID IN (SELECT QUESTIONNAIRE_ID FROM QUEST_USAGE
							WHERE MODULE_ITEM_CODE = 1
							AND MODULE_SUB_ITEM_CODE = 0
							AND IS_MANDATORY = 'Y');
	IF LI_FLAG > 0 THEN
		RETURN 'FALSE';
	END IF;
	RETURN 'TRUE';
END
