-- `FN_CHECK_SDC_GM`; 


CREATE FUNCTION `FN_CHECK_SDC_GM`(
AV_AWARD_ID 			VARCHAR(22),
AV_LOGGIN_PERSON_ID		VARCHAR(40)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT(3);
DECLARE LS_GRANT_CALL_LEAD_UNIT VARCHAR(8);
DECLARE LS_AWARD_LEAD_UNIT			VARCHAR(8);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_AWARD_ID VARCHAR(22);
SELECT COUNT(*) INTO LI_COUNT
FROM AWARD
WHERE AWARD_ID = AV_AWARD_ID
AND AWARD_DOCUMENT_TYPE_CODE = 3; 
IF LI_COUNT = 0 THEN 
	RETURN 'TRUE';
END IF;
	SELECT AWARD_NUMBER INTO LS_AWARD_NUMBER FROM AWARD
	WHERE AWARD_ID = AV_AWARD_ID; 
	SELECT LEAD_UNIT_NUMBER,AWARD_ID INTO LS_AWARD_LEAD_UNIT, LS_AWARD_ID FROM AWARD
	WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
	IF LS_LEAD_UNIT_NUMBER IS NOT NULL THEN
		SET AV_AWARD_ID = LS_AWARD_ID;
	ELSE 
		SELECT LEAD_UNIT_NUMBER INTO LS_AWARD_LEAD_UNIT 
		FROM AWARD
		WHERE AWARD_ID = AV_AWARD_ID;
	END IF;
SELECT COUNT(1) INTO LI_COUNT
FROM PERSON_ROLES T1 
WHERE T1.PERSON_ID = AV_LOGGIN_PERSON_ID
AND T1.ROLE_ID = 28
AND T1.UNIT_NUMBER = LS_AWARD_LEAD_UNIT;
IF LI_COUNT > 0 THEN
	RETURN 'TRUE';
END IF;
SELECT COUNT(1) INTO LI_COUNT FROM AWARD T1
WHERE T1.AWARD_ID = AV_AWARD_ID
AND T1.GRANT_HEADER_ID IS NOT NULL;
IF LI_COUNT > 0 THEN
	SELECT T2.HOME_UNIT_NUMBER INTO LS_GRANT_CALL_LEAD_UNIT 
	FROM AWARD T1
	INNER JOIN GRANT_CALL_HEADER T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
	WHERE T1.AWARD_ID = AV_AWARD_ID;
	SELECT COUNT(1) INTO LI_COUNT
	FROM PERSON_ROLES T1 
	WHERE PERSON_ID = AV_LOGGIN_PERSON_ID
	AND T1.ROLE_ID = 100
	AND T1.UNIT_NUMBER = LS_GRANT_CALL_LEAD_UNIT;
	IF LI_COUNT > 0 THEN
		RETURN 'TRUE';
	END IF;
END IF;
RETURN 'FALSE';
END
