-- `FN_CALC_UNCOMMITTED_AMNT_FOR_WBS`; 


CREATE FUNCTION `FN_CALC_UNCOMMITTED_AMNT_FOR_WBS`(
	AV_WBS_NUMBER		VARCHAR(30),
    AV_AWARD_ID		VARCHAR(10),
    AV_MANPOWER_TYPE_CODE	VARCHAR(3),
	AV_BUDGET_INCLUDED 		 BOOLEAN,
	AV_MANPOWER_WD_RESOURCE_ID INTEGER
) RETURNS decimal(15,2)
    DETERMINISTIC
BEGIN
	DECLARE LS_BUDGET_AMOUNT DECIMAL(15,2);
    DECLARE LS_MANPOWER_SALARY_SUM DECIMAL(15,2);
    DECLARE LS_ADJUSTED_COMMITTED_COST DECIMAL(15,2);
    DECLARE LS_COMMITTED_COST DECIMAL(15,2);
    
    SET LS_BUDGET_AMOUNT = 0;
	SET LS_MANPOWER_SALARY_SUM = 0;
	SET LS_ADJUSTED_COMMITTED_COST = 0;
	SET LS_COMMITTED_COST = 0;
	IF AV_MANPOWER_TYPE_CODE = '1' THEN
		
        SELECT IFNULL(SUM(T1.PLANNED_SALARY), 0) INTO LS_MANPOWER_SALARY_SUM FROM AWARD_MANPOWER_RESOURCE T1
		INNER JOIN AWARD_MANPOWER T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID 
		LEFT OUTER JOIN WORKDAY_POSITION_REQUISITION T3 ON T1.POSITION_ID = T3.POSITION_ID
		WHERE T2.AWARD_ID = AV_AWARD_ID AND T2.BUDGET_REFERENCE_NUMBER = AV_WBS_NUMBER AND 
		(T1.POSITION_ID IS NULL || T3.JOB_REQUISITION_STATUS IS NULL || T3.JOB_REQUISITION_STATUS NOT IN ('Filled', 'Closed', 'Frozen'));
	
    ELSEIF AV_MANPOWER_TYPE_CODE = '2' THEN 
		
        SELECT IFNULL(SUM(T1.COMMITTED_COST), 0) INTO LS_MANPOWER_SALARY_SUM FROM AWARD_MANPOWER_RESOURCE T1
		INNER JOIN AWARD_MANPOWER T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID 
		WHERE T2.AWARD_ID = AV_AWARD_ID AND T2.BUDGET_REFERENCE_NUMBER = AV_WBS_NUMBER;
        
	END IF;
	IF AV_MANPOWER_WD_RESOURCE_ID IS NOT NULL THEN
	SELECT IFNULL(SUM(COMMITTED_COST), 0) INTO LS_COMMITTED_COST FROM MANPOWER_WORKDAY_RESOURCE WHERE WBS_NUMBER = AV_WBS_NUMBER AND ADJUSTED_COMMITTED_COST IS NULL AND MANPOWER_WORKDAY_RESOURCE_ID <> AV_MANPOWER_WD_RESOURCE_ID;
    SELECT IFNULL(SUM(ADJUSTED_COMMITTED_COST), 0) INTO LS_ADJUSTED_COMMITTED_COST FROM MANPOWER_WORKDAY_RESOURCE WHERE WBS_NUMBER = AV_WBS_NUMBER AND ADJUSTED_COMMITTED_COST IS NOT NULL AND MANPOWER_WORKDAY_RESOURCE_ID <> AV_MANPOWER_WD_RESOURCE_ID;
	ELSE
	SELECT IFNULL(SUM(COMMITTED_COST), 0) INTO LS_COMMITTED_COST FROM MANPOWER_WORKDAY_RESOURCE WHERE WBS_NUMBER = AV_WBS_NUMBER AND ADJUSTED_COMMITTED_COST IS NULL;
    SELECT IFNULL(SUM(ADJUSTED_COMMITTED_COST), 0) INTO LS_ADJUSTED_COMMITTED_COST FROM MANPOWER_WORKDAY_RESOURCE WHERE WBS_NUMBER = AV_WBS_NUMBER AND ADJUSTED_COMMITTED_COST IS NOT NULL;
	END IF;
   
   IF (AV_BUDGET_INCLUDED = TRUE) THEN
		SELECT LINE_ITEM_COST INTO LS_BUDGET_AMOUNT FROM AWARD_BUDGET_DETAIL 
		WHERE BUDGET_HEADER_ID = (SELECT MAX(BUDGET_HEADER_ID) FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = AV_AWARD_ID) 
		AND (INTERNAL_ORDER_CODE = AV_WBS_NUMBER || BUDGET_DETAILS_ID = AV_WBS_NUMBER);
	RETURN LS_BUDGET_AMOUNT - (LS_MANPOWER_SALARY_SUM + LS_COMMITTED_COST + LS_ADJUSTED_COMMITTED_COST);
	ELSE
	RETURN LS_MANPOWER_SALARY_SUM + LS_COMMITTED_COST + LS_ADJUSTED_COMMITTED_COST;
   END IF;
   END
