-- `FN_CHK_DIRECT_CLAIM_AMNT`; 


CREATE FUNCTION `FN_CHK_DIRECT_CLAIM_AMNT`(AV_CLAIM_ID VARCHAR(6)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_LATEST_BUD_AMNT DECIMAL(15,2);
DECLARE LI_AWARD_ID INT;
DECLARE LI_COUNT INT DEFAULT 0;
BEGIN
				
				SELECT AWARD_ID INTO LI_AWARD_ID FROM CLAIM WHERE CLAIM_ID = AV_CLAIM_ID AND CLAIM_NUMBER LIKE 'D%';
				IF LI_AWARD_ID IS NOT NULL THEN
					SELECT
  					SUM(A3.LINE_ITEM_COST) INTO LI_LATEST_BUD_AMNT
					FROM AWARD_BUDGET_HEADER A2 				
					INNER JOIN AWARD_BUDGET_DETAIL A3 ON A2.BUDGET_HEADER_ID = A3.BUDGET_HEADER_ID
					WHERE A2.AWARD_ID = LI_AWARD_ID
					AND A3.BUDGET_CATEGORY_CODE NOT IN ('IRC','GRT','COM','TSF','IPP')
					AND A2.VERSION_NUMBER IN (SELECT MAX(AB1.VERSION_NUMBER) FROM AWARD_BUDGET_HEADER AB1 
												WHERE AB1.AWARD_ID = LI_AWARD_ID);
					
					IF LI_LATEST_BUD_AMNT IS NOT NULL THEN
					SELECT COUNT(1) INTO LI_COUNT FROM CLAIM WHERE TOTAL_AMOUNT <= LI_LATEST_BUD_AMNT AND CLAIM_ID = AV_CLAIM_ID;
					END IF;
				else
					RETURN 'TRUE'; 
				END IF;
				
                
IF LI_COUNT > 0 THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
END IF;
			
END;
END
