-- `FN_FOR_WBS_VALIDATION`; 


CREATE FUNCTION `FN_FOR_WBS_VALIDATION`(AV_AWARD_ID  VARCHAR(22)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT;
DECLARE LS_NEW_ACCOUNT_NUMBER VARCHAR(40);
DECLARE LS_CURR_ACCOUNT_NUMBER VARCHAR(40);
DECLARE LS_ACCOUNT_NUMBER VARCHAR(40);
DECLARE LS_SPONSOR_TYPE_CODE 			VARCHAR(3);
DECLARE LS_INPUT_GST_CATEGORY 			VARCHAR(30);
DECLARE LS_WBS_CODE						VARCHAR(1);
DECLARE LS_LEAD_UNIT_NUMBER 			VARCHAR(8); 
DECLARE LS_BA_CODE 						VARCHAR(4);
SELECT COUNT(*) INTO LI_COUNT
FROM AWARD 
WHERE AWARD_ID = AV_AWARD_ID
AND (ACCOUNT_NUMBER IS NULL OR ACCOUNT_NUMBER = '');
IF LI_COUNT <> 0 THEN
	RETURN 'TRUE';
END IF;
SELECT ACCOUNT_NUMBER INTO LS_ACCOUNT_NUMBER
FROM AWARD 
WHERE AWARD_ID = AV_AWARD_ID;
SELECT SPONSOR_TYPE_CODE INTO  LS_SPONSOR_TYPE_CODE
FROM SPONSOR WHERE SPONSOR_CODE = (
SELECT SPONSOR_CODE FROM AWARD WHERE AWARD_ID = AV_AWARD_ID);
SELECT VALUE INTO LS_INPUT_GST_CATEGORY
 FROM CUSTOM_DATA 
WHERE  MODULE_ITEM_CODE = 1 
AND MODULE_SUB_ITEM_CODE = 0 
AND MODULE_ITEM_KEY = AV_AWARD_ID
AND MODULE_SUB_ITEM_KEY =0
AND CUSTOM_DATA_ELEMENTS_ID  in (
					SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS WHERE CUSTOM_ELEMENT_NAME = 'Input GST Category'
				   );
 SELECT WBS_CODE INTO LS_WBS_CODE
 FROM WBS_GEN_INPUT_GST_MAPPING WHERE GST_CATEGORY = LS_INPUT_GST_CATEGORY;
 SELECT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER
 FROM AWARD WHERE AWARD_ID = AV_AWARD_ID;
 SELECT  distinct BA_CODE INTO LS_BA_CODE
 FROM SAP_FEED_UNIT_MAPPING WHERE UNIT_NUMBER  = LS_LEAD_UNIT_NUMBER;
 SELECT CONCAT('04',LS_SPONSOR_TYPE_CODE,LS_WBS_CODE,LS_BA_CODE) INTO LS_NEW_ACCOUNT_NUMBER;
 SELECT CONCAT(LEFT(LS_ACCOUNT_NUMBER,5),SUBSTR(LS_ACCOUNT_NUMBER,12))  
 INTO LS_CURR_ACCOUNT_NUMBER;
 IF LS_NEW_ACCOUNT_NUMBER =  LS_CURR_ACCOUNT_NUMBER THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
 END IF;
END
