-- `FN_RULE_PI_IS_HOD_IN_AWARD`; 


CREATE FUNCTION `FN_RULE_PI_IS_HOD_IN_AWARD`( 
AV_AWARD_ID VARCHAR(12)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LS_LEAD_UNIT VARCHAR(8);
DECLARE LS_COUNT int(11); 
DECLARE LS_LEAD_UNIT_NUMBER VARCHAR(8);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_AWARD_ID VARCHAR(22);
	SELECT AWARD_NUMBER INTO LS_AWARD_NUMBER FROM AWARD
	WHERE AWARD_ID = AV_AWARD_ID; 
	SELECT LEAD_UNIT_NUMBER,AWARD_ID INTO LS_LEAD_UNIT_NUMBER, LS_AWARD_ID FROM AWARD
	WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
	IF LS_LEAD_UNIT_NUMBER IS NOT NULL THEN
		SET AV_AWARD_ID = LS_AWARD_ID;
	ELSE 
		SELECT LEAD_UNIT_NUMBER 
		INTO LS_LEAD_UNIT
		FROM AWARD 
		where AWARD_ID = AV_AWARD_ID;
	END IF;
		SELECT COUNT(*) INTO LS_COUNT 
		FROM AWARD_PERSONS 
		WHERE AWARD_ID = AV_AWARD_ID
		AND PERSON_ID IN (	
							SELECT T1.PERSON_ID 
							FROM PERSON_ROLES T1 
							LEFT JOIN PERSON T2 ON T1.PERSON_ID = T2.PERSON_ID
							WHERE ROLE_ID = 400
							AND T1.UNIT_NUMBER =  LS_LEAD_UNIT
							);
		IF LS_COUNT THEN 
			RETURN 'TRUE';
		ELSE 
			RETURN 'FALSE';
		END IF;
END
