-- `FN_VAL_CONFIRM_PRJ_TASK`; 


CREATE FUNCTION `FN_VAL_CONFIRM_PRJ_TASK`(AV_AWARD_ID  VARCHAR(22)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
	DECLARE LI_TASK_5_COUNT INT;
	DECLARE LS_DOCUMENT_TYPE_CODE VARCHAR(3);
	SELECT AWARD_DOCUMENT_TYPE_CODE INTO LS_DOCUMENT_TYPE_CODE
	FROM AWARD 
	WHERE AWARD_ID = AV_AWARD_ID;
	IF LS_DOCUMENT_TYPE_CODE <> 1 THEN  
		RETURN 'TRUE';
	END IF;
	SELECT COUNT(TASK_ID) INTO LI_TASK_5_COUNT
	FROM TASK 
	WHERE MODULE_ITEM_ID  = AV_AWARD_ID	   
	AND TASK_TYPE_CODE  = 5 
	AND TASK_STATUS_CODE = 5; 
	IF LI_TASK_5_COUNT > 0 THEN
		RETURN 'TRUE';
	END IF;
RETURN 'FALSE';
END
