DROP TABLE IF EXISTS `proposal_sponsors`;

CREATE TABLE `proposal_sponsors` (
  `SPONSOR_ID` int(11) NOT NULL,
  `PROPOSAL_ID` int(11) DEFAULT NULL,
  `PROPOSAL_NUMBER` varchar(20) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `AMOUNT` int(11) DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `SPONSOR_CODE` varchar(20) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`SPONSOR_ID`),
  KEY `PROPOSAL_SPONSORS_FK1` (`PROPOSAL_ID`),
  KEY `PROPOSAL_SPONSORS_FK2` (`SPONSOR_CODE`),
  CONSTRAINT `PROPOSAL_SPONSORS_FK1` FOREIGN KEY (`PROPOSAL_ID`) REFERENCES `proposal` (`PROPOSAL_ID`),
  CONSTRAINT `PROPOSAL_SPONSORS_FK2` FOREIGN KEY (`SPONSOR_CODE`) REFERENCES `sponsor` (`SPONSOR_CODE`)
) ;
