
DROP TABLE IF EXISTS `proposal_action_type`;

CREATE TABLE `proposal_action_type` (
  `ACTION_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(6) DEFAULT 'Y',
  `STATUS_CODE` int(11) DEFAULT NULL,
  `ACTION_ITEM_ID` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`ACTION_TYPE_CODE`),
  KEY `PROPOSAL_ACTION_TYPE_FK1` (`STATUS_CODE`),
  KEY `PROPOSAL_ACTION_TYPE_FK2` (`ACTION_ITEM_ID`),
  CONSTRAINT `PROPOSAL_ACTION_TYPE_FK1` FOREIGN KEY (`STATUS_CODE`) REFERENCES `proposal_status` (`STATUS_CODE`),
  CONSTRAINT `PROPOSAL_ACTION_TYPE_FK2` FOREIGN KEY (`ACTION_ITEM_ID`) REFERENCES `proposal_action_item` (`ACTION_ITEM_ID`)
) ;