
DROP TABLE IF EXISTS `proposal_resrch_areas`;

CREATE TABLE `proposal_resrch_areas` (
  `RESRCH_AREA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROPOSAL_ID` int(11) DEFAULT NULL,
  `PROPOSAL_NUMBER` varchar(20) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `RESEARCH_AREA_CODE` varchar(3) DEFAULT NULL,
  `RESRCH_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `RESRCH_TYPE_AREA_CODE` varchar(255) DEFAULT NULL,
  `RESRCH_TYPE_SUB_AREA_CODE` varchar(255) DEFAULT NULL,
  `RESEARCH_SUB_AREA_CODE` varchar(255) DEFAULT NULL,
  `CHALLENGE_AREA_CODE` varchar(255) DEFAULT NULL,
  `CHALLENGE_SUBAREA_CODE` varchar(255) DEFAULT NULL,
  `RESEARCH_RANK` int(11) DEFAULT NULL,
  PRIMARY KEY (`RESRCH_AREA_ID`),
  KEY `PROP_RESRCH_AREA_FK1` (`PROPOSAL_ID`),
  KEY `PROP_RESRCH_AREA_FK2` (`RESRCH_TYPE_CODE`),
  KEY `PROP_RESRCH_AREA_FK3` (`RESRCH_TYPE_AREA_CODE`),
  KEY `PROP_RESRCH_AREA_FK4` (`RESRCH_TYPE_SUB_AREA_CODE`),
  KEY `PROP_RESRCH_AREA_FK5` (`RESEARCH_SUB_AREA_CODE`),
  KEY `PROP_RESRCH_AREA_FK6` (`CHALLENGE_AREA_CODE`),
  KEY `PROP_RESRCH_AREA_FK7` (`CHALLENGE_SUBAREA_CODE`),
  CONSTRAINT `PROP_RESRCH_AREA_FK1` FOREIGN KEY (`PROPOSAL_ID`) REFERENCES `proposal` (`PROPOSAL_ID`),
  CONSTRAINT `PROP_RESRCH_AREA_FK2` FOREIGN KEY (`RESRCH_TYPE_CODE`) REFERENCES `research_type` (`RESRCH_TYPE_CODE`),
  CONSTRAINT `PROP_RESRCH_AREA_FK3` FOREIGN KEY (`RESRCH_TYPE_AREA_CODE`) REFERENCES `research_type_area` (`RESRCH_TYPE_AREA_CODE`),
  CONSTRAINT `PROP_RESRCH_AREA_FK4` FOREIGN KEY (`RESRCH_TYPE_SUB_AREA_CODE`) REFERENCES `research_type_sub_area` (`RESRCH_TYPE_SUB_AREA_CODE`),
  CONSTRAINT `PROP_RESRCH_AREA_FK5` FOREIGN KEY (`RESEARCH_SUB_AREA_CODE`) REFERENCES `research_sub_area` (`RESEARCH_SUB_AREA_CODE`),
  CONSTRAINT `PROP_RESRCH_AREA_FK6` FOREIGN KEY (`CHALLENGE_AREA_CODE`) REFERENCES `societal_challenge_area` (`CHALLENGE_AREA_CODE`),
  CONSTRAINT `PROP_RESRCH_AREA_FK7` FOREIGN KEY (`CHALLENGE_SUBAREA_CODE`) REFERENCES `societal_challenge_subarea` (`CHALLENGE_SUBAREA_CODE`)
) ;
