DROP TABLE IF EXISTS `proposal_comment_attachments`;

CREATE TABLE `proposal_comment_attachments` (
  `COMMENT_ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROPOSAL_COMMENT_ID` int(11) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `FILE_DATA_ID` varchar(36) DEFAULT NULL,
  `MIME_TYPE` varchar(250) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COMMENT_ATTACHMENT_ID`),
  KEY `PROP_COMMENT_ATTACHMENT_FK1` (`PROPOSAL_COMMENT_ID`),
  CONSTRAINT `PROP_COMMENT_ATTACHMENT_FK1` FOREIGN KEY (`PROPOSAL_COMMENT_ID`) REFERENCES `proposal_comments` (`PROPOSAL_COMMENT_ID`)
);