
DROP TABLE IF EXISTS `proposal_attach_type`;

CREATE TABLE `proposal_attach_type` (
  `ATTACHMNT_TYPE_CODE` int(11) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ATTACHMNT_TYPE_CODE`)
) ;
