
DROP TABLE IF EXISTS `proposal_project_team`;

CREATE TABLE `proposal_project_team` (
  `PROPOSAL_PROJECT_TEAM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `END_DATE` datetime(6) DEFAULT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` varchar(255) DEFAULT NULL,
  `NON_EMPLOYEE_FLAG` varchar(255) DEFAULT NULL,
  `PERCENTAGE_CHARGED` varchar(255) DEFAULT NULL,
  `PERSON_ID` varchar(255) DEFAULT NULL,
  `PROJECT_ROLE` varchar(255) DEFAULT NULL,
  `START_DATE` datetime(6) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `PROPOSAL_ID` int(11) NOT NULL,
  PRIMARY KEY (`PROPOSAL_PROJECT_TEAM_ID`),
  KEY `PROPOSAL_PROJECT_TEAM_FK1` (`PROPOSAL_ID`),
  CONSTRAINT `PROPOSAL_PROJECT_TEAM_FK1` FOREIGN KEY (`PROPOSAL_ID`) REFERENCES `proposal` (`PROPOSAL_ID`)
) ;
