

DROP TABLE IF EXISTS `proposal_review_comment`;

CREATE TABLE `proposal_review_comment` (
  `REVIEW_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IS_PRIVATE_COMMENT` varchar(255) DEFAULT NULL,
  `PROPOSAL_ID` int(11) DEFAULT NULL,
  `REVIEW_COMMENT` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `REVIEW_ID` int(11) NOT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `FULL_NAME` varchar(90) DEFAULT NULL,
  PRIMARY KEY (`REVIEW_COMMENT_ID`),
  KEY `PROPOSAL_REVIEW_COMMENT_FK1` (`REVIEW_ID`),
  CONSTRAINT `PROPOSAL_REVIEW_COMMENT_FK1` FOREIGN KEY (`REVIEW_ID`) REFERENCES `proposal_review` (`REVIEW_ID`)
) ;
