
DROP TABLE IF EXISTS `valid_report_class`;

CREATE TABLE `valid_report_class` (
  `REPORT_CLASS_ID` int(11) NOT NULL,
  `REPORT_CLASS_CODE` varchar(3) DEFAULT NULL,
  `REPORT_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`REPORT_CLASS_ID`),
  KEY `VALID_REPORT_CLASS_FK1` (`REPORT_CLASS_CODE`),
  KEY `VALID_REPORT_CLASS_FK2` (`REPORT_CODE`),
  CONSTRAINT `VALID_REPORT_CLASS_FK1` FOREIGN KEY (`REPORT_CLASS_CODE`) REFERENCES `report_class` (`REPORT_CLASS_CODE`),
  CONSTRAINT `VALID_REPORT_CLASS_FK2` FOREIGN KEY (`REPORT_CODE`) REFERENCES `report` (`REPORT_CODE`)
) ;