SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `valid_ce_rate_types`;

CREATE TABLE `valid_ce_rate_types` (
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `COST_ELEMENT` varchar(50) NOT NULL,
  `RATE_CLASS_CODE` varchar(3) NOT NULL,
  `RATE_TYPE_CODE` varchar(3) NOT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COST_ELEMENT`,`RATE_CLASS_CODE`,`RATE_TYPE_CODE`),
  KEY `FK2g3t4p840bh00ki2pyhqeaaum` (`RATE_CLASS_CODE`,`RATE_TYPE_CODE`),
  CONSTRAINT `VALID_CE_RATE_TYPES_FK1` FOREIGN KEY (`COST_ELEMENT`) REFERENCES `cost_element` (`COST_ELEMENT`),
  CONSTRAINT `VALID_CE_RATE_TYPES_FK2` FOREIGN KEY (`RATE_CLASS_CODE`) REFERENCES `rate_class` (`RATE_CLASS_CODE`),
  CONSTRAINT `VALID_CE_RATE_TYPES_FK3` FOREIGN KEY (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`) REFERENCES `rate_type` (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`)
) ;
SET FOREIGN_KEY_CHECKS = 1;