-- `FN_CHK_CLAIM_INVOICE_LINE_ITEMS`; 

CREATE FUNCTION `FN_CHK_CLAIM_INVOICE_LINE_ITEMS`(AV_CLAIM_ID VARCHAR(12)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT(3);
DECLARE LI_CLAIM_AMOUNT DECIMAL(15,2);
DECLARE LI_AWARD_NUMBER VARCHAR(12);
   SELECT COUNT(1) INTO LI_COUNT FROM CLAIM WHERE CLAIM_ID = AV_CLAIM_ID AND CLAIM_STATUS_CODE IN (6,8);
   
    IF LI_COUNT = 0 THEN
		RETURN 'TRUE';
	ELSE
		SELECT COUNT(1) INTO LI_COUNT
		FROM CLAIM_INVOICE T1 
		INNER JOIN CLAIM_INVOICE_DETAILS T2 ON T1.INVOICE_ID = T2.INVOICE_ID
		WHERE T1.CLAIM_ID = AV_CLAIM_ID AND T1.SEQUENCE_NUMBER IN (SELECT MAX(SEQUENCE_NUMBER) FROM CLAIM_INVOICE WHERE CLAIM_ID =AV_CLAIM_ID);
		
		IF LI_COUNT = 0 THEN
		    
			SELECT AWARD_NUMBER INTO LI_AWARD_NUMBER FROM CLAIM WHERE CLAIM_ID = AV_CLAIM_ID;
			SET LI_CLAIM_AMOUNT = FN_GET_CLAIM_AMOUNT(LI_AWARD_NUMBER, AV_CLAIM_ID);
		
			IF LI_CLAIM_AMOUNT > 0 THEN
				RETURN 'FALSE';
			ELSE	
				RETURN 'TRUE';
			END IF;
		ELSE	
			RETURN 'TRUE';
		END IF;
	END IF;		
END
