DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `FN_CHCK_AGREE_ACTION_TYPE_NEW`(
AGREEMENT_REQUEST_ID    int) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LS_VALUE_ACTION_TYPE varchar(10);
DECLARE LS_IS_MOD_FILLED int;
DECLARE LI_FLAG INT;
	SELECT VALUE INTO LS_VALUE_ACTION_TYPE FROM
    CUSTOM_DATA where MODULE_ITEM_CODE = 13 AND MODULE_ITEM_KEY = AGREEMENT_REQUEST_ID AND MODULE_SUB_ITEM_KEY = 0 AND CUSTOM_DATA_ELEMENTS_ID = 500;
	IF UPPER(LS_VALUE_ACTION_TYPE) = 'NEW' THEN
		SELECT COUNT(*) INTO LS_IS_MOD_FILLED FROM
        CUSTOM_DATA where MODULE_ITEM_CODE = 13 AND MODULE_ITEM_KEY = AGREEMENT_REQUEST_ID AND MODULE_SUB_ITEM_KEY = 0 AND CUSTOM_DATA_ELEMENTS_ID = 501;
		IF LS_IS_MOD_FILLED <> 0 THEN
			RETURN 'TRUE';
        END IF;
	END IF;
RETURN 'FALSE';
END
$$
DELIMITER ;
