DELIMITER $$
CREATE  FUNCTION `FN_COUNT_OF_DMP_UPDATE`(AV_AWARD_NUMBER  VARCHAR(22)
) RETURNS int
    DETERMINISTIC
BEGIN
	DECLARE LI_COUNT INT;
	SELECT
	count(T1.AWARD_NUMBER)+1 INTO LI_COUNT
	FROM AWARD T1
	LEFT OUTER JOIN SR_HEADER T8 ON T8.ORIGINATING_MODULE_CODE = 1
    LEFT OUTER JOIN ASSOC_SR T10 ON T8.SR_HEADER_ID = T10.SR_HEADER_ID AND T10.MODULE_CODE = 1
    AND T10.MODULE_ITEM_ID IN (
        SELECT MAX(award_id)
        FROM AWARD
        WHERE award_id < T1.AWARD_ID
        AND award_number = T1.award_number
    )
   LEFT OUTER JOIN SR_TYPE T9 ON T9.TYPE_CODE = T8.TYPE_CODE
   WHERE T8.TYPE_CODE = 5
   AND T1.AWARD_NUMBER = AV_AWARD_NUMBER;
RETURN LI_COUNT;
END
$$
DELIMITER ;
