DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` FUNCTION `FN_COUNTRY_CHECK_QUESTIONNAIRE`(as_proposal INT) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
  DECLARE LI_COUNT INT;
  DECLARE LS_ANSWER VARCHAR(50);
  	DECLARE EXIT HANDLER FOR NOT FOUND BEGIN
			RETURN 'FALSE';
	END;
		SELECT IF(COUNT(1)>1,ANSWER,NULL) INTO LS_ANSWER FROM QUEST_ANSWER QA
        INNER JOIN QUEST_ANSWER_HEADER Q
        ON Q.QUESTIONNAIRE_ANS_HEADER_ID=QA.QUESTIONNAIRE_ANS_HEADER_ID
        AND Q.MODULE_ITEM_KEY=as_proposal
        AND Q.MODULE_ITEM_CODE=3
        AND QA.QUESTION_ID=4333;
        IF LS_ANSWER IS NOT NULL THEN
			SELECT IFNULL(COUNT(1),0) into LI_COUNT FROM COUNTRY where (COUNTRY_NAME=LS_ANSWER or COUNTRY_CODE=LS_ANSWER);
			IF LI_COUNT > 0 THEN
				RETURN 'TRUE';
				ELSE
				RETURN 'FALSE';
			END IF;
       ELSE
			RETURN 'FALSE';
		END IF;
END
$$
DELIMITER ;
