DELIMITER $$
CREATE  FUNCTION `FN_CHK_SR_PREAWARD_SPONSOR`(
AV_SR_HEADER_ID INT
) RETURNS varchar(10) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT;
DECLARE LI_QUESTIONNAIRE_ID INT;
DECLARE LI_ANSWER_HEADER_ID INT;
DECLARE LI_QUESTION_ID INT;
-- Fetch the Pre Award Request QUESTIONNAIRE ID
SET LI_COUNT = 0;
SELECT COUNT(1) INTO LI_COUNT FROM quest_header WHERE QUESTIONNAIRE_NUMBER = 82 AND IS_FINAL = 'Y';
IF LI_COUNT = 1 THEN
	SELECT QUESTIONNAIRE_ID INTO LI_QUESTIONNAIRE_ID FROM quest_header WHERE QUESTIONNAIRE_NUMBER = 82 AND IS_FINAL = 'Y';
ELSE
	RETURN 'FALSE';
END IF;
-- To Fetch the Question ID
SET LI_COUNT = 0;
SELECT COUNT(1) INTO LI_COUNT FROM quest_question WHERE QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID AND QUESTION LIKE '%Q1244_Sponsor%';
IF LI_COUNT = 1 THEN
	SELECT QUESTION_ID INTO LI_QUESTION_ID FROM quest_question WHERE QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID AND QUESTION LIKE '%Q1244_Sponsor%';
ELSE
	RETURN 'FALSE';
END IF;
-- To Fetch the Questionnaire Answer header
SET LI_COUNT = 0;
SELECT COUNT(1) INTO LI_COUNT FROM quest_answer_header WHERE QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID AND MODULE_ITEM_CODE = 20 AND MODULE_ITEM_KEY = AV_SR_HEADER_ID;
IF LI_COUNT = 1 THEN
	SELECT QUESTIONNAIRE_ANS_HEADER_ID INTO LI_ANSWER_HEADER_ID FROM quest_answer_header WHERE QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID AND MODULE_ITEM_CODE = 20 AND MODULE_ITEM_KEY = AV_SR_HEADER_ID;
ELSE
	RETURN 'FALSE';
END IF;
-- To Fetch the answer in the sponsor list NIH, DOD, DHHS
SET LI_COUNT = 0;
SELECT COUNT(1) INTO LI_COUNT FROM quest_answer WHERE QUESTIONNAIRE_ANS_HEADER_ID = LI_ANSWER_HEADER_ID AND QUESTION_ID = LI_QUESTION_ID AND ANSWER_LOOKUP_CODE IN ('300865', '301948', '301286');
IF LI_COUNT = 1 THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
END IF;
RETURN 'FALSE';
END
$$
DELIMITER ;
