DELIMITER $$
CREATE  FUNCTION `FN_GET_RPT_SCH_NUMBER`( PROP_UNIT_IN  VARCHAR(8) ) RETURNS varchar(8) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE RPT_SCH_NUMBER VARCHAR(8);
SELECT
    IF(COUNT(unit_number) > 0,
        unit_number,
        NULL)
INTO RPT_SCH_NUMBER FROM
    unit
WHERE
    unit_number = CONCAT(SUBSTR(PROP_UNIT_IN, 1, 3), '00000');
	RETURN RPT_SCH_NUMBER ;
END
$$
DELIMITER ;
