DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` FUNCTION `FN_IDC_BASE_TYPE`(
  AV_PROPOSAL_ID   int(10)
 ,IDC_TYPE int
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT int;
DECLARE RETURN_STRING VARCHAR(5) DEFAULT 'FALSE';
 SELECT COUNT(*)
 INTO LI_COUNT
 FROM eps_proposal p
     ,budget_header b
 WHERE b.rate_class_code = IDC_TYPE
 AND   p.PROPOSAL_ID=AV_PROPOSAL_ID
 AND   p.proposal_id = b.proposal_id;
IF LI_COUNT > 0 THEN
   SET RETURN_STRING = 'TRUE';
END IF;
RETURN RETURN_STRING;
END
$$
DELIMITER ;
