DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` FUNCTION `FN_SR_LEAD_UNIT_RULE`(AS_SR_ID  INT,
      AS_UNIT_NUMBER VARCHAR(8) ) RETURNS varchar(8) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT;
SELECT 	COUNT(1)
		INTO	LI_COUNT
		FROM	SR_HEADER
		WHERE	SR_HEADER_ID = AS_SR_ID
		AND	UNIT_NUMBER = AS_UNIT_NUMBER;
		IF LI_COUNT > 0 THEN
			RETURN 'TRUE';
		ELSE
			RETURN 'FALSE';
        END IF;
END
$$
DELIMITER ;
