DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` FUNCTION `FN_SR_LEAD_UNIT_BELOW`(AV_SR_HEADER_ID INT, AV_UNIT_NUMBER VARCHAR(8)) RETURNS varchar(8) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
    DECLARE LI_COUNT  INT;
	SELECT COUNT(1)
    INTO LI_COUNT
    FROM SR_HEADER
    WHERE SR_HEADER_ID = AV_SR_HEADER_ID
    AND UNIT_NUMBER
    IN
    (SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER = AV_UNIT_NUMBER );
    IF (LI_COUNT > 0) THEN
		RETURN 'TRUE';
	ELSE
		RETURN 'FALSE';
	END IF;
END
$$
DELIMITER ;
