DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` FUNCTION `fn_sr_person_need_check`(
  AV_SR_HEADER_ID   INT
) RETURNS varchar(6) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
  DECLARE V_TYPE_CODE VARCHAR(3) DEFAULT 'xxx';
  DECLARE SR_TYPE_CODE_SPON VARCHAR(3) DEFAULT '40';  -- Sponsor
  DECLARE SR_TYPE_CODE_PRE VARCHAR(3) DEFAULT '61';  -- PreAward
  DECLARE MATCH_FOUND INT DEFAULT 0;
  DECLARE RETURN_STRING VARCHAR(5) DEFAULT 'FALSE';
  -- Get type code
  SELECT TYPE_CODE
  INTO V_TYPE_CODE
  FROM SR_HEADER
  WHERE SR_HEADER_ID = AV_SR_HEADER_ID;
  -- Get the person count from SR_PERSONS
  SELECT COUNT(*)
  INTO MATCH_FOUND
  FROM SR_PERSONS
  WHERE sr_header_id = AV_SR_HEADER_ID
  AND ACTION_FLAG !='IMPORTED_DELETED';
  -- If TYPE is PRE-Award (61) or Sponsor (40)
  IF (V_TYPE_CODE = SR_TYPE_CODE_SPON OR V_TYPE_CODE = SR_TYPE_CODE_PRE ) THEN
  -- Check if sr_persons has any entry showing to the user
    IF MATCH_FOUND >0 THEN
	 SET RETURN_STRING ='TRUE';
     RETURN RETURN_STRING;
    END IF;
  ELSE
    IF MATCH_FOUND <= 0 THEN
	 SET RETURN_STRING ='TRUE';
     RETURN RETURN_STRING;
    END IF;
 END IF;
  RETURN RETURN_STRING;
END
$$
DELIMITER ;
