DELIMITER $$
CREATE DEFINER=`jhufibi`@`localhost` PROCEDURE `GET_MY_LEARNING_USERS`()
BEGIN
 DECLARE LI_BATCH_IDENTIFIER INT;
 DECLARE LI_USER_COUNT int;
 DECLARE LI_COUNT int;
	 SELECT count(*) into LI_count
	 FROM PERSON_TRAINING_AUDIT WHERE BATCH_IDENTIFIER IS NOT NULL;
	 IF LI_count = 0 THEN
		set LI_BATCH_IDENTIFIER = 0;
	 ELSE
		 IF HOUR(CURRENT_TIMESTAMP) = 0 then
			 SELECT (BATCH_IDENTIFIER+1)%10 INTO LI_BATCH_IDENTIFIER
			 FROM PERSON_TRAINING_AUDIT
			 WHERE AUDIT_ID = (SELECT MAX(AUDIT_ID) FROM PERSON_TRAINING_AUDIT WHERE BATCH_IDENTIFIER IS NOT NULL);
		  ELSE
			 SELECT BATCH_IDENTIFIER%10 INTO LI_BATCH_IDENTIFIER
			 FROM PERSON_TRAINING_AUDIT
			 WHERE AUDIT_ID = (SELECT MAX(AUDIT_ID) FROM PERSON_TRAINING_AUDIT WHERE BATCH_IDENTIFIER IS NOT NULL);
		 END IF;
	 END IF;
	SELECT P.USER_NAME FROM PERSON P
	WHERE EXISTS(
		SELECT  1
		FROM    PROPOSAL IP
			   ,PROPOSAL_PERSONS PP
		WHERE   IP.STATUS_CODE = 1
		AND     P.PERSON_ID NOT IN (SELECT PERSON_ID
									FROM   PERSON_CUSTOM_DATA
									WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
									AND    COLUMN_VALUE = 'Y')
		AND     IP.SEQUENCE_NUMBER = (SELECT MAX(SEQUENCE_NUMBER)
									  FROM   PROPOSAL
									  WHERE  PROPOSAL_NUMBER = IP.PROPOSAL_NUMBER)
		AND     PP.SEQUENCE_NUMBER = (SELECT MAX(SEQUENCE_NUMBER)
									   FROM   PROPOSAL_PERSONS
									   WHERE  PROPOSAL_NUMBER = PP.PROPOSAL_NUMBER)
		AND     IP.PROPOSAL_NUMBER = PP.PROPOSAL_NUMBER
		AND     PP.PERSON_ID = P.PERSON_ID
		AND 	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
		)
		AND     P.HOME_UNIT IS NOT NULL
		AND 	P.USER_NAME IS NOT NULL
	UNION
	SELECT P.USER_NAME FROM PERSON P
	WHERE EXISTS(
		SELECT  1
		FROM    AWARD A
			   ,AWARD_PERSONS AP
		WHERE   A.AWARD_SEQUENCE_STATUS = 'ACTIVE'
		AND     P.PERSON_ID NOT IN (SELECT PERSON_ID
									FROM   PERSON_CUSTOM_DATA
									WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
									AND    COLUMN_VALUE = 'Y')
		AND     A.AWARD_ID = AP.AWARD_ID
		AND     AP.PERSON_ID = P.PERSON_ID
		AND	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
		)
		AND     P.HOME_UNIT IS NOT NULL
		AND 	P.USER_NAME IS NOT NULL
	UNION
	SELECT P.USER_NAME FROM PERSON P
	WHERE EXISTS(
		SELECT 1
		FROM    EPS_PROPOSAL PD
			   ,EPS_PROPOSAL_PERSONS PDP
		WHERE  PD.STATUS_CODE IN (1, 2, 4)
		AND     P.PERSON_ID NOT IN (SELECT PERSON_ID
									FROM   PERSON_CUSTOM_DATA
									WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
									AND    COLUMN_VALUE = 'Y')
		AND     PD.PROPOSAL_ID = PDP.PROPOSAL_ID
		AND     PDP.PERSON_ID = P.PERSON_ID
		AND	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
		)
		AND     P.HOME_UNIT IS NOT NULL
		AND 	P.USER_NAME IS NOT NULL
	UNION
	SELECT P.USER_NAME FROM PERSON P
	WHERE EXISTS(
		SELECT  1
		FROM    JHU_EFFORT_CERTIFIERS J
		WHERE   J.PERSON_ID NOT IN (SELECT PERSON_ID
									FROM   PERSON_CUSTOM_DATA
									WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
									AND    COLUMN_VALUE = 'Y')
		AND    J.PERSON_ID = P.PERSON_ID
		AND	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
		)
		AND 	P.USER_NAME IS NOT NULL;
insert into PERSON_TRAINING_AUDIT(
						BATCH_IDENTIFIER,
						USER_COUNT)
						select LI_BATCH_IDENTIFIER,
						(select count(user_name) from (
							SELECT P.USER_NAME FROM PERSON P
								WHERE EXISTS(
									SELECT  1
									FROM    PROPOSAL IP
										   ,PROPOSAL_PERSONS PP
									WHERE   IP.STATUS_CODE = 1
									AND     P.PERSON_ID NOT IN (SELECT PERSON_ID
																FROM   PERSON_CUSTOM_DATA
																WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
																AND    COLUMN_VALUE = 'Y')
									AND     IP.SEQUENCE_NUMBER = (SELECT MAX(SEQUENCE_NUMBER)
																  FROM   PROPOSAL
																  WHERE  PROPOSAL_NUMBER = IP.PROPOSAL_NUMBER)
									AND     PP.SEQUENCE_NUMBER = (SELECT MAX(SEQUENCE_NUMBER)
																   FROM   PROPOSAL_PERSONS
																   WHERE  PROPOSAL_NUMBER = PP.PROPOSAL_NUMBER)
									AND     IP.PROPOSAL_NUMBER = PP.PROPOSAL_NUMBER
									AND     PP.PERSON_ID = P.PERSON_ID
									AND 	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
									)
									AND     P.HOME_UNIT IS NOT NULL
									AND 	P.USER_NAME IS NOT NULL
								UNION
								SELECT P.USER_NAME FROM PERSON P
								WHERE EXISTS(
									SELECT  1
									FROM    AWARD A
										   ,AWARD_PERSONS AP
									WHERE   A.AWARD_SEQUENCE_STATUS = 'ACTIVE'
									AND     P.PERSON_ID NOT IN (SELECT PERSON_ID
																FROM   PERSON_CUSTOM_DATA
																WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
																AND    COLUMN_VALUE = 'Y')
									AND     A.AWARD_ID = AP.AWARD_ID
									AND     AP.PERSON_ID = P.PERSON_ID
									AND	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
									)
									AND     P.HOME_UNIT IS NOT NULL
									AND 	P.USER_NAME IS NOT NULL
								UNION
								SELECT P.USER_NAME FROM PERSON P
								WHERE EXISTS(
									SELECT 1
									FROM    EPS_PROPOSAL PD
										   ,EPS_PROPOSAL_PERSONS PDP
									WHERE  PD.STATUS_CODE IN (1, 2, 4)
									AND     P.PERSON_ID NOT IN (SELECT PERSON_ID
																FROM   PERSON_CUSTOM_DATA
																WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
																AND    COLUMN_VALUE = 'Y')
									AND     PD.PROPOSAL_ID = PDP.PROPOSAL_ID
									AND     PDP.PERSON_ID = P.PERSON_ID
									AND	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
									)
									AND     P.HOME_UNIT IS NOT NULL
									AND 	P.USER_NAME IS NOT NULL
								UNION
								SELECT P.USER_NAME FROM PERSON P
								WHERE EXISTS(
									SELECT  1
									FROM    JHU_EFFORT_CERTIFIERS J
									WHERE   J.PERSON_ID NOT IN (SELECT PERSON_ID
																FROM   PERSON_CUSTOM_DATA
																WHERE  COLUMN_NAME = 'OMIT_FROM_COMPLIANCE'
																AND    COLUMN_VALUE = 'Y')
									AND    J.PERSON_ID = P.PERSON_ID
									AND	MOD(P.PERSON_ID, 10) = LI_BATCH_IDENTIFIER
									)
									AND 	P.USER_NAME IS NOT NULL) PT);
END
$$
DELIMITER ;
