DELIMITER $$
CREATE DEFINER=`jhufibi`@`localhost` PROCEDURE `GET_MY_LEARNING_PD_USERS`(
AV_PROPOSAL_ID INT(11)
)
BEGIN
DECLARE LI_USER_COUNT int;
			SELECT DISTINCT(P.USER_NAME)
			FROM   EPS_PROPOSAL_PERSONS EPP
				  ,PERSON P
			WHERE  EPP.PROPOSAL_ID = AV_PROPOSAL_ID
			AND    EPP.PERSON_ID = P.PERSON_ID;
			insert into PERSON_TRAINING_AUDIT(
											PROPOSAL_ID,
											USER_COUNT
										)
										SELECT AV_PROPOSAL_ID,
										(SELECT count(DISTINCT(P.USER_NAME))
										FROM   EPS_PROPOSAL_PERSONS EPP
											  ,PERSON P
										WHERE  EPP.PROPOSAL_ID = AV_PROPOSAL_ID
										AND    EPP.PERSON_ID = P.PERSON_ID);
END
$$
DELIMITER ;
