DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `INSERT_PERSON_ROLES`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE C1 CURSOR FOR
	select distinct PERSON_ID,PROPOSAL_ID from eps_proposal_persons where PROPOSAL_ID in (
select PROPOSAL_ID from eps_proposal where STATUS_CODE in (1,3,12)) and PI_FLAG='Y' /*and proposal_id='80291'*/ ;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE LD_END_DATE DATETIME;
	DECLARE LD_START_DATE DATETIME;
	DECLARE LI_PROPOSAL_ID,LI_CNT INT(10);
    DECLARE LS_PERSON_ID VARCHAR(10);
	DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
	FETCH C1 INTO LS_PERSON_ID,LI_PROPOSAL_ID;
	IF DONE THEN
		LEAVE LOOP1;
	END IF;
	select COUNT(1) INTO LI_CNT
    from eps_proposal_person_roles
    where PERSON_ID =LS_PERSON_ID and role_id=1329
    and proposal_id = LI_PROPOSAL_ID;
    IF LI_CNT =0 THEN
    INSERT INTO eps_proposal_person_roles
    ( PROPOSAL_ID, PERSON_ID, ROLE_ID, UPDATE_TIMESTAMP, UPDATE_USER)
    values
    (LI_PROPOSAL_ID,LS_PERSON_ID,1329,utc_timestamp(),'POLUS_ADMIN');
	END IF;
END;
END LOOP;
CLOSE C1;
END
$$
DELIMITER ;
