DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `JHU_FETCH_DEV_PROPOSAL_ID`(DATA_PROPOSAL_NUMBER VARCHAR(8),OUT DATA_PROPOSAL_ID INT)
BEGIN
	DECLARE LI_COUNT INT;
    SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM eps_proposal WHERE proposal_id = DATA_PROPOSAL_NUMBER;
	IF LI_COUNT <> 1 THEN
		SET DATA_PROPOSAL_ID = -1;
	ELSE
		SELECT PROPOSAL_ID INTO DATA_PROPOSAL_ID FROM eps_proposal WHERE proposal_id = DATA_PROPOSAL_NUMBER;
	END IF;
END
$$
DELIMITER ;
