DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATION_QUEST`(DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_STG_QUESTIONNAIRE_ID INT;
DECLARE LI_QUESTIONNAIRE_ID INT;
DECLARE LI_QUESTIONNAIRE_VERSION_NUMBER INT;
DECLARE LS_NAME varchar(50);
DECLARE LS_DESCRIPTION varchar(2000);
DECLARE LI_GROUP_TYPE_CODE smallint;
DECLARE LS_IS_FINAL varchar(1);
DECLARE LI_MIGRATED_QUESTIONNAIRE_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_NUMBER INT;
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_VALIDATION_STATUS varchar(10);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
DECLARE LS_UPDATE_USER VARCHAR(60);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (IFNULL(LI_STG_QUESTIONNAIRE_ID,0),'QUEST_QUESTIONNAIRE','MIGRATION',LS_ERROR_MSG,UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('QUEST_QUESTIONNAIRE') AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_questionnaire SET VALIDATION_STATUS = 'VALID' WHERE VALIDATION_STATUS = 'ERROR' and  MIGRATED_QUESTIONNAIRE_ID = -1 ;
	END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM migration_qtn_execution_log;
	ALTER TABLE migration_qtn_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_questionnaire;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'QUEST_QUESTIONNAIRE';
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
										VALUES 	(LI_BATCH_ID,'MIGRATION','QUEST_QUESTIONNAIRE',UTC_TIMESTAMP());
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
										VALUES 	(LI_BATCH_ID,'MIGRATION','QUEST_USAGE',UTC_TIMESTAMP());
	INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : QUEST_QUESTIONNAIRE ',UTC_TIMESTAMP());
END;
		BEGIN
		DECLARE DONE2 INT DEFAULT FALSE;
		DECLARE CUR_QUESTIONNAIRE_DETAIL CURSOR FOR
		select ID
				, QUESTIONNAIRE_ID
				, VERSION_NUMBER
				, NAME
				, DESCRIPTION
				, IS_FINAL
				, GROUP_TYPE_CODE
                , UPDATE_USER
                , UPDATE_TIMESTAMP
		from stage_questionnaire
		where validation_status = 'VALID'
		order by QUESTIONNAIRE_ID,VERSION_NUMBER;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
		OPEN CUR_QUESTIONNAIRE_DETAIL;
		QUESTIONNAIRE_DETAIL_LOOP: LOOP
		FETCH CUR_QUESTIONNAIRE_DETAIL INTO
									LI_STG_QUESTIONNAIRE_ID
									, LI_QUESTIONNAIRE_ID
									, LI_QUESTIONNAIRE_VERSION_NUMBER
									, LS_NAME
									, LS_DESCRIPTION
									, LS_IS_FINAL
									, LI_GROUP_TYPE_CODE
                                    , LS_UPDATE_USER
                                    , LS_UPDATE_TIMESTAMP;
		IF DONE2 THEN
			LEAVE QUESTIONNAIRE_DETAIL_LOOP;
		END IF;
						SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('MIGRATION','QUEST_QUESTIONNAIRE',LI_BATCH_ID,'Migration started',UTC_TIMESTAMP(),LI_QUESTIONNAIRE_ID);
						select MIGRATED_QUESTIONNAIRE_NUMBER  into LI_MIGRATED_QUESTIONNAIRE_NUMBER from stage_questionnaire
						where QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID and VERSION_NUMBER = LI_QUESTIONNAIRE_VERSION_NUMBER;
						IF LI_MIGRATED_QUESTIONNAIRE_NUMBER IS NULL or LI_MIGRATED_QUESTIONNAIRE_NUMBER = -1 THEN
									select IFNULL(max(QUESTIONNAIRE_NUMBER),0)+1 into LI_MIGRATED_QUESTIONNAIRE_NUMBER from quest_header;
									UPDATE stage_questionnaire set MIGRATED_QUESTIONNAIRE_NUMBER = LI_MIGRATED_QUESTIONNAIRE_NUMBER
									where QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID and VALIDATION_STATUS = 'VALID';
						END IF;
									select IFNULL(max(QUESTIONNAIRE_ID),0)+1 into LI_MIGRATED_QUESTIONNAIRE_ID from quest_header;
									INSERT INTO quest_header(
														QUESTIONNAIRE_ID
														,QUEST_GROUP_TYPE_CODE
														,IS_FINAL
														,QUESTIONNAIRE_NUMBER
														,VERSION_NUMBER
														,QUESTIONNAIRE
														,DESCRIPTION
														,UPDATE_TIMESTAMP
														,UPDATE_USER
												)Values(
														LI_MIGRATED_QUESTIONNAIRE_ID
														,NULL
														,LS_IS_FINAL
														,LI_MIGRATED_QUESTIONNAIRE_NUMBER
														,LI_QUESTIONNAIRE_VERSION_NUMBER
														,LS_NAME
														,LS_DESCRIPTION
														,LS_UPDATE_TIMESTAMP
														, LS_UPDATE_USER
													);
									UPDATE stage_questionnaire SET
											MIGRATED_QUESTIONNAIRE_ID = LI_MIGRATED_QUESTIONNAIRE_ID
											, VALIDATION_STATUS = 'SUCCESS' where ID =  LI_STG_QUESTIONNAIRE_ID;
									  CALL MIGRATION_QUEST_USAGE(LI_QUESTIONNAIRE_ID, LI_QUESTIONNAIRE_VERSION_NUMBER, LI_MIGRATED_QUESTIONNAIRE_ID, DATA_REFRESH_FLAG);
					IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Migrated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Questionnaire'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('MIGRATION','QUEST_QUESTIONNAIRE',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LI_QUESTIONNAIRE_ID);
								set LI_COUNT = NULL;
								set LI_MIGRATED_QUESTIONNAIRE_ID = NULL;
								set LI_MIGRATED_QUESTIONNAIRE_NUMBER = NULL;
								set LI_QUESTIONNAIRE_VERSION_NUMBER = NULL;
								set LS_NAME = NULL;
								set LS_DESCRIPTION = NULL;
								set LI_STG_QUESTIONNAIRE_ID = NULL;
								set LI_QUESTIONNAIRE_ID = NULL;
			END LOOP;
			CLOSE CUR_QUESTIONNAIRE_DETAIL;
		INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','QUEST_QUESTIONNAIRE',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
			INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Migrated total records ( ', LI_TOTAL_DATA_COUNT,' ) of Questionnaire'),UTC_TIMESTAMP()),('Migration completed successfully',UTC_TIMESTAMP());
			update quest_column_nextvalue set
						QUESTIONNAIRE_ID = (select IFNULL(max(QUESTIONNAIRE_ID),0)+1 from quest_header)
						, QUESTIONNAIRE_NUMBER = (select IFNULL(max(QUESTIONNAIRE_NUMBER),0)+1 from quest_header)
                         , QUESTIONNAIRE_USAGE_ID = (select IFNULL(MAX(QUESTIONNAIRE_USAGE_ID),0)+1 from quest_usage );
END;
	set sql_safe_updates = 1;
END
$$
DELIMITER ;
