DELIMITER $$
CREATE  PROCEDURE `MIGRATE_EPS_PROP_NOTEPAD`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_EPS_PROPOSAL_COMMENT_ID INT;
DECLARE LI_COMMENT_TYPE_CODE INT;
DECLARE LI_PROPOSAL_ID INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_RESTRICTED_VIEW VARCHAR(1);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_COMMENTS LONGTEXT;
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_validation_matrix WHERE MODULE_NAME = 'EPSPROPNOTEPAD';
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'EPSPROPNOTEPAD' AND ERROR_TYPE = 'MIGRATION';
				UPDATE stage_eps_prop_notepad SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
		END IF;
END;
BEGIN
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM comment_type WHERE UPPER(DESCRIPTION) = UPPER('General Comments(Notepad)') AND IS_ACTIVE = 'Y' AND MODULE_CODE = 3;
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'EPSPROPNOTEPAD','MIGRATION',CONCAT('Invalid comment type : General Comments(Notepad)'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT COMMENT_TYPE_CODE INTO LI_COMMENT_TYPE_CODE FROM comment_type WHERE UPPER(DESCRIPTION) = UPPER('General Comments(Notepad)') AND IS_ACTIVE = 'Y' AND MODULE_CODE = 3;
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_prop_notepad;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'EPSPROPNOTEPAD';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','EPSPROPNOTEPAD',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATE_EPS_PROP_NOTEPAD	CURSOR FOR
	SELECT      MIGRATION_EPS_PROP_NOTEPAD_ID,
				PROPOSAL_NUMBER,
				COMMENTS,
				RESTRICTED_VIEW,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM  stage_eps_prop_notepad  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'EPSPROPNOTEPAD','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATE_EPS_PROP_NOTEPAD;
	MIGRATE_EPS_PROP_NOTEPAD_LOOP      : 		LOOP
	FETCH MIGRATE_EPS_PROP_NOTEPAD       		INTO       		LI_RECORD_ID,
																LS_PROPOSAL_NUMBER,
																LS_COMMENTS,
																LS_RESTRICTED_VIEW,
																LS_UPDATE_TIMESTAMP,
																LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATE_EPS_PROP_NOTEPAD_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_EPS_PROPOSAL_COMMENT_ID = -1;
	SET LI_COUNT = -1;
	SET LI_PROPOSAL_ID = -1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPNOTEPAD',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
	CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PROPOSAL_NUMBER,@proposal_id);
	IF @proposal_id = -1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'EPSPROPNOTEPAD','MIGRATION',CONCAT('Invalid proposal number : ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SET LI_PROPOSAL_ID = @proposal_id;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPNOTEPAD',LI_BATCH_ID,'before insert',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(EPS_PROPOSAL_COMMENT_ID),0) + 1 INTO LI_EPS_PROPOSAL_COMMENT_ID
		FROM eps_proposal_comments;
		INSERT INTO   eps_proposal_comments
		(
			EPS_PROPOSAL_COMMENT_ID,
			PROPOSAL_ID,
			COMMENT_TYPE_CODE,
			COMMENTS,
			IS_PRIVATE,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			IS_PUBLIC
		)
		VALUES
		(
			LI_EPS_PROPOSAL_COMMENT_ID,
			LI_PROPOSAL_ID,
			LI_COMMENT_TYPE_CODE,
			LS_COMMENTS,
			LS_RESTRICTED_VIEW,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER,
			NULL
		);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE stage_eps_prop_notepad
		SET VALIDATION_STATUS = 'SUCCESS',
		FIBI_IDENTIFIER = LI_EPS_PROPOSAL_COMMENT_ID
		WHERE MIGRATION_EPS_PROP_NOTEPAD_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPNOTEPAD',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	ELSE
		UPDATE stage_eps_prop_notepad
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = -1
		WHERE MIGRATION_EPS_PROP_NOTEPAD_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPNOTEPAD',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	END IF;
	IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
		IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
			INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
			SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
		END IF;
	END IF ;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPNOTEPAD',LI_BATCH_ID,'Migration end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END LOOP MIGRATE_EPS_PROP_NOTEPAD_LOOP;
	CLOSE MIGRATE_EPS_PROP_NOTEPAD;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPNOTEPAD',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM eps_proposal_comments_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO eps_proposal_comments_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(EPS_PROPOSAL_COMMENT_ID),0) + 1  FROM eps_proposal_comments));
	ELSE
	UPDATE eps_proposal_comments_id_generator   SET NEXT_VAL = (SELECT IFNULL(MAX(EPS_PROPOSAL_COMMENT_ID),0) + 1  FROM eps_proposal_comments);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END IF;
END
$$
DELIMITER ;
