DELIMITER $$
CREATE  PROCEDURE `MIGRATE_BUDGET_PERIOD_PREVAL`(DATA_PROPOSAL_NUMBER VARCHAR(8), DATA_VERSION_NUMBER INT,DATA_START_DATE DATETIME,DATA_END_DATE DATETIME,FOR_AUDIT INT, OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LS_TOTAL_COST DECIMAL(12,2);
DECLARE LS_SUM_OF_COST DECIMAL(12,2);
DECLARE LS_DIRECT_TOTAL_COST DECIMAL(12,2);
DECLARE LS_INDIRECT_TOTAL_COST DECIMAL(12,2);
DECLARE LS_START_DATE DATETIME;
DECLARE LS_END_DATE DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SELECT IFNULL(MAX(BATCH_ID),0) INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'BUDGETPERIOD';
END;
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
    DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_BUDGET_PERIOD_CURSOR CURSOR FOR
		SELECT  MIGRATION_BUDGET_PERIOD_ID,
				START_DATE,
				END_DATE,
				TOTAL_COST,
				TOTAL_DIRECT_COST,
				TOTAL_INDIRECT_COST
		FROM 	stage_budget_periods
		WHERE VALIDATION_STATUS IS NULL AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND VERSION_NUMBER = DATA_VERSION_NUMBER;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
		OPEN MIGRATION_BUDGET_PERIOD_CURSOR;
		MIGRATION_BUDGET_PERIOD_CURSOR_LOOP    : LOOP
		FETCH MIGRATION_BUDGET_PERIOD_CURSOR     INTO    	LI_RECORD_ID,
															LS_START_DATE,
															LS_END_DATE,
															LS_TOTAL_COST,
															LS_DIRECT_TOTAL_COST,
															LS_INDIRECT_TOTAL_COST;
	IF DONE1 THEN
		LEAVE MIGRATION_BUDGET_PERIOD_CURSOR_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	IF FOR_AUDIT = 1 THEN
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	IF LS_START_DATE IS NULL THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION','Start date is mandatory',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after start date',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	IF LS_END_DATE IS NULL THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION','End date is mandatory',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after end date',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	IF LS_START_DATE IS NOT NULL AND LS_END_DATE IS NOT NULL AND LS_END_DATE < LS_START_DATE THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION','End date should be greater than that of start date',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after greater than check',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	IF LS_START_DATE IS NOT NULL AND (LS_START_DATE NOT BETWEEN DATA_START_DATE AND DATA_END_DATE) THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION','Start date should be in between the budget dates',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after start date compare with budget',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	IF LS_END_DATE IS NOT NULL AND (LS_END_DATE NOT BETWEEN DATA_START_DATE AND DATA_END_DATE) THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION','End date should be in between the budget dates',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after end date compare with budget',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	SET LS_SUM_OF_COST = LS_DIRECT_TOTAL_COST + LS_INDIRECT_TOTAL_COST;
	IF LS_TOTAL_COST <> LS_SUM_OF_COST THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'BUDGETPERIOD','VALIDATION','Total cost is not equal to the sum of direct cost and indirect cost',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after total calculation',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE stage_budget_periods
		SET VALIDATION_STATUS = 'VALID',
		FIBI_IDENTIFIER = NULL
		WHERE MIGRATION_BUDGET_PERIOD_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
		END IF;
	ELSE
		UPDATE stage_budget_periods
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = NULL
		WHERE MIGRATION_BUDGET_PERIOD_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
		END IF;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'validation end',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
	END LOOP MIGRATION_BUDGET_PERIOD_CURSOR_LOOP;
	CLOSE MIGRATION_BUDGET_PERIOD_CURSOR;
	IF FOR_AUDIT = 1 THEN
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','BUDGETPERIOD',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_VERSION_NUMBER);
	END IF;
END;
SELECT COUNT(1) INTO DATA_ERROR_COUNT FROM stage_budget_periods WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND VERSION_NUMBER = DATA_VERSION_NUMBER;
COMMIT;
END
$$
DELIMITER ;
