DELIMITER $$
CREATE  PROCEDURE `MIGRATION_QUEST_ANS_HEADER_PREVAL`(DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_STG_QUEST_ANS_HEADER_ID INT;
DECLARE LI_QUESTIONNAIRE_ID int;
DECLARE LI_QUESTIONNAIRE_VERSION_NUMBER smallint;
DECLARE LI_MODULE_ITEM_KEY VARCHAR(8);
DECLARE LS_MODULE_SUB_ITEM_KEY VARCHAR(40);
DECLARE LI_MODULE_SUB_ITEM_CODE SMALLINT;
DECLARE LI_QUESTIONNAIRE_COMPLETION_ID VARCHAR(10);
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1) default 'N';
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (IFNULL(LI_STG_QUEST_ANS_HEADER_ID,0),'QUEST_ANS_HEADER','VALIDATION',CONCAT(LS_ERROR_MSG),UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('QUEST_ANS_HEADER') AND ERROR_TYPE = 'VALIDATION';
			UPDATE stage_quest_answer_header SET VALIDATION_STATUS = NULL where VALIDATION_STATUS = 'ERROR' and MIGRATION_QUEST_ANSWER_HEADER_ID = NULL;
		SET SQL_SAFE_UPDATES = 1;
	END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM migration_qtn_execution_log;
	ALTER TABLE migration_qtn_execution_log AUTO_INCREMENT = 1;
SET SQL_SAFE_UPDATES = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_quest_answer_header;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'QUEST_ANS_HEADER';
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
										VALUES 	(LI_BATCH_ID,'VALIDATION','QUEST_ANS_HEADER',UTC_TIMESTAMP());
	INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : QUEST_ANS_HEADER ',UTC_TIMESTAMP());
END;
		BEGIN
		DECLARE DONE6 INT DEFAULT FALSE;
		DECLARE CUR_QUEST_ANS_HEADER CURSOR FOR
		select ID
				, QUESTIONNAIRE_COMPLETION_ID
				, MODULE_ITEM_KEY
                , MODULE_SUB_ITEM_CODE
                , MODULE_SUB_ITEM_KEY
				, QUESTIONNAIRE_ID
				, QUESTIONNAIRE_VERSION_NUMBER
		from stage_quest_answer_header
        where validation_status is NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE6 = TRUE;
		OPEN CUR_QUEST_ANS_HEADER;
		QUEST_ANS_HEADER_LOOP: LOOP
		FETCH CUR_QUEST_ANS_HEADER INTO
							LI_STG_QUEST_ANS_HEADER_ID
							, LI_QUESTIONNAIRE_COMPLETION_ID
							, LI_MODULE_ITEM_KEY
							, LI_MODULE_SUB_ITEM_CODE
							, LS_MODULE_SUB_ITEM_KEY
							, LI_QUESTIONNAIRE_ID
							, LI_QUESTIONNAIRE_VERSION_NUMBER;
		IF DONE6 THEN
			LEAVE QUEST_ANS_HEADER_LOOP;
		END IF;
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('VALIDATION','QUEST_ANS_HEADER',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LI_QUESTIONNAIRE_COMPLETION_ID);
					SET LS_DATA_ERROR_FLAG = 'N';
					SELECT COUNT(*) INTO LI_COUNT FROM stage_eps_proposal WHERE PROPOSAL_NUMBER = LI_MODULE_ITEM_KEY AND VALIDATION_STATUS IN ('VALID','SUCCESS');
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_QUEST_ANS_HEADER_ID,'QUEST_ANS_HEADER','VALIDATION',CONCAT('Invalid module item key :', LI_MODULE_ITEM_KEY),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
                    IF LI_MODULE_SUB_ITEM_CODE = 6 THEN
						set LI_COUNT = -1;
						SELECT COUNT(*) INTO LI_COUNT FROM stage_eps_prop_investigators
						WHERE proposal_number = LI_MODULE_ITEM_KEY
						and UPPER(PERSON_ID) = UPPER(LS_MODULE_SUB_ITEM_KEY)
						and validation_status in ('VALID', 'SUCCESS');
							IF LI_COUNT <> 1 then
								set LI_COUNT = -1;
								SELECT COUNT(*) INTO LI_COUNT FROM stage_eps_prop_key_persons
								WHERE proposal_number = LI_MODULE_ITEM_KEY
								and UPPER(PERSON_ID) = UPPER(LS_MODULE_SUB_ITEM_KEY)
								and validation_status in ('VALID', 'SUCCESS');
										IF LI_COUNT <> 1 THEN
											INSERT INTO migration_questionnaire_errorlog (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
											VALUES  (LI_STG_QUEST_ANS_HEADER_ID ,'QUEST_ANS_HEADER','VALIDATION',CONCAT('Invalid Proposal Person :  ', LS_MODULE_SUB_ITEM_KEY),UTC_TIMESTAMP(),'JHU_ADMIN');
												SET LS_DATA_ERROR_FLAG = 'Y';
										END if;
							END IF;
					END IF;
					IF (LI_QUESTIONNAIRE_COMPLETION_ID is NULL) THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_QUEST_ANS_HEADER_ID,'QUEST_ANS_HEADER','VALIDATION',CONCAT('Invalid Questionnaire completion id  :  ', LI_QUESTIONNAIRE_COMPLETION_ID ),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
						SELECT COUNT(*) INTO LI_COUNT FROM
						stage_questionnaire WHERE QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID
						AND VERSION_NUMBER = LI_QUESTIONNAIRE_VERSION_NUMBER
                        and validation_status in ('VALID', 'SUCCESS');
							IF LI_COUNT <> 1 THEN
								INSERT INTO migration_questionnaire_errorlog
									(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
								VALUES  (LI_STG_QUEST_ANS_HEADER_ID,'QUEST_ANS_HEADER','VALIDATION',CONCAT('Invalid Questionnaire :  ',  LI_QUESTIONNAIRE_ID,' Version : ',LI_QUESTIONNAIRE_VERSION_NUMBER ),UTC_TIMESTAMP(),'JHU_ADMIN');
								SET LS_DATA_ERROR_FLAG = 'Y';
							END IF;
						IF LS_DATA_ERROR_FLAG = 'Y' THEN
							UPDATE stage_quest_answer_header SET VALIDATION_STATUS = 'ERROR' where ID =  LI_STG_QUEST_ANS_HEADER_ID;
                            UPDATE stage_quest_answer SET VALIDATION_STATUS = 'ERROR' where QUESTIONNAIRE_COMPLETION_ID = LI_QUESTIONNAIRE_COMPLETION_ID;
						ELSE
							UPDATE stage_quest_answer_header SET VALIDATION_STATUS = 'VALID' where ID =  LI_STG_QUEST_ANS_HEADER_ID;
						END IF;
				IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Validated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Questionnaire Answer Header'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('VALIDATION','QUEST_ANS_HEADER',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LI_QUESTIONNAIRE_COMPLETION_ID);
					SET LS_DATA_ERROR_FLAG = 'N';
					set LI_COUNT = NULL;
					set LI_STG_QUEST_ANS_HEADER_ID = NULL;
					set LI_QUESTIONNAIRE_COMPLETION_ID = NULL;
					set LI_MODULE_ITEM_KEY = NULL;
					set LI_QUESTIONNAIRE_ID = NULL;
					set LI_QUESTIONNAIRE_VERSION_NUMBER = NULL;
				END LOOP;
				CLOSE CUR_QUEST_ANS_HEADER;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','QUEST_ANS_HEADER',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
			INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Validated total records ( ', LI_TOTAL_DATA_COUNT,' ) of Questionnaire Answer Header'),UTC_TIMESTAMP()),('Validation completed successfully',UTC_TIMESTAMP());
			END;
		END
$$
DELIMITER ;
