DELIMITER $$
CREATE  PROCEDURE `MIGRATE_PER_CUSTOM_DATA`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_CUSTOM_DATA_ID INT;
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT;
DECLARE LI_COLUMN_ID INT;
DECLARE LI_COLUMN_VERSION_NUMBER INT;
DECLARE LI_MODULE_ITEM_CODE INT;
DECLARE LI_MODULE_SUB_ITEM_CODE INT;
DECLARE LI_PROPOSAL_ID INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_PERSON_ID VARCHAR(9);
DECLARE LS_COLUMN_NAME VARCHAR(30);
DECLARE LS_COLUMN_VALUE VARCHAR(2000);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET fOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_validation_matrix WHERE MODULE_NAME = 'EPSPROPPERCUSTOM';
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'EPSPROPPERCUSTOM' AND ERROR_TYPE = 'MIGRATION';
				UPDATE stage_eps_prop_per_custom_data SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
		END IF;
END;
BEGIN
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM coeus_module WHERE UPPER(DESCRIPTION) = UPPER('development proposal') AND IS_ACTIVE = 'Y';
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'EPSPROPPERCUSTOM','MIGRATION',CONCAT('Invalid module item code : development proposal'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT MODULE_CODE INTO LI_MODULE_ITEM_CODE FROM coeus_module WHERE UPPER(DESCRIPTION) = UPPER('development proposal') AND IS_ACTIVE = 'Y';
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM coeus_module WHERE UPPER(DESCRIPTION) = UPPER('person') AND IS_ACTIVE = 'Y';
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'EPSPROPPERCUSTOM','MIGRATION',CONCAT('Invalid module item code : person'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT MODULE_CODE INTO LI_MODULE_SUB_ITEM_CODE FROM coeus_module WHERE UPPER(DESCRIPTION) = UPPER('person') AND IS_ACTIVE = 'Y';
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_prop_per_custom_data;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'EPSPROPPERCUSTOM';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','EPSPROPPERCUSTOM',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_EPS_PROP_PER_CUSTOM_DATA	CURSOR FOR
	SELECT      MIGRATION_PROP_PER_CUSTOM_DATA_ID,
				PROPOSAL_NUMBER,
				PERSON_ID,
				COLUMN_NAME,
				COLUMN_VALUE,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM  stage_eps_prop_per_custom_data  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'EPSPROPPERCUSTOM','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATION_EPS_PROP_PER_CUSTOM_DATA;
	MIGRATION_EPS_PROP_PER_CUSTOM_DATA_LOOP      : 	LOOP
	FETCH MIGRATION_EPS_PROP_PER_CUSTOM_DATA       	INTO       		LI_RECORD_ID,
																	LS_PROPOSAL_NUMBER,
																	LS_PERSON_ID,
																	LS_COLUMN_NAME,
																	LS_COLUMN_VALUE,
																	LS_UPDATE_TIMESTAMP,
																	LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATION_EPS_PROP_PER_CUSTOM_DATA_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_CUSTOM_DATA_ID = -1;
	SET LI_PROPOSAL_ID = -1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PROPOSAL_NUMBER,@proposal_id);
	IF @proposal_id = -1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'EPSPROPPERCUSTOM','MIGRATION',CONCAT('Invalid proposal number : ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SET LI_PROPOSAL_ID = @proposal_id;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'fetch proposal id',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM custom_data_elements WHERE UPPER(CUSTOM_ELEMENT_NAME) = UPPER(LS_COLUMN_NAME);
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'EPSPROPPERCUSTOM','MIGRATION',CONCAT('Invalid custom element :', LS_COLUMN_NAME),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT CUSTOM_DATA_ELEMENTS_ID,COLUMN_ID,COLUMN_VERSION_NUMBER INTO LI_CUSTOM_DATA_ELEMENTS_ID,LI_COLUMN_ID,LI_COLUMN_VERSION_NUMBER
		FROM custom_data_elements WHERE UPPER(CUSTOM_ELEMENT_NAME) = UPPER(LS_COLUMN_NAME);
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'fetch custom data elements before insert',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1 INTO LI_CUSTOM_DATA_ID
		FROM custom_data;
		INSERT INTO   custom_data
		(
			CUSTOM_DATA_ID,
			CUSTOM_DATA_ELEMENTS_ID,
			MODULE_ITEM_CODE,
			MODULE_SUB_ITEM_CODE,
			MODULE_ITEM_KEY,
			MODULE_SUB_ITEM_KEY,
			VALUE,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			COLUMN_ID,
			COLUMN_VERSION_NUMBER,
			DESCRIPTION
		)
		VALUES
		(
			LI_CUSTOM_DATA_ID,
			LI_CUSTOM_DATA_ELEMENTS_ID,
			LI_MODULE_ITEM_CODE,
			LI_MODULE_SUB_ITEM_CODE,
			LS_PROPOSAL_NUMBER,
			LS_PERSON_ID,
			LS_COLUMN_VALUE,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER,
			LI_COLUMN_ID,
			LI_COLUMN_VERSION_NUMBER,
			NULL
		);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE stage_eps_prop_per_custom_data
		SET VALIDATION_STATUS = 'SUCCESS',
		FIBI_IDENTIFIER = LI_CUSTOM_DATA_ID
		WHERE MIGRATION_PROP_PER_CUSTOM_DATA_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	ELSE
		UPDATE stage_eps_prop_per_custom_data
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = -1
		WHERE MIGRATION_PROP_PER_CUSTOM_DATA_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	END IF;
	IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
		IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
			INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
			SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
		END IF;
	END IF ;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'migration end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END LOOP MIGRATION_EPS_PROP_PER_CUSTOM_DATA_LOOP;
	CLOSE MIGRATION_EPS_PROP_PER_CUSTOM_DATA;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSPROPPERCUSTOM',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM custom_data_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO custom_data_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1  FROM custom_data));
	ELSE
	UPDATE custom_data_id_generator   SET NEXT_VAL = (SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1  FROM custom_data);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET fOREIGN_KEY_CHECKS = 1;
END IF;
END
$$
DELIMITER ;
