DELIMITER $$
CREATE  PROCEDURE `MIGRATE_AWRD_UNITS`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LI_MASTER_AWARD_ID INT;
DECLARE LI_AWARD_ID INT;
DECLARE LI_AWARD_PERSON_UNIT_ID INT;
DECLARE LI_MAS_AWARD_PERSON_UNIT_ID INT;
DECLARE LI_AWARD_PERSON_ID INT;
DECLARE LI_MAS_AWARD_PERSON_ID INT;
DECLARE LS_LEAD_UNIT_FLAG VARCHAR(1);
DECLARE LS_JHU_AWARD_NUMBER CHAR(10);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_UNIT_NUMBER VARCHAR(8);
DECLARE LS_PERSON_ID VARCHAR(9);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_CHILD_ERROR_MESSAGE VARCHAR(500);
DECLARE LS_CHILD_ERROR VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
			DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'AWRDUNIT' AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_award_units SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
		END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'AWRDUNIT';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','AWRDUNIT',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_AWARD_UNIT_CURSOR CURSOR FOR
		SELECT  MIGRATION_AWARD_UNIT_ID,
				MIT_AWARD_NUMBER,
				SEQUENCE_NUMBER,
				PERSON_ID,
				UNIT_NUMBER,
				LEAD_UNIT_FLAG,
				UPDATE_TIMESTAMP,
				UPDATE_USER
		FROM  stage_award_units WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
			OPEN MIGRATION_AWARD_UNIT_CURSOR;
			MIGRATION_AWARD_UNIT_CURSOR_LOOP :    		LOOP
				FETCH MIGRATION_AWARD_UNIT_CURSOR 		INTO     		LI_RECORD_ID,
																		LS_JHU_AWARD_NUMBER,
																		LI_SEQUENCE_NUMBER,
																		LS_PERSON_ID,
																		LS_UNIT_NUMBER,
																		LS_LEAD_UNIT_FLAG,
																		LS_UPDATE_TIMESTAMP,
																		LS_UPDATE_USER;
					IF DONE1 THEN
						LEAVE MIGRATION_AWARD_UNIT_CURSOR_LOOP;
					END IF;
					SET LS_DATA_ERROR_FLAG = 'N';
					SET LI_AWARD_ID = -1;
					SET LI_AWARD_PERSON_UNIT_ID = -1;
					SET LI_MAX_SEQUENCE_NUMBER = -1;
					SET LI_MASTER_AWARD_ID = -1;
					SET LI_MAS_AWARD_PERSON_UNIT_ID = -1;
					SET LI_AWARD_PERSON_ID = -1;
					SET LI_MAS_AWARD_PERSON_ID = -1;
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
					SET LS_AWARD_NUMBER = REPLACE(LS_JHU_AWARD_NUMBER,'-','-00');
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,CONCAT('Changed award number',LS_AWARD_NUMBER),UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					-- award number
					SELECT COUNT(1) INTO LI_COUNT FROM
					award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',CONCAT('Invalid award number :', LS_AWARD_NUMBER),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					ELSE
						SELECT IFNULL(MAX(SEQUENCE_NUMBER),-1) INTO LI_MAX_SEQUENCE_NUMBER FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
						IF LI_MAX_SEQUENCE_NUMBER <> -1 THEN
							SELECT AWARD_ID INTO LI_AWARD_ID FROM
							award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER;
						ELSE
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',CONCAT('Invalid sequence number :', LI_MAX_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
						END IF;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after award check',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
					END IF;
					-- Person id
					/*SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND PERSON_ID = LS_PERSON_ID;
					IF LI_COUNT = 0 THEN
						SET LI_COUNT = -1;
						SELECT COUNT(1) INTO LI_COUNT FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND ROLODEX_ID = LS_PERSON_ID;
						IF LI_COUNT = 0 THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',IFNULL(CONCAT('Invalid person/rolodex id :', LS_PERSON_ID),'Person/Rolodex Id is mandatory and cannot be NULL'),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
						ELSE
							SELECT AWARD_PERSON_ID INTO LI_AWARD_PERSON_ID FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND ROLODEX_ID = LS_PERSON_ID;
						END IF;
					ELSE
						SELECT AWARD_PERSON_ID INTO LI_AWARD_PERSON_ID FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND PERSON_ID = LS_PERSON_ID;
					END IF;*/
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after award person check',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
					END IF;
					-- Duplicate entry check
					/*SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM award_person_unit WHERE AWARD_ID = LI_AWARD_ID AND AWARD_PERSON_ID = LI_AWARD_PERSON_ID AND AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND UNIT_NUMBER = LS_UNIT_NUMBER;
					IF LI_COUNT > 0 THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',CONCAT('Data already exists for the award number : ',LS_AWARD_NUMBER,' and sequence number :',LI_MAX_SEQUENCE_NUMBER,' and award person id : ',LI_AWARD_PERSON_ID,' and the unit number : ',LS_UNIT_NUMBER),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after duplicate entry check ',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
					END IF;*/
					/*IF LS_DATA_ERROR_FLAG = 'N' THEN
						SELECT IFNULL(MAX(AWARD_PERSON_UNIT_ID),0) + 1 INTO LI_AWARD_PERSON_UNIT_ID FROM award_person_unit;
						INSERT INTO award_person_unit
						(
							AWARD_PERSON_UNIT_ID,
							AWARD_PERSON_ID,
							AWARD_ID,
							AWARD_NUMBER,
							SEQUENCE_NUMBER,
							UNIT_NUMBER,
							LEAD_UNIT_FLAG,
							UPDATE_TIMESTAMP,
							UPDATE_USER
						)
						VALUES
						(
							LI_AWARD_PERSON_UNIT_ID,
							LI_AWARD_PERSON_ID,
							LI_AWARD_ID,
							LS_AWARD_NUMBER,
							LI_MAX_SEQUENCE_NUMBER,
							LS_UNIT_NUMBER,
							LS_LEAD_UNIT_FLAG,
							LS_UPDATE_TIMESTAMP,
							LS_UPDATE_USER
						);
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after insert',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
						END IF;
					END IF;*/
					-- master logic
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'master data logic begin',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
						END IF;
							SET LI_COUNT = -1;
							SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
							IF LI_COUNT = 0 THEN
								INSERT INTO migration_transaction_errorlog
									(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
								VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',CONCAT('Invalid master award data with award number :', LS_AWARD_NUMBER,' and the sequence number : 0'),UTC_TIMESTAMP(),'quickstart');
								SET LS_DATA_ERROR_FLAG = 'Y';
							ELSE
								SELECT AWARD_ID INTO LI_MASTER_AWARD_ID FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
							END IF;
							-- Person id
							SET LI_COUNT = -1;
							SELECT COUNT(1) INTO LI_COUNT FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0 AND PERSON_ID = LS_PERSON_ID;
							IF LI_COUNT = 0 THEN
								SET LI_COUNT = -1;
								SELECT COUNT(1) INTO LI_COUNT FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0 AND ROLODEX_ID = LS_PERSON_ID;
								IF LI_COUNT = 0 THEN
									INSERT INTO migration_transaction_errorlog
										(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
									VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',IFNULL(CONCAT('Invalid person/rolodex id :', LS_PERSON_ID),'Person/Rolodex Id is mandatory and cannot be NULL'),UTC_TIMESTAMP(),'quickstart');
									SET LS_DATA_ERROR_FLAG = 'Y';
								ELSE
									SELECT AWARD_PERSON_ID INTO LI_MAS_AWARD_PERSON_ID FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0 AND ROLODEX_ID = LS_PERSON_ID;
								END IF;
							ELSE
								SELECT AWARD_PERSON_ID INTO LI_MAS_AWARD_PERSON_ID FROM award_persons WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0 AND PERSON_ID = LS_PERSON_ID;
							END IF;
							-- Duplicate entry check
							SET LI_COUNT = -1;
							SELECT COUNT(1) INTO LI_COUNT FROM award_person_unit WHERE AWARD_ID = LI_MASTER_AWARD_ID AND AWARD_PERSON_ID = LI_MAS_AWARD_PERSON_ID AND AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0 AND UNIT_NUMBER = LS_UNIT_NUMBER;
							IF LI_COUNT > 0 THEN
								INSERT INTO migration_transaction_errorlog
									(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
								VALUES  (LI_RECORD_ID,'AWRDUNIT','MIGRATION',CONCAT('Data already exists for the award number : ',LS_AWARD_NUMBER,' and sequence number : 0',' and award person id : ',LI_MAS_AWARD_PERSON_ID,' and the unit number : ',LS_UNIT_NUMBER),UTC_TIMESTAMP(),'quickstart');
								SET LS_DATA_ERROR_FLAG = 'Y';
							END IF;
							IF FOR_AUDIT = 1 THEN
								INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after duplicate entry check ',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
							END IF;
							IF LS_DATA_ERROR_FLAG = 'N' THEN
								SELECT IFNULL(MAX(AWARD_PERSON_UNIT_ID),0) + 1 INTO LI_MAS_AWARD_PERSON_UNIT_ID FROM award_person_unit;
								INSERT INTO award_person_unit
								(
									AWARD_PERSON_UNIT_ID,
									AWARD_PERSON_ID,
									AWARD_ID,
									AWARD_NUMBER,
									SEQUENCE_NUMBER,
									UNIT_NUMBER,
									LEAD_UNIT_FLAG,
									UPDATE_TIMESTAMP,
									UPDATE_USER
								)
								VALUES
								(
									LI_MAS_AWARD_PERSON_UNIT_ID,
									LI_MAS_AWARD_PERSON_ID,
									LI_MASTER_AWARD_ID,
									LS_AWARD_NUMBER,
									0,
									LS_UNIT_NUMBER,
									LS_LEAD_UNIT_FLAG,
									LS_UPDATE_TIMESTAMP,
									LS_UPDATE_USER
								);
							END IF;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'master data logic end',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
						END IF;
					END IF;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_award_units
						SET VALIDATION_STATUS = 'SUCCESS',
						FIBI_IDENTIFIER = LI_MAS_AWARD_PERSON_UNIT_ID
						WHERE MIGRATION_AWARD_UNIT_ID = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
						END IF;
					ELSE
						UPDATE stage_award_units
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = -1
						WHERE MIGRATION_AWARD_UNIT_ID  = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
						END IF;
					END IF;
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'validation end',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
			END LOOP MIGRATION_AWARD_UNIT_CURSOR_LOOP;
			CLOSE MIGRATION_AWARD_UNIT_CURSOR;
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDUNIT',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
		END;
		SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award_person_unit_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO award_person_unit_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(AWARD_PERSON_UNIT_ID),0) + 1  FROM award_person_unit));
	ELSE
	UPDATE award_person_unit_id_generator   SET NEXT_VAL = (SELECT IFNULL(MAX(AWARD_PERSON_UNIT_ID),0) + 1  FROM award_person_unit);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
		COMMIT;
END
$$
DELIMITER ;
