DELIMITER $$
CREATE  PROCEDURE `MIGRATION_QUEST_PREVAL`(DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_STG_GROUP_TYPE_ID INT;
DECLARE LI_STG_QUESTION_ID INT;
DECLARE LI_QUESTION_ID INT;
DECLARE LS_QUESTION VARCHAR(2000);
DECLARE LI_QUESTION_VERSION_NUMBER INT;
DECLARE LI_GROUP_TYPE_CODE SMALLINT;
DECLARE LI_STG_QUESTIONNAIRE_ID INT;
DECLARE LI_QUESTIONNAIRE_ID INT;
DECLARE LI_QUESTIONNAIRE_VERSION_NUMBER INT;
DECLARE LI_STG_QUEST_QTN_ID INT;
DECLARE LI_PARENT_QUESTION_NUMBER INT;
DECLARE LI_STG_QUEST_USAGE_ID INT;
DECLARE LI_MODULE_ITEM_CODE SMALLINT;
DECLARE LI_MODULE_SUB_ITEM_CODE SMALLINT;
DECLARE LI_RULE_ID INT ;
DECLARE LI_STG_QUEST_ANS_HEADER_ID INT;
DECLARE LI_MODULE_ITEM_KEY INT;
DECLARE LI_QUESTIONNAIRE_COMPLETION_ID VARCHAR(10);
DECLARE LI_STG_QUEST_ANSWER_ID INT;
DECLARE LS_ANSWER VARCHAR(2000);
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_STG_QUESTIONNAIRE_ID,'QUEST_QUESTIONNAIRE','VALIDATION',CONCAT(LS_ERROR_MSG),UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('QUEST_QUESTIONNAIRE') AND ERROR_TYPE = 'VALIDATION';
			UPDATE stage_questionnaire SET VALIDATION_STATUS = NULL where VALIDATION_STATUS = 'ERROR' and  MIGRATED_QUESTIONNAIRE_ID = NULL;
		SET SQL_SAFE_UPDATES = 1;
	END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM migration_qtn_execution_log;
	ALTER TABLE migration_qtn_execution_log AUTO_INCREMENT = 1;
SET SQL_SAFE_UPDATES = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_questionnaire;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'QUEST_QUESTIONNAIRE';
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
										VALUES 	(LI_BATCH_ID,'VALIDATION','QUEST_QUESTIONNAIRE',UTC_TIMESTAMP());
	INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : QUEST_QUESTIONNAIRE ',UTC_TIMESTAMP());
END;
		BEGIN
		DECLARE DONE3 INT DEFAULT FALSE;
		DECLARE CUR_QUESTIONNAIRE CURSOR FOR
		select ID
				, QUESTIONNAIRE_ID
				, VERSION_NUMBER
				, GROUP_TYPE_CODE
		from stage_questionnaire
        where validation_status is null;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
		OPEN CUR_QUESTIONNAIRE;
		QUESTIONNAIRE_LOOP: LOOP
		FETCH CUR_QUESTIONNAIRE INTO
							LI_STG_QUESTIONNAIRE_ID
							, LI_QUESTIONNAIRE_ID
							,LI_QUESTIONNAIRE_VERSION_NUMBER
							,LI_GROUP_TYPE_CODE;
		IF DONE3 THEN
			LEAVE QUESTIONNAIRE_LOOP;
		END IF;
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('VALIDATION','QUEST_QUESTIONNAIRE',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LI_QUESTIONNAIRE_ID);
					SET LS_DATA_ERROR_FLAG = 'N';
					IF LI_QUESTIONNAIRE_ID is NULL THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_QUESTIONNAIRE_ID,'QUEST_QUESTIONNAIRE','VALIDATION',CONCAT('Invalid Questionnaire ID :  ', LI_QUESTIONNAIRE_ID),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF (LI_QUESTIONNAIRE_VERSION_NUMBER is NULL and LI_QUESTIONNAIRE_VERSION_NUMBER < 1) THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_QUESTIONNAIRE_ID,'QUEST_QUESTIONNAIRE','VALIDATION',CONCAT('Invalid questionnaire version number :  ', LI_QUESTIONNAIRE_VERSION_NUMBER, 'of questionnaire : ',LI_QUESTIONNAIRE_ID ),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF LS_DATA_ERROR_FLAG = 'Y' THEN
						SET SQL_SAFE_UPDATES = 0;
						UPDATE stage_questionnaire SET VALIDATION_STATUS = 'ERROR' where ID =  LI_STG_QUESTIONNAIRE_ID;
						UPDATE stage_quest_usage SET VALIDATION_STATUS = 'ERROR'  where QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID and VERSION_NUMBER = LI_QUESTIONNAIRE_VERSION_NUMBER;
						update stage_quest_questions set  VALIDATION_STATUS = 'ERROR' where QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID and QUESTIONNAIRE_VERSION_NUMBER = LI_QUESTIONNAIRE_VERSION_NUMBER;
						update stage_quest_answer_header set  VALIDATION_STATUS = 'ERROR' where QUESTIONNAIRE_ID  = LI_QUESTIONNAIRE_ID and QUESTIONNAIRE_VERSION_NUMBER = LI_QUESTIONNAIRE_VERSION_NUMBER;
						update stage_quest_answer set  validation_status = 'ERROR' where QUESTIONNAIRE_COMPLETION_ID in (select QUESTIONNAIRE_COMPLETION_ID from stage_quest_answer_header where QUESTIONNAIRE_ID  = LI_QUESTIONNAIRE_ID and QUESTIONNAIRE_VERSION_NUMBER = LI_QUESTIONNAIRE_VERSION_NUMBER);
					ELSE
						UPDATE stage_questionnaire SET VALIDATION_STATUS = 'VALID' where ID =  LI_STG_QUESTIONNAIRE_ID;
					END IF;
				IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Validated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Questionnaire'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('VALIDATION','QUEST_QUESTIONNAIRE',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LI_QUESTIONNAIRE_ID);
				set LI_COUNT = NULL;
				set LI_STG_QUESTIONNAIRE_ID = NULL;
				set LI_QUESTIONNAIRE_ID = NULL;
				set LI_GROUP_TYPE_CODE = NULL;
			END LOOP;
			CLOSE CUR_QUESTIONNAIRE;
			INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','QUEST_QUESTIONNAIRE',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
			INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Validated total records ( ', LI_TOTAL_DATA_COUNT,' ) of Questionnaire'),UTC_TIMESTAMP()),('Validation completed successfully',UTC_TIMESTAMP());
			END;
			END
$$
DELIMITER ;
