DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_EPS_PROP_ATTACH`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LS_PROPOSAL_NUMBER varchar(8);
DECLARE LI_MODULE_NUMBER INT;
DECLARE LI_PROPOSAL_ID INT;
DECLARE LI_NARRATIVE_TYPE_CODE INT;
DECLARE LS_MODULE_TITLE varchar(150);
DECLARE LS_FILE_NAME varchar(150);
DECLARE LS_MIME_TYPE varchar(100);
DECLARE LS_UPDATE_TIMESTAMP DATETIME ;
DECLARE LS_UPDATE_USER varchar(8);
DECLARE LS_MODULE_STATUS_CODE  varchar(1);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_CONTENT_DATA LONGBLOB;
DECLARE UNIQUE_ID VARCHAR(36);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_PROPOSAL_ID varchar(8);
DECLARE LI_PROPOSAL_ATT_ID INT;
DECLARE LI_ATTACHMENT_ID INT;
DECLARE LI_DOCUMENT_ID INT;
DECLARE LS_ERROR VARCHAR(2000);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	SET LS_DATA_ERROR_FLAG = 'N';
		IF DATA_REFRESH_FLAG = 1 THEN
				-- DELETE FROM migration_validation_matrix WHERE MODULE_NAME = 'DEVPROPATTACH';
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'DEVPROPATTACH' AND ERROR_TYPE = 'MIGRATION';
				UPDATE stage_eps_proposal_attachment SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
		END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_proposal_attachment;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'DEVPROPATTACH';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','DEVPROPATTACH',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_PROP_ATTACHMENT_CURSOR CURSOR FOR
	SELECT     MIGRATION_DEV_PROP_ATTACH_ID,
				PROPOSAL_NUMBER,
				MODULE_NUMBER,
				NARRATIVE_TYPE_CODE ,
				MODULE_TITLE,
				MODULE_STATUS_CODE,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM 	stage_eps_proposal_attachment WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL LIMIT 1;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO MIGRATION_TRANSACTION_ERRORLOG
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'DEVPROPATTACH ','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATION_PROP_ATTACHMENT_CURSOR;
	MIGRATION_PROP_ATTACHMENT_CURSOR_LOOP      : LOOP
	FETCH MIGRATION_PROP_ATTACHMENT_CURSOR       INTO     	  LI_RECORD_ID,
	                                                          LS_PROPOSAL_NUMBER,
	                                                          LI_MODULE_NUMBER,
	                                                          LI_NARRATIVE_TYPE_CODE ,
	                                                          LS_MODULE_TITLE,
															  LS_MODULE_STATUS_CODE,
															  LS_UPDATE_TIMESTAMP,
															  LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATION_PROP_ATTACHMENT_CURSOR_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_ATTACHMENT_ID = -1;
	SET LI_COUNT = -1;
	SET LI_PROPOSAL_ID = -1;
	SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM stage_eps_prop_attach_blob WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND MODULE_NUMBER = LI_MODULE_NUMBER;
	IF LI_COUNT > 0 THEN
		SELECT FILE_NAME,NARRATIVE_PDF,MIME_TYPE INTO LS_FILE_NAME,LS_CONTENT_DATA,LS_MIME_TYPE
		FROM stage_eps_prop_attach_blob WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND MODULE_NUMBER = LI_MODULE_NUMBER;
	ELSE
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'DEVPROPATTACH','MIGRATION','File data is not available',UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'after blob data fetch',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PROPOSAL_NUMBER,@proposal_id);
	IF @proposal_id = -1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'DEVPROPATTACH','MIGRATION',CONCAT('Invalid proposal number : ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SET LI_PROPOSAL_ID = @proposal_id;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'fetch proposal id',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	SELECT IFNULL(MAX(DOCUMENT_ID),0) + 1 INTO LI_DOCUMENT_ID
	FROM EPS_PROPOSAL_ATTACHMENTS WHERE PROPOSAL_ID = LS_PROPOSAL_NUMBER;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'document id logic and before insert',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(ATTACHMENT_ID),0) + 1 INTO LI_ATTACHMENT_ID
		FROM EPS_PROPOSAL_ATTACHMENTS;
		SELECT UUID() INTO UNIQUE_ID FROM DUAL;
		INSERT INTO EPS_PROPOSAL_ATTACHMENTS
		(
			ATTACHMENT_ID,
			ATTACHMNT_TYPE_CODE,
			DESCRIPTION,
			FILE_NAME,
			MIME_TYPE,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			PROPOSAL_ID,
			NARRATIVE_STATUS_CODE,
			VERSION_NUMBER,
			FILE_DATA_ID,
			DOCUMENT_STATUS_CODE,
			DOCUMENT_ID
		)
		VALUES
		(
			LI_ATTACHMENT_ID,
			LI_NARRATIVE_TYPE_CODE ,
			LS_MODULE_TITLE ,
			LS_FILE_NAME,
			LS_MIME_TYPE,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER,
			LI_PROPOSAL_ID,
			LS_MODULE_STATUS_CODE,
			1,
			UNIQUE_ID,
			1,
			LI_DOCUMENT_ID
		);
	END IF;
	 IF LS_DATA_ERROR_FLAG = 'N' THEN
		 INSERT INTO FILE_DATA (ID,DATA,MODULE_CODE,FILE_PATH,ORIGINAL_FILE_NAME,FILE_NAME,IS_ARCHIVED,UPDATE_TIMESTAMP,UPDATE_USER) VALUES(UNIQUE_ID,LS_CONTENT_DATA,3,NULL,NULL,LS_FILE_NAME,NULL,LS_UPDATE_TIMESTAMP,LS_UPDATE_USER);
	 END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'after file data',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE STAGE_EPS_PROPOSAL_ATTACHMENT
		SET VALIDATION_STATUS = 'SUCCESS',
		FIBI_IDENTIFIER = LI_ATTACHMENT_ID
		WHERE MIGRATION_DEV_PROP_ATTACH_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	ELSE
		UPDATE STAGE_EPS_PROPOSAL_ATTACHMENT
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = -1
		WHERE MIGRATION_DEV_PROP_ATTACH_ID = LI_RECORD_ID;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	END IF;
	IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
		IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
			INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
			SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
		END IF;
	END IF ;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'migration end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
	END LOOP MIGRATION_PROP_ATTACHMENT_CURSOR_LOOP;
	CLOSE MIGRATION_PROP_ATTACHMENT_CURSOR;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPATTACH',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM EPS_PROP_ATTACH_ID_GENERATOR;
	IF LI_COUNT = 0 THEN
		INSERT INTO EPS_PROP_ATTACH_ID_GENERATOR  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(ATTACHMENT_ID),0) + 1  FROM EPS_PROPOSAL_ATTACHMENTS));
	ELSE
		UPDATE EPS_PROP_ATTACH_ID_GENERATOR   SET NEXT_VAL = (SELECT IFNULL(MAX(ATTACHMENT_ID),0) + 1  FROM EPS_PROPOSAL_ATTACHMENTS);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed Successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END
$$
DELIMITER ;
