DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_BUDGET_RATES`(DATA_PROPOSAL_NUMBER VARCHAR(8), DATA_VERSION_NUMBER INT,DATA_BUDGET_HEADER_ID INT, OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_PROPOSAL_RATE_ID INT;
DECLARE LI_ACTIVITY_TYPE_CODE INT;
DECLARE LI_VERSION_NUMBER INT;
DECLARE LI_BUDGET_HEADER_ID INT;
DECLARE LI_RATE_TYPE_CODE INT;
DECLARE LI_RATE_CLASS_CODE INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_FISCAL_YEAR VARCHAR(4);
DECLARE LS_ON_OFF_CAMPUS_FLAG VARCHAR(1);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_START_DATE DATETIME;
DECLARE LS_APPLICABLE_RATE DECIMAL(12, 2);
DECLARE LS_INSTITUTE_RATE DECIMAL(12, 2);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_EPS_PROP_RATES_CURSOR CURSOR FOR
	SELECT      MIGRATION_PROP_RATE_ID,
				PROPOSAL_NUMBER,
				VERSION_NUMBER,
				RATE_CLASS_CODE,
				RATE_TYPE_CODE,
				FISCAL_YEAR,
				ON_OFF_CAMPUS_FLAG,
				ACTIVITY_TYPE_CODE,
				START_DATE,
				APPLICABLE_RATE,
				INSTITUTE_RATE,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM  stage_eps_proposal_rates  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = VERSION_NUMBER AND VERSION_NUMBER = DATA_VERSION_NUMBER;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'EPSPROPRATE','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
		COMMIT;
	END;
	OPEN MIGRATION_EPS_PROP_RATES_CURSOR;
	MIGRATION_EPS_PROP_RATES_CURSOR_LOOP         :     LOOP
	FETCH MIGRATION_EPS_PROP_RATES_CURSOR       	   INTO       	LI_RECORD_ID,
																	LS_PROPOSAL_NUMBER,
																	LI_VERSION_NUMBER,
																	LI_RATE_CLASS_CODE,
																	LI_RATE_TYPE_CODE,
																	LS_FISCAL_YEAR,
																	LS_ON_OFF_CAMPUS_FLAG,
																	LI_ACTIVITY_TYPE_CODE,
																	LS_START_DATE,
																	LS_APPLICABLE_RATE,
																	LS_INSTITUTE_RATE,
																	LS_UPDATE_TIMESTAMP,
																	LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATION_EPS_PROP_RATES_CURSOR_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_BUDGET_HEADER_ID = -1;
	SET LI_PROPOSAL_RATE_ID = -1;
	SET LI_COUNT = -1;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(PROPOSAL_RATE_ID),0) + 1 INTO LI_PROPOSAL_RATE_ID
		FROM eps_proposal_rates;
		INSERT INTO  eps_proposal_rates
		(
			PROPOSAL_RATE_ID,
			ACTIVITY_TYPE_CODE,
			APPLICABLE_RATE,
			FISCAL_YEAR,
			INSTITUTE_RATE,
			ON_OFF_CAMPUS_FLAG,
			RATE_CLASS_CODE,
			RATE_TYPE_CODE,
			START_DATE,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			BUDGET_HEADER_ID
		)
		VALUES
		(
			LI_PROPOSAL_RATE_ID,
			LI_ACTIVITY_TYPE_CODE,
			LS_APPLICABLE_RATE,
			LS_FISCAL_YEAR,
			LS_INSTITUTE_RATE,
			LS_ON_OFF_CAMPUS_FLAG,
			LI_RATE_CLASS_CODE,
			LI_RATE_TYPE_CODE,
			LS_START_DATE,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER,
			DATA_BUDGET_HEADER_ID
		);
		UPDATE stage_eps_proposal_rates
		SET VALIDATION_STATUS = 'SUCCESS',
		FIBI_IDENTIFIER = LI_PROPOSAL_RATE_ID
		WHERE MIGRATION_PROP_RATE_ID = LI_RECORD_ID;
	ELSE
		UPDATE stage_eps_proposal_rates
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = -1
		WHERE MIGRATION_PROP_RATE_ID = LI_RECORD_ID;
	END IF;
	END LOOP MIGRATION_EPS_PROP_RATES_CURSOR_LOOP;
	CLOSE MIGRATION_EPS_PROP_RATES_CURSOR;
	COMMIT;
END;
	SET SQL_SAFE_UPDATES = 0;
	SELECT COUNT(*) INTO DATA_ERROR_COUNT FROM  stage_eps_proposal_rates WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1 AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND VERSION_NUMBER = DATA_VERSION_NUMBER;
	COMMIT;
END
$$
DELIMITER ;
