DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_EPS_PROP_KP`(DATA_PROPOSAL_NUMBER VARCHAR(8),DATA_PROPOSAL_ID INT,FOR_AUDIT INT,OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_PROPOSAL_PERSON_ID INT;
DECLARE LI_PROP_PERSON_ROLE_ID INT;
DECLARE LI_PROP_PERSON_PI_ROLE_ID INT;
DECLARE LI_PROP_PERSON_COI_ROLE_ID INT;
DECLARE LI_PROP_PERSON_KP_ROLE_ID INT;
DECLARE LS_DEPARTMENT VARCHAR(90);
DECLARE LS_FULL_NAME VARCHAR(90);
DECLARE LS_UNIT_NAME VARCHAR(100);
DECLARE LS_UNIT_NUMBER VARCHAR(8);
DECLARE LS_PERSON_ID VARCHAR(8);
DECLARE LS_ROLODEX_ID VARCHAR(8);
DECLARE LS_UPDATE_USER VARCHAR(60);
DECLARE LS_EMAIL_ADDRESS VARCHAR(255);
DECLARE LS_PI_FLAG VARCHAR(1);
DECLARE LS_DESIGNATION VARCHAR(255);
DECLARE LS_MULTI_PI VARCHAR(255);
DECLARE LS_NON_MIT_FLAG VARCHAR(1);
DECLARE LS_PROJECT_ROLE VARCHAR(60);
DECLARE LS_SOURCE_TYPE VARCHAR(20);
DECLARE LS_PERSON_TYPE VARCHAR(20);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_PERCENTAGE_EFFORT DECIMAL(5, 2);
DECLARE LS_PERCENTAGE_OF_EFFORT DECIMAL(5,2);
DECLARE LS_ACADEMIC_YEAR_EFFORT DECIMAL(5,2);
DECLARE LS_CALENDAR_YEAR_EFFORT DECIMAL(5,2);
DECLARE LS_SUMMER_YEAR_EFFORT DECIMAL(5,2);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT1 INT;
DECLARE LI_SOURCE_COUNT2 INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_DATA_EXIST_FLAG VARCHAR(1);
DECLARE LS_DELETED_DATA VARCHAR(1);
DECLARE LS_VALIDATION_STATUS VARCHAR(10);
DECLARE LS_CHILD_ERROR_MESSAGE VARCHAR(500);
DECLARE LS_CHILD_ERROR VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
    SET LI_COUNT = -1;
    SET LS_DATA_ERROR_FLAG = 'N';
    SELECT COUNT(*) INTO LI_COUNT FROM eps_prop_person_role WHERE UPPER(DESCRIPTION) = UPPER('Key Study Person') AND IS_ACTIVE = 'Y';
    IF LI_COUNT <> 1 THEN
        INSERT INTO migration_transaction_errorlog
            (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
        VALUES  (-100,'EPSKEYPERSON','MIGRATION',CONCAT('Invalid proposal role : Key Study Person'),UTC_TIMESTAMP(),'quickstart');
        SET LS_DATA_ERROR_FLAG = 'Y';
    ELSE
        SELECT PROP_PERSON_ROLE_ID INTO LI_PROP_PERSON_KP_ROLE_ID FROM eps_prop_person_role WHERE UPPER(DESCRIPTION) = UPPER('Key Study Person') AND IS_ACTIVE = 'Y';
    END IF;
    SELECT IFNULL(MAX(BATCH_ID),0) INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'EPSKEYPERSON';
    INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
    DECLARE LS_ERROR VARCHAR(2000);
    DECLARE DONE1 INT DEFAULT FALSE;
    DECLARE MIGRATION_DEV_PROP_PERSON_CURSOR CURSOR FOR
        SELECT  MIGRATION_KEY_PERSON_ID,
                PERSON_ID,
                NON_MIT_PERSON_FLAG,
                PERSON_NAME,
                PERCENTAGE_EFFORT,
                PROJECT_ROLE,
                UPDATE_TIMESTAMP,
                UPDATE_USER
        FROM  stage_eps_prop_key_persons WHERE PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL ;
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
        DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
        GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
         @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
        SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
        SELECT @full_error INTO LS_ERROR;
        INSERT INTO migration_transaction_errorlog
            (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
        VALUES  (LI_RECORD_ID,'EPSKEYPERSON','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
        SET LS_DATA_ERROR_FLAG = 'Y';
    END;
    OPEN MIGRATION_DEV_PROP_PERSON_CURSOR;
    MIGRATION_DEV_PROP_PERSON_CURSOR_LOOP :           LOOP
    FETCH MIGRATION_DEV_PROP_PERSON_CURSOR            INTO          LI_RECORD_ID,
                                                                    LS_PERSON_ID,
                                                                    LS_NON_MIT_FLAG,
                                                                    LS_FULL_NAME,
                                                                    LS_PERCENTAGE_EFFORT,
                                                                    LS_PROJECT_ROLE,
                                                                    LS_UPDATE_TIMESTAMP,
                                                                    LS_UPDATE_USER;
    IF DONE1 THEN
        LEAVE MIGRATION_DEV_PROP_PERSON_CURSOR_LOOP;
    END IF;
    SET LS_DATA_ERROR_FLAG = 'N';
    SET LS_DATA_EXIST_FLAG = 'N';
    SET LS_UNIT_NAME = NULL;
    SET LI_PROPOSAL_PERSON_ID = -1;
    SET LI_COUNT = -1;
    SET LS_UNIT_NUMBER = '0';
    SELECT COUNT(1) INTO LI_COUNT FROM stage_eps_prop_person WHERE
    PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = LS_PERSON_ID;
    IF LI_COUNT > 0 THEN
        SELECT DIRECTORY_DEPARTMENT,EMAIL_ADDRESS,PRIMARY_TITLE
        INTO LS_DEPARTMENT,LS_EMAIL_ADDRESS,LS_DESIGNATION FROM stage_eps_prop_person WHERE
        PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = LS_PERSON_ID;
    END IF;
    IF FOR_AUDIT = 1 THEN
        INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'fetch from osp$eps_prop_person',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
    END IF;
    IF LS_NON_MIT_FLAG = 'N' THEN
        SET LI_COUNT = -1;
        SELECT COUNT(1) INTO LI_COUNT FROM eps_proposal_persons WHERE PROPOSAL_ID = DATA_PROPOSAL_NUMBER AND PERSON_ID = LS_PERSON_ID;
        IF LI_COUNT > 0 THEN
            INSERT INTO migration_transaction_errorlog
                (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
            VALUES  (LI_RECORD_ID,'EPSKEYPERSON','MIGRATION',CONCAT('Data already exist for the proposal number :  ',DATA_PROPOSAL_NUMBER, ' and the person id : ', LS_PERSON_ID),UTC_TIMESTAMP(),'quickstart');
            SET LS_DATA_ERROR_FLAG = 'Y';
            SET LS_DATA_EXIST_FLAG = 'Y';
        END IF;
    ELSE
        SET LI_COUNT = -1;
        SELECT COUNT(1) INTO LI_COUNT FROM eps_proposal_persons WHERE PROPOSAL_ID = DATA_PROPOSAL_NUMBER AND ROLODEX_ID = LS_PERSON_ID;
        IF LI_COUNT > 0 THEN
            INSERT INTO migration_transaction_errorlog
                (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
            VALUES  (LI_RECORD_ID,'EPSKEYPERSON','MIGRATION',CONCAT('Data already exist for the proposal number :  ',DATA_PROPOSAL_NUMBER, ' and the rolodex id : ', LS_PERSON_ID),UTC_TIMESTAMP(),'quickstart');
            SET LS_DATA_ERROR_FLAG = 'Y';
            SET LS_DATA_EXIST_FLAG = 'Y';
        END IF;
    END IF;
    IF FOR_AUDIT = 1 THEN
        INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'Before insert',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
    END IF;
    IF LS_DATA_ERROR_FLAG = 'N' THEN
        SELECT IFNULL(MAX(PROPOSAL_PERSON_ID),0) + 1 INTO LI_PROPOSAL_PERSON_ID
        FROM eps_proposal_persons;
        INSERT INTO   eps_proposal_persons
        (
            PROPOSAL_PERSON_ID,
            DEPARTMENT,
            FULL_NAME,
            UNIT_NAME,
            UNIT_NUMBER,
            PERSON_ID,
            PROP_PERSON_ROLE_ID,
            ROLODEX_ID,
            UPDATE_TIMESTAMP,
            UPDATE_USER,
            PROPOSAL_ID,
            PERCENTAGE_OF_EFFORT,
            EMAIL_ADDRESS,
            PI_FLAG,
            DESIGNATION,
            IS_MULTI_PI,
            PROJECT_ROLE,
            IS_TRAINING_COMPLETED
        )
        VALUES
        (
            LI_PROPOSAL_PERSON_ID,
            LS_DEPARTMENT,
            LS_FULL_NAME,
            NULL,
            NULL,
            CASE WHEN LS_NON_MIT_FLAG = 'N' THEN LS_PERSON_ID ELSE NULL END,
            LI_PROP_PERSON_KP_ROLE_ID,
            CASE WHEN LS_NON_MIT_FLAG = 'Y' THEN LS_PERSON_ID ELSE NULL END,
            LS_UPDATE_TIMESTAMP,
            LS_UPDATE_USER,
            DATA_PROPOSAL_NUMBER,
            LS_PERCENTAGE_EFFORT,
            LS_EMAIL_ADDRESS,
            'N',
            LS_DESIGNATION,
            'N',
            LS_PROJECT_ROLE,
            (CASE WHEN LS_NON_MIT_FLAG = 'N' THEN 'Pending'
            WHEN LS_NON_MIT_FLAG = 'Y' THEN 'Not Applicable' ELSE NULL END)
        );
        SET LS_VALIDATION_STATUS = 'SUCCESS';
        SET LS_CHILD_ERROR_MESSAGE = 'CHILD TABLES : ';
        SET LS_CHILD_ERROR = 'N';
        SET LI_COUNT = -1;
        IF FOR_AUDIT = 1 THEN
        INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'Child prc calling',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
    END IF;
        SET LI_COUNT = -1;
        SELECT COUNT(1) INTO LI_COUNT FROM stage_eps_prop_kp_units WHERE PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = LS_PERSON_ID;
        IF LI_COUNT >0 THEN
        CALL MIGRATE_EPS_PROP_KPUNIT(DATA_PROPOSAL_NUMBER,DATA_PROPOSAL_ID,LS_PERSON_ID,LI_PROPOSAL_PERSON_ID,FOR_AUDIT,@kp_unit_error_count);
        IF FOR_AUDIT = 1 THEN
        INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,ifnull(concat('DATA_ERROR_COUNT :',@kp_unit_error_count),'DATA_ERROR_COUNT is null'),UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
    END IF;
        IF @kp_unit_error_count > 0 THEN
            SET LS_CHILD_ERROR_MESSAGE = CONCAT(LS_CHILD_ERROR_MESSAGE,'EPS PROP KP UNITS');
            SET LS_CHILD_ERROR = 'Y';
        END IF;
        IF FOR_AUDIT = 1 THEN
            INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'child procedure call end',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
        END IF;
        END IF;
        IF LS_CHILD_ERROR = 'Y' THEN
            INSERT INTO migration_transaction_errorlog
                (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
            VALUES  (LI_RECORD_ID,'EPSKEYPERSON','MIGRATION',IFNULL(CONCAT('Error in the ', LS_CHILD_ERROR_MESSAGE,' for the proposal number :',DATA_PROPOSAL_NUMBER,'and the person id : ',LS_PERSON_ID),CONCAT('Error in the ', LS_CHILD_ERROR_MESSAGE,' for the proposal number :',DATA_PROPOSAL_NUMBER,'and the rolodex id : ',LS_ROLODEX_ID)),UTC_TIMESTAMP(),'quickstart');
            SET LS_VALIDATION_STATUS  = 'ERROR';
            IF FOR_AUDIT = 1 THEN
                INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'error in child data',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
            END IF;
        END IF;
        UPDATE stage_eps_prop_key_persons
        SET VALIDATION_STATUS = LS_VALIDATION_STATUS,
        FIBI_IDENTIFIER = CASE  WHEN LS_VALIDATION_STATUS = 'ERROR' THEN -1 ELSE LI_PROPOSAL_PERSON_ID END
        WHERE MIGRATION_KEY_PERSON_ID = LI_RECORD_ID;
    ELSE
        INSERT INTO migration_transaction_errorlog
            (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
        SELECT MIGRATION_EPS_PROP_KP_UNIT_ID,'DEVPROPKPUNITS','MIGRATION',CONCAT('Parent record failed for the proposal number : ',DATA_PROPOSAL_NUMBER,' and person : ',LS_PERSON_ID),UTC_TIMESTAMP(),'quickstart' FROM stage_eps_prop_kp_units WHERE PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = LS_PERSON_ID;
        UPDATE stage_eps_prop_kp_units
        SET VALIDATION_STATUS = CASE WHEN LS_DATA_EXIST_FLAG = 'Y' THEN 'NOTVALID' ELSE 'ERROR' END,
        FIBI_IDENTIFIER = CASE WHEN LS_DATA_EXIST_FLAG = 'Y' THEN NULL ELSE -1 END
        WHERE PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = LS_PERSON_ID;
        UPDATE stage_eps_prop_key_persons
        SET VALIDATION_STATUS = CASE WHEN LS_DATA_EXIST_FLAG = 'Y' THEN 'NOTVALID' ELSE 'ERROR' END,
        FIBI_IDENTIFIER = CASE WHEN LS_DATA_EXIST_FLAG = 'Y' THEN NULL ELSE -1 END
        WHERE MIGRATION_KEY_PERSON_ID = LI_RECORD_ID;
        IF FOR_AUDIT = 1 THEN
            INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'error in KP master data',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
        END IF;
    END IF;
    END LOOP MIGRATION_DEV_PROP_PERSON_CURSOR_LOOP;
    CLOSE MIGRATION_DEV_PROP_PERSON_CURSOR;
    INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','EPSKEYPERSON',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
END;
    SELECT COUNT(1) INTO DATA_ERROR_COUNT FROM  stage_eps_prop_key_persons WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1 AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER;
ELSE
    SET DATA_ERROR_COUNT = 1;
END IF ;
COMMIT;
END
$$
DELIMITER ;
