DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_EPS_PROP_ORG_PREVAL`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_ORGANIZATION_TYPE_CODE INT;
DECLARE LI_SITE_NUMBER INT;
DECLARE LI_ROLODEX_ID INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_ORGANIZATION_ID VARCHAR(8);
DECLARE LS_PROPOSAL_UPDATE_USER VARCHAR(8);
DECLARE LS_LOCATION_NAME VARCHAR(60);
DECLARE LS_ORG_TYPE_DESC VARCHAR(200);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_CHILD_ERROR_MESSAGE VARCHAR(500);
DECLARE LS_CHILD_ERROR VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE IN ('EPSORGANIZATION','CONGDISTRICT') AND ERROR_TYPE = 'VALIDATION';
				UPDATE stage_eps_proposal_organization SET VALIDATION_STATUS = NULL,FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL;
				UPDATE stage_eps_proposal_cong_district SET VALIDATION_STATUS = NULL,FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL;
		END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_proposal_organization;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'EPSORGANIZATION';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'VALIDATION','EPSORGANIZATION',UTC_TIMESTAMP()),
				(LI_BATCH_ID,'VALIDATION','CONGDISTRICT',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR CURSOR FOR
		SELECT  MIGRATION_SITE_ID,
				PROPOSAL_NUMBER,
				SITE_NUMBER,
				ROLODEX_ID,
				ORGANIZATION_ID,
				LOCATION_NAME,
				ORG_TYPE_DESCRIPTION
		FROM 	stage_eps_proposal_organization
		WHERE VALIDATION_STATUS IS NULL AND FIBI_IDENTIFIER IS NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
			OPEN MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR;
			 MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR_LOOP : LOOP
				FETCH MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR INTO     	LI_RECORD_ID,
																			LS_PROPOSAL_NUMBER,
																			LI_SITE_NUMBER,
																			LI_ROLODEX_ID,
																			LS_ORGANIZATION_ID,
																			LS_LOCATION_NAME,
																			LS_ORG_TYPE_DESC;
					IF DONE1 THEN
						LEAVE MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR_LOOP;
					END IF;
					SET LS_DATA_ERROR_FLAG = 'N';
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM
					stage_eps_proposal WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND VALIDATION_STATUS IN ('VALID','SUCCESS');
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',CONCAT('Invalid proposal number :', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after dev prop check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM
					organization_type WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM(LS_ORG_TYPE_DESC)) AND IS_ACTIVE = 'Y';
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',IFNULL(CONCAT('Invalid organization type :', LS_ORG_TYPE_DESC), 'Organization type code ia mandatory and cannot be NULL' ),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after organization type check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					IF LI_ROLODEX_ID IS NOT NULL THEN
						SELECT COUNT(1) INTO LI_COUNT FROM
						rolodex WHERE ROLODEX_ID = LI_ROLODEX_ID;
						IF LI_COUNT = 0 THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',CONCAT('Invalid rolodex id :', LI_ROLODEX_ID),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
						END IF;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after rolodex check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					END IF;
					IF LS_ORGANIZATION_ID IS NOT NULL THEN
						SET LI_COUNT = -1;
						SELECT COUNT(1) INTO LI_COUNT FROM
						organization WHERE ORGANIZATION_ID = LS_ORGANIZATION_ID AND IS_ACTIVE = 'Y';
						IF LI_COUNT = 0 THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',CONCAT('Invalid organization id :', LS_ORGANIZATION_ID),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
						END IF;
					ELSEIF LS_ORGANIZATION_ID IS NULL AND LS_LOCATION_NAME IS NULL THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',CONCAT('Invalid organization ID and Location name'),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after organization check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					END IF;
					SET LS_CHILD_ERROR_MESSAGE = 'CHILD TABLES : ';
					SET LS_CHILD_ERROR = 'N';
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM stage_eps_proposal_cong_district WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SITE_NUMBER = LI_SITE_NUMBER;
					IF LI_COUNT > 0 THEN
						CALL MIGRATE_ORG_CONG_DIST_PREVAL(LS_PROPOSAL_NUMBER,LI_SITE_NUMBER,FOR_AUDIT,@cong_dist_error_count);
						IF @cong_dist_error_count > 0 THEN
							SET LS_CHILD_ERROR_MESSAGE = CONCAT(LS_CHILD_ERROR_MESSAGE ,'CONG DISTRICT ');
							SET LS_CHILD_ERROR = 'Y';
						END IF;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after child call',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					END IF;
					IF LS_CHILD_ERROR = 'Y' THEN
						INSERT INTO migration_transaction_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'EPSORGANIZATION','VALIDATION',CONCAT('Error in the ',LS_CHILD_ERROR_MESSAGE, ' for the proposal number : ', LS_PROPOSAL_NUMBER) ,UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_eps_proposal_organization
						SET VALIDATION_STATUS = 'VALID',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_SITE_ID = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after valid update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
						END IF;
					ELSE
						UPDATE stage_eps_proposal_organization
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_SITE_ID = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
						END IF;
					END IF;
				IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed validation of ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				IF FOR_AUDIT = 1 THEN
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'Validation end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
				END IF;
			END LOOP MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR_LOOP;
			CLOSE MIGRATION_DEV_PROPOSAL_ORGANIZATION_CURSOR;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPSORGANIZATION',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
			END IF;
		END;
		INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
		SET SQL_SAFE_UPDATES = 1;
		SET FOREIGN_KEY_CHECKS = 1;
		SELECT 1 AS RESULT;
		COMMIT;
END
$$
DELIMITER ;
