DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_BUDGET_HEADER`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_BUDGET_HEADER_ID INT;
DECLARE LI_RATE_CLASS_CODE INT;
DECLARE LI_RATE_TYPE_CODE INT;
DECLARE LI_VERSION_NUMBER INT;
DECLARE LI_UR_RATE_CLASS_CODE INT;
DECLARE LI_MAX_VERSION INT;
DECLARE LI_PROPOSAL_ID INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_ON_OFF_CAMPUS_FLAG VARCHAR(1);
DECLARE LS_COMMENTS LONGTEXT;
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_FINAL_VERSION_FLAG VARCHAR(1);
DECLARE LS_MODULAR_BUDGET_FLAG VARCHAR(1);
DECLARE LS_SUBMIT_COST_SHARING_FLAG VARCHAR(1);
DECLARE LS_UPDATE_USER_NAME VARCHAR(200);
DECLARE LS_LATEST_VERSION_FLAG VARCHAR(1);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_END_DATE DATETIME;
DECLARE LS_START_DATE DATETIME;
DECLARE LS_TOTAL_COST DECIMAL(12, 2);
DECLARE LS_TOTAL_DIRECT_COST DECIMAL(12, 2);
DECLARE LS_TOTAL_INDIRECT_COST DECIMAL(12, 2);
DECLARE LS_COST_SHARING_AMOUNT DECIMAL(12, 2);
DECLARE LS_UNDERRECOVERY_AMOUNT DECIMAL(12, 2);
DECLARE LS_RESIDUAL_FUNDS DECIMAL(12, 2);
DECLARE LS_TOTAL_COST_LIMIT DECIMAL(12, 2);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_VALIDATION_STATUS VARCHAR(10);
DECLARE LS_CHILD_ERROR_MESSAGE VARCHAR(500);
DECLARE LS_CHILD_ERROR VARCHAR(1);
DECLARE LS_DELETED_DATA VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
DECLARE LI_INPROGRESS_STATUS_CODE INT;
DECLARE LI_COMPLETE_STATUS_CODE INT;
DECLARE LS_MASTER_DATA_ERROR_FLAG INT;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	IF DATA_REFRESH_FLAG = 1 THEN
			DELETE FROM migration_validation_matrix WHERE MODULE_NAME IN ('BUDGET','BUDGETPERIOD','EPSPROPRATE');
			DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE IN ('BUDGET','BUDGETPERIOD','EPSPROPRATE') AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_budget_header SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
			UPDATE stage_budget_periods SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_budget_header;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'BUDGET';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','BUDGET',UTC_TIMESTAMP()),
				(LI_BATCH_ID,'MIGRATION','BUDGETPERIOD',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
	SET LI_COUNT = -1;
	SET LS_MASTER_DATA_ERROR_FLAG = 'N';
	SELECT COUNT(1) INTO LI_COUNT FROM budget_status WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('In Progress')) AND IS_ACTIVE = 'Y';
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'BUDGET','MIGRATION','Invalid budget status : In progress',UTC_TIMESTAMP(),'quickstart');
		SET LS_MASTER_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT BUDGET_STATUS_CODE INTO LI_INPROGRESS_STATUS_CODE FROM budget_status WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('In Progress')) AND IS_ACTIVE = 'Y';
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM budget_status WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Complete')) AND IS_ACTIVE = 'Y';
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'BUDGET','MIGRATION','Invalid budget status : Complete',UTC_TIMESTAMP(),'quickstart');
		SET LS_MASTER_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT BUDGET_STATUS_CODE INTO LI_COMPLETE_STATUS_CODE FROM budget_status WHERE UPPER(TRIM(DESCRIPTION)) = UPPER(TRIM('Complete')) AND IS_ACTIVE = 'Y';
	END IF;
END;
IF LS_MASTER_DATA_ERROR_FLAG = 'N' THEN
	BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_BUDGET_HEADER_CURSOR CURSOR FOR
		SELECT  MIGRATION_BUDGET_ID,
				PROPOSAL_NUMBER,
				VERSION_NUMBER,
				START_DATE,
				END_DATE,
				TOTAL_COST,
				TOTAL_DIRECT_COST,
				TOTAL_INDIRECT_COST,
				COST_SHARING_AMOUNT,
				UNDERRECOVERY_AMOUNT,
				RESIDUAL_FUNDS,
				TOTAL_COST_LIMIT,
				OH_RATE_CLASS_CODE,
				OH_RATE_TYPE_CODE,
				COMMENTS,
				FINAL_VERSION_FLAG,
				UPDATE_TIMESTAMP,
				UPDATE_USER,
				UR_RATE_CLASS_CODE,
				MODULAR_BUDGET_FLAG,
				ON_OFF_CAMPUS_FLAG,
				SUBMIT_COST_SHARING_FLAG
		FROM  stage_budget_header  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'BUDGET','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
		OPEN MIGRATION_BUDGET_HEADER_CURSOR;
		MIGRATION_BUDGET_HEADER_CURSOR_LOOP  :      LOOP
		FETCH MIGRATION_BUDGET_HEADER_CURSOR       	INTO       	LI_RECORD_ID,
																LS_PROPOSAL_NUMBER,
																LI_VERSION_NUMBER,
																LS_START_DATE,
																LS_END_DATE,
																LS_TOTAL_COST,
																LS_TOTAL_DIRECT_COST,
																LS_TOTAL_INDIRECT_COST,
																LS_COST_SHARING_AMOUNT,
																LS_UNDERRECOVERY_AMOUNT,
																LS_RESIDUAL_FUNDS,
																LS_TOTAL_COST_LIMIT,
																LI_RATE_CLASS_CODE,
																LI_RATE_TYPE_CODE,
																LS_COMMENTS,
																LS_FINAL_VERSION_FLAG,
																LS_UPDATE_TIMESTAMP,
																LS_UPDATE_USER,
																LI_UR_RATE_CLASS_CODE,
																LS_MODULAR_BUDGET_FLAG,
																LS_ON_OFF_CAMPUS_FLAG,
																LS_SUBMIT_COST_SHARING_FLAG;
		IF DONE1 THEN
			LEAVE MIGRATION_BUDGET_HEADER_CURSOR_LOOP;
		END IF;
		SET LS_DATA_ERROR_FLAG = 'N';
		SET LI_BUDGET_HEADER_ID = -1;
		SET LS_UPDATE_USER_NAME = NULL;
		SET LI_PROPOSAL_ID = -1;
		SET LI_TOTAL_PROCESSED_DATA_COUNT =  LI_TOTAL_PROCESSED_DATA_COUNT + 1;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
		END IF;
		SET LI_MAX_VERSION = -1;
		SELECT IFNULL(MAX(VERSION_NUMBER),0) INTO LI_MAX_VERSION FROM stage_budget_header WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER;
		IF LI_MAX_VERSION = LI_VERSION_NUMBER THEN
			SET LS_LATEST_VERSION_FLAG = 'Y';
		ELSE
			SET LS_LATEST_VERSION_FLAG = 'N';
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'maximum version flag set',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
		END IF;
		CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PROPOSAL_NUMBER,@proposal_id);
		IF @proposal_id = -1 THEN
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'BUDGET','MIGRATION',CONCAT('Invalid proposal number : ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		ELSE
			SET LI_PROPOSAL_ID = @proposal_id;
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'fetch proposal id',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
		END IF;
		IF LS_DATA_ERROR_FLAG = 'N' THEN
			SELECT IFNULL(MAX(BUDGET_HEADER_ID),0) + 1 INTO LI_BUDGET_HEADER_ID
			FROM budget_header;
			INSERT INTO  budget_header
			(
				BUDGET_HEADER_ID,
				ANTICIPATED_TOTAL,
				BUDGET_STATUS_CODE,
				BUDGET_TYPE_CODE,
				COMMENTS,
				CREATE_TIMESTAMP,
				CREATE_USER,
				CREATE_USER_NAME,
				END_DATE,
				IS_AUTO_CALC,
				MODULE_ITEM_CODE,
				MODULE_ITEM_KEY,
				MODULE_SEQUENCE_NUMBER,
				OBLIGATED_CHANGE,
				OBLIGATED_TOTAL,
				ON_OFF_CAMPUS_FLAG,
				RATE_CLASS_CODE,
				RATE_TYPE_CODE,
				START_DATE,
				TOTAL_COST,
				TOTAL_DIRECT_COST,
				TOTAL_INDIRECT_COST,
				UPDATE_TIMESTAMP,
				UPDATE_USER,
				UPDATE_USER_NAME,
				VERSION_NUMBER,
				TOTAL_SUBCONTRACT_COST,
				PROPOSAL_ID,
				COST_SHARING_AMOUNT,
				UNDERRECOVERY_AMOUNT,
				RESIDUAL_FUNDS,
				TOTAL_COST_LIMIT,
				FINAL_VERSION_FLAG,
				MODULAR_BUDGET_FLAG,
				SUBMIT_COST_SHARING_FLAG,
				UNDERRECOVERY_TYPE_CODE,
				UNDERRECOVERY_CLASS_CODE,
				IS_FINAL_BUDGET,
				IS_LATEST_VERSION,
				IS_APPROVED_BUDGET,
				BUDGET_TEMPLATE_TYPE_ID
			)
			VALUES
			(
				LI_BUDGET_HEADER_ID,
				NULL,
				CASE LS_FINAL_VERSION_FLAG WHEN 'Y' THEN LI_COMPLETE_STATUS_CODE ELSE LI_INPROGRESS_STATUS_CODE END,
				NULL,
				LS_COMMENTS,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER,
				NULL,
				LS_END_DATE,
				'N',
				NULL,
				NULL,
				NULL,
				NULL,
				NULL,
				LS_ON_OFF_CAMPUS_FLAG,
				LI_RATE_CLASS_CODE,
				LI_RATE_TYPE_CODE,
				LS_START_DATE,
				LS_TOTAL_COST,
				LS_TOTAL_DIRECT_COST,
				LS_TOTAL_INDIRECT_COST,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER,
				NULL,
				LI_VERSION_NUMBER,
				NULL,
				LI_PROPOSAL_ID,
				LS_COST_SHARING_AMOUNT,
				LS_UNDERRECOVERY_AMOUNT,
				LS_RESIDUAL_FUNDS,
				LS_TOTAL_COST_LIMIT,
				LS_FINAL_VERSION_FLAG,
				LS_MODULAR_BUDGET_FLAG,
				LS_SUBMIT_COST_SHARING_FLAG,
				NULL,
				LI_UR_RATE_CLASS_CODE,
				LS_FINAL_VERSION_FLAG,
				LS_LATEST_VERSION_FLAG,
				'N',
				NULL
			);
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'before child procedure call',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
		END IF;
		IF LS_DATA_ERROR_FLAG = 'N' THEN
			SET LS_VALIDATION_STATUS = 'SUCCESS';
			SET LS_CHILD_ERROR_MESSAGE = 'CHILD TABLES : ';
			SET LS_CHILD_ERROR = 'N';
			SET LI_COUNT = -1;
			SELECT COUNT(1) INTO LI_COUNT FROM stage_budget_periods WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND VERSION_NUMBER = LI_VERSION_NUMBER AND VALIDATION_STATUS = 'VALID';
			IF LI_COUNT > 0 THEN
				CALL MIGRATE_BUDGET_PERIOD(LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER,LI_BUDGET_HEADER_ID,FOR_AUDIT,@period_error_count);
				IF @period_error_count > 0 THEN
					SET LS_CHILD_ERROR_MESSAGE = CONCAT(LS_CHILD_ERROR_MESSAGE,'BUDGET PERIOD,');
					SET LS_CHILD_ERROR = 'Y';
				END IF;
			END IF;
			IF LS_CHILD_ERROR  = 'Y' THEN
				INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_RECORD_ID,'BUDGET','MIGRATION',CONCAT('Error in the ', LS_CHILD_ERROR_MESSAGE,' for the proposal number :',LS_PROPOSAL_NUMBER,' and the version number : ',LI_VERSION_NUMBER),UTC_TIMESTAMP(),'quickstart');
				SET LS_VALIDATION_STATUS  = 'ERROR';
				DELETE FROM budget_period WHERE BUDGET_PERIOD_ID IN (SELECT FIBI_IDENTIFIER FROM stage_budget_periods WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND VERSION_NUMBER = LI_VERSION_NUMBER AND VALIDATION_STATUS = 'SUCCESS');
				UPDATE stage_budget_periods SET VALIDATION_STATUS = 'ERROR', FIBI_IDENTIFIER = -1 WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND VERSION_NUMBER = LI_VERSION_NUMBER AND VALIDATION_STATUS = 'SUCCESS';
				DELETE FROM budget_header WHERE BUDGET_HEADER_ID = LI_BUDGET_HEADER_ID;
				IF FOR_AUDIT = 1 THEN
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'child table error and reverting the migration',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
				END IF;
			END IF;
		END IF;
		IF LS_DATA_ERROR_FLAG = 'N' THEN
			UPDATE stage_budget_header
			SET VALIDATION_STATUS = LS_VALIDATION_STATUS,
			FIBI_IDENTIFIER = CASE LS_VALIDATION_STATUS WHEN 'ERROR' THEN -1 ELSE LI_BUDGET_HEADER_ID END
			WHERE MIGRATION_BUDGET_ID = LI_RECORD_ID;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'after update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
			END IF;
		ELSE
			INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			SELECT MIGRATION_BUDGET_PERIOD_ID,'BUDGETPERIOD','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart' FROM stage_budget_periods WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND VERSION_NUMBER = LI_VERSION_NUMBER;
			UPDATE stage_budget_periods SET VALIDATION_STATUS = 'ERROR', FIBI_IDENTIFIER = -1 WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND VERSION_NUMBER = LI_VERSION_NUMBER;
			UPDATE stage_budget_header
			SET VALIDATION_STATUS = 'ERROR',
			FIBI_IDENTIFIER = -1
			WHERE MIGRATION_BUDGET_ID = LI_RECORD_ID;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
			END IF;
		END IF;
		IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
			IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
				INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
				SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
			END IF;
		END IF ;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'migration end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_VERSION_NUMBER);
		END IF;
		END LOOP MIGRATION_BUDGET_HEADER_CURSOR_LOOP;
		CLOSE MIGRATION_BUDGET_HEADER_CURSOR;
		IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','BUDGET',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL,NULL);
		END IF;
	END;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM budget_header_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO budget_header_id_generator   (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(BUDGET_HEADER_ID),0) + 1  FROM budget_header));
	ELSE
	UPDATE budget_header_id_generator    SET NEXT_VAL = (SELECT IFNULL(MAX(BUDGET_HEADER_ID),0) + 1  FROM budget_header);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM budget_period_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO budget_period_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(BUDGET_PERIOD_ID),0) + 1  FROM budget_period));
	ELSE
	UPDATE budget_period_id_generator  SET NEXT_VAL = (SELECT IFNULL(MAX(BUDGET_PERIOD_ID),0) + 1  FROM budget_period);
	END IF;
	UPDATE budget_header INNER JOIN person ON budget_header.CREATE_USER=person.USER_NAME
	SET budget_header.CREATE_USER_NAME = person.FULL_NAME,
	budget_header.UPDATE_USER_NAME = person.FULL_NAME WHERE CREATE_USER_NAME IS NULL AND UPDATE_USER_NAME IS NULL;
END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END
$$
DELIMITER ;
