DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_AWRD_FUND_PRPLS`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LI_IP_SEQUENCE_NUMBER INT;
DECLARE LI_AWARD_FUNDING_PROPOSAL_ID  INT;
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LI_MAX_IP_SEQUENCE_NUMBER INT;
DECLARE LI_AWARD_ID INT;
DECLARE LI_PROPOSAL_ID INT;
DECLARE LI_MASTER_AWARD_ID INT;
DECLARE LI_MAS_AWRD_FUND_PROP_ID INT;
DECLARE LS_MIT_AWARD_NUMBER CHAR(10);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_PROPOSAL_NUMBER VARCHAR(10);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_DATA_EXISTS VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	IF DATA_REFRESH_FLAG = 1 THEN
			DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'AWRDFUND' AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_award_funding_proposals SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'AWRDFUND';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','AWRDFUND',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE  MIGRATE_AWARD_FUND CURSOR FOR
	SELECT 		MIGRATION_AWARD_FUND_PROP_ID,
				MIT_AWARD_NUMBER,
				SEQUENCE_NUMBER,
				PROPOSAL_NUMBER,
				PROP_SEQUENCE_NUMBER,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM 	stage_award_funding_proposals  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL
	;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATE_AWARD_FUND;
	MIGRATE_AWARD_FUND_LOOP		:			LOOP
	FETCH MIGRATE_AWARD_FUND				INTO		LI_RECORD_ID,
														LS_MIT_AWARD_NUMBER,
														LI_SEQUENCE_NUMBER,
														LS_PROPOSAL_NUMBER,
														LI_IP_SEQUENCE_NUMBER,
														LS_UPDATE_TIMESTAMP,
														LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATE_AWARD_FUND_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LS_DATA_EXISTS = 'N';
	SET LI_AWARD_FUNDING_PROPOSAL_ID = -1;
	SET LI_AWARD_ID = -1;
	SET LI_MASTER_AWARD_ID = -1;
	SET LI_MAX_SEQUENCE_NUMBER = -1;
	SET LI_MAS_AWRD_FUND_PROP_ID = -1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'migration start',UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
	SET LS_AWARD_NUMBER = REPLACE(LS_MIT_AWARD_NUMBER,'-','-00');
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,CONCAT('Changed award number',LS_AWARD_NUMBER),UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER ;
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT('Invalid award number :', LS_AWARD_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT IFNULL(MAX(SEQUENCE_NUMBER),-1) INTO LI_MAX_SEQUENCE_NUMBER FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
		IF LI_MAX_SEQUENCE_NUMBER <> -1 THEN
			SELECT AWARD_ID INTO LI_AWARD_ID FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER;
		ELSE
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT('Invalid sequence number :', LI_MAX_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END IF;
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM
	stage_proposal WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER;
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT('Invalid proposal number :', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT IFNULL(MAX(SEQUENCE_NUMBER),-1) INTO LI_MAX_IP_SEQUENCE_NUMBER FROM stage_proposal WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND STATUS_CODE = 2 AND VALIDATION_STATUS IN ('VALID','SUCCESS');
		IF LI_MAX_IP_SEQUENCE_NUMBER <> -1 THEN
			SELECT PROPOSAL_ID INTO LI_PROPOSAL_ID FROM proposal WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_MAX_IP_SEQUENCE_NUMBER;
		ELSE
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT('Invalid proposal number :', LS_PROPOSAL_NUMBER, ' and the squence number : ', LI_MAX_IP_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END IF;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'before insert',UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award_funding_proposals WHERE AWARD_ID = LI_AWARD_ID AND PROPOSAL_ID = LI_PROPOSAL_ID;
	IF LI_COUNT > 0 THEN
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	/*IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(AWARD_FUNDING_PROPOSAL_ID),0) + 1 INTO LI_AWARD_FUNDING_PROPOSAL_ID FROM award_funding_proposals;
		INSERT INTO award_funding_proposals
		(
			AWARD_FUNDING_PROPOSAL_ID,
			AWARD_ID,
			PROPOSAL_ID,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			IS_ACTIVE
		)
		VALUES
		(
			LI_AWARD_FUNDING_PROPOSAL_ID,
			LI_AWARD_ID,
			LI_PROPOSAL_ID,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER,
			'Y'
		);
	END IF;*/
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'after insert',UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'get maximum sequence number',UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
		END IF;
			SET LI_COUNT = -1;
			SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
			IF LI_COUNT = 0 THEN
				INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT('Invalid master award data with award number :', LS_AWARD_NUMBER,' and the sequence number : 0'),UTC_TIMESTAMP(),'quickstart');
				SET LS_DATA_ERROR_FLAG = 'Y';
			ELSE
				SELECT AWARD_ID INTO LI_MASTER_AWARD_ID FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
			END IF;
			-- Duplicate CHECK
			SET LI_COUNT = -1;
			SELECT COUNT(1) INTO LI_COUNT FROM award_funding_proposals WHERE AWARD_ID = LI_MASTER_AWARD_ID AND PROPOSAL_ID = LI_PROPOSAL_ID;
			IF LI_COUNT <> 0 THEN
				INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_RECORD_ID,'AWRDFUND','MIGRATION',CONCAT('Duplicate for :', LI_MASTER_AWARD_ID,' and proposal : ', LI_PROPOSAL_ID),UTC_TIMESTAMP(),'quickstart');
				SET LS_DATA_ERROR_FLAG = 'Y';
				SET LS_DATA_EXISTS = 'Y';
			END IF;
			IF LS_DATA_ERROR_FLAG = 'N' THEN
				SELECT IFNULL(MAX(AWARD_FUNDING_PROPOSAL_ID),0) + 1 INTO LI_MAS_AWRD_FUND_PROP_ID FROM award_funding_proposals;
				INSERT INTO award_funding_proposals
				(
					AWARD_FUNDING_PROPOSAL_ID,
					AWARD_ID,
					PROPOSAL_ID,
					UPDATE_TIMESTAMP,
					UPDATE_USER,
					IS_ACTIVE
				)
				VALUES
				(
					LI_MAS_AWRD_FUND_PROP_ID,
					LI_MASTER_AWARD_ID,
					LI_PROPOSAL_ID,
					LS_UPDATE_TIMESTAMP,
					LS_UPDATE_USER,
					'Y'
				);
			END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'master table logic insert',UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
		END IF;
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE stage_award_funding_proposals SET VALIDATION_STATUS = 'SUCCESS', FIBI_IDENTIFIER = LI_MAS_AWRD_FUND_PROP_ID WHERE MIGRATION_AWARD_FUND_PROP_ID = LI_RECORD_ID;
	ELSE
		IF LS_DATA_EXISTS = 'N' THEN
			UPDATE stage_award_funding_proposals SET VALIDATION_STATUS = 'ERROR', FIBI_IDENTIFIER = -1 WHERE MIGRATION_AWARD_FUND_PROP_ID = LI_RECORD_ID;
		ELSE
		     UPDATE stage_award_funding_proposals SET VALIDATION_STATUS = 'NOTVALID', FIBI_IDENTIFIER = -1 WHERE MIGRATION_AWARD_FUND_PROP_ID = LI_RECORD_ID;
		END IF;
	END IF;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'migration  end',UTC_TIMESTAMP(),LS_MIT_AWARD_NUMBER);
	END LOOP MIGRATE_AWARD_FUND_LOOP;
	CLOSE MIGRATE_AWARD_FUND;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award_funding_proposal_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO award_funding_proposal_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(AWARD_FUNDING_PROPOSAL_ID ),0) + 1  FROM award_funding_proposals));
	ELSE
	UPDATE award_funding_proposal_id_generator   SET NEXT_VAL = (SELECT IFNULL(MAX(AWARD_FUNDING_PROPOSAL_ID ),0) + 1  FROM award_funding_proposals);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END
$$
DELIMITER ;
