DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `MIGRATE_EPS_PROP_ATTACHMNTS_CHECK`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE C1 CURSOR FOR
	SELECT  PROPOSAL_NUMBER,FIBI_IDENTIFIER FROM stage_eps_proposal_attachment
    WHERE VALIDATION_STATUS='SUCCESS'
    ;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE LD_END_DATE DATETIME;
	DECLARE LD_START_DATE DATETIME;
	DECLARE LI_PROPOSAL_NUMBER ,LI_FIBI_IDENTIFIER , LI_LENGHT INT(10);
    DECLARE LS_FILE_DATA_ID VARCHAR(100);
	DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
	FETCH C1 INTO  LI_PROPOSAL_NUMBER,LI_FIBI_IDENTIFIER;
	IF DONE THEN
		LEAVE LOOP1;
	END IF;
	SELECT FILE_DATA_ID INTO LS_FILE_DATA_ID FROM EPS_PROPOSAL_ATTACHMENTS WHERE ATTACHMENT_ID=LI_FIBI_IDENTIFIER;
    SELECT LENGTH(DATA) INTO LI_LENGHT FROM FILE_DATA WHERE ID=LS_FILE_DATA_ID;
    IF LI_LENGHT = 65535 THEN
    INSERT INTO STAGE_EPS_PROP_ATTACH_CHECK ( PROPOSAL_NUMBER, FIBI_IDENTIFIER, LENGTH)
    VALUES
    (LI_PROPOSAL_NUMBER,LI_FIBI_IDENTIFIER,LI_LENGHT);
    END IF;
END;
END LOOP;
CLOSE C1;
END
$$
DELIMITER ;
