DELIMITER $$
CREATE  PROCEDURE `MIGRATE_CUSTOM_DATA_TO_IP`()
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_COLUMN_ID INT;
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT;
DECLARE LI_COLUMN_VERSION_NUMBER INT;
DECLARE LI_DEV_PROPOSAL_ID INT;
DECLARE LI_INST_PROPOSAL_ID INT;
DECLARE LS_VALUE VARCHAR(4000);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
END;
BEGIN
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM custom_data_element_usage WHERE CUSTOM_DATA_ELEMENTS_ID = 9 AND MODULE_CODE = 2;
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'CUSTOMCOPY','MIGRATION',CONCAT('Invalid custom data : Proposal Preparer contact'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
	SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM proposal_admin_details;
END;
BEGIN
	DROP TABLE IF EXISTS stage_custom_copy;
	CREATE TABLE stage_custom_copy
	(
		MIGRATION_CUSTOM_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
		, DEV_PROPOSAL_ID INT NOT NULL
		, INST_PROPOSAL_ID INT NOT NULL
		, CUSTOM_DATA_ELEMENTS_ID INT NOT NULL
		, COLUMN_ID INT NOT NULL
		, COLUMN_VERSION_NUMBER INT NULL
		, VALUE VARCHAR(4000)
	)
	DATA DIRECTORY = '/var/staging'
	TABLESPACE = innodb_file_per_table
	;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Temp Table Created stage_custom_copy',UTC_TIMESTAMP());
END;
BEGIN
	INSERT INTO stage_custom_copy (DEV_PROPOSAL_ID,INST_PROPOSAL_ID,CUSTOM_DATA_ELEMENTS_ID,COLUMN_ID,COLUMN_VERSION_NUMBER,VALUE)
	SELECT
				p.DEV_PROPOSAL_ID,
				p.INST_PROPOSAL_ID,
				c.CUSTOM_DATA_ELEMENTS_ID,
				c.COLUMN_ID,
				c.COLUMN_VERSION_NUMBER,
				c.VALUE
	FROM  proposal_admin_details p inner join
	custom_data c on c.MODULE_ITEM_KEY = p.DEV_PROPOSAL_ID WHERE
	c.MODULE_ITEM_CODE = 3 AND c.MODULE_SUB_ITEM_CODE = 0 AND c.VALUE IS NOT NULL AND c.CUSTOM_DATA_ELEMENTS_ID = 9;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Inserted into temp table stage_custom_copy',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started Processing',UTC_TIMESTAMP());
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_CUSTOM_DATA_CURSOR CURSOR FOR
	SELECT      s.MIGRATION_CUSTOM_ID,
				s.DEV_PROPOSAL_ID,
				s.INST_PROPOSAL_ID,
				s.CUSTOM_DATA_ELEMENTS_ID,
				s.COLUMN_ID,
				s.COLUMN_VERSION_NUMBER,
				s.VALUE
	FROM  stage_custom_copy s left outer join custom_data c on s.INST_PROPOSAL_ID = c.MODULE_ITEM_KEY
    and c.MODULE_ITEM_CODE = 2 and c.CUSTOM_DATA_ELEMENTS_ID = s.CUSTOM_DATA_ELEMENTS_ID
    where c.MODULE_ITEM_KEY IS NULL and c.CUSTOM_DATA_ELEMENTS_ID IS NULL;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'CUSTOMCOPY','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATION_CUSTOM_DATA_CURSOR;
	MIGRATION_CUSTOM_DATA_CURSOR_LOOP      : LOOP
	FETCH MIGRATION_CUSTOM_DATA_CURSOR       INTO       		LI_RECORD_ID,
																LI_DEV_PROPOSAL_ID,
																LI_INST_PROPOSAL_ID,
																LI_CUSTOM_DATA_ELEMENTS_ID,
																LI_COLUMN_ID,
																LI_COLUMN_VERSION_NUMBER,
																LS_VALUE;
	IF DONE1 THEN
		LEAVE MIGRATION_CUSTOM_DATA_CURSOR_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
	-- Check if already EXISTS
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		INSERT INTO   custom_data
		(
			CUSTOM_DATA_ELEMENTS_ID,
			MODULE_ITEM_CODE,
			MODULE_SUB_ITEM_CODE,
			MODULE_ITEM_KEY,
			MODULE_SUB_ITEM_KEY,
			VALUE,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			COLUMN_ID,
			COLUMN_VERSION_NUMBER,
			DESCRIPTION
		)
		VALUES
		(
			LI_CUSTOM_DATA_ELEMENTS_ID,
			2,
			0,
			LI_INST_PROPOSAL_ID,
			0,
			LS_VALUE,
			UTC_TIMESTAMP(),
			'TCHITRA1',
			LI_COLUMN_ID,
			LI_COLUMN_VERSION_NUMBER,
			NULL
		);
	END IF;
	IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
		IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
			INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
			SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
		END IF;
	END IF ;
	END LOOP MIGRATION_CUSTOM_DATA_CURSOR_LOOP;
	CLOSE MIGRATION_CUSTOM_DATA_CURSOR;
END;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END IF;
END
$$
DELIMITER ;
