DELIMITER $$
CREATE  PROCEDURE `MIGRATE_SUBMIT_SERVICE_REQUEST_DEPTS`(REFRESH_FLAG INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_ROLE_ID INT;
DECLARE LI_COUNT INT;
DECLARE LI_PERSON_ROLE_ID INT;
DECLARE LS_PERSON_ID VARCHAR(40);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_DATA_EXISTS VARCHAR(1);
DECLARE LS_ROLE_NOT_AVAIL_FLAG VARCHAR(1);
DECLARE LS_MIGRATION_ERROR_MESSAGE VARCHAR(500);
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
	SET LI_COUNT = -1;
	SET LS_ROLE_NOT_AVAIL_FLAG = 'N';
	SELECT COUNT(1) INTO LI_COUNT FROM role WHERE TRIM(UPPER(ROLE_NAME)) = TRIM(UPPER('Submit Service Request')) AND STATUS_FLAG = 'Y';
	IF LI_COUNT = 1 THEN
		SELECT ROLE_ID INTO LI_ROLE_ID FROM role WHERE TRIM(UPPER(ROLE_NAME)) = TRIM(UPPER('Submit Service Request')) AND STATUS_FLAG = 'Y';
	ELSE
		SET LS_ROLE_NOT_AVAIL_FLAG = 'Y';
		INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Failed execution : Not a valid role',UTC_TIMESTAMP());
	END IF;
END;
IF LS_ROLE_NOT_AVAIL_FLAG = 'N' THEN
	BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE USER_ROLE_CURSOR CURSOR FOR
	SELECT
			DISTINCT PERSON_ID
	FROM	person_roles WHERE ROLE_ID = 1331;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (100,'USERROLES','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN USER_ROLE_CURSOR;
	USER_ROLE_CURSOR_LOOP		:	LOOP
	FETCH USER_ROLE_CURSOR			INTO 	LS_PERSON_ID;
	IF DONE1 THEN
		LEAVE USER_ROLE_CURSOR_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_PERSON_ROLE_ID = -1;
	SET LS_DATA_EXISTS = 'Y';
	-- person check
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM person WHERE PERSON_ID = LS_PERSON_ID;
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (100,'USERROLES','MIGRATION',IFNULL(CONCAT('Invalid person id : ',LS_PERSON_ID),'Person id/username is null'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	-- 000001
	-- person_roles check
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM person_roles WHERE PERSON_ID = LS_PERSON_ID AND UNIT_NUMBER = '000001' AND ROLE_ID = LI_ROLE_ID;
	IF LI_COUNT > 0 THEN
		SET LS_DATA_ERROR_FLAG = 'Y';
		SET LS_DATA_EXISTS = 'Y';
	END IF;
	-- Person role RT TABLE
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM person_role_rt WHERE PERSON_ID = LS_PERSON_ID AND UNIT_NUMBER = '000001' AND ROLE_ID = LI_ROLE_ID AND TRIM(UPPER(RIGHT_NAME)) = TRIM(UPPER('SUBMIT_SERVICE_REQUEST'));
	IF LI_COUNT > 0 THEN
		SET LS_DATA_ERROR_FLAG = 'Y';
		SET LS_DATA_EXISTS = 'Y';
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		INSERT INTO person_roles
		(
			PERSON_ID,
			ROLE_ID,
			UNIT_NUMBER,
			DESCEND_FLAG,
			UPDATE_TIMESTAMP,
			UPDATE_USER
		)
		VALUES
		(
			LS_PERSON_ID,
			LI_ROLE_ID,
			'000001',
			'N',
			UTC_TIMESTAMP(),
			'admin'
		);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		INSERT INTO person_role_rt
		(
			PERSON_ID,
			UNIT_NUMBER,
			RIGHT_NAME,
			ROLE_ID
		)
		VALUES
		(
			LS_PERSON_ID,
			'000001',
			'SUBMIT_SERVICE_REQUEST',
			LI_ROLE_ID
		);
		END IF;
	END LOOP USER_ROLE_CURSOR_LOOP;
	CLOSE USER_ROLE_CURSOR;
	END;
END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Execution completed',UTC_TIMESTAMP());
    SET FOREIGN_KEY_CHECKS = 1;
    SET SQL_SAFE_UPDATES =  1;
    COMMIT;
END
$$
DELIMITER ;
