DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `MIGRATE_AWARD_NOTEPAD`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LI_COMMENT_TYPE_CODE INT;
DECLARE LI_AWARD_COMMENT_ID  INT;
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LI_AWARD_ID INT;
DECLARE LI_MASTER_AWARD_ID INT;
DECLARE LI_MAS_AWRD_COMMENT_ID INT;
DECLARE LS_JHU_AWARD_NUMBER CHAR(10);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_COMMENTS LONGTEXT;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	IF DATA_REFRESH_FLAG = 1 THEN
			DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'AWRDNOTEPAD' AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_award_notepad SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
	END IF;
END;
BEGIN
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM comment_type WHERE UPPER(DESCRIPTION) = UPPER('General Comments(Notepad)') AND IS_ACTIVE = 'Y' AND MODULE_CODE = 1;
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'AWRDNOTEPAD','MIGRATION',CONCAT('Invalid comment type : General Comments(Notepad)'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT COMMENT_TYPE_CODE INTO LI_COMMENT_TYPE_CODE FROM comment_type WHERE UPPER(DESCRIPTION) = UPPER('General Comments(Notepad)') AND IS_ACTIVE = 'Y' AND MODULE_CODE = 1;
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'AWRDNOTEPAD';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','AWRDNOTEPAD',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE  MIGRATE_AWARD_NOTPD CURSOR FOR
	SELECT 		MIGRATION_AWARD_NOTEPAD_ID,
				MIT_AWARD_NUMBER,
				COMMENTS,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM 	stage_award_notepad  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDNOTEPAD','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATE_AWARD_NOTPD;
	MIGRATE_AWARD_NOTPD_LOOP		:		LOOP
	FETCH MIGRATE_AWARD_NOTPD				INTO		LI_RECORD_ID,
														LS_JHU_AWARD_NUMBER,
														LS_COMMENTS,
														LS_UPDATE_TIMESTAMP,
														LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATE_AWARD_NOTPD_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_AWARD_COMMENT_ID = -1;
	SET LI_MAS_AWRD_COMMENT_ID = -1;
	SET LI_MAX_SEQUENCE_NUMBER = -1;
	SET LI_AWARD_ID = -1;
	SET LI_MASTER_AWARD_ID = -1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'migration start',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	SET LS_AWARD_NUMBER = REPLACE(LS_JHU_AWARD_NUMBER,'-','-00');
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,CONCAT('Changed award number',LS_AWARD_NUMBER),UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDNOTEPAD','MIGRATION',CONCAT('Invalid award number :', LS_AWARD_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT IFNULL(MAX(SEQUENCE_NUMBER),-1) INTO LI_SEQUENCE_NUMBER FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
		IF LI_SEQUENCE_NUMBER = -1 THEN
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'AWRDNOTEPAD','MIGRATION',CONCAT('Invalid sequence number :', LI_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		ELSE
			SELECT AWARD_ID INTO LI_AWARD_ID FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_SEQUENCE_NUMBER;
		END IF;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'before insert',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END IF;
	/*IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(AWARD_COMMENT_ID),0) + 1 INTO LI_AWARD_COMMENT_ID FROM award_comment;
		INSERT INTO award_comment
		(
			AWARD_COMMENT_ID,
			AWARD_ID,
			AWARD_NUMBER,
			SEQUENCE_NUMBER,
			COMMENT_TYPE_CODE,
			COMMENTS,
			UPDATE_TIMESTAMP,
			UPDATE_USER
		)
		VALUES
		(
			LI_AWARD_COMMENT_ID,
			LI_AWARD_ID,
			LS_AWARD_NUMBER,
			LI_SEQUENCE_NUMBER,
			LI_COMMENT_TYPE_CODE,
			LS_COMMENTS,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER
		);
	END IF;*/
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'after insert',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
		END IF;
		-- Master data logic
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'get maximum sequence number',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
		END IF;
			SET LI_COUNT = -1;
			SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
			IF LI_COUNT = 0 THEN
				INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_RECORD_ID,'AWRDNOTEPAD','MIGRATION',CONCAT('Invalid master award data with award number :', LS_AWARD_NUMBER,' and the sequence number : 0'),UTC_TIMESTAMP(),'quickstart');
				SET LS_DATA_ERROR_FLAG = 'Y';
			ELSE
				SELECT AWARD_ID INTO LI_MASTER_AWARD_ID FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
			END IF;
			IF LS_DATA_ERROR_FLAG = 'N' THEN
				SELECT IFNULL(MAX(AWARD_COMMENT_ID),0) + 1 INTO LI_MAS_AWRD_COMMENT_ID FROM award_comment;
				INSERT INTO award_comment
				(
					AWARD_COMMENT_ID,
					AWARD_ID,
					AWARD_NUMBER,
					SEQUENCE_NUMBER,
					COMMENT_TYPE_CODE,
					COMMENTS,
					UPDATE_TIMESTAMP,
					UPDATE_USER
				)
				VALUES
				(
					LI_MAS_AWRD_COMMENT_ID,
					LI_MASTER_AWARD_ID,
					LS_AWARD_NUMBER,
					0,
					LI_COMMENT_TYPE_CODE,
					LS_COMMENTS,
					LS_UPDATE_TIMESTAMP,
					LS_UPDATE_USER
				);
			END IF;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'master table logic insert',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE stage_award_notepad SET VALIDATION_STATUS = 'SUCCESS', FIBI_IDENTIFIER = LI_MAS_AWRD_COMMENT_ID WHERE MIGRATION_AWARD_NOTEPAD_ID = LI_RECORD_ID;
	ELSE
		UPDATE stage_award_notepad SET VALIDATION_STATUS = 'ERROR', FIBI_IDENTIFIER = -1 WHERE MIGRATION_AWARD_NOTEPAD_ID = LI_RECORD_ID;
	END IF;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'migration  end',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END LOOP MIGRATE_AWARD_NOTPD_LOOP;
	CLOSE MIGRATE_AWARD_NOTPD;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDFUND',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award_comment_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO award_comment_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(AWARD_COMMENT_ID ),0) + 1  FROM award_comment));
	ELSE
	UPDATE award_comment_id_generator   SET NEXT_VAL = (SELECT IFNULL(MAX(AWARD_COMMENT_ID),0) + 1  FROM award_comment);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END IF;
END
$$
DELIMITER ;
