DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `MIGRATE_IP_KEYWORDS`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_KEY_RECORD_ID INT;
DECLARE LI_KEYWORD_ID INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LI_KEY_SEQUENCE_NUMBER INT;
DECLARE LI_KEY_PROPOSAL_ID INT;
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LI_RESEARCH_TYPE_CODE INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_KEY_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_SCIENCE_CODE VARCHAR(3);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_SCIENCE_CODE_INDICATOR VARCHAR(2);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_PARENT_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_DATA_AVAILABLE_FLAG VARCHAR(1);
DECLARE LS_DATA_EXISTS VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_validation_matrix WHERE MODULE_NAME = 'INSTPROPKEYWORD';
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'INSTPROPKEYWORD' AND ERROR_TYPE = 'MIGRATION';
				UPDATE stage_proposal_keywords SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
		END IF;
END;
BEGIN
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM research_type WHERE UPPER(DESCRIPTION) = UPPER('AreaÂ ofÂ Research') AND IS_ACTIVE = 'Y';
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'INSTPROPKEYWORD','MIGRATION',CONCAT('Invalid research type : AreaÂ ofÂ Research'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT RESRCH_TYPE_CODE INTO LI_RESEARCH_TYPE_CODE FROM research_type WHERE UPPER(DESCRIPTION) = UPPER('AreaÂ ofÂ Research') AND IS_ACTIVE = 'Y';
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_proposal_keywords;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'INSTPROPKEYWORD';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','INSTPROPKEYWORD',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_IP_CURSOR CURSOR FOR
	SELECT    	MIGRATION_PROPOSAL_ID,
				PROPOSAL_NUMBER,
				SEQUENCE_NUMBER,
				SCIENCE_CODE_INDICATOR,
				FIBI_IDENTIFIER
	FROM  stage_proposal  WHERE  VALIDATION_STATUS = 'SUCCESS'
	AND FIBI_IDENTIFIER IS NOT NULL AND FIBI_IDENTIFIER <> -1 AND SCIENCE_CODE_INDICATOR IN ('P1','P0') AND PROPOSAL_NUMBER IN (SELECT DISTINCT PROPOSAL_NUMBER FROM stage_proposal_keywords WHERE VALIDATION_STATUS <> 'ERROR') ORDER BY PROPOSAL_NUMBER;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'IPPROPOSAL','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATION_IP_CURSOR;
	MIGRATION_INST_PROPOSAL_CURSOR_LOOP       : LOOP
	FETCH MIGRATION_IP_CURSOR        			INTO        LI_RECORD_ID,
															LS_PROPOSAL_NUMBER,
															LI_SEQUENCE_NUMBER,
															LS_SCIENCE_CODE_INDICATOR,
															LI_KEY_PROPOSAL_ID;
	IF DONE1 THEN
		LEAVE MIGRATION_INST_PROPOSAL_CURSOR_LOOP;
	END IF;
	SET LS_PARENT_DATA_ERROR_FLAG = 'N';
	SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM proposal WHERE PROPOSAL_ID = LI_KEY_PROPOSAL_ID;
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'IPPROPOSAL','MIGRATION',CONCAT('Invalid proposal number : ',LS_PROPOSAL_NUMBER,' and the sequence number : ', LI_SEQUENCE_NUMBER,' in the proposal keywords'),UTC_TIMESTAMP(),'quickstart');
		SET LS_PARENT_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'after IP check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
	END IF;
	IF LS_PARENT_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(SEQUENCE_NUMBER),0) INTO LI_MAX_SEQUENCE_NUMBER FROM stage_proposal_keywords
		WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SEQUENCE_NUMBER <= LI_SEQUENCE_NUMBER AND VALIDATION_STATUS <> 'ERROR';
		IF LI_MAX_SEQUENCE_NUMBER = 0 THEN
			SET LS_DATA_AVAILABLE_FLAG = 'N';
		ELSE
			SET LS_DATA_AVAILABLE_FLAG = 'Y';
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'fetch max sequence number',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
		END IF;
		IF LS_DATA_AVAILABLE_FLAG = 'Y' THEN
			BEGIN
				DECLARE DONE2 INT DEFAULT FALSE;
				DECLARE MIGRATION_IP_KEYWORDS_CURSOR CURSOR FOR
				SELECT      MIGRATION_PROP_KEYWORDS_ID,
							PROPOSAL_NUMBER,
							SEQUENCE_NUMBER,
							SCIENCE_CODE,
							UPDATE_TIMESTAMP,
							UPDATE_USER
				FROM  stage_proposal_keywords WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND VALIDATION_STATUS <> 'ERROR';
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
				DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
				BEGIN
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
					@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
					SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
					SELECT @full_error INTO LS_ERROR;
					INSERT INTO migration_transaction_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
					VALUES  (LI_KEY_RECORD_ID,'INSTPROPKEYWORD','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
					SET LS_DATA_ERROR_FLAG = 'Y';
				END;
				OPEN MIGRATION_IP_KEYWORDS_CURSOR;
				MIGRATION_IP_KEYWORDS_CURSOR_LOOP :          LOOP
				FETCH  MIGRATION_IP_KEYWORDS_CURSOR          INTO			LI_KEY_RECORD_ID,
																			LS_KEY_PROPOSAL_NUMBER,
																			LI_KEY_SEQUENCE_NUMBER,
																			LS_SCIENCE_CODE,
																			LS_UPDATE_TIMESTAMP,
																			LS_UPDATE_USER;
				IF DONE2 THEN
					LEAVE MIGRATION_IP_KEYWORDS_CURSOR_LOOP;
				END IF;
				SET LS_DATA_ERROR_FLAG = 'N';
				SET LI_KEYWORD_ID = -1;
				SET LS_DATA_EXISTS = 'N';
				IF FOR_AUDIT = 1 THEN
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'before insert',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
				END IF;
				SET LI_COUNT = -1;
				SELECT COUNT(1) INTO LI_COUNT FROM proposal_resrch_areas WHERE PROPOSAL_ID = LI_KEY_PROPOSAL_ID AND PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_SEQUENCE_NUMBER AND RESRCH_TYPE_AREA_CODE = LS_SCIENCE_CODE;
				IF LI_COUNT > 0 THEN
					SET LS_DATA_ERROR_FLAG = 'Y';
					SET LS_DATA_EXISTS = 'Y';
				END IF;
				IF LS_DATA_ERROR_FLAG = 'N' THEN
					SELECT IFNULL(MAX(RESRCH_AREA_ID),0) + 1 INTO LI_KEYWORD_ID
					FROM proposal_resrch_areas;
					INSERT INTO   proposal_resrch_areas
					(
						RESRCH_AREA_ID,
						PROPOSAL_ID,
						PROPOSAL_NUMBER,
						SEQUENCE_NUMBER,
						EXCELLENCE_AREA_CODE,
						RESEARCH_AREA_CODE,
						RESRCH_TYPE_CODE,
						UPDATE_TIMESTAMP,
						UPDATE_USER,
						RESEARCH_SUB_AREA_CODE,
						CHALLENGE_AREA_CODE,
						CHALLENGE_SUBAREA_CODE,
						RESRCH_TYPE_AREA_CODE,
						RESRCH_TYPE_SUB_AREA_CODE
					)
					VALUES
					(
						LI_KEYWORD_ID,
						LI_KEY_PROPOSAL_ID,
						LS_PROPOSAL_NUMBER,
						LI_SEQUENCE_NUMBER,
						NULL,
						NULL,
						1,
						LS_UPDATE_TIMESTAMP,
						LS_UPDATE_USER,
						NULL,
						NULL,
						NULL,
						LS_SCIENCE_CODE,
						NULL
					);
				END IF;
				IF LS_DATA_ERROR_FLAG = 'N' THEN
					UPDATE stage_proposal_keywords
					SET VALIDATION_STATUS = 'SUCCESS',
					FIBI_IDENTIFIER = LI_KEYWORD_ID
					WHERE MIGRATION_PROP_KEYWORDS_ID = LI_KEY_RECORD_ID;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
				ELSE
					IF LS_DATA_EXISTS = 'N' THEN
						UPDATE stage_proposal_keywords
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = -1
						WHERE MIGRATION_PROP_KEYWORDS_ID = LI_KEY_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
						END IF;
					END IF;
				END IF;
				END LOOP MIGRATION_IP_KEYWORDS_CURSOR_LOOP;
				CLOSE MIGRATION_IP_KEYWORDS_CURSOR;
			END;
		ELSE
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'IPPROPOSAL','MIGRATION',CONCAT('There is no data available in the stage_proposal_keywords table with the proposal number :  ',LS_PROPOSAL_NUMBER,' and the sequence number : ',LI_SEQUENCE_NUMBER,' with the indicator : ',LS_SCIENCE_CODE_INDICATOR),UTC_TIMESTAMP(),'quickstart');
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'no data available',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
			END IF;
		END IF;
	END IF;
	IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
		IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
			INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
			SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
		END IF;
	END IF ;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'Migration end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
	END IF;
	END LOOP MIGRATION_INST_PROPOSAL_CURSOR_LOOP;
	CLOSE MIGRATION_IP_CURSOR;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPKEYWORD',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL,NULL);
	END IF;
END;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM seq_ip_resrch_area_id_gntr;
	IF LI_COUNT = 0 THEN
		INSERT INTO seq_ip_resrch_area_id_gntr  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(RESRCH_AREA_ID),0) + 1  FROM proposal_resrch_areas));
	ELSE
		UPDATE seq_ip_resrch_area_id_gntr   SET NEXT_VAL = (SELECT IFNULL(MAX(RESRCH_AREA_ID),0) + 1  FROM proposal_resrch_areas);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END IF;
END
$$
DELIMITER ;
