DELIMITER $$
CREATE  PROCEDURE `MIGRATE_IP_ADMINDTLS`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_PROPOSAL_ADMIN_DETAIL_ID DECIMAL(22,0);
DECLARE LI_IP_PROPOSAL_NUMBER INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LI_DEV_PROPOSAL_ID INT;
DECLARE LS_DEV_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_INST_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_IP_CREATE_USER VARCHAR(8);
DECLARE LS_SIGNED_BY VARCHAR(8);
DECLARE LS_DATE_SUBMITTED_BY_DEPT DATETIME;
DECLARE LS_DATE_RETURNED_TO_DEPT DATETIME;
DECLARE LS_DATE_APPROVED_BY_OSP DATETIME;
DECLARE LS_DATE_SUBMITTED_TO_AGENCY DATETIME;
DECLARE LS_INST_PROP_CREATE_DATE DATETIME;
DECLARE LI_PARENT_RECORD_ID INT;
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LS_PARENT_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LI_PARENT_SEQ_NUMBER INT;
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_PARENT_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_DATA_AVAILABLE_FLAG VARCHAR(1);
DECLARE LS_DATA_EXISTS VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_validation_matrix WHERE MODULE_NAME = 'INSTPROPADMIN';
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'INSTPROPADMIN' AND ERROR_TYPE = 'MIGRATION';
				UPDATE stage_proposal_admin_details SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
		END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_proposal_admin_details;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'INSTPROPADMIN';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','INSTPROPADMIN',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_IP_CURSOR CURSOR FOR
	SELECT    	MIGRATION_PROPOSAL_ID,
				PROPOSAL_NUMBER,
				SEQUENCE_NUMBER
	FROM  stage_proposal  WHERE PROPOSAL_NUMBER IN (SELECT DISTINCT INST_PROPOSAL_NUMBER FROM stage_proposal_admin_details WHERE VALIDATION_STATUS <> 'ERROR') AND VALIDATION_STATUS = 'SUCCESS' AND FIBI_IDENTIFIER IS NOT NULL AND FIBI_IDENTIFIER <> -1;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_PARENT_RECORD_ID,'IPPROPOSAL','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATION_IP_CURSOR;
	MIGRATION_INST_PROPOSAL_CURSOR_LOOP       : LOOP
	FETCH MIGRATION_IP_CURSOR        			INTO        LI_PARENT_RECORD_ID,
															LS_PARENT_PROPOSAL_NUMBER,
															LI_PARENT_SEQ_NUMBER;
	IF DONE1 THEN
		LEAVE MIGRATION_INST_PROPOSAL_CURSOR_LOOP;
	END IF;
	SET LS_PARENT_DATA_ERROR_FLAG = 'N';
	SET LI_IP_PROPOSAL_NUMBER = -1;
	SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM proposal WHERE PROPOSAL_NUMBER = LS_PARENT_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_PARENT_SEQ_NUMBER;
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'IPPROPOSAL','MIGRATION',CONCAT('Invalid proposal number : ',LS_PARENT_PROPOSAL_NUMBER,' and the sequence number : ', LI_PARENT_SEQ_NUMBER,' in the proposal admin details'),UTC_TIMESTAMP(),'quickstart');
		SET LS_PARENT_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT PROPOSAL_ID INTO LI_IP_PROPOSAL_NUMBER FROM proposal WHERE PROPOSAL_NUMBER = LS_PARENT_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_PARENT_SEQ_NUMBER;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'after IP check',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
	END IF;
	IF LS_PARENT_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(INST_PROP_SEQUENCE_NUMBER),0) INTO LI_MAX_SEQUENCE_NUMBER FROM stage_proposal_admin_details
		WHERE INST_PROPOSAL_NUMBER = LS_PARENT_PROPOSAL_NUMBER AND INST_PROP_SEQUENCE_NUMBER <= LI_PARENT_SEQ_NUMBER AND VALIDATION_STATUS <> 'ERROR';
		IF LI_MAX_SEQUENCE_NUMBER = 0 THEN
			SET LS_DATA_AVAILABLE_FLAG = 'N';
		ELSE
			SET LS_DATA_AVAILABLE_FLAG = 'Y';
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'fetch max sequence number',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
		END IF;
		IF LS_DATA_AVAILABLE_FLAG = 'Y' THEN
			BEGIN
				DECLARE DONE2 INT DEFAULT FALSE;
				DECLARE MIGRATION_IP_ADMIN_CURSOR CURSOR FOR
				SELECT      MIGRATION_PROP_ADMIN_DTLS_ID,
							DEV_PROPOSAL_NUMBER,
							INST_PROPOSAL_NUMBER,
							INST_PROP_SEQUENCE_NUMBER,
							DATE_SUBMITTED_BY_DEPT,
							DATE_RETURNED_TO_DEPT,
							DATE_APPROVED_BY_OSP,
							DATE_SUBMITTED_TO_AGENCY,
							INST_PROP_CREATE_DATE,
							INST_PROP_CREATE_USER,
							SIGNED_BY
				FROM stage_proposal_admin_details WHERE INST_PROPOSAL_NUMBER = LS_PARENT_PROPOSAL_NUMBER AND INST_PROP_SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER AND VALIDATION_STATUS <> 'ERROR';
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
				DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
				BEGIN
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
					@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
					SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
					SELECT @full_error INTO LS_ERROR;
					INSERT INTO migration_transaction_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
					VALUES  (LI_RECORD_ID,'INSTPROPADMIN','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
					SET LS_DATA_ERROR_FLAG = 'Y';
				END;
				OPEN MIGRATION_IP_ADMIN_CURSOR;
				MIGRATION_IP_ADMIN_CURSOR_LOOP :          LOOP
				FETCH  MIGRATION_IP_ADMIN_CURSOR          INTO						LI_RECORD_ID,
																					LS_DEV_PROPOSAL_NUMBER,
																					LS_INST_PROPOSAL_NUMBER,
																					LI_SEQUENCE_NUMBER,
																					LS_DATE_SUBMITTED_BY_DEPT,
																					LS_DATE_RETURNED_TO_DEPT,
																					LS_DATE_APPROVED_BY_OSP,
																					LS_DATE_SUBMITTED_TO_AGENCY,
																					LS_INST_PROP_CREATE_DATE,
																					LS_IP_CREATE_USER,
																					LS_SIGNED_BY;
				IF DONE2 THEN
					LEAVE MIGRATION_IP_ADMIN_CURSOR_LOOP;
				END IF;
				SET LS_DATA_ERROR_FLAG = 'N';
				SET LI_PROPOSAL_ADMIN_DETAIL_ID = -1;
				SET LI_DEV_PROPOSAL_ID = -1;
				SET LS_DATA_EXISTS = 'N';
				IF FOR_AUDIT = 1 THEN
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'before insert',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
				END IF;
				CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_DEV_PROPOSAL_NUMBER,@proposal_id);
				IF @proposal_id = -1 THEN
					INSERT INTO migration_transaction_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
					VALUES  (LI_RECORD_ID,'INSTPROPADMIN','MIGRATION',CONCAT('Invalid proposal number : ', LS_DEV_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
					SET LS_DATA_ERROR_FLAG = 'Y';
				ELSE
					SET LI_DEV_PROPOSAL_ID = @proposal_id;
				END IF;
				SET LI_COUNT = -1;
				SELECT COUNT(1) INTO LI_COUNT FROM proposal_admin_details WHERE DEV_PROPOSAL_ID = LI_DEV_PROPOSAL_ID AND INST_PROPOSAL_ID = LI_IP_PROPOSAL_NUMBER;
				IF LI_COUNT <> 0 THEN
					SET LS_DATA_ERROR_FLAG = 'Y';
					SET LS_DATA_EXISTS = 'Y';
				END IF;
				IF LS_DATA_ERROR_FLAG = 'N' THEN
					SELECT IFNULL(MAX(PROPOSAL_ADMIN_DETAIL_ID),0) + 1 INTO LI_PROPOSAL_ADMIN_DETAIL_ID
					FROM proposal_admin_details;
					INSERT INTO   proposal_admin_details
					(
						PROPOSAL_ADMIN_DETAIL_ID,
						DEV_PROPOSAL_ID,
						INST_PROPOSAL_ID,
						DATE_SUBMITTED_BY_DEPT,
						DATE_RETURNED_TO_DEPT,
						DATE_APPROVED_BY_OSP,
						DATE_SUBMITTED_TO_AGENCY,
						INST_PROP_CREATE_DATE,
						INST_PROP_CREATE_USER,
						SIGNED_BY,
						UPDATE_TIMESTAMP,
						UPDATE_USER
					)
					VALUES
					(
						LI_PROPOSAL_ADMIN_DETAIL_ID,
						LI_DEV_PROPOSAL_ID,
						LI_IP_PROPOSAL_NUMBER,
						LS_DATE_SUBMITTED_BY_DEPT,
						LS_DATE_RETURNED_TO_DEPT,
						LS_DATE_APPROVED_BY_OSP,
						LS_DATE_SUBMITTED_TO_AGENCY,
						LS_INST_PROP_CREATE_DATE,
						LS_IP_CREATE_USER,
						LS_SIGNED_BY,
						CASE WHEN LS_INST_PROP_CREATE_DATE IS NOT NULL THEN LS_INST_PROP_CREATE_DATE ELSE UTC_TIMESTAMP() END,
						CASE WHEN LS_IP_CREATE_USER IS NOT NULL THEN LS_IP_CREATE_USER ELSE 'JHU_ADMIN' END
					);
				END IF;
				IF LS_DATA_ERROR_FLAG = 'N' THEN
					UPDATE stage_proposal_admin_details
					SET VALIDATION_STATUS = 'SUCCESS',
					FIBI_IDENTIFIER = LI_PROPOSAL_ADMIN_DETAIL_ID
					WHERE MIGRATION_PROP_ADMIN_DTLS_ID = LI_RECORD_ID;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'after success update',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
					END IF;
				ELSE
					IF LS_DATA_EXISTS = 'N' THEN
						UPDATE stage_proposal_admin_details
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = -1
						WHERE MIGRATION_PROP_ADMIN_DTLS_ID = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
						END IF;
					END IF;
				END IF;
				END LOOP MIGRATION_IP_ADMIN_CURSOR_LOOP;
				CLOSE MIGRATION_IP_ADMIN_CURSOR;
			END;
		ELSE
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'no data available',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
			END IF;
		END IF;
	END IF;
	IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
		IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
			INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed processing of  ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
			SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
		END IF;
	END IF ;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'Migration end',UTC_TIMESTAMP(),LS_PARENT_PROPOSAL_NUMBER,LI_PARENT_SEQ_NUMBER);
	END IF;
	END LOOP MIGRATION_INST_PROPOSAL_CURSOR_LOOP;
	CLOSE MIGRATION_IP_CURSOR;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('MIGRATION','INSTPROPADMIN',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL,NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM seq_prop_admin_dtls_gntr;
	IF LI_COUNT = 0 THEN
		INSERT INTO seq_prop_admin_dtls_gntr  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(PROPOSAL_ADMIN_DETAIL_ID),0)+1  FROM proposal_admin_details));
	ELSE
		UPDATE seq_prop_admin_dtls_gntr  SET NEXT_VAL = (SELECT IFNULL(MAX(PROPOSAL_ADMIN_DETAIL_ID),0)+1  FROM proposal_admin_details);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END
$$
DELIMITER ;
