DELIMITER $$
CREATE  PROCEDURE `MIGRATION_EPS_PROP_YNQ`(AW_MIGRATED_QUESTIONNAIRE_ID INT, DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_STG_EPS_PROP_YNQ_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID iNT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(20);
DECLARE LI_MODULE_ITEM_KEY INT;
DECLARE LS_QUESTION_ID varchar(4);
DECLARE LS_ANSWER char(1);
DECLARE LI_ANSWER_COUNT INT;
DECLARE LI_MIGRATED_QUESTION_ID INT;
DECLARE LS_EXPLANATION longtext;
DECLARE LS_GROUP_NAME varchar(150);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(20);
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_PROP_YNQ_CREATED INT default 0;
DECLARE LI_PROP_PERS_YNQ_CREATED INT default 0;
DECLARE LS_DATA_ERROR_FLAG varchar(1) default 'N';
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
DECLARE LS_UPDATE_USER VARCHAR(60);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_STG_EPS_PROP_YNQ_ID,'EPS_PROP_YNQ','MIGRATION',LS_ERROR_MSG,UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('EPS_PROP_YNQ') AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_eps_prop_ynq SET VALIDATION_STATUS = 'VALID', MIGRATED_QUESTIONNAIRE_ANSWER_ID = NULL WHERE VALIDATION_STATUS = 'ERROR' and MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1;
			END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM migration_qtn_execution_log;
	ALTER TABLE migration_qtn_execution_log AUTO_INCREMENT = 1;
	SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_prop_ynq;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'EPS_PROP_YNQ';
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
										VALUES 	(LI_BATCH_ID,'MIGRATION','EPS_PROP_YNQ',UTC_TIMESTAMP());
	INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : EPS_PROP_YNQ ',UTC_TIMESTAMP());
END;
	BEGIN
	DECLARE DONE4 INT DEFAULT FALSE;
	DECLARE CUR_EPS_PROP_YNQ_ANS CURSOR FOR
    select distinct proposal_NUMBER from stage_eps_prop_ynq
	where VALIDATION_STATUS = 'VALID';
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
	OPEN CUR_EPS_PROP_YNQ_ANS;
	EPS_PROP_YNQ_ANS_LOOP: LOOP
	FETCH CUR_EPS_PROP_YNQ_ANS INTO LS_PROPOSAL_NUMBER;
	IF DONE4 THEN
		LEAVE EPS_PROP_YNQ_ANS_LOOP;
	END IF;
			SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO  migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('MIGRATION','EPS_PROP_YNQ',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_QUESTION_ID);
					SET LS_DATA_ERROR_FLAG = 'N';
			CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PROPOSAL_NUMBER,@proposal_id);
			IF @proposal_id = -1 THEN
				INSERT INTO migration_questionnaire_errorlog(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (0,'EPS_PROP_YNQ','MIGRATION',CONCAT('Invalid Proposal Number:  ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'JHU_ADMIN');
				update stage_eps_prop_ynq set VALIDATION_STATUS = 'ERROR', MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = -1 , MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1
				where PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER;
			    ITERATE EPS_PROP_YNQ_ANS_LOOP;
			ELSE
				set LI_MODULE_ITEM_KEY = @proposal_id;
			END IF;
					select IFNULL(MAX(QUESTIONNAIRE_ANS_HEADER_ID),0)+1
					into LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
					from quest_answer_header;
					INSERT INTO quest_answer_header(
											QUESTIONNAIRE_ANS_HEADER_ID
											, QUESTIONNAIRE_ID
											, MODULE_ITEM_CODE
											, MODULE_SUB_ITEM_CODE
											, MODULE_ITEM_KEY
											, MODULE_SUB_ITEM_KEY
											, QUESTIONNAIRE_COMPLETED_FLAG
											, UPDATE_TIMESTAMP
											, UPDATE_USER
							)VALUES(
											LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
											, AW_MIGRATED_QUESTIONNAIRE_ID
											, 3
											, 0
											, LI_MODULE_ITEM_KEY
											, ''
											, 'Y'
											, UTC_TIMESTAMP()
											, 'JHU_ADMIN'
								);
				SET SQL_SAFE_UPDATES = 0;
				update stage_eps_prop_ynq set MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = 	LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
                where proposal_number = LS_PROPOSAL_NUMBER;
	begin
		DECLARE DONE2 INT DEFAULT FALSE;
	DECLARE CUR_PROP_YNQ_ANS CURSOR FOR
    select   ID
			, QUESTION_ID
			, ANSWER
			, EXPLANATION
            , UPDATE_USER
			, UPDATE_TIMESTAMP
	from stage_eps_prop_ynq
	where proposal_NUMBER = LS_proposal_NUMBER;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
	OPEN CUR_PROP_YNQ_ANS;
	PROP_YNQ_ANS_LOOP: LOOP
	FETCH CUR_PROP_YNQ_ANS INTO LI_STG_EPS_PROP_YNQ_ID
							, LS_QUESTION_ID
							, LS_ANSWER
							, LS_EXPLANATION
                            , LS_UPDATE_USER
							, LS_UPDATE_TIMESTAMP
							 ;
	IF DONE2 THEN
		LEAVE PROP_YNQ_ANS_LOOP;
	END IF;
					select IFNULL(MAX(QUESTIONNAIRE_ANSWER_ID),0)+1 into LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID from quest_answer;
					select MIGRATED_QUESTION_ID INTO LI_MIGRATED_QUESTION_ID from STAGE_PROP_YNQ where question_id = LS_QUESTION_ID;
					INSERT INTO quest_answer(
											QUESTIONNAIRE_ANSWER_ID
											, QUESTIONNAIRE_ANS_HEADER_ID
											, QUESTION_ID
											, OPTION_NUMBER
											, ANSWER_NUMBER
											, ANSWER
											, ANSWER_LOOKUP_CODE
											, EXPLANATION
											, UPDATE_TIMESTAMP
											, UPDATE_USER
							)VALUES(
											LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID
											, LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
											, LI_MIGRATED_QUESTION_ID
											, NULL
											, 1
											, case LS_ANSWER when 'Y' then 'Yes' when 'N' then 'No' when 'X' then 'NA' end
											, NULL
											, NULL
											, LS_UPDATE_TIMESTAMP
											, LS_UPDATE_USER
								);
					SET SQL_SAFE_UPDATES = 0;
					UPDATE stage_eps_prop_ynq SET
											MIGRATED_QUESTIONNAIRE_ANSWER_ID = LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID
											,VALIDATION_STATUS = 'SUCCESS' where ID =  LI_STG_EPS_PROP_YNQ_ID;
				IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Migrated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Proposal YNQ Answers'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
					SET LS_DATA_ERROR_FLAG = 'N';
					SET LI_MIGRATED_QUESTION_ID = NULL;
					SET LI_STG_EPS_PROP_YNQ_ID = NULL;
					SET LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID = NULL;
					SET LS_QUESTION_ID = NULL;
					SET LS_ANSWER = NULL;
					set LI_MODULE_ITEM_KEY = NULL;
					SET LI_MIGRATED_QUESTIONNAIRE_ID = NULL;
			END LOOP;
		CLOSE CUR_PROP_YNQ_ANS;
		END;
	INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('MIGRATION','EPS_PROP_YNQ',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
                select count(*) into LI_ANSWER_COUNT from quest_answer where QUESTIONNAIRE_ANS_HEADER_ID = LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID;
                    IF LI_ANSWER_COUNT = 0 then
					SET SQL_SAFE_UPDATES = 0;
                     delete from quest_answer_header where QUESTIONNAIRE_ANS_HEADER_ID = LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID;
					 UPDATE stage_eps_prop_ynq SET VALIDATION_STATUS = 'ERROR', MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1, MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1 where proposal_number = LS_PROPOSAL_NUMBER;
                    end if;
                SET LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = NULL;
                SET LS_PROPOSAL_NUMBER = NULL;
		END LOOP;
		CLOSE CUR_EPS_PROP_YNQ_ANS;
		INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
												VALUES ('MIGRATION','EPS_PROP_YNQ',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
				INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Migrated total records ( ', LI_TOTAL_DATA_COUNT,' ) of Proposal YNQ Answers'),UTC_TIMESTAMP()),('Migration completed successfully',UTC_TIMESTAMP());
		END;
set sql_safe_updates = 0;
		update quest_column_nextvalue set
					QUESTIONNAIRE_ANS_HEADER_ID = (select IFNULL(MAX(QUESTIONNAIRE_ANS_HEADER_ID),0)+1 from quest_answer_header)
					,QUESTIONNAIRE_ANSWER_ID = (select  IFNULL(MAX(QUESTIONNAIRE_ANSWER_ID),0)+1 from quest_answer);
					SELECT COUNT(*) INTO LI_SOURCE_COUNT FROM stage_eps_prop_ynq;
					SELECT COUNT(*) INTO LI_DESTINATION_COUNT FROM quest_answer
					           where QUESTIONNAIRE_ANSWER_ID in (select MIGRATED_QUESTIONNAIRE_ANSWER_ID from stage_eps_prop_ynq);
					IF LI_SOURCE_COUNT = LI_DESTINATION_COUNT THEN
						SET LS_MIGRATION_STATUS = 'SUCCESS';
					ELSE
						SET LS_MIGRATION_STATUS = 'ERROR';
					END IF;
					INSERT INTO migration_validation_matrix (MODULE_NAME,DESTINATION_TYPE,SOURCE_NAME,DESTINATION_NAME,SOURCE_COUNT,DESTINATION_COUNT,MIGRATION_STATUS)
					VALUES ('EPS_PROPOSAL_YNQ','FIBI','stage_eps_prop_ynq','quest_answer',LI_SOURCE_COUNT,LI_DESTINATION_COUNT,LS_MIGRATION_STATUS);
		END
$$
DELIMITER ;
