DELIMITER $$
CREATE  PROCEDURE `MIGRATE_IP_ATTACHMENTS_PREVAL`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_ATTACHMENT_TYPE INT;
DECLARE LI_DOCUMENT_STATUS INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_FILE_NAME VARCHAR(150);
DECLARE LS_NARRATIVE_STATUS VARCHAR(1);
DECLARE LS_DOCUMENT LONGBLOB;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'INSTPROPATTACH' AND ERROR_TYPE = 'VALIDATION';
				UPDATE stage_proposal_attachments SET VALIDATION_STATUS = NULL,FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL;
		END IF;
		SET LI_COUNT = -1;
		SELECT COUNT(1) INTO LI_COUNT FROM
		document_status  WHERE DOCUMENT_STATUS_CODE = 1;
		IF LI_COUNT = 0 THEN
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (-100,'INSTPROPATTACH','VALIDATION','Invalid document status : 1',UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END IF;
		SET LI_COUNT = -1;
		SELECT COUNT(1) INTO LI_COUNT FROM
		narrative_status  WHERE UPPER(NARRATIVE_STATUS_CODE) = UPPER('C') AND IS_ACTIVE = 'Y';
		IF LI_COUNT = 0 THEN
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (-100,'INSTPROPATTACH','VALIDATION','invalid narrative status : C',UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_proposal_attachments;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'INSTPROPATTACH';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'VALIDATION','INSTPROPATTACH',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_INST_PROP_ATTACH_CURSOR CURSOR FOR
		SELECT  MIGRATION_PROP_ATTACH_ID,
				PROPOSAL_NUMBER,
				SEQUENCE_NUMBER,
				ATTACHMENT_TYPE_CODE,
				FILE_NAME,
				DOCUMENT
		FROM 	stage_proposal_attachments
		WHERE VALIDATION_STATUS IS NULL AND FIBI_IDENTIFIER IS NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'INSTPROPATTACH','VALIDATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
			OPEN MIGRATION_INST_PROP_ATTACH_CURSOR;
			MIGRATION_INST_PROP_ATTACH_CURSOR_LOOP : LOOP
				FETCH MIGRATION_INST_PROP_ATTACH_CURSOR INTO     	LI_RECORD_ID,
																	LS_PROPOSAL_NUMBER,
																	LI_SEQUENCE_NUMBER,
																	LI_ATTACHMENT_TYPE,
																	LS_FILE_NAME,
																	LS_DOCUMENT;
					IF DONE1 THEN
						LEAVE MIGRATION_INST_PROP_ATTACH_CURSOR_LOOP;
					END IF;
					SET LS_DATA_ERROR_FLAG = 'N';
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					IF LS_FILE_NAME IS NULL THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPATTACH','VALIDATION','File name is mandatory',UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'after file name check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
					SELECT COUNT(1) INTO LI_COUNT FROM
					stage_proposal WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_SEQUENCE_NUMBER AND VALIDATION_STATUS IN ('VALID','SUCCESS');
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPATTACH','VALIDATION',CONCAT('Invalid proposal number :', LS_PROPOSAL_NUMBER, ' and the squence number : ', LI_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'after IP check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM
					proposal_attach_type  WHERE ATTACHMNT_TYPE_CODE = LI_ATTACHMENT_TYPE AND IS_ACTIVE = 'Y';
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPATTACH','VALIDATION',CONCAT('Invalid attachment type :', LI_ATTACHMENT_TYPE),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'after attachment type check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
					IF (IFNULL(TRIM(LS_DOCUMENT),'') = '') THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPATTACH','VALIDATION',CONCAT('The blob data is empty for the proposal number : ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'after blob data check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_proposal_attachments
						SET VALIDATION_STATUS = 'VALID',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_PROP_ATTACH_ID = LI_RECORD_ID;
					ELSE
						UPDATE stage_proposal_attachments
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_PROP_ATTACH_ID = LI_RECORD_ID;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'after update',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
					IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
						IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
							INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed validation of ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
							SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
						END IF;
					END IF ;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'validation end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER,LI_SEQUENCE_NUMBER);
					END IF;
			END LOOP MIGRATION_INST_PROP_ATTACH_CURSOR_LOOP;
			CLOSE MIGRATION_INST_PROP_ATTACH_CURSOR;
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPATTACH',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL,NULL);
		END;
		INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
		SET SQL_SAFE_UPDATES = 1;
		SET FOREIGN_KEY_CHECKS = 1;
		SELECT 1 AS RESULT;
		COMMIT;
END
$$
DELIMITER ;
