DELIMITER $$
CREATE  PROCEDURE `MIGRATION_EPS_PROP_PERS_YNQ`(AW_MIGRATED_QUESTIONNAIRE_ID INT, DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_MIGRATED_QUESTION_ID int;
DECLARE LS_QUESTION_ID varchar(4);
DECLARE LI_COUNT INT;
DECLARE LS_PERSON_ID varchar(9) ;
DECLARE LI_STG_EPS_PROP_YNQ_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID INT;
DECLARE LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID iNT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(20);
DECLARE LI_MODULE_ITEM_KEY INT;
DECLARE LS_ANSWER CHAR(1);
declare LI_ANSWER_COUNT INT;
DECLARE LI_STG_EPS_PROP_PERS_YNQ_ID INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(20);
DECLARE LS_DATA_ERROR_FLAG VARChar(1);
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_PROP_YNQ_CREATED INT default 0;
DECLARE LI_PROP_PERS_YNQ_CREATED INT default 0;
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
DECLARE LS_UPDATE_USER VARCHAR(60);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (ifnull(LI_STG_EPS_PROP_PERS_YNQ_ID,0),'EPS_PROP_PERS_YNQ','MIGRATION',LS_ERROR_MSG,UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('EPS_PROP_PERS_YNQ') AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_eps_prop_Pers_ynq SET VALIDATION_STATUS = 'VALID', MIGRATED_QUESTIONNAIRE_ANSWER_ID = NULL WHERE VALIDATION_STATUS = 'ERROR' and MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1;
		SET SQL_SAFE_UPDATES = 1;
	END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_prop_ynq;
	SELECT IFNULL(MAX(BATCH_ID),0) INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'EPS_PROP_PERS_YNQ';
	INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : EPS_PROP_PERS_YNQ ',UTC_TIMESTAMP());
END;
		BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_EPS_PROP_PERS_YNQ CURSOR FOR
		select distinct PROPOSAL_NUMBER, PERSON_ID
				from stage_eps_prop_pers_ynq
				where VALIDATION_STATUS = 'VALID'
				ORDER by PROPOSAL_NUMBER, PERSON_ID ;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
        OPEN CUR_EPS_PROP_PERS_YNQ;
		EPS_PROP_PERS_YNQ_LOOP: LOOP
		FETCH CUR_EPS_PROP_PERS_YNQ INTO  LS_PROPOSAL_NUMBER
												, LS_PERSON_ID;
		IF DONE1 THEN
			LEAVE EPS_PROP_PERS_YNQ_LOOP;
		END IF;
					CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PROPOSAL_NUMBER,@proposal_id);
					IF @proposal_id = -1 THEN
						INSERT INTO migration_questionnaire_errorlog (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (0,'EPS_PROP_PERS_YNQ','MIGRATION',CONCAT('Invalid Proposal Number:  ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'JHU_ADMIN');
						UPDATE stage_eps_prop_pers_ynq SET
											MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1
											,MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = -1
											,VALIDATION_STATUS = 'ERROR'
								where PROPOSAL_NUMBER =  LS_PROPOSAL_NUMBER;
						ITERATE EPS_PROP_PERS_YNQ_LOOP;
					ELSE
						set LI_MODULE_ITEM_KEY = @proposal_id;
					END IF;
                   set LI_COUNT = -1;
						SELECT COUNT(*) INTO LI_COUNT FROM eps_proposal_persons
						WHERE proposal_id = LS_PROPOSAL_NUMBER
						and UPPER(PERSON_ID) = UPPER(LS_PERSON_ID);
                    IF LI_COUNT <> 1 then
						set LI_COUNT = -1;
						SELECT COUNT(*) INTO LI_COUNT FROM eps_proposal_persons
						WHERE proposal_id = LS_PROPOSAL_NUMBER
						and UPPER(ROLODEX_ID) = UPPER(LS_PERSON_ID);
							IF LI_COUNT <> 1 THEN
								INSERT INTO migration_questionnaire_errorlog (PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
									VALUES  (0 ,'EPS_PROP_PERS_YNQ','MIGRATION',CONCAT('Invalid Proposal Person :  ', LS_PERSON_ID),UTC_TIMESTAMP(),'JHU_ADMIN');
								UPDATE stage_eps_prop_pers_ynq SET
														MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1
														,MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = -1
														,VALIDATION_STATUS = 'ERROR'
											where PERSON_ID =  LS_PERSON_ID;
									  ITERATE EPS_PROP_PERS_YNQ_LOOP;
					END IF;
	END IF;
                    select IFNULL(MAX(QUESTIONNAIRE_ANS_HEADER_ID),0)+1
					into LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
					from quest_answer_header;
					INSERT INTO quest_answer_header(
											QUESTIONNAIRE_ANS_HEADER_ID
											, QUESTIONNAIRE_ID
											, MODULE_ITEM_CODE
											, MODULE_SUB_ITEM_CODE
											, MODULE_ITEM_KEY
											, MODULE_SUB_ITEM_KEY
											, QUESTIONNAIRE_COMPLETED_FLAG
											, UPDATE_TIMESTAMP
											, UPDATE_USER
							)VALUES(
											LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
											, AW_MIGRATED_QUESTIONNAIRE_ID
											, 3
											, 3
											, LI_MODULE_ITEM_KEY
											, LS_PERSON_ID
											, 'Y'
											, UTC_TIMESTAMP()
											, 'JHU_ADMIN'
								);
                         SET SQL_SAFE_UPDATES = 0;
                    update stage_eps_prop_pers_ynq set MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
					where PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER and PERSON_ID = LS_PERSON_ID;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('MIGRATION','EPS_PROP_PERS_YNQ',LI_BATCH_ID,'Inserted Answer header created',UTC_TIMESTAMP(),concat(LI_MODULE_ITEM_KEY ,' : ' ,LS_PERSON_ID ));
					Begin
					DECLARE DONE2 INT DEFAULT FALSE;
					DECLARE CUR_EPS_PROP_PERS_ANS_YNQ CURSOR FOR
					select  ID
							, QUESTION_ID
							, ANSWER
                            , UPDATE_USER
                            , UPDATE_TIMESTAMP
					from stage_eps_prop_pers_ynq
					where VALIDATION_STATUS = 'VALID'
					and proposal_number = LS_PROPOSAL_NUMBER
                    and PERSON_ID = LS_PERSON_ID;
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
					OPEN CUR_EPS_PROP_PERS_ANS_YNQ;
					EPS_PROP_PERS_YNQ_ANS_LOOP: LOOP
					FETCH CUR_EPS_PROP_PERS_ANS_YNQ INTO LI_STG_EPS_PROP_PERS_YNQ_ID
												, LS_QUESTION_ID
												, LS_ANSWER
                                                , LS_UPDATE_USER
                                                , LS_UPDATE_TIMESTAMP;
					IF DONE2 THEN
						LEAVE EPS_PROP_PERS_YNQ_ANS_LOOP;
					END IF;
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('MIGRATION','EPS_PROP_PERS_YNQ',LI_BATCH_ID,'Migration of answer started',UTC_TIMESTAMP(),LS_QUESTION_ID);
					SELECT  MIGRATED_QUESTION_ID INTO LI_MIGRATED_QUESTION_ID
					FROM stage_prop_pers_ynq
					WHERE QUESTION_ID = LS_QUESTION_ID;
					select ifnull(max(QUESTIONNAIRE_ANSWER_ID),0)+1 into LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID from quest_answer;
					INSERT INTO quest_answer(
											QUESTIONNAIRE_ANSWER_ID
											, QUESTIONNAIRE_ANS_HEADER_ID
											, QUESTION_ID
											, OPTION_NUMBER
											, ANSWER_NUMBER
											, ANSWER
											, ANSWER_LOOKUP_CODE
											, EXPLANATION
											, UPDATE_TIMESTAMP
											, UPDATE_USER
									)VALUES(
											LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID
											, LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
											, LI_MIGRATED_QUESTION_ID
											, NULL
											, 1
											, case LS_ANSWER when 'Y' then 'Yes' when 'N' then 'No' when 'X' then 'NA' end
											, NULL
											, NULL
											, LS_UPDATE_TIMESTAMP
											, LS_UPDATE_USER
								);
					SET SQL_SAFE_UPDATES = 0;
					UPDATE stage_eps_prop_pers_ynq SET
											MIGRATED_QUESTIONNAIRE_ANSWER_ID = LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID
											,MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID
											,VALIDATION_STATUS = 'SUCCESS' where ID =  LI_STG_EPS_PROP_PERS_YNQ_ID;
				IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Migrated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Proposal Person YNQ Ansers'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('MIGRATION','EPS_PROP_PERS_YNQ',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LS_QUESTION_ID);
				END LOOP;
		CLOSE CUR_EPS_PROP_PERS_ANS_YNQ;
		END;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
												VALUES ('MIGRATION','EPS_PROP_PERS_YNQ',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
					 select count(*) into LI_ANSWER_COUNT from quest_answer where QUESTIONNAIRE_ANS_HEADER_ID = LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID;
                    IF LI_ANSWER_COUNT = 0 then
					SET SQL_SAFE_UPDATES = 0;
                     delete from quest_answer_header where QUESTIONNAIRE_ANS_HEADER_ID = LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID;
					 UPDATE stage_eps_prop_pers_ynq SET VALIDATION_STATUS = 'ERROR', MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1, MIGRATED_QUESTIONNAIRE_ANSWER_ID = -1 where proposal_number = LS_PROPOSAL_NUMBER  and PERSON_ID = LS_PERSON_ID;
                    end if;
					SET LS_DATA_ERROR_FLAG = 'N';
					SET LI_STG_EPS_PROP_PERS_YNQ_ID = NULL;
					SET LI_MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID = NULL;
					SET LI_MIGRATED_QUESTIONNAIRE_ANSWER_ID = NULL;
					SET LS_QUESTION_ID = NULL;
					SET LS_ANSWER = NULL;
					SET LI_MIGRATED_QUESTION_ID = NULL;
					SET LS_PROPOSAL_NUMBER = NULL;
					set LI_MODULE_ITEM_KEY = NULL;
					SET LS_PERSON_ID = NULL;
					SET LI_MIGRATED_QUESTIONNAIRE_ID = NULL;
		END LOOP;
		CLOSE CUR_EPS_PROP_PERS_YNQ;
		END;
		SET SQL_SAFE_UPDATES = 0;
		update quest_column_nextvalue set
						QUESTIONNAIRE_ANS_HEADER_ID = (select IFNULL(MAX(QUESTIONNAIRE_ANS_HEADER_ID),0)+1 from quest_answer_header)
						,QUESTIONNAIRE_ANSWER_ID = (select  IFNULL(MAX(QUESTIONNAIRE_ANSWER_ID),0)+1 from quest_answer);
INSERT INTO migration_qtn_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Migrated total records ( ', LI_TOTAL_DATA_COUNT,' ) of Proposal Person YNQ Answers'),UTC_TIMESTAMP()),('Migration completed successfully',UTC_TIMESTAMP());
					SELECT COUNT(*) INTO LI_SOURCE_COUNT FROM stage_eps_prop_pers_ynq;
					SELECT COUNT(*) INTO LI_DESTINATION_COUNT FROM quest_answer where update_user = 'JHU_ADMIN';
					IF LI_SOURCE_COUNT = LI_DESTINATION_COUNT THEN
						SET LS_MIGRATION_STATUS = 'SUCCESS';
					ELSE
						SET LS_MIGRATION_STATUS = 'ERROR';
					END IF;
				 	INSERT INTO migration_validation_matrix (MODULE_NAME,DESTINATION_TYPE,SOURCE_NAME,DESTINATION_NAME,SOURCE_COUNT,DESTINATION_COUNT,MIGRATION_STATUS)
					VALUES ('EPS_PROPOSAL_PERSON_YNQ','FIBI','stage_eps_prop_pers_ynq','quest_answer',LI_SOURCE_COUNT,LI_DESTINATION_COUNT,LS_MIGRATION_STATUS);
		END
$$
DELIMITER ;
