DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_IP_PI_TO_AGREEMENT`(
	IN AV_SOURCE_MODULE_ID INT,
    IN AV_DESTINATION_MODULE_ID INT,
    IN AV_DESTINATION_MODULE_CODE INT,
    IN AV_SOURCE_MODULE_CODE INT,
    IN AV_UPDATED_USER VARCHAR(60)
)
BEGIN
    DECLARE V_COUNT INT;
    DECLARE V_START_DATE DATE;
    DECLARE V_END_DATE DATE;
    DECLARE V_UNIT_NUMBER VARCHAR(8);
    DECLARE V_UNIT_NAME VARCHAR(255);
    DECLARE LS_ROLE_ID INT;
    DECLARE LS_PERSON_ID VARCHAR(40);
    DECLARE LS_DONE INT DEFAULT FALSE;
    DECLARE LS_CURSOR CURSOR FOR SELECT ROLE_ID FROM MODULE_DERIVED_ROLES WHERE MODULE_CODE = '13' AND IS_ACTIVE = 'Y' AND AUTO_GRANT_TO_PI = 'Y';
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET LS_DONE = TRUE;
    SET LS_PERSON_ID = (SELECT PERSON_ID FROM PROPOSAL_PERSONS WHERE PROPOSAL_ID = AV_SOURCE_MODULE_ID AND PROP_PERSON_ROLE_ID = 3);
    SELECT COUNT(*) INTO V_COUNT FROM agreement_people WHERE PEOPLE_TYPE_ID = 3 AND AGREEMENT_REQUEST_ID = AV_DESTINATION_MODULE_ID;
    IF V_COUNT = 0 THEN
         INSERT INTO AGREEMENT_PEOPLE (
            AGREEMENT_REQUEST_ID,
            PERSON_ID,
            ROLODEX_ID,
            FULL_NAME,
            PEOPLE_TYPE_ID,
            UPDATE_TIMESTAMP,
            UPDATE_USER
        )
			SELECT
            AV_DESTINATION_MODULE_ID,
            PERSON_ID,
            ROLODEX_ID,
            FULL_NAME,
            3,
            UTC_TIMESTAMP(),
            AV_UPDATED_USER
            FROM proposal_persons WHERE
            PROPOSAL_ID = AV_SOURCE_MODULE_ID AND PROP_PERSON_ROLE_ID =3
        ;
	END IF;
    IF LS_PERSON_ID IS NOT NULL OR LS_PERSON_ID <> '' THEN
		OPEN LS_CURSOR;
		ROLE_LOOP: LOOP
			FETCH LS_CURSOR INTO LS_ROLE_ID;
		IF LS_DONE THEN
			LEAVE ROLE_LOOP;
		END IF;
		INSERT INTO AGREEMENT_PEOPLE_ROLES
			(AGREEMENT_REQUEST_ID,
			IS_SYSTEM_DERIVED_ROLE,
			PERSON_ID,
			ROLE_ID,
			UPDATE_TIMESTAMP,
			UPDATE_USER)
		SELECT
			AV_DESTINATION_MODULE_ID,
			'Y',
			LS_PERSON_ID,
			LS_ROLE_ID,
			NOW(),
			AV_UPDATED_USER
		WHERE NOT EXISTS (	SELECT 1
							FROM AGREEMENT_PEOPLE_ROLES
							WHERE ROLE_ID = LS_ROLE_ID
							AND PERSON_ID = LS_PERSON_ID
							AND AGREEMENT_REQUEST_ID = AV_DESTINATION_MODULE_ID);
		END LOOP;
		CLOSE LS_CURSOR;
	END IF;
END
$$
DELIMITER ;
