DELIMITER $$
CREATE  PROCEDURE `MIGRATE_EPS_PROP_KPUNIT_PREVAL`(DATA_PROPOSAL_NUMBER VARCHAR(8),DATA_PERSON_ID VARCHAR(10),FOR_AUDIT INT, OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LS_UNIT_NUMBER VARCHAR(8);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SELECT IFNULL(MAX(BATCH_ID),0) INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'DEVPROPKPUNITS';
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_DEV_PROP_KP_UNITS_CURSOR CURSOR FOR
		SELECT  MIGRATION_EPS_PROP_KP_UNIT_ID,
				UNIT_NUMBER
		FROM stage_eps_prop_kp_units WHERE VALIDATION_STATUS IS NULL AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = DATA_PERSON_ID;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'DEVPROPKPUNITS','VALIDATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
			OPEN MIGRATION_DEV_PROP_KP_UNITS_CURSOR;
			MIGRATION_DEV_PROP_KP_UNITS_CURSOR_LOOP :   LOOP
			FETCH MIGRATION_DEV_PROP_KP_UNITS_CURSOR 	INTO     		LI_RECORD_ID,
																		LS_UNIT_NUMBER;
					IF DONE1 THEN
						LEAVE MIGRATION_DEV_PROP_KP_UNITS_CURSOR_LOOP;
					END IF;
					SET LS_DATA_ERROR_FLAG = 'N';
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','DEVPROPKPUNITS',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM
					unit WHERE UNIT_NUMBER = LS_UNIT_NUMBER AND IS_ACTIVE = 'Y';
					IF LI_COUNT = 0 THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'DEVPROPKPUNITS','VALIDATION',IFNULL(CONCAT('Invalid unit number :  ', LS_UNIT_NUMBER),'Lead unit is mandatory and cannot be NULL') ,UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','DEVPROPKPUNITS',LI_BATCH_ID,'after unit check',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
					END IF;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_eps_prop_kp_units
						SET VALIDATION_STATUS = 'VALID',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_EPS_PROP_KP_UNIT_ID = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','DEVPROPKPUNITS',LI_BATCH_ID,'after valid update',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
						END IF;
					ELSE
						UPDATE stage_eps_prop_kp_units
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_EPS_PROP_KP_UNIT_ID = LI_RECORD_ID;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','DEVPROPKPUNITS',LI_BATCH_ID,'after error update',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
						END IF;
					END IF;
				IF FOR_AUDIT = 1 THEN
					INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','DEVPROPKPUNITS',LI_BATCH_ID,'Validation end',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
				END IF;
			END LOOP MIGRATION_DEV_PROP_KP_UNITS_CURSOR_LOOP;
			CLOSE MIGRATION_DEV_PROP_KP_UNITS_CURSOR;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','DEVPROPKPUNITS',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
			END IF;
		END;
		SELECT COUNT(1) INTO DATA_ERROR_COUNT FROM stage_eps_prop_kp_units WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = DATA_PERSON_ID;
		COMMIT;
END
$$
DELIMITER ;
