DELIMITER $$
CREATE  PROCEDURE `MIGRATE_AWARD_CUSTDATA`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_SEQUENCE_NUMBER INT;
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LI_COLUMN_ID INT;
DECLARE LI_COLUMN_VERSION_NUMBER INT;
DECLARE LI_CUSTOM_DATA_ID INT;
DECLARE LI_MAS_CUSTOM_DATA_ID INT;
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT;
DECLARE LI_AWARD_ID INT;
DECLARE LI_MASTER_AWARD_ID INT;
DECLARE LI_MODULE_ITEM_CODE INT;
DECLARE LS_JHU_AWARD_NUMBER CHAR(10);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_COLUMN_NAME VARCHAR(30);
DECLARE LS_COLUMN_VALUE VARCHAR(2000);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	IF DATA_REFRESH_FLAG = 1 THEN
			DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'AWRDCUSTOM' AND ERROR_TYPE = 'MIGRATION';
			UPDATE stage_award_custom_data SET VALIDATION_STATUS = 'VALID',FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1;
	END IF;
END;
BEGIN
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM coeus_module WHERE UPPER(DESCRIPTION) = UPPER('award') AND IS_ACTIVE = 'Y';
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-100,'AWRDCUSTOM','MIGRATION',CONCAT('Invalid module item code : award'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT MODULE_CODE INTO LI_MODULE_ITEM_CODE FROM coeus_module WHERE UPPER(DESCRIPTION) = UPPER('award') AND IS_ACTIVE = 'Y';
	END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'AWRDCUSTOM';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','AWRDCUSTOM',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
IF LS_DATA_ERROR_FLAG = 'N' THEN
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE  MIGRATE_AWARD_CUSTOM CURSOR FOR
	SELECT 		MIGRATION_AWARD_CUSTOM_DATA_ID,
				MIT_AWARD_NUMBER,
				SEQUENCE_NUMBER,
				COLUMN_NAME,
				COLUMN_VALUE,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM 	stage_award_custom_data  WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDCUSTOM','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATE_AWARD_CUSTOM;
	MIGRATE_AWARD_CUSTOM_LOOP		:		LOOP
	FETCH MIGRATE_AWARD_CUSTOM				INTO		LI_RECORD_ID,
														LS_JHU_AWARD_NUMBER,
														LI_SEQUENCE_NUMBER,
														LS_COLUMN_NAME,
														LS_COLUMN_VALUE,
														LS_UPDATE_TIMESTAMP,
														LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATE_AWARD_CUSTOM_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_CUSTOM_DATA_ELEMENTS_ID = -1;
	SET LI_COLUMN_ID = -1;
	SET LI_COLUMN_VERSION_NUMBER = -1;
	SET LI_AWARD_ID = -1;
	SET LI_MASTER_AWARD_ID = -1;
	SET LI_CUSTOM_DATA_ID = -1;
	SET LI_MAS_CUSTOM_DATA_ID = -1;
	SET LI_MAX_SEQUENCE_NUMBER = -1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	SET LS_AWARD_NUMBER = REPLACE(LS_JHU_AWARD_NUMBER,'-','-00');
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,CONCAT('Changed award number',LS_AWARD_NUMBER),UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
	IF LI_COUNT = 0 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDCUSTOM','MIGRATION',CONCAT('Invalid award number : ', LS_AWARD_NUMBER),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT IFNULL(MAX(SEQUENCE_NUMBER),-1) INTO LI_MAX_SEQUENCE_NUMBER FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER;
		IF LI_MAX_SEQUENCE_NUMBER <> -1 THEN
			SELECT AWARD_ID INTO LI_AWARD_ID FROM
			award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER;
		ELSE
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'AWRDCUSTOM','MIGRATION',CONCAT('Invalid sequence number :', LI_MAX_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END IF;
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'after award check',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END IF;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM custom_data_elements WHERE UPPER(CUSTOM_ELEMENT_NAME) = UPPER(LS_COLUMN_NAME);
	IF LI_COUNT <> 1 THEN
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'AWRDCUSTOM','MIGRATION',CONCAT('Invalid custom element :', LS_COLUMN_NAME),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	ELSE
		SELECT CUSTOM_DATA_ELEMENTS_ID,COLUMN_ID,COLUMN_VERSION_NUMBER INTO LI_CUSTOM_DATA_ELEMENTS_ID,LI_COLUMN_ID,LI_COLUMN_VERSION_NUMBER FROM
		custom_data_elements WHERE UPPER(CUSTOM_ELEMENT_NAME) = UPPER(LS_COLUMN_NAME);
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'after custom data elements check',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END IF;
	/*IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1 INTO LI_CUSTOM_DATA_ID FROM custom_data;
		INSERT INTO custom_data
		(
			CUSTOM_DATA_ID,
			CUSTOM_DATA_ELEMENTS_ID,
			MODULE_ITEM_CODE,
			MODULE_SUB_ITEM_CODE,
			MODULE_ITEM_KEY,
			MODULE_SUB_ITEM_KEY,
			VALUE,
			UPDATE_TIMESTAMP,
			UPDATE_USER,
			COLUMN_ID,
			COLUMN_VERSION_NUMBER,
			DESCRIPTION
		)
		VALUES
		(
			LI_CUSTOM_DATA_ID,
			LI_CUSTOM_DATA_ELEMENTS_ID,
			LI_MODULE_ITEM_CODE,
			0,
			LI_AWARD_ID,
			0,
			LS_COLUMN_VALUE,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER,
			LI_COLUMN_ID,
			LI_COLUMN_VERSION_NUMBER,
			NULL
		);
	END IF;*/
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'after insert',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
		END IF;
		-- Master logic
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'master logic begin',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
		END IF;
			SET LI_COUNT = -1;
			SELECT COUNT(1) INTO LI_COUNT FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
			IF LI_COUNT = 0 THEN
				INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_RECORD_ID,'AWRDCUSTOM','MIGRATION',CONCAT('Invalid master award data with award number :', LS_AWARD_NUMBER,' and the sequence number : 0'),UTC_TIMESTAMP(),'quickstart');
				SET LS_DATA_ERROR_FLAG = 'Y';
			ELSE
				SELECT AWARD_ID INTO LI_MASTER_AWARD_ID FROM award WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
			END IF;
			IF LS_DATA_ERROR_FLAG = 'N' THEN
				SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1 INTO LI_MAS_CUSTOM_DATA_ID FROM custom_data;
				INSERT INTO custom_data
				(
					CUSTOM_DATA_ID,
					CUSTOM_DATA_ELEMENTS_ID,
					MODULE_ITEM_CODE,
					MODULE_SUB_ITEM_CODE,
					MODULE_ITEM_KEY,
					MODULE_SUB_ITEM_KEY,
					VALUE,
					UPDATE_TIMESTAMP,
					UPDATE_USER,
					COLUMN_ID,
					COLUMN_VERSION_NUMBER,
					DESCRIPTION
				)
				VALUES
				(
					LI_MAS_CUSTOM_DATA_ID,
					LI_CUSTOM_DATA_ELEMENTS_ID,
					LI_MODULE_ITEM_CODE,
					0,
					LI_MASTER_AWARD_ID,
					0,
					LS_COLUMN_VALUE,
					LS_UPDATE_TIMESTAMP,
					LS_UPDATE_USER,
					LI_COLUMN_ID,
					LI_COLUMN_VERSION_NUMBER,
					NULL
				);
			END IF;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'master logic end',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
			END IF;
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		UPDATE stage_award_custom_data SET VALIDATION_STATUS = 'SUCCESS', FIBI_IDENTIFIER = LI_MAS_CUSTOM_DATA_ID WHERE MIGRATION_AWARD_CUSTOM_DATA_ID = LI_RECORD_ID;
	ELSE
		UPDATE stage_award_custom_data SET VALIDATION_STATUS = 'ERROR', FIBI_IDENTIFIER = -1 WHERE MIGRATION_AWARD_CUSTOM_DATA_ID = LI_RECORD_ID;
	END IF;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'migration end',UTC_TIMESTAMP(),LS_JHU_AWARD_NUMBER);
	END LOOP MIGRATE_AWARD_CUSTOM_LOOP;
	CLOSE MIGRATE_AWARD_CUSTOM;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','AWRDCUSTOM',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL);
END;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM custom_data_id_generator;
	IF LI_COUNT = 0 THEN
	INSERT INTO custom_data_id_generator  (NEXT_VAL) VALUES ((SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1  FROM custom_data));
	ELSE
	UPDATE custom_data_id_generator   SET NEXT_VAL = (SELECT IFNULL(MAX(CUSTOM_DATA_ID),0) + 1  FROM custom_data);
	END IF;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END IF;
END
$$
DELIMITER ;
