DELIMITER $$
CREATE  PROCEDURE `MIGRATE_EPS_PROP_KPUNIT`(DATA_PROPOSAL_NUMBER VARCHAR(8),DATA_PROPOSAL_ID INT,DATA_PERSON_ID VARCHAR(10),DATA_PROP_PERSON_ID INT,FOR_AUDIT INT, OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_PROP_PERSON_UNIT_ID INT;
DECLARE LI_PROPOSAL_PERSON_ID INT;
DECLARE LI_PROP_PERSON_COUNT INT;
DECLARE LI_PROP_ROLODEX_COUNT INT;
DECLARE LI_PROP_PERSON_UNIT_IDCHECK INT;
DECLARE LS_UNIT_NUMBER VARCHAR(8);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UNIT_TYPE VARCHAR(20);
DECLARE LS_LEAD_UNIT_FLAG VARCHAR(1);
DECLARE LS_SOURCE_TYPE VARCHAR(20);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SELECT IFNULL(MAX(BATCH_ID),0) INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'DEVPROPKPUNITS';
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPKPUNITS',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
END;
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_DEV_PROP_UNITS_CURSOR_1 CURSOR FOR
	SELECT  MIGRATION_EPS_PROP_KP_UNIT_ID,
		UNIT_NUMBER,
		UPDATE_TIMESTAMP,
		UPDATE_USER
	FROM stage_eps_prop_kp_units WHERE VALIDATION_STATUS = 'VALID' AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = DATA_PERSON_ID AND FIBI_IDENTIFIER IS NULL;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'DEVPROPKPUNITS','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN   MIGRATION_DEV_PROP_UNITS_CURSOR_1;
	MIGRATION_DEV_PROP_UNITS_CURSOR_LOOP_1               :     LOOP
	FETCH MIGRATION_DEV_PROP_UNITS_CURSOR_1                    INTO      LI_RECORD_ID,
																		LS_UNIT_NUMBER,
																		LS_UPDATE_TIMESTAMP,
																		LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATION_DEV_PROP_UNITS_CURSOR_LOOP_1;
	END IF;
    SET LS_DATA_ERROR_FLAG = 'N';
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPKPUNITS',LI_BATCH_ID,'before data exits check',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
	END IF;
	SET LI_PROP_PERSON_UNIT_ID = -1;
	SET LI_COUNT = -1;
	SELECT COUNT(1) INTO LI_COUNT FROM eps_prop_person_units WHERE PROPOSAL_ID = DATA_PROPOSAL_NUMBER AND PROPOSAL_PERSON_ID = DATA_PROP_PERSON_ID AND UNIT_NUMBER = LS_UNIT_NUMBER;
	IF LI_COUNT = 1 THEN
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'DEVPROPKPUNITS','MIGRATION',CONCAT('The same proposal person details are added more than once for the proposal person id :  ', DATA_PERSON_ID,' and the proposal number : ',DATA_PROPOSAL_NUMBER,' and the unit number : ',LS_UNIT_NUMBER),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF FOR_AUDIT = 1 THEN
		INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPKPUNITS',LI_BATCH_ID,'before insert',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(PROP_PERSON_UNIT_ID),0) + 1 INTO LI_PROP_PERSON_UNIT_ID
		FROM eps_prop_person_units;
		INSERT INTO   eps_prop_person_units
		(
			PROP_PERSON_UNIT_ID,
			PROPOSAL_ID,
			PROPOSAL_PERSON_ID,
			LEAD_UNIT_FLAG,
			UNIT_NUMBER,
			UPDATE_TIMESTAMP,
			UPDATE_USER
		)
		VALUES
		(
			LI_PROP_PERSON_UNIT_ID,
			DATA_PROPOSAL_NUMBER,
			DATA_PROP_PERSON_ID,
			'N',
			LS_UNIT_NUMBER,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER
		);
		UPDATE stage_eps_prop_kp_units
		SET VALIDATION_STATUS = 'SUCCESS',
		FIBI_IDENTIFIER = LI_PROP_PERSON_UNIT_ID
		WHERE MIGRATION_EPS_PROP_KP_UNIT_ID = LI_RECORD_ID;
	ELSE
		UPDATE stage_eps_prop_kp_units
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = -1
		WHERE MIGRATION_EPS_PROP_KP_UNIT_ID = LI_RECORD_ID;
	END IF;
	END LOOP MIGRATION_DEV_PROP_UNITS_CURSOR_LOOP_1;
	CLOSE MIGRATION_DEV_PROP_UNITS_CURSOR_1;
	INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','DEVPROPKPUNITS',LI_BATCH_ID,'Migration end',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER);
END;
SELECT COUNT(1) INTO DATA_ERROR_COUNT FROM  stage_eps_prop_kp_units WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1 AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND PERSON_ID = DATA_PERSON_ID;
COMMIT;
END
$$
DELIMITER ;
