DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_IP_ADMINDTLS_PREVAL`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_IP_SEQUENCE_NUMBER INT;
DECLARE LS_DEV_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_IP_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_PROPOSAL_CREATE_USER VARCHAR(8);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
		IF DATA_REFRESH_FLAG = 1 THEN
				DELETE FROM migration_transaction_errorlog WHERE SOURCE_TYPE = 'INSTPROPADMIN' AND ERROR_TYPE = 'VALIDATION';
				UPDATE stage_proposal_admin_details SET VALIDATION_STATUS = NULL,FIBI_IDENTIFIER = NULL WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL;
		END IF;
END;
BEGIN
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_proposal_admin_details;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'INSTPROPADMIN';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'VALIDATION','INSTPROPADMIN',UTC_TIMESTAMP());
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution',UTC_TIMESTAMP());
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR CURSOR FOR
		SELECT  MIGRATION_PROP_ADMIN_DTLS_ID,
				DEV_PROPOSAL_NUMBER,
				INST_PROPOSAL_NUMBER,
				INST_PROP_SEQUENCE_NUMBER,
				INST_PROP_CREATE_USER
		FROM 	stage_proposal_admin_details
		WHERE VALIDATION_STATUS IS NULL AND FIBI_IDENTIFIER IS NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
					(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'INSTPROPADMIN','VALIDATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
			OPEN MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR;
			MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR_LOOP :    LOOP
				FETCH MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR INTO     	LI_RECORD_ID,
																			LS_DEV_PROPOSAL_NUMBER,
																			LS_IP_PROPOSAL_NUMBER,
																			LI_IP_SEQUENCE_NUMBER,
																			LS_PROPOSAL_CREATE_USER;
					IF DONE1 THEN
						LEAVE MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR_LOOP;
					END IF;
					SET LS_DATA_ERROR_FLAG = 'N';
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPADMIN',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_IP_PROPOSAL_NUMBER,LI_IP_SEQUENCE_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM
					stage_eps_proposal WHERE PROPOSAL_NUMBER = LS_DEV_PROPOSAL_NUMBER AND VALIDATION_STATUS IN ('VALID','SUCCESS');
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPADMIN','VALIDATION',CONCAT('Invalid proposal number :', LS_DEV_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPADMIN',LI_BATCH_ID,CONCAT('after dev proposal check',LS_DEV_PROPOSAL_NUMBER),UTC_TIMESTAMP(),LS_IP_PROPOSAL_NUMBER,LI_IP_SEQUENCE_NUMBER);
					END IF;
					SET LI_COUNT = -1;
					SELECT COUNT(1) INTO LI_COUNT FROM
					stage_proposal  WHERE PROPOSAL_NUMBER = LS_IP_PROPOSAL_NUMBER  AND VALIDATION_STATUS IN ('VALID','SUCCESS');
					IF LI_COUNT = 0 THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPADMIN','VALIDATION',CONCAT('Invalid proposal number :', LS_IP_PROPOSAL_NUMBER, ' and the squence number : ', LI_IP_SEQUENCE_NUMBER),UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPADMIN',LI_BATCH_ID,'after IP check',UTC_TIMESTAMP(),LS_IP_PROPOSAL_NUMBER,LI_IP_SEQUENCE_NUMBER);
					END IF;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_proposal_admin_details
						SET VALIDATION_STATUS = 'VALID',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_PROP_ADMIN_DTLS_ID = LI_RECORD_ID;
					ELSE
						UPDATE stage_proposal_admin_details
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_PROP_ADMIN_DTLS_ID = LI_RECORD_ID;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPADMIN',LI_BATCH_ID,'after update',UTC_TIMESTAMP(),LS_IP_PROPOSAL_NUMBER,LI_IP_SEQUENCE_NUMBER);
					END IF;
					IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
						IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
							INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES (CONCAT('Completed validation of ',LI_TOTAL_PROCESSED_DATA_COUNT,' records'),UTC_TIMESTAMP());
							SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
						END IF;
					END IF ;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPADMIN',LI_BATCH_ID,'validation end',UTC_TIMESTAMP(),LS_IP_PROPOSAL_NUMBER,LI_IP_SEQUENCE_NUMBER);
					END IF;
			END LOOP MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR_LOOP;
			CLOSE  MIGRATION_INST_PROP_ADMIN_DETAILS_CURSOR;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPADMIN',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),NULL,NULL);
			END IF;
		END;
		INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
		SET SQL_SAFE_UPDATES = 1;
		SET FOREIGN_KEY_CHECKS = 1;
		SELECT 1 AS RESULT;
		COMMIT;
END
$$
DELIMITER ;
