DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATION_EPS_PROP_YNQ_PREVAL`(DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_STG_EPS_PROP_YNQ_ID INT;
DECLARE LS_QUESTION_ID VARCHAR(4);
DECLARE LS_ANSWER CHAR(1);
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1) DEFAULT 'N';
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_STG_EPS_PROP_YNQ_ID,'EPS_PROP_YNQ','VALIDATION',CONCAT(LS_ERROR_MSG),UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('EPS_PROP_YNQ') AND ERROR_TYPE = 'VALIDATION';
			UPDATE stage_eps_prop_ynq SET VALIDATION_STATUS = NULL WHERE VALIDATION_STATUS = 'ERROR' AND MIGRATED_QUESTIONNAIRE_ANS_HEADER_ID IS NULL and MIGRATED_QUESTIONNAIRE_ANSWER_ID is null;
		SET SQL_SAFE_UPDATES = 1;
	END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM migration_execution_log;
	ALTER TABLE migration_execution_log AUTO_INCREMENT = 1;
SET SQL_SAFE_UPDATES = 1;
SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_eps_prop_ynq;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'EPS_PROP_YNQ';
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
										VALUES 	(LI_BATCH_ID,'VALIDATION','EPS_PROP_YNQ',UTC_TIMESTAMP());
	INSERT INTO migration_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : EPS_PROP_YNQ ',UTC_TIMESTAMP());
END;
		BEGIN
		DECLARE DONE3 INT DEFAULT FALSE;
		DECLARE CUR_YNQ_EPS_PROP CURSOR FOR
		select ID
				, PROPOSAL_NUMBER
				, QUESTION_ID
				, ANSWER
		from stage_eps_prop_ynq
		where VALIDATION_STATUS is NULL
        ;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
		OPEN CUR_YNQ_EPS_PROP;
		YNQ_EPS_PROP_LOOP: LOOP
		FETCH CUR_YNQ_EPS_PROP INTO LI_STG_EPS_PROP_YNQ_ID
									, LS_PROPOSAL_NUMBER
									, LS_QUESTION_ID
									, LS_ANSWER;
		IF DONE3 THEN
			LEAVE YNQ_EPS_PROP_LOOP;
		END IF;
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('VALIDATION','EPS_PROP_YNQ',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
					SET LS_DATA_ERROR_FLAG = 'N';
					SELECT COUNT(*) INTO LI_COUNT FROM stage_eps_proposal
					WHERE PROPOSAL_NUMBER  = LS_PROPOSAL_NUMBER AND VALIDATION_STATUS IN ('VALID','SUCCESS');
					IF LI_COUNT <> 1 THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_EPS_PROP_YNQ_ID,'EPS_PROP_YNQ','VALIDATION',CONCAT('Invalid Proposal Number:  ', LS_PROPOSAL_NUMBER),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y' ;
					END IF;
					IF LS_QUESTION_ID IS NULL THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_EPS_PROP_YNQ_ID,'EPS_PROP_YNQ','VALIDATION',CONCAT('Invalid Question ID:  ', LS_QUESTION_ID),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y' ;
					ELSE
						SET LI_COUNT = -1;
                         select count(*) into LI_COUNT from stage_prop_ynq
						 where question_id = LS_QUESTION_ID;
						 IF LI_COUNT = 0 THEN
							 INSERT INTO migration_questionnaire_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_STG_EPS_PROP_YNQ_ID,'EPS_PROP_YNQ','VALIDATION',CONCAT('Invalid Question ID:  ', LS_QUESTION_ID),UTC_TIMESTAMP(),'JHU_ADMIN');
							SET LS_DATA_ERROR_FLAG = 'Y' ;
						END IF;
					END IF;
					IF (trim(LS_ANSWER) IS NULL or trim(LS_ANSWER) = '' or (trim(LS_ANSWER) != 'Y' and trim(LS_ANSWER) != 'N' and trim(LS_ANSWER) != 'X'))THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_EPS_PROP_YNQ_ID,'EPS_PROP_YNQ','VALIDATION',concat('Invalid Answer : ', ifnull(LS_ANSWER,'NULL')),UTC_TIMESTAMP(),'JHU_ADMIN');
					END IF;
					SET SQL_SAFE_UPDATES = 0;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('VALIDATION','EPS_PROP_YNQ',LI_BATCH_ID,concat(LS_DATA_ERROR_FLAG,' : LS_DATA_ERROR_FLAG'),UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
                    IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_eps_prop_ynq SET VALIDATION_STATUS = 'VALID' WHERE ID = LI_STG_EPS_PROP_YNQ_ID;
					ELSE
						UPDATE stage_eps_prop_ynq SET VALIDATION_STATUS = 'ERROR' WHERE ID = LI_STG_EPS_PROP_YNQ_ID;
					END IF;
				SET SQL_SAFE_UPDATES = 1;
				IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Validated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Proposal YNQ Ansers'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('VALIDATION','EPS_PROP_YNQ',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LS_QUESTION_ID);
					set LS_DATA_ERROR_FLAG = 'N';
					set LI_STG_EPS_PROP_YNQ_ID = NULL;
					set LS_PROPOSAL_NUMBER = NULL;
					set LS_QUESTION_ID = NULL;
					set LS_ANSWER = NULL;
		END LOOP;
		CLOSE CUR_YNQ_EPS_PROP;
		INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','EPS_PROP_YNQ',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
			INSERT INTO migration_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Validated total records ( ', LI_TOTAL_DATA_COUNT,' ) of eps_proposal YNQ'),UTC_TIMESTAMP()),('Validation completed successfully',UTC_TIMESTAMP());
		END;
END
$$
DELIMITER ;
