DELIMITER $$
CREATE  PROCEDURE `MIGRATION_PROP_YNQ_PREVAL`(DATA_REFRESH_FLAG INT)
BEGIN
DECLARE LI_STG_PROP_YNQ_ID INT;
DECLARE LS_QUESTION_ID VARCHAR(4);
DECLARE LS_DESCRIPTION VARCHAR(400);
DECLARE LS_QUESTION_TYPE CHAR(1);
DECLARE LS_STATUS CHAR(1);
DECLARE LI_STG_PROP_EXP_YNQ_ID INT;
DECLARE LS_EXPLANATION LONGTEXT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1) default 'N';
DECLARE LS_ERROR_MSG VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_BATCH_ID INT;
DECLARE LI_TOTAL_PROCESSED_DATA_COUNT INT DEFAULT 0;
DECLARE LI_TOTAL_DATA_COUNT INT DEFAULT 0;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			INSERT INTO migration_questionnaire_errorlog
						(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
				VALUES  (LI_STG_PROP_YNQ_ID,'PROP_YNQ','VALIDATION',CONCAT(LS_ERROR_MSG),UTC_TIMESTAMP(),'JHU_ADMIN');
		END;
BEGIN
	IF DATA_REFRESH_FLAG = 1 THEN
		SET SQL_SAFE_UPDATES = 0;
			DELETE FROM migration_questionnaire_errorlog WHERE SOURCE_TYPE IN ('PROP_YNQ','PROP_EXPLANATION_YNQ') AND ERROR_TYPE = 'VALIDATION';
			UPDATE stage_prop_ynq SET VALIDATION_STATUS = NULL WHERE VALIDATION_STATUS = 'ERROR' AND MIGRATED_QUESTION_ID IS NULL and MIGRATED_QUESTIONNAIRE_ID is null;
			UPDATE stage_prop_explanation_ynq SET VALIDATION_STATUS = NULL WHERE VALIDATION_STATUS = 'ERROR';
		SET SQL_SAFE_UPDATES = 1;
	END IF;
END;
BEGIN
SET SQL_SAFE_UPDATES = 0;
	DELETE FROM migration_execution_log;
	ALTER TABLE migration_execution_log AUTO_INCREMENT = 1;
	SET SQL_SAFE_UPDATES = 1;
	SELECT COUNT(1) INTO LI_TOTAL_DATA_COUNT FROM stage_prop_ynq;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header1 WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'PROP_YNQ';
	INSERT INTO migration_transtn_auditlog_header1 (BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME) VALUES (LI_BATCH_ID,'VALIDATION','PROP_YNQ',UTC_TIMESTAMP());
	INSERT INTO migration_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Started execution : PROP_YNQ ',UTC_TIMESTAMP());
END;
		BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_PROP_YNQ CURSOR FOR
		select spq.ID
				, spq.QUESTION_ID
				, spq.DESCRIPTION
				, spq.QUESTION_TYPE
				, spq.STATUS
				, spey.ID
				, spey.EXPLANATION
		from stage_prop_ynq spq
		left join stage_prop_explanation_ynq spey on spq.question_id = spey.question_id
		and spey.EXPLANATION_TYPE = 'E'
		and spq.validation_status is NULL;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN CUR_PROP_YNQ;
		PROP_YNQ_LOOP: LOOP
		FETCH CUR_PROP_YNQ INTO LI_STG_PROP_YNQ_ID
								, LS_QUESTION_ID
								, LS_DESCRIPTION
								, LS_QUESTION_TYPE
								, LS_STATUS
								, LI_STG_PROP_EXP_YNQ_ID
								, LS_EXPLANATION;
		IF DONE1 THEN
			LEAVE PROP_YNQ_LOOP;
		END IF;
					SET LI_TOTAL_PROCESSED_DATA_COUNT = LI_TOTAL_PROCESSED_DATA_COUNT + 1;
					INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
							VALUES ('VALIDATION','PROP_YNQ',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),LS_QUESTION_ID);
					SET LS_DATA_ERROR_FLAG = 'N';
					IF LS_QUESTION_ID IS NULL THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_PROP_YNQ_ID,'PROP_YNQ','VALIDATION',CONCAT('Invalid Question ID:  ', LS_QUESTION_ID),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF (trim(LS_DESCRIPTION) IS NULL or trim(LS_DESCRIPTION) = '') THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_PROP_YNQ_ID,'PROP_YNQ','VALIDATION',CONCAT('Invalid Question :  ', LS_DESCRIPTION),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF (LS_STATUS != 'A' and LS_STATUS != 'I') THEN
						INSERT INTO migration_questionnaire_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_STG_PROP_YNQ_ID,'PROP_YNQ','VALIDATION',CONCAT('Invalid Question Status:  ', LS_STATUS),UTC_TIMESTAMP(),'JHU_ADMIN');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
			SET SQL_SAFE_UPDATES = 0;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_prop_ynq SET VALIDATION_STATUS = 'VALID' WHERE ID = LI_STG_PROP_YNQ_ID;
						UPDATE stage_prop_explanation_ynq SET VALIDATION_STATUS = 'VALID' WHERE ID = LI_STG_PROP_EXP_YNQ_ID;
					ELSE
						UPDATE stage_prop_ynq SET VALIDATION_STATUS = 'ERROR' WHERE ID = LI_STG_PROP_YNQ_ID;
						UPDATE stage_prop_explanation_ynq SET VALIDATION_STATUS = 'ERROR' WHERE ID = LI_STG_PROP_EXP_YNQ_ID;
					END IF;
			SET SQL_SAFE_UPDATES = 1;
			IF LI_TOTAL_PROCESSED_DATA_COUNT < LI_TOTAL_DATA_COUNT THEN
					IF LI_TOTAL_PROCESSED_DATA_COUNT = 10000 THEN
						INSERT INTO migration_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
						VALUES (CONCAT('Validated ',LI_TOTAL_PROCESSED_DATA_COUNT,' records of Proposal YNQ Questions'),UTC_TIMESTAMP());
						SET LI_TOTAL_PROCESSED_DATA_COUNT = 0;
					END IF;
				END IF ;
				INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER)
													VALUES ('VALIDATION','PROP_YNQ',LI_BATCH_ID,'Completed execution ',UTC_TIMESTAMP(),LS_QUESTION_ID);
					set LS_DATA_ERROR_FLAG = 'N';
					set LI_STG_PROP_YNQ_ID = NULL;
					set LS_QUESTION_ID = NULL;
					set LS_DESCRIPTION = NULL;
					set LS_QUESTION_TYPE = NULL;
					set LS_STATUS = NULL;
					set LI_STG_PROP_EXP_YNQ_ID = NULL;
					set LS_EXPLANATION = NULL;
		END LOOP;
		CLOSE CUR_PROP_YNQ;
		INSERT INTO migration_transtn_auditlog_details1 (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('VALIDATION','PROP_YNQ',LI_BATCH_ID,'Exit cursor',UTC_TIMESTAMP(),NULL);
			INSERT INTO migration_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME)
					VALUES (CONCAT('Validated total records ( ', LI_TOTAL_DATA_COUNT,' ) of Proposal YNQ'),UTC_TIMESTAMP()),('Validation completed successfully',UTC_TIMESTAMP());
		END;
END
$$
DELIMITER ;
