DELIMITER $$
CREATE  PROCEDURE `MIGRATE_EPS_PROP_ROLES`(DATA_PROPOSAL_NUMBER INT,OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LI_PROPOSAL_PERSON_ROLE_ID INT;
DECLARE LI_ROLE_ID INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LS_PERSON_ID VARCHAR(15);
DECLARE LS_USER_ID VARCHAR(8);
DECLARE LS_UPDATE_USER VARCHAR(8);
DECLARE LS_UPDATE_TIMESTAMP DATETIME;
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LI_SOURCE_COUNT INT;
DECLARE LI_DESTINATION_COUNT INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_DEV_PROP_ROLES_CURSOR CURSOR FOR
	SELECT      MIGRATION_PROPOSAL_PERSON_ROLE_ID,
				PROPOSAL_NUMBER,
				USER_ID,
				ROLE_ID,
				UPDATE_TIMESTAMP,
				UPDATE_USER
	FROM stage_eps_proposal_person_roles WHERE VALIDATION_STATUS = 'VALID' AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
	GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'PERSONROLE','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN  MIGRATION_DEV_PROP_ROLES_CURSOR;
	MIGRATION_DEV_PROP_ROLES_CURSOR_LOOP            :  LOOP
	FETCH  MIGRATION_DEV_PROP_ROLES_CURSOR             INTO       	LI_RECORD_ID,
																	LS_PROPOSAL_NUMBER,
																	LS_USER_ID,
																	LI_ROLE_ID,
																	LS_UPDATE_TIMESTAMP,
																	LS_UPDATE_USER;
	IF DONE1 THEN
		LEAVE MIGRATION_DEV_PROP_ROLES_CURSOR_LOOP;
	END IF;
	SET LS_DATA_ERROR_FLAG = 'N';
	SET LI_COUNT = -1;
	SET LI_PROPOSAL_PERSON_ROLE_ID = -1;
	SELECT COUNT(*) INTO LI_COUNT FROM
	person   WHERE TRIM(UPPER(USER_NAME)) = TRIM(UPPER(LS_USER_ID));
	IF LI_COUNT = 1  THEN
		SELECT PERSON_ID INTO LS_PERSON_ID FROM person WHERE TRIM(UPPER(USER_NAME)) = TRIM(UPPER(LS_USER_ID));
	ELSE
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (LI_RECORD_ID,'PERSONROLE','MIGRATION',IFNULL(CONCAT('Invalid person :', LS_USER_ID),'Person is mandatory and cannot be NULL'),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END IF;
	IF LS_DATA_ERROR_FLAG = 'N' THEN
		SELECT IFNULL(MAX(PROPOSAL_PERSON_ROLE_ID),0) + 1 INTO LI_PROPOSAL_PERSON_ROLE_ID
		FROM eps_proposal_person_roles;
		INSERT INTO  eps_proposal_person_roles
		(
			PROPOSAL_PERSON_ROLE_ID,
			PROPOSAL_ID,
			PERSON_ID,
			ROLE_ID,
			UPDATE_TIMESTAMP,
			UPDATE_USER
		)
		VALUES
		(
			LI_PROPOSAL_PERSON_ROLE_ID,
			LS_PROPOSAL_NUMBER,
			LS_PERSON_ID,
			LI_ROLE_ID,
			LS_UPDATE_TIMESTAMP,
			LS_UPDATE_USER
		);
		UPDATE stage_eps_proposal_person_roles
		SET VALIDATION_STATUS = 'SUCCESS',
		FIBI_IDENTIFIER = LI_PROPOSAL_PERSON_ROLE_ID
		WHERE MIGRATION_PROPOSAL_PERSON_ROLE_ID = LI_RECORD_ID;
	ELSE
		UPDATE stage_eps_proposal_person_roles
		SET VALIDATION_STATUS = 'ERROR',
		FIBI_IDENTIFIER = -1
		WHERE MIGRATION_PROPOSAL_PERSON_ROLE_ID = LI_RECORD_ID;
	END IF;
	END LOOP MIGRATION_DEV_PROP_ROLES_CURSOR_LOOP;
	CLOSE MIGRATION_DEV_PROP_ROLES_CURSOR;
END;
	SELECT COUNT(*) INTO DATA_ERROR_COUNT FROM  stage_eps_proposal_person_roles WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER = -1 AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER;
	COMMIT;
END
$$
DELIMITER ;
