DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MIGRATE_IP_KEY_PERSONS_PREVAL`(DATA_PROPOSAL_NUMBER VARCHAR(8), DATA_SEQUENCE_NUMBER INT,FOR_AUDIT INT,OUT DATA_ERROR_COUNT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LS_PERSON_ID VARCHAR(9);
DECLARE LS_NON_MIT_FLAG VARCHAR(1);
DECLARE LS_ERROR_MESSAGE VARCHAR(4000);
DECLARE LI_COUNT INT;
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_CHILD_ERROR_MESSAGE VARCHAR(500);
DECLARE LS_CHILD_ERROR VARCHAR(1);
DECLARE LI_BATCH_ID INT;
BEGIN
	SELECT IFNULL(MAX(BATCH_ID),0) INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'VALIDATION' AND MODULE_NAME = 'INSTPROPKEYPERSON';
END;
BEGIN
		DECLARE LS_ERROR VARCHAR(2000);
        DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE MIGRATION_INST_PROP_PERSON_CURSOR CURSOR FOR
		SELECT  MIGRATION_PROP_KEY_PERSON_ID,
				PERSON_ID,
				NON_MIT_PERSON_FLAG
		FROM  stage_proposal_key_persons WHERE VALIDATION_STATUS IS NULL AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = DATA_SEQUENCE_NUMBER;
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR;
			INSERT INTO migration_transaction_errorlog
				(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
			VALUES  (LI_RECORD_ID,'INSTPROPKEYPERSON','VALIDATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
			SET LS_DATA_ERROR_FLAG = 'Y';
		END;
			OPEN MIGRATION_INST_PROP_PERSON_CURSOR;
			MIGRATION_INST_PROP_PERSON_CURSOR_LOOP :    LOOP
				FETCH MIGRATION_INST_PROP_PERSON_CURSOR INTO     		LI_RECORD_ID,
																		LS_PERSON_ID,
																		LS_NON_MIT_FLAG;
					IF DONE1 THEN
						LEAVE MIGRATION_INST_PROP_PERSON_CURSOR_LOOP;
					END IF;
					SET LS_DATA_ERROR_FLAG = 'N';
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'Validation start',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
					END IF;
					IF LS_NON_MIT_FLAG = 'N' THEN
						SET LI_COUNT = -1;
						SELECT COUNT(1) INTO LI_COUNT FROM
						person   WHERE PERSON_ID = LS_PERSON_ID;
						IF LI_COUNT = 0  THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'INSTPROPKEYPERSON','VALIDATION',IFNULL(CONCAT('Invalid person id :', LS_PERSON_ID),'Person Id is mandatory and cannot be NULL'),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
						END IF;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'after person check',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
						END IF;
					ELSE
						SET LI_COUNT = -1;
						SELECT COUNT(1) INTO LI_COUNT FROM
						rolodex   WHERE ROLODEX_ID = LS_PERSON_ID;
						IF LI_COUNT = 0  THEN
							INSERT INTO migration_transaction_errorlog
								(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
							VALUES  (LI_RECORD_ID,'INSTPROPKEYPERSON','VALIDATION',IFNULL(CONCAT('Invalid rolodex id :', LS_PERSON_ID),'Person Id is mandatory and cannot be NULL'),UTC_TIMESTAMP(),'quickstart');
							SET LS_DATA_ERROR_FLAG = 'Y';
						END IF;
						IF FOR_AUDIT = 1 THEN
							INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'after rolodex check',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
						END IF;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'after person/rolodex check',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
					END IF;
					SET LS_CHILD_ERROR_MESSAGE = 'CHILD TABLES : ';
					SET LS_CHILD_ERROR = 'N';
					SET LI_COUNT = -1;
					SELECT  COUNT(1) INTO LI_COUNT FROM stage_proposal_key_person_units WHERE PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = DATA_SEQUENCE_NUMBER;
					IF LI_COUNT > 0 THEN
						CALL MIGRATE_IP_KP_UNITS_PREVAL(DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER,LS_PERSON_ID,FOR_AUDIT,@prop_kp_unit_error_count);
						IF @prop_kp_unit_error_count > 0 THEN
							SET LS_CHILD_ERROR_MESSAGE = CONCAT(LS_CHILD_ERROR_MESSAGE, 'KP IP PROPOSAL UNITS, ');
							SET LS_CHILD_ERROR = 'Y';
						END IF;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'end of child data validation',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
					END IF;
					IF LS_CHILD_ERROR = 'Y' THEN
						INSERT INTO migration_transaction_errorlog
							(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
						VALUES  (LI_RECORD_ID,'INSTPROPKEYPERSON','VALIDATION',CONCAT('Error in the ',LS_CHILD_ERROR_MESSAGE, ' for the proposal number : ', DATA_PROPOSAL_NUMBER,' and the sequence number : ', DATA_SEQUENCE_NUMBER) ,UTC_TIMESTAMP(),'quickstart');
						SET LS_DATA_ERROR_FLAG = 'Y';
					END IF;
					IF LS_DATA_ERROR_FLAG = 'N' THEN
						UPDATE stage_proposal_key_persons
						SET VALIDATION_STATUS = 'VALID',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_PROP_KEY_PERSON_ID = LI_RECORD_ID;
					ELSE
						UPDATE stage_proposal_key_persons
						SET VALIDATION_STATUS = 'ERROR',
						FIBI_IDENTIFIER = NULL
						WHERE MIGRATION_PROP_KEY_PERSON_ID  = LI_RECORD_ID;
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'end of update',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
					END IF;
					IF FOR_AUDIT = 1 THEN
						INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'validation end',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
					END IF;
			END LOOP MIGRATION_INST_PROP_PERSON_CURSOR_LOOP;
			CLOSE MIGRATION_INST_PROP_PERSON_CURSOR;
			IF FOR_AUDIT = 1 THEN
				INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER,SEQUENCE_NUMBER) VALUES ('VALIDATION','INSTPROPKEYPERSON',LI_BATCH_ID,'exit cursor',UTC_TIMESTAMP(),DATA_PROPOSAL_NUMBER,DATA_SEQUENCE_NUMBER);
			END IF;
		END;
		SELECT COUNT(1) INTO DATA_ERROR_COUNT FROM stage_proposal_key_persons WHERE VALIDATION_STATUS = 'ERROR' AND FIBI_IDENTIFIER IS NULL AND PROPOSAL_NUMBER = DATA_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = DATA_SEQUENCE_NUMBER;
		COMMIT;
END
$$
DELIMITER ;
