DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `MIGRATE_EPS_IP_NUMBER_UPDATE`(DATA_REFRESH_FLAG INT,FOR_AUDIT INT)
BEGIN
DECLARE LI_RECORD_ID INT;
DECLARE LS_PROPOSAL_NUMBER VARCHAR(8);
DECLARE LI_MAX_SEQUENCE_NUMBER INT;
DECLARE LI_PD_ID INT;
DECLARE LI_COUNT INT;
DECLARE LI_BATCH_ID INT;
DECLARE LS_MIGRATION_STATUS VARCHAR(30);
DECLARE LS_DATA_ERROR_FLAG VARCHAR(1);
DECLARE LS_PD_NUMBER VARCHAR(8);
DECLARE LS_VALIDATION_STATUS VARCHAR(10);
DECLARE LS_CHILD_ERROR_MESSAGE VARCHAR(500);
DECLARE LS_CHILD_ERROR VARCHAR(1);
DECLARE LS_DELETED_DATA VARCHAR(1);
BEGIN
	SET SQL_SAFE_UPDATES = 0;
	SET FOREIGN_KEY_CHECKS = 0;
	SELECT IFNULL(MAX(BATCH_ID),0) + 1 INTO LI_BATCH_ID FROM migration_transtn_auditlog_header WHERE ACTION_TYPE = 'MIGRATION' AND MODULE_NAME = 'IPNUMBER';
	INSERT INTO migration_transtn_auditlog_header
		(BATCH_ID,ACTION_TYPE,MODULE_NAME,EXECUTION_TIME)
		VALUES 	(LI_BATCH_ID,'MIGRATION','IPNUMBER',UTC_TIMESTAMP());
	DELETE FROM migration_trans_execution_log;
	ALTER TABLE migration_trans_execution_log AUTO_INCREMENT = 1;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Start Execution',UTC_TIMESTAMP());
END;
BEGIN
	DECLARE LS_ERROR VARCHAR(2000);
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE MIGRATION_PD_PROP_CURSOR CURSOR FOR
	SELECT     DISTINCT
				INST_PROPOSAL_NUMBER
	FROM stage_proposal_admin_details WHERE VALIDATION_STATUS = 'SUCCESS' AND FIBI_IDENTIFIER <> -1
	AND DEV_PROPOSAL_NUMBER IN (SELECT PROPOSAL_ID  FROM eps_proposal WHERE IP_NUMBER IS NULL)
    ;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
	BEGIN
		GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE,
		@errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
		SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
		SELECT @full_error INTO LS_ERROR;
		INSERT INTO migration_transaction_errorlog
			(PARENT_ID,SOURCE_TYPE,ERROR_TYPE,ERROR_MESSAGE,UPDATE_TIMESTAMP,UPDATE_USER)
		VALUES  (-1,'IPNUMBER','MIGRATION',CONCAT(LS_ERROR),UTC_TIMESTAMP(),'quickstart');
		SET LS_DATA_ERROR_FLAG = 'Y';
	END;
	OPEN MIGRATION_PD_PROP_CURSOR;
	MIGRATION_PD_PROP_CURSOR_LOOP : 	  LOOP
	FETCH  MIGRATION_PD_PROP_CURSOR       INTO    		LS_PROPOSAL_NUMBER;
		IF DONE1 THEN
			LEAVE MIGRATION_PD_PROP_CURSOR_LOOP;
		END IF;
		SET LS_DATA_ERROR_FLAG = 'N';
		SET LI_COUNT = -1;
		SET LI_MAX_SEQUENCE_NUMBER = -1;
		SET LS_PD_NUMBER = NULL;
		SET LI_PD_ID = -1;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','IPNUMBER',LI_BATCH_ID,'Migration start',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
		SELECT IFNULL(MAX(INST_PROP_SEQUENCE_NUMBER),0) INTO LI_MAX_SEQUENCE_NUMBER FROM stage_proposal_admin_details WHERE INST_PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER;
		IF LI_MAX_SEQUENCE_NUMBER > 0 THEN
			SELECT DEV_PROPOSAL_NUMBER INTO LS_PD_NUMBER FROM stage_proposal_admin_details WHERE INST_PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND INST_PROP_SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER;
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','IPNUMBER',LI_BATCH_ID,IFNULL(CONCAT('After the max sequence number',LI_MAX_SEQUENCE_NUMBER),'Max sequence numver is null'),UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
		SET LI_COUNT = 0;
		SELECT COUNT(1) INTO LI_COUNT FROM proposal WHERE PROPOSAL_NUMBER = LS_PROPOSAL_NUMBER AND SEQUENCE_NUMBER = LI_MAX_SEQUENCE_NUMBER;
		IF LI_COUNT = 0 THEN
			SET LS_DATA_ERROR_FLAG = 'Y';
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','IPNUMBER',LI_BATCH_ID,'After the proposal check',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
		CALL JHU_FETCH_DEV_PROPOSAL_ID(LS_PD_NUMBER,@proposal_id);
		IF @proposal_id = -1 THEN
			SET LS_DATA_ERROR_FLAG = 'Y';
		ELSE
			SET LI_PD_ID = @proposal_id;
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','IPNUMBER',LI_BATCH_ID,IFNULL(CONCAT('After the pd number check',LI_PD_ID),'PD numver is null'),UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
		IF LS_DATA_ERROR_FLAG = 'N' THEN
			UPDATE eps_proposal SET IP_NUMBER = LS_PROPOSAL_NUMBER
			WHERE PROPOSAL_ID = LI_PD_ID;
		END IF;
		IF FOR_AUDIT = 1 THEN
			INSERT INTO migration_transtn_auditlog_details (ACTION_TYPE,MODULE_NAME,BATCH_ID,MESSAGE,EXECUTION_TIME,PARENT_NUMBER) VALUES ('MIGRATION','IPNUMBER',LI_BATCH_ID,'Migration end',UTC_TIMESTAMP(),LS_PROPOSAL_NUMBER);
		END IF;
	END LOOP MIGRATION_PD_PROP_CURSOR_LOOP;
	CLOSE MIGRATION_PD_PROP_CURSOR;
END;
	INSERT INTO migration_trans_execution_log (EXECUTION_MESSAGE,EXECUTION_TIME) VALUES ('Completed successfully',UTC_TIMESTAMP());
	SET SQL_SAFE_UPDATES = 1;
	SET FOREIGN_KEY_CHECKS = 1;
	COMMIT;
END
$$
DELIMITER ;
