DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MNPR_ACTIVE_AWARD_ACTIONS`(
    AV_CURRENT_AWARD_ID INT,
    AV_AWARD_NUMBER VARCHAR(20),
    AV_ACCOUNT_NUMBER VARCHAR(25),
    AV_DOCUMENT_TYPE VARCHAR(3),
    AV_CURRENT_SEQ_NUMBER INT,
    AV_AWARD_VARIATION_TYPE_CODE VARCHAR(3)
    )
BEGIN
    DECLARE LI_BUDGET_MANPOWER_SECTION_COUNT INT;
    DECLARE LI_MANPOWER_STAFF_SECTION_COUNT INT;
    DECLARE LI_ACTIVE_AWARD_ID INT;
    SET LI_BUDGET_MANPOWER_SECTION_COUNT = 0;
    SET LI_MANPOWER_STAFF_SECTION_COUNT = 0;
    SET LI_ACTIVE_AWARD_ID = 0;
    SELECT AWARD_ID INTO LI_ACTIVE_AWARD_ID FROM AWARD WHERE AWARD_NUMBER = AV_AWARD_NUMBER AND SEQUENCE_NUMBER = 0;
    SELECT COUNT(*) INTO LI_BUDGET_MANPOWER_SECTION_COUNT from VARIATION_SECTION_MAPPING
    WHERE TYPE_CODE = AV_AWARD_VARIATION_TYPE_CODE AND SECTION_CODE IN (102);
    IF LI_BUDGET_MANPOWER_SECTION_COUNT > 0 OR AV_DOCUMENT_TYPE = 1 THEN
        INSERT INTO AWARD_MANPOWER (AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, MANPOWER_TYPE_CODE, BUDGET_REFERENCE_NUMBER,
        BUDGET_REFERENCE_TYPE_CODE, BUDGET_VERSION_NUMBER, ACTUAL_HEADCOUNT, CREATE_USER, CREATE_TIMESTAMP,
        UPDATE_USER, UPDATE_TIMESTAMP, MODULE_CODE, SUB_MODULE_CODE)
        SELECT AV_CURRENT_AWARD_ID, AV_AWARD_NUMBER, AV_CURRENT_SEQ_NUMBER,
        IF (BUDGET_CATEGORY_CODE = 'EOM', 1, 2),
        INTERNAL_ORDER_CODE, 1, VERSION_NUMBER, QUANTITY,
        UPDATE_USER, NOW(), UPDATE_USER, NOW(), 1, 4
        FROM AWARD_BUDGET_DETAIL WHERE BUDGET_HEADER_ID IN
        (SELECT BUDGET_HEADER_ID FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = AV_CURRENT_AWARD_ID  AND VERSION_NUMBER IN (SELECT MAX(VERSION_NUMBER) from award_budget_header where AWARD_ID = AV_CURRENT_AWARD_ID))
        AND BUDGET_CATEGORY_CODE IN ('EOM', 'RSS')
        AND INTERNAL_ORDER_CODE NOT IN (SELECT BUDGET_REFERENCE_NUMBER FROM AWARD_MANPOWER WHERE AWARD_ID = AV_CURRENT_AWARD_ID AND BUDGET_REFERENCE_NUMBER IS NOT NULL);
        INSERT INTO AWARD_MANPOWER (AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, MANPOWER_TYPE_CODE, BUDGET_REFERENCE_NUMBER,
        BUDGET_REFERENCE_TYPE_CODE, BUDGET_VERSION_NUMBER, ACTUAL_HEADCOUNT, CREATE_USER, CREATE_TIMESTAMP,
        UPDATE_USER, UPDATE_TIMESTAMP, MODULE_CODE, SUB_MODULE_CODE)
        SELECT LI_ACTIVE_AWARD_ID, AWARD_NUMBER, 0, MANPOWER_TYPE_CODE, BUDGET_REFERENCE_NUMBER,
        BUDGET_REFERENCE_TYPE_CODE, BUDGET_VERSION_NUMBER, ACTUAL_HEADCOUNT, CREATE_USER, CREATE_TIMESTAMP,
        UPDATE_USER, UPDATE_TIMESTAMP, MODULE_CODE, SUB_MODULE_CODE
        FROM AWARD_MANPOWER WHERE AWARD_ID = AV_CURRENT_AWARD_ID AND BUDGET_REFERENCE_NUMBER NOT IN
        (SELECT BUDGET_REFERENCE_NUMBER FROM AWARD_MANPOWER WHERE AWARD_ID = LI_ACTIVE_AWARD_ID AND BUDGET_REFERENCE_NUMBER IS NOT NULL);
    END IF;
    SELECT COUNT(*) INTO LI_MANPOWER_STAFF_SECTION_COUNT from VARIATION_SECTION_MAPPING
    WHERE TYPE_CODE = AV_AWARD_VARIATION_TYPE_CODE AND SECTION_CODE IN (131);
    IF LI_MANPOWER_STAFF_SECTION_COUNT > 0 OR AV_DOCUMENT_TYPE = 1 THEN
        DELETE FROM WORKDAY_RESOURCE_LOG WHERE AWARD_ID = LI_ACTIVE_AWARD_ID;
        INSERT INTO WORKDAY_RESOURCE_LOG (AWARD_ID, AWARD_NUMBER, SEQUENCE_NUMBER, WBS_NUMBER, POSITION_STATUS_CODE, COST_ALLOCATION, CHARGE_START_DATE, CHARGE_END_DATE,
        BASE_SALARY_USED, COMMITTED_COST, MULTIPLIER_USED, PERSON_ID, POSITION_ID, ADJUSTED_COMMITTED_COST, JOB_PROFILE_TYPE_CODE,
        WORKDAY_REFERENCE_ID, ACTION_TYPE, UPDATE_USER, UPDATE_TIMESTAMP)
        SELECT LI_ACTIVE_AWARD_ID as AWARD_ID, AV_AWARD_NUMBER as AWARD_NUMBER, 0 as SEQUENCE_NUMBER, WBS_NUMBER, POSITION_STATUS_CODE, COST_ALLOCATION,
        CHARGE_START_DATE, CHARGE_END_DATE, BASE_SALARY_USED, COMMITTED_COST, MULTIPLIER_USED, PERSON_ID, POSITION_ID,
        ADJUSTED_COMMITTED_COST, JOB_PROFILE_TYPE_CODE, WORKDAY_REFERENCE_ID, CONCAT('ACTIVE_AWARD-', AV_AWARD_NUMBER) as ACTION_TYPE, UPDATE_USER, NOW() as UPDATE_TIMESTAMP
        FROM MANPOWER_WORKDAY_RESOURCE WHERE SUBSTRING_INDEX(WBS_NUMBER,'EOM',1) = AV_ACCOUNT_NUMBER AND ADJUSTED_COMMITTED_COST IS NOT NULL;
    END IF;
    END
$$
DELIMITER ;
