DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `UPDATE_QUEST_ANSWER_USERLOOKUP_ALL`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE LI_QUESTIONNAIRE_ANSWER_ID,LI_QUESTIONNAIRE_ANS_HEADER_ID,LI_QUESTION_ID,LS_NEW_ANSWER_NUMBER,LI_CNT,LI_ANS_CNT INT;
DECLARE LS_ANSWER, LS_NEW_ANSWER,LS_LOOKUP VARCHAR(150);
DECLARE C1 CURSOR FOR
select a.QUESTIONNAIRE_ANSWER_ID,a.QUESTIONNAIRE_ANS_HEADER_ID,a.QUESTION_ID,a.ANSWER,Replace(t1.LOOKUP_TYPE,'ARG_VALUE_LOOKUP#','')
from quest_answer a inner join (
select * from quest_question where questionnaire_id in (61) and QUESTION_ID=3569 and  LOOKUP_TYPE in ('ARG_VALUE_LOOKUP#Sci_Code_Strategic_Initiatives','ARG_VALUE_LOOKUP#Sci_Code_Med_Hlh_Related','ARG_VALUE_LOOKUP#CATALYST_DISCOVERY','ARG_VALUE_LOOKUP#Sci_Code_Funding_Proposals','ARG_VALUE_LOOKUP#Sci_Code_Gen_Proposal_Purposes') ) t1 on t1.question_id=a.question_id
where length(a.ANSWER_LOOKUP_CODE) is null /*
and QUESTIONNAIRE_ANS_HEADER_ID  in ( '232927')*/ ;
update  quest_answer a inner join (
select * from quest_question where questionnaire_id in (61) and QUESTION_ID=3569  and  LOOKUP_TYPE in ('ARG_VALUE_LOOKUP#Sci_Code_Funding_Proposals','ARG_VALUE_LOOKUP#Sci_Code_Gen_Proposal_Purposes','ARG_VALUE_LOOKUP#Sci_Code_Strategic_Initiatives','ARG_VALUE_LOOKUP#Sci_Code_Med_Hlh_Related','ARG_VALUE_LOOKUP#CATALYST_DISCOVERY') ) t1 on t1.question_id=a.question_id
set ANSWER_NUMBER=null
where length(a.ANSWER_LOOKUP_CODE) is null/*
and QUESTIONNAIRE_ANS_HEADER_ID  in ( '232927')*/ ;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
	FETCH C1 INTO LI_QUESTIONNAIRE_ANSWER_ID,LI_QUESTIONNAIRE_ANS_HEADER_ID,LI_QUESTION_ID,LS_ANSWER,LS_LOOKUP;
	IF DONE THEN
		LEAVE LOOP1;
	END IF;
	SELECT COUNT(1) INTO LI_CNT FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID=LI_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID=LI_QUESTION_ID;
	IF LI_CNT > 1 THEN
		SELECT COUNT(1) INTO LI_ANS_CNT FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID=LI_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID=LI_QUESTION_ID AND ANSWER_NUMBER=0;
	    IF LI_ANS_CNT  = 0 THEN
            SELECT DESCRIPTION  INTO LS_NEW_ANSWER FROM arg_value_lookup WHERE ARGUMENT_NAME=LS_LOOKUP AND ARGUMENT_VALUE=LS_ANSWER;
			UPDATE QUEST_ANSWER
            SET ANSWER_NUMBER=0,
            ANSWER=LS_NEW_ANSWER,
            ANSWER_LOOKUP_CODE=LS_ANSWER
            WHERE QUESTIONNAIRE_ANSWER_ID=LI_QUESTIONNAIRE_ANSWER_ID;
		ELSE
			SELECT IFNULL(MAX(ANSWER_NUMBER),0)+1 INTO LS_NEW_ANSWER_NUMBER FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID=LI_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID=LI_QUESTION_ID;
			SELECT DESCRIPTION  INTO LS_NEW_ANSWER FROM arg_value_lookup WHERE ARGUMENT_NAME=LS_LOOKUP AND ARGUMENT_VALUE=LS_ANSWER;
			UPDATE QUEST_ANSWER
			SET ANSWER_NUMBER=LS_NEW_ANSWER_NUMBER,
			ANSWER=LS_NEW_ANSWER,
			ANSWER_LOOKUP_CODE=LS_ANSWER
			WHERE QUESTIONNAIRE_ANSWER_ID=LI_QUESTIONNAIRE_ANSWER_ID;
        END IF;
    ELSE
		SELECT DESCRIPTION  INTO LS_NEW_ANSWER FROM arg_value_lookup WHERE ARGUMENT_NAME=LS_LOOKUP AND ARGUMENT_VALUE=LS_ANSWER;
		UPDATE QUEST_ANSWER
		SET ANSWER_NUMBER=0,
		ANSWER=LS_NEW_ANSWER,
		ANSWER_LOOKUP_CODE=LS_ANSWER
		WHERE QUESTIONNAIRE_ANSWER_ID=LI_QUESTIONNAIRE_ANSWER_ID;
    END IF;
END;
END LOOP;
CLOSE C1;
END
$$
DELIMITER ;
