DELIMITER $$
CREATE DEFINER=`jhufibi`@`%` PROCEDURE `UPDATE_QUEST_ANSWER_USERLOOKUP`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE LI_QUESTIONNAIRE_ANSWER_ID,LI_QUESTIONNAIRE_ANS_HEADER_ID,LI_QUESTION_ID,LS_NEW_ANSWER_NUMBER,LI_CNT,LI_ANS_CNT INT;
DECLARE LS_ANSWER, LS_NEW_ANSWER VARCHAR(100);
DECLARE C1 CURSOR FOR
select QUESTIONNAIRE_ANSWER_ID,QUESTIONNAIRE_ANS_HEADER_ID,QUESTION_ID,ANSWER from quest_answer where question_id in (
select question_id from quest_question where   LOOKUP_TYPE='ARG_VALUE_LOOKUP#activity_in_country' and questionnaire_id in (select MIGRATED_QUESTIONNAIRE_ID from stage_questionnaire) )
and length(ANSWER)= 1;
update  quest_answer
set ANSWER_NUMBER=null
where question_id in (
select question_id from quest_question where  LOOKUP_TYPE='ARG_VALUE_LOOKUP#activity_in_country' and questionnaire_id in (select MIGRATED_QUESTIONNAIRE_ID from stage_questionnaire))
and length(ANSWER)= 1;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
	FETCH C1 INTO LI_QUESTIONNAIRE_ANSWER_ID,LI_QUESTIONNAIRE_ANS_HEADER_ID,LI_QUESTION_ID,LS_ANSWER;
	IF DONE THEN
		LEAVE LOOP1;
	END IF;
	SELECT COUNT(1) INTO LI_CNT FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID=LI_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID=LI_QUESTION_ID;
	IF LI_CNT > 1 THEN
		SELECT COUNT(1) INTO LI_ANS_CNT FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID=LI_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID=LI_QUESTION_ID AND ANSWER_NUMBER=0;
	    IF LI_ANS_CNT  = 0 THEN
            SELECT DESCRIPTION  INTO LS_NEW_ANSWER FROM arg_value_lookup WHERE ARGUMENT_NAME='activity_in_country' AND ARGUMENT_VALUE=LS_ANSWER;
			UPDATE QUEST_ANSWER
            SET ANSWER_NUMBER=0,
            ANSWER=LS_NEW_ANSWER,
            ANSWER_LOOKUP_CODE=LS_ANSWER
            WHERE QUESTIONNAIRE_ANSWER_ID=LI_QUESTIONNAIRE_ANSWER_ID;
		ELSE
			SELECT IFNULL(MAX(ANSWER_NUMBER),0)+1 INTO LS_NEW_ANSWER_NUMBER FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID=LI_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID=LI_QUESTION_ID;
			SELECT DESCRIPTION  INTO LS_NEW_ANSWER FROM arg_value_lookup WHERE ARGUMENT_NAME='activity_in_country' AND ARGUMENT_VALUE=LS_ANSWER;
			UPDATE QUEST_ANSWER
			SET ANSWER_NUMBER=LS_NEW_ANSWER_NUMBER,
			ANSWER=LS_NEW_ANSWER,
			ANSWER_LOOKUP_CODE=LS_ANSWER
			WHERE QUESTIONNAIRE_ANSWER_ID=LI_QUESTIONNAIRE_ANSWER_ID;
        END IF;
    ELSE
		SELECT DESCRIPTION  INTO LS_NEW_ANSWER FROM arg_value_lookup WHERE ARGUMENT_NAME='activity_in_country' AND ARGUMENT_VALUE=LS_ANSWER;
		UPDATE QUEST_ANSWER
		SET ANSWER_NUMBER=0,
		ANSWER=LS_NEW_ANSWER,
		ANSWER_LOOKUP_CODE=LS_ANSWER
		WHERE QUESTIONNAIRE_ANSWER_ID=LI_QUESTIONNAIRE_ANSWER_ID;
    END IF;
END;
END LOOP;
CLOSE C1;
END
$$
DELIMITER ;
