-- `FN_CHK_GRANT_EVALPANEL_EXISTS`; 

CREATE FUNCTION `FN_CHK_GRANT_EVALPANEL_EXISTS`(
AV_GRANT_HEADER_ID VARCHAR(12)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LS_COUNT  INT;
SELECT COUNT(*) INTO LS_COUNT
FROM GRANT_CALL_HEADER
WHERE GRANT_HEADER_ID = AV_GRANT_HEADER_ID
AND GRANT_TYPE_CODE IN(4,7,8,9);
IF LS_COUNT = 0 THEN
RETURN 'TRUE';
END IF;
SELECT COUNT(*) INTO LS_COUNT
FROM GRANT_CALL_EVALUATION_PANEL
where GRANT_HEADER_ID = AV_GRANT_HEADER_ID
and IS_MAIN_PANEL<>'Y';
IF LS_COUNT = 0 THEN
RETURN 'FALSE';
ELSE
RETURN 'TRUE';
END IF;
END
