-- `FN_CHK_GRANT_MAIN_PANEL_EXISTS`; 

CREATE FUNCTION `FN_CHK_GRANT_MAIN_PANEL_EXISTS`(
AV_GRANT_HEADER_ID VARCHAR(12)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG  INT;
	SELECT COUNT(1) INTO LI_FLAG 
	FROM GRANT_CALL_HEADER 
	WHERE GRANT_HEADER_ID = AV_GRANT_HEADER_ID
	AND GRANT_TYPE_CODE IN(4,8);
	IF LI_FLAG > 0 THEN
		SELECT COUNT(1) INTO LI_FLAG FROM GRANT_CALL_EVALUATION_PANEL
		WHERE GRANT_HEADER_ID = AV_GRANT_HEADER_ID
		AND IS_MAIN_PANEL = 'Y';
		IF LI_FLAG > 0 THEN
			RETURN 'TRUE';
		ELSE
			RETURN 'FALSE';
		END IF;
	ELSE
		RETURN 'TRUE';
	END IF;
END
