-- `FN_CHK_GRANTCALL_ELIGIBILITY`; 

CREATE FUNCTION `FN_CHK_GRANTCALL_ELIGIBILITY`( 
AV_GRANT_HEADER_ID    INT
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT;
SELECT COUNT(1) INTO LI_COUNT 
FROM GRANT_CALL_ELIGIBILITY T1
WHERE T1.GRANT_HEADER_ID = AV_GRANT_HEADER_ID;
IF LI_COUNT > 0 THEN
	RETURN 'TRUE';
END IF;
	RETURN 'FALSE';
END
