-- `COPY_MERGE_EPS_PROPOSAL_QUESTIONNAIRE_DATA`; 

CREATE PROCEDURE `COPY_MERGE_EPS_PROPOSAL_QUESTIONNAIRE_DATA`(
IN AV_ACTIVE_PROPOSAL_ID  INT,
IN AV_ARCHIVE_PROPOSAL_ID  INT,
IN AV_TYPE VARCHAR(1) 
)
BEGIN
    DECLARE LS_COLUMN_1 				varchar(200) ;
	DECLARE LS_COLUMN_2 				varchar(200) ;
	DECLARE LS_COLUMN_3 				varchar(200) ;
	DECLARE LS_COLUMN_4 				varchar(200) ;
	DECLARE LS_COLUMN_5 				varchar(200) ;
	DECLARE LS_COLUMN_6 				varchar(200) ;
	DECLARE LS_COLUMN_7 				varchar(200) ;
	DECLARE LS_COLUMN_8 				varchar(200) ;
	DECLARE LS_COLUMN_9 				varchar(200) ;
	DECLARE LS_COLUMN_10 				varchar(200) ;
	DECLARE LS_MODULE_ITEM_KEY				varchar(20);					  
	DECLARE LS_QUESTIONNAIRE_ANSWER_ID 		bigint(12);
	DECLARE ls_ATTACHMENT 			   		longblob;
	DECLARE LS_FILE_NAME 			   		varchar(150);
	DECLARE LS_CONTENT_TYPE 		   		varchar(100);
    DECLARE LS_QST_ANS_HEADER_ID 	   		BIGINT(10);
    DECLARE LI_QUEST_ANSWER_ID 		   		BIGINT(10);
    DECLARE LI_QUEST_ATT_ID    		   		BIGINT(10);
    DECLARE LI_QUEST_TABLE_ANS_ID     	 	BIGINT(10);
    DECLARE LI_QUESTIONNAIRE_ID 			bigint(12);
	DECLARE LI_MODULE_ITEM_CODE 			smallint(3);
	DECLARE LI_MODULE_SUB_ITEM_CODE 		smallint(3);
	DECLARE LS_QUESTIONNAIRE_COMPLETED_FLAG varchar(1);
	DECLARE LI_QUESTIONNAIRE_ANS_HEADER_ID 	bigint(12);
	DECLARE LI_QUESTION_ID 					bigint(12);
	DECLARE LI_OPTION_NUMBER 				smallint(3);
	DECLARE LI_ANSWER_NUMBER 				smallint(3);
	DECLARE LS_ANSWER 						varchar(4000);
	DECLARE LS_ANSWER_LOOKUP_CODE 			varchar(100);
	DECLARE LS_EXPLANATION 					varchar(4000);
	DECLARE LD_UPDATE_TIMESTAMP 			datetime;
	DECLARE LS_UPDATE_USER 					varchar(60);
	DECLARE LI_QUESTIONNAIRE_ANSWER_ID 		bigint(12);
	DECLARE LI_ORDER_NUMBER 				smallint(3) ;
 
 
	DECLARE LS_ERROR_MSG	              VARCHAR(2000);
	DECLARE LS_ERROR_FLAG	              VARCHAR(1) DEFAULT 'N';
    DECLARE NOT_FOUND                 INT;
    DECLARE LS_PROC_LOC                VARCHAR(200);
    DECLARE li_seq_proposal_id          INT;
    DECLARE LS_MODULE_SUB_ITEM_KEY  VARCHAR(20);
	
	DECLARE SEL_QST_ANS_HEADER CURSOR FOR SELECT QUESTIONNAIRE_ID,MODULE_ITEM_CODE,MODULE_SUB_ITEM_CODE,MODULE_SUB_ITEM_KEY,QUESTIONNAIRE_COMPLETED_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,QUESTIONNAIRE_ANS_HEADER_ID FROM  QUEST_ANSWER_HEADER
                                        WHERE MODULE_ITEM_CODE = 3
										AND MODULE_SUB_ITEM_CODE IN (3,0) 
                                        AND MODULE_ITEM_KEY = li_seq_proposal_id;
										
	DECLARE QUEST_ANSWER CURSOR FOR 
	SELECT QUESTION_ID,OPTION_NUMBER,ANSWER_NUMBER,ANSWER,ANSWER_LOOKUP_CODE,EXPLANATION,UPDATE_TIMESTAMP,UPDATE_USER ,QUESTIONNAIRE_ANSWER_ID 	FROM QUEST_ANSWER
	WHERE QUESTIONNAIRE_ANS_HEADER_ID = LI_QUESTIONNAIRE_ANS_HEADER_ID;
	
    DECLARE QUEST_ATT CURSOR FOR 
	SELECT  QUESTIONNAIRE_ANSWER_ID,ATTACHMENT,FILE_NAME,CONTENT_TYPE,UPDATE_TIMESTAMP,UPDATE_USER 
	FROM QUEST_ANSWER_ATTACHMENT
	WHERE QUESTIONNAIRE_ANSWER_ID = LI_QUESTIONNAIRE_ANSWER_ID;
	
	DECLARE QUEST_TABLE_ANS CURSOR FOR 
	SELECT QUESTION_ID,ORDER_NUMBER,COLUMN_1,COLUMN_2,COLUMN_3,COLUMN_4,COLUMN_5,COLUMN_6,COLUMN_7,COLUMN_8,COLUMN_9,COLUMN_10,UPDATE_TIMESTAMP,UPDATE_USER 
	FROM QUEST_TABLE_ANSWER
	WHERE QUESTIONNAIRE_ANS_HEADER_ID = LI_QUESTIONNAIRE_ANS_HEADER_ID;	
 
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;					 
					SET @full_error = CONCAT(@msg,'/',LS_PROC_LOC);	
					SET LS_ERROR_MSG = @full_error;
                    	RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
		 
                END;
				
     DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;	
 
	 SET LS_ERROR_FLAG = 'N';
     
 	 IF AV_TYPE = 'M' THEN 
	SET SQL_SAFE_UPDATES = 0;
    
 SET LS_PROC_LOC = 'DELETE_QUESTIONNAIRE';
DELETE FROM QUEST_TABLE_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM QUEST_ANSWER_HEADER T4 WHERE T4.MODULE_ITEM_KEY = AV_ACTIVE_PROPOSAL_ID and T4.MODULE_SUB_ITEM_CODE IN (3,0)  AND T4.MODULE_ITEM_CODE = 3);
DELETE FROM QUEST_ANSWER_ATTACHMENT T2 WHERE T2.QUESTIONNAIRE_ANSWER_ID  IN (SELECT QUESTIONNAIRE_ANSWER_ID FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM QUEST_ANSWER_HEADER T4 WHERE T4.MODULE_ITEM_KEY = AV_ACTIVE_PROPOSAL_ID and T4.MODULE_SUB_ITEM_CODE IN (3,0)  AND T4.MODULE_ITEM_CODE = 3) );
DELETE FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (SELECT QUESTIONNAIRE_ANS_HEADER_ID FROM QUEST_ANSWER_HEADER T4 WHERE T4.MODULE_ITEM_KEY = AV_ACTIVE_PROPOSAL_ID and T4.MODULE_SUB_ITEM_CODE IN (3,0)  AND T4.MODULE_ITEM_CODE = 3);
DELETE FROM QUEST_ANSWER_HEADER T4 WHERE T4.MODULE_ITEM_KEY = AV_ACTIVE_PROPOSAL_ID and T4.MODULE_SUB_ITEM_CODE IN (3,0)  AND T4.MODULE_ITEM_CODE = 3;
SET SQL_SAFE_UPDATES = 1;
     SET li_seq_proposal_id = AV_ARCHIVE_PROPOSAL_ID;
	 
	 
	 ELSEIF AV_TYPE = 'C' THEN 
	 
	 SET li_seq_proposal_id = AV_ACTIVE_PROPOSAL_ID;
	 
	 END IF;
	
 SET LS_PROC_LOC = 'SEL_QST_ANS_HEADER';
			
            OPEN SEL_QST_ANS_HEADER;
            SEL_QST_ANS_HEADER:LOOP
			SET NOT_FOUND  = 0;
            
            FETCH SEL_QST_ANS_HEADER INTO LI_QUESTIONNAIRE_ID,LI_MODULE_ITEM_CODE,LI_MODULE_SUB_ITEM_CODE,LS_MODULE_SUB_ITEM_KEY,LS_QUESTIONNAIRE_COMPLETED_FLAG,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER,LI_QUESTIONNAIRE_ANS_HEADER_ID;
           
			 
            IF NOT_FOUND=1 THEN
            LEAVE SEL_QST_ANS_HEADER;
            END IF;
            
               
                INSERT INTO QUEST_ANSWER_HEADER
                ( QUESTIONNAIRE_ID, MODULE_ITEM_CODE, MODULE_SUB_ITEM_CODE, MODULE_ITEM_KEY, MODULE_SUB_ITEM_KEY, QUESTIONNAIRE_COMPLETED_FLAG, UPDATE_TIMESTAMP, UPDATE_USER)
                VALUES
                (LI_QUESTIONNAIRE_ID, LI_MODULE_ITEM_CODE, LI_MODULE_SUB_ITEM_CODE, CASE WHEN AV_TYPE = 'M' THEN AV_ACTIVE_PROPOSAL_ID WHEN AV_TYPE = 'C' THEN AV_ARCHIVE_PROPOSAL_ID END, LS_MODULE_SUB_ITEM_KEY, LS_QUESTIONNAIRE_COMPLETED_FLAG,LD_UPDATE_TIMESTAMP, LS_UPDATE_USER);
				
				SET LS_QST_ANS_HEADER_ID=last_insert_id();
				
				
				
					 SET LS_PROC_LOC = 'QUEST_ANSWER';
			
            OPEN QUEST_ANSWER;
            QUEST_ANSWER:LOOP
			SET NOT_FOUND  = 0;
            FETCH QUEST_ANSWER INTO LI_QUESTION_ID,LI_OPTION_NUMBER,LI_ANSWER_NUMBER,LS_ANSWER,LS_ANSWER_LOOKUP_CODE,LS_EXPLANATION,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER,LI_QUESTIONNAIRE_ANSWER_ID;
 
			
            IF NOT_FOUND=1 THEN
            LEAVE QUEST_ANSWER;
            END IF;
            
               
                 INSERT INTO QUEST_ANSWER( QUESTIONNAIRE_ANS_HEADER_ID, QUESTION_ID, OPTION_NUMBER, ANSWER_NUMBER, ANSWER, ANSWER_LOOKUP_CODE, EXPLANATION, UPDATE_TIMESTAMP, UPDATE_USER)
                  VALUES(LS_QST_ANS_HEADER_ID,LI_QUESTION_ID, LI_OPTION_NUMBER,LI_ANSWER_NUMBER,LS_ANSWER,LS_ANSWER_LOOKUP_CODE,LS_EXPLANATION,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER);                  
                  SET LI_QUEST_ANSWER_ID=last_insert_id();
                 SET SQL_SAFE_UPDATES = 0;
                  UPDATE QUEST_COLUMN_NEXTVALUE SET QUESTIONNAIRE_ANSWER_ID = LI_QUEST_ANSWER_ID;
				
				  
						 SET LS_PROC_LOC = 'QUEST_ATT';
			
            OPEN QUEST_ATT;
            QUEST_ATT:LOOP
			SET NOT_FOUND  = 0;
            FETCH QUEST_ATT INTO LS_QUESTIONNAIRE_ANSWER_ID,LS_ATTACHMENT,LS_FILE_NAME,LS_CONTENT_TYPE,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER;
 
             IF NOT_FOUND=1 THEN
            LEAVE QUEST_ATT;
            END IF;
            
               
                 INSERT INTO QUEST_ANSWER_ATTACHMENT
                 ( QUESTIONNAIRE_ANSWER_ID, ATTACHMENT, FILE_NAME, CONTENT_TYPE, UPDATE_TIMESTAMP, UPDATE_USER)
                 VALUES(LI_QUEST_ANSWER_ID,LS_ATTACHMENT,LS_FILE_NAME,LS_CONTENT_TYPE,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER);
                 SET LI_QUEST_ATT_ID=last_insert_id();
                SET SQL_SAFE_UPDATES = 0;
                 UPDATE QUEST_COLUMN_NEXTVALUE SET QUESTIONNAIRE_ANSWER_ATT_ID = LI_QUEST_ATT_ID;
                
              
		END LOOP QUEST_ATT;
		CLOSE QUEST_ATT;
                
              
		END LOOP QUEST_ANSWER;
		CLOSE QUEST_ANSWER;
		
		
								 SET LS_PROC_LOC = 'QUEST_TABLE_ANS';
			
            OPEN QUEST_TABLE_ANS;
            QUEST_TABLE_ANS:LOOP
			SET NOT_FOUND  = 0;
            FETCH QUEST_TABLE_ANS INTO LI_QUESTION_ID,LI_ORDER_NUMBER, LS_COLUMN_1,LS_COLUMN_2,LS_COLUMN_3,LS_COLUMN_4,LS_COLUMN_5,LS_COLUMN_6,LS_COLUMN_7,LS_COLUMN_8,LS_COLUMN_9,LS_COLUMN_10,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER ;
 
			
            IF NOT_FOUND=1 THEN
            LEAVE QUEST_TABLE_ANS;
            END IF;
            
                INSERT INTO QUEST_TABLE_ANSWER
                  (QUESTIONNAIRE_ANS_HEADER_ID,QUESTION_ID,ORDER_NUMBER,COLUMN_1,COLUMN_2,COLUMN_3,COLUMN_4,COLUMN_5,COLUMN_6,COLUMN_7,COLUMN_8,COLUMN_9,COLUMN_10,UPDATE_TIMESTAMP,UPDATE_USER)
                  VALUES(LS_QST_ANS_HEADER_ID,LI_QUESTION_ID,LI_ORDER_NUMBER, LS_COLUMN_1,LS_COLUMN_2,LS_COLUMN_3,LS_COLUMN_4,LS_COLUMN_5,LS_COLUMN_6,LS_COLUMN_7,LS_COLUMN_8,LS_COLUMN_9,LS_COLUMN_10,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER);
                  SET LI_QUEST_TABLE_ANS_ID=last_insert_id();
                  
                  SET SQL_SAFE_UPDATES = 0;
                  UPDATE QUEST_COLUMN_NEXTVALUE SET QUESTIONNAIRE_ANSWER_TABLE_ID = LI_QUEST_TABLE_ANS_ID;
                
              
		END LOOP QUEST_TABLE_ANS;
		CLOSE QUEST_TABLE_ANS;
               
                                  SET SQL_SAFE_UPDATES = 0;
          
               UPDATE QUEST_COLUMN_NEXTVALUE SET QUESTIONNAIRE_ANS_HEADER_ID = LS_QST_ANS_HEADER_ID; 
	      
    
		END LOOP SEL_QST_ANS_HEADER;
		CLOSE SEL_QST_ANS_HEADER;  
        SET SQL_SAFE_UPDATES = 1;
END
