-- `COPY_MERGE_EPS_PROPOSAL_CP_REPORT_DATA`; 

CREATE PROCEDURE `COPY_MERGE_EPS_PROPOSAL_CP_REPORT_DATA`(
IN AV_ACTIVE_PROPOSAL_ID  INT,
IN AV_ARCHIVE_PROPOSAL_ID  INT,
IN AV_TYPE VARCHAR(1) 
)
BEGIN
   DECLARE LI_NEW_CP_REPORT_HEADER_ID INT;
    DECLARE LS_PERSON_ID	varchar(40);
	DECLARE LS_NON_EMPLOYEE_FLAG	varchar(1);
	DECLARE LI_VERSION_NUMBER	int;
	DECLARE LI_MODULE_CODE	int;
	DECLARE LS_MODULE_ITEM_ID	varchar(20);
	DECLARE LS_OVERLAP	longtext;
	DECLARE LS_FOOTNOTE	longtext;
	DECLARE LS_CREATE_USER	varchar(60);
	DECLARE LD_CREATE_TIMESTAMP	datetime;
	DECLARE LI_UPDATE_USER	varchar(60);
	DECLARE LD_UPDATE_TIMESTAMP	datetime;
	DECLARE LI_CP_REPORT_HEADER_ID INT;
	DECLARE LI_LINKED_MODULE_CODE	int;
	DECLARE LS_LINKED_MODULE_ITEM_ID	varchar(20);
	DECLARE LS_IS_EXCLUDED	varchar(1);
	DECLARE LS_IS_MANUALLY_ADDED	varchar(1);
	DECLARE LS_UPDATE_USER	varchar(60); 
	DECLARE LS_PROJECT_TITLE	varchar(1000);
	DECLARE LS_GRANT_CALL_NAME	varchar(1000);
	DECLARE LI_PROP_PERSON_ROLE_ID	int;
	DECLARE LI_AMOUNT	decimal(15,2);
	DECLARE LD_END_DATE	datetime;
    DECLARE LI_NEW_CP_REPORT_PROJECT_DETAIL_ID INT;
	DECLARE LD_START_DATE	datetime;
	DECLARE LS_SPONSOR_TYPE_CODE	varchar(20);
	DECLARE LS_SPONSOR	varchar(500);
	DECLARE LI_FUNDING_STATUS_CODE	int;
	DECLARE LS_SPONSOR_CODE	varchar(20);
	DECLARE LS_CURRENCY_CODE	varchar(20);
	DECLARE LI_PERCENTAGE_OF_EFFORT	decimal(19,2);
	DECLARE LI_CP_REPORT_PROJECT_DETAIL_ID INT;
	DECLARE LS_ACADEMIC_MONTHS	varchar(5);
	DECLARE LS_CALENDAR_MONTHS	varchar(5);
	DECLARE LS_SUMMER_MONTHS	varchar(5);
	DECLARE LI_TOTAL_AWARD_AMOUNT	decimal(12,2);
	DECLARE LI_ANNUAL_DIRECT_COST	decimal(12,2);
	DECLARE LS_LEAD_PI_NON_EMPLOYEE_FLAG	varchar(1);
	DECLARE LS_LEAD_PI_PERSON_ID	varchar(40);
	DECLARE LS_LOCATION	varchar(1000);
	DECLARE LS_PERSON_ROLE_ID	int; 
	DECLARE LS_PRIME_AWARD	varchar(12);
	DECLARE LS_ACADEMIC_CONTACT_PERSON_ID	varchar(40);
	DECLARE LS_TECHNICAL_CONTACT_PERSON_ID	varchar(40);
	DECLARE LI_PROJECT_REL_TO_PROPOSED_EFFORT	decimal(5,2);
	DECLARE LS_PROJECT_GOALS	varchar(4000);
	DECLARE LS_SPECIFIC_AIMS	varchar(4000);
	DECLARE LS_PROJECT_SUMMARY	varchar(4000);
	DECLARE LS_COMMENTS	varchar(2000); 
    DECLARE LI_PERSON_ROLE_ID INT;
    DECLARE li_seq_proposal_id INT;
	DECLARE LS_ERROR_MSG	              VARCHAR(2000);
	DECLARE LS_ERROR_FLAG	              VARCHAR(1) DEFAULT 'N';
    DECLARE NOT_FOUND                 INT;
    DECLARE LS_PROC_LOC                VARCHAR(200);
	 
   
 	
    DECLARE  SEL_CP_REPORT_HEADER CURSOR FOR
    SELECT    CP_REPORT_HEADER_ID,PERSON_ID, NON_EMPLOYEE_FLAG, VERSION_NUMBER, MODULE_CODE, OVERLAP, FOOTNOTE, CREATE_USER, CREATE_TIMESTAMP, UPDATE_USER, UPDATE_TIMESTAMP FROM CP_REPORT_HEADER WHERE MODULE_ITEM_ID = li_seq_proposal_id;
	
	DECLARE  SEL_CP_REPORT_PROJECT_DETAILS CURSOR FOR
	SELECT CP_REPORT_PROJECT_DETAIL_ID,LINKED_MODULE_CODE, LINKED_MODULE_ITEM_ID, IS_EXCLUDED, IS_MANUALLY_ADDED, UPDATE_USER, UPDATE_TIMESTAMP, PROJECT_TITLE, GRANT_CALL_NAME, PROP_PERSON_ROLE_ID, AMOUNT, END_DATE, START_DATE, SPONSOR_TYPE_CODE, SPONSOR, FUNDING_STATUS_CODE, SPONSOR_CODE, CURRENCY_CODE, PERCENTAGE_OF_EFFORT FROM CP_REPORT_PROJECT_DETAILS WHERE CP_REPORT_HEADER_ID IN (LI_CP_REPORT_HEADER_ID);
	
	DECLARE  SEL_CP_REPORT_PROJECT_DETAILS_EXT CURSOR FOR
	  SELECT ACADEMIC_MONTHS, CALENDAR_MONTHS, SUMMER_MONTHS, TOTAL_AWARD_AMOUNT, ANNUAL_DIRECT_COST,
     LEAD_PI_NON_EMPLOYEE_FLAG, LEAD_PI_PERSON_ID, LOCATION, PERSON_ROLE_ID, PERCENTAGE_OF_EFFORT, PRIME_AWARD, ACADEMIC_CONTACT_PERSON_ID, TECHNICAL_CONTACT_PERSON_ID, PROJECT_REL_TO_PROPOSED_EFFORT, PROJECT_GOALS, SPECIFIC_AIMS,
      PROJECT_SUMMARY, COMMENTS, UPDATE_USER, UPDATE_TIMESTAMP FROM CP_REPORT_PROJECT_DETAILS_EXT WHERE CP_REPORT_PROJECT_DETAIL_ID = LI_CP_REPORT_PROJECT_DETAIL_ID;
	 
	
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;					 
					SET @full_error = CONCAT(@msg,'/',LS_PROC_LOC);	
					SET LS_ERROR_MSG = @full_error; 
                     RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
		 
                END;
				
     DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;	
 
	 SET LS_ERROR_FLAG = 'N';
	 
		IF AV_TYPE = 'C' THEN 
		
		  SET li_seq_proposal_id = AV_ACTIVE_PROPOSAL_ID;
 		ELSEIF AV_TYPE = 'M' THEN 
		set sql_safe_updates = 0;
         SET LS_PROC_LOC = 'DELETE_CP_REPORT_HEADER';
      	DELETE FROM CP_REPORT_PROJECT_DETAILS_EXT WHERE CP_REPORT_PROJECT_DETAIL_ID in  (select CP_REPORT_PROJECT_DETAIL_ID from 
        CP_REPORT_PROJECT_DETAILS where CP_REPORT_HEADER_ID in (select CP_REPORT_HEADER_ID from CP_REPORT_HEADER where MODULE_ITEM_ID = AV_ACTIVE_PROPOSAL_ID )) ;
        DELETE FROM CP_REPORT_PROJECT_DETAILS where CP_REPORT_HEADER_ID in (select CP_REPORT_HEADER_ID from CP_REPORT_HEADER where MODULE_ITEM_ID = AV_ACTIVE_PROPOSAL_ID );
        DELETE FROM CP_REPORT_HEADER where MODULE_ITEM_ID = AV_ACTIVE_PROPOSAL_ID ;
		 set sql_safe_updates = 1;
		 SET li_seq_proposal_id = AV_ARCHIVE_PROPOSAL_ID;		 
		  
		END IF;
		
	  
     SET LS_PROC_LOC = 'CP_REPORT_HEADER';
			
            OPEN SEL_CP_REPORT_HEADER;
            SEL_CP_REPORT_HEADER:LOOP
			SET NOT_FOUND  = 0;
             FETCH SEL_CP_REPORT_HEADER INTO LI_CP_REPORT_HEADER_ID,LS_PERSON_ID,LS_NON_EMPLOYEE_FLAG,LI_VERSION_NUMBER,LI_MODULE_CODE ,LS_OVERLAP,LS_FOOTNOTE,LS_CREATE_USER,LD_CREATE_TIMESTAMP,LI_UPDATE_USER,LD_UPDATE_TIMESTAMP;
              IF NOT_FOUND=1 THEN
            LEAVE SEL_CP_REPORT_HEADER;
            END IF;
                  INSERT INTO CP_REPORT_HEADER	
                (
				 PERSON_ID,
				 NON_EMPLOYEE_FLAG,
				 VERSION_NUMBER,
				 MODULE_CODE,
				 MODULE_ITEM_ID,
				 OVERLAP,
				 FOOTNOTE,
				 CREATE_USER,
				 CREATE_TIMESTAMP,
				 UPDATE_USER,
				 UPDATE_TIMESTAMP
					)					
                 VALUES(LS_PERSON_ID,
						LS_NON_EMPLOYEE_FLAG,
						LI_VERSION_NUMBER,
						LI_MODULE_CODE,
						CASE WHEN AV_TYPE = 'M' THEN AV_ACTIVE_PROPOSAL_ID WHEN AV_TYPE = 'C' THEN AV_ARCHIVE_PROPOSAL_ID END, 
						LS_OVERLAP,
						LS_FOOTNOTE,
						LS_CREATE_USER,
						LD_CREATE_TIMESTAMP,
						LI_UPDATE_USER,
						LD_UPDATE_TIMESTAMP
                );
				
				SET LI_NEW_CP_REPORT_HEADER_ID = LAST_INSERT_ID();
                
              
	  
	   SET LS_PROC_LOC = 'CP_REPORT_PROJECT_DETAILS';
			 
            OPEN SEL_CP_REPORT_PROJECT_DETAILS;
            SEL_CP_REPORT_PROJECT_DETAILS:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_CP_REPORT_PROJECT_DETAILS INTO LI_CP_REPORT_PROJECT_DETAIL_ID,LI_LINKED_MODULE_CODE,LS_LINKED_MODULE_ITEM_ID,LS_IS_EXCLUDED,LS_IS_MANUALLY_ADDED,LS_UPDATE_USER,LD_UPDATE_TIMESTAMP,LS_PROJECT_TITLE,LS_GRANT_CALL_NAME,LI_PROP_PERSON_ROLE_ID,LI_AMOUNT,LD_END_DATE,LD_START_DATE,LS_SPONSOR_TYPE_CODE,LS_SPONSOR,LI_FUNDING_STATUS_CODE,LS_SPONSOR_CODE,LS_CURRENCY_CODE,LI_PERCENTAGE_OF_EFFORT;
               IF NOT_FOUND=1 THEN
            LEAVE SEL_CP_REPORT_PROJECT_DETAILS;
            END IF;
             
                 INSERT INTO CP_REPORT_PROJECT_DETAILS	
                (
				 CP_REPORT_HEADER_ID,
				 LINKED_MODULE_CODE,
				 LINKED_MODULE_ITEM_ID,
				 IS_EXCLUDED,
				 IS_MANUALLY_ADDED,
				 UPDATE_USER,
				 UPDATE_TIMESTAMP,
				 PROJECT_TITLE,
				 GRANT_CALL_NAME,
				 PROP_PERSON_ROLE_ID,
				 AMOUNT,
				 END_DATE,
				 START_DATE,
				 SPONSOR_TYPE_CODE,
				 SPONSOR,
				 FUNDING_STATUS_CODE,
				 SPONSOR_CODE,
				 CURRENCY_CODE,
				 PERCENTAGE_OF_EFFORT
					)
					
                 VALUES(
				   LI_NEW_CP_REPORT_HEADER_ID,
					LI_LINKED_MODULE_CODE,
					LS_LINKED_MODULE_ITEM_ID,
					LS_IS_EXCLUDED,
					LS_IS_MANUALLY_ADDED,
					LS_UPDATE_USER,
					LD_UPDATE_TIMESTAMP,
					LS_PROJECT_TITLE,
					LS_GRANT_CALL_NAME,
					LI_PROP_PERSON_ROLE_ID,
					LI_AMOUNT,
					LD_END_DATE,
					LD_START_DATE,
					LS_SPONSOR_TYPE_CODE,
					LS_SPONSOR,
					LI_FUNDING_STATUS_CODE,
					LS_SPONSOR_CODE,
					LS_CURRENCY_CODE,
					LI_PERCENTAGE_OF_EFFORT
                );
                
              SET LI_NEW_CP_REPORT_PROJECT_DETAIL_ID = LAST_INSERT_ID();
 
		
	  SET LS_PROC_LOC = 'CP_REPORT_PROJECT_DETAILS_EXT';
			
            OPEN SEL_CP_REPORT_PROJECT_DETAILS_EXT;
            SEL_CP_REPORT_PROJECT_DETAILS_EXT:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_CP_REPORT_PROJECT_DETAILS_EXT INTO LS_ACADEMIC_MONTHS,LS_CALENDAR_MONTHS,LS_SUMMER_MONTHS,LI_TOTAL_AWARD_AMOUNT,LI_ANNUAL_DIRECT_COST,LS_LEAD_PI_NON_EMPLOYEE_FLAG,LS_LEAD_PI_PERSON_ID,
LS_LOCATION,LI_PERSON_ROLE_ID,LI_PERCENTAGE_OF_EFFORT,LS_PRIME_AWARD,LS_ACADEMIC_CONTACT_PERSON_ID,LS_TECHNICAL_CONTACT_PERSON_ID,LI_PROJECT_REL_TO_PROPOSED_EFFORT,LS_PROJECT_GOALS,LS_SPECIFIC_AIMS,LS_PROJECT_SUMMARY,LS_COMMENTS,LS_UPDATE_USER,LD_UPDATE_TIMESTAMP;
 
			
            IF NOT_FOUND=1 THEN
            LEAVE SEL_CP_REPORT_PROJECT_DETAILS_EXT;
            END IF;
            
               
                INSERT INTO CP_REPORT_PROJECT_DETAILS_EXT	
                (
				CP_REPORT_PROJECT_DETAIL_ID,
				ACADEMIC_MONTHS,
				CALENDAR_MONTHS,
				SUMMER_MONTHS,
				TOTAL_AWARD_AMOUNT,
				ANNUAL_DIRECT_COST,
				LEAD_PI_NON_EMPLOYEE_FLAG,
				LEAD_PI_PERSON_ID,
				LOCATION,
				PERSON_ROLE_ID,
				PERCENTAGE_OF_EFFORT,
				PRIME_AWARD,
				ACADEMIC_CONTACT_PERSON_ID,
				TECHNICAL_CONTACT_PERSON_ID,
				PROJECT_REL_TO_PROPOSED_EFFORT,
				PROJECT_GOALS,
				SPECIFIC_AIMS,
				PROJECT_SUMMARY,
				COMMENTS,
				UPDATE_USER,
				UPDATE_TIMESTAMP
					)
					
                 VALUES(LI_NEW_CP_REPORT_PROJECT_DETAIL_ID,
				   LS_ACADEMIC_MONTHS,
				   LS_CALENDAR_MONTHS ,
				   LS_SUMMER_MONTHS,
				   LI_TOTAL_AWARD_AMOUNT,
				   LI_ANNUAL_DIRECT_COST,
				   LS_LEAD_PI_NON_EMPLOYEE_FLAG,
				   LS_LEAD_PI_PERSON_ID,
				   LS_LOCATION,
				   LS_PERSON_ROLE_ID,
				   LI_PERCENTAGE_OF_EFFORT,
				   LS_PRIME_AWARD,
				   LS_ACADEMIC_CONTACT_PERSON_ID,
				   LS_TECHNICAL_CONTACT_PERSON_ID,
				   LI_PROJECT_REL_TO_PROPOSED_EFFORT,
				   LS_PROJECT_GOALS,
				   LS_SPECIFIC_AIMS,
				   LS_PROJECT_SUMMARY,
				   LS_COMMENTS,
				   LS_UPDATE_USER,
				   LD_UPDATE_TIMESTAMP
                );
                
              
		END LOOP SEL_CP_REPORT_PROJECT_DETAILS_EXT;
		CLOSE SEL_CP_REPORT_PROJECT_DETAILS_EXT;  
		
		
				END LOOP SEL_CP_REPORT_PROJECT_DETAILS;
		CLOSE SEL_CP_REPORT_PROJECT_DETAILS;  
		
				END LOOP SEL_CP_REPORT_HEADER;
		CLOSE SEL_CP_REPORT_HEADER; 
		 
END
