CREATE PROCEDURE `GET_PROPOSAL_DASHBOARD_COUNT`(
        AV_PROPOSAL_ID                  VARCHAR(20),
        AV_TITLE                        VARCHAR(1000),
        AV_RESEARCH_PERSON_ID           VARCHAR(200),
        AV_CATEGORY_TYPE                VARCHAR(200),
        AV_PROPOSAL_TYPE                VARCHAR(200),
        AV_SPONSOR_CODE                 VARCHAR(200),
        AV_HOME_UNIT_NUMBER             VARCHAR(200),
        AV_PROPOSAL_STATUS              VARCHAR(200),
        AV_EXTERNAL_FUNDING_AGENCY_ID   VARCHAR(200),
        AV_GRANT_HEADER_ID              VARCHAR(200),
        AV_KEYWORD                      VARCHAR(200),
        AV_PERSON_ID                    VARCHAR(200),
        AV_SORT_TYPE                    VARCHAR(500),
        AV_PAGED                        INT(10),
        AV_LIMIT                        INT(10),
        AV_TAB_TYPE                     VARCHAR(30),
        AV_UNLIMITED                    BOOLEAN,
        AV_TYPE                         VARCHAR(1),
        AV_APPLICATION_ID               VARCHAR(255),
        AV_ROLE_ID                      VARCHAR(200),
        AV_INTERNAL_DEADLINE_DATE       VARCHAR(30),
        AV_SPONSOR_DEADLINE_DATE        VARCHAR(30),
		AV_PROGRAM_ANNOUNCEMENT_NUMBER  VARCHAR(255),
        AV_FUNDING_SCHEME                VARCHAR(8)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
DECLARE TAB_QUERY LONGTEXT;
DECLARE JOIN_CONDITION LONGTEXT;
DECLARE SELECTED_FIELD_LIST LONGTEXT;

SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
SET LS_FILTER_CONDITION ='';
SET LS_DYN_SQL ='';
SET JOIN_CONDITION = '';
SET SELECTED_FIELD_LIST= '';

IF AV_TYPE = 'A' THEN

        IF AV_PROPOSAL_ID IS NOT NULL AND AV_PROPOSAL_ID <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PROPOSAL_ID LIKE ''%',AV_PROPOSAL_ID,'%'' AND ');
        END IF;

        IF AV_CATEGORY_TYPE IS NOT NULL  AND AV_CATEGORY_TYPE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.ACTIVITY_TYPE_CODE IN (',AV_CATEGORY_TYPE,') AND ');
                SET SELECTED_FIELD_LIST= CONCAT(SELECTED_FIELD_LIST,' ,T30.DESCRIPTION AS CATEGORY ');
        END IF;

        IF AV_PROPOSAL_STATUS IS NOT NULL  AND AV_PROPOSAL_STATUS <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.STATUS_CODE in (',AV_PROPOSAL_STATUS,') AND ');
        END IF;

                IF AV_FUNDING_SCHEME IS NOT NULL AND AV_FUNDING_SCHEME <> '' THEN 
		        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.FUNDING_SCHEME_CODE = ',AV_FUNDING_SCHEME,' AND ');
		END IF;

        IF AV_TITLE IS NOT NULL  AND AV_TITLE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.TITLE LIKE ',QUOTE(CONCAT('%',AV_TITLE,'%')),' AND ');
        END IF;

        IF AV_HOME_UNIT_NUMBER IS NOT NULL  AND AV_HOME_UNIT_NUMBER <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.HOME_UNIT_NUMBER LIKE ''%',AV_HOME_UNIT_NUMBER,'%'' AND ');
        END IF;

        IF AV_SPONSOR_CODE IS NOT NULL  AND AV_SPONSOR_CODE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.SPONSOR_CODE = ',AV_SPONSOR_CODE,' AND ');
        END IF;

        IF AV_PROPOSAL_TYPE IS NOT NULL  AND AV_PROPOSAL_TYPE <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PROPOSAL_TYPE_CODE IN (',AV_PROPOSAL_TYPE,') AND ');
        END IF;

        IF AV_EXTERNAL_FUNDING_AGENCY_ID IS NOT NULL  AND AV_EXTERNAL_FUNDING_AGENCY_ID <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.EXTERNAL_FUNDING_AGENCY_ID LIKE ''%',AV_EXTERNAL_FUNDING_AGENCY_ID,'%'' AND ');
        END IF;

        IF AV_GRANT_HEADER_ID IS NOT NULL  AND AV_GRANT_HEADER_ID <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.GRANT_HEADER_ID IN (',AV_GRANT_HEADER_ID,') AND ');
        END IF;

        IF AV_KEYWORD IS NOT NULL  AND AV_KEYWORD <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' T.KEYWORD LIKE ', QUOTE(CONCAT('%', AV_KEYWORD, '%')), ' AND ');
                SET JOIN_CONDITION = CONCAT(JOIN_CONDITION,' LEFT JOIN EPS_PROPOSAL_KEYWORDS T9 ON T9.PROPOSAL_ID = T1.PROPOSAL_ID
                                LEFT JOIN  SCIENCE_KEYWORD  T15 ON T15.SCIENCE_KEYWORD_CODE = T9.SCIENCE_KEYWORD_CODE ');
                SET SELECTED_FIELD_LIST= CONCAT(SELECTED_FIELD_LIST,' ,GROUP_CONCAT(IFNULL(T9.KEYWORD,''''),IFNULL(T15.DESCRIPTION,'''')   SEPARATOR '','')  AS KEYWORD ');
        END IF;

        IF AV_APPLICATION_ID IS NOT NULL  AND AV_APPLICATION_ID <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.APPLICATION_ID LIKE ''%',AV_APPLICATION_ID,'%'' AND ');
        END IF;

        IF (AV_ROLE_ID IS NOT NULL AND AV_ROLE_ID <> '') and (AV_RESEARCH_PERSON_ID IS NOT NULL AND AV_RESEARCH_PERSON_ID <> '') THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PROPOSAL_ID IN (SELECT PROPOSAL_ID
                        FROM EPS_PROPOSAL_PERSONS WHERE PROP_PERSON_ROLE_ID IN(
                        ',AV_ROLE_ID,') AND (PERSON_ID =''',AV_RESEARCH_PERSON_ID,''' OR ROLODEX_ID =''',AV_RESEARCH_PERSON_ID,''')) AND ' );
        END IF;

        IF (AV_ROLE_ID IS NOT NULL AND AV_ROLE_ID <> '') and (AV_RESEARCH_PERSON_ID IS NULL OR AV_RESEARCH_PERSON_ID = '') THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PROPOSAL_ID IN (SELECT PROPOSAL_ID
                        FROM EPS_PROPOSAL_PERSONS WHERE PROP_PERSON_ROLE_ID IN(
                        ',AV_ROLE_ID,')) AND ');
        END IF;

        IF (AV_ROLE_ID is null OR AV_ROLE_ID = '') AND (AV_RESEARCH_PERSON_ID IS NOT NULL AND AV_RESEARCH_PERSON_ID <> '') THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PROPOSAL_ID IN(SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS
                        WHERE (PERSON_ID =''',AV_RESEARCH_PERSON_ID,''' OR ROLODEX_ID =''',AV_RESEARCH_PERSON_ID,''')) AND ' );
        END IF;
					
	IF AV_INTERNAL_DEADLINE_DATE IS NOT NULL AND AV_INTERNAL_DEADLINE_DATE <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' DATE(T.INTERNAL_DEADLINE_DATE ) =   DATE_FORMAT(''',AV_INTERNAL_DEADLINE_DATE,''',''%Y-%m-%d'') AND ');
	END IF;

        IF AV_SPONSOR_DEADLINE_DATE IS NOT NULL AND AV_SPONSOR_DEADLINE_DATE <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT( LS_FILTER_CONDITION,' DATE(T.SPONSOR_DEADLINE_DATE ) =   DATE_FORMAT(''',AV_SPONSOR_DEADLINE_DATE,''',''%Y-%m-%d'') AND ');
	END IF;

        IF AV_PROGRAM_ANNOUNCEMENT_NUMBER IS NOT NULL  AND AV_PROGRAM_ANNOUNCEMENT_NUMBER <> '' THEN
                SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.PROGRAM_ANNOUNCEMENT_NUMBER LIKE ''%',AV_PROGRAM_ANNOUNCEMENT_NUMBER,'%'' AND ');
        END IF;

             IF AV_PROPOSAL_STATUS <> 35 OR AV_PROPOSAL_STATUS = '' THEN
    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' T.STATUS_CODE <> 35 AND ');
END IF;    

END IF;

IF AV_TAB_TYPE = 'MY_PROPOSAL' THEN

                SET TAB_QUERY = CONCAT(' T8.PERSON_ID = ''',AV_PERSON_ID,''' AND T8.PROP_PERSON_ROLE_ID = 3');

ELSEIF AV_TAB_TYPE = 'ALL_PROPOSALS' THEN

                SET TAB_QUERY = CONCAT(' (((T14.PERSON_ID = ''',AV_PERSON_ID,''' AND  T14.PROP_PERSON_ROLE_ID IN(3,9)) OR T3.PERSON_ID = ''',AV_PERSON_ID,''' OR T1.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)
                        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) AND (T1.GRANT_HEADER_ID IS NULL OR T6.HOME_UNIT_NUMBER = (SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = ''ROOT_UNIT'')))
                        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) AND (T1.GRANT_HEADER_ID IS NOT NULL AND T6.HOME_UNIT_NUMBER <> (SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = ''ROOT_UNIT'')))
                        OR T6.HOME_UNIT_NUMBER IN(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP_PROPOSAL_GM)))' );

                SET JOIN_CONDITION =  CONCAT(JOIN_CONDITION,' LEFT OUTER JOIN EPS_PROPOSAL_PERSON_ROLES T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID  LEFT JOIN EPS_PROPOSAL_PERSONS T14 ON T14.PROPOSAL_ID = T1.PROPOSAL_ID ');

                -- SET SELECTED_FIELD_LIST= CONCAT(SELECTED_FIELD_LIST,' ,T3.PERSON_ID AS EPS_PROPOSAL_PERSON_ROLE_ID');

ELSEIF AV_TAB_TYPE = 'INPROGRESS_PROPOSAL' THEN

                SET TAB_QUERY = CONCAT(' (T1.STATUS_CODE NOT IN(1,3,4,5,6,7,9,10,11,12,20,22,24,29,30) AND T1.HOME_UNIT_NUMBER IN
                        ((SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
                        UNION
                        (SELECT DISTINCT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))) ' );

ELSEIF AV_TAB_TYPE = 'REVIEW_COMPLETED_PROPOSALS' THEN

                SET TAB_QUERY = CONCAT(' (T1.STATUS_CODE IN(28,31,18,21,11) AND T1.HOME_UNIT_NUMBER IN
                        ((SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
                        UNION
                        (SELECT DISTINCT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))) ' );

ELSEIF AV_TAB_TYPE = 'MY_REVIEW_PENDING_PROPOSAL' THEN

                SET TAB_QUERY = CONCAT(' ((T10.REVIEWER_PERSON_ID = ''',AV_PERSON_ID,'''  AND T10.PRE_REVIEW_STATUS_CODE = ''1'' AND 
                T10.PRE_REVIEW_TYPE_CODE = ''1'' AND T10.MODULE_ITEM_CODE = 3)
                        OR (T11.REVIEW_STATUS_CODE = 1 AND T11.REVIEWER_PERSON_ID = ''',AV_PERSON_ID,''' )
                        OR (T12.IS_WORKFLOW_ACTIVE = ''Y'' AND T13.APPROVER_PERSON_ID = ''',AV_PERSON_ID,'''  AND  
                        T13.APPROVAL_STATUS = ''W''))
                        OR (T3.PERSON_ID = ''',AV_PERSON_ID,''' AND T1.STATUS_CODE IN(38))' );

                SET JOIN_CONDITION =  CONCAT(JOIN_CONDITION,' LEFT JOIN (select * from PRE_REVIEW where PRE_REVIEW_ID in (select max(PR.PRE_REVIEW_ID) as PRE_REVIEW_ID
						 from PRE_REVIEW  PR  
						where PR.REVIEWER_PERSON_ID = ''',AV_PERSON_ID,'''
						AND PR.PRE_REVIEW_STATUS_CODE = ''1''
						AND PR.MODULE_ITEM_CODE = 3 AND PR.MODULE_SUB_ITEM_CODE = 0 AND PR.MODULE_SUB_ITEM_KEY = 0
						group by PR.MODULE_ITEM_KEY ,PR.REVIEWER_PERSON_ID, PR.MODULE_ITEM_CODE,PR.MODULE_SUB_ITEM_CODE,PR.MODULE_SUB_ITEM_KEY)) T10 ON T10.MODULE_ITEM_KEY = T1.PROPOSAL_ID AND T10.MODULE_ITEM_CODE = 3 AND T10.MODULE_SUB_ITEM_CODE = 0 AND T10.MODULE_SUB_ITEM_KEY = 0
                        LEFT  OUTER JOIN  PROPOSAL_REVIEW T11 ON T11.PROPOSAL_ID = T1.PROPOSAL_ID
                        LEFT  OUTER JOIN  WORKFLOW T12 ON T12.MODULE_ITEM_ID = CAST(T1.PROPOSAL_ID AS CHAR) AND T12.MODULE_CODE =3
                        LEFT  OUTER JOIN  WORKFLOW_DETAIL T13 ON T13.WORKFLOW_ID = T12.WORKFLOW_ID 
                        LEFT OUTER JOIN EPS_PROPOSAL_PERSON_ROLES T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID AND T3.ROLE_ID = 650');

                SET SELECTED_FIELD_LIST= CONCAT(SELECTED_FIELD_LIST,' ,T10.REVIEWER_PERSON_ID AS PREREVIEWER_PERSON_ID,
                        T10.PRE_REVIEW_STATUS_CODE ,
                        T10.PRE_REVIEW_TYPE_CODE,
                        T10.MODULE_ITEM_CODE AS PRERVIEW_MODULE_ITEM_CODE,
                        T11.REVIEW_STATUS_CODE AS PROP_REVIEW_STATUS_CODE,
                        T11.REVIEWER_PERSON_ID AS PROP_REVIEWER_PERSON_ID ');
                       
					   END IF;

IF AV_SORT_TYPE IS NULL THEN
        SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
ELSE
    SET AV_SORT_TYPE = CONCAT(' ORDER BY ',AV_SORT_TYPE);
END IF;

IF AV_TYPE = 'L' THEN
        SET TAB_QUERY =  CONCAT(' T1.STATUS_CODE <> 35 AND ',TAB_QUERY);
END IF;

IF AV_UNLIMITED = TRUE THEN
        SET LS_OFFSET_CONDITION = '';
ELSE
        SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
END IF;

IF LS_FILTER_CONDITION <>'' THEN
        SET LS_FILTER_CONDITION = CONCAT(' WHERE ',LS_FILTER_CONDITION);
        SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;
END IF;
        
SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            )),
							ACCESS_TMP_PROPOSAL_GM 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') AND T1.ROLE_ID=''100'' 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') AND T1.ROLE_ID=''100''
                            ))
							');
							
        SET LS_DYN_SQL =CONCAT(LS_DYN_SQL,'SELECT DISTINCT count(*)  FROM(SELECT DISTINCT  T1.PROPOSAL_ID,
                T5.DESCRIPTION AS  PROPOSAL_STATUS,
                T1.TITLE,
                T16.DISPLAY_NAME AS HOME_UNIT_NAME,
                T31.SPONSOR_CODE,
                T31.DISPLAY_NAME AS SPONSOR_NAME,
                T31.ACRONYM,
                T1.GRANT_HEADER_ID,
                T6.NAME,
                T6.CLOSING_DATE,
                T8.FULL_NAME,
                T8.PERSON_ID AS PI_PERSON_ID,
                T1.EXTERNAL_FUNDING_AGENCY_ID,
                T1.CREATE_USER AS EPS_PROPOSAL_CREATE_USER,
                T8.PERSON_ID AS EPS_PROPOSAL_PERSON_ID,
                T1.HOME_UNIT_NUMBER,
                T1.UPDATE_TIMESTAMP,
                T1.TYPE_CODE AS PROPOSAL_TYPE_CODE,
                T7.DESCRIPTION AS PROPOSAL_TYPE,
                T1.SPONSOR_DEADLINE_DATE,
                T1.APPLICATION_ID,
                T1.ACTIVITY_TYPE_CODE,
                T1.IP_NUMBER,
                T1.GRANT_TYPE_CODE,
                T1.PROPOSAL_RANK,
                T1.EVALUATION_RECOMMENDATION_CODE,
                T1.STATUS_CODE ,
                T30.DESCRIPTION AS ACTIVITY_TYPE ,
                T1.SUBMIT_USER ,
                T1.SUBMISSION_DATE ,
                T25.GRANT_CALL_CATEGORY_CODE,
                T6.ABBREVIATION ,
                T1.INTERNAL_DEADLINE_DATE ,
            	T55.SCHEME_NAME AS FUNDING_SCHEME,
                T55.FUNDING_SCHEME_CODE,
                T1.PROGRAM_ANNOUNCEMENT_NUMBER,
                T1.END_DATE,
                T1.START_DATE ',SELECTED_FIELD_LIST,
                        ' FROM EPS_PROPOSAL T1
                        LEFT OUTER JOIN EPS_PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
                        LEFT  OUTER  JOIN GRANT_CALL_HEADER T6 ON T6.GRANT_HEADER_ID = T1.GRANT_HEADER_ID
                        LEFT OUTER JOIN  GRANT_CALL_TYPE T25 ON T25.GRANT_TYPE_CODE = T6.GRANT_TYPE_CODE
                        LEFT OUTER JOIN EPS_PROPOSAL_TYPE T7 ON T7.TYPE_CODE = T1.TYPE_CODE
                        LEFT  OUTER  JOIN EPS_PROPOSAL_PERSONS T8 ON T8.PROPOSAL_ID = T1.PROPOSAL_ID AND T8.PROP_PERSON_ROLE_ID = 3 AND T8.PI_FLAG = ''Y''
                        LEFT JOIN UNIT T16 ON T16.UNIT_NUMBER = T1.HOME_UNIT_NUMBER
                        LEFT JOIN ACTIVITY_TYPE T30 ON T30.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE
                        LEFT JOIN SPONSOR_FUNDING_SCHEME T54 ON T54.FUNDING_SCHEME_ID = T6.FUNDING_SCHEME_ID
						LEFT JOIN FUNDING_SCHEME T55 ON T55.FUNDING_SCHEME_CODE = T54.FUNDING_SCHEME_CODE
		        LEFT JOIN SPONSOR T31 ON T31.SPONSOR_CODE = T1.SPONSOR_CODE  ',JOIN_CONDITION,' WHERE T1.DOCUMENT_STATUS_CODE <> 3 AND',TAB_QUERY,
                        ' GROUP BY T1.PROPOSAL_ID)T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION );

SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;

END
