-- `FN_AWD_MANPOWER_CUTOFFDATE`; 


CREATE FUNCTION `FN_AWD_MANPOWER_CUTOFFDATE`(
AV_AWARD_ID INT
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LI_CUT_OFF_DATE INT;
DECLARE LI_CHARGE_START_DATE INT;
DECLARE LI_RESOURSEWITHCUTOFFDATE INT;
DECLARE LS_CUT_OFF_DATE INT;
SET LI_RESOURSEWITHCUTOFFDATE = 0;
SELECT CONFIGURATION_VALUE INTO LS_CUT_OFF_DATE
FROM MANPOWER_CONFIGURATION_DATA WHERE CONFIGURATION_KEY = 'MANPOWER_CUT_OFF_DATE';
SELECT COUNT(*) INTO LI_RESOURSEWITHCUTOFFDATE FROM AWARD_MANPOWER_RESOURCE WHERE AWARD_MANPOWER_ID IN(
SELECT AWARD_MANPOWER_ID FROM AWARD_MANPOWER WHERE AWARD_ID = AV_AWARD_ID)
AND ( DAY(COALESCE(CHARGE_START_DATE, PLAN_START_DATE)) > LS_CUT_OFF_DATE )
AND ( MONTH(SYSDATE()) = MONTH(COALESCE(CHARGE_START_DATE, PLAN_START_DATE)) )
AND ( DAY(SYSDATE()) > LS_CUT_OFF_DATE )
AND POSITION_STATUS_CODE in (1,2,4,7); 
	IF LI_RESOURSEWITHCUTOFFDATE > 0 THEN
		RETURN 'TRUE'; 
	ELSE
		RETURN 'FALSE';
	END IF;
END
