-- `FN_AWD_PI_IS_UNITAPPROVAL_HOD`; 


CREATE FUNCTION `FN_AWD_PI_IS_UNITAPPROVAL_HOD`(
AV_AWARD_ID	VARCHAR(22)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LS_PI_PERSON_ID 	VARCHAR(40);
DECLARE LI_FLAG 			INT;
DECLARE LS_LEAD_UNIT_NUMBER VARCHAR(50);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_AWARD_ID VARCHAR(22);
	SELECT AWARD_NUMBER INTO LS_AWARD_NUMBER FROM AWARD
	WHERE AWARD_ID = AV_AWARD_ID; 
	SELECT LEAD_UNIT_NUMBER,AWARD_ID INTO LS_LEAD_UNIT_NUMBER, LS_AWARD_ID FROM AWARD
	WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
	IF LS_LEAD_UNIT_NUMBER IS NOT NULL THEN
		SET AV_AWARD_ID = LS_AWARD_ID;
	ELSE 
		SELECT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM AWARD
		WHERE AWARD_ID = AV_AWARD_ID;
	END IF;
	SELECT PERSON_ID INTO LS_PI_PERSON_ID FROM AWARD_PERSONS
	WHERE AWARD_ID = AV_AWARD_ID
	AND PI_FLAG = 'Y';
	SELECT COUNT(1) INTO LI_FLAG FROM UNIT_ADMINISTRATOR
    WHERE PERSON_ID = LS_PI_PERSON_ID
	AND UNIT_NUMBER = LS_LEAD_UNIT_NUMBER
	AND UNIT_ADMINISTRATOR_TYPE_CODE = '5';
	IF LI_FLAG > 0 THEN
		RETURN 'TRUE';
	ELSE
		RETURN 'FALSE';
	END IF;
END
