-- `FN_CHK_TASK_AWD_ACCOUNT_FILLED`; 


CREATE FUNCTION `FN_CHK_TASK_AWD_ACCOUNT_FILLED`(AV_TASK_ID VARCHAR(10), 
AV_TASK_TYPE_CODE varchar(3) ) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LI_COUNT INT(3);
DECLARE LI_AWARD_ID INT(22);
SELECT MODULE_ITEM_ID INTO LI_AWARD_ID
FROM TASK 
where TASK_ID = AV_TASK_ID;
SELECT COUNT(*) INTO LI_COUNT 
FROM AWARD 
WHERE AWARD_ID = LI_AWARD_ID
AND AWARD_DOCUMENT_TYPE_CODE = 1; 
IF LI_COUNT = 0 THEN
	RETURN 'TRUE';
END IF;
IF AV_TASK_TYPE_CODE = 5 THEN     
		SELECT COUNT(*) INTO LI_COUNT
		FROM award
		WHERE AWARD_ID = LI_AWARD_ID
		AND (ACCOUNT_TYPE_CODE IS NOT NULL AND ACCOUNT_TYPE_CODE <> '');
		IF LI_COUNT = 0 THEN
			RETURN 'FALSE';
		ELSE
			RETURN 'TRUE';
		END IF;
END IF;
RETURN 'TRUE';
END
