-- `FN_CHK_AWARD_MILESTONE`; 


CREATE FUNCTION `FN_CHK_AWARD_MILESTONE`( 
AV_AWARD_ID VARCHAR(12)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LS_MILESTONE_START_DATE DATETIME;
DECLARE LS_MILESTONE_END_DATE DATETIME;
DECLARE LS_AWARD_START_DATE DATETIME;
DECLARE LS_AWARD_END_DATE DATETIME;
	SELECT 
		DATE(BEGIN_DATE),
		DATE(FINAL_EXPIRATION_DATE)
	INTO 
		LS_AWARD_START_DATE,
		LS_AWARD_END_DATE
	FROM AWARD
	WHERE AWARD_ID = AV_AWARD_ID;
	BEGIN
			DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE CUR_DATA CURSOR FOR
			SELECT DATE(START_DATE),DATE(END_DATE) FROM AWARD_MILESTONE
			WHERE AWARD_ID = AV_AWARD_ID;
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN CUR_DATA;
			INSERT_LOOP: LOOP 
			FETCH CUR_DATA INTO
			LS_MILESTONE_START_DATE,
			LS_MILESTONE_END_DATE;
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
			IF (LS_MILESTONE_START_DATE < LS_AWARD_START_DATE) OR (LS_MILESTONE_END_DATE > LS_AWARD_END_DATE) THEN
				RETURN 'FALSE';
			END IF;
			END LOOP;
			CLOSE CUR_DATA;
	END;
	RETURN 'TRUE';
END
