-- `FN_CHK_PREV_CLAIM_EDITABLE`; 


CREATE FUNCTION `FN_CHK_PREV_CLAIM_EDITABLE`(AV_CLAIM_ID VARCHAR(6)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_AWARD_NUMBER VARCHAR(200);
DECLARE LI_COUNT INT DEFAULT 0;
BEGIN
				SELECT AWARD_NUMBER INTO LI_AWARD_NUMBER FROM CLAIM WHERE CLAIM_ID = AV_CLAIM_ID AND CLAIM_NUMBER LIKE 'R%';
				IF LI_AWARD_NUMBER IS NOT NULL THEN
					SELECT COUNT(1) INTO LI_COUNT FROM CLAIM T1 
					WHERE T1.CLAIM_ID IN (
					SELECT T2.CLAIM_ID FROM CLAIM T2
					WHERE T2.AWARD_NUMBER=LI_AWARD_NUMBER AND T2.CLAIM_ID<> AV_CLAIM_ID 
					AND T2.CLAIM_ID< AV_CLAIM_ID AND (T2.CLAIM_STATUS_CODE IN ('2' , '7')));
				else
					RETURN 'TRUE'; 
				END IF;
IF LI_COUNT > 0 THEN
	RETURN 'FALSE';
ELSE
	RETURN 'TRUE';
END IF;
END;
END
