-- `FN_CHK_OUTSTANDING_COMMITMENTS`; 


CREATE FUNCTION `FN_CHK_OUTSTANDING_COMMITMENTS`(
AV_AWARD_ID VARCHAR(12)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_COMMITMENT INT DEFAULT 0;
BEGIN
		SELECT (SUM(AMOUNT_IN_FMA_CURRENCY) <> 0) INTO LI_COMMITMENT FROM AWARD_EXPENSE_TRANSACTIONS WHERE AWARD_NUMBER = (SELECT DISTINCT AWARD_NUMBER FROM AWARD WHERE AWARD_ID = AV_AWARD_ID) AND ACTUAL_OR_COMMITTED_FLAG = 'C';	
IF LI_COMMITMENT > 0 THEN
	RETURN 'TRUE';
ELSE
	RETURN 'FALSE';
END IF;
END;
END
