-- `FN_CHCK_AWARD_TASK_TYPE`; 


CREATE FUNCTION `FN_CHCK_AWARD_TASK_TYPE`( 
AV_TASK_ID    varchar(10)
) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LI_TASK_TYPE_CODE INT;
select TASK_TYPE_CODE INTO LI_TASK_TYPE_CODE
FROM TASK 
where TASK_ID = AV_TASK_ID;
IF LI_TASK_TYPE_CODE = 1 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 2 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 3 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 4 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 5 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 6 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 7 THEN
    RETURN 'TRUE';
ELSEIF LI_TASK_TYPE_CODE = 8 THEN
    RETURN 'TRUE';
ELSE 
	RETURN 'FALSE';
END IF;
END
