-- `FN_CHECK_QUESTIONNARE_COMPLETED`; 


CREATE FUNCTION `FN_CHECK_QUESTIONNARE_COMPLETED`(
AV_MODULE_ITEM_KEY 	VARCHAR(200)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LI_QUESTIONNAIRE_ANS_HEADER_ID 	INT(12);
DECLARE LS_MODULE_ITEM_KEY 				VARCHAR(20);
DECLARE LI_QUESTION_ID					INT(12);
DECLARE LI_FLAG 						INT(3);
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_CONDITION_FLAG VARCHAR(1000);
DECLARE LI_QUESTIONNAIRE_ID 			INT(12);
DECLARE LS_ERROR_MSG VARCHAR(1000);
			SELECT COUNT(1) INTO LI_FLAG
			FROM QUEST_ANSWER_HEADER T1 
            INNER JOIN QUEST_HEADER T2
            ON T1.QUESTIONNAIRE_ID = T2.QUESTIONNAIRE_ID
			WHERE T1.MODULE_ITEM_CODE = 1
            AND T1.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY
			AND T2.QUESTIONNAIRE_NUMBER = 1204
            AND T2.IS_FINAL = 'Y';
            IF LI_FLAG = 0 THEN 
				RETURN 'FALSE';
            END IF;
	BEGIN 
			DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE CUR_QUEST_ANSWER_HEADER CURSOR FOR
			SELECT 
				T1.QUESTIONNAIRE_ANS_HEADER_ID,
				T1.MODULE_ITEM_KEY,
                T1.QUESTIONNAIRE_ID
			FROM QUEST_ANSWER_HEADER T1 
            INNER JOIN QUEST_HEADER T2
            ON T1.QUESTIONNAIRE_ID = T2.QUESTIONNAIRE_ID
			WHERE T1.MODULE_ITEM_CODE = 1
            AND T1.MODULE_ITEM_KEY = AV_MODULE_ITEM_KEY
			AND T2.QUESTIONNAIRE_NUMBER = 1204
            AND T2.IS_FINAL = 'Y';
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN CUR_QUEST_ANSWER_HEADER;
			A_LOOP: LOOP 
			FETCH CUR_QUEST_ANSWER_HEADER INTO
			LI_QUESTIONNAIRE_ANS_HEADER_ID,
			LS_MODULE_ITEM_KEY,
            LI_QUESTIONNAIRE_ID;
			IF DONE1 THEN
				LEAVE A_LOOP;
			END IF;
						BEGIN
							DECLARE DONE2 INT DEFAULT FALSE;
							DECLARE CUR_QUEST_QUESTION CURSOR FOR
							SELECT QUESTION_ID  from QUEST_QUESTION WHERE QUESTIONNAIRE_ID = LI_QUESTIONNAIRE_ID AND PARENT_QUESTION_ID IS NULL;
							DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
							OPEN CUR_QUEST_QUESTION;
							B_LOOP: LOOP 
							FETCH CUR_QUEST_QUESTION INTO
							LI_QUESTION_ID;
							IF DONE2 THEN
								LEAVE B_LOOP;
							END IF;
							CALL QUESTION_ANSWER_CHECK(LI_QUESTIONNAIRE_ANS_HEADER_ID, LI_QUESTION_ID, LI_QUESTIONNAIRE_ID, @EXPR_RESULT);
							SET LS_CONDITION_FLAG = @EXPR_RESULT;
							IF LS_CONDITION_FLAG = 'FALSE' THEN
								RETURN 'FALSE';
							END IF;
							END LOOP;
							CLOSE CUR_QUEST_QUESTION;
						END;
			END LOOP;
			CLOSE CUR_QUEST_ANSWER_HEADER;
	END;
RETURN LS_CONDITION_FLAG;
END
