-- `FN_CHCK_BUDGET_CAN_SUBMIT`; 


CREATE FUNCTION `FN_CHCK_BUDGET_CAN_SUBMIT`(AV_AWARD_ID VARCHAR(22)) RETURNS varchar(8) 
    DETERMINISTIC
BEGIN
DECLARE LS_AVAILABLE_FUND_TYPE varchar(1);
DECLARE LI_OBLI_DISTRIBUTABLE_AMOUNT DECIMAL(15,2);
DECLARE LI_TOTAL_COST DECIMAL(15,2);
DECLARE LI_COUNT INT(3);
DECLARE LI_COUNT_TWO INT(3);
DECLARE LI_COMMITMENT_AMOUNT DECIMAL(15,2);
DECLARE LI_ANT_DISTRIBUTABLE_AMOUNT DECIMAL(15,2);
DECLARE LS_AWARD_NUMBER varchar(12);
SELECT COUNT(*) INTO LI_COUNT
FROM AWARD
WHERE AWARD_ID = AV_AWARD_ID
AND AWARD_DOCUMENT_TYPE_CODE = 1;
IF LI_COUNT = 0  THEN
SELECT COUNT(*) INTO LI_COUNT
FROM MODULE_VARIABLE_SECTION
WHERE MODULE_ITEM_KEY = AV_AWARD_ID
AND MODULE_CODE = 1 AND SUB_MODULE_CODE=0 AND SECTION_CODE = 102;
END IF;
IF LI_COUNT = 0  THEN
	RETURN 'TRUE';
END IF;
SELECT COUNT(*) INTO LI_COUNT
FROM award_budget_header
WHERE AWARD_ID = AV_AWARD_ID;
IF LI_COUNT = 0 THEN
	RETURN 'TRUE';
END IF;
SELECT AWARD_NUMBER INTO LS_AWARD_NUMBER
FROM AWARD
WHERE AWARD_ID = AV_AWARD_ID;
SELECT COUNT(*) INTO LI_COUNT 
FROM AWARD_AMOUNT_TRANSACTION T1 
WHERE (T1.SOURCE_AWARD_NUMBER = LS_AWARD_NUMBER
OR T1.DESTINATION_AWARD_NUMBER = LS_AWARD_NUMBER)  AND T1.TRANSACTION_STATUS_CODE = 'P';
IF LI_COUNT = 0 THEN
	RETURN 'TRUE';
END IF;
SELECT COUNT(*) INTO LI_COUNT_TWO 
FROM AWARD_AMOUNT_TRANSACTION T1 LEFT OUTER JOIN AWARD_AMOUNT_INFO T2 ON
 T1.TRANSACTION_ID = T2.TRANSACTION_ID
WHERE (T1.SOURCE_AWARD_NUMBER = LS_AWARD_NUMBER
OR T1.DESTINATION_AWARD_NUMBER = LS_AWARD_NUMBER) AND T1.TRANSACTION_STATUS_CODE = 'P'
AND T1.AWARD_NUMBER = LS_AWARD_NUMBER AND T2.AWARD_ID = AV_AWARD_ID;
IF (LI_COUNT= LI_COUNT_TWO) THEN
	RETURN 'TRUE';
END IF;
RETURN 'FALSE';
END
