-- `FN_GET_CLAIM_AMOUNT`; 


CREATE FUNCTION `FN_GET_CLAIM_AMOUNT`(AV_AWARD_NUMBER VARCHAR(12), AV_CLAIM_ID INT(12)) RETURNS decimal(15,2)
    DETERMINISTIC
BEGIN
DECLARE LI_TOTAL_AMOUNT DECIMAL(15,2);
	SELECT
		(CASE
		WHEN LOCATE('D',T1.CLAIM_NUMBER) > 0
			THEN T1.TOTAL_AMOUNT 
		ELSE 
			(CASE WHEN ((SELECT COUNT(1)
				FROM AWARD T3
				WHERE T3.AWARD_ID = T1.AWARD_ID AND T3.BASIS_OF_PAYMENT_CODE = '7') > 0)
				 THEN  (	
						CASE
							WHEN ((SELECT COUNT(1)
								FROM AWARD T3
								LEFT OUTER JOIN GRANT_CALL_HEADER T4 ON T4.GRANT_HEADER_ID = T3.GRANT_HEADER_ID
								LEFT OUTER JOIN SPONSOR_FUNDING_SCHEME T5 ON T5.FUNDING_SCHEME_ID = T4.FUNDING_SCHEME_ID
								left outer join CLAIM_FUNDING_SCHEME t6 on t6.funding_Scheme_Code = t5.funding_Scheme_Code
								WHERE T3.AWARD_ID = T1.AWARD_ID AND t6.OVERRIDE_NEGATIVE_AMOUNT = 'Y') > 0)
							THEN 
								(select IFNULL(SUM(t.AMOUNT_REQ_CURRENT_CLAIM),0) + IFNULL(if( ((IFNULL(SUM(t.COMMITMENTS_UPTO_PREV_CLAIM),0)*(t.OVERHEAD_PERCENTAGE/100))+
								(IFNULL(SUM(t.AMOUNT_FORCASTED),0)*(t.OVERHEAD_PERCENTAGE/100))-((select  ifnull(IDC_CUM_CLAIM_AMT_UPTO_CLAIM,0) from claim where claim_id = T1.CLAIM_ID) -((IFNULL(SUM(t.CUM_EXPENSE_UPTO_PREV_CLAIM),0)+
								IFNULL(SUM(t.AMOUNT_REQUESTED),0))*(t.OVERHEAD_PERCENTAGE/100)))) < 0,0.00, ((IFNULL(SUM(t.COMMITMENTS_UPTO_PREV_CLAIM),0)*(t.OVERHEAD_PERCENTAGE/100))+
								(IFNULL(SUM(t.AMOUNT_FORCASTED),0)*(t.OVERHEAD_PERCENTAGE/100))-((select  ifnull(IDC_CUM_CLAIM_AMT_UPTO_CLAIM,0) from claim where claim_id = T1.CLAIM_ID) -((IFNULL(SUM(t.CUM_EXPENSE_UPTO_PREV_CLAIM),0)+
								IFNULL(SUM(t.AMOUNT_REQUESTED),0))*(t.OVERHEAD_PERCENTAGE/100))))),0)
								from
								(SELECT t4.AMOUNT_REQ_CURRENT_CLAIM as AMOUNT_REQ_CURRENT_CLAIM,  t4.COMMITMENTS_UPTO_PREV_CLAIM as COMMITMENTS_UPTO_PREV_CLAIM,t4.AMOUNT_FORCASTED as AMOUNT_FORCASTED,
								t4.CUM_EXPENSE_UPTO_PREV_CLAIM as CUM_EXPENSE_UPTO_PREV_CLAIM, t4.AMOUNT_REQUESTED as AMOUNT_REQUESTED, t3.OVERHEAD_PERCENTAGE
								FROM CLAIM T3 LEFT OUTER JOIN 
								CLAIM_SUMMARY T4 ON T4.CLAIM_ID = T3.CLAIM_ID 	
								WHERE T3.CLAIM_ID =  T1.CLAIM_ID  and T4.AMOUNT_REQ_CURRENT_CLAIM >= 0	
								union
								SELECT  0 as AMOUNT_REQ_CURRENT_CLAIM,  t4.COMMITMENTS_UPTO_PREV_CLAIM as COMMITMENTS_UPTO_PREV_CLAIM,t4.AMOUNT_FORCASTED as AMOUNT_FORCASTED,
								t4.CUM_EXPENSE_UPTO_PREV_CLAIM as CUM_EXPENSE_UPTO_PREV_CLAIM, t4.AMOUNT_REQUESTED as AMOUNT_REQUESTED, t3.OVERHEAD_PERCENTAGE
								FROM CLAIM T3 LEFT OUTER JOIN 
								CLAIM_SUMMARY T4 ON T4.CLAIM_ID = T3.CLAIM_ID 				
								WHERE T3.CLAIM_ID =  T1.CLAIM_ID  and T4.AMOUNT_REQ_CURRENT_CLAIM < 0)t)
							ELSE
								(select IFNULL(SUM(t.AMOUNT_REQ_CURRENT_CLAIM),0) +IFNULL((IFNULL(SUM(t.COMMITMENTS_UPTO_PREV_CLAIM),0)*(t.OVERHEAD_PERCENTAGE/100))+
								(IFNULL(SUM(t.AMOUNT_FORCASTED),0)*(t.OVERHEAD_PERCENTAGE/100))-((select  ifnull(IDC_CUM_CLAIM_AMT_UPTO_CLAIM,0) from claim where claim_id = T1.CLAIM_ID) -((IFNULL(SUM(t.CUM_EXPENSE_UPTO_PREV_CLAIM),0)+
								IFNULL(SUM(t.AMOUNT_REQUESTED),0))*(t.OVERHEAD_PERCENTAGE/100))),0)
								from
								(SELECT t4.AMOUNT_REQ_CURRENT_CLAIM as AMOUNT_REQ_CURRENT_CLAIM,  t4.COMMITMENTS_UPTO_PREV_CLAIM as COMMITMENTS_UPTO_PREV_CLAIM,t4.AMOUNT_FORCASTED as AMOUNT_FORCASTED,
								t4.CUM_EXPENSE_UPTO_PREV_CLAIM as CUM_EXPENSE_UPTO_PREV_CLAIM, t4.AMOUNT_REQUESTED as AMOUNT_REQUESTED, t3.OVERHEAD_PERCENTAGE
								FROM CLAIM T3 LEFT OUTER JOIN 
								CLAIM_SUMMARY T4 ON T4.CLAIM_ID = T3.CLAIM_ID 	
								WHERE T3.CLAIM_ID =  T1.CLAIM_ID  and T4.AMOUNT_REQ_CURRENT_CLAIM >= 0	
								union
								SELECT t4.AMOUNT_REQ_CURRENT_CLAIM,  t4.COMMITMENTS_UPTO_PREV_CLAIM as COMMITMENTS_UPTO_PREV_CLAIM,t4.AMOUNT_FORCASTED as AMOUNT_FORCASTED,
								t4.CUM_EXPENSE_UPTO_PREV_CLAIM as CUM_EXPENSE_UPTO_PREV_CLAIM, t4.AMOUNT_REQUESTED as AMOUNT_REQUESTED, t3.OVERHEAD_PERCENTAGE
								FROM CLAIM T3 LEFT OUTER JOIN 
								CLAIM_SUMMARY T4 ON T4.CLAIM_ID = T3.CLAIM_ID 				
								WHERE T3.CLAIM_ID =  T1.CLAIM_ID  and T4.AMOUNT_REQ_CURRENT_CLAIM < 0)t)
							END
					   )
			ELSE (CASE WHEN 1= 1 THEN (SELECT IFNULL(SUM(T3.AMOUNT_REQUESTED),0)+(IFNULL(T4.ADJUSTED_INDIRECT_COST,0)) FROM
				CLAIM_SUMMARY T3
				INNER JOIN CLAIM T4 ON T3.CLAIM_ID = T4.CLAIM_ID
				WHERE T3.CLAIM_ID = T1.CLAIM_ID)
				END)
			END)
		END) AS TOTAL_AMOUNT into LI_TOTAL_AMOUNT
	FROM CLAIM T1
	WHERE T1.AWARD_NUMBER = AV_AWARD_NUMBER AND T1.CLAIM_ID = AV_CLAIM_ID;
	
	return ifnull(LI_TOTAL_AMOUNT,0.00);
END
