-- `FN_GET_AWARD_HIERARCHY_NEXTSEQ`; 


CREATE FUNCTION `FN_GET_AWARD_HIERARCHY_NEXTSEQ`(
AV_AWARD_NUMBER  varchar(12)
) RETURNS varchar(12) 
    DETERMINISTIC
BEGIN
DECLARE LS_AWARD_NUMBER varchar(12);
DECLARE LS_SUBAWARD_NUMBER varchar(12);
DECLARE LS_NXTSEQ_NUMBER varchar(12);
SELECT substring_index(AV_AWARD_NUMBER, '-', 1) INTO LS_SUBAWARD_NUMBER FROM DUAL; 
SELECT MAX(AWARD_NUMBER) INTO LS_AWARD_NUMBER FROM AWARD WHERE AWARD_NUMBER LIKE CONCAT(LS_SUBAWARD_NUMBER,'-%');
SELECT CAST(substring_index(LS_AWARD_NUMBER, '-', -1)AS DECIMAL)+1 INTO LS_NXTSEQ_NUMBER FROM DUAL;
RETURN LS_NXTSEQ_NUMBER;
END
