-- `FN_NOTIFY_LOCK_AWD_SUBMISN`; 


CREATE FUNCTION `FN_NOTIFY_LOCK_AWD_SUBMISN`( 
AV_AWARD_ID   decimal(22,0)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
DECLARE LS_COUNT INT;
SELECT COUNT(*) INTO LS_COUNT FROM AWARD 
WHERE AWARD_ID = AV_AWARD_ID
AND STATUS_CODE in (14)
AND AWARD_VARIATION_TYPE_CODE NOT IN (5);
IF LS_COUNT = 0 THEN
	RETURN 'FALSE';
ELSE
	RETURN 'TRUE';
END IF;
END
