INSERT INTO award_method_of_payment (METHOD_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Automatic Scheduled Payment (ACH)','2025-04-01 14:06:52','admin','Y');
INSERT INTO award_method_of_payment (METHOD_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('10','Special Handling Scheduled Payment','2025-04-01 14:08:40','admin','Y');
INSERT INTO award_method_of_payment (METHOD_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Fixed Price Invoice','2025-04-01 14:07:28','admin','Y');
INSERT INTO award_method_of_payment (METHOD_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Progress Payment Invoices','2025-04-01 14:09:19','admin','Y');
INSERT INTO award_method_of_payment (METHOD_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Advanced Payment Invoice','2025-04-01 14:07:55','admin','Y');
