INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Firm Fixed Price','2025-04-01 13:54:39','admin','Y');
INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Cost Reimbursement','2025-04-01 13:54:14','admin','Y');
INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Fixed Price Level of Effort','2025-04-01 13:54:27','admin','Y');
INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Other','2019-06-19 06:32:55','admin','Y');
INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Gift','2019-06-19 06:32:56','admin','Y');
INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','No Payment','2019-06-19 06:32:56','admin','Y');
INSERT INTO award_basis_of_payment (BASIS_OF_PAYMENT_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Advance','2022-05-05 10:13:53','admin','Y');
