INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('CH','Hold',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('CX','Cancelled',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('E','Error','2020-09-30 09:38:24','admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('F','Feed','2020-09-30 09:38:25','admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('H','Hold',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('N','Not To Feed','2020-09-15 19:53:15','admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('P','Pending','2020-09-30 09:38:25','admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('R','Success','2020-09-30 09:38:25','admin','Y');
INSERT INTO sap_feed_status (FEED_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('X','Cancelled','2020-09-15 19:53:15','admin','Y');
