INSERT INTO sap_feed_type (FEED_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('C','Change','Y','admin','2020-06-12 10:24:30');
INSERT INTO sap_feed_type (FEED_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATE_USER,UPDATE_TIMESTAMP) VALUES ('N','New','Y','admin','2020-06-12 10:24:30');
