-- `COPY_MERGE_EPS_PROPOSAL_ORGANIZATION_DATA`; 

CREATE PROCEDURE `COPY_MERGE_EPS_PROPOSAL_ORGANIZATION_DATA`(
IN AV_ACTIVE_PROPOSAL_ID  INT,
IN AV_ARCHIVE_PROPOSAL_ID  INT,
IN AV_TYPE VARCHAR(1) 
)
BEGIN
    DECLARE LS_ORGANIZATION_TYPE_CODE	varchar(3);
	DECLARE LS_ORGANIZATION_ID	varchar(20);
	DECLARE LI_ROLODEX_ID	int;
	DECLARE LS_LOCATION	varchar(300);
	DECLARE LD_UPDATE_TIMESTAMP	datetime;
	DECLARE LS_UPDATE_USER	varchar(60);
	DECLARE LI_PROPOSAL_ORGANIZATION_ID INT;
	DECLARE LI_CONG_DISTRICT_CODE	int;  
	DECLARE LS_ERROR_MSG	              VARCHAR(2000);
	DECLARE LS_ERROR_FLAG	              VARCHAR(1) DEFAULT 'N';
    DECLARE NOT_FOUND                 INT;
    DECLARE LS_PROC_LOC                VARCHAR(200);
    DECLARE li_seq_proposal_id          INT;
	DECLARE LI_LS_PROPOSAL_ORGANIZATION_ID INT;
	
	
	DECLARE  SEL_EPS_PROPOSAL_ORGANIZATION CURSOR FOR
	SELECT PROPOSAL_ORGANIZATION_ID,ORGANIZATION_TYPE_CODE,ORGANIZATION_ID,ROLODEX_ID,LOCATION,UPDATE_TIMESTAMP,UPDATE_USER FROM EPS_PROPOSAL_ORGANIZATION WHERE PROPOSAL_ID =li_seq_proposal_id;
  
    DECLARE  SEL_EPS_PROPOSAL_CONG_DISTRICT CURSOR FOR
	SELECT  CONG_DISTRICT_CODE, UPDATE_TIMESTAMP, UPDATE_USER FROM EPS_PROPOSAL_CONG_DISTRICT WHERE 
	PROPOSAL_ORGANIZATION_ID = LI_LS_PROPOSAL_ORGANIZATION_ID ;
	
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;					 
					SET @full_error = CONCAT(@msg,'COPY_EPS_PROPOSAL_ORGANIZATION_DATA','/',LS_PROC_LOC);	
					SET LS_ERROR_MSG = @full_error;
                    RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;			
		 
                END;
				
     DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;	
 
	 SET LS_ERROR_FLAG = 'N';
	 
	 IF AV_TYPE = 'M' THEN 
	 SET LS_PROC_LOC = 'DELETE_EPS_PROPOSAL_ORGANIZATION';
     SET SQL_SAFE_UPDATES = 0;
	  DELETE FROM EPS_PROPOSAL_CONG_DISTRICT WHERE PROPOSAL_ORGANIZATION_ID IN (SELECT PROPOSAL_ORGANIZATION_ID FROM EPS_PROPOSAL_ORGANIZATION WHERE PROPOSAL_ID =AV_ACTIVE_PROPOSAL_ID);
      DELETE FROM EPS_PROPOSAL_ORGANIZATION WHERE PROPOSAL_ID =AV_ACTIVE_PROPOSAL_ID ;
     
      SET SQL_SAFE_UPDATES = 1;
	  SET li_seq_proposal_id = AV_ARCHIVE_PROPOSAL_ID;
	  
	 ELSEIF AV_TYPE = 'C' THEN 
	 
	 SET li_seq_proposal_id = AV_ACTIVE_PROPOSAL_ID;
	 
	 END IF;
	  
    SET LS_PROC_LOC = 'EPS_PROPOSAL_ORGANIZATION';
			
            OPEN SEL_EPS_PROPOSAL_ORGANIZATION;
            SEL_EPS_PROPOSAL_ORGANIZATION:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_EPS_PROPOSAL_ORGANIZATION INTO LI_LS_PROPOSAL_ORGANIZATION_ID,LS_ORGANIZATION_TYPE_CODE,LS_ORGANIZATION_ID,LI_ROLODEX_ID,LS_LOCATION,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER;
 
			
            IF NOT_FOUND=1 THEN
            LEAVE SEL_EPS_PROPOSAL_ORGANIZATION;
            END IF;
            
               
                INSERT INTO EPS_PROPOSAL_ORGANIZATION	
                (
				 PROPOSAL_ID,
				 ORGANIZATION_TYPE_CODE,
				 ORGANIZATION_ID,
				 ROLODEX_ID,
				 LOCATION,
				 UPDATE_TIMESTAMP,
				 UPDATE_USER )
					VALUES(
				    CASE WHEN AV_TYPE = 'M' THEN AV_ACTIVE_PROPOSAL_ID WHEN AV_TYPE = 'C' THEN AV_ARCHIVE_PROPOSAL_ID END,
					LS_ORGANIZATION_TYPE_CODE,
					LS_ORGANIZATION_ID,
					LI_ROLODEX_ID,
					LS_LOCATION,
					LD_UPDATE_TIMESTAMP,
					LS_UPDATE_USER
                );
                
				SET LI_PROPOSAL_ORGANIZATION_ID = LAST_INSERT_ID();
              
		
		
    SET LS_PROC_LOC = 'EPS_PROPOSAL_CONG_DISTRICT';
			
            OPEN SEL_EPS_PROPOSAL_CONG_DISTRICT;
            SEL_EPS_PROPOSAL_CONG_DISTRICT:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_EPS_PROPOSAL_CONG_DISTRICT INTO LI_CONG_DISTRICT_CODE,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER;
 
			
            IF NOT_FOUND=1 THEN
            LEAVE SEL_EPS_PROPOSAL_CONG_DISTRICT;
            END IF;
            
               
                INSERT INTO EPS_PROPOSAL_CONG_DISTRICT	
                (
				 PROPOSAL_ORGANIZATION_ID,
				 CONG_DISTRICT_CODE,
				 UPDATE_TIMESTAMP,
				 UPDATE_USER )
					VALUES(
				   LI_PROPOSAL_ORGANIZATION_ID,
				   LI_CONG_DISTRICT_CODE,
				   LD_UPDATE_TIMESTAMP,
				   LS_UPDATE_USER
                );
                
              
		END LOOP SEL_EPS_PROPOSAL_CONG_DISTRICT;
		CLOSE SEL_EPS_PROPOSAL_CONG_DISTRICT;  
		
			END LOOP SEL_EPS_PROPOSAL_ORGANIZATION;
		CLOSE SEL_EPS_PROPOSAL_ORGANIZATION;  
   
  
END
