-- `COPY_MERGE_EPS_PROPOSAL_CUSTOM_DATA`; 

CREATE PROCEDURE `COPY_MERGE_EPS_PROPOSAL_CUSTOM_DATA`(
IN AV_ACTIVE_PROPOSAL_ID  INT,
IN AV_ARCHIVE_PROPOSAL_ID  INT,
IN AV_TYPE VARCHAR(1) 
)
BEGIN
	 
	DECLARE LI_CUSTOM_DATA_ELEMENTS_ID	int; 
	DECLARE LD_UPDATE_TIMESTAMP	datetime(6);
	DECLARE LS_UPDATE_USER	varchar(255);
	DECLARE LS_VALUE	varchar(4000);
	DECLARE LS_DESCRIPTION	varchar(255);
    DECLARE LS_ERROR_MSG	              VARCHAR(2000);
	DECLARE LS_ERROR_FLAG	              VARCHAR(1) DEFAULT 'N';
    DECLARE NOT_FOUND                 INT;
    DECLARE LS_PROC_LOC                VARCHAR(200);
    DECLARE li_seq_proposal_id          INT;
    
   DECLARE SEL_CUSTOM_DATA CURSOR FOR
   SELECT CUSTOM_DATA_ELEMENTS_ID, UPDATE_TIMESTAMP, 
   UPDATE_USER, VALUE, DESCRIPTION 
   FROM CUSTOM_DATA WHERE MODULE_ITEM_CODE = 3 AND MODULE_ITEM_KEY = li_seq_proposal_id;
   
   
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;					 
					SET @full_error = CONCAT(@msg,'/',LS_PROC_LOC);	
					SET LS_ERROR_MSG = @full_error;
                    RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;			
		 
                END;
				
     DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;	
 
	 SET LS_ERROR_FLAG = 'N';  
       
   IF AV_TYPE = 'M' THEN 
   SET LS_PROC_LOC = 'DELETE_CUSTOM_DATA';
    SET li_seq_proposal_id = AV_ARCHIVE_PROPOSAL_ID;
	SET SQL_SAFE_UPDATES = 0;
   DELETE FROM CUSTOM_DATA WHERE MODULE_ITEM_CODE = 3 AND MODULE_ITEM_KEY = AV_ACTIVE_PROPOSAL_ID;
SET SQL_SAFE_UPDATES = 1;
   ELSEIF AV_TYPE = 'C' THEN 
    
	SET li_seq_proposal_id = AV_ACTIVE_PROPOSAL_ID;
   
   END IF;
        
   SET LS_PROC_LOC = 'CUSTOM_DATA';
			
         OPEN SEL_CUSTOM_DATA;
            SEL_CUSTOM_DATA:LOOP
            SET NOT_FOUND  = 0;
            FETCH SEL_CUSTOM_DATA INTO LI_CUSTOM_DATA_ELEMENTS_ID,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER,LS_VALUE,LS_DESCRIPTION; 
			
            IF NOT_FOUND=1 THEN
            LEAVE SEL_CUSTOM_DATA;
            END IF;
            
               
                INSERT INTO CUSTOM_DATA	
                (
				 CUSTOM_DATA_ELEMENTS_ID,
				 MODULE_ITEM_CODE,
				 MODULE_ITEM_KEY,
				 MODULE_SUB_ITEM_CODE,
				 MODULE_SUB_ITEM_KEY,
				 UPDATE_TIMESTAMP,
				 UPDATE_USER,
				 VALUE,
				 DESCRIPTION  )
                 VALUES(
				 LI_CUSTOM_DATA_ELEMENTS_ID,
				 3,
				 CASE WHEN AV_TYPE = 'M' THEN AV_ACTIVE_PROPOSAL_ID WHEN AV_TYPE = 'C' THEN AV_ARCHIVE_PROPOSAL_ID END,
				 0,
				 0,
				 LD_UPDATE_TIMESTAMP,
				 LS_UPDATE_USER,
				 LS_VALUE,
				 LS_DESCRIPTION
                );
				
				
			END LOOP SEL_CUSTOM_DATA;
		CLOSE SEL_CUSTOM_DATA;         
 
		 
END
