-- `COPY_MERGE_EPS_PROPOSAL_COMMENTS_DATA`; 

CREATE PROCEDURE `COPY_MERGE_EPS_PROPOSAL_COMMENTS_DATA`(
IN AV_ACTIVE_PROPOSAL_ID  INT,
IN AV_ARCHIVE_PROPOSAL_ID  INT,
IN AV_TYPE VARCHAR(1) 
)
BEGIN 
    DECLARE LS_COMMENT_TYPE_CODE	varchar(3);
	DECLARE LS_COMMENTS	longtext; 
	DECLARE LS_IS_PRIVATE	varchar(1);
	DECLARE LI_EPS_PROPOSAL_COMMENT_ID INT;
    DECLARE LI_LS_EPS_PROPOSAL_COMMENT_ID INT;
	DECLARE LS_FILE_NAME	varchar(300);
	DECLARE LS_FILE_DATA_ID	varchar(36);
	DECLARE LS_MIME_TYPE	varchar(250);
	DECLARE LS_ACTION_TYPE_CODE	varchar(3);
	DECLARE LS_MESSAGE	varchar(2000);
	DECLARE LD_UPDATE_TIMESTAMP	datetime;
	DECLARE LS_UPDATE_USER	varchar(60); 
	
	DECLARE LS_ERROR_MSG	              VARCHAR(2000);
	DECLARE LS_ERROR_FLAG	              VARCHAR(1) DEFAULT 'N';
    DECLARE NOT_FOUND                 INT;
    DECLARE LS_PROC_LOC                VARCHAR(200);
    DECLARE li_seq_proposal_id          INT;
	DECLARE LI_COMMENT_ATTACHMENT_ID INT;
	
    DECLARE  SEL_EPS_PROPOSAL_COMMENTS CURSOR FOR
	SELECT EPS_PROPOSAL_COMMENT_ID,COMMENT_TYPE_CODE, COMMENTS, UPDATE_TIMESTAMP, 
	UPDATE_USER, IS_PRIVATE FROM EPS_PROPOSAL_COMMENTS WHERE PROPOSAL_ID IN (li_seq_proposal_id);
	DECLARE  SEL_EPS_PROPOSAL_ACTION_LOG CURSOR FOR
    SELECT  ACTION_TYPE_CODE, MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER FROM EPS_PROPOSAL_ACTION_LOG
    WHERE EPS_PROPOSAL_COMMENT_ID = LI_LS_EPS_PROPOSAL_COMMENT_ID;
	DECLARE  SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS CURSOR FOR
    SELECT  FILE_NAME, FILE_DATA_ID, MIME_TYPE, UPDATE_TIMESTAMP, UPDATE_USER FROM EPS_PROPOSAL_COMMENT_ATTACHMENTS
    WHERE EPS_PROPOSAL_COMMENT_ID = LI_LS_EPS_PROPOSAL_COMMENT_ID;
 
	
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;					 
					SET @full_error = CONCAT(@msg,'/',LS_PROC_LOC);	
					SET LS_ERROR_MSG = @full_error;
                    RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
                END;
				
     DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;	
 
	 SET LS_ERROR_FLAG = 'N';
     
	   IF AV_TYPE = 'M' THEN 
	   SET LS_PROC_LOC = 'DELETE_EPS_PROPOSAL_COMMENTS';
	   SET SQL_SAFE_UPDATES = 0;
	   DELETE FROM   EPS_PROPOSAL_COMMENT_ATTACHMENTS
       WHERE EPS_PROPOSAL_COMMENT_ID IN (SELECT EPS_PROPOSAL_COMMENT_ID FROM EPS_PROPOSAL_COMMENTS WHERE PROPOSAL_ID IN (AV_ACTIVE_PROPOSAL_ID));
	   DELETE FROM  EPS_PROPOSAL_ACTION_LOG
       WHERE EPS_PROPOSAL_COMMENT_ID IN (SELECT EPS_PROPOSAL_COMMENT_ID FROM EPS_PROPOSAL_COMMENTS WHERE PROPOSAL_ID IN (AV_ACTIVE_PROPOSAL_ID));
	   
       DELETE FROM EPS_PROPOSAL_COMMENTS WHERE PROPOSAL_ID IN (AV_ACTIVE_PROPOSAL_ID);
       SET SQL_SAFE_UPDATES = 1;
	   
	   SET li_seq_proposal_id = AV_ARCHIVE_PROPOSAL_ID;
	   ELSEIF AV_TYPE = 'C' THEN
	   
	   SET li_seq_proposal_id = AV_ACTIVE_PROPOSAL_ID;
	   
	   END IF;
	   
	  
  		 SET LS_PROC_LOC = 'EPS_PROPOSAL_COMMENTS';
			
            OPEN SEL_EPS_PROPOSAL_COMMENTS;
            SEL_EPS_PROPOSAL_COMMENTS:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_EPS_PROPOSAL_COMMENTS INTO  LI_LS_EPS_PROPOSAL_COMMENT_ID, LS_COMMENT_TYPE_CODE,LS_COMMENTS,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER,LS_IS_PRIVATE;
              IF NOT_FOUND=1 THEN
            LEAVE SEL_EPS_PROPOSAL_COMMENTS;
            END IF;
            
               
                INSERT INTO EPS_PROPOSAL_COMMENTS	
                (
				 PROPOSAL_ID,
				 COMMENT_TYPE_CODE,
				 COMMENTS,
				 UPDATE_TIMESTAMP,
				 UPDATE_USER,
				 IS_PRIVATE
					)
					
                 VALUES(
				 CASE WHEN AV_TYPE = 'M' THEN AV_ACTIVE_PROPOSAL_ID WHEN AV_TYPE = 'C' THEN AV_ARCHIVE_PROPOSAL_ID END,
				 LS_COMMENT_TYPE_CODE,
				 LS_COMMENTS,
				 LD_UPDATE_TIMESTAMP,
				 LS_UPDATE_USER,
				 LS_IS_PRIVATE
                );
                
				SET LI_EPS_PROPOSAL_COMMENT_ID = LAST_INSERT_ID();
              
 SET LS_PROC_LOC = 'EPS_PROPOSAL_ACTION_LOG';
			
            OPEN SEL_EPS_PROPOSAL_ACTION_LOG;
            SEL_EPS_PROPOSAL_ACTION_LOG:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_EPS_PROPOSAL_ACTION_LOG INTO LS_ACTION_TYPE_CODE,LS_MESSAGE,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER;
 
             IF NOT_FOUND=1 THEN
            LEAVE SEL_EPS_PROPOSAL_ACTION_LOG;
            END IF;
            
               
                INSERT INTO EPS_PROPOSAL_ACTION_LOG	
                (
					EPS_PROPOSAL_COMMENT_ID,
					ACTION_TYPE_CODE,
					MESSAGE,
					PROPOSAL_ID,
					UPDATE_TIMESTAMP,
					UPDATE_USER
					)
					
                 VALUES(
				LI_EPS_PROPOSAL_COMMENT_ID,
				LS_ACTION_TYPE_CODE,
				LS_MESSAGE,
				CASE WHEN AV_TYPE = 'M' THEN AV_ACTIVE_PROPOSAL_ID WHEN AV_TYPE = 'C' THEN AV_ARCHIVE_PROPOSAL_ID END,
				LD_UPDATE_TIMESTAMP,
				LS_UPDATE_USER
                );
                
              
		END LOOP SEL_EPS_PROPOSAL_ACTION_LOG;
		CLOSE SEL_EPS_PROPOSAL_ACTION_LOG; 
    SET LS_PROC_LOC = 'EPS_PROPOSAL_COMMENT_ATTACHMENTS';
			
            OPEN SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS;
            SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS:LOOP
			SET NOT_FOUND  = 0;
            FETCH SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS INTO LS_FILE_NAME,LS_FILE_DATA_ID,LS_MIME_TYPE,LD_UPDATE_TIMESTAMP,LS_UPDATE_USER;
 
             IF NOT_FOUND=1 THEN
            LEAVE SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS;
            END IF;
            
               
                INSERT INTO EPS_PROPOSAL_COMMENT_ATTACHMENTS	
                (
					EPS_PROPOSAL_COMMENT_ID,
					FILE_NAME,
					FILE_DATA_ID,
					MIME_TYPE,
					UPDATE_TIMESTAMP,
					UPDATE_USER
					)
					
                 VALUES(
				LI_EPS_PROPOSAL_COMMENT_ID,
				LS_FILE_NAME,
				LS_FILE_DATA_ID,
				LS_MIME_TYPE,
				LD_UPDATE_TIMESTAMP,
				LS_UPDATE_USER
                );
                
              
		END LOOP SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS;
		CLOSE SEL_EPS_PROPOSAL_COMMENT_ATTACHMENTS;  		
		
				END LOOP SEL_EPS_PROPOSAL_COMMENTS;
		CLOSE SEL_EPS_PROPOSAL_COMMENTS; 
	 
		 
END
