CREATE PROCEDURE `COPY_MERGE_EPS_PROPOSAL`(
AV_ACTIVE_PROPOSAL_ID	INT,
AV_ARCHIVE_PROPOSAL_ID	INT,
AV_TYPE	VARCHAR(1) 
)
BEGIN

	DECLARE LS_ERROR_MSG	              VARCHAR(2000);
	DECLARE LS_ERROR_FLAG	              VARCHAR(1) DEFAULT 'N';
    DECLARE NOT_FOUND                     INT;
    DECLARE LS_PROC_LOC                    VARCHAR(200);
    DECLARE LI_PROPOSAL_ID              INT;

 
	
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
				BEGIN
				
					GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
					 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;					 
					SET @full_error = CONCAT(@msg,'/',LS_PROC_LOC);	
					  SET LS_ERROR_MSG = @full_error;
                      SELECT LS_ERROR_MSG;
                       	RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
                        
                 /*   INSERT INTO `PROPOSAL_ERROR_LOG` VALUES 
                    ( LI_PROPOSAL_ID, LS_ERROR_MSG, 'COPY_MERGE_EPS_PROPOSAL', LS_PROC_LOC,NOW(), 'quickstart');
		 */
                END; 
				
	 SET LS_ERROR_FLAG = 'N'; 
	 
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_DATA(AV_ACTIVE_PROPOSAL_ID,AV_ARCHIVE_PROPOSAL_ID,AV_TYPE,@LI_NEW_PROPOSAL_ID);
	   
   
	    
		  IF AV_TYPE = 'C' THEN 
	     
		 SET LI_PROPOSAL_ID = @LI_NEW_PROPOSAL_ID;
		 
		 ELSE 
		 
		 SET LI_PROPOSAL_ID = AV_ARCHIVE_PROPOSAL_ID;
		 
		 END IF;
		 
		 SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_ATTCH_DATA';
		 
		CALL COPY_MERGE_EPS_PROPOSAL_ATTCH_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
  
		
		SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_BUDGET_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_BUDGET_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_QUESTIONNAIRE_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_QUESTIONNAIRE_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_PERSON_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_PERSON_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_ORGANIZATION_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_ORGANIZATION_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_KPI_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_KPI_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_COMMENTS_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_COMMENTS_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_CUSTOM_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_CUSTOM_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	   
	   SET LS_PROC_LOC = 'COPY_MERGE_EPS_PROPOSAL_ADDITIONAL_DATA';
	   
	   CALL COPY_MERGE_EPS_PROPOSAL_ADDITIONAL_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
       
       CALL COPY_MERGE_EPS_PROPOSAL_CP_REPORT_DATA(AV_ACTIVE_PROPOSAL_ID,LI_PROPOSAL_ID,AV_TYPE);
	 IF AV_TYPE = 'C' THEN 
      SELECT LI_PROPOSAL_ID as 'PROPOSAL_ID' ;
      ELSE 
      SELECT AV_ACTIVE_PROPOSAL_ID AS 'PROPOSAL_ID' ;
	 END IF;
END
