-- `PROPOSAL_WAITING_WORKFLOW_REMINDER`; 

CREATE PROCEDURE `PROPOSAL_WAITING_WORKFLOW_REMINDER`(AV_DAYS INT)
BEGIN
	SELECT DISTINCT T2.MODULE_CODE, T2.SUB_MODULE_CODE, T2.MODULE_ITEM_ID AS MODULE_ITEM_KEY, T2.SUB_MODULE_ITEM_KEY, T1.APPROVER_PERSON_ID AS PERSON_ID, T1.STOP_NAME AS APPROVER_STOP_NAME FROM WORKFLOW_DETAIL T1 
    INNER JOIN WORKFLOW T2 ON T2.WORKFLOW_ID = T1.WORKFLOW_ID WHERE T1.APPROVAL_STATUS = 'W' AND T2.IS_WORKFLOW_ACTIVE = 'Y' AND T2.MODULE_CODE = 3
    AND DATE(UTC_TIMESTAMP()) = DATE(DATE_ADD(T1.UPDATE_TIMESTAMP,INTERVAL AV_DAYS DAY));
END
