DROP TABLE IF EXISTS `agreement_document_type`;

CREATE TABLE `agreement_document_type` (
  `DOCUMENT_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DOCUMENT_TYPE_CODE`)
) ;