DROP TABLE IF EXISTS `agreement_esign_document`;

CREATE TABLE `agreement_esign_document` (
  `AGREEMENT_ESIGN_DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGREEMENT_ESIGN_ID` int(11) NOT NULL,
  `AGREEMENT_ATTACHMENT_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_ESIGN_DOCUMENT_ID`),
  KEY `AGREEMENT_ESIGN_DOCUMENT_FK1` (`AGREEMENT_ATTACHMENT_ID`),
  CONSTRAINT `AGREEMENT_ESIGN_DOCUMENT_FK1` FOREIGN KEY (`AGREEMENT_ATTACHMENT_ID`) REFERENCES `agreement_attachment` (`AGREEMENT_ATTACHMENT_ID`)
) ;