DROP TABLE IF EXISTS `agreement_people_roles`;

CREATE TABLE `agreement_people_roles` (
  `AGREEMENT_PEOPLE_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGREEMENT_REQUEST_ID` int(11) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `ROLE_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_SYSTEM_DERIVED_ROLE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_PEOPLE_ROLE_ID`),
  KEY `AGREEMENT_PEOPLE_ROLES_FK1` (`PERSON_ID`),
  KEY `AGREEMENT_PEOPLE_ROLES_FK2` (`ROLE_ID`),
  CONSTRAINT `AGREEMENT_PEOPLE_ROLES_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`),
  CONSTRAINT `AGREEMENT_PEOPLE_ROLES_FK2` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ROLE_ID`)
);
