DROP TABLE IF EXISTS `agreement_clauses`;

CREATE TABLE `agreement_clauses` (
  `AGREEMENT_CLAUSES_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGREEMENT_REQUEST_ID` int(11) DEFAULT NULL,
  `CLAUSES` varchar(1000) DEFAULT NULL,
  `CLAUSES_GROUP_CODE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_CLAUSES_ID`),
  KEY `AGREEMENT_CLAUSES_FK1` (`CLAUSES_GROUP_CODE`),
  KEY `AGREEMENT_TYPE_CLAUSES_FK1` (`AGREEMENT_REQUEST_ID`),
  CONSTRAINT `AGREEMENT_CLAUSES_FK1` FOREIGN KEY (`CLAUSES_GROUP_CODE`) REFERENCES `clauses_group` (`CLAUSES_GROUP_CODE`),
  CONSTRAINT `AGREEMENT_TYPE_CLAUSES_FK1` FOREIGN KEY (`AGREEMENT_REQUEST_ID`) REFERENCES `agreement_header` (`AGREEMENT_REQUEST_ID`)
) ;
