DROP TABLE IF EXISTS `agreement_note`;

CREATE TABLE `agreement_note` (
  `AGREEMENT_NOTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTION_LOG_ID` int(11) DEFAULT NULL,
  `NOTE` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `AGREEMENT_REQUEST_ID` int(11) DEFAULT NULL,
  `ACTION_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_NOTE_ID`),
  KEY `AGREEMENT_NOTE_FK2` (`ACTION_LOG_ID`),
  KEY `AGREEMENT_NOTE_FK1` (`AGREEMENT_REQUEST_ID`),
  CONSTRAINT `AGREEMENT_NOTE_FK1` FOREIGN KEY (`AGREEMENT_REQUEST_ID`) REFERENCES `agreement_header` (`AGREEMENT_REQUEST_ID`),
  CONSTRAINT `AGREEMENT_NOTE_FK2` FOREIGN KEY (`ACTION_LOG_ID`) REFERENCES `agreement_action_log` (`ACTION_LOG_ID`)
) ;
