DROP TABLE IF EXISTS `agreement_note_attachment`;

CREATE TABLE `agreement_note_attachment` (
  `AGREEMENT_NOTE_ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGREEMENT_ATTACHMENT_FILE_ID` varchar(36) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  `AGREEMENT_NOTE_ID` int(11) NOT NULL,
  PRIMARY KEY (`AGREEMENT_NOTE_ATTACHMENT_ID`),
  KEY `AGREEMENT_NOTE_ATTACHMENT_FK1` (`AGREEMENT_NOTE_ID`),
  CONSTRAINT `AGREEMENT_NOTE_ATTACHMENT_FK1` FOREIGN KEY (`AGREEMENT_NOTE_ID`) REFERENCES `agreement_note` (`AGREEMENT_NOTE_ID`)
) ;
