DROP TABLE IF EXISTS `agreement_attachment_type`;

CREATE TABLE `agreement_attachment_type` (
  `AGREEMENT_ATTACHMENT_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `IS_PRIVATE` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`AGREEMENT_ATTACHMENT_TYPE_CODE`)
);