DROP TABLE IF EXISTS `agreement_sponsor`;

CREATE TABLE `agreement_sponsor` (
  `AGREEMENT_SPONSOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SPONSOR_NAME` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `CONTACT_ADDRESS_LINE1` varchar(2000) DEFAULT NULL,
  `AGREEMENT_SPONSOR_TYPE_CODE` varchar(3) DEFAULT NULL,
  `REG_NUMBER` varchar(50) DEFAULT NULL,
  `SPONSOR_CODE` varchar(6) DEFAULT NULL,
  `SPONSOR_ROLE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `AGREEMENT_REQUEST_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`AGREEMENT_SPONSOR_ID`),
  KEY `AGREEMENT_SPONSOR_FK2` (`SPONSOR_CODE`),
  KEY `AGREEMENT_SPONSOR_FK3` (`SPONSOR_ROLE_TYPE_CODE`),
  KEY `AGREEMENT_SPONSOR_FK4` (`AGREEMENT_SPONSOR_TYPE_CODE`),
  KEY `AGREEMENT_SPONSOR_FK1` (`AGREEMENT_REQUEST_ID`),
  CONSTRAINT `AGREEMENT_SPONSOR_FK1` FOREIGN KEY (`AGREEMENT_REQUEST_ID`) REFERENCES `agreement_header` (`AGREEMENT_REQUEST_ID`),
  CONSTRAINT `AGREEMENT_SPONSOR_FK2` FOREIGN KEY (`SPONSOR_CODE`) REFERENCES `sponsor` (`SPONSOR_CODE`),
  CONSTRAINT `AGREEMENT_SPONSOR_FK3` FOREIGN KEY (`SPONSOR_ROLE_TYPE_CODE`) REFERENCES `sponsor_role` (`SPONSOR_ROLE_TYPE_CODE`),
  CONSTRAINT `AGREEMENT_SPONSOR_FK4` FOREIGN KEY (`AGREEMENT_SPONSOR_TYPE_CODE`) REFERENCES `agreement_sponsor_type` (`AGREEMENT_SPONSOR_TYPE_CODE`)
) ;
