DROP TABLE IF EXISTS `agreement_type_template`;

CREATE TABLE `agreement_type_template` (
  `TEMPLATE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGREEMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `CONTENT_TYPE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DOCUMENT_ID` int(11) DEFAULT NULL,
  `DOCUMENT_STATUS_CODE` int(11) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `IS_FINAL` varchar(1) DEFAULT NULL,
  `TEMPLATE` longblob,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  `VERSION_NUMBER` int(11) DEFAULT NULL,
  PRIMARY KEY (`TEMPLATE_ID`),
  KEY `AGREEMENT_TYPE_TEMPLATE_FK1` (`AGREEMENT_TYPE_CODE`),
  KEY `AGREEMENT_TYPE_TEMPLATE_FK2` (`DOCUMENT_STATUS_CODE`),
  CONSTRAINT `AGREEMENT_TYPE_TEMPLATE_FK1` FOREIGN KEY (`AGREEMENT_TYPE_CODE`) REFERENCES `agreement_type` (`AGREEMENT_TYPE_CODE`),
  CONSTRAINT `AGREEMENT_TYPE_TEMPLATE_FK2` FOREIGN KEY (`DOCUMENT_STATUS_CODE`) REFERENCES `document_status` (`DOCUMENT_STATUS_CODE`)
) ;
