DROP TABLE IF EXISTS `assoc_agreement`;

CREATE TABLE `assoc_agreement` (
  `ASSOC_AGREEMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGREEMENT_ID` int(11) DEFAULT NULL,
  `ASSOC_RELATION_TYPE_CODE` varchar(3) DEFAULT NULL,
  `ASSOC_CONFIG_CODE` varchar(3) DEFAULT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(12) DEFAULT NULL,
  `MODULE_ITEM_ID` int(11) DEFAULT NULL,
  `ASSOC_TYPE` varchar(10) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `IS_IMPORTED` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ASSOC_AGREEMENT_ID`),
  KEY `ASSOC_AGREEMENT_FK1_idx` (`ASSOC_RELATION_TYPE_CODE`),
  KEY `ASSOC_AGREEMENT_FK2_idx` (`ASSOC_CONFIG_CODE`),
  CONSTRAINT `ASSOC_AGREEMENT_FK1` FOREIGN KEY (`ASSOC_RELATION_TYPE_CODE`) REFERENCES `assoc_relation_type` (`ASSOC_RELATION_TYPE_CODE`),
  CONSTRAINT `ASSOC_AGREEMENT_FK2` FOREIGN KEY (`ASSOC_CONFIG_CODE`) REFERENCES `assoc_config` (`ASSOC_CONFIG_CODE`)
) ;
