DROP TABLE IF EXISTS `clauses`;

CREATE TABLE `clauses` (
  `CLAUSES_CODE` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `IS_SYSTEM_SPECIFIC` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  `CLAUSES_GROUP_CODE` int(11) DEFAULT NULL,
  PRIMARY KEY (`CLAUSES_CODE`),
  KEY `CLAUSES_FK1` (`CLAUSES_GROUP_CODE`),
  CONSTRAINT `CLAUSES_FK1` FOREIGN KEY (`CLAUSES_GROUP_CODE`) REFERENCES `clauses_group` (`CLAUSES_GROUP_CODE`)
) ;
