DROP TABLE IF EXISTS `negotiation_action_config`;

CREATE TABLE `negotiation_action_config` (
  `ACTION_ID` int(11) NOT NULL,
  `CURRENT_STATUS_CODE` varchar(3) DEFAULT NULL,
  `NEXT_STATUS_CODE` varchar(3) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `ICON_CLASS_NAME` varchar(200) DEFAULT NULL,
  `IS_CONFIRMATION_REQUIRED` varchar(1) DEFAULT NULL,
  `ACTION_TYPE_CODE` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`ACTION_ID`),
  KEY `REVIEW_STATUS_ACTION_FK1` (`CURRENT_STATUS_CODE`),
  KEY `REVIEW_STATUS_ACTION_FK3` (`ACTION_TYPE_CODE`),
  CONSTRAINT `REVIEW_STATUS_ACTION_FK1` FOREIGN KEY (`CURRENT_STATUS_CODE`) REFERENCES `negotiation_location_status` (`LOCATION_STATUS_CODE`),
  CONSTRAINT `REVIEW_STATUS_ACTION_FK3` FOREIGN KEY (`ACTION_TYPE_CODE`) REFERENCES `agreement_action_type` (`ACTION_TYPE_CODE`)
) ;
