DROP TABLE IF EXISTS `negotiation_activity`;

CREATE TABLE `negotiation_activity` (
  `NEGOTIATION_ACTIVITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NEGOTIATION_ID` int(11) DEFAULT NULL,
  `NEGOTIATION_LOCATION_ID` int(11) DEFAULT NULL,
  `LOCATION_TYPE_CODE` varchar(3) DEFAULT NULL,
  `ACTIVITY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `FOLLOWUP_DATE` datetime DEFAULT NULL,
  `DESCRIPTION` varchar(2000) DEFAULT NULL,
  `RESTRICTED` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`NEGOTIATION_ACTIVITY_ID`),
  KEY `NEGOTIATION_ACTIVITY_FK1` (`ACTIVITY_TYPE_CODE`),
  KEY `NEGOTIATION_ACTIVITY_FK2` (`NEGOTIATION_LOCATION_ID`),
  KEY `NEGOTIATION_ACTIVITY_FK3` (`NEGOTIATION_ID`),
  KEY `NEGOTIATION_ACTIVITY_FK4` (`LOCATION_TYPE_CODE`),
  CONSTRAINT `NEGOTIATION_ACTIVITY_FK1` FOREIGN KEY (`ACTIVITY_TYPE_CODE`) REFERENCES `negotiation_activity_type` (`ACTIVITY_TYPE_CODE`),
  CONSTRAINT `NEGOTIATION_ACTIVITY_FK2` FOREIGN KEY (`NEGOTIATION_LOCATION_ID`) REFERENCES `negotiation_location` (`NEGOTIATION_LOCATION_ID`),
  CONSTRAINT `NEGOTIATION_ACTIVITY_FK3` FOREIGN KEY (`NEGOTIATION_ID`) REFERENCES `negotiation` (`NEGOTIATION_ID`),
  CONSTRAINT `NEGOTIATION_ACTIVITY_FK4` FOREIGN KEY (`LOCATION_TYPE_CODE`) REFERENCES `negotiation_location_type` (`LOCATION_TYPE_CODE`)
) ;
