DROP TABLE IF EXISTS `negotiation_personnel`;

CREATE TABLE `negotiation_personnel` (
  `NEGOTIATION_PERSONNEL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NEGOTIATION_ID` int(11) DEFAULT NULL,
  `PERSONNEL_TYPE_CODE` varchar(3) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `FULL_NAME` varchar(90) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `ROLODEX_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`NEGOTIATION_PERSONNEL_ID`),
  KEY `NEGOTIATION_PERSONNEL_FK1` (`PERSONNEL_TYPE_CODE`),
  KEY `NEGOTIATION_PERSONNEL_FK2` (`NEGOTIATION_ID`),
  CONSTRAINT `NEGOTIATION_PERSONNEL_FK1` FOREIGN KEY (`PERSONNEL_TYPE_CODE`) REFERENCES `negotiation_personnel_type` (`PERSONNEL_TYPE_CODE`),
  CONSTRAINT `NEGOTIATION_PERSONNEL_FK2` FOREIGN KEY (`NEGOTIATION_ID`) REFERENCES `negotiation` (`NEGOTIATION_ID`)
) ;
