DROP TABLE IF EXISTS `right_section_mapping`;

CREATE TABLE `right_section_mapping` (
  `RIGHT_ID` int(11) NOT NULL,
  `SECTION_CODE` varchar(3) NOT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`RIGHT_ID`,`SECTION_CODE`),
  KEY `RIGHT_SECTION_MAPPING_FK2` (`SECTION_CODE`),
  CONSTRAINT `RIGHT_SECTION_MAPPING_FK1` FOREIGN KEY (`RIGHT_ID`) REFERENCES `rights` (`RIGHT_ID`),
  CONSTRAINT `RIGHT_SECTION_MAPPING_FK2` FOREIGN KEY (`SECTION_CODE`) REFERENCES `agreement_section_type` (`SECTION_CODE`)
);

