DROP TABLE IF EXISTS `triage_template_mapping`;

CREATE TABLE `triage_template_mapping` (
  `TRIAGE_TEMPLATE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `SUB_MODULE_CODE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`TRIAGE_TEMPLATE_ID`)
) ;
