

--
--  `claim_summary`
--

DROP TABLE IF EXISTS `claim_summary`;

CREATE TABLE `claim_summary` (
  `CLAIM_SUMMARY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AMOUNT_FORCASTED` decimal(19,2) DEFAULT NULL,
  `AMOUNT_REQUESTED` decimal(19,2) DEFAULT NULL,
  `BUDGET_CATEGORY_CODE` varchar(255) DEFAULT NULL,
  `BUDGET_HEADER_ID` int(11) DEFAULT NULL,
  `CLAIM_ID` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `TOTAL_AMOUNT` decimal(19,2) DEFAULT NULL,
  `AMOUNT_REQ_CURRENT_CLAIM` decimal(15,2) DEFAULT NULL,
  `CUM_CLAIM_AMOUNT_UPTO_CLAIM` decimal(15,2) DEFAULT NULL,
  `CUM_EXPENSE_UPTO_PREV_CLAIM` decimal(15,2) DEFAULT NULL,
  `COMMITMENTS_UPTO_PREV_CLAIM` decimal(15,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `LATEST_APPROVED_BUDGET` decimal(19,2) DEFAULT NULL,
  `ORIGINAL_APPROVED_BUDGET` decimal(19,2) DEFAULT NULL,
  `PREV_CLAIM_TOTAL_AMOUNT` decimal(19,2) DEFAULT NULL,
  `CLAIM_NUMBER` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`CLAIM_SUMMARY_ID`),
  KEY `CLAIM_SUMMARY_FK3` (`BUDGET_CATEGORY_CODE`),
  KEY `CLAIM_SUMMARY_FK1` (`CLAIM_ID`),
  CONSTRAINT `CLAIM_SUMMARY_FK1` FOREIGN KEY (`CLAIM_ID`) REFERENCES `claim` (`CLAIM_ID`),
  CONSTRAINT `CLAIM_SUMMARY_FK3` FOREIGN KEY (`BUDGET_CATEGORY_CODE`) REFERENCES `budget_category` (`BUDGET_CATEGORY_CODE`)
);

