-- `FN_GET_DATE_DIFFERENCE`; 

CREATE FUNCTION `FN_GET_DATE_DIFFERENCE`(
AV_NEGOTIATION_ID  DECIMAL(20,0),
AV_NEGO_LOCATION_ID  DECIMAL(20,0)
) RETURNS varchar(200) 
    DETERMINISTIC
BEGIN
DECLARE LO_DATE1   DATE;
DECLARE LO_DATE2            DATE;
DECLARE LS_DIFFERENCE       VARCHAR(50);
DECLARE LI_NEXT_LOCATION_ID DECIMAL(10,0);
    SELECT DATE(UPDATE_TIMESTAMP)  
    INTO LO_DATE1 FROM NEGOTIATION_LOCATION
    WHERE NEGOTIATION_LOCATION_ID = AV_NEGO_LOCATION_ID;
    SELECT MIN(NEGOTIATION_LOCATION_ID) 
    INTO LI_NEXT_LOCATION_ID
    FROM NEGOTIATION_LOCATION
    WHERE NEGOTIATION_ID = AV_NEGOTIATION_ID 
    AND NEGOTIATION_LOCATION_ID > AV_NEGO_LOCATION_ID;
    IF LI_NEXT_LOCATION_ID IS NOT NULL THEN
        SELECT DATE(UPDATE_TIMESTAMP)  
        INTO LO_DATE2 FROM NEGOTIATION_LOCATION
        WHERE NEGOTIATION_LOCATION_ID = LI_NEXT_LOCATION_ID;
    ELSE
        SELECT DATE(NOW()) 
        INTO LO_DATE2
        FROM DUAL;
    END IF;
    SELECT  DATEDIFF(LO_DATE2,LO_DATE1) AS DATEDIFF 
    INTO LS_DIFFERENCE
    FROM DUAL;
    RETURN LS_DIFFERENCE;
END
