-- `FN_CHK_CLAIM_INVOICE_GRT`; 

CREATE FUNCTION `FN_CHK_CLAIM_INVOICE_GRT`(
AV_CLAIM_ID    DECIMAL(22)
) RETURNS varchar(6) 
    DETERMINISTIC
BEGIN
      	
        DECLARE LI_COUNT INT;
		DECLARE LI_CLAIM_AMOUNT DECIMAL(15,2);
		DECLARE LS_AWARD_TYPE_CODE VARCHAR(3);
		
		select AWARD_TYPE_CODE into LS_AWARD_TYPE_CODE FROM AWARD WHERE AWARD_ID = (SELECT AWARD_ID FROM CLAIM WHERE CLAIM_ID = AV_CLAIM_ID);
		
		IF LS_AWARD_TYPE_CODE = 1 THEN
			SELECT COUNT(1) INTO LI_COUNT FROM CLAIM_INVOICE T1
			INNER JOIN CLAIM_INVOICE_DETAILS T2 ON T1.INVOICE_ID = T2.INVOICE_ID
			WHERE SUBSTRING(T2.GRT_WBS,1,15) IN (SELECT ACCOUNT_NUMBER  FROM CLAIM WHERE CLAIM_ID = AV_CLAIM_ID) AND T1.CLAIM_ID = AV_CLAIM_ID;
			IF LI_COUNT > 0 THEN
				RETURN 'FALSE';
			END IF;	
		END IF;
		RETURN 'TRUE';
END
