-- `FN_CHK_INVOICE_CUSTOMER_NUMBER`; 

CREATE FUNCTION `FN_CHK_INVOICE_CUSTOMER_NUMBER`(AV_CLAIM_ID INT(11)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
DECLARE LS_CUSTOMER_NUMBER  VARCHAR(10);
	SELECT 
		CUSTOMER_NUMBER 
	INTO LS_CUSTOMER_NUMBER FROM
		CLAIM_INVOICE 
	WHERE
		INVOICE_ID = (SELECT MAX(INVOICE_ID) FROM CLAIM_INVOICE WHERE CLAIM_ID = AV_CLAIM_ID);
	IF LS_CUSTOMER_NUMBER IS NULL THEN
		RETURN 'TRUE';
	ELSE
		RETURN 'FALSE';
	END IF;
END
