CREATE PROCEDURE `GET_PERSON_TRAINING_LATESTDATE`(
    AV_PERSON_ID VARCHAR(40),
    AV_PROPOSAL_ID INT(11)
)
BEGIN
    
    DECLARE LS_EFFORT_MAX_DATE_ACKNOWLEDGED VARCHAR(20);
    DECLARE LS_COI_MAX_DATE_ACKNOWLEDGED VARCHAR(20);

    -- Get the maximum DATE_ACKNOWLEDGED for training codes '350102', '212113', and '2434084'
    SELECT MAX(T1.DATE_ACKNOWLEDGED) INTO LS_EFFORT_MAX_DATE_ACKNOWLEDGED
    FROM PERSON_TRAINING T1
    INNER JOIN MYLEARNING_TRAINING_CODE T2 ON (T1.TRAINING_CODE = T2.COEUS_TRAINING_CODE) 
    WHERE T1.PERSON_ID = AV_PERSON_ID
    AND T2.MYLEARNING_TRAINING_CODE IN ('350102', '212113', '2434084');

    -- Get the maximum DATE_ACKNOWLEDGED for training code '412863'
    SELECT MAX(T1.DATE_ACKNOWLEDGED) INTO LS_COI_MAX_DATE_ACKNOWLEDGED
    FROM PERSON_TRAINING T1
    JOIN MYLEARNING_TRAINING_CODE T2 ON (T1.TRAINING_CODE = T2.COEUS_TRAINING_CODE) 
    WHERE T1.PERSON_ID = AV_PERSON_ID
    AND T2.MYLEARNING_TRAINING_CODE IN ('412863');

	SELECT LS_EFFORT_MAX_DATE_ACKNOWLEDGED, LS_COI_MAX_DATE_ACKNOWLEDGED;
END
