-- `GET_WORKFLOW_LOG`; 

CREATE PROCEDURE `GET_WORKFLOW_LOG`(
AV_MODULE_ITEM_ID VARCHAR(200),
AV_MODULE_CODE    int(3)
)
    DETERMINISTIC
BEGIN
SELECT DISTINCT T2.WORKFLOW_DETAIL_ID,
		T2.MAP_ID,
		T5.DESCRIPTION AS WORKFLOWMAP_DESCRIPTION,
		T2.MAP_NUMBER,
		T2.APPROVAL_STOP_NUMBER,
		T2.APPROVER_NUMBER,
		T2.PRIMARY_APPROVER_FLAG,
		T2.APPROVER_PERSON_ID,
		T2.APPROVER_PERSON_NAME,
		T2.APPROVAL_STATUS,
		T6.DESCRIPTION,
		T2.APPROVAL_COMMENT,
		DATE_FORMAT(T2.APPROVAL_DATE,'%m-%d-%Y %h:%i %p') AS APPROVAL_DATE,
		T2.UPDATE_USER,
		DATE_FORMAT(T2.UPDATE_TIMESTAMP,'%m-%d-%Y %h:%i %p') AS UPDATE_TIMESTAMP,
		T2.ROLE_TYPE_CODE, 
		T8.DESCRIPTION AS ROLE_TYPE_DESCRIPTION,
        T2.EMAIL_ADDRESS,
        T5.MAP_NAME,
        T9.STOP_NAME
FROM WORKFLOW T1
INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
INNER JOIN WORKFLOW_MAP T5 ON T2.MAP_ID = T5.MAP_ID
INNER JOIN WORKFLOW_MAP_DETAIL T9 ON T9.MAP_ID = T2.MAP_ID  AND T9.APPROVAL_STOP_NUMBER = T2.APPROVAL_STOP_NUMBER
INNER JOIN WORKFLOW_STATUS T6 ON T2.APPROVAL_STATUS = T6.APPROVAL_STATUS
LEFT OUTER JOIN UNIT T7 ON T2.UNIT_NUMBER = T7.UNIT_NUMBER
LEFT OUTER JOIN PERSON_ROLE_TYPE T8 on T8.ROLE_TYPE_CODE = T2.ROLE_TYPE_CODE
WHERE T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
AND T1.MODULE_CODE = AV_MODULE_CODE
AND T1.IS_WORKFLOW_ACTIVE = 'Y'
ORDER BY T2.MAP_NUMBER,T2.APPROVAL_STOP_NUMBER,T2.APPROVER_NUMBER,T2.PRIMARY_APPROVER_FLAG DESC;
END
