-- `GRANT_PI_PERMISSION`; 

CREATE PROCEDURE `GRANT_PI_PERMISSION`(
)
BEGIN
DECLARE LS_PERSON_ID 	VARCHAR(40);
DECLARE LS_HOME_UNIT	VARCHAR(8);
DECLARE LI_FLAG			INT;
DECLARE  LI_PERSON_ROLES_ID	INT;
	BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE CUR_SEL_DATA CURSOR FOR 
		SELECT PERSON_ID,HOME_UNIT FROM PERSON WHERE IS_FACULTY = 'Y';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;	
		OPEN CUR_SEL_DATA;
		INSERT_LOOP: LOOP 
		FETCH CUR_SEL_DATA INTO
		LS_PERSON_ID,
		LS_HOME_UNIT;
		IF DONE1 THEN
			LEAVE INSERT_LOOP;
		END IF;
		SELECT COUNT(1) INTO LI_FLAG
		FROM PERSON_ROLES
		WHERE PERSON_ID = LS_PERSON_ID
		AND ROLE_ID = 618;
		IF LI_FLAG = 0 THEN
			SELECT IFNULL(MAX(PERSON_ROLES_ID),0)+1 INTO LI_PERSON_ROLES_ID FROM PERSON_ROLES;
			INSERT INTO PERSON_ROLES
			(
			PERSON_ROLES_ID, 
			PERSON_ID, 
			ROLE_ID, 
			UNIT_NUMBER, 
			DESCEND_FLAG, 
			UPDATE_TIMESTAMP, 
			UPDATE_USER
			)
			VALUES
			(
			LI_PERSON_ROLES_ID,
			LS_PERSON_ID,
			618,
			LS_HOME_UNIT,
			'Y',
			NOW(),
			'admin'
			);	
		END IF;
		END LOOP;
		CLOSE CUR_SEL_DATA;
	END;
END
