CREATE PROCEDURE `INSERT_WORKFLOW_ALTER_APPROVER`(
AV_WORKFLOW_ID            int(6),
AV_MAP_ID                 int(6),
AV_MAP_NUMBER             int(3),
AV_APPROVAL_STOP_NUMBER    int(3) ,
AV_APPROVER_NUMBER         int(3),
AV_APPROVER_PERSON_ID      varchar(40),
AV_UPDATE_USER             varchar(60),
AV_PRIMARY_APPROVER_FLAG   varchar(1),
AV_MAP_NAME varchar(200),
AV_MAP_DESCRIPTION varchar(200),
AV_STOP_NAME varchar(200),
AV_NOTE varchar(2000)
)
BEGIN


DECLARE LS_WORKFLOW_DETAIL_ID INT(12);
DECLARE LS_APPROVER_PERSON_NAME VARCHAR(60);
DECLARE LS_EMAIL_ADDRESS VARCHAR(600);
DECLARE LS_MODULE_CODE INT;
DECLARE LS_MODULE_ITEM_ID VARCHAR(20);
DECLARE LS_AWARD_NUMBER VARCHAR(12);
DECLARE LS_TITLE VARCHAR(1000);
DECLARE LS_MODULE_ITEM_KEY VARCHAR(20);
DECLARE LS_MSG_TYPE varchar(4);
DECLARE LS_USER_MESSAGE varchar(4000);
DECLARE LI_SUB_MODULE_CODE  INT;
DECLARE LS_SUB_MODULE_ITEM_ID VARCHAR(20) ;
DECLARE LS_DOCUMENT_TYPE_CODE VARCHAR(3);
DECLARE LS_SERVICE_REQUEST_TYPE VARCHAR(200);
DECLARE LI_AWD_MODIFI_FLAG INT;
DECLARE LI_VARIATION_FLAG INT;
DECLARE LS_AWARD_TITLE VARCHAR(1000);
DECLARE LI_COUNT INT;
DECLARE LI_DELEGATED INT;
DECLARE LS_MAP_TYPE VARCHAR(1);
DECLARE LS_CLAIM_NUMBER VARCHAR(20);
DECLARE LS_PROGRESS_REPORT_NUMBER VARCHAR(20);
DECLARE LS_REPORT_CLASS_NAME VARCHAR(200);
DECLARE LS_AGREEMENT_TYPE VARCHAR(200);
DECLARE LS_DELEGATE_APPROVER_PERSON_ID VARCHAR(40);
DECLARE LS_REPORT_TITLE VARCHAR(1000);
DECLARE LS_APPROVAL_STATUS VARCHAR(40);

EXIT_LABEL : BEGIN
                       

SELECT FULL_NAME,EMAIL_ADDRESS INTO LS_APPROVER_PERSON_NAME,LS_EMAIL_ADDRESS FROM PERSON WHERE PERSON_ID = AV_APPROVER_PERSON_ID;

SELECT MODULE_CODE,MODULE_ITEM_ID,SUB_MODULE_CODE,SUB_MODULE_ITEM_ID,MAP_TYPE  INTO LS_MODULE_CODE,LS_MODULE_ITEM_ID,LI_SUB_MODULE_CODE,LS_SUB_MODULE_ITEM_ID,LS_MAP_TYPE
FROM WORKFLOW WHERE WORKFLOW_ID = AV_WORKFLOW_ID;

-- for setting current workflow status into local variable and use it for cehcking approval status
SELECT 
    CASE 
        WHEN COUNT(*) > 0 THEN 'W'
        ELSE 'T'
    END 
INTO LS_APPROVAL_STATUS
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID 
  AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER 
  AND MAP_ID = AV_MAP_ID 
  AND MAP_NUMBER = AV_MAP_NUMBER
  AND APPROVAL_STATUS = 'W';

SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND APPROVAL_STATUS  IN('W','T');

IF LI_COUNT = 0 THEN

	SET LS_WORKFLOW_DETAIL_ID = 0;
	LEAVE EXIT_LABEL;
	
END IF;

SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND MAP_ID = AV_MAP_ID
AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
AND APPROVER_PERSON_ID = AV_APPROVER_PERSON_ID;

IF LI_COUNT > 0 THEN

	SET LS_WORKFLOW_DETAIL_ID = 0;
	LEAVE EXIT_LABEL;
	
END IF;

SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND APPROVAL_STATUS  IN('R','J');

IF LI_COUNT > 0 THEN

	SET LS_WORKFLOW_DETAIL_ID = 0;
	LEAVE EXIT_LABEL;
	
END IF;

SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
AND PRIMARY_APPROVER_FLAG = 'Y'
AND APPROVER_PERSON_ID = AV_APPROVER_PERSON_ID
AND MAP_ID = AV_MAP_ID
AND MAP_NUMBER = AV_MAP_NUMBER;

IF LI_COUNT > 0 THEN

	SET LS_WORKFLOW_DETAIL_ID = 0;
	LEAVE EXIT_LABEL;
	
END IF;


SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
AND APPROVER_NUMBER = AV_APPROVER_NUMBER
AND APPROVER_PERSON_ID = AV_APPROVER_PERSON_ID
AND MAP_ID = AV_MAP_ID
AND MAP_NUMBER = AV_MAP_NUMBER;

IF LI_COUNT > 0 THEN

	SET LS_WORKFLOW_DETAIL_ID = 0;
	LEAVE EXIT_LABEL;
	
END IF;

SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
AND APPROVER_NUMBER = AV_APPROVER_NUMBER
AND PRIMARY_APPROVER_FLAG = 'Y'
AND APPROVAL_STATUS IN('B','A','R')
AND MAP_ID = AV_MAP_ID
AND MAP_NUMBER = AV_MAP_NUMBER;

IF LI_COUNT > 0 THEN

	SET LS_WORKFLOW_DETAIL_ID = 0;
	LEAVE EXIT_LABEL;
	
END IF;

SELECT COUNT(*) INTO LI_COUNT 
FROM WORKFLOW_DETAIL 
WHERE WORKFLOW_ID = AV_WORKFLOW_ID
AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
AND MAP_ID = AV_MAP_ID
AND MAP_NUMBER = AV_MAP_NUMBER;

IF LI_COUNT > 0 THEN

	SELECT COUNT(*) INTO LI_COUNT 
	FROM WORKFLOW_DETAIL 
	WHERE WORKFLOW_ID = AV_WORKFLOW_ID
	AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
	AND APPROVAL_STATUS IN('W','T')
	AND MAP_ID = AV_MAP_ID
	AND MAP_NUMBER = AV_MAP_NUMBER;

	IF LI_COUNT = 0 THEN

		SET LS_WORKFLOW_DETAIL_ID = 0;
		LEAVE EXIT_LABEL;
		
	END IF;
	
END IF;

IF LS_APPROVAL_STATUS = 'T' THEN

	SELECT COUNT(*) INTO LI_COUNT 
	FROM WORKFLOW_DETAIL 
	WHERE WORKFLOW_ID = AV_WORKFLOW_ID
	AND APPROVAL_STOP_NUMBER = AV_APPROVAL_STOP_NUMBER
	AND APPROVER_NUMBER = AV_APPROVER_NUMBER
	AND PRIMARY_APPROVER_FLAG = 'Y'
	AND APPROVAL_STATUS = 'W'
	AND MAP_ID = AV_MAP_ID
	AND MAP_NUMBER = AV_MAP_NUMBER;
	
	
	IF LI_COUNT > 0 THEN

		SET LS_WORKFLOW_DETAIL_ID = 0;
		LEAVE EXIT_LABEL;
	
	END IF;

END IF;


	INSERT INTO WORKFLOW_DETAIL(
	WORKFLOW_ID,
	MAP_ID,
	MAP_NUMBER,
	APPROVAL_STOP_NUMBER,
	APPROVER_NUMBER,
	PRIMARY_APPROVER_FLAG,
	APPROVER_PERSON_ID,
	APPROVER_PERSON_NAME,
	APPROVAL_STATUS,
	APPROVAL_COMMENT,
	APPROVAL_DATE,
	UPDATE_USER,
	UPDATE_TIMESTAMP,
	UNIT_NUMBER,
	ROLE_TYPE_CODE,
	EMAIL_ADDRESS,
    MAP_NAME,
    MAP_DESCRIPTION,
	STOP_NAME,
	CREATE_USER,
	CREATE_TIMESTAMP,
	NOTE)
	VALUES(
	AV_WORKFLOW_ID,
	AV_MAP_ID,
	AV_MAP_NUMBER,
	AV_APPROVAL_STOP_NUMBER,
	AV_APPROVER_NUMBER,
	AV_PRIMARY_APPROVER_FLAG,
	AV_APPROVER_PERSON_ID,
	LS_APPROVER_PERSON_NAME,
	LS_APPROVAL_STATUS,
	NULL,
	NULL,
	AV_UPDATE_USER,
	utc_timestamp(),
	NULL,
	NULL,
	LS_EMAIL_ADDRESS,
    AV_MAP_NAME,
    AV_MAP_DESCRIPTION,
    AV_STOP_NAME,
	AV_UPDATE_USER,
	utc_timestamp(),
	AV_NOTE
	);

	SELECT LAST_INSERT_ID() INTO LS_WORKFLOW_DETAIL_ID;

	IF LS_APPROVAL_STATUS = 'W' THEN

				SET LI_DELEGATED = FN_WORKFLOW_HANDLE_DELEGATIONS(AV_WORKFLOW_ID, AV_MAP_NUMBER, AV_APPROVAL_STOP_NUMBER, LS_APPROVAL_STATUS, (SELECT PERSON_ID FROM PERSON WHERE USER_NAME = AV_UPDATE_USER),AV_UPDATE_USER);

				SELECT MODULE_CODE,MODULE_ITEM_ID  INTO LS_MODULE_CODE,LS_MODULE_ITEM_ID
				FROM WORKFLOW WHERE WORKFLOW_ID = AV_WORKFLOW_ID;

				IF LS_MODULE_CODE = 1 AND LI_SUB_MODULE_CODE = 0 THEN
						SELECT TITLE,AWARD_NUMBER,AWARD_DOCUMENT_TYPE_CODE INTO LS_TITLE,LS_AWARD_NUMBER,LS_DOCUMENT_TYPE_CODE
						FROM AWARD WHERE AWARD_ID = LS_MODULE_ITEM_ID;
						IF LS_DOCUMENT_TYPE_CODE <> '3' THEN
							SET LS_MSG_TYPE := '101';
							ELSE 
							SET LS_MSG_TYPE := '122';
						END IF;
			
				ELSEIF LS_MODULE_CODE = 1 AND LI_SUB_MODULE_CODE = 2 THEN 
					SELECT T2.DESCRIPTION, T3.AWARD_DOCUMENT_TYPE_CODE INTO LS_TITLE,LS_DOCUMENT_TYPE_CODE
					FROM TASK T1 LEFT JOIN TASK_TYPE T2 ON T1.TASK_TYPE_CODE = T2.TASK_TYPE_CODE 
					INNER JOIN AWARD T3 ON T3.AWARD_ID = T1.MODULE_ITEM_ID
					WHERE T1.TASK_ID = LS_SUB_MODULE_ITEM_ID AND T1.MODULE_CODE = 1;
					
					SELECT AWARD_NUMBER,TITLE INTO LS_AWARD_NUMBER,LS_AWARD_TITLE
					FROM AWARD WHERE AWARD_ID = LS_MODULE_ITEM_ID;
					
					SET LS_MSG_TYPE := '114';

				ELSEIF LS_MODULE_CODE = 3 THEN
						SELECT TITLE INTO LS_TITLE FROM EPS_PROPOSAL WHERE PROPOSAL_ID = LS_MODULE_ITEM_ID;
						IF LS_MAP_TYPE = 'E' THEN
							SET LS_MSG_TYPE := '125';
						ELSE
							SET LS_MSG_TYPE := '102';
						END IF;
				ELSEIF LS_MODULE_CODE = 5 THEN
						SELECT T1.TITLE INTO LS_TITLE 
						FROM  NEGOTIATION T1 
						WHERE T1.NEGOTIATION_ID = LS_MODULE_ITEM_ID ;
						SET LS_MSG_TYPE := '104';
						
				ELSEIF LS_MODULE_CODE = 13 THEN
					
                        SELECT T1.TITLE INTO LS_TITLE 
						FROM  AGREEMENT_HEADER T1 
						WHERE T1.AGREEMENT_REQUEST_ID = LS_MODULE_ITEM_ID ;
						SET LS_MSG_TYPE := '1308';
				ELSEIF LS_MODULE_CODE = 14 THEN
						SELECT T1.TITLE INTO LS_TITLE 
						FROM  CLAIM T1 
						WHERE T1.CLAIM_ID = LS_MODULE_ITEM_ID ;
						SET LS_MSG_TYPE := '123';
                ELSEIF LS_MODULE_CODE = 16 THEN
						SELECT TITLE INTO LS_TITLE FROM AWARD WHERE AWARD_ID IN(SELECT AWARD_ID 
										FROM AWARD_PROGRESS_REPORT 
										WHERE PROGRESS_REPORT_ID = LS_MODULE_ITEM_ID); 
						SET LS_MSG_TYPE := '126';
				ELSEIF LS_MODULE_CODE = 20 THEN
						SELECT T1.SUBJECT INTO LS_TITLE 
						FROM  SR_HEADER T1 
						WHERE T1.SR_HEADER_ID = LS_MODULE_ITEM_ID ;
						SET LS_MSG_TYPE := '135';
				END IF;

				IF LS_MODULE_CODE = 1 THEN
					SET  LS_MODULE_ITEM_KEY = LS_AWARD_NUMBER;
				ELSE
					SET LS_MODULE_ITEM_KEY = LS_MODULE_ITEM_ID;
				END IF;

				IF LS_MODULE_CODE = 14 THEN 
        
					SELECT CLAIM_NUMBER INTO LS_CLAIM_NUMBER FROM CLAIM WHERE CLAIM_ID = LS_MODULE_ITEM_ID;
					SET  LS_MODULE_ITEM_KEY = LS_CLAIM_NUMBER;  
				END IF; 
                IF LS_MODULE_CODE = 16 THEN 
        
					SELECT PROGRESS_REPORT_NUMBER INTO LS_PROGRESS_REPORT_NUMBER FROM AWARD_PROGRESS_REPORT WHERE PROGRESS_REPORT_ID = LS_MODULE_ITEM_ID;
					SET  LS_MODULE_ITEM_KEY = LS_PROGRESS_REPORT_NUMBER;  
				END IF; 
				
				-- SET LS_USER_MESSAGE = CONCAT('#',LS_MODULE_ITEM_KEY,' - ',LS_TITLE);
	-- -----------------------STARTS MODIFICATION ON 07-MAY-2020-------------------------
		
		SELECT COUNT(1) INTO LI_VARIATION_FLAG FROM AWARD
		WHERE AWARD_ID = LS_MODULE_ITEM_ID
		AND AWARD_DOCUMENT_TYPE_CODE = 3;
		
		SELECT COUNT(1) INTO LI_AWD_MODIFI_FLAG FROM AWARD
		WHERE AWARD_ID = LS_MODULE_ITEM_ID
		AND AWARD_DOCUMENT_TYPE_CODE = 2;

		-- --------------------------change on 18/09/2020-------------

			IF LS_MODULE_CODE = 1 THEN
		
			SELECT T2.DESCRIPTION INTO LS_SERVICE_REQUEST_TYPE FROM SR_HEADER T1
			INNER JOIN SR_TYPE T2 ON T1.TYPE_CODE = T2.TYPE_CODE
			where T1.ORIGINATING_MODULE_ITEM_KEY = LS_MODULE_ITEM_ID
			AND T1.ORIGINATING_MODULE_CODE = 1;
		
		    END IF;
			-- --------------------------change on 18/09/2020-------------
		
		-- IF LS_MODULE_CODE = 1 AND LI_SUB_MODULE_CODE = 0 THEN -- AWARD
		IF LS_MODULE_CODE = 1 AND LI_SUB_MODULE_CODE = 0 AND LI_VARIATION_FLAG > 0 THEN -- AWARD VARIATION
		
			SET LS_USER_MESSAGE = CONCAT(LS_SERVICE_REQUEST_TYPE,' for #',LS_MODULE_ITEM_KEY,' : ',LS_TITLE);
				
		ELSEIF LS_MODULE_CODE = 1 AND LI_SUB_MODULE_CODE = 0 AND LI_AWD_MODIFI_FLAG > 0 THEN -- AWARD MODIFICATION
		
		  SET LS_USER_MESSAGE = CONCAT('Admin Correction for ',LS_MODULE_ITEM_KEY,' : ',LS_TITLE);

		ELSEIF LS_MODULE_CODE = 1 AND LI_SUB_MODULE_CODE = 2 THEN -- AWARD TASK
		
			IF LI_VARIATION_FLAG > 0 THEN
				SET LS_USER_MESSAGE = CONCAT(LS_SERVICE_REQUEST_TYPE,' ',LS_TITLE,' for #',LS_MODULE_ITEM_KEY,' : ',LS_AWARD_TITLE);
			ELSEIF LI_AWD_MODIFI_FLAG > 0 THEN
				SET LS_USER_MESSAGE = CONCAT('Admin Correction ',LS_TITLE,' for #',LS_MODULE_ITEM_KEY,' : ',LS_AWARD_TITLE);
			ELSE
				SET LS_USER_MESSAGE = CONCAT(LS_TITLE,' for #',LS_MODULE_ITEM_KEY,' : ',LS_AWARD_TITLE);
			END IF;
		ELSEIF LS_MODULE_CODE = 13 THEN
		
		   SELECT T2.DESCRIPTION INTO LS_AGREEMENT_TYPE FROM  AGREEMENT_HEADER T1
			INNER JOIN AGREEMENT_TYPE T2  ON T2.AGREEMENT_TYPE_CODE = T1.AGREEMENT_TYPE_CODE
			WHERE AGREEMENT_REQUEST_ID = LS_MODULE_ITEM_ID;
           SET LS_USER_MESSAGE := CONCAT('#',LS_MODULE_ITEM_KEY, ':',LS_TITLE,' - ', LS_AGREEMENT_TYPE);	

		ELSEIF LS_MODULE_CODE = 16 THEN -- PROGRESS REPORT
			select T1.TITLE,T2.DESCRIPTION into LS_REPORT_TITLE,LS_REPORT_CLASS_NAME from award_progress_report T1 LEFT JOIN REPORT_CLASS T2 
			ON T1.REPORT_CLASS_CODE = T2.REPORT_CLASS_CODE where T1.PROGRESS_REPORT_ID =  LS_MODULE_ITEM_ID;			
			SET LS_USER_MESSAGE = CONCAT(LS_REPORT_CLASS_NAME,' #',LS_PROGRESS_REPORT_NUMBER," : ",LS_REPORT_TITLE);

			ELSE 
				SET LS_USER_MESSAGE = CONCAT('#',LS_MODULE_ITEM_KEY,' : ',LS_TITLE);
		END IF;
		
		-- -----------------------ENDS MODIFICATION ON 07-MAY-2020---------------------------

		CALL ADD_TO_INBOX(LS_MODULE_CODE,LS_MODULE_ITEM_ID,AV_APPROVER_PERSON_ID,'R',LS_USER_MESSAGE,AV_UPDATE_USER,LS_MSG_TYPE,LI_SUB_MODULE_CODE,LS_SUB_MODULE_ITEM_ID);
		
		SELECT APPROVER_PERSON_ID INTO LS_DELEGATE_APPROVER_PERSON_ID FROM WORKFLOW_DETAIL WHERE WORKFLOW_ID = AV_WORKFLOW_ID AND APPROVAL_STATUS = 'W' 
			AND DELEGATED_BY_PERSON_ID = AV_APPROVER_PERSON_ID;
		
		IF LS_DELEGATE_APPROVER_PERSON_ID IS NOT null THEN
			CALL ADD_TO_INBOX(LS_MODULE_CODE,LS_MODULE_ITEM_ID,LS_DELEGATE_APPROVER_PERSON_ID,'R',LS_USER_MESSAGE,AV_UPDATE_USER,LS_MSG_TYPE,LI_SUB_MODULE_CODE,LS_SUB_MODULE_ITEM_ID);
		END IF;
	END IF;
	COMMIT;
END;

SELECT LS_WORKFLOW_DETAIL_ID as WORKFLOW_DETAIL_ID;
END
