-- `IS_FINAL_APPROVAL`; 

CREATE PROCEDURE `IS_FINAL_APPROVAL`(
AV_MODULE_ITEM_ID  VARCHAR(200),
AV_PERSON_ID        VARCHAR(200),
AV_MODULE_CODE    INT(3),
AV_SUBMODULE_CODE        DECIMAL(3,0),
AV_SUB_MODULE_ITEM_KEY    VARCHAR(20)
)
    DETERMINISTIC
BEGIN
DECLARE LI_CAN_APPROVE                  INT;
DECLARE LI_IS_IN_MULTI_STOP             INT;
DECLARE LI_COUNT                INT;
DECLARE LI_APPROVE_FLAG         INT;
DECLARE LI_CURRENT_STOP_NUMBER  INT;
DECLARE LI_APPROVER_NUMBER          INT;
SET LI_CAN_APPROVE =0;
SET LI_IS_IN_MULTI_STOP =0;
SET LI_COUNT =0;
SET LI_APPROVE_FLAG =0;
SET LI_CURRENT_STOP_NUMBER =0;
SET LI_APPROVER_NUMBER =0;
SELECT COUNT(T1.WORKFLOW_ID) INTO LI_COUNT
FROM WORKFLOW T1
INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
WHERE T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
AND T1.MODULE_CODE  = AV_MODULE_CODE
AND IFNULL(T1.SUB_MODULE_CODE,0) = IFNULL(AV_SUBMODULE_CODE,0)
AND IFNULL(T1.SUB_MODULE_ITEM_ID,0) = IFNULL(AV_SUB_MODULE_ITEM_KEY,0)
AND T1.IS_WORKFLOW_ACTIVE = 'Y'
AND T2.APPROVAL_STATUS = 'T';
IF LI_COUNT > 0 THEN
        SELECT 0;
ELSE
				SELECT COUNT(T1.WORKFLOW_ID) INTO LI_COUNT
                FROM WORKFLOW T1
                INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
                WHERE T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
                AND T1.MODULE_CODE  = AV_MODULE_CODE
                AND T1.IS_WORKFLOW_ACTIVE = 'Y'
                AND IFNULL(T1.SUB_MODULE_CODE,0) = IFNULL(AV_SUBMODULE_CODE,0)
                AND IFNULL(T1.SUB_MODULE_ITEM_ID,0) = IFNULL(AV_SUB_MODULE_ITEM_KEY,0)
                AND T2.APPROVAL_STATUS = 'W'
                AND T2.APPROVER_PERSON_ID = AV_PERSON_ID;
                IF LI_COUNT > 1 THEN
                        SELECT 0;
				ELSEIF LI_COUNT IN(0,1) THEN
						SELECT COUNT(T1.WORKFLOW_ID) INTO LI_COUNT
						FROM WORKFLOW T1
						INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
						WHERE T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
						AND T1.MODULE_CODE  = AV_MODULE_CODE
						AND T1.IS_WORKFLOW_ACTIVE = 'Y'
						AND IFNULL(T1.SUB_MODULE_CODE,0) = IFNULL(AV_SUBMODULE_CODE,0)
						AND IFNULL(T1.SUB_MODULE_ITEM_ID,0) = IFNULL(AV_SUB_MODULE_ITEM_KEY,0)
						AND T2.APPROVAL_STATUS = 'W'
						AND T2.PRIMARY_APPROVER_FLAG = 'N'
						AND T2.APPROVER_PERSON_ID = AV_PERSON_ID;
						IF LI_COUNT > 0 THEN
							SELECT COUNT(T1.WORKFLOW_ID) INTO LI_COUNT
							FROM WORKFLOW T1
							INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
							WHERE T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
							AND T1.MODULE_CODE  = AV_MODULE_CODE
							AND T1.IS_WORKFLOW_ACTIVE = 'Y'
							AND IFNULL(T1.SUB_MODULE_CODE,0) = IFNULL(AV_SUBMODULE_CODE,0)
							AND IFNULL(T1.SUB_MODULE_ITEM_ID,0) = IFNULL(AV_SUB_MODULE_ITEM_KEY,0)
							AND T2.APPROVAL_STATUS = 'W'
							AND T2.PRIMARY_APPROVER_FLAG = 'Y'
							AND T2.APPROVER_PERSON_ID <> AV_PERSON_ID;
								IF LI_COUNT = 1 THEN
										SELECT 1;
								ELSE
										SELECT 0;
								END IF;
						ELSE
								SELECT COUNT(T1.WORKFLOW_ID) INTO LI_COUNT
								FROM WORKFLOW T1
								INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
								WHERE T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
								AND T1.MODULE_CODE  = AV_MODULE_CODE
								AND T1.IS_WORKFLOW_ACTIVE = 'Y'
								AND IFNULL(T1.SUB_MODULE_CODE,0) = IFNULL(AV_SUBMODULE_CODE,0)
								AND IFNULL(T1.SUB_MODULE_ITEM_ID,0) = IFNULL(AV_SUB_MODULE_ITEM_KEY,0)
								AND T2.APPROVAL_STATUS = 'W'
								AND T2.PRIMARY_APPROVER_FLAG = 'Y'
								AND T2.APPROVER_PERSON_ID <> AV_PERSON_ID;
								IF LI_COUNT > 0 THEN
										SELECT 0;
								ELSE
										SELECT 1;
								END IF;
						END IF;
                END IF;
END IF;
END
