-- `MIGRATION_PRE_VALIDATION_B`; 

CREATE PROCEDURE `MIGRATION_PRE_VALIDATION_B`()
BEGIN
DECLARE LS_CODE CHAR(5) DEFAULT '00000';
DECLARE LS_MSG TEXT;
DECLARE LS_ERROR VARCHAR(2000);
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE LI_MA_MIGRATION_AWARD_ID	INT(11);
DECLARE LI_MA_LEGACY_PROJECT_ID	VARCHAR(20);
DECLARE LS_MA_LEGACY_WBS_NUMBER	VARCHAR(100);
DECLARE LS_MA_GRANT_CODE	VARCHAR(50);
DECLARE LS_MA_AWARD_NUMBER	VARCHAR(12);
DECLARE LS_MA_ACCOUNT_NUMBER	VARCHAR(100);
DECLARE LI_MA_GRANT_HEADER_ID	INT(10);
DECLARE LS_MA_LEAD_UNIT_NUMBER	VARCHAR(8);
DECLARE LS_MA_LEAD_UNIT_NAME	VARCHAR(100);
DECLARE LS_MA_ACCOUNT_TYPE_DESC	VARCHAR(200);
DECLARE LS_MA_AWARD_TYPE_DESC	VARCHAR(200);
DECLARE LS_MA_ACTIVITY_TYPE_DESC	VARCHAR(200);
DECLARE LS_MA_TITLE	VARCHAR(2000);
DECLARE LS_MA_AWARD_STATUS_DESC	VARCHAR(200);
DECLARE LS_MA_SPONSOR_CODE	VARCHAR(6);
DECLARE LS_MA_PRIME_SPONSOR_CODE	VARCHAR(6);
DECLARE LD_MA_START_DATE	DATETIME;
DECLARE LD_MA_END_DATE	DATETIME;
DECLARE LS_MA_STEM_NON_STEM	VARCHAR(10);
DECLARE LS_MA_DISPLAY_AT_ACAD_PROFILE	VARCHAR(3);
DECLARE LI_MA_PREVIOUS_AWARD_ID	INT(11);
DECLARE LS_MA_PREVIOUS_AWARD_FREETEXT	VARCHAR(45);
DECLARE LS_MA_SUB_LEAD_UNIT_NAME	VARCHAR(100);
DECLARE LS_MA_SUB_LEAD_UNIT_CODE	VARCHAR(8);
DECLARE LS_MA_OUTPUT_GST_CATEGORY	VARCHAR(30);
DECLARE LS_MA_INPUT_GST_CATEGORY	VARCHAR(30);
DECLARE LS_MA_CLAIM_FREQUENCY	VARCHAR(200);
DECLARE LS_MA_CLAIM_PROFILE	VARCHAR(200);
DECLARE LS_MA_BILLING_TYPE	VARCHAR(200);
DECLARE LS_MA_RIE_DOMAIN	VARCHAR(200);
DECLARE LI_ME_MIGRATION_ERROR_LOG_ID INT(11);
DECLARE LI_MG_GRANT_HEADER_ID INT(11);
DECLARE LS_U_UNIT_NAME VARCHAR(8);
DECLARE LS_SUBUNIT_UNIT_NAME VARCHAR(8);
DECLARE LS_ACT_ACCOUNT_TYPE_CODE VARCHAR(3);
DECLARE LS_AT_AWARD_TYPE_CODE VARCHAR(3);
DECLARE  LS_ACTT_ACTIVITY_TYPE_CODE VARCHAR(3);
DECLARE LS_AWT_STATUS_CODE VARCHAR(3);
DECLARE LS_S_SPONSOR_NAME VARCHAR(200);
DECLARE LS_SP_SPONSOR_NAME VARCHAR(200);
DECLARE LS_ABP_BASIS_OF_PAYMENT_CODE VARCHAR(3);
DECLARE LS_AMP_METHOD_OF_PAYMENT_CODE VARCHAR(3);
DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
BEGIN
  GET DIAGNOSTICS CONDITION 1
	LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
END;
BEGIN 
		DECLARE MIGRATION_AWARD_CURSOR CURSOR FOR 
		SELECT MA.MIGRATION_AWARD_ID,
		MA.LEGACY_PROJECT_ID,
		MA.LEGACY_WBS_NUMBER,
		MA.GRANT_CODE,
		MA.AWARD_NUMBER,
		MA.ACCOUNT_NUMBER,
		MA.GRANT_HEADER_ID,
		MA.LEAD_UNIT_NUMBER,
		MA.LEAD_UNIT_NAME,
		MA.ACCOUNT_TYPE_DESCRIPTION,
		MA.AWARD_TYPE_DESCRIPTION,
		MA.ACTIVITY_TYPE_DESCRIPTION,
		MA.TITLE,
		MA.AWARD_STATUS_DESCRIPTION,
		MA.SPONSOR_CODE,
		MA.PRIME_SPONSOR_CODE,
		MA.START_DATE,
		MA.END_DATE,
		MA.STEM_NON_STEM,
		MA.DISPLAY_AT_ACAD_PROFILE,
		MA.PREVIOUS_AWARD_ID,
		MA.PREVIOUS_AWARD_FREETEXT,
		MA.SUB_LEAD_UNIT_NAME,
		MA.SUB_LEAD_UNIT_CODE,
		MA.OUTPUT_GST_CATEGORY,
		MA.INPUT_GST_CATEGORY,
		MA.CLAIM_FREQUENCY,
		MA.CLAIM_PROFILE,
		MA.BILLING_TYPE,
		MA.RIE_DOMAIN,
		MG.GRANT_HEADER_ID,
		U.UNIT_NAME,
		ACT.ACCOUNT_TYPE_CODE,
		AT.AWARD_TYPE_CODE,
		ACTT.ACTIVITY_TYPE_CODE,
		AWS.STATUS_CODE,
		S.SPONSOR_NAME,
		PS.SPONSOR_NAME,
		SUBUNIT.UNIT_NAME,
		ABP.BASIS_OF_PAYMENT_CODE,
		AMP.METHOD_OF_PAYMENT_CODE
		FROM MIGRATION_AWARD MA 
		LEFT JOIN MIGRATION_GRANT_CALL MG ON MA.GRANT_HEADER_ID = MG.GRANT_HEADER_ID
		LEFT JOIN UNIT U ON U.UNIT_NUMBER = MA.LEAD_UNIT_NUMBER
		LEFT JOIN ACCOUNT_TYPE ACT ON TRIM(ACT.DESCRIPTION) = TRIM(MA.ACCOUNT_TYPE_DESCRIPTION)
		LEFT JOIN AWARD_TYPE AT ON TRIM(AT.DESCRIPTION) = TRIM(MA.AWARD_TYPE_DESCRIPTION)
		LEFT JOIN ACTIVITY_TYPE ACTT ON TRIM(ACTT.DESCRIPTION) = TRIM(MA.ACTIVITY_TYPE_DESCRIPTION)
		LEFT JOIN AWARD_STATUS AWS ON TRIM(AWS.DESCRIPTION) = TRIM(MA.AWARD_STATUS_DESCRIPTION)
		LEFT JOIN SPONSOR S ON S.SPONSOR_CODE = MA.SPONSOR_CODE
		LEFT JOIN SPONSOR PS ON PS.SPONSOR_CODE = MA.PRIME_SPONSOR_CODE
		LEFT JOIN UNIT SUBUNIT ON SUBUNIT.UNIT_NUMBER = MA.SUB_LEAD_UNIT_CODE
		LEFT JOIN AWARD_BASIS_OF_PAYMENT ABP ON  TRIM(ABP.DESCRIPTION) = TRIM(MA.CLAIM_PROFILE)
		LEFT JOIN AWARD_METHOD_OF_PAYMENT AMP ON  TRIM(AMP.DESCRIPTION) = TRIM(MA.BILLING_TYPE);
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN MIGRATION_AWARD_CURSOR;
		MIGRATION_AWARD_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_CURSOR INTO LI_MA_MIGRATION_AWARD_ID,
												LI_MA_LEGACY_PROJECT_ID,
												LS_MA_LEGACY_WBS_NUMBER,
												LS_MA_GRANT_CODE,
												LS_MA_AWARD_NUMBER,
												LS_MA_ACCOUNT_NUMBER,
												LI_MA_GRANT_HEADER_ID,
												LS_MA_LEAD_UNIT_NUMBER,
												LS_MA_LEAD_UNIT_NAME,
												LS_MA_ACCOUNT_TYPE_DESC,
												LS_MA_AWARD_TYPE_DESC,
												LS_MA_ACTIVITY_TYPE_DESC,
												LS_MA_TITLE,
												LS_MA_AWARD_STATUS_DESC,
												LS_MA_SPONSOR_CODE,
												LS_MA_PRIME_SPONSOR_CODE,
												LD_MA_START_DATE,
												LD_MA_END_DATE,
												LS_MA_STEM_NON_STEM,
												LS_MA_DISPLAY_AT_ACAD_PROFILE,
												LI_MA_PREVIOUS_AWARD_ID,
												LS_MA_PREVIOUS_AWARD_FREETEXT,
												LS_MA_SUB_LEAD_UNIT_NAME,
												LS_MA_SUB_LEAD_UNIT_CODE,
												LS_MA_OUTPUT_GST_CATEGORY,
												LS_MA_INPUT_GST_CATEGORY,
												LS_MA_CLAIM_FREQUENCY,
												LS_MA_CLAIM_PROFILE,
												LS_MA_BILLING_TYPE,
												LS_MA_RIE_DOMAIN,
												LI_MG_GRANT_HEADER_ID,
												LS_U_UNIT_NAME,
												LS_ACT_ACCOUNT_TYPE_CODE,
												LS_AT_AWARD_TYPE_CODE,
												LS_ACTT_ACTIVITY_TYPE_CODE,
												LS_AWT_STATUS_CODE,
												LS_S_SPONSOR_NAME,
												LS_SP_SPONSOR_NAME,
												LS_SUBUNIT_UNIT_NAME,
												LS_ABP_BASIS_OF_PAYMENT_CODE,
												LS_AMP_METHOD_OF_PAYMENT_CODE;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_CURSOR_LOOP;
				END IF;
				IF LI_MG_GRANT_HEADER_ID IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Grant call validation failed -MIGRATION_AWARD#',LI_MA_GRANT_HEADER_ID),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_U_UNIT_NAME IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Unit validation failed -MIGRATION_AWARD#',LS_MA_LEAD_UNIT_NUMBER),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF 	LS_ACT_ACCOUNT_TYPE_CODE IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Account type validation failed -MIGRATION_AWARD#',LS_MA_ACCOUNT_TYPE_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_AT_AWARD_TYPE_CODE IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Award type validation failed -MIGRATION_AWARD#',LS_MA_AWARD_TYPE_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_ACTT_ACTIVITY_TYPE_CODE IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Activity type validation failed -MIGRATION_AWARD#',LS_MA_ACTIVITY_TYPE_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_AWT_STATUS_CODE IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Award status validation failed -MIGRATION_AWARD#',LS_MA_AWARD_STATUS_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_S_SPONSOR_NAME IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Sponsor validation failed -MIGRATION_AWARD#',LS_MA_SPONSOR_CODE),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_SP_SPONSOR_NAME IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Prime Sponsor validation failed -MIGRATION_AWARD#',LS_MA_PRIME_SPONSOR_CODE),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') IS NULL THEN 
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Start date format validation failed -MIGRATION_AWARD#',LD_MA_START_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
			    ELSEIF STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') IS NOT NULL AND STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') > STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Start date validation failed -MIGRATION_AWARD#',LD_MA_START_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') IS NULL THEN 
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('End date format validation failed -MIGRATION_AWARD#',LD_MA_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
			    ELSEIF STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') IS NOT NULL AND STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') > STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('End date validation failed -MIGRATION_AWARD#',LD_MA_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;
			    ELSEIF LI_MA_PREVIOUS_AWARD_ID NOT IN (SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Previous project legacy id validation failed -MIGRATION_AWARD#',LI_MA_PREVIOUS_AWARD_ID),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_SUBUNIT_UNIT_NAME IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Sub unit validation failed -MIGRATION_AWARD#',LS_MA_SUB_LEAD_UNIT_CODE),'Before Migration',NOW(),'admin');
					COMMIT;	
				ELSEIF LS_ABP_BASIS_OF_PAYMENT_CODE IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Basis of payment(claim profile) validation failed -MIGRATION_AWARD#',LS_MA_CLAIM_PROFILE),'Before Migration',NOW(),'admin');
					COMMIT;
				ELSEIF LS_AMP_METHOD_OF_PAYMENT_CODE IS NULL THEN
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_MA_LEGACY_PROJECT_ID,'Validation',CONCAT('Method of payment(Billing type) validation failed -MIGRATION_AWARD#',LS_MA_BILLING_TYPE),'Before Migration',NOW(),'admin');
					COMMIT;
				END IF;
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration',NOW(),'admin');
					COMMIT;
					SELECT 0 AS RESULT;
				END IF;	
		END LOOP;
		CLOSE MIGRATION_AWARD_CURSOR;
END;
SELECT 1  AS RESULT;
END
