CREATE PROCEDURE MIGRATE_AWARD_PI_TO_AGREEMENT(
	IN AV_SOURCE_MODULE_ID INT,
    IN AV_DESTINATION_MODULE_ID INT,
    IN AV_DESTINATION_MODULE_CODE INT,
    IN AV_SOURCE_MODULE_CODE INT,
    IN AV_UPDATED_USER VARCHAR(60)
)
BEGIN

    DECLARE LS_DONE INT DEFAULT FALSE;
    DECLARE LS_PERSON_ID VARCHAR(40);
    DECLARE LI_ROLE_ID INT;

    DECLARE AGMT_ROLE_CUR CURSOR FOR
    WITH DERIVED_ROLE AS
    (
    SELECT ROLE_ID, 3 AS ROLE_TYPE FROM MODULE_DERIVED_ROLES WHERE MODULE_CODE = '13' AND IS_ACTIVE = 'Y' AND AUTO_GRANT_TO_PI = 'Y'
    UNION
    SELECT ROLE_ID, 1 AS ROLE_TYPE FROM MODULE_DERIVED_ROLES WHERE MODULE_CODE = '13' AND IS_ACTIVE = 'Y' AND AUTO_GRANT_TO_COI = 'Y'
    )
    SELECT  AP.PERSON_ID, MDR.ROLE_ID AS ROLE_ID FROM AWARD_PERSONS AP
    INNER JOIN DERIVED_ROLE MDR ON MDR.ROLE_TYPE = AP.PERSON_ROLE_ID
    WHERE PERSON_ID IS NOT NULL AND AP.PERSON_ROLE_ID in (3, 1) AND AP.AWARD_ID = AV_SOURCE_MODULE_ID;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET LS_DONE = TRUE;

    IF NOT EXISTS (SELECT 1 FROM AGREEMENT_PEOPLE WHERE PEOPLE_TYPE_ID IN (3, 17) AND AGREEMENT_REQUEST_ID = AV_DESTINATION_MODULE_ID) THEN
        INSERT INTO AGREEMENT_PEOPLE(
            AGREEMENT_REQUEST_ID,
            PERSON_ID,
            ROLODEX_ID,
            FULL_NAME,
            PEOPLE_TYPE_ID,
            UPDATE_TIMESTAMP,
            UPDATE_USER
        ) 
			SELECT
            AV_DESTINATION_MODULE_ID,
            PERSON_ID,
            ROLODEX_ID,
            FULL_NAME,
			IF(PERSON_ROLE_ID = 1, 17, PERSON_ROLE_ID) ,
            UTC_TIMESTAMP(),
            AV_UPDATED_USER
            FROM AWARD_PERSONS WHERE
            AWARD_ID = AV_SOURCE_MODULE_ID AND PERSON_ROLE_ID IN (1, 3);
    END IF;

	OPEN AGMT_ROLE_CUR;

		ROLE_LOOP: LOOP
			FETCH AGMT_ROLE_CUR INTO LS_PERSON_ID, LI_ROLE_ID;
            
		IF LS_DONE THEN
			LEAVE ROLE_LOOP;
		END IF;
        
        IF NOT EXISTS (SELECT 1 FROM AGREEMENT_PEOPLE_ROLES WHERE ROLE_ID = LI_ROLE_ID AND PERSON_ID = LS_PERSON_ID AND AGREEMENT_REQUEST_ID = AV_DESTINATION_MODULE_ID) THEN

            INSERT INTO AGREEMENT_PEOPLE_ROLES(
            AGREEMENT_REQUEST_ID,
			IS_SYSTEM_DERIVED_ROLE,
			PERSON_ID,
			ROLE_ID,
			UPDATE_TIMESTAMP,
			UPDATE_USER)
            VALUES 
			(AV_DESTINATION_MODULE_ID,
			'Y',
			LS_PERSON_ID,
			LI_ROLE_ID,
			UTC_TIMESTAMP(),
			AV_UPDATED_USER);

        END IF;

		END LOOP;
	CLOSE AGMT_ROLE_CUR;
    
END
