CREATE PROCEDURE `MIGRATION_PRE_VALIDATION`()
BEGIN

DECLARE LI_MA_MIGRATION_AWARD_ID	INT(11);
DECLARE LS_LEGACY_PROJECT_ID	VARCHAR(20);
DECLARE LS_LEGACY_WBS_NUMBER	VARCHAR(100);
DECLARE LS_MA_GRANT_CODE	VARCHAR(50);
DECLARE LS_MA_ACCOUNT_NUMBER	VARCHAR(100);
DECLARE LI_MA_GRANT_HEADER_ID	INT(10);
DECLARE LS_MA_LEAD_UNIT_NUMBER	VARCHAR(8);
DECLARE LS_MA_ACCOUNT_TYPE_DESC	VARCHAR(200);
DECLARE LS_MA_AWARD_TYPE_DESC	VARCHAR(200);
DECLARE LS_MA_ACTIVITY_TYPE_DESC	VARCHAR(200);
DECLARE LS_MA_AWARD_STATUS_DESC	VARCHAR(200);
DECLARE LS_MA_SPONSOR_CODE	VARCHAR(6);
DECLARE LS_MA_PRIME_SPONSOR_CODE	VARCHAR(6);
DECLARE LD_MA_START_DATE	VARCHAR(10);
DECLARE LD_MA_END_DATE	VARCHAR(10);
DECLARE LI_MA_PREVIOUS_AWARD_ID	INT(11);
DECLARE LS_MA_PREVIOUS_AWARD_FREETEXT	VARCHAR(45);
DECLARE LS_MA_SUB_LEAD_UNIT_CODE	VARCHAR(8);
DECLARE LS_MA_OUTPUT_GST_CATEGORY	VARCHAR(30);
DECLARE LS_MA_INPUT_GST_CATEGORY	VARCHAR(30);
DECLARE LS_MA_CLAIM_FREQUENCY	VARCHAR(200);
DECLARE LS_MA_CLAIM_PROFILE	VARCHAR(200);
DECLARE LS_MA_BILLING_TYPE	VARCHAR(200);
DECLARE LS_MA_RIE_DOMAIN	VARCHAR(200);


DECLARE LS_PERSON_ID	VARCHAR(40);
DECLARE LS_ROLODEX_ID	VARCHAR(10);
DECLARE LI_PERSON_ROLE	INT(12);
DECLARE LI_PERSON_ROLE_CODE INT(12);


DECLARE LI_MIGRATION_AWARD_PRIORITY_AREA_ID	INT(11);
DECLARE LS_PRIORITY_DESCRIPTION	VARCHAR(200);

DECLARE LI_MIGRATION_AWARD_BUDGET_ID	INT(11);
DECLARE LD_BUDGET_START_DATE	VARCHAR(10);
DECLARE LD_BUDGET_END_DATE	VARCHAR(10);
DECLARE LI_DIRECT_COST	DECIMAL(15,2);
DECLARE LI_F_AND_A_COST	DECIMAL(15,2);
DECLARE LI_TOTAL_COST	DECIMAL(15,2);
DECLARE LS_BUDGET_STATUS_DESCRIPTION	VARCHAR(200);
DECLARE LS_BUDGET_TYPE_DESCRIPTION	VARCHAR(200);

DECLARE LI_MIGRATION_AWARD_BUDGET_DETAIL_ID	INT(11);
DECLARE LS_BUDGET_CATEGORY_DESCRIPTION	VARCHAR(200);
DECLARE LS_COST_ELEMENT_CODE VARCHAR(200);
DECLARE LI_LINE_ITEM_COST	DECIMAL(15,2);


DECLARE LI_MIGRATION_AWARD_HIERARCHY_ID	INT(11);
DECLARE LS_PARENT_LEGACY_PROJECT_ID	VARCHAR(20);
DECLARE LS_PARENT_LEGACY_WBS_NUMBER	VARCHAR(100);

DECLARE LI_ME_MIGRATION_ERROR_LOG_ID INT(12);


-- ---------------------------------------MIGRATION_AWARD VALIDATION----------------------------------------------------------------------
BEGIN 
		DECLARE LS_CODE CHAR(5) DEFAULT '00000';
		DECLARE LS_MSG TEXT;
		DECLARE LS_ERROR VARCHAR(2000);

		
        DECLARE DONE1 INT DEFAULT FALSE;

		DECLARE MIGRATION_AWARD_CURSOR CURSOR FOR 
		SELECT MA.MIGRATION_AWARD_ID,
		MA.LEGACY_PROJECT_ID,
		MA.LEGACY_WBS_NUMBER,
		MA.GRANT_CODE,
		MA.ACCOUNT_NUMBER,
		MA.GRANT_HEADER_ID,
		MA.LEAD_UNIT_NUMBER,
		MA.ACCOUNT_TYPE_DESCRIPTION,
		MA.AWARD_TYPE_DESCRIPTION,
		MA.ACTIVITY_TYPE_DESCRIPTION,
		MA.AWARD_STATUS_DESCRIPTION,
		MA.SPONSOR_CODE,
		MA.PRIME_SPONSOR_CODE,
		MA.START_DATE,
		MA.END_DATE,
		MA.PREVIOUS_AWARD_ID,
		MA.PREVIOUS_AWARD_FREETEXT,
		MA.SUB_LEAD_UNIT_CODE,
		MA.OUTPUT_GST_CATEGORY,
		MA.INPUT_GST_CATEGORY,
		MA.CLAIM_FREQUENCY,
		MA.CLAIM_PROFILE,
		MA.BILLING_TYPE,
		MA.RIE_DOMAIN
		FROM MIGRATION_AWARD MA;


		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		  GET DIAGNOSTICS CONDITION 1
			LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
		END;

		OPEN MIGRATION_AWARD_CURSOR;

		MIGRATION_AWARD_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_CURSOR INTO LI_MA_MIGRATION_AWARD_ID,
												LS_LEGACY_PROJECT_ID,
												LS_LEGACY_WBS_NUMBER,
												LS_MA_GRANT_CODE,
												LS_MA_ACCOUNT_NUMBER,
												LI_MA_GRANT_HEADER_ID,
												LS_MA_LEAD_UNIT_NUMBER,
												LS_MA_ACCOUNT_TYPE_DESC,
												LS_MA_AWARD_TYPE_DESC,
												LS_MA_ACTIVITY_TYPE_DESC,
												LS_MA_AWARD_STATUS_DESC,
												LS_MA_SPONSOR_CODE,
												LS_MA_PRIME_SPONSOR_CODE,
												LD_MA_START_DATE,
												LD_MA_END_DATE,
												LI_MA_PREVIOUS_AWARD_ID,
												LS_MA_PREVIOUS_AWARD_FREETEXT,
												LS_MA_SUB_LEAD_UNIT_CODE,
												LS_MA_OUTPUT_GST_CATEGORY,
												LS_MA_INPUT_GST_CATEGORY,
												LS_MA_CLAIM_FREQUENCY,
												LS_MA_CLAIM_PROFILE,
												LS_MA_BILLING_TYPE,
												LS_MA_RIE_DOMAIN;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_CURSOR_LOOP;
				END IF;
				
				
				
				IF (LI_MA_GRANT_HEADER_ID <> '' OR LI_MA_GRANT_HEADER_ID IS NOT NULL) AND LI_MA_GRANT_HEADER_ID NOT IN(SELECT GRANT_HEADER_ID FROM MIGRATION_GRANT_CALL) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Grant call validation failed -MIGRATION_AWARD#',LI_MA_GRANT_HEADER_ID),'Before Migration',NOW(),'admin');
					COMMIT;	
					
				END IF;
					
				IF LS_MA_LEAD_UNIT_NUMBER NOT IN (SELECT UNIT_NUMBER FROM UNIT) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Unit validation failed -MIGRATION_AWARD#',LS_MA_LEAD_UNIT_NUMBER),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;	
				
				IF 	(LS_MA_ACCOUNT_TYPE_DESC <> '' OR LS_MA_ACCOUNT_TYPE_DESC IS NOT NULL) AND UPPER(TRIM(LS_MA_ACCOUNT_TYPE_DESC)) NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM ACCOUNT_TYPE) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Account type validation failed -MIGRATION_AWARD#',LS_MA_ACCOUNT_TYPE_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;	
				
				IF (LS_MA_AWARD_TYPE_DESC <> '' OR LS_MA_AWARD_TYPE_DESC IS NOT NULL) AND  UPPER(TRIM(LS_MA_AWARD_TYPE_DESC))  NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM AWARD_TYPE) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award type validation failed -MIGRATION_AWARD#',LS_MA_AWARD_TYPE_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;		
				
				IF UPPER(TRIM(LS_MA_ACTIVITY_TYPE_DESC))  NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM ACTIVITY_TYPE) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Activity type validation failed -MIGRATION_AWARD#',LS_MA_ACTIVITY_TYPE_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;				
				IF UPPER(TRIM(LS_MA_AWARD_STATUS_DESC))  NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM AWARD_STATUS)THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award status validation failed -MIGRATION_AWARD#',LS_MA_AWARD_STATUS_DESC),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;
				IF LS_MA_SPONSOR_CODE NOT IN(SELECT SPONSOR_CODE FROM SPONSOR) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Sponsor validation failed -MIGRATION_AWARD#',LS_MA_SPONSOR_CODE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;					
				
				IF (LS_MA_PRIME_SPONSOR_CODE <> '' OR LS_MA_PRIME_SPONSOR_CODE IS NOT NULL) AND LS_MA_PRIME_SPONSOR_CODE NOT IN(SELECT SPONSOR_CODE FROM SPONSOR) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Prime Sponsor validation failed -MIGRATION_AWARD#',LS_MA_PRIME_SPONSOR_CODE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;					
				IF STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') IS NULL THEN 
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award Start date format validation failed -MIGRATION_AWARD#',LD_MA_START_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;	
				
				IF STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') IS NULL THEN 
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award End date format validation failed -MIGRATION_AWARD#',LD_MA_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;	
				
			    IF (  STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') IS NOT NULL 
				      AND STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') IS NOT NULL 
					  AND STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') > STR_TO_DATE(LD_MA_END_DATE,'%d-%m-%Y') )THEN
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award Start date - Award End date validation failed -MIGRATION_AWARD#',LD_MA_START_DATE,'-',LD_MA_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;					
				
					
			    IF (LI_MA_PREVIOUS_AWARD_ID <> '' OR LI_MA_PREVIOUS_AWARD_ID IS NOT NULL) AND   LI_MA_PREVIOUS_AWARD_ID NOT IN (SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Previous project legacy id validation failed -MIGRATION_AWARD#',LI_MA_PREVIOUS_AWARD_ID),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;					
				IF (LS_MA_SUB_LEAD_UNIT_CODE <> '' OR LS_MA_SUB_LEAD_UNIT_CODE IS NOT NULL) AND  LS_MA_SUB_LEAD_UNIT_CODE NOT IN (SELECT UNIT_NUMBER FROM UNIT) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Sub unit validation failed -MIGRATION_AWARD#',LS_MA_SUB_LEAD_UNIT_CODE),'Before Migration',NOW(),'admin');
					COMMIT;	

				END IF;

				IF (LS_MA_CLAIM_PROFILE <> '' OR LS_MA_CLAIM_PROFILE IS NOT NULL) AND UPPER(TRIM(LS_MA_CLAIM_PROFILE)) NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM AWARD_BASIS_OF_PAYMENT) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Basis of payment(Claim profile) validation failed -MIGRATION_AWARD#',LS_MA_CLAIM_PROFILE),'Before Migration',NOW(),'admin');
					COMMIT;
				END IF;		
				
				IF (LS_MA_BILLING_TYPE <> '' OR LS_MA_BILLING_TYPE IS NOT NULL) AND UPPER(TRIM(LS_MA_BILLING_TYPE)) NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM AWARD_METHOD_OF_PAYMENT)  THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Method of payment(Billing type) validation failed -MIGRATION_AWARD#',LS_MA_BILLING_TYPE),'Before Migration',NOW(),'admin');
					COMMIT;
					
				END IF;
				
				IF (LS_MA_OUTPUT_GST_CATEGORY <> '' OR LS_MA_OUTPUT_GST_CATEGORY IS NOT NULL) AND UPPER(TRIM(LS_MA_OUTPUT_GST_CATEGORY)) NOT IN ('STANDARD RATE','ZERO RATE','OUT OF SCOPE') THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Output GST category validation failed -MIGRATION_AWARD#',LS_MA_OUTPUT_GST_CATEGORY),'Before Migration',NOW(),'admin');
					COMMIT;
					
				END IF;
				
				IF (LS_MA_INPUT_GST_CATEGORY <> '' OR LS_MA_INPUT_GST_CATEGORY IS NOT NULL) AND UPPER(TRIM(LS_MA_INPUT_GST_CATEGORY)) NOT IN ('CLAIMABLE FROM IRAS','FUNDED BY GRANT BUDGET','ABSORBED BY NTU') THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Input GST category validation failed -MIGRATION_AWARD#',LS_MA_INPUT_GST_CATEGORY),'Before Migration',NOW(),'admin');
					COMMIT;
					
				END IF;
				
				IF (LS_MA_RIE_DOMAIN <> '' OR LS_MA_RIE_DOMAIN IS NOT NULL) AND  UPPER(TRIM(LS_MA_RIE_DOMAIN)) NOT IN ('HEALTH AND BIOMEDICAL SCIENCES','SERVICES AND DIGITAL ECONOMY','ADVANCED MANUFACTURING AND ENGINEERING','URBAN SOLUTIONS & SUSTAINABILITY','ACADEMIC RESEARCH','RESEARCH MANPOWER','INNOVATION & ENTERPRISE','NON-RIE') THEN
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('RIE Domain validation failed -MIGRATION_AWARD#',LS_MA_RIE_DOMAIN),'Before Migration',NOW(),'admin');
					COMMIT;
					
				END IF;
				
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration -MIGRATION_AWARD',NOW(),'admin');
					COMMIT;
					
					
				END IF;	
		END LOOP;
		
		CLOSE MIGRATION_AWARD_CURSOR;
END;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------
/*
-- ---------------------------------------MIGRATION_AWARD_PERSONS VALIDATION----------------------------------------------------------------------
BEGIN 
		DECLARE LS_CODE CHAR(5) DEFAULT '00000';
		DECLARE LS_MSG TEXT;
		DECLARE LS_ERROR VARCHAR(2000);

		
        DECLARE DONE1 INT DEFAULT FALSE;

		DECLARE MIGRATION_AWARD_PERSONS_CURSOR CURSOR FOR 
		SELECT LEGACY_PROJECT_ID,
				LEGACY_WBS_NUMBER,
				PERSON_ID,
				ROLODEX_ID,
				PERSON_ROLE
				FROM MIGRATION_AWARD_PERSONS;



		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		  GET DIAGNOSTICS CONDITION 1
			LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
		END;
		OPEN MIGRATION_AWARD_PERSONS_CURSOR;

		MIGRATION_AWARD_PERSONS_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_PERSONS_CURSOR INTO LS_LEGACY_PROJECT_ID,
															LS_LEGACY_WBS_NUMBER,
															LS_PERSON_ID,
															LS_ROLODEX_ID,
															LI_PERSON_ROLE;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_PERSONS_CURSOR_LOOP;
				END IF;
				
				SELECT CASE WHEN LI_PERSON_ROLE = 'Co-investigator' THEN 1 
							WHEN LI_PERSON_ROLE = 'Collaborator' THEN 6 
							WHEN LI_PERSON_ROLE = 'Manager' THEN 4 
							WHEN LI_PERSON_ROLE = 'PI' THEN 9 
							WHEN LI_PERSON_ROLE = 'Team PI' THEN 7 
							ELSE NULL END INTO LI_PERSON_ROLE_CODE 
				FROM DUAL;
				
				
				IF LS_LEGACY_PROJECT_ID NOT IN(SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Project legacy id validation failed -MIGRATION_AWARD_PERSONS#',LS_LEGACY_PROJECT_ID),'Before Migration',NOW(),'admin');
					COMMIT;
					
					ITERATE MIGRATION_AWARD_PERSONS_CURSOR_LOOP;
					
				END IF;					
				IF LS_PERSON_ID NOT IN(SELECT PERSON_ID FROM PERSON) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Person id validation failed -MIGRATION_AWARD_PERSONS#',LS_PERSON_ID),'Before Migration',NOW(),'admin');
					COMMIT;
				END IF;					
				IF LS_ROLODEX_ID NOT IN(SELECT ROLODEX_ID FROM ROLODEX) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Rolodex id validation failed -MIGRATION_AWARD_PERSONS#',LS_ROLODEX_ID),'Before Migration',NOW(),'admin');
					COMMIT;
				END IF;					
				IF LI_PERSON_ROLE_CODE IS NULL  THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Person role id validation failed -MIGRATION_AWARD_PERSONS#',LI_PERSON_ROLE),'Before Migration',NOW(),'admin');
					COMMIT;
				
				END IF;
				
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration',NOW(),'admin');
					COMMIT;
					
					
				END IF;	
		END LOOP;
		
		CLOSE MIGRATION_AWARD_PERSONS_CURSOR;
END;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------
-- ---------------------------------------MIGRATION_AWARD_PRIORITY_AREA VALIDATION----------------------------------------------------------------------
BEGIN 
		DECLARE LS_CODE CHAR(5) DEFAULT '00000';
		DECLARE LS_MSG TEXT;
		DECLARE LS_ERROR VARCHAR(2000);

		
        DECLARE DONE1 INT DEFAULT FALSE;

		DECLARE MIGRATION_AWARD_PRIORITY_AREA_CURSOR CURSOR FOR 
		SELECT MIGRATION_AWARD_PRIORITY_AREA_ID,
				LEGACY_PROJECT_ID,
				LEGACY_WBS_NUMBER,
				PRIORITY_DESCRIPTION
				FROM MIGRATION_AWARD_PRIORITY_AREA;


		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		  GET DIAGNOSTICS CONDITION 1
			LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
		END;
		OPEN MIGRATION_AWARD_PRIORITY_AREA_CURSOR;

		MIGRATION_AWARD_PRIORITY_AREA_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_PRIORITY_AREA_CURSOR INTO LI_MIGRATION_AWARD_PRIORITY_AREA_ID,
																LS_LEGACY_PROJECT_ID,
																LS_LEGACY_WBS_NUMBER,
																LS_PRIORITY_DESCRIPTION;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_PRIORITY_AREA_CURSOR_LOOP;
				END IF;
				
				
				IF LS_LEGACY_PROJECT_ID NOT IN(SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Project legacy id validation failed -MIGRATION_AWARD_PRIORITY_AREA#',LS_LEGACY_PROJECT_ID),'Before Migration',NOW(),'admin');
					COMMIT;
					
					ITERATE MIGRATION_AWARD_PRIORITY_AREA_CURSOR_LOOP;
					
						    
				END IF;

			    IF UPPER(TRIM(LS_PRIORITY_DESCRIPTION)) NOT IN(SELECT UPPER(TRIM(DESCRIPTION)) FROM EXCELLENCE_AREA) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Excellence area validation failed -MIGRATION_AWARD_PRIORITY_AREA#',LS_PRIORITY_DESCRIPTION),'Before Migration',NOW(),'admin');
					COMMIT;
					
						    
				END IF;
				
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration',NOW(),'admin');
					COMMIT;
					
					
				END IF;	
		END LOOP;
		
		CLOSE MIGRATION_AWARD_PRIORITY_AREA_CURSOR;
END;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------
-- ---------------------------------------MIGRATION_AWARD_BUDGET VALIDATION----------------------------------------------------------------------
BEGIN 
		DECLARE LS_CODE CHAR(5) DEFAULT '00000';
		DECLARE LS_MSG TEXT;
		DECLARE LS_ERROR VARCHAR(2000);

		
        DECLARE DONE1 INT DEFAULT FALSE;

		DECLARE MIGRATION_AWARD_BUDGET_CURSOR CURSOR FOR 
		SELECT MIGRATION_AWARD_BUDGET_ID,
				LEGACY_WBS_NUMBER,
				LEGACY_PROJECT_ID,
				BUDGET_START_DATE,
				BUDGET_END_DATE,
				DIRECT_COST,
				F_AND_A_COST,
				TOTAL_COST,
				BUDGET_STATUS_DESCRIPTION,
				BUDGET_TYPE_DESCRIPTION
				FROM MIGRATION_AWARD_BUDGET;


		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		  GET DIAGNOSTICS CONDITION 1
			LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
		END;
		
		SET LD_MA_START_DATE = NULL;

		OPEN MIGRATION_AWARD_BUDGET_CURSOR;

		MIGRATION_AWARD_BUDGET_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_BUDGET_CURSOR INTO LI_MIGRATION_AWARD_BUDGET_ID,
															LS_LEGACY_WBS_NUMBER,
															LS_LEGACY_PROJECT_ID,
															LD_BUDGET_START_DATE,
															LD_BUDGET_END_DATE,
															LI_DIRECT_COST,
															LI_F_AND_A_COST,
															LI_TOTAL_COST,
															LS_BUDGET_STATUS_DESCRIPTION,
															LS_BUDGET_TYPE_DESCRIPTION;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_BUDGET_CURSOR_LOOP;
				END IF;
				
				
				IF LS_LEGACY_PROJECT_ID NOT IN(SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Project legacy id validation failed -MIGRATION_AWARD_BUDGET#',LS_LEGACY_PROJECT_ID),'Before Migration',NOW(),'admin');
					COMMIT;
					
					ITERATE MIGRATION_AWARD_BUDGET_CURSOR_LOOP;
					
				ELSE 
				
					SELECT START_DATE  INTO LD_MA_START_DATE 
					FROM MIGRATION_AWARD WHERE LEGACY_PROJECT_ID = LS_LEGACY_PROJECT_ID;
					
				END IF;
					
				IF STR_TO_DATE(LD_BUDGET_START_DATE,'%d-%m-%Y') IS NULL THEN 
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Budget Start date format validation failed -MIGRATION_AWARD_BUDGET#',LD_BUDGET_START_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
					
				END IF;		
				
				IF STR_TO_DATE(LD_BUDGET_END_DATE,'%d-%m-%Y') IS NULL THEN 
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Budget End date format validation failed -MIGRATION_AWARD_BUDGET#',LD_BUDGET_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;		
				
				IF  STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') IS NULL THEN 
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award start date format validation failed.Award start date - Budget start date validation failed -MIGRATION_AWARD_BUDGET#',LD_BUDGET_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;	
				
			    IF ( STR_TO_DATE(LD_BUDGET_START_DATE,'%d-%m-%Y') IS NOT NULL 
				      AND STR_TO_DATE(LD_BUDGET_END_DATE,'%d-%m-%Y') IS NOT NULL
					  AND   STR_TO_DATE(LD_BUDGET_START_DATE,'%d-%m-%Y') > STR_TO_DATE(LD_BUDGET_END_DATE,'%d-%m-%Y') ) THEN
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Budget Start date -Budget End date validation failed -MIGRATION_AWARD_BUDGET#',LD_BUDGET_START_DATE,'-',LD_BUDGET_END_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	
				END IF;
				
				IF ( STR_TO_DATE(LD_BUDGET_START_DATE,'%d-%m-%Y') IS NOT NULL 
					  AND STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y') IS NOT NULL					  
					  AND STR_TO_DATE(LD_BUDGET_START_DATE,'%d-%m-%Y') > STR_TO_DATE(LD_MA_START_DATE,'%d-%m-%Y')  ) THEN
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Award start date - Budget Start date validation failed -MIGRATION_AWARD_BUDGET#',LD_MA_START_DATE,'-',LD_BUDGET_START_DATE),'Before Migration',NOW(),'admin');
					COMMIT;	

				END IF;
				
				IF LI_TOTAL_COST <> LI_DIRECT_COST + LI_F_AND_A_COST THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Total cost validation failed -MIGRATION_AWARD_BUDGET#',LI_TOTAL_COST,' <> ',LI_DIRECT_COST,' + ',LI_F_AND_A_COST),'Before Migration',NOW(),'admin');
					COMMIT;	
				
				END IF;

				SELECT SUM(LINE_ITEM_COST) INTO LI_LINE_ITEM_COST
				FROM MIGRATION_AWARD_BUDGET_DETAIL  
				WHERE  LEGACY_PROJECT_ID = LS_LEGACY_PROJECT_ID
				GROUP BY COST_ELEMENT_CODE <> 'ICR';
				
				IF (LI_DIRECT_COST <> LI_LINE_ITEM_COST) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Total direct cost validation failed -MIGRATION_AWARD_BUDGET#',LI_DIRECT_COST,' <> ',LI_LINE_ITEM_COST),'Before Migration',NOW(),'admin');
					COMMIT;	
				
				END IF;
				
				SELECT SUM(LINE_ITEM_COST) INTO LI_LINE_ITEM_COST
				FROM MIGRATION_AWARD_BUDGET_DETAIL  
				WHERE  LEGACY_PROJECT_ID = LS_LEGACY_PROJECT_ID
				GROUP BY COST_ELEMENT_CODE = 'ICR';
				
				IF (LI_F_AND_A_COST <> LI_LINE_ITEM_COST) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Total direct cost validation failed -MIGRATION_AWARD_BUDGET#',LI_F_AND_A_COST,' <> ',LI_LINE_ITEM_COST),'Before Migration',NOW(),'admin');
					COMMIT;	
				
				END IF;
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration',NOW(),'admin');
					COMMIT;
					
					
				END IF;	
		END LOOP;
		
		CLOSE MIGRATION_AWARD_BUDGET_CURSOR;
END;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------
-- ---------------------------------------MIGRATION_AWARD_BUDGET_DETAIL VALIDATION----------------------------------------------------------------------
BEGIN 
		DECLARE LS_CODE CHAR(5) DEFAULT '00000';
		DECLARE LS_MSG TEXT;
		DECLARE LS_ERROR VARCHAR(2000);

        DECLARE DONE1 INT DEFAULT FALSE;

		DECLARE MIGRATION_AWARD_BUDGET_DETAIL_CURSOR CURSOR FOR 
		SELECT MIGRATION_AWARD_BUDGET_DETAIL_ID,
				LEGACY_PROJECT_ID,
				LEGACY_WBS_NUMBER,
				BUDGET_CATEGORY_DESCRIPTION,
				COST_ELEMENT_CODE,
				LINE_ITEM_COST
				FROM MIGRATION_AWARD_BUDGET_DETAIL;


		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		  GET DIAGNOSTICS CONDITION 1
			LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
		END;
		OPEN MIGRATION_AWARD_BUDGET_DETAIL_CURSOR;

		MIGRATION_AWARD_BUDGET_DETAIL_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_BUDGET_DETAIL_CURSOR INTO LI_MIGRATION_AWARD_BUDGET_DETAIL_ID,
																LS_LEGACY_PROJECT_ID,
																LS_LEGACY_WBS_NUMBER,
																LS_BUDGET_CATEGORY_DESCRIPTION,
																LS_COST_ELEMENT_CODE,
																LI_LINE_ITEM_COST;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_BUDGET_DETAIL_CURSOR_LOOP;
				END IF;
				

				
				IF LS_LEGACY_PROJECT_ID NOT IN(SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Project legacy id validation failed -MIGRATION_AWARD_BUDGET_DETAIL#',LS_LEGACY_PROJECT_ID),'Before Migration',NOW(),'admin');
					COMMIT;
					
					ITERATE MIGRATION_AWARD_BUDGET_DETAIL_CURSOR_LOOP;
					
						    
				END IF;

								
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration',NOW(),'admin');
					COMMIT;
					
					
				END IF;	
		END LOOP;
		
		CLOSE MIGRATION_AWARD_BUDGET_DETAIL_CURSOR;
END;
-- ----------------------------------------------------------------------------------------------------------------------------------------------------
-- ---------------------------------------MIGRATION_AWARD_HIERARCHY VALIDATION----------------------------------------------------------------------
BEGIN 
		DECLARE LS_CODE CHAR(5) DEFAULT '00000';
		DECLARE LS_MSG TEXT;
		DECLARE LS_ERROR VARCHAR(2000);
		
        DECLARE DONE1 INT DEFAULT FALSE;

		DECLARE MIGRATION_AWARD_HIERARCHY_CURSOR CURSOR FOR 
		SELECT MIGRATION_AWARD_HIERARCHY_ID,
				LEGACY_WBS_NUMBER,
				LEGACY_PROJECT_ID,
				PARENT_LEGACY_PROJECT_ID,
				PARENT_LEGACY_WBS_NUMBER
				FROM MIGRATION_AWARD_HIERARCHY WHERE LEGACY_PROJECT_ID IS NOT NULL AND PARENT_LEGACY_PROJECT_ID IS NOT NULL ;


		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		  GET DIAGNOSTICS CONDITION 1
			LS_CODE = RETURNED_SQLSTATE, LS_MSG = MESSAGE_TEXT;
		END;
		OPEN MIGRATION_AWARD_HIERARCHY_CURSOR;

		MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP : LOOP
				FETCH MIGRATION_AWARD_HIERARCHY_CURSOR INTO LI_MIGRATION_AWARD_HIERARCHY_ID,
															LS_LEGACY_WBS_NUMBER,
															LS_LEGACY_PROJECT_ID,
															LS_PARENT_LEGACY_PROJECT_ID,
															LS_PARENT_LEGACY_WBS_NUMBER;
				IF DONE1 THEN
					LEAVE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
				END IF;
				
				
				IF LS_LEGACY_PROJECT_ID NOT IN(SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD) THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Project legacy id validation failed -MIGRATION_AWARD_BUDGET_DETAIL#',LS_LEGACY_PROJECT_ID),'Before Migration',NOW(),'admin');
					COMMIT;
					
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
					
						    
				END IF;

			    IF LS_PARENT_LEGACY_PROJECT_ID NOT IN(SELECT LEGACY_PROJECT_ID FROM MIGRATION_AWARD)  THEN
				
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;

					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LS_LEGACY_PROJECT_ID,'Validation',CONCAT('Parent Project legacy id validation failed -MIGRATION_AWARD_BUDGET_DETAIL#',LS_PARENT_LEGACY_PROJECT_ID),'Before Migration',NOW(),'admin');
					COMMIT;
					
					ITERATE MIGRATION_AWARD_HIERARCHY_CURSOR_LOOP;
					
						    
				END IF;
				
				IF LS_CODE <> '00000' THEN
					SET LS_ERROR = SUBSTR(LS_MSG,1,999);
					
					SELECT IFNULL(MAX(MIGRATION_ERROR_LOG_ID),0)+1 INTO LI_ME_MIGRATION_ERROR_LOG_ID FROM MIGRATION_ERROR_LOG;
					
					INSERT INTO MIGRATION_ERROR_LOG(MIGRATION_ERROR_LOG_ID,LEGACY_PROJECT_ID,ERROR_TYPE,ERROR_MESSAGE,VALIDATION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER) 
					VALUES(LI_ME_MIGRATION_ERROR_LOG_ID,LI_ME_LEGACY_PROJECT_ID,'Exception',LS_ERROR,'Before Migration',NOW(),'admin');
					COMMIT;
					
					
				END IF;	
		END LOOP;
		
		CLOSE MIGRATION_AWARD_HIERARCHY_CURSOR;
END;

-- ----------------------------------------------------------------------------------------------------------------------------------------------------

*/

SELECT 1  AS RESULT;

END 
