CREATE PROCEDURE `QUESTION_ANSWER_CHECK`( 
AV_QUESTIONNAIRE_ANS_HEADER_ID INT(12),
AV_QUESTION_ID INT(12),
AV_QUESTIONNAIRE_ID INT(12),
OUT EXPR_RESULT VARCHAR(200)
)
    DETERMINISTIC
BEGIN
DECLARE LI_FLAG INT;
DECLARE LS_CONDITION_FLAG VARCHAR(12);
	
	SELECT COUNT(1) INTO LI_FLAG FROM QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID = AV_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID = AV_QUESTION_ID
	AND ANSWER IS NOT NULL AND ANSWER <>'';
	IF LI_FLAG = 0 THEN
		SET LS_CONDITION_FLAG = 'FALSE';
	ELSE

	BEGIN
							DECLARE DONE2 INT DEFAULT FALSE;
							DECLARE LS_ANSWER VARCHAR(4000);

							DECLARE CUR_QUEST_ANSWER CURSOR FOR
							SELECT  ANSWER FROM 
							QUEST_ANSWER WHERE QUESTIONNAIRE_ANS_HEADER_ID = AV_QUESTIONNAIRE_ANS_HEADER_ID AND QUESTION_ID = AV_QUESTION_ID AND ANSWER IS NOT NULL AND ANSWER <>'';

							DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;

							OPEN CUR_QUEST_ANSWER;
							B_LOOP: LOOP 
							FETCH CUR_QUEST_ANSWER INTO
							LS_ANSWER;
			
							
							IF DONE2 THEN
								LEAVE B_LOOP;
							END IF;
								
									SELECT COUNT(1) INTO LI_FLAG FROM QUEST_QUESTION_CONDITION WHERE QUESTION_ID = AV_QUESTION_ID;
									IF LI_FLAG >0 THEN
										
										BEGIN
											DECLARE DONE3 INT DEFAULT FALSE;
											DECLARE LS_CONDITION_TYPE VARCHAR(100);
											DECLARE LS_CONDITION_VALUE VARCHAR(2000);
											DECLARE LS_GROUP_NAME VARCHAR(100);

											DECLARE CUR_QUESTION_CONDITION CURSOR FOR
											SELECT CONDITION_TYPE, CONDITION_VALUE, GROUP_NAME FROM QUEST_QUESTION_CONDITION WHERE QUESTION_ID = AV_QUESTION_ID;
											
											DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
											
											OPEN CUR_QUESTION_CONDITION;
											C_LOOP : LOOP
											FETCH CUR_QUESTION_CONDITION INTO
											LS_CONDITION_TYPE, LS_CONDITION_VALUE, LS_GROUP_NAME;
											
											IF DONE3 THEN
											LEAVE C_LOOP;
											END IF;
											
											IF LS_CONDITION_TYPE = 'EQUALS' THEN
												IF LS_CONDITION_VALUE = LS_ANSWER THEN
													-- TAKE THE THE QUESTIONS FROM THE GROUP SPECIFIED AND THEN NEED TO ITERATE
													BEGIN
														DECLARE DONE4 INT DEFAULT FALSE;
														DECLARE CHILD_QUESTION_ID INT(12);
														
														DECLARE CUR_CHILD_QUESTIONS CURSOR FOR
														SELECT QUESTION_ID FROM QUEST_QUESTION WHERE GROUP_NAME = LS_GROUP_NAME AND QUESTIONNAIRE_ID = AV_QUESTIONNAIRE_ID ;
														
														DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
														
														OPEN CUR_CHILD_QUESTIONS;
														D_LOOP : LOOP
														FETCH CUR_CHILD_QUESTIONS INTO CHILD_QUESTION_ID;
														
														IF DONE4 THEN
														LEAVE D_LOOP;
														END IF;
														
														CALL QUESTION_ANSWER_CHECK(AV_QUESTIONNAIRE_ANS_HEADER_ID, CHILD_QUESTION_ID,AV_QUESTIONNAIRE_ID, @EXPR_RESULT);
														SET LS_CONDITION_FLAG = @EXPR_RESULT;
														
														IF LS_CONDITION_FLAG = 'FALSE' THEN
															LEAVE D_LOOP;
														END IF;

														END LOOP;
														CLOSE CUR_CHILD_QUESTIONS;
													END;
												END IF;
											ELSEIF LS_CONDITION_TYPE = 'NOTEQUALS' THEN
												IF LS_CONDITION_VALUE <> LS_ANSWER THEN
													BEGIN
														DECLARE DONE4 INT DEFAULT FALSE;
														DECLARE CHILD_QUESTION_ID INT(12);
														
														DECLARE CUR_CHILD_QUESTIONS CURSOR FOR
														SELECT QUESTION_ID FROM QUEST_QUESTION WHERE GROUP_NAME = LS_GROUP_NAME AND QUESTIONNAIRE_ID = AV_QUESTIONNAIRE_ID ;
														
														DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
														
														OPEN CUR_CHILD_QUESTIONS;
														D_LOOP : LOOP
														FETCH CUR_CHILD_QUESTIONS INTO CHILD_QUESTION_ID;
														
														IF DONE4 THEN
														LEAVE D_LOOP;
														END IF;
														
														 CALL QUESTION_ANSWER_CHECK(AV_QUESTIONNAIRE_ANS_HEADER_ID, CHILD_QUESTION_ID,AV_QUESTIONNAIRE_ID, @EXPR_RESULT);
														SET LS_CONDITION_FLAG = @EXPR_RESULT;
                                                        IF LS_CONDITION_FLAG = 'FALSE' THEN
															LEAVE D_LOOP;
														END IF;

														END LOOP;
														CLOSE CUR_CHILD_QUESTIONS;
													END;
												END IF;
											END IF;
											IF LS_CONDITION_FLAG = 'FALSE' THEN
															LEAVE C_LOOP;
											END IF;
											
											END LOOP;
											CLOSE CUR_QUESTION_CONDITION;

										END;
									END IF;
									
							IF LS_CONDITION_FLAG = 'FALSE' THEN
								LEAVE B_LOOP;
							END IF;
							END LOOP;
							CLOSE CUR_QUEST_ANSWER;
							
						END;
				END IF;
                
				IF LS_CONDITION_FLAG = 'FALSE' THEN
				SELECT  'FALSE' INTO EXPR_RESULT;
				ELSE
				SELECT  'TRUE' INTO EXPR_RESULT;
				END IF;
			
END
