-- `SUPPORT_WIDGETS`; 

CREATE PROCEDURE `SUPPORT_WIDGETS`(
    AV_PERSON_ID  VARCHAR(40),
    AV_LIMIT  INT
)
BEGIN
    DECLARE LS_DYN_SQL  LONGTEXT;
    DECLARE LS_OFFSET_CONDITION LONGTEXT;
    SET LS_OFFSET_CONDITION = '';
    IF AV_LIMIT > 0 THEN
        SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ', AV_LIMIT);
    END IF;
    SET LS_DYN_SQL = CONCAT(
        'SELECT DISTINCT
            T1.PRE_REVIEW_ID,
            T1.MODULE_ITEM_CODE,
            T1.MODULE_ITEM_KEY,
            T1.PRE_REVIEW_SECTION_TYPE_CODE,
            T1.REQUESTOR_FULLNAME,
            T1.REQUESTOR_COMMENT,
            T1.UPDATE_TIMESTAMP,
            T6.DESCRIPTION AS PRE_REVIEW_SECTION_TYPE,
			 CASE
				WHEN T1.MODULE_ITEM_CODE = 3 THEN T3.TITLE
				WHEN T1.MODULE_ITEM_CODE = 13 THEN T4.TITLE
			ELSE NULL
            END AS TITLE,
            T5.REVIEW_COMMENT
        FROM
            pre_review T1
        INNER JOIN
            support_request_notification T2
            ON T2.PRE_REVIEW_ID = T1.PRE_REVIEW_ID
        LEFT JOIN
            eps_proposal T3
            ON T3.PROPOSAL_ID = T1.MODULE_ITEM_KEY
        LEFT JOIN
            AGREEMENT_HEADER T4
            ON T4.AGREEMENT_REQUEST_ID = T1.MODULE_ITEM_KEY
		left join
        PRE_REVIEW_SECTION_TYPE t6 on t6.PRE_REVIEW_SECTION_TYPE_CODE = t1.PRE_REVIEW_SECTION_TYPE_CODE
        LEFT JOIN
            PRE_REVIEW_COMMENT T5
            ON T5.PRE_REVIEW_ID = T1.PRE_REVIEW_ID
        WHERE
            T2.IS_READ = "N" AND T2.TO_PERSON_ID = ''', AV_PERSON_ID,'''
            AND (
                  ( T1.REQUESTOR_PERSON_ID <> ''', AV_PERSON_ID,''' AND T5.PRE_REVIEW_COMMENT_ID IS NULL)
                OR
                (T5.PRE_REVIEW_COMMENT_ID IS NOT NULL AND T5.PRE_REVIEW_COMMENT_ID =(
                select max(PRE_REVIEW_COMMENT_ID) from pre_review_comment where PRE_REVIEW_ID = t1.PRE_REVIEW_ID)
                AND T5.PERSON_ID != ''', AV_PERSON_ID,''')
            )
        ORDER BY
            T1.UPDATE_TIMESTAMP DESC', LS_OFFSET_CONDITION
    );
 SET @QUERY_STATEMENT = LS_DYN_SQL;
 PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
 EXECUTE EXECUTABLE_STAEMENT;
END
