-- `UPDATE_CUSTOM_DATA`; 

CREATE PROCEDURE `UPDATE_CUSTOM_DATA`()
BEGIN
DECLARE LI_COLUMN_ID INT;
DECLARE LS_COLUMN_LABEL VARCHAR(4000);
	DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE CUR_SEL_DATA CURSOR FOR
			SELECT COLUMN_ID,COLUMN_LABEL FROM CUSTOM_DATA_ELEMENTS
			WHERE COLUMN_VERSION_NUMBER = 1;
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN CUR_SEL_DATA;
			INSERT_LOOP: LOOP 
			FETCH CUR_SEL_DATA INTO
			LI_COLUMN_ID,
			LS_COLUMN_LABEL;
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
			UPDATE CUSTOM_DATA_ELEMENTS SET CUSTOM_ELEMENT_NAME = LS_COLUMN_LABEL
			WHERE COLUMN_ID = LI_COLUMN_ID;
			END LOOP;
			CLOSE CUR_SEL_DATA;
END
