-- `FN_CHCK_IS_TERMINAL_STATUS`; 


CREATE FUNCTION `FN_CHCK_IS_TERMINAL_STATUS`(
AV_STATUS_CODE          VARCHAR(3)) RETURNS varchar(10) 
    DETERMINISTIC
BEGIN
    IF AV_STATUS_CODE NOT IN ('10', '4', '8', '9', '5') THEN
        RETURN 'TRUE';
    ELSE 
        RETURN 'FALSE';
    END IF;
END
