CREATE VIEW AC_PROTOCOL_V AS
   SELECT 
        CONCAT('AC', `t1`.`PROTOCOL_ID`) AS `ID`,
        `t1`.`PROTOCOL_ID` AS `PROTOCOL_ID`,
        `t1`.`PROTOCOL_NUMBER` AS `PROTOCOL_NUMBER`,
        `t1`.`PROTOCOL_STATUS_CODE` AS `PROTOCOL_STATUS_CODE`,
        `t2`.`DESCRIPTION` AS `PROTOCOL_STATUS`,
        `t1`.`TITLE` AS `TITLE`,
        `t1`.`SEQUENCE_NUMBER` AS `SEQUENCE_NUMBER`,
        `t3`.`DISPLAY_NAME` AS `UNIT_NAME`,
        DATE_FORMAT(`t1`.`APPROVAL_DATE`, '%m/%d/%Y') AS `APPROVAL_DATE`,
        DATE_FORMAT(`t1`.`EXPIRATION_DATE`, '%m/%d/%Y') AS `EXPIRATION_DATE`,
        `t1`.`PROTOCOL_TYPE_CODE` AS `PROTOCOL_TYPE_CODE`,
        `t4`.`DESCRIPTION` AS `PROTOCOL_TYPE`,
        NULL AS `PI_NAME`
    FROM
        (((`AC_PROTOCOL` `t1`
        JOIN `AC_PROTOCOL_STATUS` `t2` ON ((`t2`.`PROTOCOL_STATUS_CODE` = `t1`.`PROTOCOL_STATUS_CODE`)))
        JOIN `UNIT` `t3` ON ((`t1`.`LEAD_UNIT_NUMBER` = `t3`.`UNIT_NUMBER`)))
        JOIN `AC_PROTOCOL_TYPE` `t4` ON ((`t4`.`PROTOCOL_TYPE_CODE` = `t1`.`PROTOCOL_TYPE_CODE`)))
    WHERE
        (`t1`.`PROTOCOL_ID` = (SELECT 
                MAX(`AC_PROTOCOL`.`PROTOCOL_ID`)
            FROM
                `AC_PROTOCOL`
            WHERE
                (`AC_PROTOCOL`.`PROTOCOL_NUMBER` = `t1`.`PROTOCOL_NUMBER`)));
