DROP TABLE IF EXISTS `delete_workday_resource`;

CREATE TABLE `delete_workday_resource` (
  `DELETE_WORKDAY_RESOURCE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `WBS_NUMBER` varchar(50) DEFAULT NULL,
  `COST_ALLOCATION` decimal(5,2) DEFAULT NULL,
  `CHARGE_START_DATE` datetime DEFAULT NULL,
  `CHARGE_END_DATE` datetime DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`DELETE_WORKDAY_RESOURCE_ID`)
) ;
