DROP TABLE IF EXISTS `manpower_user_actions`;

CREATE TABLE `manpower_user_actions` (
  `MANPOWER_USER_ACTION_CODE` varchar(3) NOT NULL,
  `MANPOWER_USER_ACTION` varchar(200) DEFAULT NULL,
  `DESCRIPTION` varchar(4000) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`MANPOWER_USER_ACTION_CODE`)
) ;
