DROP TABLE IF EXISTS `manpower_interface_type`;

CREATE TABLE `manpower_interface_type` (
  `INTERFACE_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`INTERFACE_TYPE_CODE`)
) ;