
DROP TABLE IF EXISTS `manpower_type`;

CREATE TABLE `manpower_type` (
  `MANPOWER_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`MANPOWER_TYPE_CODE`)
);