-- `RESET_AUTO_INCREMENT_IP`; 

CREATE PROCEDURE `RESET_AUTO_INCREMENT_IP`()
BEGIN
	  SELECT @max := IFNULL(MAX(PROPOSAL_ID),0)+ 1 FROM PROPOSAL;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(ACTION_LOG_ID),0)+1 FROM PROPOSAL_ACTION_LOG;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_ACTION_LOG AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(PROPOSAL_ADMIN_DETAIL_ID),0)+1 FROM PROPOSAL_ADMIN_DETAILS;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_ADMIN_DETAILS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(ATTACHMENT_ID),0)+1 FROM PROPOSAL_ATTACHMENTS;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_ATTACHMENTS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(PROPOSAL_COMMENT_ID),0)+1 FROM PROPOSAL_COMMENTS;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_COMMENTS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(KEYWORD_ID),0)+1 FROM PROPOSAL_KEYWORDS;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_KEYWORDS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(PROPOSAL_PERSON_ID),0)+1 FROM PROPOSAL_PERSONS;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_PERSONS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(ATTACHMENT_ID),0)+1 FROM PROPOSAL_PERSONS_ATTACHMNT;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_PERSONS_ATTACHMNT AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(PROPOSAL_PROJECT_TEAM_ID),0)+1 FROM PROPOSAL_PROJECT_TEAM;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_PROJECT_TEAM AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(REVIEW_ID),0)+1 FROM PROPOSAL_REVIEW;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_REVIEW AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(REVIEW_ATTACHMENT_ID),0)+1 FROM PROPOSAL_REVIEW_ATTACHMENT;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_REVIEW_ATTACHMENT AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(REVIEW_COMMENT_ID),0)+1 FROM PROPOSAL_REVIEW_COMMENT;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_REVIEW_COMMENT AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(PROPOSAL_SPECIAL_REVIEW_ID),0)+1 FROM PROPOSAL_SPECIAL_REVIEW;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_SPECIAL_REVIEW AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(HISTORY_ID),0)+1 FROM PROPOSAL_VERSION_HISTORY;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_VERSION_HISTORY AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(PROP_PERSON_UNIT_ID),0)+1 FROM PROP_PERSON_UNITS;
      SET @alter_statement = concat('ALTER TABLE PROP_PERSON_UNITS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(BUDGET_HEADER_ID),0)+1 FROM IP_BUDGET_HEADER;
      SET @alter_statement = concat('ALTER TABLE IP_BUDGET_HEADER AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(BUDGET_PERIOD_ID),0)+1 FROM IP_BUDGET_PERIOD;
      SET @alter_statement = concat('ALTER TABLE IP_BUDGET_PERIOD AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
	  SELECT @max := IFNULL(MAX(RESRCH_AREA_ID),0)+1 FROM PROPOSAL_RESRCH_AREAS;
      SET @alter_statement = concat('ALTER TABLE PROPOSAL_RESRCH_AREAS AUTO_INCREMENT = ', @max);
      PREPARE stmt FROM @alter_statement;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
END
