
DROP TABLE IF EXISTS `researcher_media_and_outreach`;
CREATE TABLE `researcher_media_and_outreach` (
  `RESEARCHER_OUTREACH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ID` varchar(40) NOT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` text,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `IS_HIGHLIGHTED` varchar(1) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `WEBSITE_URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESEARCHER_OUTREACH_ID`),
  KEY `RESR_MEDIA_AND_OUTREACH_FK1` (`PERSON_ID`),
  CONSTRAINT `RESR_MEDIA_AND_OUTREACH_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
) ;
