
DROP TABLE IF EXISTS `researcher_publication`;

CREATE TABLE `researcher_publication` (
  `RESEARCHER_PUBLICATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `CO_AUTHORSHIP` text,
  `PUBLICATION_DATE` date DEFAULT NULL,
  `RELEVANT_URL` varchar(400) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `IS_HIGHLIGHTED` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `ORCID_WORK_TYPE_CODE` varchar(30) DEFAULT NULL,
  `ORCID_WORK_CATEGORY_CODE` varchar(3) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `JOURNAL_TITLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESEARCHER_PUBLICATION_ID`),
  KEY `RESEARCHER_PUBLICATION_FK2` (`ORCID_WORK_TYPE_CODE`,`ORCID_WORK_CATEGORY_CODE`),
  CONSTRAINT `RESEARCHER_PUBLICATION_FK2` FOREIGN KEY (`ORCID_WORK_TYPE_CODE`, `ORCID_WORK_CATEGORY_CODE`) REFERENCES `orcid_work_type` (`ORCID_WORK_TYPE_CODE`, `ORCID_WORK_CATEGORY_CODE`)
) ;