
DROP TABLE IF EXISTS `researcher_award_honor`;

CREATE TABLE `researcher_award_honor` (
  `RESEARCHER_AWARD_HONOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_NAME` varchar(1000) DEFAULT NULL,
  `AWARD_ORGANIZATION` varchar(200) DEFAULT NULL,
  `PERSON_ID` varchar(40) NOT NULL,
  `YEAR_RECEIVED` int(11) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `IS_HIGHLIGHTED` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `DESCRIPTION` text,
  PRIMARY KEY (`RESEARCHER_AWARD_HONOR_ID`),
  KEY `RESER_AWARD_HONOR_FK1` (`PERSON_ID`),
  CONSTRAINT `RESER_AWARD_HONOR_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
) ;