
DROP TABLE IF EXISTS `researcher_testimonial`;

CREATE TABLE `researcher_testimonial` (
  `RESEARCHER_TESTIMONIAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ID` varchar(40) NOT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `IS_HIGHLIGHTED` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `REFERENCE_EMAIL_ID` varchar(60) DEFAULT NULL,
  `TESTIMONIAL_TEXT` text,
  `DESIGNATION` varchar(200) DEFAULT NULL,
  `ORGANIZATION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`RESEARCHER_TESTIMONIAL_ID`),
  KEY `RESEARCHER_TESTIMONIAL_FK1` (`PERSON_ID`),
  CONSTRAINT `RESEARCHER_TESTIMONIAL_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
) ;
