
DROP TABLE IF EXISTS `researcher_keyword`;

CREATE TABLE `researcher_keyword` (
  `RESEARCHER_KEYWORD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `RESRCH_TYPE_AREA_CODE` varchar(8) DEFAULT NULL,
  `RESRCH_TYPE_SUB_AREA_CODE` varchar(3) DEFAULT NULL,
  `SCIENCE_KEYWORD_CODE` varchar(15) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `IS_HIGHLIGHTED` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`RESEARCHER_KEYWORD_ID`),
  KEY `RESEARCHER_KEYWORD_FK1` (`RESRCH_TYPE_AREA_CODE`),
  KEY `RESEARCHER_KEYWORD_FK2` (`RESRCH_TYPE_SUB_AREA_CODE`),
  KEY `RESEARCHER_KEYWORD_FK3` (`SCIENCE_KEYWORD_CODE`),
  KEY `RESEARCHER_KEYWORD_FK4` (`PERSON_ID`),
  CONSTRAINT `RESEARCHER_KEYWORD_FK1` FOREIGN KEY (`RESRCH_TYPE_AREA_CODE`) REFERENCES `research_type_area` (`RESRCH_TYPE_AREA_CODE`),
  CONSTRAINT `RESEARCHER_KEYWORD_FK2` FOREIGN KEY (`RESRCH_TYPE_SUB_AREA_CODE`) REFERENCES `research_type_sub_area` (`RESRCH_TYPE_SUB_AREA_CODE`),
  CONSTRAINT `RESEARCHER_KEYWORD_FK3` FOREIGN KEY (`SCIENCE_KEYWORD_CODE`) REFERENCES `science_keyword` (`SCIENCE_KEYWORD_CODE`),
  CONSTRAINT `RESEARCHER_KEYWORD_FK4` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
) ;
