
DROP TABLE IF EXISTS `researcher_additional_details`;

CREATE TABLE `researcher_additional_details` (
  `RESEARCHER_ADD_DTLS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESIGNATION` varchar(255) DEFAULT NULL,
  `ORGANIZATION_ID` varchar(20) DEFAULT NULL,
  `NATIONALITY` varchar(255) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `ACTION_COMMENT` varchar(2000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`RESEARCHER_ADD_DTLS_ID`),
  KEY `RESEARCHER_ADDITIONAL_DETAILS_FK1` (`PERSON_ID`),
  KEY `RESEARCHER_ADDITIONAL_DETAILS_FK2` (`ORGANIZATION_ID`),
  CONSTRAINT `RESEARCHER_ADDITIONAL_DETAILS_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`),
  CONSTRAINT `RESEARCHER_ADDITIONAL_DETAILS_FK2` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `organization` (`ORGANIZATION_ID`)
) ;
