


CREATE PROCEDURE `COI_DELETE_OPA_DISCLOSURES_BY_ID`(
AV_OPA_DISCLOSURE_ID VARCHAR(60)
)
BEGIN


	SET FOREIGN_KEY_CHECKS=0; 
	SET SQL_SAFE_UPDATES = 0;
    
    DELETE FROM OPA_ACTION_LOG 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_REVIEW 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_FORM_BUILDER_DETAILS 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_INSTITUTE_RESOURCE_USE 
	WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_DISCL_PERSON_ENTITY 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_DISCL_ACTIVITIES 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_OUTSIDE_FIN_INTERESTS 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM OPA_STUDENT_SUBORDINATE_INVOLVEMENT 
    WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;
    
    DELETE FROM COI_QUEST_ANSWER_ATTACHMENT 
    WHERE QUESTIONNAIRE_ANSWER_ID IN (select QUESTIONNAIRE_ANSWER_ID from COI_QUEST_ANSWER 
									WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (select QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer_header 
																			WHERE MODULE_ITEM_CODE = 23 AND MODULE_SUB_ITEM_CODE=0 AND MODULE_ITEM_KEY = AV_OPA_DISCLOSURE_ID));
	DELETE FROM COI_QUEST_TABLE_ANSWER 
    WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (select QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer_header 
											WHERE MODULE_ITEM_CODE = 23 AND MODULE_SUB_ITEM_CODE=0 AND MODULE_ITEM_KEY = AV_OPA_DISCLOSURE_ID);
												
	DELETE FROM COI_QUEST_ANSWER 
    WHERE QUESTIONNAIRE_ANS_HEADER_ID IN (select QUESTIONNAIRE_ANS_HEADER_ID FROM quest_answer_header 
											WHERE MODULE_ITEM_CODE = 23 AND MODULE_SUB_ITEM_CODE=0 AND MODULE_ITEM_KEY = AV_OPA_DISCLOSURE_ID);
    
    DELETE FROM OPA_DISCLOSURE WHERE OPA_DISCLOSURE_ID = AV_OPA_DISCLOSURE_ID;

    DELETE FROM DISCL_COMMENT WHERE MODULE_CODE = 23 AND MODULE_ITEM_KEY = AV_OPA_DISCLOSURE_ID;
    
    SET FOREIGN_KEY_CHECKS=1; 
	SET SQL_SAFE_UPDATES = 1;

END