


CREATE PROCEDURE `ENRICH_ENTITY_INDUSTRY_CATE`(
    IN AV_ENTITY_ID INT,
	IN AV_PERSON_ID VARCHAR(40),
    IN AV_INDUSTRY_CATEGORY_CODE VARCHAR(10),
    IN AV_CODE_DESCRIPTION VARCHAR(255),
    IN AV_TYPE_DESCRIPTION VARCHAR(255),	
    IN AV_INDUSTRY_CATEGORY_TYPE_CODE VARCHAR(10)
)
    DETERMINISTIC
BEGIN

    DECLARE v_INDUSTRY_CATEGORY_ID INT;
	 DECLARE type_exists INT DEFAULT 0;
    
    SELECT INDUSTRY_CATEGORY_ID 
    INTO v_INDUSTRY_CATEGORY_ID 
    FROM industry_category_code
    WHERE INDUSTRY_CATEGORY_TYPE_CODE = AV_INDUSTRY_CATEGORY_TYPE_CODE 
    AND INDUSTRY_CATEGORY_CODE = AV_INDUSTRY_CATEGORY_CODE;
	
    
    IF v_INDUSTRY_CATEGORY_ID IS NOT NULL THEN
		 
		SELECT COUNT(ENTITY_ID) INTO type_exists
		FROM entity_industry_classification 
		WHERE ENTITY_ID = AV_ENTITY_ID 
        AND INDUSTRY_CATEGORY_ID = v_INDUSTRY_CATEGORY_ID;

		
		IF type_exists = 0 THEN
			 INSERT INTO entity_industry_classification (ENTITY_ID, INDUSTRY_CATEGORY_ID,IS_PRIMARY,UPDATED_BY,UPDATE_TIMESTAMP)
            VALUES (AV_ENTITY_ID, v_INDUSTRY_CATEGORY_ID,'N',AV_PERSON_ID, now());
		END IF;
		
        
    ELSE
  
  
 		SELECT COUNT(INDUSTRY_CATEGORY_TYPE_CODE) INTO type_exists
		FROM industry_category_type 
		WHERE INDUSTRY_CATEGORY_TYPE_CODE = AV_INDUSTRY_CATEGORY_TYPE_CODE;

		
		IF type_exists = 0 THEN
			INSERT INTO industry_category_type (INDUSTRY_CATEGORY_TYPE_CODE, IS_PRIMARY,DESCRIPTION,IS_ACTIVE,UPDATED_BY,UPDATE_TIMESTAMP)
            VALUES (AV_INDUSTRY_CATEGORY_TYPE_CODE, 'N',AV_TYPE_DESCRIPTION,'N',AV_PERSON_ID, now());
		END IF;
		
       
        INSERT INTO industry_category_code (INDUSTRY_CATEGORY_CODE, INDUSTRY_CATEGORY_TYPE_CODE,DESCRIPTION,IS_ACTIVE,UPDATED_BY,UPDATE_TIMESTAMP)
        VALUES (AV_INDUSTRY_CATEGORY_CODE, AV_INDUSTRY_CATEGORY_TYPE_CODE,AV_CODE_DESCRIPTION,'N',AV_PERSON_ID, now());
        
        
        SELECT LAST_INSERT_ID() INTO v_INDUSTRY_CATEGORY_ID;
        
		INSERT INTO entity_industry_classification (ENTITY_ID, INDUSTRY_CATEGORY_ID,IS_PRIMARY,UPDATED_BY,UPDATE_TIMESTAMP)
        VALUES (AV_ENTITY_ID, v_INDUSTRY_CATEGORY_ID,'N',AV_PERSON_ID, now());
		
    END IF;
END