




CREATE PROCEDURE `GENERATE_ATTACHMENT_NUMBER`(
AV_ATTACHMENT_COUNTER_NAME VARCHAR(30)
)
BEGIN
    DECLARE LI_LOCK_ACQUIRED INT DEFAULT 0;
    DECLARE LI_NEXT_VALUE INT;
    START TRANSACTION;
    SELECT GET_LOCK('LOCK_ON_ATTACHMENT_NUMBER_COUNTER', 30) INTO LI_LOCK_ACQUIRED;
    IF LI_LOCK_ACQUIRED THEN
        SELECT COUNTER_VALUE INTO LI_NEXT_VALUE FROM ATTACHMENT_NUMBER_COUNTER WHERE COUNTER_NAME = AV_ATTACHMENT_COUNTER_NAME;
		UPDATE ATTACHMENT_NUMBER_COUNTER SET COUNTER_VALUE = COUNTER_VALUE + 1 WHERE COUNTER_NAME = AV_ATTACHMENT_COUNTER_NAME;
        SELECT RELEASE_LOCK('LOCK_ON_ATTACHMENT_NUMBER_COUNTER');
        COMMIT;
    END IF;
    SELECT LI_NEXT_VALUE;
END