


CREATE PROCEDURE `GET_COI_DISCL_PROJECT_DETAILS`(
	AV_COLUMN_NAMES           	VARCHAR(4000),
    AV_MODULE_ITEM_KEY         	INT,
	AV_SUB_MODULE_ITEM_KEY      INT
)
BEGIN

DECLARE LS_DYN_SQL 					LONGTEXT;
DECLARE LS_DYN_JOINS				LONGTEXT;
DECLARE LS_DYN_CONDITIONS			LONGTEXT;
DECLARE LS_DYN_SELECT_COLUMNS		LONGTEXT;


SET LS_DYN_SQL = CONCAT('SELECT ', AV_COLUMN_NAMES, ' FROM
	(SELECT
	t1.DISCLOSURE_ID AS DISCLOSURE_ID,
	COALESCE(t5.PROPOSAL_TITLE, t10.IP_TITLE, t6.AWARD_TITLE) AS FCOI_PROJECT_TITLE,
	COALESCE(t5.PROPOSAL_ID, t10.IP_NUMBER, t6.AWARD_NUMBER) AS FCOI_PROJECT_NUMBER,
	t13.PRIMARY_NAME AS SIGNIFICANT_FINANCIAL_INTEREST,
	t14.DESCRIPTION AS PROJECT_TYPE
	FROM COI_DISCLOSURE t1
	INNER JOIN COI_DISCL_PROJECT_ENTITY_REL t11 ON t11.COI_DISCL_PROJECT_ENTITY_REL_ID = ', AV_SUB_MODULE_ITEM_KEY,'
    INNER JOIN COI_DISCL_PROJECTS t9 ON t9.DISCLOSURE_ID = t1.DISCLOSURE_ID AND T9.COI_DISCL_PROJECTS_ID = t11.COI_DISCL_PROJECTS_ID
    LEFT JOIN PERSON_ENTITY t12 ON t12.PERSON_ENTITY_ID = t11.PERSON_ENTITY_ID
    INNER JOIN ENTITY t13 ON t13.ENTITY_ID = t11.ENTITY_ID
	LEFT JOIN (SELECT EXTERNAL_SYSTEM_REF_ID AS PROPOSAL_ID,
		TITLE  AS PROPOSAL_TITLE, EXTERNAL_SYSTEM_REF_ID FROM COI_PROJECT_PROPOSAL_V ) t5 ON t5.PROPOSAL_ID = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 3
	LEFT  JOIN (SELECT AWARD_NUMBER, EXTERNAL_SYSTEM_REF_ID,
		TITLE AS AWARD_TITLE FROM COI_PROJECT_AWARD_V ) t6  ON t6.AWARD_NUMBER = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 1
	LEFT  JOIN (SELECT PROPOSAL_NUMBER AS IP_NUMBER , EXTERNAL_SYSTEM_REF_ID,
		TITLE AS IP_TITLE FROM COI_PROJECT_INSTITUTE_PROPOSAL_V ) t10 ON t10.IP_NUMBER = t9.MODULE_ITEM_KEY AND t9.MODULE_CODE = 2
	LEFT JOIN COI_PROJECT_TYPE t14 ON t14.COI_PROJECT_TYPE_CODE = t9.MODULE_CODE
	WHERE t1.DISCLOSURE_ID = ', AV_MODULE_ITEM_KEY, ' AND t11.COI_DISCL_PROJECT_ENTITY_REL_ID = ', AV_SUB_MODULE_ITEM_KEY, ' ) T');

SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
END