


CREATE PROCEDURE GET_PROJECT_OVERVIEW(
AV_FILTER_TYPE            VARCHAR(40),
AV_PROPOSAL_TITLE		  VARCHAR(1000),
AV_PROPOSAL_NUMBER		  VARCHAR(20),
AV_UNIT_NUMBER            VARCHAR(8),
AV_PERSON_ID    		  VARCHAR(40),
AV_PROPOSAL_STATUS        VARCHAR(200),
AV_REVIEW_STATUS 		  VARCHAR(200),
AV_SPONSOR 					VARCHAR(6),
AV_PRIME_SPONSOR 			VARCHAR(6),
AV_PROPOSAL_START_DATE 		VARCHAR(20),
AV_PROPOSAL_END_DATE 		VARCHAR(20),
AV_PAGED                        INT(10),
AV_LIMIT                        INT(10),
AV_UNLIMITED                    BOOLEAN,
AV_TYPE						 VARCHAR(1),
AV_SORT_TYPE 				VARCHAR(2000),
AV_PI_PERSON_ID				VARCHAR(40),
AV_LOGIN_PERSON_ID	VARCHAR(40)							  
)
BEGIN

DECLARE LS_FILTER_CONDITION 		LONGTEXT;
DECLARE LS_OUTER_FILTER_CONDITION 		LONGTEXT;
DECLARE LS_JOIN_CONDITION			LONGTEXT;
DECLARE LS_PAGINATION_CONDITION 	VARCHAR(60);
DECLARE LS_DYN_SQL					LONGTEXT;
DECLARE LI_CA_ADMIN					INT;
DECLARE LI_CAN_VIEW_PRIVATE_COMMENT	INT;

DECLARE LS_OFFSET 					INT(11);
DECLARE LS_ORDER_BY 				LONGTEXT;
DECLARE LS_OFFSET_CONDITION			LONGTEXT;

SET LS_DYN_SQL ='';
SET LS_FILTER_CONDITION = '';
SET LS_OUTER_FILTER_CONDITION = '';
SET LS_PAGINATION_CONDITION = '';
SET LS_JOIN_CONDITION = '';
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);

-- added by prabhu for overall status checking:
DROP  TABLE if exists DisclosureProjects;
    	CREATE  TABLE DisclosureProjects AS SELECT DISTINCT T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_ID
		,T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_NUMBER
		,T1.KEY_PERSON_ID
		,CASE 
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
				THEN CASE 
						WHEN T55.REVIEW_STATUS_CODE IN (
								2
								,3
								,4
								,7
								,8
								)
							THEN 'DISCLOSURE_COMPLETED'
						ELSE 'DISCLOSURE_PENDING'
						END
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'
				THEN 'DISCLOSURE_NOT_REQUIRED'
			ELSE 'DISCLOSURE_TO_BE_DETERMINED'
			END AS DISCLOSURE_STATUS
		,CASE 
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'REQUIRED'
				THEN UPPER(T9.DESCRIPTION)
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = 'NOT_REQUIRED'
				THEN 'DISCLOSURE_REVIEW_NA'
			ELSE NULL
			END AS PROJECT_DISCLOSURE_REVIEW_STATUS
	FROM coi_project_proposal_v T1
	LEFT JOIN (
		SELECT T13.EXTERNAL_SYSTEM_REF_ID
			,T22.DISCLOSURE_ID
			,T6.FCOI_TYPE_CODE
			,T6.REVIEW_STATUS_CODE
			,T6.DISPOSITION_STATUS_CODE
			,T6.PERSON_ID
		FROM coi_project_proposal_v T13
		INNER JOIN COI_DISCL_PROJECTS T22 ON T22.MODULE_ITEM_KEY = T13.EXTERNAL_SYSTEM_REF_ID
			AND T22.MODULE_CODE = T13.COI_PROJECT_TYPE_CODE
		INNER JOIN COI_DISCLOSURE T6 ON T22.DISCLOSURE_ID = T6.DISCLOSURE_ID
		WHERE T6.DISPOSITION_STATUS_CODE != 2
		) AS T55 ON T55.EXTERNAL_SYSTEM_REF_ID = T1.EXTERNAL_SYSTEM_REF_ID
		AND T55.PERSON_ID = T1.KEY_PERSON_ID
	LEFT JOIN coi_review_status_type T9 ON T9.REVIEW_STATUS_CODE = T55.REVIEW_STATUS_CODE;
    
    

    SET LS_JOIN_CONDITION = CONCAT(LS_JOIN_CONDITION, ' LEFT JOIN PERSON T2 ON T1.KEY_PERSON_ID = T2.PERSON_ID
														LEFT JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T1.SPONSOR_CODE
														LEFT JOIN SPONSOR T4 ON T4.SPONSOR_CODE = T1.PRIME_SPONSOR_CODE
														LEFT JOIN (
                                                        SELECT T13.EXTERNAL_SYSTEM_REF_ID, T22.DISCLOSURE_ID, T6.FCOI_TYPE_CODE, T6.REVIEW_STATUS_CODE,
															T6.DISPOSITION_STATUS_CODE, T6.PERSON_ID
															from coi_project_proposal_v T13
                                                            INNER JOIN COI_DISCL_PROJECTS T22
																ON T22.MODULE_ITEM_KEY = T13.EXTERNAL_SYSTEM_REF_ID
																AND T22.MODULE_CODE = T13.COI_PROJECT_TYPE_CODE
                                                            inner join
															COI_DISCLOSURE T6
                                                            on T22.DISCLOSURE_ID = T6.DISCLOSURE_ID
                                                            where T6.DISPOSITION_STATUS_CODE != 2
														) AS T55 ON (T55.EXTERNAL_SYSTEM_REF_ID = T1.EXTERNAL_SYSTEM_REF_ID AND T55.PERSON_ID = T1.KEY_PERSON_ID)
														INNER JOIN eps_prop_person_role T7 ON T7.PROP_PERSON_ROLE_ID = T1.KEY_PERSON_ROLE_CODE
														LEFT JOIN UNIT T8 ON T8.UNIT_NUMBER = T2.HOME_UNIT
														LEFT JOIN coi_review_status_type T9 ON T9.REVIEW_STATUS_CODE = T55.REVIEW_STATUS_CODE
														INNER JOIN coi_project_type T10 ON T10.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
                                                        INNER JOIN coi_project_proposal_status_v T11 ON T11.STATUS_CODE = T1.PROPOSAL_STATUS_CODE
                                                         ');

IF AV_TYPE ='A' THEN

    IF AV_PROPOSAL_TITLE IS NOT NULL AND AV_PROPOSAL_TITLE <> '' THEN
		 SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.TITLE LIKE ''%', AV_PROPOSAL_TITLE, '%'' ');
	END IF;

    IF AV_PROPOSAL_NUMBER IS NOT NULL  AND AV_PROPOSAL_NUMBER <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.PROPOSAL_NUMBER LIKE ''%',AV_PROPOSAL_NUMBER, '%'' ');
	END IF;
    
    IF AV_UNIT_NUMBER IS NOT NULL AND AV_UNIT_NUMBER <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.LEAD_UNIT_NUMBER = ''',AV_UNIT_NUMBER,''' ');
    END IF;

    IF AV_PERSON_ID IS NOT NULL AND AV_PERSON_ID <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.PROPOSAL_NUMBER IN(SELECT PROPOSAL_NUMBER FROM coi_project_proposal_v WHERE KEY_PERSON_ID = ''',AV_PERSON_ID,''') ');
    END IF;

    IF AV_PROPOSAL_STATUS IS NOT NULL AND AV_PROPOSAL_STATUS <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T11.STATUS_CODE IN (', AV_PROPOSAL_STATUS, ') ');
    END IF;

    IF AV_REVIEW_STATUS IS NOT NULL AND AV_REVIEW_STATUS <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T55.REVIEW_STATUS_CODE IN (', AV_REVIEW_STATUS, ') ');
    END IF;

    IF AV_SPONSOR IS NOT NULL AND AV_SPONSOR <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T3.SPONSOR_CODE = ''',AV_SPONSOR,''' ');
    END IF;
    
    IF AV_PRIME_SPONSOR IS NOT NULL AND AV_PRIME_SPONSOR <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T4.SPONSOR_CODE = ''',AV_PRIME_SPONSOR,''' ');
    END IF;

    IF AV_PROPOSAL_START_DATE IS NOT NULL AND AV_PROPOSAL_START_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.PROPOSAL_START_DATE) >= DATE_FORMAT(''',AV_PROPOSAL_START_DATE,''',''%Y-%m-%d'') ');
    END IF;

    IF AV_PROPOSAL_END_DATE IS NOT NULL AND AV_PROPOSAL_END_DATE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND DATE(T1.PROPOSAL_END_DATE) <= DATE_FORMAT(''',AV_PROPOSAL_END_DATE,''',''%Y-%m-%d'') ');
    
	END IF;
 
	IF AV_PI_PERSON_ID IS NOT NULL AND AV_PI_PERSON_ID <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T1.PI_PERSON_ID = ''',AV_PI_PERSON_ID,''' ');
    END IF;	   
ELSE
/* Commenting the code based on Current requirement. Might revisit the logic later
	SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.PROPOSAL_TYPE_CODE = 1 AND (
      EXISTS (
          SELECT 1
          FROM COI_DISCL_PROJECTS T20
          WHERE T20.MODULE_ITEM_KEY = T1.PROPOSAL_NUMBER 
          AND T20.MODULE_CODE = T1.COI_PROJECT_TYPE_CODE
      ) 
      OR T1.SPONSOR_CODE IN (SELECT T21.SPONSOR_CODE FROM SPONSOR_DISCLOSURE_REQUIREMENTS T21)
      OR T1.PRIME_SPONSOR_CODE IN (SELECT T21.SPONSOR_CODE FROM SPONSOR_DISCLOSURE_REQUIREMENTS T21)
  )');
*/
	
    SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION, ' AND T1.PROPOSAL_TYPE_CODE = 1 AND T1.PROPOSAL_STATUS_CODE IN (2, 12)');
/*
  SET LS_OUTER_FILTER_CONDITION = CONCAT(LS_OUTER_FILTER_CONDITION,' WHERE (T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_PENDING''
         OR (T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' AND (T1.PROJECT_REVIEW_STATUS IS NOT NULL AND T1.PROJECT_REVIEW_STATUS <> ''DISCLOSURE_NA_REVIEW'')))
         OR (T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_COMPLETED'' AND T1.PROPOSAL_STATUS_CODE IN (1,2))  ');
*/
END IF;

IF AV_SORT_TYPE IS NOT NULL OR AV_SORT_TYPE <> '' THEN 

SET LS_ORDER_BY = CONCAT(' ORDER BY T1.PROJECT_SUBMISSION_STATUS IS NULL, T1.PROJECT_REVIEW_STATUS IS NULL,
 ',AV_SORT_TYPE,', T1.UPDATE_TIMESTAMP DESC,T1.SORT_ID ASC');
ELSE 

SET LS_ORDER_BY = ' ORDER BY T1.UPDATE_TIMESTAMP DESC,T1.SORT_ID ASC ';

END IF;

IF AV_UNLIMITED <> TRUE  THEN

IF AV_LIMIT IS NOT NULL AND LS_OFFSET IS NOT NULL THEN
SET LS_OFFSET_CONDITION =CONCAT(' WHERE T.ROWNUMBER BETWEEN ', (SELECT CASE WHEN LS_OFFSET = 0 THEN LS_OFFSET ELSE LS_OFFSET+1 END), ' AND ', ( LS_OFFSET + AV_LIMIT));
END IF;

ELSE 
SET LS_OFFSET_CONDITION = '';
END IF;

SELECT COUNT(1) INTO LI_CA_ADMIN
FROM PERSON_ROLES PR
JOIN ROLE_RIGHTS RR ON PR.ROLE_ID = RR.ROLE_ID
JOIN RIGHTS RT ON RR.RIGHT_ID = RT.RIGHT_ID
WHERE PR.PERSON_ID = AV_LOGIN_PERSON_ID AND RT.RIGHT_NAME = 'CONTRACT_ADMINISTRATOR';

SELECT COUNT(1) INTO LI_CAN_VIEW_PRIVATE_COMMENT
FROM PERSON_ROLES PR
JOIN ROLE_RIGHTS RR ON PR.ROLE_ID = RR.ROLE_ID
JOIN RIGHTS RT ON RR.RIGHT_ID = RT.RIGHT_ID
WHERE PR.PERSON_ID = AV_LOGIN_PERSON_ID AND RT.RIGHT_NAME IN ('VIEW_COI_PRIVATE_COMMENTS','MAINTAIN_COI_PRIVATE_COMMENTS');


SET LS_DYN_SQL = CONCAT(
    LS_DYN_SQL,
    'WITH	CommentsCount AS (
        SELECT MODULE_ITEM_KEY, MODULE_CODE, COUNT(*) AS COMMENT_COUNT
        FROM coi_project_comment
        GROUP BY MODULE_ITEM_KEY, MODULE_CODE
    ),
	 PersonCommentsCount AS (
        SELECT MODULE_ITEM_KEY, MODULE_CODE,DOCUMENT_OWNER_PERSON_ID,COUNT(*) AS PERSON_COMMENT_COUNT
        FROM DISCL_COMMENT
        where MODULE_CODE = 8 AND PARENT_COMMENT_ID IS NULL
		AND ((',LI_CA_ADMIN,' = 0 AND COMPONENT_TYPE_CODE IN (3, 4, 5, 6, 8, 9, 2, 10, 11, 12)) 
            OR (',LI_CA_ADMIN,' = 1 AND COMPONENT_TYPE_CODE = 12)
        )
		AND ((',LI_CAN_VIEW_PRIVATE_COMMENT,' = 0 AND IS_PRIVATE = ''N'') 
            OR (',LI_CAN_VIEW_PRIVATE_COMMENT,' > 0 AND IS_PRIVATE IN (''Y'',''N''))
        )
        GROUP BY MODULE_ITEM_KEY,DOCUMENT_OWNER_PERSON_ID
    ),
DisclosureProjects AS (
   
	SELECT DISTINCT T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_ID
		,T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_NUMBER
		,T1.KEY_PERSON_ID
		,CASE 
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED''
				THEN CASE 
						WHEN T55.REVIEW_STATUS_CODE IN (
								2
								,3
								,4
								,7
								,8
								)
							THEN ''DISCLOSURE_COMPLETED''
						ELSE ''DISCLOSURE_PENDING''
						END
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED''
				THEN ''DISCLOSURE_NOT_REQUIRED''
			ELSE ''DISCLOSURE_TO_BE_DETERMINED''
			END AS DISCLOSURE_STATUS
		,CASE 
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED''
				THEN UPPER(T9.DESCRIPTION)
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED''
				THEN ''DISCLOSURE_REVIEW_NA''
			ELSE NULL
			END AS PROJECT_DISCLOSURE_REVIEW_STATUS
	FROM coi_project_proposal_v T1
	LEFT JOIN (
		SELECT T13.EXTERNAL_SYSTEM_REF_ID
			,T22.DISCLOSURE_ID
			,T6.FCOI_TYPE_CODE
			,T6.REVIEW_STATUS_CODE
			,T6.DISPOSITION_STATUS_CODE
			,T6.PERSON_ID
		FROM coi_project_proposal_v T13
		INNER JOIN COI_DISCL_PROJECTS T22 ON T22.MODULE_ITEM_KEY = T13.EXTERNAL_SYSTEM_REF_ID
			AND T22.MODULE_CODE = T13.COI_PROJECT_TYPE_CODE
		INNER JOIN COI_DISCLOSURE T6 ON T22.DISCLOSURE_ID = T6.DISCLOSURE_ID
		WHERE T6.DISPOSITION_STATUS_CODE != 2
		) AS T55 ON T55.EXTERNAL_SYSTEM_REF_ID = T1.EXTERNAL_SYSTEM_REF_ID
		AND T55.PERSON_ID = T1.KEY_PERSON_ID
	LEFT JOIN coi_review_status_type T9 ON T9.REVIEW_STATUS_CODE = T55.REVIEW_STATUS_CODE
)
'
);

SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '
SELECT * FROM (SELECT 
T1.PROJECT_ID,
    T1.PROJECT_NUMBER,
    T1.TITLE,
    T1.PI_NAME,
    T1.KEY_PERSON_ID,
    T1.KEY_PERSON_NAME,
    T1.KEY_PERSON_ROLE_CODE,
    T1.KEY_PERSON_ROLE,
    T1.SPONSOR_NAME,
    T1.SPONSOR_CODE,
    T1.PRIME_SPONSOR_NAME,
    T1.PRIME_SPONSOR_CODE,
    T1.LEAD_UNIT_NUMBER,
    T1.LEAD_UNIT_NAME,
    T1.HOME_UNIT,
    T1.HOME_UNIT_NAME,
    T1.PROPOSAL_START_DATE,
    T1.PROPOSAL_END_DATE,
    T1.PROJECT_STATUS,
    T1.DISCLOSURE_ID,
    T1.DISCLOSURE_REVIEW_STATUS,
    T1.FCOI_TYPE_CODE,
    T1.PROJECT_TYPE_CODE,
    T1.PROJECT_TYPE,
    T1.BADGE_COLOR,
    T1.UPDATE_TIMESTAMP,
    T1.CERTIFICATION_FLAG,
    T1.DISCLOSURE_REQUIRED_FLAG,
    T1.COMMENT_COUNT ,
    T1.DISCLOSURE_COMPLETION_STATUS,
    T1.PROJECT_ICON,
    T1.DOCUMENT_NUMBER,
    NULL AS ACCOUNT_NUMBER,
    CASE WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN T1.DISCLOSURE_STATUS =''DISCLOSURE_NOT_REQUIRED'' THEN ''Not Required''
    WHEN T1.DISCLOSURE_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN ''TO_BE_DETERMINED''
    WHEN T1.DISCLOSURE_STATUS is null THEN ''N/A''
    WHEN T1.DISCLOSURE_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    ELSE T1.DISCLOSURE_STATUS
    END AS PERSON_SUBMISSION_STATUS ,
 	CASE WHEN T1.REVIEW_STATUS = ''Completed'' THEN ''Completed''
    WHEN T1.REVIEW_STATUS =''DISCLOSURE_REVIEW_NA'' THEN ''N/A''
    WHEN T1.REVIEW_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN ''TO_BE_DETERMINED''
    WHEN T1.REVIEW_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    ELSE T1.REVIEW_STATUS
    END AS PERSON_REVIEW_STATUS ,
    CASE WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN T1.PROJECT_SUBMISSION_STATUS =''DISCLOSURE_NOT_REQUIRED'' THEN ''Not Required''
    WHEN T1.PROJECT_SUBMISSION_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN NULL
    WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''
    ELSE T1.PROJECT_SUBMISSION_STATUS
    END AS PROJECT_SUBMISSION_STATUS ,
    CASE WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' 
    AND T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_NA_REVIEW''  THEN NULL
	WHEN T1.PROJECT_SUBMISSION_STATUS = ''DISCLOSURE_PENDING'' 
    AND T1.PROJECT_REVIEW_STATUS IS NOT NULL  THEN ''Pending''
    WHEN T1.PROJECT_SUBMISSION_STATUS IS NULL THEN NULL
    WHEN T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_COMPLETED'' THEN ''Completed''
    WHEN T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_NA_REVIEW'' THEN ''N/A''
    WHEN T1.PROJECT_REVIEW_STATUS =''DISCLOSURE_TO_BE_DETERMINED'' THEN NULL
    WHEN T1.PROJECT_REVIEW_STATUS = ''DISCLOSURE_PENDING'' THEN ''Pending''    
    ELSE T1.PROJECT_REVIEW_STATUS
    END AS PROJECT_REVIEW_STATUS,
    T1.Complete_count,
    T1.Incomplete_count,
    null as PCK,
    null as DISCLOSURE_VALIDATION_FLAG,
    null as SPONSOR_HIERARCY,
    null as RESUBMISSION_FLAG,
    null as INFO,
   @row_number := IF(@prev_value = T1.PROJECT_ID, @row_number, @row_number + 1) AS rownumber,
	@prev_value := T1.PROJECT_ID AS PROJECT_IDS,
    T1.NON_EMPLOYEE_FLAG,
    T1.PERSON_COMMENT_COUNT	
    FROM
(SELECT DISTINCT 
    T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_ID,
    T1.EXTERNAL_SYSTEM_REF_ID AS PROJECT_NUMBER,
    T1.TITLE,
    T1.PI_NAME,
    T1.KEY_PERSON_ID,
    T1.KEY_PERSON_NAME,
    T1.KEY_PERSON_ROLE_CODE,
    T7.DESCRIPTION AS KEY_PERSON_ROLE,
    T1.SPONSOR_NAME,
    T3.SPONSOR_CODE,
    T1.PRIME_SPONSOR_NAME,
    T4.SPONSOR_CODE AS PRIME_SPONSOR_CODE,
    T1.LEAD_UNIT_NUMBER,
    T1.LEAD_UNIT_NAME,
    T2.HOME_UNIT,
    T8.UNIT_NAME AS HOME_UNIT_NAME,
    T1.PROPOSAL_START_DATE,
    T1.PROPOSAL_END_DATE,
    T1.PROPOSAL_STATUS AS PROJECT_STATUS,
    T55.DISCLOSURE_ID,
    T9.DESCRIPTION AS DISCLOSURE_REVIEW_STATUS,
    T55.FCOI_TYPE_CODE,
    T1.COI_PROJECT_TYPE_CODE AS PROJECT_TYPE_CODE,
    T10.DESCRIPTION AS PROJECT_TYPE,
    T7.SORT_ID ,
    T10.BADGE_COLOR,
    T1.UPDATE_TIMESTAMP,
    T1.CERTIFICATION_FLAG,
    T1.DISCLOSURE_REQUIRED_FLAG,
    (SELECT COALESCE(COMMENT_COUNT, 0) FROM CommentsCount WHERE MODULE_ITEM_KEY = T1.EXTERNAL_SYSTEM_REF_ID	AND MODULE_CODE = T1.COI_PROJECT_TYPE_CODE LIMIT 1 ) AS COMMENT_COUNT,
    CASE 
        WHEN T55.REVIEW_STATUS_CODE IN (2, 3, 4, 7, 8)
        THEN "Yes"
        ELSE "No"
    END AS DISCLOSURE_COMPLETION_STATUS,
    T10.PROJECT_ICON,
    T1.DOCUMENT_NUMBER,
    NULL AS ACCOUNT_NUMBER,

(SELECT FN_GET_OVERALL_PRJT_DISCL_RVW_STATUS(T1.EXTERNAL_SYSTEM_REF_ID)) AS PROJECT_REVIEW_STATUS,
(SELECT FN_GET_OVERALL_PRJT_DISCL_STATUS(T1.EXTERNAL_SYSTEM_REF_ID)) AS PROJECT_SUBMISSION_STATUS,

        (SELECT COUNT(1)
                FROM DisclosureProjects
                WHERE PROJECT_ID = T1.EXTERNAL_SYSTEM_REF_ID
                    AND DISCLOSURE_STATUS = ''DISCLOSURE_COMPLETED'') AS complete_count,
	(SELECT COUNT(1)
                FROM DisclosureProjects
                WHERE PROJECT_ID = T1.EXTERNAL_SYSTEM_REF_ID
                    AND DISCLOSURE_STATUS != ''DISCLOSURE_COMPLETED'') AS Incomplete_count,

    
CASE 
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED''
				THEN CASE 
						WHEN T55.REVIEW_STATUS_CODE IN (
								2
								,3
								,4
								,7
								,8
								)
							THEN ''DISCLOSURE_COMPLETED''
						ELSE ''DISCLOSURE_PENDING''
						END
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED''
				THEN ''DISCLOSURE_NOT_REQUIRED''
			ELSE ''DISCLOSURE_TO_BE_DETERMINED''
			END AS DISCLOSURE_STATUS
		,CASE 
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''REQUIRED''
				THEN T9.DESCRIPTION
			WHEN T1.DISCLOSURE_REQUIRED_FLAG = ''NOT_REQUIRED''
				THEN ''DISCLOSURE_REVIEW_NA''
			ELSE NULL
			END AS REVIEW_STATUS,
            T1.NON_EMPLOYEE_FLAG,
			COALESCE(PC.PERSON_COMMENT_COUNT, 0) AS PERSON_COMMENT_COUNT,
			T1.PROPOSAL_STATUS_CODE
	FROM coi_project_proposal_v T1 
     ', LS_JOIN_CONDITION, '
     LEFT JOIN PersonCommentsCount PC ON PC.MODULE_ITEM_KEY = T55.DISCLOSURE_ID AND PC.DOCUMENT_OWNER_PERSON_ID = T1.KEY_PERSON_ID
	WHERE PERSON_STATUS <> ''I'' AND (T55.FCOI_TYPE_CODE = 2 OR T55.FCOI_TYPE_CODE IS NULL)
	', LS_FILTER_CONDITION, ' GROUP BY T1.EXTERNAL_SYSTEM_REF_ID , T1.KEY_PERSON_ID,T1.KEY_PERSON_ROLE_CODE )T1', LS_OUTER_FILTER_CONDITION,ifnull(LS_ORDER_BY,''),' )T ',LS_OFFSET_CONDITION,' ');
 
 
 IF AV_UNLIMITED = TRUE THEN
        SET LS_DYN_SQL = CONCAT('SELECT count(distinct PROJECT_ID) AS PROPOSAL_COUNT FROM ( ',LS_DYN_SQL,' ) T');

 END IF;
 
 SET @row_number = 0;
SET @prev_value = NULL;
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;

END
