


CREATE PROCEDURE `GET_GLOBAL_ENTITY_DETAILS`(
	AV_COLUMN_NAMES           	VARCHAR(4000),
    AV_MODULE_ITEM_KEY         	INT,
	AV_SUB_MODULE_ITEM_KEY      INT
)
BEGIN

DECLARE LS_DYN_SQL 					LONGTEXT;


    SET LS_DYN_SQL = CONCAT('SELECT ', AV_COLUMN_NAMES, ' FROM
    	(SELECT t1.PRIMARY_NAME, t1.FOREIGN_NAME, t1.PRIOR_NAME, t1.SHORT_NAME, t1.DUNS_NUMBER, t1.UEI_NUMBER, t1.CAGE_NUMBER,
    	    t1.PRIMARY_ADDRESS_LINE_1, t1.PRIMARY_ADDRESS_LINE_2, t1.CITY, t1.STATE, t1.POST_CODE, t1.ENTITY_ID,
    	    t2.DESCRIPTION AS ENTITY_STATUS,
    	    t3.DESCRIPTION AS ENTITY_OWNERSHIP,
    	    t4.COUNTRY_NAME,
    	    t5.FULL_NAME AS ENTITY_CREATED_BY,
    	    t1.CREATE_TIMESTAMP
    	    FROM ENTITY t1
            LEFT JOIN ENTITY_STATUS_TYPE t2 ON t2.ENTITY_STATUS_TYPE_CODE = t1.ENTITY_STATUS_TYPE_CODE
            LEFT JOIN ENTITY_OWNERSHIP_TYPE t3 ON t3.OWNERSHIP_TYPE_CODE = t1.ENTITY_OWNERSHIP_TYPE_CODE
            INNER JOIN COUNTRY t4 ON t4.COUNTRY_CODE = t1.COUNTRY_CODE
            LEFT JOIN PERSON t5 ON t5.PERSON_ID = t1.CREATED_BY
        WHERE t1.ENTITY_ID = ', AV_MODULE_ITEM_KEY, ')T' );

    SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STAEMENT;

END