


CREATE PROCEDURE `GET_COI_DISCLOSURE_HISTORY`(
	AV_PERSON_ID                    VARCHAR(200),
	AV_FILTER_TYPE					        VARCHAR(10),
    AV_IS_COUNT                    	BOOLEAN
)
BEGIN
		
	DECLARE LS_DYN_SQL 					LONGTEXT;
    DECLARE LS_FILTER_CONDITION 		LONGTEXT;
    DECLARE DISC_JOIN_CONDITION 		LONGTEXT;
    DECLARE TRAVEL_DISC_JOIN_CONDITION 	LONGTEXT;
    DECLARE DISC_SELECTED_FIELD_LIST 	LONGTEXT;
    DECLARE TRAVEL_SELECTED_FIELD_LIST 	LONGTEXT;
    DECLARE DISC_TAB_QUERY 				LONGTEXT;
    DECLARE TRAVEL_TAB_QUERY 			LONGTEXT;
    DECLARE CONSULTING_SELECTED_FIELD_LIST 	LONGTEXT;
    DECLARE CONSULTING_DISC_JOIN_CONDITION 				LONGTEXT;
    DECLARE CONSULTING_TAB_QUERY 			LONGTEXT;
    DECLARE ALL_DISC_SELECTED_FIELD_LIST 	LONGTEXT;
    DECLARE ALL_DISC_JOIN_CONDITION 		LONGTEXT;

    SET LS_FILTER_CONDITION ='';
    SET LS_DYN_SQL ='';
    SET DISC_JOIN_CONDITION = '';
    SET TRAVEL_DISC_JOIN_CONDITION = '';
    SET DISC_SELECTED_FIELD_LIST= '';
    SET TRAVEL_SELECTED_FIELD_LIST= '';
    SET DISC_TAB_QUERY = '';
    SET TRAVEL_TAB_QUERY = '';
    SET CONSULTING_SELECTED_FIELD_LIST = '';
    SET CONSULTING_DISC_JOIN_CONDITION = '';
    SET CONSULTING_TAB_QUERY = '';
    SET ALL_DISC_SELECTED_FIELD_LIST= '';
    SET ALL_DISC_JOIN_CONDITION= '';


    	IF AV_FILTER_TYPE = 'FCOI' THEN

    		SET DISC_TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE IN (1,3) ');

    	ELSEIF AV_FILTER_TYPE = 'PROJECT' THEN

    		SET DISC_TAB_QUERY = CONCAT(' AND T1.FCOI_TYPE_CODE = 2 ');

    	END IF;

        IF AV_FILTER_TYPE = 'ALL' THEN

    		SET ALL_DISC_SELECTED_FIELD_LIST= CONCAT('T1.DISCLOSURE_ID, NULL AS TRAVEL_DISCLOSURE_ID, NULL AS CONSULTING_DISCLOSURE_ID, T1.UPDATE_TIMESTAMP, T1.VERSION_STATUS, T1.FCOI_TYPE_CODE,
                                            T2.DESCRIPTION AS FCOI_TYPE, T1.HOME_UNIT, T3.UNIT_NAME, T1.EXPIRATION_DATE, T1.IS_EXTENDED, T1.CERTIFIED_AT, T1.CONFLICT_STATUS_CODE,
                                            T4.DESCRIPTION AS CONFLICT_STATUS, T1.DISPOSITION_STATUS_CODE, T5.DESCRIPTION AS DISPOSITION_STATUS, T1.REVIEW_STATUS_CODE,
                                            T6.DESCRIPTION AS REVIEW_STATUS, NULL AS ENTITY_NAME, NULL AS DESTINATION_COUNTRY, NULL AS STATE, NULL AS DESTINATION_CITY,
                                            NULL AS PURPOSE_OF_THE_TRIP, NULL AS TRAVEL_START_DATE, NULL AS TRAVEL_END_DATE, NULL AS TRAVEL_STATUS_CODE, NULL AS TRAVEL_STATUS,
                                            NULL AS DOCUMENT_STATUS, NULL as ENTITY_ID,
											NULL AS PROJECT_TITLE,
                                            NULL AS PROJECT_NUMBER,
											T1.COI_PROJECT_TYPE_CODE,T9.DESCRIPTION AS PROJECT_TYPE, T9.BADGE_COLOR,T9.PROJECT_ICON,NULL AS DOCUMENT_NUMBER,NULL AS PROJECT_ID ');

    		SET ALL_DISC_JOIN_CONDITION = CONCAT(' FROM COI_DISCLOSURE T1
    		                            INNER JOIN COI_DISCL_PROJECTS T11 ON T11.DISCLOSURE_ID = T1.DISCLOSURE_ID
    		                            INNER JOIN COI_DISCLOSURE_FCOI_TYPE T2 ON T2.FCOI_TYPE_CODE = T1.FCOI_TYPE_CODE
                                        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT
                                        LEFT JOIN COI_CONFLICT_STATUS_TYPE T4 ON T4.CONFLICT_STATUS_CODE = T1.CONFLICT_STATUS_CODE
                                        INNER JOIN COI_DISPOSITION_STATUS_TYPE T5 ON T5.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
                                        INNER JOIN COI_REVIEW_STATUS_TYPE T6 ON T6.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE
                                        LEFT JOIN COI_PROJECT_TYPE T9 ON T9.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
                                        WHERE T1.FCOI_TYPE_CODE IN (1,3) AND T1.PERSON_ID = ''', AV_PERSON_ID,'''
										UNION
										SELECT DISTINCT T1.DISCLOSURE_ID, NULL AS TRAVEL_DISCLOSURE_ID, NULL AS CONSULTING_DISCLOSURE_ID, T1.UPDATE_TIMESTAMP, T1.VERSION_STATUS, T1.FCOI_TYPE_CODE,
                                            T2.DESCRIPTION AS FCOI_TYPE, T1.HOME_UNIT, T3.UNIT_NAME, T1.EXPIRATION_DATE, NULL AS IS_EXTENDED, T1.CERTIFIED_AT, T1.CONFLICT_STATUS_CODE,
                                            T4.DESCRIPTION AS CONFLICT_STATUS, T1.DISPOSITION_STATUS_CODE, T5.DESCRIPTION AS DISPOSITION_STATUS, T1.REVIEW_STATUS_CODE,
                                            T6.DESCRIPTION AS REVIEW_STATUS, NULL AS ENTITY_NAME, NULL AS DESTINATION_COUNTRY, NULL AS STATE, NULL AS DESTINATION_CITY,
                                            NULL AS PURPOSE_OF_THE_TRIP, NULL AS TRAVEL_START_DATE, NULL AS TRAVEL_END_DATE, NULL AS TRAVEL_STATUS_CODE, NULL AS TRAVEL_STATUS,
                                            NULL AS DOCUMENT_STATUS, NULL as ENTITY_ID,
                                            CASE T11.MODULE_CODE WHEN 3 THEN T7.TITLE WHEN 1 THEN T8.TITLE ELSE NULL END AS PROJECT_TITLE,
                                            CASE T11.MODULE_CODE WHEN 3 THEN T7.EXTERNAL_SYSTEM_REF_ID WHEN 1 THEN T8.AWARD_NUMBER ELSE NULL END AS PROJECT_NUMBER,
											T1.COI_PROJECT_TYPE_CODE,T9.DESCRIPTION AS PROJECT_TYPE, T9.BADGE_COLOR,T9.PROJECT_ICON
											,CASE T11.MODULE_CODE WHEN 3 THEN T7.DOCUMENT_NUMBER WHEN 1 THEN T8.DOCUMENT_NUMBER ELSE NULL END AS DOCUMENT_NUMBER,
											CASE T11.MODULE_CODE WHEN 3 THEN T7.EXTERNAL_SYSTEM_REF_ID WHEN 1 THEN T8.EXTERNAL_SYSTEM_REF_ID ELSE NULL END AS PROJECT_ID 											
											 FROM COI_DISCLOSURE T1
    		                            INNER JOIN COI_DISCL_PROJECTS T11 ON T11.DISCLOSURE_ID = T1.DISCLOSURE_ID
    		                            INNER JOIN COI_DISCLOSURE_FCOI_TYPE T2 ON T2.FCOI_TYPE_CODE = T1.FCOI_TYPE_CODE
                                        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT
                                        LEFT JOIN COI_CONFLICT_STATUS_TYPE T4 ON T4.CONFLICT_STATUS_CODE = T1.CONFLICT_STATUS_CODE
                                        INNER JOIN COI_DISPOSITION_STATUS_TYPE T5 ON T5.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
                                        INNER JOIN COI_REVIEW_STATUS_TYPE T6 ON T6.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE
                                        LEFT JOIN COI_PROJECT_PROPOSAL_V T7 ON (T7.EXTERNAL_SYSTEM_REF_ID = CAST(T11.MODULE_ITEM_KEY AS UNSIGNED) AND T11.MODULE_CODE = 3)
                                        LEFT JOIN COI_PROJECT_AWARD_V T8 ON T8.AWARD_NUMBER = T11.MODULE_ITEM_KEY AND T11.MODULE_CODE = 1
										LEFT JOIN COI_PROJECT_TYPE T9 ON T9.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
                                        WHERE T1.FCOI_TYPE_CODE = 2 AND T1.PERSON_ID = ''', AV_PERSON_ID,'''
										');
        ELSE IF AV_FILTER_TYPE = 'FCOI' THEN

    		SET DISC_SELECTED_FIELD_LIST= CONCAT('T1.DISCLOSURE_ID, NULL AS TRAVEL_DISCLOSURE_ID, NULL AS CONSULTING_DISCLOSURE_ID, T1.UPDATE_TIMESTAMP, T1.VERSION_STATUS, T1.FCOI_TYPE_CODE,
                                            T2.DESCRIPTION AS FCOI_TYPE, T1.HOME_UNIT, T3.UNIT_NAME, T1.EXPIRATION_DATE, T1.IS_EXTENDED, T1.CERTIFIED_AT, T1.CONFLICT_STATUS_CODE,
                                            T4.DESCRIPTION AS CONFLICT_STATUS, T1.DISPOSITION_STATUS_CODE, T5.DESCRIPTION AS DISPOSITION_STATUS, T1.REVIEW_STATUS_CODE,
                                            T6.DESCRIPTION AS REVIEW_STATUS, NULL AS ENTITY_NAME, NULL AS DESTINATION_COUNTRY, NULL AS STATE, NULL AS DESTINATION_CITY,
                                            NULL AS PURPOSE_OF_THE_TRIP, NULL AS TRAVEL_START_DATE, NULL AS TRAVEL_END_DATE, NULL AS TRAVEL_STATUS_CODE, NULL AS TRAVEL_STATUS,
                                            NULL AS DOCUMENT_STATUS, NULL as ENTITY_ID,
                                            NULL AS PROJECT_TITLE,
                                            NULL AS PROJECT_NUMBER,
											T1.COI_PROJECT_TYPE_CODE,T9.DESCRIPTION AS PROJECT_TYPE, T9.BADGE_COLOR,T9.PROJECT_ICON
											,NULL AS DOCUMENT_NUMBER,NULL AS PROJECT_ID ');

    		SET DISC_JOIN_CONDITION = CONCAT(' FROM COI_DISCLOSURE T1
    		                            INNER JOIN COI_DISCL_PROJECTS T11 ON T11.DISCLOSURE_ID = T1.DISCLOSURE_ID
    		                            INNER JOIN COI_DISCLOSURE_FCOI_TYPE T2 ON T2.FCOI_TYPE_CODE = T1.FCOI_TYPE_CODE
                                        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT
                                        LEFT JOIN COI_CONFLICT_STATUS_TYPE T4 ON T4.CONFLICT_STATUS_CODE = T1.CONFLICT_STATUS_CODE
                                        INNER JOIN COI_DISPOSITION_STATUS_TYPE T5 ON T5.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
                                        INNER JOIN COI_REVIEW_STATUS_TYPE T6 ON T6.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE
                                        LEFT JOIN COI_PROJECT_TYPE T9 ON T9.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
                                        WHERE T1.PERSON_ID = ''', AV_PERSON_ID,'''');
        ELSE IF AV_FILTER_TYPE = 'PROJECT' THEN

    		SET DISC_SELECTED_FIELD_LIST= CONCAT('T1.DISCLOSURE_ID, NULL AS TRAVEL_DISCLOSURE_ID, NULL AS CONSULTING_DISCLOSURE_ID, T1.UPDATE_TIMESTAMP, T1.VERSION_STATUS, T1.FCOI_TYPE_CODE,
                                            T2.DESCRIPTION AS FCOI_TYPE, T1.HOME_UNIT, T3.UNIT_NAME, T1.EXPIRATION_DATE, NULL AS IS_EXTENDED, T1.CERTIFIED_AT, T1.CONFLICT_STATUS_CODE,
                                            T4.DESCRIPTION AS CONFLICT_STATUS, T1.DISPOSITION_STATUS_CODE, T5.DESCRIPTION AS DISPOSITION_STATUS, T1.REVIEW_STATUS_CODE,
                                            T6.DESCRIPTION AS REVIEW_STATUS, NULL AS ENTITY_NAME, NULL AS DESTINATION_COUNTRY, NULL AS STATE, NULL AS DESTINATION_CITY,
                                            NULL AS PURPOSE_OF_THE_TRIP, NULL AS TRAVEL_START_DATE, NULL AS TRAVEL_END_DATE, NULL AS TRAVEL_STATUS_CODE, NULL AS TRAVEL_STATUS,
                                            NULL AS DOCUMENT_STATUS, NULL as ENTITY_ID,
                                            CASE T11.MODULE_CODE WHEN 3 THEN T7.TITLE WHEN 1 THEN T8.TITLE ELSE NULL END AS PROJECT_TITLE,
                                            CASE T11.MODULE_CODE WHEN 3 THEN T7.EXTERNAL_SYSTEM_REF_ID WHEN 1 THEN T8.AWARD_NUMBER ELSE NULL END AS PROJECT_NUMBER,
											T1.COI_PROJECT_TYPE_CODE,T9.DESCRIPTION AS PROJECT_TYPE, T9.BADGE_COLOR,T9.PROJECT_ICON
											,CASE T11.MODULE_CODE WHEN 3 THEN T7.DOCUMENT_NUMBER WHEN 1 THEN T8.DOCUMENT_NUMBER ELSE NULL END AS DOCUMENT_NUMBER,
											CASE T11.MODULE_CODE WHEN 3 THEN T7.EXTERNAL_SYSTEM_REF_ID WHEN 1 THEN T8.EXTERNAL_SYSTEM_REF_ID ELSE NULL END AS PROJECT_ID ');

    		SET DISC_JOIN_CONDITION = CONCAT(' FROM COI_DISCLOSURE T1
    		                            INNER JOIN COI_DISCL_PROJECTS T11 ON T11.DISCLOSURE_ID = T1.DISCLOSURE_ID
    		                            INNER JOIN COI_DISCLOSURE_FCOI_TYPE T2 ON T2.FCOI_TYPE_CODE = T1.FCOI_TYPE_CODE
                                        INNER JOIN UNIT T3 ON T3.UNIT_NUMBER = T1.HOME_UNIT
                                        LEFT JOIN COI_CONFLICT_STATUS_TYPE T4 ON T4.CONFLICT_STATUS_CODE = T1.CONFLICT_STATUS_CODE
                                        INNER JOIN COI_DISPOSITION_STATUS_TYPE T5 ON T5.DISPOSITION_STATUS_CODE = T1.DISPOSITION_STATUS_CODE
                                        INNER JOIN COI_REVIEW_STATUS_TYPE T6 ON T6.REVIEW_STATUS_CODE = T1.REVIEW_STATUS_CODE
                                        LEFT JOIN COI_PROJECT_PROPOSAL_V T7 ON (T7.EXTERNAL_SYSTEM_REF_ID = CAST(T11.MODULE_ITEM_KEY AS UNSIGNED) AND T11.MODULE_CODE = 3)
                                        LEFT JOIN COI_PROJECT_AWARD_V T8 ON T8.AWARD_NUMBER = T11.MODULE_ITEM_KEY AND T11.MODULE_CODE = 1
										LEFT JOIN COI_PROJECT_TYPE T9 ON T9.COI_PROJECT_TYPE_CODE = T1.COI_PROJECT_TYPE_CODE
                                        WHERE T1.PERSON_ID = ''', AV_PERSON_ID,'''');
        END IF;
        END IF;
        END IF;
    	IF AV_FILTER_TYPE = 'ALL' OR AV_FILTER_TYPE = 'TRAVEL' THEN

    		SET TRAVEL_SELECTED_FIELD_LIST= CONCAT('NULL AS DISCLOSURE_ID, T21.TRAVEL_DISCLOSURE_ID, NULL AS CONSULTING_DISCLOSURE_ID, T21.UPDATE_TIMESTAMP, T21.VERSION_STATUS, NULL AS  FCOI_TYPE_CODE,
                                            NULL AS FCOI_TYPE, NULL AS HOME_UNIT, NULL AS UNIT_NAME, T21.EXPIRATION_DATE, NULL AS IS_EXTENDED, T21.CERTIFIED_AT AS CERTIFIED_AT, NULL AS CONFLICT_STATUS_CODE,
                                            NULL AS CONFLICT_STATUS, NULL AS DISPOSITION_STATUS_CODE, NULL AS DISPOSITION_STATUS, NULL AS REVIEW_STATUS_CODE, NULL AS REVIEW_STATUS,
                                            T22.PRIMARY_NAME as ENTITY_NAME, NULL AS DESTINATION_COUNTRY, NULL AS STATE, NULL AS DESTINATION_CITY, T41.VALUE AS PURPOSE_OF_THE_TRIP,
                                            AGGREGATED_DATES.MIN_STAY_START_DATE AS TRAVEL_START_DATE, AGGREGATED_DATES.MAX_STAY_END_DATE AS TRAVEL_END_DATE, NULL AS TRAVEL_STATUS_CODE, 
                                            NULL AS TRAVEL_STATUS, T46.DESCRIPTION AS DOCUMENT_STATUS, T22.ENTITY_ID,
                                            NULL AS PROJECT_TITLE, NULL AS PROJECT_NUMBER,NULL AS COI_PROJECT_TYPE_CODE,NULL AS PROJECT_TYPE,NULL AS BADGE_COLOR,NULL AS PROJECT_ICON
											,NULL AS DOCUMENT_NUMBER,NULL AS PROJECT_ID ');
    		SET TRAVEL_DISC_JOIN_CONDITION = CONCAT(' FROM COI_TRAVEL_DISCLOSURE T21 INNER JOIN ENTITY T22 ON T22.ENTITY_ID = T21.ENTITY_ID
                                            LEFT JOIN (SELECT FCA.*, ROW_NUMBER() OVER (PARTITION BY MODULE_ITEM_KEY ORDER BY CUSTOM_DATA_ELEMENTS_ID DESC) AS rn
                                                FROM FB_COMP_CUSTOM_ELEMENT_ANSWER FCA
                                                JOIN FB_COMP_CUSTOM_ELEMENT FCE ON FCA.CUSTOM_DATA_ELEMENTS_ID = FCE.CUSTOM_DATA_ELEMENTS_ID
                                                WHERE MODULE_ITEM_CODE = 24 AND CUSTOM_ELEMENT_NAME = "Purpose" 
                                            ) T41 ON T41.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID AND T41.rn = 1
                                            LEFT JOIN (SELECT FCA.*, ROW_NUMBER() OVER (PARTITION BY MODULE_ITEM_KEY ORDER BY CUSTOM_DATA_ELEMENTS_ID DESC) AS rn
                                                FROM FB_COMP_CUSTOM_ELEMENT_ANSWER FCA
                                                JOIN FB_COMP_CUSTOM_ELEMENT FCE ON FCA.CUSTOM_DATA_ELEMENTS_ID = FCE.CUSTOM_DATA_ELEMENTS_ID
                                                WHERE MODULE_ITEM_CODE = 24 AND CUSTOM_ELEMENT_NAME = "Trip Title" 
                                            ) T43 ON T43.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID AND T43.rn = 1
                                            LEFT JOIN (SELECT FCA.*,ROW_NUMBER() OVER (PARTITION BY MODULE_ITEM_KEY ORDER BY CUSTOM_DATA_ELEMENTS_ID DESC) AS rn
                                                FROM FB_COMP_CUSTOM_ELEMENT_ANSWER FCA
                                                JOIN FB_COMP_CUSTOM_ELEMENT FCE ON FCA.CUSTOM_DATA_ELEMENTS_ID = FCE.CUSTOM_DATA_ELEMENTS_ID
                                                WHERE MODULE_ITEM_CODE = 24 and CUSTOM_ELEMENT_NAME = "Reimbursed Cost" 
                                            ) T45 ON T45.MODULE_ITEM_KEY = T21.TRAVEL_DISCLOSURE_ID AND T45.rn = 1
                                            LEFT JOIN (
											SELECT 
												TRAVEL_DISCLOSURE_ID, 
												MIN(STAY_START_DATE) AS MIN_STAY_START_DATE, 
												MAX(STAY_END_DATE) AS MAX_STAY_END_DATE
											FROM COI_TRAVEL_DESTINATIONS
											GROUP BY TRAVEL_DISCLOSURE_ID
											) AGGREGATED_DATES ON AGGREGATED_DATES.TRAVEL_DISCLOSURE_ID = T21.TRAVEL_DISCLOSURE_ID
											LEFT JOIN COI_TRAVEL_DOCUMENT_STATUS_TYPE T46 ON T46.DOCUMENT_STATUS_CODE = T21.DOCUMENT_STATUS_CODE
                                            LEFT JOIN COI_TRAVEL_STATUS T23 ON T23.TRAVEL_STATUS_CODE = T21.TRAVEL_STATUS_CODE WHERE T21.PERSON_ID = ''',AV_PERSON_ID,'''');
    	END IF;
    	IF AV_FILTER_TYPE = 'ALL' OR AV_FILTER_TYPE = 'CONSULTING' THEN

    		SET CONSULTING_SELECTED_FIELD_LIST= CONCAT('NULL AS DISCLOSURE_ID, NULL AS TRAVEL_DISCLOSURE_ID, T50.DISCLOSURE_ID AS CONSULTING_DISCLOSURE_ID,
    										T50.UPDATE_TIMESTAMP, NULL AS VERSION_STATUS, NULL AS  FCOI_TYPE_CODE,
                                            NULL AS FCOI_TYPE, T51.UNIT_NUMBER AS HOME_UNIT, T51.UNIT_NAME, NULL AS EXPIRATION_DATE, NULL AS IS_EXTENDED, T50.CERTIFIED_AT,
    										NULL AS CONFLICT_STATUS_CODE, NULL AS CONFLICT_STATUS, T56.DISPOSITION_STATUS_CODE, T56.DESCRIPTION AS DISPOSITION_STATUS,
    										T52.REVIEW_STATUS_CODE, T52.DESCRIPTION AS REVIEW_STATUS, 
                                            T54.PRIMARY_NAME as ENTITY_NAME, NULL AS DESTINATION_COUNTRY, NULL AS STATE, NULL AS DESTINATION_CITY, NULL AS PURPOSE_OF_THE_TRIP,
                                            NULL AS TRAVEL_START_DATE, NULL AS TRAVEL_END_DATE, NULL AS TRAVEL_STATUS_CODE, NULL AS TRAVEL_STATUS, NULL AS DOCUMENT_STATUS, T54.ENTITY_ID,
                                            NULL AS PROJECT_TITLE, NULL AS PROJECT_NUMBER, NULL AS COI_PROJECT_TYPE_CODE,NULL AS PROJECT_TYPE,NULL AS BADGE_COLOR,NULL AS PROJECT_ICON
											,NULL AS DOCUMENT_NUMBER,NULL AS PROJECT_ID ');
    		SET CONSULTING_DISC_JOIN_CONDITION = CONCAT(' FROM CONSULTING_DISCLOSURE T50
    										LEFT JOIN PERSON_ENTITY T53 ON T53.PERSON_ENTITY_ID = T50.PERSON_ENTITY_ID
    										LEFT JOIN ENTITY T54 on T54.ENTITY_ID = T53.ENTITY_ID
    										INNER JOIN CONSULTING_DISCL_REVIEW_STATUS_TYPE T52 ON T52.REVIEW_STATUS_CODE = T50.REVIEW_STATUS_CODE
    										INNER JOIN UNIT T51 ON T51.UNIT_NUMBER = T50.HOME_UNIT
    										INNER JOIN CONSULTING_DISCL_DISPOSITION_STATUS_TYPE T56 ON T56.DISPOSITION_STATUS_CODE = T50.DISPOSITION_STATUS_CODE
    										WHERE T50.PERSON_ID = ''',AV_PERSON_ID,'''');

        END IF;

        IF AV_IS_COUNT THEN
          SET LS_DYN_SQL = CONCAT('SELECT COUNT(*) FROM ');
        ELSE
          SET LS_DYN_SQL = CONCAT('SELECT * FROM ');
        END IF;

        IF AV_FILTER_TYPE = 'ALL' THEN
    		SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '(SELECT DISTINCT ',ALL_DISC_SELECTED_FIELD_LIST, ALL_DISC_JOIN_CONDITION, DISC_TAB_QUERY, ' UNION SELECT DISTINCT ',
    							TRAVEL_SELECTED_FIELD_LIST, TRAVEL_DISC_JOIN_CONDITION, TRAVEL_TAB_QUERY, ' UNION SELECT DISTINCT ',
    							CONSULTING_SELECTED_FIELD_LIST, CONSULTING_DISC_JOIN_CONDITION, CONSULTING_TAB_QUERY, ' ) T ORDER BY UPDATE_TIMESTAMP DESC ');

        ELSEIF AV_FILTER_TYPE = 'TRAVEL' THEN
    		SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '(SELECT DISTINCT ',TRAVEL_SELECTED_FIELD_LIST, TRAVEL_DISC_JOIN_CONDITION, TRAVEL_TAB_QUERY, ')T ORDER BY T.UPDATE_TIMESTAMP DESC');

    	ELSEIF AV_FILTER_TYPE = 'CONSULTING' THEN
    		SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '(SELECT DISTINCT ',CONSULTING_SELECTED_FIELD_LIST, CONSULTING_DISC_JOIN_CONDITION, CONSULTING_TAB_QUERY, ')T ORDER BY T.UPDATE_TIMESTAMP DESC');

        ELSE
    		SET LS_DYN_SQL = CONCAT(LS_DYN_SQL, '(SELECT DISTINCT ',DISC_SELECTED_FIELD_LIST, DISC_JOIN_CONDITION, DISC_TAB_QUERY, ') T ORDER BY T.UPDATE_TIMESTAMP DESC');
        END IF;

        SET @QUERY_STATEMENT = LS_DYN_SQL;
    	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
    	EXECUTE EXECUTABLE_STAEMENT;
    END