

CREATE PROCEDURE `PROJECT_DISCLOSURE_RENEWAL_REMINDER`(AV_DAYS INT)
BEGIN
	SELECT 0 AS SUB_MODULE_ITEM_KEY, DISCLOSURE_ID AS MODULE_ITEM_KEY, 8 AS MODULE_CODE, 0 AS SUB_MODULE_CODE FROM COI_DISCLOSURE
	WHERE REVIEW_STATUS_CODE = 4 AND FCOI_TYPE_CODE = 2 AND DATE(EXPIRATION_DATE) = DATE(DATE_ADD(utc_timestamp(),INTERVAL AV_DAYS DAY));
END
