CREATE PROCEDURE `GET_AGREEMENT_DETAILS_FOR_ASSOC`(
    IN AV_MODULE_ITEM_ID INT
)
BEGIN

DECLARE LS_DYN_SQL 				LONGTEXT;

  SET LS_DYN_SQL = CONCAT(
    'WITH SPONSORS AS (',
    '    SELECT AGS.AGREEMENT_REQUEST_ID, S.DISPLAY_NAME AS ORGANIZATION, AGS.SPONSOR_CODE',
    '    FROM AGREEMENT_SPONSOR AGS',
    '    LEFT JOIN SPONSOR S ON S.SPONSOR_CODE = AGS.SPONSOR_CODE',
    '    WHERE AGS.AGREEMENT_SPONSOR_TYPE_CODE = 1',
    '), AGREEMENT_PI AS (',
    '    SELECT AGREEMENT_REQUEST_ID, PERSON_ID AS PI_PERSON_ID, FULL_NAME',
    '    FROM AGREEMENT_PEOPLE',
    '    WHERE PEOPLE_TYPE_ID = 3',
    ') ',
    'SELECT ',
    '''ID'' AS AGREEMENT_REQUEST_ID, ',
    '''Title'' AS TITLE, ',
    '''Status'' AS STATUS, ',
    '''Principal Investigator'' AS PI_FULL_NAME, ',
    '''Lead Unit'' AS UNIT, ',
	'''Type'' AS TYPE, ',
    '''Sponsor'' AS ORGANIZATION '
    'UNION ALL ',
    'SELECT ',
    '    T1.AGREEMENT_REQUEST_ID, ',
    '    T1.TITLE, ',
    'CASE ',
	'    WHEN T1.IS_HOLD = ''Y'' THEN CONCAT(T2.DESCRIPTION, '' - '', ''Compliance Pending'') ',
	'    ELSE T2.DESCRIPTION ',
	'END AS STATUS, ',
   'CASE ',
    '    WHEN COUNT(PI.PI_PERSON_ID) > 1 THEN GROUP_CONCAT(PI.FULL_NAME SEPARATOR '' | '') ',
    '    ELSE MAX(PI.FULL_NAME) ',
    'END AS PI_FULL_NAME, ',
    '    T4.DISPLAY_NAME AS LEAD_UNIT, ',
    '    T3.DESCRIPTION AS TYPE, ',
    '    SPO.ORGANIZATION AS SPONSOR '

    'FROM AGREEMENT_HEADER T1 ',
    'INNER JOIN AGREEMENT_STATUS T2 ON T2.AGREEMENT_STATUS_CODE = T1.AGREEMENT_STATUS_CODE ',
    'INNER JOIN AGREEMENT_TYPE T3 ON T3.AGREEMENT_TYPE_CODE = T1.AGREEMENT_TYPE_CODE ',
    'LEFT JOIN AGREEMENT_PI PI ON T1.AGREEMENT_REQUEST_ID = PI.AGREEMENT_REQUEST_ID ',
    'LEFT JOIN SPONSORS SPO ON T1.AGREEMENT_REQUEST_ID = SPO.AGREEMENT_REQUEST_ID ',
    'INNER JOIN UNIT T4 ON T1.UNIT_NUMBER = T4.UNIT_NUMBER ',
    'WHERE T1.AGREEMENT_REQUEST_ID = ''', AV_MODULE_ITEM_ID, ''''
);

SET @QUERY_STATEMENT = LS_DYN_SQL;
    PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
    EXECUTE EXECUTABLE_STAEMENT;
END
