CREATE PROCEDURE `UPDATE_AGREEMENT_DATA`(
    AV_MODULE_CODE INT,
    AV_SUB_MODULE_CODE INT,
    AV_TRIAGE_HEADER_ID VARCHAR(20),
    AV_AGREEMENT_HEADER_ID INT,
    AV_UPDATE_PERSON_ID VARCHAR(40),
    AV_UPDATE_USER VARCHAR(50)
)
BEGIN

    DECLARE LI_QUES_ANS_HEADER_ID INT;
    DECLARE LS_Q1_ANSWER VARCHAR(100); -- Q1. Does this agreement or award already have an SAP Grant#?
    DECLARE LS_Q2_ANSWER VARCHAR(100); -- Q2. Does this agreement involves Research Activities?
    DECLARE LS_AWARD_NUMBER VARCHAR(100);
    DECLARE LI_PROJECT_ID INT;
    DECLARE LS_AWARD_TYPE_CODE VARCHAR(3);
    DECLARE LS_AGREE_TYPE_CODE VARCHAR(3);
    DECLARE LS_AGREE_CATEGORY_CODE VARCHAR(3);
    DECLARE LI_SOURCE_MODULE_CODE INT;
    DECLARE LS_PROC_NAME VARCHAR(60);
    DECLARE LS_SPONSOR_CODE VARCHAR(10);
    DECLARE LI_IS_NOA_SPONSOR INT DEFAULT 0;
    DECLARE DONE INT DEFAULT FALSE;
	DECLARE LS_UNIT_NUMBER VARCHAR(8);
	DECLARE IS_DEPT_SPONSOR_NOA INT DEFAULT 0;
	DECLARE JHURA_NOA_GROUP_ID INT DEFAULT 301; 
	DECLARE SOM_NOA_GROUP_ID INT DEFAULT 303; 
	DECLARE LS_PROPOSAL_NUMBER VARCHAR(20);
    -- QUESTION_NUMBER will different in across questionnaire.

        SELECT QUESTIONNAIRE_ANS_HEADER_ID INTO LI_QUES_ANS_HEADER_ID FROM QUEST_ANSWER_HEADER
        WHERE MODULE_ITEM_CODE = AV_MODULE_CODE
        AND MODULE_SUB_ITEM_CODE = AV_SUB_MODULE_CODE
        AND MODULE_ITEM_KEY = AV_TRIAGE_HEADER_ID;

        IF LI_QUES_ANS_HEADER_ID IS NOT NULL THEN
       
            SELECT TRIM(T1.ANSWER) INTO LS_Q1_ANSWER
            FROM QUEST_ANSWER T1
            INNER JOIN QUEST_QUESTION T2 ON T1.QUESTION_ID = T2.QUESTION_ID
            WHERE T1.QUESTIONNAIRE_ANS_HEADER_ID = LI_QUES_ANS_HEADER_ID
            AND T2.QUESTION_NUMBER = 6865; -- Q1. Does this agreement or award already have an SAP Grant#?

             IF LS_Q1_ANSWER <> '' AND LS_Q1_ANSWER IS NOT NULL AND UPPER(LS_Q1_ANSWER) = 'YES'  THEN

                SELECT TRIM(T1.ANSWER_LOOKUP_CODE) INTO LS_AWARD_NUMBER FROM QUEST_ANSWER T1
                INNER JOIN QUEST_QUESTION T2 ON T1.QUESTION_ID = T2.QUESTION_ID
                WHERE T1.QUESTIONNAIRE_ANS_HEADER_ID = LI_QUES_ANS_HEADER_ID
                AND T2.QUESTION_NUMBER = 6869; -- Q1 -> yes -> Please search for and choose the relevant Award.

                IF LS_AWARD_NUMBER IS NOT NULL THEN

                    SELECT AWARD_ID,  AWARD_TYPE_CODE, SPONSOR_CODE, LEAD_UNIT_NUMBER INTO LI_PROJECT_ID, LS_AWARD_TYPE_CODE, LS_SPONSOR_CODE, LS_UNIT_NUMBER
                    FROM AWARD WHERE AWARD_NUMBER = LS_AWARD_NUMBER AND ((AWARD_SEQUENCE_STATUS ='ACTIVE') OR (AWARD_SEQUENCE_STATUS ='PENDING' AND AWARD_DOCUMENT_TYPE_CODE = 1));

                    INSERT INTO ASSOC_AGREEMENT (AGREEMENT_ID, ASSOC_RELATION_TYPE_CODE, ASSOC_CONFIG_CODE, MODULE_CODE, MODULE_ITEM_KEY, MODULE_ITEM_ID, ASSOC_TYPE, UPDATE_USER, UPDATE_TIMESTAMP, IS_IMPORTED) 
                    VALUES (AV_AGREEMENT_HEADER_ID, '6', '1', '1', LS_AWARD_NUMBER , LI_PROJECT_ID,'DIRECT', AV_UPDATE_PERSON_ID, UTC_TIMESTAMP(), 'Y');

                    SET LI_SOURCE_MODULE_CODE = 1;
                END IF;                
             END IF;
           
            IF LS_Q1_ANSWER IS NULL OR LS_Q1_ANSWER = '' OR UPPER(LS_Q1_ANSWER) = 'NO' THEN
                
                SELECT TRIM(T1.ANSWER) INTO LS_Q2_ANSWER FROM QUEST_ANSWER T1
                INNER JOIN QUEST_QUESTION T2 ON T1.QUESTION_ID = T2.QUESTION_ID
                WHERE T1.QUESTIONNAIRE_ANS_HEADER_ID = LI_QUES_ANS_HEADER_ID
                AND T2.QUESTION_NUMBER = 6866; -- Q1.2 Was a Fibi Proposal Development record (PD) submitted for this agreement/award?

                IF LS_Q2_ANSWER <> '' AND LS_Q2_ANSWER IS NOT NULL AND UPPER(LS_Q2_ANSWER) = 'YES'  THEN

                    SELECT TRIM(T1.ANSWER_LOOKUP_CODE) INTO LI_PROJECT_ID
                    FROM QUEST_ANSWER T1
                    INNER JOIN QUEST_QUESTION T2 ON T1.QUESTION_ID = T2.QUESTION_ID
                    WHERE T1.QUESTIONNAIRE_ANS_HEADER_ID = LI_QUES_ANS_HEADER_ID
                    AND T2.QUESTION_NUMBER = 6868; -- Q1.2 -> yes -> Please search for and choose the relevant IPN.

                    IF LI_PROJECT_ID IS NOT NULL THEN
                        SELECT PROPOSAL_NUMBER, AWARD_TYPE_CODE, SPONSOR_CODE, HOME_UNIT_NUMBER INTO  LS_PROPOSAL_NUMBER, LS_AWARD_TYPE_CODE, LS_SPONSOR_CODE, LS_UNIT_NUMBER
                        FROM PROPOSAL WHERE PROPOSAL_ID = LI_PROJECT_ID;

                        INSERT INTO ASSOC_AGREEMENT (AGREEMENT_ID, ASSOC_RELATION_TYPE_CODE, ASSOC_CONFIG_CODE, MODULE_CODE, MODULE_ITEM_KEY, MODULE_ITEM_ID, ASSOC_TYPE, UPDATE_USER, UPDATE_TIMESTAMP, IS_IMPORTED) 
                        VALUES (AV_AGREEMENT_HEADER_ID, '6', '5', '2', LS_PROPOSAL_NUMBER , LI_PROJECT_ID,'DIRECT', AV_UPDATE_PERSON_ID, UTC_TIMESTAMP(), 'Y');

                        SET LI_SOURCE_MODULE_CODE = 2;
                    END IF;
                END IF;

            END IF;

         IF LS_SPONSOR_CODE IS NOT NULL AND LS_UNIT_NUMBER IS NOT NULL THEN
			-- Check if unit falls under JHURA or SOM, then check sponsor mapping
				-- Check JHURA
				IF EXISTS (
					SELECT 1 FROM UNIT_WITH_CHILDREN
					WHERE UNIT_NUMBER = 'JHURA' AND CHILD_UNIT_NUMBER = LS_UNIT_NUMBER
				) THEN
					SELECT COUNT(*) INTO IS_DEPT_SPONSOR_NOA
					FROM SPONSOR_HIERARCHY
					WHERE SPONSOR_CODE = LS_SPONSOR_CODE
					  AND SPONSOR_ORIGINATING_GROUP_ID = JHURA_NOA_GROUP_ID;
				
				-- Check SOM
				ELSEIF EXISTS (
					SELECT 1 FROM UNIT_WITH_CHILDREN
					WHERE UNIT_NUMBER = 'SOM' AND CHILD_UNIT_NUMBER = LS_UNIT_NUMBER
				) THEN
					SELECT COUNT(*) INTO IS_DEPT_SPONSOR_NOA
					FROM SPONSOR_HIERARCHY
					WHERE SPONSOR_CODE = LS_SPONSOR_CODE
					  AND SPONSOR_ORIGINATING_GROUP_ID = SOM_NOA_GROUP_ID;
				END IF; 
         END IF;

				-- Set AGREEMENT_TYPE_CODE based on department-specific sponsor match
		IF LS_AWARD_TYPE_CODE = '1' AND IS_DEPT_SPONSOR_NOA > 0 THEN
			SET LS_AGREE_TYPE_CODE = '62'; -- NOA
		ELSE
		  SELECT AGREEMENT_TYPE_CODE INTO LS_AGREE_TYPE_CODE FROM AGREEMENT_TYPE WHERE ASSOCIATION_TYPE_CODE = LS_AWARD_TYPE_CODE
		  AND CATEGORY_CODE = (SELECT CATEGORY_CODE FROM AGREEMENT_HEADER WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_HEADER_ID );
		END IF;

            IF LI_PROJECT_ID IS NOT NULL THEN
                UPDATE AGREEMENT_HEADER 
                SET AGREEMENT_TYPE_CODE = LS_AGREE_TYPE_CODE
                WHERE AGREEMENT_REQUEST_ID = AV_AGREEMENT_HEADER_ID;
            END IF;

            IF  LI_SOURCE_MODULE_CODE IS NOT NULL AND LI_PROJECT_ID IS NOT NULL AND AV_AGREEMENT_HEADER_ID IS NOT NULL AND AV_UPDATE_USER IS NOT NULL THEN
            BEGIN
                DECLARE MIGRATION_CURSOR CURSOR FOR
                SELECT MIGRATION_ROUTINE_NAME  FROM ASSOC_DATA_MIGRATION WHERE IS_ACTIVE = 'Y' AND MIGRATION_TYPE = 'PROCEDURE' AND DESTINATION_MODULE_CODE = 13 AND SOURCE_MODULE_CODE = LI_SOURCE_MODULE_CODE;
                DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
                    OPEN MIGRATION_CURSOR;
                        READ_LOOP: LOOP
                            FETCH MIGRATION_CURSOR INTO LS_PROC_NAME;
                            IF DONE THEN
                                LEAVE READ_LOOP;
                            END IF;
                            
                            SET @query = CONCAT("CALL ", LS_PROC_NAME, " (", LI_PROJECT_ID, ",", AV_AGREEMENT_HEADER_ID, ",", LI_SOURCE_MODULE_CODE, ",", 13, ",'", AV_UPDATE_USER,"')");
                            PREPARE stmt FROM @query;
                            EXECUTE stmt;
                            DEALLOCATE PREPARE stmt;
                        END LOOP;
                    CLOSE MIGRATION_CURSOR;
            END;
            END IF;    
        END IF;
END
