

--
--  `fb_comp_custom_element_answer`
--

DROP TABLE IF EXISTS `fb_comp_custom_element_answer`;

CREATE TABLE `fb_comp_custom_element_answer` (
  `CUSTOM_DATA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOM_DATA_ELEMENTS_ID` int(11) DEFAULT NULL,
  `MODULE_ITEM_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(255) DEFAULT NULL,
  `MODULE_SUB_ITEM_CODE` int(11) DEFAULT NULL,
  `MODULE_SUB_ITEM_KEY` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `VALUE` varchar(4000) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOM_DATA_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx2` (`MODULE_ITEM_KEY`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx3` (`CUSTOM_DATA_ELEMENTS_ID`),
  KEY `FB_COMP_CUSTOM_ELEMENT_ANSWER_idx4` (`MODULE_ITEM_KEY`,`CUSTOM_DATA_ELEMENTS_ID`)
);

