DROP TABLE IF EXISTS `fb_comp_custom_element_options`;

CREATE TABLE `fb_comp_custom_element_options` (
  `CUSTOM_DATA_OPTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CUSTOM_DATA_ELEMENTS_ID` int(11) DEFAULT NULL,
  `OPTION_NAME` varchar(1000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`CUSTOM_DATA_OPTION_ID`)
);
