

--
--  `fb_quest_answer_header`
--

DROP TABLE IF EXISTS `fb_quest_answer_header`;

CREATE TABLE `fb_quest_answer_header` (
  `QUESTIONNAIRE_ANS_HEADER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `QUESTIONNAIRE_ID` int(11) DEFAULT NULL,
  `MODULE_ITEM_CODE` int(11) DEFAULT NULL,
  `MODULE_SUB_ITEM_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `MODULE_SUB_ITEM_KEY` varchar(20) DEFAULT NULL,
  `QUESTIONNAIRE_COMPLETED_FLAG` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`QUESTIONNAIRE_ANS_HEADER_ID`),
  KEY `FB_QUEST_ANSWER_HEADER_FK1` (`QUESTIONNAIRE_ID`),
  CONSTRAINT `FB_QUEST_ANSWER_HEADER_FK1` FOREIGN KEY (`QUESTIONNAIRE_ID`) REFERENCES `quest_header` (`QUESTIONNAIRE_ID`)
);

