
DROP TABLE IF EXISTS `form_builder_section_component`;

CREATE TABLE `form_builder_section_component` (
  `FORM_BUILDER_SECT_COMP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FORM_BUILDER_SECTION_ID` int(11) NOT NULL,
  `COMPONENT_TYPE_CODE` varchar(3) NOT NULL,
  `COMPONENT_ORDER_NUMBER` int(11) NOT NULL,
  `COMPONENT_DATA` varchar(1000) DEFAULT NULL,
  `COMPONENT_REF_ID` varchar(10) DEFAULT NULL,
  `DESCRIPTION` varchar(300) NOT NULL,
  `HEADER_INSTRUCTION` varchar(4000) DEFAULT NULL,
  `FOOTER_INSTRUCTION` varchar(4000) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) NOT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  `UPDATE_USER` varchar(60) NOT NULL,
  `VALIDATION_MESSAGE` varchar(1000) DEFAULT NULL,
  `LABEL` varchar(300) DEFAULT NULL,
  `IS_MANDATORY` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`FORM_BUILDER_SECT_COMP_ID`),
  KEY `FORM_BUILDER_SECT_COMP_FK1` (`FORM_BUILDER_SECTION_ID`),
  KEY `FORM_BUILDER_SECT_COMP_FK2` (`COMPONENT_TYPE_CODE`),
  CONSTRAINT `FORM_BUILDER_SECT_COMP_FK1` FOREIGN KEY (`FORM_BUILDER_SECTION_ID`) REFERENCES `form_builder_section` (`FORM_BUILDER_SECTION_ID`),
  CONSTRAINT `FORM_BUILDER_SECT_COMP_FK2` FOREIGN KEY (`COMPONENT_TYPE_CODE`) REFERENCES `form_section_component_type` (`COMPONENT_TYPE_CODE`)
) ;