
DROP TABLE IF EXISTS `kpi_template`;

CREATE TABLE `kpi_template` (
  `KPI_TEMPLATE_ID` int(11) NOT NULL,
  `KPI_TEMPLATE_HEADER_ID` int(11) DEFAULT NULL,
  `KPI_TYPE_CODE` varchar(3) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_TEMPLATE_ID`),
  KEY `KPI_TEMPLATE_FK` (`KPI_TEMPLATE_HEADER_ID`),
  CONSTRAINT `KPI_TEMPLATE_FK` FOREIGN KEY (`KPI_TEMPLATE_HEADER_ID`) REFERENCES `kpi_template_header` (`KPI_TEMPLATE_HEADER_ID`)
) ;