DROP TABLE IF EXISTS `progress_report_kpi_grant_specific`;

CREATE TABLE `progress_report_kpi_grant_specific` (
  `KPI_GRANT_SPECIFIC_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` int(11) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `TYPE` varchar(200) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_GRANT_SPECIFIC_ID`)
) ;
