
DROP TABLE IF EXISTS `progress_report_status`;

CREATE TABLE `progress_report_status` (
  `PROGRESS_REPORT_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`PROGRESS_REPORT_STATUS_CODE`)
) ;