
DROP TABLE IF EXISTS `progress_report_kpi_technologies_deployed`;

CREATE TABLE `progress_report_kpi_technologies_deployed` (
  `KPI_TECHNOLOGIES_DEPLOYED_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` decimal(10,0) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `NAME_OF_COMPANY` varchar(200) DEFAULT NULL,
  `COUNTRY_CODE` varchar(3) DEFAULT NULL,
  `DATE_OF_DEPLOYING` datetime DEFAULT NULL,
  `COMPANY_UEN` varchar(200) DEFAULT NULL,
  `DETAILS_OF_TECHNOLOGIES` varchar(200) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_TECHNOLOGIES_DEPLOYED_ID`),
  KEY `KPI_TECHNOLOGIES_DEPLOYED_FK1` (`COUNTRY_CODE`),
  CONSTRAINT `KPI_TECHNOLOGIES_DEPLOYED_FK1` FOREIGN KEY (`COUNTRY_CODE`) REFERENCES `country` (`COUNTRY_CODE`)
) ;