DROP TABLE IF EXISTS `progress_report_kpi_inkind_contributions`;

CREATE TABLE `progress_report_kpi_inkind_contributions` (
  `KPI_INKIND_CONTRIBUTIONS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` int(11) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `NAME_OF_COMPANY` varchar(200) DEFAULT NULL,
  `COUNTRY_CODE` varchar(3) DEFAULT NULL,
  `DATE_OF_CONTRIBUTION` datetime DEFAULT NULL,
  `COMPANY_UEN` varchar(200) DEFAULT NULL,
  `AMOUNT` decimal(12,2) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_INKIND_CONTRIBUTIONS_ID`),
  KEY `KPI_INKIND_CONTRIBUTIONS_FK1` (`COUNTRY_CODE`),
  CONSTRAINT `KPI_INKIND_CONTRIBUTIONS_FK1` FOREIGN KEY (`COUNTRY_CODE`) REFERENCES `country` (`COUNTRY_CODE`)
) ;