
DROP TABLE IF EXISTS `progress_report_kpi_competitive_grants`;

CREATE TABLE `progress_report_kpi_competitive_grants` (
  `KPI_COMPETITIVE_GRANTS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` int(11) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `PROJECT_TITLE` varchar(1000) DEFAULT NULL,
  `PROJECT_DESCRIPTION` varchar(200) DEFAULT NULL,
  `PROJECT_START_DATE` datetime DEFAULT NULL,
  `PROJECT_END_DATE` datetime DEFAULT NULL,
  `NAME_OF_GRANT_RECEIVED` varchar(200) DEFAULT NULL,
  `PROJECT_REFERENCE_NO` varchar(30) DEFAULT NULL,
  `SPONSOR_CODE` varchar(100) DEFAULT NULL,
  `RECIPIENT_OF_GRANT` varchar(100) DEFAULT NULL,
  `HOST_INSTITUTION` varchar(100) DEFAULT NULL,
  `DIRECT_COST` decimal(12,2) DEFAULT NULL,
  `INDIRECT_COST` decimal(12,2) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_COMPETITIVE_GRANTS_ID`),
  KEY `KPI_COMPETITIVE_GRANTS_FK1` (`SPONSOR_CODE`),
  CONSTRAINT `KPI_COMPETITIVE_GRANTS_FK1` FOREIGN KEY (`SPONSOR_CODE`) REFERENCES `sponsor` (`SPONSOR_CODE`)
) ;