
DROP TABLE IF EXISTS `progress_report_kpi_manpower_development`;

CREATE TABLE `progress_report_kpi_manpower_development` (
  `KPI_MANPOWER_DEVELOPMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` int(11) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `NAME_OF_STUDENT` varchar(200) DEFAULT NULL,
  `CITIZENSHIP` varchar(200) DEFAULT NULL,
  `CURRENT_STATUS_CODE` varchar(3) DEFAULT NULL,
  `DATE_ENROLLED` datetime DEFAULT NULL,
  `DATE_GRADUATED` datetime DEFAULT NULL,
  `DATE_OF_JOINING` datetime DEFAULT NULL,
  `DATE_OF_LEAVING` datetime DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_MANPOWER_DEVELOPMENT_ID`),
  KEY `KPI_MANPOWER_DEVELOPMENT_FK1` (`CURRENT_STATUS_CODE`),
  CONSTRAINT `KPI_MANPOWER_DEVELOPMENT_FK1` FOREIGN KEY (`CURRENT_STATUS_CODE`) REFERENCES `kpi_manpower_development_current_status` (`CURRENT_STATUS_CODE`)
) ;