DROP TABLE IF EXISTS `progress_report_kpi_conference_presentation`;

CREATE TABLE `progress_report_kpi_conference_presentation` (
  `KPI_CONFERENCE_PRESENTATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` int(11) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `NAME_OF_PRESENTER` varchar(200) DEFAULT NULL,
  `TITLE` varchar(300) DEFAULT NULL,
  `CONFERENCE_TITLE` varchar(200) DEFAULT NULL,
  `ORGANISER` varchar(200) DEFAULT NULL,
  `CONFERENCE_LOCATION` varchar(200) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_CONFERENCE_PRESENTATION_ID`)
) ;