DROP TABLE IF EXISTS `progress_report_kpi_post_docs_employed`;

CREATE TABLE `progress_report_kpi_post_docs_employed` (
  `KPI_POST_DOCS_EMPLOYED_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KPI_SUMMARY_ID` int(11) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `KPI_CRITERIA_TYPE_CODE` varchar(3) DEFAULT NULL,
  `EMPLOYEE_NAME` varchar(90) DEFAULT NULL,
  `EMPLOYMENT_START_DATE` datetime DEFAULT NULL,
  `NATIONALITY` varchar(30) DEFAULT NULL,
  `PERMANENT_RESIDENCE` varchar(30) DEFAULT NULL,
  `IDENTIFICATION_NUMBER` varchar(50) DEFAULT NULL,
  `COMMENTS` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`KPI_POST_DOCS_EMPLOYED_ID`)
) ;
