INSERT INTO agreement_sponsor_contct_type (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Primary',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO agreement_sponsor_contct_type (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Technical',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO agreement_sponsor_contct_type (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Legal',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO agreement_sponsor_contct_type (SPONSOR_CONTCT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Other',UTC_TIMESTAMP(),'admin','Y');
