INSERT INTO agreement_section_type (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('100','OVERVIEW',UTC_TIMESTAMP(),'admin');
INSERT INTO agreement_section_type (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('101','PEOPLE',UTC_TIMESTAMP(),'admin');
INSERT INTO agreement_section_type (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('102','THIRD_PARTY',UTC_TIMESTAMP(),'admin');
INSERT INTO agreement_section_type (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('103','QUESTIONNAIRE',UTC_TIMESTAMP(),'admin');
INSERT INTO agreement_section_type (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('104','CLAUSES',UTC_TIMESTAMP(),'admin');
INSERT INTO agreement_section_type (SECTION_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('105','SPECIAL_REVIEW',UTC_TIMESTAMP(),'admin');
