INSERT INTO negotiation_association_type (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('1','Award',UTC_TIMESTAMP(),'admin');
INSERT INTO negotiation_association_type (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('2','Institute Proposal',UTC_TIMESTAMP(),'admin');
INSERT INTO negotiation_association_type (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('3','None',UTC_TIMESTAMP(),'admin');
INSERT INTO negotiation_association_type (ASSOCIATION_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('4','Agreement',UTC_TIMESTAMP(),'admin');
