INSERT INTO negotiation_status (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','In Progress',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO negotiation_status (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('2','Waiting for response',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO negotiation_status (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Suspended',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO negotiation_status (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Complete',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO negotiation_status (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Approval in Progress',UTC_TIMESTAMP(),'admin','Y');
INSERT INTO negotiation_status (NEGOTIATION_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Approved',UTC_TIMESTAMP(),'admin','Y');
