INSERT INTO grant_call_status (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (1,'Draft','2019-05-31 10:50:59','admin','Y');
INSERT INTO grant_call_status (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (2,'Open','2019-05-31 10:50:59','admin','Y');
INSERT INTO grant_call_status (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (3,'Closed','2019-05-31 10:50:59','admin','Y');
INSERT INTO grant_call_status (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (4,'Tentative','2019-05-23 11:22:38','admin','Y');
INSERT INTO grant_call_status (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (5,'Archived','2019-05-23 11:22:38','admin','Y');
INSERT INTO grant_call_status (GRANT_STATUS_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES (6,'Not to Publish','2020-02-26 16:37:19','admin','Y');
