DROP TABLE IF EXISTS `award_review_comment`;

CREATE TABLE `award_review_comment` (
  `AWARD_REVIEW_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(255) DEFAULT NULL,
  `IS_RESOLVED` varchar(255) DEFAULT NULL,
  `PARENT_REVIEW_COMMENT_ID` int(11) DEFAULT NULL,
  `RESOLVED_BY` varchar(255) DEFAULT NULL,
  `RESOLVED_TIMESTAMP` datetime(6) DEFAULT NULL,
  `REVIEW_COMMENT` varchar(4000) DEFAULT NULL,
  `REVIEW_COMMENT_TYPE_CODE` varchar(255) DEFAULT NULL,
  `REVIEW_SECTION_CODE` varchar(255) DEFAULT NULL,
  `REVIEWER_PERSON_ID` varchar(255) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `IS_PRIVATE_COMMENT` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AWARD_REVIEW_COMMENT_ID`)
) ;
