DROP TABLE IF EXISTS `award_person_attachmnt`;

CREATE TABLE `award_person_attachmnt` (
  `ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `AWARD_PERSON_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `AWARD_PERSON_ATTACHMNT_FK1` (`AWARD_PERSON_ID`),
  CONSTRAINT `AWARD_PERSON_ATTACHMNT_FK1` FOREIGN KEY (`AWARD_PERSON_ID`) REFERENCES `award_persons` (`AWARD_PERSON_ID`)
) ;
