DROP TABLE IF EXISTS `award_expense_header`;

CREATE TABLE `award_expense_header` (
  `AWARD_NUMBER` varchar(12) NOT NULL,
  `ACCOUNT_NUMBER` varchar(100) NOT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `LAST_SYNCH_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`AWARD_NUMBER`,`ACCOUNT_NUMBER`)
) ;
