DROP TABLE IF EXISTS `award_budget_det_cal_amt`;

CREATE TABLE `award_budget_det_cal_amt` (
  `BUDGET_DETAILS_CAL_AMTS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `APPLY_RATE_FLAG` varchar(1) DEFAULT NULL,
  `BUDGET_ID` int(11) DEFAULT NULL,
  `BUDGET_PERIOD` int(11) DEFAULT NULL,
  `BUDGET_PERIOD_NUMBER` int(11) DEFAULT NULL,
  `CALCULATED_COST` decimal(15,2) DEFAULT NULL,
  `CALCULATED_COST_SHARING` decimal(15,2) DEFAULT NULL,
  `LINE_ITEM_NUMBER` int(11) DEFAULT NULL,
  `RATE_CLASS_CODE` varchar(3) DEFAULT NULL,
  `RATE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `RATE_TYPE_DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `BUDGET_DETAILS_ID` int(11) DEFAULT NULL,
  `APPLICABLE_RATE` decimal(15,2) DEFAULT NULL,
  `BUDGET_HEADER_ID` int(11) DEFAULT NULL,
  `BUDGET_PERIOD_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_DETAILS_CAL_AMTS_ID`),
  KEY `AWARD_BUDGET_DET_CAL_AMT_FK1` (`BUDGET_DETAILS_ID`),
  KEY `FK98vx4s5dccuxhl27mffw40k7o` (`RATE_CLASS_CODE`,`RATE_TYPE_CODE`),
  CONSTRAINT `AWARD_BUDGET_DET_CAL_AMT_FK1` FOREIGN KEY (`BUDGET_DETAILS_ID`) REFERENCES `award_budget_detail` (`BUDGET_DETAILS_ID`),
  CONSTRAINT `AWARD_BUDGET_DET_CAL_AMT_FK2` FOREIGN KEY (`RATE_CLASS_CODE`) REFERENCES `rate_class` (`RATE_CLASS_CODE`),
  CONSTRAINT `AWARD_BUDGET_DET_CAL_AMT_FK3` FOREIGN KEY (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`) REFERENCES `rate_type` (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`)
) ;
