DROP TABLE IF EXISTS `award_budget_persons`;

CREATE TABLE `award_budget_persons` (
  `BUDGET_PERSON_ID` int(11) NOT NULL AUTO_INCREMENT,
  `APPOINTMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `BUDGET_HEADER_ID` int(11) DEFAULT NULL,
  `TBN_ID` varchar(9) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `ROLODEX_ID` int(11) DEFAULT NULL,
  `JOB_CODE` varchar(6) DEFAULT NULL,
  `EFFECTIVE_DATE` datetime DEFAULT NULL,
  `CALCULATION_BASE` decimal(15,2) DEFAULT NULL,
  `PERSON_NAME` varchar(90) DEFAULT NULL,
  `NON_EMPLOYEE_FLAG` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SALARY_ANNIVERSARY_DATE` datetime DEFAULT NULL,
  `PERSON_TYPE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_PERSON_ID`),
  KEY `AWARD_BUDGET_PERS_FK1` (`JOB_CODE`),
  KEY `AWARD_BUDGET_PERS_FK2` (`APPOINTMENT_TYPE_CODE`),
  KEY `AWARD_BUDGET_PERS_FK3` (`TBN_ID`),
  KEY `AWARD_BUDGET_PERS_FK4` (`PERSON_TYPE`),
  CONSTRAINT `AWARD_BUDGET_PERS_FK1` FOREIGN KEY (`JOB_CODE`) REFERENCES `job_code` (`JOB_CODE`),
  CONSTRAINT `AWARD_BUDGET_PERS_FK2` FOREIGN KEY (`APPOINTMENT_TYPE_CODE`) REFERENCES `appointment_type` (`APPOINTMENT_TYPE_CODE`),
  CONSTRAINT `AWARD_BUDGET_PERS_FK3` FOREIGN KEY (`TBN_ID`) REFERENCES `tbn` (`TBN_ID`),
  CONSTRAINT `AWARD_BUDGET_PERS_FK4` FOREIGN KEY (`PERSON_TYPE`) REFERENCES `award_personnel_type` (`VALUE`)
) ;
