DROP TABLE IF EXISTS `award_funding_proposals`;

CREATE TABLE `award_funding_proposals` (
  `AWARD_FUNDING_PROPOSAL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `PROPOSAL_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` timestamp(6) NULL DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AWARD_FUNDING_PROPOSAL_ID`),
  KEY `AWARD_FUNDING_PROPOSALS_FK2` (`PROPOSAL_ID`),
  KEY `AWARD_FUNDING_PROPOSALS_IX18` (`AWARD_ID`),
  CONSTRAINT `AWARD_FUNDING_PROPOSALS_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`),
  CONSTRAINT `AWARD_FUNDING_PROPOSALS_FK2` FOREIGN KEY (`PROPOSAL_ID`) REFERENCES `proposal` (`PROPOSAL_ID`)
) ;
