DROP TABLE IF EXISTS `award_budget_non_person_detail`;

CREATE TABLE `award_budget_non_person_detail` (
  `BUDGET_NON_PERSON_DTL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INTERNAL_ORDER_CODE` varchar(255) DEFAULT NULL,
  `LINE_ITEM_COST` decimal(15,2) DEFAULT NULL,
  `LINE_ITEM_NUMBER` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `BUDGET_DETAILS_ID` int(11) NOT NULL,
  PRIMARY KEY (`BUDGET_NON_PERSON_DTL_ID`),
  KEY `AWARD_BUD_NON_PERSON_DTL_FK1` (`BUDGET_DETAILS_ID`),
  CONSTRAINT `AWARD_BUD_NON_PERSON_DTL_FK1` FOREIGN KEY (`BUDGET_DETAILS_ID`) REFERENCES `award_budget_detail` (`BUDGET_DETAILS_ID`)
) ;
