DROP TABLE IF EXISTS `award_project_team`;

CREATE TABLE `award_project_team` (
  `AWARD_PROJECT_TEAM_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `PROJECT_ROLE` varchar(100) DEFAULT NULL,
  `NON_EMPLOYEE_FLAG` varchar(1) DEFAULT NULL,
  `PERCENTAGE_CHARGED` decimal(5,2) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `DESIGNATION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AWARD_PROJECT_TEAM_ID`),
  KEY `AWARD_PROJECT_TEAM_FK1` (`AWARD_ID`),
  CONSTRAINT `AWARD_PROJECT_TEAM_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`)
) ;
