SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `award_progress_report_achievement`;

CREATE TABLE `award_progress_report_achievement` (
  `PROGRESS_REPORT_ACHIEVEMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `ACHIEVEMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DESCRIPTION` varchar(3000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`PROGRESS_REPORT_ACHIEVEMENT_ID`),
  KEY `PROGRESS_REPRT_ACHIEVEMENT_FK1` (`ACHIEVEMENT_TYPE_CODE`),
  KEY `PROGRESS_REPRT_ACHIEVEMENT_FK2` (`PROGRESS_REPORT_ID`),
  CONSTRAINT `PROGRESS_REPRT_ACHIEVEMENT_FK1` FOREIGN KEY (`ACHIEVEMENT_TYPE_CODE`) REFERENCES `progress_report_achievement_type` (`ACHIEVEMENT_TYPE_CODE`),
  CONSTRAINT `PROGRESS_REPRT_ACHIEVEMENT_FK2` FOREIGN KEY (`PROGRESS_REPORT_ID`) REFERENCES `award_progress_report` (`PROGRESS_REPORT_ID`)
) ;
SET FOREIGN_KEY_CHECKS = 1;