DROP TABLE IF EXISTS `award_section_type`;

CREATE TABLE `award_section_type` (
  `AWARD_SECTION_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_SECTION_TYPE_CODE`)
) ;
