DROP TABLE IF EXISTS `award_original_l2_amt_rt`;

CREATE TABLE `award_original_l2_amt_rt` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `INTERNAL_ORDER_CODE` varchar(20) DEFAULT NULL,
  `AMOUNT` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `AWARD_ORIGINAL_L2_AMT_RT_IDX_1` (`AWARD_NUMBER`,`INTERNAL_ORDER_CODE`,`AMOUNT`)
) ;