DROP TABLE IF EXISTS `award_association`;

CREATE TABLE `award_association` (
  `AWARD_ASSOCIATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ASSOCIATED_PROJECT_ID` varchar(255) DEFAULT NULL,
  `ASSOCIATION_TYPE_CODE` varchar(255) DEFAULT NULL,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(255) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AWARD_ASSOCIATION_ID`),
  KEY `AWARD_ASSOCIATION_FK2` (`ASSOCIATION_TYPE_CODE`),
  KEY `AWARD_ASSOCIATION_FK1` (`AWARD_ID`),
  CONSTRAINT `AWARD_ASSOCIATION_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`),
  CONSTRAINT `AWARD_ASSOCIATION_FK2` FOREIGN KEY (`ASSOCIATION_TYPE_CODE`) REFERENCES `award_association_type` (`ASSOCIATION_TYPE_CODE`)
) ;
