DROP TABLE IF EXISTS `award_person_orcid_work`;

CREATE TABLE `award_person_orcid_work` (
  `AWARD_PERSON_ORCID_WORK_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `PERSON_ORCID_WORK_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_PERSON_ORCID_WORK_ID`),
  KEY `AWARD_PERSON_ORCID_WORK_FK1` (`PERSON_ORCID_WORK_ID`),
  CONSTRAINT `AWARD_PERSON_ORCID_WORK_FK1` FOREIGN KEY (`PERSON_ORCID_WORK_ID`) REFERENCES `person_orcid_work` (`PERSON_ORCID_WORK_ID`)
) ;
