DROP TABLE IF EXISTS `award_comment`;

CREATE TABLE `award_comment` (
  `AWARD_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `COMMENT_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COMMENTS` longtext,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_COMMENT_ID`),
  KEY `AWARD_COMMENT_FK1` (`AWARD_ID`),
  CONSTRAINT `AWARD_COMMENT_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`)
) ;
