DROP TABLE IF EXISTS `award_cost_share`;

CREATE TABLE `award_cost_share` (
  `AWARD_COST_SHARE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` decimal(22,0) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `PROJECT_PERIOD` varchar(4) DEFAULT NULL,
  `COST_SHARE_PERCENTAGE` decimal(5,2) DEFAULT NULL,
  `COST_SHARE_TYPE_CODE` int(11) DEFAULT NULL,
  `SOURCE` varchar(32) DEFAULT NULL,
  `COMMENTS` varchar(4000) DEFAULT NULL,
  `DESTINATION` varchar(32) DEFAULT NULL,
  `COMMITMENT_AMOUNT` decimal(15,2) DEFAULT NULL,
  `VERIFICATION_DATE` datetime DEFAULT NULL,
  `COST_SHARE_MET` decimal(15,2) DEFAULT NULL,
  `UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `COST_SHARE_DISTRIBUTABLE` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`AWARD_COST_SHARE_ID`),
  KEY `AWARD_COST_SHARE_FK1` (`UNIT_NUMBER`),
  KEY `AWARD_COST_SHARE_FK2` (`COST_SHARE_TYPE_CODE`),
  CONSTRAINT `AWARD_COST_SHARE_FK1` FOREIGN KEY (`UNIT_NUMBER`) REFERENCES `unit` (`UNIT_NUMBER`),
  CONSTRAINT `AWARD_COST_SHARE_FK2` FOREIGN KEY (`COST_SHARE_TYPE_CODE`) REFERENCES `cost_share_type` (`COST_SHARE_TYPE_CODE`)
) ;
