DROP TABLE IF EXISTS `award_science_keyword`;

CREATE TABLE `award_science_keyword` (
  `AWARD_SCIENCE_KEYWORD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `SCIENCE_KEYWORD_CODE` varchar(15) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `KEYWORD` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`AWARD_SCIENCE_KEYWORD_ID`),
  KEY `AWARD_SCIENCE_KEYWORD_FK2` (`SCIENCE_KEYWORD_CODE`),
  KEY `AWARD_SCIENCE_KEYWORD_FK1` (`AWARD_ID`),
  CONSTRAINT `AWARD_SCIENCE_KEYWORD_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`),
  CONSTRAINT `AWARD_SCIENCE_KEYWORD_FK2` FOREIGN KEY (`SCIENCE_KEYWORD_CODE`) REFERENCES `science_keyword` (`SCIENCE_KEYWORD_CODE`)
) ;
