DROP TABLE IF EXISTS `award_special_review`;

CREATE TABLE `award_special_review` (
  `AWARD_SPECIAL_REVIEW_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` decimal(22,0) NOT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `SPECIAL_REVIEW_CODE` varchar(3) NOT NULL,
  `APPROVAL_TYPE_CODE` varchar(3) DEFAULT NULL,
  `EXPIRATION_DATE` datetime DEFAULT NULL,
  `PROTOCOL_NUMBER` varchar(20) DEFAULT NULL,
  `APPLICATION_DATE` datetime DEFAULT NULL,
  `APPROVAL_DATE` datetime DEFAULT NULL,
  `COMMENTS` longtext,
  `UPDATE_USER` varchar(60) NOT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  `SPECIAL_REVIEW_NUMBER` int(11) DEFAULT NULL,
  `IS_INTEGRATED_PROTOCOL` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`AWARD_SPECIAL_REVIEW_ID`),
  KEY `AWARD_SPECIAL_REVIEW_FK2` (`SPECIAL_REVIEW_CODE`),
  KEY `AWARD_SPECIAL_REVIEW_FK3` (`APPROVAL_TYPE_CODE`),
  CONSTRAINT `AWARD_SPECIAL_REVIEW_FK2` FOREIGN KEY (`SPECIAL_REVIEW_CODE`) REFERENCES `special_review` (`SPECIAL_REVIEW_CODE`),
  CONSTRAINT `AWARD_SPECIAL_REVIEW_FK3` FOREIGN KEY (`APPROVAL_TYPE_CODE`) REFERENCES `sp_rev_approval_type` (`APPROVAL_TYPE_CODE`)
) ;
