DROP TABLE IF EXISTS `award_milestone`;

CREATE TABLE `award_milestone` (
  `AWARD_MILESTONE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(255) DEFAULT NULL,
  `DURATION` varchar(50) DEFAULT NULL,
  `END_DATE` datetime DEFAULT NULL,
  `MILESTONE` varchar(1000) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `MILESTONE_NUMBER` varchar(30) DEFAULT NULL,
  `MILESTONE_STATUS_CODE` varchar(3) DEFAULT NULL,
  `COMMENT` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`AWARD_MILESTONE_ID`),
  KEY `AWARD_MILESTONE_FK1` (`MILESTONE_STATUS_CODE`),
  CONSTRAINT `AWARD_MILESTONE_FK1` FOREIGN KEY (`MILESTONE_STATUS_CODE`) REFERENCES `milestone_status` (`MILESTONE_STATUS_CODE`)
) ;
