DROP TABLE IF EXISTS `award_approved_subawards`;

CREATE TABLE `award_approved_subawards` (
  `AWARD_APPROVED_SUBAWARD_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `ORGANIZATION_ID` varchar(20) DEFAULT NULL,
  `AMOUNT` decimal(12,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_APPROVED_SUBAWARD_ID`),
  KEY `AWARD_APPROVED_SUBAWARDS_FK2` (`ORGANIZATION_ID`),
  KEY `AWARD_APPROVED_SUBAWARDS_FK1` (`AWARD_ID`),
  CONSTRAINT `AWARD_APPROVED_SUBAWARDS_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`),
  CONSTRAINT `AWARD_APPROVED_SUBAWARDS_FK2` FOREIGN KEY (`ORGANIZATION_ID`) REFERENCES `organization` (`ORGANIZATION_ID`)
) ;
