DROP TABLE IF EXISTS `award_amount_transaction`;

CREATE TABLE `award_amount_transaction` (
  `AWARD_AMOUNT_TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `TRANSACTION_ID` decimal(22,0) DEFAULT NULL,
  `TRANSACTION_TYPE_CODE` decimal(3,0) DEFAULT NULL,
  `FUNDED_PROPOSAL_ID` decimal(12,0) DEFAULT NULL,
  `NOTICE_DATE` datetime DEFAULT NULL,
  `COMMENTS` varchar(2000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SOURCE_AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `DESTINATION_AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `TRANSACTION_STATUS_CODE` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`AWARD_AMOUNT_TRANSACTION_ID`),
  UNIQUE KEY `AWARD_AMOUNT_TRANSACTION_UK` (`TRANSACTION_ID`),
  KEY `AWARD_AMOUNT_TRANSACTION_FK1` (`TRANSACTION_TYPE_CODE`),
  KEY `AWARD_AMOUNT_TRANSACTION_FK2` (`TRANSACTION_STATUS_CODE`),
  CONSTRAINT `AWARD_AMOUNT_TRANSACTION_FK1` FOREIGN KEY (`TRANSACTION_TYPE_CODE`) REFERENCES `award_transaction_type` (`AWARD_TRANSACTION_TYPE_CODE`),
  CONSTRAINT `AWARD_AMOUNT_TRANSACTION_FK2` FOREIGN KEY (`TRANSACTION_STATUS_CODE`) REFERENCES `award_transaction_status` (`TRANSACTION_STATUS_CODE`)
) ;
