DROP TABLE IF EXISTS `award_approved_equipment`;

CREATE TABLE `award_approved_equipment` (
  `AWARD_APPROVED_EQUIPMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `ITEM` varchar(100) DEFAULT NULL,
  `VENDOR` varchar(50) DEFAULT NULL,
  `MODEL` varchar(50) DEFAULT NULL,
  `AMOUNT` decimal(12,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_APPROVED_EQUIPMENT_ID`),
  KEY `AWARD_APPROVED_EQUIPMENT_FK1` (`AWARD_ID`),
  CONSTRAINT `AWARD_APPROVED_EQUIPMENT_FK1` FOREIGN KEY (`AWARD_ID`) REFERENCES `award` (`AWARD_ID`)
) ;
