DROP TABLE IF EXISTS `award_expense_trans_amt_rt`;

CREATE TABLE `award_expense_trans_amt_rt` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `INTERNAL_ORDER_CODE` varchar(20) DEFAULT NULL,
  `BUDGET_CATEGORY_CODE` varchar(3) DEFAULT NULL,
  `FM_POSTING_DATE` date DEFAULT NULL,
  `ACTUAL_AMOUNT` decimal(12,2) DEFAULT NULL,
  `COMMITTED_AMOUNT` decimal(12,2) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `AWARD_EXPENSE_TRANS_AMT_RT_IDX_1` (`AWARD_NUMBER`,`BUDGET_CATEGORY_CODE`,`ACTUAL_AMOUNT`,`COMMITTED_AMOUNT`),
  KEY `AWARD_EXPENSE_TRANS_AMT_RT_IDX_2` (`FM_POSTING_DATE`)
) ;
