DROP TABLE IF EXISTS `award_report_tracking_file`;

CREATE TABLE `award_report_tracking_file` (
  `AWARD_REPORT_TRACKING_FILE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_REPORT_TERMS_ID` int(11) DEFAULT NULL,
  `AWARD_REPORT_TRACKING_ID` int(11) DEFAULT NULL,
  `AWARD_ID` decimal(22,0) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `VERSION_NUMBER` int(11) DEFAULT NULL,
  `DOCUMENT_STATUS_CODE` varchar(1) DEFAULT NULL,
  `FILE_ID` varchar(36) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `CONTENT_TYPE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_REPORT_TRACKING_FILE_ID`),
  KEY `AWARD_REPORT_TRACKING_FILE_FK1` (`AWARD_REPORT_TRACKING_ID`),
  CONSTRAINT `AWARD_REPORT_TRACKING_FILE_FK1` FOREIGN KEY (`AWARD_REPORT_TRACKING_ID`) REFERENCES `award_report_tracking` (`AWARD_REPORT_TRACKING_ID`)
) ;
