DROP TABLE IF EXISTS `award_report_tracking`;

CREATE TABLE `award_report_tracking` (
  `AWARD_REPORT_TRACKING_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_REPORT_TERMS_ID` int(11) DEFAULT NULL,
  `AWARD_ID` decimal(22,0) DEFAULT NULL,
  `AWARD_NUMBER` varchar(12) DEFAULT NULL,
  `SEQUENCE_NUMBER` int(11) DEFAULT NULL,
  `STATUS_CODE` varchar(3) DEFAULT NULL,
  `ACTIVITY_DATE` datetime DEFAULT NULL,
  `COMMENTS` varchar(2000) DEFAULT NULL,
  `PREPARER_ID` varchar(40) DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `DUE_DATE` datetime(6) DEFAULT NULL,
  `PREPARER_NAME` varchar(255) DEFAULT NULL,
  `PROGRESS_REPORT_ID` int(11) DEFAULT NULL,
  `UNIQUE_ID` int(11) DEFAULT NULL,
  `IS_ADHOC` varchar(1) DEFAULT 'N',
  `NOTE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`AWARD_REPORT_TRACKING_ID`),
  KEY `AWARD_REPORT_TRACKING_FK1` (`AWARD_REPORT_TERMS_ID`),
  CONSTRAINT `AWARD_REPORT_TRACKING_FK1` FOREIGN KEY (`AWARD_REPORT_TERMS_ID`) REFERENCES `award_report_terms` (`AWARD_REPORT_TERMS_ID`)
) ;
