DROP TABLE IF EXISTS `award_expense_details`;

CREATE TABLE `award_expense_details` (
  `AWARD_NUMBER` varchar(12) NOT NULL,
  `ACCOUNT_NUMBER` varchar(100) NOT NULL,
  `INTERNAL_ORDER_CODE` varchar(50) NOT NULL,
  `TOTAL_EXPENSE_AMOUNT` decimal(15,2) DEFAULT NULL,
  `TOTAL_LOGGED_HOURS` decimal(6,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`AWARD_NUMBER`,`ACCOUNT_NUMBER`,`INTERNAL_ORDER_CODE`)
) ;
