DROP TABLE IF EXISTS `awd_repreq_duedt_log`;

CREATE TABLE `awd_repreq_duedt_log` (
  `AWD_REPREQ_DUEDT_LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `AWARD_ID` int(11) DEFAULT NULL,
  `AWARD_REPORT_TERMS_ID` int(11) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_USER` varchar(40) DEFAULT 'admin',
  PRIMARY KEY (`AWD_REPREQ_DUEDT_LOG_ID`)
) ;
