DROP TABLE IF EXISTS `canned_cost_element`;

CREATE TABLE `canned_cost_element` (
  `CANNED_COST_ELEMENT_ID` int(11) NOT NULL,
  `MODULE_ITEM_CODE` int(11) DEFAULT NULL,
  `COST_ELEMENT` varchar(50) DEFAULT NULL,
  `RULE_ID` varchar(10) DEFAULT NULL,
  `UPDATE_TIMESTAMP` date DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `IS_SYSTEM_GENRTED_COST_ELEMENT` varchar(1) DEFAULT NULL,
  `SYSTEM_GEN_COST_ELEMENT_TYPE` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`CANNED_COST_ELEMENT_ID`),
  KEY `CANNED_COST_ELEMENT_FK1` (`COST_ELEMENT`),
  CONSTRAINT `CANNED_COST_ELEMENT_FK1` FOREIGN KEY (`COST_ELEMENT`) REFERENCES `cost_element` (`COST_ELEMENT`)
);
