DROP TABLE IF EXISTS `institute_rates`;

CREATE TABLE `institute_rates` (
  `IS_ACTIVE` varchar(1) NOT NULL DEFAULT 'Y',
  `RATE_CLASS_CODE` varchar(3) DEFAULT NULL,
  `RATE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `ACTIVITY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `FISCAL_YEAR` varchar(4) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `ON_OFF_CAMPUS_FLAG` varchar(1) DEFAULT NULL,
  `RATE` decimal(5,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `INSTITUTE_RATE_ID` int(11) NOT NULL,
  `CAMPUSFLAG` varchar(255) DEFAULT NULL,
  `UNITNAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`INSTITUTE_RATE_ID`),
  UNIQUE KEY `INSTITUTE_RATES_UQ` (`RATE_CLASS_CODE`,`RATE_TYPE_CODE`,`ACTIVITY_TYPE_CODE`,`FISCAL_YEAR`,`START_DATE`,`ON_OFF_CAMPUS_FLAG`,`UNIT_NUMBER`),
  KEY `INSTITUTE_RATES_FK1` (`ACTIVITY_TYPE_CODE`),
  KEY `INSTITUTE_RATES_FK3` (`UNIT_NUMBER`),
  CONSTRAINT `INSTITUTE_RATES_FK1` FOREIGN KEY (`ACTIVITY_TYPE_CODE`) REFERENCES `activity_type` (`ACTIVITY_TYPE_CODE`),
  CONSTRAINT `INSTITUTE_RATES_FK2` FOREIGN KEY (`RATE_CLASS_CODE`) REFERENCES `rate_class` (`RATE_CLASS_CODE`),
  CONSTRAINT `INSTITUTE_RATES_FK3` FOREIGN KEY (`UNIT_NUMBER`) REFERENCES `unit` (`UNIT_NUMBER`),
  CONSTRAINT `INSTITUTE_RATES_FK4` FOREIGN KEY (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`) REFERENCES `rate_type` (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`)
) ;
