DROP TABLE IF EXISTS `institute_la_rates`;

CREATE TABLE `institute_la_rates` (
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `RATE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `FISCAL_YEAR` varchar(4) DEFAULT NULL,
  `START_DATE` datetime DEFAULT NULL,
  `ON_OFF_CAMPUS_FLAG` varchar(1) DEFAULT NULL,
  `RATE` decimal(5,2) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `RATE_CLASS_CODE` varchar(3) DEFAULT NULL,
  `CAMPUSFLAG` varchar(255) DEFAULT NULL,
  `INSTITUTE_LA_RATE_ID` int(11) NOT NULL,
  PRIMARY KEY (`INSTITUTE_LA_RATE_ID`),
  KEY `INSTITUTE_LA_RATES_FK3` (`RATE_CLASS_CODE`,`RATE_TYPE_CODE`),
  KEY `INSTITUTE_LA_RATES_FK1` (`UNIT_NUMBER`),
  CONSTRAINT `INSTITUTE_LA_RATES_FK1` FOREIGN KEY (`UNIT_NUMBER`) REFERENCES `unit` (`UNIT_NUMBER`),
  CONSTRAINT `INSTITUTE_LA_RATES_FK2` FOREIGN KEY (`RATE_CLASS_CODE`) REFERENCES `rate_class` (`RATE_CLASS_CODE`),
  CONSTRAINT `INSTITUTE_LA_RATES_FK3` FOREIGN KEY (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`) REFERENCES `rate_type` (`RATE_CLASS_CODE`, `RATE_TYPE_CODE`)
) ;