DROP TABLE IF EXISTS `orcid_work_status`;

CREATE TABLE `orcid_work_status` (
  `ORCID_WORK_STATUS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ORCID_WORK_STATUS_CODE`)
) ;
