DROP TABLE IF EXISTS `project_details_api`;

CREATE TABLE `project_details_api` (
  `PROJECT_DETAILS_ID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key which is not related to API',
  `OPERATING_UNIT` varchar(255) DEFAULT NULL COMMENT 'Name field from API',
  `ORG_CODE` varchar(10) DEFAULT NULL COMMENT 'orgCode field from API',
  `PROJECT_ID` int(11) DEFAULT NULL COMMENT 'projectId field from API',
  `PROJECT_NAME` varchar(255) DEFAULT NULL COMMENT 'projectName field from API',
  `PROJECT_NUMBER` varchar(255) DEFAULT NULL COMMENT 'segment1 field from API',
  `PROJECT_TYPE` varchar(100) DEFAULT NULL COMMENT 'projectType field from API',
  `PROJECT_STATUS_CODE` varchar(50) DEFAULT NULL COMMENT 'projectStatusCode field from API',
  `PROJECT_STATUS` varchar(255) DEFAULT NULL COMMENT 'projectStatus from API code mapping',
  `LONG_DESCRIPTION` varchar(1000) DEFAULT NULL COMMENT 'longDescription field from API',
  `DESCRIPTION` varchar(1000) DEFAULT NULL COMMENT 'description field from API',
  `FULL_DESCRIPTION` varchar(4000) DEFAULT NULL COMMENT 'fullDescription field from API',
  `START_DATE` datetime DEFAULT NULL COMMENT 'startDate field from API',
  `COMPLETION_DATE` datetime DEFAULT NULL COMMENT 'completionDate field from API',
  `CLOSED_DATE` datetime DEFAULT NULL COMMENT 'closedDate field from API',
  `ENABLED_FLAG` varchar(3) DEFAULT NULL COMMENT 'enabledFlag field from API',
  `ORGANIZATION_ID` int(11) DEFAULT NULL COMMENT 'orgId field from API',
  `PM_EMPLOYEE_ID` varchar(50) DEFAULT NULL COMMENT 'pmEmployeeId field from API',
  `PM_FULL_NAME` varchar(200) DEFAULT NULL COMMENT 'Full Name from person table if person exists',
  `LEDGER_ID` varchar(70) DEFAULT NULL COMMENT 'ledgerId field from API',
  `PROJECT_ROLE` varchar(70) DEFAULT NULL COMMENT 'projectRole field from API',
  `PM_PERSON_ID` varchar(50) DEFAULT NULL COMMENT 'Person id of the PM',
  `AWARD_NUMBER` varchar(50) DEFAULT NULL COMMENT 'Linked Award number',
  `FINAL_EXPIRATION_DATE` datetime DEFAULT NULL,
  `BEGIN_DATE` datetime DEFAULT NULL,
  `AWARD_PI_ID` varchar(20) DEFAULT NULL,
  `AWARD_PI_NAME` varchar(200) DEFAULT NULL,
  `AWARD_STATUS_CODE` varchar(3) DEFAULT NULL,
  `AWARD_STATUS` varchar(70) DEFAULT NULL,
  `AWARD_MAPPED_STATUS_CODE` varchar(50) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PROJECT_DETAILS_ID`)
) ;
