DROP TABLE IF EXISTS `publication`;

CREATE TABLE `publication` (
  `PUBLICATION_ID` int(11) NOT NULL,
  `AUTHORS` varchar(255) DEFAULT NULL,
  `AUTHORGANIZATION` varchar(255) DEFAULT NULL,
  `EDITION` varchar(255) DEFAULT NULL,
  `ISSN` varchar(255) DEFAULT NULL,
  `PAGE` varchar(200) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  `REVIEW_STATUS` varchar(255) DEFAULT NULL,
  `SCHOOL_OF_AUTHOR` varchar(255) DEFAULT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  `VOLUME` varchar(255) DEFAULT NULL,
  `YEAR` varchar(200) DEFAULT NULL,
  `NAME_OF_JOURNAL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PUBLICATION_ID`)
) ;
