DROP TABLE IF EXISTS `sap_award_feed_batch_error_log`;

CREATE TABLE `sap_award_feed_batch_error_log` (
  `BATCH_ERROR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BATCH_ID` int(11) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(255) DEFAULT NULL,
  `ERROR_TYPE` varchar(255) DEFAULT NULL,
  `FEED_ID` int(11) DEFAULT NULL,
  `GRANT_CODE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `BUSINESS_AREA` varchar(4) DEFAULT NULL,
  PRIMARY KEY (`BATCH_ERROR_ID`),
  KEY `AWARD_FEED_BATCH_ERROR_LOG_FK2` (`FEED_ID`),
  KEY `AWARD_FEED_BATCH_ERROR_LOG_FK1` (`BATCH_ID`),
  CONSTRAINT `AWARD_FEED_BATCH_ERROR_LOG_FK1` FOREIGN KEY (`BATCH_ID`) REFERENCES `sap_award_feed_batch` (`BATCH_ID`),
  CONSTRAINT `AWARD_FEED_BATCH_ERROR_LOG_FK2` FOREIGN KEY (`FEED_ID`) REFERENCES `sap_award_feed` (`FEED_ID`)
) ;
