DROP TABLE IF EXISTS `sap_claim_feed_batch_error_log`;

CREATE TABLE `sap_claim_feed_batch_error_log` (
  `BATCH_ERROR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BATCH_ID` int(11) DEFAULT NULL,
  `FEED_ID` int(11) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(1000) DEFAULT NULL,
  `BUSINESS_AREA` varchar(4) DEFAULT NULL,
  `ERROR_TYPE` varchar(50) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  `UPDATE_USER` varchar(60) NOT NULL,
  PRIMARY KEY (`BATCH_ERROR_ID`),
  KEY `CLAIM_FEED_BATCH_ERROR_LOG_FK2_idx` (`FEED_ID`),
  KEY `CLAIM_FEED_BATCH_ERROR_LOG_FK1_idx` (`BATCH_ID`),
  CONSTRAINT `CLAIM_FEED_BATCH_ERROR_LOG_FK1` FOREIGN KEY (`BATCH_ID`) REFERENCES `sap_claim_feed_batch` (`BATCH_ID`),
  CONSTRAINT `CLAIM_FEED_BATCH_ERROR_LOG_FK2` FOREIGN KEY (`FEED_ID`) REFERENCES `sap_claim_feed` (`FEED_ID`)
) ;
