DROP TABLE IF EXISTS `sap_feed_tmpl_funded_prgm`;

CREATE TABLE `sap_feed_tmpl_funded_prgm` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BATCH_ID` int(11) DEFAULT NULL,
  `CREATE_STATUS` varchar(255) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(255) DEFAULT NULL,
  `FEED_ID` int(11) DEFAULT NULL,
  `FEED_STATUS` varchar(255) DEFAULT NULL,
  `FUNDED_PROGRAM` varchar(255) DEFAULT NULL,
  `FUNDED_PROGRAM_TYPE` varchar(255) DEFAULT NULL,
  `PROGRAM_DESCRIPTION` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `USER_COMMENT` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ;
