DROP TABLE IF EXISTS `sap_feed_tmpl_gm_derivation`;

CREATE TABLE `sap_feed_tmpl_gm_derivation` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BATCH_ID` int(11) DEFAULT NULL,
  `CREATE_STATUS` varchar(255) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(255) DEFAULT NULL,
  `FEED_ID` int(11) DEFAULT NULL,
  `FEED_STATUS` varchar(255) DEFAULT NULL,
  `WBS_ELEMENT` varchar(255) DEFAULT NULL,
  `FROM_GL_ACCOUNT` varchar(255) DEFAULT NULL,
  `TO_GL_ACCOUNT` varchar(255) DEFAULT NULL,
  `SPONSORED_PROGRAM` varchar(255) DEFAULT NULL,
  `SPONSORED_CLASS` varchar(255) DEFAULT NULL,
  `GRANT_CODE` varchar(255) DEFAULT NULL,
  `FUND` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `USER_COMMENT` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ;
