DROP TABLE IF EXISTS `sap_award_feed_batch`;

CREATE TABLE `sap_award_feed_batch` (
  `BATCH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NO_OF_RECORDS` int(11) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `RESPONSE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`BATCH_ID`)
) ;
