

--
--  `task_comment_attachment`
--

DROP TABLE IF EXISTS `task_comment_attachment`;

CREATE TABLE `task_comment_attachment` (
  `ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `TASK_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `COMMENT_ID` int(11) NOT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `TASK_COMMENT_ATTACHMENT_FK1` (`TASK_ID`),
  KEY `TASK_COMMENT_ATTACHMENT_FK2` (`COMMENT_ID`),
  CONSTRAINT `TASK_COMMENT_ATTACHMENT_FK1` FOREIGN KEY (`TASK_ID`) REFERENCES `task` (`TASK_ID`),
  CONSTRAINT `TASK_COMMENT_ATTACHMENT_FK2` FOREIGN KEY (`COMMENT_ID`) REFERENCES `task_comments` (`COMMENT_ID`)
);

