

--
--  `task_attachment`
--

DROP TABLE IF EXISTS `task_attachment`;

CREATE TABLE `task_attachment` (
  `ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `TASK_ID` int(11) NOT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `TASK_ATTACHMENT_FK1` (`TASK_ID`),
  CONSTRAINT `TASK_ATTACHMENT_FK1` FOREIGN KEY (`TASK_ID`) REFERENCES `task` (`TASK_ID`)
);

