

--
--  `task_section_module_mapping`
--

DROP TABLE IF EXISTS `task_section_module_mapping`;

CREATE TABLE `task_section_module_mapping` (
  `SECTION_MODULE_MAPPING_ID` int(11) NOT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `SUB_MODULE_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(12) DEFAULT NULL,
  `SECTION_CODE` varchar(4) DEFAULT NULL,
  `TASK_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`SECTION_MODULE_MAPPING_ID`),
  KEY `TASK_SECTION_MOD_MAPPING_FK1` (`TASK_TYPE_CODE`),
  KEY `TASK_SECTION_MOD_MAPPING_FK2` (`SECTION_CODE`),
  CONSTRAINT `TASK_SECTION_MOD_MAPPING_FK1` FOREIGN KEY (`TASK_TYPE_CODE`) REFERENCES `task_type` (`TASK_TYPE_CODE`),
  CONSTRAINT `TASK_SECTION_MOD_MAPPING_FK2` FOREIGN KEY (`SECTION_CODE`) REFERENCES `section_type` (`SECTION_CODE`)
);

