

--
--  `task_section_mapping`
--

DROP TABLE IF EXISTS `task_section_mapping`;

CREATE TABLE `task_section_mapping` (
  `SECTION_CODE` varchar(4) NOT NULL,
  `TASK_TYPE_CODE` varchar(255) NOT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SECTION_CODE`,`TASK_TYPE_CODE`),
  KEY `TASK_SECTION_MAPPING_FK1` (`TASK_TYPE_CODE`),
  CONSTRAINT `TASK_SECTION_MAPPING_FK1` FOREIGN KEY (`TASK_TYPE_CODE`) REFERENCES `task_type` (`TASK_TYPE_CODE`),
  CONSTRAINT `TASK_SECTION_MAPPING_FK2` FOREIGN KEY (`SECTION_CODE`) REFERENCES `section_type` (`SECTION_CODE`)
);

