

--
--  `task_action_log`
--

DROP TABLE IF EXISTS `task_action_log`;

CREATE TABLE `task_action_log` (
  `ACTION_LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACTION_TYPE_CODE` varchar(255) DEFAULT NULL,
  `SYSTEM_COMMENT` varchar(255) DEFAULT NULL,
  `TASK_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ACTION_LOG_ID`),
  KEY `TASK_ACTION_LOG_FK1` (`TASK_ID`),
  KEY `TASK_ACTION_LOG_FK2` (`ACTION_TYPE_CODE`),
  CONSTRAINT `TASK_ACTION_LOG_FK1` FOREIGN KEY (`TASK_ID`) REFERENCES `task` (`TASK_ID`),
  CONSTRAINT `TASK_ACTION_LOG_FK2` FOREIGN KEY (`ACTION_TYPE_CODE`) REFERENCES `task_action_type` (`ACTION_TYPE_CODE`)
);

