

--
--  `variation_request_header`
--

DROP TABLE IF EXISTS `variation_request_header`;

CREATE TABLE `variation_request_header` (
  `VARIATION_REQUEST_HEADER_ID` int(11) NOT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(255) DEFAULT NULL,
  `SECTION_CODE` varchar(4) DEFAULT NULL,
  `SUB_MODULE_CODE` int(11) DEFAULT NULL,
  `TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`VARIATION_REQUEST_HEADER_ID`),
  KEY `VARIATION_REQUEST_HEADER_FK2` (`SECTION_CODE`),
  KEY `VARIATION_REQUEST_HEADER_FK1` (`TYPE_CODE`),
  CONSTRAINT `VARIATION_REQUEST_HEADER_FK1` FOREIGN KEY (`TYPE_CODE`) REFERENCES `sr_type` (`TYPE_CODE`),
  CONSTRAINT `VARIATION_REQUEST_HEADER_FK2` FOREIGN KEY (`SECTION_CODE`) REFERENCES `section_type` (`SECTION_CODE`)
);

