-- `GET_EXT_REVIEWER_DASHBOARD_COUNT`; 

CREATE PROCEDURE `GET_EXT_REVIEWER_DASHBOARD_COUNT`(
    AV_FIRST_NAME                           VARCHAR(500),
    AV_LAST_NAME                            VARCHAR(500),
    AV_PASPORT_NAME                         VARCHAR(500),
    AV_PRIMARY_EMAIL                        VARCHAR(500),
    AV_START_MONTH                          VARCHAR(100),
    AV_EXTERNAL_REVIEWER_ID                 VARCHAR(200),
    AV_END_MONTH                            VARCHAR(100),
    AV_STATUS                               VARCHAR(10),
    AV_COUNTRY_CODE                         VARCHAR(10),
    AV_ACADEMIC_AREA_CODE_SECONDARY         VARCHAR(50),
    AV_ACADEMIC_AREA_CODE_PRIMARY           VARCHAR(1000),
    AV_AFFILATION_INSTITUITION_CODE         VARCHAR(50),
    AV_HINDEX                               VARCHAR(200),
    AV_KEYWORD_CODE                         LONGTEXT,
    AV_ACADEMIC_RANK_CODE                   VARCHAR(200),
    AV_PAGED  				                INT(10),
    AV_LIMIT				                INT(10),
    AV_UNLIMITED                            BOOLEAN
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
DECLARE SELECTED_HINDEX_VALUE VARCHAR(500);
DECLARE DONE1 INT DEFAULT FALSE;
DECLARE SELECTED_HINDEX_VALUE_CURSOR CURSOR FOR
SELECT VALUE FROM H_INDEX WHERE FIND_IN_SET(ID, AV_HINDEX);
DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
SET LS_OFFSET = (AV_LIMIT * AV_PAGED);
SET LS_FILTER_CONDITION ='';
SET LS_DYN_SQL ='';
SET SELECTED_HINDEX_VALUE = '';
    IF AV_FIRST_NAME IS NOT NULL AND AV_FIRST_NAME <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.FIRST_NAME LIKE ''%',AV_FIRST_NAME,'%'' AND ');
    END IF;
    IF AV_LAST_NAME IS NOT NULL AND AV_LAST_NAME <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.LAST_NAME LIKE ''%',AV_LAST_NAME,'%'' AND ');
    END IF;
    IF AV_PASPORT_NAME IS NOT NULL  AND AV_PASPORT_NAME <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.FULL_NAME LIKE ''%',AV_PASPORT_NAME,'%'' AND ');
    END IF;
    IF AV_PRIMARY_EMAIL IS NOT NULL AND AV_PRIMARY_EMAIL <> '' THEN 
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.EMAIL_ADDRESS_PRIMARY LIKE ''%',AV_PRIMARY_EMAIL,'%'' AND ');
    END IF;
    IF AV_START_MONTH IS NOT NULL  AND AV_START_MONTH <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' MONTH(T1.AGREEMENT_START_DATE) = MONTH("',AV_START_MONTH,'") AND ',' YEAR(T1.AGREEMENT_START_DATE) = YEAR("',AV_START_MONTH,'") AND ');
    END IF;
    IF AV_EXTERNAL_REVIEWER_ID   IS NOT NULL  AND AV_EXTERNAL_REVIEWER_ID   <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.EXTERNAL_REVIEWER_ID   in (',AV_EXTERNAL_REVIEWER_ID  ,') AND ');
    END IF;
    IF AV_END_MONTH IS NOT NULL  AND AV_END_MONTH <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' MONTH(T1.AGREEMENT_END_DATE) = MONTH("',AV_END_MONTH,'") AND ',' YEAR(T1.AGREEMENT_END_DATE) = YEAR("',AV_END_MONTH,'") AND ');
    END IF;
    IF AV_STATUS IS NOT NULL  AND AV_STATUS <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.STATUS = ''',AV_STATUS ,''' AND ');
    END IF;
    IF AV_COUNTRY_CODE IS NOT NULL  AND AV_COUNTRY_CODE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.COUNTRY_CODE LIKE ''%',AV_COUNTRY_CODE,'%'' AND ');
    END IF;
    IF AV_ACADEMIC_AREA_CODE_SECONDARY IS NOT NULL  AND AV_ACADEMIC_AREA_CODE_SECONDARY <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.ACADEMIC_AREA_CODE_SECONDARY IN(''',REPLACE(AV_ACADEMIC_AREA_CODE_SECONDARY,",","','"),''') AND ');
    END IF;
    IF AV_ACADEMIC_AREA_CODE_PRIMARY IS NOT NULL  AND AV_ACADEMIC_AREA_CODE_PRIMARY <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.ACADEMIC_AREA_CODE_PRIMARY IN(''',REPLACE(AV_ACADEMIC_AREA_CODE_PRIMARY,",","','"),''') AND ');
    END IF;
    IF AV_AFFILATION_INSTITUITION_CODE IS NOT NULL  AND AV_AFFILATION_INSTITUITION_CODE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.AFFILATION_INSTITUITION_CODE = ''',AV_AFFILATION_INSTITUITION_CODE,''' AND ');
    END IF;
	IF AV_ACADEMIC_RANK_CODE IS NOT NULL  AND AV_ACADEMIC_RANK_CODE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.ACADEMIC_RANK_CODE IN(''',REPLACE(AV_ACADEMIC_RANK_CODE,",","','"),''') AND ');
    END IF;
    IF AV_HINDEX IS NOT NULL  AND AV_HINDEX <> '' THEN
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' ( ');
		 OPEN SELECTED_HINDEX_VALUE_CURSOR;
			INSERT_HINDEX_VALUE_LOOP: LOOP 
			FETCH SELECTED_HINDEX_VALUE_CURSOR INTO
			SELECTED_HINDEX_VALUE;
			IF DONE1 THEN
				LEAVE INSERT_HINDEX_VALUE_LOOP;
			END IF;
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T2.HI_INDEX ',SELECTED_HINDEX_VALUE,' OR ');
        END LOOP;
        CLOSE SELECTED_HINDEX_VALUE_CURSOR;
        SELECT TRIM(TRAILING 'OR ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,') AND ');
    END IF;
    IF AV_KEYWORD_CODE IS NOT NULL  AND AV_KEYWORD_CODE <> '' THEN
        SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T1.EXTERNAL_REVIEWER_ID IN (SELECT T9.EXTERNAL_REVIEWER_ID FROM EXTERNAL_REVIEWER T9 
    LEFT OUTER JOIN EXTERNAL_REVIEWER_SPECIALIZATION T8 ON T8.EXTERNAL_REVIEWER_ID = T9.EXTERNAL_REVIEWER_ID
    WHERE T8.SPECIALIZATION_CODE in (',AV_KEYWORD_CODE,')) AND ');
    END IF;
    IF LS_FILTER_CONDITION <> '' THEN 
    SET LS_FILTER_CONDITION = CONCAT(' WHERE ',LS_FILTER_CONDITION);
    SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;
    END IF;
    SET LS_DYN_SQL = CONCAT(
    '(SELECT DISTINCT  COUNT(1) FROM EXTERNAL_REVIEWER T1
    LEFT OUTER JOIN EXTERNAL_REVIEWER_EXT T2 ON T2.EXTERNAL_REVIEWER_ID = T1.EXTERNAL_REVIEWER_ID
    ',LS_FILTER_CONDITION,')'
);
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
END
