DELIMITER $$
CREATE  PROCEDURE `SR_CONTRACT_ADMIN_UPDATION`(AV_MODULE_KEY INT, AV_CHANGED_UNIT VARCHAR(20), AV_UPDATED_PERSON VARCHAR(200), AV_UPDATE_TIME TIMESTAMP)
PROC:BEGIN
END PROC
$$
DELIMITER ;
