-- `AWARD_DMP_END_DATE_REMAINDER`; 

CREATE PROCEDURE `AWARD_DMP_END_DATE_REMAINDER`( AV_DAYS INT )
BEGIN
	SELECT 0 AS SUB_MODULE_ITEM_KEY, AWARD_ID AS MODULE_ITEM_KEY, 1 AS MODULE_CODE, 0 AS SUB_MODULE_CODE FROM AWARD
	WHERE DATE(FINAL_EXPIRATION_DATE) = DATE(DATE_ADD(utc_timestamp(),INTERVAL AV_DAYS DAY));
END
