-- `AWARD_END_DATE_REMINDER`; 

CREATE PROCEDURE `AWARD_END_DATE_REMINDER`(AV_DAYS INT)
BEGIN
	SELECT 0 AS SUB_MODULE_ITEM_KEY, AWARD_ID AS MODULE_ITEM_KEY, 1 AS MODULE_CODE, 0 AS SUB_MODULE_CODE FROM AWARD
	WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE' AND DATE(FINAL_EXPIRATION_DATE) = DATE(DATE_ADD(utc_timestamp(),INTERVAL AV_DAYS DAY));
END
