-- `GET_AWARD_PAYMNT_SCHEDULE`; 

CREATE PROCEDURE `GET_AWARD_PAYMNT_SCHEDULE`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
SELECT 
        T1.AWARD_ID, 
        T1.AWARD_NUMBER,
        T1.AWARD_REPORT_TERM_DESC AS SCHEDULE_DETAILS,
        T1.DUE_DATE,
        T1.SUBMITTED_BY_PERSON_ID,
        CONCAT(T3.LAST_NM,", ",T3.FIRST_NM," ",T3.MIDDLE_NM)  AS FULL_NAME,
        T1.REPORT_STATUS_CODE,
        T2.DESCRIPTION AS STATUS,
        T1.STATUS_DESCRIPTION AS COMMENTS,
        T1.AMOUNT
    FROM AWARD_PAYMENT_SCHEDULE T1 
    LEFT OUTER JOIN REPORT_STATUS T2 ON T1.REPORT_STATUS_CODE = T2.REPORT_STATUS_CODE
    LEFT OUTER JOIN PERSON T3 ON T1.SUBMITTED_BY_PERSON_ID = T3.PERSON_ID
    WHERE T1.AWARD_ID = AV_AWARD_ID;
END
