-- `GET_AWARD_DATA_FOR_ORCID_SYNC`; 

CREATE PROCEDURE `GET_AWARD_DATA_FOR_ORCID_SYNC`(IN AV_AWARD_ID INT)
BEGIN
   SELECT 
        A.AWARD_ID AS AWARD_ID,
        A.AWARD_NUMBER AS AWARD_NUMBER,
        A.TITLE AS AWARD_TITLE,
        DATE(A.BEGIN_DATE) AS START_DATE, 
        DATE(A.FINAL_EXPIRATION_DATE) AS END_DATE,  
        AP.PERSON_ID AS PERSON_ID,
        P.FULL_NAME AS PI_FULL_NAME,
        S.SPONSOR_NAME AS SPONSOR_NAME,
        IFNULL(S.CITY, C.COUNTRY_NAME) AS SPONSOR_CITY,
        C.COUNTRY_CODE_ISO2 AS COUNTRY_CODE,
        P.ACCESS_TOKEN AS ACCESS_TOKEN,
        P.ORCID_ID AS ORCID_ID,
        S.ROR_ID AS DISAMBIGUATED_ORGANIZATION_IDENTIFIER, 
        'ROR' AS DISAMBIGUATED_ORGANIZATION_SOURCE
   FROM 
        AWARD A
   LEFT JOIN 
        SPONSOR S ON A.SPONSOR_CODE = S.SPONSOR_CODE
   LEFT JOIN 
        AWARD_PERSONS AP ON A.AWARD_ID = AP.AWARD_ID AND AP.PI_FLAG = 'Y' 
   LEFT JOIN 
        COUNTRY C ON S.COUNTRY_CODE = C.COUNTRY_CODE
   LEFT JOIN 
        PERSON P ON AP.PERSON_ID = P.PERSON_ID
   WHERE 
        A.AWARD_ID = AV_AWARD_ID;
END
