CREATE PROCEDURE `GET_SAP_FEED_DASHBOARD_COUNT`(
AV_BATCH_ID 		VARCHAR(5),
AV_FEED_START_DATE	VARCHAR(30),
AV_FEED_END_DATE	VARCHAR(30),
AV_AWARD_ID		VARCHAR(22),
AV_AWARD_NUMBER		VARCHAR(20),
AV_FEED_STATUS		VARCHAR(20),
AV_ACCOUNT_NUMBER VARCHAR(20),
AV_PAGED                                         INT(10),
AV_SORT_TYPE                             VARCHAR(500),
AV_LIMIT                                         INT(10),
AV_TAB_TYPE                                  VARCHAR(30),
AV_UNLIMITED                     BOOLEAN,
AV_TYPE                          VARCHAR(1)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
DECLARE TAB_QUERY LONGTEXT;
DECLARE TAB_QUERY1 LONGTEXT;
DECLARE JOIN_CONDITION LONGTEXT;
DECLARE SELECTED_FIELD_LIST LONGTEXT;

SET LS_OFFSET = (AV_LIMIT * AV_PAGED);

SET LS_FILTER_CONDITION ='';
SET LS_DYN_SQL ='';
SET JOIN_CONDITION = '';
SET SELECTED_FIELD_LIST= '';
SET TAB_QUERY ='';



IF AV_TYPE = 'A'   THEN


						IF AV_AWARD_NUMBER IS NOT NULL  AND AV_AWARD_NUMBER <> '' THEN
                         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.AWARD_NUMBER LIKE ''%',AV_AWARD_NUMBER,'%'' AND ');
                        END IF;
                        
                        IF AV_BATCH_ID IS NOT NULL  AND AV_BATCH_ID <> '' THEN
                         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.BATCH_ID LIKE ''%',AV_BATCH_ID,'%'' AND ');
                        END IF;
                        
						IF AV_AWARD_ID IS NOT NULL  AND AV_AWARD_ID <> '' THEN
                         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.AWARD_ID LIKE ''%',AV_AWARD_ID,'%'' AND ');
                        END IF;
                        
                        IF AV_ACCOUNT_NUMBER IS NOT NULL  AND AV_ACCOUNT_NUMBER <> '' THEN
                         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.ACCOUNT_NUMBER LIKE ''%',AV_ACCOUNT_NUMBER,'%'' AND ');
                        END IF;
                        
						IF AV_FEED_STATUS IS NOT NULL AND AV_FEED_STATUS <> '' AND AV_FEED_STATUS <> 'A'  AND AV_FEED_STATUS <> 'AP' THEN
                         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.FEED_STATUS in (''',AV_FEED_STATUS,''') AND ');
                        END IF;
                        
                         IF AV_FEED_START_DATE IS NOT NULL  AND AV_FEED_START_DATE <> '' AND AV_FEED_END_DATE IS  NULL AND AV_FEED_END_DATE = '' THEN
                         SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.CREATE_TIMESTAMP = DATE_FORMAT(''',AV_FEED_START_DATE,''',''%Y-%m-%d'') AND ');
                        END IF;
                        
                        IF AV_FEED_END_DATE IS NOT NULL  AND AV_FEED_END_DATE <> '' AND AV_FEED_START_DATE IS  NULL  AND AV_FEED_START_DATE = '' THEN
                          SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.CREATE_TIMESTAMP = DATE_FORMAT(''',AV_FEED_END_DATE,''',''%Y-%m-%d'') AND ');
                        END IF;
                        
                       IF AV_FEED_END_DATE IS NOT NULL  AND AV_FEED_END_DATE <> '' AND AV_FEED_START_DATE IS NOT NULL  AND AV_FEED_START_DATE <> '' THEN
                          SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.CREATE_TIMESTAMP BETWEEN DATE_FORMAT(''',AV_FEED_START_DATE,''',''%Y-%m-%d'') AND DATE_FORMAT(''',AV_FEED_END_DATE,''',''%Y-%m-%d'') AND ');
                        END IF;

END IF;


IF AV_TAB_TYPE = 'BATCH_DETAIL' THEN

		SET JOIN_CONDITION = CONCAT('SELECT 
		T1.FEED_ID,
		T1.BATCH_ID,
        T1.AWARD_NUMBER,
        T1.AWARD_ID,
        T4.ACCOUNT_NUMBER,
		T1.FEED_TYPE,
        T1.FEED_STATUS ,
        T1.USER_ACTION_CODE,
        T5.DESCRIPTION AS FEED_TYPE_DESC,
        T6.DESCRIPTION AS FEED_STATUS_DESC,
        T7.USER_ACTION AS USER_ACTION_CODE_DESC,
        T1.USER_COMMENT,
		T3.CREATE_TIMESTAMP,
		T2.FULL_NAME,
		T3.RESPONSE_TIMESTAMP,
        T1.UPDATE_TIMESTAMP,
        T1.UPDATE_USER,
        T1.SEQUENCE_NUMBER,
        T8.FULL_NAME AS PI_NAME,
        T2.FULL_NAME AS UPDATE_USER_NAME
	FROM SAP_AWARD_FEED T1
    LEFT JOIN PERSON T2 ON T2.USER_NAME = T1.UPDATE_USER
    LEFT JOIN AWARD T4 ON T4.AWARD_ID = T1.AWARD_ID
	LEFT JOIN sap_feed_type T5 ON T5.FEED_TYPE_CODE = T1.FEED_TYPE
	LEFT JOIN sap_feed_status T6 ON T6.FEED_STATUS_CODE = T1.FEED_STATUS
	LEFT JOIN sap_feed_user_actions T7 ON T7.USER_ACTION_CODE = T1.USER_ACTION_CODE
    LEFT JOIN AWARD_PERSONS T8 ON T8.AWARD_ID = T1.AWARD_ID AND T8.PI_FLAG = ''Y''
	LEFT JOIN SAP_AWARD_FEED_BATCH T3 ON T1.BATCH_ID = T3.BATCH_ID
		');
                                    
	IF AV_TYPE = 'A' THEN							
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.FEED_STATUS in (''E'',''R'',''F'',''N'') AND ');
	ELSE 
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.FEED_STATUS in (''E'') AND ');
	END IF;
                                
		IF AV_SORT_TYPE IS  NULL THEN
			SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
		END IF;
        
  ELSEIF AV_TAB_TYPE = 'PENDING_FEEDS' THEN
  
		SET JOIN_CONDITION = CONCAT('SELECT 
		T1.FEED_ID,
		T1.BATCH_ID,
        T1.AWARD_NUMBER,
        T1.AWARD_ID,
        T4.ACCOUNT_NUMBER,
		T1.FEED_TYPE,
        T1.FEED_STATUS ,
        T1.USER_ACTION_CODE,
        T5.DESCRIPTION AS FEED_TYPE_DESC,
        T6.DESCRIPTION AS FEED_STATUS_DESC,
        T7.USER_ACTION AS USER_ACTION_CODE_DESC,
        T1.USER_COMMENT,
		T3.CREATE_TIMESTAMP,
		T2.FULL_NAME,
		T3.RESPONSE_TIMESTAMP,
        T1.UPDATE_TIMESTAMP,
        T1.UPDATE_USER,
        T1.SEQUENCE_NUMBER,
        T8.FULL_NAME AS PI_NAME,
        T2.FULL_NAME AS UPDATE_USER_NAME
	FROM SAP_AWARD_FEED T1
    LEFT JOIN PERSON T2 ON T2.USER_NAME = T1.UPDATE_USER
    LEFT JOIN AWARD T4 ON T4.AWARD_ID = T1.AWARD_ID
	LEFT JOIN sap_feed_type T5 ON T5.FEED_TYPE_CODE = T1.FEED_TYPE
	LEFT JOIN sap_feed_status T6 ON T6.FEED_STATUS_CODE = T1.FEED_STATUS
	LEFT JOIN sap_feed_user_actions T7 ON T7.USER_ACTION_CODE = T1.USER_ACTION_CODE
    LEFT JOIN AWARD_PERSONS T8 ON T8.AWARD_ID = T1.AWARD_ID AND T8.PI_FLAG = ''Y''
	LEFT JOIN SAP_AWARD_FEED_BATCH T3 ON T1.BATCH_ID = T3.BATCH_ID');
			
		SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.FEED_STATUS in (''P'',''H'',''X'',''N'') AND ');

		IF AV_SORT_TYPE IS  NULL THEN
			SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.UPDATE_TIMESTAMP DESC ');
		END IF;
                    
	ELSEIF AV_TAB_TYPE = 'BATCH_HISTORY'   THEN
	
		SET JOIN_CONDITION = CONCAT('SELECT 
		T1.BATCH_ID,
        T1.FEED_STATUS,
		T3.CREATE_TIMESTAMP,
		T1.AWARD_NUMBER,
        T1.AWARD_ID,
        T4.ACCOUNT_NUMBER,
		T2.FULL_NAME,
		T3.RESPONSE_TIMESTAMP
		FROM SAP_AWARD_FEED T1
		LEFT JOIN PERSON T2 ON T2.USER_NAME = T1.UPDATE_USER
		LEFT JOIN AWARD T4 ON T4.AWARD_ID = T1.AWARD_ID
		LEFT JOIN SAP_AWARD_FEED_BATCH T3 ON T1.BATCH_ID = T3.BATCH_ID 
        WHERE T1.FEED_STATUS in (''E'',''R'',''F'',''N'',''C'')');
                                    
		-- SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' T.FEED_STATUS in (''E'',''R'',''F'',''N'',''C'') AND ');		
                
		IF AV_SORT_TYPE IS  NULL THEN
			SET AV_SORT_TYPE =  CONCAT(' ORDER BY T.BATCH_ID DESC ');
		END IF;
        
END IF;



IF AV_UNLIMITED = TRUE THEN
        SET LS_OFFSET_CONDITION = '';
ELSE
        SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ',AV_LIMIT,' OFFSET ',LS_OFFSET);
END IF;

IF LS_FILTER_CONDITION <>'' THEN

SET LS_FILTER_CONDITION = CONCAT(' WHERE ',LS_FILTER_CONDITION);
SELECT TRIM(TRAILING 'AND ' FROM LS_FILTER_CONDITION) into LS_FILTER_CONDITION from dual;

END IF;

IF AV_TAB_TYPE = 'BATCH_HISTORY'   THEN
SET LS_DYN_SQL =CONCAT('SELECT  COUNT(DISTINCT T.BATCH_ID) FROM(
                                    ',JOIN_CONDITION,TAB_QUERY,
                                     ')T ',LS_FILTER_CONDITION,'',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION );
ELSE
     SET LS_DYN_SQL =CONCAT('SELECT DISTINCT COUNT(*) FROM(
                                    ',JOIN_CONDITION,TAB_QUERY,
                                     ')T ',LS_FILTER_CONDITION,' ',AV_SORT_TYPE,' ',LS_OFFSET_CONDITION );
 END IF;                                   
-- SELECT LS_DYN_SQL;
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT ;

END
