-- `GET_AWARD_UNIT_CONTACT`; 

CREATE PROCEDURE `GET_AWARD_UNIT_CONTACT`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
   SELECT 
    T1.AWARD_ID,
    T1.ROLODEX_ID,
    T1.FULL_NAME,
    T3.EMAIL_ADDRESS,
    T3.OFFICE_PHONE
    FROM AWARD_CONTACT T1
    LEFT OUTER JOIN PERSON T3 ON T1.ROLODEX_ID = T3.PERSON_ID
    WHERE T1.AWARD_ID = AV_AWARD_ID;
END
