-- `GET_AWARD_PAYMENT_INVOICE`; 

CREATE PROCEDURE `GET_AWARD_PAYMENT_INVOICE`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
SELECT 
        T1.AWARD_ID,
        T1.AWARD_NUMBER,
        T1.REPORT_CLASS_CODE,
        T2.DESCRIPTION AS REPORT_CLASS,
        T1.REPORT_CODE,
        T3.DESCRIPTION AS REPORT,
        T1.FREQUENCY_CODE,
        T4.DESCRIPTION AS FREQUENCY,
        T1.FREQUENCY_BASE_CODE,
        T5.DESCRIPTION AS FREQUENCY_BASE,
        T1.OSP_DISTRIBUTION_CODE,
        T6.DESCRIPTION AS OSP_DISTRIBUTION,
        T1.DUE_DATE
    FROM AWARD_REPORT_TERMS T1
    INNER JOIN REPORT_CLASS T2 ON T1.REPORT_CLASS_CODE = T2.REPORT_CLASS_CODE AND T1.REPORT_CLASS_CODE = 6
    INNER JOIN REPORT T3 ON T1.REPORT_CODE = T3.REPORT_CODE 
    INNER JOIN FREQUENCY T4 ON T1.FREQUENCY_CODE = T4.FREQUENCY_CODE
    INNER JOIN FREQUENCY_BASE T5 ON T1.FREQUENCY_BASE_CODE = T5.FREQUENCY_BASE_CODE
    INNER JOIN DISTRIBUTION T6 ON T1.OSP_DISTRIBUTION_CODE = T6.OSP_DISTRIBUTION_CODE
    WHERE T1.AWARD_ID = AV_AWARD_ID;
END
