-- `GET_AWARD_SPECIAL_REVIEW`; 

CREATE PROCEDURE `GET_AWARD_SPECIAL_REVIEW`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
SELECT 
    T1.AWARD_ID,
    T1.SPECIAL_REVIEW_CODE,
    T2.DESCRIPTION AS SPECIAL_REVIEW_TYPE,
    T1.APPROVAL_TYPE_CODE,
    T3.DESCRIPTION,
    '' AS APPROVAL_STATUS,
    T1.PROTOCOL_NUMBER,
    DATE_FORMAT(T1.APPLICATION_DATE,'%m/%d/%Y') AS APPLICATION_DATE,
    DATE_FORMAT(T1.APPROVAL_DATE,'%m/%d/%Y') AS APPROVAL_DATE,
    DATE_FORMAT(T1.EXPIRATION_DATE,'%m/%d/%Y') AS EXPIRATION_DATE
    FROM AWARD_SPECIAL_REVIEW T1
    LEFT OUTER JOIN SPECIAL_REVIEW T2 ON T1.SPECIAL_REVIEW_CODE = T2.SPECIAL_REVIEW_CODE
    LEFT OUTER JOIN SP_REV_APPROVAL_TYPE T3 ON T1.APPROVAL_TYPE_CODE = T3.APPROVAL_TYPE_CODE
    WHERE T1.AWARD_ID = AV_AWARD_ID;
END
