-- `GET_AWARD_FA_RATES`; 

CREATE PROCEDURE `GET_AWARD_FA_RATES`(
IN AV_AWARD_ID INT)
    DETERMINISTIC
BEGIN
SELECT 
    T1.AWARD_ID,
    T1.AWARD_NUMBER,
    T1.APPLICABLE_IDC_RATE,
    T1.IDC_RATE_TYPE_CODE,
    T2.DESCRIPTION AS IDC_RATE_TYPE,
    T1.FISCAL_YEAR,
    T1.START_DATE,
	CASE WHEN T1.ON_CAMPUS_FLAG = 'N' THEN 'on'
		  WHEN T1.ON_CAMPUS_FLAG = 'F' THEN 'off'
	END AS CAMPUS
FROM AWARD_IDC_RATE T1 
INNER JOIN IDC_RATE_TYPE T2 ON T1.IDC_RATE_TYPE_CODE = T2.IDC_RATE_TYPE_CODE
WHERE AWARD_ID = AV_AWARD_ID;
END
