-- `INSERT_MIGRATION_DATA_TO_SAP`; 

CREATE PROCEDURE `INSERT_MIGRATION_DATA_TO_SAP`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE C1 CURSOR FOR 
	SELECT T1.AWARD_ID, T1.AWARD_NUMBER, T2.SEQUENCE_NUMBER FROM MIGRATION_LEGACY_AWARD_MAPPING T1
	INNER JOIN AWARD T2 ON T2.AWARD_ID = T1.AWARD_ID;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE LI_AWARD_ID DECIMAL(22,0);
	DECLARE LS_AWARD_NUMBER VARCHAR(12);
	DECLARE LI_SEQUENCE_NUMBER INT(4);
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
FETCH C1 INTO LI_AWARD_ID, LS_AWARD_NUMBER, LI_SEQUENCE_NUMBER;
IF DONE THEN
LEAVE LOOP1;
END IF;
			CALL SAP_AWARD_FEED(LI_AWARD_ID, LS_AWARD_NUMBER, LI_SEQUENCE_NUMBER, 'admin');
END; 
END LOOP;
CLOSE C1;
END
