CREATE PROCEDURE `MERGE_AWD_SECTION_DISTRIBUTION`(
AV_AWARD_ID 			INT,
AV_AWARD_NUMBER			VARCHAR(12),
AV_SEQUENCE_NUMBER		INT(4),
AV_VARIATION_TYPE_CODE	VARCHAR(3),
AV_UPDATE_USER			VARCHAR(60)
)
BEGIN

DECLARE LS_ERROR_MSG						VARCHAR(1000);
DECLARE LS_TABLE_NAME						VARCHAR(30);
DECLARE LI_FLAG								INT;
DECLARE LI_MASTER_AWARD_ID					DECIMAL(22,0);
DECLARE LI_MASTER_SEQ_NUMBER				INT(4);

DECLARE LS_BUDGET_PERIOD 			INT(11);
DECLARE	LS_COMMENT 					VARCHAR(4000);
DECLARE	LS_CREATE_TIMESTAMP 		DATETIME;
DECLARE	LS_CREATE_USER 				VARCHAR(60);
DECLARE	LS_END_DATE 				DATETIME;
DECLARE	LS_START_DATE 				DATETIME;
DECLARE	LS_TOTAL_DIRECT_COST		DECIMAL(15,2);
DECLARE	LS_TOTAL_INDIRECT_COST		DECIMAL(15,2);


DECLARE LS_UPDATE_TIMESTAMP	DATETIME;
DECLARE LS_UPDATE_USER		VARCHAR(60);
				


	BEGIN
	
			DECLARE EXIT HANDLER FOR SQLEXCEPTION
			BEGIN
			
				GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
				 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
				 
				SET @full_error = CONCAT(@msg,'|SEC108|',LS_TABLE_NAME );
					
				SELECT @full_error INTO LS_ERROR_MSG;
																	
				RESIGNAL SET MESSAGE_TEXT = LS_ERROR_MSG;
				
			END;
			
			SELECT COUNT(1) INTO LI_FLAG
			FROM AWARD 
			WHERE AWARD_NUMBER = AV_AWARD_NUMBER
			AND SEQUENCE_NUMBER = 0;
			
			IF LI_FLAG > 0 THEN
			
				SELECT AWARD_ID,SEQUENCE_NUMBER 
				INTO LI_MASTER_AWARD_ID,LI_MASTER_SEQ_NUMBER
				FROM AWARD 
				WHERE AWARD_NUMBER = AV_AWARD_NUMBER
				AND SEQUENCE_NUMBER = 0;
			
			END IF;
			
			DELETE FROM AWARD_AMT_FNA_DISTRIBUTION
			WHERE AWARD_ID = LI_MASTER_AWARD_ID;
			
			-- -------------------------------STARTS INSERT INTO AWARD_AMT_FNA_DISTRIBUTION-----------------------
			SET LS_TABLE_NAME = 'AWARD_AMT_FNA_DISTRIBUTION';
            BEGIN
			
				DECLARE DONE1 INT DEFAULT FALSE;

				DECLARE CUR_AWARD_AMT_DIST_ST CURSOR FOR
				SELECT 
					BUDGET_PERIOD,
					COMMENT,
					CREATE_TIMESTAMP,
					CREATE_USER,
					END_DATE,
					START_DATE,
					TOTAL_DIRECT_COST,
					TOTAL_INDIRECT_COST,
					UPDATE_TIMESTAMP,
					UPDATE_USER
				FROM AWARD_AMT_FNA_DISTRIBUTION
				WHERE AWARD_ID = AV_AWARD_ID;
				
				DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

				OPEN CUR_AWARD_AMT_DIST_ST;
				INSERT_CUR_AWARD_AMT_DIST_ST_LOOP: LOOP 
				FETCH CUR_AWARD_AMT_DIST_ST INTO
					LS_BUDGET_PERIOD,
					LS_COMMENT,
					LS_CREATE_TIMESTAMP,
					LS_CREATE_USER,
					LS_END_DATE,
					LS_START_DATE,
					LS_TOTAL_DIRECT_COST,
					LS_TOTAL_INDIRECT_COST,
					LS_UPDATE_TIMESTAMP,
					LS_UPDATE_USER;
								
				IF DONE1 THEN
					LEAVE INSERT_CUR_AWARD_AMT_DIST_ST_LOOP;
				END IF;
				
				INSERT INTO AWARD_AMT_FNA_DISTRIBUTION(
				AWARD_ID, 
				AWARD_NUMBER, 
				SEQUENCE_NUMBER, 
				BUDGET_PERIOD,
				COMMENT,
				CREATE_TIMESTAMP,
				CREATE_USER,
				END_DATE,
				START_DATE,
				TOTAL_DIRECT_COST,
				TOTAL_INDIRECT_COST,
				UPDATE_TIMESTAMP,
				UPDATE_USER
				)
				VALUES
				(
				LI_MASTER_AWARD_ID,
				AV_AWARD_NUMBER,
				LI_MASTER_SEQ_NUMBER,
				LS_BUDGET_PERIOD,
				LS_COMMENT,
				LS_CREATE_TIMESTAMP,
				LS_CREATE_USER,
				LS_END_DATE,
				LS_START_DATE,
				LS_TOTAL_DIRECT_COST,
				LS_TOTAL_INDIRECT_COST,
				LS_UPDATE_TIMESTAMP,
				LS_UPDATE_USER
				);
			
				END LOOP;
				CLOSE CUR_AWARD_AMT_DIST_ST;
			
			END;
			-- -------------------------------ENDS INSERT INTO AWARD_AMT_FNA_DISTRIBUTION-------------------------
	END;
END
