-- `SAP_FEED_PROBLEMATIC_GRANT_CODE_REPORT`; 

CREATE PROCEDURE `SAP_FEED_PROBLEMATIC_GRANT_CODE_REPORT`(AV_BATCH_ID INT)
BEGIN
	
DECLARE LI_FEED_ID							INT;
DECLARE LI_AWARD_ID 						INT;
DECLARE LS_AWARD_NUMBER 					VARCHAR(12);
DECLARE LI_SEQUENCE_NUMBER 					INT;
DECLARE LI_FLAG								INT;
DECLARE LI_BATCH_ID							INT;
DECLARE LI_ERR_FLAG 						INT;
DECLARE LS_ERROR_MSG        				VARCHAR(4000);
DECLARE LI_SEQ_ERROR_LOG_ID					INT;
DECLARE LI_SPONSOR_PRGM_ID  				INT;
DECLARE LI_SPONSOR_CLASS_ID 				INT;
DECLARE LI_GRANT_MASTER_ID 					INT;
DECLARE LS_ACCOUNT_NUMBER  					VARCHAR(100);
DECLARE LS_TITLE            				VARCHAR(1000);
DECLARE LS_IO_CODE          				VARCHAR(50);
DECLARE LS_COST_ELEMENT						VARCHAR(200);
DECLARE LS_GRANT_CODE 						VARCHAR(4000);
DECLARE LS_FUND_CODE						VARCHAR(4000);
DECLARE LI_CUSTOM_DATA_ELEMENTS_ID			INT;
DECLARE LI_FUNDED_PRGM_ID 					INT;
DECLARE LS_UPDATE_USER 						VARCHAR(60);
DECLARE LI_GRANT_BUD_MASTER_ID				INT;
DECLARE LI_LINE_ITEM_COST					DECIMAL(15,2);
DECLARE	LI_PREV_LINE_ITEM_COST				DECIMAL(15,2);
DECLARE	LS_LINE_ITEM_DESCRIPTION			VARCHAR(200);
DECLARE LI_BUDGET_AMOUNT					DECIMAL(15,2);
DECLARE LI_FM_BUDGET_ID						INT;
DECLARE LS_LEAD_UNIT_NUMBER					VARCHAR(50);
DECLARE LI_PROJECT_DEF_ID					INT;
DECLARE LS_AWARD_TITLE 						VARCHAR(1000);
DECLARE LS_AWARD_START_DATE					DATETIME;
DECLARE LS_AWARD_END_DATE					DATETIME;
DECLARE LI_WBS_ID							INT;
DECLARE LS_ACCOUNT_TYPE_CODE				VARCHAR(3);
DECLARE LS_PROJECT_TYPE         			VARCHAR(3);
DECLARE LS_AWARD_PI_NAME					VARCHAR(20);
DECLARE LS_INPUT_GST						VARCHAR(4000);
DECLARE LS_GST_CLAIMABLE					VARCHAR(1);

DECLARE LS_CLASS_TYPE						VARCHAR(1);	
DECLARE LS_GRANT_CURRENCY					VARCHAR(3);
DECLARE LS_FUNDED_PROGRAM_TYPE				VARCHAR(4);
DECLARE LS_PROCESS							VARCHAR(4);
DECLARE LS_HEADER_DESCRIPTION				VARCHAR(40);
DECLARE LS_BUDGET_VERSION					VARCHAR(4);
DECLARE LS_PROJECT_PROFILE					VARCHAR(80);
DECLARE LS_PROJECT_CURRENCY					VARCHAR(80);
DECLARE LS_FACTORY_CALENDER_KEY				VARCHAR(80); 
DECLARE LS_BUDGET_PROFILE					VARCHAR(80);
DECLARE LS_PLANNING_PROFILE					VARCHAR(80);
DECLARE LS_KEYWORD_ID 						VARCHAR(7);
DECLARE LS_BILLING_ELEMENT					VARCHAR(1);
DECLARE LS_OBJECT_CLASS						VARCHAR(5); 
DECLARE LS_FACTORY_CALENDER					VARCHAR(2);
DECLARE LS_PERSON_RESPONSIBLE_NUMBER		VARCHAR(50);
DECLARE LS_COMPANY_CODE						VARCHAR(80);
DECLARE LS_CONTROLLING_AREA					VARCHAR(80);
DECLARE LS_PLANT							VARCHAR(80);
DECLARE LS_ERROR_TABLE						VARCHAR(30);
DECLARE LS_PROFIT_CENTER 					VARCHAR(4000);
DECLARE LS_AWARD_STATUS_CODE 				VARCHAR(3);
DECLARE LS_AWARD_STATUS 					VARCHAR(1);
DECLARE LS_BA_CODE							VARCHAR(4);
DECLARE LS_PARENT_UNIT_NUMBER 				VARCHAR(50);
DECLARE LS_FEED_START_DATE 					VARCHAR(15);
DECLARE LS_FEED_START_YEAR 					VARCHAR(4);
DECLARE LS_FISCAL_YEAR						INT(4);
DECLARE LS_BUDGET_CATEGORY_CODE				VARCHAR(3);
DECLARE LS_COMMITMENT_ITEM 					VARCHAR(10);
DECLARE LS_AWD_ACCOUNT_TYPE_CODE 			VARCHAR(3);
DECLARE LS_PARENT_AWARD_NUMBER 				VARCHAR(12);
DECLARE LS_ACCOUNT_ASSIGN_ELEMENT 			VARCHAR(1);
DECLARE LS_FEED_STATUS 						VARCHAR(1);
DECLARE LS_CREATE_STATUS 					VARCHAR(1);
DECLARE LI_WRITE_FLAG						INT; -- CHECKING ROWLEVEL.IF LI_WRITE_FLAG = 1 THEN ABLE TO WRITE INTO TABLE ELSE NO NEED TO CREATE A NEW ENTRY
DECLARE LS_PROGRAM_DESCRIPTION				VARCHAR(30);
DECLARE LI_WBS_L1_LEVEL 					INT(3);
DECLARE LI_WBS_L2_LEVEL     				INT(3);
DECLARE LS_WBS_L1_ACCOUNT_ASSIGNMENT       	VARCHAR(1);
DECLARE LS_WBS_L2_ACCOUNT_ASSIGNMENT    	VARCHAR(1);
DECLARE LS_POSTING_DATE						DATETIME;
DECLARE LI_BUDGET_HEADER_ID					INT;
DECLARE LS_ROOT_AWARD_NUMBER				VARCHAR(12);
DECLARE LS_GM_DOC_TYPE						VARCHAR(2);
DECLARE LS_FUND_CENTER						VARCHAR(10);
DECLARE LS_DISTR_KEY						VARCHAR(1);
DECLARE LS_FM_AREA							VARCHAR(3);
DECLARE LS_COST_CENTER						VARCHAR(10);
DECLARE LS_RETURN_AWARD_ID					VARCHAR(22);
DECLARE LI_FM_ID 							INT;
DECLARE LS_LINE_ITEM						VARCHAR(20);
DECLARE LI_LINE_ITEM_COUNT					INT;
DECLARE LS_BCS_VALUE_TYPE					VARCHAR(2);
DECLARE LS_FM_DOC_TYPE						VARCHAR(4);
DECLARE LS_BUDGET_TYPE						VARCHAR(4);
DECLARE LS_GRANT							VARCHAR(10);
DECLARE LS_FM_DISTRIBUTION_KEY				VARCHAR(1);
DECLARE LI_CURRENT_TOTAL_COST				DECIMAL(15,2);
DECLARE LI_PREV_TOTAL_COST					DECIMAL(15,2);
DECLARE LS_LAST_PROCESS						VARCHAR(4);
DECLARE LS_L1_WBS_SHORT_DESCRIPTION 		VARCHAR(40);
DECLARE LS_L1_WBS_PI_NAME					VARCHAR(40);
DECLARE LS_SPONSOR_AWARD_NUMBER				VARCHAR(40);
DECLARE LS_L2_WBS_SHORT_DESCRIPTION			VARCHAR(40);
DECLARE LI_PREV_FEED_ID 					INT;
DECLARE LI_PREV_AWARD_ID 					INT;
DECLARE LI_PREV_BATCH_ID					INT;
DECLARE LS_CHK_ANY_FEED						VARCHAR(1);
DECLARE LS_CUR_LINE_ITEM					VARCHAR(20);
DECLARE LI_CUR_VERSION_NUMBER				INT(3);
DECLARE LI_PREV_VERSION_NUMBER				INT(3);
DECLARE LI_TRAN_COUNT						INT;
DECLARE LS_TRAN_LINE_ITEM					VARCHAR(20);
DECLARE LI_TOTAL_COUNT						INT;
DECLARE LS_AWARD_VARIATION_TYPE_CODE		VARCHAR(3);
DECLARE LS_AWARD_DOCUMENT_TYPE_CODE 		VARCHAR(3);
DECLARE LI_GRANT_CODE_EXCLUSION_FLAG		INT;
DECLARE LS_VARIATION_TYPE					VARCHAR(200);
DECLARE LS_VARIATION_TYPE_CODE				VARCHAR(3);
DECLARE LS_CUR_PI_NAME 						VARCHAR(40);
DECLARE LS_COST_ELEMENT_DESCRIPTION			VARCHAR(200);
DECLARE LI_REPORT_ID						INT(11);
DECLARE LS_ACCOUNT_TYPE 					VARCHAR(200);



	
		BEGIN
		-- ---------STARTS ERROR LOGGING--------------------------------
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
			
			INSERT INTO SAP_FEED_REPORT_ERROR_LOG(ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LS_ERROR_MSG,utc_timestamp(),'admin');
			COMMIT;
			
			
		END;
		
		-- -------------ENDS ERROR LOGGING -------------------------------
	
			
		-- ---------STARTS SELECTING HARDCODED VALUES----------------------------------------
		
		SELECT 
			-- CLASS_TYPE,
			GRANT_CURRENCY,
			-- FUNDED_PROGRAM_TYPE,
			-- PROCESS,
			HEADER_DESCRIPTION,
			BUDGET_VERSION,
			PROJECT_PROFILE,
			PROJECT_CURRENCY,
			FACTORY_CALENDER_KEY, 
			BUDGET_PROFILE,
			PLANNING_PROFILE,
			KEYWORD_ID,
			BILLING_ELEMENT,
			OBJECT_CLASS, 
			FACTORY_CALENDER,
			WBS_L1_LEVEL,
			WBS_L2_LEVEL,
			WBS_L1_ACCOUNT_ASSIGNMENT,
			WBS_L2_ACCOUNT_ASSIGNMENT,
			GM_DOC_TYPE,
			DISTR_KEY,
			FM_AREA,
			BCS_VALUE_TYPE,
			FM_DOC_TYPE,
			BUDGET_TYPE,
			FM_GRANT,
			FM_DISTRIBUTION_KEY
		INTO
			-- LS_CLASS_TYPE,
			LS_GRANT_CURRENCY,
			-- LS_FUNDED_PROGRAM_TYPE,
			-- LS_PROCESS,
			LS_HEADER_DESCRIPTION,
			LS_BUDGET_VERSION,
			LS_PROJECT_PROFILE,
			LS_PROJECT_CURRENCY,
			LS_FACTORY_CALENDER_KEY,
			LS_BUDGET_PROFILE,
			LS_PLANNING_PROFILE,
			LS_KEYWORD_ID,
			LS_BILLING_ELEMENT,
			LS_OBJECT_CLASS,
			LS_FACTORY_CALENDER,
			LI_WBS_L1_LEVEL,
			LI_WBS_L2_LEVEL,
			LS_WBS_L1_ACCOUNT_ASSIGNMENT,
			LS_WBS_L2_ACCOUNT_ASSIGNMENT,
			LS_GM_DOC_TYPE,
			LS_DISTR_KEY,
			LS_FM_AREA,
			LS_BCS_VALUE_TYPE,
			LS_FM_DOC_TYPE,
			LS_BUDGET_TYPE,
			LS_GRANT,
			LS_FM_DISTRIBUTION_KEY
		FROM 
		SAP_FEED_HARDCODE_VALUES;
			
		
		
		-- ---------ENDS SELECTING HARDCODED VALUES------------------------------------------
		BEGIN
			DECLARE DONE1 INT DEFAULT FALSE;

			DECLARE CUR_FEED_DATA CURSOR FOR
			SELECT T2.FEED_ID,T2.AWARD_ID,T2.AWARD_NUMBER,T2.SEQUENCE_NUMBER FROM SAP_AWARD_FEED_BATCH_ERROR_LOG T1
			INNER JOIN SAP_AWARD_FEED T2 ON T1.FEED_ID = T2.FEED_ID
			WHERE T1.BATCH_ID = AV_BATCH_ID AND T1.ERROR_TYPE = 'GRANT_CODE_ERROR'
			ORDER BY T2.FEED_ID;
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

			OPEN CUR_FEED_DATA;
			INSERT_LOOP: LOOP 
			FETCH CUR_FEED_DATA INTO
			LI_FEED_ID,
			LI_AWARD_ID,
			LS_AWARD_NUMBER,
			LI_SEQUENCE_NUMBER;
			
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
						
				SELECT 
					IF(TRIM(ACCOUNT_NUMBER) = '',NULL,TRIM(ACCOUNT_NUMBER)),
					IF(TRIM(TITLE)='',NULL,SUBSTR(TRIM(UPPER(TITLE)),1,30)),
					IF(TRIM(LEAD_UNIT_NUMBER) = '',NULL,TRIM(LEAD_UNIT_NUMBER)),
					-- AWARD_EFFECTIVE_DATE,
					BEGIN_DATE,
					FINAL_EXPIRATION_DATE,
					IF(TRIM(STATUS_CODE) = '',NULL,TRIM(STATUS_CODE)),
					IF(TRIM(ACCOUNT_TYPE_CODE) = '',NULL,TRIM(ACCOUNT_TYPE_CODE))
				INTO 
					LS_ACCOUNT_NUMBER,
					LS_TITLE,
					LS_LEAD_UNIT_NUMBER,
					LS_AWARD_START_DATE,
					LS_AWARD_END_DATE,
					LS_AWARD_STATUS_CODE,
					LS_AWD_ACCOUNT_TYPE_CODE
				FROM AWARD
				WHERE AWARD_ID = LI_AWARD_ID;
				
				SELECT 
					PERSON_RESPONSIBLE_NUMBER,
					COMPANY_CODE,
					CONTROLLING_AREA,
					PLANT
				INTO
					LS_PERSON_RESPONSIBLE_NUMBER,
					LS_COMPANY_CODE,
					LS_CONTROLLING_AREA,
					LS_PLANT
					
				FROM SAP_FEED_UNIT_MAPPING
				WHERE UNIT_NUMBER = LS_LEAD_UNIT_NUMBER;
				
				SELECT 
				T1.AWARD_VARIATION_TYPE_CODE,
				T2.DESCRIPTION,
				T3.DESCRIPTION 
				INTO 
				LS_VARIATION_TYPE_CODE,
				LS_VARIATION_TYPE,
				LS_ACCOUNT_TYPE
				FROM AWARD T1 
				LEFT OUTER JOIN SR_TYPE T2 ON T1.AWARD_VARIATION_TYPE_CODE = T2.TYPE_CODE
				LEFT OUTER JOIN ACCOUNT_TYPE T3 ON T1.ACCOUNT_TYPE_CODE = T3.ACCOUNT_TYPE_CODE

				WHERE T1.AWARD_ID = LI_AWARD_ID;

				SELECT IF(TRIM(FULL_NAME) = '',NULL,SUBSTR(TRIM(FULL_NAME),1,20))
				INTO LS_CUR_PI_NAME
				FROM AWARD_PERSONS
				WHERE AWARD_ID = LI_AWARD_ID
				AND PI_FLAG = 'Y';
				
				
				-- ------------------STARTS FETCHING BA_CODE----------------------------------------------------
				BEGIN
				
					GET_BA_CODE_LOOP:WHILE (LS_BA_CODE IS NULL OR LS_BA_CODE = '') DO
					
						SELECT 
							BA_CODE
						INTO
							LS_BA_CODE
						FROM SAP_FEED_UNIT_MAPPING
						WHERE UNIT_NUMBER = LS_LEAD_UNIT_NUMBER;
						
						IF (LS_BA_CODE IS NULL OR LS_BA_CODE = '') THEN
						
							SELECT PARENT_UNIT_NUMBER 
							INTO LS_LEAD_UNIT_NUMBER 
							FROM UNIT
							WHERE UNIT_NUMBER = LS_LEAD_UNIT_NUMBER; 
						
						END IF;
						
						IF LS_LEAD_UNIT_NUMBER = NULL THEN
						
							LEAVE GET_BA_CODE_LOOP;
						END IF;
					
					
					END WHILE GET_BA_CODE_LOOP;
				
				END;
								
				-- ------------------ENDS FETCHING BA_CODE------------------------------------------------------
				
				-- ------------------STARTS FETCHING CUSTOM ELEMENT 'GRANT CODE'--------------------------------
								
				SELECT COUNT(1) INTO LI_FLAG
				FROM CUSTOM_DATA T1
				WHERE  T1.MODULE_ITEM_CODE = 1 
				AND T1.MODULE_SUB_ITEM_CODE = 0 
				AND T1.MODULE_SUB_ITEM_KEY = 0
				AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
				AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
									WHERE CUSTOM_ELEMENT_NAME = 'GRANT CODE'
									AND IS_LATEST_VERSION = 'Y'
								   );

				IF LI_FLAG > 0 THEN

					SELECT IF(TRIM(VALUE) = '',NULL,TRIM(VALUE)) INTO LS_GRANT_CODE
					FROM CUSTOM_DATA T1
					WHERE  T1.MODULE_ITEM_CODE = 1
					AND T1.MODULE_SUB_ITEM_CODE = 0
					AND T1.MODULE_SUB_ITEM_KEY = 0
					AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
					AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
										WHERE CUSTOM_ELEMENT_NAME = 'GRANT CODE'
										AND IS_LATEST_VERSION = 'Y'
									   );

				END IF;
				-- ------------------ENDS FETCHING CUSTOM ELEMENT 'GRANT CODE'-----------------------------------


				-- ------------------STARTS FINDING 'FUND CODE'----------------------------------

				IF LS_AWD_ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN

					/*
						1 - External Funding (RSO)
						2 - External funding (non-RSO)
						4 - External talent award (TRACS)
						6 - RCA
					*/

					SET LS_FUND_CODE = 'R_RESFUND';

				ELSEIF LS_AWD_ACCOUNT_TYPE_CODE = '7' THEN -- Internal Funding (Co-Funding)

					SET LS_FUND_CODE = 'R_NTUCORES';

				ELSEIF LS_AWD_ACCOUNT_TYPE_CODE IN ('3','5') THEN

					/*
						3 - 'Internal funding'
						5 - 'Internal talent award (TRACS)'
					*/

					IF SUBSTR(LS_AWARD_NUMBER,INSTR(LS_AWARD_NUMBER,'-')+1) = '00001' THEN

						SET LS_FUND_CODE = 'G_DESIGNAT';

					ELSE

						SELECT CONCAT(SUBSTR(LS_AWARD_NUMBER,1,INSTR(LS_AWARD_NUMBER,'-')-1),'-00001')
						INTO LS_ROOT_AWARD_NUMBER
						FROM DUAL;

						SELECT
							CASE WHEN ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN
							'R_NTUCORES'
							ELSE
							'G_DESIGNAT'
							END
						INTO LS_FUND_CODE
						FROM AWARD
						WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
						AND AWARD_SEQUENCE_STATUS = 'ACTIVE';


					END IF;

				END IF;

				-- ------------------ENDS FINDING 'FUND CODE'------------------------------------

				-- ------------------STARTS FETCHING CUSTOM ELEMENT 'Input GST'----------------------------------

					SELECT COUNT(1) INTO LI_FLAG
					FROM CUSTOM_DATA T1
					WHERE  T1.MODULE_ITEM_CODE = 1
					AND T1.MODULE_SUB_ITEM_CODE = 0
					AND T1.MODULE_SUB_ITEM_KEY = 0
					AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
					AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
										WHERE CUSTOM_ELEMENT_NAME = 'Input GST Category'
										AND IS_LATEST_VERSION = 'Y'
									   );
					IF LI_FLAG > 0 THEN

						SELECT IF(TRIM(VALUE) = '',NULL,TRIM(VALUE)) INTO LS_INPUT_GST
						FROM CUSTOM_DATA T1
						WHERE  T1.MODULE_ITEM_CODE = 1
						AND T1.MODULE_SUB_ITEM_CODE = 0
						AND T1.MODULE_SUB_ITEM_KEY = 0
						AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
						AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
											WHERE CUSTOM_ELEMENT_NAME = 'Input GST Category'
											AND IS_LATEST_VERSION = 'Y'
										   );

					END IF;
				-- ------------------ENDS FETCHING CUSTOM ELEMENT 'Input GST'------------------------------------

				-- ------------------STARTS FETCHING CUSTOM ELEMENT 'Profit Center'------------------------------

					SELECT COUNT(1) INTO LI_FLAG
					FROM CUSTOM_DATA T1
					WHERE  T1.MODULE_ITEM_CODE = 1
					AND T1.MODULE_SUB_ITEM_CODE = 0
					AND T1.MODULE_SUB_ITEM_KEY = 0
					AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
					AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
										WHERE CUSTOM_ELEMENT_NAME = 'PROFIT CENTER'
										AND IS_LATEST_VERSION = 'Y'
									   );
					IF LI_FLAG > 0 THEN

						SELECT IF(TRIM(VALUE) = '',NULL,TRIM(VALUE)) INTO LS_PROFIT_CENTER
						FROM CUSTOM_DATA T1
						WHERE  T1.MODULE_ITEM_CODE = 1
						AND T1.MODULE_SUB_ITEM_CODE = 0
						AND T1.MODULE_SUB_ITEM_KEY = 0
						AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
						AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
											WHERE CUSTOM_ELEMENT_NAME = 'PROFIT CENTER'
											AND IS_LATEST_VERSION = 'Y'
										   );


					END IF;

					/*IF LS_PROFIT_CENTER IS NULL THEN -- FOR ONLY TESTING PURPOSE

							SET LS_PROFIT_CENTER = 'D824041000';
					END IF;
					*/





				-- ------------------ENDS FETCHING CUSTOM ELEMENT 'Profit Center'------------------------------------

				-- ------------------STARTS FETCHING CUSTOM ELEMENT 'FUND CENTER'------------------------------------

					SELECT COUNT(1) INTO LI_FLAG
					FROM CUSTOM_DATA T1
					WHERE  T1.MODULE_ITEM_CODE = 1
					AND T1.MODULE_SUB_ITEM_CODE = 0
					AND T1.MODULE_SUB_ITEM_KEY = 0
					AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
					AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
										WHERE CUSTOM_ELEMENT_NAME = 'FUND CENTER'
										AND IS_LATEST_VERSION = 'Y'
									   );
					IF LI_FLAG > 0 THEN

						SELECT IF(TRIM(VALUE) = '',NULL,TRIM(VALUE)) INTO LS_FUND_CENTER
						FROM CUSTOM_DATA T1
						WHERE  T1.MODULE_ITEM_CODE = 1
						AND T1.MODULE_SUB_ITEM_CODE = 0
						AND T1.MODULE_SUB_ITEM_KEY = 0
						AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
						AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
											WHERE CUSTOM_ELEMENT_NAME = 'FUND CENTER'
											AND IS_LATEST_VERSION = 'Y'
										   );

					END IF;

					IF LS_FUND_CENTER IS NULL THEN

						SET LS_FUND_CENTER = LS_PROFIT_CENTER;

					END IF;

				-- ------------------ENDS FETCHING CUSTOM ELEMENT 'FUND CENTER'-------------------------------------
				-- ------------------STARTS FETCHING CUSTOM ELEMENT 'COST CENTER'------------------------------------

					SELECT COUNT(1) INTO LI_FLAG
					FROM CUSTOM_DATA T1
					WHERE  T1.MODULE_ITEM_CODE = 1
					AND T1.MODULE_SUB_ITEM_CODE = 0
					AND T1.MODULE_SUB_ITEM_KEY = 0
					AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
					AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
										WHERE CUSTOM_ELEMENT_NAME = 'COST CENTER'
										AND IS_LATEST_VERSION = 'Y'
									   );
					IF LI_FLAG > 0 THEN

						SELECT IF(TRIM(VALUE) = '',NULL,TRIM(VALUE)) INTO LS_COST_CENTER
						FROM CUSTOM_DATA T1
						WHERE  T1.MODULE_ITEM_CODE = 1
						AND T1.MODULE_SUB_ITEM_CODE = 0
						AND T1.MODULE_SUB_ITEM_KEY = 0
						AND T1.MODULE_ITEM_KEY = LI_AWARD_ID
						AND T1.CUSTOM_DATA_ELEMENTS_ID = (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS
											WHERE CUSTOM_ELEMENT_NAME = 'COST CENTER'
											AND IS_LATEST_VERSION = 'Y'
										   );
					
					END IF;
					
					IF LS_COST_CENTER IS NULL THEN
						
						SET LS_COST_CENTER = LS_PROFIT_CENTER;
					
					END IF;
					
				-- ------------------ENDS FETCHING CUSTOM ELEMENT 'COST CENTER'-------------------------------------
				
				
						
			-- -----------STARTS INSERT INTO SAP_FEED_TMPL_GRANT_BUD_MASTER TABLE -----------------------
			
			 IF LS_FUND_CODE <> 'G_DESIGNAT' THEN
			 
				SET LS_ERROR_TABLE = 'SAP_FEED_TMPL_GRANT_BUD_MASTER';
				
				IF DATE(LS_AWARD_START_DATE) < DATE(NOW()) THEN -- FINDING OF POSTING_DATE
				
					SET LS_POSTING_DATE = NOW();
				ELSE
					SET LS_POSTING_DATE = LS_AWARD_START_DATE;
					
				END IF;
			
			    -- ---------------------------STARTS FINDING FISCAL YEAR--------------------			
					SELECT 
						DATE(NOW()),
						YEAR(NOW())
						INTO 
						LS_FEED_START_DATE,
						LS_FEED_START_YEAR
					FROM DUAL;
					
					IF LS_FEED_START_DATE > (CONCAT(LS_FEED_START_YEAR,'-03-31')) THEN
					
						SET LS_FISCAL_YEAR = CAST(LS_FEED_START_YEAR AS UNSIGNED);
						
					ELSE
					
						SET LS_FISCAL_YEAR = CAST((LS_FEED_START_YEAR - 1) AS UNSIGNED);
					
					END IF;
				
				-- ----------------------------ENDS FINDING FISCAL YEAR------------------------
				
				-- ---------------STARTS FINDING CURRENT VERSION TOTAL COST--------------------
				SELECT COUNT(1) INTO LI_FLAG FROM AWARD_BUDGET_HEADER T1
				WHERE T1.AWARD_ID = LI_AWARD_ID
				AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
										  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
										 )
				AND T1.AWARD_BUDGET_STATUS_CODE = 10
				AND T1.TOTAL_COST IS NOT NULL;
				
				IF LI_FLAG > 0 THEN
				
					SELECT TOTAL_COST INTO LI_CURRENT_TOTAL_COST FROM AWARD_BUDGET_HEADER T1
					WHERE T1.AWARD_ID = LI_AWARD_ID
					AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
											  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
											 )
					AND T1.AWARD_BUDGET_STATUS_CODE = 10;
					
				
				END IF;
				-- ------------------ENDS FINDING CURRENT VERSION TOTAL COST----------------------
				
				-- ------------------STARTS FINDING PREVIOUS VERSION TOTAL COST-------------------
				
				SELECT COUNT(1) INTO LI_FLAG FROM SAP_AWARD_FEED T1
				WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
				AND T1.FEED_ID IN (SELECT MAX(T2.FEED_ID) FROM SAP_AWARD_FEED T2 
									WHERE  T1.AWARD_NUMBER = T2.AWARD_NUMBER 
									AND T2.FEED_ID < LI_FEED_ID
									-- AND T2.FEED_STATUS <> 'N'
									);
														  

				
				IF LI_FLAG > 0 THEN
				
					SELECT AWARD_ID,FEED_ID,BATCH_ID INTO LI_PREV_AWARD_ID,LI_PREV_FEED_ID,LI_PREV_BATCH_ID FROM SAP_AWARD_FEED T1
					WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
					AND T1.FEED_ID IN (SELECT MAX(T2.FEED_ID) FROM SAP_AWARD_FEED T2 
									WHERE  T1.AWARD_NUMBER = T2.AWARD_NUMBER 
									AND T2.FEED_ID < LI_FEED_ID
									-- AND T2.FEED_STATUS <> 'N'
									);
															  
					SELECT COUNT(1) INTO LI_FLAG FROM AWARD_BUDGET_HEADER T1
					WHERE T1.AWARD_ID = LI_PREV_AWARD_ID
					AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
										  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
										 )
					AND T1.AWARD_BUDGET_STATUS_CODE = 10
					AND T1.TOTAL_COST IS NOT NULL;
				
					IF LI_FLAG > 0 THEN
				
						SELECT TOTAL_COST INTO  LI_PREV_TOTAL_COST FROM AWARD_BUDGET_HEADER T1
						WHERE T1.AWARD_ID = LI_PREV_AWARD_ID
						AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
												  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
												 )
						AND T1.AWARD_BUDGET_STATUS_CODE = 10;
					
				
					END IF;
					
				
				END IF;
				
				-- ------------------ENDS FINDING PREVIOUS VERSION TOTAL COST---------------------
				
                				
				BEGIN
							
					DECLARE DONE4 INT DEFAULT FALSE;
					
					DECLARE CUR_MASTER_BUD_DETAIL CURSOR FOR 
					
					SELECT SUM(T2.LINE_ITEM_COST),SUM(T2.PREVIOUS_LINE_ITEM_COST),
					IF(TRIM(T2.BUDGET_CATEGORY_CODE) = '',NULL,TRIM(T2.BUDGET_CATEGORY_CODE)),
					IF(TRIM(T2.INTERNAL_ORDER_CODE) = '',NULL,TRIM(T2.INTERNAL_ORDER_CODE)),
					T2.BUDGET_HEADER_ID,
					IF(TRIM(T4.DESCRIPTION) = '',NULL,SUBSTR(TRIM(T4.DESCRIPTION),1,30)) AS COST_ELEMENT
					FROM AWARD_BUDGET_HEADER T1
					INNER JOIN AWARD_BUDGET_DETAIL T2 ON T2.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID
					INNER JOIN COST_ELEMENT T4 ON T4.COST_ELEMENT = T2.COST_ELEMENT
					WHERE T1.AWARD_ID = LI_AWARD_ID 
					-- AND T1.IS_LATEST_VERSION = 'Y'
					AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
											  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
											 )
					AND T1.AWARD_BUDGET_STATUS_CODE = 10
					GROUP BY T2.INTERNAL_ORDER_CODE;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
					
					OPEN CUR_MASTER_BUD_DETAIL;
					
					INSERT_LOOP4: LOOP 
					FETCH CUR_MASTER_BUD_DETAIL INTO 
					LI_LINE_ITEM_COST,
					LI_PREV_LINE_ITEM_COST,
					LS_BUDGET_CATEGORY_CODE,
					LS_IO_CODE,
					LI_BUDGET_HEADER_ID,
					LS_COST_ELEMENT_DESCRIPTION;
					
					IF DONE4 THEN
						LEAVE INSERT_LOOP4;
					END IF;
					
					SELECT COUNT(1) INTO LI_FLAG 
					FROM AWARD_BUDGET_DETAIL
					WHERE BUDGET_HEADER_ID = LI_BUDGET_HEADER_ID
					AND INTERNAL_ORDER_CODE = LS_IO_CODE;
					
					IF LI_FLAG > 0 THEN
						
						SELECT IF(TRIM(TRIM(BOTH '|' FROM REPLACE(GROUP_CONCAT(SUBSTR(LINE_ITEM_DESCRIPTION,1,50),'|'),',',''))) = '',NULL,TRIM(TRIM(BOTH '|'FROM REPLACE(GROUP_CONCAT(SUBSTR(LINE_ITEM_DESCRIPTION,1,50),'|'),',','')))) INTO LS_LINE_ITEM_DESCRIPTION FROM AWARD_BUDGET_DETAIL
						WHERE BUDGET_HEADER_ID = LI_BUDGET_HEADER_ID
						AND INTERNAL_ORDER_CODE = LS_IO_CODE;
					END IF;
					
					
					SELECT COUNT(1)
					INTO LI_FLAG
					FROM SAP_FEED_BUD_CATEGORY_MAPPING
					WHERE BUDGET_CATEGORY_CODE = LS_BUDGET_CATEGORY_CODE;
					
					IF LI_FLAG > 0 THEN
					
						SELECT COMMITMENT_ITEM
						INTO LS_COMMITMENT_ITEM
						FROM SAP_FEED_BUD_CATEGORY_MAPPING
						WHERE BUDGET_CATEGORY_CODE = LS_BUDGET_CATEGORY_CODE;
					
					END IF;
					
					SET LI_BUDGET_AMOUNT = IFNULL(LI_LINE_ITEM_COST,0) - IFNULL(LI_PREV_LINE_ITEM_COST,0);
					
					
					-- -------------STARTS ROW LEVEL CHECKING-----------------------------------------
					SET LS_FEED_STATUS = NULL;
					SET LS_CREATE_STATUS = NULL;
					SET LI_WRITE_FLAG = 0;
					
					/*SELECT COUNT(1) INTO LI_FLAG
					FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
					WHERE T1.GRANT_CODE = LS_GRANT_CODE
					AND T1.FUND_CODE = LS_FUND_CODE
					AND T1.SPONSOR_PROGRAM = LS_ACCOUNT_NUMBER
					AND T1.SPONSOR_CLASS = LS_IO_CODE;
					
					IF LI_FLAG > 0 THEN
					
						SELECT FEED_STATUS,CREATE_STATUS INTO LS_FEED_STATUS,LS_CREATE_STATUS
						FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
						WHERE T1.GRANT_CODE = LS_GRANT_CODE
						AND T1.FUND_CODE = LS_FUND_CODE
						AND T1.SPONSOR_PROGRAM = LS_ACCOUNT_NUMBER
						AND T1.SPONSOR_CLASS = LS_IO_CODE
						AND T1.ID = (SELECT MAX(T2.ID) FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T2 
									 WHERE T1.GRANT_CODE = T2.GRANT_CODE
									 AND T1.FUND_CODE = T2.FUND_CODE
									 AND T1.SPONSOR_PROGRAM = T2.SPONSOR_PROGRAM
									 AND T1.SPONSOR_CLASS = T2.SPONSOR_CLASS
									 -- AND T2.BATCH_ID <> LI_BATCH_ID
									 AND T2.FEED_ID <> LI_FEED_ID
									 );
						
						IF LS_FEED_STATUS = 'E' THEN
							
							
							IF IFNULL(LI_CURRENT_TOTAL_COST,0) <> IFNULL(LI_PREV_TOTAL_COST,0) THEN -- NOT A VIREMENT
						
								SELECT COUNT(1) INTO LI_FLAG 
								FROM DUAL 
								WHERE INSTR(LI_BUDGET_AMOUNT,'-') > 0;
								
								IF LI_FLAG > 0 THEN
								
									SET LS_PROCESS = 'RETN';
								ELSE
									SET LS_PROCESS = 'SUPL';
								END IF;
								
								SET LI_BUDGET_AMOUNT = ABS(LI_BUDGET_AMOUNT);
								SET LS_CREATE_STATUS = 'C';
								
							ELSE
							
								SET LS_PROCESS = 'TRAN';
								SET LI_BUDGET_AMOUNT = LI_BUDGET_AMOUNT;
								SET LS_CREATE_STATUS = 'C';
								
								
							END IF;
							
							-- starts modification ---------------------------------
							
							SELECT 
							COUNT(1) INTO LI_FLAG
							FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
							WHERE T1.GRANT_CODE = LS_GRANT_CODE
							AND T1.FUND_CODE = LS_FUND_CODE
							AND T1.SPONSOR_PROGRAM = LS_ACCOUNT_NUMBER
							AND T1.SPONSOR_CLASS = LS_IO_CODE
							AND T1.ID = (SELECT MAX(ID) FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T2 
										 WHERE T1.GRANT_CODE = T2.GRANT_CODE
										 AND T1.FUND_CODE = T2.FUND_CODE
										 AND T1.SPONSOR_PROGRAM = T2.SPONSOR_PROGRAM
										 AND T1.SPONSOR_CLASS = T2.SPONSOR_CLASS
										 )
							-- AND IFNULL(T1.PROCESS,'0') = IFNULL(LS_PROCESS,'0')
							AND	IFNULL(T1.HEADER_DESCRIPTION,'0') = IFNULL(LS_HEADER_DESCRIPTION,'0')
							AND IFNULL(T1.BUDGET_AMOUNT,'0') = IFNULL(LI_BUDGET_AMOUNT,'0')
							AND IFNULL(DATE(T1.POSTING_DATE),'0') = IFNULL(DATE(LS_POSTING_DATE),'0')
							AND IFNULL(T1.BUDGET_VERSION,'0') = IFNULL(LS_BUDGET_VERSION,'0')
							AND IFNULL(T1.LINE_ITEM_TEXT,'0') = IFNULL(LS_LINE_ITEM_DESCRIPTION,'0')
							AND IFNULL(T1.FUNCTIONAL_AREA,'0') = IFNULL(LS_BA_CODE,'0')
							AND IFNULL(T1.COMMITMENT_ITEM,'0') = IFNULL(LS_COMMITMENT_ITEM,'0')
							AND IFNULL(T1.YEAR,'0') = IFNULL(LS_FISCAL_YEAR,'0')
							AND IFNULL(T1.GM_DOC_TYPE,'0') = IFNULL(LS_GM_DOC_TYPE,'0')
							AND IFNULL(T1.GRANT_CUR,'0') = IFNULL(LS_GRANT_CURRENCY,'0')
							AND IFNULL(T1.FUNDED_PROGRAM,'0') = IFNULL(LS_ACCOUNT_NUMBER,'0')
							AND IFNULL(T1.FUND_CENTER,'0') = IFNULL(LS_FUND_CENTER,'0')
							AND IFNULL(T1.DISTR_KEY,'0') = IFNULL(LS_DISTR_KEY,'0')
							AND IFNULL(T1.FM_AREA,'0') = IFNULL(LS_FM_AREA,'0');
							
							IF LI_FLAG = 0 THEN
							
								SET LI_WRITE_FLAG = 1;
								
							END IF;
							
							-- ends modification ------------------------------------
							
						
						ELSEIF LS_FEED_STATUS = 'S' THEN
						
							IF IFNULL(LI_CURRENT_TOTAL_COST,0) <> IFNULL(LI_PREV_TOTAL_COST,0) THEN -- NOT A VIREMENT
						
								SELECT COUNT(1) INTO LI_FLAG 
								FROM DUAL 
								WHERE INSTR(LI_BUDGET_AMOUNT,'-') > 0;
								
								IF LI_FLAG > 0 THEN
								
									SET LS_PROCESS = 'RETN';
								ELSE
									SET LS_PROCESS = 'SUPL';
								END IF;
								
								SET LI_BUDGET_AMOUNT = ABS(LI_BUDGET_AMOUNT);
								
							ELSE
							
								SET LS_PROCESS = 'TRAN';
								SET LI_BUDGET_AMOUNT = LI_BUDGET_AMOUNT;
								
							END IF;
							
							SELECT 
							COUNT(1) INTO LI_FLAG
							FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
							WHERE T1.GRANT_CODE = LS_GRANT_CODE
							AND T1.FUND_CODE = LS_FUND_CODE
							AND T1.SPONSOR_PROGRAM = LS_ACCOUNT_NUMBER
							AND T1.SPONSOR_CLASS = LS_IO_CODE
							AND T1.FEED_STATUS = 'S'
							AND T1.ID = (SELECT MAX(ID) FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T2 
										 WHERE T1.GRANT_CODE = T2.GRANT_CODE
										 AND T1.FUND_CODE = T2.FUND_CODE
										 AND T1.SPONSOR_PROGRAM = T2.SPONSOR_PROGRAM
										 AND T1.SPONSOR_CLASS = T2.SPONSOR_CLASS
										 AND T2.FEED_STATUS = 'S'
										 )
							-- AND IFNULL(T1.PROCESS,'0') = IFNULL(LS_PROCESS,'0')
							AND	IFNULL(T1.HEADER_DESCRIPTION,'0') = IFNULL(LS_HEADER_DESCRIPTION,'0')
							AND IFNULL(T1.BUDGET_AMOUNT,'0') = IFNULL(LI_BUDGET_AMOUNT,'0')
							AND IFNULL(DATE(T1.POSTING_DATE),'0') = IFNULL(DATE(LS_POSTING_DATE),'0')
							AND IFNULL(T1.BUDGET_VERSION,'0') = IFNULL(LS_BUDGET_VERSION,'0')
							AND IFNULL(T1.LINE_ITEM_TEXT,'0') = IFNULL(LS_LINE_ITEM_DESCRIPTION,'0')
							AND IFNULL(T1.FUNCTIONAL_AREA,'0') = IFNULL(LS_BA_CODE,'0')
							AND IFNULL(T1.COMMITMENT_ITEM,'0') = IFNULL(LS_COMMITMENT_ITEM,'0')
							AND IFNULL(T1.YEAR,'0') = IFNULL(LS_FISCAL_YEAR,'0')
							AND IFNULL(T1.GM_DOC_TYPE,'0') = IFNULL(LS_GM_DOC_TYPE,'0')
							AND IFNULL(T1.GRANT_CUR,'0') = IFNULL(LS_GRANT_CURRENCY,'0')
							AND IFNULL(T1.FUNDED_PROGRAM,'0') = IFNULL(LS_ACCOUNT_NUMBER,'0')
							AND IFNULL(T1.FUND_CENTER,'0') = IFNULL(LS_FUND_CENTER,'0')
							AND IFNULL(T1.DISTR_KEY,'0') = IFNULL(LS_DISTR_KEY,'0')
							AND IFNULL(T1.FM_AREA,'0') = IFNULL(LS_FM_AREA,'0');
							
			
							IF LI_FLAG = 0 THEN
							
								SET LI_WRITE_FLAG = 1;
								SET LS_CREATE_STATUS = 'C';
								
							END IF;
							
						ELSEIF LS_FEED_STATUS IS NULL THEN


							IF IFNULL(LI_CURRENT_TOTAL_COST,0) <> IFNULL(LI_PREV_TOTAL_COST,0) THEN -- NOT A VIREMENT
						
								SELECT COUNT(1) INTO LI_FLAG 
								FROM DUAL 
								WHERE INSTR(LI_BUDGET_AMOUNT,'-') > 0;
								
								IF LI_FLAG > 0 THEN
								
									SET LS_PROCESS = 'RETN';
								ELSE
									SET LS_PROCESS = 'SUPL';
								END IF;
								
								SET LI_BUDGET_AMOUNT = ABS(LI_BUDGET_AMOUNT);
								
							ELSE
							
								SET LS_PROCESS = 'TRAN';
								SET LI_BUDGET_AMOUNT = LI_BUDGET_AMOUNT;
								
							END IF;
							
							SELECT 
							COUNT(1) INTO LI_FLAG
							FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
							WHERE T1.GRANT_CODE = LS_GRANT_CODE
							AND T1.FUND_CODE = LS_FUND_CODE
							AND T1.SPONSOR_PROGRAM = LS_ACCOUNT_NUMBER
							AND T1.SPONSOR_CLASS = LS_IO_CODE
							AND T1.ID = (SELECT MAX(ID) FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T2 
										 WHERE T1.GRANT_CODE = T2.GRANT_CODE
										 AND T1.FUND_CODE = T2.FUND_CODE
										 AND T1.SPONSOR_PROGRAM = T2.SPONSOR_PROGRAM
										 AND T1.SPONSOR_CLASS = T2.SPONSOR_CLASS
										 
										 )
							-- AND IFNULL(T1.PROCESS,'0') = IFNULL(LS_PROCESS,'0')
							AND	IFNULL(T1.HEADER_DESCRIPTION,'0') = IFNULL(LS_HEADER_DESCRIPTION,'0')
							AND IFNULL(T1.BUDGET_AMOUNT,'0') = IFNULL(LI_BUDGET_AMOUNT,'0')
							AND IFNULL(DATE(T1.POSTING_DATE),'0') = IFNULL(DATE(LS_POSTING_DATE),'0')
							AND IFNULL(T1.BUDGET_VERSION,'0') = IFNULL(LS_BUDGET_VERSION,'0')
							AND IFNULL(T1.LINE_ITEM_TEXT,'0') = IFNULL(LS_LINE_ITEM_DESCRIPTION,'0')
							AND IFNULL(T1.FUNCTIONAL_AREA,'0') = IFNULL(LS_BA_CODE,'0')
							AND IFNULL(T1.COMMITMENT_ITEM,'0') = IFNULL(LS_COMMITMENT_ITEM,'0')
							AND IFNULL(T1.YEAR,'0') = IFNULL(LS_FISCAL_YEAR,'0')
							AND IFNULL(T1.GM_DOC_TYPE,'0') = IFNULL(LS_GM_DOC_TYPE,'0')
							AND IFNULL(T1.GRANT_CUR,'0') = IFNULL(LS_GRANT_CURRENCY,'0')
							AND IFNULL(T1.FUNDED_PROGRAM,'0') = IFNULL(LS_ACCOUNT_NUMBER,'0')
							AND IFNULL(T1.FUND_CENTER,'0') = IFNULL(LS_FUND_CENTER,'0')
							AND IFNULL(T1.DISTR_KEY,'0') = IFNULL(LS_DISTR_KEY,'0')
							AND IFNULL(T1.FM_AREA,'0') = IFNULL(LS_FM_AREA,'0');
							
			
							IF LI_FLAG = 0 THEN
							
								SET LI_WRITE_FLAG = 1;
								SET LS_CREATE_STATUS = 'C';
								
							END IF;

						
						END IF;
						
					ELSE*/
						
						SET LS_CREATE_STATUS = 'C';
						
						SET LI_WRITE_FLAG = 1;
						
						-- ----STARTS CHECKING WHETHER IT IS VIREMENT OR NOT ------------------------
						-- IF LI_SEQUENCE_NUMBER = 1 THEN
						
							-- -----------------------------------START NEW MODIFICATION----------------------------------
							
							
							SELECT COUNT(1) INTO LI_FLAG
							FROM AWARD_BUDGET_HEADER T1
							INNER JOIN AWARD_BUDGET_DETAIL T2 ON T2.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID
							WHERE T1.AWARD_ID = LI_PREV_AWARD_ID 
							AND T1.SEQUENCE_NUMBER = (SELECT MAX(T3.SEQUENCE_NUMBER) FROM AWARD_BUDGET_HEADER T3
													  WHERE T1.AWARD_ID = T3.AWARD_ID AND T3.AWARD_BUDGET_STATUS_CODE = 10
													 )
							AND T1.AWARD_BUDGET_STATUS_CODE = 10
							AND TRIM(T2.INTERNAL_ORDER_CODE) =  TRIM(LS_IO_CODE);
							
							IF LI_FLAG = 0 THEN
													
								-- ----------------------------------------------------------
								
									
									IF IFNULL(LI_CURRENT_TOTAL_COST,0) = IFNULL(LI_PREV_TOTAL_COST,0) THEN 
								
										SET LS_PROCESS = 'TRAN';
										
									ELSE
										
										SET LS_PROCESS = 'ENTR';
										
									END IF;
									
								
								
								-- ----------------------------------------------------------
							ELSE
							
								
									
									set LI_WRITE_FLAG = 0;
							
									IF IFNULL(LI_CURRENT_TOTAL_COST,0) <> IFNULL(LI_PREV_TOTAL_COST,0) THEN -- NOT A VIREMENT
							
										SELECT COUNT(1) INTO LI_FLAG 
										FROM DUAL 
										WHERE INSTR(LI_BUDGET_AMOUNT,'-') > 0;
										
										IF LI_FLAG > 0 THEN
										
											SET LS_PROCESS = 'RETN';
										ELSE
											SET LS_PROCESS = 'SUPL';
										END IF;
										
										SET LI_BUDGET_AMOUNT = ABS(LI_BUDGET_AMOUNT);
									
									ELSE
								
										SET LS_PROCESS = 'TRAN';
										SET LI_BUDGET_AMOUNT = LI_BUDGET_AMOUNT;
									
									END IF;
									
									
									SELECT 
									COUNT(1) INTO LI_FLAG
									FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T1
									WHERE T1.GRANT_CODE = LS_GRANT_CODE
									AND T1.FUND_CODE = LS_FUND_CODE
									AND T1.SPONSOR_PROGRAM = LS_ACCOUNT_NUMBER
									AND T1.SPONSOR_CLASS = LS_IO_CODE
									AND T1.FEED_STATUS = 'S'
									AND T1.ID = (SELECT MAX(ID) FROM SAP_FEED_TMPL_GRANT_BUD_MASTER T2 
												 WHERE T1.GRANT_CODE = T2.GRANT_CODE
												 AND T1.FUND_CODE = T2.FUND_CODE
												 AND T1.SPONSOR_PROGRAM = T2.SPONSOR_PROGRAM
												 AND T1.SPONSOR_CLASS = T2.SPONSOR_CLASS
												 AND T2.FEED_STATUS = 'S'
												 )
									-- AND IFNULL(T1.PROCESS,'0') = IFNULL(LS_PROCESS,'0')
									AND	IFNULL(T1.HEADER_DESCRIPTION,'0') = IFNULL(LS_HEADER_DESCRIPTION,'0')
									AND IFNULL(T1.BUDGET_AMOUNT,'0') = IFNULL(LI_BUDGET_AMOUNT,'0')
									AND IFNULL(DATE(T1.POSTING_DATE),'0') = IFNULL(DATE(LS_POSTING_DATE),'0')
									AND IFNULL(T1.BUDGET_VERSION,'0') = IFNULL(LS_BUDGET_VERSION,'0')
									AND IFNULL(T1.LINE_ITEM_TEXT,'0') = IFNULL(LS_LINE_ITEM_DESCRIPTION,'0')
									AND IFNULL(T1.FUNCTIONAL_AREA,'0') = IFNULL(LS_BA_CODE,'0')
									AND IFNULL(T1.COMMITMENT_ITEM,'0') = IFNULL(LS_COMMITMENT_ITEM,'0')
									AND IFNULL(T1.YEAR,'0') = IFNULL(LS_FISCAL_YEAR,'0')
									AND IFNULL(T1.GM_DOC_TYPE,'0') = IFNULL(LS_GM_DOC_TYPE,'0')
									AND IFNULL(T1.GRANT_CUR,'0') = IFNULL(LS_GRANT_CURRENCY,'0')
									AND IFNULL(T1.FUNDED_PROGRAM,'0') = IFNULL(LS_ACCOUNT_NUMBER,'0')
									AND IFNULL(T1.FUND_CENTER,'0') = IFNULL(LS_FUND_CENTER,'0')
									AND IFNULL(T1.DISTR_KEY,'0') = IFNULL(LS_DISTR_KEY,'0')
									AND IFNULL(T1.FM_AREA,'0') = IFNULL(LS_FM_AREA,'0');
									
					
									IF LI_FLAG = 0 THEN
									
										SET LI_WRITE_FLAG = 1;
										SET LS_CREATE_STATUS = 'C';
										
									END IF;
							
							END IF;
							
							-- -----------------------------------ENDS NEW MODIFICATION-----------------------------------
						
						
						/*	IF IFNULL(LI_CURRENT_TOTAL_COST,0) = IFNULL(LI_PREV_TOTAL_COST,0) THEN
							
								SET LS_PROCESS = 'TRAN';
								SET LI_BUDGET_AMOUNT = LI_BUDGET_AMOUNT;
								
							ELSE
							
								SET LS_PROCESS = 'ENTR';
							
							END IF;
						
						ELSE
						
							IF IFNULL(LI_CURRENT_TOTAL_COST,0) <> IFNULL(LI_PREV_TOTAL_COST,0) THEN -- NOT A VIREMENT
						
								SELECT COUNT(1) INTO LI_FLAG 
								FROM DUAL 
								WHERE INSTR(LI_BUDGET_AMOUNT,'-') > 0;
								
								IF LI_FLAG > 0 THEN
								
									SET LS_PROCESS = 'RETN';
								ELSE
									SET LS_PROCESS = 'SUPL';
								END IF;
								
								SET LI_BUDGET_AMOUNT = ABS(LI_BUDGET_AMOUNT);
								
							ELSE
							
								SET LS_PROCESS = 'TRAN';
								SET LI_BUDGET_AMOUNT = LI_BUDGET_AMOUNT;
								
							END IF;
						
						END IF;*/
						
						-- ------ENDS CHECKING WHETHER IT IS VIREMENT OR NOT ------------------------
					
				-- END IF;
					
					IF LI_BUDGET_AMOUNT = 0 THEN -- CHECKING IF BUDGET AMOUNT IS ZERO THEN NO NEED TO WRITE
						
						SET LI_WRITE_FLAG = 0;

					END IF;
					
					IF LI_PREV_AWARD_ID IS NOT NULL THEN 
					
						SELECT MAX(VERSION_NUMBER) INTO LI_PREV_VERSION_NUMBER FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = LI_PREV_AWARD_ID 
						AND AWARD_BUDGET_STATUS_CODE = 10;
						
						SELECT MAX(VERSION_NUMBER) INTO LI_CUR_VERSION_NUMBER FROM AWARD_BUDGET_HEADER WHERE AWARD_ID = LI_AWARD_ID
						AND AWARD_BUDGET_STATUS_CODE = 10;
						
						IF LI_PREV_VERSION_NUMBER = LI_CUR_VERSION_NUMBER THEN
						
							SET LI_WRITE_FLAG = 0;
							
						END IF;
						
					END IF;
					
					IF LS_BUDGET_CATEGORY_CODE = 'GRT' THEN

						SET LI_WRITE_FLAG = 0;

					END IF;
				
				-- -------------ENDS ROW LEVEL CHECKING-----------------------------------------
				
					IF LI_WRITE_FLAG = 1 THEN
					
						SELECT COUNT(1) INTO LI_FLAG
						FROM SAP_FEED_PROB_GRANTCODE_REPORT
						WHERE BATCH_ID = AV_BATCH_ID
						AND FEED_ID = LI_FEED_ID
						AND IO_CODE = LS_IO_CODE;
						
						IF LI_FLAG = 0 THEN
					
						INSERT INTO SAP_FEED_PROB_GRANTCODE_REPORT(
						BATCH_ID,
						FEED_ID,
						AWARD_ID,
						AWARD_NUMBER,
						ACCOUNT_NUMBER,
						SEQUENCE_NUMBER,
						BUSINESS_AREA,
						VARIATION_TYPE_CODE,
						VARIATION_TYPE,
						ACCOUNT_TYPE,
						TITLE,
						IO_CODE,
						FUND_CODE,
						PROCESS,
						BUDGET_AMOUNT,
						CUR_LINE_ITEM_COST,
						PREV_LINE_ITEM_COST,
						CUR_PI_NAME,
						COST_ELEMENT_DESCRIPTION,
						UPDATE_TIMESTAMP,
						UPDATE_USER,
						GRANT_CODE,
						PROFIT_CENTER,
						COST_CENTER,
						FUND_CENTER)
						VALUES(
						AV_BATCH_ID,
						LI_FEED_ID,
						LI_AWARD_ID,
						LS_AWARD_NUMBER,
						LS_ACCOUNT_NUMBER,
						LI_SEQUENCE_NUMBER,
						LS_BA_CODE,
						LS_VARIATION_TYPE_CODE,
						LS_VARIATION_TYPE,
						LS_ACCOUNT_TYPE,
						LS_TITLE,
						LS_IO_CODE,
						LS_FUND_CODE,
						LS_PROCESS,
						LI_BUDGET_AMOUNT,
						LI_LINE_ITEM_COST,
						LI_PREV_LINE_ITEM_COST,
						LS_CUR_PI_NAME,
						LS_COST_ELEMENT_DESCRIPTION,
						UTC_TIMESTAMP(),
						'admin',
						LS_GRANT_CODE,
						LS_PROFIT_CENTER,
						LS_COST_CENTER,
						LS_FUND_CENTER
						);
						
					END IF;
					END IF;
				
				SET LS_LINE_ITEM_DESCRIPTION = NULL;	
				SET LS_IO_CODE = NULL;
				SET LS_COMMITMENT_ITEM = NULL;
				SET LS_BUDGET_CATEGORY_CODE = NULL;
				SET LS_PROCESS = NULL;
				END LOOP;
				CLOSE CUR_MASTER_BUD_DETAIL;
			END;
				
						
			 END IF;
			
			-- -----------ENDS INSERT INTO SAP_FEED_TMPL_GRANT_BUD_MASTER TABLE-------------------------
			
							
			SET LS_ACCOUNT_NUMBER = NULL;
			SET LS_TITLE = NULL;
			SET LS_IO_CODE = NULL;
			SET LS_COST_ELEMENT = NULL;	
			SET LS_GRANT_CODE = NULL;
			SET LS_FUND_CODE = NULL;
			SET LS_LEAD_UNIT_NUMBER = NULL;
			SET LS_AWARD_START_DATE = NULL;
			SET LS_AWARD_END_DATE = NULL;
			SET LS_AWARD_PI_NAME = NULL;
			SET LS_GST_CLAIMABLE = NULL;
			SET LS_PROJECT_TYPE = NULL;
			SET LS_AWARD_TITLE = NULL;
			SET LS_AWARD_STATUS = NULL;
			SET LS_FISCAL_YEAR = NULL;
			SET LI_FEED_ID = 0;
			SET LS_FUND_CENTER = NULL;
			SET LS_COST_CENTER = NULL;
			SET LS_BA_CODE = NULL;
			SET LS_L1_WBS_SHORT_DESCRIPTION = NULL;
			SET LS_L1_WBS_PI_NAME = NULL;
			SET LS_SPONSOR_AWARD_NUMBER = NULL;
			SET LS_L2_WBS_SHORT_DESCRIPTION = NULL;
			SET LI_PREV_AWARD_ID = NULL;
			SET LI_PREV_FEED_ID = NULL;
			SET LI_PREV_BATCH_ID = NULL;
			SET LI_CURRENT_TOTAL_COST = NULL;
			SET LI_PREV_TOTAL_COST = NULL;
			SET LS_CHK_ANY_FEED = 'N';
			SET LS_CUR_LINE_ITEM = NULL;
			-- SET LI_LINE_ITEM_COUNT = 0;
			SET LI_CUR_VERSION_NUMBER = NULL;
			SET LI_PREV_VERSION_NUMBER = NULL;
			SET LI_TRAN_COUNT = 0;
			SET LS_TRAN_LINE_ITEM = NULL;
			SET LS_BILLING_ELEMENT = '';
			SET LI_TOTAL_COUNT = 0;
			SET LS_AWARD_VARIATION_TYPE_CODE = NULL;
            SET LS_AWARD_DOCUMENT_TYPE_CODE = NULL;
			SET LS_FUNDED_PROGRAM_TYPE = NULL;
			SET LS_BUDGET_CATEGORY_CODE = NULL;
			SET LS_PROFIT_CENTER = NULL;
			SET LI_GRANT_CODE_EXCLUSION_FLAG = 0;
			SET LS_VARIATION_TYPE = NULL;
			SET LS_VARIATION_TYPE_CODE = NULL;
			SET LS_CUR_PI_NAME = NULL;
			SET LS_COST_ELEMENT_DESCRIPTION = NULL;
			SET LS_ACCOUNT_TYPE = NULL;
			
			COMMIT;
		END LOOP;
		CLOSE CUR_FEED_DATA;
		END;
	END;

		SELECT 1 AS RETUN_VALUE FROM DUAL;	
END
