-- `SAP_FEED_SOFT_LAUNCH_NO_REPORT`; 

CREATE PROCEDURE `SAP_FEED_SOFT_LAUNCH_NO_REPORT`(
AV_BATCH_ID	INT
)
BEGIN
	DECLARE LI_SEQ_ERROR_LOG_ID INT;
	DECLARE LS_ERROR_MSG		VARCHAR(4000);
	DECLARE LI_FEED_ID 			INT;
	DECLARE LI_AWARD_ID			INT;
	DECLARE LS_AWARD_NUMBER		VARCHAR(12);
	DECLARE LI_SEQUENCE_NUMBER	INT;
	DECLARE LS_ACCOUNT_NUMBER	VARCHAR(100);
	DECLARE LS_IS_100_PCT_INTERNAL		VARCHAR(5);
	DECLARE LS_ACCOUNT_TYPE_CODE		VARCHAR(3);
	DECLARE LS_ACCOUNT_TYPE				VARCHAR(200);
	DECLARE LS_LEAD_UNIT_NUMBER			VARCHAR(50);
	DECLARE LS_LEAD_UNIT_NAME			VARCHAR(200);
	DECLARE LS_AWARD_TITLE				VARCHAR(1000);
	DECLARE LS_PI_PERSON_ID				VARCHAR(40);
	DECLARE LS_PI_NAME					VARCHAR(90);
	DECLARE LS_SPONSOR_CODE				VARCHAR(6);
	DECLARE LS_SPONSOR_NAME				VARCHAR(200);
	DECLARE LS_SPONSOR_AWARD_NUMBER		VARCHAR(70);
	DECLARE LS_VARIATION_TYPE_CODE		VARCHAR(3);
	DECLARE LS_VARIATION_TYPE			VARCHAR(200);
	DECLARE LS_VARIATION_SUBJECT		VARCHAR(1000);		
	DECLARE LS_SUBMISSION_DATE			DATETIME;
	DECLARE LS_FEED_STATUS				VARCHAR(1);
	DECLARE LS_SYSTEM_COMMENT			VARCHAR(500);
	DECLARE LS_BUSINESS_AREA			VARCHAR(4);
	DECLARE LS_FEED_CREATE_USER			VARCHAR(60);
	DECLARE LS_FEED_CREATE_TIMESTAMP	DATETIME;
	DECLARE LI_FLAG						INT;
	
	
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
												
			SELECT IFNULL(MAX(ERROR_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM SAP_FEED_REPORT_ERROR_LOG;
			
			INSERT INTO SAP_FEED_REPORT_ERROR_LOG(ERROR_ID,ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_ERROR_MSG,utc_timestamp(),'admin');
			COMMIT;
		END;	
		
		BEGIN
		
			DECLARE DONE1 INT DEFAULT FALSE;
			DECLARE CUR_FEED_DATA CURSOR FOR
			SELECT
				F1.FEED_ID,
				T1.AWARD_ID,
				T1.AWARD_NUMBER,
				T1.SEQUENCE_NUMBER,
				T1.ACCOUNT_NUMBER,
				IF(T1.ACCOUNT_TYPE_CODE IN ('3','5'), 'Yes' , 'No') as IS_100_PCT_INTERNAL,
				T1.ACCOUNT_TYPE_CODE,
				T6.DESCRIPTION AS ACCOUNT_TYPE,
				T1.LEAD_UNIT_NUMBER,
				T3.UNIT_NAME AS LEAD_UNIT_NAME,
				T1.TITLE as AWARD_TITLE,
				T2.PERSON_ID AS PI_PERSON_ID,
				T2.FULL_NAME AS PI_NAME,
				T1.SPONSOR_CODE,
				T5.SPONSOR_NAME,
				T1.SPONSOR_AWARD_NUMBER,
				T1.SUBMISSION_DATE,
				F1.FEED_STATUS,
				F1.SYSTEM_COMMENT,
				F1.BUSINESS_AREA,
				F1.CREATE_USER,
				F1.CREATE_TIMESTAMP
				
			
			FROM 
			SAP_AWARD_FEED F1
			INNER JOIN AWARD T1 ON F1.AWARD_ID = T1.AWARD_ID
			INNER JOIN AWARD_PERSONS T2 ON T1.AWARD_ID = T2.AWARD_ID
			INNER JOIN UNIT T3 ON T1.LEAD_UNIT_NUMBER = T3.UNIT_NUMBER
			INNER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE
			INNER JOIN ACCOUNT_TYPE T6 ON T6.ACCOUNT_TYPE_CODE = T1.ACCOUNT_TYPE_CODE
			INNER JOIN AWARD_DOCUMENT_TYPE T7 ON T7.AWARD_DOCUMENT_TYPE_CODE = T1.AWARD_DOCUMENT_TYPE_CODE
			WHERE F1.FEED_STATUS IN('F','C') 
			AND F1.BATCH_ID = AV_BATCH_ID 
			AND T2.PI_FLAG = 'Y'
			UNION
			SELECT
				F1.FEED_ID,
				T1.AWARD_ID,
				T1.AWARD_NUMBER,
				T1.SEQUENCE_NUMBER,
				T1.ACCOUNT_NUMBER,
				IF(T1.ACCOUNT_TYPE_CODE IN ('3','5'), 'Yes' , 'No') as IS_100_PCT_INTERNAL,
				T1.ACCOUNT_TYPE_CODE,
				T6.DESCRIPTION AS ACCOUNT_TYPE,
				T1.LEAD_UNIT_NUMBER,
				T3.UNIT_NAME AS LEAD_UNIT_NAME,
				T1.TITLE as AWARD_TITLE,
				T2.PERSON_ID AS PI_PERSON_ID,
				T2.FULL_NAME AS PI_NAME,
				T1.SPONSOR_CODE,
				T5.SPONSOR_NAME,
				T1.SPONSOR_AWARD_NUMBER,
				T1.SUBMISSION_DATE,
				F1.FEED_STATUS,
				F1.SYSTEM_COMMENT,
				F1.BUSINESS_AREA,
				F1.CREATE_USER,
				F1.CREATE_TIMESTAMP
				
			FROM 
			SAP_AWARD_FEED F1
			INNER JOIN AWARD T1 ON F1.AWARD_ID = T1.AWARD_ID
			INNER JOIN AWARD_PERSONS T2 ON T1.AWARD_ID = T2.AWARD_ID
			INNER JOIN UNIT T3 ON T1.LEAD_UNIT_NUMBER = T3.UNIT_NUMBER
			INNER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE
			INNER JOIN ACCOUNT_TYPE T6 ON T6.ACCOUNT_TYPE_CODE = T1.ACCOUNT_TYPE_CODE
			INNER JOIN AWARD_DOCUMENT_TYPE T7 ON T7.AWARD_DOCUMENT_TYPE_CODE = T1.AWARD_DOCUMENT_TYPE_CODE
			WHERE F1.FEED_STATUS = 'N' 
			AND F1.NO_FEED_REPORT_FLAG = 'N'
			AND T2.PI_FLAG = 'Y';
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
			OPEN CUR_FEED_DATA;
			INSERT_LOOP: LOOP 
			FETCH CUR_FEED_DATA INTO
			LI_FEED_ID,
			LI_AWARD_ID,
			LS_AWARD_NUMBER,
			LI_SEQUENCE_NUMBER,
			LS_ACCOUNT_NUMBER,
			LS_IS_100_PCT_INTERNAL,
			LS_ACCOUNT_TYPE_CODE,
			LS_ACCOUNT_TYPE,
			LS_LEAD_UNIT_NUMBER,
			LS_LEAD_UNIT_NAME,
			LS_AWARD_TITLE,
			LS_PI_PERSON_ID,
			LS_PI_NAME,
			LS_SPONSOR_CODE,
			LS_SPONSOR_NAME,
			LS_SPONSOR_AWARD_NUMBER,
			LS_SUBMISSION_DATE,
			LS_FEED_STATUS,
			LS_SYSTEM_COMMENT,
			LS_BUSINESS_AREA,
			LS_FEED_CREATE_USER,
			LS_FEED_CREATE_TIMESTAMP;
			
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
			
			SELECT COUNT(1) INTO LI_FLAG
			FROM SR_HEADER T1
			LEFT JOIN ASSOC_SR T2 ON T2.SR_HEADER_ID = T1.SR_HEADER_ID
			WHERE T1.ORIGINATING_MODULE_CODE = 1
			AND T2.MODULE_ITEM_ID IN (SELECT MAX(AWARD_ID) FROM AWARD 
									   WHERE AWARD_ID < LI_AWARD_ID 
									   AND AWARD_NUMBER = LS_AWARD_NUMBER
									   );
									   
			IF LI_FLAG > 0 THEN
			
				SELECT T1.SUBJECT,T1.TYPE_CODE,T2.DESCRIPTION 
				INTO LS_VARIATION_SUBJECT,LS_VARIATION_TYPE_CODE,LS_VARIATION_TYPE
				FROM SR_HEADER T1
				INNER JOIN SR_TYPE T2 ON T1.TYPE_CODE = T2.TYPE_CODE
				LEFT JOIN ASSOC_SR T3 ON T3.SR_HEADER_ID = T1.SR_HEADER_ID
				WHERE T1.ORIGINATING_MODULE_CODE = 1
				AND T3.MODULE_ITEM_ID IN (SELECT MAX(AWARD_ID) FROM AWARD 
										   WHERE AWARD_ID < LI_AWARD_ID 
										   AND AWARD_NUMBER = LS_AWARD_NUMBER
										   );
										   
			
			END IF;
			
			
			SELECT COUNT(1) INTO LI_FLAG
			FROM SAP_NO_FEED_SOFT_LAUNCH_REPORT
			WHERE FEED_ID = LI_FEED_ID
			AND BATCH_ID  = AV_BATCH_ID;
			
			IF LI_FLAG = 0 THEN
			
				INSERT INTO SAP_NO_FEED_SOFT_LAUNCH_REPORT(
				BATCH_ID, 
				FEED_ID, 
				AWARD_ID, 
				AWARD_NUMBER, 
				SEQUENCE_NUMBER, 
				ACCOUNT_NUMBER, 
				IS_100_PCT_INTERNAL, 
				ACCOUNT_TYPE_CODE, 
				ACCOUNT_TYPE, 
				LEAD_UNIT_NUMBER, 
				LEAD_UNIT_NAME, 
				AWARD_TITLE, 
				PI_PERSON_ID, 
				PI_NAME, 
				SPONSOR_CODE, 
				SPONSOR_NAME, 
				SPONSOR_AWARD_NUMBER, 
				VARIATION_TYPE_CODE, 
				VARIATION_TYPE, 
				VARIATION_SUBJECT, 
				SUBMISSION_DATE, 
				FEED_STATUS, 
				SYSTEM_COMMENT, 
				BUSINESS_AREA, 
				FEED_CREATE_USER, 
				FEED_CREATE_TIMESTAMP
				)
				VALUES(
				AV_BATCH_ID,
				LI_FEED_ID,
				LI_AWARD_ID,
				LS_AWARD_NUMBER,
				LI_SEQUENCE_NUMBER,
				LS_ACCOUNT_NUMBER,
				LS_IS_100_PCT_INTERNAL,
				LS_ACCOUNT_TYPE_CODE,
				LS_ACCOUNT_TYPE,
				LS_LEAD_UNIT_NUMBER,
				LS_LEAD_UNIT_NAME,
				LS_AWARD_TITLE,
				LS_PI_PERSON_ID,
				LS_PI_NAME,
				LS_SPONSOR_CODE,
				LS_SPONSOR_NAME,
				LS_SPONSOR_AWARD_NUMBER,
				LS_VARIATION_TYPE_CODE,
				LS_VARIATION_TYPE,
				LS_VARIATION_SUBJECT,
				LS_SUBMISSION_DATE,
				LS_FEED_STATUS,
				LS_SYSTEM_COMMENT,
				LS_BUSINESS_AREA,
				LS_FEED_CREATE_USER,
				LS_FEED_CREATE_TIMESTAMP
				);
			
			END IF;
			
			 UPDATE SAP_AWARD_FEED SET NO_FEED_REPORT_FLAG = 'Y'
			 WHERE FEED_ID = LI_FEED_ID
			 AND NO_FEED_REPORT_FLAG = 'N';
			
			
			SET LS_VARIATION_SUBJECT = NULL;
			SET LS_VARIATION_TYPE_CODE = NULL;
			SET LS_VARIATION_TYPE = NULL;
			END LOOP;
			CLOSE CUR_FEED_DATA;
		
		END;
			
	
END
