-- `SAP_FEED_REPORT`; 

CREATE PROCEDURE `SAP_FEED_REPORT`(
AV_BATCH_ID	INT
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_ERROR_MSG		VARCHAR(4000);
DECLARE LI_FEED_ID 			INT;
DECLARE LI_AWARD_ID			INT;
DECLARE LS_AWARD_NUMBER		VARCHAR(12);
DECLARE LI_SEQUENCE_NUMBER	INT;
DECLARE LI_REPORT_ID		INT;
DECLARE LS_VARIATION_TYPE	VARCHAR(200);
DECLARE LS_ACCOUNT_NUMBER	VARCHAR(100);
DECLARE LS_AWARD_TITLE		VARCHAR(1000);
DECLARE LS_ACCOUNT_TYPE		VARCHAR(200);
DECLARE LI_FLAG				INT;
DECLARE LS_CUR_START_DATE	DATETIME;
DECLARE LS_CUR_END_DATE		DATETIME;
DECLARE LI_PREV_AWARD_ID	INT;
DECLARE LS_PREV_START_DATE 	DATETIME;
DECLARE LS_PREV_END_DATE	DATETIME;
DECLARE LS_IO_CODE			VARCHAR(50);
DECLARE LS_COST_ELEMENT_DESCRIPTION	VARCHAR(200);
DECLARE LS_FUND_CODE		VARCHAR(4000);
DECLARE LS_GM_FUND_CODE		VARCHAR(4000);
DECLARE LS_AWD_ACCOUNT_TYPE_CODE	VARCHAR(3);
DECLARE LS_ROOT_AWARD_NUMBER	VARCHAR(12);
DECLARE LS_FUNDED_PROGRAM		VARCHAR(100);
DECLARE LS_PROGRAM_DESCRIPTION	VARCHAR(200);
DECLARE LS_PROCESS				VARCHAR(4);
DECLARE LI_BUDGET_AMOUNT		DECIMAL(15,2);
DECLARE LI_CUR_LINE_ITEM_COST	DECIMAL(15,2);
DECLARE LI_PREV_LINE_ITEM_COST	DECIMAL(15,2);
DECLARE LS_PROJECT_DEFINITION	VARCHAR(80);
DECLARE LS_SHORT_DESCRIPTION	VARCHAR(40);
DECLARE LS_WBS_ELEMENT			VARCHAR(50);
DECLARE LI_WBS_LEVEL			INT;
DECLARE LS_WBS_SHORT_DESCRIPTION	VARCHAR(40);
DECLARE LS_PRNCP_INVESTGTR			VARCHAR(40);
DECLARE LS_L1_WBS_DESCRIPTION		VARCHAR(40);
DECLARE LS_L2_WBS_DESCRIPTION		VARCHAR(40);
DECLARE LS_PREV_PI_NAME				VARCHAR(40);
DECLARE LS_TITLE					VARCHAR(300);
DECLARE LS_VARIATION_TYPE_CODE		VARCHAR(3);
DECLARE LS_BA_CODE					VARCHAR(4);
DECLARE LS_LEAD_UNIT_NUMBER			VARCHAR(50);
DECLARE LS_FEED_TYPE				VARCHAR(1);
DECLARE MASTER_AWARD_ID				INT;
DECLARE LI_PREV_FEED_ID			INT;
DECLARE LS_PROFIT_CENTER		VARCHAR(255);
DECLARE LS_GRANT_CODE		    VARCHAR(255);
DECLARE LI_COUNT INT;

	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
		
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			 
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			
			SELECT @full_error INTO LS_ERROR_MSG;
												
			SELECT IFNULL(MAX(ERROR_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM SAP_FEED_REPORT_ERROR_LOG;
			
			INSERT INTO SAP_FEED_REPORT_ERROR_LOG(ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(CONCAT(LS_ERROR_MSG,LI_FEED_ID),utc_timestamp(),'admin');
			COMMIT;
			
			
		END;
		
		BEGIN
		
			DECLARE DONE1 INT DEFAULT FALSE;

			DECLARE CUR_FEED_DATA CURSOR FOR
			SELECT FEED_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,FEED_TYPE FROM SAP_AWARD_FEED 
			WHERE BATCH_ID = AV_BATCH_ID AND FEED_STATUS NOT IN ('N','C')  ORDER BY FEED_ID;
			
			DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

			OPEN CUR_FEED_DATA;
			INSERT_LOOP: LOOP 
			FETCH CUR_FEED_DATA INTO
			LI_FEED_ID,
			LI_AWARD_ID,
			LS_AWARD_NUMBER,
			LI_SEQUENCE_NUMBER,
			LS_FEED_TYPE;
			
			IF DONE1 THEN
				LEAVE INSERT_LOOP;
			END IF;
			set sql_safe_updates = 0;
			
			SELECT GRANT_CODE,PROFIT_CENTER INTO  LS_GRANT_CODE,LS_PROFIT_CENTER
            FROM custom_data_v
			WHERE MODULE_ITEM_KEY = LI_AWARD_ID; 
            
			SELECT AWARD_ID INTO MASTER_AWARD_ID FROM AWARD WHERE AWARD_NUMBER IN
			(SELECT AWARD_NUMBER FROM AWARD WHERE AWARD_ID = LI_AWARD_ID) AND AWARD_SEQUENCE_STATUS ='ACTIVE';
			
			SELECT T1.ACCOUNT_NUMBER,T2.DESCRIPTION,T3.DESCRIPTION, 
			T1.ACCOUNT_TYPE_CODE,T1.TITLE,T1.BEGIN_DATE,
			T1.FINAL_EXPIRATION_DATE,T1.AWARD_VARIATION_TYPE_CODE
			INTO LS_ACCOUNT_NUMBER,LS_VARIATION_TYPE,LS_ACCOUNT_TYPE,LS_AWD_ACCOUNT_TYPE_CODE,LS_TITLE,
			LS_CUR_START_DATE,
			LS_CUR_END_DATE,LS_VARIATION_TYPE_CODE
			FROM AWARD T1
			LEFT OUTER JOIN SR_TYPE T2 ON T1.AWARD_VARIATION_TYPE_CODE = T2.TYPE_CODE
			LEFT OUTER JOIN ACCOUNT_TYPE T3 ON T1.ACCOUNT_TYPE_CODE = T3.ACCOUNT_TYPE_CODE
			WHERE AWARD_ID = MASTER_AWARD_ID;
			
			
			SELECT IF(TRIM(FULL_NAME) = '',NULL,SUBSTR(TRIM(FULL_NAME),1,20))
			INTO LS_PRNCP_INVESTGTR
			FROM AWARD_PERSONS
			WHERE AWARD_ID = MASTER_AWARD_ID
			AND PI_FLAG = 'Y';
			
			SELECT IF(TRIM(LEAD_UNIT_NUMBER) = '',NULL,TRIM(LEAD_UNIT_NUMBER))
			INTO LS_LEAD_UNIT_NUMBER
			FROM AWARD
			WHERE AWARD_ID = MASTER_AWARD_ID;
			
			
			
			-- ------------------STARTS FETCHING BA_CODE----------------------------------------------------
				BEGIN
				
					GET_BA_CODE_LOOP:WHILE (LS_BA_CODE IS NULL OR LS_BA_CODE = '') DO
					
						SELECT 
							BA_CODE
						INTO
							LS_BA_CODE
						FROM SAP_FEED_UNIT_MAPPING
						WHERE UNIT_NUMBER = LS_LEAD_UNIT_NUMBER;
						
						IF (LS_BA_CODE IS NULL OR LS_BA_CODE = '') THEN
						
							SELECT PARENT_UNIT_NUMBER 
							INTO LS_LEAD_UNIT_NUMBER 
							FROM UNIT
							WHERE UNIT_NUMBER = LS_LEAD_UNIT_NUMBER; 
						
						END IF;
						
						IF LS_LEAD_UNIT_NUMBER = NULL THEN
						
							LEAVE GET_BA_CODE_LOOP;
						END IF;
					
					
					END WHILE GET_BA_CODE_LOOP;
				
				END;
								
				-- ------------------ENDS FETCHING BA_CODE------------------------------------------------------
		
			-- ------------------STARTS FINDING 'FUND CODE'----------------------------------
				
				IF LS_AWD_ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN 

					/*
						1 - External Funding (RSO)
						2 - External funding (non-RSO)
						4 - External talent award (TRACS)
						6 - RCA			
					*/
				
					SET LS_FUND_CODE = 'R_RESFUND';
					
				ELSEIF LS_AWD_ACCOUNT_TYPE_CODE = '7' THEN -- Internal Funding (Co-Funding)
				
					SET LS_FUND_CODE = 'R_NTUCORES';
					
				ELSEIF LS_AWD_ACCOUNT_TYPE_CODE IN ('3','5') THEN 
				
					/*
						3 - 'Internal funding'
						5 - 'Internal talent award (TRACS)'
					*/
					
					IF SUBSTR(LS_AWARD_NUMBER,INSTR(LS_AWARD_NUMBER,'-')+1) = '00001' THEN
					
						SET LS_FUND_CODE = 'G_DESIGNAT';
						
					ELSE
						
						SELECT CONCAT(SUBSTR(LS_AWARD_NUMBER,1,INSTR(LS_AWARD_NUMBER,'-')-1),'-00001') 
						INTO LS_ROOT_AWARD_NUMBER
						FROM DUAL;
						
						SELECT COUNT(1) INTO LI_FLAG
						FROM AWARD
						WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
						AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
						
						IF LI_FLAG > 0 THEN
						
							SELECT 
								CASE WHEN ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN 
								'R_NTUCORES'  
								ELSE
								'G_DESIGNAT'
								END
							INTO LS_FUND_CODE
							FROM AWARD
							WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
							AND AWARD_SEQUENCE_STATUS = 'ACTIVE';
							
						ELSE
						
							SELECT 
								CASE WHEN ACCOUNT_TYPE_CODE IN ('1','2','4','6') THEN 
								'R_NTUCORES'  
								ELSE
								'G_DESIGNAT'
								END
							INTO LS_FUND_CODE
							FROM AWARD
							WHERE AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
							AND AWARD_SEQUENCE_STATUS = 'PENDING'
							AND SEQUENCE_NUMBER IN(SELECT MAX(SEQUENCE_NUMBER) FROM AWARD
													WHERE  AWARD_NUMBER = LS_ROOT_AWARD_NUMBER
													AND AWARD_SEQUENCE_STATUS = 'PENDING' 
												  );
						
						END IF;
						
					
					END IF;
					
				END IF;
								
				-- ------------------ENDS FINDING 'FUND CODE'------------------------------------

				
				SELECT COUNT(1) INTO LI_FLAG FROM SAP_FEED_TMPL_SPONSOR_PRGM
				WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
				
				IF LI_FLAG > 0 THEN
				
					SELECT PROGRAM_DESCRIPTION INTO LS_AWARD_TITLE FROM SAP_FEED_TMPL_SPONSOR_PRGM
					WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
					
				END IF;

				SELECT COUNT(1) INTO LI_FLAG FROM SAP_FEED_TMPL_PROJECT_DEF
				WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
				
				IF LI_FLAG > 0 THEN
				
					SELECT 
						SHORT_DESCRIPTION -- ,
						-- START_DATE,
						-- FINISH_DATE 
					INTO
						LS_AWARD_TITLE -- ,
						-- LS_CUR_START_DATE,
						-- LS_CUR_END_DATE
					FROM SAP_FEED_TMPL_PROJECT_DEF
					WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
				
				END IF;
				-- -----------STARTS FINDING PREVIOUS AWARD START DATE AND END DATE ------------------
				
				SELECT COUNT(1) INTO LI_FLAG FROM SAP_AWARD_FEED T1
				WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
				AND T1.BATCH_ID IN (SELECT MAX(T2.BATCH_ID) FROM SAP_AWARD_FEED T2 INNER JOIN SAP_FEED_TMPL_PROJECT_DEF T3
									ON T3.FEED_ID = T2.FEED_ID  
								WHERE T1.AWARD_NUMBER = T2.AWARD_NUMBER
									AND T2.BATCH_ID < AV_BATCH_ID
									) AND T1.FEED_STATUS <> 'C';
								
				IF LI_FLAG > 0 THEN
								
					SELECT T1.FEED_ID INTO LI_PREV_FEED_ID FROM SAP_AWARD_FEED T1
					WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
					AND T1.BATCH_ID IN (SELECT MAX(T2.BATCH_ID) FROM SAP_AWARD_FEED T2 INNER JOIN SAP_FEED_TMPL_PROJECT_DEF T3
									ON T3.FEED_ID = T2.FEED_ID  
								WHERE T1.AWARD_NUMBER = T2.AWARD_NUMBER
									AND T2.BATCH_ID < AV_BATCH_ID
									) AND T1.FEED_STATUS <> 'C' ;
									 
									
					SELECT 
						START_DATE,
						FINISH_DATE 
					INTO 
						LS_PREV_START_DATE,
						LS_PREV_END_DATE
					FROM SAP_FEED_TMPL_PROJECT_DEF
					WHERE FEED_ID = LI_PREV_FEED_ID;
								
				END IF;
								
				-- -----------ENDS FINDING PREVIOUS AWARD START DATE AND END DATE ---------------------
				-- -----------STARTS FINDING PREVIOUS AWARD PI ------------------
				
				SELECT COUNT(1) INTO LI_FLAG FROM SAP_AWARD_FEED T1
				WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
				AND T1.BATCH_ID IN (SELECT MAX(T2.BATCH_ID) FROM SAP_AWARD_FEED T2 INNER JOIN SAP_FEED_TMPL_WBS T3
									ON T3.FEED_ID = T2.FEED_ID  
								WHERE T1.AWARD_NUMBER = T2.AWARD_NUMBER
									AND T2.BATCH_ID < AV_BATCH_ID
									) AND T1.FEED_STATUS <> 'C';
								
				IF LI_FLAG > 0 THEN
								
					SELECT T1.FEED_ID INTO LI_PREV_FEED_ID FROM SAP_AWARD_FEED T1
					WHERE T1.AWARD_NUMBER = LS_AWARD_NUMBER 
					AND T1.BATCH_ID IN (SELECT MAX(T2.BATCH_ID) FROM SAP_AWARD_FEED T2 INNER JOIN SAP_FEED_TMPL_WBS T3
									ON T3.FEED_ID = T2.FEED_ID  
								WHERE T1.AWARD_NUMBER = T2.AWARD_NUMBER
									AND T2.BATCH_ID < AV_BATCH_ID
									) AND T1.FEED_STATUS <> 'C' ;
									 
					
					SELECT PRNCP_INVESTGTR
					INTO LS_PREV_PI_NAME
					FROM SAP_FEED_TMPL_WBS
					WHERE ID IN (SELECT MAX(ID)
					FROM SAP_FEED_TMPL_WBS
					WHERE FEED_ID = LI_PREV_FEED_ID);
					
								
				END IF;
								
				-- -----------ENDS FINDING PREVIOUS AWARD PI ---------------------
				-- ------------------------STARTS SPONSOR CLASS REPORT ----------------------------------
				BEGIN
				
					DECLARE DONE2 INT DEFAULT FALSE;
					
					DECLARE CUR_SPONSOR_CLASS CURSOR FOR 
					SELECT SPONSOR_CLASS,CLASS_DESCRIPTION FROM SAP_FEED_TMPL_SPONSOR_CLASS
					WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
					
					OPEN CUR_SPONSOR_CLASS;
					
					INSERT_LOOP2: LOOP 
					FETCH CUR_SPONSOR_CLASS INTO 
					LS_IO_CODE,
					LS_COST_ELEMENT_DESCRIPTION;
					
					IF DONE2 THEN
						LEAVE INSERT_LOOP2;
					END IF;
					
					
						SELECT IFNULL(MAX(ID),0)+1 INTO LI_REPORT_ID FROM SAP_FEED_REPORT;
						INSERT INTO SAP_FEED_REPORT
						(
							ID, 
							BATCH_ID,
							FEED_ID,
							AWARD_ID, 
							AWARD_NUMBER, 
							ACCOUNT_NUMBER,
							SEQUENCE_NUMBER,
							VARIATION_TYPE,
							ACCOUNT_TYPE,
							TITLE,
							CUR_START_DATE,
							PREV_START_DATE,
							CUR_END_DATE,
							PREV_END_DATE,
							IO_CODE,
							COST_ELEMENT_DESCRIPTION,
							CUR_PI_NAME,
							PREV_PI_NAME,
							UPDATE_TIMESTAMP,
							UPDATE_USER,
							VARIATION_TYPE_CODE,
							BUSINESS_AREA,
							FUND_CODE,
							GRANT_CODE,
							PROFIT_CENTER
						)
						VALUES
						(
							LI_REPORT_ID,
							AV_BATCH_ID,
							LI_FEED_ID,
							LI_AWARD_ID,
							LS_AWARD_NUMBER,
							LS_ACCOUNT_NUMBER,
							LI_SEQUENCE_NUMBER,
							-- LS_VARIATION_TYPE,
							CASE WHEN LS_FEED_TYPE = 'N' THEN 'New'
							  ELSE 
								'Change'
							  END,
							LS_ACCOUNT_TYPE,
							LS_TITLE,
							LS_CUR_START_DATE,
							LS_PREV_START_DATE,
							LS_CUR_END_DATE,
							LS_PREV_END_DATE,
							LS_IO_CODE,
							LS_COST_ELEMENT_DESCRIPTION,
							LS_PRNCP_INVESTGTR,
							LS_PREV_PI_NAME,
							utc_timestamp(),
							'admin',
							LS_VARIATION_TYPE_CODE,
							LS_BA_CODE,
							LS_FUND_CODE,
							LS_GRANT_CODE,
							LS_PROFIT_CENTER
						);
						COMMIT;
			
					
					
					END LOOP;
					CLOSE CUR_SPONSOR_CLASS;
				
				END;
			-- -----------------------------------ENDS SPONSOR_CLASS REPORT-----------------------------
			-- ------------------------STARTS SAP_FEED_TMPL_GRANT_MASTER REPORT ----------------------------------
				BEGIN
				
					DECLARE DONE3 INT DEFAULT FALSE;
					
					DECLARE CUR_GM_MASTER CURSOR FOR 
					SELECT SPONSOR_CLASS,FUND_CODE FROM SAP_FEED_TMPL_GRANT_MASTER
					WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE3 = TRUE;
					
					OPEN CUR_GM_MASTER;
					
					INSERT_LOOP3: LOOP 
					FETCH CUR_GM_MASTER INTO 
					LS_IO_CODE,
					LS_GM_FUND_CODE;
					
					IF DONE3 THEN
						LEAVE INSERT_LOOP3;
					END IF;
					
						SELECT COUNT(1) INTO LI_FLAG
						FROM SAP_FEED_REPORT 
						WHERE FEED_ID = LI_FEED_ID
						AND IO_CODE = LS_IO_CODE AND BATCH_ID = AV_BATCH_ID;
					
						IF LI_FLAG = 0 THEN
						
							SELECT IFNULL(MAX(ID),0)+1 INTO LI_REPORT_ID FROM SAP_FEED_REPORT;
							INSERT INTO SAP_FEED_REPORT
							(
								ID, 
								BATCH_ID,
								FEED_ID,
								AWARD_ID, 
								AWARD_NUMBER, 
								ACCOUNT_NUMBER,
								SEQUENCE_NUMBER,
								VARIATION_TYPE,
								ACCOUNT_TYPE,
								TITLE,
								CUR_START_DATE,
								PREV_START_DATE,
								CUR_END_DATE,
								PREV_END_DATE,
								IO_CODE,
								FUND_CODE,
								CUR_PI_NAME,
								PREV_PI_NAME,
								UPDATE_TIMESTAMP,
								UPDATE_USER,
								VARIATION_TYPE_CODE,
								BUSINESS_AREA,
								GRANT_CODE,
								PROFIT_CENTER
							)
							VALUES
							(
								LI_REPORT_ID,
								AV_BATCH_ID,
								LI_FEED_ID,
								LI_AWARD_ID,
								LS_AWARD_NUMBER,
								LS_ACCOUNT_NUMBER,
								LI_SEQUENCE_NUMBER,
								-- LS_VARIATION_TYPE,
								CASE WHEN LS_FEED_TYPE = 'N' THEN 'New'
							  ELSE 
								'Change'
							  END,
								LS_ACCOUNT_TYPE,
								LS_TITLE,
								LS_CUR_START_DATE,
								LS_PREV_START_DATE,
								LS_CUR_END_DATE,
								LS_PREV_END_DATE,
								LS_IO_CODE,
								LS_GM_FUND_CODE,
								LS_PRNCP_INVESTGTR,
								LS_PREV_PI_NAME,
								utc_timestamp(),
								'admin',
								LS_VARIATION_TYPE_CODE,
								LS_BA_CODE,
								LS_GRANT_CODE,
								LS_PROFIT_CENTER
							);
						
						ELSE
						
							UPDATE SAP_FEED_REPORT SET FUND_CODE = LS_GM_FUND_CODE,UPDATE_TIMESTAMP = utc_timestamp()
							WHERE FEED_ID = LI_FEED_ID
							AND IO_CODE = LS_IO_CODE AND BATCH_ID = AV_BATCH_ID;
							
						END IF;
						COMMIT;
			
					
					
					END LOOP;
					CLOSE CUR_GM_MASTER;
				
				END;
			-- -----------------------------------ENDS SAP_FEED_TMPL_GRANT_MASTER REPORT-----------------------------
			
			-- ------------------------STARTS SAP_FEED_TMPL_FUNDED_PRGM REPORT ----------------------------------
				BEGIN
				
					DECLARE DONE4 INT DEFAULT FALSE;
					
					DECLARE CUR_FUND_PGM CURSOR FOR 
					SELECT FUNDED_PROGRAM,PROGRAM_DESCRIPTION FROM SAP_FEED_TMPL_FUNDED_PRGM
					WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE4 = TRUE;
					
					OPEN CUR_FUND_PGM;
					
					INSERT_LOOP4: LOOP 
					FETCH CUR_FUND_PGM INTO 
					LS_FUNDED_PROGRAM,
					LS_PROGRAM_DESCRIPTION;
					
					IF DONE4 THEN
						LEAVE INSERT_LOOP4;
					END IF;
					
						IF LS_FUND_CODE <> 'G_DESIGNAT' THEN
						
							SELECT COUNT(1) INTO LI_FLAG
							FROM SAP_FEED_REPORT 
							WHERE FEED_ID = LI_FEED_ID
							AND ACCOUNT_NUMBER = LS_FUNDED_PROGRAM 
							AND BATCH_ID = AV_BATCH_ID;
							
						ELSE
						
							SELECT COUNT(1) INTO LI_FLAG
							FROM SAP_FEED_REPORT 
							WHERE FEED_ID = LI_FEED_ID
							AND IO_CODE = LS_FUNDED_PROGRAM
							AND BATCH_ID = AV_BATCH_ID;
							
						END IF;
					
						IF LI_FLAG = 0 THEN
						
							SELECT IFNULL(MAX(ID),0)+1 INTO LI_REPORT_ID FROM SAP_FEED_REPORT;
							INSERT INTO SAP_FEED_REPORT
							(
								ID, 
								BATCH_ID,
								FEED_ID,
								AWARD_ID, 
								AWARD_NUMBER, 
								ACCOUNT_NUMBER,
								SEQUENCE_NUMBER,
								VARIATION_TYPE,
								ACCOUNT_TYPE,
								TITLE,
								CUR_START_DATE,
								PREV_START_DATE,
								CUR_END_DATE,
								PREV_END_DATE,
								IO_CODE,
								COST_ELEMENT_DESCRIPTION,
								FUND_CODE,
								CUR_PI_NAME,
								PREV_PI_NAME,
								UPDATE_TIMESTAMP,
								UPDATE_USER,
								VARIATION_TYPE_CODE,
								BUSINESS_AREA,
								GRANT_CODE,
								PROFIT_CENTER
							)
							VALUES
							(
								LI_REPORT_ID,
								AV_BATCH_ID,
								LI_FEED_ID,
								LI_AWARD_ID,
								LS_AWARD_NUMBER,
								LS_ACCOUNT_NUMBER,
								LI_SEQUENCE_NUMBER,
								-- LS_VARIATION_TYPE,
								CASE WHEN LS_FEED_TYPE = 'N' THEN 'New'
							  ELSE 
								'Change'
							  END,
								LS_ACCOUNT_TYPE,
								LS_TITLE,
								LS_CUR_START_DATE,
								LS_PREV_START_DATE,
								LS_CUR_END_DATE,
								LS_PREV_END_DATE,
								CASE WHEN LS_FUND_CODE = 'G_DESIGNAT' THEN LS_FUNDED_PROGRAM ELSE NULL END,
								CASE WHEN LS_FUND_CODE = 'G_DESIGNAT' THEN LS_PROGRAM_DESCRIPTION ELSE NULL END,
								LS_FUND_CODE,
								LS_PRNCP_INVESTGTR,
								LS_PREV_PI_NAME,
								utc_timestamp(),
								'admin',
								LS_VARIATION_TYPE_CODE,
								LS_BA_CODE,
								LS_GRANT_CODE,
								LS_PROFIT_CENTER
							);
						
						ELSE
						
							IF LS_FUND_CODE <> 'G_DESIGNAT' THEN -- ACCOUNT NUMBER
							
								UPDATE SAP_FEED_REPORT SET TITLE = LS_PROGRAM_DESCRIPTION,FUND_CODE=LS_FUND_CODE
								WHERE FEED_ID = LI_FEED_ID
								AND ACCOUNT_NUMBER = LS_FUNDED_PROGRAM
								AND BATCH_ID = AV_BATCH_ID;
								
							ELSE
							
								UPDATE SAP_FEED_REPORT SET COST_ELEMENT_DESCRIPTION = LS_PROGRAM_DESCRIPTION,FUND_CODE=LS_FUND_CODE
								WHERE FEED_ID = LI_FEED_ID
								AND IO_CODE = LS_FUNDED_PROGRAM
								AND BATCH_ID = AV_BATCH_ID;
								
							END IF;
							
						END IF;
						COMMIT;
			
					
					
					END LOOP;
					CLOSE CUR_FUND_PGM;
				
				END;
			-- -----------------------------------ENDS SAP_FEED_TMPL_FUNDED_PRGM REPORT-----------------------------
				
			-- -----------------------------------STARTS SAP_FEED_TMPL_PROJECT_DEF----------------------------------
			
			SELECT COUNT(1) INTO LI_FLAG FROM SAP_FEED_TMPL_PROJECT_DEF
			WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
			
			IF LI_FLAG > 0 THEN
			
				SELECT PROJECT_DEFINITION,SHORT_DESCRIPTION -- ,START_DATE,FINISH_DATE
				INTO LS_PROJECT_DEFINITION,LS_SHORT_DESCRIPTION -- ,LS_CUR_START_DATE,LS_CUR_END_DATE
				FROM SAP_FEED_TMPL_PROJECT_DEF
				WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
				
				SELECT COUNT(1) INTO LI_FLAG
				FROM SAP_FEED_REPORT
				WHERE ACCOUNT_NUMBER = LS_PROJECT_DEFINITION AND BATCH_ID = AV_BATCH_ID;
				
				IF LI_FLAG = 0 THEN
				
					SELECT IFNULL(MAX(ID),0)+1 INTO LI_REPORT_ID FROM SAP_FEED_REPORT;
						INSERT INTO SAP_FEED_REPORT
						(
							ID, 
							BATCH_ID,
							FEED_ID,
							AWARD_ID, 
							AWARD_NUMBER, 
							ACCOUNT_NUMBER,
							SEQUENCE_NUMBER,
							VARIATION_TYPE,
							ACCOUNT_TYPE,
							TITLE,
							CUR_START_DATE,
							PREV_START_DATE,
							CUR_END_DATE,
							PREV_END_DATE,
							CUR_PI_NAME,
							PREV_PI_NAME,
							UPDATE_TIMESTAMP,
							UPDATE_USER,
							VARIATION_TYPE_CODE,
							BUSINESS_AREA,
							FUND_CODE,
							GRANT_CODE,
							PROFIT_CENTER
						)
						VALUES
						(
							LI_REPORT_ID,
							AV_BATCH_ID,
							LI_FEED_ID,
							LI_AWARD_ID,
							LS_AWARD_NUMBER,
							LS_ACCOUNT_NUMBER,
							LI_SEQUENCE_NUMBER,
							-- LS_VARIATION_TYPE,
							CASE WHEN LS_FEED_TYPE = 'N' THEN 'New'
							  ELSE 
								'Change'
							  END,
							LS_ACCOUNT_TYPE,
							LS_TITLE,
							LS_CUR_START_DATE,
							LS_PREV_START_DATE,
							LS_CUR_END_DATE,
							LS_PREV_END_DATE,
							LS_PRNCP_INVESTGTR,
							LS_PREV_PI_NAME,
							utc_timestamp(),
							'admin',
							LS_VARIATION_TYPE_CODE,
							LS_BA_CODE,
							LS_FUND_CODE,
							LS_GRANT_CODE,
							LS_PROFIT_CENTER
						);
					
				/*ELSE
					
						UPDATE SAP_FEED_REPORT SET TITLE = LS_TITLE,-- LS_SHORT_DESCRIPTION,
						CUR_START_DATE = LS_CUR_START_DATE,CUR_END_DATE = LS_CUR_END_DATE
						WHERE ACCOUNT_NUMBER = LS_PROJECT_DEFINITION;
						*/
					
				END IF;
				
			
			END IF;
			
			-- ------------------------------------ENDS SAP_FEED_TMPL_PROJECT_DEF-----------------------------------
			
			-- ------------------------STARTS SAP_FEED_TMPL_WBS REPORT ----------------------------------
				BEGIN
				
					DECLARE DONE7 INT DEFAULT FALSE;
					
					DECLARE CUR_WBS CURSOR FOR 
					SELECT WBS_ELEMENT,WBS_LEVEL,SHORT_DESCRIPTION,
					FUND -- ,PRNCP_INVESTGTR,BASIC_START_DATE,BASIC_FINISH_DATE
					FROM SAP_FEED_TMPL_WBS
					WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
					
					DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE7 = TRUE;
					
					OPEN CUR_WBS;
					
					INSERT_LOOP7: LOOP 
					FETCH CUR_WBS INTO 
					LS_WBS_ELEMENT,
					LI_WBS_LEVEL,
					LS_WBS_SHORT_DESCRIPTION,
					LS_FUND_CODE; -- ,
					-- LS_PRNCP_INVESTGTR,
					-- LS_CUR_START_DATE,
					-- LS_CUR_END_DATE;
					
					IF DONE7 THEN
						LEAVE INSERT_LOOP7;
					END IF;
					
						IF LI_WBS_LEVEL = 1 THEN -- ACCOUNT NUMBER 
						
							SELECT COUNT(1) INTO LI_FLAG 
							FROM SAP_FEED_REPORT
							WHERE FEED_ID = LI_FEED_ID
							AND ACCOUNT_NUMBER = LS_WBS_ELEMENT AND BATCH_ID = AV_BATCH_ID;
							
							SET LS_L1_WBS_DESCRIPTION = LS_WBS_SHORT_DESCRIPTION;
							
						ELSEIF LI_WBS_LEVEL = 2 THEN -- IO_CODE
						
							SELECT COUNT(1) INTO LI_FLAG 
							FROM SAP_FEED_REPORT
							WHERE FEED_ID = LI_FEED_ID
							AND IO_CODE = LS_WBS_ELEMENT AND BATCH_ID = AV_BATCH_ID;
							
							SET LS_L2_WBS_DESCRIPTION = LS_WBS_SHORT_DESCRIPTION;

						
						END IF;
						
						IF LI_FLAG = 0 THEN
						
							SELECT IFNULL(MAX(ID),0)+1 INTO LI_REPORT_ID FROM SAP_FEED_REPORT;
							INSERT INTO SAP_FEED_REPORT
							(
								ID, 
								BATCH_ID,
								FEED_ID,
								AWARD_ID, 
								AWARD_NUMBER, 
								ACCOUNT_NUMBER,
								SEQUENCE_NUMBER,
								VARIATION_TYPE,
								ACCOUNT_TYPE,
								TITLE,
								CUR_START_DATE,
								PREV_START_DATE,
								CUR_END_DATE,
								PREV_END_DATE,
								IO_CODE,
								COST_ELEMENT_DESCRIPTION,
								FUND_CODE,
								L1_WBS_DESCRIPTION,
								L2_WBS_DESCRIPTION,
								CUR_PI_NAME,
								PREV_PI_NAME,
								UPDATE_TIMESTAMP,
								UPDATE_USER,
								VARIATION_TYPE_CODE,
								BUSINESS_AREA,
								GRANT_CODE,
								PROFIT_CENTER
								
							)
							VALUES
							(
								LI_REPORT_ID,
								AV_BATCH_ID,
								LI_FEED_ID,
								LI_AWARD_ID,
								LS_AWARD_NUMBER,
								LS_ACCOUNT_NUMBER,
								LI_SEQUENCE_NUMBER,
								-- LS_VARIATION_TYPE,
								CASE WHEN LS_FEED_TYPE = 'N' THEN 'New'
							  ELSE 
								'Change'
							  END,
								LS_ACCOUNT_TYPE,
								LS_TITLE,
								LS_CUR_START_DATE,
								LS_PREV_START_DATE,
								LS_CUR_END_DATE,
								LS_PREV_END_DATE,
								CASE WHEN LI_WBS_LEVEL = 2 THEN LS_WBS_ELEMENT ELSE NULL END,
								NULL,
								LS_FUND_CODE,
								CASE WHEN LI_WBS_LEVEL = 1 THEN LS_L1_WBS_DESCRIPTION ELSE NULL END,
								CASE WHEN LI_WBS_LEVEL = 2 THEN LS_L2_WBS_DESCRIPTION ELSE NULL END,
								LS_PRNCP_INVESTGTR,
								LS_PREV_PI_NAME,
								utc_timestamp(),
								'admin',
								LS_VARIATION_TYPE_CODE,
								LS_BA_CODE,
								LS_GRANT_CODE,
								LS_PROFIT_CENTER
							);
						
						ELSE
						
							IF LI_WBS_LEVEL = 1 THEN -- ACCOUUNT NUMBER 
							
								UPDATE SAP_FEED_REPORT SET CUR_START_DATE = LS_CUR_START_DATE,CUR_END_DATE = LS_CUR_END_DATE,
								FUND_CODE = LS_FUND_CODE,
								L1_WBS_DESCRIPTION = LS_L1_WBS_DESCRIPTION,
								CUR_PI_NAME = LS_PRNCP_INVESTGTR,
								PREV_PI_NAME = LS_PREV_PI_NAME
								WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID
								AND ACCOUNT_NUMBER = LS_WBS_ELEMENT;
															
							ELSEIF LI_WBS_LEVEL = 2 THEN -- IO_CODE
							
								UPDATE SAP_FEED_REPORT SET CUR_START_DATE = LS_CUR_START_DATE,CUR_END_DATE = LS_CUR_END_DATE,
								FUND_CODE = LS_FUND_CODE,
								L2_WBS_DESCRIPTION = LS_L2_WBS_DESCRIPTION,
								CUR_PI_NAME = LS_PRNCP_INVESTGTR,
								PREV_PI_NAME = LS_PREV_PI_NAME
								WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID
								AND IO_CODE = LS_WBS_ELEMENT;
								
								SET LS_L2_WBS_DESCRIPTION = LS_WBS_SHORT_DESCRIPTION;

							
							END IF;
							
						END IF;
						COMMIT;
			
					
					
					END LOOP;
					CLOSE CUR_WBS;
				
				END;
			-- -----------------------------------ENDS SAP_FEED_TMPL_WBS REPORT-----------------------------
			
			-- -----------------------------------STARTS NEW MODIFICATION-----------------------------------
			
				SELECT COUNT(1) INTO LI_FLAG FROM SAP_FEED_TMPL_SPONSOR_PRGM
				WHERE FEED_ID = LI_FEED_ID AND BATCH_ID = AV_BATCH_ID;
			
				IF LI_FLAG > 0 THEN
				
					SELECT COUNT(1) INTO LI_FLAG 
					FROM SAP_FEED_REPORT
					WHERE FEED_ID = LI_FEED_ID
					AND BATCH_ID = AV_BATCH_ID;
				
				IF LI_FLAG = 0 THEN
			
						SELECT IFNULL(MAX(ID),0)+1 INTO LI_REPORT_ID FROM SAP_FEED_REPORT;
						INSERT INTO SAP_FEED_REPORT
						(
							ID, 
							BATCH_ID,
							FEED_ID,
							AWARD_ID, 
							AWARD_NUMBER, 
							ACCOUNT_NUMBER,
							SEQUENCE_NUMBER,
							VARIATION_TYPE,
							ACCOUNT_TYPE,
							TITLE,
							CUR_START_DATE,
							PREV_START_DATE,
							CUR_END_DATE,
							PREV_END_DATE,
							CUR_PI_NAME,
							PREV_PI_NAME,
							UPDATE_TIMESTAMP,
							UPDATE_USER,
							VARIATION_TYPE_CODE,
							BUSINESS_AREA,
							FUND_CODE,
							GRANT_CODE,
							PROFIT_CENTER
						)
						VALUES
						(
							LI_REPORT_ID,
							AV_BATCH_ID,
							LI_FEED_ID,
							LI_AWARD_ID,
							LS_AWARD_NUMBER,
							LS_ACCOUNT_NUMBER,
							LI_SEQUENCE_NUMBER,
							-- LS_VARIATION_TYPE,
							CASE WHEN LS_FEED_TYPE = 'N' THEN 'New'
							  ELSE 
								'Change'
							  END,
							LS_ACCOUNT_TYPE,
							LS_TITLE,
							LS_CUR_START_DATE,
							LS_PREV_START_DATE,
							LS_CUR_END_DATE,
							LS_PREV_END_DATE,
							LS_PRNCP_INVESTGTR,
							LS_PREV_PI_NAME,
							utc_timestamp(),
							'admin',
							LS_VARIATION_TYPE_CODE,
							LS_BA_CODE,
							LS_FUND_CODE,
							LS_GRANT_CODE,
							LS_PROFIT_CENTER
						);
						COMMIT;
				END IF;
			END IF;
			-- -----------------------------------ENDS NEW MODIFICATION-------------------------------------
				
			SET LS_VARIATION_TYPE = NULL;
			SET LS_ACCOUNT_NUMBER = NULL;
			SET LS_AWARD_TITLE = NULL;
			SET LS_ACCOUNT_TYPE = NULL;
			SET LS_CUR_START_DATE = NULL;
			SET LS_CUR_END_DATE	 = NULL;
			SET LI_PREV_AWARD_ID = NULL;
			SET LS_PREV_START_DATE  = NULL;
			SET LS_PREV_END_DATE = NULL;
			SET LS_IO_CODE = NULL;
			SET LS_COST_ELEMENT_DESCRIPTION = NULL;
			SET LS_FUND_CODE = NULL;
			SET LS_GM_FUND_CODE = NULL;
			SET LS_AWD_ACCOUNT_TYPE_CODE = NULL;
			SET LS_ROOT_AWARD_NUMBER = NULL;
			SET LS_FUNDED_PROGRAM = NULL;
			SET LS_PROGRAM_DESCRIPTION = NULL;
			SET LS_PROCESS = NULL;
			SET LI_BUDGET_AMOUNT = NULL;
			SET LI_CUR_LINE_ITEM_COST = NULL;
			SET LI_PREV_LINE_ITEM_COST = NULL;
			SET LS_PROJECT_DEFINITION = NULL;
			SET LS_SHORT_DESCRIPTION = NULL;
			SET LS_WBS_ELEMENT = NULL;
			SET LI_WBS_LEVEL		 = NULL;
			SET LS_WBS_SHORT_DESCRIPTION = NULL;
			SET LS_PRNCP_INVESTGTR		 = NULL;
			SET LS_L1_WBS_DESCRIPTION	 = NULL;
			SET LS_L2_WBS_DESCRIPTION	 = NULL;
			SET LS_PREV_PI_NAME			 = NULL;
			SET LS_TITLE = NULL;
			SET LS_VARIATION_TYPE_CODE	= NULL;
			SET LS_BA_CODE = NULL;
			SET MASTER_AWARD_ID = NULL;
			SET LI_PREV_FEED_ID = NULL;
			SET	LS_GRANT_CODE = NULL;
			SET	LS_PROFIT_CENTER = NULL;
			
			END LOOP;
			CLOSE CUR_FEED_DATA;
		
		END;

END
