-- `SAP_FEED_SOFT_LAUNCH_COUNT`; 

CREATE PROCEDURE `SAP_FEED_SOFT_LAUNCH_COUNT`(
AV_BATCH_ID	INT
)
BEGIN
DECLARE LI_SEQ_ERROR_LOG_ID INT;
DECLARE LS_ERROR_MSG		VARCHAR(4000);
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
		BEGIN
			GET DIAGNOSTICS CONDITION 1 @sqlstate = RETURNED_SQLSTATE, 
			 @errno = MYSQL_ERRNO, @msg = MESSAGE_TEXT;
			SET @full_error = CONCAT("ERROR ", @errno, " (", @sqlstate, "): ", @msg);
			SELECT @full_error INTO LS_ERROR_MSG;
			SELECT IFNULL(MAX(ERROR_ID),0)+1 INTO LI_SEQ_ERROR_LOG_ID FROM SAP_FEED_REPORT_ERROR_LOG;
			INSERT INTO SAP_FEED_REPORT_ERROR_LOG(ERROR_ID,ERROR_MESSAGE, UPDATE_TIMESTAMP, UPDATE_USER)
			VALUES(LI_SEQ_ERROR_LOG_ID,LS_ERROR_MSG,utc_timestamp(),'admin');
			COMMIT;
		END;
	SELECT IFNULL(VARIATION_TYPE,'New Award') AS VARIATION_TYPE ,COUNT(1) AS TOTAL_COUNT FROM SAP_NO_FEED_SOFT_LAUNCH_REPORT
	WHERE BATCH_ID = AV_BATCH_ID AND FEED_STATUS <>'N'
	GROUP BY VARIATION_TYPE
	UNION
	SELECT 'No Feed' AS VARIATION_TYPE,COUNT(1) AS TOTAL_COUNT FROM SAP_NO_FEED_SOFT_LAUNCH_REPORT
	WHERE BATCH_ID = AV_BATCH_ID AND FEED_STATUS = 'N';
END
