-- `UPDATE_WBS_NUMBER`; 

CREATE PROCEDURE `UPDATE_WBS_NUMBER`()
BEGIN
DECLARE DONE TINYINT DEFAULT 0;
DECLARE LS_FILTER_CONDITION VARCHAR(200);
DECLARE LS_WBS_GENERATED VARCHAR(200);
DECLARE FLAG VARCHAR(10) DEFAULT 'N';
DECLARE IOC_GENERATED VARCHAR(200);
DECLARE LS_ACCONUT_NUMBER VARCHAR(200);
DECLARE C1 CURSOR FOR 
	SELECT T1.BUDGET_DETAILS_ID, T1.BUDGET_CATEGORY_CODE, T2.AWARD_ID, T3.ACCOUNT_NUMBER FROM AWARD_BUDGET_DETAIL T1  
    INNER JOIN AWARD_BUDGET_HEADER T2 ON T2.BUDGET_HEADER_ID = T1.BUDGET_HEADER_ID
    INNER JOIN AWARD T3 ON T3.AWARD_ID = T2.AWARD_ID
    WHERE T2.AWARD_ID IN (SELECT AWARD_ID FROM AWARD WHERE AWARD_ID IN(1415)) ;
OPEN C1;
	LOOP1: LOOP BEGIN
	DECLARE LS_AWARD_ID INT;
	DECLARE LS_BUDGET_CATEGORY_CODE VARCHAR(6);
	DECLARE LS_BUDGET_DETAILS_ID INT(20);
    DECLARE LS_ACCONUT_NUMBER VARCHAR(200);
DECLARE CONTINUE HANDLER FOR SQLSTATE '02000' SET DONE = 1;
FETCH C1 INTO LS_BUDGET_DETAILS_ID, LS_BUDGET_CATEGORY_CODE, LS_AWARD_ID, LS_ACCONUT_NUMBER;
	SELECT ACCOUNT_NUMBER INTO LS_ACCONUT_NUMBER FROM AWARD WHERE AWARD_ID = LS_AWARD_ID;
	IF (LS_ACCONUT_NUMBER IS NULL OR LS_ACCONUT_NUMBER = '') THEN
		CALL GENERATE_AWARD_WBS_NUMBER(LS_AWARD_ID, NULL, NULL, 'Y');
    END IF;
IF DONE THEN
LEAVE LOOP1;
END IF;
			CALL GENERATE_AWARD_WBS_NUMBER(LS_AWARD_ID, LS_BUDGET_DETAILS_ID, LS_BUDGET_CATEGORY_CODE, 'N');
			INSERT INTO SAMPLE(A,B,C,D) VALUES (LS_AWARD_ID, LS_BUDGET_DETAILS_ID, LS_BUDGET_CATEGORY_CODE, 'N');
END; 
END LOOP;
CLOSE C1;
END
