CREATE  FUNCTION `FN_PR_NOT_SUBMITTED_BY_PI`(
AV_PROGRESS_REPORT_ID VARCHAR(10), 
AV_PERSON_ID VARCHAR(40) 
) RETURNS varchar(6)
    DETERMINISTIC
BEGIN

DECLARE LS_PI_PERSON_ID     VARCHAR(40);
DECLARE LS_ASSIGNEE_PERSON_ID     VARCHAR(40);
DECLARE LI_AWARD_ID INT(22);
DECLARE LI_COUNT INT(3);


SELECT AWARD_ID INTO LI_AWARD_ID
FROM AWARD_PROGRESS_REPORT 
WHERE PROGRESS_REPORT_ID = AV_PROGRESS_REPORT_ID ;
   

	
SELECT PERSON_ID INTO LS_PI_PERSON_ID 
FROM AWARD_PERSONS
WHERE AWARD_ID = LI_AWARD_ID
AND PI_FLAG = 'Y';

	
IF AV_PERSON_ID <> LS_PI_PERSON_ID THEN
	
	RETURN 'FALSE'; -- Adding map with PI
	
ELSE

	RETURN 'TRUE';

END IF;
    
END 
