-- `GET_EXTERNAL_REVIEW_SUMMARY_DETAILS`; 

CREATE PROCEDURE `GET_EXTERNAL_REVIEW_SUMMARY_DETAILS`(
AV_WIDGET VARCHAR(200),
AV_VIEW_ALL VARCHAR(1),
AV_EXT_REVIEWER_ID VARCHAR(1000)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LL_EXT_REVIEWER_ID VARCHAR(4000);
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_LIMIT VARCHAR(50);
SET LS_FILTER_CONDITION = '';
IF AV_WIDGET = 'REVIEW_SUMMARY_BY_REVIEWERS' THEN
	 IF AV_EXT_REVIEWER_ID = '' THEN 
			SET LS_FILTER_CONDITION = '';
      ELSE
			SET LS_FILTER_CONDITION = CONCAT(LS_FILTER_CONDITION,' AND T2.EXTERNAL_REVIEWER_ID IN( ',AV_EXT_REVIEWER_ID,')');
	 END IF;
	 
	SET LS_DYN_SQL = CONCAT('(SELECT ''Pending'' AS PENDING_REVIEWS, 
								(SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 1 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1, 8) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE=1 ) AS MAIN_PROPOSAL, 
								(SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 1 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1, 8) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE=2 ) AS PRE_PROPOSAL,
                                 (SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 1 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1, 8) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE IN (1,2)) AS TOTAL_COUNT,
									COUNT(T1.EXT_REVIEW_ID) AS COUNT,
									1 AS REVIEWER_STATUS_CODE FROM EXT_REVIEW T1
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 1 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1, 8) ',LS_FILTER_CONDITION,')
							  UNION
								(SELECT ''In Progress'' AS INPROGRESS_REVIEWS, 
                                (SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 2 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE=1 ) AS MAIN_PROPOSAL, 
								(SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 2 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE=2 ) AS PRE_PROPOSAL,
								(SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 2 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE IN (1,2)) AS TOTAL_COUNT,
									COUNT(T1.EXT_REVIEW_ID) AS COUNT,
									2 AS REVIEWER_STATUS_CODE FROM EXT_REVIEW T1
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 2 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,')
							  UNION
								(SELECT ''Completed'' AS COMPLETED_REVIEWS, 
                                (SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 5 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE=1 ) AS MAIN_PROPOSAL, 
								(SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 5 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE=2 ) AS PRE_PROPOSAL,
                                (SELECT COUNT(DISTINCT T1.EXT_REVIEW_ID) FROM EXT_REVIEW T1 
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID 
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 5 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,' AND T1.EXT_REVIEW_SERVICE_TYPE_CODE IN (1,2)) AS TOTAL_COUNT,
									COUNT(T1.EXT_REVIEW_ID) AS COUNT,
									3 AS REVIEWER_STATUS_CODE FROM EXT_REVIEW T1
									LEFT JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
									LEFT JOIN EXT_REVIEW_STATUS T5 ON T5.EXT_REVIEW_STATUS_CODE = T1.EXT_REVIEW_STATUS_CODE
									WHERE T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE = 5 AND T5.EXT_REVIEW_STATUS_CODE NOT IN (1) ',LS_FILTER_CONDITION,')');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
ELSEIF AV_WIDGET = 'REVIEW_SUMMARY' THEN
SET LS_DYN_SQL = CONCAT('(SELECT ''Review Draft'' AS REVIEW_STATUS, 
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 1 AND T2.EXT_REVIEW_STATUS_CODE in (2,4)) AS MAIN_PROPOSAL,
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 2 AND T2.EXT_REVIEW_STATUS_CODE in (2,4)) AS PRE_PROPOSAL,
							COUNT(T1.EXT_REVIEW_ID) AS TOTAL_COUNT, 4 AS EXT_REVIEW_STATUS_CODE FROM EXT_REVIEW T1
								WHERE T1.EXT_REVIEW_STATUS_CODE in (2,4))
						UNION
							(SELECT ''Review Pending'' AS REVIEW_STATUS, 
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 1 AND T2.EXT_REVIEW_STATUS_CODE =5) AS MAIN_PROPOSAL,
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 2 AND T2.EXT_REVIEW_STATUS_CODE =5) AS PRE_PROPOSAL,
							COUNT(T1.EXT_REVIEW_ID) AS TOTAL_COUNT,	T1.EXT_REVIEW_STATUS_CODE AS EXT_REVIEW_STATUS_CODE FROM EXT_REVIEW T1
								WHERE T1.EXT_REVIEW_STATUS_CODE=5)
						UNION
							(SELECT ''Review In Progress'' AS REVIEW_STATUS, 
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 1 AND T2.EXT_REVIEW_STATUS_CODE =6) AS MAIN_PROPOSAL,
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 2 AND T2.EXT_REVIEW_STATUS_CODE =6) AS PRE_PROPOSAL,
							COUNT(T1.EXT_REVIEW_ID) AS TOTAL_COUNT,	T1.EXT_REVIEW_STATUS_CODE AS EXT_REVIEW_STATUS_CODE FROM EXT_REVIEW T1
								WHERE T1.EXT_REVIEW_STATUS_CODE=6)
						UNION
							(SELECT ''Completed'' AS REVIEW_STATUS, 
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 1 AND T2.EXT_REVIEW_STATUS_CODE =3) AS MAIN_PROPOSAL,
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 2 AND T2.EXT_REVIEW_STATUS_CODE =3) AS PRE_PROPOSAL,
								COUNT(T1.EXT_REVIEW_ID) AS TOTAL_COUNT,	T1.EXT_REVIEW_STATUS_CODE AS EXT_REVIEW_STATUS_CODE FROM EXT_REVIEW T1
								WHERE T1.EXT_REVIEW_STATUS_CODE=3)
						UNION
							(SELECT ''Inactive'' AS REVIEW_STATUS, 
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 1 AND T2.EXT_REVIEW_STATUS_CODE =8) AS MAIN_PROPOSAL,
							(SELECT COUNT(T2.EXT_REVIEW_ID) FROM EXT_REVIEW T2 WHERE T2.EXT_REVIEW_SERVICE_TYPE_CODE = 2 AND T2.EXT_REVIEW_STATUS_CODE =8) AS PRE_PROPOSAL,
								COUNT(T1.EXT_REVIEW_ID) AS TOTAL_COUNT,	T1.EXT_REVIEW_STATUS_CODE AS EXT_REVIEW_STATUS_CODE FROM EXT_REVIEW T1
								WHERE T1.EXT_REVIEW_STATUS_CODE=8)');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
ELSEIF AV_WIDGET = 'ACTIVE_REVIEWERS_WIDGET' THEN
SET LS_DYN_SQL = CONCAT('SELECT ''1'' AS REVIEWERS_ASSIGNED , COUNT(EXTERNAL_REVIEWER_ID) FROM
					(SELECT EXTERNAL_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID
					HAVING COUNT(EXTERNAL_REVIEWER_ID) = 1) T
				UNION
				SELECT ''2'' AS REVIEWERS_ASSIGNED , COUNT(EXTERNAL_REVIEWER_ID) FROM
					(SELECT EXTERNAL_REVIEWER_ID FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID
					HAVING COUNT(EXTERNAL_REVIEWER_ID) = 2) T
				UNION
				SELECT ''3'' AS REVIEWERS_ASSIGNED , COUNT(EXTERNAL_REVIEWER_ID) FROM
					(SELECT EXTERNAL_REVIEWER_ID FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID
					HAVING COUNT(EXTERNAL_REVIEWER_ID) = 3) T
				UNION
				SELECT ''4'' AS REVIEWERS_ASSIGNED , COUNT(EXTERNAL_REVIEWER_ID) FROM
					(SELECT EXTERNAL_REVIEWER_ID FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID
					HAVING COUNT(EXTERNAL_REVIEWER_ID) = 4) T
				UNION
				SELECT ''5'' AS REVIEWERS_ASSIGNED , COUNT(EXTERNAL_REVIEWER_ID) FROM
					(SELECT EXTERNAL_REVIEWER_ID FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID
					HAVING COUNT(EXTERNAL_REVIEWER_ID) = 5) T
				UNION
				SELECT ''More than 5'' AS REVIEWERS_ASSIGNED , COUNT(EXTERNAL_REVIEWER_ID) FROM
					(SELECT EXTERNAL_REVIEWER_ID FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID
					HAVING COUNT(EXTERNAL_REVIEWER_ID) > 5) T
				UNION
				SELECT ''Total'' AS REVIEWERS_ASSIGNED, COUNT(T.EXT_REVIEW_COUNT) FROM
					(SELECT COUNT(T1.EXT_REVIEW_ID) AS EXT_REVIEW_COUNT 
					FROM EXT_REVIEW T1 
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID = T1.EXT_REVIEW_ID
					WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(4,7,8) AND EXT_REVIEW_SERVICE_TYPE_CODE=2
					GROUP BY T1.EXT_REVIEW_ID) T');
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
ELSEIF AV_WIDGET = 'INCOMING_REVIEW' THEN
	
    IF AV_VIEW_ALL ='N' THEN 
		SET LS_LIMIT = ' LIMIT 6 ';
	ELSE
		SET LS_LIMIT = '';
    END IF;
					SET LS_DYN_SQL = CONCAT('SELECT EXT_REVIEW_ID,T1.DESCRIPTION AS REVIEW_TITLE,T1.REQUEST_DATE,T2.DESCRIPTION AS REVIEW_TYPE,CONCAT (MODULE_ITEM_KEY,''-'',lpad(VERSION_NUMBER,3,0)) as EXT_REVIEW_NUMBER  from EXT_REVIEW T1
						INNER JOIN EXT_REVIEW_SERVICE_TYPE T2 ON T2.EXT_REVIEW_SERVICE_TYPE_CODE=T1.EXT_REVIEW_SERVICE_TYPE_CODE 
                        WHERE T1.EXT_REVIEW_STATUS_CODE in (2, 4) ORDER BY T1.UPDATE_TIMESTAMP DESC',LS_LIMIT,'');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
    
ELSEIF AV_WIDGET = 'REVIEWERS_EVALUATED' THEN
SET LS_DYN_SQL = CONCAT('SELECT ''1'' AS REVIEWERS_EVALUATED , COUNT(REVIEW_REVIEWER_ID) FROM
					(SELECT COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) AS REVIEW_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1  AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID HAVING COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) = 1) T
                    UNION
                    SELECT ''2'' AS REVIEWERS_EVALUATED , COUNT(REVIEW_REVIEWER_ID) FROM
					(SELECT COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) AS REVIEW_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1   AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID HAVING COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) = 2) T
                    UNION
                    SELECT ''3'' AS REVIEWERS_EVALUATED , COUNT(REVIEW_REVIEWER_ID) FROM
					(SELECT COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) AS REVIEW_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1   AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID HAVING COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) = 3) T
                    UNION
                    SELECT ''4'' AS REVIEWERS_EVALUATED , COUNT(REVIEW_REVIEWER_ID) FROM
					(SELECT COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) AS REVIEW_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1   AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID HAVING COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) = 4) T
                    UNION
                    SELECT ''5'' AS REVIEWERS_EVALUATED , COUNT(REVIEW_REVIEWER_ID) FROM
					(SELECT COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) AS REVIEW_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1  AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID HAVING COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) = 5) T
                    UNION
                    SELECT ''More than 5'' AS REVIEWERS_EVALUATED , COUNT(REVIEW_REVIEWER_ID) FROM
					(SELECT COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) AS REVIEW_REVIEWER_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1  AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID HAVING COUNT(DISTINCT T2.REVIEW_REVIEWER_ID) > 5) T
                    UNION
                    SELECT ''Total'' AS REVIEWERS_EVALUATED , COUNT(EXT_REVIEW_ID) FROM
					(SELECT T1.EXT_REVIEW_ID  FROM EXT_REVIEW T1
					INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
                    INNER JOIN EXT_REV_REVIEWER_SCORE T3 ON T3.REVIEW_REVIEWER_ID =T2.REVIEW_REVIEWER_ID
                   	WHERE EXT_REVIEW_SERVICE_TYPE_CODE=1 AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE= 5
					GROUP BY  T2.EXT_REVIEW_ID) T');
		
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
ELSEIF AV_WIDGET = 'ASSIGNMENT_LIMIT_WIDGET' THEN
SET LS_DYN_SQL = CONCAT('SELECT REVIWER AS REVIEWER_ID, FULL_NAME,
							(SELECT COUNT(T1.EXT_REVIEW_ID) FROM EXT_REVIEW_REVIEWERS T1 INNER JOIN EXT_REVIEW T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID WHERE T1.EXTERNAL_REVIEWER_ID IN (REVIWER) AND T2.EXT_REVIEW_SERVICE_TYPE_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(2,3,4,7) AND T1.EXT_REV_REVIEWER_FLOW_STATUS_CODE NOT IN(5) GROUP BY T1.EXTERNAL_REVIEWER_ID ) AS MAIN_PROPOSAL, 
							(SELECT COUNT(T1.EXT_REVIEW_ID) FROM EXT_REVIEW_REVIEWERS T1 INNER JOIN EXT_REVIEW T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID WHERE T1.EXTERNAL_REVIEWER_ID IN (REVIWER) AND T2.EXT_REVIEW_SERVICE_TYPE_CODE=2 AND EXT_REVIEW_STATUS_CODE NOT IN(2,3,4,7) AND T1.EXT_REV_REVIEWER_FLOW_STATUS_CODE NOT IN(5) GROUP BY T1.EXTERNAL_REVIEWER_ID ) AS PRE_PROPOSAL,
							(SELECT COUNT(T1.EXT_REVIEW_ID) FROM EXT_REVIEW_REVIEWERS T1 INNER JOIN EXT_REVIEW T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID WHERE T1.EXTERNAL_REVIEWER_ID IN (REVIWER) AND T2.EXT_REVIEW_SERVICE_TYPE_CODE IN (1,2) AND EXT_REVIEW_STATUS_CODE NOT IN(2,3,4,7) AND T1.EXT_REV_REVIEWER_FLOW_STATUS_CODE NOT IN(5) GROUP BY T1.EXTERNAL_REVIEWER_ID ) AS TOTAL
							FROM (SELECT T2.EXTERNAL_REVIEWER_ID AS REVIWER , T3.FULL_NAME AS FULL_NAME FROM EXT_REVIEW T1
								INNER JOIN EXT_REVIEW_REVIEWERS T2 ON T2.EXT_REVIEW_ID=T1.EXT_REVIEW_ID
								INNER JOIN EXTERNAL_REVIEWER T3 ON T3.EXTERNAL_REVIEWER_ID = T2.EXTERNAL_REVIEWER_ID
								WHERE T2.EXT_REVIEWERS_STATUS_CODE=1 AND EXT_REVIEW_STATUS_CODE NOT IN(2,3,4,8) AND EXT_REVIEW_SERVICE_TYPE_CODE IN (1,2)
								AND T2.EXT_REV_REVIEWER_FLOW_STATUS_CODE NOT IN(5)
								GROUP BY T2.EXTERNAL_REVIEWER_ID
								HAVING COUNT(T1.EXT_REVIEW_ID) >=7) T');
                                
                                
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;                              
END IF;
END
