INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('1','Regular','2025-04-01 14:10:44','admin','Y');
INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('3','Core Grant Administration','2019-05-31 10:51:07','admin','Y');
INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('4','Gift','2019-05-31 10:51:07','admin','Y');
INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('5','Conversion Account','2019-05-31 10:51:07','admin','Y');
INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('6','Off-Campus Account','2025-04-01 14:11:02','admin','Y');
INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('7','Service Facilities','2025-04-01 14:11:41','admin','Y');
INSERT INTO account_type (ACCOUNT_TYPE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,IS_ACTIVE) VALUES ('8','No Account','2025-04-01 14:11:52','admin','Y');
