

DROP TABLE IF EXISTS `person_rt`;

CREATE TABLE `person_rt` (
  `PERSON_RT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS_LINE_1` varchar(255) DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `DEGREE` varchar(255) DEFAULT NULL,
  `DIRECTORY_DEPARTMENT` varchar(255) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `HOME_UNIT` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `OFFICE_LOCATION` varchar(255) DEFAULT NULL,
  `OFFICE_PHONE` varchar(255) DEFAULT NULL,
  `PERSON_ID` varchar(255) DEFAULT NULL,
  `PRIMARY_TITLE` varchar(255) DEFAULT NULL,
  `RELATIONSHIP` varchar(255) DEFAULT NULL,
  `STATE_PROVINCE` varchar(255) DEFAULT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  `ZIP_CODE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PERSON_RT_ID`)
) ;
