
DROP TABLE IF EXISTS `report_columns`;

CREATE TABLE `report_columns` (
  `REPORT_COLUMN_ID` int(11) NOT NULL,
  `TYPE_CODE` varchar(5) DEFAULT NULL,
  `COLUMN_ID` int(11) DEFAULT NULL,
  `IS_FILTER` varchar(1) DEFAULT NULL,
  `IS_COLUMN` varchar(1) DEFAULT NULL,
  `DISPLAY_NAME` varchar(250) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`REPORT_COLUMN_ID`),
  KEY `REPORT_COLUMNS_FK1` (`COLUMN_ID`),
  KEY `REPORT_COLUMNS_FK2` (`TYPE_CODE`),
  CONSTRAINT `REPORT_COLUMNS_FK1` FOREIGN KEY (`COLUMN_ID`) REFERENCES `column_lookup` (`COLUMN_ID`),
  CONSTRAINT `REPORT_COLUMNS_FK2` FOREIGN KEY (`TYPE_CODE`) REFERENCES `report_type` (`TYPE_CODE`)
) ;