
DROP TABLE IF EXISTS `report_type_join`;

CREATE TABLE `report_type_join` (
  `TYPE_JOIN_ID` int(11) NOT NULL,
  `TYPE_CODE` varchar(3) DEFAULT NULL,
  `JOIN_QUERY` longtext,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`TYPE_JOIN_ID`),
  KEY `REPORT_TYPE_JOIN_FK1` (`TYPE_CODE`),
  CONSTRAINT `REPORT_TYPE_JOIN_FK1` FOREIGN KEY (`TYPE_CODE`) REFERENCES `report_type` (`TYPE_CODE`)
) ;