CREATE  PROCEDURE `AGT_LOC_REVIEW_START_DATE_REMAINDER`( AV_DAYS INT )
BEGIN
SELECT
    13 AS MODULE_CODE,
    0 AS SUB_MODULE_CODE,
    t1.AGREEMENT_REQUEST_ID AS MODULE_ITEM_KEY,
    t3.NEGOTIATION_LOCATION_ID AS SUB_MODULE_ITEM_KEY,
    '1300' AS MESSAGE_TYPE_CODE,
    'P' AS SUBJECT_TYPE_CODE,
    CONCAT('#',t1.AGREEMENT_REQUEST_ID,' - ',t1.TITLE,' - ',t7.DESCRIPTION) AS USER_MESSAGE,
    t3.ASSIGNEE_PERSON_ID AS PERSON_ID,
    t4.FULL_NAME AS ASSIGNEE,
    t6.DESCRIPTION AS NEGOTIATION_LOCATION,
    t5.DESCRIPTION AS NEGOTIATION_STATUS,
    DATE(t3.REVIEW_START_DATE) AS LOCATION_ASSIGNED_DATE,
    DATE(t3.REVIEW_END_DATE) AS REVIEW_END_DATE
FROM agreement_header t1
INNER JOIN negotiation_association t2 ON t1.AGREEMENT_REQUEST_ID = t2.ASSOCIATED_PROJECT_ID
INNER JOIN negotiation_location t3 ON t2.NEGOTIATION_ID = t3.NEGOTIATION_ID
INNER JOIN person t4 ON t3.ASSIGNEE_PERSON_ID = t4.PERSON_ID
INNER JOIN negotiation_location_status t5 ON t3.LOCATION_STATUS_CODE = t5.LOCATION_STATUS_CODE
INNER JOIN negotiation_location_type t6 ON t3.LOCATION_TYPE_CODE = t6.LOCATION_TYPE_CODE
LEFT JOIN AGREEMENT_TYPE t7 ON t1.AGREEMENT_TYPE_CODE = t7.AGREEMENT_TYPE_CODE
WHERE t3.ASSIGNEE_PERSON_ID IS NOT NULL
AND t1.AGREEMENT_STATUS_CODE IN (SELECT S.AGREEMENT_STATUS_CODE FROM AGREEMENT_STATUS S WHERE S.IS_TERMINAL <> 'Y')
AND t3.LOCATION_STATUS_CODE NOT IN ('3', '4')
AND t3.REVIEW_END_DATE IS NULL
AND (DATE_ADD(DATE(UTC_TIMESTAMP()), INTERVAL AV_DAYS DAY) = DATE(t3.REVIEW_START_DATE));
END