CREATE PROCEDURE `CHECK_USER_HAS_RIGHT_IN_DOC`(
AV_MODULE_CODE int(3),
AV_MODULE_ITEM_ID VARCHAR(22),	
AV_RIGHT_NAME VARCHAR(100),
AV_PERSON_ID VARCHAR(40))
BEGIN
DECLARE LI_FLAG INT;
DECLARE LI_COUNT INT;
DECLARE LS_RIGHT_NAME VARCHAR(500);
DECLARE LS_LEAD_UNIT varchar(50);
DECLARE LS_SYS_GENERATED varchar(1);
DECLARE LS_MODULE_CODE int(3);
DECLARE LS_MODULE_ITEM_KEY VARCHAR(22);
DECLARE LS_DYN_SQL VARCHAR(2000) default '';

IF AV_RIGHT_NAME != '' THEN
	SET LS_RIGHT_NAME = CONCAT("'", REPLACE(AV_RIGHT_NAME, ",", "','"), "'");
ELSE
	SET LS_RIGHT_NAME = AV_RIGHT_NAME;
END IF; 

IF AV_MODULE_CODE = 1 THEN

											SELECT G1.HOME_UNIT_NUMBER INTO LS_LEAD_UNIT FROM AWARD AWD1 
											INNER JOIN GRANT_CALL_HEADER G1 ON AWD1.GRANT_HEADER_ID = G1.GRANT_HEADER_ID
											WHERE AWD1.AWARD_ID = AV_MODULE_ITEM_ID;
											
										IF LS_LEAD_UNIT IS NULL THEN 
												SET LS_LEAD_UNIT ='';
										END IF;
											
	set LS_DYN_SQL = concat(LS_DYN_SQL, ' select COUNT(1) INTO @LI_FLAG from (
										SELECT DISTINCT T3.RIGHT_NAME FROM AWARD_PERSON_ROLES T1
											INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
											INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
											WHERE T1.AWARD_ID = ', AV_MODULE_ITEM_ID,' AND T3.RIGHT_NAME IN(',LS_RIGHT_NAME,') AND T1.PERSON_ID =''', AV_PERSON_ID,'''
										UNION
										SELECT DISTINCT RLE.RIGHT_NAME  FROM  PERSON_ROLES PR JOIN
										(SELECT ROLE_ID,RT.RIGHT_NAME FROM ROLE_RIGHTS RR, RIGHTS RT
										WHERE RR.RIGHT_ID = RT.RIGHT_ID AND RT.RIGHT_NAME IN (',LS_RIGHT_NAME,')) RLE ON RLE.ROLE_ID = PR.ROLE_ID AND RLE.ROLE_ID =100 
										WHERE PR.PERSON_ID = ''', AV_PERSON_ID,''' AND (( PR. DESCEND_FLAG = ''Y'' AND  EXISTS (SELECT 1
                                         FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER = PR.UNIT_NUMBER AND CHILD_UNIT_NUMBER = ''', LS_LEAD_UNIT,'''
										))OR ( PR. DESCEND_FLAG = ''N'' AND PR.UNIT_NUMBER = ''', LS_LEAD_UNIT,''' ))
										
										UNION
										SELECT DISTINCT RLE.RIGHT_NAME  FROM  PERSON_ROLES PR JOIN
										(SELECT ROLE_ID,RT.RIGHT_NAME FROM ROLE_RIGHTS RR, RIGHTS RT
										WHERE RR.RIGHT_ID = RT.RIGHT_ID AND RT.RIGHT_NAME IN (',LS_RIGHT_NAME,')) RLE ON RLE.ROLE_ID = PR.ROLE_ID
										WHERE PR.PERSON_ID = (SELECT DISTINCT PERSON_ID
												FROM GRANT_CALL_FUNDING_SCHEME_MANAGERS
												WHERE FUNDING_SCHEME_CODE IN (SELECT TS3.FUNDING_SCHEME_CODE FROM GRANT_CALL_HEADER TS1
														INNER JOIN AWARD TS2 ON TS1.GRANT_HEADER_ID = TS2.GRANT_HEADER_ID
														INNER JOIN SPONSOR_FUNDING_SCHEME TS3 ON TS3.FUNDING_SCHEME_ID = TS1.FUNDING_SCHEME_ID
														WHERE TS2.AWARD_ID = ', AV_MODULE_ITEM_ID,')
												AND PERSON_ID =''', AV_PERSON_ID,''')) T');
											
											
					
				SET @QUERY_STATEMENT = LS_DYN_SQL;
				PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
				EXECUTE EXECUTABLE_STAEMENT ;
				SET LI_FLAG = @LI_FLAG; 

				IF LI_FLAG > 0 THEN
					SELECT 'TRUE' FROM DUAL;
				ELSE 
					SELECT 'FALSE' FROM DUAL;
				END IF;
				
ELSEIF AV_MODULE_CODE = 3 AND (find_in_set ('VIEW_CONFIDENTIAL_PROPOSAL_ATTACHMENTS',AV_RIGHT_NAME) > 0) THEN
	
    set LS_DYN_SQL = concat(LS_DYN_SQL, 'SELECT COUNT(1) INTO @LI_FLAG FROM EPS_PROPOSAL_PERSON_ROLES T1
											INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
											INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
											WHERE T1.PROPOSAL_ID = ', AV_MODULE_ITEM_ID,' AND T3.RIGHT_NAME IN(',LS_RIGHT_NAME,') AND T1.PERSON_ID =''', AV_PERSON_ID,'''');
											
											
					
				SET @QUERY_STATEMENT = LS_DYN_SQL;
				PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
				EXECUTE EXECUTABLE_STAEMENT ;
				SET LI_FLAG = @LI_FLAG; 

				IF LI_FLAG > 0 THEN
					SELECT 'TRUE' FROM DUAL;
				ELSE 
					SELECT 'FALSE' FROM DUAL;
				END IF;

ELSEIF AV_MODULE_CODE = 3 AND (find_in_set ('VIEW_PRIVATE_COMMENTS',AV_RIGHT_NAME) > 0) THEN

		set LS_RIGHT_NAME = 'VIEW_PRIVATE_COMMENTS';
			
			PROC_LABEL : BEGIN
				SELECT HOME_UNIT_NUMBER INTO LS_LEAD_UNIT FROM EPS_PROPOSAL
				WHERE PROPOSAL_ID = AV_MODULE_ITEM_ID;

				SELECT COUNT(1) INTO LI_COUNT 
				FROM EPS_PROPOSAL
				WHERE PROPOSAL_ID = AV_MODULE_ITEM_ID
				AND GRANT_HEADER_ID IS NOT NULL;
				
						IF LI_COUNT > 0 THEN
								SELECT COUNT(1) INTO LI_COUNT FROM GRANT_CALL_HEADER T1
								INNER JOIN EPS_PROPOSAL T2 ON T1.GRANT_HEADER_ID = T2.GRANT_HEADER_ID
								WHERE T2.PROPOSAL_ID = AV_MODULE_ITEM_ID
								AND T1.HOME_UNIT_NUMBER <> (SELECT VALUE FROM PARAMETER WHERE PARAMETER_NAME = 'ROOT_UNIT');
						END IF;
					
					IF LI_COUNT = 0 THEN
							SELECT COUNT(1) INTO LI_FLAG
							FROM PERSON_ROLES PR JOIN
							(SELECT ROLE_ID,RT.RIGHT_NAME 
							   FROM ROLE_RIGHTS RR,
									RIGHTS RT
								WHERE RR.RIGHT_ID = RT.RIGHT_ID
								  AND RT.RIGHT_NAME = LS_RIGHT_NAME
							 ) RLE ON RLE.ROLE_ID = PR.ROLE_ID
							WHERE PR.PERSON_ID = AV_PERSON_ID
							  AND (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1 FROM UNIT_WITH_CHILDREN 
																				   WHERE UNIT_NUMBER = PR.UNIT_NUMBER
																					AND CHILD_UNIT_NUMBER = LS_LEAD_UNIT
								 ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT ));
								
								IF LI_FLAG > 0 THEN
									SELECT 'TRUE' FROM DUAL;
									LEAVE PROC_LABEL;
								END IF; 

							SELECT COUNT(1) INTO LI_FLAG FROM EPS_PROPOSAL_PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.PROPOSAL_ID = AV_MODULE_ITEM_ID
							AND T1.PERSON_ID = AV_PERSON_ID
							AND T3.RIGHT_NAME = LS_RIGHT_NAME;
							
								IF LI_FLAG > 0 THEN
									SELECT 'TRUE' FROM DUAL;
									LEAVE PROC_LABEL;
								END IF;
					ELSE
						  
							SELECT COUNT(1) INTO LI_FLAG
							FROM PERSON_ROLES PR JOIN
							(SELECT ROLE_ID,RT.RIGHT_NAME 
							   FROM ROLE_RIGHTS RR,
									RIGHTS RT
								WHERE RR.RIGHT_ID = RT.RIGHT_ID
								  AND RT.RIGHT_NAME = LS_RIGHT_NAME
							) RLE ON  RLE.ROLE_ID = PR.ROLE_ID
							WHERE PR.PERSON_ID = AV_PERSON_ID
							  AND (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1 FROM UNIT_WITH_CHILDREN 
																					WHERE UNIT_NUMBER = PR.UNIT_NUMBER
																					AND CHILD_UNIT_NUMBER = LS_LEAD_UNIT
								 ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT ));
							
								IF LI_FLAG > 0 THEN
									SELECT 'TRUE' FROM DUAL;
									LEAVE PROC_LABEL;
								END IF; 
							
						SELECT COUNT(1) INTO LI_FLAG FROM EPS_PROPOSAL_PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
							WHERE T1.PROPOSAL_ID = AV_MODULE_ITEM_ID
							AND T1.PERSON_ID = AV_PERSON_ID
							AND T3.RIGHT_NAME = LS_RIGHT_NAME;
							
						
								IF LI_FLAG > 0 THEN
									SELECT 'TRUE' FROM DUAL;
									LEAVE PROC_LABEL;
								END IF;
								
							SELECT G1.HOME_UNIT_NUMBER INTO LS_LEAD_UNIT FROM EPS_PROPOSAL EPS1
													INNER JOIN GRANT_CALL_HEADER G1 ON EPS1.GRANT_HEADER_ID = G1.GRANT_HEADER_ID
													WHERE EPS1.PROPOSAL_ID = AV_MODULE_ITEM_ID;
							
							SELECT COUNT(1) INTO LI_FLAG
							FROM PERSON_ROLES PR JOIN 
							(SELECT ROLE_ID,RT.RIGHT_NAME 
							   FROM ROLE_RIGHTS RR,
									RIGHTS RT
								WHERE RR.RIGHT_ID = RT.RIGHT_ID
								  AND RT.RIGHT_NAME = LS_RIGHT_NAME
							) RLE ON RLE.ROLE_ID = PR.ROLE_ID AND RLE.ROLE_ID = 100
							WHERE PR.PERSON_ID = AV_PERSON_ID
							  AND (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1
																					 FROM UNIT_WITH_CHILDREN 
																									  WHERE UNIT_NUMBER = PR.UNIT_NUMBER
																									  AND CHILD_UNIT_NUMBER = LS_LEAD_UNIT
								 ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = LS_LEAD_UNIT ));

								IF LI_FLAG > 0 THEN
									SELECT 'TRUE' FROM DUAL;
									LEAVE PROC_LABEL;
								END IF;
				END IF;
			SELECT 'FALSE' FROM DUAL;
		END;

ELSEIF AV_MODULE_CODE = 20 THEN

SELECT UNIT_NUMBER,IS_SYSTEM_GENERATED,ORIGINATING_MODULE_CODE,ORIGINATING_MODULE_ITEM_KEY  INTO LS_LEAD_UNIT,LS_SYS_GENERATED,LS_MODULE_CODE,LS_MODULE_ITEM_KEY FROM SR_HEADER
                            WHERE SR_HEADER_ID =AV_MODULE_ITEM_ID;

IF LS_SYS_GENERATED = 'Y'  AND LS_MODULE_CODE = '1' THEN

SELECT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT FROM AWARD
                            WHERE AWARD_ID =LS_MODULE_ITEM_KEY;
ELSE
SELECT UNIT_NUMBER INTO LS_LEAD_UNIT FROM SR_HEADER
                            WHERE SR_HEADER_ID =AV_MODULE_ITEM_ID;
END IF;

							
set LS_DYN_SQL = concat(LS_DYN_SQL, 'SELECT COUNT(1) INTO @LI_FLAG FROM  PERSON_ROLES PR JOIN 
										(SELECT ROLE_ID,RT.RIGHT_NAME FROM ROLE_RIGHTS RR, RIGHTS RT
										WHERE RR.RIGHT_ID = RT.RIGHT_ID AND RT.RIGHT_NAME IN (',LS_RIGHT_NAME,')) RLE ON RLE.ROLE_ID = PR.ROLE_ID
										WHERE PR.PERSON_ID = ''', AV_PERSON_ID,''' AND (( PR. DESCEND_FLAG = ''Y'' AND  EXISTS (SELECT 1
                                         FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER = PR.UNIT_NUMBER AND CHILD_UNIT_NUMBER = ''', LS_LEAD_UNIT,'''
										))OR ( PR. DESCEND_FLAG = ''N'' AND PR.UNIT_NUMBER = ''', LS_LEAD_UNIT,''' ))');							
					
				SET @QUERY_STATEMENT = LS_DYN_SQL;
                
				 PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
                
				EXECUTE EXECUTABLE_STAEMENT ;
				SET LI_FLAG = @LI_FLAG; 
				
  				IF LI_FLAG = 0 then

                set LS_DYN_SQL =concat('SELECT count(1) into @LI_FLAG
					FROM 
					SR_PERSON_ROLES P 
					JOIN ROLE_RIGHTS R
					ON P.ROLE_ID = R.ROLE_ID 
					JOIN RIGHTS RI 
					ON RI.RIGHT_ID = R.RIGHT_ID
					WHERE 
					P.SR_HEADER_ID = ', AV_MODULE_ITEM_ID,' and RI.RIGHT_NAME  in 
                    (',LS_RIGHT_NAME,') AND P.PERSON_ID =''',  AV_PERSON_ID,'''');	
                SET @QUERY_STATEMENT = LS_DYN_SQL;

				 PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;

				EXECUTE EXECUTABLE_STAEMENT ;
				END IF;
				SET LI_FLAG = @LI_FLAG;
				IF LI_FLAG > 0 THEN
					SELECT 'TRUE' FROM DUAL;
				ELSE 
					SELECT 'FALSE' FROM DUAL;
				END IF;
				

ELSEIF AV_MODULE_CODE = 13 AND (find_in_set ('VIEW_CONFIDENTIAL_AGREEMENT_ATTACHMENTS',AV_RIGHT_NAME) > 0) THEN
	
    set LS_DYN_SQL = concat(LS_DYN_SQL, 'SELECT COUNT(1) INTO @LI_FLAG FROM AGREEMENT_PEOPLE_ROLES T1
											INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
											INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID
											WHERE T1.AGREEMENT_REQUEST_ID = ', AV_MODULE_ITEM_ID,' AND T3.RIGHT_NAME IN(',LS_RIGHT_NAME,') AND T1.PERSON_ID =''', AV_PERSON_ID,'''');
											
											
					
				SET @QUERY_STATEMENT = LS_DYN_SQL;
				PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
				EXECUTE EXECUTABLE_STAEMENT ;
				SET LI_FLAG = @LI_FLAG; 

				IF LI_FLAG > 0 THEN
					SELECT 'TRUE' FROM DUAL;
				ELSE 
					SELECT 'FALSE' FROM DUAL;
				END IF;
END IF;

END
