CREATE PROCEDURE GET_SPONSOR_GROUP_NAMES(IN AV_SEARCH_WORD VARCHAR(60))
BEGIN
    IF AV_SEARCH_WORD IS NULL OR TRIM(AV_SEARCH_WORD) = '' THEN
        SELECT DISTINCT SPONSOR_GROUP_NAME, SPONSOR_GROUP_ID
        FROM SPONSOR_HIERARCHY
        WHERE SPONSOR_CODE IS NULL;
    ELSE
        SELECT DISTINCT SPONSOR_GROUP_NAME, SPONSOR_GROUP_ID
        FROM SPONSOR_HIERARCHY
        WHERE SPONSOR_CODE IS NULL
          AND SPONSOR_GROUP_NAME LIKE AV_SEARCH_WORD;
    END IF;
END
