-- `GET_WORKFLOW_MISSING_ROLE_TYPE`; 

CREATE PROCEDURE `GET_WORKFLOW_MISSING_ROLE_TYPE`(
AV_MODULE_CODE			INT(3),
AV_SUBMODULE_CODE		INT(3),
AV_MODULE_ITEM_ID		VARCHAR(20),
AV_SUB_MODULE_ITEM_ID	VARCHAR(20)
)
BEGIN
	SELECT DISTINCT T2.MAP_ID,T3.ROLE_TYPE_CODE,T4.DESCRIPTION AS ROLE_TYPE,T5.MAP_NAME
	FROM WORKFLOW T1 
	INNER JOIN WORKFLOW_DETAIL T2 ON T1.WORKFLOW_ID = T2.WORKFLOW_ID
    INNER JOIN workflow_map_detail T3 ON T2.MAP_ID = T3.MAP_ID
    LEFT OUTER JOIN PERSON_ROLE_TYPE T4 ON T3.ROLE_TYPE_CODE = T4.ROLE_TYPE_CODE
    INNER JOIN WORKFLOW_MAP T5 ON T2.MAP_ID = T5.MAP_ID
	WHERE T1.MODULE_CODE = AV_MODULE_CODE
	AND T1.SUB_MODULE_CODE = AV_SUBMODULE_CODE
	AND T1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
	AND ifnull(T1.SUB_MODULE_ITEM_ID,'0') = AV_SUB_MODULE_ITEM_ID
	AND T1.IS_WORKFLOW_ACTIVE = 'Y'
    AND T3.ROLE_TYPE_CODE IS NOT NULL
    AND T3.ROLE_TYPE_CODE NOT IN (SELECT DISTINCT W2.ROLE_TYPE_CODE
								FROM WORKFLOW W1 
								INNER JOIN WORKFLOW_DETAIL W2 ON W1.WORKFLOW_ID = W2.WORKFLOW_ID
								WHERE W1.MODULE_CODE = AV_MODULE_CODE
								AND W1.SUB_MODULE_CODE = AV_SUBMODULE_CODE
								AND W1.MODULE_ITEM_ID = AV_MODULE_ITEM_ID
								AND ifnull(W1.SUB_MODULE_ITEM_ID,'0') = AV_SUB_MODULE_ITEM_ID
								AND W1.IS_WORKFLOW_ACTIVE = 'Y'
                                AND W2.ROLE_TYPE_CODE IS NOT NULL
                                AND W2.MAP_ID = T2.MAP_ID);
END
