-- `GET_PERSON_BASED_RIGHT_AND_UNIT`; 

CREATE PROCEDURE `GET_PERSON_BASED_RIGHT_AND_UNIT`(AV_RIGHT_NAME VARCHAR(150),
AV_UNIT_NUMBER VARCHAR(50)
)
BEGIN
IF AV_UNIT_NUMBER IS NULL OR AV_UNIT_NUMBER = '' THEN
   SELECT DISTINCT PR.PERSON_ID FROM PERSON_ROLES PR
   JOIN 
        (SELECT ROLE_ID,RT.RIGHT_NAME
           FROM ROLE_RIGHTS RR JOIN
                RIGHTS RT
            ON RR.RIGHT_ID = RT.RIGHT_ID
              WHERE RT.RIGHT_NAME = AV_RIGHT_NAME
        ) RLE
        ON  RLE.ROLE_ID = PR.ROLE_ID;
ELSE
  SELECT DISTINCT PR.PERSON_ID FROM PERSON_ROLES PR
  JOIN
        (SELECT ROLE_ID,RT.RIGHT_NAME
           FROM ROLE_RIGHTS RR JOIN
                RIGHTS RT
            ON RR.RIGHT_ID = RT.RIGHT_ID
              WHERE RT.RIGHT_NAME = AV_RIGHT_NAME
        ) RLE
        ON
          (( PR. DESCEND_FLAG = 'Y' AND  EXISTS (SELECT 1
                                                                 FROM UNIT_WITH_CHILDREN
                                                                                  WHERE UNIT_NUMBER = PR.UNIT_NUMBER AND CHILD_UNIT_NUMBER = AV_UNIT_NUMBER
             ))OR ( PR. DESCEND_FLAG = 'N' AND PR.UNIT_NUMBER = AV_UNIT_NUMBER )
            )
         WHERE RLE.ROLE_ID = PR.ROLE_ID;
         END IF;
END
