CREATE PROCEDURE `GET_RULE_EVALUATE_REROUTING`(
    IN AV_MODULE_CODE           DECIMAL(38,0),
    IN AV_SUBMODULE_CODE        DECIMAL(38,0),
    IN AV_MODULE_ITEM_KEY       VARCHAR(200),
    IN AV_UPDATE_USER           VARCHAR(200),
    IN AV_LOGGIN_PERSON_ID      VARCHAR(200),
    IN AV_SUB_MODULE_ITEM_KEY   VARCHAR(20)
)
BEGIN
    DECLARE LS_RESULT VARCHAR(10);
    DECLARE LI_RULE_ID INT(6);
    DECLARE LS_RULE_TYPE VARCHAR(2);
    DECLARE LS_RULE_EXPRESSION VARCHAR(300);
    DECLARE LS_USER_MESSAGE VARCHAR(4000);
    DECLARE LS_PARENT_UNIT_NUMBER VARCHAR(50);
    DECLARE LS_LEAD_UNIT_NUMBER VARCHAR(50);
    DECLARE LI_COUNT INT;
    DECLARE DONE1 INT DEFAULT FALSE;
    DECLARE RULE_FAILED INT DEFAULT -1;

    DECLARE RULE_CURSOR CURSOR FOR 
        SELECT T1.RULE_ID, T1.RULE_TYPE, T1.RULE_EXPRESSION, T1.USER_MESSAGE 
        FROM BUSINESS_RULES T1
        WHERE T1.MODULE_CODE = AV_MODULE_CODE 
          AND T1.SUB_MODULE_CODE = AV_SUBMODULE_CODE
          AND T1.UNIT_NUMBER = LS_PARENT_UNIT_NUMBER
          AND T1.RULE_TYPE = 'RR'
          AND T1.IS_ACTIVE = 'Y';

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

    -- Determine LEAD UNIT NUMBER based on module code
    IF AV_MODULE_CODE = 1 THEN
        SELECT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM AWARD WHERE AWARD_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 3 THEN
        SELECT HOME_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM EPS_PROPOSAL WHERE PROPOSAL_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 13 THEN
        SELECT UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM AGREEMENT_HEADER WHERE AGREEMENT_REQUEST_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 15 THEN
        SELECT HOME_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM grant_call_header WHERE GRANT_HEADER_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 14 THEN
        SELECT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM AWARD 
        WHERE AWARD_ID IN (SELECT AWARD_ID FROM CLAIM WHERE CLAIM_ID = AV_MODULE_ITEM_KEY);
    ELSEIF AV_MODULE_CODE = 16 THEN
        SELECT LEAD_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM AWARD 
        WHERE AWARD_ID IN (SELECT AWARD_ID FROM AWARD_PROGRESS_REPORT WHERE PROGRESS_REPORT_ID = AV_MODULE_ITEM_KEY);
    ELSEIF AV_MODULE_CODE = 2 THEN
        SELECT HOME_UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM PROPOSAL WHERE PROPOSAL_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 20 THEN
        SELECT UNIT_NUMBER INTO LS_LEAD_UNIT_NUMBER FROM SR_HEADER WHERE SR_HEADER_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 8 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT_NUMBER FROM COI_DISCLOSURE WHERE DISCLOSURE_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 24 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT_NUMBER FROM COI_TRAVEL_DISCLOSURE WHERE TRAVEL_DISCLOSURE_ID = AV_MODULE_ITEM_KEY;
    ELSEIF AV_MODULE_CODE = 23 THEN
        SELECT HOME_UNIT INTO LS_LEAD_UNIT_NUMBER FROM OPA_DISCLOSURE WHERE OPA_DISCLOSURE_ID = AV_MODULE_ITEM_KEY;
    END IF;

    SET LS_PARENT_UNIT_NUMBER = LS_LEAD_UNIT_NUMBER;
    
    -- SELECT LS_PARENT_UNIT_NUMBER;
 -- SELECT  RULE_FAILED;
    -- Start rule evaluation loop
    outer_loop: WHILE LS_PARENT_UNIT_NUMBER IS NOT NULL DO
        SET DONE1 = FALSE;
        OPEN RULE_CURSOR;

        RULE_CURSOR_LOOP: LOOP
        
            FETCH RULE_CURSOR INTO LI_RULE_ID, LS_RULE_TYPE, LS_RULE_EXPRESSION, LS_USER_MESSAGE;
            IF DONE1 THEN
                LEAVE RULE_CURSOR_LOOP;
            END IF;
           
            CALL RULE_EVALUATE_EXPRESSION(
                AV_MODULE_CODE,
                AV_SUBMODULE_CODE,
                AV_MODULE_ITEM_KEY,
                LI_RULE_ID,
                LS_RULE_EXPRESSION,
                AV_UPDATE_USER,
                AV_LOGGIN_PERSON_ID,
                AV_SUB_MODULE_ITEM_KEY,
                @RESULT_EXP
            );

            SET LS_RESULT = @RESULT_EXP;

            IF IFNULL(LS_RESULT,'X') != 'TRUE'  THEN
                SET RULE_FAILED = 1;
                CLOSE RULE_CURSOR;
                LEAVE outer_loop;
			ELSE  SET RULE_FAILED = 0;
            END IF;
        END LOOP;

        CLOSE RULE_CURSOR;

        -- Traverse up the unit hierarchy
        SELECT COUNT(PARENT_UNIT_NUMBER) INTO LI_COUNT 
        FROM UNIT WHERE UNIT_NUMBER = LS_PARENT_UNIT_NUMBER;

        IF LI_COUNT = 0 THEN
            SET LS_PARENT_UNIT_NUMBER = NULL;
        ELSE
            SELECT PARENT_UNIT_NUMBER INTO LS_PARENT_UNIT_NUMBER 
            FROM UNIT WHERE UNIT_NUMBER = LS_PARENT_UNIT_NUMBER;
        END IF;
    END WHILE;
    -- Final result
    IF RULE_FAILED = 0 THEN
        SELECT 'TRUE' AS ROUTING_VALID;
    ELSE
        SELECT 'FALSE' AS ROUTING_VALID;
    END IF;

END
