CREATE PROCEDURE GET_WIDGET_DATA_IN_DETAIL(
AV_WIDGET VARCHAR(200),
AV_PERSON_ID VARCHAR(50),
AV_SEARCH VARCHAR(1000),
AV_UNIT_NUMBER VARCHAR(50),
AV_SPONSOR_CODE VARCHAR(1000),
AV_SPONSOR_GROUP_ID VARCHAR(1000),
AV_START_DATE VARCHAR(50),
AV_END_DATE VARCHAR(50),
AV_DESCENT_FLAG VARCHAR(1),
AV_PAGED INT(10),
AV_LIMIT INT(10)

)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE COL3 VARCHAR(20);
DECLARE LL_SPONSOR VARCHAR(4000);
DECLARE LS_LIMIT VARCHAR(4000);
DECLARE JOIN_CONDITION LONGTEXT;
DECLARE LS_UNIT_NUMBER_CONDITION LONGTEXT;
DECLARE LS_HOME_UNIT_CONDITION LONGTEXT;
DECLARE LS_LEAD_UNIT_CONDITION LONGTEXT;
DECLARE LS_FY_START_DATE VARCHAR(20);
DECLARE LS_FY_END_DATE VARCHAR(20);
DECLARE LS_FY_MONTH_CRITERIA VARCHAR(3);
DECLARE LS_STATUS VARCHAR(100);
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
/** 
LS_FY_MONTH_CRITERIA, LS_FY_START_DATE and LS_FY_END_DATE values are used for calculating FY in JHU.
**/
SET LS_FY_MONTH_CRITERIA ='4';
SET LS_FY_START_DATE="-04-01";
SET LS_FY_END_DATE="-03-31";

SET JOIN_CONDITION = '';
SET LS_HOME_UNIT_CONDITION = '';
SET LS_LEAD_UNIT_CONDITION = '';
SET LS_OFFSET = (AV_PAGED * AV_LIMIT);
IF AV_LIMIT = 0 THEN
    SET LS_OFFSET_CONDITION = '';
ELSE 
    SET LS_OFFSET_CONDITION = CONCAT(' LIMIT ', AV_LIMIT, ' OFFSET ', LS_OFFSET);
END IF;

IF AV_UNIT_NUMBER = '' THEN 
	SET AV_UNIT_NUMBER = NULL ;
END IF;
IF AV_UNIT_NUMBER IS NOT NULL AND AV_DESCENT_FLAG = 'Y' THEN 
	SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	SET LS_HOME_UNIT_CONDITION = CONCAT(' OR T1.HOME_UNIT_NUMBER IN (SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,')');
	SET LS_LEAD_UNIT_CONDITION = CONCAT(' OR T1.LEAD_UNIT_NUMBER IN (SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN WHERE UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,')');	
END IF;

IF AV_WIDGET = 'INPROGRESS_PROPOSALS' THEN
	IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;

	SET LS_DYN_SQL = CONCAT('
		WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))');
		SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'						
    SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T5.DISPLAY_NAME AS SPONSOR_NAME, ifNULL(T2.TOTAL_COST,0.00) as TOTAL_COST, T4.FULL_NAME AS PI,T7.DESCRIPTION 
	FROM EPS_PROPOSAL T1 
    LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID  AND
		CASE
			WHEN T2.IS_FINAL_BUDGET =''Y'' THEN T2.IS_FINAL_BUDGET =''Y''
			WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T2.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
			THEN T2.IS_LATEST_VERSION=''Y'' 
        END
	LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y''
	LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE  
	INNER JOIN EPS_PROPOSAL_STATUS T7 ON T1.STATUS_CODE = T7.STATUS_CODE
	WHERE T1.STATUS_CODE IN(''3'',''12'',''9'',''1'',''20'',''24'') AND T1.DOCUMENT_STATUS_CODE <> ''3'' 
     AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
    AND (T4.PERSON_ID = ''',AV_PERSON_ID,'''
    OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)) 
    OR EXISTS(SELECT (1) FROM  EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PROPOSAL_ID = T1.PROPOSAL_ID))',
    LS_OFFSET_CONDITION,
    ';');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;
ELSEIF AV_WIDGET = 'APPROVAL_INPROGRESS_PROPOSALS' THEN
IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;

	SET LS_DYN_SQL = CONCAT('
		WITH ACCESS_TMP AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))');

	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'						
    SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T5.DISPLAY_NAME AS SPONSOR_NAME, ifNULL(T2.TOTAL_COST,0.00) as TOTAL_COST,T4.FULL_NAME AS PI,T9.APPROVER_PERSON_NAME
	FROM EPS_PROPOSAL T1 
    LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID  AND 
		CASE
			WHEN T2.IS_FINAL_BUDGET =''Y'' THEN T2.IS_FINAL_BUDGET =''Y''
			WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T2.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
			THEN T2.IS_LATEST_VERSION=''Y'' 
        END
	LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y'' 
	LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE 
	INNER JOIN (SELECT GROUP_CONCAT(T8.APPROVER_PERSON_NAME SEPARATOR '' | '') AS APPROVER_PERSON_NAME, 
    T7.MODULE_ITEM_ID FROM WORKFLOW T7 INNER JOIN WORKFLOW_DETAIL T8 ON T8.WORKFLOW_ID= T7.WORKFLOW_ID
    WHERE IS_WORKFLOW_ACTIVE = ''Y'' AND APPROVAL_STATUS=''W'' and PRIMARY_APPROVER_FLAG=''Y'' AND MODULE_CODE=3
	 GROUP BY T7.WORKFLOW_ID
    ) T9 ON T9.MODULE_ITEM_ID = T1.PROPOSAL_ID WHERE T1.STATUS_CODE = 2 AND T1.DOCUMENT_STATUS_CODE <> ''3''
	AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
	AND (T4.PERSON_ID = ''',AV_PERSON_ID,'''
    OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)))', LS_OFFSET_CONDITION,';
');

SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;
ELSEIF AV_WIDGET = 'AWARDED_PROPOSALS' THEN
IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
SET LS_DYN_SQL = CONCAT('
		WITH ACCESS_TMP AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            )),
							UNIT_ADMIN_TMP AS (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE 
							PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)');
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'							
	SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T5.DISPLAY_NAME AS SPONSOR_NAME, T2.TOTAL_COST, T4.FULL_NAME AS PI
	FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID  AND 
		CASE
			WHEN T2.IS_FINAL_BUDGET =''Y'' THEN T2.IS_FINAL_BUDGET =''Y''
			WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T2.PROPOSAL_ID = S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
			THEN T2.IS_LATEST_VERSION=''Y'' 
        END
	LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y''
	LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE  
	WHERE T1.STATUS_CODE = 11 AND T1.DOCUMENT_STATUS_CODE <> ''3'' AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
    AND (T4.PERSON_ID = ''',AV_PERSON_ID,'''
	OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)) 
    OR EXISTS(SELECT (1) FROM  EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PROPOSAL_ID = T1.PROPOSAL_ID)
    OR (T1.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMIN_TMP)))', LS_OFFSET_CONDITION,';
    ');

SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;

ELSEIF AV_WIDGET = 'PROPOSAL_BY_SPONSOR_TYPE' THEN
	IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
	SET LS_DYN_SQL = CONCAT('
				WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							    ');
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'								
	SELECT T1.PROPOSAL_ID, T1.TITLE, T2.DISPLAY_NAME, T4.DESCRIPTION AS PROPOSAL_TYPE, T3.FULL_NAME AS PI, T1.SUBMISSION_DATE FROM EPS_PROPOSAL T1 
	INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID AND T3.PI_FLAG =''Y''
	INNER JOIN EPS_PROPOSAL_TYPE T4 ON T1.TYPE_CODE = T4.TYPE_CODE WHERE T1.DOCUMENT_STATUS_CODE <> ''3'' AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
	AND T2.SPONSOR_TYPE_CODE = ''',AV_SEARCH,''' AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL
	WHERE HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM  ACCESS_TMP) UNION
	SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = ''',AV_PERSON_ID,''' );
	');

	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;

ELSEIF AV_WIDGET IN ('AWARD_BY_SPONSOR_TYPE', 'ACTIVE_AWARDS_BY_SPONSOR_TYPE') THEN
		IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
	IF month(NOW()) >= LS_FY_MONTH_CRITERIA THEN 
		SET COL3 = YEAR(NOW());
	ELSE
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
	SET LS_DYN_SQL = CONCAT('
					WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 
                            ))
							');
							
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'
	SELECT DISTINCT T1.AWARD_NUMBER,T1.ACCOUNT_NUMBER,T1.TITLE, T2.DISPLAY_NAME AS SPONSOR_NAME, T1.AWARD_ID, T1.ANTICIPATED_TOTAL_AMOUNT, T1.PI_NAME FROM 
	award_master_dataset_rt T1
	LEFT JOIN SPONSOR T2  ON T1.SPONSOR_CODE = T2.SPONSOR_CODE
	WHERE T1.AWARD_SEQUENCE_STATUS = ''ACTIVE''
	-- AND (ifNULL (FUND_CODE , ''R_RESFUND'')) <> ''G_DESIGNAT''
    AND T1.AWARD_STATUS_CODE <> ''3''
	AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.LEAD_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_LEAD_UNIT_CONDITION,')
	AND T1.BEGIN_DATE BETWEEN CONCAT(''',COL3,''',''',LS_FY_START_DATE,''') AND CONCAT(''',COL3,'''+1,''',LS_FY_END_DATE,''')
	AND ( T1.AWARD_ID  IN 
		(SELECT T4.AWARD_ID FROM AWARD_PERSON_ROLES T4 
		INNER JOIN ROLE_RIGHTS T2 ON T4.ROLE_ID = T2.ROLE_ID
		INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
		WHERE T4.PERSON_ID = ''',AV_PERSON_ID,''' AND T3.RIGHT_NAME = ''VIEW_AWARD'')
		OR T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP))
			AND T1.SPONSOR_TYPE_CODE =''',AV_SEARCH,''';
	');

	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;
ELSEIF AV_WIDGET = 'INPROGRESS_PROPOSALS_BY_SPONSOR' THEN
				
	IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
	
	IF LOCATE(',',AV_SEARCH) = 0 THEN
		SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ',AV_PERSON_ID,'
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ',AV_PERSON_ID,'
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT T1.PROPOSAL_ID, T1.TITLE, T4.FULL_NAME AS PI, T1.TYPE_CODE, T5.DESCRIPTION AS PROPOSAL_TYPE, ifNULL(T6.TOTAL_COST,''0.00'')AS BUDGET, T1.SPONSOR_DEADLINE_DATE,T7.DISPLAY_NAME AS SPONSOR_NAME  FROM EPS_PROPOSAL T1 
			LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND  T4.PI_FLAG =''Y'' INNER JOIN EPS_PROPOSAL_TYPE T5 ON T1.TYPE_CODE=T5.TYPE_CODE 
			LEFT OUTER JOIN BUDGET_HEADER T6 ON T1.PROPOSAL_ID = T6.PROPOSAL_ID  AND
            CASE
            WHEN T6.IS_FINAL_BUDGET =''Y'' THEN T6.IS_FINAL_BUDGET =''Y''
            WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T6.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
            THEN T6.IS_LATEST_VERSION=''Y'' 
            END 
            INNER JOIN SPONSOR T7 ON T1.SPONSOR_CODE = T7.SPONSOR_CODE
			WHERE T1.STATUS_CODE IN (1,3,12) AND T1.DOCUMENT_STATUS_CODE <> ''3'' AND T1.SPONSOR_CODE IN (',AV_SEARCH,')
			AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
			AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = ''',AV_PERSON_ID, ''' UNION 
			SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID, ''' UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID
			WHERE S1.IS_WORKFLOW_ACTIVE = ''Y'' AND S2.APPROVER_PERSON_ID = ''',AV_PERSON_ID, '''	AND S1.MODULE_CODE = 3)');
	ELSE
		SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ',AV_PERSON_ID,'
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ',AV_PERSON_ID,'
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT T1.PROPOSAL_ID, T1.TITLE, T4.FULL_NAME AS PI, T1.TYPE_CODE, T5.DESCRIPTION AS PROPOSAL_TYPE, ifNULL(T6.TOTAL_COST,''0.00'')AS BUDGET, T1.SPONSOR_DEADLINE_DATE, T7.DISPLAY_NAME AS SPONSOR_NAME  FROM EPS_PROPOSAL T1 
			LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND  T4.PI_FLAG =''Y'' INNER JOIN EPS_PROPOSAL_TYPE T5 ON T1.TYPE_CODE=T5.TYPE_CODE 
			LEFT OUTER JOIN BUDGET_HEADER T6 ON T1.PROPOSAL_ID = T6.PROPOSAL_ID  AND 
            CASE
            WHEN T6.IS_FINAL_BUDGET =''Y'' THEN T6.IS_FINAL_BUDGET =''Y''
            WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T6.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
            THEN T6.IS_LATEST_VERSION=''Y'' 
            END 
            LEFT OUTER JOIN SPONSOR T7 ON T1.SPONSOR_CODE = T7.SPONSOR_CODE
			WHERE T1.STATUS_CODE IN (1,3,12) AND T1.DOCUMENT_STATUS_CODE <> ''3'' 
			AND (T1.SPONSOR_CODE NOT IN (',AV_SEARCH,') OR T1.SPONSOR_CODE IS NULL)
			AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')			
			AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL WHERE HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)UNION SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = ''',AV_PERSON_ID, ''' UNION 
			SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID, ''' UNION SELECT S1.MODULE_ITEM_ID FROM WORKFLOW S1 INNER JOIN WORKFLOW_DETAIL S2 ON S1.WORKFLOW_ID = S2.WORKFLOW_ID
			WHERE S1.IS_WORKFLOW_ACTIVE = ''Y'' AND S2.APPROVER_PERSON_ID = ''',AV_PERSON_ID, '''	AND S1.MODULE_CODE = 3)');            
    END IF;
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STATEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STATEMENT;

ELSEIF AV_WIDGET = 'AWARDED_PROPOSALS_BY_SPONSOR' THEN
	IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
	ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
	SET LS_DYN_SQL = CONCAT('
				WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID =  ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID =  ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
	');
	SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'	
	SELECT T1.PROPOSAL_NUMBER, T1.TITLE, T4.FULL_NAME AS PI, T1.ACTIVITY_TYPE_CODE, T5.DESCRIPTION AS ACTIVITY_TYPE, T1.TYPE_CODE as PROPOSAL_TYPE_CODE,T6.DESCRIPTION AS PROPOSAL_TYPE, 
	T1.SPONSOR_CODE, T1.PROPOSAL_ID FROM PROPOSAL T1 INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PROP_PERSON_ROLE_ID = 3 
	INNER JOIN ACTIVITY_TYPE T5 ON T1.ACTIVITY_TYPE_CODE = T5.ACTIVITY_TYPE_CODE INNER JOIN PROPOSAL_TYPE T6 ON T1.TYPE_CODE = T6.TYPE_CODE WHERE  T1.STATUS_CODE = 2
	AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')	
	AND T1.SPONSOR_CODE = ''',AV_SEARCH,''' AND T1.PROPOSAL_NUMBER IN (SELECT PROPOSAL_NUMBER FROM PROPOSAL WHERE HOME_UNIT_NUMBER IN  
	(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) UNION SELECT PROPOSAL_ID FROM
	PROPOSAL_PERSONS WHERE PERSON_ID =  ''',AV_PERSON_ID,''');
	');
		SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;
ELSEIF AV_WIDGET = 'AWARD_BY_SPONSOR' THEN

   	SET LS_DYN_SQL = CONCAT('SELECT group_CONCAT('''',SPONSOR_CODE,'''') INTO @SPONSOR_LIST FROM(
	SELECT SPONSOR_CODE FROM SPONSOR WHERE SPONSOR_GROUP IN (',AV_SEARCH,')
	UNION 
	SELECT SPONSOR_CODE FROM SPONSOR WHERE SPONSOR_GROUP IS NULL AND SPONSOR_CODE IN (',AV_SEARCH,')) AS TAB');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;
	SET LL_SPONSOR = @SPONSOR_LIST;
    
	IF AV_UNIT_NUMBER IS NULL THEN
					SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
			ELSE
					SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;

	IF LOCATE(',',AV_SEARCH) = 0 THEN
				SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.AWARD_NUMBER,T1.ACCOUNT_NUMBER,TITLE, T2.DISPLAY_NAME AS SPONSOR_NAME, T1.AWARD_ID, T1.ANTICIPATED_TOTAL_AMOUNT FROM 
        award_master_dataset_rt T1
        LEFT JOIN SPONSOR T2  ON T1.SPONSOR_CODE = T2.SPONSOR_CODE
        WHERE T1.AWARD_SEQUENCE_STATUS = ''ACTIVE''
		AND T1.AWARD_STATUS_CODE <> ''3''
        AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.LEAD_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_LEAD_UNIT_CONDITION,')
        AND (ifNULL (FUND_CODE , ''R_RESFUND'')) <> ''G_DESIGNAT''
		AND T1.FINAL_EXPIRATION_DATE >= CURDATE() 
        AND (T1.AWARD_NUMBER  IN 
					(SELECT T1.AWARD_NUMBER FROM AWARD_PERSON_ROLES T1 
					INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
					INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
					WHERE T1.PERSON_ID = ''',AV_PERSON_ID, '''AND T3.RIGHT_NAME = ''VIEW_AWARD'')
        OR T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP))
        AND T1.SPONSOR_CODE IN (',LL_SPONSOR,')');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
	ELSE
				SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.AWARD_NUMBER,T1.ACCOUNT_NUMBER,TITLE, T2.DISPLAY_NAME AS SPONSOR_NAME, T1.AWARD_ID, T1.ANTICIPATED_TOTAL_AMOUNT FROM 
        award_master_dataset_rt T1
        LEFT JOIN SPONSOR T2  ON T1.SPONSOR_CODE = T2.SPONSOR_CODE
        WHERE T1.AWARD_SEQUENCE_STATUS = ''ACTIVE''
		AND T1.AWARD_STATUS_CODE <> ''3''
        AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.LEAD_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_LEAD_UNIT_CONDITION,')
        AND (ifNULL (FUND_CODE , ''R_RESFUND'')) <> ''G_DESIGNAT''
		AND T1.BEGIN_DATE BETWEEN ''',COL3,'-04-01'' AND ''', COL3+1,'-03-31'' 
        AND (T1.AWARD_NUMBER  IN 
					(SELECT T1.AWARD_NUMBER FROM AWARD_PERSON_ROLES T1 
					INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
					INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
					WHERE T1.PERSON_ID = ''',AV_PERSON_ID, '''AND T3.RIGHT_NAME = ''VIEW_AWARD'')
        OR T1.LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP))
        AND T1.SPONSOR_CODE NOT IN (',LL_SPONSOR,')');
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
    END IF;

ELSEIF AV_WIDGET = 'AWARD_BY_UTALIZATION' THEN

	IF AV_SEARCH = 'Low Utilisation' THEN
						WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('VIEW_AWARD') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('VIEW_AWARD') 
                            ))
		SELECT DISTINCT AWARD_NUMBER , TITLE, UTILIZATION_RATE_WO_IRC
			FROM award_master_dataset_rt 
				WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
                AND AWARD_STATUS_CODE = '1'
				AND (
			AWARD_ID  IN 
			(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1 
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
				INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
				WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
				OR LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
				)
		AND FINAL_EXPIRATION_DATE >= utc_timestamp()
		AND (UTILIZATION_RATE_WO_IRC + 10) < ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100
		ORDER BY FINAL_EXPIRATION_DATE ASC;

	ELSEIF AV_SEARCH = 'High Utilisation' THEN
						WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('VIEW_AWARD') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('VIEW_AWARD') 
                            ))
    	SELECT DISTINCT AWARD_NUMBER , TITLE, UTILIZATION_RATE_WO_IRC
			FROM award_master_dataset_rt 
				WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
                AND AWARD_STATUS_CODE = '1'
				AND (
			AWARD_ID  IN 
			(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1 
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
				INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
				WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
				OR LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
				)
		AND FINAL_EXPIRATION_DATE >= utc_timestamp()
		AND (UTILIZATION_RATE_WO_IRC - 10) > ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1)) *100      
		ORDER BY FINAL_EXPIRATION_DATE ASC;

	ELSEIF AV_SEARCH = 'Acceptable Utilisation' THEN
						WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('VIEW_AWARD') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('VIEW_AWARD') 
                            ))
		SELECT DISTINCT AWARD_NUMBER , TITLE, UTILIZATION_RATE_WO_IRC
			FROM award_master_dataset_rt 
				WHERE AWARD_SEQUENCE_STATUS = 'ACTIVE'
                AND AWARD_STATUS_CODE = '1'
				AND (
			AWARD_ID  IN 
			(SELECT T1.AWARD_ID FROM AWARD_PERSON_ROLES T1 
			INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
				INNER JOIN RIGHTS T3 ON T3.RIGHT_ID = T2.RIGHT_ID
				WHERE T1.PERSON_ID = AV_PERSON_ID AND T3.RIGHT_NAME = 'VIEW_AWARD')
				OR LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
				)
		AND FINAL_EXPIRATION_DATE >= utc_timestamp()
		AND ((DATEDIFF(UTC_TIMESTAMP(),BEGIN_DATE)+1)/(DATEDIFF(FINAL_EXPIRATION_DATE,BEGIN_DATE)+1))*100 BETWEEN (UTILIZATION_RATE_WO_IRC - 10) AND (UTILIZATION_RATE_WO_IRC + 10)      
		ORDER BY FINAL_EXPIRATION_DATE ASC;
	END IF;

ELSEIF AV_WIDGET = 'PENDING_PROPOSAL_BY_SPONSOR_TYPE' THEN
			WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL') 
                            ))	   
	SELECT T1.PROPOSAL_ID, T1.TITLE, T2.DISPLAY_NAME AS SPONSOR_NAME, IFNULL(T4.TOTAL_COST, '0.00'), T3.FULL_NAME  FROM EPS_PROPOSAL T1 
	LEFT JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID AND T3.PI_FLAG ='Y'
	LEFT OUTER JOIN (SELECT IS_LATEST_VERSION ,TOTAL_COST, PROPOSAL_ID FROM BUDGET_HEADER WHERE IS_LATEST_VERSION = 'Y' GROUP BY BUDGET_HEADER_ID) T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID 
    WHERE T1.STATUS_CODE = 41 AND T1.DOCUMENT_STATUS_CODE <> '3' AND T2.SPONSOR_TYPE_CODE = AV_SEARCH  AND  T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM EPS_PROPOSAL
	WHERE HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) UNION
	SELECT PROPOSAL_ID FROM EPS_PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID);
			
ELSEIF AV_WIDGET = 'PENDING_PROPOSALS_OF_SPONSORS' THEN
	
    IF AV_UNIT_NUMBER IS NULL THEN
	SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
		ELSE
	SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
    
	IF AV_SPONSOR_CODE ='' THEN
		SET LL_SPONSOR=CONCAT((with recursive cte (SPONSOR_GROUP_ID, SPONSOR_GROUP_NAME, SPONSOR_ORIGINATING_GROUP_ID, SPONSOR_ROOT_GROUP_ID, SPONSOR_CODE) as
        (SELECT SPONSOR_GROUP_ID, SPONSOR_GROUP_NAME, SPONSOR_ORIGINATING_GROUP_ID, SPONSOR_ROOT_GROUP_ID, SPONSOR_CODE FROM sponsor_hierarchy where SPONSOR_GROUP_ID = AV_SPONSOR_GROUP_ID UNION ALL SELECT T6.SPONSOR_GROUP_ID, T6.SPONSOR_GROUP_NAME, T6.SPONSOR_ORIGINATING_GROUP_ID, T6.SPONSOR_ROOT_GROUP_ID, T6.SPONSOR_CODE  FROM sponsor_hierarchy T6 INNER JOIN cte on T6.SPONSOR_ORIGINATING_GROUP_ID = cte.SPONSOR_GROUP_ID ) SELECT group_CONCAT('''',SPONSOR_CODE,'''')  FROM cte where SPONSOR_CODE IS NOT NULL)) ;

	ELSEIF AV_SPONSOR_GROUP_ID ='' THEN	
		SELECT GROUP_CONCAT('''',SPONSOR_CODE,'''') INTO LL_SPONSOR FROM SPONSOR WHERE FIND_IN_SET(SPONSOR_CODE,AV_SPONSOR_CODE);
	  
    END IF; 

   	SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'',''CREATE_AWARD'',''MODIFY_INST_PROPOSAL'',''VIEW_INST_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'',''CREATE_AWARD'',''MODIFY_INST_PROPOSAL'',''VIEW_INST_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T3.DISPLAY_NAME, T4.FULL_NAME, COALESCE(T2.TOTAL_COST,0.00) as TOTAL_COST,T1.PROPOSAL_NUMBER FROM  PROPOSAL T1
		LEFT JOIN IP_BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.IS_LATEST_VERSION  = ''Y''
		LEFT JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T1.SPONSOR_CODE
        LEFT OUTER JOIN PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y''
        WHERE T1.STATUS_CODE = 1 AND T1.PROPOSAL_SEQUENCE_STATUS = ''ACTIVE'' 
        AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
		AND T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM PROPOSAL_PERSONS WHERE PERSON_ID = ''',AV_PERSON_ID,'''
		UNION SELECT PROPOSAL_ID FROM PROPOSAL WHERE T1.HOME_UNIT_NUMBER IN 
		(SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
		) AND T1.SPONSOR_CODE IN (',LL_SPONSOR,')');
				
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT ;
  
ELSEIF AV_WIDGET = 'PENDING_AWARDS_OF_SPONSORS' THEN

	IF AV_UNIT_NUMBER IS NULL THEN
		SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
    ELSE
    	SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
	
	IF AV_SPONSOR_CODE ='' THEN
		SET LL_SPONSOR = CONCAT((with recursive cte (SPONSOR_GROUP_ID, SPONSOR_GROUP_NAME, SPONSOR_ORIGINATING_GROUP_ID, SPONSOR_ROOT_GROUP_ID, SPONSOR_CODE) as
        (SELECT SPONSOR_GROUP_ID, SPONSOR_GROUP_NAME, SPONSOR_ORIGINATING_GROUP_ID, SPONSOR_ROOT_GROUP_ID, SPONSOR_CODE FROM sponsor_hierarchy where SPONSOR_GROUP_ID = AV_SPONSOR_GROUP_ID UNION ALL SELECT T6.SPONSOR_GROUP_ID, T6.SPONSOR_GROUP_NAME, T6.SPONSOR_ORIGINATING_GROUP_ID, T6.SPONSOR_ROOT_GROUP_ID, T6.SPONSOR_CODE  FROM sponsor_hierarchy T6 INNER JOIN cte on T6.SPONSOR_ORIGINATING_GROUP_ID = cte.SPONSOR_GROUP_ID ) SELECT group_CONCAT('''',SPONSOR_CODE,'''')  FROM cte where SPONSOR_CODE IS NOT NULL)) ;
	
   	ELSEIF AV_SPONSOR_GROUP_ID ='' THEN
		SELECT GROUP_CONCAT('''',SPONSOR_CODE,'''') INTO LL_SPONSOR FROM SPONSOR WHERE FIND_IN_SET(SPONSOR_CODE,AV_SPONSOR_CODE);
	
    END IF;

       	SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_AWARD'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.AWARD_ID, T1.TITLE, T3.DISPLAY_NAME AS SPONSOR_NAME, T4.FULL_NAME, COALESCE(T2.TOTAL_COST,0.00) AS TOTAL_AMOUNT,T1.AWARD_NUMBER FROM AWARD T1 
		LEFT JOIN AWARD_BUDGET_HEADER  T2 ON T1.AWARD_ID = T2.AWARD_ID AND IS_LATEST_VERSION = ''Y''
        LEFT JOIN AWARD_PERSONS T4 ON T1.AWARD_ID = T4.AWARD_ID AND T4.PERSON_ROLE_ID=3
        INNER JOIN SPONSOR T3 ON T3.SPONSOR_CODE = T1.SPONSOR_CODE
        WHERE T1.AWARD_SEQUENCE_STATUS = ''ACTIVE'' 
        AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.LEAD_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_LEAD_UNIT_CONDITION,')
		AND T1.AWARD_ID IN (SELECT AWARD_ID FROM AWARD_PERSONS WHERE AWARD_PERSON_ID = ''',AV_PERSON_ID,''' UNION SELECT AWARD_ID FROM AWARD WHERE LEAD_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) UNION
		SELECT AWARD_ID FROM AWARD_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''')
        AND T1.SPONSOR_CODE IN (',LL_SPONSOR,')');
					
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
            
ELSEIF AV_WIDGET = 'APPROVAL_INPROGRESS_PROPOSALS_COUNT' THEN
  
    IF AV_UNIT_NUMBER IS NULL THEN 
	    SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
    ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
            
    IF AV_START_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP < ''',AV_END_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_END_DATE,'','%','''))');
	ELSEIF AV_END_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP > ''',AV_START_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%','''))');
	ELSE 
		IF AV_START_DATE = AV_END_DATE THEN 
			SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%',''')');
		ELSE 
			SET LS_LIMIT = CONCAT('AND ((T1.CREATE_TIMESTAMP < ''',AV_END_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_END_DATE,'','%',''') )AND (T1.CREATE_TIMESTAMP > ''',AV_START_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%',''')))');
		END IF;
	END IF;
                  
   		SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T5.DISPLAY_NAME AS SPONSOR_NAME,ifNULL(T2.TOTAL_COST,0.00) as TOTAL_COST,T4.FULL_NAME AS PI,T9.APPROVER_PERSON_NAME
			FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID  AND 
			CASE
				WHEN T2.IS_FINAL_BUDGET =''Y'' THEN T2.IS_FINAL_BUDGET =''Y''
				WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T2.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
				THEN T2.IS_LATEST_VERSION=''Y'' 
            END
			LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y'' 
			LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE 
			INNER JOIN (SELECT GROUP_CONCAT(T8.APPROVER_PERSON_NAME SEPARATOR '' | '') AS APPROVER_PERSON_NAME, 
            T7.MODULE_ITEM_ID FROM WORKFLOW T7 INNER JOIN WORKFLOW_DETAIL T8 ON T8.WORKFLOW_ID= T7.WORKFLOW_ID
            WHERE IS_WORKFLOW_ACTIVE = ''Y'' AND APPROVAL_STATUS=''W'' and PRIMARY_APPROVER_FLAG=''Y'' AND MODULE_CODE=3 GROUP BY T7.WORKFLOW_ID
            ) T9 ON T9.MODULE_ITEM_ID = T1.PROPOSAL_ID 
            WHERE T1.STATUS_CODE = 2 AND T1.DOCUMENT_STATUS_CODE <> ''3'' 
            AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')',LS_LIMIT,'
			AND (T4.PERSON_ID = ''',AV_PERSON_ID,'''
            OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)))');

    SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
                 
ELSEIF AV_WIDGET = 'INPROGRESS_PROPOSALS_COUNT' THEN

    IF AV_UNIT_NUMBER IS NULL THEN 
	    SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
    ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
            
    IF AV_START_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP < ''',AV_END_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_END_DATE,'','%','''))');
	ELSEIF AV_END_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP > ''',AV_START_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%','''))');
	ELSE 
		IF AV_START_DATE = AV_END_DATE THEN 
            SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%',''')');
		ELSE 
			SET LS_LIMIT = CONCAT('AND ((T1.CREATE_TIMESTAMP < ''',AV_END_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_END_DATE,'','%',''') )AND (T1.CREATE_TIMESTAMP > ''',AV_START_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%',''')))');
		END IF;
	END IF;
            
      		SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T5.DISPLAY_NAME AS SPONSOR_NAME, ifNULL(T2.TOTAL_COST,0.00) as TOTAL_COST, T4.FULL_NAME AS PI,T7.DESCRIPTION 
		FROM EPS_PROPOSAL T1 
        LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID  AND
		CASE
			WHEN T2.IS_FINAL_BUDGET =''Y'' THEN T2.IS_FINAL_BUDGET =''Y''
			WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T2.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
			THEN T2.IS_LATEST_VERSION=''Y'' 
        END
		LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y'' 
		LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE  
		INNER JOIN EPS_PROPOSAL_STATUS T7 ON T1.STATUS_CODE = T7.STATUS_CODE
		WHERE T1.STATUS_CODE IN(''3'',''12'',''9'',''1'',''20'',''24'') AND T1.DOCUMENT_STATUS_CODE <> ''3'' 
        AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')',LS_LIMIT,'
        AND (T4.PERSON_ID = ''',AV_PERSON_ID,'''
        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)) 
        OR EXISTS(SELECT (1) FROM  EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PROPOSAL_ID = T1.PROPOSAL_ID))');

        SET @QUERY_STATEMENT = LS_DYN_SQL;
		PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
		EXECUTE EXECUTABLE_STAEMENT;  
            
ELSEIF AV_WIDGET = 'AWARDED_PROPOSALS_COUNT' THEN

    IF AV_UNIT_NUMBER IS NULL THEN 
	    SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
    ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
            
    IF AV_START_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP < ''',AV_END_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_END_DATE,'','%','''))');
	ELSEIF AV_END_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP > ''',AV_START_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%','''))');
	ELSE 
		IF AV_START_DATE = AV_END_DATE THEN 
            SET LS_LIMIT = CONCAT('AND (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%',''')');
		ELSE 
			SET LS_LIMIT = CONCAT('AND ((T1.CREATE_TIMESTAMP < ''',AV_END_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_END_DATE,'','%',''') )AND (T1.CREATE_TIMESTAMP > ''',AV_START_DATE,''' OR (T1.CREATE_TIMESTAMP LIKE ','''','%' ,'',AV_START_DATE,'','%',''')))');
		END IF;
	END IF;
            
	      		SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'SELECT DISTINCT T1.PROPOSAL_ID, T1.TITLE, T5.DISPLAY_NAME AS SPONSOR_NAME, T2.TOTAL_COST, T4.FULL_NAME AS PI
		FROM EPS_PROPOSAL T1 LEFT OUTER JOIN BUDGET_HEADER T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID  AND 
			CASE
				WHEN T2.IS_FINAL_BUDGET =''Y'' THEN T2.IS_FINAL_BUDGET =''Y''
				WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T2.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
				THEN T2.IS_LATEST_VERSION=''Y'' 
            END
			LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG =''Y'' 
			LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE  
			WHERE T1.STATUS_CODE = 11 AND T1.DOCUMENT_STATUS_CODE <> ''3'' 
            AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')',LS_LIMIT,' AND (
            T4.PERSON_ID = ''',AV_PERSON_ID,'''
            OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)) 
            OR EXISTS(SELECT (1) FROM  EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PROPOSAL_ID = T1.PROPOSAL_ID )
            OR (T1.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3)))');

        SET @QUERY_STATEMENT = LS_DYN_SQL;
		PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
		EXECUTE EXECUTABLE_STAEMENT;

ELSEIF AV_WIDGET = 'PROPOSAL_RESEARCH_SUMMARY_BY_DEADLINE_DATE' OR AV_WIDGET = 'PROPOSAL_APPROVAL_IN_PROGRESS_BY_DEADLINE_DATE' 
OR AV_WIDGET = 'PROPOSAL_INPROGRESS_BY_DEADLINE_DATE' OR AV_WIDGET = 'PROPOSAL_SUBMITTED_BY_DEADLINE_DATE' THEN

IF AV_UNIT_NUMBER IS NULL THEN 
	    SET LS_UNIT_NUMBER_CONDITION = '''NULL''';
    ELSE
		SET LS_UNIT_NUMBER_CONDITION = CONCAT("'",AV_UNIT_NUMBER,"'");
	END IF;
            
    IF AV_START_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.SPONSOR_DEADLINE_DATE < ''',AV_END_DATE,''' OR (T1.SPONSOR_DEADLINE_DATE LIKE ','''','%' ,'',AV_END_DATE,'','%','''))');
	ELSEIF AV_END_DATE ='' THEN 
        SET LS_LIMIT = CONCAT('AND (T1.SPONSOR_DEADLINE_DATE > ''',AV_START_DATE,''' OR (T1.SPONSOR_DEADLINE_DATE LIKE ','''','%' ,'',AV_START_DATE,'','%','''))');
	ELSE 
		IF AV_START_DATE = AV_END_DATE THEN 
			SET LS_LIMIT = CONCAT('AND (T1.SPONSOR_DEADLINE_DATE LIKE ','''','%' ,'',AV_START_DATE,'','%',''')');
		ELSE 
			SET LS_LIMIT = CONCAT('AND ((T1.SPONSOR_DEADLINE_DATE < ''',AV_END_DATE,''' OR (T1.SPONSOR_DEADLINE_DATE LIKE ','''','%' ,'',AV_END_DATE,'','%',''') )AND (T1.SPONSOR_DEADLINE_DATE > ''',AV_START_DATE,''' OR (T1.SPONSOR_DEADLINE_DATE LIKE ','''','%' ,'',AV_START_DATE,'','%',''')))');
		END IF;
	END IF;
  
  IF AV_WIDGET = 'PROPOSAL_RESEARCH_SUMMARY_BY_DEADLINE_DATE' THEN
         SET LS_STATUS = CONCAT(' T1.STATUS_CODE IN(2, 3, 11, 12, 9, 1, 20, 24) AND ');
  ELSEIF AV_WIDGET = 'PROPOSAL_APPROVAL_IN_PROGRESS_BY_DEADLINE_DATE' THEN 
         SET LS_STATUS = CONCAT('T1.STATUS_CODE = 2 AND ');
  ELSEIF AV_WIDGET = 'PROPOSAL_INPROGRESS_BY_DEADLINE_DATE' THEN 
          SET LS_STATUS = CONCAT('T1.STATUS_CODE IN(3, 12, 9, 1, 20, 24) AND ');
   ELSE 
             SET LS_STATUS = CONCAT('T1.STATUS_CODE = 11 AND ');
   END IF;
	SET JOIN_CONDITION =  CONCAT(JOIN_CONDITION,' INNER JOIN EPS_PROPOSAL_TYPE T3 ON T1.TYPE_CODE = T3.TYPE_CODE
		LEFT OUTER JOIN EPS_PROPOSAL_PERSONS T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID AND T4.PI_FLAG = ''Y'' 
		LEFT OUTER JOIN SPONSOR T5 ON T1.SPONSOR_CODE = T5.SPONSOR_CODE 
		INNER JOIN EPS_PROPOSAL_STATUS T6 ON T1.STATUS_CODE=T6.STATUS_CODE
		LEFT OUTER JOIN SPONSOR T7 ON T1.PRIME_SPONSOR_CODE = T7.SPONSOR_CODE 
		INNER JOIN UNIT T8 ON T1.HOME_UNIT_NUMBER = T8.UNIT_NUMBER
		INNER JOIN ACTIVITY_TYPE T9 ON T1.ACTIVITY_TYPE_CODE = T9.ACTIVITY_TYPE_CODE
		LEFT OUTER JOIN AWARD_TYPE T10 ON T1.AWARD_TYPE_CODE = T10.AWARD_TYPE_CODE
		LEFT OUTER JOIN BUDGET_HEADER T11 ON T1.PROPOSAL_ID = T11.PROPOSAL_ID  AND 
			CASE
				WHEN T11.IS_FINAL_BUDGET =''Y'' THEN T11.IS_FINAL_BUDGET =''Y''
				WHEN ((SELECT COUNT(*) FROM BUDGET_HEADER S1 WHERE  T11.PROPOSAL_ID=S1.PROPOSAL_ID AND S1.IS_FINAL_BUDGET=''Y'') = 0)
				THEN T11.IS_LATEST_VERSION=''Y'' 
            END
		LEFT OUTER JOIN CUSTOM_DATA T15 ON T15.MODULE_ITEM_KEY = CAST(T1.PROPOSAL_ID AS CHAR) AND T15.MODULE_ITEM_CODE = 3
				AND T15.CUSTOM_DATA_ELEMENTS_ID= (SELECT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENTS S1 WHERE S1.CUSTOM_ELEMENT_NAME = ''CONTACT_PERSON'' 
				AND S1.COLUMN_VERSION_NUMBER = (SELECT MAX(COLUMN_VERSION_NUMBER) FROM CUSTOM_DATA_ELEMENTS 
				S2 WHERE S1.CUSTOM_ELEMENT_NAME = S2.CUSTOM_ELEMENT_NAME))
        ');

	    SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_PERSON_ID,'''
							AND RIGHT_NAME IN (''MODIFY_PROPOSAL'',''VIEW_PROPOSAL'',''VIEW_ANY_PROPOSAL'') 
                            ))
							');
							
        SET LS_DYN_SQL = CONCAT(LS_DYN_SQL,'(SELECT DISTINCT T1.PROPOSAL_ID,T3.DESCRIPTION AS PROPOSAL_TYPE,T6.DESCRIPTION AS PROPOSAL_STATUS, T1.TITLE,
		T8.UNIT_NUMBER,T8.DISPLAY_NAME AS LEAD_UNIT,T4.FULL_NAME AS PI,T1.SPONSOR_DEADLINE_DATE, T5.DISPLAY_NAME,T7.DISPLAY_NAME AS PRIME_SPONSOR_NAME,T9.DESCRIPTION AS ACTIVITY_TYPE,
		T10.DESCRIPTION AS ANTICIPATED_AWARD_TYPE,T1.PROGRAM_ANNOUNCEMENT_NUMBER,T15.VALUE AS PROPOSAL_CONTACT,T8.ACRONYM AS UNIT_ABBREVIATION 
        FROM EPS_PROPOSAL T1 ',JOIN_CONDITION,' 
		WHERE ', LS_STATUS ,' T1.DOCUMENT_STATUS_CODE <> ''3'' ',LS_LIMIT,'
        AND (',LS_UNIT_NUMBER_CONDITION,' = ''NULL'' OR T1.HOME_UNIT_NUMBER = ',LS_UNIT_NUMBER_CONDITION,LS_HOME_UNIT_CONDITION,')
		AND (EXISTS(SELECT (1) FROM EPS_PROPOSAL_PERSONS  WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PROPOSAL_ID = T1.PROPOSAL_ID AND PROP_PERSON_ROLE_ID =3) 
		OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)) 
		OR EXISTS(SELECT (1) FROM  EPS_PROPOSAL_PERSON_ROLES WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND PROPOSAL_ID = T1.PROPOSAL_ID)
        or( T1.HOME_UNIT_NUMBER IN (SELECT UNIT_NUMBER FROM UNIT_ADMINISTRATOR WHERE PERSON_ID = ''',AV_PERSON_ID,''' AND UNIT_ADMINISTRATOR_TYPE_CODE = 3))))');
     
	 SET @QUERY_STATEMENT = LS_DYN_SQL;
	 PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	 EXECUTE EXECUTABLE_STAEMENT;

ELSEIF AV_WIDGET = 'PENDING_INSTITUTE_PROPOSAL' THEN

WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))	
	SELECT T1.PROPOSAL_NUMBER,T1.TITLE,T2.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT JOIN PROPOSAL_PERSONS T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.PROP_PERSON_ROLE_ID = 3 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	LEFT JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T2.PERSON_ID = AV_PERSON_ID AND  T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) 
	        OR (T1.HOME_UNIT_NUMBER = ( SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP WHERE UNIT_NUMBER = AV_UNIT_NUMBER)
	     ))   
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.STATUS_CODE =1;

ELSEIF AV_WIDGET = 'NOT_FUNDED_INSTITUTE_PROPOSAL' THEN

WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT T1.PROPOSAL_NUMBER,T1.TITLE,T2.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT JOIN PROPOSAL_PERSONS T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.PROP_PERSON_ROLE_ID = 3 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	LEFT JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T2.PERSON_ID = AV_PERSON_ID AND  T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) 
	        OR (T1.HOME_UNIT_NUMBER = (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP WHERE UNIT_NUMBER =AV_UNIT_NUMBER)
	     )) 
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.STATUS_CODE =8;

ELSEIF AV_WIDGET = 'FUNDED_INSTITUTE_PROPOSAL' THEN

WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT T1.PROPOSAL_NUMBER,T1.TITLE,T2.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT JOIN PROPOSAL_PERSONS T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.PROP_PERSON_ROLE_ID = 3 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	LEFT JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T2.PERSON_ID = AV_PERSON_ID AND  T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) 
	        OR (T1.HOME_UNIT_NUMBER = (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP WHERE UNIT_NUMBER =AV_UNIT_NUMBER)
	     )) 
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.STATUS_CODE =2;

ELSEIF AV_WIDGET = 'WITHDRAWN_INSTITUTE_PROPOSAL' THEN

WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT T1.PROPOSAL_NUMBER,T1.TITLE,T2.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT JOIN PROPOSAL_PERSONS T2 ON T1.PROPOSAL_ID = T2.PROPOSAL_ID AND T2.PROP_PERSON_ROLE_ID = 3 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	LEFT JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T2.PERSON_ID = AV_PERSON_ID AND  T1.HOME_UNIT_NUMBER = AV_UNIT_NUMBER) 
	        OR (T1.HOME_UNIT_NUMBER = (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP WHERE UNIT_NUMBER =AV_UNIT_NUMBER)
	     )) 
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.STATUS_CODE =5;

ELSEIF AV_WIDGET = 'PENDING_INSTITUTE_PROPOSAL_SPONSOR' THEN

    IF month(NOW()) >= LS_FY_MONTH_CRITERIA THEN 
		SET COL3 = YEAR(NOW());
    ELSE
        SET COL3 = YEAR(NOW()) - 1;
	END IF;

	SET LS_FY_START_DATE = CONCAT(COL3,LS_FY_START_DATE);
    SET LS_FY_END_DATE = CONCAT(COL3+1,LS_FY_END_DATE);
	WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT DISTINCT T1.PROPOSAL_NUMBER,T1.TITLE,T8.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT  JOIN PROPOSAL_PERSONS T8 ON T8.PROPOSAL_ID = T1.PROPOSAL_ID AND T8.PROP_PERSON_ROLE_ID = 3 AND T8.PI_FLAG = 'Y' 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	INNER JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T8.PERSON_ID = AV_PERSON_ID) 
	        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
	     ))   
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.SPONSOR_CODE = AV_SPONSOR_CODE AND T1.STATUS_CODE =1
    AND T1.SUBMISSION_DATE BETWEEN LS_FY_START_DATE AND LS_FY_END_DATE;

ELSEIF AV_WIDGET = 'NOT_FUNDED_INSTITUTE_PROPOSAL_SPONSOR' THEN

    IF month(NOW()) >= LS_FY_MONTH_CRITERIA THEN 
		SET COL3 = YEAR(NOW());
    ELSE
        SET COL3 = YEAR(NOW()) - 1;
	END IF;

    SET LS_FY_START_DATE = CONCAT(COL3,LS_FY_START_DATE);
    SET LS_FY_END_DATE = CONCAT(COL3+1,LS_FY_END_DATE);
		WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT DISTINCT T1.PROPOSAL_NUMBER,T1.TITLE,T8.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT  JOIN PROPOSAL_PERSONS T8 ON T8.PROPOSAL_ID = T1.PROPOSAL_ID AND T8.PROP_PERSON_ROLE_ID = 3 AND T8.PI_FLAG = 'Y' 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	INNER JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T8.PERSON_ID = AV_PERSON_ID) 
	        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
	     ))   
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.SPONSOR_CODE = AV_SPONSOR_CODE AND T1.STATUS_CODE =8
	and T1.SUBMISSION_DATE BETWEEN LS_FY_START_DATE AND LS_FY_END_DATE;

ELSEIF AV_WIDGET = 'FUNDED_INSTITUTE_PROPOSAL_SPONSOR' THEN
     
	IF month(NOW()) >= LS_FY_MONTH_CRITERIA THEN 
		SET COL3 = YEAR(NOW());
    ELSE
        SET COL3 = YEAR(NOW()) - 1;
	END IF;

    SET LS_FY_START_DATE = CONCAT(COL3,LS_FY_START_DATE);
    SET LS_FY_END_DATE = CONCAT(COL3+1,LS_FY_END_DATE);
			WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT DISTINCT T1.PROPOSAL_NUMBER,T1.TITLE,T8.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT  JOIN PROPOSAL_PERSONS T8 ON T8.PROPOSAL_ID = T1.PROPOSAL_ID AND T8.PROP_PERSON_ROLE_ID = 3 AND T8.PI_FLAG = 'Y' 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	INNER JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T8.PERSON_ID = AV_PERSON_ID) 
	        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
	     ))   
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.SPONSOR_CODE = AV_SPONSOR_CODE AND T1.STATUS_CODE =2
	and T1.SUBMISSION_DATE BETWEEN LS_FY_START_DATE AND LS_FY_END_DATE;

ELSEIF AV_WIDGET = 'WITHDRAWN_INSTITUTE_PROPOSAL_SPONSOR' THEN

   IF month(NOW()) >= LS_FY_MONTH_CRITERIA THEN 
		SET COL3 = YEAR(NOW());
    ELSE
        SET COL3 = YEAR(NOW()) - 1;
	END IF;
    SET LS_FY_START_DATE = CONCAT(COL3,LS_FY_START_DATE);
    SET LS_FY_END_DATE = CONCAT(COL3+1,LS_FY_END_DATE);
			WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT DISTINCT T1.PROPOSAL_NUMBER,T1.TITLE,T8.FULL_NAME,T3.DESCRIPTION AS ACTIVITY_TYPE, T4.DESCRIPTION AS PROPOSAL_TYPE,
	T5.DESCRIPTION AS  PROPOSAL_STATUS,T6.DISPLAY_NAME AS SPONSOR_NAME,T1.SUBMISSION_DATE,T1.PROPOSAL_ID
	FROM PROPOSAL T1
	LEFT  JOIN PROPOSAL_PERSONS T8 ON T8.PROPOSAL_ID = T1.PROPOSAL_ID AND T8.PROP_PERSON_ROLE_ID = 3 AND T8.PI_FLAG = 'Y' 
	INNER JOIN ACTIVITY_TYPE T3 ON T3.ACTIVITY_TYPE_CODE = T1.ACTIVITY_TYPE_CODE 
	INNER JOIN PROPOSAL_TYPE T4 ON T4.TYPE_CODE = T1.TYPE_CODE 
	LEFT JOIN PROPOSAL_STATUS T5 ON T5.STATUS_CODE = T1.STATUS_CODE
	INNER JOIN SPONSOR T6 ON T6.SPONSOR_CODE = T1.SPONSOR_CODE
	WHERE   ((T8.PERSON_ID = AV_PERSON_ID) 
	        OR (T1.HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
	     ))   
	AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T1.SPONSOR_CODE = AV_SPONSOR_CODE AND T1.STATUS_CODE =5
	and T1.SUBMISSION_DATE BETWEEN LS_FY_START_DATE AND LS_FY_END_DATE;

ELSEIF AV_WIDGET = 'PENDING_INSTITUTE_PROPOSAL_BY_SPONSOR_TYPE' THEN	
	
				WITH ACCESS_TMP 
							AS
							(SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'N' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL')				
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = 'Y' AND T1.PERSON_ID = AV_PERSON_ID
							AND RIGHT_NAME IN ('MODIFY_PROPOSAL','VIEW_PROPOSAL','VIEW_ANY_PROPOSAL','CREATE_AWARD','MODIFY_INST_PROPOSAL','VIEW_INST_PROPOSAL') 
                            ))
	SELECT DISTINCT T1.PROPOSAL_NUMBER, T1.TITLE, T2.DISPLAY_NAME AS SPONSOR_NAME,IFNULL(T4.TOTAL_COST, '0.00'), T3.FULL_NAME, T1.PROPOSAL_ID FROM PROPOSAL T1 
	INNER JOIN SPONSOR T2 ON T1.SPONSOR_CODE = T2.SPONSOR_CODE LEFT OUTER JOIN PROPOSAL_PERSONS T3 ON T1.PROPOSAL_ID = T3.PROPOSAL_ID AND T3.PI_FLAG ='Y'
	LEFT JOIN (SELECT IS_LATEST_VERSION ,TOTAL_COST, PROPOSAL_ID FROM IP_BUDGET_HEADER WHERE IS_FINAL_BUDGET ='Y' OR (IS_FINAL_BUDGET ='N' AND IS_LATEST_VERSION='Y') GROUP BY BUDGET_HEADER_ID) T4 ON T1.PROPOSAL_ID = T4.PROPOSAL_ID 
    WHERE T1.STATUS_CODE IN ( '1', '2', '8', '5' ) AND T1.PROPOSAL_SEQUENCE_STATUS = 'ACTIVE' AND T2.SPONSOR_TYPE_CODE = AV_SEARCH  
    AND  T1.PROPOSAL_ID IN (SELECT PROPOSAL_ID FROM PROPOSAL
	WHERE HOME_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP) UNION
	SELECT PROPOSAL_ID FROM PROPOSAL_PERSONS WHERE PERSON_ID = AV_PERSON_ID);
 
END IF;		
END
