-- `LOAD_BUINESS_RULE`; 

CREATE PROCEDURE `LOAD_BUINESS_RULE`()
BEGIN
	DECLARE LI_LVL INT;
	DECLARE LS_UNIT_NUMBER VARCHAR(40);
	DECLARE   LL_DESCRIPTION VARCHAR(200);
	DECLARE   LL_RULE_TYPE varchar(2);
	DECLARE   LL_UNIT_NUMBER varchar(50);
	DECLARE   LL_MODULE_CODE  INT;
	DECLARE   LL_SUB_MODULE_CODE  INT;
	DECLARE   LL_IS_ACTIVE varchar(1);
	DECLARE   LL_RULE_EXPRESSION varchar(300);
	DECLARE   LL_NOTIFICATION_ID  INT;
	DECLARE   LL_USER_MESSAGE varchar(4000);
	DECLARE   LL_RULE_EVALUATION_ORDER  INT(8);
	DECLARE   LL_MAP_ID  INT;
	DECLARE   LL_RULE_CATEGORY varchar(1);
	DECLARE    LL_RULES_EXPERSSION_ID INT;
	DECLARE    LL_RULE_ID INT;
	DECLARE    LL_EXPRESSION_NUMBER INT;
	DECLARE    LL_EXPRESSION_TYPE_CODE varchar(1);
	DECLARE    LL_LVALUE varchar(4000);
	DECLARE    LL_CONDITION_OPERATOR varchar(25);
	DECLARE    LL_RVALUE varchar(4000);
	DECLARE    LL_PARENT_EXPRESSION_NUMBER  INT;
	DECLARE LI_SEQ_RULE_ID     INT(12);
	DECLARE LI_SEQ_RULE_EXP_ID INT(12);
	SET SQL_SAFE_UPDATES = 0;
BEGIN 
	DECLARE DONE1 INT DEFAULT FALSE;
	DECLARE UNIT_CURSOR CURSOR FOR 
			select UNIT_NUMBER,LVL from NTU_UNIT 
			where LVL in (2,3,4) 
			and UNIT_NUMBER not in ('228','456','208');
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
	OPEN UNIT_CURSOR;
	UNIT_CURSOR_LOOP : LOOP
			FETCH UNIT_CURSOR INTO 	
						LS_UNIT_NUMBER,
						LI_LVL;
			IF DONE1 THEN
				LEAVE UNIT_CURSOR_LOOP;
			END IF;
				IF LI_LVL = 2 THEN
					BEGIN
					DECLARE DONE1 INT DEFAULT FALSE;
					DECLARE CUR_BIZ_RULE CURSOR FOR 
						SELECT  RULE_ID,
								DESCRIPTION,
								RULE_TYPE,
								UNIT_NUMBER,
								MODULE_CODE,
								SUB_MODULE_CODE,
								IS_ACTIVE,
								RULE_EXPRESSION,
								NOTIFICATION_ID,
								USER_MESSAGE,
								RULE_EVALUATION_ORDER,
								MAP_ID,
								RULE_CATEGORY
						FROM BUSINESS_RULES WHERE  UNIT_NUMBER =  '208';
						DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
						OPEN CUR_BIZ_RULE;
						CUR_BIZ_RULE_LOOP : LOOP
									FETCH CUR_BIZ_RULE INTO 																																		
															   LL_RULE_ID,
															   LL_DESCRIPTION,
															   LL_RULE_TYPE,
															   LL_UNIT_NUMBER,
															   LL_MODULE_CODE,
															   LL_SUB_MODULE_CODE,
															   LL_IS_ACTIVE,
															   LL_RULE_EXPRESSION,
															   LL_NOTIFICATION_ID,
															   LL_USER_MESSAGE,
															   LL_RULE_EVALUATION_ORDER,
															   LL_MAP_ID,
															   LL_RULE_CATEGORY;															
									IF DONE1 THEN
										LEAVE CUR_BIZ_RULE_LOOP;
									END IF;
									SELECT (CASE WHEN MAX(RULE_ID) IS NULL THEN 1 ELSE MAX(RULE_ID)+1 END) INTO LI_SEQ_RULE_ID  FROM business_rules;					
									INSERT INTO business_rules(RULE_ID,DESCRIPTION,RULE_TYPE,UNIT_NUMBER,MODULE_CODE,SUB_MODULE_CODE,IS_ACTIVE,
											RULE_EXPRESSION,UPDATE_TIMESTAMP,UPDATE_USER,NOTIFICATION_ID,USER_MESSAGE,RULE_EVALUATION_ORDER,MAP_ID,
											RULE_CATEGORY)
									VALUE(LI_SEQ_RULE_ID,LL_DESCRIPTION,LL_RULE_TYPE,LL_UNIT_NUMBER,LL_MODULE_CODE,LL_SUB_MODULE_CODE,LL_IS_ACTIVE, LL_RULE_EXPRESSION,now(),'admin',LL_NOTIFICATION_ID,LL_USER_MESSAGE,LL_RULE_EVALUATION_ORDER, LL_MAP_ID,LL_RULE_CATEGORY);
									BEGIN
												DECLARE DONE2 INT DEFAULT FALSE;
												DECLARE CUR_BIZ_EXP_RULE CURSOR FOR 
													SELECT  
														RULES_EXPERSSION_ID ,
														RULE_ID,
														EXPRESSION_NUMBER,
														EXPRESSION_TYPE_CODE ,
														LVALUE,
														CONDITION_OPERATOR ,
														RVALUE,  
														PARENT_EXPRESSION_NUMBER
														FROM BUSINESS_RULES_EXPERSSION 
													   WHERE  RULE_ID =  LL_RULE_ID;
											DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
												OPEN CUR_BIZ_EXP_RULE;
													CUR_BIZ_EXP_RULE_LOOP : LOOP
														FETCH CUR_BIZ_EXP_RULE INTO
																		LL_RULES_EXPERSSION_ID,
																		LL_RULE_ID,
																		LL_EXPRESSION_NUMBER,
																		LL_EXPRESSION_TYPE_CODE,
																		LL_LVALUE,
																		LL_CONDITION_OPERATOR,
																		LL_RVALUE,
																		LL_PARENT_EXPRESSION_NUMBER;
													IF DONE1 THEN
														LEAVE CUR_BIZ_EXP_RULE_LOOP;
													END IF;
												SELECT (CASE WHEN MAX(RULES_EXPERSSION_ID) IS NULL THEN 1 ELSE MAX(RULES_EXPERSSION_ID)+1 END) INTO LI_SEQ_RULE_EXP_ID  FROM BUSINESS_RULES_EXPERSSION;
												INSERT INTO BUSINESS_RULES_EXPERSSION(RULES_EXPERSSION_ID,RULE_ID,EXPRESSION_NUMBER,EXPRESSION_TYPE_CODE,LVALUE,CONDITION_OPERATOR,RVALUE,UPDATE_TIMESTAMP,UPDATE_USER,PARENT_EXPRESSION_NUMBER)
												VALUE(LI_SEQ_RULE_EXP_ID,LL_RULE_ID,LL_EXPRESSION_NUMBER,LL_EXPRESSION_TYPE_CODE,LL_LVALUE,LL_CONDITION_OPERATOR,LL_RVALUE,now(),'admin',LL_PARENT_EXPRESSION_NUMBER);
												COMMIT;
											END LOOP;
											CLOSE CUR_BIZ_EXP_RULE;
										END;
								END LOOP;
								CLOSE CUR_BIZ_RULE;
							END;
		ELSEIF LI_LVL = 3 THEN
			BEGIN
							DECLARE DONE1 INT DEFAULT FALSE;
							DECLARE CUR_BIZ_RULE CURSOR FOR 
								SELECT  RULE_ID,
										DESCRIPTION,
										RULE_TYPE,
										UNIT_NUMBER,
										MODULE_CODE,
										SUB_MODULE_CODE,
										IS_ACTIVE,
										RULE_EXPRESSION,
										NOTIFICATION_ID,
										USER_MESSAGE,
										RULE_EVALUATION_ORDER,
										MAP_ID,
										RULE_CATEGORY
								FROM BUSINESS_RULES WHERE  UNIT_NUMBER =  '456';
								DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
								OPEN CUR_BIZ_RULE;
								CUR_BIZ_RULE_LOOP : LOOP
											FETCH CUR_BIZ_RULE INTO 																																		
																	   LL_RULE_ID,
																	   LL_DESCRIPTION,
																	   LL_RULE_TYPE,
																	   LL_UNIT_NUMBER,
																	   LL_MODULE_CODE,
																	   LL_SUB_MODULE_CODE,
																	   LL_IS_ACTIVE,
																	   LL_RULE_EXPRESSION,
																	   LL_NOTIFICATION_ID,
																	   LL_USER_MESSAGE,
																	   LL_RULE_EVALUATION_ORDER,
																	   LL_MAP_ID,
																	   LL_RULE_CATEGORY;															
											IF DONE1 THEN
												LEAVE CUR_BIZ_RULE_LOOP;
											END IF;
											SELECT (CASE WHEN MAX(RULE_ID) IS NULL THEN 1 ELSE MAX(RULE_ID)+1 END) INTO LI_SEQ_RULE_ID  FROM business_rules;					
											INSERT INTO business_rules(RULE_ID,DESCRIPTION,RULE_TYPE,UNIT_NUMBER,MODULE_CODE,SUB_MODULE_CODE,IS_ACTIVE,
													RULE_EXPRESSION,UPDATE_TIMESTAMP,UPDATE_USER,NOTIFICATION_ID,USER_MESSAGE,RULE_EVALUATION_ORDER,MAP_ID,
													RULE_CATEGORY)
											VALUE(LI_SEQ_RULE_ID,LL_DESCRIPTION,LL_RULE_TYPE,LL_UNIT_NUMBER,LL_MODULE_CODE,LL_SUB_MODULE_CODE,LL_IS_ACTIVE, LL_RULE_EXPRESSION,now(),'admin',LL_NOTIFICATION_ID,LL_USER_MESSAGE,LL_RULE_EVALUATION_ORDER, LL_MAP_ID,LL_RULE_CATEGORY);
											BEGIN
														DECLARE DONE2 INT DEFAULT FALSE;
														DECLARE CUR_BIZ_EXP_RULE CURSOR FOR 
															SELECT  
																RULES_EXPERSSION_ID ,
																RULE_ID,
																EXPRESSION_NUMBER,
																EXPRESSION_TYPE_CODE ,
																LVALUE,
																CONDITION_OPERATOR ,
																RVALUE,  
																PARENT_EXPRESSION_NUMBER
																FROM BUSINESS_RULES_EXPERSSION 
															    WHERE  RULE_ID =  LL_RULE_ID;
													DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
														OPEN CUR_BIZ_EXP_RULE;
															CUR_BIZ_EXP_RULE_LOOP : LOOP
																FETCH CUR_BIZ_EXP_RULE INTO
																				LL_RULES_EXPERSSION_ID,
																				LL_RULE_ID,
																				LL_EXPRESSION_NUMBER,
																				LL_EXPRESSION_TYPE_CODE,
																				LL_LVALUE,
																				LL_CONDITION_OPERATOR,
																				LL_RVALUE,
																				LL_PARENT_EXPRESSION_NUMBER;
															IF DONE1 THEN
																LEAVE CUR_BIZ_EXP_RULE_LOOP;
															END IF;
														SELECT (CASE WHEN MAX(RULES_EXPERSSION_ID) IS NULL THEN 1 ELSE MAX(RULES_EXPERSSION_ID)+1 END) INTO LI_SEQ_RULE_EXP_ID  FROM BUSINESS_RULES_EXPERSSION;
														INSERT INTO BUSINESS_RULES_EXPERSSION(RULES_EXPERSSION_ID,RULE_ID,EXPRESSION_NUMBER,EXPRESSION_TYPE_CODE,LVALUE,CONDITION_OPERATOR,RVALUE,UPDATE_TIMESTAMP,UPDATE_USER,PARENT_EXPRESSION_NUMBER)
														VALUE(LI_SEQ_RULE_EXP_ID,LL_RULE_ID,LL_EXPRESSION_NUMBER,LL_EXPRESSION_TYPE_CODE,LL_LVALUE,LL_CONDITION_OPERATOR,LL_RVALUE,now(),'admin',LL_PARENT_EXPRESSION_NUMBER);
														COMMIT;
													END LOOP;
													CLOSE CUR_BIZ_EXP_RULE;
												END;
										END LOOP;
										CLOSE CUR_BIZ_RULE;
									END;	
		ELSEIF LI_LVL = 4 THEN
						BEGIN
							DECLARE DONE1 INT DEFAULT FALSE;
							DECLARE CUR_BIZ_RULE CURSOR FOR 
								SELECT  RULE_ID,
										DESCRIPTION,
										RULE_TYPE,
										UNIT_NUMBER,
										MODULE_CODE,
										SUB_MODULE_CODE,
										IS_ACTIVE,
										RULE_EXPRESSION,
										NOTIFICATION_ID,
										USER_MESSAGE,
										RULE_EVALUATION_ORDER,
										MAP_ID,
										RULE_CATEGORY
								FROM BUSINESS_RULES WHERE  UNIT_NUMBER =  '228';
								DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
								OPEN CUR_BIZ_RULE;
								CUR_BIZ_RULE_LOOP : LOOP
											FETCH CUR_BIZ_RULE INTO 																																		
																	   LL_RULE_ID,
																	   LL_DESCRIPTION,
																	   LL_RULE_TYPE,
																	   LL_UNIT_NUMBER,
																	   LL_MODULE_CODE,
																	   LL_SUB_MODULE_CODE,
																	   LL_IS_ACTIVE,
																	   LL_RULE_EXPRESSION,
																	   LL_NOTIFICATION_ID,
																	   LL_USER_MESSAGE,
																	   LL_RULE_EVALUATION_ORDER,
																	   LL_MAP_ID,
																	   LL_RULE_CATEGORY;															
											IF DONE1 THEN
												LEAVE CUR_BIZ_RULE_LOOP;
											END IF;
											SELECT (CASE WHEN MAX(RULE_ID) IS NULL THEN 1 ELSE MAX(RULE_ID)+1 END) INTO LI_SEQ_RULE_ID  FROM business_rules;					
											INSERT INTO business_rules(RULE_ID,DESCRIPTION,RULE_TYPE,UNIT_NUMBER,MODULE_CODE,SUB_MODULE_CODE,IS_ACTIVE,
													RULE_EXPRESSION,UPDATE_TIMESTAMP,UPDATE_USER,NOTIFICATION_ID,USER_MESSAGE,RULE_EVALUATION_ORDER,MAP_ID,
													RULE_CATEGORY)
											VALUE(LI_SEQ_RULE_ID,LL_DESCRIPTION,LL_RULE_TYPE,LL_UNIT_NUMBER,LL_MODULE_CODE,LL_SUB_MODULE_CODE,LL_IS_ACTIVE, LL_RULE_EXPRESSION,now(),'admin',LL_NOTIFICATION_ID,LL_USER_MESSAGE,LL_RULE_EVALUATION_ORDER, LL_MAP_ID,LL_RULE_CATEGORY);
											BEGIN
														DECLARE DONE2 INT DEFAULT FALSE;
														DECLARE CUR_BIZ_EXP_RULE CURSOR FOR 
															SELECT  
																RULES_EXPERSSION_ID ,
																RULE_ID,
																EXPRESSION_NUMBER,
																EXPRESSION_TYPE_CODE ,
																LVALUE,
																CONDITION_OPERATOR ,
																RVALUE,  
																PARENT_EXPRESSION_NUMBER
																FROM BUSINESS_RULES_EXPERSSION 
															    WHERE  RULE_ID =  LL_RULE_ID;
													DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
														OPEN CUR_BIZ_EXP_RULE;
															CUR_BIZ_EXP_RULE_LOOP : LOOP
																FETCH CUR_BIZ_EXP_RULE INTO
																				LL_RULES_EXPERSSION_ID,
																				LL_RULE_ID,
																				LL_EXPRESSION_NUMBER,
																				LL_EXPRESSION_TYPE_CODE,
																				LL_LVALUE,
																				LL_CONDITION_OPERATOR,
																				LL_RVALUE,
																				LL_PARENT_EXPRESSION_NUMBER;
															IF DONE1 THEN
																LEAVE CUR_BIZ_EXP_RULE_LOOP;
															END IF;
														SELECT (CASE WHEN MAX(RULES_EXPERSSION_ID) IS NULL THEN 1 ELSE MAX(RULES_EXPERSSION_ID)+1 END) INTO LI_SEQ_RULE_EXP_ID  FROM BUSINESS_RULES_EXPERSSION;
														INSERT INTO BUSINESS_RULES_EXPERSSION(RULES_EXPERSSION_ID,RULE_ID,EXPRESSION_NUMBER,EXPRESSION_TYPE_CODE,LVALUE,CONDITION_OPERATOR,RVALUE,UPDATE_TIMESTAMP,UPDATE_USER,PARENT_EXPRESSION_NUMBER)
														VALUE(LI_SEQ_RULE_EXP_ID,LL_RULE_ID,LL_EXPRESSION_NUMBER,LL_EXPRESSION_TYPE_CODE,LL_LVALUE,LL_CONDITION_OPERATOR,LL_RVALUE,now(),'admin',LL_PARENT_EXPRESSION_NUMBER);
														COMMIT;
													END LOOP;
													CLOSE CUR_BIZ_EXP_RULE;
												END;
										END LOOP;
										CLOSE CUR_BIZ_RULE;
									END;									
				END IF;
	END LOOP;
CLOSE UNIT_CURSOR;	
END;			
SELECT 1  AS RESULT;
END
