-- `MIGRATE_AGREEMENT_SPONSOR_TO_AGREEMENT`; 

CREATE PROCEDURE `MIGRATE_AGREEMENT_SPONSOR_TO_AGREEMENT`(
	IN AV_SOURCE_MODULE_ID INT,
    IN AV_DESTINATION_MODULE_ID INT,
    IN AV_DESTINATION_MODULE_CODE INT,
    IN AV_SOURCE_MODULE_CODE INT,
    IN AV_UPDATED_USER VARCHAR(60)
)
BEGIN
    DECLARE V_COUNT INT;
    DECLARE V_START_DATE DATE;
    DECLARE V_END_DATE DATE;
    DECLARE V_UNIT_NUMBER VARCHAR(50);
    DECLARE V_UNIT_NAME VARCHAR(255);
    
    SELECT COUNT(*) INTO V_COUNT FROM AGREEMENT_SPONSOR WHERE AGREEMENT_REQUEST_ID = AV_DESTINATION_MODULE_ID;
    IF V_COUNT = 0 THEN
         INSERT INTO AGREEMENT_SPONSOR (
            AGREEMENT_REQUEST_ID,
			SPONSOR_NAME,
			SPONSOR_CODE,
            UPDATE_TIMESTAMP,
            SPONSOR_ROLE_TYPE_CODE,
            AGREEMENT_SPONSOR_TYPE_CODE,
            UPDATE_USER
        )
        SELECT
            AV_DESTINATION_MODULE_ID,
            SPONSOR_NAME,
            SPONSOR_CODE,
            UTC_TIMESTAMP(),
            SPONSOR_ROLE_TYPE_CODE,
           AGREEMENT_SPONSOR_TYPE_CODE,
            AV_UPDATED_USER
            FROM AGREEMENT_SPONSOR WHERE
            AGREEMENT_REQUEST_ID = AV_SOURCE_MODULE_ID AND SPONSOR_ROLE_TYPE_CODE = 1 AND AGREEMENT_SPONSOR_TYPE_CODE = 1 
        ;
	END IF;
    INSERT INTO AGREEMENT_SPONSOR (
            AGREEMENT_REQUEST_ID,
            SPONSOR_NAME,
            SPONSOR_CODE,
            UPDATE_TIMESTAMP,
            SPONSOR_ROLE_TYPE_CODE,
            AGREEMENT_SPONSOR_TYPE_CODE,
            UPDATE_USER
        )
		SELECT
            AV_DESTINATION_MODULE_ID,
            SPONSOR_NAME,
            SPONSOR_CODE,
            UTC_TIMESTAMP(),
            SPONSOR_ROLE_TYPE_CODE,
			AGREEMENT_SPONSOR_TYPE_CODE,
            AV_UPDATED_USER
            FROM AGREEMENT_SPONSOR WHERE
            AGREEMENT_REQUEST_ID = AV_SOURCE_MODULE_ID AND SPONSOR_ROLE_TYPE_CODE = 5 AND AGREEMENT_SPONSOR_TYPE_CODE = 2 
        ;
END
