CREATE PROCEDURE `REFRESH_UNIT_HIERARCHY_LEVEL`()
    DETERMINISTIC
BEGIN


DECLARE LS_VAR LONGTEXT;
DECLARE LS_INTO_VAR LONGTEXT;
DECLARE LS_CHILD_LIST LONGTEXT;
DECLARE LS_ROOT_UNIT VARCHAR(50);

SELECT VALUE INTO LS_VAR FROM PARAMETER WHERE PARAMETER_NAME = 'ROOT_UNIT';
SELECT VALUE INTO LS_ROOT_UNIT FROM PARAMETER WHERE PARAMETER_NAME = 'ROOT_UNIT';
SET LS_CHILD_LIST = '';
	
	

    REPEAT
		
		SELECT GROUP_CONCAT(UNIT_NUMBER SEPARATOR ',') INTO LS_INTO_VAR FROM UNIT WHERE FIND_IN_SET(PARENT_UNIT_NUMBER, LS_VAR) > 0  ;
			
            IF LS_INTO_VAR IS NOT NULL  THEN 
            
				SET LS_CHILD_LIST = CONCAT(LS_CHILD_LIST,',',LS_INTO_VAR) ;
        
				SET LS_VAR = LS_INTO_VAR ;
        
			END IF;
        
       UNTIL LS_INTO_VAR IS NULL  END REPEAT;
       
	   
	  truncate table UNIT_LEVEL;
	  INSERT INTO UNIT_LEVEL(UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER,IS_ACTIVE,LVL)
	  SELECT UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER,IS_ACTIVE, 1 AS LVL 
      FROM UNIT WHERE UNIT_NUMBER =LS_ROOT_UNIT
      UNION ALL
      
	  SELECT UNIT_NUMBER,UNIT_NAME,PARENT_UNIT_NUMBER,ACTIVE_FLAG,FN_GET_UNIT_HIERARCHY_LEVEL(UNIT_NUMBER) AS LVL  
      FROM UNIT WHERE FIND_IN_SET(UNIT_NUMBER,LS_CHILD_LIST)
	  order by LVL,PARENT_UNIT_NUMBER;
	
	Commit;


END
