-- `UPD_UNIT_HIERARCHY_PARENT_ROOT`; 

CREATE PROCEDURE `UPD_UNIT_HIERARCHY_PARENT_ROOT`()
    DETERMINISTIC
BEGIN
 DECLARE LI_ID INT;
 DECLARE LI_PARENT_ID INT;
 DECLARE LS_UNIT_NUMBER VARCHAR(50);
 DECLARE LS_UNIT_NAME VARCHAR(200);
 DECLARE LS_PARENT_UNIT_NUMBER VARCHAR(50);
 DECLARE DONE INT DEFAULT FALSE;
 DECLARE CUR CURSOR FOR 
 SELECT 
	ID, 
	UNIT_NUMBER,
    UNIT_NAME,
    PARENT_UNIT_NUMBER
    FROM
    UNIT_TMP;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE = TRUE;
    OPEN CUR;
    INSERT_LOOP: LOOP
        FETCH CUR INTO 
        LI_ID,
        LS_UNIT_NUMBER,
        LS_UNIT_NAME,
        LS_PARENT_UNIT_NUMBER;
	IF DONE THEN
        LEAVE INSERT_LOOP;
    END IF;
    UPDATE UNIT_TMP SET PARENT_ID= LI_ID
    WHERE PARENT_UNIT_NUMBER = LS_UNIT_NUMBER;
END LOOP;
CLOSE CUR;
	COMMIT;
END
