-- `FN_CHCK_MANPOWER_POSITION_ID`; 


CREATE FUNCTION `FN_CHCK_MANPOWER_POSITION_ID`(AV_AWARD_ID VARCHAR(22)) RETURNS varchar(8) 
    DETERMINISTIC
BEGIN
    DECLARE LI_COUNT INT(3);
    DECLARE LS_POSITION_ID VARCHAR(50);
    DECLARE LS_RESOURCE_UNIQUE_ID VARCHAR(50);
    DECLARE LD_PLAN_START_DATE DATETIME;
    DECLARE LD_PLAN_END_DATE DATETIME;
    DECLARE LS_AWARD_NUMBER VARCHAR(12);
    SELECT COUNT(*) INTO LI_COUNT
    FROM AWARD_MANPOWER T1
    LEFT JOIN AWARD_MANPOWER_RESOURCE T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID
    WHERE T1.AWARD_ID = AV_AWARD_ID;
    IF LI_COUNT =0 THEN
    RETURN 'TRUE';
    END IF;
    SELECT COUNT(*) INTO LI_COUNT
    FROM AWARD_MANPOWER T1
    LEFT JOIN AWARD_MANPOWER_RESOURCE T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID
    WHERE T1.AWARD_ID = AV_AWARD_ID
    AND IFNULL(T2.POSITION_ID,'') <> ''
    AND T2.PLAN_START_DATE IS NOT NULL
    AND T2.PLAN_END_DATE IS NOT NULL
    AND T1.AWARD_NUMBER IS NOT NULL
    AND T2.POSITION_STATUS_CODE = 7;
    IF LI_COUNT =0 THEN
    RETURN 'TRUE';
    END IF;
    BEGIN
    DECLARE LS_ERROR VARCHAR(2000);
    DECLARE DONE1 INT DEFAULT FALSE;
    DECLARE MIGRATION_MANPOWER_POSITION_CURSOR CURSOR FOR
    SELECT T2.POSITION_ID, T2.RESOURCE_UNIQUE_ID
    FROM AWARD_MANPOWER T1
    LEFT JOIN AWARD_MANPOWER_RESOURCE T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID
    WHERE T1.AWARD_ID = AV_AWARD_ID
    AND IFNULL(T2.POSITION_ID,'') <> ''
    AND T2.PLAN_START_DATE IS NOT NULL
    AND T2.PLAN_END_DATE IS NOT NULL
    AND T1.AWARD_NUMBER IS NOT NULL
    AND T2.POSITION_STATUS_CODE = 7;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
    OPEN MIGRATION_MANPOWER_POSITION_CURSOR;
    MIGRATION_MANPOWER_POSITION_CURSOR_LOOP : LOOP
    FETCH MIGRATION_MANPOWER_POSITION_CURSOR INTO LS_POSITION_ID, LS_RESOURCE_UNIQUE_ID;
    IF DONE1 THEN
    LEAVE MIGRATION_MANPOWER_POSITION_CURSOR_LOOP;
    END IF;
    SELECT T2.PLAN_START_DATE,T2.PLAN_END_DATE,T1.AWARD_NUMBER
    INTO LD_PLAN_START_DATE,LD_PLAN_END_DATE,LS_AWARD_NUMBER
    FROM AWARD_MANPOWER T1
    LEFT JOIN AWARD_MANPOWER_RESOURCE T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID
    WHERE T1.AWARD_ID = AV_AWARD_ID
    AND T2.POSITION_ID = LS_POSITION_ID
    AND T2.RESOURCE_UNIQUE_ID = LS_RESOURCE_UNIQUE_ID
    AND T2.PLAN_START_DATE IS NOT NULL
    AND T2.PLAN_END_DATE IS NOT NULL
    AND T1.AWARD_NUMBER IS NOT NULL
    AND T2.POSITION_STATUS_CODE = 7;
    SELECT COUNT(*) INTO LI_COUNT
    FROM AWARD_MANPOWER T1
    LEFT JOIN AWARD_MANPOWER_RESOURCE T2 ON T1.AWARD_MANPOWER_ID = T2.AWARD_MANPOWER_ID
    LEFT JOIN AWARD T3 ON T1.AWARD_ID = T3.AWARD_ID
    WHERE T2.POSITION_ID = LS_POSITION_ID
    AND T2.POSITION_STATUS_CODE NOT IN (5, 8)
    AND T1.AWARD_NUMBER <> LS_AWARD_NUMBER
    AND T3.AWARD_SEQUENCE_STATUS IN ('ACTIVE', 'PENDING')
    AND (
    CASE 
        WHEN T2.CHARGE_START_DATE IS NOT NULL AND T2.CHARGE_END_DATE IS NOT NULL 
            THEN (LD_PLAN_START_DATE BETWEEN T2.CHARGE_START_DATE AND T2.CHARGE_END_DATE)
                OR (LD_PLAN_END_DATE BETWEEN T2.CHARGE_START_DATE AND T2.CHARGE_END_DATE)
                OR (T2.CHARGE_START_DATE BETWEEN LD_PLAN_START_DATE AND LD_PLAN_END_DATE )
                OR (T2.CHARGE_END_DATE BETWEEN LD_PLAN_START_DATE AND LD_PLAN_END_DATE)	
        ELSE 
            (LD_PLAN_START_DATE BETWEEN T2.PLAN_START_DATE AND T2.PLAN_END_DATE)
            OR (LD_PLAN_END_DATE BETWEEN T2.PLAN_START_DATE AND T2.PLAN_END_DATE)
            OR (T2.PLAN_START_DATE BETWEEN LD_PLAN_START_DATE AND LD_PLAN_END_DATE )
            OR (T2.PLAN_END_DATE BETWEEN LD_PLAN_START_DATE AND LD_PLAN_END_DATE)
        END
    );
    IF LI_COUNT <> 0 THEN
    RETURN 'FALSE';
    END IF;
    END LOOP;
    CLOSE MIGRATION_MANPOWER_POSITION_CURSOR;
    END;
    RETURN 'TRUE';
END
