-- `GET_IOI_DASHBOARD`; 

CREATE PROCEDURE `GET_IOI_DASHBOARD`(
AV_GRANT_HEADER_ID               int(10),
AV_LOGPERSON_ID                              VARCHAR(40),
AV_TAB_TYPE                                  VARCHAR(30)
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LS_FILTER_CONDITION LONGTEXT;
DECLARE LS_OFFSET_CONDITION VARCHAR(600);
DECLARE LS_OFFSET INT(11);
DECLARE TAB_QUERY LONGTEXT;
DECLARE JOIN_CONDITION LONGTEXT;
DECLARE SELECTED_FIELD_LIST LONGTEXT;
SET LS_DYN_SQL ='';
SET TAB_QUERY ='';
IF AV_TAB_TYPE = 'MY_IOI' THEN
          SET TAB_QUERY = CONCAT(' (T1.PI_PERSON_ID =''', AV_LOGPERSON_ID,''' OR T1.CREATE_USER  = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID =''', AV_LOGPERSON_ID,''')) AND T1.STATUS_CODE = 2');
ELSEIF AV_TAB_TYPE = 'ALL_IOI' THEN
         SET TAB_QUERY = CONCAT('((T1.SUBMITING_UNIT_NUMBER IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
                                                                         OR T15.HOME_UNIT_NUMBER  IN (SELECT DISTINCT UNIT_NUMBER FROM ACCESS_TMP)
                                                                         OR T1.CREATE_USER  = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID =''', AV_LOGPERSON_ID,''')) AND T1.STATUS_CODE = 2)');
ELSEIF AV_TAB_TYPE = 'DRAFT_IOI' THEN
          SET TAB_QUERY = CONCAT(' (T1.CREATE_USER  = (SELECT USER_NAME FROM PERSON WHERE PERSON_ID =''', AV_LOGPERSON_ID,''')  AND T1.STATUS_CODE = 1 )');
END IF;
			SET LS_DYN_SQL = CONCAT('WITH ACCESS_TMP 
							AS
							(
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''N'' AND T1.PERSON_ID = ''',AV_LOGPERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_IOI'') 							
							UNION
							SELECT CHILD_UNIT_NUMBER FROM UNIT_WITH_CHILDREN 
							WHERE UNIT_NUMBER IN (
							SELECT UNIT_NUMBER
							FROM PERSON_ROLES T1
							INNER JOIN ROLE_RIGHTS T2 ON T1.ROLE_ID = T2.ROLE_ID
							INNER JOIN RIGHTS T3 ON T2.RIGHT_ID = T3.RIGHT_ID 
							WHERE T1.DESCEND_FLAG = ''Y'' AND T1.PERSON_ID = ''',AV_LOGPERSON_ID,'''
							AND RIGHT_NAME IN (''VIEW_IOI'') 
                            ))
							');
SET LS_DYN_SQL =CONCAT(LS_DYN_SQL,'SELECT DISTINCT T10.DISPLAY_NAME AS SUBMITING_UNIT_NAME,T4.FULL_NAME AS PI_FULL_NAME,T1.PROJECT_TITLE,
                                                                T1.REQUESTED_DIRECT_COST,T5.FULL_NAME AS UPDATE_USER
                                ,COUNT(T2.IOI_MEMBER_ID) AS PERSON_COUNT,T1.IOI_ID,T3.STATUS_CODE,T3.DESCRIPTION,T16.FULL_NAME AS CREATE_USER,
                                                                T1.UNIT_NUMBER,
                                                                T11.UNIT_NAME
                                                FROM GRANT_CALL_IOI_HEADER T1
                                                LEFT JOIN GRANT_CALL_IOI_MEMBERS T2 ON T1.IOI_ID = T2.IOI_ID
                                                LEFT JOIN IOI_STATUS T3 ON T3.STATUS_CODE = T1.STATUS_CODE
                                                LEFT JOIN PERSON T4 ON T4.PERSON_ID = T1.PI_PERSON_ID
                        LEFT JOIN PERSON T5 ON T1.UPDATE_USER = T5.USER_NAME
                        LEFT JOIN UNIT T10 ON T1.SUBMITING_UNIT_NUMBER = T10.UNIT_NUMBER
                        LEFT JOIN GRANT_CALL_HEADER T15 ON T15.GRANT_HEADER_ID = T1.GRANT_HEADER_ID
                                                LEFT JOIN PERSON T16 ON T1.CREATE_USER = T16.USER_NAME
                                                LEFT JOIN UNIT T11 ON T11.UNIT_NUMBER = T1.UNIT_NUMBER
                                                WHERE T1.GRANT_HEADER_ID = ',AV_GRANT_HEADER_ID,' AND ', TAB_QUERY,' GROUP BY T1.IOI_ID,
                                                T10.DISPLAY_NAME, T4.FULL_NAME, T1.PROJECT_TITLE, T1.REQUESTED_DIRECT_COST, T5.FULL_NAME, 
                                                T3.STATUS_CODE,T3.DESCRIPTION,T16.FULL_NAME,T1.UNIT_NUMBER,T11.UNIT_NAME');
SET @QUERY_STATEMENT = LS_DYN_SQL;
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;
END
