-- `NOTIFY_GRANT_ELIGIBLE_PERSONS`; 

CREATE PROCEDURE `NOTIFY_GRANT_ELIGIBLE_PERSONS`( 
AV_GRANT_CALL int
)
BEGIN
DECLARE LS_DYN_SQL LONGTEXT;
DECLARE LI_DESCRIPTION VARCHAR(200);
DECLARE LI_GRANT_ELIGIBILITY_ID int(12);
DECLARE LI_ELIGIBILITY_TARGET_TYPE_CODE varchar(3);
DECLARE LI_TARGET_VALUE varchar(50);
SET LS_DYN_SQL = '';
BEGIN
		DECLARE DONE1 INT DEFAULT FALSE;
		DECLARE HAS_NO_TARGET_CUR CURSOR FOR	
		SELECT t2.DESCRIPTION
		FROM GRANT_CALL_ELIGIBILITY T1 LEFT JOIN GRANT_CALL_ELGIBLITY_TYPE T2
		ON T1.GRANT_ELGBLTY_TYPE_CODE = T2.GRANT_ELGBLTY_TYPE_CODE
		WHERE T1.GRANT_HEADER_ID = AV_GRANT_CALL
		AND T2.HAS_TARGET = 'N';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;
		OPEN HAS_NO_TARGET_CUR; 
		HAS_NO_TARGET_CUR_LOOP : LOOP
				FETCH HAS_NO_TARGET_CUR 
				INTO LI_DESCRIPTION;
					IF DONE1 THEN
							LEAVE HAS_NO_TARGET_CUR_LOOP;
					END IF;	
				IF LI_DESCRIPTION = 'External' THEN 
				  SET  LS_DYN_SQL =CONCAT(LS_DYN_SQL,' SELECT PERSON_ID FROM PERSON WHERE HOME_UNIT = ''999999'' UNION ');
				END IF;
		END LOOP;
		CLOSE HAS_NO_TARGET_CUR;
END;
BEGIN
		DECLARE DONE2 INT DEFAULT FALSE;
		DECLARE HAS_TARGET_CUR CURSOR FOR	
		SELECT t2.DESCRIPTION,t1.GRANT_ELIGIBILITY_ID
		FROM GRANT_CALL_ELIGIBILITY T1 LEFT JOIN GRANT_CALL_ELGIBLITY_TYPE T2
		ON T1.GRANT_ELGBLTY_TYPE_CODE = T2.GRANT_ELGBLTY_TYPE_CODE
		WHERE T1.GRANT_HEADER_ID = AV_GRANT_CALL
		AND T2.HAS_TARGET = 'Y';
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE2 = TRUE;
		OPEN HAS_TARGET_CUR; 
		HAS_TARGET_CUR_LOOP : LOOP
				FETCH HAS_TARGET_CUR 
				INTO LI_DESCRIPTION,LI_GRANT_ELIGIBILITY_ID;
					IF DONE2 THEN
							LEAVE HAS_TARGET_CUR_LOOP;
					END IF;	
				SELECT ELIGIBILITY_TARGET_TYPE_CODE,TARGET_VALUE INTO LI_ELIGIBILITY_TARGET_TYPE_CODE,LI_TARGET_VALUE
				FROM GRANT_ELIGIBILITY_TARGET 
				WHERE GRANT_ELIGIBILITY_ID = LI_GRANT_ELIGIBILITY_ID;
				IF LI_ELIGIBILITY_TARGET_TYPE_CODE = 1 THEN
					SET  LS_DYN_SQL = CONCAT(LS_DYN_SQL,' SELECT PERSON_ID FROM PERSON WHERE HOME_UNIT <> ''999999'' UNION ');
				ELSEIF LI_ELIGIBILITY_TARGET_TYPE_CODE = 2 THEN
					SET  LS_DYN_SQL = CONCAT(LS_DYN_SQL,' SELECT PERSON_ID FROM PERSON WHERE HOME_UNIT = ',LI_TARGET_VALUE,' UNION ');
				ELSEIF LI_ELIGIBILITY_TARGET_TYPE_CODE = 3 THEN
					SET  LS_DYN_SQL = CONCAT(LS_DYN_SQL,' SELECT PERSON_ID FROM PERSON WHERE PERSON_ID = ',LI_TARGET_VALUE,' UNION ');
				END IF;
		END LOOP;
		CLOSE HAS_TARGET_CUR;
END;
IF LS_DYN_SQL IS NOT NULL THEN
	SELECT TRIM(TRAILING 'UNION ' FROM LS_DYN_SQL) into LS_DYN_SQL from dual;
	SET @QUERY_STATEMENT = LS_DYN_SQL;
	PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
	EXECUTE EXECUTABLE_STAEMENT;
else
	SELECT '0';
END IF;
END
