
DROP TABLE IF EXISTS `envelope_recipient`;

CREATE TABLE `envelope_recipient` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENVELOPE_ID` varchar(255) DEFAULT NULL,
  `RECIPIENT_COUNT` varchar(255) DEFAULT NULL,
  `CURRENT_ROUTING_ORDER` varchar(255) DEFAULT NULL,
  `COMPLETE_COUNT` varchar(255) DEFAULT NULL,
  `CREATION_REASON` varchar(255) DEFAULT NULL,
  `DELIVERED_DATE_TIME` varchar(255) DEFAULT NULL,
  `DELIVERY_METHOD` varchar(250) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `RECIPIENT_ID` varchar(255) DEFAULT NULL,
  `RECIPIENT_ID_GUID` varchar(255) DEFAULT NULL,
  `RECIPIENT_TYPE` varchar(255) DEFAULT NULL,
  `ROLE_NAME` varchar(255) DEFAULT NULL,
  `ROUTING_ORDER` varchar(255) DEFAULT NULL,
  `SIGNED_DATE_TIME` varchar(255) DEFAULT NULL,
  `DECLINED_DATE_TIME` varchar(255) DEFAULT NULL,
  `DECLINED_REASON` varchar(2000) DEFAULT NULL,
  `SENT_DATE_TIME` varchar(255) DEFAULT NULL,
  `USER_ID` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) 
