-- `ADD_FULL_COLUMN_IN_AWARD_CUSTOM_DATA_RT`; 

CREATE PROCEDURE `ADD_FULL_COLUMN_IN_AWARD_CUSTOM_DATA_RT`()
BEGIN
 DECLARE LI_CUSTOM_DATA_ELEMENTS_ID INT;
 DECLARE NOT_FOUND INT DEFAULT 0;
 
 
 DECLARE SEL_CUSTOM_DATA_ELEMENTS_ID CURSOR FOR  SELECT DISTINCT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENT_USAGE WHERE MODULE_CODE = 1;
 
 DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
 DROP TABLE IF EXISTS AWARD_CUSTOM_DATA_RT;
 CREATE TABLE AWARD_CUSTOM_DATA_RT (
  AWARD_CUSTOM_DATA_RT_ID INT NOT NULL AUTO_INCREMENT,
  AWARD_ID INT NOT NULL,   
  UPDATE_TIMESTAMP DATETIME DEFAULT NULL,
  PRIMARY KEY (AWARD_CUSTOM_DATA_RT_ID)
);
		OPEN SEL_CUSTOM_DATA_ELEMENTS_ID;
		SEL_CUSTOM_DATA_ELEMENTS_ID : LOOP
			SET NOT_FOUND = 0;
			FETCH SEL_CUSTOM_DATA_ELEMENTS_ID INTO LI_CUSTOM_DATA_ELEMENTS_ID;
			IF NOT_FOUND = 1 THEN
				LEAVE SEL_CUSTOM_DATA_ELEMENTS_ID;
			END IF;
			
			CALL ADD_COLUMN_IN_AWARD_CUSTOM_DATA_RT(LI_CUSTOM_DATA_ELEMENTS_ID, 'I');
			
			END LOOP;
			CLOSE SEL_CUSTOM_DATA_ELEMENTS_ID;
	SELECT 1 AS 'SUCCESS';
END
