CREATE PROCEDURE `AWARD_CUSTOM_DATA_RT_SYNC_BY_AWARD_ID`(AV_ORIGINAL_AWARD_ID INT, AV_COPY_AWARD_ID INT)
PROC:BEGIN
    DECLARE LS_INSERT LONGTEXT DEFAULT '';
    DECLARE LS_QUERY LONGTEXT DEFAULT '';
    DECLARE LS_COLUMN_NAME VARCHAR(4000);
    DECLARE LI_COST_ELEMENT_ID VARCHAR(2000);
    DECLARE NOT_FOUND INT DEFAULT 0;
	DECLARE L_CNT INT DEFAULT 1;
	DECLARE LS_SELECT_FIELD LONGTEXT DEFAULT ' ';
	DECLARE LS_TAB_FORM LONGTEXT DEFAULT ' ';
	DECLARE LI_COLUMN_ID INT;
    DECLARE LI_DEL_CNT INT DEFAULT 0;
	DECLARE LI_FLAG_COUNT INT DEFAULT 0;
	DECLARE LS_FLAG CHAR(1);
    DECLARE LI_DEL INT DEFAULT 0;
    DECLARE LS_STATUS VARCHAR(255) ;
    DECLARE LI_SEQUENCE_NUMBER INT DEFAULT 0;
    DECLARE l_count INT;
    DECLARE SEL_COLUMN_NAME CURSOR FOR
        SELECT COLUMN_NAME
        FROM INFORMATION_SCHEMA.COLUMNS 
        WHERE TABLE_SCHEMA = (SELECT DATABASE())
            AND TABLE_NAME = 'AWARD_CUSTOM_DATA_RT'
            AND COLUMN_NAME <> 'AWARD_ID'
            AND COLUMN_NAME <> 'UPDATE_TIMESTAMP'
            AND COLUMN_NAME <> 'AWARD_CUSTOM_DATA_RT_ID'
        ORDER BY ORDINAL_POSITION;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
SELECT count(1) into l_count FROM CUSTOM_DATA 
         WHERE MODULE_ITEM_KEY = AV_ORIGINAL_AWARD_ID and MODULE_ITEM_CODE = 1;
IF l_count = 0 THEN 
SET SQL_SAFE_UPDATES = 0;
DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_ORIGINAL_AWARD_ID;
SET SQL_SAFE_UPDATES = 1;
LEAVE PROC;
END IF;

IF AV_ORIGINAL_AWARD_ID = AV_COPY_AWARD_ID THEN 
SET SQL_SAFE_UPDATES = 0;
DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID IN (
SELECT AWARD_ID FROM AWARD WHERE SEQUENCE_NUMBER != 0 AND AWARD_NUMBER =
(SELECT AWARD_NUMBER FROM AWARD WHERE AWARD_ID =AV_ORIGINAL_AWARD_ID ));
SET SQL_SAFE_UPDATES = 1;
LEAVE PROC;
END IF;
SELECT  AWARD_SEQUENCE_STATUS,SEQUENCE_NUMBER INTO  LS_STATUS,LI_SEQUENCE_NUMBER FROM AWARD  WHERE AWARD_ID = AV_ORIGINAL_AWARD_ID; 
IF AV_COPY_AWARD_ID IS NOT NULL OR AV_COPY_AWARD_ID <> '' THEN 
SELECT COUNT(DISTINCT AWARD_NUMBER) INTO LI_FLAG_COUNT FROM AWARD  WHERE AWARD_ID in (AV_ORIGINAL_AWARD_ID,AV_COPY_AWARD_ID);
IF LI_FLAG_COUNT = 1 THEN 
	SET LS_FLAG =  CASE WHEN ((LS_STATUS = 'ACTIVE') OR (LS_STATUS IN ('ARCHIVE','PENDING') AND LI_SEQUENCE_NUMBER = 1 )) THEN 'C' ELSE'M' END;
ELSE 
  SET LS_FLAG = 'C';
END IF; 
END IF;

    OPEN SEL_COLUMN_NAME;
    COLUMN_NAME_LOOP: LOOP
        SET NOT_FOUND = 0;
        FETCH SEL_COLUMN_NAME INTO LS_COLUMN_NAME ;
        IF NOT_FOUND = 1 THEN 
            LEAVE COLUMN_NAME_LOOP;
        END IF;

		SELECT  t1.CUSTOM_DATA_ELEMENTS_ID INTO LI_COST_ELEMENT_ID FROM CUSTOM_DATA_ELEMENTS T1
		WHERE CONCAT('CUST_ELEMENTS_ID_',T1.CUSTOM_DATA_ELEMENTS_ID) = LS_COLUMN_NAME;
         IF (LI_COST_ELEMENT_ID IS NOT NULL)  AND       
			(LI_COST_ELEMENT_ID IN (SELECT distinct CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA_ELEMENT_USAGE WHERE MODULE_CODE = 1))
            AND (LI_COST_ELEMENT_ID IN (SELECT DISTINCT CUSTOM_DATA_ELEMENTS_ID FROM CUSTOM_DATA 
         WHERE MODULE_ITEM_CODE = 1 AND MODULE_ITEM_KEY = AV_ORIGINAL_AWARD_ID))
         THEN 
		 SET LS_INSERT = CONCAT(LS_INSERT,LS_COLUMN_NAME,',');		 
		 SET LS_SELECT_FIELD = CONCAT(LS_SELECT_FIELD,',T',L_CNT,'.C1');

		  IF L_CNT = 1 THEN 
         SET LS_TAB_FORM = CONCAT(LS_TAB_FORM,' (SELECT MODULE_ITEM_KEY, COALESCE(DESCRIPTION, VALUE) AS c1 
            FROM CUSTOM_DATA WHERE MODULE_ITEM_CODE = 1 AND CUSTOM_DATA_ELEMENTS_ID = ',LI_COST_ELEMENT_ID,') AS T',L_CNT, ' RIGHT JOIN ');
		ELSE
        SET LS_TAB_FORM = CONCAT(LS_TAB_FORM,' (SELECT MODULE_ITEM_KEY, COALESCE(DESCRIPTION, VALUE) AS c1 
            FROM CUSTOM_DATA WHERE MODULE_ITEM_CODE = 1 AND CUSTOM_DATA_ELEMENTS_ID = ',LI_COST_ELEMENT_ID,')
            AS T',L_CNT,' ON  T',L_CNT,'.MODULE_ITEM_KEY = T',(L_CNT-1),'.MODULE_ITEM_KEY RIGHT JOIN');
        END IF;
       SET L_CNT = L_CNT+1;
       	END IF;
    END LOOP COLUMN_NAME_LOOP;
    CLOSE SEL_COLUMN_NAME;
IF (LS_TAB_FORM IS NULL OR LS_TAB_FORM = ' ' OR  LS_SELECT_FIELD IS NULL OR LS_SELECT_FIELD = ' ') THEN
LEAVE PROC;
END IF;
  SET LS_TAB_FORM = LEFT(LS_TAB_FORM,LENGTH(LS_TAB_FORM)-11);
   IF LS_FLAG = 'C' THEN 
  IF LS_STATUS NOT IN ('ACTIVE', 'PENDING') THEN  
  SET SQL_SAFE_UPDATES = 0;
    DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_ORIGINAL_AWARD_ID ;
  SET SQL_SAFE_UPDATES = 1;  
  END IF;

     SELECT COUNT(1) INTO LI_DEL FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_COPY_AWARD_ID;
	IF LI_DEL >= 1  THEN 
    SET SQL_SAFE_UPDATES = 0;
         DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_COPY_AWARD_ID ;
	SET SQL_SAFE_UPDATES = 1;
    END IF;
  SET LS_QUERY = CONCAT('SELECT ''', AV_COPY_AWARD_ID,'''' ,LS_SELECT_FIELD,' ,NOW()  FROM ',LS_TAB_FORM,' WHERE T1.MODULE_ITEM_KEY = ',AV_ORIGINAL_AWARD_ID);
  ELSE IF LS_FLAG = 'M' THEN  
     SELECT COUNT(1) INTO LI_DEL FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_COPY_AWARD_ID;
	IF LI_DEL >= 1  THEN 
    SET SQL_SAFE_UPDATES = 0;
         DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_COPY_AWARD_ID ;
		 DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_ORIGINAL_AWARD_ID ;
	SET SQL_SAFE_UPDATES = 1;
    END IF;
    SET LS_QUERY = CONCAT('SELECT ''', AV_COPY_AWARD_ID,'''' ,LS_SELECT_FIELD,' ,NOW()  FROM ',LS_TAB_FORM,' WHERE T1.MODULE_ITEM_KEY = ',AV_ORIGINAL_AWARD_ID);
  ELSE
   SELECT COUNT(1) INTO LI_DEL FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_ORIGINAL_AWARD_ID;
	IF LI_DEL >= 1  THEN 
    SET SQL_SAFE_UPDATES = 0;
         DELETE FROM AWARD_CUSTOM_DATA_RT WHERE AWARD_ID = AV_ORIGINAL_AWARD_ID ;
	SET SQL_SAFE_UPDATES = 1;
    END IF;
      SET LS_QUERY = CONCAT('SELECT T1.MODULE_ITEM_KEY ',LS_SELECT_FIELD,' ,NOW()  FROM ',LS_TAB_FORM,' WHERE T1.MODULE_ITEM_KEY = ',AV_ORIGINAL_AWARD_ID);
  END IF;
  END IF;

    SET @sql = CONCAT('    
            INSERT INTO AWARD_CUSTOM_DATA_RT (AWARD_ID,',LS_INSERT,'UPDATE_TIMESTAMP) ' , LS_QUERY
    );
   PREPARE STMT FROM @SQL;
  EXECUTE STMT;
  DEALLOCATE PREPARE STMT;
END PROC
