INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Proposal','Award','FUNDED_AS_PROP',UTC_TIMESTAMP(),'admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Proposal','Award','FUNDED_PROP_AS',UTC_TIMESTAMP(),'admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Proposal','InstituteProposal','REVISION',UTC_TIMESTAMP(),'admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Proposal','ACProtocol','AC_PROTOCOL_DP',UTC_TIMESTAMP(),'admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Proposal','IRBProtocol','IRB_PROTOCOL_DP',UTC_TIMESTAMP(),'admin');
INSERT INTO medusa_relation (SOURCE_MODULE,DESTINATION_MODULE,RELATION_NAME,UPDATE_TIMESTAMP,UPDATE_USER) VALUES ('Proposal','InstituteProposal','SUBMITTED_TO',UTC_TIMESTAMP(),'admin');
