DROP TABLE IF EXISTS `assoc_relation_type_module_mapping`;

CREATE TABLE `assoc_relation_type_module_mapping` (
  `ASSOC_MAPPING_CODE` varchar(3) NOT NULL,
  `ASSOC_RELATION_TYPE_CODE` varchar(3) NOT NULL,
  `MODULE_CODE` int NOT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ASSOC_MAPPING_CODE`),
  KEY `ASSOC_RELATION_TYPE_CODE_FK1` (`ASSOC_RELATION_TYPE_CODE`),
  CONSTRAINT `ASSOC_RELATION_TYPE_CODE_FK1` FOREIGN KEY (`ASSOC_RELATION_TYPE_CODE`) REFERENCES `assoc_relation_type` (`ASSOC_RELATION_TYPE_CODE`)
);

