DROP TABLE IF EXISTS `budget_category_type`;

CREATE TABLE `budget_category_type` (
  `BUDGET_CATEGORY_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `SORT_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`BUDGET_CATEGORY_TYPE_CODE`)
);