DROP TABLE IF EXISTS `business_hour`;

CREATE TABLE `business_hour` (
  `BH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DAY_OF_WEEK` enum('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY') NOT NULL,
  `OPEN_TIME` time DEFAULT NULL,
  `CLOSE_TIME` time DEFAULT NULL,
  `IS_CLOSED` varchar(1) NOT NULL DEFAULT 'N',
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`BH_ID`)
) ;
