

--
--  `coeus_sub_module`
--

DROP TABLE IF EXISTS `coeus_sub_module`;

CREATE TABLE `coeus_sub_module` (
  `COEUS_SUB_MODULE_ID` int(11) NOT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `SUB_MODULE_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` date DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `REQUIRE_UNIQUE_QUESTIONNAIRE` varchar(1) DEFAULT 'N',
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`COEUS_SUB_MODULE_ID`),
  KEY `COEUS_SUB_MODULE_FK1` (`MODULE_CODE`),
  CONSTRAINT `COEUS_SUB_MODULE_FK1` FOREIGN KEY (`MODULE_CODE`) REFERENCES `coeus_module` (`MODULE_CODE`)
);

