DROP TABLE IF EXISTS `document_status`;

CREATE TABLE `document_status` (
  `DOCUMENT_STATUS_CODE` int(11) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`DOCUMENT_STATUS_CODE`)
) ;
