DROP TABLE IF EXISTS `dyn_element_config`;

CREATE TABLE `dyn_element_config` (
  `ELEMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UI_REFERENCE_ID` varchar(30) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `SUB_SECTION_CODE` varchar(5) DEFAULT NULL,
  `SECTION_CODE` varchar(6) DEFAULT NULL,
  `HELP` varchar(2000) DEFAULT NULL,
  `INSTRUCTION` varchar(2000) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ELEMENT_ID`),
  KEY `DYN_ELEMENT_CONFIG_FK1_idx` (`SUB_SECTION_CODE`),
  KEY `DYN_ELEMENT_CONFIG_FK2_idx` (`SECTION_CODE`),
  CONSTRAINT `DYN_ELEMENT_CONFIG_FK1` FOREIGN KEY (`SUB_SECTION_CODE`) REFERENCES `dyn_subsection_config` (`SUB_SECTION_CODE`),
  CONSTRAINT `DYN_ELEMENT_CONFIG_FK2` FOREIGN KEY (`SECTION_CODE`) REFERENCES `dyn_section_config` (`SECTION_CODE`)
) ;
