

--
--  `faq_sub_category`
--

DROP TABLE IF EXISTS `faq_sub_category`;

CREATE TABLE `faq_sub_category` (
  `SUB_CATEGORY_CODE` int(11) NOT NULL,
  `CATEGORY_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`SUB_CATEGORY_CODE`),
  KEY `FAQ_CATEGORY_FK1` (`CATEGORY_CODE`),
  CONSTRAINT `FAQ_CATEGORY_FK1` FOREIGN KEY (`CATEGORY_CODE`) REFERENCES `faq_category` (`CATEGORY_CODE`),
  CONSTRAINT `FAQ_SUB_CATEGORY_FK` FOREIGN KEY (`CATEGORY_CODE`) REFERENCES `faq_category` (`CATEGORY_CODE`)
);

