

--
--  `fibi_workflow_reviewer_detail`
--

DROP TABLE IF EXISTS `fibi_workflow_reviewer_detail`;

CREATE TABLE `fibi_workflow_reviewer_detail` (
  `REVIEWER_DETAILS_ID` int(11) NOT NULL,
  `APPROVAL_STATUS_CODE` varchar(255) DEFAULT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `REVIEW_DATE` date DEFAULT NULL,
  `REVIEWER_PERSON_ID` varchar(255) DEFAULT NULL,
  `REVIEWER_PERSON_NAME` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `WORKFLOW_DETAIL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REVIEWER_DETAILS_ID`),
  KEY `FK1_FIBI_WRKFLW_REVIWER_DTL` (`WORKFLOW_DETAIL_ID`),
  KEY `FK2_FIBI_WRKFLW_REVIWER_DTL` (`APPROVAL_STATUS_CODE`),
  CONSTRAINT `FK1_FIBI_WRKFLW_REVIWER_DTL` FOREIGN KEY (`WORKFLOW_DETAIL_ID`) REFERENCES `fibi_workflow_detail` (`WORKFLOW_DETAIL_ID`),
  CONSTRAINT `FK2_FIBI_WRKFLW_REVIWER_DTL` FOREIGN KEY (`APPROVAL_STATUS_CODE`) REFERENCES `fibi_workflow_status` (`APPROVAL_STATUS_CODE`)
);

