

--
--  `lookup_window`
--

DROP TABLE IF EXISTS `lookup_window`;

CREATE TABLE `lookup_window` (
  `LOOKUP_WINDOW_NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `TABLE_NAME` varchar(30) DEFAULT NULL,
  `COLUMN_NAME` varchar(30) DEFAULT NULL,
  `OTHERS_DISPLAY_COLUMNS` varchar(300) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(40) DEFAULT NULL,
  `DATA_TYPE_CODE` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`LOOKUP_WINDOW_NAME`),
  KEY `LOOKUP_WINDOW_FK2` (`DATA_TYPE_CODE`),
  CONSTRAINT `LOOKUP_WINDOW_FK2` FOREIGN KEY (`DATA_TYPE_CODE`) REFERENCES `custom_data_elements_data_type` (`DATA_TYPE_CODE`)
);

