DROP TABLE IF EXISTS `meta_rule_detail`;

CREATE TABLE `meta_rule_detail` (
  `META_RULE_DETAIL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `META_RULE_ID` int(11) NOT NULL,
  `NODE_NUMBER` int(11) NOT NULL,
  `RULE_ID` int(11) NOT NULL,
  `PARENT_NODE` int(11) NOT NULL,
  `NEXT_NODE` int(11) DEFAULT NULL,
  `NODE_IF_TRUE` int(11) DEFAULT NULL,
  `NODE_IF_FALSE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`META_RULE_DETAIL_ID`),
  KEY `META_RULE_DETAIL_FK1` (`META_RULE_ID`),
  KEY `META_RULE_DETAIL_RULE_FK2` (`RULE_ID`),
  CONSTRAINT `META_RULE_DETAIL_FK1` FOREIGN KEY (`META_RULE_ID`) REFERENCES `meta_rules` (`META_RULE_ID`),
  CONSTRAINT `META_RULE_DETAIL_RULE_FK2` FOREIGN KEY (`RULE_ID`) REFERENCES `business_rules` (`RULE_ID`)
) ;
