DROP TABLE IF EXISTS `meta_rules`;

CREATE TABLE `meta_rules` (
  `META_RULE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `UNIT_NUMBER` varchar(8) NOT NULL,
  `META_RULE_TYPE` varchar(2) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `MODULE_CODE` int(11) NOT NULL,
  `SUB_MODULE_CODE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`META_RULE_ID`),
  KEY `META_RULES_FK1` (`UNIT_NUMBER`),
  CONSTRAINT `META_RULES_FK1` FOREIGN KEY (`UNIT_NUMBER`) REFERENCES `unit` (`UNIT_NUMBER`)
);
