

--
--  `notification_log`
--

DROP TABLE IF EXISTS `notification_log`;

CREATE TABLE `notification_log` (
  `NOTIFICATION_LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOTIFICATION_TYPE_ID` int(11) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `FROM_USER_EMAIL_ID` varchar(200) DEFAULT NULL,
  `TO_USER_EMAIL_ID` varchar(2000) DEFAULT NULL,
  `SUBJECT` varchar(2000) DEFAULT NULL,
  `MESSAGE` longtext,
  `SEND_DATE` datetime DEFAULT NULL,
  `IS_SUCCESS` varchar(1) DEFAULT NULL,
  `ERROR_MESSAGE` varchar(1000) DEFAULT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  PRIMARY KEY (`NOTIFICATION_LOG_ID`),
  KEY `NOTIFICATION_LOG_FK1` (`NOTIFICATION_TYPE_ID`)
);

