

--
--  `person_training_attachment_ext`
--

DROP TABLE IF EXISTS `person_training_attachment_ext`;

CREATE TABLE `person_training_attachment_ext` (
  `TRAINING_ATTACHMENT_EXT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRAINING_ATTACHMENT_ID` int(11) DEFAULT NULL,
  `STATUS` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SOURCE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `PERSON_TRAINING_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`TRAINING_ATTACHMENT_EXT_ID`),
  KEY `PERSON_TRAINING_ATTACHMENT_EXT_FK1` (`TRAINING_ATTACHMENT_ID`),
  KEY `PERSON_TRAINING_ATTACHMENT_EXT_FK2` (`SOURCE_TYPE_CODE`),
  CONSTRAINT `PERSON_TRAINING_ATTACHMENT_EXT_FK1` FOREIGN KEY (`TRAINING_ATTACHMENT_ID`) REFERENCES `person_training_attachment` (`TRAINING_ATTACHMENT_ID`),
  CONSTRAINT `PPERSON_TRAINING_ATTACHMENT_EXT_FK2` FOREIGN KEY (`SOURCE_TYPE_CODE`) REFERENCES `source_type` (`SOURCE_TYPE_CODE`)
);

