DROP TABLE IF EXISTS `person_training`;

CREATE TABLE `person_training` (
  `PERSON_TRAINING_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `DATE_ACKNOWLEDGED` datetime(6) DEFAULT NULL,
  `DATE_REQUESTED` datetime(6) DEFAULT NULL,
  `DATE_SUBMITTED` datetime(6) DEFAULT NULL,
  `FOLLOWUP_DATE` datetime(6) DEFAULT NULL,
  `PERSON_ID` varchar(255) DEFAULT NULL,
  `SCORE` decimal(10,4) DEFAULT NULL,
  `TRAINING_CODE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `IS_NON_EMPLOYEE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`PERSON_TRAINING_ID`),
  KEY `PERSON_TRAINING_FK1` (`TRAINING_CODE`),
  CONSTRAINT `PERSON_TRAINING_FK1` FOREIGN KEY (`TRAINING_CODE`) REFERENCES `training` (`TRAINING_CODE`)
) ;
