

--
--  `pre_review_comment`
--

DROP TABLE IF EXISTS `pre_review_comment`;

CREATE TABLE `pre_review_comment` (
  `PRE_REVIEW_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IS_PRIVATE_COMMENT` varchar(255) DEFAULT NULL,
  `REVIEW_COMMENT` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `PRE_REVIEW_ID` int(11) NOT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `PERSON_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PRE_REVIEW_COMMENT_ID`),
  KEY `PRE_REVIEW_COMMENT_FK1` (`PRE_REVIEW_ID`),
  CONSTRAINT `PRE_REVIEW_COMMENT_FK1` FOREIGN KEY (`PRE_REVIEW_ID`) REFERENCES `pre_review` (`PRE_REVIEW_ID`)
);

