

--
--  `pre_review_attachment`
--

DROP TABLE IF EXISTS `pre_review_attachment`;

CREATE TABLE `pre_review_attachment` (
  `PRE_REVIEW_ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `PRE_REVIEW_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `PRE_REVIEW_COMMENT_ID` int(11) NOT NULL,
  PRIMARY KEY (`PRE_REVIEW_ATTACHMENT_ID`),
  KEY `PRE_REVIEW_ATTACHMENT_FK1` (`PRE_REVIEW_COMMENT_ID`),
  CONSTRAINT `PRE_REVIEW_ATTACHMENT_FK1` FOREIGN KEY (`PRE_REVIEW_COMMENT_ID`) REFERENCES `pre_review_comment` (`PRE_REVIEW_COMMENT_ID`)
);

