

--
--  `quest_usage`
--

DROP TABLE IF EXISTS `quest_usage`;

CREATE TABLE `quest_usage` (
  `QUESTIONNAIRE_USAGE_ID` int(11) NOT NULL,
  `MODULE_ITEM_CODE` int(11) DEFAULT NULL,
  `MODULE_SUB_ITEM_CODE` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_ID` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_LABEL` varchar(200) DEFAULT NULL,
  `IS_MANDATORY` varchar(1) DEFAULT NULL,
  `RULE_ID` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` date DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `SORT_ORDER` int(11) DEFAULT NULL,
  `TRIGGER_POST_EVALUATION` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`QUESTIONNAIRE_USAGE_ID`),
  KEY `QUEST_USAGE_FK1` (`QUESTIONNAIRE_ID`),
  CONSTRAINT `QUEST_USAGE_FK1` FOREIGN KEY (`QUESTIONNAIRE_ID`) REFERENCES `quest_header` (`QUESTIONNAIRE_ID`)
);

