

--
--  `quest_column_nextvalue`
--

DROP TABLE IF EXISTS `quest_column_nextvalue`;

CREATE TABLE `quest_column_nextvalue` (
  `QUESTIONNAIRE_ID` int(11) NOT NULL,
  `QUESTIONNAIRE_NUMBER` int(11) DEFAULT NULL,
  `QUESTION_ID` int(11) DEFAULT NULL,
  `QUESTION_NUMBER` int(11) DEFAULT NULL,
  `QUESTION_CONDITION_ID` int(11) DEFAULT NULL,
  `QUESTION_OPTION_ID` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_ANS_HEADER_ID` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_ANSWER_ID` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_ANSWER_ATT_ID` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_USAGE_ID` int(11) DEFAULT NULL,
  `QUESTIONNAIRE_ANSWER_TABLE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`QUESTIONNAIRE_ID`)
);

