

--
--  `rate_type`
--

DROP TABLE IF EXISTS `rate_type`;

CREATE TABLE `rate_type` (
  `RATE_CLASS_CODE` varchar(3) NOT NULL,
  `RATE_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  PRIMARY KEY (`RATE_CLASS_CODE`,`RATE_TYPE_CODE`),
  CONSTRAINT `RATE_TYPE_FK1` FOREIGN KEY (`RATE_CLASS_CODE`) REFERENCES `rate_class` (`RATE_CLASS_CODE`)
);

