

--
--  `rate_class`
--

DROP TABLE IF EXISTS `rate_class`;

CREATE TABLE `rate_class` (
  `RATE_CLASS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `RATE_CLASS_TYPE` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`RATE_CLASS_CODE`),
  KEY `RATE_CLASS_FK1` (`RATE_CLASS_TYPE`),
  CONSTRAINT `RATE_CLASS_FK1` FOREIGN KEY (`RATE_CLASS_TYPE`) REFERENCES `rate_class_type` (`RATE_CLASS_TYPE`)
);

