DROP TABLE IF EXISTS `report_class`;

CREATE TABLE `report_class` (
  `REPORT_CLASS_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ATTACHMENT_OR_REPORT` varchar(1) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) NOT NULL DEFAULT 'Y',
  `COPY_REPORT` varchar(1) DEFAULT 'N',
  `COPY_FROM` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`REPORT_CLASS_CODE`)
) ;
