

--
--  `research_type_area`
--

DROP TABLE IF EXISTS `research_type_area`;

CREATE TABLE `research_type_area` (
  `RESRCH_TYPE_AREA_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(4000) DEFAULT NULL,
  `RESRCH_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `OLD_PK` varchar(3) DEFAULT NULL,
  `STYLED_AREA_OF_RESEARCH` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`RESRCH_TYPE_AREA_CODE`),
  KEY `RESEARCH_TYPE_AREA_FK1` (`RESRCH_TYPE_CODE`),
  CONSTRAINT `RESEARCH_TYPE_AREA_FK1` FOREIGN KEY (`RESRCH_TYPE_CODE`) REFERENCES `research_type` (`RESRCH_TYPE_CODE`)
);

