

--
--  `role_rights_audit_tab`
--

DROP TABLE IF EXISTS `role_rights_audit_tab`;

CREATE TABLE `role_rights_audit_tab` (
  `ROLE_RIGHTS_AUDIT_TAB_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SOURCE` varchar(25) NOT NULL,
  `MODE` varchar(10) NOT NULL,
  `OLD_RLE_RIGHTS_ID` decimal(22,0) DEFAULT NULL,
  `NEW_RLE_RIGHTS_ID` decimal(22,0) DEFAULT NULL,
  `OLD_PER_ROLES_ID` decimal(22,0) DEFAULT NULL,
  `NEW_PER_ROLES_ID` decimal(22,0) DEFAULT NULL,
  `OLD_PERSON_ID` varchar(40) DEFAULT NULL,
  `NEW_PERSON_ID` varchar(40) DEFAULT NULL,
  `OLD_ROLE_ID` int(11) DEFAULT NULL,
  `NEW_ROLE_ID` int(11) DEFAULT NULL,
  `OLD_ROLE_NAME` varchar(50) DEFAULT NULL,
  `NEW_ROLE_NAME` varchar(50) DEFAULT NULL,
  `OLD_RIGHT_ID` int(11) DEFAULT NULL,
  `NEW_RIGHT_ID` int(11) DEFAULT NULL,
  `OLD_UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `NEW_UNIT_NUMBER` varchar(8) DEFAULT NULL,
  `OLD_DESCEND_FLG` varchar(1) DEFAULT NULL,
  `NEW_DESCEND_FLG` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  `UPDATE_USER` varchar(60) NOT NULL,
  PRIMARY KEY (`ROLE_RIGHTS_AUDIT_TAB_ID`)
);

