

--
--  `section_module`
--

DROP TABLE IF EXISTS `section_module`;

CREATE TABLE `section_module` (
  `MODULE_CODE` int(11) NOT NULL,
  `SECTION_CODE` varchar(4) NOT NULL,
  `SUB_MODULE_CODE` int(11) NOT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`MODULE_CODE`,`SECTION_CODE`,`SUB_MODULE_CODE`),
  KEY `SECTION_MODULE_FK1` (`SECTION_CODE`),
  CONSTRAINT `SECTION_MODULE_FK1` FOREIGN KEY (`SECTION_CODE`) REFERENCES `section_type` (`SECTION_CODE`)
);

