SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `sponsor_type`;

CREATE TABLE `sponsor_type` (
  `SPONSOR_TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(100) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT 'Y',
  `FROM_GL_MAPPING` varchar(60) DEFAULT NULL,
  `TO_GL_MAPPING` varchar(60) DEFAULT NULL,
  `BUDGET_CATEGORY_CODE` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`SPONSOR_TYPE_CODE`),
  KEY `SPONSOR_TYPE_FK1` (`BUDGET_CATEGORY_CODE`),
  CONSTRAINT `SPONSOR_TYPE_FK1` FOREIGN KEY (`BUDGET_CATEGORY_CODE`) REFERENCES `budget_category` (`BUDGET_CATEGORY_CODE`)
);

SET foreign_key_checks = 1;