SET foreign_key_checks = 0;
DROP TABLE IF EXISTS `sr_type`;
CREATE TABLE `sr_type` (
  `TYPE_CODE` varchar(3) NOT NULL,
  `DESCRIPTION` varchar(500) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `INSTRUCTION` varchar(4000) DEFAULT NULL,
  `SUBJECT` varchar(255) DEFAULT NULL,
  `IS_ACTIVE` varchar(255) DEFAULT NULL,
  `sort_order` int(11) DEFAULT NULL,
  `CATEGORY_CODE` varchar(3) DEFAULT NULL,
  `ADMIN_GROUP_ID` int(11) DEFAULT NULL,
  `HELP_TEXT` varchar(1000) DEFAULT NULL,
  `STATUS_CODE` int(11) DEFAULT NULL,
  PRIMARY KEY (`TYPE_CODE`),
  KEY `SR_TYPE_IX21` (`TYPE_CODE`),
  KEY `SR_TYPE_FK1` (`ADMIN_GROUP_ID`),
  KEY `SR_TYPE_FK2` (`STATUS_CODE`),
  KEY `SR_TYPE_FK3` (`CATEGORY_CODE`),
  CONSTRAINT `SR_TYPE_FK1` FOREIGN KEY (`ADMIN_GROUP_ID`) REFERENCES `admin_group` (`ADMIN_GROUP_ID`),
  CONSTRAINT `SR_TYPE_FK2` FOREIGN KEY (`STATUS_CODE`) REFERENCES `sr_status` (`STATUS_CODE`),
  CONSTRAINT `SR_TYPE_FK3` FOREIGN KEY (`CATEGORY_CODE`) REFERENCES `sr_category` (`CATEGORY_CODE`)
) ;
SET foreign_key_checks = 1;