

--
--  `workflow_reviewer_attmnts`
--

DROP TABLE IF EXISTS `workflow_reviewer_attmnts`;

CREATE TABLE `workflow_reviewer_attmnts` (
  `WORKFLOW_REVIEWER_ATTMNTS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(255) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime(6) DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `WORKFLOW_REVIEWER_COMMENTS_ID` int(11) NOT NULL,
  PRIMARY KEY (`WORKFLOW_REVIEWER_ATTMNTS_ID`),
  KEY `WORKFLOW_REVIEWER_ATTMNTS_FK2` (`WORKFLOW_REVIEWER_COMMENTS_ID`),
  CONSTRAINT `WORKFLOW_REVIEWER_ATTMNTS_FK2` FOREIGN KEY (`WORKFLOW_REVIEWER_COMMENTS_ID`) REFERENCES `workflow_reviewer_comments` (`WORKFLOW_REVIEWER_COMMENTS_ID`)
);

