

--
--  `workflow_feedback_type`
--

DROP TABLE IF EXISTS `workflow_feedback_type`;

CREATE TABLE `workflow_feedback_type` (
  `FEEDBACK_TYPE_CODE` varchar(3) NOT NULL,
  `ROLE_TYPE_CODE` int(11) DEFAULT NULL,
  `MODULE_CODE` int(11) DEFAULT NULL,
  `SUB_MODULE_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`FEEDBACK_TYPE_CODE`),
  KEY `WORKFLOW_FEEDBACK_TYPE_FK1` (`ROLE_TYPE_CODE`),
  CONSTRAINT `WORKFLOW_FEEDBACK_TYPE_FK1` FOREIGN KEY (`ROLE_TYPE_CODE`) REFERENCES `person_role_type` (`ROLE_TYPE_CODE`)
);

