

--
--  `workflow_reviewer_detail`
--

DROP TABLE IF EXISTS `workflow_reviewer_detail`;

CREATE TABLE `workflow_reviewer_detail` (
  `REVIEWER_DETAILS_ID` int(11) NOT NULL,
  `APPROVAL_STATUS` varchar(255) DEFAULT NULL,
  `COMMENTS` varchar(255) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `REVIEW_DATE` date DEFAULT NULL,
  `REVIEWER_PERSON_ID` varchar(255) DEFAULT NULL,
  `REVIEWER_PERSON_NAME` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `WORKFLOW_DETAIL_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`REVIEWER_DETAILS_ID`),
  KEY `WRKFLW_REVIWER_DTL_FK1` (`WORKFLOW_DETAIL_ID`),
  KEY `WRKFLW_REVIWER_DTL_FK2` (`APPROVAL_STATUS`),
  CONSTRAINT `WRKFLW_REVIWER_DTL_FK1` FOREIGN KEY (`WORKFLOW_DETAIL_ID`) REFERENCES `workflow_detail` (`WORKFLOW_DETAIL_ID`),
  CONSTRAINT `WRKFLW_REVIWER_DTL_FK2` FOREIGN KEY (`APPROVAL_STATUS`) REFERENCES `workflow_status` (`APPROVAL_STATUS`)
);

