

--
--  `workflow_attachment`
--

DROP TABLE IF EXISTS `workflow_attachment`;

CREATE TABLE `workflow_attachment` (
  `ATTACHMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ATTACHMENT` longblob,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(300) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(255) DEFAULT NULL,
  `WORKFLOW_DETAIL_ID` int(11) DEFAULT NULL,
  `REVIEWER_DETAILS_ID` int(11) DEFAULT NULL,
  `FILE_DATA_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  KEY `WORKFLOW_ATTACHMENT_FK1` (`WORKFLOW_DETAIL_ID`),
  KEY `WORKFLOW_ATTACHMENT_FK2` (`REVIEWER_DETAILS_ID`),
  CONSTRAINT `WORKFLOW_ATTACHMENT_FK1` FOREIGN KEY (`WORKFLOW_DETAIL_ID`) REFERENCES `workflow_detail` (`WORKFLOW_DETAIL_ID`),
  CONSTRAINT `WORKFLOW_ATTACHMENT_FK2` FOREIGN KEY (`REVIEWER_DETAILS_ID`) REFERENCES `workflow_reviewer_detail` (`REVIEWER_DETAILS_ID`),
  CONSTRAINT `WORKFLOW_ATTACHMENT_FK3` FOREIGN KEY (`REVIEWER_DETAILS_ID`) REFERENCES `workflow_reviewer_detail` (`REVIEWER_DETAILS_ID`)
);

