-- `AGREEMENT_CUSTOM_DATA_RT_FULL_SYNC`; 

CREATE PROCEDURE `AGREEMENT_CUSTOM_DATA_RT_FULL_SYNC`()
BEGIN
    
    DECLARE LS_MODULE_ITEM_KEY VARCHAR(4000); 
    DECLARE NOT_FOUND INT DEFAULT 0;
       
    DECLARE SEL_MODULE_ITEM_KEY CURSOR FOR
        SELECT DISTINCT MODULE_ITEM_KEY FROM CUSTOM_DATA WHERE MODULE_ITEM_CODE = 13
        AND MODULE_ITEM_KEY IN (SELECT AGREEMENT_REQUEST_ID FROM AGREEMENT_HEADER WHERE AGREEMENT_SEQUENCE_STATUS = 'ACTIVE');
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET NOT_FOUND = 1;
   
call ADD_FULL_COLUMN_IN_AGREEMENT_CUSTOM_DATA_RT()  ;  
OPEN SEL_MODULE_ITEM_KEY;
    
    SEL_MODULE_ITEM_KEY: LOOP
        SET NOT_FOUND = 0;
        FETCH SEL_MODULE_ITEM_KEY INTO LS_MODULE_ITEM_KEY ;
        IF NOT_FOUND = 1 THEN 
            LEAVE SEL_MODULE_ITEM_KEY;
        END IF;
 	CALL AGREEMENT_CUSTOM_DATA_RT_SYNC_BY_AGREEMENT_ID(LS_MODULE_ITEM_KEY,NULL);            
        
    END LOOP SEL_MODULE_ITEM_KEY;
    CLOSE SEL_MODULE_ITEM_KEY;
  
  SELECT 1 AS 'SUCCESS';
END
