CREATE PROCEDURE `DMP_REPORT_SYNC`()
BEGIN
DECLARE LD_SYNC_INTERVAL_START_TIME  DATETIME;
DECLARE LD_SYNC_INTERVAL_END_TIME    DATETIME;
DECLARE LD_CURRENT_TIMESTAMP         DATETIME;
DECLARE LS_DYN_SQL                   LONGTEXT;
DECLARE LS_DYN_SQL_SEL               LONGTEXT;
DECLARE LS_SEL_STMT                  LONGTEXT;
DECLARE AWARD_IDS                    LONGTEXT;
DECLARE EXIT HANDLER FOR SQLEXCEPTION
BEGIN
SELECT CONCAT('Count of failed : ', (SELECT COUNT(1) FROM TEMP_DMP_AWARDS)) AS ''
	UNION
SELECT 'Please refer the below list for the list of records that failed to sync';
SELECT * FROM TEMP_DMP_AWARDS;
TRUNCATE TEMP_DMP_AWARDS;
END;

SELECT  UTC_TIMESTAMP() INTO LD_CURRENT_TIMESTAMP;
SELECT  DATE_SUB(DMP_LAST_SYNC_TIMESTAMP,INTERVAL 4 MINUTE) INTO LD_SYNC_INTERVAL_START_TIME FROM REPORT_LAST_SYNC_TIME;
SELECT  DATE_SUB(UTC_TIMESTAMP(), INTERVAL 3 MINUTE) INTO LD_SYNC_INTERVAL_END_TIME;

SET SQL_SAFE_UPDATES = 0;

SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

TRUNCATE TEMP_DMP_AWARDS;

INSERT INTO TEMP_DMP_AWARDS (AWARD_ID,AWARD_NUMBER)  
SELECT A3.AWARD_ID,A3.AWARD_NUMBER   
FROM AWARD A3  
WHERE A3.DOCUMENT_UPDATE_TIMESTAMP BETWEEN LD_SYNC_INTERVAL_START_TIME AND LD_SYNC_INTERVAL_END_TIME  
AND (
    (A3.AWARD_SEQUENCE_STATUS = 'PENDING'  
        AND A3.SEQUENCE_NUMBER = 1  
        AND EXISTS (SELECT 1  
                    FROM QUEST_ANSWER_HEADER QAH  
                    WHERE QAH.MODULE_ITEM_CODE = 1					
                    AND QAH.MODULE_SUB_ITEM_CODE = 3  
                    AND QAH.MODULE_ITEM_KEY = A3.AWARD_ID
                    AND QAH.UPDATE_TIMESTAMP BETWEEN LD_SYNC_INTERVAL_START_TIME AND LD_SYNC_INTERVAL_END_TIME))
	OR  
    ((A3.AWARD_SEQUENCE_STATUS = 'ACTIVE') AND EXISTS (
    SELECT 1 FROM AWARD WHERE AWARD_NUMBER =A3.AWARD_NUMBER  GROUP BY AWARD_NUMBER HAVING COUNT(AWARD_NUMBER) = 2))
    OR  
    ((A3.AWARD_SEQUENCE_STATUS = 'ACTIVE') AND EXISTS (SELECT 1 
			   FROM AWARD 
			   WHERE AWARD_NUMBER = A3.AWARD_NUMBER 
				 AND AWARD_SEQUENCE_STATUS = 'ARCHIVE'
				 AND AWARD_VARIATION_TYPE_CODE IN ( SELECT B.TYPE_CODE 
													FROM SECTION_TYPE A,
														 VARIATION_SECTION_MAPPING B 
												   WHERE A.DESCRIPTION = 'DMP QUESTIONNAIRE'
													 AND B.SECTION_CODE= A.SECTION_CODE)
				  AND DOCUMENT_UPDATE_TIMESTAMP BETWEEN LD_SYNC_INTERVAL_START_TIME AND LD_SYNC_INTERVAL_END_TIME))
	OR ((A3.AWARD_ID IN (
	  SELECT AW.AWARD_ID FROM AWARD AW
	  INNER JOIN QUEST_ANSWER_HEADER T1 ON  AW.AWARD_ID = T1.MODULE_ITEM_KEY
	  INNER JOIN QUEST_ANSWER T3 ON T1.QUESTIONNAIRE_ANS_HEADER_ID= T3.QUESTIONNAIRE_ANS_HEADER_ID
	  WHERE  AW.AWARD_SEQUENCE_STATUS = 'ACTIVE' AND T1.MODULE_ITEM_CODE = 1 AND T1.MODULE_SUB_ITEM_CODE = 3
	 AND NOT EXISTS(SELECT 1 FROM AWARD_DMP_DATASET_RT WHERE AWARD_ID = AW.AWARD_ID)))));

COMMIT;
													 	 								

SET SESSION group_concat_max_len = 4294967295;
				SELECT GROUP_CONCAT(A3.AWARD_ID) INTO AWARD_IDS FROM (
				SELECT AWARD_ID FROM AWARD A 
				INNER JOIN QUEST_ANSWER_HEADER QAH  
				WHERE QAH.MODULE_ITEM_CODE = 1					
				AND QAH.MODULE_SUB_ITEM_CODE = 3  
				AND QAH.MODULE_ITEM_KEY = A.AWARD_ID
				AND A.AWARD_SEQUENCE_STATUS ='PENDING'
				AND QAH.UPDATE_TIMESTAMP BETWEEN LD_SYNC_INTERVAL_START_TIME AND LD_SYNC_INTERVAL_END_TIME
				UNION
				SELECT A3.AWARD_ID FROM AWARD A3
				WHERE A3.DOCUMENT_UPDATE_TIMESTAMP BETWEEN LD_SYNC_INTERVAL_START_TIME AND LD_SYNC_INTERVAL_END_TIME
				AND (A3.AWARD_SEQUENCE_STATUS IN('ARCHIVE','CANCELLED') AND A3.SEQUENCE_NUMBER = 1)
				UNION
				SELECT A3.AWARD_ID FROM AWARD A3  WHERE
				A3.AWARD_SEQUENCE_STATUS =  'ACTIVE' 
				AND  EXISTS (SELECT 1 
							FROM AWARD 
							WHERE AWARD_NUMBER = A3.AWARD_NUMBER 
								AND AWARD_SEQUENCE_STATUS = 'ARCHIVE'
								AND AWARD_VARIATION_TYPE_CODE IN ( SELECT B.TYPE_CODE FROM SECTION_TYPE A, VARIATION_SECTION_MAPPING B WHERE A.DESCRIPTION = 'DMP QUESTIONNAIRE' AND B.SECTION_CODE= A.SECTION_CODE)
								AND DOCUMENT_UPDATE_TIMESTAMP BETWEEN LD_SYNC_INTERVAL_START_TIME AND LD_SYNC_INTERVAL_END_TIME))A3;
		IF AWARD_IDS IS NOT NULL THEN
		SET LS_DYN_SQL  = CONCAT('DELETE FROM AWARD_DMP_DATASET_RT T2
		WHERE T2.AWARD_ID IN(', AWARD_IDS, ')');

		SET @QUERY_STATEMENT = LS_DYN_SQL;
		PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
		EXECUTE EXECUTABLE_STAEMENT;
		END IF;
        
        BEGIN
        DECLARE DONE1 INT DEFAULT FALSE;

        DECLARE CUR_SEL CURSOR FOR
        SELECT
                CONCAT(
                  'MAX(CASE WHEN T1.QUESTION_NUMBER =',
                  Q1.QUESTION_NUMBER,
                  ' THEN S1.ANSWER END) AS `',
                  Q1.SORT_ORDER, '`'
                )
        FROM
          QUEST_QUESTION Q1 LEFT OUTER JOIN QUEST_HEADER QH ON Q1.QUESTIONNAIRE_ID = QH.QUESTIONNAIRE_ID

          WHERE Q1.QUESTIONNAIRE_ID = QH.QUESTIONNAIRE_ID AND QH.IS_FINAL ='Y' AND QH.QUESTIONNAIRE_NUMBER = 1204 ORDER BY Q1.SORT_ORDER;

        DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE1 = TRUE;

        OPEN CUR_SEL;

        INSERT_LOOP1: LOOP
        FETCH CUR_SEL INTO
        LS_DYN_SQL_SEL;

        IF DONE1 THEN
                LEAVE INSERT_LOOP1;
        END IF;

                SET LS_SEL_STMT:= CONCAT(IFNULL(LS_SEL_STMT,''),',',LS_DYN_SQL_SEL);

        END LOOP;
        CLOSE CUR_SEL;

                SELECT TRIM(TRAILING ',' FROM LS_SEL_STMT) INTO LS_SEL_STMT FROM DUAL;
        END;

SET SESSION group_concat_max_len = 4294967295;
SET LS_DYN_SQL = CONCAT(' INSERT INTO award_dmp_dataset_rt(AWARD_ID,AWARD_NUMBER,VERSION_NUMBER,QUESTIONNAIRE_ID,SUBMISSION_DATE,LAST_SYNC_TIME,QUESTION_1_A,QUESTION_1_B,QUESTION_2_A,
QUESTION_2_B,QUESTION_3_A,QUESTION_3_A9,QUESTION_3_A8,
QUESTION_3_A7,QUESTION_3_A6,QUESTION_3_A5,QUESTION_3_A4,QUESTION_3_A3,QUESTION_3_A2,
QUESTION_3_A1,QUESTION_3_B,QUESTION_3_C,QUESTION_4_A,QUESTION_4_B1,QUESTION_4_B2,
QUESTION_4_C,QUESTION_4_D1,QUESTION_4_D2,QUESTION_5_A,QUESTION_5_B,QUESTION_5_B1,
QUESTION_5_C,QUESTION_5_D,QUESTION_5_E,QUESTION_5_F,QUESTION_5_F1,
QUESTION_6_A,QUESTION_6_A3,QUESTION_6_A2,QUESTION_6_A1B,QUESTION_6_A1A,QUESTION_6_A1,
QUESTION_6_A2B,QUESTION_6_A2A,QUESTION_7_A,QUESTION_7_A1,QUESTION_7_B,QUESTION_7_B2,
QUESTION_7_B1,QUESTION_8_A,QUESTION_8_B,QUESTION_8_C,QUESTION_9A,QUESTION_9_A1,
QUESTION_9_A2,QUESTION_9_A3,QUESTION_9_A4,QUESTION_9_A5)
                                   SELECT       A1.AWARD_ID,
                                   A1.AWARD_NUMBER,
                                                         FN_COUNT_OF_DMP_UPDATE(A1.AWARD_NUMBER),
                                                        T1.QUESTIONNAIRE_ID,S1.SUBMISSION_DATE,UTC_TIMESTAMP() ', LS_SEL_STMT, '
                   FROM QUEST_QUESTION T1
                                   LEFT OUTER JOIN(
                                                                   SELECT
                                                                                T3.QUESTION_ID,
                                                                                T2.MODULE_ITEM_KEY,
                                                                                CASE WHEN T2.QUESTIONNAIRE_COMPLETED_FLAG=''Y'' THEN T2.UPDATE_TIMESTAMP ELSE NULL END AS SUBMISSION_DATE,
                                                                                GROUP_CONCAT(DISTINCT T3.ANSWER ORDER BY T3.QUESTIONNAIRE_ANSWER_ID) AS ANSWER, T2.MODULE_SUB_ITEM_KEY
                                                                        FROM QUEST_ANSWER_HEADER T2
                                                                        INNER JOIN QUEST_QUESTION QQ ON QQ.QUESTIONNAIRE_ID = T2.QUESTIONNAIRE_ID
                                                                        LEFT OUTER JOIN QUEST_ANSWER T3 ON T2.QUESTIONNAIRE_ANS_HEADER_ID = T3.QUESTIONNAIRE_ANS_HEADER_ID
                                                                        WHERE T2.MODULE_ITEM_CODE = 1
                                                                        AND T2.MODULE_SUB_ITEM_CODE = 3
                                                                        AND T2.QUESTIONNAIRE_ID = (SELECT MAX(S.QUESTIONNAIRE_ID) FROM QUEST_ANSWER_HEADER S 
							  INNER JOIN QUEST_HEADER T5 ON S.QUESTIONNAIRE_ID = T5.QUESTIONNAIRE_ID 
                              WHERE S.MODULE_ITEM_KEY = T2.MODULE_ITEM_KEY AND S.MODULE_SUB_ITEM_KEY = T2.MODULE_SUB_ITEM_KEY
                              AND T5.QUESTIONNAIRE_NUMBER = 1204
			 AND S.MODULE_ITEM_CODE = 1
                              AND S.MODULE_SUB_ITEM_CODE = 3)    
                                                                      AND T2.MODULE_ITEM_KEY IN(SELECT AWARD_ID FROM TEMP_DMP_AWARDS)
                                                                        GROUP BY T3.QUESTION_ID,T3.QUESTIONNAIRE_ANS_HEADER_ID
                                                                )S1 ON T1.QUESTION_ID = S1.QUESTION_ID
                                    INNER JOIN TEMP_DMP_AWARDS A1 ON A1.AWARD_ID = S1.MODULE_ITEM_KEY
                    WHERE T1.QUESTIONNAIRE_ID = (SELECT MAX(S.QUESTIONNAIRE_ID) FROM QUEST_ANSWER_HEADER S 
			 INNER JOIN QUEST_HEADER T5 ON S.QUESTIONNAIRE_ID = T5.QUESTIONNAIRE_ID 
                              WHERE S.MODULE_ITEM_KEY = S1.MODULE_ITEM_KEY AND S.MODULE_SUB_ITEM_KEY = S1.MODULE_SUB_ITEM_KEY
                              AND T5.QUESTIONNAIRE_NUMBER = 1204
			AND S.MODULE_ITEM_CODE = 1
                              AND S.MODULE_SUB_ITEM_CODE = 3)
                                   GROUP BY T1.QUESTIONNAIRE_ID,S1.MODULE_ITEM_KEY'
                                   );
SET @QUERY_STATEMENT = LS_DYN_SQL; 
PREPARE EXECUTABLE_STAEMENT FROM @QUERY_STATEMENT;
EXECUTE EXECUTABLE_STAEMENT;



SET SQL_SAFE_UPDATES = 0;

DELETE FROM award_dmp_dataset_rt WHERE AWARD_ID NOT IN (SELECT AWARD_ID FROM AWARD);
UPDATE REPORT_LAST_SYNC_TIME SET DMP_LAST_SYNC_TIMESTAMP = LD_CURRENT_TIMESTAMP;
TRUNCATE TEMP_DMP_AWARDS;
SET SQL_SAFE_UPDATES = 1;
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
 SELECT 1 AS SUCCESS FROM DUAL;

END
