

--
--  `coi_int_stage_dev_qnr_answer`
--

DROP TABLE IF EXISTS `coi_int_stage_dev_qnr_answer`;

CREATE TABLE `coi_int_stage_dev_qnr_answer` (
  `STAGE_PROPOSAL_QNR_ANSWER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PROPOSAL_NUMBER` varchar(20) NOT NULL,
  `KEY_PERSON_ID` varchar(40) NOT NULL,
  `QUESTIONNAIRE_ID` int(11) DEFAULT NULL,
  `QUESTION_ID` int(11) DEFAULT NULL,
  `ANSWER` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `ATTRIBUTE_1_LABEL` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_1_VALUE` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_2_LABEL` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_2_VALUE` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_3_LABEL` varchar(90) DEFAULT NULL,
  `ATTRIBUTE_3_VALUE` varchar(90) DEFAULT NULL,
  PRIMARY KEY (`STAGE_PROPOSAL_QNR_ANSWER_ID`)
) ;



