

--
--  `coi_travel_funding_agencies`
--

DROP TABLE IF EXISTS `coi_travel_funding_agencies`;

CREATE TABLE `coi_travel_funding_agencies` (
  `TRAVEL_FUNDING_AGENCY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRAVEL_DISCLOSURE_ID` int(11) DEFAULT NULL,
  `FUNDING_AGENCY_CODE` varchar(3) DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`TRAVEL_FUNDING_AGENCY_ID`),
  KEY `COI_TRAVEL_FUNDING_AGENCIES_FK1_idx` (`TRAVEL_DISCLOSURE_ID`),
  KEY `COI_TRAVEL_FUNDING_AGENCIES_FK2_idx` (`FUNDING_AGENCY_CODE`),
  CONSTRAINT `COI_TRAVEL_FUNDING_AGENCIES_FK1` FOREIGN KEY (`TRAVEL_DISCLOSURE_ID`) REFERENCES `coi_travel_disclosure` (`TRAVEL_DISCLOSURE_ID`),
  CONSTRAINT `COI_TRAVEL_FUNDING_AGENCIES_FK2` FOREIGN KEY (`FUNDING_AGENCY_CODE`) REFERENCES `coi_travel_funding_agency_type` (`FUNDING_AGENCY_CODE`)
) ;



