

--
--  `coi_review_comment`
--

DROP TABLE IF EXISTS `coi_review_comment`;

CREATE TABLE `coi_review_comment` (
  `COI_REVIEW_COMMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COI_REVIEW_ID` int(11) DEFAULT NULL,
  `COI_SECTIONS_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COMMENT` varchar(2000) DEFAULT NULL,
  `COI_REVIEW_ACTIVITY_ID` varchar(3) DEFAULT NULL,
  `COI_PARENT_COMMENT_ID` int(11) DEFAULT NULL,
  `COI_SUB_SECTIONS_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `COMMENTED_BY_PERSON_ID` varchar(40) DEFAULT NULL,
  `IS_PRIVATE` varchar(1) DEFAULT NULL,
  `DISCLOSURE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`COI_REVIEW_COMMENT_ID`),
  KEY `COI_REVIEW_COMMENT_FK1` (`COI_REVIEW_ID`),
  KEY `COI_REVIEW_COMMENT_FK2` (`COI_SECTIONS_TYPE_CODE`),
  KEY `COI_REVIEW_COMMENT_FK5` (`COI_REVIEW_ACTIVITY_ID`),
  KEY `COI_REVIEW_COMMENT_FK6` (`DISCLOSURE_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK1` FOREIGN KEY (`COI_REVIEW_ID`) REFERENCES `coi_review` (`COI_REVIEW_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK2` FOREIGN KEY (`COI_SECTIONS_TYPE_CODE`) REFERENCES `coi_sections_type` (`COI_SECTIONS_TYPE_CODE`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK5` FOREIGN KEY (`COI_REVIEW_ACTIVITY_ID`) REFERENCES `coi_review_activity` (`COI_REVIEW_ACTIVITY_ID`),
  CONSTRAINT `COI_REVIEW_COMMENT_FK6` FOREIGN KEY (`DISCLOSURE_ID`) REFERENCES `coi_disclosure` (`DISCLOSURE_ID`)
) ;



