

--
--  `coi_with_person`
--

DROP TABLE IF EXISTS `coi_with_person`;

CREATE TABLE `coi_with_person` (
  `COI_WITH_PERSON_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `EXTERNAL_REVIEWER_ID` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_WITH_PERSON_ID`),
  KEY `COI_WITH_PERSON_MAPPING_FK1` (`EXTERNAL_REVIEWER_ID`),
  KEY `COI_WITH_PERSON_MAPPING_FK2` (`PERSON_ID`),
  CONSTRAINT `COI_WITH_PERSON_MAPPING_FK1` FOREIGN KEY (`EXTERNAL_REVIEWER_ID`) REFERENCES `external_reviewer` (`EXTERNAL_REVIEWER_ID`),
  CONSTRAINT `COI_WITH_PERSON_MAPPING_FK2` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`)
) ;



