

--
--  `disclosure_mv`
--

DROP TABLE IF EXISTS `disclosure_mv`;

CREATE TABLE `disclosure_mv` (
  `DOCUMENT_NUMBER` varchar(40) DEFAULT NULL,
  `COI_DISCLOSURE_ID` decimal(12,0) NOT NULL,
  `COI_DISCLOSURE_NUMBER` varchar(20) DEFAULT NULL,
  `SEQUENCE_NUMBER` decimal(6,0) DEFAULT NULL,
  `PERSON_ID` varchar(40) DEFAULT NULL,
  `FULL_NAME` varchar(163) DEFAULT NULL,
  `DISCLOSURE_DISPOSITION_CODE` decimal(3,0) DEFAULT NULL,
  `DISCLOSURE_DISPOSITION` varchar(200) DEFAULT NULL,
  `DISCLOSURE_STATUS_CODE` decimal(3,0) DEFAULT NULL,
  `DISCLOSURE_STATUS` varchar(200) DEFAULT NULL,
  `MODULE_ITEM_KEY` varchar(20) DEFAULT NULL,
  `DISC_ACTIVE_STATUS` decimal(1,0) DEFAULT NULL,
  `EXPIRATION_DATE` date DEFAULT NULL,
  `UPDATE_TIMESTAMP` date DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`COI_DISCLOSURE_ID`)
) ;



