

--
--  `entity_telephone`
--

DROP TABLE IF EXISTS `entity_telephone`;

CREATE TABLE `entity_telephone` (
  `ENTITY_TELEPHONE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `INT_DIALING_CODE` varchar(5) DEFAULT NULL,
  `TELEPHONE_NUMBER` bigint(20) DEFAULT NULL,
  `UPDATE_TIMESTAMP` timestamp NULL DEFAULT NULL,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_TELEPHONE_ID`),
  KEY `ENTITY_TELEPHONE_FK1_idx` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_TELEPHONE_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`)
) ;



