

--
--  `entity_mailing_address`
--

DROP TABLE IF EXISTS `entity_mailing_address`;

CREATE TABLE `entity_mailing_address` (
  `ENTITY_MAILING_ADDRESS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `ADDRESS_TYPE_CODE` varchar(10) DEFAULT NULL,
  `ADDRESS_LINE_1` varchar(500) DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(500) DEFAULT NULL,
  `CITY` varchar(100) DEFAULT NULL,
  `STATE` varchar(100) DEFAULT NULL,
  `POST_CODE` varchar(20) DEFAULT NULL,
  `COUNTRY_CODE` varchar(3) DEFAULT NULL,
  `LOCALITY` varchar(100) DEFAULT NULL,
  `REGION` varchar(100) DEFAULT NULL,
  `COUNTY` varchar(100) DEFAULT NULL,
  `UPDATE_TIMESTAMP` timestamp NULL DEFAULT NULL,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  `IS_COPY` char(1) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_MAILING_ADDRESS_ID`),
  KEY `ENTITY_MAILING_ADDRESS_FK1_idx` (`ENTITY_ID`),
  KEY `ENTITY_MAILING_ADDRESS_FK2_idx` (`COUNTRY_CODE`),
  KEY `ENTITY_MAILING_ADDRESS_FK3_idx` (`ADDRESS_TYPE_CODE`),
  CONSTRAINT `ENTITY_MAILING_ADDRESS_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_MAILING_ADDRESS_FK2` FOREIGN KEY (`COUNTRY_CODE`) REFERENCES `country` (`COUNTRY_CODE`),
  CONSTRAINT `ENTITY_MAILING_ADDRESS_FK3` FOREIGN KEY (`ADDRESS_TYPE_CODE`) REFERENCES `entity_address_type` (`ADDRESS_TYPE_CODE`)
) ;



