

--
--  `entity_external_id_mapping`
--

DROP TABLE IF EXISTS `entity_external_id_mapping`;

CREATE TABLE `entity_external_id_mapping` (
  `ENTITY_EXTERNAL_MAPPING_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `EXTERNAL_ID_TYPE_CODE` varchar(3) DEFAULT NULL,
  `EXTERNAL_ID` varchar(50) DEFAULT NULL,
  `DESCRIPTION` varchar(500) DEFAULT NULL,
  `SPONSOR_CODE` varchar(10) DEFAULT NULL,
  `ORGANIZATION_ID` varchar(10) DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ENTITY_EXTERNAL_MAPPING_ID`),
  KEY `ENTITY_EXTERNAL_MAPPING_FK1_idx` (`ENTITY_ID`),
  KEY `ENTITY_EXTERNAL_MAPPING_FK2_idx` (`EXTERNAL_ID_TYPE_CODE`),
  CONSTRAINT `ENTITY_EXTERNAL_MAPPING_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_EXTERNAL_MAPPING_FK2` FOREIGN KEY (`EXTERNAL_ID_TYPE_CODE`) REFERENCES `entity_external_id_type` (`EXTERNAL_ID_TYPE_CODE`)
) ;



