

--
--  `entity_notes`
--

DROP TABLE IF EXISTS `entity_notes`;

CREATE TABLE `entity_notes` (
  `NOTE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) NOT NULL,
  `TITLE` varchar(500) DEFAULT NULL,
  `CONTENT` text,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`NOTE_ID`),
  KEY `ENTITY_NOTE_FK1_idx` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_NOTE_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`)
) ;



