

--
--  `entity_family_tree_role`
--

DROP TABLE IF EXISTS `entity_family_tree_role`;

CREATE TABLE `entity_family_tree_role` (
  `ENTITY_FAMILY_TREE_ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `FAMILY_ROLE_TYPE_CODE` varchar(10) DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ENTITY_FAMILY_TREE_ROLE_ID`),
  KEY `ENTITY_FAMILY_TREE_ROLE_FK1_idx` (`ENTITY_ID`),
  KEY `ENTITY_FAMILY_TREE_ROLE_FK2_idx` (`FAMILY_ROLE_TYPE_CODE`),
  CONSTRAINT `ENTITY_FAMILY_TREE_ROLE_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_FAMILY_TREE_ROLE_FK2` FOREIGN KEY (`FAMILY_ROLE_TYPE_CODE`) REFERENCES `entity_family_role_type` (`FAMILY_ROLE_TYPE_CODE`)
) ;



