

--
--  `entity_industry_classification`
--

DROP TABLE IF EXISTS `entity_industry_classification`;

CREATE TABLE `entity_industry_classification` (
  `ENTITY_INDUSTRY_CLASS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `INDUSTRY_CATEGORY_ID` int(11) DEFAULT NULL,
  `IS_PRIMARY` varchar(1) DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ENTITY_INDUSTRY_CLASS_ID`),
  KEY `ENTITY_INDUSTRY_CLASS_FK1_idx` (`ENTITY_ID`),
  KEY `ENTITY_INDUSTRY_CLASS_FK2_idx` (`INDUSTRY_CATEGORY_ID`),
  CONSTRAINT `ENTITY_INDUSTRY_CLASS_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_INDUSTRY_CLASS_FK2` FOREIGN KEY (`INDUSTRY_CATEGORY_ID`) REFERENCES `industry_category_code` (`INDUSTRY_CATEGORY_ID`)
) ;



