

--
--  `entity_compliance_info`
--

DROP TABLE IF EXISTS `entity_compliance_info`;

CREATE TABLE `entity_compliance_info` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `ENTITY_TYPE_CODE` varchar(3) DEFAULT NULL,
  `UPDATE_TIMESTAMP` timestamp NULL DEFAULT NULL,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `ENTITY_COMPLIANCE_INFO_FK1_idx` (`ENTITY_ID`),
  KEY `ENTITY_COMPLIANCE_INFO_FK2_idx` (`ENTITY_TYPE_CODE`),
  CONSTRAINT `ENTITY_COMPLIANCE_INFO_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_COMPLIANCE_INFO_FK2` FOREIGN KEY (`ENTITY_TYPE_CODE`) REFERENCES `coi_entity_type` (`ENTITY_TYPE_CODE`)
) ;



