

--
--  `entity_trade_style_name`
--

DROP TABLE IF EXISTS `entity_trade_style_name`;

CREATE TABLE `entity_trade_style_name` (
  `ENTITY_TRADE_NAME_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `TRADE_STYLE_NAME` varchar(200) DEFAULT NULL,
  `PRIORITY` varchar(10) DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ENTITY_TRADE_NAME_ID`),
  KEY `ENTITY_TRADE_STYLE_NAME_FK1_idx` (`ENTITY_ID`),
  CONSTRAINT `ENTITY_TRADE_STYLE_NAME_FK1` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`)
) ;



