

--
--  `entity_non_foreign_countries`
--

DROP TABLE IF EXISTS `entity_non_foreign_countries`;

CREATE TABLE `entity_non_foreign_countries` (
  `ENTITY_NON_FOREIGN_COUNTRY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NON_FOREIGN_COUNTRY_CODE` varchar(3) DEFAULT NULL,
  `IS_ACTIVE` varchar(1) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`ENTITY_NON_FOREIGN_COUNTRY_ID`),
  KEY `NON_FOREIGN_COUNTRY_CODE_IDX_1` (`NON_FOREIGN_COUNTRY_CODE`),
  CONSTRAINT `NON_FOREIGN_COUNTRY_CODE_FK_1` FOREIGN KEY (`NON_FOREIGN_COUNTRY_CODE`) REFERENCES `country` (`COUNTRY_CODE`)
) ;



