

--
--  `opa_action_log`
--

DROP TABLE IF EXISTS `opa_action_log`;

CREATE TABLE `opa_action_log` (
  `ACTION_LOG_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPA_DISCLOSURE_ID` int(11) DEFAULT NULL,
  `OPA_DISCLOSURE_NUMBER` varchar(20) DEFAULT NULL,
  `ACTION_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `COMMENT` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ACTION_LOG_ID`),
  KEY `OPA_ACTION_LOG_FK2` (`ACTION_TYPE_CODE`),
  KEY `OPA_ACTION_LOG_FK1` (`OPA_DISCLOSURE_ID`),
  CONSTRAINT `OPA_ACTION_LOG_FK1` FOREIGN KEY (`OPA_DISCLOSURE_ID`) REFERENCES `opa_disclosure` (`OPA_DISCLOSURE_ID`),
  CONSTRAINT `OPA_ACTION_LOG_FK2` FOREIGN KEY (`ACTION_TYPE_CODE`) REFERENCES `opa_action_log_type` (`ACTION_TYPE_CODE`)
) ;



