

--
--  `opa_discl_activities`
--

DROP TABLE IF EXISTS `opa_discl_activities`;

CREATE TABLE `opa_discl_activities` (
  `OPA_DISCL_ACTIVITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPA_DISCLOSURE_ID` int(11) NOT NULL,
  `OPA_DISCL_PERSON_ENTITY_ID` int(11) DEFAULT NULL,
  `IS_COMPENSATED` varchar(1) NOT NULL,
  `NUM_OF_DAYS_SUMMER` decimal(5,2) DEFAULT NULL,
  `NUM_OF_DAYS_ACADEMIC` decimal(5,2) DEFAULT NULL,
  `NUM_OF_DAYS_IN_YEAR` decimal(5,2) DEFAULT NULL,
  `NATURE_OF_WORK` varchar(4000) DEFAULT NULL,
  `DESCRIPTION_1` varchar(4000) DEFAULT NULL,
  `DESCRIPTION_2` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime NOT NULL,
  `UPDATE_USER` varchar(60) NOT NULL,
  PRIMARY KEY (`OPA_DISCL_ACTIVITY_ID`),
  KEY `OPA_DISCL_ACTIVITIES_FK1` (`OPA_DISCLOSURE_ID`),
  KEY `OPA_DISCL_ACTIVITIES_FK2` (`OPA_DISCL_PERSON_ENTITY_ID`),
  CONSTRAINT `OPA_DISCL_ACTIVITIES_FK1` FOREIGN KEY (`OPA_DISCLOSURE_ID`) REFERENCES `opa_disclosure` (`OPA_DISCLOSURE_ID`),
  CONSTRAINT `OPA_DISCL_ACTIVITIES_FK2` FOREIGN KEY (`OPA_DISCL_PERSON_ENTITY_ID`) REFERENCES `opa_discl_person_entity` (`OPA_DISCL_PERSON_ENTITY_ID`)
) ;



