

--
--  `per_ent_matrix_answer`
--

DROP TABLE IF EXISTS `per_ent_matrix_answer`;

CREATE TABLE `per_ent_matrix_answer` (
  `MATRIX_ANSWER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ENTITY_ID` int(11) DEFAULT NULL,
  `PERSON_ENTITY_NUMBER` int(11) DEFAULT NULL,
  `MATRIX_QUESTION_ID` int(11) DEFAULT NULL,
  `COLUMN_VALUE` varchar(500) DEFAULT NULL,
  `RELATIONSHIP_TYPE_CODE` varchar(3) DEFAULT NULL,
  `COMMENTS` varchar(500) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`MATRIX_ANSWER_ID`),
  KEY `COI_MATRIX_ANSWER_FK2` (`MATRIX_QUESTION_ID`),
  KEY `COI_MATRIX_ANSWER_FK1` (`RELATIONSHIP_TYPE_CODE`),
  CONSTRAINT `COI_MATRIX_ANSWER_FK1` FOREIGN KEY (`RELATIONSHIP_TYPE_CODE`) REFERENCES `person_entity_rel_type` (`RELATIONSHIP_TYPE_CODE`),
  CONSTRAINT `COI_MATRIX_ANSWER_FK2` FOREIGN KEY (`MATRIX_QUESTION_ID`) REFERENCES `per_ent_matrix_question` (`MATRIX_QUESTION_ID`)
) ;



