

--
--  `per_ent_discl_type_selection`
--

DROP TABLE IF EXISTS `per_ent_discl_type_selection`;

CREATE TABLE `per_ent_discl_type_selection` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ENTITY_ID` int(11) DEFAULT NULL,
  `DISCLOSURE_TYPE_CODE` varchar(3) DEFAULT NULL,
  `DATA_CAPTURING_TYPE_CODE` int(11) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATED_BY` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PER_ENT_DISCL_TYPE_SELECTION_FK1_idx` (`PERSON_ENTITY_ID`),
  KEY `PER_ENT_DISCL_TYPE_SELECTION_FK2_idx` (`DISCLOSURE_TYPE_CODE`),
  KEY `PER_ENT_DISCL_TYPE_SELECTION_FK3_idx` (`DATA_CAPTURING_TYPE_CODE`),
  CONSTRAINT `PER_ENT_DISCL_TYPE_SELECTION_FK1` FOREIGN KEY (`PERSON_ENTITY_ID`) REFERENCES `person_entity` (`PERSON_ENTITY_ID`),
  CONSTRAINT `PER_ENT_DISCL_TYPE_SELECTION_FK2` FOREIGN KEY (`DISCLOSURE_TYPE_CODE`) REFERENCES `coi_disclosure_type` (`DISCLOSURE_TYPE_CODE`),
  CONSTRAINT `PER_ENT_DISCL_TYPE_SELECTION_FK3` FOREIGN KEY (`DATA_CAPTURING_TYPE_CODE`) REFERENCES `per_ent_data_capturing_type` (`DATA_CAPTURING_TYPE_CODE`)
) ;



