

--
--  `person_entity`
--

DROP TABLE IF EXISTS `person_entity`;

CREATE TABLE `person_entity` (
  `PERSON_ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERSON_ID` varchar(45) DEFAULT NULL,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `ENTITY_NUMBER` int(11) DEFAULT NULL,
  `IS_FORM_COMPLETED` varchar(1) DEFAULT NULL,
  `VERSION_NUMBER` int(11) DEFAULT NULL,
  `VERSION_STATUS` varchar(45) DEFAULT NULL,
  `SPONSORS_RESEARCH` varchar(1) DEFAULT NULL,
  `INVOLVEMENT_START_DATE` date DEFAULT NULL,
  `INVOLVEMENT_END_DATE` date DEFAULT NULL,
  `STUDENT_INVOLVEMENT` varchar(4000) DEFAULT NULL,
  `STAFF_INVOLVEMENT` varchar(4000) DEFAULT NULL,
  `INSTITUTE_RESOURCE_INVOLVEMENT` varchar(4000) DEFAULT NULL,
  `UPDATE_TIMESTAMP` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(60) DEFAULT NULL,
  `CREATE_TIMESTAMP` datetime DEFAULT NULL,
  `CREATE_USER` varchar(60) DEFAULT NULL,
  `PERSON_ENTITY_NUMBER` int(11) DEFAULT NULL,
  `REVISION_REASON` varchar(100) DEFAULT NULL,
  `IS_COMPENSATED` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`PERSON_ENTITY_ID`),
  KEY `PERSON_ENTITY_FK1_idx` (`PERSON_ID`),
  KEY `PERSON_ENTITY_FK2_idx` (`ENTITY_ID`),
  CONSTRAINT `PERSON_ENTITY_FK1` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`PERSON_ID`),
  CONSTRAINT `PERSON_ENTITY_FK2` FOREIGN KEY (`ENTITY_ID`) REFERENCES `entity` (`ENTITY_ID`)
) ;



