

--
--  `sponsor_export_stage_1nov2024`
--

DROP TABLE IF EXISTS `sponsor_export_stage_1nov2024`;

CREATE TABLE `sponsor_export_stage_1nov2024` (
  `SPONSOR_CODE` varchar(10) DEFAULT NULL,
  `ACRONYM` varchar(10) DEFAULT NULL,
  `CUSTOMER_NUMBER` varchar(50) DEFAULT NULL,
  `DODAC_NUMBER` varchar(50) DEFAULT NULL,
  `SPONSOR_TYPE_CODE` varchar(50) DEFAULT NULL,
  `SPONSOR_NAME` varchar(255) DEFAULT NULL,
  `DUN_AND_BRADSTREET_NUMBER` varchar(50) DEFAULT NULL,
  `SPONSOR_TYPE_CODE_1` varchar(50) DEFAULT NULL,
  `CAGE_NUMBER` varchar(50) DEFAULT NULL,
  `UEI` varchar(50) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `ADDRESS_LINE_1` varchar(255) DEFAULT NULL,
  `ADDRESS_LINE_2` varchar(255) DEFAULT NULL,
  `POSTAL_CODE` varchar(50) DEFAULT NULL,
  `STATE` varchar(50) DEFAULT NULL,
  `COUNTRY_CODE` varchar(50) DEFAULT NULL,
  `HUMAN_SUB_ASSURANCE` varchar(50) DEFAULT NULL,
  `ANIMAL_WELFARE_ASSURANCE` varchar(50) DEFAULT NULL
) ;



